### PR TITLE
fix flaky tests in redis integration test

### LINKED ISSUE #8917: Test flake in //test/extensions/clusters/redis:redis_cluster_integration_test
The test has failed several times in CI due to a timeout: 
https://dev.azure.com/cncf/envoy/_build/results?buildId=18375
https://dev.azure.com/cncf/envoy/_build/results?buildId=18300

Based on the first output the issue seems to be in `IpVersions/RedisClusterWithAuthIntegrationTest.SingleSlotMasterReplica/IPv4`:
```
==================== Test output for //test/extensions/clusters/redis:redis_cluster_integration_test:
[==========] Running 8 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 6 tests from IpVersions/RedisClusterIntegrationTest
[ RUN      ] IpVersions/RedisClusterIntegrationTest.SingleSlotMasterReplica/IPv4
[       OK ] IpVersions/RedisClusterIntegrationTest.SingleSlotMasterReplica/IPv4 (346 ms)
[ RUN      ] IpVersions/RedisClusterIntegrationTest.SingleSlotMasterReplica/IPv6
[       OK ] IpVersions/RedisClusterIntegrationTest.SingleSlotMasterReplica/IPv6 (273 ms)
[ RUN      ] IpVersions/RedisClusterIntegrationTest.TwoSlot/IPv4
[       OK ] IpVersions/RedisClusterIntegrationTest.TwoSlot/IPv4 (272 ms)
[ RUN      ] IpVersions/RedisClusterIntegrationTest.TwoSlot/IPv6
[       OK ] IpVersions/RedisClusterIntegrationTest.TwoSlot/IPv6 (288 ms)
[ RUN      ] IpVersions/RedisClusterIntegrationTest.ClusterSlotRequestAfterRedirection/IPv4
[       OK ] IpVersions/RedisClusterIntegrationTest.ClusterSlotRequestAfterRedirection/IPv4 (272 ms)
[ RUN      ] IpVersions/RedisClusterIntegrationTest.ClusterSlotRequestAfterRedirection/IPv6
[       OK ] IpVersions/RedisClusterIntegrationTest.ClusterSlotRequestAfterRedirection/IPv6 (268 ms)
[----------] 6 tests from IpVersions/RedisClusterIntegrationTest (1719 ms total)

[----------] 2 tests from IpVersions/RedisClusterWithAuthIntegrationTest
[ RUN      ] IpVersions/RedisClusterWithAuthIntegrationTest.SingleSlotMasterReplica/IPv4
================================================================================

TIMEOUT: //test/extensions/clusters/redis:redis_cluster_integration_test (Summary)
```

but other runs don't output anything, so there might be something else going on. Running this locally with `bazel test //test/extensions/clusters/redis:redis_cluster_integration_test --nocache_test_results --runs_per_test=10000 --local_resources=1000,1000,1000 --jobs 80` didn't reproduce any timeout, although running just the SingleSlotMasterReplica resulted in 2 failures out of 1000  runs:

```
Note: Google Test filter = IpVersions/RedisClusterWithAuthIntegrationTest.SingleSlotMasterReplica/IPv4
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from IpVersions/RedisClusterWithAuthIntegrationTest
[ RUN      ] IpVersions/RedisClusterWithAuthIntegrationTest.SingleSlotMasterReplica/IPv4
test/extensions/clusters/redis/redis_cluster_integration_test.cc:222: Failure
Value of: fake_upstreams_[stream_index]->waitForRawConnection(fake_upstream_connection_)
  Actual: false (Timed out waiting for raw connection)
Expected: true
```
which might be related.

@HenryYYang Are you able to take a look at this?

### PR DESCRIPTION
**Pull request by HenryYYang**
Description: I cannot locally repro the failed test locally, but looking at the code this is where the likely failure might be.
Risk Level: Low
Testing: Integration test updated.
Docs Changes: N/A
Release Notes: N/A
Fixes #8917

### CODE REVIEW

File: test/extensions/clusters/redis/redis_cluster_integration_test.cc [hunk 1]
```diff
@@ -136,13 +136,15 @@ class RedisClusterIntegrationTest : public testing::TestWithParam<Network::Addre
       }
     });
 
-    BaseIntegrationTest::initialize();
+    on_server_ready_function_ = [this](Envoy::IntegrationTestServer& test_server) {
+      mock_rng_ = dynamic_cast<Runtime::MockRandomGenerator*>(&(test_server.server().random()));
+      // Abort now if we cannot downcast the server's random number generator pointer.
+      ASSERT_TRUE(mock_rng_ != nullptr);
+      // Ensure that fake_upstreams_[0] is the load balancer's host of choice by default.
+      ON_CALL(*mock_rng_, random()).WillByDefault(Return(random_index_));
```
Comment (mattklein123) [inline test/extensions/clusters/redis/redis_cluster_integration_test.cc]: qq: f we are trying to hard code it to a single uptream, why don't we just have a single upstream in the test?

Comment (HenryYYang) [reply test/extensions/clusters/redis/redis_cluster_integration_test.cc]: we're forcing the service discovery(cluster slots) requests to a single upstream, but all the other Redis requests are sent to multiple upstreams in the tests according to redis cluster protocol.

Comment (mattklein123) [reply test/extensions/clusters/redis/redis_cluster_integration_test.cc]: OK goit it, makes sense.

File: test/integration/server.cc [hunk 2]
```diff
@@ -153,6 +157,9 @@ void IntegrationTestServer::onWorkerListenerRemoved() {
 void IntegrationTestServer::serverReady() {
   pending_listeners_ = server().listenerManager().listeners().size();
   server_set_.setReady();
+  if (on_server_ready_cb_ != nullptr) {
```
Comment (mattklein123) [inline test/integration/server.cc]: I think this should be done before the conditional set on the previous line, right?

File: test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc [hunk 3]
```diff
@@ -462,13 +462,14 @@ void RedisProxyIntegrationTest::initialize() {
   setUpstreamCount(num_upstreams_);
   setDeterministic();
   config_helper_.renameListener("redis_proxy");
+  on_server_ready_function_ = [this](Envoy::IntegrationTestServer& test_server) {
+    mock_rng_ = dynamic_cast<Runtime::MockRandomGenerator*>(&(test_server.server().random()));
+    // Abort now if we cannot downcast the server's random number generator pointer.
+    ASSERT_TRUE(mock_rng_ != nullptr);
+    // Ensure that fake_upstreams_[0] is the load balancer's host of choice by default.
+    ON_CALL(*mock_rng_, random()).WillByDefault(Return(0));
```
Comment (mattklein123) [inline test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc]: This is the default, so none of this is necessary for these cases. Can you remove this? (I just noticed this because I need this for a test I'm working on).

File: test/integration/server.cc (hunk 2 above)
Comment (HenryYYang) [reply test/integration/server.cc]: yes, that's right.  Let me change that

File: test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc (hunk 3 above)
Comment (HenryYYang) [reply test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc]: ok, removed.

Comment (mattklein123) [reply test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc]: Sorry I mean actually remove all of this code that sets up to return 0 from existing tests. It's the default behavior.

/wait
