### PR TITLE
oauth2: add allow_failed_matcher for unauthenticated pass-through on auth failure

### LINKED ISSUE #36523: oauth2 filter: option to allow errors and pass through
*Title*: Provide an option to allow errors and pass through

*Description*:

Today, there is a `deny_redirect_matcher`, which is useful for APIs where redirecting does not make sense (e.g. AJAX endpoint). For endpoints that are listed in `deny_redirect_matcher`, the behavior would be:
1. If access token exists and valid, succeed and pass to next filter
2. If access token is expired and refresh token exists, attempt to refresh the access token and set it to cookies
3. If refresh failed or refresh token is absent, `sendLocalReply` with an error message "OAuth flow failed."
 
While local reply is customizable using [local reply modification](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply), we still run into a use case where upstream service wants to handle the error themselves, i.e. we need an option that makes the 3rd bullet above become:
* If refresh failed or refresh token is absent, _pass through_

Similarly, in JWT authentication filter, there is a JWT requirement rule called `allow_missing_or_failed` ([doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-jwtrequirement)), with which any missing or invalid jwt will pass through so the upstream service can handle the error themselves.

### PR DESCRIPTION
**Pull request by mchen391**
Commit Message:

This PR adds an allow_failed_matcher field to the OAuth2 filter configuration, enabling requests to proceed to upstream as unauthenticated when OAuth validation fails (missing, invalid, or expired credentials) and the request matches the configured matchers.

This enables graceful degradation patterns where services can handle both authenticated and unauthenticated requests, similar to the JWT filter's allow_missing_or_failed functionality.

When triggered:
- All OAuth cookies are stripped from the request
- Context headers x-envoy-oauth-status: failed and x-envoy-oauth-failure-reason are added
- Request continues to upstream as unauthenticated

Matcher evaluation order: pass_through_matcher > allow_failed_matcher > deny_redirect_matcher > default behavior.

Signed-off-by: Mo Chen <carterchen.m@gmail.com>

Additional Description:

Use case: An API that returns personalized results for authenticated requests but falls back to generic results for unauthenticated requests.

Example configuration:
```yaml
allow_failed_matcher:
  - name: ":path"
    string_match:
      prefix: "/api/public"
```

Risk Level: Medium

Testing:
Added unit tests covering multiple scenarios (no cookies, invalid refresh token, async/sync failures, OAuth callback path, matcher precedence). All existing OAuth2 tests pass. Verified backward compatibility.

Docs Changes: Updated proto documentation for allow_failed_matcher field. Added release notes to changelogs/current.yaml.

Release Notes: Added to changelogs/current.yaml

Platform Specific Features: N/A

[Optional Runtime guard:] N/A - Config-guarded feature (optional proto field)
[Optional Fixes #Issue] Fixes #36523
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]
- New optional field allow_failed_matcher (field 27) to OAuth2Config proto
- Backward compatible - no behavior change when not configured
- Uses existing HeaderMatcher type, follows same pattern as other matchers in OAuth2Config

### CODE REVIEW

File: source/extensions/filters/http/oauth2/oauth_client.cc [hunk 1]
```diff
@@ -121,8 +122,9 @@ void OAuth2ClientImpl::dispatchRequest(Http::RequestMessagePtr&& msg) {
 
     in_flight_request_ =
         thread_local_cluster->httpAsyncClient().send(std::move(msg), *this, options);
+    return absl::OkStatus();
   } else {
-    parent_->sendUnauthorizedResponse("Token endpoint cluster not found");
+    return absl::UnavailableError("Token endpoint cluster not found");
```
Comment (mchen391) [inline source/extensions/filters/http/oauth2/oauth_client.cc]: Although this error is thrown inside `oauth_client`, it is not an error thrown from the async context and as a result it cannot call `parent_->asyncOnUnauthorized`. To allow this sync failure and forward the request to upstream, it needs to go back to filter.cc and let it return `FilterHeadersStatus::Continue`.

**Comment by tyxia** [comment]
Hi @zhaohuabing, I saw you contributed a lot to this area in the past. Could we borrow your expertise to review this PR

cc @wbpcode as code owner as well

Thanks!

**Comment by zhaohuabing** [comment]
> Use case: An API that returns personalized results for authenticated requests but falls back to generic results for unauthenticated requests.

Can't this be achieved with [Custom Response](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/custom_response_filter)?

Here is an [example](https://github.com/zhaohuabing/kubecon-envoy-gateway-securitypolicy/blob/e3f11e8b5e4f2994e77e53514a8cdfd8f2122713/oidc-cognito/oidc-jwt-auth-id-token.yaml#L52C3-L134) using Envoy Gateway BackendTrafficPolicy.

**Comment by mchen391** [comment]
@zhaohuabing Unless the local reply is able to forward the request to upstream, no
unfortunately. Imagine the homepage of a website - it will render normally
for anonymous users, but will render tailored content for logged-in users
too. Or imagine a search engine API that gives anonymous users result
(likely from DB) but also gives tailored result to users with credentials.

As a result, we need the request that does not carry any oauth credentials
to still forward to upstream and let upstream handles the request.

**Comment by zhaohuabing** [comment]
I think we could redirect unauthenticated requests. Since the OAuth2 filter is already fairly complex, it might be better to handle this in a more generalized way rather than adding another knob to the OAuth2 filter.

https://github.com/zhaohuabing/playground/blob/main/gateway/oidc-keycloak/response-override-redirect.yaml

**Comment by mchen391** [comment]
> I think we could redirect unauthenticated requests. Since the OAuth2 filter is already fairly complex, it might be better to handle this in a more generalized way rather than adding another knob to the OAuth2 filter.
> 
> https://github.com/zhaohuabing/playground/blob/main/gateway/oidc-keycloak/response-override-redirect.yaml

@zhaohuabing Sorry I still don't think this would solve the problem. In this case we do NOT want to show the anonymous user an error page, but instead want to show them a normal content but just not tailored for them since they are anonymous. 

Just imagine the google homepage - you will be able to load google and use its search engine without login completely fine, but can also do that in a logged-in state, with maybe some tailored search result sorting if you search in logged-in state. 

I don't see a clean way to achieve that with redirects. One thing I can think of is to make a duplicate set of all the APIs that are supposed to be optional auth (could work with or without auth), one require auth and one does not require, and make the former redirect to the latter if auth failed. You could imagine that there are going to tons of endpoints that need to be duplicated and maintained separately, which I don't think is ideal or maintenable.

In fact I think the Envoy jwt_authn filter's `allow_missing_or_failed` option is also designed with this requirement in mind. https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-field-extensions-filters-http-jwt-authn-v3-jwtrequirement-allow-missing-or-failed

**Comment by zhaohuabing** [comment]
Thanks for the clarification — I don’t think you necessarily need a full duplicate setup, but it's true that you’d still need some separate routing or handling logic for unauthenticated vs authenticated requests, which would require changes on the application side and isn’t ideal. In that case, having a pass-through option is really helpful. So this approach seems reasonable to me.

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto [hunk 2]
```diff
@@ -283,6 +283,18 @@ message OAuth2Config {
...
+  // even if OAuth validation fails (missing, invalid, or expired credentials).
+  // This is useful for services that can handle both authenticated and unauthenticated requests,
+  // enabling graceful degradation patterns.
+  //
+  // When triggered, all OAuth cookies are stripped from the request and the request proceeds as unauthenticated.
+  // Context headers ``x-envoy-oauth-status: failed`` and ``x-envoy-oauth-failure-reason`` are added to inform upstream.
+  //
+  // Note: If a request matches pass_through_matcher, it bypasses OAuth validation and this matcher won't be evaluated.
+  // This matcher takes precedence over deny_redirect_matcher.
+  repeated config.route.v3.HeaderMatcher allow_failed_matcher = 27;
```
Comment (zhaohuabing) [inline api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:306]: Should this matcher take precedence over deny_redirect_matcher?

deny_redirect_matcher won't redirect matching requests to the oauth server, which happens before auth fails/succeeds.

File: source/extensions/filters/http/oauth2/filter.cc [hunk 3]
```diff
@@ -1402,6 +1422,43 @@ void OAuth2Filter::sendUnauthorizedResponse(const std::string& details) {
...
+    if (matcher->matchesHeaders(headers)) {
+      return true;
+    }
+  }
+  return false;
+}
+
+void OAuth2Filter::continueAsUnauthorized(const std::string& failure_reason) {
+  removeOAuthTokenCookies(*request_headers_);
+  request_headers_->addCopy(OAuth2Headers::get().OAuthStatus, "failed");
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: Should we use `setCopy` here?

File: source/extensions/filters/http/oauth2/filter.cc [hunk 4]
```diff
@@ -1402,6 +1422,43 @@ void OAuth2Filter::sendUnauthorizedResponse(const std::string& details) {
...
+
+  for (const auto& matcher : config_->allowFailedMatchers()) {
+    if (matcher->matchesHeaders(headers)) {
+      return true;
+    }
+  }
+  return false;
+}
+
+void OAuth2Filter::continueAsUnauthorized(const std::string& failure_reason) {
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: Should we also sanitize the OAuthStatus and OAuthFailureReason headers for all requests to the backend?

File: source/extensions/filters/http/oauth2/filter.cc [hunk 5]
```diff
@@ -1402,6 +1422,43 @@ void OAuth2Filter::sendUnauthorizedResponse(const std::string& details) {
...
+  removeOAuthTokenCookies(*request_headers_);
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc:1456]: unauthenticated requests shouldn’t have those cookies?

File: source/extensions/filters/http/oauth2/filter.cc [hunk 6]
```diff
@@ -892,6 +897,13 @@ std::string OAuth2Filter::decryptToken(const std::string& encrypted_token) const
 }
 
 bool OAuth2Filter::canRedirectToOAuthServer(Http::RequestHeaderMap& headers) const {
+  for (const auto& matcher : config_->allowFailedMatchers()) {
+    if (matcher->matchesHeaders(headers)) {
+      ENVOY_LOG(debug, "allow_failed_matcher matched, will not redirect");
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: request matching `allowFailedMatchers` should be directed to the OAuth2 server to start the oauth flow.

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto (hunk 2 above)
Comment (mchen391) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:306]: Correct me if I'm wrong, but I think the filter works in this way:

* First of all, if `pass_through_matcher` matches, skip the entire filter
* Do auth on OAuth cookies, refresh token if needed. If auth succeeded, forward to upstream
* If auth failed (could be missing cookies, refresh failure, etc), it will either
  a. redirect to OAuth server to start a new OAuth, or
  b. If `deny_redirect_matcher` matches, do not redirect and reject with a 401.

As a result, `deny_redirect_matcher` check happens after auth, and is determining what is the behavior when auth failed. I think this new `allow_failed_matcher` is in fact defining a new behavior after a & b:
  
c. If `allow_failed_matcher` matches, allow this auth failure and forward to upstream

So it's in fact in parallel to `deny_redirect_matcher`. Technically it's ok for either of them to take precedes over the other one, but I feel like c happens before b makes more sense. Please let me know if you think other way though!

File: source/extensions/filters/http/oauth2/filter.cc (hunk 4 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Good call! We definitely should. Will do

File: source/extensions/filters/http/oauth2/filter.cc (hunk 5 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc:1456]: Unauthenticated requests could be:
* A request without any oauth cookies
* A request with expired oauth cookies, especially an expired refresh token, which cannot be used to obtain a new access token any more

The clean up of the token cookies are for the 2nd case.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 6 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: I actually intentionally let requests matching `allowFailedMatchers` to never initiate a new OAuth on its own by the filter. Basically if the filter fail to authenticate the request (that matches `allowFailedMatchers`) or any reasons, it should forward to upstream and let upstream to decide what to do with the unauthenticated request.

If we redirect to OAuth server to start a new oauth flow for these requests, the filter is still enforcing authentication.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 4 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Added header sanitization

File: source/extensions/filters/http/oauth2/filter.cc (hunk 3 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Changed to `setCopy`

**Comment by mchen391** [comment]
@zhaohuabing, sorry for the ping, but I could use another look at the PR. Changes have been made to the header sanitization per the suggestions, though there are a few other comments I think are worth discussing. Thank you!

**Comment by theon73** [comment]
Friendly bump on this in case anyone has had a chance to look since the last ping.
I’m helping cover while @mchen391 is away. Feedback appreciated, thanks.

**Comment by botengyao** [comment]
friendly ping @zhaohuabing

**Comment by zhaohuabing** [comment]
Hi folks, Sorry for the delay — I’ll review this sometime this week.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 5 above)
Comment (zhaohuabing) [reply source/extensions/filters/http/oauth2/filter.cc:1456]: We should also call removeOAuthFlowCookies to remove internal cookies.

Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc:1456]: Added `removeOAuthFlowCookies` call and also added assertions of the removals of flow cookies in the tests.

File: source/extensions/filters/http/oauth2/filter.cc [hunk 7]
```diff
@@ -690,19 +696,17 @@ Http::FilterHeadersStatus OAuth2Filter::decodeHeaders(Http::RequestHeaderMap& he
...
+        return onUnauthorized(result.error_details_);
       }
 
       // Return 401 unauthorized if the original request URL in the state matches the redirect
       // config to avoid infinite redirect loops.
       Http::Utility::Url original_request_url;
       original_request_url.initialize(result.original_request_url_, false);
       if (config_->redirectPathMatcher().match(original_request_url.pathAndQueryParams())) {
-        sendUnauthorizedResponse(
+        return onUnauthorized(
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: Nit: this may be confusing to future readers, since requests on this path should never match the passthrough matcher. I’d keep the original code in this patch to avoid another nested call(which checks if the path is redirect path matcher again) and preserve readability.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 6 above)
Comment (zhaohuabing) [reply source/extensions/filters/http/oauth2/filter.cc]: Yeah, it makes sense. Thanks for the explanation.

File: source/extensions/filters/http/oauth2/filter.cc [hunk 8]
```diff
@@ -747,9 +756,8 @@ Http::FilterHeadersStatus OAuth2Filter::decodeHeaders(Http::RequestHeaderMap& he
       redirectToOAuthServer(headers);
       return Http::FilterHeadersStatus::StopIteration;
     } else {
-      sendUnauthorizedResponse(fmt::format(
+      return onUnauthorized(fmt::format(
           "Unauthorized, and redirecting to OAuth server is not allowed: {}", path_str));
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: This message isn’t precise, since the request may match the allow failed matcher(not the deny_redirect_matcher). Also, prefer a simple flow here that would be easier to follow, like:

```
    if shouldAllowFailed(headers) {
      continueAsUnauthorized("not logged in, continue as unauthorized");
      return Http::FilterHeadersStatus::Continue;
    }
    if shouldDenyRedirect(headers) {
      sendUnauthorizedResponse(fmt::format(
          "Unauthorized, and redirecting to OAuth server is not allowed: {}", path_str));
       return Http::FilterHeadersStatus::StopIteration;
    }
    ENVOY_STREAM_LOG(debug, "redirecting to OAuth server: {}", *decoder_callbacks_, path_str);
    redirectToOAuthServer(headers);
    return Http::FilterHeadersStatus::StopIteration;
```

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto (hunk 2 above)
Comment (zhaohuabing) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:306]: Agree. Thanks for the explanation.

**Comment by zhaohuabing** [comment]
Hi @mchen391 — The logic in this PR looks solid! I left a few comments (sorry in advance for the nitpicks). I understand the goal is to handle unauthorized requests in a unified way, but I’d prefer to keep the code as easy to follow as possible for maintainability(with fewer nested calls and repeatedly checks if possible :-) ),  Happy to chat offline if you see it differently.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 7 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: That makes sense. Totally agree that requests to the callback endpoint should never be "allow failed". Will revert to the original code

File: source/extensions/filters/http/oauth2/filter.cc (hunk 8 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Makes sense. I'll try to reorganize the code here. I think I was trying to avoid code duplication (use `onUnauthorized` v.s. unwrap that to the way you suggested), but I can see that flatting those conditions makes it more readable since there are more than one matcher that are being respected here.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 7 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Reverted this place and also several other places that are errors on callback path as well.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 8 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Unwrapped the code here and also another place (`onRefreshTokenFailure` where the exact same logic exists).

**Comment by mchen391** [comment]
@zhaohuabing Wonder if you had a chance to review the readability changes. Happy to make more improvements if needed.
We are trying to see if we can catch the next release scheduled on 4/14 to unblock our work, so please let me know what's the next thing I need to do to get an approval & merge. Still new to this project so please forgive my ignorance. Thanks!

File: source/extensions/filters/http/oauth2/filter.cc [hunk 9]
```diff
@@ -656,6 +657,11 @@ Http::FilterHeadersStatus OAuth2Filter::decodeHeaders(Http::RequestHeaderMap& he
     headers.removeInline(authorization_handle.handle());
   }
 
+  // Sanitize OAuth status headers to prevent header injection attacks.
+  // These headers are only set by the filter itself when allow_failed_matcher is used.
+  headers.remove(OAuth2Headers::get().OAuthStatus);
+  headers.remove(OAuth2Headers::get().OAuthFailureReason);
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: `pass_through_matcher` returns before the new OAuth status headers are sanitized, so clients can spoof `x-envoy-oauth-status` / `x-envoy-oauth-failure-reason` on pass-through requests. 

Since these two headers should only to be added by the OAuth2 filter, should we sanitize them at the start of the `decodeHeaders` method?

File: source/extensions/filters/http/oauth2/filter.cc [hunk 10]
```diff
@@ -1280,13 +1292,25 @@ void OAuth2Filter::finishRefreshAccessTokenFlow() {
...
     sendUnauthorizedResponse(
         "Failed to refresh the access token, and redirecting to OAuth server is not allowed");
+  } else {
+    redirectToOAuthServer(*request_headers_);
+  }
+}
+
+void OAuth2Filter::asyncOnUnauthorized(const std::string& details) {
+  // Handle unauthorized request in async context
+  const auto status = onUnauthorized(details);
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: This directly exposes the IDP auth response body to the backend, prefer to use a more abstract messag instead of the IDP auth response, because:
* This leaks IDP auth internal errors
* The body can be large and blow request-header limits upstream.

**Comment by zhaohuabing** [comment]
Hi @mchen39 1 really sorry for the delay. The past few weeks have been quite busy for me, and I’ve only had time to review on weekends. I left a few more comments, and once those are addressed, this PR should be good to go.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 10 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: I don't see anywhere this method or `onUnauthorized` is called with IDP auth response message directly. All of them are called with an abstract message. Am I missing somewhere?

File: source/extensions/filters/http/oauth2/filter.cc (hunk 9 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Good call. Moved to the top in `decodeHeaders` and added a unit test for `pass_through_matcher` case header sanitization specifically.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 10 above)
Comment (zhaohuabing) [reply source/extensions/filters/http/oauth2/filter.cc]: https://github.com/mchen391/envoy/blob/2f87d33b5f16a66fa6f8367578d71783cbc1d932/source/extensions/filters/http/oauth2/oauth_client.cc#L173

Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Ah right sorry I skimmed the beginning of the message and didn't realize that it's logging the response body/exception message at the end. I'll see what I can do with them.

Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Alright I changed it in a way that:
* Abstract error message & detailed messages are passed-in separately
* The failure reason header is populated with the abstract message only
* The debug log will still contain the detailed message like IDP response body and exception message

Let me know if you think it's too complicated/have any better idea though!

File: source/extensions/filters/http/oauth2/filter.cc [hunk 11]
```diff
@@ -1405,6 +1430,60 @@ void OAuth2Filter::sendUnauthorizedResponse(const std::string& details) {
...
+bool OAuth2Filter::shouldDenyRedirect(const Http::RequestHeaderMap& headers) const {
+  for (const auto& matcher : config_->denyRedirectMatchers()) {
+    if (matcher->matchesHeaders(headers)) {
+      return true;
+    }
+  }
+  return false;
+}
+
+void OAuth2Filter::continueAsUnauthorized(const std::string& reason,
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: Nit: how about naming it `continueWithFailedOAuth` ? Feel like this name is clearer as we don't send `401` Unauthorized response to the client, an it also aligns better with `allow_failed_matcher`.

File: source/extensions/filters/http/oauth2/filter.cc [hunk 12]
```diff
@@ -1405,6 +1430,60 @@ void OAuth2Filter::sendUnauthorizedResponse(const std::string& details) {
...
+  request_headers_->setCopy(OAuth2Headers::get().OAuthStatus, "failed");
+  request_headers_->setCopy(OAuth2Headers::get().OAuthFailureReason, reason);
+  config_->stats().oauth_allow_failed_passthrough_.inc();
+  const std::string log_details =
+      extra_details.empty() ? reason : absl::StrCat(reason, ": ", extra_details);
+  ENVOY_STREAM_LOG(debug, "allow_failed_matcher matched, continuing as unauthorized: {}",
+                   *decoder_callbacks_, log_details);
+}
+
+Http::FilterHeadersStatus OAuth2Filter::onUnauthorized(const std::string& reason,
```
Comment (zhaohuabing) [inline source/extensions/filters/http/oauth2/filter.cc]: Nit: a clearer name could be `onOAuthFailure ` or `handleOAuthFailure`.

**Comment by zhaohuabing** [comment]
The PR looks to be in good shape. I just had two more minor nits, otherwise LGTM.

File: source/extensions/filters/http/oauth2/oauth_client.cc (hunk 1 above)
Comment (zhaohuabing) [reply source/extensions/filters/http/oauth2/oauth_client.cc]: Yeah, this is clearer than the previous approach.

File: source/extensions/filters/http/oauth2/filter.cc (hunk 11 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Renamed!

File: source/extensions/filters/http/oauth2/filter.cc (hunk 12 above)
Comment (mchen391) [reply source/extensions/filters/http/oauth2/filter.cc]: Renamed this and also `asyncOnUnauthorized` to `handleOAuthFailureAsync`.

**Comment by mchen391** [comment]
Thank you @zhaohuabing for the detailed reviews! Fixed the nits and also resolved conflicts. Let me know if there are any other actions I need to take to get this approved/merged, thanks!

**Comment by mchen391** [comment]
@wbpcode friendly ping - I think I still need another approval from you to get this move forward. Thank you!

**Review by wbpcode — CHANGES_REQUESTED** [review]
Sorry. I think we need to re-evaluate the whole implementation. Note, the onFailure may be called directly in sometimes. Then, call the `continueDecoding()` in the failure callback will result in unexpected behavior.
We must to take it into account.

cc @zhaohuabing

**Comment by mchen391** [comment]
> Sorry. I think we need to re-evaluate the whole implementation. Note, the onFailure may be called directly in sometimes. Then, call the `continueDecoding()` in the failure callback will result in unexpected behavior. We must to take it into account.
> 
> cc @zhaohuabing

Ahh, I didn't realize that `onFailure` will be called when  in `send()` and it may fail in sync context instead of async immediately. One of the challenge of the implementation was distinguishing sync v.s. async failure because I ran into the unexpected behavior you said if `continueDecoding` is called in sync context.

I'll try to see how I can handle this sync failure explicitly. Meanwhile, if y'all have any idea how to detect in code whether the failure happens in async or sync context it would be greatly appreciated.

File: source/extensions/filters/http/oauth2/oauth_client.cc [hunk 13]
```diff
@@ -144,12 +144,40 @@ void OAuth2ClientImpl::dispatchRequest(Http::RequestMessagePtr&& msg) {
...
+    state_ = (result == Http::FilterHeadersStatus::Continue) ? OAuthState::FailureContinue
+                                                             : OAuthState::FailureStop;
   }
 }
 
 void OAuth2ClientImpl::onSuccess(const Http::AsyncClient::Request&,
                                  Http::ResponseMessagePtr&& message) {
+  // If not yet dispatched, onSuccess is called synchronously during decodeHeaders, not in an async
+  // token request. Set state_ for the caller to check instead of calling continueDecoding.
+  const bool is_request_dispatched = (in_flight_request_ != nullptr);
```
Comment (mchen391) [inline source/extensions/filters/http/oauth2/oauth_client.cc:180]: This is one of the key changes to detect synchronous calls of `onSuccess` or `onFailure` in `send()`: check if the async request has been dispatched. If `onSuccess` or `onFailure` is called in `send()`, async request hasn't been dispatched and hasn't been assigned to `in_flight_request_`, and in this case we should not call `continueDecoding()`.

File: source/extensions/filters/http/oauth2/oauth_client.cc [hunk 14]
```diff
@@ -144,12 +144,40 @@ void OAuth2ClientImpl::dispatchRequest(Http::RequestMessagePtr&& msg) {
...
+}
+
+void OAuth2ClientImpl::handleOAuthFailure(bool is_request_dispatched, const std::string& reason,
+                                          const std::string& extra_details) {
+  if (is_request_dispatched) {
+    parent_->handleOAuthFailureAsync(reason, extra_details);
+  } else {
+    const auto result = parent_->handleOAuthFailure(reason, extra_details);
+    state_ = (result == Http::FilterHeadersStatus::Continue) ? OAuthState::FailureContinue
+                                                             : OAuthState::FailureStop;
```
Comment (mchen391) [inline source/extensions/filters/http/oauth2/oauth_client.cc:160]: This is another key change: if request failed in `onSuccess` or `onFailure` before dispatched, `decodeHeaders` should either stop or continue accordingly, but we won't be able to directly return the decision back to `decodeHeaders`. Here we extended `OAuthState` so that `decodeHeaders` can check the state of the request and handle accordingly.

**Comment by mchen391** [comment]
> Sorry. I think we need to re-evaluate the whole implementation. Note, the onFailure may be called directly in sometimes. Then, call the `continueDecoding()` in the failure callback will result in unexpected behavior. We must to take it into account.
> 
> cc @zhaohuabing

Ok in fact when investigating this issue I found that not only `onFailure` but also `onSuccess` can be called directly inside `send()`, so calling `continueDecoding` in `onSuccess` is not safe either.

I've pushed a fix which I think is the most straightforward and easy solution on top of my head. In short, `onSuccess` and `onFailure` will now check if it is called _before_ the async request is dispatched (should not call `continueDecoding`), or _after_ it is dispatched (should call `continueDecoding`). Please refer to the two comments I left on the code for more details.

Happy to learn and discuss if y'all have any better and cleaner solution to this. Thank you for bringing this up!

cc @zhaohuabing @wbpcode

**Comment by wbpcode** [comment]
> Ok in fact when investigating this issue I found that not only onFailure but also onSuccess can be called directly inside send(), so calling continueDecoding in onSuccess is not safe either.

This should never happen in practice 🤔 ?

**Comment by mchen391** [comment]
> > Ok in fact when investigating this issue I found that not only onFailure but also onSuccess can be called directly inside send(), so calling continueDecoding in onSuccess is not safe either.
> 
> This should never happen in practice 🤔 ?

I'm not that familiar with the entire infra but there's actually a test around calling `onSuccess()` for unhealthy upstream ([here](https://github.com/mchen391/envoy/blob/ed070799f56093ec06c1025f4aeb47b2d82b17d6/test/extensions/filters/http/oauth2/oauth_test.cc#L302)). Based on my investigation (with claude):
* `send()` will call `onSuccess()` with response status being 5xx for unhealthy upstream
* `send()` will call `onFailure()` if network is completely unreachable

Either way, I made `onSuccess()` safe to call in both sync/async context as well as `onFailure()` just in case it ever hits that pattern.

**Comment by wbpcode** [comment]
> I'm not that familiar with the entire infra but there's actually a test around calling onSuccess() for unhealthy upstream ([here](https://github.com/mchen391/envoy/blob/ed070799f56093ec06c1025f4aeb47b2d82b17d6/test/extensions/filters/http/oauth2/oauth_test.cc#L302)). Based on my investigation (with claude):

This should be a test error. The onSuccess() should never be called synchronously

File: source/extensions/filters/http/oauth2/oauth_client.cc (hunk 14 above)
Comment (wbpcode) [reply source/extensions/filters/http/oauth2/oauth_client.cc:160]: Great. I think we may needn't the `handleOAuthFailureAsync` now?

We only need to call the `handleOAuthFailure`. And then to set the state or to call the continueDecoding based on the value of is_request_dispatched.

Just like the `handleRefreshTokenFailure` below.

Comment (mchen391) [reply source/extensions/filters/http/oauth2/oauth_client.cc:160]: Good call. Inlined `handleOAuthFailureAsync`.

**Comment by mchen391** [comment]
@wbpcode thanks for another review, please let me know if there's anything I need to do to move forward! Thank you!

**Comment by mchen391** [comment]
CI failed due to test coverage low. Added a few new tests in filter_test
