### PR TITLE
stats: fix req/resp body/hdrs sizes tracking

### LINKED ISSUE #15879: track_cluster_stats/request_response_sizes not working
I pushed a change -- via CDS -- to enable `track_cluster_stats/request_response_sizes` (#11559) and the change went through (e.g.: /config_dump shows that clusters picked up the knob) but still no stats:

```
$ curl -s 0:9901/stats  | grep upstream_rs_headers_size
cluster.foo.upstream_rs_headers_size: No recorded values
cluster.bar.upstream_rs_headers_size: No recorded values
...
```

I tried a binary (hot) restart and also nothing... Anyone using this feature? Digging through the code now to see if
there's anything special about it. It's not working for both mTLS upstreams and over the loopback upstreams (not that it should make a difference). 

cc: @sc0ttbeardsley

### PR DESCRIPTION
**Pull request by rgs1**
Perform the accounting for these stats from UpstreamRequest, where we
get access to the correct numbers.

Things fixed:

* values are recorded now (they weren't previously)
* values will be exactly what's sent/received from upstream since they are recorded
   in the router after/before other filters
* the destination cluster will be the right one
* reqs/resps with trailers are handled (they weren't previously)
* added an integration test to prevent regressions

Fixes #15879.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

**Comment by rgs1** [comment]
I'll follow-up with updated unit tests and an integration tests.

File: source/common/http/conn_manager_impl.cc [hunk 1]
```diff
@@ -987,6 +965,11 @@ void ConnectionManagerImpl::ActiveStream::decodeHeaders(RequestHeaderMapPtr&& he
   ASSERT(!cached_route_);
   refreshCachedRoute();
 
+  auto req_resp_stats = clusterRequestResponseSizeStats();
+  if (req_resp_stats.has_value()) {
+    req_resp_stats->get().upstream_rq_headers_size_.recordValue(request_headers_->byteSize());
+  }
+
```
Comment (rgs1) [inline source/common/http/conn_manager_impl.cc:972]: Note to self & others (will add a inline comment most likely): an important change here is that we now compute request headers size _after_ the route has been selected (because that's what makes cluster info available), so we are most likely adding some internally added headers to the calculation. We might want to note this in some related docs as well.

**Comment by rgs1** [comment]
Need to an integration test.

/wait

File: source/common/http/conn_manager_impl.cc [hunk 2]
```diff
@@ -669,18 +669,13 @@ ConnectionManagerImpl::ActiveStream::ActiveStream(ConnectionManagerImpl& connect
...
-    Upstream::ClusterRequestResponseSizeStatsOptRef req_resp_stats =
-        upstream_host->cluster().requestResponseSizeStats();
-    if (req_resp_stats.has_value()) {
-      req_resp_stats->get().upstream_rq_body_size_.recordValue(
-          filter_manager_.streamInfo().bytesReceived());
-      req_resp_stats->get().upstream_rs_body_size_.recordValue(
-          filter_manager_.streamInfo().bytesSent());
-    }
+
+  auto req_resp_stats = clusterRequestResponseSizeStats();
```
Comment (jmarantz) [inline source/common/http/conn_manager_impl.cc:673]: I think it's clearer to leave the explicit type in, as you cannot deduce it from the RHS.

https://google.github.io/styleguide/cppguide.html#Type_deduction

File: source/common/http/conn_manager_impl.cc [hunk 3]
```diff
@@ -777,15 +772,9 @@ void ConnectionManagerImpl::ActiveStream::chargeStats(const ResponseHeaderMap& h
...
-  Upstream::HostDescriptionConstSharedPtr upstream_host =
-      connection_manager_.read_callbacks_->upstreamHost();
-
-  if (upstream_host != nullptr) {
-    Upstream::ClusterRequestResponseSizeStatsOptRef req_resp_stats =
-        upstream_host->cluster().requestResponseSizeStats();
-    if (req_resp_stats.has_value()) {
-      req_resp_stats->get().upstream_rs_headers_size_.recordValue(headers.byteSize());
-    }
+  auto req_resp_stats = clusterRequestResponseSizeStats();
```
Comment (jmarantz) [inline source/common/http/conn_manager_impl.cc:775]: ditto

File: source/common/http/conn_manager_impl.cc [hunk 4]
```diff
@@ -987,6 +965,15 @@ void ConnectionManagerImpl::ActiveStream::decodeHeaders(RequestHeaderMapPtr&& he
   ASSERT(!cached_route_);
   refreshCachedRoute();
 
+  // Note: this is the earliest point at which we can record headers size stats, given that
+  // cluster info becomes available after refreshCachedRoute() is called. So any additional
+  // headers that were added before this point will be accounted for, thus this number will
+  // be bigger than expected.
+  auto req_resp_stats = clusterRequestResponseSizeStats();
```
Comment (jmarantz) [inline source/common/http/conn_manager_impl.cc:972]: ditto

File: test/common/http/conn_manager_impl_test_2.cc [hunk 5]
```diff
@@ -2667,16 +2667,17 @@ TEST_F(HttpConnectionManagerImplTest, TestUpstreamRequestHeadersSize) {
       .WillOnce(Return(FilterHeadersStatus::StopIteration));
   EXPECT_CALL(*decoder_filters_[0], decodeComplete());
 
-  std::shared_ptr<NiceMock<Upstream::MockHostDescription>> host_{
-      new NiceMock<Upstream::MockHostDescription>()};
-  filter_callbacks_.upstreamHost(host_);
+  std::shared_ptr<Upstream::MockThreadLocalCluster> cluster =
```
Comment (jmarantz) [inline test/common/http/conn_manager_impl_test_2.cc:2670]: actually this is a case where `auto` is fine as it's clear from the RHS what the type has to be

File: test/common/http/conn_manager_impl_test_2.cc [hunk 6]
```diff
@@ -2709,16 +2710,17 @@ TEST_F(HttpConnectionManagerImplTest, TestUpstreamRequestBodySize) {
 
   EXPECT_CALL(*decoder_filters_[0], decodeComplete());
 
-  std::shared_ptr<NiceMock<Upstream::MockHostDescription>> host_{
-      new NiceMock<Upstream::MockHostDescription>()};
-  filter_callbacks_.upstreamHost(host_);
+  std::shared_ptr<Upstream::MockThreadLocalCluster> cluster =
```
Comment (jmarantz) [inline test/common/http/conn_manager_impl_test_2.cc:2713]: ditto

**Review by jmarantz — COMMENTED** [review]
looks good; just a few nits about `auto`

**Review by jmarantz — APPROVED** [review]
@envoyproxy/senior-maintainers

**Comment by rgs1** [comment]
Btw, I think we could merge this as is and I'll follow-up with an integration test to avoid regressions. Thanks!

**Comment by rgs1** [comment]
@jmarantz added an integration test, in case you want to do another pass -- thanks.

**Comment by rgs1** [comment]
> @jmarantz added an integration test, in case you want to do another pass -- thanks.

... and I verified that the integration test does not pass/finish without the new approach (using cluster info to get that stats instead of the upstream host).

File: source/common/http/conn_manager_impl.cc [hunk 7]
```diff
@@ -987,6 +967,16 @@ void ConnectionManagerImpl::ActiveStream::decodeHeaders(RequestHeaderMapPtr&& he
...
+  // Note: this is the earliest point at which we can record headers size stats, given that
+  // cluster info becomes available after refreshCachedRoute() is called. So any additional
+  // headers that were added before this point will be accounted for, thus this number will
+  // be bigger than expected.
+  Upstream::ClusterRequestResponseSizeStatsOptRef req_resp_stats =
+      clusterRequestResponseSizeStats();
+  if (req_resp_stats.has_value()) {
+    req_resp_stats->get().upstream_rq_headers_size_.recordValue(request_headers_->byteSize());
+  }
+
```
Comment (snowp) [inline source/common/http/conn_manager_impl.cc:979]: This will record the stats for the cluster selected before any of the filters ran, which doesn't seem ideal: the target cluster might change before it hits the router, which would misattribute the values

Any way to do this after we know the upstream for sure? Can this be done in the router? Or log this once the stream ends, reading the upstream cluster from the stream info?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks, one high level question before I dig deeper

File: source/common/http/conn_manager_impl.cc (hunk 7 above)
Comment (rgs1) [reply source/common/http/conn_manager_impl.cc:979]: Hmm, would doing it from completeRequest() -- where we record values for req/resp body size -- work?

Comment (rgs1) [reply source/common/http/conn_manager_impl.cc:979]: Alright we chatted offline, we'll push all the recording into completeRequest() and note the limitations of this approach (doesn't work well with direct responses, retries, etc).

Comment (rgs1) [reply source/common/http/conn_manager_impl.cc]: Had 2nd thoughts, let's get it right -- I'll move this to the router.

**Comment by rgs1** [comment]
Ok moved things into the router, will follow-up with unit tests in a bit (integration test is still good). I'll take a look at supporting retries too, if it'll need significant refactoring we can probably do that in a follow-up?

**Comment by rgs1** [comment]
Tests coming up in a bit.

/wait

**Comment by rgs1** [comment]
cc: @mattklein123 for visibility (given there will be more work in this area, e.g.: to properly compute these stats for retries).

File: source/common/router/router.cc [hunk 8]
```diff
@@ -738,6 +744,12 @@ Http::FilterDataStatus Filter::decodeData(Buffer::Instance& data, bool end_strea
   }
 
   if (end_stream) {
+    Upstream::ClusterRequestResponseSizeStatsOptRef req_resp_stats =
+        cluster_->requestResponseSizeStats();
+    if (req_resp_stats.has_value()) {
+      req_resp_stats->get().upstream_rq_body_size_.recordValue(
+          callbacks_->streamInfo().bytesReceived());
+    }
```
Comment (snowp) [inline source/common/router/router.cc:752]: This only captures the full data if the body was fully buffered by another filter since decodeData can be called multiple times

File: source/common/router/router.cc [hunk 9]
```diff
@@ -1380,6 +1405,13 @@ void Filter::onUpstreamData(Buffer::Instance& data, UpstreamRequest& upstream_re
   // streams.
   ASSERT(upstream_requests_.size() == 1);
   if (end_stream) {
+    Upstream::ClusterRequestResponseSizeStatsOptRef req_resp_stats =
+        cluster_->requestResponseSizeStats();
+    if (req_resp_stats.has_value()) {
+      req_resp_stats->get().upstream_rs_body_size_.recordValue(
+          callbacks_->streamInfo().bytesSent());
+    }
```
Comment (snowp) [inline source/common/router/router.cc:1413]: We never buffer the upstream at this point, so this too would only account for the last data chunk

**Review by snowp — CHANGES_REQUESTED** [review]

File: source/common/router/router.cc (hunk 8 above)
Comment (rgs1) [reply source/common/router/router.cc:752]: Isn't callbacks_->streamInfo().bytesReceived() meant to be cumulative?

https://github.com/envoyproxy/envoy/blob/main/include/envoy/stream_info/stream_info.h#L289

File: source/common/router/router.cc (hunk 9 above)
Comment (rgs1) [reply source/common/router/router.cc:1413]: Same as above, thought callbacks_->streamInfo().bytesSent() would be cumulative

[the remark this answers is not in the document]
Comment (rgs1) [reply source/common/router/router.cc:1413]: sure, thought about it but since they didn't add up to that many lines i didn't -- but i'll fold them into helpers.

File: source/common/router/router.cc (hunk 8 above)
Comment (rgs1) [reply source/common/router/router.cc]: Ok per offline chat, moving this into UpstreamRequest and using the stream_info_ there when applicable.

File: source/common/router/router.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (rgs1) [reply source/common/router/router.cc]: Now that we are doing everything from `~UpstreamRequest`, everything  happens in one place so it's much DRY-ier.

**Comment by rgs1** [comment]
@snowp Ok, I think is ready for another pass -- thanks!

**Comment by rgs1** [comment]
FYI this patch is generating stats nicely for us in prod 👍

File: docs/root/version_history/current.rst [hunk 10]
```diff
@@ -19,6 +19,7 @@ Bug Fixes
 ---------
 *Changes expected to improve the state of the world and are unlikely to have negative effects*
 
+* cluster: fixed the :ref:`cluster stats <config_cluster_manager_cluster_stats_request_response_sizes>` histograms.
```
Comment (alyssawilk) [inline docs/root/version_history/current.rst:22]: I think it's worth noting what is being fixed, that we'll now record responses read from upstream even if not delivered downstream, and record per-retry .

Do you think it's worth calling this out in docs as well?  I could imagine it being confusing if the number of upstream entries is higher than downstream, but odds are most folks won't notice and it could be more detail than it's worth :-P

File: source/common/router/upstream_request.cc [hunk 11]
```diff
@@ -94,6 +94,20 @@ UpstreamRequest::~UpstreamRequest() {
         FilterUtility::percentageOfTimeout(response_time, parent_.timeout().per_try_timeout_));
   }
 
+  // Ditto for request/response size histograms.
+  Upstream::ClusterRequestResponseSizeStatsOptRef req_resp_stats_opt =
+      parent_.cluster()->requestResponseSizeStats();
+  if (req_resp_stats_opt.has_value()) {
+    auto& req_resp_stats = req_resp_stats_opt->get();
+    req_resp_stats.upstream_rq_headers_size_.recordValue(parent_.downstreamHeaders()->byteSize());
```
Comment (alyssawilk) [inline source/common/router/upstream_request.cc:102]: As long as we're improving these stats, should 100 continue headers be included in header size?
strange that no one cares about trailers, but I guess we can add them if anyone wants them, I'd think we'd want to keep them distinct from headers in any case.

File: source/common/router/upstream_request.cc [hunk 12]
```diff
@@ -94,6 +94,20 @@ UpstreamRequest::~UpstreamRequest() {
         FilterUtility::percentageOfTimeout(response_time, parent_.timeout().per_try_timeout_));
   }
 
+  // Ditto for request/response size histograms.
+  Upstream::ClusterRequestResponseSizeStatsOptRef req_resp_stats_opt =
+      parent_.cluster()->requestResponseSizeStats();
+  if (req_resp_stats_opt.has_value()) {
```
Comment (alyssawilk) [inline source/common/router/upstream_request.cc:100]: I think this will also correctly report bytes sent to multiple upstreams for hedging requests.  I think that's worth a regression test as well?

File: source/common/router/upstream_request.h [hunk 13]
```diff
@@ -141,6 +141,7 @@ class UpstreamRequest : public Logger::Loggable<Logger::Id::router>,
   StreamInfo::StreamInfoImpl stream_info_;
   StreamInfo::UpstreamTiming upstream_timing_;
   const MonotonicTime start_time_;
+  absl::optional<uint64_t> response_headers_size_{};
```
Comment (alyssawilk) [inline source/common/router/upstream_request.h:144]: worth a comment on why we latch original size?

File: test/common/router/router_test.cc [hunk 14]
```diff
@@ -73,6 +73,78 @@ class RouterTest : public RouterTestBase {
...
+        cm_.thread_local_cluster_.cluster_.info_->request_response_size_stats_store_,
+        deliverHistogramToSinks(Property(&Stats::Metric::name, "upstream_rs_body_size"), 5ull));
+    Buffer::OwnedImpl response_data("hello");
+    // NOLINTNEXTLINE: Silence null pointer access warning
+    response_decoder->decodeData(response_data, !with_trailers);
+
+    if (with_trailers) {
+      Http::ResponseTrailerMapPtr response_trailers(
+          new Http::TestResponseTrailerMapImpl{{"some-trailer", "13"}});
+      // NOLINTNEXTLINE: Silence null pointer access warning
```
Comment (alyssawilk) [inline test/common/router/router_test.cc:142]: alternately, would it be possible to remove the NOLINT if you skipped the temporary variable?

File: test/common/router/router_test.cc [hunk 15]
```diff
@@ -73,6 +73,78 @@ class RouterTest : public RouterTestBase {
...
+      Http::TestRequestTrailerMapImpl trailers{{"some", "trailer"}};
+      router_.decodeTrailers(trailers);
+    }
+
+    EXPECT_CALL(
+        cm_.thread_local_cluster_.cluster_.info_->request_response_size_stats_store_,
+        deliverHistogramToSinks(Property(&Stats::Metric::name, "upstream_rs_headers_size"), 10ull));
+    Http::ResponseHeaderMapPtr response_headers(
+        new Http::TestResponseHeaderMapImpl{{":status", "200"}});
+    // NOLINTNEXTLINE: Silence null pointer access warning
```
Comment (alyssawilk) [inline test/common/router/router_test.cc:129]: would an assert that response decoder is non-null silence the warnings, or is our linter just not smart enough?

File: test/integration/req_resp_size_stats_integration_test.cc [hunk 16]
```diff
@@ -0,0 +1,39 @@
...
+      {":method", "GET"}, {":path", "/found"}, {":scheme", "http"}, {":authority", "foo.com"}};
+  Http::TestResponseHeaderMapImpl response_headers{{":status", "200"}};
+  auto response = sendRequestAndWaitForResponse(request_headers, 0, response_headers, 0, 0,
+                                                TestUtility::DefaultTimeout);
+  EXPECT_TRUE(upstream_request_->complete());
+  ASSERT_TRUE(response->complete());
+  EXPECT_EQ("200", response->headers().getStatusValue());
+
+  test_server_->waitUntilHistogramHasSamples("cluster.cluster_0.upstream_rq_headers_size");
+  test_server_->waitUntilHistogramHasSamples("cluster.cluster_0.upstream_rs_headers_size");
```
Comment (alyssawilk) [inline test/integration/req_resp_size_stats_integration_test.cc:35]: Let's put this in protocol integration test - I don't think we need a new file for it :-)

Also consider adding histogram checks to http_timeout_integration_test.cc:TEST_P(HttpTimeoutIntegrationTest, HedgedPerTryTimeout) {
and TEST_P(ProtocolIntegrationTest, Retry) {

File: test/integration/server_stats.h [hunk 17]
```diff
@@ -38,6 +38,14 @@ class IntegrationTestServerStats {
    */
   virtual void waitForCounterExists(const std::string& name) PURE;
 
+  /**
+   * Wait until a histogram has samples.
+   * @param name histogram name.
+   */
+  virtual void waitUntilHistogramHasSamples(
+      const std::string& name,
+      std::chrono::milliseconds timeout = std::chrono::milliseconds::zero()) PURE;
```
Comment (alyssawilk) [inline test/integration/server_stats.h:47]: I'd prefer waiting for Default timeout and passing on the status-failure if the histogram doesn't exist so 
ASSERT_TRUE(waitUntilHistogram...)?

**Review by alyssawilk — COMMENTED** [review]
This looks fantastic - thanks for tracking it down!

File: source/common/router/upstream_request.cc (hunk 11 above)
Comment (rgs1) [reply source/common/router/upstream_request.cc:102]: We are including the 100 continue headers right? In decodeHeaders() we do:

```
  response_headers_size_ = headers->byteSize();
  ```
  
  unconditionally. 
  
  I am not crazy about trailers, so we can add them later maybe?

File: docs/root/version_history/current.rst (hunk 10 above)
Comment (rgs1) [reply docs/root/version_history/current.rst:32]: Pushing some improvements in a bit to the change log, I am thinking they might be too much detail for the docs? Happy to follow up later on if someone asks :p

File: source/common/router/upstream_request.cc (hunk 12 above)
Comment (rgs1) [reply source/common/router/upstream_request.cc:100]: The router creates one UpstreamRequest per each upstream request, so yeah we are covered. Yeah I can add something to the existing hedging tests or extend one of those.

File: source/common/router/upstream_request.h (hunk 13 above)
Comment (rgs1) [reply source/common/router/upstream_request.h:144]: Sure thing.

File: test/common/router/router_test.cc (hunk 15 above)
Comment (rgs1) [reply test/common/router/router_test.cc:129]: you mean instead of:

```
    Http::ResponseDecoder* response_decoder = nullptr;

    EXPECT_CALL(cm_.thread_local_cluster_.conn_pool_, newStream(_, _))
        .WillOnce(Invoke(
            [&](Http::ResponseDecoder& decoder,
                Http::ConnectionPool::Callbacks& callbacks) -> Http::ConnectionPool::Cancellable* {
              response_decoder = &decoder;
```

accessing the decoder directly via `cm_.thread_local_cluster_.conn_pool_` or something?

Comment (rgs1) [reply test/common/router/router_test.cc:129]: errr this comment was for the prev comment about a temporary. Let me see if the assert makes the linter happy.

File: source/common/router/upstream_request.cc (hunk 12 above)
Comment (rgs1) [reply source/common/router/upstream_request.cc:100]: Done.

File: test/integration/server_stats.h (hunk 17 above)
Comment (rgs1) [reply test/integration/server_stats.h:47]: Hmm, everything else in that file follows this pattern tho and the default would still be zero/unbound.

File: test/integration/req_resp_size_stats_integration_test.cc (hunk 16 above)
Comment (rgs1) [reply test/integration/req_resp_size_stats_integration_test.cc]: Moved into protocol integration test, can I add the other checks with the proposed remaining follow ups?

File: source/common/router/upstream_request.cc (hunk 11 above)
Comment (rgs1) [reply source/common/router/upstream_request.cc:101]: I take back my comment – we are not accounting in `decode100ContinueHeaders()`. I think we should... Adding it.

Comment (rgs1) [reply source/common/router/upstream_request.cc:101]: My comment about punting on accounting for trailers remains though.

File: test/common/router/router_test.cc (hunk 15 above)
Comment (rgs1) [reply test/common/router/router_test.cc]: The linter isn't buying the assert()... so NOLINT stays I am afraid :-(

File: source/common/router/upstream_request.h [hunk 18]
```diff
@@ -141,6 +144,9 @@ class UpstreamRequest : public Logger::Loggable<Logger::Id::router>,
   StreamInfo::StreamInfoImpl stream_info_;
   StreamInfo::UpstreamTiming upstream_timing_;
   const MonotonicTime start_time_;
+  // This is wrapped in an optional, since we want to avoid computing zero size headers when in
+  // reality we just didn't get a response back.
+  absl::optional<uint64_t> response_headers_size_{};
```
Comment (alyssawilk) [inline source/common/router/upstream_request.h:149]: optionally: what do you think of just initializing to zero?  I don't think you can have valid 0 length headers so not recording when 0 seems fine to me.
That said if we do optional lengths for bodies (where we may want to disambiguate between 0 and not-present) and you want this optional for consistency that's fine.

File: source/common/router/upstream_request.cc [hunk 19]
```diff
@@ -93,6 +93,28 @@ UpstreamRequest::~UpstreamRequest() {
...
+    auto rq_body_size = stream_info_.bytesSent();
+    if (rq_body_size != 0) {
+      req_resp_stats.upstream_rq_body_size_.recordValue(rq_body_size);
+    }
+
+    if (response_headers_size_.has_value()) {
+      req_resp_stats.upstream_rs_headers_size_.recordValue(response_headers_size_.value());
+
+      auto rs_body_size = stream_info_.bytesSent();
+      if (rs_body_size != 0) {
```
Comment (alyssawilk) [inline source/common/router/upstream_request.cc:112]: So unlike response headers, here I _think_ we want to either
1) differentiate between 0 length bodies and no bodies or
2) always record 0 if we can't differentiate

Previously we did add to the histogram for empty bodies and I think not doing that may be a functional change some folks don't want.

File: test/integration/protocol_integration_test.cc [hunk 20]
```diff
@@ -2436,4 +2436,26 @@ TEST_P(ProtocolIntegrationTest, RemoveResponseHeadersFilter) {
   EXPECT_THAT(response->body(), HasSubstr("missing required header: :status"));
 }
 
+TEST_P(ProtocolIntegrationTest, ReqRespSizeStats) {
+  config_helper_.addConfigModifier([&](envoy::config::bootstrap::v3::Bootstrap& bootstrap) -> void {
```
Comment (alyssawilk) [inline test/integration/protocol_integration_test.cc:2440]: can we add this modifier into (ProtocolIntegrationTest, Retry) and make sure we get both updates?

File: test/integration/server_stats.h (hunk 17 above)
Comment (alyssawilk) [reply test/integration/server_stats.h:47]: Yeah, I'm trying to eradicate infinite timeouts in Envoy tests.  I can refactor this with the rest though.

File: test/extensions/upstreams/http/tcp/upstream_request_test.cc [hunk 21]
```diff
@@ -103,15 +107,15 @@ class TcpUpstreamTest : public ::testing::Test {
...
-  NiceMock<Network::MockClientConnection> connection_;
-  NiceMock<Router::MockRouterFilterInterface> mock_router_filter_;
-  Envoy::Tcp::ConnectionPool::MockConnectionData* mock_connection_data_;
-  std::unique_ptr<TcpUpstream> tcp_upstream_;
   TestRequestHeaderMapImpl request_{{":method", "CONNECT"},
                                     {":path", "/"},
                                     {":protocol", "bytestream"},
                                     {":scheme", "https"},
                                     {":authority", "host"}};
+  NiceMock<Network::MockClientConnection> connection_;
```
Comment (alyssawilk) [inline test/extensions/upstreams/http/tcp/upstream_request_test.cc:115]: why move these?

**Review by alyssawilk — COMMENTED** [review]
Looking good!  One functional nit I'm sorry I missed in the first pass, but nearly there regardless :-)

File: source/common/router/upstream_request.cc (hunk 19 above)
Comment (rgs1) [reply source/common/router/upstream_request.cc:112]: Hmm, I don't think anyone would complain given the stats aren't currently generated :p 

The way I see it is – and really this is how we are using this internally – that we use this to track regressions in payload sizes (oh you did what to that Javascript lib again). So skipping 0 length bodies is probably alright, if what you are tracking really is that your bodies don't get bloated and not so much how many empty bodies were sent.

File: source/common/router/upstream_request.h (hunk 18 above)
Comment (rgs1) [reply source/common/router/upstream_request.h:149]: See below, leaning toward avoiding detecting if body should be there and accounting zero sized bodies (IMO they don't add signal anyway).

File: test/integration/protocol_integration_test.cc (hunk 20 above)
Comment (rgs1) [reply test/integration/protocol_integration_test.cc:2440]: Sure thing.

File: test/extensions/upstreams/http/tcp/upstream_request_test.cc (hunk 21 above)
Comment (rgs1) [reply test/extensions/upstreams/http/tcp/upstream_request_test.cc:115]: Because:

```
+    EXPECT_CALL(mock_router_filter_, downstreamHeaders())
+        .Times(AnyNumber())
+        .WillRepeatedly(Return(&request_));
+    EXPECT_CALL(mock_router_filter_, cluster()).Times(AnyNumber());
```

We need to access the request headers from ~UpstreamRequest, so the headers have to be destroyed last.

Comment (alyssawilk) [reply test/extensions/upstreams/http/tcp/upstream_request_test.cc:115]: gotcha, makes sense!

File: source/common/router/upstream_request.cc (hunk 19 above)
Comment (alyssawilk) [reply source/common/router/upstream_request.cc:112]: Wait not at all?  yikes, it looks from code like it'd be generated, just not for retries.

Regardless I _think_ we should track 0 length bodies, because while they're not needed for your use case, they could be for others' 
If you actively prefer not doing so, I think you need to update docs to make that explicit, and then if someone wants it later thy can add a knob, but I'd prefer just tracking all bodies.

Comment (rgs1) [reply source/common/router/upstream_request.cc:111]: Hmm, in the case of the request's body we have:

https://github.com/envoyproxy/envoy/blob/main/envoy/stream_info/stream_info.h#L419

Should we make that `absl::optional<uint64_t> bytesSent()` to centralize the process of determining if there was a body or not?

Ditto for `bytesReceived()`:

https://github.com/envoyproxy/envoy/blob/main/envoy/stream_info/stream_info.h#L296

Comment (rgs1) [reply source/common/router/upstream_request.cc:111]: Ok I added accounting for 0 length bodies and empty bodies back. We can change it or add a knob to configure this later on, if there's a need for excluding them.

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
oh actually you handed over to me, I'll assume it's all good :-)

**Review by jmarantz — APPROVED** [review]

File: test/test_common/utility.cc [hunk 22]
```diff
@@ -222,6 +222,28 @@ AssertionResult TestUtility::waitForGaugeEq(Stats::Store& store, const std::stri
...
 
+AssertionResult TestUtility::waitUntilHistogramHasSamples(Stats::Store& store,
+                                                          const std::string& name,
+                                                          Event::TestTimeSystem& time_system,
+                                                          std::chrono::milliseconds timeout) {
+  Event::TestTimeSystem::RealTimeBound bound(timeout);
+  while (true) {
+    auto histo = findByName<Stats::ParentHistogramSharedPtr>(store.histograms(), name);
+    if (histo) {
+      if (histo->cumulativeStatistics().sampleCount()) {
```
Comment (antoniovicente) [inline test/test_common/utility.cc:233]: this call is not thread safe and is triggering TSAN errors, please fix ASAP.

https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/78702/logs/189

Comment (rgs1) [reply test/test_common/utility.cc:233]: Hmm, how come TSAN didn't complain with the original diff? I'll send a fix in a bit

Comment (rgs1) [reply test/test_common/utility.cc:233]: You sure it's me, seeing quic integration failing TSAN too:

https://dev.azure.com/cncf/envoy/_build/results?buildId=78720&view=logs&jobId=d1f76054-8f79-554b-6f4a-11d6a63b8e00&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=266e17e3-d213-54b5-deef-0dcee01da137

Comment (rgs1) [reply test/test_common/utility.cc:233]: Well, the integration test I touched did become flaky so maybe it is me:

```
//test/integration:protocol_integration_test                              FLAKY, failed in 1 out of 6 in 227.4s
  Stats over 6 runs: max = 227.4s, min = 214.3s, avg = 219.7s, dev = 5.2s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/testlogs/test/integration/protocol_integration_test/shard_5_of_5/test_attempts/attempt_1.log
//test/integration:quic_http_integration_test                            FAILED in 4 out of 8 in 37.9s
  Stats over 8 runs: max = 37.9s, min = 33.8s, avg = 35.5s, dev = 1.3s
```

Looking into it...

Comment (rgs1) [reply test/test_common/utility.cc:233]: the quic TSAN failure is here: https://gist.github.com/rgs1/1d352d45a78779b14e68cde4ac39e254

Comment (rgs1) [reply test/test_common/utility.cc:233]: Ok now I see mine:

https://gist.github.com/rgs1/bbd811c453484d8887a0448cc8c3d99c

This race is acceptable, so I think we can tell TSAN to ignore it.

Comment (antoniovicente) [reply test/test_common/utility.cc:233]: The TSAN failure involves waitUntilHistogramHasSamples which was introduced in this PR.  That's why I suspect it is related to this.

2021-06-11T18:24:15.8290833Z     #0 Envoy::Stats::HistogramStatisticsImpl::sampleCount() const /proc/self/cwd/./source/common/stats/histogram_impl.h:62:50 (protocol_integration_test+0x7c8b879)
2021-06-11T18:24:15.8292040Z     #1 Envoy::TestUtility::waitUntilHistogramHasSamples(Envoy::Stats::Store&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Envoy::Event::TestTimeSystem&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) /proc/self/cwd/test/test_common/utility.cc:233:41 (protocol_integration_test+0x794eef8)

Comment (rgs1) [reply test/test_common/utility.cc:233]: Possible fix: https://github.com/envoyproxy/envoy/pull/16946
