### PR TITLE
proxy_protocol: fix bug that disallowed duplicate TLVs

### LINKED ISSUE #42075: v1.34.0+ silently skips duplicate TLV types for upstream proxy protocol v2 connections
### Title

v1.34.0+ silently skips duplicate TLV types for upstream proxy protocol v2 connections

### Background

Custom Envoy listener filters and network filters can set the [`ProxyProtocolFilterState`](https://github.com/envoyproxy/envoy/blob/eef470f6f39dc621f3e336f8a7b588fea445a31a/source/common/network/proxy_protocol_filter_state.h#L12) with custom TLVs. The Envoy cluster proxy protocol transport socket [would then encode these TLVs](https://github.com/envoyproxy/envoy/blob/eef470f6f39dc621f3e336f8a7b588fea445a31a/source/extensions/common/proxy_protocol/proxy_protocol_header.cc#L113) in proxy protocol connection to the upstream.

In Confluent, we have a use case where our custom filters set multiple TLVs with the same `type` but different `subtype`. Example:

```
TLV 1: Type=0xEF, Subtype=0x01
TLV 2: Type=0xEF, Subtype=0x02
```

### Problem

Prior to Envoy v1.34.0, custom filters could set TLVs with duplicate types in `ProxyProtocolFilterState`, and proxy protocol transport socket would correctly propagate the TLVs to the upstream.

v1.34.0 **introduced a hidden behavior change** due to https://github.com/envoyproxy/envoy/pull/37591: When two TLVs with the same type are detected, the transport socket **silently drops** the 2nd TLV.

https://github.com/envoyproxy/envoy/blob/eef470f6f39dc621f3e336f8a7b588fea445a31a/source/extensions/common/proxy_protocol/proxy_protocol_header.cc#L134-L136

### Spec Compliance

Proxy protocol specification: https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

This new behavior is **incorrect**. The original behavior before v1.34.0 was spec-compliant. The spec does NOT prohibit sending duplicate TLV types. Envoy should not skip duplicate TLVs.

### Proposed Fix

Revert the behavior change by completely removing the following lines

https://github.com/envoyproxy/envoy/blob/eef470f6f39dc621f3e336f8a7b588fea445a31a/source/extensions/common/proxy_protocol/proxy_protocol_header.cc#L134-L136

I don't have context on if it's needed. The transport socket is able to correctly pass duplicate TLVs to upstream cluster once these lines are removed (patched and tested in Confluent).

### Ref

https://github.com/envoyproxy/envoy/issues/18520
https://github.com/envoyproxy/envoy/pull/37591

@timflannagan (introduced the change above) do you have context on why the duplicate TLV check was introduced?
@ggreenway (owner of proxy protocol in Envoy)

### PR DESCRIPTION
**Pull request by ggreenway**
Commit Message: A bug was introduced in https://github.com/envoyproxy/envoy/pull/37591 which removed TLVs if
there were multiple TLVs with the same key. This is not correct behavior according to the PROXY protocol specification.

This change allows duplicates to both be passed through from a downstream, or configured for addition at the transport socket or host level.
Risk Level: Low
Testing: New test added
Docs Changes: Updated
Release Notes: Added
Runtime guard: `envoy.reloadable_features.proxy_protocol_allow_duplicate_tlvs`
Fixes #42075

### CODE REVIEW

File: source/extensions/transport_sockets/proxy_protocol/proxy_protocol.cc [hunk 1]
```diff
@@ -198,30 +198,50 @@ std::vector<Envoy::Network::ProxyProtocolTLV> UpstreamProxyProtocolSocket::build
...
       }
     }
   }
 
   // If host-level parse failed or was not present, we still read config-level TLVs.
-  for (const auto& tlv : added_tlvs_) {
-    if (processed_tlv_types.contains(tlv.type)) {
-      ENVOY_LOG_EVERY_POW_2_MISC(info, "Skipping duplicate TLV type from added_tlvs {}", tlv.type);
-      continue;
+  if (Runtime::runtimeFeatureEnabled(
```
Comment (botengyao) [inline source/extensions/transport_sockets/proxy_protocol/proxy_protocol.cc]: seems multiple runtime guard get, can we latch the value to improve it a bit?

File: api/envoy/config/core/v3/proxy_protocol.proto [hunk 2]
```diff
@@ -102,6 +102,9 @@ message ProxyProtocolConfig {
   //   at the transport socket level and override them at the host level.
   // - Any TLV defined in the ``pass_through_tlvs`` field will be overridden by either the host-level
   //   or transport socket-level TLV.
+  //
+  // If there are multiple TLVs with the same key, only the TLVs from the highest precedence level
```
Comment (botengyao) [inline api/envoy/config/core/v3/proxy_protocol.proto]: nit: s/key/type?
