### PR TITLE
test: fix macOS http2_integration_test hang with longer connect timeout

### LINKED ISSUE #1937: hang in http2_integration_test's CookieRoutingNoCookieNoTtl
It's somewhat difficult to reproduce outside of CI. Locally, hung copies of the test are stuck in `FakeUpstream::waitForHttpConnection(client_dispatcher, upstreams)`. Unlike the hang that @alyssawilk debugged last week, this test does invoke the client dispatcher.

In practice, when running the test repeatedly, macOS ends up with roughly 7,000 connections in the TIME_WAIT state. At that point, the connections to FakeUpstream (which are using http1 in this test) start taking longer to complete. The connect timeout is 5 seconds, and I believe that in some cases the connection times out and the test ends up waiting for a connection that timed out.

If I bump the timeout up to 30s, it seems I can run the test for as many iterations as I like (10,000+). With a 1s timeout it reliably fails after a few hundred iterations. I can modify this particular test to increase the timeout easily enough, but I'm not sure that's a great solution.

### PR DESCRIPTION
**Pull request by zuercher**
Empirically, the macOS TCP stack can take a very long time to form a connection, causing integration tests to hang since they do not expect connection timeouts to occur. Work around the problem by increasing the integration test connect timeout.

Fixes #1937.

Signed-off-by: Stephan Zuercher <stephan@turbinelabs.io>

### CODE REVIEW

File: test/config/utility.cc [hunk 1]
```diff
@@ -114,6 +114,13 @@ void ConfigHelper::finalize(const std::vector<uint32_t>& ports) {
     }
   }
   ASSERT(port_idx == ports.size());
+
+#ifdef __APPLE__
+  // Under heavy load (and in particular in CI), macOS connections can take inordinately long to
+  // complete.
+  setConnectTimeout(std::chrono::seconds(30));
```
Comment (alyssawilk) [inline test/config/utility.cc]: Thought: rather than doing this, you may want to setConnectionTimeout(default timeout we have today) and then in the set function scale up for apple.

reason being if someone wants to set a higher or lower timeout this may not behave as you'd expect for Apple.
I'm totally fine with you sticking with this and revising if needed since you pretty much singlehandedly support the macos builds and can always tweak later if you run into the thing I'm concerned about :-)

Comment (zuercher) [reply test/config/utility.cc]: Let me poke at it a bit.

File: test/config/utility.cc [hunk 2]
```diff
@@ -114,6 +113,18 @@ void ConfigHelper::finalize(const std::vector<uint32_t>& ports) {
     }
   }
   ASSERT(port_idx == ports.size());
+
+  if (!connect_timeout_set_) {
```
Comment (alyssawilk) [inline test/config/utility.cc]: Alternately you could just set it in initialize() before anyone has had a chance to override.

Comment (zuercher) [reply test/config/utility.cc]: I put it at the end of finalize() so that it sees any additional clusters that the test might create via addConfigModifier.

**Comment by mattklein123** [comment]
I'm actually going to go ahead and merge this to stop the failing tests as @alyssawilk is OOO today I think. We can fix any follow ups if she finds anything.
