### PR TITLE
xds: enable the `is_optional` field for HttpFilter

### LINKED ISSUE #15025: allow HTTP filters to be marked as optional
#14982 added new fields to the API to allow HTTP filters to be marked as optional -- i.e., if a filter is not known to a client, the client will ignore that particular filter instead of NACKing the entire config.  gRPC is implementing this now, and we'd like Envoy to have the same behavior.

CC @htuch

### LINKED ISSUE #15770: [xds] Relax the CHECK on factories for typed per-filter config
*Title*: Do not reject the typed per-filter-config if a factory can't be found, remove binaries version coupling.

*Description*:
Right now for the typedConfig in route we demand the factory class to be linked in at Envoy, otherwise it rejects the whole DiscoveryResponse. 
This adds coupling between management server and Envoy, which introduces complexity to rollout/backs of these binaries. 

Let's be more tolerant to such config change. (with a runtime feature flag guard),  similar to Protobuf upgrade.

Instead of throwing an exception, let's do logging and adding stats for such missing factories.

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: xds: enable the `is_optional` field for HttpFilter

Additional Description:
Enable `is_optional` field for `HttpFilter`. The default value is `false`, it will keep the same behavior with the current implementation. The envoy will reject the unsupported HTTP filter, also will reject the unsupported HTTP filter in typed per filter config. When the value is `true`, the unsupported HTTP filter will be ignored by the envoy, also will be ignored by typed per filter config, with a warning log.

Risk Level: low
Testing: unit tests and integration tests are added
Docs Changes: API doc is added
Release Notes: added as new feature
Fixes #15770 
Fixes #15025

### CODE REVIEW

File: source/common/router/config_impl.cc [hunk 1]
```diff
@@ -1522,25 +1537,42 @@ RouteConstSharedPtr ConfigImpl::route(const RouteCallback& cb,
...
-  ProtobufTypes::MessagePtr proto_config = factory.createEmptyRouteConfigProto();
+  ProtobufTypes::MessagePtr proto_config = factory->createEmptyRouteConfigProto();
   Envoy::Config::Utility::translateOpaqueConfig(typed_config, config, validator, *proto_config);
-  return factory.createRouteSpecificFilterConfig(*proto_config, factory_context, validator);
+  auto object = factory->createRouteSpecificFilterConfig(*proto_config, factory_context, validator);
+  if (object == nullptr) {
+    if (Runtime::runtimeFeatureEnabled(
+            "envoy.reloadable_features.check_unsupported_typed_per_filter_config")) {
+      throw EnvoyException(
+          fmt::format("The filter {} doesn't support virtual host-specific configurations", name));
```
Comment (soulxu) [inline source/common/router/config_impl.cc:1560]: Should we ignore the unsupported typed per filter config for the optional http filter also? I assume there will be the same upgrade issue for the new filter. like, the filter added typed per filter config in the new version, the old version can't support it. Although there is a runtime flag here, the is_optional flag feels better.

**Comment by soulxu** [comment]
cc @stevenzzzz @markdroth

File: include/envoy/router/route_config_provider_manager.h [hunk 2]
```diff
@@ -25,6 +25,7 @@ namespace Router {
 class RouteConfigProviderManager {
 public:
   virtual ~RouteConfigProviderManager() = default;
+  using OptionalHttpFilters = std::set<std::string>;
```
Comment (lizan) [inline include/envoy/router/route_config_provider_manager.h:28]: `absl::flat_hash_set`?

Comment (soulxu) [reply include/envoy/router/route_config_provider_manager.h:28]: yea, it can be absl::flat_hash_set, thanks!

File: source/common/config/utility.h [hunk 3]
```diff
@@ -266,6 +266,29 @@ class Utility {
...
 
+  /**
+   * Get a Factory from the registry with a particular name (and templated type) with error checking
+   * to ensure the name and factory are valid.
+   * @param name string identifier for the particular implementation.
+   * @param is_optional exception will be throw when the value is false and no factory found.
+   * @return factory the factory requested or nullptr if it does not exist.
+   */
+  template <class Factory>
+  static Factory* getAndCheckFactoryByName(const std::string& name, bool is_optional) {
```
[the remark this answers is not in the document]
Comment (soulxu) [reply source/common/config/utility.h:277]: I need to return a pointer. The invoker can know whether the factory created successfully or not.

File: source/common/router/config_impl.cc (hunk 1 above)
Comment (markdroth) [reply source/common/router/config_impl.cc:1560]: Yes, I think that if `is_optional` is set, we should ignore unknown per-route filter configs.

File: source/common/config/utility.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (lizan) [reply source/common/config/utility.h:277]: Then refactor the function above to use this one? It's not good to copy the whole code.

File: source/common/router/config_impl.cc (hunk 1 above)
Comment (soulxu) [reply source/common/router/config_impl.cc:1560]: got it, thanks

File: source/common/config/utility.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (soulxu) [reply source/common/config/utility.h:277]: yes, it can be. Let me refractory it, thanks for the feedback!

**Comment by soulxu** [comment]
sorry for the reply late, I will update the PR after the holidays.

**Comment by lizan** [comment]
Can you resolve conflicts? Other than that LGTM

**Comment by soulxu** [comment]
> Can you resolve conflicts? Other than that LGTM

Just resolved, thanks!

**Review by lizan — APPROVED** [review]

**Comment by soulxu** [comment]
@lizan thanks!
