### PR TITLE
Fix least request lb not fair

### LINKED ISSUE #11004: Least requests LB is not fair at edge cases
Least requests LB does independent random pick at every iteration without preserving any knowledge about previous attempts. This leads to unexpected behavior in a few edge cases.

1. In case of low number of backends envoy has increasingly higher chance of picking the same host twice instead of two different ones, which leads to higher chance (as high as 50% in case of 2 backends) to send next request to an instance with more active requests.
2. In some cases full scan is desired (e.g. relatively small amount of backends with strong requirements for utilization), but setting high choice count only wastes cpu without providing any guarantees.

Potential options:
1. For both (1) and (2), alter `LeastRequestLoadBalancer::unweightedHostPick` to preserve knowledge across iterations. It may add more memory usage (`hosts.size() * 8 bytes`) per load balancer instance) but should keep performance otherwise intact.
2. For (2), add new full-scan least requests load balancer.

Relevant Links:
https://github.com/envoyproxy/envoy/blob/0d9f2d59f9cac9dc742e8bcd4588e71e9331f4ac/source/common/upstream/load_balancer_impl.cc#L807-L828

### PR DESCRIPTION
**Pull request by barroca**
Commit Message: Fix Least requests LB when doing a random pick so it removes already chosen hosts from the random function to remove the chance of selecting the same host again when dealing with a small amount of hosts. Also, when the number of choices is smaller or equal the number of hosts, use full scan of least used instead.

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
This Release changes the default behaviour of Least Request Load Balancer doing a full scan when the number of choices is more than equal the size of hosts and also adds a new option on the envoy::extensions::load_balancing_policies::least_request::v3::LeastRequest configuration to always do a full scan. Allowing a full scan instead of random making choices reduces the chance of selecting a host that doesn't have least requests when the number of hosts is smaller.

Platform Specific Features:
[Optional Runtime guard:]
Fixes #11004 
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: source/common/upstream/load_balancer_impl.cc [hunk 1]
```diff
@@ -1299,9 +1299,42 @@ HostConstSharedPtr LeastRequestLoadBalancer::unweightedHostPick(const HostVector
...
+    // so we don't repeat the selection when there are enough hosts.
+    // This will prevent use to choose the same host on our selection since there
+    // is a higher chance of selecting the same host when the number of hosts is
+    // too big.
+    uint32_t last_host_idx = hosts_to_use_current_size - 1;
+    if (hosts_to_use.size() > choice_count_) {
+      --hosts_to_use_current_size;
+
+      hosts->at(rand_idx) = hosts->at(last_host_idx);
+    }
```
Comment (wbpcode) [inline source/common/upstream/load_balancer_impl.cc:1337]: Please don't do this here. Coping whole host list is super expensive.

If we have no much hosts, the full scan should be good enough to resolve the issue in the #11004.
If we have lots of hosts, the ratio to choose same host should be minor.

Current implementation isn't perfect, but it's acceptable. Please leave it like that before we find better way.

File: source/common/upstream/load_balancer_impl.h [hunk 2]
```diff
@@ -690,11 +690,15 @@ class LeastRequestLoadBalancer : public EdfLoadBalancerBase {
             least_request_config.has_value()
                 ? PROTOBUF_GET_WRAPPED_OR_DEFAULT(least_request_config.ref(), choice_count, 2)
                 : 2),
+
```
Comment (wbpcode) [inline source/common/upstream/load_balancer_impl.h:693]: nit: unnecessary change.

File: source/common/upstream/load_balancer_impl.h [hunk 3]
```diff
@@ -690,11 +690,15 @@ class LeastRequestLoadBalancer : public EdfLoadBalancerBase {
...
         active_request_bias_runtime_(
             least_request_config.has_value() && least_request_config->has_active_request_bias()
                 ? absl::optional<Runtime::Double>(
                       {least_request_config->active_request_bias(), runtime})
-                : absl::nullopt) {
+                : absl::nullopt),
+        full_scan_hosts_(least_request_config.has_value()
+                             ? least_request_config->full_scan_hosts().value()
+                             : false) {
```
Comment (wbpcode) [inline source/common/upstream/load_balancer_impl.h:701]: Maybe could use `PROTOBUF_GET_WRAPPED_OR_DEFAULT` here.

File: source/common/upstream/load_balancer_impl.h [hunk 4]
```diff
@@ -709,11 +713,15 @@ class LeastRequestLoadBalancer : public EdfLoadBalancerBase {
...
+
         active_request_bias_runtime_(
             least_request_config.has_active_request_bias()
                 ? absl::optional<Runtime::Double>(
                       {least_request_config.active_request_bias(), runtime})
-                : absl::nullopt) {
+                : absl::nullopt),
+        full_scan_hosts_(least_request_config.has_full_scan_hosts()
+                             ? least_request_config.full_scan_hosts().value()
+                             : false) {
```
Comment (wbpcode) [inline source/common/upstream/load_balancer_impl.h:724]: ditto.

File: test/common/upstream/load_balancer_impl_test.cc [hunk 5]
```diff
@@ -2787,20 +2787,20 @@ TEST_P(LeastRequestLoadBalancerTest, SingleHost) {
...
-    EXPECT_CALL(random_, random()).WillOnce(Return(0)).WillOnce(Return(2)).WillOnce(Return(3));
+    EXPECT_CALL(random_, random()).WillOnce(Return(9999));
     EXPECT_EQ(hostSet().healthy_hosts_[0], lb_.chooseHost(nullptr));
   }
 
   HostVector empty;
   {
     hostSet().runCallbacks(empty, empty);
-    EXPECT_CALL(random_, random()).WillOnce(Return(0)).WillOnce(Return(2)).WillOnce(Return(3));
+    EXPECT_CALL(random_, random()).WillOnce(Return(9999));
```
Comment (wbpcode) [inline test/common/upstream/load_balancer_impl_test.cc:2803]: I didn't get why these change is necessary 🤔

File: api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto [hunk 6]
```diff
@@ -58,4 +59,9 @@ message LeastRequest {
 
   // Configuration for local zone aware load balancing or locality weighted load balancing.
   common.v3.LocalityLbConfig locality_lb_config = 4;
+
+  // Configuration for performing full scan on the list of hosts.
+  // If this configuration is set, when selecting the host a full scan on the list hosts will be
+  // used to select the one with least requests instead of using random choices.
+  google.protobuf.BoolValue full_scan_hosts = 5;
```
Comment (wbpcode) [inline api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto:66]: maybe name it `enable_full_scan`. And it's necessary to tell if the `enable_full_span` is set to true, the `choice_count` will be ignored. I am not sure, but maybe this field and `choice_count` should be in a `oneof` (?). 

cc @lizan

File: api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto [hunk 7]
```diff
@@ -22,6 +22,7 @@ option (udpa.annotations.file_status).package_version_status = ACTIVE;
 // This configuration allows the built-in LEAST_REQUEST LB policy to be configured via the LB policy
 // extension point. See the :ref:`load balancing architecture overview
 // <arch_overview_load_balancing_types>` for more information.
+// [#next-free-field: 6]
 message LeastRequest {
   // The number of random healthy hosts from which the host with the fewest active requests will
   // be chosen. Defaults to 2 so that we perform two-choice selection if the field is not set.
```
Comment (wbpcode) [inline api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto:28]: This PR change the behavior of the LB. It's necessary to add some more comment to tell that if the `choice_count` is larger than or equal to the hosts size, a full scan will be used.

**Review by wbpcode — CHANGES_REQUESTED** [review]
Thanks for your contribution. And some comments are added.

And at least a release note is necessary to tell what this PR changed or fixed. You can add a new change log entry in this file. https://github.com/envoyproxy/envoy/blob/main/changelogs/current.yaml

File: api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto (hunk 7 above)
Comment (wbpcode) [reply api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto:28]: This behavior change should be harmless to end users and maybe make the LB's behavior closer to it's name `least request`. 
So, I think a change log should enough rather than a runtime guard.

But still need a check from @envoyproxy/runtime-guard-changes

File: api/envoy/config/cluster/v3/cluster.proto [hunk 8]
```diff
@@ -476,6 +476,11 @@ message Cluster {
     // Configuration for slow start mode.
     // If this configuration is not set, slow start will not be not enabled.
     SlowStartConfig slow_start_config = 3;
+
+    // Configuration for performing full scan on the list of hosts.
+    // If this configuration is set, when selecting the host a full scan on the list hosts will be
+    // used to select the one with least requests instead of using random choices.
+    google.protobuf.BoolValue full_scan_hosts = 4;
```
[the remark this answers is not in the document]
Comment (barroca) [reply api/envoy/config/cluster/v3/cluster.proto]: I'm not 100% sure how to do this on the code, when removing the field from here I was having problems compiling the load_balancer_impl.* files. I would appreciate help on this.

File: source/common/upstream/load_balancer_impl.cc (hunk 1 above)
Comment (barroca) [reply source/common/upstream/load_balancer_impl.cc]: Makes sense, I've changed the code to do full scan or keep the old behaviour.

File: test/common/upstream/load_balancer_impl_test.cc (hunk 5 above)
Comment (barroca) [reply test/common/upstream/load_balancer_impl_test.cc]: Doesn't make sense to change to 9999, but the number of calls for random have changed since we will call full scan instead.

File: api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto (hunk 6 above)
Comment (barroca) [reply api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto]: Changed to be enable_full_scan instead.

File: source/common/upstream/load_balancer_impl.h [hunk 9]
```diff
@@ -694,7 +694,9 @@ class LeastRequestLoadBalancer : public EdfLoadBalancerBase {
             least_request_config.has_value() && least_request_config->has_active_request_bias()
                 ? absl::optional<Runtime::Double>(
                       {least_request_config->active_request_bias(), runtime})
-                : absl::nullopt) {
+                : absl::nullopt),
+        enable_full_scan_(
+            PROTOBUF_GET_WRAPPED_OR_DEFAULT(least_request_config.ref(), enable_full_scan, false)) {
```
Comment (wbpcode) [inline source/common/upstream/load_balancer_impl.h:699]: > I'm not 100% sure how to do this on the code, when removing the field from here I was having problems compiling the load_balancer_impl.* files. I would appreciate help on this.

Just keep this `enable_full_scan_` always be false if legacy API is used. Then I think this will resolve the compiling problem.

/wait

File: source/common/upstream/load_balancer_impl.h [hunk 10]
```diff
@@ -749,6 +752,7 @@ class LeastRequestLoadBalancer : public EdfLoadBalancerBase {
   double active_request_bias_{};
 
   const absl::optional<Runtime::Double> active_request_bias_runtime_;
+  const bool enable_full_scan_;
```
Comment (wbpcode) [inline source/common/upstream/load_balancer_impl.h:755]: nit: `const bool enable_full_scan_{};`

**Review by wbpcode — COMMENTED** [review]
This LGTM overall. Please check the CI and add a release note, thanks.

File: test/integration/http_subset_lb_integration_test.cc [hunk 11]
```diff
@@ -176,7 +176,10 @@ class HttpSubsetLbIntegrationTest
       }
     }
 
-    if (is_hash_lb_) {
+    // The default number of choices for the LEAST_REQUEST policy is 2 hosts, if the number of hosts
+    // is equal to the number of choices, a full scan happens instead, this means that the same host
+    // will be chosen.
+    if (is_hash_lb_ || (GetParam() == envoy::config::cluster::v3::Cluster::LEAST_REQUEST)) {
```
Comment (barroca) [inline test/integration/http_subset_lb_integration_test.cc:182]: If there is an way of checking the number of hosts of the cluster so we can make sure the test has the correct behaviour that would be great, for now I added a comment on why we need this check on the test here.

**Review by wbpcode — DISMISSED** [review]
LGTM. Thanks.

**Comment by wbpcode** [comment]
Please merge main and add a release note. Then we can land this. Thanks.

/wait

File: changelogs/current.yaml [hunk 12]
```diff
@@ -20,5 +25,9 @@ removed_config_or_runtime:
 # *Normally occurs at the end of the* :ref:`deprecation period <deprecated>`
 
 new_features:
+- area: upstream
+  change: |
+    Adds the option enable_full_scan on envoy.extensions.load_balancing_policies.least_request.v3.LeastRequest
+    so instead of using the choice_count to choose the hosts, we do a full scan on this list of hosts.
```
Comment (wbpcode) [inline changelogs/current.yaml:31]:
```
Added :ref: `enable full scan option 
<envoy_v3_api_field_extensions.load_balancing_policies.least_request.v3.LeastRequest.enable_full_scan>`
to least request load balancer. If it is set to true, Envoy will do a full scan on the list of hosts rather than using
`choice_count
<envoy_v3_api_field_extensions. load_balancing_policies.least_request.v3.LeastRequest.choice_count>`.
```

I am not a native speaker, so you can also check the grammar by chatgpt or similiar API tools.

/wait

**Review by wbpcode — CHANGES_REQUESTED** [review]
Last nit comment to the release note. Only last step, then I can lant this great patch. Thanks.

**Review by wbpcode — DISMISSED** [review]
LGTM. Thanks.

**Comment by barroca** [comment]
Not sure If I need someone else to approve since "envoyproxy/api-shepherds must approve for any API change" is pending.

**Comment by barroca** [comment]
perhaps @lizan needs to take a look again?

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.

**Comment by kyessenov** [comment]
We are reverting this change since we noticed that there is a significant impact on hosts with a small number of hosts caused by the deterministic loop which makes every client pick the same hosts. I think we need a better understanding of the impact with a load simulation for this change to be re-applied. Please consider adding some independent sampling to the algorithm and we can do a more thorough review again.

**Comment by barroca** [comment]
I understand that changing the behaviour would have impacted people, but It is not clear to me that adding an option to enable full scan would have a bad impact since it is explicitly selecting the host with least requests. Wondering if we can put add it back?

**Comment by wbpcode** [comment]
The API will be kept and new implementation is still welcome. And @tonya11en is working a simulated system to ensure we can get a more reasonable implementation in the future.

Thanks for your contribution and so sorry for that we need to revert it. We know it taken you lots of time. :(

Hope we can bring it back soon.

**Comment by tonya11en** [comment]
If the patch is limited to only the “full scan” flag, it should do what you want without affecting the existing selection behavior.

**Comment by barroca** [comment]
Hello, I have this PR open that changes the behaviour for a random index: https://github.com/envoyproxy/envoy/pull/31146
