### PR TITLE
lint: All text files for general formatting

### LINKED ISSUE #15442: Improve general text file linting
### description

there are some rules that we probably want to apply to all *text* files (maybe with some specific exceptions)

for example:

- new line at the end of file
- no mixture of tabs and spaces (maybe just no tabs)

there may be others

most lang linters will pick up these issues - but eg yaml files are failing this and we could/should just make a general rule

we probs only want to lint changes i guess rather than checking entire repo on every change

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: lint: All text files for general formatting
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #15442 
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
cc @mattklein123 @htuch 

this is a first attempt at a script to cleanup text/code files in the repo that have language-independent linting issues

so far it does not:

- allow exceptions
- automate a fix
- fix the files

File: tools/code_format/glint.sh [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+for file in $(find_text_files); do
+    check_new_line "$file"
+    check_mixed_tabs_spaces "$file"
+    check_trailing_whitespace "$file"
+done
+
+if [[ -n "$ERRORS" ]]; then
+    echo
+    echo "ERRORS found"
```
Comment (phlax) [inline tools/code_format/glint.sh:48]: echo to stderr

File: tools/code_format/glint.sh [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+    echo "$MISSING_NEWLINE files with missing newline found"
```
Comment (phlax) [inline tools/code_format/glint.sh:49]: remove ...found

File: tools/code_format/glint.sh [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+MIXED_TABS_AND_SPACES=0
+TRAILING_WHITESPACE=0
+
+
+check_mixed_tabs_spaces () {
+    local spaced tabbed
+    tabbed=$(grep -ce '^\t' "$1")
+    spaced=$(grep -ce '^ ' "$1")
+    if [[ $tabbed -gt 0 ]] && [[ $spaced -gt 0 ]]; then
+	echo "mixed tabs and spaces: '$1'"
```
Comment (phlax) [inline tools/code_format/glint.sh:14]: get rid of superfluous `'` - same below

**Comment by phlax** [comment]
just looking at autofix - to automate `untabify` it will require hard-coding what the indentation should be

**Comment by phlax** [comment]
re untabify - this situation is made worse as `.sh` scripts currently use a mix of indents sometimes within the same file

my vote is defo to use 4-space indents but im struggling to find anything (reliable) that will properly lint indents in shell scripts (no matter what the number of spaces is)

**Comment by htuch** [comment]
@phlax I'd probably prefer Python here TBH. Bash becomes hard to write if we want to extend it.

**Comment by phlax** [comment]
ill have a look at reimplementing in python.

my concern is that it will make it much slower and probs require quite a bit more code. Also some of the things (like finding the text files) are going to be much harder to implement in python (bash still has some uses 8/) so we may end up with the ~same bash lines just wrapped in python

**Comment by htuch** [comment]
I think `pathlib` globbing is pretty good for this. But, I agree on performance. I guess my question is how complex do we anticipate this growing? The current level of complexity is fine and somewhat maintainable. I would hate to see something that reached 2x the size though..

**Comment by phlax** [comment]
> I think pathlib globbing is pretty good for this. 

its not the globbing thats the issue - its easy enough to find and filter files - this is using *git* to filter what it sees as a "text" file

File: tools/code_format/glint.sh [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+check_trailing_whitespace () {
+    if grep -r '[[:blank:]]$' "$1" > /dev/null; then
+	echo "trailing whitespace: ${1}"
+	ERRORS=yes
+	((TRAILING_WHITESPACE=TRAILING_WHITESPACE+1))
+    fi
+}
+
+find_text_files () {
+    git grep --cached -Il ''
```
Comment (phlax) [inline tools/code_format/glint.sh:37]: this bit

File: tools/code_format/glint.sh [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+    spaced=$(grep -ce '^ ' "$1")
+    if [[ $tabbed -gt 0 ]] && [[ $spaced -gt 0 ]]; then
+	echo "mixed tabs and spaces: ${1}"
+	ERRORS=yes
+	((MIXED_TABS_AND_SPACES=MIXED_TABS_AND_SPACES+1))
+    fi
+}
+
+check_new_line () {
+    test "$(tail -c 1 "$1" | wc -l)" -eq 0 && {
```
Comment (phlax) [inline tools/code_format/glint.sh:21]: and this - its using a kinda bash trick to make sure that there is a new line - regardless of what type of new line it is

File: test/extensions/transport_sockets/tls/test_data/ticket_key_a [hunk 6]
```diff
@@ -1 +1 @@
-�p���	Z�D��	=+;MJ��^k|8Ĵ��f`�A���gy��㌰�{��F�Դ�����烗�v�'�N[����p
```
Comment (phlax) [inline test/extensions/transport_sockets/tls/test_data/ticket_key_a:1]: i think these should probs be excluded

File: .azure-pipelines/pipelines.yml [hunk 7]
```diff
@@ -26,6 +26,7 @@ stages:
               BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
               GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)
             displayName: "Run format pre-checks"
+            continueOnError: true
```
Comment (phlax) [inline .azure-pipelines/pipelines.yml:29]: remove

**Review by davinci26 — COMMENTED** [review]
+1 to write it with python because it would help with having cross platform tooling

**Comment by phlax** [comment]
> +1 to write it with python because it would help with having cross platform tooling

apologies - the conversation continued in slack - and for the reason that bash really is the best tool for these it has been done this way for now

using python would add a huge amount of complexity and depending on how much complexity was added would potentially be a lot slower

**Comment by phlax** [comment]
also at very least (without a lot of working around) it would need to include a github dependency - so it would require a lot more of users (ie python + github)

File: tools/code_format/glint.sh [hunk 8]
```diff
@@ -0,0 +1,55 @@
+#!/bin/bash
+
+NOLINT_RE="\.patch$|^test/server/server_corpus/clusterfuzz|test/extensions/transport_sockets/tls/test_data/password_protected_password.txt$|Whitespace.txt$|WhiteSpace.txt$"
```
Comment (phlax) [inline tools/code_format/glint.sh:3]: @justin-mp do you know if the trailing whitespace is necessary for these tests' data (ie not all of the ws)

Comment (phlax) [reply tools/code_format/glint.sh:3]: re these `Whitespace.txt$|WhiteSpace.txt$"`

File: test/server/server_corpus/clusterfuzz-testcase-minimized-server_fuzz_test-5632902623657984 [hunk 9]
```diff
@@ -1 +1 @@
-static_resources {   clusters {     name: " "     connect_timeout {       nanos: 6     }     hosts {       pipe {         path: " "       }     }     health_checks {       timeout {         nanos: 6       }       interval {         nanos: 6       }       unhealthy_threshold {       }       healthy_threshold {       }       tcp_health_check {       }     }   } } cluster_manager {   upstream_bind_config {     source_address {       address: "0.0.0.0"       port_value: 0     }     freebind {       value: true     }   } } admin {   address {     pipe {       path: " "     }   } } 
+static_resources {   clusters {     name: " "     connect_timeout {       nanos: 6     }     hosts {       pipe {         path: " "       }     }     health_checks {       timeout {         nanos: 6       }       interval {         nanos: 6       }       unhealthy_threshold {       }       healthy_threshold {       }       tcp_health_check {       }     }   } } cluster_manager {   upstream_bind_config {     source_address {       address: "0.0.0.0"       port_value: 0     }     freebind {       value: true     }   } } admin {   address {     pipe {       path: " "     }   } }
```
Comment (phlax) [inline test/server/server_corpus/clusterfuzz-testcase-minimized-server_fuzz_test-5632902623657984:1]: @asraa am i correct that its okay to remove the trailing whitespace from these fuzz test data files ?

File: tools/code_format/glint.sh (hunk 8 above)
Comment (justin-mp) [reply tools/code_format/glint.sh]: All of the trailing whitespace in `test/extensions/filters/http/cdn_loop/parser_corpus` is intentional since there are weird edge cases that the parser is trying to get at.  (Some of them, for example, are even in the RFC!)

Comment (phlax) [reply tools/code_format/glint.sh]: ok - ill revert this dir and exclude

Comment (phlax) [reply tools/code_format/glint.sh]: thanks @justin-mp

File: test/server/server_corpus/clusterfuzz-testcase-minimized-server_fuzz_test-5632902623657984 (hunk 9 above)
Comment (phlax) [reply test/server/server_corpus/clusterfuzz-testcase-minimized-server_fuzz_test-5632902623657984:1]: nm - i have excluded all of the `*_corpus/*` files from linting

**Comment by phlax** [comment]
@mattklein123 this should be ready for final review hopefully

i have excluded all of the `*_corpus/` folders so hopefully this doesnt mess with any test data that it shouldnt

current exclude is

```bash
 NOLINT_RE="\.patch$|^test/.*_corpus/|^tools/.*_corpus/|password_protected_password.txt"
```

File: tools/code_format/glint.sh [hunk 10]
```diff
@@ -0,0 +1,55 @@
+#!/bin/bash
```
Comment (mattklein123) [inline tools/code_format/glint.sh:1]: Can you add a human readable comment on the top of each function just to make it clear what is being checked for? Also, do you plan on having an auto fix version? I think this will probably annoy people if we don't auto fix at least the whitespace issues?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Very nice, thanks. Just some small comments.

/wait

File: tools/code_format/glint.sh (hunk 10 above)
Comment (phlax) [reply tools/code_format/glint.sh:1]: the problem is the tabs - theres not an easy way of knowing what it should be - editors know

for the other whitespace issues - yep thats easy - can we do in a follow up ?

Comment (mattklein123) [reply tools/code_format/glint.sh:1]: Sure, can you add the comments to the formatter so it's clear what it's doing when people get an error and look at the file?

Comment (phlax) [reply tools/code_format/glint.sh:1]: ticket added re autofix - and comments added here

**Review by mattklein123 — APPROVED** [review]
Thanks!
