### PR TITLE
http: check virtual host-specific typed per filter config

### LINKED ISSUE #15043: api: Envoy should NACK typed_per_filter_config entries for filters that don't support override configs
Currently, if an HTTP filter registers a given config type as its top-level config in the HCM filter list, and Envoy receives a RouteConfiguration that has a message of that config type in a `typed_per_filter_config` map, it will ignore that entry instead of NACKing the config, even though that config will never be used.  This seems like it's silently ignoring an error that could cause confusion for users, because they might think that they're overriding something that can't actually be overridden, and they're not getting any error to tell them it's not working.

I think this can probably be done by changing [`NamedHttpFilterConfigFactory::createRouteSpecificFilterConfig()`](https://github.com/envoyproxy/envoy/blob/f174fba476a921efb981e80c346faf7e6723c0c4/include/envoy/server/filter_config.h#L193) to throw an exception instead of returning null.  That way, any filter that overrides that method to actually parse the relevant config type will allow the config to be parsed, but any filter that doesn't will reject an override config.

CC @htuch

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: http: check virtual host-specific typed per filter config
Additional Description:
When filter doesn't support virtual host-specific typed per filter config,
the envoy should reject any per filter config for that filter.

Also, adds new runtime config `envoy.reloadable_features.check_unsupported_typed_per_filter_config`
for backward-compatible. The default value is true, only when the value is true,
the check will be executed.

Risk Level: low
Testing: unit test added
Docs Changes: n/a
Release Notes: note new feature
Runtime guard: envoy.reloadable_features.check_unsupported_typed_per_filter_config
Fixes #15043

Signed-off-by: He Jie Xu <hejie.xu@intel.com>

### CODE REVIEW

File: source/extensions/filters/http/common/factory_base.h [hunk 1]
```diff
@@ -55,6 +58,11 @@ class FactoryBase : public Server::Configuration::NamedHttpFilterConfigFactory {
   createRouteSpecificFilterConfigTyped(const RouteConfigProto&,
                                        Server::Configuration::ServerFactoryContext&,
                                        ProtobufMessage::ValidationVisitor&) {
+    if (Runtime::runtimeFeatureEnabled(
+            "envoy.reloadable_features.check_unsupported_typed_per_filter_config")) {
+      throw EnvoyException(fmt::format(
+          "The filter {} doesn't support virtual host-specific configurations", name()));
+    }
```
Comment (dmitri-d) [inline source/extensions/filters/http/common/factory_base.h:65]: Logging a warning here might be useful here to draw attention to a configuration that needs to be fixed.

File: test/extensions/filters/http/common/factory_base_test.cc [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+namespace Common {
+namespace {
+
+class FakeFilterFactory
+    : public FactoryBase<test::extensions::filters::http::common::FakeFilterConfig> {
+public:
+  FakeFilterFactory() : FactoryBase("test") {}
+
+private:
+  virtual Http::FilterFactoryCb createFilterFactoryFromProtoTyped(
```
Comment (dmitri-d) [inline test/extensions/filters/http/common/factory_base_test.cc:25]: nit: `virtual` isn't needed here, as the method has been declared as an `override`

File: source/extensions/filters/http/common/factory_base.h (hunk 1 above)
Comment (soulxu) [reply source/extensions/filters/http/common/factory_base.h:65]: got it, thanks!

File: tools/code_format/check_format.py [hunk 3]
```diff
@@ -114,7 +114,8 @@
 # Header files that can throw exceptions. These should be limited; the only
 # valid situation identified so far is template functions used for config
 # processing.
-EXCEPTION_ALLOWLIST = ("./source/common/config/utility.h")
+EXCEPTION_ALLOWLIST = ("./source/common/config/utility.h",
+                       "./source/extensions/filters/http/common/factory_base.h")
```
Comment (antoniovicente) [inline tools/code_format/check_format.py:118]: @ahedberg @htuch 

We may have some problems here depending on the intent behind this check.  It seems to me that headers in this list may need to be restricted so they are not included from other headers in other to prevent multiple definitions in builds that partially disable exceptions at a per-library basis. That said, there seems to be no restrictions in place that control where source/common/config/utility.h is included from or the use of those functions in header files.

This PR introduces an exception that is thrown from a base class method of a class that seems to be widely used.  I think this change could break compilation of libraries that disable exceptions.

File: source/common/runtime/runtime_features.cc [hunk 4]
```diff
@@ -110,6 +110,8 @@ constexpr const char* disabled_runtime_features[] = {
     "envoy.reloadable_features.remove_legacy_json",
     // Sentinel and test flag.
     "envoy.reloadable_features.test_feature_false",
+    // Reject virtual host-specific configuration when filter doesn't support it.
+    "envoy.reloadable_features.check_unsupported_typed_per_filter_config",
```
Comment (antoniovicente) [inline source/common/runtime/runtime_features.cc:114]: My understanding is that runtime features should default to true.  They provide a way for devs affected by a breaking change to temporarily rollback the behavior.  Once we have given time to find and address all the breakages, we'll remove the runtime feature checks and only keep the new behavior.

Out of curiosity, are there any existing tests that fail when this runtime feature is enabled?

File: test/extensions/filters/http/common/factory_base_test.cc [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+               EnvoyException);
+}
+
+TEST(FactoryBaseTest, TestAcceptUnsupportedTypedFilterConfig) {
+  FakeFilterFactory factory;
+  NiceMock<Server::Configuration::MockServerFactoryContext> context;
+  ProtobufTypes::MessagePtr config = factory.createEmptyRouteConfigProto();
+
+  EXPECT_EQ(nullptr, factory.createRouteSpecificFilterConfig(
+                         *config, context, ProtobufMessage::getNullValidationVisitor()));
```
Comment (antoniovicente) [inline test/extensions/filters/http/common/factory_base_test.cc:51]: It would be good to have some e2e integration tests that cover this functionality.  I don't know exactly what existing types would fail config load if you tried to provide per-route config for them.  It seems that Envoy::Extensions::HttpFilters::HealthCheck::HealthCheckFilterConfig doesn't implement an override for createRouteSpecificFilterConfigTyped, perhaps that is a good extension to write a test against?

File: source/extensions/filters/http/common/factory_base.h [hunk 6]
```diff
@@ -55,6 +58,16 @@ class FactoryBase : public Server::Configuration::NamedHttpFilterConfigFactory {
...
+    ENVOY_LOG(warn,
+              "The filter {} doesn't support virtual host-specific configurations. Set runtime "
+              "config `envoy.reloadable_features.check_unsupported_typed_per_filter_config` as "
+              "true to reject any invalid virtual-host specific configuration.",
+              name())
```
Comment (antoniovicente) [inline source/extensions/filters/http/common/factory_base.h:70]: The continuous integration test run detected a build breakage on this line due to missing ; at the end of the line.

**Review by antoniovicente — COMMENTED** [review]
Welcome to Envoy and thanks for the improvement to config validation.  I'm not that familiar with all the interactions between config components and object factories, so hopefully @htuch can help fill in my gaps in understanding.

File: tools/code_format/check_format.py (hunk 3 above)
Comment (soulxu) [reply tools/code_format/check_format.py:118]: Another option is we can fix it here https://github.com/envoyproxy/envoy/blob/b23ee3b438050228b7c7b0097d182ac828fa2247/source/common/router/config_impl.cc#L1492-L1502

File: source/common/runtime/runtime_features.cc (hunk 4 above)
Comment (soulxu) [reply source/common/runtime/runtime_features.cc:114]: > My understanding is that runtime features should default to true. They provide a way for devs affected by a breaking change to temporarily rollback the behavior. Once we have given time to find and address all the breakages, we'll remove the runtime feature checks and only keep the new behavior.


As `https://github.com/envoyproxy/envoy/issues/15043#issuecomment-778703531` said, I thought we should set ti as false default, then it won't break existing user. But I may miss understanding that.


> Out of curiosity, are there any existing tests that fail when this runtime feature is enabled?

I tested with the default value is true. In my env, only get one test failed 'IoSocketHandleImplIntegration.LastRoundTripIntegrationTest', I don't think it is related.

File: test/extensions/filters/http/common/factory_base_test.cc (hunk 5 above)
Comment (soulxu) [reply test/extensions/filters/http/common/factory_base_test.cc:51]: Yea, `HealthCheckFilterConfig` doesn't implement override, let me add integration tests.

File: source/extensions/filters/http/common/factory_base.h (hunk 6 above)
Comment (soulxu) [reply source/extensions/filters/http/common/factory_base.h:70]: thanks

File: tools/code_format/check_format.py (hunk 3 above)
Comment (ahedberg) [reply tools/code_format/check_format.py:118]: If we decide to have `createRouteSpecificFilterConfigTyped` throw an exception, the `throw` statement should be in the .cc file instead of the .h file. Then we don't need to add it to the exception allowlist.

Comment (antoniovicente) [reply tools/code_format/check_format.py:118]: FactoryBase is a template class, the throw can't be moved to a cc file (well, except possibly by adding a helper function)

Returning null and doing the validation in config_impl.cc seems attractive.  Is that the only place where this factory method is called from?

Comment (soulxu) [reply tools/code_format/check_format.py:118]: > Returning null and doing the validation in config_impl.cc seems attractive. Is that the only place where this factory method is called from?

Yes, that is the only place I found at least.

File: source/common/runtime/runtime_features.cc (hunk 4 above)
Comment (antoniovicente) [reply source/common/runtime/runtime_features.cc:114]: cc @htuch

Having the runtime flag so affected devs can disable the functionality while they fixed their config should be enough.  I think that the default should be true.

And I agree that the 'IoSocketHandleImplIntegration.LastRoundTripIntegrationTest' failure is not related to this change.  That's a non-hermetic test that does network communication.  I think I'll file an issue about it.

Comment (htuch) [reply source/common/runtime/runtime_features.cc:114]: I think default true is fine, as long as we have the runtime for now.

File: tools/code_format/check_format.py (hunk 3 above)
Comment (htuch) [reply tools/code_format/check_format.py:118]: I think `config_impl.cc` is more robust in any case, since regardless of inheritance hierarchy, if there is no config, we can fire the exception.

**Review by htuch — COMMENTED** [review]
Thanks for taking this on!

**Comment by htuch** [comment]
@markdroth does this match your intended behavior?

File: tools/code_format/check_format.py (hunk 3 above)
Comment (antoniovicente) [reply tools/code_format/check_format.py:118]: It would be really helpful to some of us if exceptions were only thrown from cc files.  Could you do the new config validation in config_impl.cc instead of the template factory class?

File: source/common/runtime/runtime_features.cc (hunk 4 above)
Comment (antoniovicente) [reply source/common/runtime/runtime_features.cc:114]: cc @htuch

Having the runtime flag so affected devs can disable the functionality while they fixed their config should be enough.  I think that the default should be true.

And I agree that the 'IoSocketHandleImplIntegration.LastRoundTripIntegrationTest' failure is not related to this change.  That's a non-hermetic test that does network communication.  I think I'll file an issue about it.

Comment (soulxu) [reply source/common/runtime/runtime_features.cc:114]: let me change the default value as true, thanks.

File: tools/code_format/check_format.py (hunk 3 above)
Comment (soulxu) [reply tools/code_format/check_format.py:118]: Yes, I will update, thanks for the feedback!

**Comment by markdroth** [comment]
Yes, this looks right to me.  Thanks for doing this!

File: source/extensions/filters/http/common/factory_base.h (hunk 6 above)
Comment (antoniovicente) [reply source/extensions/filters/http/common/factory_base.h:70]: /wait

Build still looks broken.  Did you implement a fix but didn't "git push" it out?

**Comment by antoniovicente** [comment]
/wait

Please look into the build breakages.

**Comment by soulxu** [comment]
thanks for all the review! let me work on the update.

**Review by htuch — APPROVED** [review]
LGTM, thanks!
