### PR TITLE
admin: call listen in tests to verify behavior of SO_REUSEPORT

### LINKED ISSUE #7636: ServerInstanceImplTest.BootstrapNodeWithSocketOptions fails in certain environment
*Description*:

The test added #7562 fails in my local env (Debian stretch with Clang-8), error log:

```
[ RUN      ] IpVersions/ServerInstanceImplTest.BootstrapNodeWithSocketOptions/IPv4
test/server/server_test.cc:576: Failure
Failed
Exception should take place. It did not.
[  FAILED  ] IpVersions/ServerInstanceImplTest.BootstrapNodeWithSocketOptions/IPv4, where GetParam() = 4-byte object <00-00 00-00> (50 ms)
[ RUN      ] IpVersions/ServerInstanceImplTest.BootstrapNodeWithSocketOptions/IPv6
test/server/server_test.cc:576: Failure
Failed
Exception should take place. It did not.
[  FAILED  ] IpVersions/ServerInstanceImplTest.BootstrapNodeWithSocketOptions/IPv6, where GetParam() = 4-byte object <01-00 00-00> (23 ms)
```

It does fail regardless whether I build/run this test in build container (i.e. via `ci/run_envoy_docker.sh`) or not, so I guess this is somewhat related to kernel or its config. Just FYI the kernel version is `4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`. Any idea? @euroelessar

### PR DESCRIPTION
**Pull request by euroelessar**
Description: In some cases `bind` call may succeed, so verify by calling `listen` as well.
Risk Level: LOW
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Fixes #7636

### CODE REVIEW

File: test/server/server_test.cc [hunk 1]
```diff
@@ -568,17 +568,29 @@ TEST_P(ServerInstanceImplTest, BootstrapNodeWithoutAccessLog) {
...
+} // namespace
+
 // Test that `socket_options` field in an Admin proto is honored.
 TEST_P(ServerInstanceImplTest, BootstrapNodeWithSocketOptions) {
   ASSERT_NO_THROW(initialize("test/server/node_bootstrap_with_admin_socket_options.yaml"));
   const auto address = server_->admin().socket().localAddress();
-  EXPECT_THAT_THROWS_MESSAGE(std::make_unique<Network::TcpListenSocket>(address, nullptr, true),
-                             EnvoyException, HasSubstr("Address already in use"));
+  EXPECT_THAT_THROWS_MESSAGE(bindAndListenTcpSocket(address, nullptr), EnvoyException,
+                             HasSubstr("Address already in use"));
```
Comment (zuercher) [inline test/server/server_test.cc]: Oh, one question -- Is the purpose of this change to allow the test to pass on when the kernel allows the bind without SO_REUSEPORT? Because it seems to me that in that case `bindAndListenTcpSocket` will throw an exception with "cannot listen" and the errno and the test will still fail.

Comment (zuercher) [reply test/server/server_test.cc]: That all makes sense except the last part. It seems to me that the exception message will not be "Address already in use" and so the test will fail.

Comment (euroelessar) [reply test/server/server_test.cc]: I'll double check, but my expectation is that `strerror` should convert EADDRINUSE error number to "Address already in use" text

Comment (euroelessar) [reply test/server/server_test.cc]: Updated the code to verify `errno` directly + added comments about the intent.
Does it help?

Comment (zuercher) [reply test/server/server_test.cc]: You're right, I was reading the original EXPECT_THROW_HAS_MESSAGE line incorrectly the whole time. It was fine. The new version is very explicit about the error number, which is probably good since I'm not sure those error messages are necessarily the same across operating systems.

File: test/server/server_test.cc [hunk 2]
```diff
@@ -568,17 +568,41 @@ TEST_P(ServerInstanceImplTest, BootstrapNodeWithoutAccessLog) {
...
 TEST_P(ServerInstanceImplTest, BootstrapNodeWithSocketOptions) {
+  // Start Envoy instance with admin port with SO_REUSEPORT option.
   ASSERT_NO_THROW(initialize("test/server/node_bootstrap_with_admin_socket_options.yaml"));
   const auto address = server_->admin().socket().localAddress();
-  EXPECT_THAT_THROWS_MESSAGE(std::make_unique<Network::TcpListenSocket>(address, nullptr, true),
-                             EnvoyException, HasSubstr("Address already in use"));
+
+  // First attempt to bind and listen socket should fail due to the lack of SO_REUSEPORT socket
+  // options.
+  try {
```
Comment (mattklein123) [inline test/server/server_test.cc]: nit: can you use EXPECT_THROW_WITH_MESSAGE here?

Comment (euroelessar) [reply test/server/server_test.cc]: I can try to do smth like `EXPECT_THROW_WITH_MESSAGE(bindAndListenTcpSocket(address, nullptr), strerror(EADDRINUSE))`, would it be clear enough?

Comment (mattklein123) [reply test/server/server_test.cc]: Yes any variant of that is fine, there is also a regex version. Basically just trying to avoid re-implementing the construct.
