### PR TITLE
retry: retry immediately on 425 response code and H3 stream reset

### LINKED ISSUE #19423: Post-handshake HTTP/3 errors should result in fallback to TCP
When an HTTP/3 connection encounters errors after the handshake completes there is no longer a TCP vs QUIC race running and the request can not fallback to TCP. The retry should happen up at the HTTP layer, and should result in HTTP/3 being marked as "broken" if the fallback just ends up succeeding.

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: implement retry on 425 response code and configurable retry on HTTP/3 post-handshake stream reset without timed backoff. 
Automatically configure retry policy for a 0-RTT safe request if its upstream might be over H3  with retry on 425 response code. The retried request shouldn't be sent as early data. (We don't sent early data right now anyway.)
And add retry-on`http3-post-connect-failure`. If configured and the H3 upstream request was sent over a conn pool supporting TCP fallback, the request will be retried upon stream reset and the retrial shouldn't be sent using HTTP/3. This config can be used to mitigate request reset due to upstream HTTP/3 being broken. No effect if the conn pool is a TCP pool or H/3 pool which doesn't support TCP fallback.
Also change retry state impl to automatically retry HTTP/3 0-RTT request if the connect failed and the cluster is configured to support TCP fallback. (We are not sending 0-RTT request right now.)

Additional Description: add new struct StreamOptions to Http::ConnectionPool::Instance::newStream() interface, and plumbing it from router filter.

Risk Level: medium, behavior change to retry logic and conn pool.
Testing: added unit tests and integration tests
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
Runtime guard: envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc
Fixes #19423
Part of #18715

### CODE REVIEW

**Comment by jmarantz** [comment]
Can you fix format? Thanks :)

File: source/common/http/conn_pool_base.cc [hunk 1]
```diff
@@ -58,22 +58,32 @@ HttpConnPoolImplBase::~HttpConnPoolImplBase() { destructAllConnections(); }
...
 ConnectionPool::Cancellable*
 HttpConnPoolImplBase::newStream(Http::ResponseDecoder& response_decoder,
-                                Http::ConnectionPool::Callbacks& callbacks) {
+                                Http::ConnectionPool::Callbacks& callbacks, bool has_early_data,
+                                bool should_use_alt_svc) {
   HttpAttachContext context({&response_decoder, &callbacks});
-  return newStreamImpl(context);
+  if (Runtime::runtimeFeatureEnabled(
+          "envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc") &&
+      !should_use_alt_svc && onlySupportsAltSvc()) {
```
Comment (RyanTheOptimist) [inline source/common/http/conn_pool_base.cc:66]: nit: maybe "isAlternateProtocol()" would be better than "onlySupportsAltSvc()"? what do you think?

File: source/common/http/conn_pool_grid.cc [hunk 2]
```diff
@@ -17,11 +17,20 @@ absl::string_view describePool(const ConnectionPool::Instance& pool) {
...
     : grid_(grid), decoder_(decoder), inner_callbacks_(&callbacks),
       next_attempt_timer_(
           grid_.dispatcher_.createTimer([this]() -> void { tryAnotherConnection(); })),
-      current_(pool_it) {}
+      current_(pool_it), has_early_data_(has_early_data), should_use_alt_svc_(should_use_alt_svc) {
+  if (Runtime::runtimeFeatureEnabled(
+          "envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc") &&
+      !should_use_alt_svc) {
+    // If alt_svc is explicitly disabled, there must have been a failed request over Http3 and the
+    // failure must be post-handshake.
```
Comment (RyanTheOptimist) [inline source/common/http/conn_pool_grid.cc:30]: This comment accurately describes why should_use_alt_svc might be true but it's just before a line of code which disables http3 for this request. So how about adding a sentence like "So disable HTTP/3 for this request." to the comment?

File: source/common/router/retry_state_impl.cc [hunk 3]
```diff
@@ -225,17 +226,21 @@ RetryStateImpl::parseResetInterval(const Http::ResponseHeaderMap& response_heade
 }
 
 void RetryStateImpl::resetRetry() {
-  if (callback_) {
+  if (backoff_callback_) {
```
Comment (RyanTheOptimist) [inline source/common/router/retry_state_impl.cc:229]: Should this be "!= nullptr" (or perhaps the one below should just be "if (!next_loop_callback_)" so they're consistent.

File: source/common/router/retry_state_impl.cc [hunk 4]
```diff
@@ -313,47 +335,63 @@ RetryStatus RetryStateImpl::shouldHedgeRetryPerTryTimeout(DoRetryCallback callba
...
-        return true;
+      uint32_t status_code = Http::Utility::getResponseStatus(response_headers);
+      if (status_code == code) {
+        if (!Runtime::runtimeFeatureEnabled(
+                "envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc") ||
+            static_cast<Http::Code>(code) != Http::Code::TooEarly) {
+          return RetryDecision::RetryWithBackoff;
+        }
+        if (original_request.get(Http::Headers::get().EarlyData).empty()) {
+          // Retry iff the downstream request wasn't sent as early data. Otherwise, regardless if
```
Comment (RyanTheOptimist) [inline source/common/router/retry_state_impl.cc:381]: nit: iff => if

File: source/common/router/retry_state_impl.cc [hunk 5]
```diff
@@ -313,47 +335,63 @@ RetryStatus RetryStateImpl::shouldHedgeRetryPerTryTimeout(DoRetryCallback callba
...
+          // the request was sent as early date in upstream or not, don't retry. Instead, forwarding
```
Comment (RyanTheOptimist) [inline source/common/router/retry_state_impl.cc:382]: nit: date => data

Comment (RyanTheOptimist) [reply source/common/router/retry_state_impl.cc:382]: nit: forwarding => forward (I think)

File: source/common/router/retry_state_impl.cc [hunk 6]
```diff
@@ -374,41 +412,82 @@ bool RetryStateImpl::wouldRetryFromHeaders(const Http::ResponseHeaderMap& respon
...
+  const bool consider_disable_alt_svc = Runtime::runtimeFeatureEnabled(
+      "envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc");
+  if (consider_disable_alt_svc) {
+    if (reset_reason != Http::StreamResetReason::ConnectionFailure) {
+      ASSERT(was_using_alt_svc.has_value());
+      if (*was_using_alt_svc) {
+        // Retry any post-handshake failure immediately with no alt_svc if the request was sent over
+        // Http/3.
+        disable_alt_svc = true;
+        // TODO(danzh) consider making the retry configurable.
```
Comment (RyanTheOptimist) [inline source/common/router/retry_state_impl.cc:442]: FWIW: Chrome retries immediately in this case, so I think doing the same here is a fine idea.

File: source/common/router/retry_state_impl.cc [hunk 7]
```diff
@@ -374,41 +412,82 @@ bool RetryStateImpl::wouldRetryFromHeaders(const Http::ResponseHeaderMap& respon
...
+        return RetryDecision::RetryNoBackoff;
+      }
+    } else {
+      if (was_using_alt_svc.has_value()) {
```
Comment (RyanTheOptimist) [inline source/common/router/retry_state_impl.cc:446]: This is a bit confusing to me. What's the difference between was_using_alt_svc = false and was_using_alt_svc.has_value() = false? In general, optional<bool> can be a bit confusing. I wonder if we should consider using a 3-state enum for this?

File: source/common/router/retry_state_impl.cc [hunk 8]
```diff
@@ -374,41 +412,82 @@ bool RetryStateImpl::wouldRetryFromHeaders(const Http::ResponseHeaderMap& respon
...
   }
 
   if ((retry_on_ & RetryPolicy::RETRY_ON_REFUSED_STREAM) &&
       reset_reason == Http::StreamResetReason::RemoteRefusedStreamReset) {
-    return true;
+    return RetryDecision::RetryWithBackoff;
   }
 
-  if ((retry_on_ & RetryPolicy::RETRY_ON_CONNECT_FAILURE) &&
+  if (!consider_disable_alt_svc && (retry_on_ & RetryPolicy::RETRY_ON_CONNECT_FAILURE) &&
```
Comment (RyanTheOptimist) [inline source/common/router/retry_state_impl.cc:475]: if consider_disable_alt_svc is true, won't we return early from the previous block? In other words, can we skip checking consider_disable_alt_svc again here?

File: source/common/router/router.cc [hunk 9]
```diff
@@ -704,8 +704,31 @@ Http::FilterHeadersStatus Filter::decodeHeaders(Http::RequestHeaderMap& headers,
   // Hang onto the modify_headers function for later use in handling upstream responses.
   modify_headers_ = modify_headers;
 
-  UpstreamRequestPtr upstream_request =
-      std::make_unique<UpstreamRequest>(*this, std::move(generic_conn_pool));
+  bool as_early_data{false};
+  if (Runtime::runtimeFeatureEnabled(
+          "envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc")) {
+    absl::string_view method = downstream_headers_->getMethodValue();
+    const bool is_safe_method = (method == Http::Headers::get().MethodValues.Get ||
```
Comment (RyanTheOptimist) [inline source/common/router/router.cc:711]: Might consider referencing the RFC definition of safe in a comment here.

File: source/common/router/router.cc [hunk 10]
```diff
@@ -704,8 +704,31 @@ Http::FilterHeadersStatus Filter::decodeHeaders(Http::RequestHeaderMap& headers,
   // Hang onto the modify_headers function for later use in handling upstream responses.
   modify_headers_ = modify_headers;
 
-  UpstreamRequestPtr upstream_request =
-      std::make_unique<UpstreamRequest>(*this, std::move(generic_conn_pool));
+  bool as_early_data{false};
```
Comment (RyanTheOptimist) [inline source/common/router/router.cc:707]: nit: I'm not quite sure what "as_early_data" means.

File: source/common/router/upstream_request.h [hunk 11]
```diff
@@ -187,6 +191,9 @@ class UpstreamRequest : public Logger::Loggable<Logger::Id::router>,
   bool cleaned_up_ : 1;
 
   Event::TimerPtr max_stream_duration_timer_;
+  bool has_early_data_;
+  bool use_alt_svc_ : 1;
```
Comment (RyanTheOptimist) [inline source/common/router/upstream_request.h:195]: Should the other two bools also be :1 fields? Should they come before max_stream_duration_timer_ so they can all be packed together?

File: source/common/tcp/conn_pool.h [hunk 12]
```diff
@@ -178,16 +179,16 @@ class ConnPoolImpl : public Envoy::ConnectionPool::ConnPoolImplBase,
   }
   ConnectionPool::Cancellable* newConnection(Tcp::ConnectionPool::Callbacks& callbacks) override {
     TcpAttachContext context(&callbacks);
-    return newStreamImpl(context);
+    return newStreamImpl(context, /*has_early_data=*/false);
```
Comment (RyanTheOptimist) [inline source/common/tcp/conn_pool.h:182]: maybe a comment about why we set this to false. (because we don't yet support TLS early data over TCP)

**Review by RyanTheOptimist — COMMENTED** [review]
Wow, there is a lot here. Thanks for doing this. It looks like a lot of the changes are plumbing through the bools, so even though the PR is huge it's not too bad. I only reviewed the changes to source/ but will look at the changes to tests once we've got source/ sorted out.

File: source/common/router/router.cc (hunk 10 above)
Comment (danzh2010) [reply source/common/router/router.cc]: rename to `can_use_early_data`

File: source/common/router/router.cc (hunk 9 above)
Comment (danzh2010) [reply source/common/router/router.cc:712]: done

File: source/common/router/upstream_request.h (hunk 11 above)
Comment (danzh2010) [reply source/common/router/upstream_request.h]: done

File: source/common/tcp/conn_pool.h (hunk 12 above)
Comment (danzh2010) [reply source/common/tcp/conn_pool.h]: done

**Comment by danzh2010** [comment]
This PR is good for review now!

File: source/common/router/router.cc [hunk 13]
```diff
@@ -704,8 +704,33 @@ Http::FilterHeadersStatus Filter::decodeHeaders(Http::RequestHeaderMap& headers,
...
+          "envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc")) {
+    absl::string_view method = downstream_headers_->getMethodValue();
+    // According to safe methods defined in https://www.rfc-editor.org/rfc/rfc7231#section-4.2.1
+    const bool is_safe_method = (method == Http::Headers::get().MethodValues.Get ||
+                                 method == Http::Headers::get().MethodValues.Head ||
+                                 method == Http::Headers::get().MethodValues.Options ||
+                                 method == Http::Headers::get().MethodValues.Trace);
+
+    if (retry_state_ == nullptr) {
+      ENVOY_LOG(warn, "No retry policy is configured. There won't be any fallback for alternate "
```
Comment (RyanTheOptimist) [inline source/common/router/router.cc:718]: I'm not sure what the Envoy approach to warning is. I wonder if this might be too frequent since it's potentially once for every request?

File: source/common/router/router.cc [hunk 14]
```diff
@@ -1352,10 +1406,16 @@ void Filter::onUpstreamHeaders(uint64_t response_code, Http::ResponseHeaderMapPt
       // We already retried this request (presumably for a per try timeout) so
       // we definitely won't retry it again. Check if we would have retried it
       // if we could.
-      could_not_retry = retry_state_->wouldRetryFromHeaders(*headers);
+      bool dumb;
```
Comment (RyanTheOptimist) [inline source/common/router/router.cc:1409]: Instead of naming this "dumb", how about just naming it retry_as_early_data and then perhaps commenting about how it's not being used?

**Review by RyanTheOptimist — COMMENTED** [review]
I think this is looking pretty good. I think we'll definitely want to have someone who is very familiar with the router take a look at those changes.

File: source/common/router/retry_state_impl.cc [hunk 15]
```diff
@@ -374,41 +414,82 @@ bool RetryStateImpl::wouldRetryFromHeaders(const Http::ResponseHeaderMap& respon
...
+        return RetryDecision::RetryImmediately;
+      }
+      if ((retry_on_ & RetryPolicy::RETRY_ON_CONNECT_FAILURE)) {
+        // This is a pool failure.
+        return RetryDecision::RetryWithBackoff;
+      }
+    } else if (alternate_protocols_used == AlternateProtocolsUsed::Yes &&
+               (retry_on_ & RetryPolicy::RETRY_ON_ALT_PROTOCOLS_POST_CONNECT_FAILURE)) {
+      // Retry any post-handshake failure immediately with no alt_svc if the request was sent over
+      // Http/3.
```
Comment (alyssawilk) [inline source/common/router/retry_state_impl.cc:455]: So this strikes me as a bit sketchy. 
If there's a way for an upstream to communicate "I don't support HTTP/3" blacklisting HTTP/3 make sense.  But for explicit-http3 config, saying "we got an early error so we're going to ignore the standard retry config, retry and fast-fail" seems sub-optimal behavior, because it'll burn a retry just determining that the grid doesn't support alt-protocols failover, if that makes sense?

File: envoy/router/router.h [hunk 16]
```diff
@@ -1223,6 +1256,15 @@ class UpstreamToDownstream : public Http::ResponseDecoder, public Http::StreamCa
...
   virtual const Network::Connection& connection() const PURE;
+  /**
+   * @return returns true if the downstream request could be sent as early data.
+   */
+  virtual bool canUseEarlyData() const PURE;
+  /**
+   * @return returns true if the downstream request can be sent to upstream using
+   * protocols advertised in Alt-Svc by the upstream.
+   */
+  virtual bool canUseAlternateProtocols() const PURE;
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply envoy/router/router.h:1267]: This is used in post-handshake failure where h3 pool doesn't update the grid about the connection close. So the router needs to explicitly tell the underlying pool to retry with h3 or not. We could have made h3 pool always update conn pool when the connection gets closed, but then we need to distinguish which connection close error indicates a real error.

For pre-handshake failures, the pool can update the h3 status and the router filter doesn't need to specify whether to use h3 or not.

File: envoy/http/conn_pool.h [hunk 17]
```diff
@@ -100,11 +100,16 @@ class Instance : public Envoy::ConnectionPool::Instance, public Event::DeferredD
...
+   * @param can_use_alternate_protocols whether to attempt the advertised alternate protocols or not
+   * for this new stream if the pool supports. If false and the pool only suppports alt-svc,
+   * callback will be invoked with an immediate failure.
    * @warning Do not call cancel() from the callbacks, as the request is implicitly canceled when
    *          the callbacks are called.
    */
-  virtual Cancellable* newStream(Http::ResponseDecoder& response_decoder,
-                                 Callbacks& callbacks) PURE;
+  virtual Cancellable* newStream(Http::ResponseDecoder& response_decoder, Callbacks& callbacks,
+                                 bool can_use_early_data, bool can_use_alternate_protocols) PURE;
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply envoy/http/conn_pool.h:112]: Currently Ryan and I can't think of any other per-request settings we would pass down. So how about re-visit when we indeed have a real case for that?

File: source/common/router/retry_state_impl.cc (hunk 15 above)
Comment (danzh2010) [reply source/common/router/retry_state_impl.cc:455]: If a user configures explicit-http3 pool, IMO they shouldn't config RETRY_ON_ALT_PROTOCOLS_POST_CONNECT_FAILURE, knowing their pool doesn't have fallback. So no retry for H3 post handshake failure. WDYT?

File: envoy/router/router.h (hunk 16 above)
[the remark this answers is not in the document]
Comment (alyssawilk) [reply envoy/router/router.h:1267]: "h3 pool doesn't update the grid about the connection close"

So we have to add an interface _somewhere_.  We can either have the router tell the pool "no http3 for this stream" or have the H3 connection tell the grid "something went wrong, try TCP for a bit".  The latter leaks to non-http3 streams via the "not qualified" error so feels like the wrong abstraction.

I would think for the "something went wrong" could infer something went wrong with a connection closing with open streams, or streams being reset?  let me sync with you and Ryan offline about options here

File: envoy/router/router.h [hunk 18]
```diff
@@ -338,7 +339,23 @@ class InternalRedirectPolicy {
...
 public:
+  enum class RetryDecision {
+    // Retry the request immediately.
+    RetryImmediately,
+    // Retry the request with timed backoff delay.
+    RetryWithBackoff,
+    NoRetry,
+  };
+
+  enum class AlternateProtocolsUsed {
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply envoy/router/router.h]: No other use cases.

File: source/common/router/retry_state_impl.cc (hunk 15 above)
Comment (danzh2010) [reply source/common/router/retry_state_impl.cc]: I made it not depending on the config but retry only with auto pool. PTAL

File: source/common/router/retry_state_impl.cc [hunk 19]
```diff
@@ -27,7 +33,7 @@ RetryStatePtr RetryStateImpl::create(const RetryPolicy& route_policy,
 
   // We short circuit here and do not bother with an allocation if there is no chance we will retry.
   if (request_headers.EnvoyRetryOn() || request_headers.EnvoyRetryGrpcOn() ||
-      route_policy.retryOn()) {
+      route_policy.retryOn() || clusterUseGrid(cluster)) {
```
Comment (alyssawilk) [inline source/common/router/retry_state_impl.cc:36]: Oh carp, I didn't quite think this out.  If we're going to create a retry policy _and buffer_, I think we're going to want to have explicit configuration.
Before we go any farther here I want Matt's advice.

Hey @mattklein123 can I get API thoughts on this PR?
tl;dr generally users are going to want to send most GET requests over 0-rtt QUIC
Sometimes servers may have 0-rtt handshakes turned off, at which point they send a 425, and the client should retry after the handshake has been confirmed.

I had asked Dan to do this "by default" because I don't want folks having to configure the correct behavior for HTTP/3 but auto-creating a retry policy means buffering bodies and I think we simply shouldn't do that by default.  I think I am Ok auto-creating a retry policy for requests without bodies, but requests with bodies (which is mostly non-idempotent and shouldn't 0-rtt by default) wouldn't retry 425.  
Should I give up on doing the right thing by default and have explicit config or  is it reasonable to auto-retry for bodiless requests, or

**Review by alyssawilk — COMMENTED** [review]
argh, hit a snag on the retry thing again, sorry for delay
/wait

File: envoy/http/conn_pool.h [hunk 20]
```diff
@@ -100,11 +100,16 @@ class Instance : public Envoy::ConnectionPool::Instance, public Event::DeferredD
    *                      callbacks is called and the routine returns nullptr. NOTE: Once a callback
    *                      is called, the handle is no longer valid and any further cancellation
    *                      should be done by resetting the stream.
+   * @param can_use_early_data whether the new stream can be sent as early data or not. If true,
+   * the connection might be ready immediately.
+   * @param can_use_alternate_protocols whether to attempt the advertised alternate protocols or not
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply envoy/http/conn_pool.h:105]: Yes, this is not e a failure but ENVOY_BUG now. I will remove the enum in a following commit.

File: source/common/router/retry_state_impl.cc (hunk 19 above)
Comment (mattklein123) [reply source/common/router/retry_state_impl.cc:36]: I started to look through this PR but it's complicated. I will spend some time on this today/tomorrow and response then. Sorry for the delay.

File: envoy/router/router.h (hunk 16 above)
[the remark this answers is not in the document]
Comment (danzh2010) [reply envoy/router/router.h:1266]: QUIC connection error alone, especially post-handshake, isn't sufficient to mark quic pool broken and try TCP only.  Even if the grid could observe "real" quic error but without any knowledge about TCP connectivity , can't tell whether it should send the following requests only over TCP or race QUIC with TCP, without a signal from the router indicating "this request was already sent over QUIC and failed, now don't send it over QUIC again".

File: source/common/router/retry_state_impl.cc (hunk 19 above)
Comment (danzh2010) [reply source/common/router/retry_state_impl.cc:36]: @mattklein123 thanks for looking at this PR! To make it easier to understand, this PR, though large, only changes router retry behavior. The majority plumbings are no-op in conn pool. And we are discussing about those seemingly "must have" retries (because they are h3 or 0-RTT) should depends on config knobs or not.

File: source/common/router/router.cc [hunk 21]
```diff
@@ -696,8 +696,34 @@ Http::FilterHeadersStatus Filter::decodeHeaders(Http::RequestHeaderMap& headers,
...
+    // According to safe methods defined in https://www.rfc-editor.org/rfc/rfc7231#section-4.2.1
+    const bool is_safe_method = (method == Http::Headers::get().MethodValues.Get ||
+                                 method == Http::Headers::get().MethodValues.Head ||
+                                 method == Http::Headers::get().MethodValues.Options ||
+                                 method == Http::Headers::get().MethodValues.Trace);
+
+    if (retry_state_ == nullptr) {
+      ENVOY_LOG_EVERY_POW_2(
+          warn, "No retry policy is configured. There won't be any fallback for alternate "
+                "protocol failure.");
```
Comment (mattklein123) [inline source/common/router/router.cc:712]: I think this log is going to be confusing for those not using H3? Can this new code somehow be gated on H3 support in the cluster?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks in general this makes sense to me. I left some comments from a first pass.

File: source/common/http/http3/conn_pool.cc [hunk 22]
```diff
@@ -43,6 +43,16 @@ void ActiveClient::onMaxStreamsChanged(uint32_t num_streams) {
   }
 }
 
+ConnectionPool::Cancellable* Http3ConnPoolImpl::newStream(Http::ResponseDecoder& response_decoder,
+                                                          ConnectionPool::Callbacks& callbacks,
+                                                          bool can_use_early_data,
+                                                          bool can_use_alternate_protocols) {
+  ENVOY_BUG(can_use_alternate_protocols,
+            "Trying to send request over h3 while alternate protocols is disabled.");
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply source/common/http/http3/conn_pool.cc:51]: We do have prior knowledge about h3.  The router should have already known the pool is a grid before setting this to false and the connectivity grid should have only chosen tcp pool if this is false. That's why this is an ENVOY_BUG.

File: envoy/router/router.h [hunk 23]
```diff
@@ -366,38 +383,53 @@ class RetryState {
...
+   *                 This is used to add timed backoff, etc. It takes a bool to indicate whether the
+   * retry should disable alternate protocols or not. The callback will never be called inline.
    * @return RetryStatus if a retry should take place. @param callback will be called at some point
    *         in the future. Otherwise a retry should not take place and the callback will never be
    *         called. Calling code should proceed with error handling.
    */
-  virtual RetryStatus shouldRetryReset(const Http::StreamResetReason reset_reason,
-                                       DoRetryCallback callback) PURE;
+  virtual RetryStatus shouldRetryReset(Http::StreamResetReason reset_reason,
+                                       Http3Used alternate_protocols_used,
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply envoy/router/router.h]: done

File: source/common/http/conn_pool_grid.cc [hunk 24]
```diff
@@ -13,14 +13,22 @@ absl::string_view describePool(const ConnectionPool::Instance& pool) {
...
+    ConnectivityGrid& grid, Http::ResponseDecoder& decoder, PoolIterator pool_it,
+    ConnectionPool::Callbacks& callbacks, bool can_use_early_data, bool can_use_alternate_protocols)
     : grid_(grid), decoder_(decoder), inner_callbacks_(&callbacks),
       next_attempt_timer_(
           grid_.dispatcher_.createTimer([this]() -> void { tryAnotherConnection(); })),
-      current_(pool_it) {}
+      current_(pool_it), can_use_early_data_(can_use_early_data),
+      can_use_alternate_protocols_(can_use_alternate_protocols) {
+  if (Runtime::runtimeFeatureEnabled(
+          "envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc") &&
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply source/common/http/conn_pool_grid.cc:25]: Latching it to class members of router and retry state impls.

File: source/common/router/retry_state_impl.cc [hunk 25]
```diff
@@ -13,10 +13,16 @@
...
 #include "source/common/http/utility.h"
+#include "source/common/runtime/runtime_features.h"
 
 namespace Envoy {
 namespace Router {
 
+bool clusterUseGrid(const Upstream::ClusterInfo& cluster) {
+  return (cluster.features() & Upstream::ClusterInfo::Features::HTTP3) &&
+         (cluster.features() & Upstream::ClusterInfo::Features::USE_ALPN);
+}
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply source/common/router/retry_state_impl.cc:24]: This logic is in cluster creation. USE_ALPN means the conn pool is able to choose between h3 and h2/h1 based on ALPN, so it definitely can fallback to TCP if the newStream() specifies can_use_alternate_protocols = false. 
`ClusterInfo::features()` seems to be a reasonable abstraction, I'm not sure if it worth to abstract out another interface to expose "this cluster is configured to use h3 and it also supports TCP fallback".

File: envoy/http/conn_pool.h [hunk 26]
```diff
@@ -80,6 +80,14 @@ class ConnectionLifetimeCallbacks {
  */
 class Instance : public Envoy::ConnectionPool::Instance, public Event::DeferredDeletable {
 public:
+  struct StreamOptions {
+
```
Comment (alyssawilk) [inline envoy/http/conn_pool.h:84]: extra whitespace?

File: envoy/http/conn_pool.h [hunk 27]
```diff
@@ -100,11 +108,16 @@ class Instance : public Envoy::ConnectionPool::Instance, public Event::DeferredD
    *                      callbacks is called and the routine returns nullptr. NOTE: Once a callback
    *                      is called, the handle is no longer valid and any further cancellation
    *                      should be done by resetting the stream.
+   * @param can_use_early_data whether the new stream can be sent as early data or not. If true,
```
Comment (alyssawilk) [inline envoy/http/conn_pool.h:111]: update comments?

File: envoy/router/router.h [hunk 28]
```diff
@@ -1223,6 +1248,10 @@ class UpstreamToDownstream : public Http::ResponseDecoder, public Http::StreamCa
    * @return return the connection for the downstream stream.
    */
   virtual const Network::Connection& connection() const PURE;
+  /**
+   * @return returns true if the downstream request could be sent as early data.
```
Comment (alyssawilk) [inline envoy/router/router.h:1252]: update comments

File: source/common/conn_pool/conn_pool_base.h [hunk 29]
```diff
@@ -143,6 +143,7 @@ class PendingStream : public LinkedObject<PendingStream>, public ConnectionPool:
   virtual AttachContext& context() PURE;
 
   ConnPoolImplBase& parent_;
+  bool can_use_early_data_;
```
[the remark this answers is not in the document]
Comment (alyssawilk) [reply source/common/conn_pool/conn_pool_base.h:147]: ping on naming?

File: source/common/http/utility.h [hunk 30]
```diff
@@ -621,6 +622,9 @@ AuthorityAttributes parseAuthority(absl::string_view host);
 envoy::config::route::v3::RetryPolicy
 convertCoreToRouteRetryPolicy(const envoy::config::core::v3::RetryPolicy& retry_policy,
                               const std::string& retry_on);
+
+bool isZeroRttSafeRequest(Http::RequestHeaderMap& request_headers);
```
Comment (alyssawilk) [inline source/common/http/utility.h:626]: comments + unit tests?

File: source/common/router/retry_state_impl.cc [hunk 31]
```diff
@@ -25,11 +31,17 @@ RetryStatePtr RetryStateImpl::create(const RetryPolicy& route_policy,
                                      TimeSource& time_source, Upstream::ResourcePriority priority) {
   RetryStatePtr ret;
 
+  const bool conn_pool_new_stream_with_early_data_and_alt_svc = Runtime::runtimeFeatureEnabled(
+      "envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_alt_svc");
   // We short circuit here and do not bother with an allocation if there is no chance we will retry.
   if (request_headers.EnvoyRetryOn() || request_headers.EnvoyRetryGrpcOn() ||
-      route_policy.retryOn()) {
+      route_policy.retryOn() ||
+      (conn_pool_new_stream_with_early_data_and_alt_svc &&
```
Comment (alyssawilk) [inline source/common/router/retry_state_impl.cc:39]: Let's comment why we create a retry policy when the user didn't configure it.
Explain this will allow for retries in the case we sent an HTTP/3 request before handshake completion, the server asked for a retry after full handshake, and we're only doing it for requests which traditionally don't have bodies (no expensive buffering)

Maybe even break out the extra logic into a stanalone do_http3_early_data_retries and comment there?

Also I think we're at the point we should do release notes for new http3 features so we should doc this up in docs/root/version_history/current.rst

File: source/common/router/retry_state_impl.cc [hunk 32]
```diff
@@ -58,8 +71,17 @@ RetryStateImpl::RetryStateImpl(const RetryPolicy& route_policy,
...
       reset_headers_(route_policy.resetHeaders()),
-      reset_max_interval_(route_policy.resetMaxInterval()) {
-
+      reset_max_interval_(route_policy.resetMaxInterval()),
+      conn_pool_new_stream_with_early_data_and_alt_svc_(
+          conn_pool_new_stream_with_early_data_and_alt_svc) {
+  if (conn_pool_new_stream_with_early_data_and_alt_svc_ &&
+      (cluster.features() & Upstream::ClusterInfo::Features::HTTP3) &&
+      Http::Utility::isZeroRttSafeRequest(request_headers)) {
+    // Always retry potential 0-RTT requests if they are rejected.
```
Comment (alyssawilk) [inline source/common/router/retry_state_impl.cc:80]: Can we make this comment a bit more detail: if they're rejected due to the request being sent too early

File: source/common/http/utility.h (hunk 30 above)
Comment (RyanTheOptimist) [inline source/common/http/utility.h:630]: nit: I think there is no need for "ZeroRtt" in the name of this method since the definition of "safe" in this context is from rfc7231 which is oblivious to zero RTT / early data stuff.

File: source/common/conn_pool/conn_pool_base.h (hunk 29 above)
[the remark this answers is not in the document]
Comment (danzh2010) [reply source/common/conn_pool/conn_pool_base.h:147]: renamed to can_send_early_data

**Comment by danzh2010** [comment]
The cds_integration_test failure seems unrelated. This PR is good for another round of review!

**Comment by danzh2010** [comment]
Ping?

File: envoy/router/router.h [hunk 33]
```diff
@@ -185,20 +185,21 @@ using ResetHeaderParserSharedPtr = std::shared_ptr<ResetHeaderParser>;
...
+  static constexpr uint32_t RETRY_ON_GRPC_CANCELLED                     = 0x20;
+  static constexpr uint32_t RETRY_ON_GRPC_DEADLINE_EXCEEDED             = 0x40;
+  static constexpr uint32_t RETRY_ON_GRPC_RESOURCE_EXHAUSTED            = 0x80;
+  static constexpr uint32_t RETRY_ON_GRPC_UNAVAILABLE                   = 0x100;
+  static constexpr uint32_t RETRY_ON_GRPC_INTERNAL                      = 0x200;
+  static constexpr uint32_t RETRY_ON_RETRIABLE_STATUS_CODES             = 0x400;
+  static constexpr uint32_t RETRY_ON_RESET                              = 0x800;
+  static constexpr uint32_t RETRY_ON_RETRIABLE_HEADERS                  = 0x1000;
+  static constexpr uint32_t RETRY_ON_ENVOY_RATE_LIMITED                 = 0x2000;
+  static constexpr uint32_t RETRY_ON_HTTP3_POST_CONNECT_FAILURE = 0x4000;
```
Comment (mattklein123) [inline envoy/router/router.h:202]: nit: line up equal or just remove the clang format disable/enable.

File: docs/root/version_history/current.rst [hunk 34]
```diff
@@ -49,6 +49,7 @@ New Features
 * http: added support for :ref:`proxy_status_config <envoy_v3_api_field_extensions.filters.network.http_connection_manager.v3.HttpConnectionManager.proxy_status_config>` for configuring `Proxy-Status <https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-proxy-status-08>`_ HTTP response header fields.
 * http: make consistent custom header format fields ``%(DOWN|DIRECT_DOWN|UP)STREAM_(LOCAL|REMOTE)_*%`` to provide all combinations of local & remote addresses for upstream & downstream connections.
 * http3: downstream HTTP/3 support is now GA! Upstream HTTP/3 also GA for specific deployments. See :ref:`here <arch_overview_http3>` for details.
+* http3: supports upstream HTTP/3 retries. Automatically retry 0-RTT safe requests if they are rejected because they are sent too early. And automatically retry 0-RTT safe requests if connect attempt fails later on and the cluster is configured with TCP fallback. And add retry on ``alt-protocols-post-connect-failure`` policy which allows retry of failed HTTP/3 requests with TCP fallback even after handshake if the cluster is configured with TCP fallback.
```
Comment (mattklein123) [inline docs/root/version_history/current.rst:52]: Is there somewhere you can link to (RFC, etc.) that explains "0-RTT safe requests?"

Also, I think alt-protocols-post-connect-failure is out of date and needs updating? See my other comment also about additional docs on this wherever the other retry docs are.

File: source/common/http/conn_pool_grid.cc (hunk 24 above)
[the remark this answers is not in the document]
Comment (mattklein123) [reply source/common/http/conn_pool_grid.cc:26]: I still see this in various places? It should be pretty easy to put a constexpr in a header file and refer to it in all the other places? I don't feel super strongly about it but this seems like an easy typo to make when we refer to it in various places.

Also, potentially rename envoy.reloadable_features.conn_pool_new_stream_with_early_data_and_http3? Also this should be documented in the release note?

File: source/common/http/utility.h [hunk 35]
```diff
@@ -621,6 +622,13 @@ AuthorityAttributes parseAuthority(absl::string_view host);
 envoy::config::route::v3::RetryPolicy
 convertCoreToRouteRetryPolicy(const envoy::config::core::v3::RetryPolicy& retry_policy,
                               const std::string& retry_on);
+
+/**
+ * @param request_headers the request header to be looked into.
+ * @return true if the request method is 0-RTT safe.
+ */
+bool isSafeRequest(Http::RequestHeaderMap& request_headers);
```
Comment (mattklein123) [inline source/common/http/utility.h:630]: nit: can you make this more informative for what it is? Potentially isZeroRttSafeRequest()? IsIdempotentRequest()? Something like that?

File: source/common/router/retry_state_impl.cc (hunk 25 above)
[the remark this answers is not in the document]
Comment (mattklein123) [reply source/common/router/retry_state_impl.cc:24]: This still seems magical to me given that we do this logic in multiple places. Can you add more comments here or potentially just add some helper method with comments that is called in both places?

File: source/common/router/retry_state_impl.h [hunk 36]
```diff
@@ -123,6 +133,7 @@ class RetryStateImpl : public RetryState {
   std::vector<Http::HeaderMatcherSharedPtr> retriable_headers_;
   std::vector<ResetHeaderParserSharedPtr> reset_headers_{};
   std::chrono::milliseconds reset_max_interval_{};
+  bool conn_pool_new_stream_with_early_data_and_alt_svc_{};
```
Comment (mattklein123) [inline source/common/router/retry_state_impl.h:136]: nit: const

File: source/common/router/retry_state_impl.cc [hunk 37]
```diff
@@ -58,8 +74,20 @@ RetryStateImpl::RetryStateImpl(const RetryPolicy& route_policy,
...
+      reset_max_interval_(route_policy.resetMaxInterval()),
+      conn_pool_new_stream_with_early_data_and_alt_svc_(
+          conn_pool_new_stream_with_early_data_and_alt_svc) {
+  if (conn_pool_new_stream_with_early_data_and_alt_svc_ &&
+      (cluster.features() & Upstream::ClusterInfo::Features::HTTP3) &&
+      Http::Utility::isSafeRequest(request_headers)) {
+    // Because 0-RTT requests could be rejected because they are sent too early, and such requests
+    // should always be retried, setup retry policy for 425 response code for all potential 0-RTT
+    // requests even though the retry policy isn't configured to do so. Since 0-RTT safe requests
+    // traditionally shouldn't have body, automatically retrying them will not cause extra
```
Comment (mattklein123) [inline source/common/router/retry_state_impl.cc:86]: They can have body though, right? We don't block that. Will that cause any issues?

File: source/common/http/headers.h [hunk 38]
```diff
@@ -274,6 +274,7 @@ class HeaderValues {
     const std::string RetriableStatusCodes{"retriable-status-codes"};
     const std::string RetriableHeaders{"retriable-headers"};
     const std::string Reset{"reset"};
+    const std::string Http3PostConnectFailure{"http3-post-connect-failure"};
```
Comment (mattklein123) [inline source/common/http/headers.h:277]: This should be documented somewhere? Not just release notes?

File: source/common/router/retry_state_impl.cc [hunk 39]
```diff
@@ -374,42 +438,69 @@ bool RetryStateImpl::wouldRetryFromHeaders(const Http::ResponseHeaderMap& respon
...
   }
 
-  return false;
+  return RetryDecision::NoRetry;
 }
 
-bool RetryStateImpl::wouldRetryFromReset(const Http::StreamResetReason reset_reason) {
+RetryState::RetryDecision
+RetryStateImpl::wouldRetryFromReset(const Http::StreamResetReason reset_reason,
+                                    Http3Used http3_used, bool& disable_alternate_protocols) {
```
Comment (mattklein123) [inline source/common/router/retry_state_impl.cc:451]: s/disable_alternate_protocols/disable_http3? Same elsewhere.

File: source/common/router/router.cc [hunk 40]
```diff
@@ -1114,9 +1128,24 @@ bool Filter::maybeRetryReset(Http::StreamResetReason reset_reason,
   if (downstream_response_started_ || !retry_state_ || upstream_request.retried()) {
     return false;
   }
-
-  const RetryStatus retry_status =
-      retry_state_->shouldRetryReset(reset_reason, [this]() -> void { doRetry(); });
+  RetryState::Http3Used was_using_alternate_protocol = RetryState::Http3Used::Unknown;
+  if (conn_pool_new_stream_with_early_data_and_alt_svc_ && upstream_request.hadUpstream()) {
+    was_using_alternate_protocol =
```
Comment (mattklein123) [inline source/common/router/router.cc:1133]: was_using_http3

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks this LGTM overall. Just a bunch of small comments.

/wait

File: docs/root/version_history/current.rst (hunk 34 above)
Comment (RyanTheOptimist) [reply docs/root/version_history/current.rst:52]: There's a link to down in http/utility.cc to https://www.rfc-editor.org/rfc/rfc7231#section-4.2.1 which defines safe methods. I guess we could also link to https://datatracker.ietf.org/doc/html/rfc8470 which talks about using safe methods for early data. We could mention this here, perhaps?

File: source/common/http/utility.h (hunk 35 above)
Comment (RyanTheOptimist) [reply source/common/http/utility.h:630]: I think "Safe" is the correct term to use, based on RFC 7231. (Amusingly, "Safe" is distinct in this context from "Idempotent" as the latter also includes PUT). Perhaps we could include the RFC link in this comment instead of in the .cc file?

**Review by RyanTheOptimist — COMMENTED** [review]
I think this mostly looks good to me, modulo the questions Matt Klein raised. So once those are sorted out, I think this is good to go.

**Review by mattklein123 — APPROVED** [review]
Thanks LGTM. Will defer to others for final review/merge.

File: source/common/http/utility.h [hunk 41]
```diff
@@ -621,6 +622,14 @@ AuthorityAttributes parseAuthority(absl::string_view host);
 envoy::config::route::v3::RetryPolicy
 convertCoreToRouteRetryPolicy(const envoy::config::core::v3::RetryPolicy& retry_policy,
                               const std::string& retry_on);
+
+/**
+ * @param request_headers the request header to be looked into.
+ * @return true if the request method is safe method defined in
```
Comment (RyanTheOptimist) [inline source/common/http/utility.h:628]: nit: "@return true if the request method is safe as defined in"

**Review by RyanTheOptimist — APPROVED** [review]
LGTM modulo a comment nit. Over to you @alyssawilk

File: test/common/router/retry_state_impl_test.cc [hunk 42]
```diff
@@ -821,28 +966,50 @@ TEST_F(RouterRetryStateImplTest, Backoff) {
...
   EXPECT_CALL(*retry_timer_, enableTimer(std::chrono::milliseconds(90), _));
-  EXPECT_EQ(RetryStatus::Yes, state_->shouldRetryReset(connect_failure_, callback_));
+  EXPECT_EQ(
+      RetryStatus::Yes,
+      state_->shouldRetryReset(connect_failure_, RetryState::Http3Used::Unknown, reset_callback_));
   EXPECT_CALL(callback_ready_, ready());
   retry_timer_->invokeCallback();
 
+  // Connect failure over HTTP/3 should be retried immediately without disabling alt-svc if the
+  // cluster is configured with auto pool.
```
Comment (alyssawilk) [inline test/common/router/retry_state_impl_test.cc:992]: do we test that we don't do this for explicit HTTP/3 pool?

File: test/integration/multiplexed_upstream_integration_test.cc [hunk 43]
```diff
@@ -640,4 +640,43 @@ TEST_P(MultiplexedUpstreamIntegrationTest, UpstreamGoaway) {
...
+  initialize();
+  codec_client_ = makeHttpConnection(lookupPort("http"));
+
+  // Kick off the initial request and make sure it's received upstream.
+  auto response = codec_client_->makeHeaderOnlyRequest(default_request_headers_);
+  waitForNextUpstreamRequest();
+
+  const Http::TestResponseHeaderMapImpl too_early_response_headers{{":status", "425"}};
+  upstream_request_->encodeHeaders(too_early_response_headers, true);
+  // 425 response will be retried by Envoy, so expect another upstream request.
```
Comment (alyssawilk) [inline test/integration/multiplexed_upstream_integration_test.cc:658]: actually can we do this test for HTTP/2 and make sure that we don't retry on early data?

File: test/integration/protocol_integration_test.cc [hunk 44]
```diff
@@ -2119,9 +2119,13 @@ name: passthrough-filter
   initialize();
   codec_client_ = makeHttpConnection(lookupPort("http"));
 
-  // Sends a request with headers and data.
-  changeHeadersForStopAllTests(default_request_headers_, false);
-  auto encoder_decoder = codec_client_->startRequest(default_request_headers_);
+  // Sends a POST request with headers and data.
+  Http::TestRequestHeaderMapImpl request_headers{{":method", "POST"},
```
Comment (alyssawilk) [inline test/integration/protocol_integration_test.cc:2123]: why does this test need to be changed?

**Review by alyssawilk — COMMENTED** [review]
Looking great!  Just a few minor nits and you're good to go!
/wait

File: test/integration/protocol_integration_test.cc (hunk 44 above)
Comment (alyssawilk) [reply test/integration/protocol_integration_test.cc:2123]: makes sense.  let's just  default_request_headers_.setMethod("POST"); here and in other places to minimize diffs, and call it a day.

Comment (alyssawilk) [reply test/integration/protocol_integration_test.cc:2123]: actually as discussed in person, let's see if we can avoid the  buffering for only-retrying-for-"safe"-http3.  If not, stick with the above comment :-)

Comment (danzh2010) [reply test/integration/protocol_integration_test.cc]: It works!

File: test/integration/multiplexed_upstream_integration_test.cc (hunk 43 above)
Comment (danzh2010) [reply test/integration/multiplexed_upstream_integration_test.cc:664]: included H2 in this test

File: docs/root/configuration/http/http_filters/router_filter.rst [hunk 45]
```diff
@@ -128,6 +128,9 @@ retriable-headers
   :ref:`the retry policy <envoy_v3_api_field_config.route.v3.RetryPolicy.retriable_headers>` or in the
   :ref:`config_http_filters_router_x-envoy-retriable-header-names` header.
 
+http3-post-connect-failure:
+  Envoy will attempt a retry if a request is sent over HTTP/3 to the upstream server and failed after getting connected.
```
[the remark this answers is not in the document]
Comment (danzh2010) [reply docs/root/configuration/http/http_filters/router_filter.rst:132]: added

**Comment by danzh2010** [comment]
@mattklein123 for reviewing the diff since last approval and merge!

**Review by mattklein123 — APPROVED** [review]
