### PR TITLE
filters/on_demand: fix first request dropped when body is present

### LINKED ISSUE #17891: OnDemand VHDS makes the first request returns 404.
*Description*:
> I used OnDemand VHDS to dynamically obtain the virtual host configuration. When a  request to a certain host comes for the first time, the request of the `route` is `nullptr`, then the `on demand filter` will send a VHDS request, and execute its callback `onRouteConfigUpdateCompletion` when the VHDS response is received. If the request to the host doesn't have a body, it works fine because a new stream will be created and the request's route will be re-calculated. However if the request has a body,   it won't re-create a stream but just continue to next filter, thus the request's `route` is still `nullptr` since the `snapped_route_config_` is still the old one. Finally the `router` filter will send a local response of 404 to downstream and set the response flag to `NR`.

cc @dmitri-d @htuch @lambdai

### PR DESCRIPTION
**Pull request by wdauchy**
Commit Message:

Track downstream_end_stream_ to support stream recreation with fully read request bodies. Previously, the filter rejected all requests with bodies by checking !callbacks_->decodingBuffer(), even when the body was complete.

Now properly distinguishes incomplete vs complete requests by tracking end_stream state through decoder methods, following the same pattern as the router filter's internal redirect support.

Additional Description:
Risk Level:
Testing: updated tests
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]

Fixes #17891

[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: source/extensions/filters/http/on_demand/on_demand_update.cc [hunk 1]
```diff
@@ -241,9 +245,9 @@ void OnDemandRouteUpdate::onRouteConfigUpdateCompletion(bool route_exists) {
     return;
   }
 
-  if (route_exists &&                  // route can be resolved after an on-demand
-                                       // VHDS update
-      !callbacks_->decodingBuffer() && // Redirects with body not yet supported.
+  if (route_exists &&           // route can be resolved after an on-demand
+                                // VHDS update
+      downstream_end_stream_ && // Redirects require fully read body.
```
Comment (botengyao) [inline source/extensions/filters/http/on_demand/on_demand_update.cc]: Thanks for the fix, do you mind also adding a [runtime guard](https://github.com/envoyproxy/envoy/blob/2f17c73b8ab4176d19627cc154a33b34bc6667a2/source/common/runtime/runtime_features.cc ) for this change?

**Review by botengyao — COMMENTED** [review]
Thanks, the fix lgtm, and could you also add a change log [here](https://github.com/envoyproxy/envoy/blob/2f17c73b8ab4176d19627cc154a33b34bc6667a2/changelogs/current.yaml)?

/wait

File: source/extensions/filters/http/on_demand/on_demand_update.cc [hunk 2]
```diff
@@ -241,9 +245,17 @@ void OnDemandRouteUpdate::onRouteConfigUpdateCompletion(bool route_exists) {
     return;
   }
 
-  if (route_exists &&                  // route can be resolved after an on-demand
-                                       // VHDS update
-      !callbacks_->decodingBuffer() && // Redirects with body not yet supported.
+  bool can_recreate_stream = false;
+  if (Runtime::runtimeFeatureEnabled("envoy.reloadable_features.on_demand_track_end_stream")) {
```
Comment (botengyao) [inline source/extensions/filters/http/on_demand/on_demand_update.cc:249]: can we latch the runtime value without checking it each time?

Comment (botengyao) [reply source/extensions/filters/http/on_demand/on_demand_update.cc:249]: actually it is okay to me

**Review by botengyao — APPROVED** [review]
thanks!

**Comment by adisuissa** [comment]
Does this addresses the comment mentioned https://github.com/envoyproxy/envoy/issues/17891#issuecomment-909359447 for both H/1 and H/2?

**Comment by wdauchy** [comment]
> Does this addresses the comment mentioned [#17891 (comment)](https://github.com/envoyproxy/envoy/issues/17891#issuecomment-909359447) for both H/1 and H/2?

I believe the protocol level `end_stream` flag remains accurate regardless of buffering. The check `!callbacks_->decodingBuffer()` would fail for HTTP/2, since HTTP/2 may still hold a buffer even when the entire body has already been read.

I will double check this in practice.

**Comment by adisuissa** [comment]
> I believe the protocol level `end_stream` flag remains accurate regardless of buffering. The check `!callbacks_->decodingBuffer()` would fail for HTTP/2, since HTTP/2 may still hold a buffer even when the entire body has already been read.
> 
> I will double check this in practice.

Will it make sense to add integration tests?

**Comment by wdauchy** [comment]
> > I believe the protocol level `end_stream` flag remains accurate regardless of buffering. The check `!callbacks_->decodingBuffer()` would fail for HTTP/2, since HTTP/2 may still hold a buffer even when the entire body has already been read.
> > I will double check this in practice.
> 
> Will it make sense to add integration tests?

good point, I will see if I can test this scenario

**Comment by wdauchy** [comment]
> > I believe the protocol level `end_stream` flag remains accurate regardless of buffering. The check `!callbacks_->decodingBuffer()` would fail for HTTP/2, since HTTP/2 may still hold a buffer even when the entire body has already been read.
> > I will double check this in practice.
> 
> Will it make sense to add integration tests?

I tried something in https://github.com/envoyproxy/envoy/pull/42248
let me know what you think
