### PR TITLE
server: pause rds when initializing static listeners

### LINKED ISSUE #3399: RDS update stuck on boot
Using envoy at 71c0fd695e992e21d2e0439eb14b449fa0b8aea4 and java-control-plane we've run into an issue where envoy fails to load all the RDS resources at boot. 

Envoy is configured with two listeners, using two route tables (`standard_egress`/`standard_ingress`). Envoy begins by requesting the routes for *just* `standard_egress`, and gets this back with version = X. Following this it requests `[standard_egress, standard_ingress]` but since the nonce is the same the control plane ignores the request. Finally, envoy requests `[standard_egress, standard_ingress]` again with version X. Because the version matches what the control plane has, it doesn't send the requested resources right away, instead waiting for the next time the resources are updated. This leaves Envoy without a route table for `standard_ingress`, resulting in 404s.

Raw logs from the control plane: 
```
2018-05-16T08:10:52,156  INFO [rpc-server-dispatcher-9] server.DiscoveryServer - [1] request type.googleapis.com/envoy.api.v2.RouteConfiguration[standard_egress] with nonce  from version
2018-05-16T08:10:52,158  INFO [rpc-server-dispatcher-9] cache.SimpleCache - responding for type.googleapis.com/envoy.api.v2.RouteConfiguration from node slug--LOCAL at version  with version 0f9e47ac-faba-4b9f-a3bd-5e94c6b7dc35
2018-05-16T08:10:52,158  INFO [rpc-server-dispatcher-9] server.DiscoveryServer - [1] response type.googleapis.com/envoy.api.v2.RouteConfiguration with nonce 1 version 0f9e47ac-faba-4b9f-a3bd-5e94c6b7dc35
2018-05-16T08:10:52,162  INFO [rpc-server-dispatcher-10] server.DiscoveryServer - [1] request type.googleapis.com/envoy.api.v2.RouteConfiguration[standard_ingress, standard_egress] with nonce  from version
2018-05-16T08:10:52,168  INFO [rpc-server-dispatcher-12] server.DiscoveryServer - [1] request type.googleapis.com/envoy.api.v2.RouteConfiguration[standard_ingress, standard_egress] with nonce 1 from version 0f9e47ac-faba-4b9f-a3bd-5e94c6b7dc35
2018-05-16T08:10:52,170  INFO [rpc-server-dispatcher-12] cache.SimpleCache - open watch 5 for type.googleapis.com/envoy.api.v2.RouteConfiguration[standard_ingress, standard_egress] from node slug--LOCAL for version 0f9e47ac-faba-4b9f-a3bd-5e94c6b7dc35
```

What is the expected way of handling this? Not clear to me whether this is a control plane bug or an envoy bug - should the control plane update its version when new resources are requested? Or should envoy reset its version when it sends a request with new resources? or maybe wait until it knows what resources to request before sending the xDS request?

### PR DESCRIPTION
**Pull request by snowp**
*title*: server: pause rds when initializing static listeners

*Description*:
In order to prevent RDS requests from being fired up before we know all
the route configurations we care about, pause RDS while we initialize
all the listeners from static config. This matches what we do during LDS
update.

We pause the RDS updates over ADS immediately, then once we know that all 
the init callbacks have been completed we resume RDS updates. This was 
necessary because the RDS subscriptions happen in the init callbacks. 

*Risk Level*: 
Low: Small bug fix

*Testing*:
Manually verified that it fixes the repro case from #3399

*Docs Changes*:
N/A

*Release Notes*:
N/A

Fixes #3399

### CODE REVIEW

**Comment by snowp** [comment]
I'd love to add a proper test for this but not sure where best to put it. Open for suggestions

**Comment by junr03** [comment]
@htuch assigning over to you due to discussion in #3399

File: source/server/configuration_impl.cc [hunk 1]
```diff
@@ -51,6 +52,12 @@ void MainImpl::initialize(const envoy::config::bootstrap::v2::Bootstrap& bootstr
       server.localInfo(), server.accessLogManager(), server.admin());
   const auto& listeners = bootstrap.static_resources().listeners();
   ENVOY_LOG(info, "loading {} listener(s)", listeners.size());
+
+  // Immediately pause RDS to ensure that we don't send any requests until we've
+  // subscribed to all the RDS resources. The subscriptions happen in the init callbacks,
+  // so we pause RDS until we've completed all the callbacks.
+  cluster_manager_->adsMux().pause(Config::TypeUrl::get().RouteConfiguration);
```
Comment (mattklein123) [inline source/server/configuration_impl.cc]: I don't have a great answer, but I wish there was a more general way of solving this problem, as I could see us having issues in the future for other resource types that get added. @htuch any ideas?

File: source/server/server.cc [hunk 2]
```diff
@@ -388,7 +389,7 @@ RunHelper::RunHelper(Event::Dispatcher& dispatcher, Upstream::ClusterManager& cm
   // this can fire immediately if all clusters have already initialized. Also note that we need
   // to guard against shutdown at two different levels since SIGTERM can come in once the run loop
   // starts.
-  cm.setInitializedCb([this, &init_manager, workers_start_cb]() {
```
Comment (htuch) [inline source/server/server.cc]: I think the scope here is too wide. Won't this prevent listeners warming? I think ideally we pause/resume around just this loop: https://github.com/envoyproxy/envoy/blob/c223232bbff5aadde8ec83a548e18f99d4729914/source/server/configuration_impl.cc#L54

File: source/server/configuration_impl.cc (hunk 1 above)
Comment (htuch) [reply source/server/configuration_impl.cc]: I think it's fine, there are only two other places this comes up: EDS and SDS. We should either fix EDS in this PR or leave some TODOs and an open issue. I don't think we're going to arbitrarily scale the number of resources in xDS, so seems fine to have a handful of special case handling.

File: source/server/server.cc (hunk 2 above)
Comment (snowp) [reply source/server/server.cc]: I tried that at first but it didn't seem to work - while the listeners are created there the RDS subscription isn't started until the initialize callback. Pausing just around the static listener loop mean that we resumed before the subscriptions started.

It won't block the listeners from warming because I'm resuming after all `initialize` callbacks are called, not when initialization has been complete. Doing the resume inside the callback passed to `init_manager` does prevent the listeners from warming, presumably because some init callback is waiting for the routes. 

Happy to consider another approach - I'm not super happy about having the start and resume action be so far from each other.

**Comment by snowp** [comment]
Added a test to verify that this fixes it for RDS and that it already works for EDS. Also moved the `pause` call to the ClusterManager's init callback: all the RDS subscriptions happen in the init callbacks, so we can narrow the pause down to just around the init callbacks. 

Turns out this already works for EDS: the subscriptions happen during `ClusterManager` init *before* the ADS mux has been started. Once the `GrpcMux` starts, it fires off a xDS request for all the resources, at which point all the statically defined EDS resources have already been subscribed to.

File: test/integration/ads_integration_test.cc [hunk 3]
```diff
@@ -489,5 +493,112 @@ TEST_P(AdsConfigIntegrationTest, EdsClusterWithAdsConfigSource) {
...
+const std::string static_resources_config = R"EOF(
+dynamic_resources:
+  ads_config:
+    api_type: GRPC
+static_resources:
+  listeners:
+  - name: dummy_listener
+    address:
+      socket_address:
+        address: 127.0.0.1
```
Comment (htuch) [inline test/integration/ads_integration_test.cc]: I'd suggest taking the existing bootstrap built by the config utility helper and just augmenting the static resources in `ConfigHelper::addConfigModifier`. That will reduce boilerplate here and make the test more robust as we evolve the integration test bootstrap.

File: test/integration/ads_integration_test.cc [hunk 4]
```diff
@@ -489,5 +493,112 @@ TEST_P(AdsConfigIntegrationTest, EdsClusterWithAdsConfigSource) {
...
+      port_value: 0
+  )EOF";
+
+class StaticAdsIntegrationTest : public AdsIntegrationTest {
+public:
+  StaticAdsIntegrationTest() : AdsIntegrationTest(static_resources_config) {}
+};
+
+TEST_P(StaticAdsIntegrationTest, XdsBatching) {
+  // Validates that the initial xDS request batches all resources referred to in static config
```
Comment (htuch) [inline test/integration/ads_integration_test.cc]: Can you move this to above the `TEST_P`?
