### PR TITLE
test: deflaking a connection pool race

### LINKED ISSUE #5316: Timeout failure in http2_upstream_integration_test's UpstreamConnectionCloseWithManyStreams
*Description*:

While building the Envoy trunk on a newly installed host, I got an intermittent test failure for `IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams`: both the IPv4 and the IPv6 versions of the test timed out.

Upon rerunning `bazel test`, with all the other test results cached so that `UpstreamConnectionCloseWithManyStreams` wasn't competing with anything else, this test case passed.

*Repro steps*:
Starting with a fresh checkout of the [current](https://github.com/envoyproxy/envoy/commit/6a49ebf9d0b6d0a2c826f12d531992c68efd868a) Envoy trunk on macOS, I ran:
```
bazel build //source/exe:envoy-static
time bazel test //test/...
```

*Test log output*:
```
[ RUN      ] IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv4
test/integration/http2_upstream_integration_test.cc:329: Failure
Value of: fake_upstream_connection_->waitForNewStream(*dispatcher_, upstream_requests.back())
  Actual: false (Timed out waiting for new stream.)
Expected: true
[  FAILED  ] IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv4, where GetParam() = 4-byte object <00-00 00-00> (10095 ms)
[ RUN      ] IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv6
test/integration/http2_upstream_integration_test.cc:329: Failure
Value of: fake_upstream_connection_->waitForNewStream(*dispatcher_, upstream_requests.back())
  Actual: false (Timed out waiting for new stream.)
Expected: true
[  FAILED  ] IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv6, where GetParam() = 4-byte object <01-00 00-00> (10092 ms)
```

### PR DESCRIPTION
**Pull request by alyssawilk**
Removing a race where we reset a stream before the upstream stream had been established.

*Risk Level*: low (test only)
*Testing*: 1k runs locally still pass but it was a mac-only bug.
*Docs Changes*: n/a
*Release Notes*: n/a
Fixes #5316

### CODE REVIEW

File: test/integration/http2_upstream_integration_test.cc [hunk 1]
```diff
@@ -306,30 +306,33 @@ TEST_P(Http2UpstreamIntegrationTest, UpstreamConnectionCloseWithManyStreams) {
...
+
+  // Now drain the upstream connection.
+  for (uint32_t i = 1; i < num_requests; ++i) {
     upstream_requests.emplace_back();
     ASSERT_TRUE(
         fake_upstream_connection_->waitForNewStream(*dispatcher_, upstream_requests.back()));
   }
   for (uint32_t i = 0; i < num_requests; ++i) {
-    if (i % 15 != 0) {
+    if (i != 0) {
```
Comment (mattklein123) [inline test/integration/http2_upstream_integration_test.cc]: nit: I would just do for i = 1; ... like you do above (same below) for consistency.
