### PR TITLE
ext_authz: Skip setting content-length when it is part of the allowed headers

### LINKED ISSUE #9603: Content-length header corrupted by ext_authz
*Description*:
When using ext_authz, requests that specify a content length result in a corrupted content-length header being sent to the authentication application. This seems ~like it is a regression from~ related to #3865. The corruption seems to be due to this line:
https://github.com/envoyproxy/envoy/blob/58e733bfbd0a26e3c86b5de3e6b3a7de436e5269/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc#L210
If the incoming request already contains a `content-length` header, then this results in a comma-separated list being sent to the authentication server (see for instance in the logs below, where `content-length: 0,4` is sent to the server).

*Repro steps*:
- Configure ext_authz to send authentication requests to an HTTP server
- Try to call a POST endpoint with a request body using e.g. curl

Example curl output:
```
$ curl -iu test:test localhost:8082/endpoint -d'test'
HTTP/1.1 400 Bad Request
content-type: text/plain; charset=utf-8
content-length: 4
date: Wed, 08 Jan 2020 14:39:19 GMT
server: envoy
x-envoy-upstream-service-time: 1

Invalid HTTP Header: Content-Length%                                                                                                                                                                                                      
```

*Config*:
[envoy.yaml.txt](https://github.com/envoyproxy/envoy/files/4035851/envoy.yaml.txt)

*Logs*:
```
[2020-01-08 14:39:19.749][22][debug][http] [source/common/http/conn_manager_impl.cc:259] [C0] new stream
[2020-01-08 14:39:19.750][22][debug][http] [source/common/http/conn_manager_impl.cc:708] [C0][S14461594867658536095] request headers complete (end_stream=false):
':authority', 'localhost:8082'
':path', '/endpoint'
':method', 'POST'
'authorization', 'Basic dGVzdDp0ZXN0'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'content-length', '4'
'content-type', 'application/x-www-form-urlencoded'

[2020-01-08 14:39:19.750][22][debug][router] [source/common/router/router.cc:434] [C0][S14125282183838975606] cluster 'auth' match for URL '/auth/endpoint'
[2020-01-08 14:39:19.750][22][debug][router] [source/common/router/router.cc:549] [C0][S14125282183838975606] router decoding headers:
':authority', 'localhost:8082'
':method', 'POST'
':path', '/auth/api/1/decant/1/confirm'
':scheme', 'http'
'content-length', '0,4'
'x-forwarded-proto', 'http'
'accept', '*/*'
'content-type', 'application/x-www-form-urlencoded'
'user-agent', 'curl/7.64.1'
'authorization', 'Basic dGVzdDp0ZXN0'
'x-request-id', 'c032c6e9-cc9b-424b-8f94-0fe1c2b2b32d'
'x-envoy-internal', 'true'
'x-forwarded-for', '172.20.0.9'
'x-envoy-expected-rq-timeout-ms', '250'
```

### PR DESCRIPTION
**Pull request by dio**
Description: 

In ext_authz HTTP implementation, when users set `content-length` as one of the allowed headers patterns as part of request authorization, we should skip setting it since it is already configured at initialization and the value depends on the `request_length`.

Risk Level: Low
Testing: N/A
Docs Changes: N/A
Release Notes: N/A
Fixes #9603

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

**Comment by dio** [comment]
@htuch could you help to review this? Thanks!

File: source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc [hunk 1]
```diff
@@ -200,11 +200,14 @@ void RawHttpClientImpl::check(RequestCallbacks& callbacks,
 
   for (const auto& header : request.attributes().request().http().headers()) {
     const Http::LowerCaseString key{header.first};
+    // Skip setting content-length header since it is already configured at initialization.
+    if (key == Http::Headers::get().ContentLength) {
```
Comment (htuch) [inline source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc]: A few questions:
1. Why is `content-length` alone unique? Are there any other similar headers?
2. Where is this documented in the API or operator docs? I think we need to explain this.
3. What harm is there in sending `content-length` to the ext authz server, even if it is redundant with request size?

Comment (dio) [reply source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc]: 1. Because the `content-length` of the request to be sent to the authorization server is not the request itself, but it is the "check request". The payload of the original request can be forwarded in the check request, but it depends on the [max_request_bytes](https://github.com/envoyproxy/envoy/blob/c7f25e8f1d94c72d952544e46ae379b928883ea7/api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto#L112) and if it is [allowed to send partial message or not](https://github.com/envoyproxy/envoy/blob/c7f25e8f1d94c72d952544e46ae379b928883ea7/api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto#L117). Hence it is possible the `content-length` is different (smaller) than the original request.
2. I agree that wee need to explain this behavior more in the doc, it is now cluttered in several places, probably here: https://github.com/envoyproxy/envoy/blob/c7f25e8f1d94c72d952544e46ae379b928883ea7/api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto#L168-L169 and here: https://github.com/envoyproxy/envoy/blob/c7f25e8f1d94c72d952544e46ae379b928883ea7/api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto#L56-L59
3. The `content-length` should be matched with the payload size as mentioned in point 1. above. This patch however to avoid the bugs as mention in the #9603, (the check request has `content-length` header contains `,` in its value, e.g. `content-length: 0,14`), since the value of `content-length` of the check request is already initialized in [here](https://github.com/envoyproxy/envoy/blob/20dddf007f05dd5ad8d09f7221fe835fb5699cfd/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc#L190-L199).

Comment (htuch) [reply source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc]: Ack, I think if you can just add some docs as described in (2) this sounds good.

Comment (dio) [reply source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc]: 👍
