### PR TITLE
ratelimit: add support for failure_mode_allow configuration

### LINKED ISSUE #4023: RateLimit: Add ability to configure denying traffic if rate limit service is failing
*Title*: Add an option to the rate limit filter config to deny traffic on rate limit RPC service failures

*Description*:
Currently if external rate limit requests fail, requests continue through the filter chain. This "fail open" design is a reasonable default so APIs remain available during rate limit service maintenance or failures. 

However for a very sensitive data service, we'd prefer to "fail closed" and not expose the service to non-rate limited traffic.

The ext_authz filter has this concept with the `failure_mode_allow` boolean.

*Relevent links*:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2alpha/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2alpha-extauthz

### PR DESCRIPTION
**Pull request by ramaraochavali**
For an explanation of how to fill out the fields, please see the relevant section 
in PULL_REQUESTS.md

*Description*: Adds supports for specifying `failure_mode_allow` configuration in rate limit filter config. It is defaulted to `true` to be sync with current behaviour. 
*Risk Level*: Low
*Testing*: Automated tests
*Docs Changes*: Updated
*Release Notes*: Updated
Fixes #4023

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@mattklein123 can you PTAL?

**Comment by mattklein123** [comment]
Assigning to @junr03 for first pass.

File: include/envoy/request_info/request_info.h [hunk 1]
```diff
@@ -48,8 +48,10 @@ enum ResponseFlag {
   RateLimited = 0x800,
   // Request was unauthorized by external authorization service.
   UnauthorizedExternalService = 0x1000,
+  // Unable to call Ratelimiting service.
+  RateLimitingServiceError = 0x1200,
```
Comment (junr03) [inline include/envoy/request_info/request_info.h]: nit: RateLimitServiceError

File: source/extensions/filters/http/ratelimit/ratelimit.h [hunk 2]
```diff
@@ -66,6 +68,7 @@ class FilterConfig {
   Stats::Scope& scope_;
   Runtime::Loader& runtime_;
   Upstream::ClusterManager& cm_;
+  bool failure_mode_allow_;
```
Comment (junr03) [inline source/extensions/filters/http/ratelimit/ratelimit.h]: const

File: source/extensions/filters/network/ratelimit/ratelimit.h [hunk 3]
```diff
@@ -57,6 +59,7 @@ class Config {
   std::vector<RateLimit::Descriptor> descriptors_;
   const InstanceStats stats_;
   Runtime::Loader& runtime_;
+  bool failure_mode_allow_;
```
Comment (junr03) [inline source/extensions/filters/network/ratelimit/ratelimit.h]: const

File: test/extensions/filters/http/ratelimit/ratelimit_test.cc [hunk 4]
```diff
@@ -239,6 +242,37 @@ TEST_F(HttpRateLimitFilterTest, ErrorResponse) {
   EXPECT_EQ(
       1U,
       cm_.thread_local_cluster_.cluster_.info_->stats_store_.counter("ratelimit.error").value());
+  EXPECT_EQ(1U, cm_.thread_local_cluster_.cluster_.info_->stats_store_
+                    .counter("ratelimit.failure_mode_allowed")
+                    .value());
+}
+
+TEST_F(HttpRateLimitFilterTest, ErrorResponseWithFailureAllowModeOff) {
```
Comment (junr03) [inline test/extensions/filters/http/ratelimit/ratelimit_test.cc]: nit: FailureModeAllow for naming consistency

File: test/extensions/filters/network/ratelimit/ratelimit_test.cc [hunk 5]
```diff
@@ -53,6 +55,8 @@ class RateLimitFilterTest : public testing::Test {
     Json::ObjectSharedPtr json_config = Json::Factory::loadFromString(json);
     envoy::config::filter::network::rate_limit::v2::RateLimit proto_config{};
     Envoy::Config::FilterJson::translateTcpRateLimitFilter(*json_config, proto_config);
+    // TODO(ramaraochavali): move the config to yaml and use a different config for failure_mode.
```
Comment (junr03) [inline test/extensions/filters/network/ratelimit/ratelimit_test.cc]: I would go ahead and do this, and change these tests to use a SetUpTest(const std::string& yaml) setup function. Prevents the subclass addition here, as you point out in the TODO.

File: test/extensions/filters/http/ratelimit/ratelimit_test.cc [hunk 6]
```diff
@@ -46,10 +46,13 @@ class HttpRateLimitFilterTest : public testing::Test {
         .WillByDefault(Return(true));
   }
 
-  void SetUpTest(const std::string json) {
+  void SetUpTest(const std::string json, const bool failure_mode = true) {
     Json::ObjectSharedPtr json_config = Json::Factory::loadFromString(json);
     envoy::config::filter::http::rate_limit::v2::RateLimit proto_config{};
     Config::FilterJson::translateHttpRateLimitFilter(*json_config, proto_config);
+    // TODO(ramaraochavali): move filter_config_ to yaml and use a different config for
```
Comment (junr03) [inline test/extensions/filters/http/ratelimit/ratelimit_test.cc]: I would go ahead and do this real quick.

File: test/integration/ratelimit_integration_test.cc [hunk 7]
```diff
@@ -157,10 +162,19 @@ class RatelimitIntegrationTest : public HttpIntegrationTest,
 
   const uint64_t request_size_ = 1024;
   const uint64_t response_size_ = 512;
+  bool failure_mode_ = false;
```
Comment (junr03) [inline test/integration/ratelimit_integration_test.cc]: the integration test and the unit tests use the same varaible name `failure_mode_` in opposite ways. In the unit tests we use it directly for the `failure_mode_allow` config value, and here we use it logically opposite, i.e if `failure_mode_` is true then `failure_mode_allow` is false. Can we make it consistent between the tests?

File: source/common/request_info/utility.cc [hunk 8]
```diff
@@ -31,7 +31,7 @@ void ResponseFlagUtils::appendString(std::string& result, const std::string& app
 const std::string ResponseFlagUtils::toShortString(const RequestInfo& request_info) {
   std::string result;
 
-  static_assert(ResponseFlag::LastFlag == 0x1000, "A flag has been added. Fix this code.");
+  static_assert(ResponseFlag::LastFlag == 0x1200, "A flag has been added. Fix this code.");
```
Comment (junr03) [inline source/common/request_info/utility.cc]: For this, and all the other asserts related to the LastFlag, we not only need to fix the value. There is accompanying code that needs to be fixed. For example here we need to add the new flag to the mapping between the enum and the string.

Any suggestions appreciated on how to make this maintenance more obvious.

Comment (ramaraochavali) [reply source/common/request_info/utility.cc]: Oh. Sorry..did not realize that. Will change

**Comment by ramaraochavali** [comment]
@junr03 addressed the comments. PTAL.

File: test/common/access_log/access_log_impl_test.cc [hunk 9]
```diff
@@ -834,6 +834,7 @@ name: envoy.file_access_log
       RequestInfo::ResponseFlag::FaultInjected,
       RequestInfo::ResponseFlag::RateLimited,
       RequestInfo::ResponseFlag::UnauthorizedExternalService,
+      RequestInfo::ResponseFlag::RateLimitServiceError,
```
Comment (junr03) [inline test/common/access_log/access_log_impl_test.cc]: Interesting. This test should fail due to unmatched expectation [here](https://github.com/envoyproxy/envoy/blob/37b691369b0c2a0dc64ebd80aa878ac28ca72e38/test/common/access_log/access_log_impl_test.cc#L845), because the new flag was not added to the filter config [here](https://github.com/envoyproxy/envoy/blob/37b691369b0c2a0dc64ebd80aa878ac28ca72e38/test/common/access_log/access_log_impl_test.cc#L802)

File: test/integration/ratelimit_integration_test.cc [hunk 10]
```diff
@@ -162,13 +162,13 @@ class RatelimitIntegrationTest : public HttpIntegrationTest,
 
   const uint64_t request_size_ = 1024;
   const uint64_t response_size_ = 512;
-  bool failure_mode_ = false;
+  bool failure_mode_ = true;
```
Comment (junr03) [inline test/integration/ratelimit_integration_test.cc]: nit: sorry I don't think I was clear with my previous comment. Now that you changed the logic of this var, can we change the name to match the config name `failure_mode_allow`. I think that adds clarity.

File: test/common/access_log/access_log_impl_test.cc (hunk 9 above)
Comment (junr03) [reply test/common/access_log/access_log_impl_test.cc]: I'm going to take a look in the morning.

Comment (ramaraochavali) [reply test/common/access_log/access_log_impl_test.cc]: Great Catch. I see the problem. The hex value I gave for RateLimitServiceError is incorrect so the intersectResponseFlags is returning wrong value. I have corrected it.

**Comment by ramaraochavali** [comment]
@junr03 addressed review comments. PTAL.

**Comment by ramaraochavali** [comment]
@junr03 can you PTAL when you get time?

**Comment by junr03** [comment]
lgtm, @ggreenway can you take a look?

File: api/envoy/config/filter/http/rate_limit/v2/rate_limit.proto [hunk 11]
```diff
@@ -34,4 +35,10 @@ message RateLimit {
   // The timeout in milliseconds for the rate limit service RPC. If not
   // set, this defaults to 20ms.
   google.protobuf.Duration timeout = 4 [(gogoproto.stdduration) = true];
+
+  // The filter's behaviour in case the rate limiting service does
+  // not respond back. When it is set to true, Envoy will also allow traffic in case of
+  // communication failure between rate limiting service and the proxy.
+  // Defaults to true.
+  google.protobuf.BoolValue failure_mode_allow = 5;
```
[the remark this answers is not in the document]
Comment (ramaraochavali) [reply api/envoy/config/filter/http/rate_limit/v2/rate_limit.proto]: There is no other reason except to be consistent with external_authz proto naming. I will change.

File: source/extensions/filters/http/ratelimit/ratelimit.cc [hunk 12]
```diff
@@ -147,6 +147,15 @@ void Filter::complete(RateLimit::LimitStatus status, Http::HeaderMapPtr&& header
     callbacks_->sendLocalReply(Http::Code::TooManyRequests, "",
                                [this](Http::HeaderMap& headers) { addHeaders(headers); });
     callbacks_->requestInfo().setResponseFlag(RequestInfo::ResponseFlag::RateLimited);
+  } else if (status == RateLimit::LimitStatus::Error) {
+    if (config_->failureModeAllow()) {
```
Comment (ramaraochavali) [inline source/extensions/filters/http/ratelimit/ratelimit.cc]: I did not change the method name in config because it seems more readable like this. LMK if you think otherwise

File: source/extensions/filters/http/ratelimit/ratelimit.cc [hunk 13]
```diff
@@ -147,6 +147,15 @@ void Filter::complete(RateLimit::LimitStatus status, Http::HeaderMapPtr&& header
...
+      cluster_->statsScope().counter("ratelimit.failure_mode_allowed").inc();
```
Comment (ggreenway) [inline source/extensions/filters/http/ratelimit/ratelimit.cc]: Do we need this new counter at all? We already have a counter for ratelimit service failures, and presumably the user knows which way they have this configured (failure_mode_deny value). In one case this counter will always be zero, in the other it will be equal to `ratelimit.error`. So is there value in this new counter?

File: source/extensions/filters/http/ratelimit/ratelimit.cc (hunk 12 above)
Comment (ggreenway) [reply source/extensions/filters/http/ratelimit/ratelimit.cc]: This is fine as is

File: source/extensions/filters/http/ratelimit/ratelimit.cc (hunk 13 above)
Comment (ramaraochavali) [reply source/extensions/filters/http/ratelimit/ratelimit.cc]: I think this would help in general, while looking at stats user do not have to check back on what his configuration is.

Comment (ggreenway) [reply source/extensions/filters/http/ratelimit/ratelimit.cc]: Ok, I'm fine with that.

**Comment by junr03** [comment]
@ramaraochavali @ggreenway, @danielhochman spotted a problem in this patch here https://github.com/envoyproxy/envoy/pull/4073/files#diff-12a885082b482d2c6be37666e04013b0R153. We noticed that in the new flow, we continueDecoding without checking initiating_call_. This is causing crashes at Lyft, so we'd like to revert.
