### PR TITLE
tls_validation_context: fix empty trusted ca

### LINKED ISSUE #39387: No certificate chain validation when trusted CA file exists but empty
I observed an unexpected behavior where the following configuration:
```
validation_context:
  trusted_ca:
    filename: empty_file.cer
```

Where the file exists but is empty, will practically allow any TLS handshake to go through as opposed to the expected behavior where no connection can be established in this case. In this case, there will be no peer validation.

My suggested fix for this bug would be forcing peer certificate validation in case ``trusted_ca`` is configured, regardless of the content of the file. Practically, when the file is empty, it would cause any TLS handshake to fail.
The reasons for this suggested fix:
1. Following the semantics of the configuration where configuring ``trusted_ca`` field enabled cert chain validation, and where the trusted CA file contains no trusted CAs, therefore no chain can be trusted
2. Allowing the update of clusters that use SDS to block all TLS handshake (for example, due to a security issue needed to be patched at runtime) by updating the trusted CA file, even if CDS is not used.

@ggreenway

### PR DESCRIPTION
**Pull request by ohadvano**
Additional Description: Fixes #39387. Fixes the issue by enforcing a non-empty CA string in case ``trusted_ca`` was set in configuration
Risk Level: low
Testing: unit tests
Docs Changes: none
Release Notes: changelog
Platform Specific Features: none
Optional Runtime guard: ``envoy.reloadable_features.reject_empty_trusted_ca_file`` added

### CODE REVIEW

File: test/common/tls/context_impl_test.cc [hunk 1]
```diff
@@ -1154,6 +1155,107 @@ TEST_F(SslServerContextImplTicketTest, VerifySanWithNoCA) {
...
+          filename: "{{ test_rundir }}/test/common/tls/test_data/san_dns_cert.pem"
+        private_key:
+          filename: "{{ test_rundir }}/test/common/tls/test_data/san_dns_key.pem"
+      validation_context:
+        trusted_ca:
+          inline_bytes: ""
+  )EOF";
+  EXPECT_NO_THROW(loadConfigYaml(yaml));
+}
+
```
Comment (ggreenway) [inline test/common/tls/context_impl_test.cc:1258]: Please add one more test case where no `trusted_ca` is set in the `validation_context`. Maybe set `verify_certificate_hash` instead, and validate that it doesn't throw.

File: changelogs/current.yaml [hunk 2]
```diff
@@ -78,6 +78,11 @@ bug_fixes:
   change: |
     Fixes a bug in Envoy's HTTP/3-to-HTTP/1 proxying when a "transfer-encoding" header is incorrectly appended.
     Protected by runtime guard ``envoy.reloadable_features.quic_signal_headers_only_to_http1_backend``.
+- area: tls
+  change: |
+    Fixes a bug where empty trusted CA file or inline string is accepted and causes Envoy to successfully validate any certificate
```
Comment (ggreenway) [inline changelogs/current.yaml:87]: Please state what the new behavior is (generates a config-loading error).

**Review by ggreenway — CHANGES_REQUESTED** [review]
/wait

File: changelogs/current.yaml (hunk 2 above)
Comment (ohadvano) [reply changelogs/current.yaml:87]: Updated

**Review by ggreenway — APPROVED** [review]
LGTM
