### PR TITLE
access log: translate extension config to correct type

### LINKED ISSUE #15940: Access log command extension config parameter is not constructed correctly
Access log command extensions have `typed_config`. The config message, which is given as parameter to the extension, is currently constructed as protobuf `Any` and not translated to the concrete type defined by the extension.

`std::bad_cast` will be thrown when extension tries to cast the config message to the concrete type.

Repro steps:

For example test case `SubstitutionFormatStringUtilsTest::TestFromProtoConfigFormatterExtension` uses `StringValue` as `typed_config` as seen here

https://github.com/envoyproxy/envoy/blob/542f7dfc395e92c83e28d84a43618967c51a8701/test/common/formatter/substitution_format_string_test.cc#L113

In the current test case code the config message is unused and therefore the test passes, see [here](https://github.com/envoyproxy/envoy/blob/542f7dfc395e92c83e28d84a43618967c51a8701/test/common/formatter/command_extension.cc#L32).  If adding a cast to concrete config type to, the test will fail:

```cpp
CommandParserPtr
TestCommandFactory::createCommandParserFromProto(const Protobuf::Message& message) {
  const auto config = dynamic_cast<const ProtobufWkt::StringValue&>(message);  // Throws std::bad_cast
  return std::make_unique<TestCommandParser>();
}
```

### PR DESCRIPTION
**Pull request by tsaarni**
Signed-off-by: Tero Saarni <tero.saarni@est.tech>

**Commit Message:**
Fixes #15940

**Additional Description:**
The consequence of this change is also that the extension config will be validate according to the config type provided by the extension.  Previously this was missed and invalid configuration could have been passed as `typed_config` without error.

**Risk Level:** Low
**Testing:** unit test
**Docs Changes**: N/A
**Release Notes:** N/A
**Platform Specific Features:** N/A

### CODE REVIEW

File: source/common/formatter/substitution_format_string.cc [hunk 1]
```diff
@@ -18,15 +19,18 @@ SubstitutionFormatStringUtils::createJsonFormatter(const ProtobufWkt::Struct& st
...
   // Instantiate formatter extensions.
   std::vector<CommandParserPtr> commands;
   for (const auto& formatter : config.formatters()) {
     auto* factory = Envoy::Config::Utility::getFactory<CommandParserFactory>(formatter);
     if (!factory) {
       throw EnvoyException(absl::StrCat("Formatter not found: ", formatter.name()));
     }
-    auto parser = factory->createCommandParserFromProto(formatter.typed_config());
+    auto typed_config = Envoy::Config::Utility::translateAnyToFactoryConfig(
+        formatter.typed_config(), context.messageValidationVisitor(), *factory);
```
Comment (rgs1) [inline source/common/formatter/substitution_format_string.cc:32]: I am OK with this, we did however have a recent discussion about this in #14855 with @alyssawilk and @mattklein123 and there are two schools of thought as to where the translation should happen:

a) centrally, where the extension point instantiates the extensions or 
b) within the extension's config code so validations can be nicely unit tested without requiring the extension point code itself

Comment (tsaarni) [reply source/common/formatter/substitution_format_string.cc:32]: Ah ok, I see. 

For me it took quite a long time to figure out what was going on, since there isn't other extension points doing the translation in the extension itself, but that would of course get easier when there are examples.

`context` is not passed to formatter extension though, so it cannot get access to the message validation visitor?

Comment (tsaarni) [reply source/common/formatter/substitution_format_string.cc:32]: Another aspect: if extension are passed `typed_config` constructed as `Any` and extensions are expected to translate that to concrete config type, then does it still make sense to have extensions implement `TypedFactory::createEmptyConfigProto()`? Isn't the purpose of that method and the reason for inheriting from `TypedFactory` targeted to allow translation to happen centrally but still in a generic way?

Comment (zuercher) [reply source/common/formatter/substitution_format_string.cc:32]: I think I prefer this way -- it's easier to write extensions. As long as there's a test that shows that validation is triggered in this path, we're probably fine. Though the other requirement is that something has to include the validation implementation for each config type so that the validation is actually triggered.

**Review by zuercher — APPROVED** [review]

**Comment by zuercher** [comment]
@asraa do you have time to have this a second pass?

**Review by asraa — APPROVED** [review]
Thanks! LGTM

Can you merge main? That'll also retrigger tests and macos will hopefully pass

**Review by zuercher — APPROVED** [review]
