### PR TITLE
config: verify the existence of v2 api backing source at config time

### LINKED ISSUE #2240: Envoy segfaults if the LDS config path is invalid
**Bug Template**

*Description*:

Given the `dynamic_resource.lds_config.path` is an invalid path envoy will segfault.

*Repro steps*:

The following shows the steps necessary to repro the issue on the latest envoy

```
root@cbc1703eeb58:/# envoy -c /envoy-config/config.yaml --v2-config-only --service-node some-node --service-cluster some-cluster
[2017-12-20 15:02:00.958][17][info][main] source/server/server.cc:185] initializing epoch 0 (hot restart version=9.200.16384.127)
[2017-12-20 15:02:00.983][17][info][upstream] source/common/upstream/cluster_manager_impl.cc:131] cm init: all clusters initialized
[2017-12-20 15:02:00.983][17][info][config] source/server/configuration_impl.cc:46] loading 0 listener(s)
[2017-12-20 15:02:00.983][17][info][config] source/server/configuration_impl.cc:84] loading tracing configuration
[2017-12-20 15:02:00.983][17][info][config] source/server/configuration_impl.cc:110] loading stats sink configuration
[2017-12-20 15:02:00.984][17][info][main] source/server/server.cc:347] all clusters initialized. initializing init manager
[2017-12-20 15:02:00.984][17][critical][backtrace] bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:101] Caught Segmentation fault, suspect faulting address 0x0
[2017-12-20 15:02:00.984][17][critical][backtrace] bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:85] Backtrace obj<envoy> thr<0> (use tools/stack_decode.py):
[2017-12-20 15:02:00.984][17][critical][backtrace] bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #0 0x8c88c4
[2017-12-20 15:02:00.984][17][critical][backtrace] bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:93] thr<0> obj</lib/x86_64-linux-gnu/libpthread.so.0>
[2017-12-20 15:02:00.984][17][critical][backtrace] bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #1 0x7fe8b741b32f
[2017-12-20 15:02:00.984][17][critical][backtrace] bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:97] end backtrace thread 0
Segmentation fault (core dumped)
root@cbc1703eeb58:/# cat /envoy-config/config.yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901

static_resources:
  clusters:
    - name: 0-service-cluster
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 8080

dynamic_resources:
  lds_config:
    path: /some/invalid/path.yaml

root@cbc1703eeb58:/# envoy --version

envoy  version: 3a69c0a47ae5eed6980af6d43e0999e63efe24b2/Clean/RELEASE
```

*Config*:

See the snippet above

*Logs*:

See the snippet above

### PR DESCRIPTION
**Pull request by junr03**
Signed-off-by: Jose Nino <jnino@lyft.com>

config: verify the existence of v2 api backing source at config time

*Description*: in the v2 world there are no config load time checks for the
static existence of xDS backing sources. This PR adds config load time checks
for: 

1. The existence of any XDS api config source
    resource cluster name in the static cluster list.
2. The existence of any XDS path in the filesystem.
3. The existence of the ADS cluster name in the static cluster list.
4. The existence of the cluster name or path of the SDS v1 deprecated config in the 
     static cluster list or in the file system respectively.

*Risk Level*:  Medium. This PR restricts some dynamic scenarios, and will shutdown if presented with xDS resources without existing backing sources.

*Testing*: updating testing for the scenarios that throw exceptions at config load time, and 
ones that don't. 

*Docs Changes*: https://github.com/envoyproxy/data-plane-api/pull/371

*Release Notes*: updated

Fixes #2240

### CODE REVIEW

**Comment by junr03** [comment]
@mattklein123 @htuch @alyssawilk 

I think all of us are on board for items `3` and `4` above. And we agree that `1` and `2` should be the case for `CDS` at the very least. Do we want to extend `1` and `2` to all XDS configs as this PR does?

**Comment by mattklein123** [comment]
> Do we want to extend 1 and 2 to LDS config as this PR does?

IMO the checks should happen for all xDS. Although it's technically possible for there to be dynamic nesting, IMO, it's needlessly confusing and opens up an entire different class of errors that we need to handle (what if someone removes the management cluster while the server is running, etc.). I would just force all xDS targets to be statically defined at bootstrap time.

**Comment by alyssawilk** [comment]
+1 to consistent checking.  I'd be happy to have file checks everywhere and I defer to Matt/Harvey on the rest as I'm still less familiar with the various config sources.

File: source/common/config/subscription_factory.h [hunk 1]
```diff
@@ -54,6 +60,11 @@ class SubscriptionFactory {
             "envoy::api::v2::ConfigSource must have a singleton cluster name specified");
       }
       const auto& cluster_name = api_config_source.cluster_name()[0];
+      if (!cm.get(cluster_name)) {
```
Comment (mattklein123) [inline source/common/config/subscription_factory.h]: I think you need to additionally check that this cluster was not "added via API" (https://github.com/envoyproxy/envoy/blob/master/include/envoy/upstream/upstream.h#L333). I think by definition the cluster below can't be added by API but you might assert that.

File: source/common/config/subscription_factory.h [hunk 2]
```diff
@@ -43,6 +44,11 @@ class SubscriptionFactory {
     SubscriptionStats stats = Utility::generateStats(scope);
     switch (config.config_source_specifier_case()) {
     case envoy::api::v2::ConfigSource::kPath:
+      if (!Filesystem::fileExists(config.path())) {
```
Comment (mattklein123) [inline source/common/config/subscription_factory.h]: Technically, in the file case, the file/directory could get deleted between this check and when the watch/load happens, so error handling really should work correctly at that point, or the watch should be setup here. With that said, that is an edge case, and if you want to put in a TODO for that I don't mind. Same below.

File: source/common/upstream/cluster_manager_impl.cc [hunk 3]
```diff
@@ -206,8 +207,49 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::api::v2::Bootstrap& bootstra
...
     loadCluster(cluster, false);
+    cluster_names.insert(cluster.name());
+  }
+
+  // All the static clusters have been loaded. At this point we can check for the
+  // existence of the v1 sds backing cluster, and the ads backing cluster.
+  // TODO(htuch): Add support for multiple clusters, #1170.
+  if (bootstrap.dynamic_resources().deprecated_v1().has_sds_config()) {
+    const auto& sds_config = bootstrap.dynamic_resources().deprecated_v1().sds_config();
+    switch (sds_config.config_source_specifier_case()) {
```
Comment (htuch) [inline source/common/upstream/cluster_manager_impl.cc]: This code is similar to that added in `SubscriptionFactory`, operating on a `ApiConfigSource`, would it make sense to refactor?

File: source/common/config/subscription_factory.h (hunk 1 above)
Comment (junr03) [reply source/common/config/subscription_factory.h]: I was thinking about this on my bike ride home yesterday! We definitely need to add that additional check in order to accomplish what I set out to enforce with this checks

File: source/common/config/subscription_factory.h [hunk 4]
```diff
@@ -43,17 +45,33 @@ class SubscriptionFactory {
...
+        throw EnvoyException(fmt::format("envoy::api::v2::Path must refer to a existing path in "
+                                         "your system: '{}' does not exist",
+                                         config.path()));
+      }
       result.reset(
           new Config::FilesystemSubscriptionImpl<ResourceType>(dispatcher, config.path(), stats));
       break;
     case envoy::api::v2::ConfigSource::kApiConfigSource: {
       const auto& api_config_source = config.api_config_source();
+
```
Comment (htuch) [inline source/common/config/subscription_factory.h]: Nit: not sure if this additional whitespace adds much.

File: source/common/upstream/cluster_manager_impl.cc [hunk 5]
```diff
@@ -207,15 +208,58 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::api::v2::Bootstrap& bootstra
...
   }
 
-  // We can now potentially create the CDS API once the backing cluster exists.
-  if (bootstrap.dynamic_resources().has_cds_config()) {
-    cds_api_ = factory_.createCds(bootstrap.dynamic_resources().cds_config(), eds_config_, *this);
-    init_helper_.setCds(cds_api_.get());
-  } else {
-    init_helper_.setCds(nullptr);
+  for (const auto& cluster : bootstrap.static_resources().clusters()) {
+    // Now load all the secondary clusters.
```
Comment (htuch) [inline source/common/upstream/cluster_manager_impl.cc]: Can you add some explanation here on the distinction between primary and secondary clusters?

Comment (junr03) [reply source/common/upstream/cluster_manager_impl.cc]: The one edge case that remains here is that I am not being strict about EDS clusters backed by EDS clusters. That is, if when we load EDS cluster `foo`, we have already loaded EDS cluster `bar` (which `foo` depends on) we let it be. However, if we load `bar` then `foo`, we throw the exception.

I have toyed with 3 ways to reason this:

1. We prohibit EDS clusters backed by EDS clusters.
2. We allow EDS clusters backed by EDS clusters, at which point I bifurcate to:
  a.  We leave the change as is, and now that we have understandable exceptions people can reason about add order and can reorganize their statically loaded clusters to fix the problem.
  b. I make the code even more complex, where we have a third verification pass after all clusters have been added and verify that all EDS clusters backed by EDS clusters are valid.

Comment (mattklein123) [reply source/common/upstream/cluster_manager_impl.cc]: What is an EDS cluster backed by an EDS cluster?

File: source/common/upstream/cluster_manager_impl.cc [hunk 6]
```diff
@@ -206,16 +207,69 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::api::v2::Bootstrap& bootstra
...
+  // currently stands all non-EDS clusters are primary and only EDS
+  // clusters are secondary.
+  // This two phase loading is done for the same reason that we have
+  // a two phase cluster initialization sequence: secondary clusters
+  // might depend on primary clusters, and thus we need to load
+  // secondary cluster dependencies first.
   for (const auto& cluster : bootstrap.static_resources().clusters()) {
-    loadCluster(cluster, false);
+    // First load all the primary clusters.
+    if (cluster.type() != envoy::api::v2::Cluster::EDS) {
```
Comment (mattklein123) [inline source/common/upstream/cluster_manager_impl.cc]: I'm a little confused by this change and don't understand why it is necessary. Is this because in v2 config each EDS cluster individually sets up a subscription on an API source using generic code, so the non-EDS clusters must be loaded first? If that's the case can you update the comment to be more specific?

File: source/common/upstream/cluster_manager_impl.cc [hunk 7]
```diff
@@ -206,16 +207,69 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::api::v2::Bootstrap& bootstra
...
+    // Now load all the secondary clusters.
+    if (cluster.type() == envoy::api::v2::Cluster::EDS) {
+      loadCluster(cluster, false);
+    }
+  }
+
+  // All the static clusters have been loaded. At this point we can check for the
+  // existence of the v1 sds backing cluster, and the ads backing cluster.
+  // TODO(htuch): Add support for multiple clusters, #1170.
+  const ClusterInfoMap loaded_clusters = clusters();
```
Comment (mattklein123) [inline source/common/upstream/cluster_manager_impl.cc]: is it necessary to copy the cluster map here? Can you just use primary_clusters_ directly?

File: source/common/upstream/cluster_manager_impl.cc [hunk 8]
```diff
@@ -206,16 +207,69 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::api::v2::Bootstrap& bootstra
...
+  if (bootstrap.dynamic_resources().deprecated_v1().has_sds_config()) {
+    const auto& sds_config = bootstrap.dynamic_resources().deprecated_v1().sds_config();
+    switch (sds_config.config_source_specifier_case()) {
```
Comment (mattklein123) [inline source/common/upstream/cluster_manager_impl.cc]: This switch statement is almost identical to the one in the subscription code. Is there any way to put it into a utility? Perhaps a utility that just checks for errors? Then that could be called here as well as in the subscription code.

File: source/common/upstream/cluster_manager_impl.cc (hunk 5 above)
Comment (mattklein123) [reply source/common/upstream/cluster_manager_impl.cc]: I see, you mean an EDS cluster that uses a config source that is another EDS cluster. We should block this I think, so (1).

File: source/common/upstream/cluster_manager_impl.cc (hunk 7 above)
Comment (junr03) [reply source/common/upstream/cluster_manager_impl.cc]: you're right, no need to copy

File: source/common/upstream/cluster_manager_impl.cc (hunk 5 above)
Comment (junr03) [reply source/common/upstream/cluster_manager_impl.cc]: Yes that is exactly what I mean. Ok, sounds good. I'll update

File: source/common/upstream/cluster_manager_impl.cc (hunk 6 above)
Comment (junr03) [reply source/common/upstream/cluster_manager_impl.cc]: Yes, exactly. I'll clarify the comment.

File: source/common/upstream/cluster_manager_impl.cc [hunk 9]
```diff
@@ -206,16 +207,57 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::api::v2::Bootstrap& bootstra
         bootstrap.cluster_manager().upstream_bind_config().source_address());
   }
 
+  // Cluster loading happens in two phases: first all the primary clusters
+  // are loaded, and then all the secondary clusters are loaded. As it
+  // currently stands all non-EDS clusters are primary and only EDS
+  // clusters are secondary.
```
Comment (mattklein123) [inline source/common/upstream/cluster_manager_impl.cc]: please fix comment wrapping

File: source/common/config/utility.h [hunk 10]
```diff
@@ -117,6 +117,39 @@ class Utility {
...
+    if (api_config_source.cluster_name().size() != 1) {
+      // TODO(htuch): Add support for multiple clusters, #1170.
+      throw EnvoyException(
+          "envoy::api::v2::ConfigSource must have a singleton cluster name specified");
+    }
+
+    const auto& cluster_name = api_config_source.cluster_name()[0];
+    const auto& it = clusters.find(cluster_name);
+    if (it == clusters.end() || it->second.get().info()->addedViaApi() ||
+        (typeid(ResourceType) == typeid(envoy::api::v2::ClusterLoadAssignment) &&
```
Comment (mattklein123) [inline source/common/config/utility.h]: Sorry I just saw this. What is the reason for this check? IMO no resource type should depend on an EDS cluster even though it's technically possible. I would just make all xDS use fully static cluster types until if/when someone complains about it.

Comment (junr03) [reply source/common/config/utility.h]: Reasoning was that the most confusing dependency was EDS where we could even get in cyclical dependencies. But yes, I agree that to keep in line with the philosophy of the change (restrict all xDS deps equally) we could keep all xDS dependent on **fully** static clusters -- both non loaded via API and endpoints not done via EDS. I'll adjust.

 I'll also make a follow up doc PR to document the restriction.

Comment (mattklein123) [reply source/common/config/utility.h]: +1, thanks!

**Comment by mattklein123** [comment]
@junr03 was going to merge this but looks like needs a master merge. Do you mind fixing?
