### PR TITLE
event: fix deadlock around post()

### LINKED ISSUE #3644: Envoy main thread can deadlock itself
```
void DispatcherImpl::runPostCallbacks() {
  std::function<void()> callback;
  while (true) {
    {
      Thread::LockGuard lock(post_lock_);
      if (post_callbacks_.empty()) {
        return;
      }
      callback = post_callbacks_.front();
      post_callbacks_.pop_front();
    }
    callback();
  }
}
```

In DispatcherImpl::runPostCallbacks(), callback is declared outside the loop and assigned to on each iteration. Then we release the lock and call the callback, then repeat.

The problem is on the next iteration. We assign callback again. This causes the previous iteration callback to get destructed. If that lambda holds an object that gets destructed, the destructor is run while holding the post_lock_. If running the destructor causes some chain of events that result in post()ing back to the same thread, the thread will deadlock itself.

Callstack showing this:

```
#7  0x000000000092427d in absl::Mutex::Lock() ()
#8  0x0000000000678fa3 in Envoy::Thread::MutexBasicLockable::lock (this=0x38b6070) at bazel-out/k8-opt/bin/source/common/common/_virtual_includes/thread_lib/common/common/thread.h:45
#9  Envoy::Thread::LockGuard::LockGuard (lock=..., this=<synthetic pointer>) at bazel-out/k8-opt/bin/source/common/common/_virtual_includes/lock_guard_lib/common/common/lock_guard.h:103
#10 Envoy::Event::DispatcherImpl::post(std::function<void ()>) (this=0x38b6000, callback=...) at source/common/event/dispatcher_impl.cc:142
#11 0x000000000069f72e in Envoy::Stats::ThreadLocalStoreImpl::releaseScopeCrossThread (this=0x380a420, scope=scope@entry=0xcd876c0) at source/common/stats/thread_local_store.cc:139
#12 0x00000000006a09dd in Envoy::Stats::ThreadLocalStoreImpl::ScopeImpl::~ScopeImpl (this=0xcd876c0, __in_chrg=<optimized out>) at source/common/stats/thread_local_store.cc:173
#13 0x00000000006a0b41 in Envoy::Stats::ThreadLocalStoreImpl::ScopeImpl::~ScopeImpl (this=0xcd876c0, __in_chrg=<optimized out>) at source/common/stats/thread_local_store.cc:173
#14 0x00000000006eff83 in std::default_delete<Envoy::Stats::Scope>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:76
#15 std::unique_ptr<Envoy::Stats::Scope, std::default_delete<Envoy::Stats::Scope> >::~unique_ptr (this=0x6988068, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#16 Envoy::Upstream::ClusterInfoImpl::~ClusterInfoImpl (this=0x6988000, __in_chrg=<optimized out>)
    at bazel-out/k8-opt/bin/source/common/upstream/_virtual_includes/upstream_includes/common/upstream/upstream_impl.h:309
#17 0x00000000006efff1 in Envoy::Upstream::ClusterInfoImpl::~ClusterInfoImpl (this=0x6988000, __in_chrg=<optimized out>)
    at bazel-out/k8-opt/bin/source/common/upstream/_virtual_includes/upstream_includes/common/upstream/upstream_impl.h:309
#18 0x00000000006efbea in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1195bf80) at /usr/include/c++/5/bits/shared_ptr_base.h:150
#19 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7650310, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:659
#20 std::__shared_ptr<Envoy::Upstream::ClusterInfo const, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7650308, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:925
#21 std::shared_ptr<Envoy::Upstream::ClusterInfo const>::~shared_ptr (this=0x7650308, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr.h:93
#22 Envoy::Upstream::HostDescriptionImpl::~HostDescriptionImpl (__vtt_parm=0xc314e0 <VTT for Envoy::Upstream::HostImpl+8>, this=0x7650300, __in_chrg=<optimized out>)
    at bazel-out/k8-opt/bin/source/common/upstream/_virtual_includes/upstream_includes/common/upstream/upstream_impl.h:55
#23 Envoy::Upstream::HostImpl::~HostImpl (this=0x7650300, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at bazel-out/k8-opt/bin/source/common/upstream/_virtual_includes/upstream_includes/common/upstream/upstream_impl.h:122
#24 Envoy::Upstream::HostImpl::~HostImpl (this=0x7650300, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at bazel-out/k8-opt/bin/source/common/upstream/_virtual_includes/upstream_includes/common/upstream/upstream_impl.h:122
#25 0x0000000000462a72 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0xdb93d80) at /usr/include/c++/5/bits/shared_ptr_base.h:150
#26 0x0000000000734189 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x10451e48, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:659
#27 std::__shared_ptr<Envoy::Upstream::Host, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x10451e40, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:925
#28 std::shared_ptr<Envoy::Upstream::Host>::~shared_ptr (this=0x10451e40, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr.h:93
#29 Envoy::Upstream::Outlier::DetectorImpl::<lambda()>::~<lambda> (this=0x10451e30, __in_chrg=<optimized out>) at source/common/upstream/outlier_detection_impl.cc:304
#30 std::_Function_base::_Base_manager<Envoy::Upstream::Outlier::DetectorImpl::notifyMainThreadConsecutiveError(Envoy::Upstream::HostSharedPtr, Envoy::Upstream::Outlier::EjectionType)::<lambda()> >::_M_destroy (__victim=...) at /usr/include/c++/5/functional:1726
#31 std::_Function_base::_Base_manager<Envoy::Upstream::Outlier::DetectorImpl::notifyMainThreadConsecutiveError(Envoy::Upstream::HostSharedPtr, Envoy::Upstream::Outlier::EjectionType)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=<optimized out>) at /usr/include/c++/5/functional:1750
#32 0x0000000000678e50 in std::_Function_base::~_Function_base (this=0x7ffee8fbf070, __in_chrg=<optimized out>) at /usr/include/c++/5/functional:1830
#33 std::function<void ()>::~function() (this=0x7ffee8fbf070, __in_chrg=<optimized out>) at /usr/include/c++/5/functional:1974
#34 std::function<void ()>::operator=(std::function<void ()> const&) (__x=..., this=0x7ffee8fbf050) at /usr/include/c++/5/functional:2071
#35 Envoy::Event::DispatcherImpl::runPostCallbacks (this=0x38b6000) at source/common/event/dispatcher_impl.cc:172
#36 0x00000000008d9128 in event_process_active_single_queue (base=base@entry=0x38602c0, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0, activeq=<optimized out>) at event.c:1646
#37 0x00000000008d968f in event_process_active (base=0x38602c0) at event.c:1738
#38 event_base_loop (base=0x38602c0, flags=0) at event.c:1961
#39 0x0000000000643d1e in Envoy::Server::InstanceImpl::run (this=0x383e500) at source/server/server.cc:403
#40 0x000000000046bdf1 in Envoy::MainCommonBase::run (this=this@entry=0x3888168) at source/exe/main_common.cc:83
```

### PR DESCRIPTION
**Pull request by ggreenway**
Fixes #3644

Signed-off-by: Greg Greenway <ggreenway@apple.com>

*Risk Level*: Low

*Testing*: New unit test.

### CODE REVIEW

File: test/common/event/dispatcher_impl_test.cc [hunk 1]
```diff
@@ -96,6 +96,44 @@ TEST_F(DispatcherImplTest, Post) {
   }
 }
 
+// Ensure that n
```
Comment (lizan) [inline test/common/event/dispatcher_impl_test.cc]: ?

File: source/common/event/dispatcher_impl.cc [hunk 2]
```diff
@@ -162,8 +162,14 @@ void DispatcherImpl::run(RunType type) {
...
 void DispatcherImpl::runPostCallbacks() {
-  std::function<void()> callback;
   while (true) {
+    // It is important that this declaration is inside the body of the loop so that the callback is
+    // destructed while post_lock_ is not held. If callback is declared outside the loop and reused
+    // for each iteration, the previous iteration's callback is destructed when callback is
+    // re-assigned, which happens while holding the lock. This can lead to a deadlock (via
+    // recursive mutex acquisition) if destroying the callback runs a destructor, which through some
+    // callstack calls post() on this dispatcher.
+    std::function<void()> callback;
```
Comment (lizan) [inline source/common/event/dispatcher_impl.cc]: though not directly related to this fix, since you're here, how much is the cost by copying callback function here? could this be more efficient by swapping the whole list from `post_callbacks_` and run them, instead of locking for each callbacks?

Comment (mattklein123) [reply source/common/event/dispatcher_impl.cc]: Yes that would be more efficient to just move the whole list and lock once. I would be fine with changing the code to do that also.

Comment (jmarantz) [reply source/common/event/dispatcher_impl.cc]: I assume you'd still need the loop to collect callbacks that get posted after the loop starts.

Comment (mattklein123) [reply source/common/event/dispatcher_impl.cc]: It wouldn't be explicitly necessary. When the array goes from 0 -> 1 a new message would be posted to run callbacks again. A single move would work.

Comment (ggreenway) [reply source/common/event/dispatcher_impl.cc]: I think for this change I would rather keep it as a minimal bug fix. Someone can go through later to make it faster by swapping the list out.

File: test/common/event/dispatcher_impl_test.cc (hunk 1 above)
Comment (ggreenway) [reply test/common/event/dispatcher_impl_test.cc]: Oops. Fixed.
