### PR TITLE
[Geoip+ci] Fix flaky release check in ci

### LINKED ISSUE #35829: geoip provider of maxmind flaky
https://dev.azure.com/cncf/envoy/_build/results?buildId=178428&view=logs&jobId=76424b50-4542-51d2-ddfa-1b282263c744&j=76424b50-4542-51d2-ddfa-1b282263c744&t=ee414bb6-1c71-528f-760c-893708054276

### PR DESCRIPTION
**Pull request by nezdolik**
Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
Partially Fixes #35829
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by nezdolik** [comment]
cc @phlax

File: test/extensions/geoip_providers/maxmind/geoip_provider_test.cc [hunk 1]
```diff
@@ -116,6 +115,7 @@ class GeoipProviderTestBase {
                                                           Filesystem::Watcher::OnChangedCb cb) {
                 {
                   absl::WriterMutexLock lock(&mutex_);
+                  on_changed_cbs_.reserve(1);
```
Comment (KBaichoo) [inline test/extensions/geoip_providers/maxmind/geoip_provider_test.cc:118]: Is the flake that we should only be accessing on_change_cbs_ with the mutex?

**Review by KBaichoo — APPROVED** [review]

File: test/extensions/geoip_providers/maxmind/geoip_provider_test.cc (hunk 1 above)
Comment (nezdolik) [reply test/extensions/geoip_providers/maxmind/geoip_provider_test.cc:118]: yes, the tests were failing nondeterministically in somewhat random code paths before this fix (in release ci check)
