### PR TITLE
http: fixing CONNECT to not advertise chunk encoding.

### LINKED ISSUE #11227: Terminating HTTP CONNECT 200 response should not send "Transfer-Encoding: chunked" header
When Envoy terminates an HTTP CONNECT tunnel (see #1451) and sends a 200 response, it sends a `Transfer-Encoding: chunked` header. This is a violation of the [RFC-7231](https://tools.ietf.org/html/rfc7231#section-4.3.6) which states:

> A server MUST NOT send any Transfer-Encoding or Content-Length header fields in a 2xx (Successful) response to CONNECT.

It looks as if the request path knows to strip the transfer-encoding header, since in `Http1::RequestEncoderImpl::encodeHeaders`, there is a branch that disables chunked encoding when the method is CONNECT:

```c++
  } else if (method->value() == Headers::get().MethodValues.Connect) {
    disableChunkEncoding();
    connect_request_ = true;
  }
```

There is no such check in `Http1::ResponseEncoderImpl::encodeHeaders` but if I unconditionally call `disableChunkEncoding()` in that method, the the transfer-encoding header goes away.

Edit: it looks like `is_response_to_connect_request_` does the right thing, so this is probably an easy fix. I can submit a PR for this.

### PR DESCRIPTION
**Pull request by alyssawilk**
Risk Level: low (connect only)
Testing: UT, IT
Docs Changes: n/a
Release Notes: n/a
Fixes #11227
Part of #1451

### CODE REVIEW

File: source/common/http/header_utility.cc [hunk 1]
```diff
@@ -161,6 +162,12 @@ bool HeaderUtility::isConnect(const RequestHeaderMap& headers) {
   return headers.Method() && headers.Method()->value() == Http::Headers::get().MethodValues.Connect;
 }
 
+bool HeaderUtility::isConnectResponse(const RequestHeaderMapPtr& request_headers,
+                                      const ResponseHeaderMap& response_headers) {
+  return request_headers.get() && isConnect(*request_headers) &&
+      Http::Utility::getResponseStatus(response_headers) == 200;
```
Comment (mattklein123) [inline source/common/http/header_utility.cc:168]: nit: s/200/Http::Code::OK

File: source/common/http/http1/codec_impl.cc [hunk 2]
```diff
@@ -165,8 +165,12 @@ void StreamEncoderImpl::encodeHeadersBase(const RequestOrResponseHeaderMap& head
     } else if (connection_.protocol() == Protocol::Http10) {
       chunk_encoding_ = false;
     } else {
-      encodeFormattedHeader(Headers::get().TransferEncoding.get(),
-                            Headers::get().TransferEncodingValues.Chunked);
+      // For responses to connct requests, do not send the chunked encoding header:
```
Comment (mattklein123) [inline source/common/http/http1/codec_impl.cc:168]: typo connct, same below

File: test/integration/integration_test.cc [hunk 3]
```diff
@@ -1351,25 +1353,12 @@ TEST_P(IntegrationTest, ConnectWithChunkedBody) {
...
-
-  // Make sure the early payload is proxied without chunks or any other modifications.
-  ASSERT_TRUE(fake_upstream_connection->waitForData(
-      FakeRawConnection::waitForInexactMatch("\r\n\r\npayload")));
-
-  ASSERT_TRUE(fake_upstream_connection->write("return-payload"));
-  tcp_client->waitForData("\r\n\r\nreturn-payload", false);
-
-  tcp_client->close();
+  // The response will be rejected because chunked headers are not allowed with CONNECT upgrades.
```
Comment (chradcliffe) [inline test/integration/integration_test.cc:1358]: Let me see if I understand this correctly: does this means that Envoy will reject a proxied HTTP CONNECT if the upstream proxy server happens to send a TE header in the response?

This seems like it might break some upstream proxies that aren't carefully implemented. Is there a reason to reject these responses rather than just ignoring the header?

Comment (alyssawilk) [reply test/integration/integration_test.cc:1358]: Unfortunately Envoy will strip the TE header (that's pretty strongly asserted across the code base) and not add it back.  AFIK if there is a TE header there ought to be TE-chunked data, and so by altering that header we'd be sending potentially compromised payload.

Comment (chradcliffe) [reply test/integration/integration_test.cc:1358]: Just so I'm clear: do you mean Envoy strips TE whenever it appears or just for the CONNECT case?

Comment (alyssawilk) [reply test/integration/integration_test.cc:1358]: Envoy always strips TE for headers passing through Envoy.
It re-emits TE for HTTP/1.1 requests/responses which may have bodies if there's no content length provided.   Given for connect it is not allowed to have T-E it wouldn't know to reapply it, so it'd end up in an inconsistent state I'd like to avoid.
Worst case if there's a widely deployed proxy which does this illegal thing we could transform T-E into some Had-TE-Header and reinstate it, but I'd rather err on the side of simplicity until-if someone complains.

Comment (chradcliffe) [reply test/integration/integration_test.cc:1358]: That seems fair. Thanks for educating me :)
