### PR TITLE
sds: keep warming when dynamic inserted cluster can't be extracted secret entity

### LINKED ISSUE #11120: sds: cluster not warming while certificates are being fetched; immediately marked active
When creating clusters that reference SDS certificates, the warming behavior does not seem correct. My expectation is that until the secret is sent, the cluster will be marked as "warming" until the initial_fetch_timeout, and block the rest of initialization from occuring.

What I am actually seeing is initialization *is* blocked, but there is nothing indicating the clusters are warming.

Using this config:
`docker run -v $HOME/kube/local:/config -p 15000:15000 envoyproxy/envoy-dev -c /config/envoy-sds-lds.yaml --log-format-prefix-with-location 0 --reject-unknown-dynamic-fields`

with `envoy  version: 49efb9841a58ebdc43a666f55c445911c8e4181c/1.15.0-dev/Clean/RELEASE/BoringSSL`

and config files: 

cds.yaml:
```yaml
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: outbound_cluster_tls
  connect_timeout: 5s
  max_requests_per_connection: 1
  load_assignment:
    cluster_name: xds-grpc
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 8080
  type: STATIC
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
      common_tls_context:
        tls_certificate_sds_secret_configs:
          - name: "default"
            sds_config:
              initial_fetch_timeout: 20s
              api_config_source:
                api_type: GRPC
                grpc_services:
                  - envoy_grpc:
                      cluster_name: "sds-grpc"
                refresh_delay: 60s
        combined_validation_context:
          default_validation_context: {}
          validation_context_sds_secret_config:
            name: ROOTCA
            sds_config:
              initial_fetch_timeout: 20s
              api_config_source:
                api_type: GRPC
                grpc_services:
                - envoy_grpc:
                    cluster_name: sds-grpc    
```

envoy-sds-lds.yaml:
```yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 15000
node:
  id: id
  cluster: sdstest
dynamic_resources:
  lds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
        envoy_grpc:
          cluster_name: lds
  cds_config:
    path: /config/cds.yaml
static_resources:
  clusters:    
  - name: sds-grpc
    type: STATIC
    http2_protocol_options: {}
    connect_timeout: 5s
    lb_policy: ROUND_ROBIN
  - name: lds
    type: STATIC
    http2_protocol_options: {}
    connect_timeout: 5s
    lb_policy: ROUND_ROBIN
```

Basically what should happen here is we get a dynamic CDS cluster with SDS config. This SDS config fails, as the sds server is not setup. We have initial_fetch_timeout, so for 20s everything should be warming.

What we see instead:

* Stats are not showing warming:
```
cluster_manager.cds.init_fetch_timeout: 0
cluster_manager.cds.update_attempt: 1
cluster_manager.cds.update_failure: 0
cluster_manager.cds.update_rejected: 0
cluster_manager.cds.update_success: 1
cluster_manager.cds.update_time: 1588972075968
cluster_manager.cds.version: 17241709254077376921
cluster_manager.cluster_added: 3
cluster_manager.cluster_modified: 0
cluster_manager.cluster_removed: 0
cluster_manager.cluster_updated: 0
cluster_manager.cluster_updated_via_merge: 0
cluster_manager.update_merge_cancelled: 0
cluster_manager.update_out_of_merge_window: 0
cluster_manager.warming_clusters: 0
```

We also see `init_fetch_timeout` is `0`; this does not change after 20s

* LDS is not requested until 20s later, indicating the initial_fetch_timeout is respected. This can be seen in the logs:
(note - for simple testing I don't have a real LDS server, but we can see its not even attempted until 20s in)
```
[2020-05-08 21:07:55.967][1][info][upstream] cds: add 1 cluster(s), remove 2 cluster(s)
[2020-05-08 21:07:55.968][1][warning][config] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[2020-05-08 21:07:55.968][1][warning][config] Unable to establish new stream
[2020-05-08 21:07:55.968][1][warning][config] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[2020-05-08 21:07:55.968][1][warning][config] Unable to establish new stream
[2020-05-08 21:07:55.968][1][info][upstream] cds: add/update cluster 'outbound_cluster_tls'
[2020-05-08 21:07:55.968][1][info][main] starting main dispatch loop
[2020-05-08 21:07:56.703][1][warning][config] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[2020-05-08 21:07:56.703][1][warning][config] Unable to establish new stream
[2020-05-08 21:07:56.938][1][warning][config] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[2020-05-08 21:07:56.938][1][warning][config] Unable to establish new stream
[2020-05-08 21:07:57.135][1][warning][config] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[2020-05-08 21:07:57.135][1][warning][config] Unable to establish new stream
[2020-05-08 21:07:57.682][1][warning][config] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[2020-05-08 21:07:57.682][1][warning][config] Unable to establish new stream
[2020-05-08 21:07:58.671][1][warning][config] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[2020-05-08 21:07:58.671][1][warning][config] Unable to establish new stream
[2020-05-08 21:08:08.992][1][warning][config] StreamSecrets gRPC config stream closed: 14, no healthy upstream
[2020-05-08 21:08:08.992][1][warning][config] Unable to establish new stream
[2020-05-08 21:08:15.967][1][info][upstream] cm init: all clusters initialized
[2020-05-08 21:08:15.967][1][info][main] all clusters initialized. initializing init manager
[2020-05-08 21:08:15.967][1][warning][config] StreamListeners gRPC config stream closed: 14, no healthy upstream
```

* `dynamic_active_clusters` shows the cluster in cds.yaml. I would expect it to be "warming".

This example above is meant to simplify it, I have originally seen this with a normal deployment using ADS gRPC server (Istio) not just files.

### PR DESCRIPTION
**Pull request by Shikugawa**
Commit Message: fix #11120. This PR highly depends on #12783. Changed to keep warming if dynamic inserted clusters (when initialize doesn't finished) failed to extract TLS certificate and certificate validation context. They shouldn't be indicated as ACTIVE cluster.
Additional Description:
Risk Level: Mid
Testing: Unit
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by williamaronli** [comment]
@lizan @Shikugawa do we have any process for this PR. I think this is a fix for this release blocker issue: https://github.com/istio/istio/issues/22443

could we accelerate it

File: source/common/upstream/cluster_manager_impl.cc [hunk 1]
```diff
@@ -416,7 +418,42 @@ void ClusterManagerImpl::onClusterInit(Cluster& cluster) {
...
+      auto upstream_tls_context = MessageUtil::anyConvert<
+          envoy::extensions::transport_sockets::tls::v3::UpstreamTlsContext>(
+          cluster.info()->transportSocket().typed_config());
+      const auto& common_tls_context = upstream_tls_context.common_tls_context();
+
+      for (const auto& sds_secret_config :
+           common_tls_context.tls_certificate_sds_secret_configs()) {
+        auto& config_name = sds_secret_config.name();
+        auto& config_source = sds_secret_config.sds_config();
+        if (!secret_manager_.checkTlsCertificateEntityExists(config_source, config_name)) {
```
Comment (lambdai) [inline source/common/upstream/cluster_manager_impl.cc:433]: Could you add the comment when `checkTlsCertificateEntityExists` could return false?

What is the recovery path to fix if it's temporary failure? An implicit retry? Redeliver the same SDS config or cluster config?

Comment (Shikugawa) [reply source/common/upstream/cluster_manager_impl.cc:433]: I think that there is no secret entity should be treated as failed to initialize cluster, so that it should be warming forever. Do you have any idea about this to be more reliable?

Comment (Shikugawa) [reply source/common/upstream/cluster_manager_impl.cc:440]: comment addition done.

File: source/common/upstream/cluster_manager_impl.cc [hunk 2]
```diff
@@ -417,7 +420,47 @@ void ClusterManagerImpl::onClusterInit(Cluster& cluster) {
...
+      // Context, when it failed to extract them via SDS, it will fail to change cluster status from
+      // warming to active. In current implementation, there is no strategy to activate clusters
+      // which failed to initialize at once.
+      // TODO(shikugawa): Consider retry strategy of clusters which failed to activate at once.
+      for (const auto& sds_secret_config :
+           common_tls_context.tls_certificate_sds_secret_configs()) {
+        auto& config_name = sds_secret_config.name();
+        auto& config_source = sds_secret_config.sds_config();
+        if (!secret_manager_.checkTlsCertificateEntityExists(config_source, config_name)) {
+          ENVOY_LOG(info, "Failed to activate {} on {}", config_name, cluster.info()->name());
```
Comment (howardjohn) [inline source/common/upstream/cluster_manager_impl.cc:441]: Should this be a warning rather than info?

**Review by howardjohn — COMMENTED** [review]
I tried this out on my cluster, I believe this has introduced a crash:
```
2020-10-14T20:09:44.575361Z     critical        envoy assert    assert failure: !std::any_of(cluster_list.begin(), cluster_list.end(), [&existing_warming_cluster](Cluster* cluster) { return existing_warming_cluster->second->cluster_.get() == cluster; }).
2020-10-14T20:09:44.575747Z     critical        envoy backtrace Caught Aborted, suspect faulting address 0x53900000012
2020-10-14T20:09:44.575826Z     critical        envoy backtrace Backtrace (use tools/stack_decode.py to get line numbers):
2020-10-14T20:09:44.575838Z     critical        envoy backtrace Envoy version: 697c43c3b7d970bb01de403fcac2a9bf218a2562/1.17.0-dev/Clean/DEBUG/BoringSSL
2020-10-14T20:09:44.767932Z     critical        envoy backtrace #0: Envoy::SignalAction::sigHandler() [0x55b51b353a5c]
2020-10-14T20:09:44.768136Z     critical        envoy backtrace #1: __restore_rt [0x7fcf9c1a08a0]
2020-10-14T20:09:44.918339Z     critical        envoy backtrace #2: Envoy::Upstream::CdsApiImpl::onConfigUpdate() [0x55b51a5dd073]
2020-10-14T20:09:45.052725Z     critical        envoy backtrace #3: Envoy::Upstream::CdsApiImpl::onConfigUpdate() [0x55b51a5dc689]
2020-10-14T20:09:45.184972Z     critical        envoy backtrace #4: Envoy::Config::GrpcSubscriptionImpl::onConfigUpdate() [0x55b51ad67d41]
2020-10-14T20:09:45.352374Z     critical        envoy backtrace #5: Envoy::Config::GrpcMuxImpl::onDiscoveryResponse() [0x55b51ad6cece]
2020-10-14T20:09:45.542644Z     critical        envoy backtrace #6: Envoy::Config::GrpcStream<>::onReceiveMessage() [0x55b51ad72cd7]
2020-10-14T20:09:45.699578Z     critical        envoy backtrace #7: Envoy::Grpc::AsyncStreamCallbacks<>::onReceiveMessageRaw() [0x55b51ad72869]
2020-10-14T20:09:45.871283Z     critical        envoy backtrace #8: Envoy::Grpc::AsyncStreamImpl::onData() [0x55b51ada11f6]
2020-10-14T20:09:46.418313Z     critical        envoy backtrace #9: Envoy::Http::AsyncStreamImpl::encodeData() [0x55b51adae98b]
2020-10-14T20:09:46.823011Z     critical        envoy backtrace #10: Envoy::Router::Filter::onUpstreamData() [0x55b51ae2fa4e]
2020-10-14T20:09:47.082308Z     critical        envoy backtrace #11: Envoy::Router::UpstreamRequest::decodeData() [0x55b51ae460e6]
2020-10-14T20:09:47.248533Z     critical        envoy backtrace #12: Envoy::Http::ResponseDecoderWrapper::decodeData() [0x55b51a868b3c]
2020-10-14T20:09:47.404514Z     critical        envoy backtrace #13: Envoy::Http::Http2::ConnectionImpl::onFrameReceived() [0x55b51acdd652]
2020-10-14T20:09:47.595835Z     critical        envoy backtrace #14: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_18::operator()() [0x55b51ace9b00]
2020-10-14T20:09:47.765358Z     critical        envoy backtrace #15: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_18::__invoke() [0x55b51ace9ac5]
2020-10-14T20:09:47.938590Z     critical        envoy backtrace #16: session_call_on_frame_received [0x55b51b09d802]
2020-10-14T20:09:48.091134Z     critical        envoy backtrace #17: nghttp2_session_on_data_received [0x55b51b09f2ae]
2020-10-14T20:09:48.227366Z     critical        envoy backtrace #18: session_process_data_frame [0x55b51b0a3ba7]
2020-10-14T20:09:48.379274Z     critical        envoy backtrace #19: nghttp2_session_mem_recv [0x55b51b0a1cba]
2020-10-14T20:09:48.542720Z     critical        envoy backtrace #20: Envoy::Http::Http2::ConnectionImpl::innerDispatch() [0x55b51acd945f]
2020-10-14T20:09:48.767699Z     critical        envoy backtrace #21: Envoy::Http::Http2::ConnectionImpl::dispatch()::$_8::operator()() [0x55b51acebc4a]
2020-10-14T20:09:48.946253Z     critical        envoy backtrace #22: std::_Function_handler<>::_M_invoke() [0x55b51acebaeb]
2020-10-14T20:09:49.130159Z     critical        envoy backtrace #23: std::function<>::operator()() [0x55b51b011791]
2020-10-14T20:09:49.306681Z     critical        envoy backtrace #24: Envoy::Http::Utility::exceptionToStatus() [0x55b51b005438]
2020-10-14T20:09:49.501596Z     critical        envoy backtrace #25: Envoy::Http::Http2::ConnectionImpl::dispatch() [0x55b51acd8cbc]
2020-10-14T20:09:49.645102Z     critical        envoy backtrace #26: Envoy::Http::Http2::ConnectionImpl::dispatch() [0x55b51acd8ddb]
2020-10-14T20:09:49.886405Z     critical        envoy backtrace #27: Envoy::Http::CodecClient::onData() [0x55b51a99b41a]
2020-10-14T20:09:50.161979Z     critical        envoy backtrace #28: Envoy::Http::CodecClient::CodecReadFilter::onData() [0x55b51a99fde7]
2020-10-14T20:09:50.403897Z     critical        envoy backtrace #29: Envoy::Network::FilterManagerImpl::onContinueReading() [0x55b51a519e35]
2020-10-14T20:09:50.553617Z     critical        envoy backtrace #30: Envoy::Network::FilterManagerImpl::onRead() [0x55b51a51a2da]
2020-10-14T20:09:50.694561Z     critical        envoy backtrace #31: Envoy::Network::ConnectionImpl::onRead() [0x55b51a5022e1]
2020-10-14T20:09:50.862013Z     critical        envoy backtrace #32: Envoy::Network::ConnectionImpl::onReadReady() [0x55b51a50d156]
2020-10-14T20:09:51.022075Z     critical        envoy backtrace #33: Envoy::Network::ConnectionImpl::onFileEvent() [0x55b51a5090ef]
2020-10-14T20:09:51.162114Z     critical        envoy backtrace #34: Envoy::Network::ConnectionImpl::ConnectionImpl()::$_6::operator()() [0x55b51a51208e]
2020-10-14T20:09:51.330130Z     critical        envoy backtrace #35: std::_Function_handler<>::_M_invoke() [0x55b51a511f51]
2020-10-14T20:09:51.529677Z     critical        envoy backtrace #36: std::function<>::operator()() [0x55b51a4e9fba]
2020-10-14T20:09:51.726144Z     critical        envoy backtrace #37: Envoy::Event::FileEventImpl::mergeInjectedEventsAndRunCb() [0x55b51a4e8fcb]
2020-10-14T20:09:51.907346Z     critical        envoy backtrace #38: Envoy::Event::FileEventImpl::assignEvents()::$_1::operator()() [0x55b51a4e9589]
2020-10-14T20:09:52.064777Z     critical        envoy backtrace #39: Envoy::Event::FileEventImpl::assignEvents()::$_1::__invoke() [0x55b51a4e90d6]
2020-10-14T20:09:52.240164Z     critical        envoy backtrace #40: event_persist_closure [0x55b51b08029e]
2020-10-14T20:09:52.400234Z     critical        envoy backtrace #41: event_process_active_single_queue [0x55b51b07f8c8]
2020-10-14T20:09:52.558007Z     critical        envoy backtrace #42: event_process_active [0x55b51b07a08a]
2020-10-14T20:09:52.780285Z     critical        envoy backtrace #43: event_base_loop [0x55b51b078f3c]
2020-10-14T20:09:52.942622Z     critical        envoy backtrace #44: Envoy::Event::LibeventScheduler::run() [0x55b51b05dcb4]
2020-10-14T20:09:53.131037Z     critical        envoy backtrace #45: Envoy::Event::DispatcherImpl::run() [0x55b51a4def6a]
2020-10-14T20:09:53.305119Z     critical        envoy backtrace #46: Envoy::Server::InstanceImpl::run() [0x55b51a4698d2]
2020-10-14T20:09:53.532208Z     critical        envoy backtrace #47: Envoy::MainCommonBase::run() [0x55b51786f074]
2020-10-14T20:09:53.742968Z     critical        envoy backtrace #48: Envoy::MainCommon::run() [0x55b517872dce]
2020-10-14T20:09:53.945325Z     critical        envoy backtrace #49: Envoy::MainCommon::main() [0x55b51786fd7c]
2020-10-14T20:09:54.087207Z     critical        envoy backtrace #50: main [0x55b51786cd3b]
2020-10-14T20:09:54.087701Z     critical        envoy backtrace #51: __libc_start_main [0x7fcf9bdbeb97]
AsyncClient 0x25b4bf272300, stream_id_: 1817134650148571154
&stream_info_:
  StreamInfoImpl 0x25b4bf272490, protocol_: 1, response_code_: null, response_code_details_: null, health_check_request_: 0, route_name_:
```

I have gotten this fairly often, looks like ~5% of the time

**Comment by Shikugawa** [comment]
@howardjohn This problem is caused on cluster manager. So I will fix it on #12783. Thank you for reporting!

**Comment by Shikugawa** [comment]
@lizan ping

File: source/common/upstream/cluster_manager_impl.cc [hunk 3]
```diff
@@ -422,6 +425,40 @@ void ClusterManagerImpl::onClusterInit(Cluster& cluster) {
   // We have a situation that clusters will be immediately active, such as static and primary
   // cluster. So we must have this prevention logic here.
   if (cluster_data != warming_clusters_.end()) {
+    if (cluster.info()->transportSocket().has_typed_config()) {
```
Comment (lizan) [inline source/common/upstream/cluster_manager_impl.cc:428]: This shouldn't be part of cluster manager, it breaks the transport socket abstraction a lot by assuming UpstreamTlsContext is the only TLS impl and how TLS transport socket will behave.

Instead, we should use the ready callback added in #13516, or add some `isready` method in transport socket factory, and check whether secret is ready or not.

**Review by lizan — CHANGES_REQUESTED** [review]

File: source/common/upstream/cluster_manager_impl.cc (hunk 3 above)
Comment (Shikugawa) [reply source/common/upstream/cluster_manager_impl.cc]: Done. like this?

File: include/envoy/network/transport_socket.h [hunk 4]
```diff
@@ -233,6 +233,11 @@ class TransportSocketFactory {
    * are already loaded.
    */
   virtual void addReadyCb(std::function<void()> callback) PURE;
+
+  /**
+   * Check whether matched transport socket which required to use secret information is available.
+   */
+  virtual bool secureTransportReady() const PURE;
```
Comment (lizan) [inline include/envoy/network/transport_socket.h:240]: I would just name this `isReady`.

File: source/extensions/transport_sockets/tls/ssl_socket.cc [hunk 5]
```diff
@@ -388,6 +389,29 @@ void ClientSslSocketFactory::addReadyCb(std::function<void()> callback) {
   }
 }
 
+bool ClientSslSocketFactory::secureTransportReady() const {
+  if (!implementsSecureTransport()) {
```
Comment (lizan) [inline source/extensions/transport_sockets/tls/ssl_socket.cc:393]: this always returns true.

File: source/extensions/transport_sockets/tls/ssl_socket.cc [hunk 6]
```diff
@@ -388,6 +389,29 @@ void ClientSslSocketFactory::addReadyCb(std::function<void()> callback) {
...
+    return false;
+  }
+  // If there is no secret entity, currently supports only TLS Certificate and Validation
+  // Context, when it failed to extract them via SDS, it will fail to change cluster status from
+  // warming to active. In current implementation, there is no strategy to activate clusters
+  // which failed to initialize at once.
+  // TODO(shikugawa): Consider retry strategy of clusters which failed to activate at once.
+  const auto& tls_certificate_sds_configs = config_->tlsCertificateSdsConfigs();
+  for (const auto& config : tls_certificate_sds_configs) {
+    if (!secret_manager_.checkTlsCertificateEntityExists(config.sds_config(), config.name())) {
```
Comment (lizan) [inline source/extensions/transport_sockets/tls/ssl_socket.cc:403]: I think we can use `tls_certificate_providers_` from ContextConfigImpl (you may need to expose it via methods) to do this?

**Review by lizan — CHANGES_REQUESTED** [review]

File: include/envoy/network/transport_socket.h (hunk 4 above)
Comment (Shikugawa) [reply include/envoy/network/transport_socket.h:240]: It will be always false when raw buffer socket. So I prefer `secureTransportReady`.

Comment (lizan) [reply include/envoy/network/transport_socket.h:240]: actually that would be oppose, raw buffer socket should always return `true` for this. It will be consistent with `addReadyCb` behavior above.

Comment (Shikugawa) [reply include/envoy/network/transport_socket.h]: done

File: source/extensions/transport_sockets/tls/ssl_socket.cc (hunk 5 above)
Comment (Shikugawa) [reply source/extensions/transport_sockets/tls/ssl_socket.cc]: done

File: source/extensions/transport_sockets/tls/ssl_socket.cc (hunk 6 above)
Comment (Shikugawa) [reply source/extensions/transport_sockets/tls/ssl_socket.cc]: done

File: source/extensions/transport_sockets/tls/ssl_socket.cc [hunk 7]
```diff
@@ -362,6 +362,11 @@ void ClientSslSocketFactory::onAddOrUpdateSecret() {
   stats_.ssl_context_update_by_sds_.inc();
 }
 
+bool ClientSslSocketFactory::isReady() const {
+  return config_->checkTlsCertificateEntityExists() &&
```
Comment (lizan) [inline source/extensions/transport_sockets/tls/ssl_socket.cc:366]: I think you can simply make those two function into `isSecretsReady` in ContextConfig interface.

File: source/extensions/transport_sockets/tls/context_config_impl.h [hunk 8]
```diff
@@ -99,6 +96,11 @@ class ContextConfigImpl : public virtual Ssl::ContextConfig {
 
   Ssl::HandshakerFactoryCb handshaker_factory_cb_;
   Ssl::HandshakerCapabilities capabilities_;
+
+protected:
+  std::vector<Secret::TlsCertificateConfigProviderSharedPtr> tls_certificate_providers_;
+  Secret::CertificateValidationContextConfigProviderSharedPtr
+      certificate_validation_context_provider_;
```
Comment (lizan) [inline source/extensions/transport_sockets/tls/context_config_impl.h:103]: just double-checking, is the re-order fine? also style guide says in a class it should be `public` -> `protected` -> `private` order.

File: include/envoy/ssl/context_config.h [hunk 9]
```diff
@@ -111,6 +111,16 @@ class ClientContextConfig : public virtual ContextConfig {
...
+
+  /**
+   * Check whether TLS Certificate entity was being extracted from SDS server.
+   */
+  virtual bool checkTlsCertificateEntityExists() const PURE;
+
+  /**
+   * Check whether certificate validation context entity was being extracted from SDS server.
+   */
+  virtual bool checkCertificateValidationContextEntityExists() const PURE;
```
Comment (lizan) [inline include/envoy/ssl/context_config.h:123]: do we need these to be separate? see comment below.

File: source/extensions/transport_sockets/tap/tap.cc [hunk 10]
```diff
@@ -66,6 +66,8 @@ bool TapSocketFactory::implementsSecureTransport() const {
   return transport_socket_factory_->implementsSecureTransport();
 }
 
+bool TapSocketFactory::isReady() const { NOT_REACHED_GCOVR_EXCL_LINE; }
```
Comment (lizan) [inline source/extensions/transport_sockets/tap/tap.cc:69]: `return transport_socket_factory_->isReady()`?

File: source/extensions/transport_sockets/tls/ssl_socket.cc [hunk 11]
```diff
@@ -403,6 +408,8 @@ void ServerSslSocketFactory::onAddOrUpdateSecret() {
   stats_.ssl_context_update_by_sds_.inc();
 }
 
+bool ServerSslSocketFactory::isReady() const { NOT_REACHED_GCOVR_EXCL_LINE; }
```
Comment (lizan) [inline source/extensions/transport_sockets/tls/ssl_socket.cc:411]: shall we just implement this?

**Review by lizan — COMMENTED** [review]
In right track, thanks.

File: source/extensions/transport_sockets/tls/ssl_socket.cc (hunk 7 above)
Comment (Shikugawa) [reply source/extensions/transport_sockets/tls/ssl_socket.cc]: done

File: source/extensions/transport_sockets/tls/context_config_impl.h (hunk 8 above)
Comment (Shikugawa) [reply source/extensions/transport_sockets/tls/context_config_impl.h]: done

File: include/envoy/ssl/context_config.h (hunk 9 above)
Comment (Shikugawa) [reply include/envoy/ssl/context_config.h]: done

File: source/extensions/transport_sockets/tap/tap.cc (hunk 10 above)
Comment (Shikugawa) [reply source/extensions/transport_sockets/tap/tap.cc]: done

File: source/extensions/transport_sockets/tls/ssl_socket.cc (hunk 11 above)
Comment (Shikugawa) [reply source/extensions/transport_sockets/tls/ssl_socket.cc]: done

**Review by lizan — APPROVED** [review]
LGTM, @htuch or @mattklein123 for non-Tetrands review.

File: source/common/upstream/cluster_manager_impl.cc [hunk 12]
```diff
@@ -422,6 +422,17 @@ void ClusterManagerImpl::onClusterInit(Cluster& cluster) {
   // We have a situation that clusters will be immediately active, such as static and primary
   // cluster. So we must have this prevention logic here.
   if (cluster_data != warming_clusters_.end()) {
+    Network::TransportSocketFactory& factory =
+        cluster.info()->transportSocketMatcher().resolve(&cluster.info()->metadata()).factory_;
+    // If there is no secret entity, currently supports only TLS Certificate and Validation
+    // Context, when it failed to extract them via SDS, it will fail to change cluster status from
+    // warming to active. In current implementation, there is no strategy to activate clusters
+    // which failed to initialize at once.
+    // TODO(shikugawa): Consider retry strategy of clusters which failed to activate at once.
```
Comment (htuch) [inline source/common/upstream/cluster_manager_impl.cc:431]: This seems a bit dicey. If I'm reading the code/comments correctly, we have a race condition in cluster warming where a slow SDS update will leave a cluster stuck in the warming state forever.

Comment (Shikugawa) [reply source/common/upstream/cluster_manager_impl.cc:431]: I can't imagine what problem will cause if warming state is being stuck forever. Sorry. It will be an expected behavior. What you say is that the retry comment is not required, isn't it?

Comment (htuch) [reply source/common/upstream/cluster_manager_impl.cc:431]: The issue is that this is very surprising behavior to an Envoy operator who experiences a race between SDS availability and cluster warming. In fact, I'd argue that this effectively breaks eventual warming semantics.

It looks like, from the comment, that the right long-term solution is to continue warming when SDS makes the necessary secret available.

I think we should have this behavior. If you don't want to do it in this PR, then we should at least put in place a runtime flag that disables this new behavior by default, and leave it disabled until we actually fix warming for folks who are relying on eventual consistency.

Comment (Shikugawa) [reply source/common/upstream/cluster_manager_impl.cc:431]: Sure. So to speak, what you said is that we should implement to be available by keeping warming after no-available secret entity behavior occured, right? This feature is the blocker of next Istio release. So I overcome this by setting runtime feature flag temporary.

File: source/common/runtime/runtime_features.cc [hunk 13]
```diff
@@ -109,7 +109,8 @@ constexpr const char* disabled_runtime_features[] = {
     "envoy.reloadable_features.test_feature_false",
     // gRPC Timeout header is missing (#13580)
     "envoy.reloadable_features.ext_authz_measure_timeout_on_check_created",
-
+    // The cluster which can't extract secret entity by SDS to be warming and never activate.
+    "envoy.reloadable_features.cluser_keep_warming_no_secret_entity",
```
Comment (htuch) [inline source/common/runtime/runtime_features.cc:113]: Nit: s/clusr/cluster

File: test/common/upstream/cluster_manager_impl_test.cc [hunk 14]
```diff
@@ -2344,6 +2348,9 @@ TEST_F(ClusterManagerImplTest,
 }
 
 TEST_F(ClusterManagerImplTest, DynamicAddedAndKeepWarmingWithoutTlsCertificateEntity) {
+  TestScopedRuntime scoped_runtime;
+  Runtime::LoaderSingleton::getExisting()->mergeValues(
```
Comment (htuch) [inline test/common/upstream/cluster_manager_impl_test.cc:2352]: Do we have tests for the old behavior when this is disabled?

File: source/common/upstream/cluster_manager_impl.cc [hunk 15]
```diff
@@ -428,8 +428,12 @@ void ClusterManagerImpl::onClusterInit(Cluster& cluster) {
     // Context, when it failed to extract them via SDS, it will fail to change cluster status from
     // warming to active. In current implementation, there is no strategy to activate clusters
     // which failed to initialize at once.
-    // TODO(shikugawa): Consider retry strategy of clusters which failed to activate at once.
-    if (!factory.isReady()) {
+    // TODO(shikugawa): To implement to be available by keeping warming after no-available secret
+    // entity behavior occured. And remove
+    // `envoy.reloadable_features.cluser_keep_warming_no_secret_entity` runtime feature flag.
+    auto keep_warming_enabled = Runtime::runtimeFeatureEnabled(
```
Comment (htuch) [inline source/common/upstream/cluster_manager_impl.cc:434]: Nit: `const bool`

**Review by htuch — COMMENTED** [review]
@lizan are you in agreement here from an API shepherd angle?

File: source/common/runtime/runtime_features.cc (hunk 13 above)
Comment (Shikugawa) [reply source/common/runtime/runtime_features.cc]: done

File: test/common/upstream/cluster_manager_impl_test.cc (hunk 14 above)
Comment (Shikugawa) [reply test/common/upstream/cluster_manager_impl_test.cc:2388]: added.

File: source/common/upstream/cluster_manager_impl.cc (hunk 15 above)
Comment (Shikugawa) [reply source/common/upstream/cluster_manager_impl.cc]: done

**Review by htuch — COMMENTED** [review]
LGTM modulo @lizan confirming the behavioral assertions I made. Also, can you open a tracking issue and reference it in the PR for the future work to be done to keep warming after secret failure?

**Comment by lizan** [comment]
@htuch SGTM.

**Review by lizan — APPROVED** [review]
