### PR TITLE
lua filter: ensure active_request_ is verified before deletion Fixes #38017

### LINKED ISSUE #38017: Lua filter causes envoy to SIGSEGV upon removing some headers
(already reported to envoy-security@, was approved to post in here)

*Title*: Lua filter causes envoy to SIGSEGV upon removing `:status` header

*Description*:

If you remove the :status header in the response, which is a questionable operation semantically, but something that's allowed programatically, envoy SIGSEGVs.

*Repro steps*:

Add the following snippet as a lua filter:

                  function envoy_on_response(response_handle)
                    local response_headers = response_handle:headers()
                    response_headers:remove(":status")
                    response_handle:body(true):setBytes("hello world")
                  end

(I'm not providing the detailed stats as this works with the most trivial setup on envoys from 1.28 to 1.33, so it's not dependent on the specific configuration details. It's reproduced with both a raw config and e.g. istio).

*Call Stack*:

```
# curl localhost:8089
[2025-01-14 20:04:51.455][355][critical][backtrace] [./source/server/backtrace.h:129] Caught Segmentation fault, suspect faulting address 0x160
[2025-01-14 20:04:51.455][355][critical][backtrace] [./source/server/backtrace.h:113] Backtrace (use tools/stack_decode.py to get line numbers):
[2025-01-14 20:04:51.455][355][critical][backtrace] [./source/server/backtrace.h:114] Envoy version: b0f43d67aa25c1b03c97186a200cc187f4c22db3/1.33.0/Clean/RELEASE/BoringSSL
[2025-01-14 20:04:51.455][355][critical][backtrace] [./source/server/backtrace.h:116] Address mapping: 555c5948b000-555c5c02e000 /usr/local/bin/envoy
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #0: [0x7f715d904520]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #1: [0x555c5b57ce94]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #2: [0x555c5b57d0a4]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #3: [0x555c5b56a9d6]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #4: [0x555c5b61c06d]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #5: [0x555c5b614038]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #6: [0x555c5b614b1e]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #7: [0x555c5b61b72e]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #8: [0x555c5b87709a]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #9: [0x555c5b8771b3]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #10: [0x555c5b61fab0]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #11: [0x555c5b61e8e7]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #12: [0x555c5b615354]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #13: [0x555c5b619b66]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #14: [0x555c5b5e8dd9]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #15: [0x555c5b5e981c]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #16: [0x555c5b5fbbb5]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #17: [0x555c5b5d885b]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #18: [0x555c5b35bd46]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #19: [0x555c5b37dcb3]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #20: [0x555c5b37d4b9]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #21: [0x555c5b7fef0e]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #22: [0x555c5b4ee1e4]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #23: [0x555c5b4edad8]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #24: [0x555c5b4f3188]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #25: [0x555c5b4f0d9a]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #26: [0x555c5b4fac86]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #27: [0x555c5af87696]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #28: [0x555c5af88be5]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #29: [0x555c5ba01510]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #30: [0x555c5b9ffe51]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #31: [0x555c5af7ec8d]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #32: [0x555c5ba88372]
[2025-01-14 20:04:51.456][355][critical][backtrace] [./source/server/backtrace.h:123] #33: [0x7f715d956ac3]
ActiveStream 0x4833f713100, stream_id_: 15666871359428048408&filter_manager_:
  FilterManager 0x4833f7131b0, state_.has_1xx_headers_: 0, state_.decoder_filter_chain_complete_: 1, state_.encoder_filter_chain_complete_: 1, state_.observed_decode_end_stream_: 1, state_.observed_encode_end_stream_: 1
  filter_manager_callbacks_.requestHeaders():
    ':authority', 'localhost:8089'
    ':path', '/'
    ':method', 'GET'
    ':scheme', 'http'
    'user-agent', 'curl/7.81.0'
    'accept', '*/*'
    'x-forwarded-proto', 'http'
    'x-request-id', '73bd28e7-a184-41dd-88b3-60c3e3c6fc8e'
    'x-envoy-expected-rq-timeout-ms', '15000'
  filter_manager_callbacks_.requestTrailers():   null
  filter_manager_callbacks_.responseHeaders():
    ':status', '502'
    'content-length', '32'
    'content-type', 'text/plain'
    'date', 'Tue, 14 Jan 2025 20:04:51 GMT'
    'server', 'envoy'
  filter_manager_callbacks_.responseTrailers():   null
  &streamInfo():
    StreamInfoImpl 0x4833f7132e8, protocol_: 1, response_code_: 502, response_code_details_: filter_removed_required_response_headers{missing_required_header:_:status}, attempt_count_: 1, health_check_request_: 0, getRouteName():     upstream_info_:
      UpstreamInfoImpl 0x4833f4e17b8, upstream_connection_id_: null
    OverridableRemoteConnectionInfoSetterStreamInfo 0x4833f7132e8, remoteAddress(): [127.0.0.1:50366](http://127.0.0.1:50366/), directRemoteAddress(): [127.0.0.1:50366](http://127.0.0.1:50366/), localAddress(): [127.0.0.1:8089](http://127.0.0.1:8089/)
ConnectionImpl 0x4833f458900, connecting_: 1, bind_error_: 0, state(): Closed, read_buffer_limit_: 1048576
socket_:
  ListenSocketImpl 0x4833f519490, transport_protocol_:
  connection_info_provider_:
    ConnectionInfoSetterImpl 0x4833f541998, remote_address_: [127.0.0.1:16686](http://127.0.0.1:16686/), direct_remote_address_: [127.0.0.1:16686](http://127.0.0.1:16686/), local_address_: [127.0.0.1:46484](http://127.0.0.1:46484/), server_name_:
curl: (52) Empty reply from server
[1]+  Segmentation fault      envoy -c config
```

### PR DESCRIPTION
**Pull request by leocfig**
Commit Message:
Lua filter was removing ":status" and then setting a response body, which was causing envoy to terminate with a SIGSEGV. The issue occurred because "onEncodeComplete()" attempted to delete "activerequest" via "deferredDelete()", but "activerequest" had already been deleted earlier, leading to a segmentation fault. This fix ensures that "activerequest" is only deleted once, preventing double deletion. This is done by verifying that "activerequest" is not null before the existing check of "activerequest->remotecomplete".

Additional Description:
I compiled Envoy in release mode (using the -c flag) and also ran the new test in release mode to verify the fix.

Risk Level: Low

Testing:
I added a new integration test in "lua_integration_test.cc" file specifically for this bug. Without the fix, the test fails; with it applied, the test passes successfully.

Fixes #38017

### CODE REVIEW

**Comment by leocfig** [comment]
I believe the pipeline is failing because the tests are running in debug mode. In this mode, the code eventually reaches a verification where [ENVOY_BUG()](https://github.com/envoyproxy/envoy/blob/6c38b6a020e7577ccffff9e56c7b1b88cd9056a9/source/common/http/utility.cc#L613) forcefully aborts the program, when in **debug** mode. What my fix avoids is the program ending with a segmentation fault in **release** mode.

**Comment by KBaichoo** [comment]
Hey @leocfig ,

Thank you for working on this.

We do run CI (strangely under pre-check) with the release mode run of tests: https://github.com/envoyproxy/envoy/actions/runs/14021237617/job/39253502671

It seems like the test is still failing in release mode. 

You can also try wrapping the test with a macro similar to https://github.com/envoyproxy/envoy/blob/2533c82d653c3da2c3f69568ab8478ce55a1051b/test/test_common/utility.h#L99 to catch the error depending on DEBUG vs release build

/wait

**Comment by leocfig** [comment]
Thanks for the suggestion! I’ll first investigate why it’s still failing in release mode since it passed locally, then update the test to use EXPECT_ENVOY_BUG.

**Comment by leocfig** [comment]
I realized that my test was failing in the pipeline despite passing locally because my code was not up-to-date with a recent commit that modified the `lua_integration_test.cc` file. After reviewing the changes to this file, I updated my test accordingly.

Additionally, I added the `#ifdef NDEBUG` preprocessor directive to ensure the test only runs in release mode. This was necessary because in **debug** mode, the program aborts before reaching the segmentation fault, making the test irrelevant in that mode.

**Comment by leocfig** [comment]
I noticed that the `//test/extensions/filters/http/dynamic_forward_proxy:legacy_proxy_filter_integration_test` target is failing in the pipeline, even though it passes when I run it locally. However, I believe this issue is unrelated to my null verification.

**Comment by KBaichoo** [comment]
/wait-any

There's some conversation on slack on how to possibly better address this as it slightly circumvents the fix from https://github.com/envoyproxy/envoy/pull/16745

**Comment by leocfig** [comment]
I’ve implemented the suggested changes, and it works as expected! I’ve also left a message on Slack with further details.

**Comment by KBaichoo** [comment]
hey @leocfig ,

did you push the changes you referenced in https://github.com/envoyproxy/envoy/pull/38863#issuecomment-2787511347?

**Comment by leocfig** [comment]
Hey! Yes, I’ve just now pushed the changes mentioned in [#38863(comment)](https://github.com/envoyproxy/envoy/pull/38863#issuecomment-2787511347). Let me know if anything looks off or needs adjustment.

File: source/common/http/filter_manager.cc [hunk 1]
```diff
@@ -1224,6 +1225,27 @@ void FilterManager::maybeContinueEncoding(StreamEncoderFilters::Iterator continu
...
+  // Check if the filter chain above did not remove critical headers or set malformed header values.
+  // We could do this at the codec in order to prevent other places than the filter chain from
+  // removing critical headers, but it will come with the implementation complexity.
+  // See the previous attempt (#15658) for detail, and for now we choose to protect only against
+  // filter chains.
+  auto validate_required_headers = absl::MakeCleanup([&]() {
+    const auto status = HeaderUtility::checkRequiredResponseHeaders(headers);
+    if (!status.ok()) {
+      // If the check failed, then we reply with BadGateway, and stop the further processing.
+      sendLocalReply(
```
Comment (KBaichoo) [inline source/common/http/filter_manager.cc:1241]: this might be a problem if the filter already sent a local reply e.g. prior we only did this if we made it here https://github.com/envoyproxy/envoy/pull/38863/files#diff-e91327a311d8130daac76a7c43dca2ae70d5a6a37dc7fdb658cf25b2fde88cc9R1309 but we might now exit here: https://github.com/envoyproxy/envoy/pull/38863/files#diff-e91327a311d8130daac76a7c43dca2ae70d5a6a37dc7fdb658cf25b2fde88cc9R1300

so we might want to modify the filter_manager a bit more to ensure we don't end up sending multiple of these.

**Review by KBaichoo — COMMENTED** [review]
/wait

File: source/common/http/filter_manager.cc (hunk 1 above)
Comment (leocfig) [reply source/common/http/filter_manager.cc:1241]: Good point, I’ll take a closer look at this and follow up with a fix. Thank you for the help!

Comment (leocfig) [reply source/common/http/filter_manager.cc:1241]: I've been trying to fix the issue, but I'm not sure about this part — do we want to remove the `sendLocalReply` call that happens inside the `if (!continue_iteration)` block? Or should we keep it there and just make sure we don't end up calling `sendLocalReply` again later on, in case it does enter the `if (!continue_iteration)` block?

Comment (KBaichoo) [reply source/common/http/filter_manager.cc:1241]: I think what we want is to only call sendLocalReply here if sendLocalReply has not already been called https://github.com/envoyproxy/envoy/blob/3be167b56628d6eb1564c2db2826b3a485e4cdaf/source/common/http/filter_manager.cc#L961

Comment (leocfig) [reply source/common/http/filter_manager.cc:1241]: Perhaps we could add a bool to check for that case. This bool would be added in [here](https://github.com/envoyproxy/envoy/blob/3be167b56628d6eb1564c2db2826b3a485e4cdaf/source/common/http/filter_manager.h#L963), like for example `bool local_reply_sent_{}` and we would only call `sendLocalReply` in the cleanup function if `local_reply_sent_` is false.

File: source/common/http/filter_manager.cc [hunk 2]
```diff
@@ -1236,12 +1236,13 @@ void FilterManager::encodeHeaders(ActiveStreamEncoderFilter* filter, ResponseHea
...
   auto validate_required_headers = absl::MakeCleanup([&]() {
     const auto status = HeaderUtility::checkRequiredResponseHeaders(headers);
-    if (!status.ok()) {
+    if (!status.ok() && !state_.local_reply_sent_) {
       // If the check failed, then we reply with BadGateway, and stop the further processing.
       sendLocalReply(
           Http::Code::BadGateway, status.message(), nullptr, absl::nullopt,
           absl::StrCat(StreamInfo::ResponseCodeDetails::get().FilterRemovedRequiredResponseHeaders,
                        "{", StringUtil::replaceAllEmptySpace(status.message()), "}"));
+      state_.local_reply_sent_ = true;
```
Comment (KBaichoo) [inline source/common/http/filter_manager.cc:1245]: I think we want to set this here https://github.com/envoyproxy/envoy/blob/3be167b56628d6eb1564c2db2826b3a485e4cdaf/source/common/http/filter_manager.cc#L968 -- otherwise if a filter sends the local reply we'd miss it.

**Review by KBaichoo — COMMENTED** [review]
Sorry for the delay -- I think this is nearly there. This is a very complex part of the code, so nice job tackling some of the intricacies here.

/wait

File: source/common/http/filter_manager.cc (hunk 2 above)
Comment (leocfig) [reply source/common/http/filter_manager.cc]: Thanks for pointing that out! I've updated the code accordingly.

**Comment by KBaichoo** [comment]
several tests seem to be meaningfully failing: https://github.com/envoyproxy/envoy/actions/runs/14775459103/job/41482826530

/wait

**Comment by leocfig** [comment]
Yes, it looks like the latest change introduced some compile-time errors. Would you recommend reverting it for now, or should I try to fix it directly?

**Comment by KBaichoo** [comment]
Yes, it looks like the latest change introduced some compile-time errors. Would you recommend reverting it for now, or should I try to fix it directly?
> It seems like these are test failures failing during running across a slew of builds. I think if you reverted the changes to signal state to avoid multiple local replies we'd _likely_ have a bug there.

**Comment by leocfig** [comment]
Thanks for the clarification. Just to confirm, would you recommend exploring an alternative approach to adding the `local_reply_sent_` boolean, or is that direction generally fine and I should focus on fixing the current test failures?

**Comment by KBaichoo** [comment]
>Just to confirm, would you recommend exploring an alternative approach to adding the local_reply_sent_ boolean, or is that direction generally fine and I should focus on fixing the current test failures?

If you can think of a better fix that covers the cases we've discussed without the tradeoffs that sgtm. It's a bit hard to know without digging into the tests more if we've violating and assumption of the test or if we've introduced a regression.

**Comment by leocfig** [comment]
Understood, I’ll take a closer look and explore if there’s a cleaner alternative.

**Comment by leocfig** [comment]
I have been analyzing the situation around the management of `local_reply_sent_` and its interaction with local replies. Setting it at [this location](https://github.com/envoyproxy/envoy/blob/3be167b56628d6eb1564c2db2826b3a485e4cdaf/source/common/http/filter_manager.cc#L968) introduces a regression in behavior. However, keeping it in its previous position leads to a segmentation fault in certain scenarios—for instance, during the `SendLocalReplyDuringEncodingGrpcClassiciation` test in test/common/http/filter_manager_test.cc.

**Comment by leocfig** [comment]
I moved the assignment of` local_reply_sent_ = true` outside of `sendLocalReply()`, ensuring it's set earlier in the control flow. This is necessary because the code path may invoke `sendLocalReply()` before encodeHeaders() is reached, leading to inconsistent state handling otherwise and regression.

Additionally, I addressed the segmentation fault in the test by safely accessing `responseHeaders()` using `.ref`() only after checking `has_value()`, inside the `MakeCleanup` callback.

**Comment by leocfig** [comment]
I've noticed that the failing test is passing locally, so I suspect the failure may be unrelated to the changes in this PR.

**Comment by KBaichoo** [comment]
nice work, I'll circle back here tomorrow to review this. Test failure doesn't look related.

/retest

File: test/extensions/filters/http/lua/lua_integration_test.cc [hunk 3]
```diff
@@ -2026,5 +2026,63 @@ name: lua
   cleanup();
 }
 
+#ifdef NDEBUG
```
Comment (KBaichoo) [inline test/extensions/filters/http/lua/lua_integration_test.cc:2029]: Can you add a comment on why we're not running this under debug? It's not immediately clear to a reader.

File: test/extensions/filters/http/lua/lua_integration_test.cc [hunk 4]
```diff
@@ -2026,5 +2026,63 @@ name: lua
...
+  default_source_code:
+    inline_string: |
+      function envoy_on_response(response_handle)
+        local response_headers = response_handle:headers()
+        response_headers:remove(":status")
+        response_handle:body(true):setBytes("hello world")
+      end
+)EOF";
+
+  std::string route_config =
```
Comment (KBaichoo) [inline test/extensions/filters/http/lua/lua_integration_test.cc]: const

File: source/common/http/filter_manager.cc [hunk 5]
```diff
@@ -1224,6 +1225,32 @@ void FilterManager::maybeContinueEncoding(StreamEncoderFilters::Iterator continu
...
+
+  // Flag to control early return
+  bool should_exit = false;
+
+  // Check if the filter chain above did not remove critical headers or set malformed header values.
+  // We could do this at the codec in order to prevent other places than the filter chain from
+  // removing critical headers, but it will come with the implementation complexity.
+  // See the previous attempt (#15658) for detail, and for now we choose to protect only against
+  // filter chains.
+  auto validate_required_headers = absl::MakeCleanup([&]() {
```
Comment (KBaichoo) [inline source/common/http/filter_manager.cc]: Can you guard this with a runtime flag:
https://github.com/envoyproxy/envoy/blob/39339150a76959fac0ef47b85441f38fe27d061c/source/common/runtime/runtime_features.cc#L11-L31

Given this is in a complex part of the codebase it'd be helpful for it to be controllable with a feature flag

File: source/common/http/filter_manager.cc [hunk 6]
```diff
@@ -1224,6 +1225,32 @@ void FilterManager::maybeContinueEncoding(StreamEncoderFilters::Iterator continu
 
 void FilterManager::encodeHeaders(ActiveStreamEncoderFilter* filter, ResponseHeaderMap& headers,
                                   bool end_stream) {
+
+  // Flag to control early return
+  bool should_exit = false;
+
+  // Check if the filter chain above did not remove critical headers or set malformed header values.
```
Comment (KBaichoo) [inline source/common/http/filter_manager.cc]: It might be useful to specify that this is done as a cleanup function so that it can be invoked if we early return stopping iteration  https://github.com/envoyproxy/envoy/pull/38863/files#diff-e91327a311d8130daac76a7c43dca2ae70d5a6a37dc7fdb658cf25b2fde88cc9R1305

**Comment by leocfig** [comment]
I've incorporated the requested changes, please let me know if they're in line with what you had in mind. If anything still needs adjusting, I'm happy to update it. Thanks again for your time reviewing this!

**Review by KBaichoo — APPROVED** [review]
Thanks this LGTM. We might want to wait until after the next release to merge just incase something was missed.

/assign @yanavlasov 

for senior maintainer signoff

**Comment by leocfig** [comment]
Understood, I’ll be available in case any follow-ups or adjustments are needed.
Appreciate the time spent reviewing!

File: source/common/http/filter_manager.cc [hunk 7]
```diff
@@ -1224,6 +1225,37 @@ void FilterManager::maybeContinueEncoding(StreamEncoderFilters::Iterator continu
 
 void FilterManager::encodeHeaders(ActiveStreamEncoderFilter* filter, ResponseHeaderMap& headers,
                                   bool end_stream) {
+
+  // Flag to control early return
+  bool should_exit = false;
```
Comment (yanavlasov) [inline source/common/http/filter_manager.cc]: Thanks @leocfig for working on this. This change however fixed only one error condition. There is a bigger bug in the `ActiveStreamFilterBase::commonContinue()` function. It checks if the filter chain can be ran [only at the start](https://github.com/envoyproxy/envoy/blob/d7eb05aae65c08921256705c12f4dc7436092dfd/source/common/http/filter_manager.cc#L51) . However it needs to recheck this condition after each doNNN() call on lines 85, 93, 96 and 104. Every doNNN call can cause a sendLocalReply or stream reset and no filters should be continued after that.

A better change would be to put the additional canContinue() checks. This should resolve the problem.

**Comment by leocfig** [comment]
I've restructured the logic in `commonContinue()` so that `canContinue()` is now re-evaluated after each `doNNN()` call, as recommended. Let me know if there's anything else you'd like me to adjust.
