### PR TITLE
upstream: ensure hosts are not shared between resolve targets

### LINKED ISSUE #4590: Reconcile the differences in behavior between STRICT_DNS and EDS
*Description*:

This is a follow-up discussion of https://github.com/envoyproxy/envoy/issues/4548 and https://github.com/envoyproxy/envoy/pull/4575.

From @snowp in https://github.com/envoyproxy/envoy/issues/4548#issuecomment-426495302: I think we might want to follow up with figuring out how to reconcile the differences in behavior between STRICT_DNS and EDS, either by getting rid of the differences or acknowledging that they'll be different and making that clearer in code. For instance, EDS guarantees that a host only exists in one priority and will reuse the host instance (and consequently HC status etc.) when a host moves between priorities. Neither of these is true for STRICT_DNS AFAIK.

### LINKED ISSUE #5013: crash deleting unknown host from health checker
We have seen this crash a few times. Somehow we are trying to delete a host that the health checker doesn't know about. I would imagine this somehow has to do with us specifying the same DNS host multiple times but I'm not sure. 

cc @dio @snowp for recent work in this area. cc @tonya11en who can explain the config we use that might be causing this. I haven't looked into this in any detail yet.

```
Backtrace:
#0  operator() (this=0x6ba7428, __den=23, __num=<optimized out>) at /usr/include/c++/5/bits/hashtable_policy.h:446
#0  operator() (this=0x6ba7428, __den=23, __num=<optimized out>) at /usr/include/c++/5/bits/hashtable_policy.h:446
#1  _M_bucket_index (this=0x6ba7428, __n=23, __p=0x0) at /usr/include/c++/5/bits/hashtable_policy.h:1180
#2  _M_bucket_index (this=0x6ba7428, __n=0x0) at /usr/include/c++/5/bits/hashtable.h:617
#3  erase (__it=..., this=0x6ba7428) at /usr/include/c++/5/bits/hashtable.h:1732
#4  erase (__it=..., this=0x6ba7428) at /usr/include/c++/5/bits/hashtable.h:745
#5  erase (__position=..., this=0x6ba7428) at /usr/include/c++/5/bits/unordered_map.h:523
#6  Envoy::Upstream::HealthCheckerImplBase::onClusterMemberUpdate (this=0x6ba7350, hosts_added=..., hosts_removed=...) at external/envoy/source/common/upstream/health_checker_base_impl.cc:126
#7  0x000000000067448f in operator() (__args#2=..., __args#1=..., __args#0=1, this=<optimized out>) at /usr/include/c++/5/functional:2267
#8  runCallbacks (args#2=..., args#1=..., args#0=1, this=<optimized out>) at bazel-out/k8-opt/bin/external/envoy/source/common/common/_virtual_includes/callback_impl_lib/common/common/callback_impl.h:40
#9  runUpdateCallbacks (hosts_removed=..., hosts_added=..., priority=1, this=<optimized out>) at bazel-out/k8-opt/bin/external/envoy/source/common/upstream/_virtual_includes/upstream_includes/common/upstream/upstream_impl.h:348
#10 operator() (hosts_removed=..., hosts_added=..., priority=1, __closure=<optimized out>) at external/envoy/source/common/upstream/upstream_impl.cc:295
#11 std::_Function_handler<void(unsigned int, const std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > >&, const std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > >&), Envoy::Upstream::PrioritySetImpl::getOrCreateHostSet(uint32_t, absl::optional<unsigned int>)::<lambda(uint32_t, const HostVector&, const HostVector&)> >::_M_invoke(const std::_Any_data &, <unknown type in /usr/sbin/envoy, CU 0x51da897, DIE 0x52faca0>, const std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > > &, const std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > > &) (__functor=..., __args#0=<optimized out>, __args#1=..., __args#2=...) at /usr/include/c++/5/functional:1871
#12 0x000000000067b25c in operator() (__args#2=..., __args#1=..., __args#0=1, this=<optimized out>) at /usr/include/c++/5/functional:2267
#13 runCallbacks (args#2=..., args#1=..., args#0=1, this=0x9ad6a70) at bazel-out/k8-opt/bin/external/envoy/source/common/common/_virtual_includes/callback_impl_lib/common/common/callback_impl.h:40
#14 runUpdateCallbacks (hosts_removed=..., hosts_added=..., this=0x9ad6a20) at bazel-out/k8-opt/bin/external/envoy/source/common/upstream/_virtual_includes/upstream_includes/common/upstream/upstream_impl.h:289
#15 Envoy::Upstream::HostSetImpl::updateHosts (this=this@entry=0x9ad6a20, hosts=..., healthy_hosts=..., hosts_per_locality=..., healthy_hosts_per_locality=..., locality_weights=..., hosts_added=..., hosts_removed=..., overprovisioning_factor=...) at external/envoy/source/common/upstream/upstream_impl.cc:255
#16 0x0000000000685b1e in Envoy::Upstream::PriorityStateManager::updateClusterPrioritySet(unsigned int, std::shared_ptr<std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > > >&&, absl::optional<std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > > > const&, absl::optional<std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > > > const&, absl::optional<Envoy::Upstream::Host::HealthFlag>, absl::optional<unsigned int>) (this=this@entry=0x7ffd1a372bf0, priority=priority@entry=1, current_hosts=current_hosts@entry=<unknown type in /usr/sbin/envoy, CU 0x51da897, DIE 0x5378365>, hosts_added=..., hosts_removed=..., health_checker_flag=..., health_checker_flag@entry=..., overprovisioning_factor=...) at external/envoy/source/common/upstream/upstream_impl.cc:862
#17 0x00000000006864d1 in Envoy::Upstream::StrictDnsClusterImpl::updateAllHosts (this=0x6ba6dc0, hosts_added=..., hosts_removed=..., current_priority=1) at external/envoy/source/common/upstream/upstream_impl.cc:1158
#18 0x0000000000686bc5 in operator() (address_list=<optimized out>, __closure=0x141f81e8) at external/envoy/source/common/upstream/upstream_impl.cc:1210
#19 std::_Function_handler<void(const std::list<std::shared_ptr<const Envoy::Network::Address::Instance>, std::allocator<std::shared_ptr<const Envoy::Network::Address::Instance> > >&&), Envoy::Upstream::StrictDnsClusterImpl::ResolveTarget::startResolve()::<lambda(const std::list<std::shared_ptr<const Envoy::Network::Address::Instance>, std::allocator<std::shared_ptr<const Envoy::Network::Address::Instance> > >&&)> >::_M_invoke(const std::_Any_data &, <unknown type in /usr/sbin/envoy, CU 0x51da897, DIE 0x537de5c>) (__functor=..., __args#0=<unknown type in /usr/sbin/envoy, CU 0x51da897, DIE 0x537de5c>) at /usr/include/c++/5/functional:1871
#20 0x00000000005fb62e in operator() (__args#0=<optimized out>, this=0x141f81e8) at /usr/include/c++/5/functional:2267
#21 Envoy::Network::DnsResolverImpl::PendingResolution::onAresHostCallback (this=0x141f81e0, status=<optimized out>, timeouts=2, hostent=0x0) at external/envoy/source/common/network/dns_impl.cc:124
#22 0x00000000005fcb7a in end_hquery (hquery=0x16a5ccc0, status=<optimized out>, host=0x0) at ../ares_gethostbyname.c:234
#23 0x00000000005fcdfc in next_lookup (hquery=hquery@entry=0x16a5ccc0, status_code=status_code@entry=12) at ../ares_gethostbyname.c:176
#24 0x00000000005fcf72 in host_callback (arg=0x16a5ccc0, status=12, timeouts=<optimized out>, abuf=<optimized out>, alen=<optimized out>) at ../ares_gethostbyname.c:228
#25 0x0000000000603c2c in end_squery (squery=0xcf4a100, status=<optimized out>, abuf=<optimized out>, alen=<optimized out>) at ../ares_search.c:210
#26 0x0000000000603d12 in search_callback (arg=0xcf4a100, status=<optimized out>, timeouts=<optimized out>, abuf=<optimized out>, alen=<optimized out>) at ../ares_search.c:157
#27 0x00000000006039bb in qcallback (arg=0x17c87a60, status=<optimized out>, timeouts=<optimized out>, abuf=<optimized out>, alen=<optimized out>) at ../ares_query.c:183
#28 0x0000000000602084 in end_query (channel=0x2194000, query=0x167acc30, status=12, abuf=abuf@entry=0x0, alen=alen@entry=0) at ../ares_process.c:1437
#29 0x00000000006029a7 in next_server (channel=channel@entry=0x2194000, query=<optimized out>, now=now@entry=0x7ffd1a3730c0) at ../ares_process.c:802
#30 0x00000000006036f4 in process_timeouts (now=0x7ffd1a3730c0, channel=0x2194000) at ../ares_process.c:561
#31 processfds (channel=0x2194000, read_fds=read_fds@entry=0x0, read_fd=read_fd@entry=-1, write_fds=write_fds@entry=0x0, write_fd=write_fd@entry=-1) at ../ares_process.c:132
#32 0x0000000000603973 in ares_process_fd (channel=<optimized out>, read_fd=read_fd@entry=-1, write_fd=write_fd@entry=-1) at ../ares_process.c:152
#33 0x00000000005fbd9c in onEventCallback (events=0, fd=-1, this=0x20d4720) at external/envoy/source/common/network/dns_impl.cc:168
#34 operator() (__closure=<optimized out>) at external/envoy/source/common/network/dns_impl.cc:27
#35 std::_Function_handler<void(), Envoy::Network::DnsResolverImpl::DnsResolverImpl(Envoy::Event::Dispatcher&, const std::vector<std::shared_ptr<const Envoy::Network::Address::Instance> >&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/5/functional:1871
#36 0x00000000008aef80 in event_process_active_single_queue (base=base@entry=0x21922c0, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0, activeq=<optimized out>) at ../event.c:1646
#37 0x00000000008af65f in event_process_active (base=base@entry=0x21922c0) at ../event.c:1738
#38 0x00000000008b23b8 in event_base_loop (base=0x21922c0, flags=<optimized out>) at ../event.c:1961
#39 0x00000000005b75cc in Envoy::Server::InstanceImpl::run (this=0x2192000) at external/envoy/source/server/server.cc:460
#40 0x0000000000452671 in Envoy::MainCommonBase::run (this=this@entry=0x20f0870) at external/envoy/source/exe/main_common.cc:102
#41 0x0000000000409a53 in run (this=<optimized out>) at bazel-out/k8-opt/bin/external/envoy/source/exe/_virtual_includes/envoy_main_common_lib/exe/main_common.h:81
#42 main (argc=17, argv=0x7ffd1a3734b8) at external/envoy/source/exe/main.cc:37
```

### PR DESCRIPTION
**Pull request by snowp**
This updates `STRICT_DNS` to no longer attempt to share hosts between
resolve targets. Due to the async nature of resolve targets, sharing
host objects can cause the same object to be removed multiple times,
which doesn't work well with the cluster update API (the same host is
sent as a `hosts_removed` multiple times).

As a consequence of this change, active health check values of hosts between
resolve targets are completely independent. This means that active health
checking is duplicated and if a host is added to the cluster in a
resolve target it will *not* reuse the active health value of any
existing hosts, even if we already have a value for the same address.

This differs from EDS, which accomplishes this by ensuring that only one
copy of a given host object exists per cluster. The property that allows
EDS to do this is that the entire cluster is updated at once instead of
per resolve target like in strict DNS.

Fixes #5013
Fixes #4590

Signed-off-by: Snow Pettersen <snowp@squareup.com>

*Risk Level*: Medium, changes how StrictDns works
*Testing*: Updated UTs
*Docs Changes*: n/a
*Release Notes*: n/a

### CODE REVIEW

File: source/common/upstream/upstream_impl.h [hunk 1]
```diff
@@ -661,25 +661,13 @@ class BaseDynamicClusterImpl : public ClusterImplBase {
...
-  /**
-   * Updates the internal collection of all hosts. This should be called with the updated
-   * map of hosts after issuing updateDynamicHostList for each priority.
-   *
-   * @param all_hosts the updated map of address to host after a cluster update.
-   */
-  void updateHostMap(HostMap&& all_hosts) { all_hosts_ = std::move(all_hosts); }
-
-private:
-  HostMap all_hosts_;
```
Comment (snowp) [inline source/common/upstream/upstream_impl.h]: Moved this to eds since it's no longer shared between types

Comment (dio) [reply source/common/upstream/upstream_impl.h]: +1
