### PR TITLE
Fix the alignement in optval of setsockopt when compiled with libc++.

### LINKED ISSUE #7968: AddressSanitizer: misaligned access in setsockopt()
*Description*:

The argument passed to `setsockopt()` is not properly aligned, which ASan complains about when linked against libc++.

*Repro steps*:

`bazel test --config=clang-asan --config=libc++ //test/...`

*Logs*:

This is a list of tests that fail because of this failure:
```
//test/common/network:addr_family_aware_socket_option_impl_test          FAILED
//test/common/network:socket_option_factory_test                         FAILED
//test/common/network:socket_option_impl_test                            FAILED
//test/common/upstream:cluster_manager_impl_test                         FAILED
//test/config_test:example_configs_test                                  FAILED
//test/server:listener_manager_impl_test                                 FAILED
```

*Call Stack*:

```
[ RUN      ] AddrFamilyAwareSocketOptionImplTest.SetOptionSuccess
test/common/network/socket_option_test.h:45:15: runtime error: reference binding to misaligned address 0x60700001e899 for type 'const int', which requires 4 byte alignment
0x60700001e899: note: pointer points here
 00 00 00  08 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  b9 96 6e cc 00
              ^
```

cc @lizan

### PR DESCRIPTION
**Pull request by lizan**
Description:
libc++ std::string may inline the data which results the memory is not
aligned to `void*`. Use vector instead to store the optval.

Detected by UBSAN with libc++ config. Preparation for #4251

Risk Level: Low
Testing: unittest locally
Docs Changes: N/A
Release Notes: N/A
Fixes #7968 

Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

File: source/common/network/socket_option_impl.h [hunk 1]
```diff
@@ -123,17 +126,20 @@ class SocketOptionImpl : public Socket::Option, Logger::Loggable<Logger::Id::con
...
    * @param optname the option name.
    * @param value the option value.
+   * @param size the option value size.
    * @return a Api::SysCallIntResult with rc_ = 0 for success and rc = -1 for failure. If the call
    * is successful, errno_ shouldn't be used.
    */
   static Api::SysCallIntResult setSocketOption(Socket& socket,
                                                const Network::SocketOptionName& optname,
-                                               absl::string_view value);
+                                               const void* value, size_t size);
```
Comment (PiotrSikora) [inline source/common/network/socket_option_impl.h]: Why not `const std::vector<uint8_t>& value)`?

Comment (lizan) [reply source/common/network/socket_option_impl.h]: to match what the syscall is taking. a const ref of vector must be a vector instance but here it want a memory address and a size.

Comment (PiotrSikora) [reply source/common/network/socket_option_impl.h]: It wasn't doing that before, so this adds an unnecessary change to a fix, IMHO.

It's a nit, anyway, I was going back-and-forth myself between both variants in #7969, so I wanted to see how did you justify your choice.

Comment (lizan) [reply source/common/network/socket_option_impl.h]: Yeah it is not necessary though the underlying type is no longer std::string thus I didn't feel string_view is appropriate. So just made this same as the syscall.

Comment (PiotrSikora) [reply source/common/network/socket_option_impl.h]: Erm, I was suggesting `const std::vector<uint8_t>& value`, not `absl::string_view value`.

Comment (lizan) [reply source/common/network/socket_option_impl.h]: because then it must be a vector instance, but not a (address, size) pair, which is not a big deal really though
