### PR TITLE
Copy configs into example images

### LINKED ISSUE #12287: Jaeger native tracing example segfaults
### description

While testing the examples in the repo, i noticed that the `jaeger-native-tracing` example segfaults when you make an `http` request of it.

### steps to reproduce

Follow the example instructions, eg

```
cd examples/jaeger-native-tracing
docker-compose up --build -d
curl -v localhost:8000/trace/1
```

### logs

the logs from the failing container show

```
front-envoy_1  | [2020-07-24 12:51:35.638][11][info][config] [source/server/listener_manager_impl.cc:844] all dependencies initialized. starting workers
front-envoy_1  | [2020-07-24 12:51:35.639][11][warning][main] [source/server/server.cc:549] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
front-envoy_1  | [2020-07-24 12:52:15.762][19][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x10
front-envoy_1  | [2020-07-24 12:52:15.762][19][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
front-envoy_1  | [2020-07-24 12:52:15.762][19][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: f20c9168aa2e92b2c5b6f8103d792e66fd813c62/1.16.0-dev/Clean/RELEASE/BoringSSL
front-envoy_1  | [2020-07-24 12:52:15.763][19][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #0: __restore_rt [0x7f92319d18a0]
front-envoy_1  | [2020-07-24 12:52:15.765][19][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #1: jaegertracing::propagation::Propagator<>::extract() [0x7f922f1b4ffe]
front-envoy_1  | [2020-07-24 12:52:15.766][19][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #2: jaegertracing::Tracer::Extract() [0x7f922f1b531a]
front-envoy_1  | ActiveStream 0x55ca59282880, stream_id_: 12345331179989539751, state_.has_continue_headers_: 0, state_.is_head_request_: 0, state_.decoding_headers_only_: 0, state_.encoding_headers_only_: 0
front-envoy_1  | request_headers_: 
front-envoy_1  |   ':authority', 'localhost:8000'
front-envoy_1  |   ':path', '/trace/1'
front-envoy_1  |   ':method', 'GET'
front-envoy_1  |   'user-agent', 'curl/7.68.0'
front-envoy_1  |   'accept', '*/*'
front-envoy_1  |   'x-forwarded-for', '192.168.128.1'
front-envoy_1  |   'x-forwarded-proto', 'http'
front-envoy_1  |   'x-envoy-internal', 'true'
front-envoy_1  |   'x-request-id', 'efe080d2-f7ab-9e33-aabd-a460fa4164b2'
front-envoy_1  | request_trailers_: null
front-envoy_1  | response_headers_: null
front-envoy_1  | response_trailers_: null
front-envoy_1  | &stream_info_: 
front-envoy_1  |   StreamInfoImpl 0x55ca592829c8, protocol_: 1, response_code_: null, response_code_details_: null, health_check_request_: 0, route_name_: 
front-envoy_1  | /start-front.sh: line 3:    11 Segmentation fault      (core dumped) /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
```

### PR DESCRIPTION
**Pull request by phlax**
Commit Message:
Copy configs into example docker images and fix remaining permission issues
Additional Description:

Since the `envoy` docker image no longer runs as `root`, a strict `umask` setting in a development environment can prevent the examples from working.

There were also some remaining permissions issues in the  examples that are dealt with here.

There are some docs that are out of date or that can/should be updated - i will update these shortly

There is a test runner that I built for tracking down and testing the documented commands. It can be seen here:

https://github.com/phlax/envoy-examples

And the output from a successful test run using this `PR` can be seen here:

https://travis-ci.org/github/phlax/envoy-examples/builds/711188378

The `grpc-bridge` example didnt work at all - so i separated that to a different issue #12231

*Edit: the `jaeger-native-tracing` example segfaults - but not as a result of this PR` see #12287*

*Update: binary for `jaeger-native-tracing` is included and the example works*

*Update: fixes for the `grpc-bridge` example are now included, but  i'll leave docs updates to a separate PR*

Risk Level: low
Testing: see above
Docs Changes: tba
Release Notes: n/a
[Optional Runtime guard:]
[Optional Fixes #Issue] Touch #12112 Fixes #12287 
[Optional Deprecated:]

### CODE REVIEW

File: examples/ext_authz/Dockerfile-frontenvoy [hunk 1]
```diff
@@ -0,0 +1,9 @@
+FROM envoyproxy/envoy-dev:latest
+
+RUN apt-get update && apt-get -q install -y \
+    curl
+COPY ./config /etc/envoy-config
+COPY ./run_envoy.sh /run_envoy.sh
+RUN chmod go+r -R /etc/envoy-config \
+    && chmod go+rx /run_envoy.sh /etc/envoy-config /etc/envoy-config/*
```
Comment (dio) [inline examples/ext_authz/Dockerfile-frontenvoy:8]: Sorry why do we need to "+x" to: `/etc/envoy-config /etc/envoy-config/*`?

File: examples/ext_authz/run_envoy.sh [hunk 2]
```diff
@@ -0,0 +1,3 @@
+#!/bin/sh
+
+/usr/local/bin/envoy -c "/etc/envoy-${FRONT_ENVOY_YAML}" --service-cluster front-proxy
```
Comment (dio) [inline examples/ext_authz/run_envoy.sh:3]: Should be `/etc/envoy-config/${FRONT_ENVOY_YAML}`?

File: examples/ext_authz/Dockerfile-frontenvoy (hunk 1 above)
Comment (dio) [reply examples/ext_authz/Dockerfile-frontenvoy:8]: Hum, sorry, my bad. This is right.

**Comment by dio** [comment]
@phlax I think we can run the run examples project as GitHub Actions workflow. @lizan WDYT?

File: examples/ext_authz/run_envoy.sh (hunk 2 above)
Comment (phlax) [reply examples/ext_authz/run_envoy.sh:3]: no - the existing config has  `confg/path/to/file` - ie with the `config/` prefix

i opted to leave it that way rather than changing the docs - but i can change it

**Comment by phlax** [comment]
@dio yep im just cleaning up the code now, but i think its a good idea. The only reservation is that its a 10  minutes test run, so not sure if we want it to trigger on every change - perhaps only if docs or examples change

**Comment by lizan** [comment]
@dio we used to run ci/verify_examples.sh so if we can bring that back it would be great.

File: examples/ext_authz/run_envoy.sh (hunk 2 above)
Comment (dio) [reply examples/ext_authz/run_envoy.sh:3]: Hum, sorry, my bad. This is right.

**Comment by phlax** [comment]
@dio @lizan i updated the `jaeger-native-tracing` example to include the binary downloaded from here:

https://github.com/tetratelabs/getenvoy-package/files/3518103/getenvoy-centos-jaegertracing-plugin.tar.gz

This seems to fix the problem and the example now works, i think. Not sure if just including the binary is the best way.

**Comment by phlax** [comment]
@dio i fixed the `grpc-bridge` example. The docs still need updating, but if its ok, ill update docs in a separate PR

File: examples/jaeger-native-tracing/Dockerfile-frontenvoy [hunk 3]
```diff
@@ -0,0 +1,8 @@
+FROM envoyproxy/envoy-dev:latest
+
+RUN apt-get update && apt-get -q install -y \
+    curl
+COPY ./front-envoy-jaeger.yaml /etc/front-envoy.yaml
+COPY ./libjaegertracing.so.0.4.2 /usr/local/lib/libjaegertracing_plugin.so
```
Comment (dio) [inline examples/jaeger-native-tracing/Dockerfile-frontenvoy:6]: Wait, sorry, I think we can do `ADD` or `curl`-ing in here?

Comment (phlax) [reply examples/jaeger-native-tracing/Dockerfile-frontenvoy:6]: well, sort of. We can do `curl` + `tar`, not sure about `ADD` (which seems discouraged in this context - https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy)

i didnt do this because the source seemed a bit unofficial.

im happy to implement either the curl way or with binary in repo.

Ill add a comment in the recipe now about where the binary came from etc

Comment (dio) [reply examples/jaeger-native-tracing/Dockerfile-frontenvoy:6]: OK. I'll let @lizan to comment.

1. We can have that but under certain env var or commented.
2. Make sure we do checksum as well.

Comment (phlax) [reply examples/jaeger-native-tracing/Dockerfile-frontenvoy:6]: @lizan do you have a preference re `jaeger-native-tracing` binary ?

should we:

- curl the binary from the `getenvoy` repo/file, checksum it and include
- or, just include the binary in the envoy repo

lmk and ill update the PR

Comment (lizan) [reply examples/jaeger-native-tracing/Dockerfile-frontenvoy:6]: let's do curl with checksum

**Comment by phlax** [comment]
@dio PR updated with `jaeger-native-tracing` bin curled

latest test can be seen here:

https://travis-ci.org/github/phlax/envoy-examples/builds/712510401

File: examples/csrf/samesite/front-envoy.yaml [hunk 4]
```diff
@@ -114,3 +114,12 @@ admin:
...
       port_value: 8001
+
+layered_runtime:
+  layers:
+  - name: static_layer
+    static_layer:
+      envoy.deprecated_features:envoy.api.v2.route.CorsPolicy.allow_origin: true
+      envoy.deprecated_features:envoy.api.v2.route.Route.per_filter_config: true
+      envoy.deprecated_features:envoy.api.v2.route.VirtualHost.per_filter_config: true
+      envoy.deprecated_features:envoy.type.matcher.StringMatcher.regex: true
```
Comment (mattklein123) [inline examples/csrf/samesite/front-envoy.yaml:125]: I think these configs are missing from https://github.com/envoyproxy/envoy/blob/master/examples/BUILD. Can we fix the configs? This will have to be updated also https://github.com/envoyproxy/envoy/blob/master/test/config_test/example_configs_test.cc.

Bonus points for figuring out how to automatically make sure new configs get added for testing. This is a consistent problem that we have. Thank you!

Comment (phlax) [reply examples/csrf/samesite/front-envoy.yaml:125]: @mattklein123 i found the problem using this  test runner 

https://github.com/phlax/envoy-examples

weve been talking about how/if we could land it in envoy repo - i was waiting to land this first before thinking  about it

Comment (mattklein123) [reply examples/csrf/samesite/front-envoy.yaml:125]: OK sounds good. In the interim can you fix the configs and add to the config tests? Thank you.

Comment (phlax) [reply examples/csrf/samesite/front-envoy.yaml:125]: not sure if it would catch these configs tho

Comment (phlax) [reply examples/csrf/samesite/front-envoy.yaml:125]: > I think these configs are missing from https://github.com/envoyproxy/envoy/blob/master/examples/BUILD. Can we fix the configs?

I updated the `BUILD` script with all of the configs with `yaml` suffix.

Not entirely clear if this is correct, but also noticing that there is at least one non-yaml config listed, so there may be more

> This will have to be updated also https://github.com/envoyproxy/envoy/blob/master/test/config_test/example_configs_test.cc.

Im afraid its not immediately obvious to me what needs to change here

Comment (mattklein123) [reply examples/csrf/samesite/front-envoy.yaml:125]: You need to:
1) Add the missing configs to the build config
2) Fix the configs
3) Update the test to account for the new number of configs (you will see the test will fail).

Thank you!

Comment (phlax) [reply examples/csrf/samesite/front-envoy.yaml]: @mattklein123 

i have fixed the deprecation issues in the example configs and updated the necessary test files

I wasnt able to include the `jaeger-native` config as it fails with

```
2020-08-01T17:22:05.6865108Z test/config_test/config_test.cc:134: Failure
2020-08-01T17:22:05.6865445Z Failed
2020-08-01T17:22:05.6866695Z '/b/f/w/_tmp/163cb06a4250265abc95a57e525238d7/test/config_test/jaeger-native-tracing_service1-envoy-jaeger.yaml' config failed. Error: opentracing: failed to load dynamic library: /usr/local/lib/libjaegertracing_plugin.so: cannot open shared object file: No such file or directory
```

im not  sure how to mock/expect the files absence. Im happy to update if i know how.

i also updated the test runner i have tor the examples to test both the `cors` and `csrf`  examples more thoroughly, and ensure i wasnt breaking anything.

regarding keeping the `BUILD` script up-to-date, we could do something like
```
cd examples
configs="$(find . -name "*.yaml" -o -name "*.lua" | grep -v docker-compose | cut  -d/ -f2-)"
for config in $configs; do
    grep "\"$config\"" BUILD || exit 1
done
```
it would fail on this PR because the `jaeger` configs arent   included

Comment (mattklein123) [reply examples/csrf/samesite/front-envoy.yaml]: Awesome thanks a ton. Agreed we can do something like the script you recommend as a follow up? (Perhaps with an exclusion list for configs we know won't work.)
