### PR TITLE
headers: Fixing addCopy and addViaMove for multiple inline headers

### LINKED ISSUE #2004: Envoy inline headers do not support appending values
For performance reasons, the headers that Envoy uses internally are stored inline in the Http::HeaderMap implementation. Appending values is not supported for these headers. The v2 API, however, allows them to be configured for append or replace at various levels (see #2003).

Currently, requests to append values are ignored and the header value is simply replaced. It can be argued that even this should not be allowed.

Need to determine whether modification of the inline headers via API config is allowed. If not, write validation code to prevent it. If allowed, consider whether specifying values to append is a configuration error or should just be ignored. The chosen behavior and the list of inline headers should be documented.

### PR DESCRIPTION
**Pull request by alyssawilk**
Currently, addCopy() is currently no-op for existing inline headers, so
addCopy("cache-control", "max-age=1234")
addCopy("cache-control", public)
results in
cache-control: public

This PR fixes addCopy and addViaMove so the result will be
cache-control: max-age:1234,public
It leaves all of the add*Reference* functions untouched, but adds an ASSERT to the utility to at least fail in debug mode if someone inadvertently exercises the unsupported code paths.

*Risk Level*: High: Changing existing header processing.  If any existing code depends on the existing buggy behavior, there may be unexpected results.
*Testing*: unit tests of new code.  Fixed existing tests relying on prior code.
*Docs Changes*: n/a (existing docs don't cover the buggy behavior)
*Release Notes*: added

Fixes #2004

### CODE REVIEW

File: source/common/http/header_map_impl.h [hunk 1]
```diff
@@ -37,6 +37,14 @@ public:
  */
 class HeaderMapImpl : public HeaderMap {
 public:
+  /**
+   * Appends data to header. If header already has a value, the string ',' is added between the
```
Comment (mattklein123) [inline source/common/http/header_map_impl.h]: Q: Is this RFC particular about whether it should be ',' or ", "? I feel like in practice there is a space after the comma, but I'm not sure. (I think this is what we do for appending XFF FWIW, and on that topic can we have XFF append use this new code?).

File: source/common/http/header_map_impl.cc [hunk 2]
```diff
@@ -320,7 +327,14 @@ void HeaderMapImpl::insertByKey(HeaderString&& key, HeaderString&& value) {
 }
 
 void HeaderMapImpl::addViaMove(HeaderString&& key, HeaderString&& value) {
-  insertByKey(std::move(key), std::move(value));
+  // If this is an inline header, we can't addViaMove, because we'll overwrite
+  // the existing value.
+  auto* entry = getExistingInline(key.c_str());
+  if (entry) {
```
Comment (mattklein123) [inline source/common/http/header_map_impl.cc]: nit: `entry != nullptr` (same elsewhere)

File: source/common/http/header_map_impl.cc [hunk 3]
```diff
@@ -346,6 +360,11 @@ void HeaderMapImpl::addReferenceKey(const LowerCaseString& key, const std::strin
 }
 
 void HeaderMapImpl::addCopy(const LowerCaseString& key, uint64_t value) {
+  auto* entry = getExistingInline(key.get().c_str());
+  if (entry) {
+    appendToHeader(entry->value(), fmt::format("{}", value));
```
Comment (mattklein123) [inline source/common/http/header_map_impl.cc]: perf nit: fmt::format is pretty slow. I think we could make this substantially faster by doing itoa directly inline during the append (special case of append into a header string). At least maybe put a perf TODO here?

File: source/common/http/header_map_impl.h (hunk 1 above)
Comment (alyssawilk) [reply source/common/http/header_map_impl.h]: I believe whitespace is optional.  We do direct comma appending internally except for the Via header which we special case ", " with no explanation of why.  Via needs whitespace between received-protocol and received-by but as documented it appears to be optional between the , and received-protocol.
https://tools.ietf.org/html/rfc7230#page-82     OWS (optional whitespace)

Comment (alyssawilk) [reply source/common/http/header_map_impl.h]: Also https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html
(which I'm failing to find subsection links for)

Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

Comment (mattklein123) [reply source/common/http/header_map_impl.h]: OK cool I'm fine either way. It would be good to be consistent everywhere we can which I guess this will do for us.

File: source/common/http/header_map_impl.cc [hunk 4]
```diff
@@ -6,6 +6,7 @@
 
 #include "common/common/assert.h"
 #include "common/common/empty_string.h"
+#include "common/common/fmt.h"
```
Comment (mattklein123) [inline source/common/http/header_map_impl.cc]: not needed now?

File: source/common/http/header_map_impl.h (hunk 1 above)
Comment (mattklein123) [reply source/common/http/header_map_impl.h]: Worth linking to RFC here for whitespace? I'm fine either way.

**Comment by alyssawilk** [comment]
Mildly prefer moving xff over in a follow up in the unlikely even it causes problems for anyone.  It's the same reason I didn't ask Constance move over to it when she added the utility :-)
I'll add a TODO and follow up next week (once this has landed and stuck) if that's OK?

**Comment by mattklein123** [comment]
Sure, SGTM

**Comment by danielhochman** [comment]
I think there might be an off-by-one error somewhere in this code. I haven't had a chance to look at the code yet, but we started seeing a header that was a concatenation of two headers after deploying a diff including this. e.g. `user-agentcontent-type: python-requestsapplication/json\r\n`.

File: source/common/http/header_map_impl.cc [hunk 5]
```diff
@@ -320,7 +326,14 @@ void HeaderMapImpl::insertByKey(HeaderString&& key, HeaderString&& value) {
 }
 
 void HeaderMapImpl::addViaMove(HeaderString&& key, HeaderString&& value) {
-  insertByKey(std::move(key), std::move(value));
+  // If this is an inline header, we can't addViaMove, because we'll overwrite
+  // the existing value.
+  auto* entry = getExistingInline(key.c_str());
+  if (entry != nullptr) {
+    appendToHeader(entry->value(), value.c_str());
```
Comment (mattklein123) [inline source/common/http/header_map_impl.cc]: @alyssawilk I'm pretty sure the bug is here. The `addViaMove` function expects both parameters to be moved/cleared, which doesn't happen in this path. I think in this case we need to explicitly clear `value`. See https://github.com/envoyproxy/envoy/blob/28cea916a2a23c25d9175373c0413610586f5a16/source/common/http/http1/codec_impl.cc#L301. We should add more asserts at the end of this function such as `ASSERT(value.empty());`

cc @junr03 @danielhochman

File: source/common/http/header_map_impl.cc [hunk 6]
```diff
@@ -346,6 +359,13 @@ void HeaderMapImpl::addReferenceKey(const LowerCaseString& key, const std::strin
 }
 
 void HeaderMapImpl::addCopy(const LowerCaseString& key, uint64_t value) {
+  auto* entry = getExistingInline(key.get().c_str());
+  if (entry != nullptr) {
+    char buf[32];
+    StringUtil::itoa(buf, sizeof(buf), value);
+    appendToHeader(entry->value(), buf);
```
Comment (mattklein123) [inline source/common/http/header_map_impl.cc]: I just noticed this, but we are creating an `std::string` in this path. Can we make this not create a string here also for perf reasons?

File: source/common/http/header_map_impl.cc (hunk 5 above)
Comment (alyssawilk) [reply source/common/http/header_map_impl.cc]: I can explicitly clear, but ASSERT(value.empty()) doesn't pass with the existing insertByKey() function.  We explicitly test in HeaderStringTest.All that when we std::move(string) the "original" string retains a pointer at the underlying buffer and the size is not cleared.  

I've added an integration test instead, which trips the ASSERT you called out, and still fails with it commented out, due to "eep" not being found.
https://github.com/envoyproxy/envoy/pull/3597
