### PR TITLE
gRPC-Web: Fix failing HTTP/2 requests on some browsers due to empty trailers

### LINKED ISSUE #10514: gRPC-Web requests on Safari fail when using Envoy 1.13
When attempting to use gRPC-Web on Safari using Envoy 1.13, the request succeeds, but in the inspector in Safari, this is the error I see:

`Failed to load resource: WebKit encountered an internal error`

Here's the web inspector output from Safari:

#### Summary
```
URL: https://myurl.io/svc.Authentication/Login
Status: —
Source: —
Initiator: 
2.c85f5bc6.chunk.js:2:583533
```

#### Request
```
Content-Type: application/grpc-web-text
Accept: application/grpc-web-text
Origin: https://my-url.com
Referer: https://my-url.com/login
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
X-User-Agent: grpc-web-javascript/0.1
X-Grpc-Web: 1
grpc-timeout: 4999m
```

#### Response
```
No response headers
```

#### Request Data
```
MIME Type: application/grpc-web-text
Request Data: 
```

This issue was initially raised under the https://github.com/grpc/grpc-web repo: https://github.com/grpc/grpc-web/issues/759

The request should return a successful response.

To give you more context, I'm personally running envoy via https://github.com/projectcontour/contour, though I don't think it's specific to contour since @phlippieb seems to be experiencing the same issue without contour I think.

I'm running envoy on GKE 1.15.9 as an ingress via a LoadBalancer (hence why I'm using contour).

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This adds `envoy.reloadable_features.skip_encoding_empty_trailers` runtime feature flag (enabled by default) to skip encoding empty trailers in H2 codec. This behavior can be reverted temporarily by setting runtime feature `envoy.reloadable_features.skip_encoding_empty_trailers` to false.

Before this commit, seeing empty trailers of gRPC-Web filter response:

```
[  5.036] recv DATA frame <length=28, flags=0x00, stream_id=13>
[  5.040] recv DATA frame <length=52, flags=0x00, stream_id=13>
[  5.053] recv HEADERS frame <length=0, flags=0x05, stream_id=13>
          ; END_STREAM | END_HEADERS
```

After:

```
[  5.036] recv DATA frame <length=28, flags=0x00, stream_id=13>
[  5.040] recv DATA frame <length=52, flags=0x00, stream_id=13>
[  5.052] recv DATA frame <length=0, flags=0x01, stream_id=13>
          ; END_STREAM
```
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

Additional Description: I have a reproducer here: https://github.com/dio/grpc-web-hello, and this patch is confirmed to work: https://github.com/envoyproxy/envoy/issues/10514#issuecomment-660937969. For WebKit, the issue is logged here: https://bugs.webkit.org/show_bug.cgi?id=210108. The issue is also observed in Internet Explorer 11￼ and Edge on various patch versions of Windows 10 (pre-Chromium).

Risk Level: Low
Testing: Updated
Docs Changes: N/A.
Release Notes: Added
Fixes #10514

### CODE REVIEW

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 1]
```diff
@@ -211,8 +211,14 @@ Http::FilterTrailersStatus GrpcWebFilter::encodeTrailers(Http::ResponseTrailerMa
     return Http::HeaderMap::Iterate::Continue;
   });
 
-  // Clear out the trailers so they don't get added since it is now in the body
-  trailers.clear();
+  // Due to https://github.com/envoyproxy/envoy/issues/10514 (and
+  // https://bugs.webkit.org/show_bug.cgi?id=210108) we need to skip clearing response trailer
+  // when the downstream protocol is HTTP/2.
+  if (encoder_callbacks_->streamInfo().protocol() != Http::Protocol::Http2) {
```
Comment (lizan) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:217]: Can we use more specific workaround for this instead of sending trailers to all H2 client? e.g. inspecting user-agent or something else?

Comment (rogchap) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:217]: This bug also effects Internet Explorer 11￼ and Edge on various patch versions of Windows 10 (pre Chromium); so inspecting user-agents could miss some effected browsers.

Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:217]: Hum, need to update the description and comments then?

Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:217]: How about clearing the trailers when H2 and Chrome/Chromium only? Yeap. user-agent detection is tricky.

Comment (rogchap) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:216]: What is the downside of sending the trailers (I'm presuming twice as they are in the body too) to all H2 clients for grpc-web? 
Doing any kind of browser filtering could lead to future debugging headaches.

Comment (lizan) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:216]: On a second thought, I don't think gRPC-web need a response trailers ever, so shall we always clear (or say, not sending HEADERS frame at the end in case of H2)? I don't think in H1 we send trailers by default so it's not emit anyway.

Comment (wenbozhu) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:216]: Agreed. For grpc-web, we should always drop the trailers as the data has been copied to the body.

===

Is it correct that the general problem could also apply to HTTP endpoints which choose to emit any trailers,  if Envoy or any forward proxies choose to forward trailers to a browser client? If so, it seems that we should make trailer forwarding an opt-in config for both H1 and H2 in Envoy.

Comment (rogchap) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:216]: Agree that we should not need the trailers for gRPC-web, but that is the current behaviour that has caused the described issue in Safari and IE. By sending the trailers when H2 resolves the problem; but at the cost of sending the trailers twice

Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: @lizan a good catch. I think we can skip submitting trailers when it is cleared. Let me test it.

**Comment by dio** [comment]
Before working on this further. I would like to validate the direction of this PR. To give a scoped context: gPRC-Web Filter, mandated by spec to embed the trailers in the body, hence [it clears the trailers](https://github.com/envoyproxy/envoy/blob/54652f03ea0b3504bd4d64e8ae31985be2892a95/source/extensions/filters/http/grpc_web/grpc_web_filter.cc#L215) after copying it to the body. Since we always encode empty trailers, this introduces an issue for Safari (as reported here https://bugs.webkit.org/show_bug.cgi?id=210108 ) and other browsers (i.e. IE11 pre-Chromium era https://github.com/envoyproxy/envoy/issues/10514) when the downstream is HTTP/2. 

@lizan @alyssawilk could you give your advice here? I'm not sure if HCM level is OK for this since this, I think, can be done in our H2 codec as well (from my limited knowledge of understanding code seems like the example from nghttp2 is also skipping submitting trailers when it is empty: https://github.com/nghttp2/nghttp2/blob/a3a034813b86f7413b745ce9e416bc9f8e7fd053/src/shrpx_http2_downstream_connection.cc#L206). Or probably there is a better solution for this.

Thank you 🙏🏽.

File: source/common/http/conn_manager_impl.cc [hunk 2]
```diff
@@ -2048,6 +2048,17 @@ void ConnectionManagerImpl::ActiveStream::encodeTrailers(ActiveStreamEncoderFilt
     }
   }
 
+  // Some browsers (e.g. WebKit-based browsers: https://bugs.webkit.org/show_bug.cgi?id=210108) have
+  // a problem with processing empty trailers of an HTTP/2 response as reported here:
+  // https://github.com/envoyproxy/envoy/issues/10514. This runtime feature flag is disabled by
+  // default.
+  const bool skip_encoding_empty_trailers =
+      Runtime::runtimeFeatureEnabled("envoy.reloadable_features.skip_encoding_empty_trailers");
```
Comment (alyssawilk) [inline source/common/http/conn_manager_impl.cc:2056]: Thanks for un-breaking Safari, @dio  :-)  

If this is a common client-side bug, I'd think we want to make sure it "just works" by default.  

If this sort of transformation is legal by default (like taking an empty data frame and sending FIN in headers, but I'm not sure about the H2 spec here.  @PiotrSikora ?) This is fine, and I'd just suggest defaulting the runtime guard on and adding tests.  If we think it's dicey by the spec, I think we'd want to either only do it for known buggy user-agents, or have a permanent config option.

Comment (dio) [reply source/common/http/conn_manager_impl.cc:2056]: Thank you. While waiting for confirmation from @PiotrSikora I think I'll make this runtime feature flag enabled by default and add tests for it. Having a permanent config option also sounds plausible for me.

Comment (PiotrSikora) [reply source/common/http/conn_manager_impl.cc:2056]: I think this change is fine, thanks!

Do you happen to have a tcpdump or debug logs with nghttp2 output that show what's getting transmitted on the wire? I'm wondering if the issue is really a `HEADERS` frame with `END_HEADERS|END_STREAM` flags and empty header block or do we mess something on the wire?

Comment (dio) [reply source/common/http/conn_manager_impl.cc:2056]: @PiotrSikora yes, I just tried using nghttp2.

I think if we have:

```
[  5.053] recv HEADERS frame <length=0, flags=0x05, stream_id=13>
          ; END_STREAM | END_HEADERS
```

Safari throws an error, while: 

```
[  5.050] recv (stream_id=13) grpc-status: 0
[  5.050] recv (stream_id=13) grpc-message: OK
[  5.050] recv HEADERS frame <length=26, flags=0x05, stream_id=13>
          ; END_STREAM | END_HEADERS
          (padlen=0)
[  5.050] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=NO_ERROR(0x00), opaque_data(0)=[])
```

Safari will be fine. But I think what we want is END_STREAM without END_HEADERS with empty HEADERS frame:

```
[  1.362] recv DATA frame <length=0, flags=0x01, stream_id=13>
          ; END_STREAM
```

Complete response when Safari crashes:

```
[  5.032] recv WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=268369921)
[  5.032] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  5.049] recv (stream_id=13) :status: 200
[  5.049] recv (stream_id=13) grpc-accept-encoding: identity
[  5.049] recv (stream_id=13) grpc-encoding: identity
[  5.049] recv (stream_id=13) content-type: application/grpc-web-text+proto
[  5.049] recv (stream_id=13) date: Thu, 23 Jul 2020 07:49:27 GMT
[  5.049] recv (stream_id=13) x-envoy-upstream-service-time: 19
[  5.049] recv (stream_id=13) access-control-allow-origin: https://ok.local:8000
[  5.049] recv (stream_id=13) access-control-expose-headers: custom-header-1,grpc-status,grpc-message
[  5.049] recv (stream_id=13) server: envoy
[  5.049] recv HEADERS frame <length=192, flags=0x04, stream_id=13>
          ; END_HEADERS
          (padlen=0)
          ; First response header
[  5.049] recv DATA frame <length=28, flags=0x00, stream_id=13>
[  5.053] recv DATA frame <length=52, flags=0x00, stream_id=13>
[  5.053] recv HEADERS frame <length=0, flags=0x05, stream_id=13>
          ; END_STREAM | END_HEADERS
          (padlen=0)
[  5.053] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=NO_ERROR(0x00), opaque_data(0)=[])

```

I have a question though. seems like this patch doesn't work either, we need to somehow set `END_STREAM` when `encodeTrailers` is called. However, I tried to call `nghttp2_submit_data` but it is failing with -510 which is odd since `nghttp2_submit_trailer` is fine with the same session and stream ids. I believe I missed something obvious here.

Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc:2056]: You'll want to make sure that you send an end stream bit somehow.  doing encodeData(empty_buffer, false) should do it.

Comment (lizan) [reply source/common/http/conn_manager_impl.cc:2060]: From Filter API perspective, I don't like this approach, I think we should either do:
a) introduce a new return enum to FilterTrailersStatus, to indicate that trailers should not be emit.
b) add `end_stream` flags to `addEncodedData`, end stream there and encodeTrailers return StopIteration

I mildly prefer b) then we have clear H2 frames on wire for gRPC-web without breaking other behavior.

A theoretical case which might break is we have gRPC-web with Safari, though some other H2 client expects empty H2 trailers being proxied from upstream.

Comment (dio) [reply source/common/http/conn_manager_impl.cc:2060]: Interestingly, I also did use the `injectEncodedDataToFilterChain`, but scared of the side-effect, while the response frame seems better:

```
[  5.026] recv (stream_id=13) :status: 200
<SNIP>
[  5.026] recv HEADERS frame <length=191, flags=0x04, stream_id=13>
          ; END_HEADERS
          (padlen=0)
          ; First response header
[  5.026] recv DATA frame <length=28, flags=0x00, stream_id=13>
[  5.026] recv DATA frame <length=52, flags=0x01, stream_id=13>
          ; END_STREAM
[  5.026] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
```

```diff
diff --git a/source/extensions/filters/http/grpc_web/grpc_web_filter.cc b/source/extensions/filters/http/grpc_web/grpc_web_filter.cc
index 7595839881..2ad5ba0881 100644
--- a/source/extensions/filters/http/grpc_web/grpc_web_filter.cc
+++ b/source/extensions/filters/http/grpc_web/grpc_web_filter.cc
@@ -222,11 +222,11 @@ Http::FilterTrailersStatus GrpcWebFilter::encodeTrailers(Http::ResponseTrailerMa
   buffer.move(temp);
   if (is_text_response_) {
     Buffer::OwnedImpl encoded(Base64::encode(buffer, buffer.length()));
-    encoder_callbacks_->addEncodedData(encoded, true);
+    encoder_callbacks_->injectEncodedDataToFilterChain(encoded, true);
   } else {
-    encoder_callbacks_->addEncodedData(buffer, true);
+    encoder_callbacks_->injectEncodedDataToFilterChain(buffer, true);
   }
-  return Http::FilterTrailersStatus::Continue;
+  return Http::FilterTrailersStatus::StopIteration;
 }

 void GrpcWebFilter::setupStatTracking(const Http::RequestHeaderMap& headers) {
```

WDYT @lizan?

Comment (lizan) [reply source/common/http/conn_manager_impl.cc:2060]: @dio `injectEncodedDataToFilterChain` bypass existing HCM write buffer, so it shouldn't be used. that's why I'm suggesting `addEncodedData`.

Comment (dio) [reply source/common/http/conn_manager_impl.cc]: @lizan updated.

File: source/common/http/conn_manager_impl.cc [hunk 3]
```diff
@@ -1934,7 +1935,7 @@ void ConnectionManagerImpl::ActiveStream::addEncodedData(ActiveStreamEncoderFilt
   } else if (state_.filter_call_state_ & FilterCallState::EncodeTrailers) {
     // In this case we need to inline dispatch the data to further filters. If those filters
     // choose to buffer/stop iteration that's fine.
-    encodeData(&filter, data, false, FilterIterationStartState::AlwaysStartFromNext);
+    encodeData(&filter, data, end_stream, FilterIterationStartState::AlwaysStartFromNext);
```
Comment (lizan) [inline source/common/http/conn_manager_impl.cc:1938]: I think we need handling this correctly in encodeData:
https://github.com/envoyproxy/envoy/blob/defea7ecbf6f3ebffe8b9d41afa7f62322756f05/source/common/http/conn_manager_impl.cc#L1983

Also, some ASSERT needed when end_stream is added, decodeTrailers should only return StopIteration.

Comment (dio) [reply source/common/http/conn_manager_impl.cc:1938]: >  (*entry)->end_stream_ = end_stream && !response_trailers_; 

@lizan, sorry, so previously it is always false, so we want to preserve that?

Comment (lizan) [reply source/common/http/conn_manager_impl.cc:1938]: Since !response_trailers is always `false` there in this case, the filters in front of grpc-web still get called encodeData(data, false) while they should get encodeData(data, true).

File: source/common/http/conn_manager_impl.cc (hunk 2 above)
Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc]: I agree this new approach gives more authentic view of what's happening to downstream filters, but I'm wary of the complexity it adds to the already complicated HCM chain, what with some number of filters getting trailers, and a stopiteration which should stop trailers but what if another filter adds trailers back?  Just stripping empty trailers at the codec has the advantages of simplicity, and allowing Envoy-as-an-edge-proxy do fleet wide compliance checks for all upstream servers (we can always add a config option later if someone wants their empty trailers).  If we opt to go this route I think we need a lot more HCM unit tests, verifying if we have filter A-gRPCWeb-B that A and gRPC-web gets trailers, no encodeData(_, true), and B gets encodeData(_, true) no trailers, and then another test where a subsequent downstream filter adds trailers _back_ via addEncodedTrailers and all the right things happen there.
cc @mattklein123

Comment (dio) [reply source/common/http/conn_manager_impl.cc]: @alyssawilk I was feeling adventurous when seeing the data frames seem more correct using this approach tipped by @lizan. At the same time it is scary indeed making changes to HCM this way. I personally prefer to have the simple approach in place first, then since @snowp is making an effort re: filter manager, probably could give clearer path for this case as well.

File: include/envoy/http/filter.h [hunk 4]
```diff
@@ -632,8 +632,9 @@ class StreamEncoderFilterCallbacks : public virtual StreamFilterCallbacks {
    *
    * @param data Buffer::Instance supplies the data to be encoded.
    * @param streaming_filter boolean supplies if this filter streams data or buffers the full body.
+   * @param end_stream boolean supplies whether this is the last data frame.
    */
-  virtual void addEncodedData(Buffer::Instance& data, bool streaming_filter) PURE;
+  virtual void addEncodedData(Buffer::Instance& data, bool streaming_filter, bool end_stream) PURE;
```
Comment (mattklein123) [inline include/envoy/http/filter.h:637]: If we stick with this fix we should do a parallel fix in addDecodedData

File: source/common/http/conn_manager_impl.cc (hunk 2 above)
Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc]: I haven't fully tracked this PR, so apologies, but in general if there is a simple fix I think we should do that. However, I'm a little confused what that fix would be. Are you suggesting to replace empty trailers with an empty data block with end_stream set? If so that seems OK to me.

Either way I agree with @alyssawilk that I would like to see a runtime feature flag for this as well as an integration test.

Comment (dio) [reply source/common/http/conn_manager_impl.cc]: @mattklein123 yes, the original proposal was replacing it by empty data block.

Comment (dio) [reply source/common/http/conn_manager_impl.cc]: @mattklein123 @alyssawilk @lizan is it OK to proceed with the simpler approach first (with runtime guard), then revisit the `addEncodedData`/`addDecodedData` changes after?

Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc]: SGTM!

Comment (lizan) [reply source/common/http/conn_manager_impl.cc]: SG. Can you file an issue to track that?

Comment (lizan) [reply source/common/http/conn_manager_impl.cc]: On a second thought, since TrailersMap is already a separate class, how about we just add a boolean flag there to indicate it shouldn't be encoded, rather than relying on `empty()`?

Comment (dio) [reply source/common/http/conn_manager_impl.cc]: @lizan are you saying that having empty trailers doesn't automatically infer skipping encoding? And filter needs to explicitly set that?

Comment (dio) [reply source/common/http/conn_manager_impl.cc]: Submitted the issue here: https://github.com/envoyproxy/envoy/issues/12374.

Comment (lizan) [reply source/common/http/conn_manager_impl.cc]: > @lizan are you saying that having empty trailers doesn't automatically infer skipping encoding? And filter needs to explicitly set that?

Yes. We can add a flag to https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/header_map.h#L761 ?

Comment (dio) [reply source/common/http/conn_manager_impl.cc]: Cool. Adding flag seems fine. I wanted to confirm the behavior: explicitness of skipping encoding is controlled by filter not the trailers "data".

Comment (lizan) [reply source/common/http/conn_manager_impl.cc]: Yep

File: docs/root/version_history/current.rst [hunk 5]
```diff
@@ -28,6 +28,7 @@ Bug Fixes
 * csrf: fixed issues with regards to origin and host header parsing.
 * dynamic_forward_proxy: only perform DNS lookups for routes to Dynamic Forward Proxy clusters since other cluster types handle DNS lookup themselves.
 * fault: fixed an issue with `active_faults` gauge not being decremented for when abort faults were injected.
+* grpc-web: fixed an issue with failing HTTP/2 requests on some browsers. Notably, WebKit-based browsers (https://bugs.webkit.org/show_bug.cgi?id=210108), Internet Explorer 11, and Edge (pre-Chromium).
```
Comment (alyssawilk) [inline docs/root/version_history/current.rst:31]: Release note should go back to being general, and include the runtime guard

File: source/common/http/conn_manager_impl.cc [hunk 6]
```diff
@@ -2079,6 +2079,20 @@ void ConnectionManagerImpl::FilterManager::encodeTrailers(ActiveStreamEncoderFil
     }
   }
 
+  // Some browsers (e.g. WebKit-based browsers: https://bugs.webkit.org/show_bug.cgi?id=210108) have
+  // a problem with processing empty trailers (END_STREAM | END_HEADERS with zero length HEADERS) of
+  // an HTTP/2 response as reported here: https://github.com/envoyproxy/envoy/issues/10514.
+  const bool skip_encoding_empty_trailers =
+      Runtime::runtimeFeatureEnabled("envoy.reloadable_features.skip_encoding_empty_trailers");
```
Comment (alyssawilk) [inline source/common/http/conn_manager_impl.cc:2086]: If it's just HTTP/2 should we do it in the codec?  It would potentially affect the request and response, but it'd leave complexity outside the HCM and wouldn't affect HTTP/1.1 with trailers.  I'd mildly prefer that location but I'm Ok doing it here if we explicitly check that it's HTTP/2

Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc:2086]: +1 to move to the codec

File: docs/root/version_history/current.rst (hunk 5 above)
Comment (dio) [reply docs/root/version_history/current.rst:33]: This is a side-effect of skipping encoding empty trailers, could we keep this one as well?

File: source/common/http/http2/codec_impl.cc [hunk 7]
```diff
@@ -344,6 +349,20 @@ void ConnectionImpl::StreamImpl::saveHeader(HeaderString&& name, HeaderString&&
 }
 
 void ConnectionImpl::StreamImpl::submitTrailers(const HeaderMap& trailers) {
+  // Some browsers (e.g. WebKit-based browsers: https://bugs.webkit.org/show_bug.cgi?id=210108) have
+  // a problem with processing empty trailers (END_STREAM | END_HEADERS with zero length HEADERS) of
+  // an HTTP/2 response as reported here: https://github.com/envoyproxy/envoy/issues/10514.
+  const bool skip_encoding_empty_trailers =
+      Runtime::runtimeFeatureEnabled("envoy.reloadable_features.skip_encoding_empty_trailers");
+  if (trailers.empty() && skip_encoding_empty_trailers) {
```
Comment (dio) [inline source/common/http/http2/codec_impl.cc:357]: So I haven't implemented @lizan's suggestions on adding a flag to `ResponseTrailerMap` which tells whether the trailers map needs to be submitted or not. Hence it is up to filter to decide, even when the map is not empty. If this is an agreeable action that needs to be done I'll do that. cc. @alyssawilk @mattklein123.

File: source/common/http/conn_manager_impl.cc (hunk 6 above)
Comment (dio) [reply source/common/http/conn_manager_impl.cc]: Moved to codec.

File: source/common/http/http2/codec_impl.cc (hunk 7 above)
Comment (mattklein123) [reply source/common/http/http2/codec_impl.cc:357]: My personal opinion is that replacing empty trailers with a empty data frame with end_stream true is very likely safe in all cases. I would vote to just do it universally behind a runtime flag and see if anyone complains?

File: docs/root/version_history/current.rst [hunk 8]
```diff
@@ -15,6 +15,7 @@ Minor Behavior Changes
 * http: changed Envoy to send error headers and body when possible. This behavior may be temporarily reverted by setting `envoy.reloadable_features.allow_response_for_timeout` to false.
 * http: clarified and enforced 1xx handling. Multiple 100-continue headers are coalesced when proxying. 1xx headers other than {100, 101} are dropped.
 * http: fixed the 100-continue response path to properly handle upstream failure by sending 5xx responses. This behavior can be temporarily reverted by setting `envoy.reloadable_features.allow_500_after_100` to false.
+* http: skip encoding empty trailers. This behavior can be reverted temporarily by setting runtime feature `envoy.reloadable_features.skip_encoding_empty_trailers` to false.
```
Comment (mattklein123) [inline docs/root/version_history/current.rst:18]: Can you clarify that this is a) for HTTP/2 and b) replaces empty trailers with an empty data frame with end_stream == true?

File: docs/root/version_history/current.rst (hunk 5 above)
Comment (mattklein123) [reply docs/root/version_history/current.rst:33]: Yeah this is fine, thanks.

File: source/common/http/http2/codec_impl.cc [hunk 9]
```diff
@@ -222,7 +223,11 @@ void ConnectionImpl::ServerStreamImpl::encodeHeaders(const ResponseHeaderMap& he
 
 void ConnectionImpl::StreamImpl::encodeTrailersBase(const HeaderMap& trailers) {
   ASSERT(!local_end_stream_);
-  local_end_stream_ = true;
+
+  const bool skip_encoding_empty_trailers =
+      Runtime::runtimeFeatureEnabled("envoy.reloadable_features.skip_encoding_empty_trailers");
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.cc:228]: nit: I would just latch this in the connection constructor.

File: source/common/http/http2/codec_impl.cc [hunk 10]
```diff
@@ -222,7 +223,11 @@ void ConnectionImpl::ServerStreamImpl::encodeHeaders(const ResponseHeaderMap& he
...
+  local_end_stream_ = !(trailers.empty() && skip_encoding_empty_trailers);
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.cc:229]: I'm confused why local_end_stream_ is not always true here like it was before. Logically it's the same, right?

File: source/common/http/http2/codec_impl.cc [hunk 11]
```diff
@@ -344,6 +349,20 @@ void ConnectionImpl::StreamImpl::saveHeader(HeaderString&& name, HeaderString&&
 }
 
 void ConnectionImpl::StreamImpl::submitTrailers(const HeaderMap& trailers) {
+  // Some browsers (e.g. WebKit-based browsers: https://bugs.webkit.org/show_bug.cgi?id=210108) have
+  // a problem with processing empty trailers (END_STREAM | END_HEADERS with zero length HEADERS) of
+  // an HTTP/2 response as reported here: https://github.com/envoyproxy/envoy/issues/10514.
+  const bool skip_encoding_empty_trailers =
+      Runtime::runtimeFeatureEnabled("envoy.reloadable_features.skip_encoding_empty_trailers");
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.cc:356]: per other comment, this can be latched, also per my other comment I don't think we need to change the other function.

File: source/common/http/http2/codec_impl.cc (hunk 10 above)
Comment (dio) [reply source/common/http/http2/codec_impl.cc:229]: If we set it true here, we can't call `encodeData` due to assertion here: https://github.com/envoyproxy/envoy/blob/d7c7e9a79eed80afa56a0b05cf6adf0516750d14/source/common/http/http2/codec_impl.cc#L444

Comment (mattklein123) [reply source/common/http/http2/codec_impl.cc:229]: I would fix the assertion somehow. I think it's incorrect to change local_end_stream_ to not be true here. (You could somehow not fire the assertion in the empty trailer conversion case by having a common encodeData helper function with a boolean param or something like that, up to you)

File: docs/root/version_history/current.rst (hunk 8 above)
Comment (dio) [reply docs/root/version_history/current.rst]: I have updated the entry.

File: source/common/http/http2/codec_impl.cc [hunk 12]
```diff
@@ -441,7 +451,7 @@ void ConnectionImpl::StreamImpl::onPendingFlushTimer() {
 }
 
 void ConnectionImpl::StreamImpl::encodeData(Buffer::Instance& data, bool end_stream) {
-  ASSERT(!local_end_stream_);
+  ASSERT(!local_end_stream_ || (parent_.skip_encoding_empty_trailers_ && end_stream));
```
Comment (PiotrSikora) [inline source/common/http/http2/codec_impl.cc:454]: Assuming that `local_end_stream_` means that we already sent `END_STREAM`, this seems wrong, since we cannot emit it again.

File: docs/root/version_history/current.rst [hunk 13]
```diff
@@ -15,6 +15,7 @@ Minor Behavior Changes
 * http: changed Envoy to send error headers and body when possible. This behavior may be temporarily reverted by setting `envoy.reloadable_features.allow_response_for_timeout` to false.
 * http: clarified and enforced 1xx handling. Multiple 100-continue headers are coalesced when proxying. 1xx headers other than {100, 101} are dropped.
 * http: fixed the 100-continue response path to properly handle upstream failure by sending 5xx responses. This behavior can be temporarily reverted by setting `envoy.reloadable_features.allow_500_after_100` to false.
+* http: changed empty trailers encoding behavior by sending empty data with end_stream true (instead of sending empty trailers) for HTTP/2 downstream. This behavior can be reverted temporarily by setting runtime feature `envoy.reloadable_features.skip_encoding_empty_trailers` to false.
```
Comment (mattklein123) [inline docs/root/version_history/current.rst:18]:
```suggestion
* http: changed empty trailers encoding behavior by sending empty data with end_stream true (instead of sending empty trailers) for HTTP/2. This behavior can be reverted temporarily by setting runtime feature `envoy.reloadable_features.skip_encoding_empty_trailers` to false.
```

File: source/common/http/http2/codec_impl.cc (hunk 12 above)
Comment (mattklein123) [reply source/common/http/http2/codec_impl.cc:454]: It doesn't mean that, it's logical in that the stream owner thinks that have finished the stream. However, I think this is a bit fragile from an assert perspective. Can you add an `encodeDataHelper` or similar and pass a boolean as to whether we are calling this to handle the empty trailer case? That will all the assert to be more clear.

File: source/common/http/http2/codec_impl.cc [hunk 14]
```diff
@@ -530,6 +540,8 @@ ConnectionImpl::ConnectionImpl(Network::Connection& connection, CodecStats& stat
           http2_options.max_inbound_priority_frames_per_stream().value()),
       max_inbound_window_update_frames_per_data_frame_sent_(
           http2_options.max_inbound_window_update_frames_per_data_frame_sent().value()),
+      skip_encoding_empty_trailers_(
+          Runtime::runtimeFeatureEnabled("envoy.reloadable_features.skip_encoding_empty_trailers")),
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.cc:544]:
```suggestion
          Runtime::runtimeFeatureEnabled("envoy.reloadable_features.http2_skip_encoding_empty_trailers")),
```

?

Comment (dio) [reply source/common/http/http2/codec_impl.cc]: Updated with the suggestion. Thank you!

File: docs/root/version_history/current.rst (hunk 13 above)
Comment (dio) [reply docs/root/version_history/current.rst]: 👍

File: source/common/http/http2/codec_impl.cc (hunk 12 above)
Comment (dio) [reply source/common/http/http2/codec_impl.cc]: Sorry I didn't get you for the first time. While I'm not 100% sure, I have updated to have a helper.

**Comment by dio** [comment]
@lizan I obviously missed the resolution for: 

```
source/common/http/http2/codec_impl.h:19:10: error: 'common/common/statusor.h' file not found [clang-diagnostic-error]
```

Could spell your magic here? Thanks!

**Comment by lizan** [comment]
@dio #12426 is the ultimate solution

File: source/common/http/http2/codec_impl_legacy.cc [hunk 15]
```diff
@@ -333,6 +334,17 @@ void ConnectionImpl::StreamImpl::saveHeader(HeaderString&& name, HeaderString&&
 }
 
 void ConnectionImpl::StreamImpl::submitTrailers(const HeaderMap& trailers) {
+  const bool skip_encoding_empty_trailers =
+      trailers.empty() && parent_.skip_encoding_empty_trailers_;
+  if (skip_encoding_empty_trailers) {
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl_legacy.cc:339]: can you ASSERT(local_end_stream_) above this line? I think it should always be true?

Comment (dio) [reply source/common/http/http2/codec_impl_legacy.cc:340]: Added in 3f2c2d8.

**Comment by dio** [comment]
Thanks to @lizan clang-tidy issue for codec_impl.h is fixed.

**Comment by mattklein123** [comment]
LGTM can you merge main?

/wait
