### PR TITLE
Shellcheck: bazel/ examples/ and other remaining linting issues

### LINKED ISSUE #7793: Use Shellcheck on CI for static analysis of Bash scripts
*Title*: Use Shellcheck on CI for static analysis of Bash scripts

*Description*:
[Shellcheck](https://www.shellcheck.net/) is a shell script analysis tool with numerous flags for atypical or dangerous bash constructs. Shellcheck's [Gallery of Bad Code](https://github.com/koalaman/shellcheck#gallery-of-bad-code) gives examples of what it catches. It's how I identified [this minor bash issue](https://github.com/envoyproxy/envoy/pull/5406) in Envoy previously.

Shellcheck is additionally configurable so we can disable flags we don't want at the global level, file level, or line level for one-off exceptions. My team has been using Shellcheck and found it quite helpful. The only downside I know of is that it doesn't have a `--fix` flag like `clang-tidy` does.

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: Shellcheck: bazel/ examples/
Additional Description:
Remaining shellcheck cleanups
Risk Level: low
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] fixes #7793
[Optional Deprecated:]

### CODE REVIEW

File: bazel/coverage/collect_cc_coverage.sh [hunk 1]
```diff
@@ -68,24 +68,24 @@ function init_gcov() {
 # $COVERAGE_DIR.
 # Writes the collected coverage into the given output file.
 function llvm_coverage() {
-  local output_file="${1}"; shift
+  local output_file="${1}" object_files object_param=()
```
Comment (phlax) [inline bazel/coverage/collect_cc_coverage.sh:71]: add `object_file`

File: bazel/coverage/collect_cc_coverage.sh [hunk 2]
```diff
@@ -97,25 +97,27 @@ function llvm_coverage() {
 # - output_file     The location of the file where the generated code coverage
 #                   report is written.
 function gcov_coverage() {
-  local output_file="${1}"; shift
+  local gcda output_file="${1}"
```
Comment (phlax) [inline bazel/coverage/collect_cc_coverage.sh:100]: add `line`

File: bazel/coverage/collect_cc_coverage.sh [hunk 3]
```diff
@@ -134,12 +136,12 @@ function gcov_coverage() {
           # Don't generate branch coverage (-b) because of a gcov issue that
           # segfaults when both -i and -b are used (see
           # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84879).
-          "${GCOV}" -i $COVERAGE_GCOV_OPTIONS -o "$(dirname ${gcda})" "${gcda}"
+          "${GCOV}" -i "$COVERAGE_GCOV_OPTIONS" -o "$(dirname "${gcda}")" "${gcda}"
```
Comment (phlax) [inline bazel/coverage/collect_cc_coverage.sh:139]: im wondering if this should be an array, but it doesnt appear to be defined anywhere

File: bazel/test_for_benchmark_wrapper.sh [hunk 4]
```diff
@@ -3,4 +3,4 @@
 # Set the benchmark time to 0 to just verify that the benchmark runs to
 # completion.  We're interacting with two different flag parsers, so the order
 # of flags and the -- matters.
-"${TEST_SRCDIR}/envoy/$@" --skip_expensive_benchmarks -- --benchmark_min_time=0
+"${TEST_SRCDIR}/envoy/$*" --skip_expensive_benchmarks -- --benchmark_min_time=0
```
Comment (phlax) [inline bazel/test_for_benchmark_wrapper.sh:6]: not sure about this

File: bazel/sh_test_wrapper.sh [hunk 5]
```diff
@@ -4,8 +4,8 @@
 # TODO(lizan): remove when we have a solution for
 # https://github.com/bazelbuild/bazel/issues/3510
 
-cd $(dirname "$0")
+cd "$(dirname "$0")" || exit 1
 
 if [ $# -gt 0 ]; then
-  "./$@"
+  "./$*"
```
Comment (phlax) [inline bazel/sh_test_wrapper.sh:10]: not sure about this

File: bazel/coverage/fuzz_coverage_wrapper.sh [hunk 6]
```diff
@@ -9,11 +9,11 @@ shift
...
 
 # TODO(asraa): When fuzz targets are stable, remove error suppression and run coverage while fuzzing.
-LLVM_PROFILE_FILE= ${TEST_BINARY} fuzz_corpus -seed=${FUZZ_CORPUS_SEED:-1} -max_total_time=${FUZZ_CORPUS_TIME:-60} -max_len=2048 -rss_limit_mb=8192 -timeout=30 || true
+LLVM_PROFILE_FILE=${TEST_BINARY} fuzz_corpus -seed="${FUZZ_CORPUS_SEED:-1}" -max_total_time="${FUZZ_CORPUS_TIME:-60}" -max_len=2048 -rss_limit_mb=8192 -timeout=30 || :
 
 # Passing files instead of a directory will run fuzzing as a regression test.
-# TODO(asraa): Remove manual `|| true`, but this shouldn't be necessary. 
-${TEST_BINARY} $(find fuzz_corpus -type f) -rss_limit_mb=8192 || true
+# TODO(asraa): Remove manual `|| :`, but this shouldn't be necessary.
+${TEST_BINARY} "$(find fuzz_corpus -type f)" -rss_limit_mb=8192 || :
```
Comment (phlax) [inline bazel/coverage/fuzz_coverage_wrapper.sh:19]: im wondering if this will handle multiline output from `find` correctly

File: bazel/coverage/collect_cc_coverage.sh (hunk 3 above)
Comment (zuercher) [reply bazel/coverage/collect_cc_coverage.sh:139]: It's noted in the comment at the top as a var you set to pass extra options. I expect that also means it shouldn't get quoted or you won't be able to pass multiple options?

File: bazel/coverage/fuzz_coverage_wrapper.sh (hunk 6 above)
Comment (zuercher) [reply bazel/coverage/fuzz_coverage_wrapper.sh:19]: I don't think it does:
```
$ printf "1: %s, 2: %s\n" $(printf "a\nb\n")
1: a, 2: b
$ printf "1: %s, 2: %s\n" "$(printf "a\nb\n")"
1: a
b, 2: 
```

File: bazel/coverage/collect_cc_coverage.sh (hunk 3 above)
Comment (phlax) [reply bazel/coverage/collect_cc_coverage.sh:139]: > I expect that also means it shouldn't get quoted or you won't be able to pass multiple options?

yep - well that, or read into array (and make shellcheck happy)

File: bazel/coverage/fuzz_coverage_wrapper.sh (hunk 6 above)
Comment (phlax) [reply bazel/coverage/fuzz_coverage_wrapper.sh:19]: which without `readarray` means this i think
```
$ _args="$(printf "a\nb\n")"
$ while read -r line; do args+=($line); done \
    <<< "$_args"
$ printf "1: %s, 2: %s\n" "${args[@]}"
1: a, 2: b
```

File: bazel/coverage/collect_cc_coverage.sh [hunk 7]
```diff
@@ -97,25 +99,27 @@ function llvm_coverage() {
...
 #                   report is written.
 function gcov_coverage() {
-  local output_file="${1}"; shift
+  local gcda gcno_path line output_file="${1}"
+  shift
 
   # We'll save the standard output of each the gcov command in this log.
-  local gcov_log="$output_file.gcov.log"
+  # this appears to be unused
+  # local gcov_log="$output_file.gcov.log"
```
Comment (phlax) [inline bazel/coverage/collect_cc_coverage.sh:107]: @zuercher im wondering whether its better to remove this or add `> "$gcov_log"` to the end of the `gcov` command. 

afaict, at least in the ci pipeline its not going to be collected by anything

Comment (phlax) [reply bazel/coverage/collect_cc_coverage.sh:107]: ...and probs would suppress stdout too

File: bazel/coverage/fuzz_coverage_wrapper.sh [hunk 8]
```diff
@@ -9,11 +9,14 @@ shift
 rm -rf fuzz_corpus
 
 mkdir -p fuzz_corpus/seed_corpus
-cp -r $@ fuzz_corpus/seed_corpus
+cp -r "$@" fuzz_corpus/seed_corpus
 
 # TODO(asraa): When fuzz targets are stable, remove error suppression and run coverage while fuzzing.
-LLVM_PROFILE_FILE= ${TEST_BINARY} fuzz_corpus -seed=${FUZZ_CORPUS_SEED:-1} -max_total_time=${FUZZ_CORPUS_TIME:-60} -max_len=2048 -rss_limit_mb=8192 -timeout=30 || true
```
Comment (phlax) [inline bazel/coverage/fuzz_coverage_wrapper.sh:15]: i think this space is intentional, hopefully this is the cause of the fail...

**Comment by phlax** [comment]
im thinking that #12889 should probably land before this one as i think one or other will need to rebase

File: bazel/coverage/fuzz_coverage_wrapper.sh (hunk 8 above)
Comment (phlax) [reply bazel/coverage/fuzz_coverage_wrapper.sh:15]: great! that worked

File: ci/build_setup.sh [hunk 9]
```diff
@@ -86,7 +86,9 @@ export LLVM_ROOT="${LLVM_ROOT:-/opt/llvm}"
 
 [[ "${BUILD_REASON}" != "PullRequest" ]] && BAZEL_EXTRA_TEST_OPTIONS+=("--nocache_test_results")
 
-export BAZEL_QUERY_OPTIONS="${BAZEL_OPTIONS}"
+# TODO(phlax): deprecate/remove this - i believe it was made redundant here:
+#   https://github.com/envoyproxy/envoy/commit/3ebedeb708a23062332a6fcdf33b462b7070adba#diff-2fa22a1337effee365a51e6844be0ab3
```
Comment (phlax) [inline ci/build_setup.sh:90]: just to flag this @zuercher

File: bazel/coverage/collect_cc_coverage.sh (hunk 7 above)
Comment (zuercher) [reply bazel/coverage/collect_cc_coverage.sh:107]: I think just remove it.

**Comment by zuercher** [comment]
This looks good to me. Do you want to hold it until #12889 lands?

**Comment by phlax** [comment]
> This looks good to me. Do you want to hold it until #12889 lands?

yep waiting...

8)

**Comment by zuercher** [comment]
Is this ready to go now?

**Comment by phlax** [comment]
yep

**Review by zuercher — APPROVED** [review]
