### PR TITLE
starttls: double events when connecting upstream

### LINKED ISSUE #19232: starttls transport socket double open event
*Title*: starttls transport socket double open event

*Description*:
I am writing a small filter that is meant to take advantage of the starttls transport in order to handle a server-first pre-TLS handshake. I've completed the custom implementation and it works properly up to the point where the TLS negotiation succeeds.

Pretty sure this is a bug, but I'm not exactly sure the best route to take in fixing it. Probably an e2e test that triggers the bug.

@cpakulski @lizan

*Repro steps*:

The rawbuffer socket that the connection is initiated with raises an `onConnected` event when the socket successfully connects. The problem comes after `startSecureTransport` is called and the sslsocket completes its handshake, it also calles `onConnected` (expected in cases where it's the only socket handler).

This second connected event confuses the connection pooler and causes an assert (in debug build, segfault in release) when it attempts to move the socket from the pending queue, where it does not reside.

*Logs*:
```
2021-12-09T16:52:21.384887Z	debug	envoy connection	[C6] connecting to 10.66.20.131:4222
2021-12-09T16:52:21.384986Z	debug	envoy connection	[C6] connection in progress
2021-12-09T16:52:21.385009Z	debug	envoy pool	queueing request due to no available connections
2021-12-09T16:52:21.385024Z	debug	envoy conn_handler	[C5] new connection from 10.66.94.100:45272
2021-12-09T16:52:21.385057Z	trace	envoy connection	[C5] socket event: 2
2021-12-09T16:52:21.385063Z	trace	envoy connection	[C5] write ready
2021-12-09T16:52:21.385356Z	trace	envoy connection	[C6] socket event: 2
2021-12-09T16:52:21.385366Z	trace	envoy connection	[C6] write ready
2021-12-09T16:52:21.385373Z	debug	envoy connection	[C6] connected
2021-12-09T16:52:21.385378Z	trace	envoy connection	[C6] raising connection event 2
2021-12-09T16:52:21.385389Z	debug	envoy pool	[C6] assigning connection
2021-12-09T16:52:21.385403Z	trace	envoy connection	[C5] readDisable: disable=false disable_count=1 state=0 buffer_length=0
2021-12-09T16:52:21.385427Z	debug	envoy filter	[C5] TCP:onUpstreamEvent(), requestedServerName: 
2021-12-09T16:52:21.385468Z	trace	envoy connection	[C5] socket event: 2
2021-12-09T16:52:21.385475Z	trace	envoy connection	[C5] write ready
2021-12-09T16:52:21.385848Z	trace	envoy connection	[C6] socket event: 3
2021-12-09T16:52:21.385858Z	trace	envoy connection	[C6] write ready
2021-12-09T16:52:21.385866Z	trace	envoy connection	[C6] read ready. dispatch_buffered_data=false
2021-12-09T16:52:21.385914Z	trace	envoy connection	[C6] read returns: 255
2021-12-09T16:52:21.385944Z	trace	envoy connection	[C6] read error: Resource temporarily unavailable
2021-12-09T16:52:21.385956Z	trace	envoy filter	Alpn Protocol Not Found. Expected istio-peer-exchange, Got starttls
2021-12-09T16:52:21.385980Z	trace	envoy filter	[C6] nats_hs: onData(255bytes,false) 'INFO {"server_id":"7ORFS8GtENuL3rCZs76jsT","version":"1.3.0","proto":1,"go":"go1.11","host":"0.0.0.0","port":4222,"tls_required":true,"tls_verify":true,"max_payload":20971520,"client_id":5829382,"connect_urls":["10.66.20.131:4222","10.66.20.130:4222"]} 

'
2021-12-09T16:52:21.385987Z	trace	envoy filter	[C6] nats_hs: handling
2021-12-09T16:52:21.386072Z	trace	envoy filter	[C6] nats_hs: unmarshalled info pdu
2021-12-09T16:52:21.386083Z	trace	envoy filter	[C6] nats_hs: server requires tls, starting secure transport
2021-12-09T16:52:21.386094Z	trace	envoy filter	[C6] nats_hs: tls handshake begun
2021-12-09T16:52:21.386130Z	trace	envoy filter	[C6] nats_hs: sending transmogrified info downstream, I take my leave 'INFO {"client_id":5829382,"go":"go1.11","host":"0.0.0.0","max_payload":20971520,"port":4222,"proto":1,"server_id":"7ORFS8GtENuL3rCZs76jsT","version":"1.3.0"}

'
2021-12-09T16:52:21.386140Z	trace	envoy filter	[C5] upstream connection received 159 bytes, end_stream=false
2021-12-09T16:52:21.386151Z	trace	envoy connection	[C5] writing 159 bytes, end_stream false
2021-12-09T16:52:21.386177Z	trace	envoy connection	[C5] socket event: 2
2021-12-09T16:52:21.386183Z	trace	envoy connection	[C5] write ready
2021-12-09T16:52:21.386219Z	trace	envoy connection	[C5] write returns: 159
2021-12-09T16:52:21.386448Z	trace	envoy connection	[C5] socket event: 3
2021-12-09T16:52:21.386457Z	trace	envoy connection	[C5] write ready
2021-12-09T16:52:21.386468Z	trace	envoy connection	[C5] read ready. dispatch_buffered_data=false
2021-12-09T16:52:21.386499Z	trace	envoy connection	[C5] read returns: 137
2021-12-09T16:52:21.386522Z	trace	envoy connection	[C5] read error: Resource temporarily unavailable
2021-12-09T16:52:21.386534Z	trace	envoy filter	[C5] downstream connection received 137 bytes, end_stream=false
2021-12-09T16:52:21.386543Z	trace	envoy filter	[C6] nats_hs: onWrite(137bytes,false) 'CONNECT {"verbose":false,"pedantic":false,"tls_required":false,"name":"","lang":"go","version":"1.10.0","protocol":1,"echo":true}

PING

'
2021-12-09T16:52:21.386598Z	trace	envoy filter	[C6] nats_hs: unmarshalled connect pdu
2021-12-09T16:52:21.386641Z	trace	envoy filter	[C6] nats_hs: sending transmogrified connect upstream, I take my leave 'CONNECT {"echo":true,"lang":"go","name":"","pedantic":false,"tls_required":true,"verbose":false,"version":"1.10.0"}

PING

'
2021-12-09T16:52:21.386656Z	trace	envoy connection	[C6] writing 123 bytes, end_stream false
2021-12-09T16:52:21.386676Z	trace	envoy connection	[C6] socket event: 2
2021-12-09T16:52:21.386681Z	trace	envoy connection	[C6] write ready
2021-12-09T16:52:21.386756Z	trace	envoy connection	[C6] ssl error occurred while read: WANT_READ
2021-12-09T16:52:21.398687Z	trace	envoy connection	[C6] socket event: 3
2021-12-09T16:52:21.398702Z	trace	envoy connection	[C6] write ready
2021-12-09T16:52:21.411023Z	trace	envoy connection	[C6] ssl error occurred while read: WANT_READ
2021-12-09T16:52:21.411044Z	trace	envoy connection	[C6] read ready. dispatch_buffered_data=false
2021-12-09T16:52:21.411053Z	trace	envoy connection	[C6] ssl error occurred while read: WANT_READ
2021-12-09T16:52:21.411968Z	trace	envoy connection	[C6] socket event: 3
2021-12-09T16:52:21.411980Z	trace	envoy connection	[C6] write ready
2021-12-09T16:52:21.412281Z	trace	envoy connection	[C6] raising connection event 2
2021-12-09T16:52:21.412302Z	debug	envoy pool	[C6] moving to ready
2021-12-09T16:52:21.412310Z	critical	envoy assert	assert failure: std::find(src.begin(), src.end(), *entry_) != src.end().
2021-12-09T16:52:21.412334Z	critical	envoy backtrace	Caught Aborted, suspect faulting address 0x53900000011
2021-12-09T16:52:21.412343Z	critical	envoy backtrace	Backtrace (use tools/stack_decode.py to get line numbers):
2021-12-09T16:52:21.412350Z	critical	envoy backtrace	Envoy version: 2fa0bfebd2757680b1e49017c6439cba5d4fed1a/1.19.2-dev/Modified/DEBUG/BoringSSL
2021-12-09T16:52:21.442870Z	critical	envoy backtrace	#0: Envoy::SignalAction::sigHandler() [0x55d7b8eab4cc]
2021-12-09T16:52:21.442970Z	critical	envoy backtrace	#1: __restore_rt [0x7f8fcf1143c0]
2021-12-09T16:52:21.474084Z	critical	envoy backtrace	#2: Envoy::Tcp::OriginalConnPoolImpl::processIdleConnection() [0x55d7b7eb56c6]
2021-12-09T16:52:21.504416Z	critical	envoy backtrace	#3: Envoy::Tcp::OriginalConnPoolImpl::onConnectionEvent() [0x55d7b7eb50cc]
2021-12-09T16:52:21.536408Z	critical	envoy backtrace	#4: Envoy::Tcp::OriginalConnPoolImpl::ActiveConn::onEvent() [0x55d7b7eba15c]
2021-12-09T16:52:21.566556Z	critical	envoy backtrace	#5: Envoy::Network::ConnectionImplBase::raiseConnectionEvent() [0x55d7b8bb9fcc]
2021-12-09T16:52:21.596781Z	critical	envoy backtrace	#6: Envoy::Network::ConnectionImpl::raiseEvent() [0x55d7b8b9c08c]
2021-12-09T16:52:21.627116Z	critical	envoy backtrace	#7: Envoy::Extensions::TransportSockets::Tls::SslSocket::onSuccess() [0x55d7b8a9feec]
2021-12-09T16:52:21.657293Z	critical	envoy backtrace	#8: Envoy::Extensions::TransportSockets::Tls::SslHandshakerImpl::doHandshake() [0x55d7b8c1c417]
2021-12-09T16:52:21.687428Z	critical	envoy backtrace	#9: Envoy::Extensions::TransportSockets::Tls::SslSocket::doHandshake() [0x55d7b8a9ea9a]
2021-12-09T16:52:21.718362Z	critical	envoy backtrace	#10: Envoy::Extensions::TransportSockets::Tls::SslSocket::doWrite() [0x55d7b8aa039d]
2021-12-09T16:52:21.748434Z	critical	envoy backtrace	#11: Envoy::Extensions::TransportSockets::StartTls::StartTlsSocket::doWrite() [0x55d7b65744a6]
2021-12-09T16:52:21.778804Z	critical	envoy backtrace	#12: Envoy::Network::ConnectionImpl::onWriteReady() [0x55d7b8ba4bc4]
2021-12-09T16:52:21.808892Z	critical	envoy backtrace	#13: Envoy::Network::ConnectionImpl::onFileEvent() [0x55d7b8ba35ec]
2021-12-09T16:52:21.840062Z	critical	envoy backtrace	#14: Envoy::Network::ConnectionImpl::ConnectionImpl()::$_6::operator()() [0x55d7b8bb3d4e]
2021-12-09T16:52:21.871298Z	critical	envoy backtrace	#15: std::__1::__invoke<>() [0x55d7b8bb3d11]
2021-12-09T16:52:21.902333Z	critical	envoy backtrace	#16: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x55d7b8bb3cb2]
2021-12-09T16:52:21.933909Z	critical	envoy backtrace	#17: std::__1::__function::__alloc_func<>::operator()() [0x55d7b8bb3c72]
2021-12-09T16:52:21.964447Z	critical	envoy backtrace	#18: std::__1::__function::__func<>::operator()() [0x55d7b8bb2de3]
2021-12-09T16:52:21.994698Z	critical	envoy backtrace	#19: std::__1::__function::__value_func<>::operator()() [0x55d7b8b5244d]
2021-12-09T16:52:22.026756Z	critical	envoy backtrace	#20: std::__1::function<>::operator()() [0x55d7b8b523ef]
2021-12-09T16:52:22.064591Z	critical	envoy backtrace	#21: Envoy::Event::DispatcherImpl::createFileEvent()::$_5::operator()() [0x55d7b8b465c4]
2021-12-09T16:52:22.106230Z	critical	envoy backtrace	#22: std::__1::__invoke<>() [0x55d7b8b46571]
2021-12-09T16:52:22.136652Z	critical	envoy backtrace	#23: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x55d7b8b46512]
2021-12-09T16:52:22.168610Z	critical	envoy backtrace	#24: std::__1::__function::__alloc_func<>::operator()() [0x55d7b8b464d2]
2021-12-09T16:52:22.200526Z	critical	envoy backtrace	#25: std::__1::__function::__func<>::operator()() [0x55d7b8b456e3]
2021-12-09T16:52:22.200561Z	critical	envoy backtrace	#26: std::__1::__function::__value_func<>::operator()() [0x55d7b8b5244d]
2021-12-09T16:52:22.200568Z	critical	envoy backtrace	#27: std::__1::function<>::operator()() [0x55d7b8b523ef]
2021-12-09T16:52:22.232617Z	critical	envoy backtrace	#28: Envoy::Event::FileEventImpl::mergeInjectedEventsAndRunCb() [0x55d7b8b5961f]
2021-12-09T16:52:22.264092Z	critical	envoy backtrace	#29: Envoy::Event::FileEventImpl::assignEvents()::$_1::operator()() [0x55d7b8b59a6a]
2021-12-09T16:52:22.294572Z	critical	envoy backtrace	#30: Envoy::Event::FileEventImpl::assignEvents()::$_1::__invoke() [0x55d7b8b59666]
2021-12-09T16:52:22.325388Z	critical	envoy backtrace	#31: event_persist_closure [0x55d7b8e89a4e]
2021-12-09T16:52:22.356128Z	critical	envoy backtrace	#32: event_process_active_single_queue [0x55d7b8e89078]
2021-12-09T16:52:22.386445Z	critical	envoy backtrace	#33: event_process_active [0x55d7b8e8383a]
2021-12-09T16:52:22.416534Z	critical	envoy backtrace	#34: event_base_loop [0x55d7b8e826ec]
2021-12-09T16:52:22.446563Z	critical	envoy backtrace	#35: Envoy::Event::LibeventScheduler::run() [0x55d7b8e2fb64]
2021-12-09T16:52:22.476735Z	critical	envoy backtrace	#36: Envoy::Event::DispatcherImpl::run() [0x55d7b8b3aada]
2021-12-09T16:52:22.506790Z	critical	envoy backtrace	#37: Envoy::Server::WorkerImpl::threadRoutine() [0x55d7b789d616]
2021-12-09T16:52:22.536799Z	critical	envoy backtrace	#38: Envoy::Server::WorkerImpl::start()::$_5::operator()() [0x55d7b78a65f5]
2021-12-09T16:52:22.566634Z	critical	envoy backtrace	#39: std::__1::__invoke<>() [0x55d7b78a65ad]
2021-12-09T16:52:22.596952Z	critical	envoy backtrace	#40: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x55d7b78a655d]
2021-12-09T16:52:22.626754Z	critical	envoy backtrace	#41: std::__1::__function::__alloc_func<>::operator()() [0x55d7b78a652d]
2021-12-09T16:52:22.656953Z	critical	envoy backtrace	#42: std::__1::__function::__func<>::operator()() [0x55d7b78a572e]
2021-12-09T16:52:22.686741Z	critical	envoy backtrace	#43: std::__1::__function::__value_func<>::operator()() [0x55d7b4666115]
2021-12-09T16:52:22.719265Z	critical	envoy backtrace	#44: std::__1::function<>::operator()() [0x55d7b46660d5]
2021-12-09T16:52:22.749422Z	critical	envoy backtrace	#45: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::operator()() [0x55d7b93bfc82]
2021-12-09T16:52:22.780466Z	critical	envoy backtrace	#46: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::__invoke() [0x55d7b93bfc55]
2021-12-09T16:52:22.780538Z	critical	envoy backtrace	#47: start_thread [0x7f8fcf108609]
```

### PR DESCRIPTION
**Pull request by cpakulski**
Continuation of #19926.

starttls is basically a wrapper around raw and tls sockets. 
Each of those sockets may issue its own events.
For upstream connections, CONNECTED events conflict with  pool manager's state machine. 
This PR fixes the problem using the following logic:
The second CONNECTED event is filtered out and the only action taken is flushing out upstream transport socket.

Commit Message: Issue single CONNECTED event for upstream starttls transport socket.

Additional Description:
Risk Level: Low
Testing: Added unit tests.
Docs Changes: No
Release Notes: No
Platform Specific Features:

Fixes #19232

### CODE REVIEW

File: source/extensions/transport_sockets/starttls/starttls_socket.h [hunk 1]
```diff
@@ -56,6 +57,41 @@ class StartTlsSocket : public Network::TransportSocket, Logger::Loggable<Logger:
...
+  // This is a proxy for wrapping the transport callback object passed from the consumer.
+  // Its primary purpose is to filter Connected events to ensure they only happen once per open.
+  // connection open.
+  class CallbackProxy : public Network::TransportSocketCallbacks {
+  public:
+    CallbackProxy(Network::TransportSocketCallbacks* callbacks) : parent_(callbacks) {}
+
+    Network::IoHandle& ioHandle() override { return parent_->ioHandle(); }
+    const Network::IoHandle& ioHandle() const override {
+      return const_cast<const Network::TransportSocketCallbacks*>(parent_)->ioHandle();
```
Comment (lizan) [inline source/extensions/transport_sockets/starttls/starttls_socket.h:69]: You shouldn't need `const_cast` to add const.

File: test/extensions/transport_sockets/starttls/starttls_socket_test.cc [hunk 2]
```diff
@@ -110,6 +110,66 @@ TEST(StartTlsTest, BasicSwitch) {
...
+
+  // Verify all the passthrough functions work
+
+  Network::MockIoHandle handle;
+  EXPECT_CALL(transport_callbacks, ioHandle()).WillOnce(testing::ReturnRef(handle));
+  proxy->ioHandle();
+
+  // Check const version of ioHandle
+  EXPECT_CALL(testing::Const(transport_callbacks), ioHandle()).WillOnce(testing::ReturnRef(handle));
+  const_cast<const Network::TransportSocketCallbacks*>(proxy)->ioHandle();
```
Comment (lizan) [inline test/extensions/transport_sockets/starttls/starttls_socket_test.cc:157]: ditto

File: source/extensions/transport_sockets/starttls/starttls_socket.h (hunk 1 above)
Comment (cpakulski) [reply source/extensions/transport_sockets/starttls/starttls_socket.h:69]: This is not to return `const` value, but to add `const` to `parent_`, so the compiler will select `const` version of `ioHandle`.
 https://github.com/envoyproxy/envoy/blob/main/envoy/network/transport_socket.h#L51-L56
Without the `const`, the compiler invokes `non-const` version of `ioHandle`.

The other way of doing it would be `static_cast` or `const` local variable.

Comment (lizan) [reply source/extensions/transport_sockets/starttls/starttls_socket.h:69]: I know what you're trying to do, but `const_cast` is to remove but not add. You may want to use `std::as_const`.

Comment (cpakulski) [reply source/extensions/transport_sockets/starttls/starttls_socket.h]: Yes, you are right. Thanks. Changed to `static_cast.`

**Comment by KBaichoo** [comment]
friendly ping @lizan PTAL

**Review by lizan — APPROVED** [review]
