### PR TITLE
websocket: support route timeout for HTTP upgrade

### LINKED ISSUE #41068: Unable to set a request timeout for websocket upgrades
*Title*: Unable to set a request timeout for websocket upgrades

*Description*:

Attempting to set a request timeout for an HTTP upgrade is ignored.

Both `request_timeout` on the HCM and route-level `timeout` variants are not effective. There is some mention that route `timeout` doesn't support streaming use-cases.

I believe this is known issue related to pausing the parser while we wait for the upgrade response, but I'd like to discuss how we can fix it as it represents a pretty significant gap fro proxying websockets via envoy.

*Repro steps*:

 * Add a timeout on either the HCM or route that is used for an HTTP upgrade
 * Ensure that the server processing the upgrade exceeds the timeout duration
 * Observe that the upgrade request will hang until the stream timeout is hit (5m default)

*Config*:

```yaml
static_resources:
  listeners:
    - name: main
      address:
        socket_address: { address: 127.0.0.1, port_value: 8000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                upgrade_configs:
                  - upgrade_type: websocket
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: local_service
                            retry_policy:
                              per_try_timeout: 5s
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

*Logs*:

```
[2025-09-12 15:42:13.376][97547451][trace][http] [source/common/http/http1/codec_impl.cc:545] [Tags: "ConnectionId":"0"] completed header: key=Connection value=Upgrade
[2025-09-12 15:42:13.376][97547451][trace][http] [source/common/http/http1/codec_impl.cc:545] [Tags: "ConnectionId":"0"] completed header: key=Upgrade value=websocket
[2025-09-12 15:42:13.376][97547451][trace][http] [source/common/http/http1/codec_impl.cc:545] [Tags: "ConnectionId":"0"] completed header: key=Sec-WebSocket-Version value=13
[2025-09-12 15:42:13.376][97547451][trace][http] [source/common/http/http1/codec_impl.cc:838] [Tags: "ConnectionId":"0"] onHeadersCompleteImpl
[2025-09-12 15:42:13.376][97547451][trace][http] [source/common/http/http1/codec_impl.cc:545] [Tags: "ConnectionId":"0"] completed header: key=Sec-WebSocket-Key value=4u+HRFaQTWxaIW3kHbPXyQ==
[2025-09-12 15:42:13.376][97547451][trace][http] [source/common/http/http1/codec_impl.cc:876] [Tags: "ConnectionId":"0"] codec entering upgrade mode.
[2025-09-12 15:42:13.376][97547451][trace][http] [source/common/http/http1/codec_impl.cc:1200] [Tags: "ConnectionId":"0"] Server: onHeadersComplete size=5
[2025-09-12 15:42:13.377][97547451][debug][http] [source/common/http/conn_manager_impl.cc:1206] [Tags: "ConnectionId":"0","StreamId":"17915200470360081045"] request headers complete (end_stream=false):
':authority', 'localhost:8000'
':path', '/'
':method', 'GET'
'connection', 'Upgrade'
'upgrade', 'websocket'
'sec-websocket-version', '13'
'sec-websocket-key', '4u+HRFaQTWxaIW3kHbPXyQ=='

[2025-09-12 15:42:13.377][97547451][debug][router] [source/common/router/router.cc:539] [Tags: "ConnectionId":"0","StreamId":"17915200470360081045"] cluster 'local_service' match for URL '/'
[2025-09-12 15:42:13.377][97547451][debug][router] [source/common/router/router.cc:799] [Tags: "ConnectionId":"0","StreamId":"17915200470360081045"] router decoding headers:
':authority', 'localhost:8000'
':path', '/'
':method', 'GET'
':scheme', 'http'
'connection', 'Upgrade'
'upgrade', 'websocket'
'sec-websocket-version', '13'
'x-forwarded-proto', 'http'
'x-request-id', 'ec74a4a2-3ed2-42ac-bea2-cac4715e3b56'
'x-envoy-expected-rq-timeout-ms', '5000'

[2025-09-12 15:42:13.378][97547451][trace][http] [source/common/http/filter_manager.cc:597] [Tags: "ConnectionId":"0","StreamId":"17915200470360081045"] decode headers called: filter=envoy.filters.http.upstream_codec status=4
[2025-09-12 15:42:13.378][97547451][trace][http] [source/common/http/filter_manager.cc:597] [Tags: "ConnectionId":"0","StreamId":"17915200470360081045"] decode headers called: filter=envoy.filters.http.router status=1
[2025-09-12 15:42:13.378][97547451][trace][http] [source/common/http/http1/codec_impl.cc:951] [Tags: "ConnectionId":"0"] message complete
[2025-09-12 15:42:13.378][97547451][trace][http] [source/common/http/http1/codec_impl.cc:959] [Tags: "ConnectionId":"0"] Pausing parser due to upgrade.
[2025-09-12 15:42:13.378][97547451][trace][http] [source/common/http/http1/codec_impl.cc:696] [Tags: "ConnectionId":"0"] parsed 153 bytes
[2025-09-12 15:42:13.378][97547451][trace][http] [source/common/http/http1/codec_impl.cc:623] [Tags: "ConnectionId":"0"] direct-dispatched 0 bytes
[2025-09-12 15:42:13.378][97547451][trace][http] [source/common/http/http1/codec_impl.cc:1288] [Tags: "ConnectionId":"0"] body size=0
[2025-09-12 15:42:13.378][97547451][trace][http] [source/common/http/filter_manager.cc:743] [Tags: "ConnectionId":"0","StreamId":"17915200470360081045"] decode data called: filter=envoy.filters.http.router status=3
[2025-09-12 15:42:13.378][97547451][debug][router] [source/common/router/upstream_request.cc:589] [Tags: "ConnectionId":"0","StreamId":"17915200470360081045"] pool ready
[2025-09-12 15:42:13.378][97547451][trace][router] [source/common/router/upstream_codec_filter.cc:61] [Tags: "ConnectionId":"0","StreamId":"17915200470360081045"] proxying headers
```

*Call Stack*:
N/A

### PR DESCRIPTION
**Pull request by garrettheel**
Commit Message: websocket: support route timeout for HTTP upgrade
Additional Description:

Route timeouts currently do not work for the initial HTTP upgrade request for websockets. This special-cases the upgrade request so that we can correctly apply a timeout to those.

I found #20062 which suggested that this partially worked at some point (though buggy, since not disarmed on the upgrade response), but I was not able to reproduce that behavior on main. The main risk I can think of would be upgrades that take >15 seconds and now see the default route timeout, however I think that would be fairly unusual.

Risk Level: Medium
Testing: added integration tests and tested the config in the linked issue manually
Docs Changes: open to suggestion, but I could update the timeout docs
Release Notes: added entry for minor behavior change
Platform Specific Features: n/a
Fixes #41068

### CODE REVIEW

**Comment by botengyao** [comment]
CI can be addressed through merging the main now.

**Comment by garrettheel** [comment]
@botengyao I rebased on the latest main, though the only failing test was the PR assignment one. I'd appreciate if you could take a look!

File: source/common/router/upstream_request.cc [hunk 1]
```diff
@@ -652,6 +652,17 @@ void UpstreamRequest::onPoolReady(std::unique_ptr<GenericUpstream>&& upstream,
...
+  // even if downstream_end_stream_ is not yet set, because the upstream request
+  // will be paused waiting for the upgrade response.
+  if (paused_for_websocket_) {
+    // Set up per-try timeout if configured
+    if (!per_try_timeout_ && parent_.timeout().per_try_timeout_.count() > 0) {
+      setupPerTryTimeout();
+    }
+    parent_.setupRouteTimeoutForWebsocketUpgrade();
+  }
+
```
Comment (botengyao) [inline source/common/router/upstream_request.cc]: Should we move the start point of the timer to when the upgrade header is [accepted from route](https://github.com/envoyproxy/envoy/blob/317d7fdf8cac9f4e7f677540e68d16c7f9de72c5/source/common/router/upstream_request.cc#L394-L396)r so the time includes the connection pool time? And moving there will be similar to the current timer in `onRequestComplete()` place.

File: source/common/router/upstream_request.cc [hunk 2]
```diff
@@ -652,6 +652,17 @@ void UpstreamRequest::onPoolReady(std::unique_ptr<GenericUpstream>&& upstream,
     create_per_try_timeout_on_request_complete_ = true;
   }
 
+  // For websocket upgrades, we need to set up timeouts immediately
+  // even if downstream_end_stream_ is not yet set, because the upstream request
+  // will be paused waiting for the upgrade response.
+  if (paused_for_websocket_) {
```
Comment (botengyao) [inline source/common/router/upstream_request.cc]: Also would be safer to add a runtime guard for this enhancement.

Comment (garrettheel) [reply source/common/router/upstream_request.cc]: Sounds good - I added this

File: source/common/router/upstream_request.cc (hunk 1 above)
Comment (garrettheel) [reply source/common/router/upstream_request.cc]: Sounds good, I moved to header accept

**Comment by garrettheel** [comment]
@botengyao thanks for reviewing, please take another look
