### PR TITLE
tracing: Fix spankind = CLIENT bug when sharedSpanContext is false

### LINKED ISSUE #13141: All spans get kind = CLIENT when sharedSpanContext = false
Hi,

When sharedSpanContext is set to false, which is the default in istio, all spans sent from sidecars to zipkin is marked as kind = CLIENT, at least in my setup.

I wonder whether this is by design. My understanding is that egress traffic should get kind = CLIENT, whereas ingress traffic should have kind = SERVER, regardless of whether shared spans are used or not.

Setup: k8s, istio (tested both 1.7 and 1.6), zipkin tracing. Tested HTTP traffic with curl, using the BookInfo sample. 

Please advice.

Best regards,
Lars Andreas Ek

### PR DESCRIPTION
**Pull request by objectiser**
Commit Message:
Introducing the `sharedSpanContext` flag, to control whether shared or new span ids were used, inadvertently affected the value used for the span kind annotation. This PR separates out setting the annotation from the logic controlling whether span ids are shared or not.

Risk Level: low
Testing: Enhanced the unit tests.

Docs Changes: n/a
Release Notes:

Fixes #13141

### CODE REVIEW

**Review by dio — APPROVED** [review]
Thanks, @objectiser! Most of my comments will be on how we put comments (as a complete sentence), but I have a plan to drop v1 and model this tracer to support v2 only, probably we can do that when the time comes 🙂.

File: test/extensions/tracers/zipkin/tracer_test.cc [hunk 1]
```diff
@@ -395,15 +395,27 @@ TEST_F(ZipkinTracerTest, SharedSpanContext) {
...
 
   NiceMock<Tracing::MockConfig> config;
-  ON_CALL(config, operationName()).WillByDefault(Return(Tracing::OperationName::Ingress));
+  ON_CALL(config, operationName()).WillByDefault(Return(Tracing::OperationName::Egress));
 
   // Create parent span
   SpanPtr parent_span = tracer.startSpan(config, "parent_span", timestamp);
   SpanContext parent_context(*parent_span);
 
+  // An CS annotation must have been added
```
Comment (dio) [inline test/extensions/tracers/zipkin/tracer_test.cc:404]: nit: s/An/A.
