### PR TITLE
path: Fix merge slash for paths ending with slash and present query args

### LINKED ISSUE #10912: merge_slashes option moves trailing slash from path to end of the the query string
Hi.

Trying to remove duplicated slashes from URL, so enabled _merge_slashes_ option in http_connection_manager config. Duplicated slashes become single now, but now I'm getting trailing slash moved from the end of the URL path to the end of the query string, which is very unexpected.

For example:
http://example.com//test/?somequery_string becomes http://example.com/test?somequery_string/

However these requests are processing as expected:
http://example.com/test/?somequery_string  -> http://example.com/test/?somequery_string
http://example.com//test/foo  -> http://example.com/test/foo

When merge_slashes is disabled, everything is kinda as expected too:
http://example.com//test/?somequery_string -> http://example.com//test?somequery_string

Didn't find any related issue, looks like a bug?

Tried on envoy 1.12.2, 1.13.0, 1.14.1
normalize_path option is off

Envoy config:
```
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          common_http_protocol_options:
            idle_timeout: 300s
          use_remote_address: yes
          xff_num_trusted_hops: 1
          merge_slashes: yes
          access_log:
            - name: envoy.file_access_log
              config:
                path: /dev/stdout
          route_config:
            name: local_route
            virtual_hosts:
            - name: example_vhost
              domains: ["example.com"]
              routes:
              - match: { prefix: "/" }
                direct_response:
                    status: "200"
```

### PR DESCRIPTION
**Pull request by euroelessar**
Commit Message: Order of path suffix and query string was wrong, so the ending slash was moved to a query. Tests did not cover this scenario so add a new one.
Additional Description: n/a
Risk Level: low (bug fix)
Testing: added unit test
Docs Changes: n/a
Release Notes: added
Fixes #10912

### CODE REVIEW

**Comment by euroelessar** [comment]
@jmarantz Can you have a look, please?

File: source/common/http/path_utility.cc [hunk 1]
```diff
@@ -64,10 +64,11 @@ void PathUtil::mergeSlashes(RequestHeaderMap& headers) {
...
   }
-  const absl::string_view prefix = absl::StartsWith(path, "/") ? "/" : absl::string_view();
-  const absl::string_view suffix = absl::EndsWith(path, "/") ? "/" : absl::string_view();
-  headers.setPath(absl::StrCat(
-      prefix, absl::StrJoin(absl::StrSplit(path, '/', absl::SkipEmpty()), "/"), query, suffix));
+  const absl::string_view path_prefix = absl::StartsWith(path, "/") ? "/" : absl::string_view();
+  const absl::string_view path_suffix = absl::EndsWith(path, "/") ? "/" : absl::string_view();
+  headers.setPath(absl::StrCat(path_prefix,
+                               absl::StrJoin(absl::StrSplit(path, '/', absl::SkipEmpty()), "/"),
+                               path_suffix, query));
```
Comment (jmarantz) [inline source/common/http/path_utility.cc:71]: TBH this transform scares me from a security perspective, but I guess it's off by default so someone has to consciously enable it.

@htuch for visibility and @envoyproxy/senior-maintainers pass

At a glance it looks fine.

Comment (htuch) [reply source/common/http/path_utility.cc:71]: Yeah, it seems this could be a source of potential vulnerability if enabled. @euroelessar do you think this is worth a security advisory? This is all tempered by this not being RFC mandated behavior.
