### PR TITLE
fix envoy.filters.http.lua metadata empty

### LINKED ISSUE #17166: filter_metadata is always empty when working with direct_response
*Title*: filter_metadata would be empty when working with direct_response

*Description*:

Using the following config file
```yaml
static_resources:
  clusters:
  - name: nginx
    connect_timeout: "10s"
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: nginx
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  request_handle:logInfo(string.format('foo=%s', request_handle:metadata():get('foo') or nil))
                end

                function envoy_on_response(response_handle)
                end

          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: [ "*" ]
              routes:
              - name: r1
                metadata:
                  filter_metadata:
                    envoy.filters.http.lua:
                      foo: bar
                match:
                  prefix: '/'
#                route:
#                  cluster: "nginx"
                direct_response:
                  status: 200
                  body:
                    inline_string: "hello"

```

It's expected envoy would print log "foo=bar", but got "foo=nil" in fact.
If uncomment the `route` part and comment the `direct_response` part, will get "foo=bar" as expected.

*Repro steps*:
Our OS is MacOS 10.14.6 and envoy  version is 98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/clean-getenvoy-b76c773-envoy/RELEASE/BoringSSL.

see the description for reproduce steps.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

### PR DESCRIPTION
**Pull request by chrisxrepo**
Signed-off-by: Chris Xin xinchuantao@qq.com

```
// in source/common/router/config_impl.cc
const RouteEntry* RouteEntryImplBase::routeEntry() const {
  if (isDirectResponse()) {
    return nullptr;
  } else {
    return this;
  }
}

// in source/extensions/filters/http/lua/lua_filter.cc
const ProtobufWkt::Struct& getMetadata(Http::StreamFilterCallbacks* callbacks) {
  if (callbacks->route() == nullptr || callbacks->route()->routeEntry() == nullptr) {
    return ProtobufWkt::Struct::default_instance();
  }
  const auto& metadata = callbacks->route()->routeEntry()->metadata();
  .....
}
```
if route set direct response, `callbacks->route()->routeEntry()` will return nullptr.  request_handle:metadata() will return empty in filter:`filter.http.lua` inline lua script,

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #17166]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by chrisxrepo** [comment]
i will add unit test later

**Comment by snowp** [comment]
Can you elaborate on the issue a bit more? If the problem is just around the metadata entry not being set can we just gate on what instead of having to rely on dynamic casts?

**Comment by chrisxrepo** [comment]
yeah, i think so, i will add ` metadata()` interface in Router::Route

**Comment by snowp** [comment]
Looks like CI is broken, and this will need a test case as well

/wait

File: envoy/router/router.h [hunk 1]
```diff
@@ -1075,6 +1075,15 @@ class Route {
   template <class Derived> const Derived* perFilterConfigTyped(const std::string& name) const {
     return dynamic_cast<const Derived*>(perFilterConfig(name));
   }
+
+  /**
+   * @return const envoy::config::core::v3::Metadata& return the metadata provided in the config for
+   * this route.
+   */
+  virtual const envoy::config::core::v3::Metadata& metadata() const { return empty_metadata_; }
```
Comment (snowp) [inline envoy/router/router.h:1083]: Do you know why we don't just return a RouteEntry for direct response entries? I'm a bit concerned that exposing metadata on both Route and RouteEntry leaves the API in an odd state where it's not clear why one would use on over the other. Thoughts?

Comment (chrisxrepo) [reply envoy/router/router.h:1083]: yeah， it will be odd state. but how can it get the metadata int http filter for direct response entries?

Comment (snowp) [reply envoy/router/router.h:1083]: I think it probably would be populated on the `RouteEntryImplBase` already, we just somehow refuse to give the caller a RouteEntry when it's a direct response. @mattklein123 @alyssawilk any idea why we special case direct response in this way? 

The current proposed implementation seems incomplete as well, seems like we'd always return empty metadata in this case?

Comment (alyssawilk) [reply envoy/router/router.h:1083]: yeah seems weird to me, I'd rather (runtime guard) expose the route entry on direct response but maybe git blame who special cased it and ask them?

Comment (mattklein123) [reply envoy/router/router.h:1083]: From looking at the code, I suspect the original intention is that a direction response != an upstream route entry, and that is why the interface/code is broken down that way. I have 2 comments:
1) Personally, I would remove metadata() from RouteEntry and add it to Route as this PR does. Then it can be grabbed in all cases.
2) I don't understand how always returning empty metadata here makes sense. Don't you want to return the configured route metadata?

Comment (chrisxrepo) [reply envoy/router/router.h:1083]: yeah, if metadata() interface in RouteEntry, it will make many weird problems for direct response entries. ok, i will remove metadata() from RouteEntry.

Comment (chrisxrepo) [reply envoy/router/router.h:1083]: i try to remove metadata() from Router::RouteEntry, so many files will be change. i think it will take a another problem.

Comment (mattklein123) [reply envoy/router/router.h:1077]: Yes, it will be a larger change, but that is the change we need to do.

Comment (chrisxrepo) [reply envoy/router/router.h:1077]: ok， i will do it

File: source/common/http/async_client_impl.h [hunk 2]
```diff
@@ -299,7 +299,6 @@ class AsyncStreamImpl : public AsyncClient::Stream,
     const Router::VirtualHost& virtualHost() const override { return virtual_host_; }
     bool autoHostRewrite() const override { return false; }
     bool includeVirtualHostRateLimits() const override { return true; }
-    const envoy::config::core::v3::Metadata& metadata() const override { return metadata_; }
     const Config::TypedMetadata& typedMetadata() const override { return typed_metadata_; }
```
Comment (snowp) [inline source/common/http/async_client_impl.h:302]: Do we want to do the same thing with typedMetadata? iiuc it comes from the same proto field

Comment (mattklein123) [reply source/common/http/async_client_impl.h:302]: +1

File: envoy/router/router.h (hunk 1 above)
Comment (mattklein123) [reply envoy/router/router.h:1077]: I'm still not sure why this is returning empty metadata. I would keep this as a PURE virtual function and let the implementation return the right thing.

/wait

File: source/common/http/async_client_impl.h (hunk 2 above)
Comment (chrisxrepo) [reply source/common/http/async_client_impl.h]: ok, i will do it in this PR

File: envoy/stream_info/stream_info.h [hunk 3]
```diff
@@ -491,6 +493,11 @@ class StreamInfo {
    */
   virtual Ssl::ConnectionInfoConstSharedPtr upstreamSslConnection() const PURE;
 
+  /**
+   * @return const Router::RouteConstSharedPtr Get the route selected for this request.
+   */
+  virtual Router::RouteConstSharedPtr route() const PURE;
```
Comment (mattklein123) [inline envoy/stream_info/stream_info.h:499]: Let's remove `routeEntry()` below as it's now redundant.

File: source/common/router/delegating_route_impl.h [hunk 4]
```diff
@@ -25,9 +28,13 @@ class DelegatingRoute : public Router::Route {
   const Router::Decorator* decorator() const override;
   const Router::RouteTracing* tracingConfig() const override;
   const Router::RouteSpecificFilterConfig* perFilterConfig(const std::string&) const override;
+  const envoy::config::core::v3::Metadata& metadata() const override { return metadata_; }
+  const Envoy::Config::TypedMetadata& typedMetadata() const override { return typed_metadata_; }
 
 private:
   const Router::RouteConstSharedPtr base_route_;
+  const envoy::config::core::v3::Metadata metadata_;
+  const Envoy::Config::TypedMetadataImpl<Envoy::Config::TypedMetadataFactory> typed_metadata_;
```
Comment (mattklein123) [inline source/common/router/delegating_route_impl.h:37]: This should be calling the parent methods, not returning empty.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks this looks like great progress.

/wait

File: envoy/stream_info/stream_info.h (hunk 3 above)
Comment (chrisxrepo) [reply envoy/stream_info/stream_info.h:499]: ok, i will remove it, it will be a large change

File: source/common/router/delegating_route_impl.h (hunk 4 above)
Comment (chrisxrepo) [reply source/common/router/delegating_route_impl.h]: I accidentally ignored it.

**Comment by mattklein123** [comment]
@chrisxrepo please do not force push as it makes reviews much more difficult. Just merge main and add commits. Thanks!

File: source/extensions/filters/http/lua/lua_filter.cc [hunk 5]
```diff
@@ -11,6 +11,7 @@
 #include "source/common/config/datasource.h"
 #include "source/common/crypto/utility.h"
 #include "source/common/http/message_impl.h"
+#include "source/common/router/config_impl.h"
```
Comment (mattklein123) [inline source/extensions/filters/http/lua/lua_filter.cc:14]: No need to include the impl here or in the BUILD file above, same elsewhere if I missed it.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks this is a great change. A small comment. Thank you!

/wait

File: source/extensions/filters/http/lua/BUILD [hunk 6]
```diff
@@ -26,6 +26,7 @@ envoy_cc_library(
         "//source/common/config:datasource_lib",
         "//source/common/crypto:utility_lib",
         "//source/common/http:message_lib",
+        "//source/common/router:config_lib",
```
Comment (mattklein123) [inline source/extensions/filters/http/lua/BUILD:29]: revert

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks LGTM with another small change. @snowp any further comments?

/wait

**Review by snowp — APPROVED** [review]
LGTM, just one small comment

**Review by mattklein123 — APPROVED** [review]
Thanks!
