### PR TITLE
tooling: Yapf fix diff

### LINKED ISSUE #20459: Yapf formatter not uploading fix to artefacts
### description

I need to confirm but reviewing a PR with a yapf fail, it seems as tho no fix/diff was uploaded as artefact

Parking this here while i investigate further

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Fix #20459 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: ci/format_pre.sh [hunk 1]
```diff
@@ -63,5 +63,11 @@ if [[ "${#FAILED[@]}" -ne "0" ]]; then
     for failed in "${FAILED[@]}"; do
         echo "${BASH_ERR_PREFIX} $failed" >&2
     done
+    if [[ $(git status --porcelain) ]]; then
+        git diff > "$DIFF_OUTPUT"
+        echo
+        echo "Diff file with (some) fixes will be uploaded. Please check the artefacts for this PR run in the azure pipeline."
```
Comment (daixiang0) [inline ci/format_pre.sh:69]: How about `Please check the logs ...`

Comment (phlax) [reply ci/format_pre.sh:69]: it has nothing to do with logs

Comment (htuch) [inline ci/format_pre.sh:69]: Can you programmatically generate the URL here? As a personal pain point, hunting around AZP results for things like coverage results, docs, is a PITA. It would be nice if we could have some way (ideally a single click away from the PR on GH) to get at these artefacts.

Comment (htuch) [reply ci/format_pre.sh:69]: Sure, let's ship this, but it would be great to have this improvement.

**Review by htuch — APPROVED** [review]
LGTM, thanks!
