### PR TITLE
json transcoder: set decoded percent-encoded message as json response

### LINKED ISSUE #15193: grpc status details are percent-encoded when mapped to json
*Title*: grpc status details are percent-encoded when mapped to json

*Description*:
When using envoy's grpc-json transcoding with `convert_grpc_status: true` and a nodejs upstream, envoy does not decode "percent encoded" responses, eg. we send responses like `{"code":5,"message":"No%20such%20resource","details":[]}` instead of `{"code":5,"message":"No such resource","details":[]}`

This one-liner fixes the issue: https://github.com/kentik/envoy/commit/92b1742e714d0098bd3b21460f8b1afd663d746c

I have more details and a repro here: https://github.com/stfp/envoy-no-status-decode-repro

*Repro steps*:
Complete repro steps and notes here: https://github.com/stfp/envoy-no-status-decode-repro

*Config*:
https://github.com/stfp/envoy-no-status-decode-repro/blob/main/conf/envoy.yaml

*Logs*:
N/A

*Call Stack*:
N/A

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Shikugawa <rei@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: Close #15193. Fix not to set percent-encoded message as transcoded json response.
Additional Description:
Risk Level: Low
Testing: Unit
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Review by qiwzhang — APPROVED** [review]

File: test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc [hunk 1]
```diff
@@ -1224,6 +1224,25 @@ TEST_F(GrpcJsonTranscoderFilterConvertGrpcStatusTest,
...
+  EXPECT_CALL(encoder_callbacks_, addEncodedData(_, false))
+      .WillOnce(Invoke([&expected_response](Buffer::Instance& data, bool) {
+        EXPECT_EQ(expected_response, data.toString());
+      }));
+
+  Http::TestResponseHeaderMapImpl response_headers{{":status", "200"},
+                                                   {"content-type", "application/grpc"},
+                                                   {"grpc-status", "5"},
+                                                   {"grpc-message", "Resource%20not%20found"}};
+  EXPECT_EQ(Http::FilterHeadersStatus::Continue, filter_.encodeHeaders(response_headers, true));
```
Comment (dmitri-d) [inline test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc:1239]: Do you think these checks are necessary here? We are only verifying that percent-encoded grpc status has been decoded; the other checks have been performed elsewhere and imo only muddle this test.

Comment (Shikugawa) [reply test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc:1239]: I think that these redundant tests aren't necessarily bad.

**Review by lizan — APPROVED** [review]

**Review by mattklein123 — APPROVED** [review]
