### PR TITLE
scaled range timer: guard against queue deletion during timer fire

### LINKED ISSUE #14798: scaled range timer manager: potential use-after-free when disabling timer during another timer's callback
*Description*:
During the triggering of a callback for a `ScaledRangeTimerManagerImpl` timer, if another timer in the same queue is disabled such that the queue becomes empty, the queue will be deleted. This will result in a use-after-free error in the loop inside `ScaledRangeTimerManagerImpl::onQueueTimerFired` when checking `!timers.empty()`.

This issue does not seem to be possible in mainline Envoy, since there are very few places that the scaled range timers are currently used; however, our internal modifications of Envoy have hit this issue and it is reproducible in a unit test.

*Repro steps*:
See https://github.com/chradcliffe/envoy/commit/6666db72231985e661aa5061930df43efa4f9bfb for a minimal unit test that reproduces the issue when run under ASAN.

### PR DESCRIPTION
**Pull request by chradcliffe**
Commit Message:
Fix a potential use-after-free error in `ScaledRangeTimerManagerImpl` by adding a `processing_timers_` flag to the timer queues that is set during `onQueueTimerFired` processing. This flag is checked when a timer is removed to ensure that the timer's queue isn't deleted while it is in a callback triggered by `onQueueTimerFired`.

Additional Description: N/A
Risk Level: Low - the issue does not appear possible in current Envoy code
Testing: unit test that reproduces the issue under ASAN
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A

Issue #14798

### CODE REVIEW

**Comment by chradcliffe** [comment]
cc @akonradi

**Comment by akonradi** [comment]
Sweet, thanks for the fix!

**Review by akonradi — APPROVED** [review]

File: test/common/event/scaled_range_timer_manager_impl_test.cc [hunk 1]
```diff
@@ -157,6 +157,33 @@ TEST_F(ScaledRangeTimerManagerTest, DisableWhileScalingMax) {
...
+
+  MockFunction<TimerCb> callback1;
+  auto timer1 =
+      manager.createTimer(AbsoluteMinimum(std::chrono::seconds(5)), callback1.AsStdFunction());
+  MockFunction<TimerCb> callback2;
+  auto timer2 =
+      manager.createTimer(AbsoluteMinimum(std::chrono::seconds(5)), callback2.AsStdFunction());
+
+  timer1->enableTimer(std::chrono::seconds(100));
+  timer2->enableTimer(std::chrono::seconds(100));
```
Comment (akonradi) [inline test/common/event/scaled_range_timer_manager_impl_test.cc:171]: Since these timers are enabled for the same duration, they can fire in either order. Consider making timer1 fire in 95 seconds with an absolute minimum of 0.

Comment (antoniovicente) [reply test/common/event/scaled_range_timer_manager_impl_test.cc]: We need both timers to end up in the same queues so their durations should be the same.

I think the solution is to do an advance of 5 seconds between the first enable and the second enable.

Comment (akonradi) [reply test/common/event/scaled_range_timer_manager_impl_test.cc]: Either of those will work. The duration that matters is (max - min) which is (100 - 5) or (95 - 0) as adjusted.

File: source/common/event/scaled_range_timer_manager_impl.cc [hunk 2]
```diff
@@ -255,12 +259,14 @@ void ScaledRangeTimerManagerImpl::onQueueTimerFired(Queue& queue) {
...
   // Pop and trigger timers until the one at the front isn't supposed to have expired yet (given the
   // current scale factor).
+  queue.processing_timers_ = true;
   while (!timers.empty() &&
          computeTriggerTime(timers.front(), queue.duration_, scale_factor_) <= now) {
     auto item = std::move(queue.range_timers_.front());
     queue.range_timers_.pop_front();
     item.timer_.trigger();
   }
+  queue.processing_timers_ = false;
```
Comment (antoniovicente) [inline source/common/event/scaled_range_timer_manager_impl.cc:269]: So processing_timers_ needs to be per queue since otherwise the queue not empty invariant would not hold if a timer from queue A removes a timer from queue B.  It would be good to also cover that case in tests.

Also, is there code somewhere that verifies the invariant that all active queues are non-empty?

Comment (akonradi) [reply source/common/event/scaled_range_timer_manager_impl.cc:269]: > Also, is there code somewhere that verifies the invariant that all active queues are non-empty?

I don't believe there is currently. The number of queues and sizes is not currently exposed. I'm okay to keep this PR focused on the bugfix and add additional testing in a follow-on.

Comment (chradcliffe) [reply source/common/event/scaled_range_timer_manager_impl.cc:269]: 023d9ec adds a test for cancelling a timer from a different queue in the context of a timer callback.

Comment (antoniovicente) [reply source/common/event/scaled_range_timer_manager_impl.cc:269]: cc: @asraa 

@akonradi Please do followup.  Regarding ASSERTs, I think failing this one will result in a crash in the next line.

https://github.com/envoyproxy/envoy/blob/bf84a7b51bbe8a9496cc5c4bb0df14606f9545f0/source/common/event/scaled_range_timer_manager_impl.cc#L244

**Review by antoniovicente — APPROVED** [review]
Thanks for reporting this bug and providing a fix.

I would like to keep the issue you filed open until we manage to followup on some of the test improvements mentioned in various review comments.

**Comment by chradcliffe** [comment]
Does this make sense as a candidate for a backport to 1.17? That is where I originally discovered this issue.

**Comment by antoniovicente** [comment]
Tagged for backport.

@envoyproxy/senior-maintainers could one of you review the PR?

**Comment by antoniovicente** [comment]
ping @envoyproxy/senior-maintainers  for review since previous mention was over the weekend.

**Review by ggreenway — APPROVED** [review]
