### PR TITLE
request_id_extension: Add noop impl by default

### LINKED ISSUE #10686: core dump in AccessLog::RuntimeFilter when RequestIDExtension not set
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: 
core dump in AccessLog::RuntimeFilter when RequestIDExtension not set

*Call Stack*:
Backtrace:
#0  Envoy::AccessLog::RuntimeFilter::evaluate (this=0x555c0cda5440, stream_info=..., request_headers=...) at external/envoy/source/common/access_log/access_log_impl.cc:131
#0  Envoy::AccessLog::RuntimeFilter::evaluate (this=0x555c0cda5440, stream_info=..., request_headers=...) at external/envoy/source/common/access_log/access_log_impl.cc:131
#1  0x0000555c0ade4190 in Envoy::Extensions::AccessLoggers::Common::ImplBase::log (this=0x555c0c5cc018, request_headers=0x555c0fe0e3f0, response_headers=0x555c1420f4d0, response_trailers=0x555c0f800cb0, stream_info=...) at external/envoy/source/extensions/access_loggers/common/access_log_base.cc:28
#2  0x0000555c0aae8a9c in Envoy::TcpProxy::Filter::~Filter (this=0x555c102084f8) at external/envoy/source/common/tcp_proxy/tcp_proxy.cc:233
#3  0x0000555c0abfc60c in __release_shared (this=0x555c102084e0) at /opt/llvm/bin/../include/c++/v1/memory:3415
#4  __release_shared (this=0x555c102084e0) at /opt/llvm/bin/../include/c++/v1/memory:3457
#5  ~shared_ptr (this=0x555c151649e0) at /opt/llvm/bin/../include/c++/v1/memory:4393
#6  ~ActiveReadFilter (this=0x555c151649c0, vtt=<optimized out>) at bazel-out/k8-opt/bin/external/envoy/source/common/network/_virtual_includes/filter_manager_lib/common/network/filter_manager_impl.h:113
#7  ~ActiveReadFilter (this=0x555c151649c0) at bazel-out/k8-opt/bin/external/envoy/source/common/network/_virtual_includes/filter_manager_lib/common/network/filter_manager_impl.h:113
#8  Envoy::Network::FilterManagerImpl::ActiveReadFilter::~ActiveReadFilter (this=0x555c151649c0) at bazel-out/k8-opt/bin/external/envoy/source/common/network/_virtual_includes/filter_manager_lib/common/network/filter_manager_impl.h:113
#9  0x0000555c0abf500b in operator() (__ptr=0x7f82491ae944, this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/memory:2338
#10 reset (this=0x555c1055eb70, __p=0x0) at /opt/llvm/bin/../include/c++/v1/memory:2593
#11 ~unique_ptr (this=0x555c1055eb70) at /opt/llvm/bin/../include/c++/v1/memory:2547
#12 __destroy<std::__1::unique_ptr<Envoy::Network::FilterManagerImpl::ActiveReadFilter, std::__1::default_delete<Envoy::Network::FilterManagerImpl::ActiveReadFilter> > > (__p=0x555c1055eb70) at /opt/llvm/bin/../include/c++/v1/memory:1747
#13 destroy<std::__1::unique_ptr<Envoy::Network::FilterManagerImpl::ActiveReadFilter, std::__1::default_delete<Envoy::Network::FilterManagerImpl::ActiveReadFilter> > > (__a=..., __p=0x555c1055eb70) at /opt/llvm/bin/../include/c++/v1/memory:1595
#14 clear (this=0x555c0ff40090) at /opt/llvm/bin/../include/c++/v1/list:762
#15 ~__list_imp (this=0x555c0ff40090) at /opt/llvm/bin/../include/c++/v1/list:741
#16 Envoy::Network::FilterManagerImpl::~FilterManagerImpl (this=0x555c0ff40078) at bazel-out/k8-opt/bin/external/envoy/source/common/network/_virtual_includes/filter_manager_lib/common/network/filter_manager_impl.h:101
#17 0x0000555c0abf59ec in Envoy::Network::ConnectionImpl::~ConnectionImpl (this=0x555c0ff40000, vtt=0x555c0b5da2b0 <VTT for Envoy::Network::ConnectionImpl>) at external/envoy/source/common/network/connection_impl.cc:89
#18 0x0000555c0abf5c8f in virtual thunk to Envoy::Network::ConnectionImpl::~ConnectionImpl() () at external/envoy/source/common/network/connection_impl.cc:80
#19 0x0000555c0abeb32c in operator() (__ptr=0x7f82491ae944, this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/memory:2338
#20 reset (this=0x555c153b4990, __p=0x0) at /opt/llvm/bin/../include/c++/v1/memory:2593
#21 ~unique_ptr (this=0x555c153b4990) at /opt/llvm/bin/../include/c++/v1/memory:2547
#22 Envoy::Server::ConnectionHandlerImpl::ActiveTcpConnection::~ActiveTcpConnection (this=0x555c153b4960) at external/envoy/source/server/connection_handler_impl.cc:471
#23 0x0000555c0abeb3ae in Envoy::Server::ConnectionHandlerImpl::ActiveTcpConnection::~ActiveTcpConnection (this=0x555c153b4960) at external/envoy/source/server/connection_handler_impl.cc:458
#24 0x0000555c0abf0823 in operator() (__ptr=0x7f82491ae944, this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/memory:2338
#25 reset (this=<optimized out>, __p=0x0) at /opt/llvm/bin/../include/c++/v1/memory:2593
#26 Envoy::Event::DispatcherImpl::clearDeferredDeleteList (this=0x555c0caacd80) at external/envoy/source/common/event/dispatcher_impl.cc:95
#27 0x0000555c0af58636 in event_process_active_single_queue (base=0x555c0c80c580, activeq=0x555c0c738510, max_to_process=2147483647, endtime=0x0) at /root/.cache/bazel/_bazel_root/e500e327e6981ab742dbacbb6723d21d/sandbox/processwrapper-sandbox/1734/execroot/envoy_lyft/external/com_github_libevent_libevent/event.c:1713
#28 0x0000555c0af571be in event_process_active (base=0x555c0c80c580) at /root/.cache/bazel/_bazel_root/e500e327e6981ab742dbacbb6723d21d/sandbox/processwrapper-sandbox/1734/execroot/envoy_lyft/external/com_github_libevent_libevent/event.c:1808
#29 event_base_loop (base=0x555c0c80c580, flags=<optimized out>) at /root/.cache/bazel/_bazel_root/e500e327e6981ab742dbacbb6723d21d/sandbox/processwrapper-sandbox/1734/execroot/envoy_lyft/external/com_github_libevent_libevent/event.c:2047
#30 0x0000555c0abe6d84 in Envoy::Server::WorkerImpl::threadRoutine (this=0x555c0c90ff20, guard_dog=...) at external/envoy/source/server/worker_impl.cc:110
#31 0x0000555c0b0097b3 in operator() (this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/functional:1860
#32 operator() (this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/functional:2419
#33 operator() (this=<optimized out>, arg=<optimized out>) at external/envoy/source/common/common/posix/thread_impl.cc:33
#34 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) (arg=<optimized out>) at external/envoy/source/common/common/posix/thread_impl.cc:32
#35 0x00007f824b596184 in start_thread (arg=0x7f82491c0700) at pthread_create.c:312
#36 0x00007f824b2c303d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

### PR DESCRIPTION
**Pull request by euroelessar**
Description: By default use noop `RequestIDExtension` implementation in `StreamInfo`. This allows avoiding nullptr checks outside of HTTP context.
Risk Level: low
Testing: added unit test, updated integration test (crashes without `StreamInfoImpl` changes)
Docs Changes: n/a
Release Notes: n/a
Fixes #10686

### CODE REVIEW

File: source/common/http/request_id_extension_impl.cc [hunk 1]
```diff
@@ -7,6 +7,20 @@
 namespace Envoy {
 namespace Http {
 
+namespace {
+
+// NoopRequestIDExtension is the implementation used outside of HTTP context.
+class NoopRequestIDExtension : public RequestIDExtension {
```
Comment (mattklein123) [inline source/common/http/request_id_extension_impl.cc:13]: nit: it would be nice to get coverage of the other methods here in the unit test you added.

File: source/common/stream_info/stream_info_impl.h [hunk 2]
```diff
@@ -20,12 +21,14 @@ struct StreamInfoImpl : public StreamInfo {
   StreamInfoImpl(TimeSource& time_source)
       : time_source_(time_source), start_time_(time_source.systemTime()),
         start_time_monotonic_(time_source.monotonicTime()),
-        filter_state_(std::make_shared<FilterStateImpl>(FilterState::LifeSpan::FilterChain)) {}
+        filter_state_(std::make_shared<FilterStateImpl>(FilterState::LifeSpan::FilterChain)),
+        request_id_extension_(Http::RequestIDExtensionFactory::noopInstance()) {}
```
Comment (mattklein123) [inline source/common/stream_info/stream_info_impl.h:25]: looking at this, I think these constructors can mostly be collapsed with each one invoking the previous with fewer arguments. This would be a nice follow up.

Comment (euroelessar) [reply source/common/stream_info/stream_info_impl.h:25]: Sounds good, will send a follow up pr. Does it need a TODO for the time being?

Comment (euroelessar) [reply source/common/stream_info/stream_info_impl.h:25]: Created #10691, will rebase once this one is merged.
