### PR TITLE
Not to throw exception when internal listener registry not initialized

### LINKED ISSUE #28413: Envoy validate mode not working with internal listener
*Title*: *Envoy validate mode not working with internal listener*

*Description*:
If I define an internal listener in Envoy config and then tries to validate it using --mode validate, it throws an error saying `error initializing configuration 'envoy-test.yaml': error adding listener 'envoy://singleton_internal_encap': internal listener registry is not initialized.`

I tried even with the sample config given on the Envoy wiki:
https://www.envoyproxy.io/docs/envoy/v1.23.9/configuration/other_features/internal_listener#config-internal-listener

I can see the same issue in 1.26.2 version as well where a config is working fine but when I tries to validate it throws the same error.

*Repro steps*:

- Copy and save the envoy sample config from https://www.envoyproxy.io/docs/envoy/v1.23.9/configuration/other_features/internal_listener#config-internal-listener. 
- Run `./envoy_1.23.9 --mode validate -c envoy-test.yaml` to validate the config

*Config*:
Sample config mentioned at https://www.envoyproxy.io/docs/envoy/v1.23.9/configuration/other_features/internal_listener#config-internal-listener wiki or see the following attached file: [envoy-congif.txt](https://github.com/envoyproxy/envoy/files/12053962/envoy-congif.txt)

*Logs*:
`$ ./envoy_1.23.9 --mode validate -c envoy-test.yaml`
`[2023-07-14 12:06:14.066][700145][info][main] [source/server/server.cc:801] runtime: layers:`
`  - name: enable_internal_address`
`    static_layer:`
`      envoy.reloadable_features.internal_address: true`
`[2023-07-14 12:06:14.066][700145][info][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:531] c-ares library initialized.`
`[2023-07-14 12:06:14.067][700145][info][config] [source/server/configuration_impl.cc:131] loading tracing configuration`
`[2023-07-14 12:06:14.067][700145][info][config] [source/server/configuration_impl.cc:91] loading 0 static secret(s)`
`[2023-07-14 12:06:14.067][700145][info][config] [source/server/configuration_impl.cc:97] loading 2 cluster(s)`
`[2023-07-14 12:06:14.068][700145][info][config] [source/server/configuration_impl.cc:101] loading 2 listener(s)`
`[2023-07-14 12:06:14.070][700145][critical][main] [source/server/config_validation/server.cc:64] error initializing configuration 'envoy-test.yaml': error adding listener 'envoy://singleton_internal_encap': internal listener registry is not initialized.`
`[2023-07-14 12:06:14.071][700145][info][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:540] c-ares library cleaned up.`

### PR DESCRIPTION
**Pull request by ningcng**
Fix #28413.

### CODE REVIEW

**Comment by ncihnegn** [comment]
I believe the test failure is irrelevant to the change.

**Review by kyessenov — COMMENTED** [review]
I don't think this is the right approach. The error can happen in non-validate mode as well, e.g. if the bootstrap extension is not added by accident. 

Moreover, the listener config is mandatory and cannot be nullptr because it holds the listener information that can be used by the filter factories. If the other types of listeners populate it, then the internal listener should also populate it.

**Comment by ningcng** [comment]
Add validation to ensure the configuration contains the `internal_listener` bootstrap extension.

**Comment by ningcng** [comment]
@kyessenov Please review the update.

**Comment by adisuissa** [comment]
I agree with @kyessenov, as this fix will not fail prod-configs that are incorrect.
Not an expert in this domain, but I wonder if this can somehow be activated by the creation of the validation listener manager factory, i.e., maybe creating a "fake" api-listener-manger-validator (similar to https://github.com/envoyproxy/envoy/blob/7f3da8ea87ff5a5f57e000ed0ea8a1810d086b03/source/extensions/listener_managers/validation_listener_manager/validation_listener_manager.h#L70) that handles the correctness in validation mode.

**Review by kyessenov — CHANGES_REQUESTED** [review]
I think @adisuissa has a good suggestion to create a validation-specific registry in the validation mode in the singleton. This version is not reliable, since the extension name is free-form.

**Comment by ningcng** [comment]
Don't want to add a fake implementation. I think it should be limited to checking the configuration.

File: source/common/listener_manager/listener_impl.cc [hunk 1]
```diff
@@ -509,12 +509,24 @@ void ListenerImpl::buildInternalListener(const envoy::config::listener::v3::List
...
+      // "internal_listener" is present.
+      if (absl::c_none_of(
+              listener_factory_context_->serverFactoryContext().bootstrap().bootstrap_extensions(),
+              [=](const auto extension) {
+                return extension.typed_config().type_url() ==
+                       "type.googleapis.com/"
+                       "envoy.extensions.bootstrap.internal_listener.v3.InternalListener";
+              })) {
+        throw EnvoyException(
+            fmt::format("error adding listener named '{}': internal_listener is mandatory", name_));
```
Comment (kyessenov) [inline source/common/listener_manager/listener_impl.cc:523]: InternalListener bootstrap extension is mandatory

**Review by kyessenov — COMMENTED** [review]
This is better than before, but we need a test.

File: source/common/listener_manager/listener_impl.cc (hunk 1 above)
Comment (ningcng) [reply source/common/listener_manager/listener_impl.cc]: Done

File: test/common/listener_manager/listener_impl_integration_test.cc [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+#include "test/test_common/file_system_for_test.h"
+#include "test/test_common/thread_factory_for_test.h"
+
+#include "gmock/gmock.h"
+#include "gtest/gtest.h"
+
+namespace Envoy {
+
+// Regression test for https://github.com/envoyproxy/envoy/issues/28413
+TEST(ConfigValidateTest, ValidateGood) {
```
Comment (kyessenov) [inline test/common/listener_manager/listener_impl_integration_test.cc:18]: Can you move this to listener_impl_test.cc, please?

Comment (kyessenov) [reply test/common/listener_manager/listener_impl_integration_test.cc:18]: Alternatively, rename it to `listener_impl_test.cc`, since it's not an integration test.

**Review by kyessenov — APPROVED** [review]
/retest
a flake

**Comment by ningcng** [comment]
How to fix the tsan test?

**Comment by ningcng** [comment]
The `Mobile/Compile time options` check has bee running for two days. How to restart it?

**Comment by phlax** [comment]
@ningcng it was a temporary glitch since fixed - its passing - so either dont worry or merge main to kick

**Comment by ncihnegn** [comment]
@phlax The `Mobile/Compile time options` check still does not finish.

**Comment by phlax** [comment]
yeah - apologies - it wasnt fixed previously - should be fixed now

**Comment by ravenblackx** [comment]
@kyessenov to click squash and merge (I'm only 80% sure that's the right thing to do now, so an abundance of caution suggests you should do it!)
