### PR TITLE
quic: fix ASAN in QuicHttpIntegrationTest.QuicMultipleQuicConnectionsNoBPF

### LINKED ISSUE #34353: undefined behavior in quic integration test
Log https://dev.azure.com/cncf/envoy/_build/results?buildId=171258&view=logs&jobId=1439b9f7-a348-5b50-b5fe-ea612ea91241&j=1439b9f7-a348-5b50-b5fe-ea612ea91241&t=1002ac43-da84-5fae-70b2-98833b702d09&s=4f7d954b-a765-565f-91a2-c04870dab43f
```
[ RUN      ] QuicHttpIntegrationTests/QuicHttpIntegrationTest.MultipleQuicConnectionsNoBPF/IPv4
source/common/http/http1/codec_impl.cc:1067:9: runtime error: member call on address 0x61c00003d080 which does not point to an object of type 'Envoy::Http::Http1::ServerConnectionImpl'
0x61c00003d080: note: object has invalid vptr
 19 01 00 00  73 67 12 00 00 00 00 00  be be be be be be be be  78 25 a4 0f 00 00 00 00  88 5e f7 0f
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0xaa84996 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Http::Http1::ServerConnectionImpl::ServerConnectionImpl(Envoy::Network::Connection&, Envoy::Http::Http1::CodecStats&, Envoy::Http::ServerConnectionCallbacks&, Envoy::Http::Http1Settings const&, unsigned int, unsigned int, envoy::config::core::v3::HttpProtocolOptions_HeadersWithUnderscoresAction, Envoy::Server::OverloadManager&)::$_5&, Envoy::Buffer::OwnedBufferFragmentImpl const*>(Envoy::Http::Http1::ServerConnectionImpl::ServerConnectionImpl(Envoy::Network::Connection&, Envoy::Http::Http1::CodecStats&, Envoy::Http::ServerConnectionCallbacks&, Envoy::Http::Http1Settings const&, unsigned int, unsigned int, envoy::config::core::v3::HttpProtocolOptions_HeadersWithUnderscoresAction, Envoy::Server::OverloadManager&)::$_5&, Envoy::Buffer::OwnedBufferFragmentImpl const*&&) /proc/self/cwd/source/common/http/http1/codec_impl.cc:1067:9
    #1 0xaa8467a in std::__1::__function::__func<Envoy::Http::Http1::ServerConnectionImpl::ServerConnectionImpl(Envoy::Network::Connection&, Envoy::Http::Http1::CodecStats&, Envoy::Http::ServerConnectionCallbacks&, Envoy::Http::Http1Settings const&, unsigned int, unsigned int, envoy::config::core::v3::HttpProtocolOptions_HeadersWithUnderscoresAction, Envoy::Server::OverloadManager&)::$_5, std::__1::allocator<Envoy::Http::Http1::ServerConnectionImpl::ServerConnectionImpl(Envoy::Network::Connection&, Envoy::Http::Http1::CodecStats&, Envoy::Http::ServerConnectionCallbacks&, Envoy::Http::Http1Settings const&, unsigned int, unsigned int, envoy::config::core::v3::HttpProtocolOptions_HeadersWithUnderscoresAction, Envoy::Server::OverloadManager&)::$_5>, void (Envoy::Buffer::OwnedBufferFragmentImpl const*)>::operator()(Envoy::Buffer::OwnedBufferFragmentImpl const*&&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:180:16
    #2 0xaa91e20 in std::__1::__function::__value_func<void (Envoy::Buffer::OwnedBufferFragmentImpl const*)>::operator()(Envoy::Buffer::OwnedBufferFragmentImpl const*&&) const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #3 0xaa919dd in Envoy::Buffer::OwnedBufferFragmentImpl::done() /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #4 0xe6968b8 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Buffer::Slice::Slice(Envoy::Buffer::BufferFragment&)::'lambda'()&>(Envoy::Buffer::Slice::Slice(Envoy::Buffer::BufferFragment&)::'lambda'()&) /proc/self/cwd/./source/common/buffer/buffer_impl.h:95:42


SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior source/common/http/http1/codec_impl.cc:1067:9 in  
```

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: switch to use autonomous upstream in testMultipleQuicConnections(). The ASAN complains about the  multiple resets of fake_upstream_connection_ during the tests which races with the FakeUpstream's network connection's I/O events in the upstream thread. This test helper function doesn't need to use controlled test upstream, so using autonomous upstream should avoid the race.
 
This potentially fix #34353 which I wasn't able to reproduce locally under ASAN. This test has to run with `--jobs=1` if we set `--runs_under_test` to be larger than 1. 1000 runs already took more than 1h to finish. 

Risk Level: low, test onlhy
Testing: existing test passes under ASAN
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
Fixes #34353

### CODE REVIEW

File: test/integration/quic_http_integration_test.cc [hunk 1]
```diff
@@ -431,19 +432,11 @@ class QuicHttpIntegrationTestBase : public HttpIntegrationTest {
...
     for (size_t i = 0; i < concurrency_; ++i) {
-      fake_upstream_connection_ = nullptr;
-      upstream_request_ = nullptr;
       auto encoder_decoder = codec_clients[i]->startRequest(default_request_headers_);
 
       auto& request_encoder = encoder_decoder.first;
       auto response = std::move(encoder_decoder.second);
       codec_clients[i]->sendData(request_encoder, 1000, true);
-      waitForNextUpstreamRequest();
-      upstream_request_->encodeHeaders(Http::TestResponseHeaderMapImpl{{":status", "200"},
```
Comment (alyssawilk) [inline test/integration/quic_http_integration_test.cc:442]: do we want to set the response headers to include cookies or was that just a cut and paste rather than an intentional test?
/wait-any

Comment (danzh2010) [reply test/integration/quic_http_integration_test.cc:442]: We don't need cookies for this test. The test only verifies that we can finish a request/response on each connections connected to different Envoy workers.

**Review by alyssawilk — APPROVED** [review]

**Comment by alyssawilk** [comment]
/retest?
otherwise may need a main merge to kick whatever is stalled

**Comment by alyssawilk** [comment]
yeah I think arm stalled out :-(

**Comment by alyssawilk** [comment]
yeah the amd build is wedged - failed but report bounced so it's stuck running.  I don't know of a way to fix other than pushing a main merge
