### PR TITLE
upstream: fix duplicate clusters

### LINKED ISSUE #3987: Envoy crashes if CDS response has two clusters with the same name
When Envoy has initialized it self with a set of clusters, if a CDS update comes that has two clusters with the same name, it crashes. If the duplicate comes in the as part of the initial CDS response, it works correctly.

It crashes at this [line](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L367) 
``` 
 if (existing_active_cluster != active_clusters_.end() ||
      existing_warming_cluster != warming_clusters_.end()) {
    // The following init manager remove call is a NOP in the case we are already initialized. It's
    // just kept here to avoid additional logic.
    init_helper_.removeCluster(*existing_active_cluster->second->cluster_);
    cm_stats_.cluster_modified_.inc();
  } else {
    cm_stats_.cluster_added_.inc();
```
It passes through if the condition because it has add the cluster with the same name to `warming_clusters` and hence it enters the if loop but since the cluster with name does not existing in the active_clusters, `*existing_active_cluster->second` crashes.

We could guard this `removeCluster` call with` if (existing_active_cluster != active_clusters_.end())` to prevent this crash. This is simpler solution which I tried and it works.
Since cluster name is supposed to be unique, ideally should we validate the resource list at `onConfigUpdate` method of [cdsapi](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cds_api_impl.cc#L48) and check for duplicates? If we introduce the validation what should be the behaviour? should we reject the entire cds response ? or simplify overwrite with the latest cluster?

### PR DESCRIPTION
**Pull request by ramaraochavali**
Signed-off-by: Rama <rama.rao@salesforce.com>
*Description*: Fixes envoy crash with duplicate clusters in cds response.
*Risk Level*: Low
*Testing*: Added Automated tests
*Docs Changes*: N/A
*Release Notes*: N/A

Fixes #3987

### CODE REVIEW

File: source/common/upstream/cds_api_impl.cc [hunk 1]
```diff
@@ -48,6 +48,13 @@ CdsApiImpl::CdsApiImpl(const envoy::api::v2::core::ConfigSource& cds_config,
 void CdsApiImpl::onConfigUpdate(const ResourceVector& resources, const std::string& version_info) {
   cm_.adsMux().pause(Config::TypeUrl::get().ClusterLoadAssignment);
   Cleanup eds_resume([this] { cm_.adsMux().resume(Config::TypeUrl::get().ClusterLoadAssignment); });
+
+  std::unordered_set<std::string> cluster_names;
+  for (const auto& cluster : resources) {
+    if (!cluster_names.insert(cluster.name()).second) {
+      throw EnvoyException("duplicate clusters found");
```
Comment (mattklein123) [inline source/common/upstream/cds_api_impl.cc]: Can you say which cluster is duplicated?

File: test/common/upstream/cds_api_impl_test.cc [hunk 2]
```diff
@@ -124,6 +124,23 @@ TEST_F(CdsApiImplTest, ValidateFail) {
...
+  setup(true);
+
+  Protobuf::RepeatedPtrField<envoy::api::v2::Cluster> clusters;
+  auto* cluster_1 = clusters.Add();
+  cluster_1->set_name("duplicate_cluster");
+
+  auto* cluster_2 = clusters.Add();
+  cluster_2->set_name("duplicate_cluster");
+
+  EXPECT_THROW(dynamic_cast<CdsApiImpl*>(cds_.get())->onConfigUpdate(clusters, ""), EnvoyException);
```
Comment (mattklein123) [inline test/common/upstream/cds_api_impl_test.cc]: EXPECT_THROW_WITH_MESSAGE?

File: source/common/upstream/cds_api_impl.cc (hunk 1 above)
Comment (ramaraochavali) [reply source/common/upstream/cds_api_impl.cc]: I can, if we have multiple need to maintain the list and combine all of them as single string display? -NBD, I can do that.

File: test/common/upstream/cds_api_impl_test.cc (hunk 2 above)
Comment (ramaraochavali) [reply test/common/upstream/cds_api_impl_test.cc]: will change...

File: source/common/upstream/cds_api_impl.cc (hunk 1 above)
Comment (mattklein123) [reply source/common/upstream/cds_api_impl.cc]: I would just keep it simple and fail on the first one you find and print the cluster...

**Comment by ramaraochavali** [comment]
@mattklein123  addressed comments. PTAL.
