### PR TITLE
sendLocalReply:call modify_headers before call encode_headers

### LINKED ISSUE #12690: Envoy does not modify `content-length` header after applying BodyFormat to error responses from External Authorization service
*Title*: *Envoy does not modify `content-length` header after applying BodyFormat to error responses from External Authorization service.*

*Description*:
When using a [localReply](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply) Envoy treats responses from External Authorization Service as 'local' (I might argue that external authorization responses should not be treated as 'local' but that may be 'as designed').  However, when applying a body format the `content-length` header returned for the original body of the external authorization response is not modified after applying the body format. This causes the `content-length` response header and the actual length of the body to be mismatched.

*Repro steps*:
- Configure an external http authorization service
- Configure local reply to apply a new Body Format
For example a JSON format:
```
            "local_reply_config": {
             "body_format": {
              "json_format": {
               "code": "%RESPONSE_CODE%",
               "error": "%LOCAL_REPLY_BODY%",
               "trace": "%REQ(X-REQUEST-ID)%"
              }
             }
            }
```
- Make request that fails authorization

For example, response direct from authorization service:
```
< content-length: 12
< 
Unauthorized
```

Response returned by Envoy

```
< content-length: 12
< x-request-id: b87918f4-5b88-4b85-b150-77e8310a4436
< 
* Excess found in a non pipelined read: excess = 71, size = 12, maxdownload = 12, bytecount = 0
{"trace":"b8
```

*Logs*:
```
{"bytes-sent":83,"response-duration":null,"x-forwarded-for":"172.17.0.1","method":"GET","x-global-transaction-id":"1722909b-70e9-46f9-8ebe-23a19cd3b5a5","response-flags":"UAEX","status-details":"ext_authz_denied","response-tx-duration":null,"upstream-cluster":null,"type":"ACCESS","time_date":"2020-08-17T18:21:36.613Z","upstream-host":null,"status":401,"x-aaa-userinfo":null,"host":"test-service.com:32500","upstream-path":"/xxx/ok","bytes-received":0,"path":"/xxx/ok","request-duration":4,"upstream-tls-fail":null,"duration":192,"x-request-id":"1722909b-70e9-46f9-8ebe-23a19cd3b5a5"}
```

If other information is needed to reproduce/debug I can, but was having issues sanitizing the large amount of data.

### PR DESCRIPTION
**Pull request by qiwzhang**
To fix https://github.com/envoyproxy/envoy/issues/12690

There is a conflict between "modify_headers" in this [API](https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/filter.h#L340) and "local_reply_config" in [HCM](https://github.com/envoyproxy/envoy/blob/e8216a8cf79c54e3e0a77ab729ebf27f4e79eb1b/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L535)

When "local_reply_config" is used, the local reply body and its type is generated by Utility::sendLocalReply(), modify_headers should not override it, otherwise it will be wrong.

The modify_headers function is used by many places: route_direct_response and ext_authz.  
*  ext_authz use it to send ext_authz response headers and body to the client in "denied" case.
* route_direct_response use it to send specified response_headers.  It may want to specify the content-type.

Detail changes:
* pass `modify_headers` funtion into Utilitty::sendLocalReply() so it can be called separately.
* call `modify_headers` first in Utilitty::sendLocalReply()
* if body size is not empty, set content-length
* if body_text is modified by local_reply_config, or content-type is not set by `modify_headers`, set it

Risk Level: Low
Testing:  Added integration test.
Docs Changes: N/A
Release Notes: N/A
Fixes #12690

### CODE REVIEW

File: test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc [hunk 1]
```diff
@@ -581,4 +581,110 @@ TEST_P(ExtAuthzHttpIntegrationTest, DisableCaseSensitiveStringMatcher) {
...
+      {":status", "401"},
+      {"content-type", "fake-type"},
+  };
+  ext_authz_request->encodeHeaders(ext_authz_response_headers, true);
+
+  response->waitForEndStream();
+  EXPECT_TRUE(response->complete());
+
+  EXPECT_EQ("401", response->headers().Status()->value().getStringView());
+  // Without the fix, "content-type" and "content-length" are overrided by ext_authz.
```
Comment (dio) [inline test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc:677]: Could you expand "the fix" here? It will be confusing when looking at this line without context.

nit. s/overrided/overriden

Comment (qiwzhang) [reply test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc]: Done

File: source/common/http/utility.h [hunk 2]
```diff
@@ -270,6 +270,7 @@ bool isWebSocketUpgradeRequest(const RequestHeaderMap& headers);
 Http1Settings parseHttp1Settings(const envoy::config::core::v3::Http1ProtocolOptions& config);
 
 struct EncodeFunctions {
+  std::function<void(ResponseHeaderMap& headers)> modify_headers_;
```
Comment (dio) [inline source/common/http/utility.h:273]: Oops. Sorry, missed this. I think you need to add comments as well just like the other entries in this struct.

**Review by dio — COMMENTED** [review]
Looks good. A request to add comments. Sorry missed at my first pass.

File: source/common/http/utility.h (hunk 2 above)
Comment (qiwzhang) [reply source/common/http/utility.h:274]: Done

**Review by dio — APPROVED** [review]
Thanks!

**Comment by dio** [comment]
Oops, seems like you need to merge main?

**Comment by mattklein123** [comment]
Assigning to @alyssawilk to take a quick look.

File: source/common/http/conn_manager_impl.cc [hunk 3]
```diff
@@ -1621,15 +1621,13 @@ void ConnectionManagerImpl::FilterManager::sendLocalReplyViaFilterChain(
...
       state_.destroyed_,
       Utility::EncodeFunctions{
+          modify_headers,
           [this](ResponseHeaderMap& response_headers, Code& code, std::string& body,
                  absl::string_view& content_type) -> void {
             active_stream_.connection_manager_.config_.localReply().rewrite(
                 request_headers_.get(), response_headers, stream_info_, code, body, content_type);
           },
           [this, modify_headers](ResponseHeaderMapPtr&& headers, bool end_stream) -> void {
-            if (modify_headers != nullptr) {
```
Comment (alyssawilk) [inline source/common/http/conn_manager_impl.cc:1630]: hmmm, this is clearly an improvement but also clearly causes L7 changes (one fix that we know of, but maybe someone depends on the order?)  I'd lean towards runtime guarding.

Either way we definitely want a release note about the bugfix.

File: source/common/http/utility.cc [hunk 4]
```diff
@@ -441,6 +441,9 @@ void Utility::sendLocalReply(const bool& is_reset, const EncodeFunctions& encode
   ResponseHeaderMapPtr response_headers{createHeaderMap<ResponseHeaderMapImpl>(
       {{Headers::get().Status, std::to_string(enumToInt(response_code))}})};
 
+  if (encode_functions.modify_headers_) {
+    encode_functions.modify_headers_(*response_headers);
+  }
```
Comment (alyssawilk) [inline source/common/http/utility.cc:446]: So the problem as I understand it, was that modify_headers_ is setting an incorrect content length, and then we need to run the

 if (!body_text.empty()) {
    response_headers->setContentLength(body_text.size());
    response_headers->setReferenceContentType(content_type);	
}
just before encoding to ensure that both values are set correctly.
Aren't we still not necessarily doing that correctly for gRPC trailer-only responses?  if the modify headers function or encode functions set content length based on the body, and then we hit the "Respond with a gRPC trailers-only response if the request is gRPC"  block below, I think we'd update the content type but not the content length.
If I'm reading it right, mind fixing that in this PR as well?

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (qiwzhang) [reply source/common/http/conn_manager_impl.cc:1630]: I think the change is isolated within this function: ConnectionManagerImpl::ActiveStream::sendLocalReply

Here are the steps in the Utility::sendLocalReply()
1) new response_headers
2) local_reply.write(response_headers)
3) response_headers.set_content_type() + content_length() for the local reply_body
4) modify_headers(response_headers) // which may override content_type and content_length.

This change just moved 4) to be before 2).   I think this change should be local and safe.   Could you elaborate the L7 changes you are worrying?

File: source/common/http/utility.cc (hunk 4 above)
Comment (qiwzhang) [reply source/common/http/utility.cc:446]: We are doing that in the old code.  But encode_functions.encode_headers_  is calling `modify_headers` function that may override them.   That is why this change move `modify_headers` out of encode_functions.encode_headers_ and pass it to this function directly.

Comment (qiwzhang) [reply source/common/http/utility.cc:446]: For grpc trailer-only response, it should have the same issue if `modify_headers` is called in side encode_headers_ function.  By moving it out, it should solve the problem.

Comment (qiwzhang) [reply source/common/http/utility.cc:446]: Your third issue of if `modify_headers` is supposed to set content-type and content-length for the response body. My take is: for the requests using Utility::sendLocalReply, the response body is generated by this function, so content-type and length should be set by this function, it should not be set by `modify_headers`.  This change is correct to call `modify_headers` first, and override its content-type and length headers

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (qiwzhang) [reply source/common/http/conn_manager_impl.cc:1630]: I saw the problem from an integration test failure. 

IpVersions/IntegrationTest.RouterDirectResponse/IPv4
test/integration/integration_test.cc:180: Failure
Expected equality of these values:
  "text/html"
    Which is: 0x3af299
  response->headers().getContentTypeValue()
    Which is: "text/plain"

RouterDirectResponse is also calling sendLocalReply.   It may have response_headers to add.  
With this change,  If Direct_Response.respone_headers has "content-length" and "type", they are overridden by Utility::sendLocalReply()

Comment (qiwzhang) [reply source/common/http/conn_manager_impl.cc:1630]: There is a conflict between "modify_headers" in this [API](https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/filter.h#L340) and "local_reply_config" in [HCM](https://github.com/envoyproxy/envoy/blob/e8216a8cf79c54e3e0a77ab729ebf27f4e79eb1b/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L535)

When  "local_reply_config" is used,  the reply body and its type is generated by Utility::sendLocalReply(), modify_headers should not override it, otherwise it will be wrong.   

But I also see the usage from Route_Direct_Response where it wants to set content-type for its response body.

Comment (qiwzhang) [reply source/common/http/conn_manager_impl.cc:1630]: I think this policy should work:

1) content-length should always be set by Utility::sendLocalReply() since it generates reply body,  it should override one set by `modify_headers`  function.

2) if reply body is modified by `local_reply_config` or `modify_headers` did not set content-type, set its content-type in Utility::sendLocalReply()

2) is to fix IpVersions/IntegrationTest.RouterDirectResponse/IPv4 test failure where redirect_response wants to set content-type as "text/html", but Utility::sendLocalReply() set it as "plain/text"

File: source/common/http/utility.cc (hunk 4 above)
Comment (qiwzhang) [reply source/common/http/utility.cc:446]: I fixed gRPC trailer-only issue:  remove content-length if modify_headers set it.

**Comment by qiwzhang** [comment]
@alyssawilk PTAL

File: source/common/http/utility.cc [hunk 5]
```diff
@@ -463,13 +466,22 @@ void Utility::sendLocalReply(const bool& is_reset, const EncodeFunctions& encode
...
   if (!body_text.empty()) {
     response_headers->setContentLength(body_text.size());
-    response_headers->setReferenceContentType(content_type);
+    // If the `rewrite` function has changed body_text or content-type is not set, set it.
+    if (body_text != local_reply_data.body_text_ || response_headers->ContentType() == nullptr) {
+      response_headers->setReferenceContentType(content_type);
+    }
+  } else {
+    // The `modify_headers` function may have added content-length and content-type, remove them.
+    response_headers->removeContentLength();
```
Comment (alyssawilk) [inline source/common/http/utility.cc:483]: Good catch on remocal, but in the case of HTTP/1.1 having an explicit content length of 0 is useful, so maybe just force update the content length to the length of body_text if it's empty or not?

File: source/common/http/utility.cc [hunk 6]
```diff
@@ -463,13 +466,22 @@ void Utility::sendLocalReply(const bool& is_reset, const EncodeFunctions& encode
...
   }
 
   if (!body_text.empty()) {
     response_headers->setContentLength(body_text.size());
-    response_headers->setReferenceContentType(content_type);
+    // If the `rewrite` function has changed body_text or content-type is not set, set it.
+    if (body_text != local_reply_data.body_text_ || response_headers->ContentType() == nullptr) {
+      response_headers->setReferenceContentType(content_type);
+    }
+  } else {
```
Comment (alyssawilk) [inline source/common/http/utility.cc:481]: Let's make sure all of this new logic is unit tested.

File: source/common/http/utility.cc (hunk 5 above)
Comment (qiwzhang) [reply source/common/http/utility.cc]: Set Content-Length to 0 for empty body break some tests.  Decided not to add or remove any headers for empty body. Try to minimize the changes as much as possible.

File: source/common/http/utility.cc (hunk 6 above)
Comment (qiwzhang) [reply source/common/http/utility.cc]: Updated code is not adding too much new logic.  The logic is covered by router.direct_response and ext_authz integration tests.

**Comment by qiwzhang** [comment]
@alyssawilk PTAL

File: source/common/http/utility.cc (hunk 5 above)
Comment (alyssawilk) [reply source/common/http/utility.cc]: I think without those changes the code paths might still be buggy if the body is removed. cc @mattklein123 in case he has thought on this.

Comment (alyssawilk) [reply source/common/http/utility.cc]: fwiw I'm fine with skipping content-length:0 - my main goal was to avoid frame by connection close and as long as we encode headers with end_stream=true the HTTP/1 codec takes care of that.  I think removing invalid content lengths is still worth doing though.

Comment (mattklein123) [reply source/common/http/utility.cc]: Sorry not fully tracking the convo here. I agree that we should be able to set content-length in all cases, but I would be OK with minimizing changes for now.

Comment (qiwzhang) [reply source/common/http/utility.cc:485]: OK, I restored the code back to the previous version.  
When body is empty, remove ContentType and ContentLength headers.

Also add an new DirectResonse Integration test to test the new logic.

**Comment by alyssawilk** [comment]
@dio any final thoughts and @mattklein123 want to take a look or you good with my LGTM?
