### PR TITLE
config: regression test for wrong xDS gRPC method descriptor

### LINKED ISSUE #8927: DELTA_GRPC used for GRPC api type
I'm seeing delta xDS requests sent for CDS set to use regular GRPC api_type:
```
[2019-11-06 19:17:34.029][19268][info][upstream] [source/common/upstream/cluster_manager_impl.cc:156] cm init: initializing cds
[2019-11-06 19:17:34.030][19268][debug][config] [bazel-out/k8-fastbuild/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:47] Establishing new gRPC bidi stream for rpc DeltaClusters(stream .envoy.api.v2.DeltaDiscoveryRequest) returns (stream .envoy.api.v2.DeltaDiscoveryResponse);
```

This is for the bootstrap https://github.com/envoyproxy/go-control-plane/blob/master/sample/bootstrap-xds.yaml

### PR DESCRIPTION
**Pull request by fredlas**
The restMethod, sotwGrpcMethod, deltaGrpcMethod family turned out to be a bit error-prone. If you accidentally use e.g. deltaGrpcMethod rather than sotw, and pass the result into a newly constructed GrpcMux, nothing will immediately break: the GrpcMux will still be using the sotw request+response protos you intended. However, the gRPC client will identify itself to the server with the wrong method string, causing the server to reject the client.

Added a check to the CDS integration tests that would catch this mistake.

Risk Level: none, just added a test
Testing: added to cds_integration_test

Fixes #8927

### CODE REVIEW

**Comment by mattklein123** [comment]
Awesome thanks for adding this test. So this can go in before redoing the other PR I guess? @wgallagher PTAL

**Comment by fredlas** [comment]
No probs. Correct, this is a cleanup/sort-of-safety-measure added to the pre-existing swath of code where the bug was introduced, together with a test that would have caught the error even without this PR's code change. It fits well both before and after the big change.

File: source/common/config/type_to_endpoint.cc [hunk 1]
```diff
@@ -84,6 +84,23 @@ const Protobuf::MethodDescriptor& restMethod(absl::string_view type_url) {
...
+                 envoy::api::v2::core::ApiConfigSource::ApiType api_type) {
+  switch (api_type) {
+  case envoy::api::v2::core::ApiConfigSource::REST:
+    return restMethod(type_url);
+  case envoy::api::v2::core::ApiConfigSource::GRPC:
+    return sotwGrpcMethod(type_url);
+  case envoy::api::v2::core::ApiConfigSource::DELTA_GRPC:
+    return deltaGrpcMethod(type_url);
+  default:
+    return *Protobuf::DescriptorPool::generated_pool()->FindMethodByName(
```
Comment (wgallagher) [inline source/common/config/type_to_endpoint.cc]: you should probably assert here instead

File: source/common/config/type_to_endpoint.cc [hunk 2]
```diff
@@ -12,8 +12,8 @@
 namespace Envoy {
 namespace Config {
 
+namespace {
```
Comment (wgallagher) [inline source/common/config/type_to_endpoint.cc]: why is this necessary?

File: source/common/config/type_to_endpoint.cc (hunk 1 above)
Comment (mattklein123) [reply source/common/config/type_to_endpoint.cc]: +1 this should be NOT_REACHED due to schema checking.

File: source/common/config/type_to_endpoint.cc (hunk 2 above)
Comment (wgallagher) [reply source/common/config/type_to_endpoint.cc]: nvm, I see, no longer accessed outside of this file

**Comment by wgallagher** [comment]
one comment otherwise +1

File: source/common/config/type_to_endpoint.cc (hunk 1 above)
Comment (fredlas) [reply source/common/config/type_to_endpoint.cc]: Before sending out the PR I had tried the GCOVR NOT_REACHED thing, and found that there is at least one test (for UNSUPPORTED_REST_LEGACY) that does reach here. Until UNSUPPORTED_REST_LEGACY is more definitively removed, with its throw replaced by a NOT_REACHED, I think the cleanest way possible is to just let FindMethodByName return whatever "not found" descriptor.

Comment (fredlas) [reply source/common/config/type_to_endpoint.cc]: ...ah, but, there's apparently a potentially uninitialized value that msan/asan are complaining about. I slightly suspect it's what we're talking about here. Not really sure what else it could be.

Comment (mattklein123) [reply source/common/config/type_to_endpoint.cc]: Then shouldn't we test for UNSUPPORTED_REST_LEGACY and throw on that directly?

Comment (fredlas) [reply source/common/config/type_to_endpoint.cc]: There is a test for that. I meant that where the method_descriptor is currently gotten, it will be gotten for UNSUPPORTED_REST_LEGACY as well. That's unavoidable, other than repeating the function call for each switch case. Maybe that would be best, despite being ugly?

However, I just tried reverting all of the changes and running my local clang-msan again, and I still got the same crash. clang-asan doesn't work for me and my machine apparently doesn't have enough disk space to run the bazel.asan CI script. So... I don't have a way to actually engage with this problem. Since (presumably) just dropping all of the changes other than the integration test should avoid the problem, I'm thinking maybe it's best to drop these changes. They're kind of just a nice-to-have cleanup anyways; the integration test is the real safety measure.

Comment (mattklein123) [reply source/common/config/type_to_endpoint.cc]: OK I don't really have enough context. As long as the integration test catches the original bug it's fine.

Comment (fredlas) [reply source/common/config/type_to_endpoint.cc]: Done.

**Comment by fredlas** [comment]
@mattklein123 ready to go; please merge!
