### PR TITLE
dfp: request failed when cached in dns cache

### LINKED ISSUE #27331: upstream: switching from http to https causes upstream handshake failure
*Description*:
Today DNS cache retains IP:port pair for hosts. If 2 requests are made to the same upstream, one uses http, the 2nd one uses https, the 2nd connection to upstream which uses TLS will be connected to port 80 which causes handshake failure.

*Repro steps*:

This was originally observed by E-M hello app. An easier way to reproduce it is to run mobile/test/kotlin/integration/ReceiveDataTest.kt with below modification:
```
diff --git a/mobile/test/kotlin/integration/ReceiveDataTest.kt b/mobile/test/kotlin/integration/ReceiveDataTest.kt
index ba326eb9a8..e9c64ec6a1 100644
--- a/mobile/test/kotlin/integration/ReceiveDataTest.kt
+++ b/mobile/test/kotlin/integration/ReceiveDataTest.kt
@@ -5,6 +5,7 @@ import io.envoyproxy.envoymobile.EngineBuilder
 import io.envoyproxy.envoymobile.RequestHeadersBuilder
 import io.envoyproxy.envoymobile.RequestMethod
 import io.envoyproxy.envoymobile.engine.JniLibrary
+import io.envoyproxy.envoymobile.LogLevel
 import java.nio.ByteBuffer
 import java.util.concurrent.CountDownLatch
 import java.util.concurrent.TimeUnit
@@ -24,15 +25,53 @@ class ReceiveDataTest {
   fun `response headers and response data call onResponseHeaders and onResponseData`() {
 
     val engine = EngineBuilder(Standard())
-      .addNativeFilter("test_remote_response", "{'@type': $testResponseFilterType}")
+    //  .addNativeFilter("test_remote_response", "{'@type': $testResponseFilterType}")
+      .addLogLevel(LogLevel.TRACE)
       .build()
     val client = engine.streamClient()
 
+    // http
+    val headersExpectation2 = CountDownLatch(1)
+    val dataExpectation2 = CountDownLatch(1)
+
+    var status2: Int? = null
+    var body2: ByteBuffer? = null
+
+    val requestHeaders2 = RequestHeadersBuilder(
+      method = RequestMethod.GET,
+      scheme = "http",
+      authority = "example.com",
+      path = "/"
+    )
+    .build()
+
+    client.newStreamPrototype()
+      .setOnResponseHeaders { responseHeaders, _, _ ->
+        status2 = responseHeaders.httpStatus
+        headersExpectation2.countDown()
+      }
+      .setOnResponseData { data, _, _ ->
+        body2 = data
+        dataExpectation2.countDown()
+      }
+      .setOnError { _, _ ->
+        fail("Unexpected error")
+      }
+      .start()
+      .sendHeaders(requestHeaders2, true)
+
+    headersExpectation2.await(10, TimeUnit.SECONDS)
+    dataExpectation2.await(10, TimeUnit.SECONDS)
+
+    assertThat(headersExpectation2.count).isEqualTo(0)
+    assertThat(dataExpectation2.count).isEqualTo(0)
+
+    // https
     val requestHeaders = RequestHeadersBuilder(
       method = RequestMethod.GET,
       scheme = "https",
       authority = "example.com",
-      path = "/test"
+      path = "/"
     )
       .build()
 
@@ -56,12 +95,15 @@ class ReceiveDataTest {
 
     headersExpectation.await(10, TimeUnit.SECONDS)
     dataExpectation.await(10, TimeUnit.SECONDS)
+
     engine.terminate()
 
     assertThat(headersExpectation.count).isEqualTo(0)
     assertThat(dataExpectation.count).isEqualTo(0)
 
     assertThat(status).isEqualTo(200)
-    assertThat(body!!.array().toString(Charsets.UTF_8)).isEqualTo("data")
+    // assertThat(body!!.array().toString(Charsets.UTF_8)).isEqualTo("data")
+    assertThat(status2).isEqualTo(200)
+    // assertThat(body2!!.array().toString(Charsets.UTF_8)).isEqualTo("data")
   }
 }
```

To run the test:
```
$ cd mobile/
$ bazel test test/kotlin/integration:receive_data_test --define=signal_trace=disabled --config=test-android
```

*Logs*:
```
[2023-05-10 19:14:02.321][255][debug][router] [external/envoy/source/common/router/router.cc:686] [C12345][S14343024669129136904] router decoding headers:
':authority', 'example.com'
':method', 'GET'
':path', '/'
':scheme', 'https'
'accept-encoding', 'gzip'

[2023-05-10 19:14:02.321][255][trace][pool] [external/envoy/source/common/http/conn_pool_grid.cc:420] No alternate protocols available for host 'example.com', skipping HTTP/3.
[2023-05-10 19:14:02.321][255][trace][pool] [external/envoy/source/common/http/conn_pool_grid.cc:116] HTTP/1 HTTP/2 ALPN pool attempting to create a new stream to host 'example.com'.
[2023-05-10 19:14:02.321][255][debug][pool] [external/envoy/source/common/http/conn_pool_base.cc:78] queueing stream due to no available connections (ready=0 busy=0 connecting=0)
[2023-05-10 19:14:02.321][255][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:291] trying to create new connection
[2023-05-10 19:14:02.321][255][trace][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:292] ConnPoolImplBase 0x7fae4456df10, ready_clients_.size(): 0, busy_clients_.size(): 0, connecting_clients_.size(): 0, connecting_stream_capacity_: 0, num_active_streams_: 0, pending_streams_.size(): 1 per upstream preconnect ratio: 1
[2023-05-10 19:14:02.321][255][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:145] creating a new connection (connecting=0)
[2023-05-10 19:14:02.321][255][error][upstream] [external/envoy/source/common/upstream/upstream_impl.cc:535] =============== HappyEyeballsConnectionImpl with addresses [2606:2800:220:1:248:1893:25c8:1946]:80
[2023-05-10 19:14:02.321][255][debug][multi_connection] [external/envoy/source/common/network/multi_connection_base_impl.cc:14] [C3] connections=2
[2023-05-10 19:14:02.321][255][debug][happy_eyeballs] [external/envoy/source/common/network/happy_eyeballs_connection_impl.cc:33] C[3] address=[2606:2800:220:1:248:1893:25c8:1946]:80
[2023-05-10 19:14:02.321][255][debug][connection] [external/envoy/source/common/network/connection_impl.cc:941] [C4] connecting to [2606:2800:220:1:248:1893:25c8:1946]:80
[2023-05-10 19:14:02.321][255][debug][connection] [external/envoy/source/common/network/connection_impl.cc:965] [C4] immediate connect error: Network is unreachable
[2023-05-10 19:14:02.321][255][trace][multi_connection] [external/envoy/source/common/network/multi_connection_base_impl.cc:436] Scheduling next attempt.
[2023-05-10 19:14:02.321][255][trace][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:131] not creating a new connection, shouldCreateNewConnection returned false.
[2023-05-10 19:14:02.321][255][trace][http] [external/envoy/source/common/http/filter_manager.cc:539] [C12345][S14343024669129136904] decode headers called: filter=envoy.filters.http.upstream_codec status=4
[2023-05-10 19:14:02.321][255][trace][http] [external/envoy/source/common/http/filter_manager.cc:539] [C12345][S14343024669129136904] decode headers called: filter=envoy.router status=1
[2023-05-10 19:14:02.321][255][trace][misc] [external/envoy/source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x7fae4462f240 for 15000ms, min is 15000ms
[2023-05-10 19:14:02.321][255][trace][connection] [external/envoy/source/common/network/connection_impl.cc:568] [C4] socket event: 3
[2023-05-10 19:14:02.321][255][debug][connection] [external/envoy/source/common/network/connection_impl.cc:580] [C4] raising immediate error
[2023-05-10 19:14:02.321][255][debug][connection] [external/envoy/source/common/network/connection_impl.cc:250] [C4] closing socket: 0
[2023-05-10 19:14:02.321][255][trace][connection] [external/envoy/source/common/network/connection_impl.cc:423] [C4] raising connection event 0
[2023-05-10 19:14:02.321][255][debug][multi_connection] [external/envoy/source/common/network/multi_connection_base_impl.cc:450] [C3] connection=1
[2023-05-10 19:14:02.321][255][trace][multi_connection] [external/envoy/source/common/network/multi_connection_base_impl.cc:454] Disabling next attempt timer.
[2023-05-10 19:14:02.321][255][trace][multi_connection] [external/envoy/source/common/network/multi_connection_base_impl.cc:426] Trying another connection.
[2023-05-10 19:14:02.321][255][debug][happy_eyeballs] [external/envoy/source/common/network/happy_eyeballs_connection_impl.cc:33] C[3] address=93.184.216.34:80
[2023-05-10 19:14:02.322][255][debug][connection] [external/envoy/source/common/network/connection_impl.cc:941] [C5] connecting to 93.184.216.34:80
[2023-05-10 19:14:02.322][255][debug][connection] [external/envoy/source/common/network/connection_impl.cc:960] [C5] connection in progress
[2023-05-10 19:14:02.322][255][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=1)
[2023-05-10 19:14:02.322][255][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:125] clearing deferred deletion list (size=1)
[2023-05-10 19:14:02.323][255][trace][connection] [external/envoy/source/common/network/connection_impl.cc:568] [C5] socket event: 2
[2023-05-10 19:14:02.324][255][trace][connection] [external/envoy/source/common/network/connection_impl.cc:679] [C5] write ready
[2023-05-10 19:14:02.324][255][debug][connection] [external/envoy/source/common/network/connection_impl.cc:688] [C5] connected
[2023-05-10 19:14:02.324][255][trace][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_handshaker.cc:93] [C5] ssl error occurred while read: WANT_READ
[2023-05-10 19:14:02.326][255][trace][connection] [external/envoy/source/common/network/connection_impl.cc:568] [C5] socket event: 3
[2023-05-10 19:14:02.326][255][trace][connection] [external/envoy/source/common/network/connection_impl.cc:679] [C5] write ready
[2023-05-10 19:14:02.326][255][trace][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_handshaker.cc:93] [C5] ssl error occurred while read: SSL
[2023-05-10 19:14:02.326][255][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:234] [C5] remote address:93.184.216.34:80,TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2023-05-10 19:14:02.326][255][debug][connection] [external/envoy/source/common/network/connection_impl.cc:250] [C5] closing socket: 0
[2023-05-10 19:14:02.326][255][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:234] [C5] remote address:93.184.216.34:80,TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2023-05-10 19:14:02.326][255][trace][connection] [external/envoy/source/common/network/connection_impl.cc:423] [C5] raising connection event 0
```

The upstream connection gets destination address from a `LogicalHost` which is created during DNS cache update. The DNS cache entry has port 80, so all the clusters are updated with a host info with port 80. 

To fix this issue, there are several places we can change the host address port, 1) DNS cache population; 2) LogicalHost creation during DNS cache update callback and setAddress()/setAddressList(); 3) connection creation by the Host. I'm not sure where is the most ideal place to make the port change, and would like to get input from the community.

### PR DESCRIPTION
**Pull request by danzh2010**
In light of https://github.com/envoyproxy/envoy/pull/27407, the DNS matched matches against host:port. But an entry is found in DNS cache, DFP filter call getHost() again on the cache with raw host. That call failed the lookup and causes `dns_resolution_failure`.

Additional Description: remove mobile/test/kotlin/integration/MixedSchemeTest.kt which doesn't work under CI; And make Hello Envoy app on android runs with Android certification validation APIs.

Risk Level: low
Testing: add new test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A 
Further Fixes #27331

### CODE REVIEW

**Comment by moderation** [comment]
Interesting. I _think_ this is why my requests for `http` `apt` updates for Ubuntu packages through a DFP proxy are failing with 503s

File: source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc [hunk 1]
```diff
@@ -263,7 +263,7 @@ Http::FilterHeadersStatus ProxyFilter::decodeHeaders(Http::RequestHeaderMap& hea
     ASSERT(cache_load_handle_ == nullptr);
     ENVOY_STREAM_LOG(debug, "DNS cache entry already loaded, continuing", *decoder_callbacks_);
 
-    auto const& host = config_->cache().getHost(headers.Host()->value().getStringView());
+    auto const& host = result.host_info_;
```
Comment (RyanTheOptimist) [inline source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc:266]: Just to confirm, this is the bug fix, right?

File: mobile/examples/java/hello_world/MainActivity.java [hunk 2]
```diff
@@ -61,6 +63,7 @@ protected void onCreate(Bundle savedInstanceState) {
                    Log.d("MainActivity", "Envoy async internal setup completed");
                    return null;
                  })
+                 // .enablePlatformCertificatesValidation(true)
```
Comment (RyanTheOptimist) [inline mobile/examples/java/hello_world/MainActivity.java:66]: Should we remove this since it's commented out?

File: mobile/examples/java/hello_world/MainActivity.java [hunk 3]
```diff
@@ -115,7 +119,8 @@ private void makeRequest() {
           String headerText = sb.toString();
 
           Log.d("MainActivity", message);
-          if (status == 301) {
+          if ((scheme == REQUEST_SCHEME_HTTP && status == 301) ||
+              (scheme == REQUEST_SCHEME_HTTPS && status == 200)) {
```
Comment (RyanTheOptimist) [inline mobile/examples/java/hello_world/MainActivity.java:123]: What's the story with the different status codes per scheme here? Is this just how the server behaves? In any case, maybe we should add some comments? Or maybe just consider 3xx or 2xx a success irrespective of scheme?

**Review by RyanTheOptimist — COMMENTED** [review]
Thanks for doing this! Looks great. Couple small questions.

**Comment by danzh2010** [comment]
MixedSchemeTest.kt failed on kotlin_tests_linux CI. It seems to use a dns resolver which isn't able to resolve example.com on CI: 

[2023-05-26 16:27:10.746][44][debug][forward_proxy] [external/envoy/source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:295] starting main thread resolve for host='example.com:80' dns='example.com' port='80'
[2023-05-26 16:27:10.746][44][debug][dns] [external/envoy/source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc:33] adding new query [example.com] to pending queries
[2023-05-26 16:27:10.746][49][debug][dns] [external/envoy/source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc:162] popped pending query [example.com]
[2023-05-26 16:27:10.755][49][debug][dns] [external/envoy/source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc:184] getaddrinfo failed with rc=Temporary failure in name resolution errno=Resource temporarily unavailable
[2023-05-26 16:27:10.755][44][debug][forward_proxy] [external/envoy/source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:319] main thread resolve complete for host 'example.com:80': []
[2023-05-26 16:27:10.755][44][debug][forward_proxy] [external/envoy/source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc:389] [C12345][S9844527111277460371] load DNS cache complete, continuing after adding resolved host: example.com
[2023-05-26 16:27:10.755][44][debug][filter] [library/common/extensions/filters/http/network_configuration/filter.cc:146] NetworkConfigurationFilter::onLocalReply
[2023-05-26 16:27:10.755][44][debug][upstream] [library/common/network/connectivity_manager.cc:147] reportNetworkUsage(configuration_key: 1, network_fault: true)
[2023-05-26 16:27:10.755][44][debug][upstream] [library/common/network/connectivity_manager.cc:150] bailing due to interface binding being disabled
[2023-05-26 16:27:10.755][44][trace][filter] [library/common/extensions/filters/http/local_error/filter.cc:14] LocalErrorFilter::onLocalReply(503, dns_resolution_failure)
[2023-05-26 16:27:10.755][44][debug][http] [external/envoy/source/common/http/filter_manager.cc:902] [C12345][S9844527111277460371] Resetting stream due to dns_resolution_failure. onLocalReply requested reset.

The test seems to be able to resolve example.com when ran locally. @alyssawilk Any idea why they resolved DNS names differently?

**Comment by phlax** [comment]
@alyssawilk seems this one is waiting for review

/wait-any

File: mobile/test/kotlin/integration/BUILD [hunk 4]
```diff
@@ -250,6 +250,20 @@ envoy_mobile_jni_kt_test(
     ],
 )
 
+envoy_mobile_jni_kt_test(
```
Comment (alyssawilk) [inline mobile/test/kotlin/integration/BUILD:253]: sorry I had to revert this test becasue example.com doesn't work on CI.  guess I failed to remove the file.
please remove the test and this file and add regression to TEST_P(ProxyFilterIntegrationTest, MultiPortTest) {

**Review by alyssawilk — COMMENTED** [review]
/wait on CI

File: mobile/test/kotlin/integration/BUILD (hunk 4 above)
Comment (danzh2010) [reply mobile/test/kotlin/integration/BUILD:253]: ProxyFilterIntegrationTest and most other integration tests I observed explicitly specify port in the `Host` header. Whereas the issue this PR is trying to fix happens when the port is implicit derived from the scheme. So other than this test, I couldn't find another one suitable for regression test. Do you have any DNS cache integration test in your mind which doesn't specify a upstream port in request headers?

Comment (alyssawilk) [reply mobile/test/kotlin/integration/BUILD:253]: argh, then you need the e2e test which doesn't work on CI for reasons I never tracked down.
let's land this with the unit test because it fixes a real problem, and assign me a follow-up bug to get the e2e tes tworking

Comment (alyssawilk) [reply mobile/test/kotlin/integration/BUILD:253]: strike that


+// Regression test a bug where the host header was used for cache lookups rather than host:port key
+TEST_P(ProxyFilterIntegrationTest, CacheSansPort) {
+  useAccessLog("%RESPONSE_CODE_DETAILS%");
+  initializeWithArgs();
+  codec_client_ = makeHttpConnection(lookupPort("http"));
+  const Http::TestRequestHeaderMapImpl request_headers{
+      {":method", "POST"},
+      {":path", "/test/long/url"},
+      {":scheme", "http"},
+      {":authority", "localhost"}};
+
+  // Send a request to localhost, with no port specified. The cluster will
+  // default to localhost:443, and the connection will fail.
+  auto response = codec_client_->makeHeaderOnlyRequest(request_headers);
+  ASSERT_TRUE(response->waitForEndStream());
+  EXPECT_EQ("503", response->headers().getStatusValue());
+  EXPECT_THAT(waitForAccessLog(access_log_name_), HasSubstr("upstream_reset_before_response_started"));
+
+  // Now try a second request and make sure it encounters the same error.
+  auto response2 = codec_client_->makeHeaderOnlyRequest(request_headers);
+  ASSERT_TRUE(response2->waitForEndStream());
+  EXPECT_EQ("503", response2->headers().getStatusValue());
+  EXPECT_THAT(waitForAccessLog(access_log_name_, 1), HasSubstr("upstream_reset_before_response_started"));
+}
+
[ RUN      ] IpVersions/ProxyFilterIntegrationTest.CacheSansPort/IPv6
test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc:513: Failure
Value of: waitForAccessLog(access_log_name_, 1)
Expected: has substring "upstream_reset_before_response_started"
  Actual: "dns_resolution_failure"
Stack trace:
  0x296693e: Envoy::(anonymous namespace)::ProxyFilterIntegrationTest_CacheSansPort_Test::TestBody()
  0x6d6b31b: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x6d5ba1a: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x6d47913: testing::Test::Run()
  0x6d482b4: testing::TestInfo::Run()
... Google Test internal frames ...

Comment (danzh2010) [reply mobile/test/kotlin/integration/BUILD]: This is clever! Thanks for the regression test! I can MixedSchemeTest.kt now.

**Review by alyssawilk — APPROVED** [review]
