### PR TITLE
event: fix DispatcherImplTest::InitializeStats flake

### LINKED ISSUE #6611: DispatcherImplTest.InitializeStats flake on release builds
See https://circleci.com/gh/envoyproxy/envoy/199729?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link:

```
[ RUN      ] DispatcherImplTest.InitializeStats
[2019-04-16 21:43:17.249][22113][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Segmentation fault, suspect faulting address 0x0
[2019-04-16 21:43:17.249][22113][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-04-16 21:43:17.249][22113][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #0: __restore_rt [0x7f5dbc28c390]
[2019-04-16 21:43:17.251][22113][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #1: Envoy::Event::DispatcherImpl::run() [0x3b13cf]
[2019-04-16 21:43:17.252][22113][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #2: std::_Function_handler<>::_M_invoke() [0x36e8d2]
[2019-04-16 21:43:17.252][22113][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #3: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::_FUN() [0x67c5c5]
[2019-04-16 21:43:17.252][22113][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #4: start_thread [0x7f5dbc2826ba]
external/bazel_tools/tools/test/test-setup.sh: line 310: 22092 Segmentation fault      "${TEST_PATH}" "$@" 2>&1
```

### PR DESCRIPTION
**Pull request by mergeconflict**
Description: Fix DispatcherImplTest::InitializeStats flake due to dispatcher lifetime exceeding mock stats scope lifetime.
Risk Level: low
Testing: bazel test //test/common/event:dispatcher_impl_test --runs_per_test=1000 (with ASAN enabled)
Docs Changes: n/a
Release Notes: n/a
Fixes #6611

Signed-off-by: Dan Rosen <mergeconflict@google.com>

### CODE REVIEW

File: test/common/event/dispatcher_impl_test.cc [hunk 1]
```diff
@@ -85,6 +85,7 @@ class DispatcherImplTest : public testing::Test {
     dispatcher_thread_->join();
   }
 
+  NiceMock<Stats::MockStore> scope_;
```
Comment (htuch) [inline test/common/event/dispatcher_impl_test.cc]: Can you add something like `// Used by InitializeStats to ensure lives past the destructor and dispatcher exit.`?

File: test/common/event/dispatcher_impl_test.cc [hunk 2]
```diff
@@ -85,7 +85,7 @@ class DispatcherImplTest : public testing::Test {
     dispatcher_thread_->join();
   }
 
-  NiceMock<Stats::MockStore> scope_;
+  NiceMock<Stats::MockStore> scope_; // Used in InitializeStats, needs to outlive dispatcher_.
```
Comment (htuch) [inline test/common/event/dispatcher_impl_test.cc]: Can you clarify that it's not about outliving `dispatcher_` object lifetime (which was true even before thie PR), but the `dispatcher_->exit()`.
