### PR TITLE
mysql_filter: add handling for partial messages

### LINKED ISSUE #6696: mysql filter fails to parse a partial mysql message
When faced with a fragmented packet, mysql filter fails to parse a mysql message and gives up.

The issue is reproduced with istio-1.1.3 ([istio bug](https://github.com/istio/istio/issues/13484)), by having php talk to mysql. When the mysql filter is enabled, envoy fails with:

```
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 09:21:32.783][30][trace][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_decoder.cc:140] mysql_proxy: decoding 16384 bytes at offset 16337
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 09:21:32.783][30][trace][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_utils.cc:149] mysql_proxy: MYSQL-hdrseq 141, len 61
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 09:21:32.783][30][trace][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_decoder.cc:13] mysql_proxy: parsing message, offset 16341, seq 141, len 61
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 09:21:32.783][30][trace][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_decoder.cc:136] mysql_proxy: msg parsed, session in state 9
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 09:21:32.783][30][trace][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_decoder.cc:160] mysql_proxy: offset after decoding is 16402 out of 16384
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 09:21:32.783][30][trace][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_decoder.cc:140] mysql_proxy: decoding 16384 bytes at offset 16402
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 09:21:32.784][30][info][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_filter.cc:57] mysql_proxy: decoding error: error parsing mysql packet header
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 09:21:32.784][30][trace][filter] [external/envoy/source/common/tcp_proxy/tcp_proxy.cc:501] [C37] upstream connection received 105729 bytes, end_stream=false
```

after which the connection stalls and php times out.

Here's the last packet forwarded by envoy:

image

The `16402` points at the end of the last full message:

image

This PDU is split in half between the TCP packets and that, I guess, causes the mysql filter to flip out.

### PR DESCRIPTION
**Pull request by venilnoronha**
Description: This adds logic to handle partially buffered protocol messages in the MySQL filter.
Risk Level: Med
Testing: Added a new test
Docs Changes: N/A
Release Notes: N/A
Fixes #6696

### CODE REVIEW

File: source/extensions/filters/network/mysql_proxy/mysql_filter.cc [hunk 1]
```diff
@@ -23,23 +23,26 @@ void MySQLFilter::initializeReadFilterCallbacks(Network::ReadFilterCallbacks& ca
...
   return Network::FilterStatus::Continue;
 }
 
 Network::FilterStatus MySQLFilter::onWrite(Buffer::Instance& data, bool) {
-  doDecode(data);
-  return Network::FilterStatus::Continue;
-}
-
-void MySQLFilter::doDecode(Buffer::Instance& buffer) {
   // Safety measure just to make sure that if we have a decoding error we keep going and lose stats.
```
[the remark this answers is not in the document]
Comment (venilnoronha) [reply source/extensions/filters/network/mysql_proxy/mysql_filter.cc]: I think it'd be valid as long as there's the `sniffing_` variable.

**Comment by venilnoronha** [comment]
Gentle ping for a review.

File: source/extensions/filters/network/mysql_proxy/mysql_filter.cc [hunk 2]
```diff
@@ -23,23 +23,26 @@ void MySQLFilter::initializeReadFilterCallbacks(Network::ReadFilterCallbacks& ca
...
   // This can be removed once we are more confident of this code.
-  if (!sniffing_) {
-    buffer.drain(buffer.length());
-    return;
+  if (sniffing_) {
```
Comment (rshriram) [inline source/extensions/filters/network/mysql_proxy/mysql_filter.cc]: could you remind me how this sniffing works? the github diff is not showing the entire thing.. I remember this was a boolean that indicated whether we had a decoding error or not and if there was an error, it would simply forward all data as is. But you seem to have flipped the condition.. why?

Comment (venilnoronha) [reply source/extensions/filters/network/mysql_proxy/mysql_filter.cc]: If there was a decoding error, we used to empty the `buffer`. That isn't correct. We need to retain the information in the buffer as that's what is being passed to the next filter (and eventually to MySQL).

In this new logic, I'm not modifying the original `buffer` instance at all. I'm only copying its contents to a new `read_buffer_`/`write_buffer_` instance if the `sniffing_` flag is set to `true`. I've flipped the logic to just reorganize the code.

Comment (venilnoronha) [reply source/extensions/filters/network/mysql_proxy/mysql_filter.cc]: Now, if there's a decoding error, nothing will be copied over to the read/write buffers; however, the original contents of the message will still be forwarded to the next filter hoping that MySQL will be able to handle it correctly.

**Comment by venilnoronha** [comment]
@mattklein123 this is ready for a final pass.

File: source/extensions/filters/network/mysql_proxy/mysql_codec.h [hunk 3]
```diff
@@ -109,18 +109,15 @@ class MySQLCodec : public Logger::Loggable<Logger::Id::filter> {
...
-    offset = prev_offset + len; // Ensure that the whole message was consumed
-    return result;
+    return parseMessage(data, len);
   }
 
   virtual std::string encode() PURE;
 
 protected:
-  virtual int parseMessage(Buffer::Instance& data, uint64_t& offset, int len) PURE;
+  virtual int parseMessage(Buffer::Instance& data, int len) PURE;
```
Comment (mattklein123) [inline source/extensions/filters/network/mysql_proxy/mysql_codec.h]: Not in this change but can you update `int` to a proper unsigned type? Same above for `decode` and other places it applies in this PR? Thank you.

Comment (venilnoronha) [reply source/extensions/filters/network/mysql_proxy/mysql_codec.h]: Addressed in 9968c6a.
