### PR TITLE
listener: ensure `getBalancedHandlerByAddress` works with ipv4_compat

### LINKED ISSUE #18134: Some (IPv4) clusters not reachable in 1.19 proxy
*Title*: *Some (IPv4) clusters not reachable in 1.19 proxy*

*Description*:
We are currently testing a dual-stack solution for Istio, *loosely* based on istio/istio#29076 with further modifications. Think mainly using :: listeners with ipv4_compat mode instead of the default wildcard listeners. This has been working pretty well in Istio 1.10/Envoy 1.18.3, but now using Istio 1.11/Envoy 1.19.1, some of the requests are failing because Envoy seems unable to reach certain clusters (filter chains not matching as expected?).

*Repro steps*:
- Deploy istiod with listener modifications in dual-stack cluster and using `meshConfig.outboundTrafficPolicy.mode=REGISTRY_ONLY` and `pilot.env.PILOT_ENABLE_INBOUND_PASSTHROUGH=false`
- Deploy pod WITHOUT Istio sidecar from image kennethreitz/httpbin, using `{"command": ["gunicorn"], "args": ["-b", "[::]:80", "--access-logfile", "-", "httpbin:app"]`, and create separate IPv4 (httpbin4) and IPv6 (httpbin6) single-stack services pointing to said pod
- Deploy pod WITH Istio 1.11/Envoy 1.19.1-based sidecar from image curlimages/curl
- Deploy pod WITH Istio 1.10/Envoy 1.18.3-based sidecar from image curlimages/curl
- Curl httpbin4 and httpbin6 from both curl pods and observe requests to httpbin4 fail in pod with the 1.19.1 proxy

I have tcpdump-ed the packets, but only found the DNS requests, TCP handshake b/w pod IP and 127.0.0.1:15001 (redirected from svc IP via iptables), the actual GET request and Envoy responding [ACK] followed by [RST, ACK].
I also could not find significant differences in the config dumps between the working and non-working proxies, though admittedly I may have just missed it, so I am resigned to suspect some change in Envoy 1.19...

*Admin and Stats Output*:
See attached config dumps (and following o/p from istioctl)

1.19.1 proxy:
```
$ istioctl proxy-config listeners mesh-client-56c9c7db79-xjlc9.test-2753776
ADDRESS         PORT  MATCH                                                                                         DESTINATION
::              80    Trans: raw_buffer; App: HTTP                                                                  Route: 80
::              80    ALL                                                                                           Non-HTTP/Non-TCP
10.109.60.149   443   ALL                                                                                           Cluster: outbound|443||istio-ingressgateway-ipv4.test-2753776.svc.cluster.local
10.111.177.166  443   ALL                                                                                           Cluster: outbound|443||istio-egressgateway.test-2753776.svc.cluster.local
10.99.235.180   443   ALL                                                                                           Cluster: outbound|443||istiod.test-2753776.svc.cluster.local
fc00:2000::b5ab 443   ALL                                                                                           Cluster: outbound|443||istio-ingressgateway-ipv6.test-2753776.svc.cluster.local
::              15001 Addr: *:15001                                                                                 Non-HTTP/Non-TCP
::              15001 ALL                                                                                           Non-HTTP/Non-TCP
::              15006 Addr: *:15006                                                                                 Non-HTTP/Non-TCP
::              15006 Trans: tls; Addr: ::0/0                                                                       InboundPassthroughClusterIpv6
::              15006 Trans: raw_buffer; Addr: ::0/0                                                                InboundPassthroughClusterIpv6
::              15006 Trans: tls; App: TCP TLS; Addr: ::0/0                                                         InboundPassthroughClusterIpv6
::              15006 Trans: raw_buffer; App: HTTP; Addr: ::0/0                                                     InboundPassthroughClusterIpv6
::              15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: ::0/0                          InboundPassthroughClusterIpv6
::              15006 Trans: tls; Addr: 0.0.0.0/0                                                                   InboundPassthroughClusterIpv4
::              15006 Trans: raw_buffer; Addr: 0.0.0.0/0                                                            InboundPassthroughClusterIpv4
::              15006 Trans: tls; App: TCP TLS; Addr: 0.0.0.0/0                                                     InboundPassthroughClusterIpv4
::              15006 Trans: raw_buffer; App: HTTP; Addr: 0.0.0.0/0                                                 InboundPassthroughClusterIpv4
::              15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: 0.0.0.0/0                      InboundPassthroughClusterIpv4
::              15006 Trans: tls; App: istio,istio-peer-exchange,istio-http/1.0,istio-http/1.1,istio-h2; Addr: *:80 Cluster: inbound|80||
::              15006 Trans: raw_buffer; Addr: *:80                                                                 Cluster: inbound|80||
::              15010 Trans: raw_buffer; App: HTTP                                                                  Route: 15010
::              15010 ALL                                                                                           Non-HTTP/Non-TCP
10.99.235.180   15012 ALL                                                                                           Cluster: outbound|15012||istiod.test-2753776.svc.cluster.local
::              15014 Trans: raw_buffer; App: HTTP                                                                  Route: 15014
::              15014 ALL                                                                                           Non-HTTP/Non-TCP
10.109.60.149   15021 Trans: raw_buffer; App: HTTP                                                                  Route: istio-ingressgateway-ipv4.test-2753776.svc.cluster.local:15021
10.109.60.149   15021 ALL                                                                                           Cluster: outbound|15021||istio-ingressgateway-ipv4.test-2753776.svc.cluster.local
::              15021 ALL                                                                                           Inline Route: /healthz/ready*
fc00:2000::b5ab 15021 Trans: raw_buffer; App: HTTP                                                                  Route: istio-ingressgateway-ipv6.test-2753776.svc.cluster.local:15021
fc00:2000::b5ab 15021 ALL                                                                                           Cluster: outbound|15021||istio-ingressgateway-ipv6.test-2753776.svc.cluster.local
::              15090 ALL                                                                                           Inline Route: /stats/prometheus*
$ istioctl proxy-config clusters mesh-client-56c9c7db79-xjlc9.test-2753776
SERVICE FQDN                                                 PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
                                                             80        -          inbound       STATIC           
BlackHoleCluster                                             -         -          -             STATIC           
InboundPassthroughClusterIpv4                                -         -          -             ORIGINAL_DST     
InboundPassthroughClusterIpv6                                -         -          -             ORIGINAL_DST     
PassthroughCluster                                           -         -          -             ORIGINAL_DST     
agent                                                        -         -          -             STATIC           
httpbin4.test-2753776.svc.cluster.local                      80        -          outbound      EDS              
httpbin6.test-2753776.svc.cluster.local                      80        -          outbound      EDS              
istio-egressgateway.test-2753776.svc.cluster.local           80        -          outbound      EDS              
istio-egressgateway.test-2753776.svc.cluster.local           443       -          outbound      EDS              
istio-ingressgateway-ipv4.test-2753776.svc.cluster.local     80        -          outbound      EDS              
istio-ingressgateway-ipv4.test-2753776.svc.cluster.local     443       -          outbound      EDS              
istio-ingressgateway-ipv4.test-2753776.svc.cluster.local     15021     -          outbound      EDS              
istio-ingressgateway-ipv6.test-2753776.svc.cluster.local     80        -          outbound      EDS              
istio-ingressgateway-ipv6.test-2753776.svc.cluster.local     443       -          outbound      EDS              
istio-ingressgateway-ipv6.test-2753776.svc.cluster.local     15021     -          outbound      EDS              
istiod.test-2753776.svc.cluster.local                        443       -          outbound      EDS              
istiod.test-2753776.svc.cluster.local                        15010     -          outbound      EDS              
istiod.test-2753776.svc.cluster.local                        15012     -          outbound      EDS              
istiod.test-2753776.svc.cluster.local                        15014     -          outbound      EDS              
mesh-client4.test-2753776.svc.cluster.local                  80        -          outbound      EDS              
mesh-client6.test-2753776.svc.cluster.local                  80        -          outbound      EDS              
prometheus_stats                                             -         -          -             STATIC           
sds-grpc                                                     -         -          -             STATIC           
sleep.test-2753776.svc.cluster.local                         80        -          outbound      EDS              
xds-grpc                                                     -         -          -             STATIC           
zipkin                                                       -         -          -             STRICT_DNS       
$ istioctl proxy-config routes mesh-client-56c9c7db79-xjlc9.test-2753776
NAME                                                               DOMAINS                                                                           MATCH                  VIRTUAL SERVICE
80                                                                 *                                                                                 /*                     
80                                                                 httpbin4, httpbin4.test-2753776 + 1 more...                                       /*                     
80                                                                 httpbin6, httpbin6.test-2753776                                                   /*                     
80                                                                 istio-egressgateway, istio-egressgateway.test-2753776 + 1 more...                 /*                     
80                                                                 istio-ingressgateway-ipv4, istio-ingressgateway-ipv4.test-2753776 + 1 more...     /*                     
80                                                                 istio-ingressgateway-ipv6, istio-ingressgateway-ipv6.test-2753776                 /*                     
80                                                                 mesh-client4, mesh-client4.test-2753776 + 1 more...                               /*                     
80                                                                 mesh-client6, mesh-client6.test-2753776                                           /*                     
80                                                                 sleep, sleep.test-2753776 + 1 more...                                             /*                     
istio-ingressgateway-ipv4.test-2753776.svc.cluster.local:15021     istio-ingressgateway-ipv4, istio-ingressgateway-ipv4.test-2753776 + 1 more...     /*                     
InboundPassthroughClusterIpv4                                      *                                                                                 /*                     
istio-ingressgateway-ipv6.test-2753776.svc.cluster.local:15021     istio-ingressgateway-ipv6, istio-ingressgateway-ipv6.test-2753776                 /*                     
InboundPassthroughClusterIpv6                                      *                                                                                 /*                     
InboundPassthroughClusterIpv6                                      *                                                                                 /*                     
inbound|80||                                                       *                                                                                 /*                     
                                                                   *                                                                                 /stats/prometheus*     
InboundPassthroughClusterIpv4                                      *                                                                                 /*                     
                                                                   *                                                                                 /healthz/ready*        
15010                                                              *                                                                                 /*                     
15010                                                              istiod, istiod.test-2753776 + 1 more...                                           /*                     
15014                                                              *                                                                                 /*                     
15014                                                              istiod, istiod.test-2753776 + 1 more...                                           /*                     
inbound|80||                                                       *                                                                                 /*     
```

1.18.3 proxy:
```
$ istioctl proxy-config listeners sleep-568fc658f-cbpgc.test-2753776
ADDRESS         PORT  MATCH                                                                                         DESTINATION
::              80    Trans: raw_buffer; App: HTTP                                                                  Route: 80
::              80    ALL                                                                                           Non-HTTP/Non-TCP
10.109.60.149   443   ALL                                                                                           Cluster: outbound|443||istio-ingressgateway-ipv4.test-2753776.svc.cluster.local
10.111.177.166  443   ALL                                                                                           Cluster: outbound|443||istio-egressgateway.test-2753776.svc.cluster.local
10.99.235.180   443   ALL                                                                                           Cluster: outbound|443||istiod.test-2753776.svc.cluster.local
fc00:2000::b5ab 443   ALL                                                                                           Cluster: outbound|443||istio-ingressgateway-ipv6.test-2753776.svc.cluster.local
::              15001 Addr: *:15001                                                                                 Non-HTTP/Non-TCP
::              15001 ALL                                                                                           Non-HTTP/Non-TCP
::              15006 Addr: *:15006                                                                                 Non-HTTP/Non-TCP
::              15006 Trans: tls; Addr: ::0/0                                                                       InboundPassthroughClusterIpv6
::              15006 Trans: raw_buffer; Addr: ::0/0                                                                InboundPassthroughClusterIpv6
::              15006 Trans: tls; App: TCP TLS; Addr: ::0/0                                                         InboundPassthroughClusterIpv6
::              15006 Trans: raw_buffer; App: HTTP; Addr: ::0/0                                                     InboundPassthroughClusterIpv6
::              15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: ::0/0                          InboundPassthroughClusterIpv6
::              15006 Trans: tls; Addr: 0.0.0.0/0                                                                   InboundPassthroughClusterIpv4
::              15006 Trans: raw_buffer; Addr: 0.0.0.0/0                                                            InboundPassthroughClusterIpv4
::              15006 Trans: tls; App: TCP TLS; Addr: 0.0.0.0/0                                                     InboundPassthroughClusterIpv4
::              15006 Trans: raw_buffer; App: HTTP; Addr: 0.0.0.0/0                                                 InboundPassthroughClusterIpv4
::              15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: 0.0.0.0/0                      InboundPassthroughClusterIpv4
::              15006 Trans: tls; App: istio,istio-peer-exchange,istio-http/1.0,istio-http/1.1,istio-h2; Addr: *:80 Cluster: inbound|80||
::              15006 Trans: raw_buffer; Addr: *:80                                                                 Cluster: inbound|80||
::              15010 Trans: raw_buffer; App: HTTP                                                                  Route: 15010
::              15010 ALL                                                                                           Non-HTTP/Non-TCP
10.99.235.180   15012 ALL                                                                                           Cluster: outbound|15012||istiod.test-2753776.svc.cluster.local
::              15014 Trans: raw_buffer; App: HTTP                                                                  Route: 15014
::              15014 ALL                                                                                           Non-HTTP/Non-TCP
10.109.60.149   15021 Trans: raw_buffer; App: HTTP                                                                  Route: istio-ingressgateway-ipv4.test-2753776.svc.cluster.local:15021
10.109.60.149   15021 ALL                                                                                           Cluster: outbound|15021||istio-ingressgateway-ipv4.test-2753776.svc.cluster.local
::              15021 ALL                                                                                           Inline Route: /healthz/ready*
fc00:2000::b5ab 15021 Trans: raw_buffer; App: HTTP                                                                  Route: istio-ingressgateway-ipv6.test-2753776.svc.cluster.local:15021
fc00:2000::b5ab 15021 ALL                                                                                           Cluster: outbound|15021||istio-ingressgateway-ipv6.test-2753776.svc.cluster.local
::              15090 ALL                                                                                           Inline Route: /stats/prometheus*
$ istioctl proxy-config clusters sleep-568fc658f-cbpgc.test-2753776
SERVICE FQDN                                                 PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
                                                             80        -          inbound       STATIC           
BlackHoleCluster                                             -         -          -             STATIC           
InboundPassthroughClusterIpv4                                -         -          -             ORIGINAL_DST     
InboundPassthroughClusterIpv6                                -         -          -             ORIGINAL_DST     
PassthroughCluster                                           -         -          -             ORIGINAL_DST     
agent                                                        -         -          -             STATIC           
httpbin4.test-2753776.svc.cluster.local                      80        -          outbound      EDS              
httpbin6.test-2753776.svc.cluster.local                      80        -          outbound      EDS              
istio-egressgateway.test-2753776.svc.cluster.local           80        -          outbound      EDS              
istio-egressgateway.test-2753776.svc.cluster.local           443       -          outbound      EDS              
istio-ingressgateway-ipv4.test-2753776.svc.cluster.local     80        -          outbound      EDS              
istio-ingressgateway-ipv4.test-2753776.svc.cluster.local     443       -          outbound      EDS              
istio-ingressgateway-ipv4.test-2753776.svc.cluster.local     15021     -          outbound      EDS              
istio-ingressgateway-ipv6.test-2753776.svc.cluster.local     80        -          outbound      EDS              
istio-ingressgateway-ipv6.test-2753776.svc.cluster.local     443       -          outbound      EDS              
istio-ingressgateway-ipv6.test-2753776.svc.cluster.local     15021     -          outbound      EDS              
istiod.test-2753776.svc.cluster.local                        443       -          outbound      EDS              
istiod.test-2753776.svc.cluster.local                        15010     -          outbound      EDS              
istiod.test-2753776.svc.cluster.local                        15012     -          outbound      EDS              
istiod.test-2753776.svc.cluster.local                        15014     -          outbound      EDS              
mesh-client4.test-2753776.svc.cluster.local                  80        -          outbound      EDS              
mesh-client6.test-2753776.svc.cluster.local                  80        -          outbound      EDS              
prometheus_stats                                             -         -          -             STATIC           
sds-grpc                                                     -         -          -             STATIC           
sleep.test-2753776.svc.cluster.local                         80        -          outbound      EDS              
xds-grpc                                                     -         -          -             STATIC           
zipkin                                                       -         -          -             STRICT_DNS     
$ istioctl proxy-config routes sleep-568fc658f-cbpgc.test-2753776
NAME                                                               DOMAINS                                                                           MATCH                  VIRTUAL SERVICE
80                                                                 *                                                                                 /*                     
80                                                                 httpbin4, httpbin4.test-2753776 + 1 more...                                       /*                     
80                                                                 httpbin6, httpbin6.test-2753776                                                   /*                     
80                                                                 istio-egressgateway, istio-egressgateway.test-2753776 + 1 more...                 /*                     
80                                                                 istio-ingressgateway-ipv4, istio-ingressgateway-ipv4.test-2753776 + 1 more...     /*                     
80                                                                 istio-ingressgateway-ipv6, istio-ingressgateway-ipv6.test-2753776                 /*                     
80                                                                 mesh-client4, mesh-client4.test-2753776 + 1 more...                               /*                     
80                                                                 mesh-client6, mesh-client6.test-2753776                                           /*                     
80                                                                 sleep, sleep.test-2753776 + 1 more...                                             /*                     
15010                                                              *                                                                                 /*                     
15010                                                              istiod, istiod.test-2753776 + 1 more...                                           /*                     
istio-ingressgateway-ipv4.test-2753776.svc.cluster.local:15021     istio-ingressgateway-ipv4, istio-ingressgateway-ipv4.test-2753776 + 1 more...     /*                     
InboundPassthroughClusterIpv4                                      *                                                                                 /*                     
istio-ingressgateway-ipv6.test-2753776.svc.cluster.local:15021     istio-ingressgateway-ipv6, istio-ingressgateway-ipv6.test-2753776                 /*                     
InboundPassthroughClusterIpv6                                      *                                                                                 /*                     
inbound|80||                                                       *                                                                                 /*                     
                                                                   *                                                                                 /stats/prometheus*     
                                                                   *                                                                                 /healthz/ready*        
InboundPassthroughClusterIpv4                                      *                                                                                 /*                     
InboundPassthroughClusterIpv6                                      *                                                                                 /*                     
15014                                                              *                                                                                 /*                     
15014                                                              istiod, istiod.test-2753776 + 1 more...                                           /*                     
inbound|80||                                                       *                                                                                 /*           
```

*Config*:
[new_proxy.txt](https://github.com/envoyproxy/envoy/files/7171293/new_proxy.txt)
[old_proxy.txt](https://github.com/envoyproxy/envoy/files/7171298/old_proxy.txt)

*Logs*:
1.19.1 proxy:
```
$ k exec -n test-2753776 mesh-client-56c9c7db79-xjlc9 -c client -- curl -s http://httpbin4/status/418
command terminated with exit code 56

2021-09-15T09:18:04.517619Z	debug	envoy filter	original_dst: New connection accepted
2021-09-15T09:18:04.518005Z	debug	envoy filter	[C477] new tcp proxy session
2021-09-15T09:18:04.518053Z	debug	envoy filter	[C477] Creating connection to cluster BlackHoleCluster

$ k exec -n test-2753776 mesh-client-56c9c7db79-xjlc9 -c client -- curl -s http://httpbin6/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
2021-09-15T12:00:57.035144Z	debug	envoy filter	original_dst: New connection accepted
2021-09-15T12:00:57.035228Z	debug	envoy filter	tls inspector: new connection accepted
2021-09-15T12:00:57.035253Z	debug	envoy filter	http inspector: new connection accepted
2021-09-15T12:00:57.035487Z	debug	envoy filter	override with 3 ALPNs
[2021-09-15T12:00:57.035Z] "GET /status/418 HTTP/1.1" 418 - via_upstream - "-" 0 135 2 1 "-" "curl/7.60.0" "c8e8a781-fa30-4032-a0dc-083e9c0f25ab" "httpbin6" "[fc00:1000::4e2e]:80" outbound|80||httpbin6.test-2753776.svc.cluster.local [fc00:1000::75d8]:39504 [fc00:2000::92da]:80 [fc00:1000::75d8]:36672 - default
```

1.18.3 proxy:
```
$ k exec -n test-2753776 sleep-568fc658f-cbpgc -c sleep -- curl -s http://httpbin4/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
[2021-09-15T13:38:14.572Z] "GET /status/418 HTTP/1.1" 418 - via_upstream - "-" 0 135 2 1 "-" "curl/7.60.0" "813d5818-bbeb-465e-823b-4c77a80ce4b3" "httpbin4" "192.168.78.60:80" outbound|80||httpbin4.test-2753776.svc.cluster.local 192.168.185.237:59088 10.101.126.114:80 192.168.185.237:45962 - default

$ k exec -n test-2753776 sleep-568fc658f-cbpgc -c sleep -- curl -s http://httpbin6/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
[2021-09-15T13:38:10.761Z] "GET /status/418 HTTP/1.1" 418 - via_upstream - "-" 0 135 8 7 "-" "curl/7.60.0" "b7cd6687-8757-4dbf-8626-3d613dbad7d3" "httpbin6" "[fc00:1000::4e2e]:80" outbound|80||httpbin6.test-2753776.svc.cluster.local [fc00:1000::b9e6]:40210 [fc00:2000::92da]:80 [fc00:1000::b9e6]:43436 - default
```

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: listener: ensure `getBalancedHandlerByAddress` works with ipv4_compat
Additional Description:
When a listener is listening on ipv6 any-address or ipv4-compatible ipv6 address, and with ipv4_compat flag as true, it is expected to accept the request both from ipv4 and ipv6 address.

This PR will add a duplicated map item for ipv4 any-address or ipv4 compatible address if the listener has ipv4_compat flag, that will ensure `getBalancedHandlerByAddress` can match ipv4 request for it.

Also, add a more strict check on `ipv4_compat` flag. The `ip4_compat` only can be set as true when the address is Ipv6 any address or Ipv4-mapped Ipv6 address. The runtime flag is added `envoy.reloadable_features.strict_check_on_ipv4_compat` and the default is true.

Risk Level: low
Testing: unittest 
Docs Changes: n/a
Release Notes: A note added to minor incompatible change.
Platform Specific Features: n/a
Fixes #18134

Signed-off-by: He Jie Xu <hejie.xu@intel.com>

### CODE REVIEW

**Review by jacob-delgado — COMMENTED** [review]
Similar to what I had, but I couldn't get the tests in a good state. Thanks for doing this!

**Comment by jacob-delgado** [comment]
cc @soulxu and @ggreenway since this bug was written for v1.19+ should it be backported? I can help backport it if @soulxu is busy. Let me know as I believe you triage bugs for back porting. Thanks!

**Comment by ggreenway** [comment]
@lambdai can you take a first pass on this?

**Comment by lambdai** [comment]
> @lambdai can you take a first pass on this?

ack

**Comment by soulxu** [comment]
@lambdai thanks

**Review by lambdai — CHANGES_REQUESTED** [review]
Other than the inline commentsat connection_handler, I have below questions 

1. Is `[::]` w/o ipv6only actually listen on ipv4 any address? The listen and bind is executed on main thread, but I don't see the change there. 
  If not, the current code only fix the part that finding listener not binding_to_port, but not the general re balancing among physical listener.

The partial fix makes it hard to deduct tcp_listener_map_by_address_. Perhaps it's ok to leave a TODO

File: source/server/connection_handler_impl.cc [hunk 1]
```diff
@@ -94,6 +94,16 @@ void ConnectionHandlerImpl::addListener(absl::optional<uint64_t> overridden_list
           details->typed_listener_)) {
     tcp_listener_map_by_address_.insert_or_assign(
         config.listenSocketFactory().localAddress()->asStringView(), details);
+
+    auto& address = details->address_;
+    // If the address is IPv6 and isn't v6only, adds an extra ipv4 any-address item to the map.
+    // Then this allows the `getBalancedHandlerByAddress` can match the ipv4 any-address also.
+    if (address->type() == Network::Address::Type::Ip &&
+        address->ip()->version() == Network::Address::IpVersion::v6 &&
+        !address->ip()->ipv6()->v6only()) {
```
[the remark this answers is not in the document]
Comment (soulxu) [reply source/server/connection_handler_impl.cc:103]: After looking https://datatracker.ietf.org/doc/html/rfc3493#section-3.7, I see now. you are right, it is more than just any address.  I should get the compatible ipv4 address out of the ipv6, and put it into the map.

**Comment by soulxu** [comment]
> Other than the inline commentsat connection_handler, I have below questions
> 
> 1. Is `[::]` w/o ipv6only actually listen on ipv4 any address? The listen and bind is executed on main thread, but I don't see the change there.

Yes, I tested that, the  `[::]` listen on ipv4 any address also. That should be done by the kernel.

File: source/server/connection_handler_impl.cc (hunk 1 above)
[the remark this answers is not in the document]
Comment (lambdai) [reply source/server/connection_handler_impl.cc:104]: Thank you! This is awesome.

**Review by lambdai — CHANGES_REQUESTED** [review]
Thank you for the update!
LGTM modulo the exception throw.

**Comment by soulxu** [comment]
> Thank you for the update! LGTM modulo the exception throw.

thanks for the review! Do you want to remove the exception?

**Comment by soulxu** [comment]
after conn handler fixed, this is ready for review again.

File: source/server/connection_handler_impl.cc [hunk 2]
```diff
@@ -94,6 +94,28 @@ void ConnectionHandlerImpl::addListener(absl::optional<uint64_t> overridden_list
...
+    auto& address = details->address_;
+    // If the address is IPv6 and isn't v6only, parse out the ipv4 compatible address from the ipv6
+    // address and put an item to the map. Then this allows the `getBalancedHandlerByAddress`
+    // can match the ipv4 any-address also.
+    if (address->type() == Network::Address::Type::Ip &&
+        address->ip()->version() == Network::Address::IpVersion::v6 &&
+        !address->ip()->ipv6()->v6only()) {
+      if (address->ip()->isAnyAddress()) {
+        tcp_listener_map_by_address_.insert_or_assign(
+            Network::Utility::getIpv4AnyAddress(address->ip()->port())->asStringView(), details);
```
Comment (soulxu) [inline source/server/connection_handler_impl.cc:107]: I need update this.

**Comment by soulxu** [comment]
success to run istio integration test locally

**Comment by lambdai** [comment]
> after conn handler fixed, this is ready for review again.

Thank you for the fix and holding this.

Can you remove the exception and move to listener manager? See the inline comment.

Also, can you explain how the listener manager handles two listener config: one is ipv4-any:80 and another is ipv6-any:80?

To be more precise, I think kernel allows the above 2 listening socket, but my hunch is that tcp_listener_map_by_address_ doesn't like two ipv4-any

**Comment by soulxu** [comment]
> > after conn handler fixed, this is ready for review again.
> 
> Thank you for the fix and holding this.
> 
> Can you remove the exception and move to listener manager? See the inline comment.

Got it, I moved to ListenerImpl. But in the end, I realize this is API behavior change. So I added a runtime flag this also.

The old behavior is you can set `ipv4_compat` flag on any kind of address, and linux kernel won't complain that also. But actually, only ipv6 any address and ipv4-mapped ipv6 address can work. From the API point of view, this seems wrong, since it is silent on something that doesn't work. But yes, this will break some people if they didn't use the `ipv4_compat` correctly before.  Anyway, let me know if this is the right choice.

> 
> Also, can you explain how the listener manager handles two listener config: one is ipv4-any:80 and another is ipv6-any:80?
> 
> To be more precise, I think kernel allows the above 2 listening socket, but my hunch is that tcp_listener_map_by_address_ doesn't like two ipv4-any

The ipv4 any address is "0.0.0.0" and the ipv6 any address is "::". And the tcp_listener_map_by_address_  is using those address string as key. so it should be ok. Although we have multiple way to right any address in Ipv6, but we have code to make it as canonical format https://github.com/envoyproxy/envoy/blob/main/source/common/network/address_impl.cc#L261

**Comment by soulxu** [comment]
> 
> > Also, can you explain how the listener manager handles two listener config: one is ipv4-any:80 and another is ipv6-any:80?
> 
> The listener manager can distinguish the two address by
> 
> https://github.com/envoyproxy/envoy/blob/027d6ca15adeae8cd478fcce67fc24322318e52e/source/common/network/address_impl.cc#L268-L272
> 
> The dynamic cast should return nullptr when it is same ip version, so listener manager is ok here.
> 
> > To be more precise, I think kernel allows the above 2 listening socket, but my hunch is that tcp_listener_map_by_address_ doesn't like two ipv4-any
> 
> The ipv4 any address is "0.0.0.0" and the ipv6 any address is "::". And the tcp_listener_map_by_address_ is using those address string as key. so it should be ok. Although we have multiple way to right any address in Ipv6, but we have code to make it as canonical format https://github.com/envoyproxy/envoy/blob/main/source/common/network/address_impl.cc#L261

Thanks for this good call. In the end, I found a corner case. We can one listener for "::" and ipv4_compat, another listener is for "0.0.0.0". The kernel will route the request to "0.0.0.0". And same behavior on ipv4-mapped ipv6 address.

File: source/server/connection_handler_impl.cc [hunk 3]
```diff
@@ -95,6 +95,29 @@ void ConnectionHandlerImpl::addListener(absl::optional<uint64_t> overridden_list
...
+    // can match the ipv4 any-address also.
+    if (address->type() == Network::Address::Type::Ip &&
+        address->ip()->version() == Network::Address::IpVersion::v6 &&
+        !address->ip()->ipv6()->v6only()) {
+      if (address->ip()->isAnyAddress()) {
+        tcp_listener_map_by_address_.insert_or_assign(
+            Network::Address::Ipv4Instance(address->ip()->port()).asStringView(), details);
+      } else {
+        auto v4_compatible_addr = address->ip()->ipv6()->v4CompatibleAddress();
+        // Remove this check when runtime flag
```
Comment (ggreenway) [inline source/server/connection_handler_impl.cc:111]: It may be better to leave the check in, and trigger an ENVOY_BUG when it fails, after the runtime check is removed. That seems better than crashing, and this check is inexpensive.

File: source/server/connection_handler_impl.cc [hunk 4]
```diff
@@ -95,6 +95,29 @@ void ConnectionHandlerImpl::addListener(absl::optional<uint64_t> overridden_list
...
+        // `envoy.reloadable_features.strict_check_on_ipv4_compat` deprecated.
+        if (v4_compatible_addr.ok()) {
+          // Since both "::" with ipv4_compat and "0.0.0.0" can be supported.
```
Comment (ggreenway) [inline source/server/connection_handler_impl.cc:114]: Is it a valid config to have listeners on both :: and 0.0.0.0? What is the expected behavior? Is it OS dependent?

File: source/server/listener_impl.cc [hunk 5]
```diff
@@ -348,6 +348,19 @@ ListenerImpl::ListenerImpl(const envoy::config::listener::v3::Listener& config,
               validation_visitor_, parent_.server_.api(), parent_.server_.options())),
       quic_stat_names_(parent_.quicStatNames()) {
 
+  if (address_->type() == Network::Address::Type::Ip &&
+      config.address().socket_address().ipv4_compat() &&
+      Runtime::runtimeFeatureEnabled("envoy.reloadable_features.strict_check_on_ipv4_compat")) {
+    if (address_->ip()->version() == Network::Address::IpVersion::v6) {
+      if (!address_->ip()->ipv6()->v4CompatibleAddress().ok()) {
+        throw EnvoyException("Only the Ipv6 any address and Ipv4-mapped Ipv6 address can be set "
```
Comment (ggreenway) [inline source/server/listener_impl.cc:356]: I think it may be clearer to say `::` and `0.0.0.0` instead of `any`

Comment (ggreenway) [reply source/server/listener_impl.cc:356]: `IPv6` and `IPv4` (capitalization) for consistency with other docs/messages.

Comment (ggreenway) [reply source/server/listener_impl.cc:356]: `Only IPv6 address '::' or valid IPv4-mapped IPv6 addresses can set ipv4_compat`

**Review by ggreenway — CHANGES_REQUESTED** [review]
I'm concerned about what happens if there are multiple overlapping wildcard listeners with ipv4 and ipv6+ipv4_compat. Can you elaborate on whether that config is even possible, what the expected behavior is, etc?

/wait

**Comment by soulxu** [comment]
> I'm concerned about what happens if there are multiple overlapping wildcard listeners with ipv4 and ipv6+ipv4_compat. Can you elaborate on whether that config is even possible, what the expected behavior is, etc?
> 
> /wait

Envoy supports that one listener is listening on `::` with `ipv4_compat` flag, and another listener is listening on `0.0.0.0`.  The ipv4 request is going to the second listener and the ipv6 request is going to the first listener. This is the Linux behavior. I don't know other OS behavior yet, I should be able to test it on Windows when I got the chance. For now I matched this behavior for the redirect in the code. https://github.com/envoyproxy/envoy/pull/19716/files#diff-3df0a7bd0288faa35b611e2bc11ea94713d9ca617ad16dfab81386c814f5e1eeR1554

But I do a test today on the ipv4-mapped ipv6 address. It is surprising that it has different behavior. We can both listen on `::FFFF:192.168.0.11 and `192.168.0.1`. But all the requests are going to the `192.168.0.1` listener even for ipv6 request. Using `netstat`, I can see envoy is only listening on "192.168.0.1".

I wrote a simple socket program to listen on those two addresses, it was rejected by kernel, only one of addresses can listen. In the end, I can listen to two addresses with `SO_REUSEADDR` opt. Also, interesting thing is that Envoy can listen on both addresses with `enable_reuse_port` as false, but I found this https://github.com/envoyproxy/envoy/blob/d1f5c2bc389d6217bca008c82b6a49019025f2d3/source/common/network/listen_socket_impl.h#L125-L133
That is probably the reason why Envoy always can listen to both addresses.

This is also only the Linux behavior.

But seems we should reject the user create two listeners for "::FFFF:192.168.0.1" and "192.168.0.1" at same time, it seems meanless.

I'm not sure on the use-case of "::" with ipv4_compat and "0.0.0.0" are valid or not, at least the linux works with that. I can keep matching that behavior for the redirect.

File: source/common/network/address_impl.cc [hunk 6]
```diff
@@ -233,6 +237,14 @@ std::string Ipv6Instance::Ipv6Helper::makeFriendlyAddress() const {
   ASSERT(str == ptr);
   return ptr;
 }
+StatusOr<InstanceConstSharedPtr> Ipv6Instance::Ipv6Helper::v4CompatibleAddress() const {
+  if (!v6only_ && IN6_IS_ADDR_V4MAPPED(&address_.sin6_addr)) {
+    struct sockaddr_in sin;
+    ipv6ToIpv4CompatibleAddress(&address_, &sin);
+    return Address::InstanceFactory::createInstancePtr<Address::Ipv4Instance>(&sin);
+  }
+  return absl::InvalidArgumentError(fmt::format("It isn't Ipv4-mapped Ipv6 address"));
```
[the remark this answers is not in the document]
Comment (soulxu) [reply source/common/network/address_impl.cc:246]: got it.

File: source/server/connection_handler_impl.cc (hunk 3 above)
Comment (soulxu) [reply source/server/connection_handler_impl.cc:111]: When `envoy.reloadable_features.strict_check_on_ipv4_compat` is false, should we go back to the original behavior instead of let Envoy stop?

File: source/server/connection_handler_impl.cc (hunk 4 above)
Comment (soulxu) [reply source/server/connection_handler_impl.cc:114]: Replied in the main thread.

File: source/server/listener_impl.cc (hunk 5 above)
Comment (soulxu) [reply source/server/listener_impl.cc:356]: got it.

File: source/server/connection_handler_impl.cc (hunk 4 above)
Comment (soulxu) [reply source/server/connection_handler_impl.cc:114]: oops, I should use `insert_or_assign` for any address also, sorry for I just realize that.

File: source/server/connection_handler_impl.cc [hunk 7]
```diff
@@ -95,6 +95,35 @@ void ConnectionHandlerImpl::addListener(absl::optional<uint64_t> overridden_list
...
+        address->ip()->version() == Network::Address::IpVersion::v6 &&
+        !address->ip()->ipv6()->v6only()) {
+      if (address->ip()->isAnyAddress()) {
+        // Since both "::" with ipv4_compat and "0.0.0.0" can be supported.
+        // So use `emplace` here, if there already one and it isn't shutdown for compatible addr,
+        // then won't insert a new one.
+        auto ipv4_any_listener = tcp_listener_map_by_address_.find(
+            Network::Address::Ipv4Instance(address->ip()->port()).asStringView());
+        if (ipv4_any_listener == tcp_listener_map_by_address_.end() ||
+            ipv4_any_listener->second->listener_->listener() == nullptr) {
```
Comment (soulxu) [inline source/server/connection_handler_impl.cc:113]: Take care of one more case. There could be one "0.0.0.0" listener was stopped, then a "::" with ipv4_compat listener was added, then ensure the ipv6 listener will replace the ipv4 one.

**Comment by soulxu** [comment]
> > But I do a test today on the ipv4-mapped ipv6 address. It is surprising that it has different behavior. We can both listen on `::FFFF:192.168.0.11 and `192.168.0.1`. But all the requests are going to the `192.168.0.1`listener even for ipv6 request. Using`netstat`, I can see envoy is only listening on "192.168.0.1". @lambdai sorry, I didn't find this before, probably I mess with test.
> 
> @lambdai @ggreenway If we are going to reject this from the API, it seems a separated PR. So I filed another issue for this in case this needs a broader discussion #19981

I removed the part of taking care of both ipv4 and ipv4-mapped ipv6 are listening since both linux and windows don't work with it. 

But still keep the part of both "0.0.0.0" and "::" are listening, but I will update if we don't want to support that also.

**Comment by soulxu** [comment]
> > > But I do a test today on the ipv4-mapped ipv6 address. It is surprising that it has different behavior. We can both listen on `::FFFF:192.168.0.11 and `192.168.0.1`. But all the requests are going to the `192.168.0.1`listener even for ipv6 request. Using`netstat`, I can see envoy is only listening on "192.168.0.1". @lambdai sorry, I didn't find this before, probably I mess with test.
> > 
> > 
> > @lambdai @ggreenway If we are going to reject this from the API, it seems a separated PR. So I filed another issue for this in case this needs a broader discussion #19981
> 
> I removed the part of taking care of both ipv4 and ipv4-mapped ipv6 are listening since both linux and windows don't work with it.
> 

Clarify this. Above is about two listeners are set `bind_to_port` as `true`. After a test, using the `original dst`, the kernel only return ipv4 address even request with ipv4-mapped address. So two listeners (ipv4 and ipv4-mapped) with `bind_to_port` as `false`, seems useless also.

**Comment by lambdai** [comment]
@soulxu 
Thanks for the update. Your latest description matches my observation.

In the kernel ::FFFF:192.168.0.11 address requires ipv4 stack.

In this way, envoy should actively reject "::FFFF:192.168.0.11" if 192.168.0.11 listener exists. I think it could be in separate PR

File: source/server/connection_handler_impl.cc [hunk 8]
```diff
@@ -95,6 +95,36 @@ void ConnectionHandlerImpl::addListener(absl::optional<uint64_t> overridden_list
...
+      if (address->ip()->isAnyAddress()) {
+        // Since both "::" with ipv4_compat and "0.0.0.0" can be supported.
+        // If there already one and it isn't shutdown for compatible addr,
+        // then won't insert a new one.
+        auto ipv4_any_address =
+            Network::Address::Ipv4Instance(address->ip()->port()).asStringView();
+        auto ipv4_any_listener = tcp_listener_map_by_address_.find(ipv4_any_address);
+        if (ipv4_any_listener == tcp_listener_map_by_address_.end() ||
+            ipv4_any_listener->second->listener_->listener() == nullptr) {
+          tcp_listener_map_by_address_.insert_or_assign(ipv4_any_address, details);
```
Comment (lambdai) [inline source/server/connection_handler_impl.cc:115]: Can you guard this with the runtime behavior? 

My concern is that the new matching behavior, though correct, will break a lot of existing [::] listener configs

because the new behavior requires **both** the `filter chains` ipv4 set and ipv6 set. I don't think all the control planes are that strong.

CC @howardjohn

**Comment by soulxu** [comment]
> @soulxu Thanks for the update. Your latest description matches my observation.
> 
> In the kernel ::FFFF:192.168.0.11 address requires ipv4 stack.
> 
> In this way, envoy should actively reject "::FFFF:192.168.0.11" if 192.168.0.11 listener exists. I think it could be in separate PR

thanks for the feedback! I will reject them by separated PR, double-check this rejection includes the bind_to_port=false case also, right?

File: source/server/connection_handler_impl.cc [hunk 9]
```diff
@@ -95,6 +95,28 @@ void ConnectionHandlerImpl::addListener(absl::optional<uint64_t> overridden_list
...
+    if (address->type() == Network::Address::Type::Ip &&
+        address->ip()->version() == Network::Address::IpVersion::v6 &&
+        !address->ip()->ipv6()->v6only()) {
+      if (address->ip()->isAnyAddress()) {
+        tcp_listener_map_by_address_.insert_or_assign(
+            Network::Address::Ipv4Instance(address->ip()->port()).asStringView(), details);
+      } else {
+        auto v4_compatible_addr = address->ip()->ipv6()->v4CompatibleAddress();
+        if (!v4_compatible_addr.ok() && !v4_compatible_addr.status().ok()) {
+          throw EnvoyException(fmt::format("Can't get v4 compatible address for {}: {}",
```
[the remark this answers is not in the document]
Comment (soulxu) [reply source/server/connection_handler_impl.cc]: Yea, I already moved to ListenerImpl. I guess this is your old comment which forgets to submit.

File: source/server/connection_handler_impl.cc (hunk 8 above)
Comment (soulxu) [reply source/server/connection_handler_impl.cc:115]: Emm...this is the regression https://github.com/envoyproxy/envoy/issues/18134 we are trying to fix. So...it should be a regression, not a behavior change.

**Comment by lambdai** [comment]
re: bind_to_port

+1 to make the discrepancy as little as possible.

File: source/server/connection_handler_impl.cc (hunk 8 above)
Comment (lambdai) [reply source/server/connection_handler_impl.cc:115]: @soulxu  Make sense!

**Review by lambdai — APPROVED** [review]
LGTM!

**Comment by lambdai** [comment]
CC @ggreenway for the next step

**Comment by rojkov** [comment]
@ggreenway gentle ping

File: envoy/network/address.h [hunk 10]
```diff
@@ -50,6 +55,11 @@ class Ipv6 {
    * @return true if address is Ipv6 and Ipv4 compatibility is disabled, false otherwise
    */
   virtual bool v6only() const PURE;
+
+  /**
+   * @return Ipv4 address from Ipv4-compatible Ipv6 address.
```
Comment (mattklein123) [inline envoy/network/address.h:60]: Presumably this fails if the v6 address is not in the v4 compatible range? Can you make that more clear in the comments?

File: source/common/network/address_impl.cc [hunk 11]
```diff
@@ -233,6 +237,14 @@ std::string Ipv6Instance::Ipv6Helper::makeFriendlyAddress() const {
   ASSERT(str == ptr);
   return ptr;
 }
+StatusOr<InstanceConstSharedPtr> Ipv6Instance::Ipv6Helper::v4CompatibleAddress() const {
+  if (!v6only_ && IN6_IS_ADDR_V4MAPPED(&address_.sin6_addr)) {
+    struct sockaddr_in sin;
+    ipv6ToIpv4CompatibleAddress(&address_, &sin);
+    return Address::InstanceFactory::createInstancePtr<Address::Ipv4Instance>(&sin);
+  }
+  return absl::InvalidArgumentError("It isn't Ipv4-mapped Ipv6 address");
```
Comment (mattklein123) [inline source/common/network/address_impl.cc:246]: Instead of using StatusOr perhaps just return nullptr? I'm not sure the status provides much value here?

File: source/common/network/address_impl.cc [hunk 12]
```diff
@@ -61,16 +73,8 @@ StatusOr<Address::InstanceConstSharedPtr> addressFromSockAddr(const sockaddr_sto
     const struct sockaddr_in6* sin6 = reinterpret_cast<const struct sockaddr_in6*>(&ss);
     ASSERT(AF_INET6 == sin6->sin6_family);
     if (!v6only && IN6_IS_ADDR_V4MAPPED(&sin6->sin6_addr)) {
```
Comment (mattklein123) [inline source/common/network/address_impl.cc:75]: I think you can just call v4CompatibleAddress() here and if null do the other branch?

File: source/common/network/address_impl.cc [hunk 13]
```diff
@@ -233,6 +237,14 @@ std::string Ipv6Instance::Ipv6Helper::makeFriendlyAddress() const {
   ASSERT(str == ptr);
   return ptr;
 }
+StatusOr<InstanceConstSharedPtr> Ipv6Instance::Ipv6Helper::v4CompatibleAddress() const {
```
Comment (mattklein123) [inline source/common/network/address_impl.cc:240]: nit: newline above this line

File: source/common/network/address_impl.cc [hunk 14]
```diff
@@ -260,6 +272,7 @@ Ipv6Instance::Ipv6Instance(const std::string& address, uint32_t port,
   // Just in case address is in a non-canonical format, format from network address.
   ip_.friendly_address_ = ip_.ipv6_.makeFriendlyAddress();
   friendly_name_ = fmt::format("[{}]:{}", ip_.friendly_address_, ip_.port());
+  ip_.ipv6_.v6only_ = v6only;
```
Comment (mattklein123) [inline source/common/network/address_impl.cc:275]: Not your code, but is there any reason this part of the function can't reuse initHelper()? (I didn't look carefully just curious, seems like some duplication.)

File: source/server/connection_handler_impl.cc (hunk 3 above)
Comment (mattklein123) [reply source/server/connection_handler_impl.cc:118]: ENVOY_BUG won't stop in a production build, so I think it might be worth it to do it in this case.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks this makes sense to me. Just some small comments.

/wait

File: envoy/network/address.h (hunk 10 above)
Comment (soulxu) [reply envoy/network/address.h:60]: Yes, will update

File: source/common/network/address_impl.cc (hunk 12 above)
Comment (soulxu) [reply source/common/network/address_impl.cc:75]: Emm...the Instance obj doesn't create yet. We create different Instance obj below these few lines and depend on this check result.

https://github.com/envoyproxy/envoy/pull/19716/files/228cc7e14615516b1397e3501f8dfa66cc5676a1#diff-6925fefb8a60a68e4059b0d4fdbb943c4b3af9fa77df231724cabcc1f1b35f9fL74-L76

File: source/common/network/address_impl.cc (hunk 11 above)
Comment (soulxu) [reply source/common/network/address_impl.cc:246]: yes, agree with you, will update

File: source/server/connection_handler_impl.cc (hunk 3 above)
Comment (soulxu) [reply source/server/connection_handler_impl.cc:118]: I see, that makes sense, thanks!

**Comment by soulxu** [comment]
> Thanks this makes sense to me. Just some small comments.
> 
> /wait

Thanks for the review!

File: source/common/network/address_impl.cc (hunk 14 above)
Comment (mattklein123) [reply source/common/network/address_impl.cc:277]: Sure that's fine. No worries.

File: source/server/connection_handler_impl.cc [hunk 15]
```diff
@@ -115,12 +115,11 @@ void ConnectionHandlerImpl::addListener(absl::optional<uint64_t> overridden_list
...
       } else {
         auto v4_compatible_addr = address->ip()->ipv6()->v4CompatibleAddress();
-        // Remove this check when runtime flag
-        // `envoy.reloadable_features.strict_check_on_ipv4_compat` deprecated.
-        // If this isn't a valid Ipv4-mapped address, then do nothing.
         if (v4_compatible_addr != nullptr) {
           tcp_listener_map_by_address_.insert_or_assign(v4_compatible_addr->asStringView(),
                                                         details);
+        } else {
+          IS_ENVOY_BUG("If the Ipv6 address isn't v6only, it supposed to be Ipv4-mapped");
```
[the remark this answers is not in the document]
Comment (soulxu) [reply source/server/connection_handler_impl.cc:122]: Yes, config load will block it once runtime flag gone. 
https://github.com/envoyproxy/envoy/pull/19716/files#diff-b0d5e1a1317df8e22a556ee74d6f728379c5f85ce640a9404acc14bfe8192ad3R356-R357

How a about a warning near the exception. And the warning will gone with runtime flag in the future.

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Comment by moderation** [comment]
@soulxu  I'm having trouble with one of my configs now.
```json
                 "address": {
                     "socket_address": {
                         "address": "::0",
                         "ipv4_compat": true,
                         "port_value": 443
                     }
                 },
```
errors with
```
[2022-03-03 21:37:30.259][183239][critical][main] [source/server/server.cc:117] error initializing configuration 'sync-front-envoy-v3.json': Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: [::]:443
[2022-03-03 21:37:30.259][183239][info][main] [source/server/server.cc:933] exiting
Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: [::]:443
```
Do I have the config incorrect?

**Comment by soulxu** [comment]
> @soulxu I'm having trouble with one of my configs now.
> 
> ```json
>                  "address": {
>                      "socket_address": {
>                          "address": "::0",
>                          "ipv4_compat": true,
>                          "port_value": 443
>                      }
>                  },
> ```
> 
> errors with
> 
> ```
> [2022-03-03 21:37:30.259][183239][critical][main] [source/server/server.cc:117] error initializing configuration 'sync-front-envoy-v3.json': Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: [::]:443
> [2022-03-03 21:37:30.259][183239][info][main] [source/server/server.cc:933] exiting
> Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: [::]:443
> ```
> 
> Do I have the config incorrect?

Yes, you have the config correct.

Sorry for I made stupid mistake, I forget to add a check for any address

https://github.com/envoyproxy/envoy/pull/19716/files#diff-b0d5e1a1317df8e22a556ee74d6f728379c5f85ce640a9404acc14bfe8192ad3R351-R354

Even I have an error message for `::` is valid.

**Comment by soulxu** [comment]
> > @soulxu I'm having trouble with one of my configs now.
> > ```json
> >                  "address": {
> >                      "socket_address": {
> >                          "address": "::0",
> >                          "ipv4_compat": true,
> >                          "port_value": 443
> >                      }
> >                  },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > errors with
> > ```
> > [2022-03-03 21:37:30.259][183239][critical][main] [source/server/server.cc:117] error initializing configuration 'sync-front-envoy-v3.json': Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: [::]:443
> > [2022-03-03 21:37:30.259][183239][info][main] [source/server/server.cc:933] exiting
> > Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: [::]:443
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do I have the config incorrect?
> 
> Yes, you have the config correct.
> 
> Sorry for I made stupid mistake, I forget to add a check for any address
> 
> https://github.com/envoyproxy/envoy/pull/19716/files#diff-b0d5e1a1317df8e22a556ee74d6f728379c5f85ce640a9404acc14bfe8192ad3R351-R354
> 
> Even I have an error message for `::` is valid.

@moderation here is the fix https://github.com/envoyproxy/envoy/pull/20214

Sorry again
