### PR TITLE
upstream: init host hc value based on hc value from other priorities

### LINKED ISSUE #3930: Changing priority level of a locality causes requests to fail
*Description*: Changing the priority level of one or more localities in EDS can cause requests to fail due to the fact that endpoint health checking is done per-priority (as was discussed previously in [#3327](https://github.com/envoyproxy/envoy/issues/3327). Essentially priority changes (e.g. swapping the priority of two localities) look to EDS code like endpoints being removed and added, and therefore health checking state is reset.

This issue is probably only visible when using the `drain_connections_on_host_removal: true` setting because connections will not be torn down until health checks fail, although that would mean twice the health checking and twice the connections.

*Repro steps*:
1) Create a cluster with `drain_connections_on_host_removal: true` and cluster load assignment with two localities, one with priority 0 and one with priority 1
2) generate traffic to this cluster. I was able to reproduce with just `while true; do curl $args; sleep .1; done`
3) In control plane, swap the priorities of the two localities.

In the Envoy access log, I see a failed request amidst successful ones: 
```
[2018-07-23T17:38:40.879Z] "GET /whoareyou HTTP/1.1" 200 - 0 17 2 2 "-" "curl/7.29.0" "178d8607-6924-4fe6-aa4b-335fd5b11949" "envoy-test.slug.gns.square" "10.1.3.5:32351"
[2018-07-23T17:38:40.990Z] "GET /whoareyou HTTP/1.1" 200 - 0 17 2 2 "-" "curl/7.29.0" "943ece9e-1daf-4cba-83d6-276ac4f5cd3c" "envoy-test.slug.gns.square" "10.1.3.5:32351"
[2018-07-23T17:38:41.100Z] "GET /whoareyou HTTP/1.1" 503 UH 0 19 0 - "-" "curl/7.29.0" "c3b4afb0-1821-4931-89c0-d8f2a7f3ab1f" "envoy-test.slug.gns.square" "-"
[2018-07-23T17:38:41.207Z] "GET /whoareyou HTTP/1.1" 200 - 0 18 9 9 "-" "curl/7.29.0" "29c1e2c3-1df1-41cb-b7f5-9499caefb6cf" "envoy-test.slug.gns.square" "10.1.3.26:32351"
[2018-07-23T17:38:41.325Z] "GET /whoareyou HTTP/1.1" 200 - 0 19 9 9 "-" "curl/7.29.0" "1e6974b2-37db-4751-8e4d-824cb76da78c" "envoy-test.slug.gns.square" "10.1.3.45:32351"
```
The client sees `no healthy upstream`.

This issue arises from a difference between the way we model cluster membership and the way the code does. The code seems to assume that priorities are static and immutable, whereas we view _localities_ as static and immutable with priorities that may change. My argument for thinking about it this way is that localities make reference to physical regions (region, zone, sub zone) but you might want to reprioritize regional routing, for instance during a disaster recovery exercise or if you add a new region.

Unfortunately this would probably require a pretty significant refactor to fix. With some guidance we might have some bandwidth to look into this.

### PR DESCRIPTION
**Pull request by snowp**
*Description*:
In order to allow hosts to move from one priority to another, this
compares a "new" host against all known hosts in order to determine
whether we've already health checked this host successfully.
The idea is that if we already know that a host is healthy we should
treat it as such when it's added to a different priority. Without this, we'll
fail requests coming in between the EDS update and the moved hosts
being successfully health checked. 

Signed-off-by: Snow Pettersen <snowp@squareup.com>

*Risk Level*: Low, only affects the initial health check value when hosts are added to a priority
*Testing*: Unit test
*Docs Changes*: N/A
*Release Notes*: N/A

Fixes #3930

### CODE REVIEW

**Comment by dio** [comment]
`git commit --allow-empty -m 'trigger build' -s; git push` probably could help 😄.

File: source/common/upstream/eds.cc [hunk 1]
```diff
@@ -61,6 +61,15 @@ void EdsClusterImpl::onConfigUpdate(const ResourceVector& resources, const std::
     throw EnvoyException(fmt::format("Unexpected EDS cluster (expecting {}): {}", cluster_name_,
                                      cluster_load_assignment.cluster_name()));
   }
+
+  HostVector all_current_hosts;
```
Comment (mattklein123) [inline source/common/upstream/eds.cc]: Although I agree with the intention here, I'm concerned about the perf impact of this change, given that we are already having perf issues with this code which is starting to be addressed in https://github.com/envoyproxy/envoy/pull/3941 by @rgs1. 

I think we might need to holistically step back and try to figure out the right path forward for solving this issue while also keeping/improving perf. Concretely, I wonder if we should be keeping an "all hosts" unordered_map keyed by address in parallel to the per-priority vectors? This would allow us to quickly do checks for whether a host already exists in a different priority. 

I will also review https://github.com/envoyproxy/envoy/pull/3941 today and will probably have additional thoughts after I do that so will circle back then.

Comment (snowp) [reply source/common/upstream/eds.cc]: Yeah I thought about the map approach but I wasn't sure about the perf requirements of this code path so I wanted to float the naive solution first.

Thinking out loud a bit: if we kept such a map we could potentially simplify/speed up this code quite a bit by making addresses unique across priorities: instead of iterating over the current hosts we'd just check the map for an existing host with that address. This would make moving a host between priorities no longer require additional code and would eliminate the O(n) scan over existing addresses. A nice thing here is that we could reuse the `Host` from another priority when a host moves, saving us some heap allocations.

Alternatively if we want to maintain the current behavior of allowing duplicate addresses across priorities: we could maintain two maps `std::unordered_map<AddressPtr, Host>` and `std::unordered_map<std::pair<AddressPtr, Integer>, Host>` where one would let us look up hosts from any priority (for the "all hosts" check) and the other would let us look up hosts within the same priority. Essentially this transforms the code in my PR to two map lookups instead of two array scans per priority. 

Unclear to me whether the host uniqueness only within priority invariant is intentional or just a result of the implementation, so not sure how important it is to maintain.

Comment (mattklein123) [reply source/common/upstream/eds.cc]: > Unclear to me whether the host uniqueness only within priority invariant is intentional or just a result of the implementation, so not sure how important it is to maintain.

I actually don't know if this was intentional or not. I feel like it was but I'm not sure. IMO it would be great to simplify it if we can. @mpuncel @htuch @alyssawilk @zuercher do you remember the history here? I don't.

Comment (mpuncel) [reply source/common/upstream/eds.cc]: I don't have historical context on the code, but that plan sounds reasonable. I can't think of a reason you'd want multiple endpoints with the same address in the same cluster since there is proper support for load balancing weight.

**Comment by snowp** [comment]
Updated this to maintain a map of address -> host instead of constructing a list on each config update. PTAL

File: source/common/upstream/upstream_impl.cc [hunk 2]
```diff
@@ -835,100 +837,88 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
...
   }
 
+
+  // Do a single pass over the current_hosts and remove any that were added to the map in the
+  // previous loop
+  current_hosts.erase(std::remove_if(current_hosts.begin(), current_hosts.end(), [&updated_hosts](auto host) { 
+      return updated_hosts.count(host->address()->asString()); 
+      }), current_hosts.end());
+
+  // Do a single pass over the current_hosts and remove any that were added to the map in the
```
Comment (rgs1) [inline source/common/upstream/upstream_impl.cc]: copy/pasta?

File: source/common/upstream/eds.h [hunk 3]
```diff
@@ -41,7 +41,7 @@ class EdsClusterImpl : public BaseDynamicClusterImpl,
                               LocalityWeightsMap& locality_weights_map,
                               LocalityWeightsMap& new_locality_weights_map,
                               PriorityStateManager& priority_state_manager,
-                              const HostVector& all_hosts);
+                              std::unordered_map<std::string, HostSharedPtr>& updated_hosts);
```
Comment (rgs1) [inline source/common/upstream/eds.h]: the new param name (`updated_hosts`) doesn't match the definition's

File: source/common/upstream/eds.cc [hunk 4]
```diff
@@ -116,10 +121,10 @@ void EdsClusterImpl::onConfigUpdate(const ResourceVector& resources, const std::
...
 }
 
-bool EdsClusterImpl::updateHostsPerLocality(const uint32_t priority, const HostVector& new_hosts,
-                                            LocalityWeightsMap& locality_weights_map,
-                                            LocalityWeightsMap& new_locality_weights_map,
-                                            PriorityStateManager& priority_state_manager) {
+bool EdsClusterImpl::updateHostsPerLocality(
+    const uint32_t priority, const HostVector& new_hosts, LocalityWeightsMap& locality_weights_map,
+    LocalityWeightsMap& new_locality_weights_map, PriorityStateManager& priority_state_manager,
+    std::unordered_map<std::string, HostSharedPtr>& new_all_hosts) {
```
Comment (rgs1) [inline source/common/upstream/eds.cc]: `new_all_hosts` is a bit confusing here, was this meant to be `updated_hosts`?

File: source/common/upstream/eds.cc [hunk 5]
```diff
@@ -133,14 +138,17 @@ bool EdsClusterImpl::updateHostsPerLocality(const uint32_t priority, const HostV
   // out of the locality scheduler, we discover their new weights. We don't currently have a shared
   // object for locality weights that we can update here, we should add something like this to
   // improve performance and scalability of locality weight updates.
-  if (updateDynamicHostList(new_hosts, *current_hosts_copy, hosts_added, hosts_removed) ||
+
+  if (updateDynamicHostList(new_hosts, *current_hosts_copy, hosts_added, hosts_removed,
+                            new_all_hosts, all_hosts_) ||
```
Comment (rgs1) [inline source/common/upstream/eds.cc]: hmm why pass `all_hosts_` as a param given it's a member of `BaseDynamicClusterImpl` (so `updateDynamicHostList()` has access to it already)?

File: source/common/upstream/eds.h [hunk 6]
```diff
@@ -40,7 +40,8 @@ class EdsClusterImpl : public BaseDynamicClusterImpl,
   bool updateHostsPerLocality(const uint32_t priority, const HostVector& new_hosts,
                               LocalityWeightsMap& locality_weights_map,
                               LocalityWeightsMap& new_locality_weights_map,
-                              PriorityStateManager& priority_state_manager);
+                              PriorityStateManager& priority_state_manager,
+                              std::unordered_map<std::string, HostSharedPtr>& updated_hosts);
```
Comment (rgs1) [inline source/common/upstream/eds.h]: noted before, doesn't match the definition's param name.

File: source/common/upstream/upstream_impl.cc [hunk 7]
```diff
@@ -834,80 +834,87 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
   // https://github.com/envoyproxy/envoy/issues/2874). We also check for duplicates here. It's
   // possible for DNS to return the same address multiple times, and a bad SDS implementation could
   // do the same thing.
-  std::unordered_set<std::string> host_addresses;
+
+  // Keep track of hosts we've seen during this pass so we can remove it from the
+  // list of current (i.e. existing hosts from this priority)
```
Comment (rgs1) [inline source/common/upstream/upstream_impl.cc]: nit: most (all?) envoy comments are fully formed sentences (e.g.: finish them with a period, etc).

File: source/common/upstream/eds.cc (hunk 4 above)
Comment (snowp) [reply source/common/upstream/eds.cc]: yeah names went through a few iterations, will change

File: source/common/upstream/eds.cc (hunk 5 above)
Comment (snowp) [reply source/common/upstream/eds.cc]: good point! i'll update

File: source/common/upstream/upstream_impl.cc [hunk 8]
```diff
@@ -919,20 +924,25 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
...
         i = current_hosts.erase(i);
       } else {
         i++;
       }
     }
   }
 
+  // Add the remaining hosts into the updated list of all hosts
+  for (auto& host : final_hosts) {
+    updated_hosts[host->address()->asString()] = host;
```
[the remark this answers is not in the document]
Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: yeah you're right, i'll remove

File: source/common/upstream/upstream_impl.cc [hunk 9]
```diff
@@ -1054,15 +1065,19 @@ void StrictDnsClusterImpl::ResolveTarget::startResolve() {
               parent_.info_, dns_address_, Network::Utility::getAddressWithPort(*address, port_),
               lb_endpoint_.metadata(), lb_endpoint_.load_balancing_weight().value(),
               locality_lb_endpoint_.locality(), lb_endpoint_.endpoint().health_check_config()));
+          updated_hosts[address->asString()] = new_hosts.back();
```
[the remark this answers is not in the document]
Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: yeah i agree - i suspect this was left over from a previous iteration and is no longer needed.

File: source/common/upstream/upstream_impl.cc [hunk 10]
```diff
@@ -834,83 +833,89 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
...
+  current_hosts.erase(std::remove_if(current_hosts.begin(), current_hosts.end(),
+                                     [&seen_hosts](auto host) {
+                                       return seen_hosts.count(host->address()->asString());
+                                     }),
+                      current_hosts.end());
+
+  // Do a single pass over the current_hosts and remove any that were added to the map in the
   const bool dont_remove_healthy_hosts =
       health_checker_ != nullptr && !info()->drainConnectionsOnHostRemoval();
-  // If there are removed hosts, check to see if we should only delete if unhealthy.
```
[the remark this answers is not in the document]
Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: oops, i was supposed to remove the other comment you commented on

**Comment by snowp** [comment]
This should be ready for another review

File: source/common/upstream/upstream_impl.h [hunk 11]
```diff
@@ -630,6 +632,7 @@ class StrictDnsClusterImpl : public BaseDynamicClusterImpl {
     uint32_t port_;
     Event::TimerPtr resolve_timer_;
     HostVector hosts_;
+    std::unordered_map<std::string, HostSharedPtr> all_hosts_;
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.h]: Is this used?

File: source/common/upstream/upstream_impl.cc [hunk 12]
```diff
@@ -932,14 +938,14 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
...
   info_->stats().max_host_weight_.set(max_host_weight);
-
   if (!hosts_added.empty() || !current_hosts.empty()) {
     hosts_removed = std::move(current_hosts);
     current_hosts = std::move(final_hosts);
     return true;
   } else {
-    // During the search we moved all of the hosts from hosts_ into final_hosts so just
-    // move them back.
+    // During the search populated final_hosts with either from hosts_ or from all_hosts, so
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.cc]: This sentence is a little hard to read and I think the comment is important. Can you tighten?

File: source/common/upstream/eds.cc [hunk 13]
```diff
@@ -133,14 +138,17 @@ bool EdsClusterImpl::updateHostsPerLocality(const uint32_t priority, const HostV
   // out of the locality scheduler, we discover their new weights. We don't currently have a shared
   // object for locality weights that we can update here, we should add something like this to
   // improve performance and scalability of locality weight updates.
-  if (updateDynamicHostList(new_hosts, *current_hosts_copy, hosts_added, hosts_removed) ||
+
```
Comment (mattklein123) [inline source/common/upstream/eds.cc]: nit: del newline

File: source/common/upstream/upstream_impl.h [hunk 14]
```diff
@@ -503,6 +503,7 @@ class ClusterImplBase : public Cluster, protected Logger::Loggable<Logger::Id::u
 
 protected:
   PrioritySetImpl priority_set_;
+  std::unordered_map<std::string, Upstream::HostSharedPtr> all_hosts_;
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.h]: Is this used in the base class? Should this be part of  `BaseDynamicClusterImpl` ?

File: source/common/upstream/upstream_impl.cc [hunk 15]
```diff
@@ -834,80 +833,86 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
   // https://github.com/envoyproxy/envoy/issues/2874). We also check for duplicates here. It's
   // possible for DNS to return the same address multiple times, and a bad SDS implementation could
   // do the same thing.
-  std::unordered_set<std::string> host_addresses;
+
+  // Keep track of hosts we've seen during this pass so we can remove it from the
+  // list of current (i.e. existing hosts from this priority) hosts.
+  std::unordered_set<std::string> seen_hosts(current_hosts.size());
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.cc]: This is related to the ongoing PR that @dio is working on where we are trying to make this code easier to understand. I actually think this PR is a huge improvement, but can you potentially either add more comments or think of different names for the variables? "seen_hosts" and "current_hosts" is still pretty confusing. In this code I would opt for very long and verbose names and/or lots of comments since it's so hard to understand.

File: source/common/upstream/upstream_impl.cc [hunk 16]
```diff
@@ -834,119 +834,135 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
...
+    } else {
       if (host->weight() > max_host_weight) {
         max_host_weight = host->weight();
       }
 
-      final_hosts.push_back(host);
-      hosts_added.push_back(host);
-
-      // If we are depending on a health checker, we initialize to unhealthy.
+      // If we are depending on a health checker, determine what to initialize the new host
```
Comment (rgs1) [inline source/common/upstream/upstream_impl.cc]: why is this comment changing?

File: source/common/upstream/upstream_impl.h [hunk 17]
```diff
@@ -596,8 +596,24 @@ class BaseDynamicClusterImpl : public ClusterImplBase {
...
+   * Updates the host list of a single priority by reconciling the list of new hosts
+   * with existing hosts.
+   *
+   * @param new_hosts the full lists of hosts in the new configuration.
+   * @param current_priority_hosts the full lists of hosts for the priority to be updated. The list
+   * will be modified to contain the updated list of hosts.
+   * @param hosts_added_to_priority will be populated with hosts added to the priority.
+   * @param hosts_removed_from_priority will be populated with hosts removed from the priority.
+   * @param updated_hosts is used to aggregate the new state of all hosts accross priority, and will
+   * be be updated with the hosts that remain in this priority after the update.
```
Comment (rgs1) [inline source/common/upstream/upstream_impl.h]: nit: be be

File: source/common/upstream/upstream_impl.h [hunk 18]
```diff
@@ -596,8 +596,24 @@ class BaseDynamicClusterImpl : public ClusterImplBase {
...
-                             HostVector& hosts_added, HostVector& hosts_removed);
+  /**
+   * Updates the host list of a single priority by reconciling the list of new hosts
+   * with existing hosts.
+   *
+   * @param new_hosts the full lists of hosts in the new configuration.
+   * @param current_priority_hosts the full lists of hosts for the priority to be updated. The list
+   * will be modified to contain the updated list of hosts.
+   * @param hosts_added_to_priority will be populated with hosts added to the priority.
+   * @param hosts_removed_from_priority will be populated with hosts removed from the priority.
```
Comment (rgs1) [inline source/common/upstream/upstream_impl.h]: doesn't match the param name (`hosts_removed`)

File: source/common/upstream/upstream_impl.cc (hunk 16 above)
Comment (mattklein123) [reply source/common/upstream/upstream_impl.cc]: +1 seems more clear before

File: source/common/upstream/upstream_impl.h [hunk 19]
```diff
@@ -596,8 +596,26 @@ class BaseDynamicClusterImpl : public ClusterImplBase {
...
+   * @param updated_hosts is used to aggregate the new state of all hosts accross priority, and will
+   * be updated with the hosts that remain in this priority after the update.
+   * @return whether the hosts for the priority changed.
+   */
+  bool updateDynamicHostList(const HostVector& new_hosts, HostVector& current_priority_hosts,
+                             HostVector& hosts_added_to_current_priority,
+                             HostVector& hosts_removed_from_current_priority,
+                             std::unordered_map<std::string, HostSharedPtr>& updated_hosts);
+
+  std::unordered_map<std::string, Upstream::HostSharedPtr> all_hosts_;
```
Comment (zuercher) [inline source/common/upstream/upstream_impl.h]: Seems like all_hosts_ is only used by updateDynamicHostList. Perhaps it should be private with an explicit method that takes updated_hosts invoked after all the priorities have been updated? My reasoning is that it makes management of all_hosts_ explicitly the responsibility of BaseDynamicClusterImpl.

Comment (snowp) [reply source/common/upstream/upstream_impl.h]: yeah i like that idea
