### PR TITLE
listener: allow setting only a default filter chain

### LINKED ISSUE #13685: Setting Default filter chain but no common filter chains should not "no filter chains specified" exception
```
void ListenerImpl::validateFilterChains(Network::Socket::Type socket_type) {
  if (config_.filter_chains().empty() && (socket_type == Network::Socket::Type::Stream ||
                                          !udp_listener_factory_->isTransportConnectionless())) {
    // If we got here, this is a tcp listener or connection-oriented udp listener, so ensure there
    // is a filter chain specified
    throw EnvoyException(fmt::format("error adding listener '{}': no filter chains specified",
                                     address_->asString()));
```

Work around: create a never hit filter chain in listener.

Need to add tests coverage also validate that the rest of the code could tolerate empty common filter chain collection.

### PR DESCRIPTION
**Pull request by tbarrella**
I didn't add anything to the release notes because it looks like specifying a default filter chain will be new for the upcoming release and this is fixing a bug

Commit Message:
listener: allow setting only a default filter chain

Signed-off-by: Taylor Barrella <tabarr@google.com>

Additional Description:
Risk Level: Low
Testing: New unit test fails without these changes. I also searched for occurrences of `.filter_chains()` and only found them in `listener_impl.cc` and test files
Docs Changes: N/A
Release Notes:
Fixes #13685

### CODE REVIEW

**Comment by tbarrella** [comment]
cc @lambdai

File: source/server/listener_impl.cc [hunk 1]
```diff
@@ -38,15 +38,24 @@ namespace Envoy {
 namespace Server {
 
 namespace {
+bool anyFilterChain(
+    const envoy::config::listener::v3::Listener& config,
+    std::function<bool(const envoy::config::listener::v3::FilterChain&)> predicate) {
+  if (config.has_default_filter_chain() && predicate(config.default_filter_chain())) {
+    return true;
+  }
+  return std::any_of(config.filter_chains().begin(), config.filter_chains().end(), predicate);
```
Comment (lambdai) [inline source/server/listener_impl.cc:47]: nit: config.has_default_filter_chain() && predicate(config.default_filter_chain()) || std::any_of(config.filter_chains().begin(), config.filter_chains().end(), predicate)

File: source/server/listener_impl.cc [hunk 2]
```diff
@@ -714,8 +730,7 @@ bool ListenerImpl::supportUpdateFilterChain(const envoy::config::listener::v3::L
 
   // See buildProxyProtocolListenerFilter(). Full listener update guarantees at least 1 filter chain
   // at tcp listener.
```
Comment (lambdai) [inline source/server/listener_impl.cc:732]: Could you delete the comment because it doesn't hold anymore?

**Review by lambdai — CHANGES_REQUESTED** [review]
Thanks! Almost there!

Could you fix and merge master to see if coverage passes? I don't think transport socket coverage should be impacted by your change

**Review by lambdai — DISMISSED** [review]
LGTM.
Thank you for the fix!

File: source/server/listener_impl.cc [hunk 3]
```diff
@@ -55,6 +62,12 @@ bool needTlsInspector(const envoy::config::listener::v3::Listener& config) {
                       filter.name() == "envoy.listener.tls_inspector";
              });
 }
+
+bool usesProxyProto(const envoy::config::listener::v3::Listener& config) {
```
Comment (mattklein123) [inline source/server/listener_impl.cc:66]: Doesn't this need to look like `needTlsInspector` with a search through all filter chains? I don't understand how you can only check the default or the first chain? Was this a bug that already existed?

**Review by mattklein123 — COMMENTED** [review]
Thanks for fixing. One question.

/wait-any

File: source/server/listener_impl.cc (hunk 3 above)
Comment (tbarrella) [reply source/server/listener_impl.cc:66]: It seems this is the only file that checks `use_proxy_proto`, so maybe it was a bug/undocumented expectation. Not sure if the previous behavior should be modified in this change. I just realized it might be more conservative to change the condition from `config.has_default_filter_chain()` to `config.filter_chains().empty()` though

Comment (mattklein123) [reply source/server/listener_impl.cc:66]: To me this is a bug as I don't think it makes any sense. If we don't want to fix this now I would make no changes here and then fix it in a follow up?

If we auto inject proxy proto I think all filter chains should probably be asking for it?

Comment (tbarrella) [reply source/server/listener_impl.cc:66]: Makes sense to me. I'm reluctant to change two behaviors in one commit; opened #14085 for now

Comment (lambdai) [reply source/server/listener_impl.cc:66]: @mattklein123 It's an invalid config if partial of the filter chain set use proxy proto while other filter chain don't. We check the first filter chain here for back compatibility.

Comment (mattklein123) [reply source/server/listener_impl.cc:66]: OK where is that checked? If that is already done can you just comment on it here?

Comment (tbarrella) [reply source/server/listener_impl.cc:66]: I didn't see a place where consistency is currently enforced; this seems to be the only code that actually uses `use_proxy_proto`

Comment (lambdai) [reply source/server/listener_impl.cc:66]: There is no enforcement at this moment. And don't add enforcement in this PR.
However, could you add the warning message?

Comment (tbarrella) [reply source/server/listener_impl.cc:66]: I didn't add a printed warning since deprecation should serve that purpose, but I added a comment referencing #14085

Comment (mattklein123) [reply source/server/listener_impl.cc:66]: Given that none of this make any sense, do you want to just revert this part of the PR entirely? Also do we want a warning in a PR or do you want to do this as a follow up? Otherwise this change LGTM and thanks for the discussion here.

/wait-any

Comment (tbarrella) [reply source/server/listener_impl.cc:66]: This is still needed to avoid an indexing error when only a default filter chain is provided. I'd rather leave user-facing warnings etc. as a follow-up (part of the other issue) since this is consistent with existing behavior/isn't a regression or anything

Comment (mattklein123) [reply source/server/listener_impl.cc:66]: OK fair enough. If you can fix all of ^ as a follow up that would be appreciated.

**Review by mattklein123 — APPROVED** [review]
Thanks!
