### PR TITLE
filter chain manager/tls: comparing the DNS name as case insensitive 

### LINKED ISSUE #6199: SSL handshake is case-sensitive
*Title*: *SSL handshake is case-sensitive*

*Description*:
For a wildcard cert `*.bar.com`, requests to `foo.bar.com` work but fail with `Foo.bar.com`, `FOO.bar.com` and the like.

I don't have an endpoint you can hit. I "fixed" this by adding

```std::transform(server_name_.begin(), server_name_.end(), server_name_.begin(), ::tolower);```

to [`ConnectionSocketImpl::setRequestedServerName`](https://github.com/envoyproxy/envoy/blob/v1.8.0/source/common/network/listen_socket_impl.h#L115-L117) but I'm not so sure I didn't break something else.

*Repro steps*:

Working request
```
$ curl -vvv https://foo.bar.com
*   Trying 123.123.123...
* TCP_NODELAY set
* Connected to foo.bar.com (123.123.123) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.bar.com
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> GET / HTTP/1.1
> Host: foo.bar.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/json;charset=UTF-8
< content-length: 18
< date: Wed, 06 Mar 2019 21:26:33 GMT
< x-envoy-upstream-service-time: 15
< server: envoy
<
* Connection #0 to host foo.bar.com left intact
{"message":"pong"}%
```

Failing request
```
$ curl -vvv https://Foo.bar.com
*   Trying 123.123.123.123...
* TCP_NODELAY set
* Connected to Foo.bar.com (123.123.123.123) port 443 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
```

*Admin and Stats Output*:
N/A

*Config*:
The endpoint was configured dynamically with Contour. I can rebuild my cluster and grab the relevant sections of config if it's needed but I think this is easily reproducible.

*Logs*:
The key logs that helped me track this down were
```
[2019-03-06 21:26:31.523][43][debug][filter] source/extensions/filters/listener/tls_inspector/tls_inspector.cc:73] tls inspector: new connection accepted
[2019-03-06 21:26:31.528][43][debug][filter] source/extensions/filters/listener/tls_inspector/tls_inspector.cc:126] tls:onServerName(), requestedServerName: Foo.bar.com
[2019-03-06 21:26:31.528][43][debug][main] source/server/connection_handler_impl.cc:193] closing connection: no matching filter chain found
```

*Call Stack*:
N/A

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: filter chain manager/tls: comparing the DNS name as case insensitive
Additional Description:
Currently, the comparing of DNS name with filter chain matching and SANs is case sensitive.
This PR aims to compare them as case insensitive.

Risk Level: medium
Testing: unit tests added
Docs Changes: n/a
Release Notes: note bug fixes
Platform Specific Features: n/a
Fixes #6199

### CODE REVIEW

File: source/common/upstream/cluster_manager_impl.cc [hunk 1]
```diff
@@ -681,38 +681,40 @@ void ClusterManagerImpl::clusterWarmingToActive(const std::string& cluster_name)
 
 bool ClusterManagerImpl::removeCluster(const std::string& cluster_name) {
   bool removed = false;
-  auto existing_active_cluster = active_clusters_.find(cluster_name);
+  std::string lower_cluster_name = absl::AsciiStrToLower(cluster_name);
```
Comment (asraa) [inline source/common/upstream/cluster_manager_impl.cc:684]: can this be const?

Comment (soulxu) [reply source/common/upstream/cluster_manager_impl.cc:684]: Yes, I will update, thanks!

**Review by PiotrSikora — CHANGES_REQUESTED** [review]
I think this doesn't cover the case when:
1. Filter chain match configuration supplies upper-case name,
2. TLS validation context supplies upper-case name in SAN matchers,
3. Certificate contains subject name with upper-case name (I'm not entirely sure if that's legal in practice), and the TLS validation context contains lower-case name.

It's possible that some of those cases already work, but I don't believe we have tests for them.

**Comment by soulxu** [comment]
@PiotrSikora thanks for your review!

I update the PR to address your comment. The fix includes three commits.

The first commit is for SNI matching the cluster name.

> I think this doesn't cover the case when:
> 
> 1. Filter chain match configuration supplies upper-case name,

The second commit is for SNI matching the filter chain

> 2. TLS validation context supplies upper-case name in SAN matchers,
> 3. Certificate contains subject name with upper-case name (I'm not entirely sure if that's legal in practice), and the TLS validation context contains lower-case name.
> 

The last commit is for SAN matchers, it includes the two cases you mentioned above.

Appreciate your help again :)

File: source/server/filter_chain_manager_impl.cc [hunk 2]
```diff
@@ -466,7 +468,7 @@ const Network::FilterChain* FilterChainManagerImpl::findFilterChainForDestinatio
 
 const Network::FilterChain* FilterChainManagerImpl::findFilterChainForServerName(
     const ServerNamesMap& server_names_map, const Network::ConnectionSocket& socket) const {
-  const std::string server_name(socket.requestedServerName());
+  const std::string server_name(absl::AsciiStrToLower(socket.requestedServerName()));
```
Comment (PiotrSikora) [inline source/server/filter_chain_manager_impl.cc:471]: Nit: `requestedServerName()` should always return lower-case value.

Consider also fixing `setRequestedServerName()` to always lower-case the new value.

**Review by PiotrSikora — APPROVED** [review]
LGTM, thanks!

File: source/server/filter_chain_manager_impl.cc (hunk 2 above)
Comment (soulxu) [reply source/server/filter_chain_manager_impl.cc:471]: I remove the change for `requestedServerName()` in this update, since I think we already cover all the cases, and it is hard to convert everything to lower case in the code base, so I choose to make the change more focused on the place need the lower case. But I'm ok both way, let me know your thought, I can update it.

Comment (PiotrSikora) [reply source/server/filter_chain_manager_impl.cc:471]: I think having it in `setRequestedServerName()` would be more future-proof, otherwise new code using `requestedServerName()` needs to know about the need to lower-case the value.

Comment (soulxu) [reply source/server/filter_chain_manager_impl.cc:471]: got it, that makes sense, let me update it, thanks again!

Comment (PiotrSikora) [reply source/server/filter_chain_manager_impl.cc:471]: There is one more `setRequestedServerName()` in `source/common/stream_info/stream_info_impl.h`... but to be honest, I'm not sure if it's relevant here.

**Review by PiotrSikora — DISMISSED** [review]
Thanks!

File: source/common/network/listen_socket_impl.h [hunk 3]
```diff
@@ -116,7 +116,8 @@ class ConnectionSocketImpl : public SocketImpl, public ConnectionSocket {
   }
 
   void setRequestedServerName(absl::string_view server_name) override {
-    server_name_ = std::string(server_name);
+    // Always keep the server_name_ as lower case.
+    server_name_ = absl::AsciiStrToLower(std::string(server_name));
```
Comment (ggreenway) [inline source/common/network/listen_socket_impl.h:120]: I think the overload of `absl::AsciiStrToLower` called here takes a `string_view` not a `std::string`, so the `std::string` conversion here should be removed.

**Review by ggreenway — CHANGES_REQUESTED** [review]
The changes to lower-case all the TLS/SNI values make sense, but I'm not sure we want to change the case of all the cluster names. Cluster names are sometimes matched to SNI values, but in many configurations they aren't related to hostnames at all, and this could have issues for stats, xDS, maybe other things. @htuch is it valid right now to have two cluster names that differ only in the ascii-case of the name? @jmarantz do you know if anybody treats stats as case-sensitive, or if we emit stats in mixed-case?

File: source/common/network/listen_socket_impl.h (hunk 3 above)
Comment (soulxu) [reply source/common/network/listen_socket_impl.h:120]: got it, will update

File: source/server/filter_chain_manager_impl.cc (hunk 2 above)
Comment (soulxu) [reply source/server/filter_chain_manager_impl.cc:471]: Looks like the stream info's requested server name is getting from the SNI's server name, since we already convert the SNI name as lower case, so it should be ok.

https://github.com/envoyproxy/envoy/blob/cfe0391ce24f7d11b3b125078ab77f6f4142e4ac/source/common/http/conn_manager_impl.cc#L663

https://github.com/envoyproxy/envoy/blob/cfe0391ce24f7d11b3b125078ab77f6f4142e4ac/source/common/tcp_proxy/tcp_proxy.cc#L639

**Comment by jmarantz** [comment]
There is no case-folding in the core stats system, so "Foo" and "foo" are distinct. There may be case-folding in the sinks.

I would not recommend case-folding going *into* the stats system. I would guess that would break something somewhere.

File: include/envoy/upstream/cluster_manager.h [hunk 4]
```diff
@@ -174,11 +174,12 @@ class ClusterManager {
     }
 
     ClusterConstOptRef getCluster(absl::string_view cluster) {
-      auto active_cluster = active_clusters_.find(cluster);
+      auto cluster_name = absl::AsciiStrToLower(cluster);
```
Comment (htuch) [inline include/envoy/upstream/cluster_manager.h:177]: I think this can technically be considered a breaking API change, to @ggreenway point this would conflate two valid distinct clusters `FooX` and `foox`.  Which situation do we expect cluster names to be DNS names that need normalizing?

This is tangentially related to recent discussion with @envoyproxy/api-shepherds on how to normalize names for lookup with `xdstp://`, we are planning on a more extensive `ClusterHandle` approach.

I would remove this normalization unless there is a good rationale.

**Comment by soulxu** [comment]
@ggreenway @jmarantz , thanks for your review! 

Another way is we only use low-case for the map inside cluster manager. Then it will ensure we search cluster with case-insensitive way, but still keep the original cluster name. But yes, we need to ensure the anyone depends on 'two cluster names that differ only in the ascii-case of the name' yet. 

Otherwise, I can drop the cluster manager commit, then just focus on other part fixing.

**Comment by htuch** [comment]
@soulxu can you elaborate further on why we need _any_ cluster name normalization? How does this relate to the DNS normalization?

**Comment by soulxu** [comment]
> @soulxu can you elaborate further on why we need _any_ cluster name normalization? How does this relate to the DNS normalization?

The only case is using SNI to matching the cluster, I guess sni_cluster extension is the only case using that. https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_cluster_filter#config-network-filters-sni-cluster

**Comment by htuch** [comment]
@soulxu I think in this case we should do the lower case normalization prior to lookup and expect cluster names to be lower case. One other option, consistent with where we're heading, is to have a special prefix for cluster names that should be normalized as per DNS, e.g. `dns://foo.bar.com`.

**Comment by soulxu** [comment]
> @soulxu I think in this case we should do the lower case normalization prior to lookup and expect cluster names to be lower case. 
Yes, with this commit 
https://github.com/envoyproxy/envoy/pull/14793/commits/ea5643b490c1bd32fee0a64f1c89770be4ee3405, then we implement that.

> One other option, consistent with where we're heading, is to have a special prefix for cluster names that should be normalized as per DNS, e.g. `dns://foo.bar.com`.

I'm cool with this also, and this won't break the existing API. I guess this depends on how many people using sni_cluster extension, then if there are still a lot of people using that, this option looks likes useful for the user. And if we choose this option, do you think I should separate this change to another PR? then this PR just focus on TLS part.

**Comment by htuch** [comment]
>  And if we choose this option, do you think I should separate this change to another PR? then this PR just focus on TLS part.

Yes, definitely a separate PR, I think we can just focus on TLS here.

**Comment by soulxu** [comment]
> > And if we choose this option, do you think I should separate this change to another PR? then this PR just focus on TLS part.
> 
> Yes, definitely a separate PR, I think we can just focus on TLS here.

Thanks!

**Comment by soulxu** [comment]
Updated the PR with removing the cluster manager change. I will submit another PR to follow @htuch's suggested option to fix the SNI matching cluster manager, and the discussion can be continued in the new PR.

File: source/extensions/transport_sockets/tls/cert_validator/default_validator.cc [hunk 5]
```diff
@@ -293,16 +293,19 @@ bool DefaultCertValidator::verifySubjectAltName(X509* cert,
 
 bool DefaultCertValidator::dnsNameMatch(const absl::string_view dns_name,
                                         const absl::string_view pattern) {
-  if (dns_name == pattern) {
+  std::string lower_case_dns_name = absl::AsciiStrToLower(dns_name);
+  std::string lower_case_pattern = absl::AsciiStrToLower(pattern);
```
Comment (lambdai) [inline source/extensions/transport_sockets/tls/cert_validator/default_validator.cc:297]: const std::string

File: source/server/filter_chain_manager_impl.cc (hunk 2 above)
Comment (lambdai) [reply source/server/filter_chain_manager_impl.cc:471]: It's nice to add ASSERT(absl::AsciiStrToLower(socket.requestedServerName() == socket.requestedServerName()) here.

Theoretically setRequestedServerName can be overridden by any other filter. Let's enforce a to_lower in setRequestedServerName()

File: test/common/network/listen_socket_impl_test.cc [hunk 6]
```diff
@@ -126,6 +126,15 @@ class ListenSocketImplTest : public testing::TestWithParam<Address::IpVersion> {
     EXPECT_GT(socket->addressProvider().localAddress()->ip()->port(), 0U);
     EXPECT_EQ(Type, socket->socketType());
   }
+
+  void testLowerCaseRequestedServerName() {
```
Comment (lambdai) [inline test/common/network/listen_socket_impl_test.cc:130]: This function is not invoked during the test
You probably want something like 
```
TEST_P(ListenSocketImplTestTcp, TestLowerCaseRequestedServerName) {
         Your code here.
}

**Review by lambdai — CHANGES_REQUESTED** [review]
Almost there!

File: source/extensions/transport_sockets/tls/cert_validator/default_validator.cc (hunk 5 above)
Comment (soulxu) [reply source/extensions/transport_sockets/tls/cert_validator/default_validator.cc:297]: got it, thanks!

File: test/common/network/listen_socket_impl_test.cc (hunk 6 above)
Comment (soulxu) [reply test/common/network/listen_socket_impl_test.cc:130]: got it, thanks

File: source/server/filter_chain_manager_impl.cc (hunk 2 above)
Comment (soulxu) [reply source/server/filter_chain_manager_impl.cc:471]: got it, will update

File: test/common/network/listen_socket_impl_test.cc [hunk 7]
```diff
@@ -21,6 +22,15 @@ namespace Envoy {
 namespace Network {
 namespace {
 
+TEST(ConnectionSocketImplTest, LowerCaseRequestedServerName) {
+  absl::string_view serverName("www.EXAMPLE.com");
+  std::string expectedServerName("www.example.com");
```
Comment (lambdai) [inline test/common/network/listen_socket_impl_test.cc:27]: nit: absl::string_view expectedServerName or const std::string

Not a big deal in test code :)

**Review by lambdai — APPROVED** [review]
LGTM 

@soulxu Please don't force push in the future. Always merge. I remember I had other comments they are gone because of the force push.

**Comment by soulxu** [comment]
> LGTM
> 
> @soulxu Please don't force push in the future. Always merge. I remember I had other comments they are gone because of the force push.

got it, thanks!

**Comment by ggreenway** [comment]
> > LGTM
> > @soulxu Please don't force push in the future. Always merge. I remember I had other comments they are gone because of the force push.
> 
> got it, thanks!

Something in your workflow is off; you force-pushed right after leaving that comment.

**Review by ggreenway — APPROVED** [review]
LGTM

/retest

**Comment by soulxu** [comment]
> > > LGTM
> > > @soulxu Please don't force push in the future. Always merge. I remember I had other comments they are gone because of the force push.
> > 
> > 
> > got it, thanks!
> 
> Something in your workflow is off; you force-pushed right after leaving that comment.

Yea, I debug the CI failed problem, then I missed force push again, sorry about that. Thanks for your review :)

**Review by ggreenway — CHANGES_REQUESTED** [review]
Apologies, I forgot to note ealier that this needs a release note entry

**Comment by soulxu** [comment]
> Apologies, I forgot to note ealier that this needs a release note entry

No worries, I added the release note, appreciate the review!

**Review by ggreenway — APPROVED** [review]

**Comment by soulxu** [comment]
@ggreenway thanks!
