### PR TITLE
Listener: reset the file event when destroying listener filters

### LINKED ISSUE #16951: envoy still try to create file event twice on the same fd when continue_on_listener_filters_timeout is true
*Title*: envoy still create file event twice on the same fd when continue_on_listener_filters_timeout is true

*Description*:
This is a regression of the issue https://github.com/istio/istio/issues/18229 and it is fixed previously by https://github.com/envoyproxy/envoy/pull/8922

https://github.com/envoyproxy/envoy/pull/8922 clean the listener filter before create new connection. It works at the time tls inspect filter using `FileEventImpl` to create event directly.

But now, the tls inspect and http inspect filter are changed to use the socket's ioHandle::initializeFileEvent(). But the owning of socket isn't the filter, so the event won't be clean after the filter cleaned.
https://github.com/envoyproxy/envoy/blob/b164962eb367e054df7fd563acce59663b16dd86/source/extensions/filters/listener/tls_inspector/tls_inspector.cc#L93

After the new connection adds event to the fd, the assertion will be triggered.
https://github.com/envoyproxy/envoy/blob/b164962eb367e054df7fd563acce59663b16dd86/source/common/network/io_socket_handle_impl.cc#L638

In the production build, it should reproduce the issue https://github.com/istio/istio/issues/18229, since the new FileEventImpl is created before the old one destructed.
https://github.com/envoyproxy/envoy/blob/b164962eb367e054df7fd563acce59663b16dd86/source/common/network/io_socket_handle_impl.cc#L640

*Repro steps*:
1. startup envoy with listener's continue_on_listener_filters_timeout set as true. also enable the tls inspect filter
2. client connect to the envoy, but didn't set the full tls hello message in the frist write
3. waiting the listener filter timeout

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: Listener: reset the file event before initializing new one
Additional Description:
The listener filter may add event on the new socket, but it won't cleanup the event.
If `continue_on_listener_filters_timeout` is set, the new connection may add same event
to the socket. So reset the file event before initialize new one.
Risk Level: low
Testing: integration test added
Docs Changes: n/a
Release Notes: n/a
Fixes #16951

Signed-off-by: He Jie Xu <hejie.xu@intel.com>

### CODE REVIEW

**Comment by Chucky-ux** [comment]
Delete

File: source/common/network/io_socket_handle_impl.cc [hunk 1]
```diff
@@ -635,8 +635,11 @@ Address::InstanceConstSharedPtr IoSocketHandleImpl::peerAddress() {
 
 void IoSocketHandleImpl::initializeFileEvent(Event::Dispatcher& dispatcher, Event::FileReadyCb cb,
                                              Event::FileTriggerType trigger, uint32_t events) {
-  ASSERT(file_event_ == nullptr, "Attempting to initialize two `file_event_` for the same "
-                                 "file descriptor. This is not allowed.");
+  // Reset the file_event_ for the case of initialize two `file_event_` for
+  // the same file descriptor. This is not allowed.
+  if (file_event_ != nullptr) {
+    file_event_.reset();
+  }
```
Comment (soulxu) [inline source/common/network/io_socket_handle_impl.cc:642]: Another fix will be to reset the event in the destructor of the listener filter, but that would require every listener filter to take care of it.

Also, this fix doesn't prevent initiate two instances of FileEventImpl directly, it is how the bug https://github.com/istio/istio/issues/18229 was trigger initially, but I searched the code, we don't have that case anymore. Since we create FileEventImpl only through the dispatcher. So maybe we can move the constructor of FileEventImpl as protected, and only dispatcher can instantiate it.

Comment (antoniovicente) [reply source/common/network/io_socket_handle_impl.cc:642]: I have concerns about file_event_ referring to a Event::FileReadyCb cb that points to a deleted listener filter.  Given that, I think it is important that we find a way to reset the file event when the listen filter is destroyed, rather than hack it this way.  Who owns the listener IoSocketHandleImpl?

I think that the 2 listener filters that seem to be calling initializeFileEvent are tls_inspector and http_inspector.  Is the issue here that those filters need events during some parts of the connection lifetime, but eventually need to remove themselves from accepting events directly?

It would be useful to know more about when this ASSERT fails, and possibly change this from ASSERT to RELEASE_ASSERT.  Do the added tests cause this ASSERT to be hit?

**Review by antoniovicente — COMMENTED** [review]
Thanks for the fix.  It would be useful to know more about what is going on here in order to evaluate if ignoring the file event re-registration is the right fix.

File: source/common/network/io_socket_handle_impl.cc (hunk 1 above)
Comment (antoniovicente) [reply source/common/network/io_socket_handle_impl.cc:642]: One option that could be considered for cases like this one is to add a RAII object that can be used for filters like this one to hold the file_event registration in cases where the filter does own a the file event registration.

Also, I think that falling back to the default filter chain in cases where tls inspector times out may not be the right thing.  If the client is not sending a handshake within a reasonable time, the proxy should just close the connection.

Comment (florincoras) [reply source/common/network/io_socket_handle_impl.cc:642]: If this happens only on continue_on_listener_filters_timeout_, would resetting the file_event in ActiveTcpSocket::onTimeout() solve the issue?

Comment (antoniovicente) [reply source/common/network/io_socket_handle_impl.cc:642]: No, because ActiveTcpSocket doesn't know who owns the relevant connection socket.  The filters need to properly manage the file events they own.

Comment (florincoras) [reply source/common/network/io_socket_handle_impl.cc:642]: Agreed! That would be ideal.

Comment (soulxu) [reply source/common/network/io_socket_handle_impl.cc:642]: > I have concerns about file_event_ referring to a Event::FileReadyCb cb that points to a deleted listener filter. Given that, I think it is important that we find a way to reset the file event when the listen filter is destroyed, rather than hack it this way. Who owns the listener IoSocketHandleImpl?

Indeed, FileReadyCb is pointed to a deleted listener filter, I missed that. IoSocketHandleImpl is owned by AcceptedSocketImpl which is owned by ActiveTcpSocket, then passes the ownership to the ActiveTcpConnection.

> I think that the 2 listener filters that seem to be calling initializeFileEvent are tls_inspector and http_inspector. Is the issue here that those filters need events during some parts of the connection lifetime, but eventually need to remove themselves from accepting events directly?

not sure I understand your question. Those filters need to ready some data from the socket, like TLS inspect need to read the tls hello message. Those added events will be removed after the new FileEventImpl is created. https://github.com/envoyproxy/envoy/blob/b164962eb367e054df7fd563acce59663b16dd86/source/common/network/io_socket_handle_impl.cc#L640

And it will trigger the same issue https://github.com/envoyproxy/envoy/pull/8922 fixed.

> 
> It would be useful to know more about when this ASSERT fails, and possibly change this from ASSERT to RELEASE_ASSERT. Do the added tests cause this ASSERT to be hit?

I added an integration test for this case https://github.com/envoyproxy/envoy/pull/16952/files#diff-11652aeb508dd4b3ac24783eb9a5d38d7e33e42791cbce382b0d5b269797e9f1R146
If you removed the fix from this PR, that integration test will fail at the ASSERTION.

Comment (antoniovicente) [reply source/common/network/io_socket_handle_impl.cc:642]: I looked at the code of TLS inspector and I think I understand the issue better.  I have concerns about the TLS inspector filter effectively removing itself from the filter chain on timeout.  This behavior allows for trivial bypass of the TLS inspector and HTTP inspector functionality by waiting for a few seconds before sending the rest of the client hello.  Are these inspectors purely debug hooks or are they meant to provide specific functionality or security properties?

Thanks for confirming that your new tests repo the ASSERT failure.  I suggest we try to fix this issue by calling resetFileEvent in TLS inspector and HTTP inspector destructors if the filters haven't invoked their respective done callbacks.

Comment (soulxu) [reply source/common/network/io_socket_handle_impl.cc:642]: > I looked at the code of TLS inspector and I think I understand the issue better. I have concerns about the TLS inspector filter effectively removing itself from the filter chain on timeout. This behavior allows for trivial bypass of the TLS inspector and HTTP inspector functionality by waiting for a few seconds before sending the rest of the client hello. Are these inspectors purely debug hooks or are they meant to provide specific functionality or security properties?

Those inspectors are meant to provider specific functionality, for example, tls inspect get the SNI for later the filter chain matching.
> 
> Thanks for confirming that your new tests repo the ASSERT failure. I suggest we try to fix this issue by calling resetFileEvent in TLS inspector and HTTP inspector destructors if the filters haven't invoked their respective done callbacks.

got it, thanks for the review!

Comment (antoniovicente) [reply source/common/network/io_socket_handle_impl.cc:642]: > > I looked at the code of TLS inspector and I think I understand the issue better. I have concerns about the TLS inspector filter effectively removing itself from the filter chain on timeout. This behavior allows for trivial bypass of the TLS inspector and HTTP inspector functionality by waiting for a few seconds before sending the rest of the client hello. Are these inspectors purely debug hooks or are they meant to provide specific functionality or security properties?
> 
> Those inspectors are meant to provider specific functionality, for example, tls inspect get the SNI for later the filter chain matching.

This seems problematic since the SNI extraction logic of the filter is trivially bypass-able by waiting for a timeout condition before sening the SNI.  Is there potential for that to cause any security concerns?

> > Thanks for confirming that your new tests repo the ASSERT failure. I suggest we try to fix this issue by calling resetFileEvent in TLS inspector and HTTP inspector destructors if the filters haven't invoked their respective done callbacks.
> 
> got it, thanks for the review!

Comment (soulxu) [reply source/common/network/io_socket_handle_impl.cc:642]: > > Those inspectors are meant to provider specific functionality, for example, tls inspect get the SNI for later the filter chain matching.
> 
> This seems problematic since the SNI extraction logic of the filter is trivially bypass-able by waiting for a timeout condition before sening the SNI. Is there potential for that to cause any security concerns?
> 

I searched that, the Istio is using that https://github.com/istio/istio/blob/f38465f8f5c1edd944ed7776c1253ffa2d9768b2/pilot/pkg/networking/core/v1alpha3/listener_builder.go#L213

the `protocolDetectionTimeout`'s doc probably explains the reason https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/

so it should be for a listener accepts both tls and server-first protocol connection.

File: source/extensions/filters/listener/http_inspector/http_inspector.h [hunk 2]
```diff
@@ -66,6 +66,11 @@ using ConfigSharedPtr = std::shared_ptr<Config>;
 class Filter : public Network::ListenerFilter, Logger::Loggable<Logger::Id::filter> {
 public:
   Filter(const ConfigSharedPtr config);
+  ~Filter() override {
+    if (cb_) {
+      cb_->socket().ioHandle().resetFileEvents();
```
[the remark this answers is not in the document]
Comment (soulxu) [reply source/extensions/filters/listener/http_inspector/http_inspector.h:71]: Yes, it could be owned by other filter. Like we enable tls inspect and http inspect at same time, tls inspect successed, then http inspect timeout, both filter will reset the file event in the destruction. But it should be fine since the reset can be execute multiple times.

File: test/extensions/filters/listener/http_inspector/http_inspector_test.cc [hunk 3]
```diff
@@ -31,7 +31,11 @@ class HttpInspectorTest : public testing::Test {
   HttpInspectorTest()
       : cfg_(std::make_shared<Config>(store_)),
         io_handle_(std::make_unique<Network::IoSocketHandleImpl>(42)) {}
-  ~HttpInspectorTest() override { io_handle_->close(); }
+  ~HttpInspectorTest() override {
+    io_handle_->close();
+    filter_.reset();
+    EXPECT_EQ(false, io_handle_->isFileEventInitialized());
```
[the remark this answers is not in the document]
Comment (soulxu) [reply test/extensions/filters/listener/http_inspector/http_inspector_test.cc:37]: sorry, I'm not sure I understand your comment. do you mean try to find a way to initializeFileEvent again, then using the ASSERT test the case?

[the remark this answers is not in the document]
Comment (soulxu) [reply test/extensions/filters/listener/http_inspector/http_inspector_test.cc]: ha, I think I got what you mean, already update the PR.

File: source/extensions/filters/listener/http_inspector/http_inspector.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (antoniovicente) [reply source/extensions/filters/listener/http_inspector/http_inspector.h:71]: The question is wherever a filter that is not the TLS inspector nor HTTP inspector could own the file event.  For example, the network::Connection owned by the http connection manager.

File: source/extensions/filters/listener/proxy_protocol/proxy_protocol.h [hunk 4]
```diff
@@ -118,7 +122,7 @@ class Filter : public Network::ListenerFilter, Logger::Loggable<Logger::Id::filt
   bool parseV2Header(char* buf);
   absl::optional<size_t> lenV2Address(char* buf);
 
-  Network::ListenerFilterCallbacks* cb_{};
+  Network::ListenerFilterCallbacks* cb_{nullptr};
```
Comment (antoniovicente) [inline source/extensions/filters/listener/proxy_protocol/proxy_protocol.h:125]: nit: the original initialization with `{}` is equivalent.  Consider reverting this change.

File: source/extensions/filters/listener/tls_inspector/tls_inspector.h [hunk 5]
```diff
@@ -85,7 +90,7 @@ class Filter : public Network::ListenerFilter, Logger::Loggable<Logger::Id::filt
   void onServername(absl::string_view name);
 
   ConfigSharedPtr config_;
-  Network::ListenerFilterCallbacks* cb_;
+  Network::ListenerFilterCallbacks* cb_{nullptr};
```
Comment (antoniovicente) [inline source/extensions/filters/listener/tls_inspector/tls_inspector.h:93]: See comment in proxy_protocol.h

File: source/server/active_tcp_listener.cc [hunk 6]
```diff
@@ -199,10 +199,8 @@ void ActiveTcpSocket::newConnection() {
     if (socket_->detectedTransportProtocol().empty()) {
       socket_->setDetectedTransportProtocol("raw_buffer");
     }
-    // TODO(lambdai): add integration test
-    // TODO: Address issues in wider scope. See https://github.com/envoyproxy/envoy/issues/8925
-    // Erase accept filter states because accept filters may not get the opportunity to clean up.
-    // Particularly the assigned events need to reset before assigning new events in the follow up.
+    // Clear the listener filter to ensure the file event registered by
+    // listener filter to be removed. reference PR #8922.
```
Comment (antoniovicente) [inline source/server/active_tcp_listener.cc:203]: nit: Please prefer clickable links.  Change `PR #8922` back to `https://github.com/envoyproxy/envoy/issues/8925`

File: test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc [hunk 7]
```diff
@@ -210,6 +212,23 @@ INSTANTIATE_TEST_SUITE_P(IpVersions, ProxyProtocolTest,
                          testing::ValuesIn(TestEnvironment::getIpVersionsForTest()),
                          TestUtility::ipTestParamsToString);
 
+// This test ensures the socket file event was reset after timeout, otherwise
+// the assertion which avoid to create file event duplicated will be triggered.
+TEST_P(ProxyProtocolTest, Timeout) {
+  connect();
+  absl::SleepFor(absl::Seconds(5));
```
Comment (antoniovicente) [inline test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc:219]: Would it be possible to use simulated time instead of sleeping for such a long time?

File: test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc [hunk 8]
```diff
@@ -210,6 +212,23 @@ INSTANTIATE_TEST_SUITE_P(IpVersions, ProxyProtocolTest,
...
+  if (GetParam() == Envoy::Network::Address::IpVersion::v4) {
+    EXPECT_EQ(server_connection_->addressProvider().remoteAddress()->ip()->addressAsString(),
+              "127.0.0.1");
+  } else {
+    EXPECT_EQ(server_connection_->addressProvider().remoteAddress()->ip()->addressAsString(),
+              "::1");
+  }
+
+  disconnect();
+}
```
Comment (antoniovicente) [inline test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc:230]: I'm not seeing any expectations in the test that verify that the timeout was hit and the filter chain was then re-created.  Are there some stats that can be checked in order to verify that this test does as advertised?

File: test/integration/listener_filter_integration_test.cc [hunk 9]
```diff
@@ -98,27 +118,45 @@ class ListenerFilterIntegrationTest : public testing::TestWithParam<Network::Add
...
+TEST_P(ListenerFilterIntegrationTest, ContinueOnListenerTimeout) {
+  setupConnections(/*listener_filter_disabled=*/false, /*expect_connection_open=*/true,
+                   /*ssl_client=*/false);
+  // The length of tls hello message is defined as `TLS_MAX_CLIENT_HELLO = 64 * 1024`
+  // if tls inspect filter doesn't read the max length of hello message data, it
+  // will continue wait. Then the listener filter timeout timer will be triggered.
+  Buffer::OwnedImpl buffer("fake data");
+  client_->write(buffer, false);
+  // the timeout is set as one seconds, sleep 5 to trigger the timeout.
+  absl::SleepFor(absl::Seconds(5));
```
Comment (antoniovicente) [inline test/integration/listener_filter_integration_test.cc:155]: Would it be possible to use simulated time to avoid such a long sleep?

Also, see comments above regarding additional expectations we could add in order to ensure that this test case goes down the expected code paths.

**Review by antoniovicente — COMMENTED** [review]
Looks good.  Just a few nits and requests to tighten test expectations.

/wait

File: source/extensions/filters/listener/http_inspector/http_inspector.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (soulxu) [reply source/extensions/filters/listener/http_inspector/http_inspector.h:71]: I think there is no other filter own the file event. Since this is on the stage of accepting the connection, so the l3/l4 filter doesn't instance yet.

File: source/extensions/filters/listener/proxy_protocol/proxy_protocol.h (hunk 4 above)
Comment (soulxu) [reply source/extensions/filters/listener/proxy_protocol/proxy_protocol.h:125]: got it, thanks

File: source/server/active_tcp_listener.cc (hunk 6 above)
Comment (soulxu) [reply source/server/active_tcp_listener.cc:203]: got it

File: test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc (hunk 7 above)
Comment (soulxu) [reply test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc:219]: emm...this test is using a real dispatcher, so I can't mock it. I feel the whole proxy test is like an integration test, it listens and connects on real loopback.

File: test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc (hunk 8 above)
Comment (soulxu) [reply test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc:230]: yea, let me see how to verfiy that.

File: test/integration/listener_filter_integration_test.cc (hunk 9 above)
Comment (soulxu) [reply test/integration/listener_filter_integration_test.cc:155]: let me see how to simulate time in integration test. If there is way, I should be able fix the proxy filter unittest also.

Comment (soulxu) [reply test/integration/listener_filter_integration_test.cc]: I changed the proxy filter unitest to use `SimulatedTimeSystemHelper`. But for the integration test, I saw the BaseIntegrationTest is using the real time-system. https://github.com/envoyproxy/envoy/blob/f8d8023d3a192fc7e2f2457e892db2a667a8491d/test/integration/base_integration_test.h#L259

so I thought the integration is preferred to run at real timesystem?

**Review by antoniovicente — APPROVED** [review]
Many thanks for this awesome fix with comprehensive testing.  You rock!

**Comment by soulxu** [comment]
@antoniovicente thanks for your review!

**Comment by mattklein123** [comment]
@soulxu @antoniovicente I'm late to the discussion and I see quite a bit of back and forth, but it seems sub-optimal that each listener filter has to include this new stanza to release the file event. Are we going to follow up with some RAII wrapper? Or even better is there some way in which the code that is running the filters (IIRC ActiveTcpConncetion or something like that) could keep track of dealing with this if needed? Apologize if this has already been discussed at length, but a summary might be nice. Thank you.

**Comment by soulxu** [comment]
> @soulxu @antoniovicente I'm late to the discussion and I see quite a bit of back and forth, but it seems sub-optimal that each listener filter has to include this new stanza to release the file event. Are we going to follow up with some RAII wrapper? Or even better is there some way in which the code that is running the filters (IIRC ActiveTcpConncetion or something like that) could keep track of dealing with this if needed? Apologize if this has already been discussed at length, but a summary might be nice. Thank you.

Initially, I reset the file event before initializing a new one inside ioHandle::initializeFileEvent(), then @antoniovicente has great point, that is file_event reset late after the accept filter destructed, which means file_event's callback still have reference to the accept filter at that time. So I changed back to reset file_event inside filter's destruction. But I think I did miss that we can reset the file event just before we clear the accept filters. https://github.com/envoyproxy/envoy/blob/5a8f89a90ab7c18f336f7d6b89686ca878fde3c4/source/server/active_tcp_listener.cc#L204

so can invoke ioHandle().resetFileEvents() before accept_filters.clear(). and 'resetFileEvents' works fine even with the filter doesn't create any file event.

@antoniovicente correct me if I forget some points you pointed out.

**Comment by mattklein123** [comment]
> But I think I did miss that we can reset the file event just before we clear the accept filters.

Yeah this is how would have thought we would do it, but there is probably something I am missing about that. @antoniovicente WDYT?

File: source/common/network/io_socket_handle_impl.cc (hunk 1 above)
Comment (antoniovicente) [reply source/common/network/io_socket_handle_impl.cc]: I do appreciate the desire to handle all kinds of things transparently, but adding significant delays for all connections to server-talks-first protocols seems broken.

**Comment by antoniovicente** [comment]
Use of an RAII wrapper to track ownership of the file event in the network filters that need it seems like a potential improvement.  The framework itself resetting the file event as it clears and re-creates the filter chain seems like a potential option also.

That said, re-creation of the filter chain on timeout seems like broken behavior to me, see https://github.com/envoyproxy/envoy/pull/16952#discussion_r653055951

**Comment by antoniovicente** [comment]
Also, I wonder if there's an alternate way to provide the functionality provided by this filters, like an observer callback that Network::ConnectionImpl can provide to peek at the bytes read early in the connection in order to allow these inspector filters to look at the bytes that are being processed without requiring them to peek at the socket buffer every time the client sends additional bytes.

**Comment by mattklein123** [comment]
> The framework itself resetting the file event as it clears and re-creates the filter chain seems like a potential option also.

This is the approach I would take personally.

> Also, I wonder if there's an alternate way to provide the functionality provided by this filters, like an observer callback that Network::ConnectionImpl can provide to peek at the bytes read early in the connection in order to allow these inspector filters to look at the bytes that are being processed without requiring them to peek at the socket buffer every time the client sends additional bytes.

+1 this seems like a better option, though a much larger change to think about in the future.

**Comment by ggreenway** [comment]
That's something I've thought about for awhile as well. For a long time, BoringSSL was running in owns-the-fd mode, but I think it doesn't anymore (uses a memory BIO), so this could now be implemented. I'm a strong +1 on no more PEEK calls in the listener filters.

**Comment by antoniovicente** [comment]
A possible complexity is that the proxy protocol filter may do a real read after the PEEK in order to consume bytes that represent the proxy protocol header when it is present.  The API that would replace the PEEKs would need to allow stop-and-buffer to support the proxy protocol case in addition to pure PEEK functionality that I think other filters depend on.

**Comment by ggreenway** [comment]
Maybe the way to do it is have the listener filters read what they want into a `Buffer::Instance`, and then pass the buffer with any data they didn't consume to the next step?

**Comment by antoniovicente** [comment]
Yes, moving the actual read from the socket to base infrastructure and passing the buffer through the various filters seems like the most likely implementation path.

**Comment by soulxu** [comment]
> > The framework itself resetting the file event as it clears and re-creates the filter chain seems like a potential option also.
> 
> This is the approach I would take personally.

Let me submit another PR fix it.

> 
> > Also, I wonder if there's an alternate way to provide the functionality provided by this filters, like an observer callback that Network::ConnectionImpl can provide to peek at the bytes read early in the connection in order to allow these inspector filters to look at the bytes that are being processed without requiring them to peek at the socket buffer every time the client sends additional bytes.
> 
> +1 this seems like a better option, though a much larger change to think about in the future.

Let me file an issue for this.
