### PR TITLE
http: Fix ASSERT failure and infinite loop when attempting to unset readDisable state on a closed connection.

### LINKED ISSUE #9508: HTTP/1: watchdog death when clearing readDisable in onMessageComplete and the upstream connection is closed
*Description*:
The loop to clear the ConnectionImpl's readDisable flag in ClientConnectionImpl::onMessageComplete fails to terminate in cases where ConnectionImpl::readDisable exits early due to the connection not being in an open state.  It is possible to hit this scenario in some circumstances including when handling a large response framed by connection close and the downstream is slower than the upstream.  HTTP/1.1 responses framed by connection close are relatively uncommon compared to responses that specify a content-length or use transfer-encoding: chunked.

Envoy shouldn't become unresponsive and crash when handling these responses.

*Repro steps*:
Read the last bytes of the response body and detect that the connection is closed, and then trigger readDisable on the upstream connection by exceeding the downstream connection high watermark.  I have a PR in progress with a test that repos the issue most of the time and a potential fix.

*Call Stack*:
[2019-12-27 17:59:30.020][236][critical][assert] [source/common/network/connection_impl.cc:282] assert failure: state() == State::Open.
#0: Envoy::SignalAction::sigHandler() [0x3bbdb0c]
#1: __restore_rt [0x7f0edb8383a0]
#2: Envoy::Http::Http1::ClientConnectionImpl::onMessageComplete() [0x2c58362]
#3: Envoy::Http::Http1::ConnectionImpl::onMessageCompleteBase() [0x2c5561c]
#4: Envoy::Http::Http1::ConnectionImpl::$_8::operator()() [0x2c58d40]
#5: Envoy::Http::Http1::ConnectionImpl::$_8::__invoke() [0x2c58d15]
#6: http_parser_execute [0x31c041e]
#7: Envoy::Http::Http1::ConnectionImpl::dispatchSlice() [0x2c53e99]
#8: Envoy::Http::Http1::ConnectionImpl::dispatch() [0x2c53d92]
#9: Envoy::Http::CodecClient::onData() [0x2c4a64c]
#10: Envoy::Http::CodecClient::onEvent() [0x2c4a450]
#11: Envoy::Network::ConnectionImplBase::raiseConnectionEvent() [0x2fd2a01]
#12: Envoy::Network::ConnectionImpl::raiseEvent() [0x2fc79c5]
#13: Envoy::Network::ConnectionImpl::closeSocket() [0x2fc6a3d]
#14: Envoy::Network::ConnectionImpl::onReadReady() [0x2fc974f]
#15: Envoy::Network::ConnectionImpl::onFileEvent() [0x2fc93f5]
#16: Envoy::Network::ConnectionImpl::ConnectionImpl()::$_2::operator()() [0x2fce6be]
#17: std::__1::__invoke<>() [0x2fce681]
#18: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x2fce622]
#19: std::__1::__function::__alloc_func<>::operator()() [0x2fce5e2]
#20: std::__1::__function::__func<>::operator()() [0x2fcd723]
#21: std::__1::__function::__value_func<>::operator()() [0x26f23bd]
#22: std::__1::function<>::operator()() [0x26f233f]
#23: Envoy::Event::FileEventImpl::assignEvents()::$_0::operator()() [0x2fbd86c]
#24: Envoy::Event::FileEventImpl::assignEvents()::$_0::__invoke() [0x2fbd6f6]
#25: event_persist_closure [0x3b78bbe]
#26: event_process_active_single_queue [0x3b781e8]
#27: event_process_active [0x3b729aa]
#28: event_base_loop [0x3b7187c]
#29: Envoy::Event::LibeventScheduler::run() [0x307b698]
#30: Envoy::Event::DispatcherImpl::run() [0x2fb2e7a]
#31: Envoy::Server::WorkerImpl::threadRoutine() [0x1d297e1]
#32: Envoy::Server::WorkerImpl::start()::$_3::operator()() [0x1d2f35c]
#33: std::__1::__invoke<>() [0x1d2f31d]
#34: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x1d2f2cd]
#35: std::__1::__function::__alloc_func<>::operator()() [0x1d2f29d]
#36: std::__1::__function::__func<>::operator()() [0x1d2e3ce]
#37: std::__1::__function::__value_func<>::operator()() [0x19bdd15]
#38: std::__1::function<>::operator()() [0x19bdbd5]
#39: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::operator()() [0x3b661b2]
#40: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x3b66185]
#41: start_thread [0x7f0edb82dc73]

### PR DESCRIPTION
**Pull request by antoniovicente**
Description: Handle calls to ConnectionImpl::readDisable on Closed connections more gracefully.  There are several places under source/common, including ClientConnectionImpl::onMessageComplete, where Connection::readDisable(false) is called on a loop to clear the readDisable state as part of the process of preparing upstream connections for reuse.  It is possible to end up in an infinite loop if proxying an HTTP/1 response is framed by connection close, the call to onData triggers readDisable(true), and there is a pending PostIoAction::Close action.  The closeSocket call on the upstreamConnection triggers the call to ClientConnectionImpl::onMessageComplete
Risk Level: Low
Testing: unit and integration tests
Docs Changes: n/a
Release Notes: n/a
Fixes #9508

### CODE REVIEW

File: source/common/network/connection_impl.cc [hunk 1]
```diff
@@ -302,6 +297,11 @@ void ConnectionImpl::readDisable(bool disable) {
     ASSERT(read_enabled_);
     read_enabled_ = false;
 
+    if (state() != State::Open || file_event_ == nullptr) {
+      // If readDisable is called on a closed connection, do not crash.
+      return;
```
Comment (jmarantz) [inline source/common/network/connection_impl.cc]: the bug fix is to allow read_disable_count_ to be adjusted prior to the exit?

Comment (antoniovicente) [reply source/common/network/connection_impl.cc]: The fix is to allow read_enabled_ to transition to true in the branch below.

**Comment by antoniovicente** [comment]
> Awesome, thanks for debugging and fixing this. In general this makes sense to me. Optimally I would like @alyssawilk to review, but if this needs to merge urgently we can do that and she can post-review. Also need to check format.

I think it would be fine to wait until @alyssawilk is back from the holidays

File: source/common/network/connection_impl.cc [hunk 2]
```diff
@@ -279,13 +279,8 @@ void ConnectionImpl::enableHalfClose(bool enabled) {
 }
 
 void ConnectionImpl::readDisable(bool disable) {
-  ASSERT(state() == State::Open);
```
Comment (alyssawilk) [inline source/common/network/connection_impl.cc]: High level comment - prior to this the thought was that changing the read status of an open socket indicated an error and should be avoided.  I'm fine having error handling in case someone makes an error, but do we also think we should leave this ASSERT in and fix this at the call site to not attempt to change readDisable status for closed sockets?  It seems buggy behavior to read disable or enable a closed socket as it won't actually work.

File: test/integration/integration_test.cc [hunk 3]
```diff
@@ -221,6 +221,10 @@ TEST_P(IntegrationTest, RouterUpstreamDisconnectBeforeResponseComplete) {
   testRouterUpstreamDisconnectBeforeResponseComplete();
 }
 
+TEST_P(IntegrationTest, ResponseFramedByConnectionCloseWithReadLimits) {
+  testResponseFramedByConnectionCloseWithReadLimits();
```
Comment (alyssawilk) [inline test/integration/integration_test.cc]: If this is only used in one place please just put the code inline - it's not totally obvious but I'm trying to push for inline code where things are not reused.

File: test/integration/http_integration.cc [hunk 4]
```diff
@@ -867,6 +867,32 @@ void HttpIntegrationTest::testEnvoyProxying100Continue(bool continue_before_upst
...
+  initialize();
+
+  codec_client_ = makeHttpConnection(
+      create_connection ? ((*create_connection)()) : makeClientConnection((lookupPort("http"))));
+  fake_upstreams_[0]->set_allow_unexpected_disconnects(true);
+
+  auto response = codec_client_->makeHeaderOnlyRequest(default_request_headers_);
+  waitForNextUpstreamRequest();
+  // Disable chunking to trigger framing by connection close.
+  upstream_request_->encodeHeaders(Http::TestHeaderMapImpl{{":status", "200"}, {":no-chunks", "1"}},
```
Comment (alyssawilk) [inline test/integration/http_integration.cc]: This is just run for HTTP/1.1 right?
ostensibly the no chunk header is never supposed to be sent on the wire - I think if you don't send a content length and send HTTP/1.0 (see existing example tests) you can force frame by close that way. Mind trying it out?

Comment (antoniovicente) [reply test/integration/http_integration.cc]: I'm having some trouble finding examples under test/integration that encode an HTTP/1.0 response.  Do you have some links handy?

As far as I can tell ":no-chunks" is the way to tell StreamEncoderImpl::encodeHeaders in source/common/http/http1/codec_impl.cc to not chunk a response without a content-length.

File: source/common/network/connection_impl.cc (hunk 2 above)
Comment (antoniovicente) [reply source/common/network/connection_impl.cc]: We may want to go further and say it is illegal to call readEnabled() on a closed socket.  We'll need to add some connection state checks in a few places to avoid hitting ASSERT failures during runtime.

File: test/integration/http_integration.cc (hunk 4 above)
Comment (alyssawilk) [reply test/integration/http_integration.cc]: grep around for config_helper_.addConfigModifier(&setAllowHttp10WithDefaultHost); ?

They all use sendRawHttpAndWaitForResponse but given this is a header only request and you're waiting for connection close I _think_ that should be fine.

File: source/common/network/connection_impl.cc (hunk 2 above)
Comment (antoniovicente) [reply source/common/network/connection_impl.cc]: I brought the ASSERT back and extended it to also cover file_event_ != nullptr.  ASSERT also added to readEnabled.

connection_.state() check added to source/common/http/http1/codec_impl.cc to avoid hitting the ASSERT in ConnectionImplTest.ReadDisableAfterCloseHandledGracefully

File: test/integration/integration_test.cc (hunk 3 above)
Comment (antoniovicente) [reply test/integration/integration_test.cc]: Done.

File: test/integration/http_integration.cc (hunk 4 above)
Comment (antoniovicente) [reply test/integration/http_integration.cc]: I'm fairly sure that the :no-chunk does not end up on the wire.  One thing that I wanted to verify in some way is that the Envoy does see an upstream response framed by connection close.  I'm not sure how to accomplish that, since I think envoy will add chunk encoding to the response it sends downstream.

Let's talk briefly offline.

File: source/common/http/http1/codec_impl.cc [hunk 5]
```diff
@@ -944,7 +944,7 @@ void ClientConnectionImpl::onMessageComplete(HeaderMapImplPtr&& trailers) {
     // reused, unwind any outstanding readDisable() calls here. Only do this if there are no
     // pipelined responses remaining. Also do this before we dispatch end_stream in case the caller
     // immediately reuses the connection.
-    if (pending_responses_.empty()) {
+    if (connection_.state() == Network::Connection::State::Open && pending_responses_.empty()) {
```
Comment (alyssawilk) [inline source/common/http/http1/codec_impl.cc]: I'd be inclined to move this up and not do any work  (ignore pending responses) if the connection is not open.   @mattklein123 WDYT?

File: source/common/network/connection_impl.cc [hunk 6]
```diff
@@ -342,7 +352,12 @@ void ConnectionImpl::raiseEvent(ConnectionEvent event) {
   }
 }
 
-bool ConnectionImpl::readEnabled() const { return read_enabled_; }
+bool ConnectionImpl::readEnabled() const {
+  // Calls to readEnabled on a closed socket are considered to be an error.
```
Comment (alyssawilk) [inline source/common/network/connection_impl.cc]: Good call.
I wonder if the readEnabled loop in ConnectionManagerImpl::doEndStream could be subject to this in any weird corner case?  I _think_ it should be fine because if the connection gets closed it should be in DrainState::Closing but it might be worth adding an open check in that loop as well

File: source/common/http/http1/codec_impl.cc (hunk 5 above)
Comment (antoniovicente) [reply source/common/http/http1/codec_impl.cc]: You mean moving this connection state check to https://github.com/envoyproxy/envoy/blob/e9b59142c329ca9bd32cc4ab352f617f18260d2e/source/common/http/http1/codec_impl.cc#L936 ?

There are some calls to the decoder below that I think we need to perform, otherwise handling of upstream responses framed by connection closed which are proxied over H2 or chunked-encoded via HTTP/1.1 to the downstream won't be framed correctly.

File: source/common/network/connection_impl.cc (hunk 6 above)
Comment (antoniovicente) [reply source/common/network/connection_impl.cc]: I think that the "drain_state_ != DrainState::Closing" check in ConnectionManagerImpl::doEndStream is equivalent.  Or at least I don't see any tests failing due to me adding this ASSERT.

File: source/common/http/http1/codec_impl.cc (hunk 5 above)
Comment (mattklein123) [reply source/common/http/http1/codec_impl.cc]: Yeah this looks right to me. What did you have in mind @alyssawilk?

File: test/integration/integration_test.cc [hunk 7]
```diff
@@ -221,6 +221,31 @@ TEST_P(IntegrationTest, RouterUpstreamDisconnectBeforeResponseComplete) {
...
+  initialize();
+
+  codec_client_ = makeHttpConnection(makeClientConnection((lookupPort("http"))));
+  fake_upstreams_[0]->set_allow_unexpected_disconnects(true);
+
+  auto response = codec_client_->makeHeaderOnlyRequest(default_request_headers_);
+  waitForNextUpstreamRequest();
+  // Disable chunk encoding to trigger framing by connection close.
+  upstream_request_->encodeHeaders(Http::TestHeaderMapImpl{{":status", "200"}, {":no-chunks", "1"}},
+                                   false);
```
Comment (mattklein123) [inline test/integration/integration_test.cc]: If you wanted to avoid the `:no-chunks` business, you could potentially just use a raw TCP fake upstream connection and manually send an HTTP/1.0 response (you could I suppose also build HTTP/1.0 handling into the fake upstream but that sounds like a lot more work), which IIRC Envoy should handle correctly with close framing. I don't feel strongly about it but I know @alyssawilk commented on this.

Comment (alyssawilk) [reply test/integration/integration_test.cc]: I take Antonio's point that :no-chunks doesn't reach the wire - I'm (warily) fine with it.

File: source/common/http/http1/codec_impl.cc (hunk 5 above)
Comment (alyssawilk) [reply source/common/http/http1/codec_impl.cc]: let's leave as is then

**Comment by PiotrSikora** [comment]
@lambdai could you create the PR against `release/v1.12`? Thanks!
