### PR TITLE
health_check: `scheme` header for gRPC HC requests

### LINKED ISSUE #2583: Native gRPC health checker must send a `scheme` header
*Description*:
I tried Native gRPC health chekcer which was implemented with https://github.com/envoyproxy/envoy/pull/2316, but the checker does not send `sceheme` header. The `scheme` header is required for valid HTTP/2 request:

>All HTTP/2 requests MUST include exactly one valid value for the :method, :scheme, and :path pseudo-header fields, unless it is a CONNECT request

https://http2.github.io/http2-spec/#rfc.section.8.1.2.3

The problem is, some gRPC server implementations (in my case, it's Ruby implementation) reset streams with the malformed request, so Envoy can not correctly do health checkes to the servers.

The temporal fix is below, but we need consider upstream TLS context and apply this fix to other gRPC clients in Envoy if needed:

```diff
diff --git a/source/common/grpc/common.cc b/source/common/grpc/common.cc
index 84b97ead1..a301c859b 100644
--- a/source/common/grpc/common.cc
+++ b/source/common/grpc/common.cc
@@ -234,6 +234,7 @@ Http::MessagePtr Common::prepareHeaders(const std::string& upstream_cluster,
                                         const std::string& method_name) {
   Http::MessagePtr message(new Http::RequestMessageImpl());
   message->headers().insertMethod().value().setReference(Http::Headers::get().MethodValues.Post);
+  message->headers().insertScheme().value().setReference(Http::Headers::get().SchemeValues.Http);
   message->headers().insertPath().value().append("/", 1);
   message->headers().insertPath().value().append(service_full_name.c_str(),
                                                  service_full_name.size());
```

Envoy's request headers from a packet capture:

```
        [Header Length: 170]
        [Header Count: 6]
        Header: :method: POST
            Name Length: 7
            Name: :method
            Value Length: 4
            Value: POST
            Representation: Indexed Header Field
            Index: 3
        Header: :path: /grpc.health.v1.Health/Check
            Name Length: 5
            Name: :path
            Value Length: 28
            Value: /grpc.health.v1.Health/Check
            Representation: Literal Header Field without Indexing - Indexed Name
            Index: 4
        Header: :authority: some_service
            Name Length: 10
            Name: :authority
            Value Length: 12
            Value: some_service
            Representation: Literal Header Field with Incremental Indexing - Indexed Name
            Index: 1
        Header: content-type: application/grpc
            Name Length: 12
            Name: content-type
            Value Length: 16
            Value: application/grpc
            Representation: Literal Header Field with Incremental Indexing - Indexed Name
            Index: 31
        Header: te: trailers
            Name Length: 2
            Name: te
            Value Length: 8
            Value: trailers
            Representation: Literal Header Field with Incremental Indexing - New Name
        Header: user-agent: Envoy/HC
            Name Length: 10
            Name: user-agent
            Value Length: 8
            Value: Envoy/HC
            Representation: Literal Header Field with Incremental Indexing - Indexed Name
            Index: 58
```

*Repro steps*:
Building Ruby gRPC server with https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto. Then configure gRPC health checks.

*Admin and Stats Output*:
```
cluster.some_service.health_check.attempt: 1
cluster.some_service.health_check.failure: 1
cluster.some_service.health_check.healthy: 0
cluster.some_service.health_check.network_failure: 1
cluster.some_service.health_check.passive_failure: 0
cluster.some_service.health_check.success: 0
cluster.some_service.health_check.verify_cluster: 0
```

*Config*:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 9211 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.router
  clusters:
  - name: some_service
    http2_protocol_options: {}
    connect_timeout: { seconds: 10 }
    type: STATIC
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 8080 }}]
    health_checks:
      - grpc_health_check: { service_name: 'test' }
        timeout: { seconds: 10 }
        interval: { seconds: 10 }
        unhealthy_threshold: 2
        healthy_threshold: 2
```

*Logs*:
```
[2018-02-12 04:44:36.891][1553850][debug][hc] source/common/upstream/health_checker_impl.cc:748] [C1] connection/stream error health_flags=/failed_active_hc
```

### PR DESCRIPTION
**Pull request by taiki45**
*Description*:
Fixes #2583. Add required `scheme` header to gRPC health check requests.

*Risk Level*: Low
Small bug fix or small optional feature.

*Testing*:
Unit tests should cover this.

*Docs Changes*:
N/A

*Release Notes*:
N/A

Fixes #2583

### CODE REVIEW

File: source/common/upstream/health_checker_impl.cc [hunk 1]
```diff
@@ -723,6 +724,7 @@ void GrpcHealthCheckerImpl::GrpcActiveHealthCheckSession::onInterval() {
       parent_.service_method_.name());
   headers_message->headers().insertUserAgent().value().setReference(
       Http::Headers::get().UserAgentValues.EnvoyHealthChecker);
+  Router::FilterUtility::setUpstreamScheme(headers_message->headers(), *parent_.cluster_.info());
```
Comment (lizan) [inline source/common/upstream/health_checker_impl.cc]: Since this is required in gRPC spec, maybe add this to `Grpc::Common::prepareHeaders`?

Comment (taiki45) [reply source/common/upstream/health_checker_impl.cc]: Yeah, it's a reasonable option. And since `scheme` header is also required in h2 spec, we might have another place to add this to ensure all out-going h2 requests have necessary headers. Still I couldn't find the proper place.

Comment (taiki45) [reply source/common/upstream/health_checker_impl.cc]: With some digging the code base, other gRPC client codes in Envoy use a HttpAsyncClient which use a Router. Since a router sets proper h2 headers, it seems other gRPC client codes don't need to inject the `scheme` header. This has been commented https://github.com/envoyproxy/envoy/issues/2583#issuecomment-364789736.

File: test/common/upstream/health_checker_impl_test.cc [hunk 2]
```diff
@@ -1819,6 +1819,9 @@ TEST_F(GrpcHealthCheckerImplTest, Success) {
         EXPECT_EQ(Http::Headers::get().ContentTypeValues.Grpc,
                   headers.ContentType()->value().c_str());
         EXPECT_EQ(std::string("/grpc.health.v1.Health/Check"), headers.Path()->value().c_str());
+        EXPECT_EQ(Http::Headers::get().SchemeValues.Http, headers.Scheme()->value().c_str());
+        EXPECT_TRUE(headers.Method());
```
Comment (mattklein123) [inline test/common/upstream/health_checker_impl_test.cc]: nit: `EXPECT_NE(nullptr, ...)`. Same following.
