### PR TITLE
upstream: fix bugs of healthStatus() method

### LINKED ISSUE #27830: Backend health provided by EDS doesn't work properly with stateful session/override health status
*Title*: Backend health provided by EDS doesn't work properly with stateful session/override health status

*Description*:

We use EDS (over ADS) to dynamically control cluster load assignments and we control the health of each member from the management server. In our use case we use the HDS (Health Discovery Service) to collect endpoint health and will propagate this health status via EDS. We also use StatefulSession using an HTTP cookie and use `overrideHostStatus` with `HEALTHY`, `UNKOWN` and `DEGRADED`.  Since upgrading to Envoy 1.26 from Envoy 1.22, we now have an issue where stateful sessions no longer work.

#24094 introduced a change that uses `healthStatus()` instead of `coarseHealth()` which introduced this issue. Setting the `envoy.reloadable_features.validate_detailed_override_host_statuses: false` resolves the issue for us but this isn't a permanent solution.  

It seems that endpoint health delivered by EDS doesn't properly work with this change. For example, when an endpoint is marked as unhealthy via EDS `coarseHealth()` properly returns `Unhealthy` but `healthStatus()` returns `HealthStatus.HEALTHY`

*Repro steps*:
Running on Envoy 1.26 but change was introduced in 1.25. Use StatefulSession/Cookie and update endpoint health with EDS from healthy to unhealthy.

cc @wbpcode

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: upstream: fix bugs of healthStatus() method

Additional Description:

To close #27830. This PR fixed tow bugs. 

First, when the EDS API updates the endpoint, the proto health status is not updated into the host. This bug will make the `healthStatus()` return incorrect health status.

Second, the `healthStatus()` method will return unmatched status with `coarseHealth()` method in previous impl. Because in previous impl, the `healthStatus()` method always evaluate the dynamic flags first. If a host is marked as unhealthy by the EDS and is marked degraded by the active health checker, the `healthStatus()` will return DEGRADED and the `coarseHealth()` will return UNHEALTHY.

Risk Level: low.
Testing: unit.
Docs Changes: n/a.
Release Notes: added.
Platform Specific Features: n/a.

### CODE REVIEW

File: source/common/upstream/upstream_impl.h [hunk 1]
```diff
@@ -453,7 +471,7 @@ class HostImpl : public HostDescriptionImpl,
   // TODO(wbpcode): should we store the EDS health status to health_flags_ to get unified status or
   // flag access? May be we could refactor HealthFlag to contain all these statuses and flags in the
   // future.
-  HealthStatus health_status_{};
+  std::atomic<Host::HealthStatus> health_status_{};
```
Comment (htuch) [inline source/common/upstream/upstream_impl.h:474]: When do we modify health status cross-thread?

File: source/common/upstream/upstream_impl.h [hunk 2]
```diff
@@ -427,6 +434,14 @@ class HostImpl : public HostDescriptionImpl,
     return Host::Health::Healthy;
   }
 
+  void setEdsHealthStatus(envoy::config::core::v3::HealthStatus health_status) override {
+    health_status_ = health_status;
```
Comment (htuch) [inline source/common/upstream/upstream_impl.h:438]: Should this be `eds_health_status_`?

File: source/common/upstream/upstream_impl.h (hunk 1 above)
Comment (wbpcode) [reply source/common/upstream/upstream_impl.h:474]: When the health status is updated by the EDS API.

File: source/common/upstream/upstream_impl.h (hunk 2 above)
Comment (wbpcode) [reply source/common/upstream/upstream_impl.h:438]: Sounds better, thanks.

File: source/common/upstream/upstream_impl.h (hunk 1 above)
Comment (htuch) [reply source/common/upstream/upstream_impl.h]: So, the worker threads use this as a way to receive EDS health status from the main thread? I think atomics aren't super ideal here, given we also have other health fields atomics, and their updates might have corner cases where they update in different orders depending on memory ordering model of the machine. It's generally fine for stats and maybe even health status if you have only a single field, but when you have cross-field dependency with `health_flags_`, it's something I'd avoid. Please see https://abseil.io/docs/cpp/atomic_danger.

I wonder if all this shared health status between main thread and worker threads for a host should be under a reader-writer lock, reflecting that this is mostly read and fine to be accessed in parallel.

Comment (wbpcode) [reply source/common/upstream/upstream_impl.h]: Not sure the performance of the rwlock in multiple thread. 

 🤔 Another option is to store all the eds status in the `health_flags_`.

>   // TODO(wbpcode): should we store the EDS health status to health_flags_ to get unified status or
>  // flag access? May be we could refactor HealthFlag to contain all these statuses and flags in the
>  // future.

Comment (htuch) [reply source/common/upstream/upstream_impl.h]: The lesser evil probably would be to have a single atomic vs. multiple atomics tracking related state. It's still somewhat dangerous as per that link, but probably no worse than today. Is it plausible t oombine them?

Comment (wbpcode) [reply source/common/upstream/upstream_impl.h]: >  Is it plausible t oombine them.

I think eds unhelthy and eds degrade have been set to the health_flags_. So I think it should be ok. But I am not sure if it's the most efficient way to store these statuses.

Comment (htuch) [reply source/common/upstream/upstream_impl.h]: Why isn't flattening into a single variable the most efficient? In any case, I think we're kind of just stepping around the bigger problem, we don't have a clear set of documented expectations and invariants when it comes to cross-thread health.

Comment (wbpcode) [reply source/common/upstream/upstream_impl.h]: Because the `health_flags_` is desinged to store multiple statuses at same time. If we use it to store all eds statuses, we need check the flag one by one for get the original status.

```
if (health_flags_ & UKNOW_FLAG) {
  return unkonw;
} else if (....) {
  // ......
}
```

>  we don't have a clear set of documented expectations and invariants when it comes to cross-thread health.

I can add some more comment to the health status interfaces this time.

---

btw, I am thinking if the new `healthStatus()` support has truely value. we add the `healthStatus()` method in the #24094 to expose more detailed host status (Unknow, healthy, unhealthy, timeout, etc).

However, years go, the `coarseHealth()` still enough for users. And considering the bug #27830, maybe no accutally users want the detailed `healthStatus()`. `coarseHealth()` is enough.

Maybe we should stop and go back a step, to remove all this redundant support and just keep the original `Unhealthy`, `Degraded`, `Healthy`.

Comment (htuch) [reply source/common/upstream/upstream_impl.h]: https://github.com/envoyproxy/envoy/issues/27830 seems something to fix in any case but not the deal maker/breaker. How do you conclude that `coarseHealth()` is enough? The reason I ask is that when I approved https://github.com/envoyproxy/envoy/pull/24094 I was under the impression this was going to be available in EDS config dumps - how do we know if they are being used actively or not?

Comment (wbpcode) [reply source/common/upstream/upstream_impl.h]: 1. Because only `coarseHealth()` is used when dump the eds config.
2. Because the `eds_health_status_` never be updated correctly by the EDS API.

And considering the #27830, the only place where use the `healthStatus()` but has bugs, so, I think `healthStatus()` never be used correctly.

Comment (htuch) [reply source/common/upstream/upstream_impl.h]: @markdroth we originally added this more detailed EDS health status for gRPC parity I think? It seemed to make sense at the time, but according to @wbpcode we're not actually using it now it seems.

**Comment by htuch** [comment]
I think this issue is waiting for @wbpcode to determine if we should just drop the finer grained health status. Getting @markdroth take on this would help as we originally added this I think for gRPC parity.

**Comment by wbpcode** [comment]
At least for now, I think the fine-grained status make no sense for Envoy. So, I think we should drop this fine-grained status.

If we have a strong reason to add it back in the future, then we should redesign the store structure of these statues.

**Comment by wbpcode** [comment]
I think we can drop this feature directly, but if community wants to keep it for a while, I can create a simple patch to fix current bugs and then flip default value of the runtime flag.

cc @alyssawilk @htuch

**Comment by htuch** [comment]
I looked back at https://github.com/envoyproxy/envoy/issues/23213, which was the motivation for this work. It seems @markdroth is pointing to an actual bug that your original PR was intended to fix. Presumably if we roll back we have this bug again?

**Comment by wbpcode** [comment]
> Presumably if we roll back we have this bug again?

Yeah. But from https://github.com/envoyproxy/envoy/issues/27830, our users may never expect the fine-grained statuses.

I still can refactor this PR to fix exist bugs first. An additional atomic `int32_t` to store the fine-grained statuses should be ok. Even if it is inconsistent with flags at some point, there are no serious consequences. 🤔

**Comment by htuch** [comment]
I'm really confused, the original fix was intended to give better granularity on things like draining vs. timeout vs. unknown. How does this cause the behavior in https://github.com/envoyproxy/envoy/issues/27830, i.e.

> It seems that endpoint health delivered by EDS doesn't properly work with this change. For example, when an endpoint is marked as unhealthy via EDS coarseHealth() properly returns Unhealthy but healthStatus() returns HealthStatus.HEALTHY

This bit doesn't seem intuitive to me at all.

**Comment by wbpcode** [comment]
@htuch

Because when we add the fine-grained statuses support, a new field is used to store the eds status. But we didn't update it correctly when the host is updated by the EDS API.
It means that the original fix (#24094) introduced a new bug and result in the #27830.

**Comment by htuch** [comment]
The thing I'm confused about with option (1) is that we had a bug originally in #23213, we then tried to fix it with granular health status, the fix didn't work, and now we're saying it's fine to drop the bug fix because nobody is using it? This reasoning seems a bit circular.

Taking a step back, either we want to fix the bug in #23213 or not long term. Forgetting about the code situation today, should we fix that or mark it as "won't fix" with reason XYZ? What would XYZ be?

**Comment by wbpcode** [comment]
> The thing I'm confused about with option (1) is that we had a bug originally in https://github.com/envoyproxy/envoy/issues/23213, we then tried to fix it with granular health status, the fix didn't work, and now we're saying it's fine to drop the bug fix because nobody is using it? This reasoning seems a bit circular.

I used to think the fine-grained statuses would help. But one year go, fact tell me it just is senseless. 😞

**Comment by wbpcode** [comment]
> Taking a step back, either we want to fix the bug in https://github.com/envoyproxy/envoy/issues/23213 or not long term. Forgetting about the code situation today, should we fix that or mark it as "won't fix" with reason XYZ? What would XYZ be?

If let me re-make the decision, I will mark it as `won't fix` or `pending` until actual Envoy users complain about the health status management:

The `DRAINING` and `TIMEOUT` will be interpreted as `UNHEALTHY` is well [documented](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/core/v3/health_check.proto) and work well for all users.
Fine-grained status support will introduce new complexity and maybe have no any actual value for users.

---

In fact, the only key point is whether the fine-grained status support has actual value for users. At the moment, I think the answer is no, so I'm inclined to drop it.

**Comment by htuch** [comment]
OK, I think given the issues and overall complexity, let's go back to the original issue and revert the original change until we have some demand. Thanks.

File: source/common/upstream/upstream_impl.h (hunk 1 above)
Comment (markdroth) [reply source/common/upstream/upstream_impl.h]: Note that gRPC honors the full-fidelity EDS health status in `override_host_status`.  If Envoy reverts to its old behavior, then gRPC and Envoy will have different behavior, and I don't think that's what we want.

Comment (wbpcode) [reply source/common/upstream/upstream_impl.h]: cc @markdroth Hi, thanks for the response and explaination.

I think the coarse health is well [documented](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/core/v3/health_check.proto) and work well for all current Envoy users. And in the Envoy, the fine-grained status support never be used or never work correctly.

I may want drop the fine-grained status support and re-open #23213 **until actual Envoy users complain about the health status management.**

Although this will result in minor behavior difference between gRPC proxy and Envoy, but I think it's better than introducing new complexity to add feature that senseless for Envoy users.

Comment (markdroth) [reply source/common/upstream/upstream_impl.h]: > I think the coarse health is well [documented](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/core/v3/health_check.proto)

That file defines the fine-grained EDS health status values.  I don't see anything there that actually documents the coarse-grained values or the fact that data planes are expected to convert the fine-grained values into coarse-grained values internally.

But more fundamentally, I don't think this is a documentation issue; I think it's an issue of the defined meaning of the xDS API.  The xDS protos have an enum that defines the fine-grained EDS health status values, and the `override_host_status` field uses those same enum values.  The only reasonable behavior for this API is that we honor the individual values.  Any other behavior is completely counter-intuitive from the perspective of the way these APIs are defined in xDS.

I also don't think it's okay for Envoy and gRPC to have semantically different behavior here.  If any xDS-aware data plane just ignores what the API says whenever it's convenient, then the xDS ecosystem is not going to provide any actual definition of data plane behavior.

Comment (wbpcode) [reply source/common/upstream/upstream_impl.h]: Am I misunderstanding? I think the document declare this point clearly? In the Envoy, the `UNKNOW` will be interpreted as `HEALTHY` and `DRAINING`/`TIMEOUT` will be interpreted as `UNHEALTHY`?

> // The health status is not known. This is interpreted by Envoy as ``HEALTHY``.              <-- here

>   // Connection draining in progress. E.g.,
>  // `<https://aws.amazon.com/blogs/aws/elb-connection-draining-remove-instances-from-service-with-care/>`_
>  // or
>  // `<https://cloud.google.com/compute/docs/load-balancing/enabling-connection-draining>`_.
>  // This is interpreted by Envoy as ``UNHEALTHY``.                                                           <-- here

>   // Health check timed out. This is part of HDS and is interpreted by Envoy as
>  // ``UNHEALTHY``                                                                                                              <-- here

Comment (markdroth) [reply source/common/upstream/upstream_impl.h]: The documentation says what Envoy considers healthy or unhealthy, but it doesn't actually say what that means -- i.e., what specific behavior will be different based on that decision of healthiness?  And I don't think anything there implies that, for example, setting `override_host_status` to `DRAINING` will actually match hosts in `UNHEALTHY` state.  Those two states are not the same thing, and there will be cases where users will want to match one without the other, and I don't see anything in the documentation that would lead a reader to expect the counter-intuitive behavior of matching statuses that are not actually in the list.

In any case, as I said above, the problem here is not just documentation; the problem is that the coarse-grained behavior is inherently broken.  If `override_host_status` was expressed in terms of coarse-grained health status, then you might be able to argue that Envoy's old behavior made sense -- although it would still probably not be fine-grained enough to address the kind of use-case I cited above.  But since it's actually expressed using the fine-grained EDS health status, I think the natural expectation of this API is that it will actually match endpoints in the specified statuses.  I think any other behavior is simply broken with respect to the API semantics.

Comment (wbpcode) [reply source/common/upstream/upstream_impl.h]: Thanks for your patient explanation. I am not convinced because I think the document is clearly enough to tell users that Envoy has specifc logic at there.

But I admit the #23213 is a reasonable bug. But now, I don't think it has no big value to be fixed before some actual users to complain that.

But then again, I didn't acutally insist on my point in particular. I just want to fix #27830 (which acutally influence our users) before we cut 1.27.

So I think we should make a decision as soon as possible because we may cut the new release these days. If @markdroth strongly object to drop the fine-grained status support, a quick fix (store the eds status by additional atomic int and update in the main thread, I don't think there are any side effects other than the possibility of inconsistent health status in some very extreme cases) is also acceptable to me.

**Review by htuch — APPROVED** [review]
The use of multiple atomics I'm still not a super fan of, but I agree it's likely not an issue in practice for the consumers of this health status. Let's ship it as is, I think I'm persuaded we should fix this bug. Thanks @markdroth and @wbpcode for the in-depth discussion.

**Comment by wbpcode** [comment]
Thanks review cc @htuch.

There are lots of interfaces will do multiple times atomic reads/writes in same call, this means a read call on the worker threads may get a Intermediate result of another write call on the main thread.
It maybe better to ensure all these interfaces to do only one time atomic reads/writes in one call.
