### PR TITLE
fix: fix ext_proc to reliably populate request-based attributes

### LINKED ISSUE #41744: ext_proc: attributes based on request headers are not populated if ext_proc only run on encode path
PR #40800 made it possible for filters to be conditionally executed based on response headers. The ext_proc filter functions properly in this setup (where only encode-direction callbacks are invoked on it), though I have hit one problem: attributes that are based on request header values (e.g. "request.host") do not get populated in `ProcessingRequest`s sent to ext_proc servers.

Sequence, supposing that the ext_proc filter has been configured to send the "request.host" attribute, but is under an `ExtensionWithMatcher` that causes it to only be invoked in the encode* direction:

1. Because ext_proc filter doesn't have `decodeHeaders` called on it, `setRequestHeaders` never called [here](https://github.com/envoyproxy/envoy/blob/e753a7037e48c7b1dc41fcfede5c2badd718d418/source/extensions/filters/http/ext_proc/ext_proc.cc#L772-L773)
2. Therefore, `state.requestHeaders()` returns `nullptr` [here](https://github.com/envoyproxy/envoy/blob/e753a7037e48c7b1dc41fcfede5c2badd718d418/source/extensions/filters/http/ext_proc/ext_proc.cc#L1443)
3. Therefore, `activation_request_headers_` is `nullptr` [here](https://github.com/envoyproxy/envoy/blob/e753a7037e48c7b1dc41fcfede5c2badd718d418/source/extensions/filters/common/expr/evaluator.cc#L60)
4. Therefore, `RequestWrapper::operator[]` doesn't find an entry when passed `key` = "host" [here](https://github.com/envoyproxy/envoy/blob/e753a7037e48c7b1dc41fcfede5c2badd718d418/source/extensions/filters/common/expr/context.cc#L554) (for resolving the "host" part of "request.host")
5. Therefore, CEL expression evaluation for "request.host" fails, and no value for it is included in the ext_proc `ProcessingRequest`.

IOW, ext_proc attribute CEL evaluation is basing its view of request headers on a locally stored pointer to the `RequestHeaderMap` that is null if decode callbacks are skipped/disabled.

The fix is to instead feed the CEL evaluator the per-request `StreamInfo` object, which always has requestHeaders regardless of what callbacks are invoked on the ext_proc filter. IOW, change the `Filters::Common::Expr::createActivation` call [here](https://github.com/envoyproxy/envoy/blob/e753a7037e48c7b1dc41fcfede5c2badd718d418/source/extensions/filters/http/ext_proc/ext_proc.cc#L1441) from:

```
  auto activation_ptr = Filters::Common::Expr::createActivation(
      &config_->expressionManager().localInfo(), state.callbacks()->streamInfo(),
      state.requestHeaders(), dynamic_cast<const Http::ResponseHeaderMap*>(state.responseHeaders()),
      dynamic_cast<const Http::ResponseTrailerMap*>(state.responseTrailers()));
```

to:

```
  auto activation_ptr = Filters::Common::Expr::createActivation(
      &config_->expressionManager().localInfo(), state.callbacks()->streamInfo(),
      state.callbacks()->streamInfo().getRequestHeaders(), dynamic_cast<const Http::ResponseHeaderMap*>(state.responseHeaders()),
      dynamic_cast<const Http::ResponseTrailerMap*>(state.responseTrailers()));
```

### PR DESCRIPTION
**Pull request by mpwarres**
Fixes #41744 

Fix is as suggested in the issue; this PR also adds an integration test to exercise the case.

### CODE REVIEW

**Comment by mpwarres** [comment]
@yanjunxiang-google FYI

**Comment by mpwarres** [comment]
Also @mbadov

File: test/extensions/filters/http/ext_proc/ext_proc_integration_common.cc [hunk 1]
```diff
@@ -838,40 +850,80 @@ void ExtProcIntegrationTest::serverSendTrailerRespDuplexStreamed() {
...
+  on_match.mutable_action()->mutable_typed_config()->PackFrom(
+      execute_filter_action);
+
+  composite_filter.mutable_typed_config()->PackFrom(extension_with_matcher);
+  config_helper_.prependFilter(
+      MessageUtil::getJsonStringFromMessageOrError(composite_filter), true);
+}
+
+void ExtProcIntegrationTest::
+    prependExtProcCompositeFilterMatchOnResponseHeaders() {
```
Comment (yanjunxiang-google) [inline test/extensions/filters/http/ext_proc/ext_proc_integration_common.cc]: It looks to me you can share common code for these two test functions. Otherwise LGTM

Comment (mpwarres) [reply test/extensions/filters/http/ext_proc/ext_proc_integration_common.cc]: Ah, right, of course! Done.

**Comment by mpwarres** [comment]
FWIW, it looks like the one failing CI action ("Verify / distroless / ./ci/do_ci.sh verify-distroless", [link](https://github.com/envoyproxy/envoy/actions/runs/18960110913/job/54147666895)) failed due to reasons unrelated to this PR specifically (disk space exhaustion):

```
Syncing repository: envoyproxy/envoy
Getting Git version info
  Working directory is '/home/runner/work/envoy/envoy'
  /usr/bin/git version
  git version 2.51.2
Copying '/home/runner/.gitconfig' to '/home/runner/work/_temp/f4456ef8-a69c-4f45-bfcb-50b8603270fd/.gitconfig'
Temporarily overriding HOME='/home/runner/work/_temp/f4456ef8-a69c-4f45-bfcb-50b8603270fd' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/envoy/envoy
Deleting the contents of '/home/runner/work/envoy/envoy'
Initializing the repository
  /usr/bin/git init /home/runner/work/envoy/envoy
  /home/runner/work/envoy/envoy/.git: No space left on device
  Error: The process '/usr/bin/git' failed with exit code 1
```

**Comment by yanjunxiang-google** [comment]
LGTM

**Comment by agrawroh** [comment]
@mpwarres Could you please add a small release note as requested by @adisuissa?

/wait

**Comment by agrawroh** [comment]
Please add a release note in `changelogs/current.yaml`. Thanks!

/wait

**Comment by mpwarres** [comment]
> @mpwarres Could you please add a small release note as requested by @adisuissa?
> 
> /wait

Sorry for the delay, missed this! Done.

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
Based on @yanjunxiang-google (codeowner) prior approval, this PR can be merged.
