### PR TITLE
HTTP health checker: handle GOAWAY from HTTP2 upstreams

### LINKED ISSUE #13544: HTTP health checker does not gracefully handle HTTP2 server shutdown (GOAWAY with NO_ERROR)
*Title*: *HTTP health checker does not gracefully handle HTTP2 server shutdown (GOAWAY with NO_ERROR)*

*Description*:
The HTTP health checker does not gracefully handle when an HTTP2 server performs the graceful drain sequence. GOAWAY is ignored (no callbacks registered) and then health checks on the old connection fail with REFUSED_STREAM until the connection is forcibly closed by the upstream, at which point the health checker reconnects.

*Repro steps*:
I've reproduced with this Envoy bootstrap config:

```
admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8082
  access_log_path: '/tmp/envoytesting/admin.log'

dynamic_resources:
  lds_config:
    path: /tmp/envoytesting/lds.yaml

static_resources:
  clusters:
  - name: self_health_checked
    connect_timeout: 5s
    type: STATIC
    lb_policy: RANDOM
    http2_protocol_options: {}
    health_checks:
    - interval: "1s"
      no_traffic_interval: 1s
      timeout: 5s
      unhealthy_threshold: 1
      healthy_threshold: 1
      http_health_check:
        path: /_status
        codec_client_type: HTTP2
      always_log_health_check_failures: true
      event_log_path: /tmp/envoytesting/healthcheck.log
    load_assignment:
      cluster_name: self_health_checked
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address: { address: 127.0.0.1, port_value: 8081 }
    http2_protocol_options: {}
node:
  id: foo
  cluster: foo
```

And this in `/tmp/envoytesting/lds.yaml`

```
version_info: "http_stats2"
type_url: type.googleapis.com/envoy.config.listener.v3.Listener
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: http_listener
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8081
  filter_chains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: http_stats2
        http_filters:
        - name: health
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
            pass_through_mode: false
            headers:
              name: :path
              exact_match: /_status
        - name: router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route_config:
          virtual_hosts:
          - name: "only_host"
            domains: ["*"]
            routes:
            - match:
                prefix: "/"
              direct_response:
                status: 200
                body:
                  inline_string: "direct response"
```

Triggering an lds update by updating something like the stat prefix and `mv` over lds.yaml causes health checks to fail.

Logs from running Envoy with `--component-log-level connection:debug,http2:debug,client:debug,hc:debug`:

```

[2020-10-13 15:24:20.877][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:295] [C1] hc response=200 health_flags=healthy
[2020-10-13 15:24:20.877][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:960] [C1] stream closed: 0
[2020-10-13 15:24:21.229][69][info][upstream] [external/envoy/source/server/lds_api.cc:79] lds: add/update listener 'http_listener'
[2020-10-13 15:24:21.877][77][debug][http2] [external/envoy/source/common/http/http2/codec_impl_legacy.cc:813] [C2] sent goaway code=0
[2020-10-13 15:24:21.877][77][debug][http2] [external/envoy/source/common/http/http2/codec_impl_legacy.cc:933] [C2] stream closed: 0
[2020-10-13 15:24:21.877][69][debug][client] [external/envoy/source/common/http/codec_client.cc:109] [C1] response complete
[2020-10-13 15:24:21.877][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:295] [C1] hc response=200 health_flags=healthy
[2020-10-13 15:24:21.877][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:960] [C1] stream closed: 0
[2020-10-13 15:24:22.878][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:960] [C1] stream closed: 7
[2020-10-13 15:24:22.878][69][debug][client] [external/envoy/source/common/http/codec_client.cc:119] [C1] request reset
[2020-10-13 15:24:22.878][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:287] [C1] connection/stream error health_flags=healthy
[2020-10-13 15:24:23.879][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:960] [C1] stream closed: 7
[2020-10-13 15:24:23.880][69][debug][client] [external/envoy/source/common/http/codec_client.cc:119] [C1] request reset
[2020-10-13 15:24:23.880][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:287] [C1] connection/stream error health_flags=/failed_active_hc
[2020-10-13 15:24:24.880][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:960] [C1] stream closed: 7
[2020-10-13 15:24:24.881][69][debug][client] [external/envoy/source/common/http/codec_client.cc:119] [C1] request reset
[2020-10-13 15:24:24.881][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:287] [C1] connection/stream error health_flags=/failed_active_hc
[2020-10-13 15:24:25.883][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:960] [C1] stream closed: 7
[2020-10-13 15:24:25.883][69][debug][client] [external/envoy/source/common/http/codec_client.cc:119] [C1] request reset
[2020-10-13 15:24:25.883][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:287] [C1] connection/stream error health_flags=/failed_active_hc
[2020-10-13 15:24:26.879][77][debug][http2] [external/envoy/source/common/http/http2/codec_impl_legacy.cc:813] [C2] sent goaway code=0
[2020-10-13 15:24:26.880][77][debug][connection] [external/envoy/source/common/network/connection_impl.cc:106] [C2] closing data_to_write=17 type=2
[2020-10-13 15:24:26.880][77][debug][connection] [external/envoy/source/common/network/connection_impl_base.cc:40] [C2] setting delayed close timer with timeout 1000 ms
[2020-10-13 15:24:26.880][77][debug][connection] [external/envoy/source/common/network/connection_impl.cc:641] [C2] write flush complete
[2020-10-13 15:24:26.882][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:960] [C1] stream closed: 7
[2020-10-13 15:24:26.882][69][debug][client] [external/envoy/source/common/http/codec_client.cc:119] [C1] request reset
[2020-10-13 15:24:26.882][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:287] [C1] connection/stream error health_flags=/failed_active_hc
[2020-10-13 15:24:27.884][77][debug][connection] [external/envoy/source/common/network/connection_impl_base.cc:54] [C2] triggered delayed close
[2020-10-13 15:24:27.884][77][debug][connection] [external/envoy/source/common/network/connection_impl.cc:202] [C2] closing socket: 1
[2020-10-13 15:24:27.884][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:960] [C1] stream closed: 7
[2020-10-13 15:24:27.884][69][debug][client] [external/envoy/source/common/http/codec_client.cc:119] [C1] request reset
[2020-10-13 15:24:27.885][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:287] [C1] connection/stream error health_flags=/failed_active_hc
[2020-10-13 15:24:27.885][69][debug][connection] [external/envoy/source/common/network/connection_impl.cc:579] [C1] remote close
[2020-10-13 15:24:27.885][69][debug][connection] [external/envoy/source/common/network/connection_impl.cc:202] [C1] closing socket: 0
[2020-10-13 15:24:27.885][69][debug][client] [external/envoy/source/common/http/codec_client.cc:95] [C1] disconnect. resetting 0 pending requests
[2020-10-13 15:24:28.887][69][debug][client] [external/envoy/source/common/http/codec_client.cc:39] [C3] connecting
[2020-10-13 15:24:28.887][69][debug][connection] [external/envoy/source/common/network/connection_impl.cc:755] [C3] connecting to 127.0.0.1:8081
[2020-10-13 15:24:28.887][69][debug][connection] [external/envoy/source/common/network/connection_impl.cc:771] [C3] connection in progress
[2020-10-13 15:24:28.887][69][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:1168] [C3] updating connection-level initial window size to 268435456
[2020-10-13 15:24:28.888][69][debug][connection] [external/envoy/source/common/network/connection_impl.cc:611] [C3] connected
[2020-10-13 15:24:28.888][69][debug][client] [external/envoy/source/common/http/codec_client.cc:77] [C3] connected
[2020-10-13 15:24:28.888][77][debug][http2] [external/envoy/source/common/http/http2/codec_impl_legacy.cc:1139] [C4] updating connection-level initial window size to 268435456
[2020-10-13 15:24:28.888][77][debug][http2] [external/envoy/source/common/http/http2/codec_impl_legacy.cc:933] [C4] stream closed: 0
[2020-10-13 15:24:28.889][69][debug][client] [external/envoy/source/common/http/codec_client.cc:109] [C3] response complete
[2020-10-13 15:24:28.889][69][debug][hc] [external/envoy/source/common/upstream/health_checker_impl.cc:295] [C3] hc response=200 health_flags=/failed_active_hc
```

You can see this sequence:

1) health checks are succeeding
2) the server says `sent goaway code=0`
3) the in-flight health check succeeds one last time
4) a sequence of "stream closed: 7" (7 is REFUSED_STREAM) causing health checks to fail
5) server says `closing socket: 1`, client says `remote close`
6) client reconnects and health checks start succeeding again.

I'm working on a PR to make the http health checker handle GOAWAY similarly to how the gRPC one does, and will test with my same local repro.

### PR DESCRIPTION
**Pull request by mpuncel**
Makes the HTTP health checker handle GOAWAY properly. When the NO_ERROR
code is received, any in flight request will be allowed to complete, at
which time the connection will be closed and a new connection created on
the next interval.

GOAWAY frames with codes other than NO_ERROR are treated as a health
check failure, and immediately close the connection.

Commit Message:

Makes the HTTP health checker handle GOAWAY properly. When the NO_ERROR
code is received, any in flight request will be allowed to complete, at
which time the connection will be closed and a new connection created on
the next interval.

GOAWAY frames with codes other than NO_ERROR are treated as a health
check failure, and immediately close the connection.
Additional Description: 

I verified this locally with the same setup as the described issue, and saw the desired behavior.

Risk Level: Low
Testing: Unit tests
Docs Changes: N/A
Release Notes: Included
Fixes #13544

### CODE REVIEW

**Comment by mpuncel** [comment]
It doesn't look like the test failure was likely caused by this?

**Comment by mpuncel** [comment]
@htuch it sounds like Snow is OOO this week, is there someone else who can be assigned to review?

**Comment by htuch** [comment]
Reassigning to @alyssawilk for data plane.

**Review by alyssawilk — COMMENTED** [review]
Nice improvement to goaway handling!  Quick question before I dive in why is NO_ERROR special cased alone here?  GOAWAY is generally used to stop establishing new streams while gracefully handling old ones I'd be inclined to say that your "no_error" behavior should be the default.

I'd also be inclined to runtime guard this one per the L7 change policy if it's not too ugly to do so.

**Comment by mpuncel** [comment]
@alyssawilk I did that to be consistent with the way the GrpcHealthChecker handles GOAWAY, to be honest I'm not very familiar with the h2 spec. You're probably right that we shouldn't do a local reset of an inflight request if there is a GOAWAY error. If you confirm that's the right thing to do I can make that change.

I'm happy to look into adding a runtime guard as well, will let you know if I think that greatly complicates things.

**Comment by alyssawilk** [comment]
Huh, consistency is a pretty good argument.  cc @snowp @mattklein123 @PiotrSikora on if we should go for GOAWAY consistency,  or have this HTTP health checker do graceful goaway for all error codes (and eventually maybe do the same for gRPC)

**Comment by mattklein123** [comment]
> Huh, consistency is a pretty good argument. cc @snowp @mattklein123 @PiotrSikora on if we should go for GOAWAY consistency, or have this HTTP health checker do graceful goaway for all error codes (and eventually maybe do the same for gRPC)

IMO it's correct treat NO_ERROR as a special case, because it's not a failure, it's just telling the downstream to make a new connection. If a GOAWAY is not NO_ERROR it does indicate an actual problem. I agree you could probably implement either way and it's not a huge deal, but given that gRPC already works like this it seems fine to have it be consistent.

File: source/common/upstream/health_checker_impl.cc [hunk 1]
```diff
@@ -279,15 +282,50 @@ void HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onInterval() {
...
 }
 
+void HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onGoAway(
+    Http::GoAwayErrorCode error_code) {
+  ENVOY_CONN_LOG(debug, "connection going away health_flags={}", *client_,
+                 HostUtility::healthFlagsToString(*host_));
+
+  // If GOAWAY handling is explicitly disabled via runtime, go back to the old
+  // behavior of ignoring GOAWAY completely.
+  if (parent_.runtime_.snapshot().featureEnabled("health_check.disable_goaway_handling", 0UL)) {
```
Comment (mpuncel) [inline source/common/upstream/health_checker_impl.cc:306]: @alyssawilk it turned out to be simple to go back to the old behavior. Let me know if I got the defaults the right direction, not sure if you wanted to make this opt in or opt out

File: docs/root/version_history/current.rst [hunk 2]
```diff
@@ -17,6 +17,9 @@ Bug Fixes
 ---------
 *Changes expected to improve the state of the world and are unlikely to have negative effects*
 
+* active health checks: health checks using a TLS transport socket and secrets delivered via :ref:`SDS <config_secret_discovery_service>` will now wait until secrets are loaded before the first health check attempt. This should improve startup times by not having to wait for the :ref:`no_traffic_interval <envoy_v3_api_field_config.core.v3.HealthCheck.no_traffic_interval>` until the next attempt.
+* active http health checks: properly handles HTTP/2 GOAWAY frames from the upstream. Previously a GOAWAY frame due to a graceful listener drain could cause improper failed health checks due to streams being refused by the upstream on a connection that is going away.
```
Comment (alyssawilk) [inline docs/root/version_history/current.rst:21]: please call out the runtime guard here

File: source/common/upstream/health_checker_impl.cc (hunk 1 above)
Comment (alyssawilk) [reply source/common/upstream/health_checker_impl.cc:306]: opt-out is fine, but can you please check https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#runtime-guarding
and go with the naming and such used there? 
If you stick the flag in runtime_features.cc it'll go back to opt-out.

File: source/common/upstream/health_checker_impl.cc [hunk 3]
```diff
@@ -345,7 +385,7 @@ bool HttpHealthCheckerImpl::HttpActiveHealthCheckSession::shouldClose() const {
     return false;
   }
 
-  if (!parent_.reuse_connection_) {
+  if (!parent_.reuse_connection_ || received_no_error_goaway_) {
```
Comment (alyssawilk) [inline source/common/upstream/health_checker_impl.cc:388]: Curious, could we just set parent_.reuse_connection_ false when get the goaway, and let all the rest of the code proceed as usual?  I assume if we're not reusing the connection it would close on stream reset or stream complete.

File: test/common/upstream/health_checker_impl_test.cc [hunk 4]
```diff
@@ -2494,6 +2513,291 @@ TEST_F(HttpHealthCheckerImplTest, NoTransportSocketMatchCriteria) {
...
+  EXPECT_CALL(*test_sessions_[0]->interval_timer_, enableTimer(_, _));
+  respond(0, "200", false, false, true, false, {}, false);
+  EXPECT_EQ(Host::Health::Healthy, cluster_->prioritySet().getMockHostSet(0)->hosts_[0]->health());
+}
+
+// Smoke test that receiving GOAWAY (no error) is ignored when GOAWAY handling
+// is disabled via runtime. This is based on the
+// GoAwayProbeInProgressStreamReset test case. More test cases isn't necessary
+// due to the simplicity of the runtime check.
+TEST_F(HttpHealthCheckerImplTest, GoAwayProbeInProgressStreamResetRuntimeDisabled) {
```
Comment (mpuncel) [inline test/common/upstream/health_checker_impl_test.cc:2758]: let me know if I should add more test cases covering the runtime flag. I figured since it's a single conditional, just a single smoke test case is good enough and it's not worth it to duplicate all of the other cases.

File: test/common/upstream/health_checker_impl_test.cc [hunk 5]
```diff
@@ -2494,6 +2513,291 @@ TEST_F(HttpHealthCheckerImplTest, NoTransportSocketMatchCriteria) {
...
+  expectStreamCreate(0);
+  EXPECT_CALL(*test_sessions_[0]->timeout_timer_, enableTimer(_, _));
+  health_checker_->start();
+
+  test_sessions_[0]->codec_client_->raiseGoAway(Http::GoAwayErrorCode::NoError);
+  EXPECT_EQ(Host::Health::Healthy, cluster_->prioritySet().getMockHostSet(0)->hosts_[0]->health());
+
+  // Unhealthy threshold is 1 so first timeout causes unhealthy
+  EXPECT_CALL(event_logger_, logUnhealthy(_, _, _, true));
+  EXPECT_CALL(event_logger_, logEjectUnhealthy(_, _, _));
```
Comment (alyssawilk) [inline test/common/upstream/health_checker_impl_test.cc:2619]: optional, but do you think it's worth bundling these expect calls into function helper routines which are easier to read/understand?  expectUnhealthy()

**Review by alyssawilk — COMMENTED** [review]
Awesome, glad the guarding was simple.  Just a few more comments and this should be good to go!

File: source/common/upstream/health_checker_impl.cc (hunk 3 above)
Comment (mpuncel) [reply source/common/upstream/health_checker_impl.cc:389]: i think we need both because otherwise we wouldn't know what to reset `parent_.reuse_connection_` to when we start a new stream

File: test/common/upstream/health_checker_impl_test.cc (hunk 5 above)
Comment (mpuncel) [reply test/common/upstream/health_checker_impl_test.cc]: updated

File: source/common/upstream/health_checker_impl.cc (hunk 3 above)
Comment (mpuncel) [reply source/common/upstream/health_checker_impl.cc:389]: Maybe this is what you meant: one thing I could do is name this variable `reuse_connection_`, and at the start of the stream set it to `parent.reuse_connection_`, and then in set it to false if there is a NO_ERROR GOAWAY. That might make it more clear

File: source/common/upstream/health_checker_impl.cc [hunk 6]
```diff
@@ -279,15 +282,51 @@ void HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onInterval() {
 
 void HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onResetStream(Http::StreamResetReason,
                                                                         absl::string_view) {
+  request_in_flight_ = false;
+  ENVOY_CONN_LOG(debug, "connection/stream error health_flags={}", *client_,
+                 HostUtility::healthFlagsToString(*host_));
+  if (client_ && received_no_error_goaway_) {
+    client_->close();
```
Comment (mpuncel) [inline source/common/upstream/health_checker_impl.cc:289]: @alyssawilk this is the one place it might be weird to just use a `reuse_connection_` bool, because in the old behavior it looks like it would not close the connection if the stream was reset? That means i'd have to change the behavior a bit, but it also might be a small bug that it wasn't closing the connection before?

Comment (mpuncel) [reply source/common/upstream/health_checker_impl.cc:289]: I'll push the commit, we can always revert it

File: source/common/upstream/health_checker_impl.cc [hunk 7]
```diff
@@ -279,15 +282,51 @@ void HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onInterval() {
...
 }
 
+void HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onGoAway(
+    Http::GoAwayErrorCode error_code) {
+  ENVOY_CONN_LOG(debug, "connection going away health_flags={}", *client_,
+                 HostUtility::healthFlagsToString(*host_));
+
+  // Runtime guard around graceful handling of NO_ERROR GOAWAY handling. The old behavior is to
+  // ignore GOAWAY completely.
+  if (!parent_.runtime_.snapshot().featureEnabled(
```
Comment (alyssawilk) [inline source/common/upstream/health_checker_impl.cc:306]: runtimeFeatureEnabled() ?

File: source/common/upstream/health_checker_impl.cc [hunk 8]
```diff
@@ -279,15 +282,51 @@ void HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onInterval() {
...
+    return;
+  }
+
+  if (request_in_flight_) {
+    // Record this as a failed health check.
+    handleFailure(envoy::data::core::v3::NETWORK);
+  }
+
+  if (client_) {
+    expect_reset_ = true;
```
Comment (alyssawilk) [inline source/common/upstream/health_checker_impl.cc:325]: hm, if we get a reset we're going to close again.  looks like that's legal but seems weird - optionally, think it's worth a "are we still connected" check before we close up there?

It also makes me think it's probably worth having an end to end test for this, just to make sure it all hangs together smoothly when not mocking things out.

File: test/common/upstream/health_checker_impl_test.cc (hunk 4 above)
Comment (alyssawilk) [reply test/common/upstream/health_checker_impl_test.cc:2791]: SGTM :-)

File: source/common/upstream/health_checker_impl.cc (hunk 6 above)
Comment (alyssawilk) [reply source/common/upstream/health_checker_impl.cc:289]: yeah, closing if we can't reuse and the stream is reset seems fine, and it's behind the guard so even if someone gets surprised they can always revert the behavior

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks at a high level this LGTM. I will take a look again once Alyssa's comments are addressed.

/wait

File: source/common/upstream/health_checker_impl.cc (hunk 6 above)
Comment (mpuncel) [reply source/common/upstream/health_checker_impl.cc:289]: some of this behavior change is not guarded. It looks like the same case came up when implementing GOAWAY handling in gRPC.

There is a slight behavior change if you have connection reuse disabled, and get a reset stream. Previously the connection would be reused! which seems wrong, but is an unguarded behavior change.

Reference PR: https://github.com/envoyproxy/envoy/pull/11325

File: source/common/upstream/health_checker_impl.cc (hunk 8 above)
Comment (mpuncel) [reply source/common/upstream/health_checker_impl.cc:325]: it looks like I can just reorder things in `onResetStream()` to only close after checking `expect_reset_` and early exit.

I'll look into adding an end to end test, do you have any pointers to where there might be tests with similar setups?

**Comment by mpuncel** [comment]
addressed all feedback except the end-to-end test

**Comment by asraa** [comment]
@zasweq cc'ing you here -- in case you want to add as a follow up to https://github.com/envoyproxy/envoy/pull/13822

File: test/integration/health_check_integration_test.cc [hunk 9]
```diff
@@ -253,6 +253,46 @@ TEST_P(HttpHealthCheckIntegrationTest, SingleEndpointTimeoutHttp) {
...
+  initialize();
+  initHttpHealthCheck(cluster_idx);
+
+  // GOAWAY doesn't exist in HTTP1.
+  if (upstream_protocol_ != FakeHttpConnection::Type::HTTP1) {
+    // Send a GOAWAY with NO_ERROR and then a 200. The health checker should allow the request
+    // to finish despite the GOAWAY.
+    clusters_[cluster_idx].host_fake_connection_->onGoAway(Http::GoAwayErrorCode::Other);
+  }
+  clusters_[cluster_idx].host_stream_->onResetStream(Http::StreamResetReason::RemoteReset,
```
Comment (mpuncel) [inline test/integration/health_check_integration_test.cc:288]: I believe this is the case you were talking about wanting an end to end test for @alyssawilk

**Comment by mpuncel** [comment]
it's hard to tell but I think the build failed with "no space left on device" errors

File: test/integration/health_check_integration_test.cc (hunk 9 above)
Comment (mattklein123) [reply test/integration/health_check_integration_test.cc:290]: IMO it would be better to just guard this test and the above test for not HTTP/1, and avoid trying to test multiple things here.

Also, for HTTP/2, I'm not a spec expert, but I'm pretty sure that when sending GOAWAY with error != NOERROR it generally means a connection level error that will be immediately followed by closure, so I'm not sure this test is super accurate.

I think a better integration test for this would be to 1) Just do it for HTTP/2 and 2) Send a GOAWAY != NOERROR and make sure it's counted as a failure and the connection gets recreated?

@alyssawilk WDYT?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Generally LGTM with some small test comments. Thank you!

/wait

File: test/integration/health_check_integration_test.cc (hunk 9 above)
Comment (alyssawilk) [reply test/integration/health_check_integration_test.cc:290]: Yeah, H2 only SGTM.

Comment (mpuncel) [reply test/integration/health_check_integration_test.cc:290]: Thanks all, I'll update to only test H2.

@mattklein123 clarifying your last comment, what would "immediately followed by closure" look like? wouldn't that be a remote reset? I do think there's value in making sure a reset after an error goaway isn't double counted as a health check failure just not sure how to make that realistic. I think with the new code we most likely get a LocalReset because we close the connection when we see a GOAWAY with an error, so maybe that would be more realistic?

Comment (mattklein123) [reply test/integration/health_check_integration_test.cc:290]: What I meant is that a compliant impl should close the connection after sending GOAWAY != NOERROR. So in your test I would send GOAWAY != NOERROR, the close the connection. This should result in reset of the stream and disconnect, and then you could test that the next health check reconnects?

File: .github/workflows/codeql-push.yml [hunk 10]
```diff
@@ -59,7 +59,7 @@ jobs:
     - name: Clean Artifacts
       run: |
         git clean -xdf
-
```
Comment (mpuncel) [inline .github/workflows/codeql-push.yml:62]: not sure how this happened i'll revert

**Comment by mpuncel** [comment]
apologies for the force push, I forgot the signature on a commit before my `git merge master`. also the branch seems like it got into a weird state

File: test/integration/health_check_integration_test.cc [hunk 11]
```diff
@@ -253,6 +253,72 @@ TEST_P(HttpHealthCheckIntegrationTest, SingleEndpointTimeoutHttp) {
...
+  }
+
+  const uint32_t cluster_idx = 0;
+  initHttpHealthCheck(cluster_idx);
+
+  // Send a GOAWAY with an error. The health checker should treat this as an
+  // error and cancel the request.
+  clusters_[cluster_idx].host_fake_connection_->raiseProtocolError();
+  ASSERT_TRUE(clusters_[cluster_idx].host_fake_connection_->waitForDisconnect(
+      std::chrono::milliseconds(1000)));
```
Comment (mpuncel) [inline test/integration/health_check_integration_test.cc:295]: @mattklein123 I added this after your last round of comments, and confirmed this fails if I comment out `raiseProtocolError()`.

File: source/common/http/http2/codec_impl.h [hunk 12]
```diff
@@ -105,6 +105,11 @@ class ConnectionImpl : public virtual Connection, protected Logger::Loggable<Log
   void goAway() override;
   Protocol protocol() override { return Protocol::Http2; }
   void shutdownNotice() override;
+
+  // Send a GOAWAY frame with the PROTOCOL_ERROR code. This is used for
+  // integration testing and is not on the public interface.
+  void protocolError();
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.h:111]: Please name this `protocolErrorForTest`, same below.

File: test/integration/fake_upstream.cc [hunk 13]
```diff
@@ -344,6 +344,23 @@ void FakeHttpConnection::onGoAway(Http::GoAwayErrorCode code) {
   ENVOY_LOG(info, "FakeHttpConnection receives GOAWAY: ", code);
 }
 
+void FakeHttpConnection::raiseGoAway() {
```
Comment (mattklein123) [inline test/integration/fake_upstream.cc:347]: I'm pretty sure both of these functions need to use `executeOnDispatcher`.

Also, I would call them `sendGoAway` and `sendProtocolError` or `encodeGoAway`, etc. Whichever matches the other functions.

File: test/integration/health_check_integration_test.cc [hunk 14]
```diff
@@ -253,6 +253,72 @@ TEST_P(HttpHealthCheckIntegrationTest, SingleEndpointTimeoutHttp) {
   EXPECT_EQ(1, test_server_->counter("cluster.cluster_1.health_check.failure")->value());
 }
 
+// Tests that health checking gracefully handles a NO_ERROR GOAWAY from the upstream.
+TEST_P(HttpHealthCheckIntegrationTest, SingleEndpointGoAway) {
```
Comment (mattklein123) [inline test/integration/health_check_integration_test.cc:257]: As long as you have this test, can you also test that another health check creates a new connection?

File: test/integration/health_check_integration_test.cc (hunk 11 above)
Comment (mattklein123) [reply test/integration/health_check_integration_test.cc:295]: I would use the default timeout, 15s or whatever.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks generally LGTM with small comments. Thank you!

/wait

**Comment by mattklein123** [comment]
CI issue looks legit.

/wait

**Comment by mpuncel** [comment]
I'm stuck on the integration test flake. With print debugging I've seen that a successful run looks something like this:

```
mpuncel: encoding protocol error
mpuncel: done encoding protocol error
[2020-12-01 20:53:55.009][73967][debug][http2] [source/common/http/http2/codec_impl_legacy.cc:845] [C3] sent goaway code=11
[2020-12-01 20:53:55.010][73950][debug][hc] [source/common/upstream/health_checker_impl.cc:308] [C2] connection going away goaway_code=1, health_flags=/failed_active_hc
mpuncel: no connection in onInterval, making a new one
```

and a failed run looks like this, i.e. the `encodeProtocolErrorForTest()` finishes, but the codec never says "sent goaway" and then the test times out waiting for a disconnect that will never happen. You can see that ~10 seconds elapses between log messages:

```
[2020-12-01 20:53:44.705][72329][debug][client] [source/common/http/codec_client.cc:77] [C2] connected
mpuncel: encoding protocol error
mpuncel: session nil? 0
mpuncel: last stream ID1
mpuncel: done encoding protocol error
test/integration/health_check_integration_test.cc:317: Failure
Value of: clusters_[cluster_idx].host_fake_connection_->waitForDisconnect()
  Actual: false (Timed out waiting for disconnect.)
Expected: true
Stack trace:
  0x2114e82: Envoy::(anonymous namespace)::HttpHealthCheckIntegrationTest_SingleEndpointGoAwayError_Test::TestBody()
  0x4b4bbc4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4b3bebe: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4b24543: testing::Test::Run()
  0x4b2513d: testing::TestInfo::Run()
... Google Test internal frames ...

[2020-12-01 20:53:55.055][72365][debug][connection] [source/common/network/connection_impl.cc:117] [C3] closing data_to_write=0 type=0
```

**Comment by mpuncel** [comment]
I learned that if I add `sendPendingFrames()`, it throws an exception with "user callback function failed". but if I comment out the throw, then the test succeeds 100% of the time! I think that tells me that the test failures are due to the frame being queued and never sent, but not sure how to ensure it is sent without cla

**Comment by mattklein123** [comment]
cc @asraa @yanavlasov who have been looking at a lot of this code and might be able to help debug.

File: source/common/http/http2/codec_impl.cc [hunk 15]
```diff
@@ -855,6 +870,13 @@ int ConnectionImpl::onFrameSend(const nghttp2_frame* frame) {
   case NGHTTP2_GOAWAY: {
     ENVOY_CONN_LOG(debug, "sent goaway code={}", connection_, frame->goaway.error_code);
     if (frame->goaway.error_code != NGHTTP2_NO_ERROR) {
+      if (allow_protocol_error_frame_for_test_ &&
```
Comment (mpuncel) [inline source/common/http/http2/codec_impl.cc:873]: I got the tests passing reliably, but I had to add this hack so that we don't fail the nghttp2 callback. Let me know if there is a better approach

**Comment by mpuncel** [comment]
windows build looks like it failed on a `pip install` error?

File: source/common/http/http2/codec_impl.cc (hunk 15 above)
Comment (mattklein123) [reply source/common/http/http2/codec_impl.cc:873]: Can you explain a bit more about why this is required? In general this makes me really uncomfortable and at minimum I would request this is disabled by default, and only somehow enabled for the test in question, but I would really love to figure out some other way of doing this. I'm going to request a consultation with @asraa @yanavlasov @antoniovicente who are more familiar with all of this code at this point and can hopefully help advise better than I can. Thank you.

/wait

Comment (mpuncel) [reply source/common/http/http2/codec_impl.cc:873]: The original problem I was solving was ~3% of test runs would fail brecause the PROTOCOL_ERROR frame is never sent. To fix it I tried the following:

1) Call `sendPendingFrames()` in `protocolErrorForTest()`. This made the test fail 100% of the time because the user callback function returns an error code.
2) Instead of calling `sendPendingFrames()`, I tried calling `nghttp2_session_send()` (which is what `sendPendingFrames()` does) directly in `protocolErrorForTest()` and just tolerate the response code showing a callback error. At this point the test started failing ~.5% of the time because the frame would send twice. I don't know why this was happening, I speculate that if the user callback function fails nghttp2 still sends the frame, but the frame also remains in the queue so the next time `sendPendingFrames()` gets called it sends again?

In any case, it seems more straightforward to have the callback not fail. I totally understand being uncomfortable with this case which is why I called it out, maybe I can figure out a way of setting a different callback function in my test rather than changing the real one.

Comment (mattklein123) [reply source/common/http/http2/codec_impl.cc:873]: Yeah like I said at minimum we need to figure out how to do this only for test code, but I still want to try to understand the underlying problem. Hopefully one of the people that I pinged can help out. If not I will try to find time to take a look.

File: test/integration/fake_upstream.cc [hunk 16]
```diff
@@ -413,6 +414,43 @@ void FakeHttpConnection::onGoAway(Http::GoAwayErrorCode code) {
...
+}
+
+void FakeHttpConnection::encodeProtocolError() {
+  ASSERT(type_ == Type::HTTP2);
+
+  Http::Http2::ServerConnectionImpl* codec =
+      dynamic_cast<Http::Http2::ServerConnectionImpl*>(codec_.get());
+  if (codec != nullptr) {
+    shared_connection_.connection().dispatcher().post([this, codec]() {
+      expect_protocol_error_ = true;
```
Comment (mpuncel) [inline test/integration/fake_upstream.cc:430]: @mattklein123 this is basically the same approach as before, but I was able to move the hack into the fake upstream.

What the issue was is that when the nghttp2 callback fails, the upstream end of the connection gets closed, which then creates a race from the perspective of the health checker: it will either see the GOAWAY first and close its end of thee connection (good) or see the reset from the upstream (bad, causes timing issues in the test).

It's still not ideal, but it's at least limited only to the fake upstream, and this flag is only set in encodeProtocolError(). The benefit is that other tests that don't need to exercise protocol errors won't have their behavior changed.

Also I just wanted to say thanks for all of the time you've spent reviewing, I appreciate it. I've learned a lot from this PR so hopefully my next contribution will require less maintainer time :)

**Comment by mpuncel** [comment]
build failure looks due to coverage in source/common/http/http2/. I can look into adding a unit test for protocolErrorForTest()

File: source/common/http/http2/codec_impl.cc [hunk 17]
```diff
@@ -716,6 +716,16 @@ void ConnectionImpl::shutdownNotice() {
...
 }
 
+void ConnectionImpl::protocolErrorForTest() {
+  int rc = nghttp2_submit_goaway(session_, NGHTTP2_FLAG_NONE,
+                                 nghttp2_session_get_last_proc_stream_id(session_),
+                                 NGHTTP2_PROTOCOL_ERROR, nullptr, 0);
+  ASSERT(rc == 0);
+
+  if (sendPendingFrames().ok()) {
+  }
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.cc:726]: I would probably just return the error code here and assert it in the test itself.

File: source/common/http/http2/codec_impl.h [hunk 18]
```diff
@@ -532,6 +534,7 @@ class ConnectionImpl : public virtual Connection, protected Logger::Loggable<Log
   bool dispatching_ : 1;
   bool raised_goaway_ : 1;
   bool pending_deferred_reset_ : 1;
+  bool allow_protocol_error_frame_for_test_ : 1;
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.h:537]: Not needed anymore?

File: test/integration/fake_upstream.cc (hunk 16 above)
Comment (mattklein123) [reply test/integration/fake_upstream.cc:430]: Sorry which callback fails? You mean when you send the GOAWAY, this causes the fake upstream to close, and that sometimes races with the GOAWAY being received by the health checker? I guess we are doing a close without flush in this case? How often does it flake when you run the test with runs_per_test?

File: test/integration/fake_upstream.cc [hunk 19]
```diff
@@ -413,6 +414,43 @@ void FakeHttpConnection::onGoAway(Http::GoAwayErrorCode code) {
...
+      codec->protocolErrorForTest();
+      // We'd ideally set expect_protocol_error_ back to false after this, but
+      // it's difficult to sequence that correctly since it needs to be true
+      // until the PROTOCOL_ERROR goaway frame is flushed.
+    });
+    return;
```
Comment (mattklein123) [inline test/integration/fake_upstream.cc:436]: del

File: test/integration/fake_upstream.h [hunk 20]
```diff
@@ -436,7 +442,7 @@ class FakeHttpConnection : public Http::ServerConnectionCallbacks, public FakeCo
     Network::FilterStatus onData(Buffer::Instance& data, bool) override {
       Http::Status status = parent_.codec_->dispatch(data);
 
-      if (Http::isCodecProtocolError(status)) {
+      if (Http::isCodecProtocolError(status) && !parent_.expect_protocol_error_) {
```
Comment (mattklein123) [inline test/integration/fake_upstream.h:445]: I see this is the fix? I would think it would work though with the flush and write delay?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks for working through this. Just a few more comments.

/wait

File: test/integration/fake_upstream.cc (hunk 16 above)
Comment (mpuncel) [reply test/integration/fake_upstream.cc:430]: The `onFrameSend()` callback (which is what I modified in my previous approach) is what fails. Then in `onData()` in FakeHttpConnection::ReadFilter it closes the connection which causes the race. It failed ~1-3 times with --runs_per_test=500

I don't think the issue is that the frame not getting flushed, I'd consistently see "connection going away" in the logs on a failed run. It was just a timing issue where in the integration test we have this sequence:

```
  ASSERT_TRUE(clusters_[cluster_idx].host_fake_connection_->waitForDisconnect());
  timeSystem().advanceTimeWait(std::chrono::milliseconds(500));
```

We want `waitForDisconnect()` to mean that the health checker has seen the GOAWAY frame, and then enabled the interval timer to set up the next check. However on a test flake run, waitForDisconnect() gets triggered by the fake upstream itself closing, so then the clock is advanced before the interval timer has been enabled. If there is a different way of waiting for the health checker to see the frame and enable thee timer then that would also work, although that kind of takes some of the value out of asserting a disconnect, we do want to make sure that the health checker closes the connection immediately.

File: test/integration/fake_upstream.cc (hunk 19 above)
Comment (mpuncel) [reply test/integration/fake_upstream.cc:436]: If I remove this I need an `else` for the rest of the method, or not assert that one or the other `dynamic_cast` succeeds. Another option would be to make sure we never use the legacy codec? I don't have context on that migration, it seems like only in the `compile_time_options` test is the legacy codec used

File: test/integration/fake_upstream.h (hunk 20 above)
Comment (mpuncel) [reply test/integration/fake_upstream.h:445]: I answered in another comment too, but the issue isn't the flushing but the connection close prematurely causing my integration test to advance past `waitForDisconnect()`. I want to wait until the client closes rather than the upstream

File: test/integration/fake_upstream.cc (hunk 16 above)
Comment (mattklein123) [reply test/integration/fake_upstream.cc:430]: I see. Can you just wait on a stat emitted by the health checker? Then wait on the disconnect?

File: test/integration/fake_upstream.cc [hunk 21]
```diff
@@ -413,6 +414,37 @@ void FakeHttpConnection::onGoAway(Http::GoAwayErrorCode code) {
...
+
+  Http::Http2::ServerConnectionImpl* codec =
+      dynamic_cast<Http::Http2::ServerConnectionImpl*>(codec_.get());
+  if (codec != nullptr) {
+    shared_connection_.connection().dispatcher().post([this, codec]() {
+      expect_protocol_error_ = true;
+      Http::Status status = codec->protocolErrorForTest();
+      ASSERT(Http::getStatusCode(status) == Http::StatusCode::CodecProtocolError);
+    });
+  } else {
```
Comment (mattklein123) [inline test/integration/fake_upstream.cc:434]: Sorry I think I read the last diff about the brace wrong, apologies. I think this is also kind of strange though. Is the issue here that you need to do the dynamic cast on each type since we have 2 codecs and that is what the early return was before? This is pretty hacky though I guess the legacy code is going away soon so maybe not a huge deal. If you don't do this the tests don't pass on the legacy codec builds?

Comment (mpuncel) [reply test/integration/fake_upstream.cc:434]: yeah that's right. One option would be to not implement protocolErrorForTest() at all in the legacy codec, and have my test try to detect which codec is used and just skip if it's the legacy codec. I'm not sure how exactly that would work, seems like i'd need `#ifdef` from looking at how the codec is initialized? So not sure if that is any better than what I have

Comment (mpuncel) [reply test/integration/fake_upstream.cc:434]: Another option would be to use ifdef in this method. That might be easier for someone to find/clean up when the legacy codec is removed?

Comment (mattklein123) [reply test/integration/fake_upstream.cc:434]: I think it's fine to do this as the code won't compile when the legacy codec is removed. Can you add a TODO though to make it clear?

File: test/integration/fake_upstream.cc (hunk 16 above)
Comment (mpuncel) [reply test/integration/fake_upstream.cc:430]: I would need to reorder when stats are incremented, because that happens before the interval timer is enabled. Would that be preferable to this change?

Comment (mattklein123) [reply test/integration/fake_upstream.cc:430]: I think it would be less hacky, but why does the stat need to be reordered? Is the issue that you need the connection attempted stat because this doesn't count as a failure?

Comment (mpuncel) [reply test/integration/fake_upstream.cc:430]: the issue is that we're using simulated time, so I have to call `  timeSystem().advanceTimeWait(std::chrono::milliseconds(500));` to advance time to trigger another health check. But that only works if the timer has been enabled before I advance the time system. So I need something I can wait on in the test that tells me that the health checker has enabled the timer. The client connection close does happen after the timer is enabled, but stats are incremented before which doesn't make them suitable to wait on.

Comment (mattklein123) [reply test/integration/fake_upstream.cc:430]: I'm not following you. What stats are available? Is the issue that there is no stat when the GOAWAY is received?

**Comment by alyssawilk** [comment]
Preconnect SGTM.  I'll swap it out Monday :-)

File: test/integration/fake_upstream.cc (hunk 16 above)
Comment (mpuncel) [reply test/integration/fake_upstream.cc:430]: Basically the existing stats are incremented too early for them to be useful for my test to wait on, it may still be "too soon" to advance time.

If I add a new stat for GOAWAY errors (which is maybe useful anyway?) I can increment it after the health check interval timer is enabled and solve it that way. I'll push a new commit with that approach

Comment (mattklein123) [reply test/integration/fake_upstream.cc:430]: Yes I would add a stat for "close_notify" or similar like we do on the data plane side. Please check that stat name. Also, please remember to doc the new stat. Otherwise sgtm. Thanks!

Comment (mpuncel) [reply test/integration/fake_upstream.cc]: I didn't see this comment until after my most recent commit with the stat named `goaway_error`. It looks like `close_notify` is used for graceful close, e.g. `Connection: close` in HTTP/1. Here we're talking about an ungraceful close since the GOAWAY has a code other than `NO_ERROR`. Is that stat name still appropriate? If so, I should probably also increment it in the NO_ERROR and HTTP/1 Connection: close cases

Comment (mattklein123) [reply test/integration/fake_upstream.cc]: I don't see where you incremented the new stat anywhere in the code you pushed. Also, you have lost me at this point. If this is a sub-class of a network error why can't you wait on the failure stat?

Comment (mpuncel) [reply test/integration/fake_upstream.cc]: I apparently did not commit the 1 line where I incremented it 🤦

Comment (mpuncel) [reply test/integration/fake_upstream.cc]: I can use the failure stat instead, IF I move the the stat `inc()` call to after `interval_timer_->enableTimer();`

File: source/common/upstream/health_checker_impl.cc [hunk 22]
```diff
@@ -281,15 +284,52 @@ void HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onInterval() {
...
+    reuse_connection_ = false;
+    return;
+  }
+
+  if (request_in_flight_) {
+    // Record this as a failed health check.
+    handleFailure(envoy::data::core::v3::NETWORK);
+  }
+
+  parent_.stats_.goaway_error_.inc();
```
Comment (mpuncel) [inline source/common/upstream/health_checker_impl.cc:326]: @mattklein123 this line has to be after `handleFailure()` or my test will flake. If you dig into `handleFailure()`, it increments the general health check failure stat, and then enables the interval timer. So order is:

1) health failure increment
2) health check timer enabled
3) goaway_error increment.

I need something that will reliably happen after the health check timer. 999/1000 times, waiting for client disconnect is good enough (because of the `client_->close()` on line 329) but the other 1 time the fake upstream was closing first, which would cause my test to advance too quickly and advance simulated time before the timer was enabled.

Comment (mattklein123) [reply source/common/upstream/health_checker_impl.cc:326]: OK really sorry for all the back and forth here, but this is pretty tricky and I'm trying to leave the code as clean as possible.

I think there are two options here that are both fine:
1) Swap the order of (1) and (2). I can't see any huge reason this would cause a problem and if it makes the tests cleaner that is fine with me.
2) Stop using simulated time. I think that would also work since you wouldn't have to actually advance and you could just wait?

I would be fine either way but I think this is simpler?

File: test/common/http/http2/codec_impl_test.cc [hunk 23]
```diff
@@ -360,6 +360,30 @@ TEST_P(Http2CodecImplTest, ShutdownNotice) {
   response_encoder_->encodeHeaders(response_headers, true);
 }
 
+TEST_P(Http2CodecImplTest, ProtocolErrorForTest) {
```
Comment (mattklein123) [inline test/common/http/http2/codec_impl_test.cc:363]: I think you cover this now in the integration test? Do we need this? Then the hack with the dynamic cast is only in one place.

File: test/common/upstream/health_check_fuzz_test_utils.h [hunk 24]
```diff
@@ -48,6 +48,7 @@ class HttpHealthCheckerImplTestBase : public HealthCheckerTestBase {
     Network::MockClientConnection* client_connection_{};
     NiceMock<Http::MockRequestEncoder> request_encoder_;
     Http::ResponseDecoder* stream_response_callbacks_{};
+    CodecClientForTest* codec_client_{};
```
Comment (mattklein123) [inline test/common/upstream/health_check_fuzz_test_utils.h:51]: Are these changes needed?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks for powering through this. Almost there and appreciate your willingness to iterate on this non-trivial change.

/wait

File: source/common/upstream/health_checker_impl.cc (hunk 22 above)
Comment (mpuncel) [reply source/common/upstream/health_checker_impl.cc:326]: No worries about the back and forth! I'm happy to do whatever it takes to get it right.

Both of those options should work, using real time might make the test a bit slower though. I couldn't tell in your last sentence which one you were saying is simpler?

File: test/common/http/http2/codec_impl_test.cc (hunk 23 above)
Comment (mpuncel) [reply test/common/http/http2/codec_impl_test.cc:363]: I needed it because the code coverage for source/common/http/http2 dropped too low without it

File: test/common/upstream/health_check_fuzz_test_utils.h (hunk 24 above)
Comment (mpuncel) [reply test/common/upstream/health_check_fuzz_test_utils.h:51]: yeah, I have to capture the codec_client_ because that's what I call `raiseGoAway(_)` on

Comment (mattklein123) [reply test/common/upstream/health_check_fuzz_test_utils.h:51]: Oh I see sorry didn't realize this was used elsewhere.

File: source/common/upstream/health_checker_impl.cc (hunk 22 above)
Comment (mattklein123) [reply source/common/upstream/health_checker_impl.cc:326]: Either is fine with me. I think they are both simple and I'm not worried about test speed when using real time.

**Comment by mpuncel** [comment]
Apologies for the force push, forgot DCO on a commit (and the auto signing has never worked for me for some reason).

File: test/integration/health_check_integration_test.cc [hunk 25]
```diff
@@ -319,9 +319,20 @@ TEST_P(HttpHealthCheckIntegrationTest, SingleEndpointGoAwayError) {
...
+  // the health check interval timer so we can advance simulated time to cause
+  // another check. However, due to special handling for protocol errors, there
+  // is a race where both the downstream (health checker) and upstream (fake
+  // upstream) close the connection, so we may exit waitForDisconnect() before
+  // the health checker has actually seen the GOAWAY and enabled the timer. To
+  // address this, we use a small real sleep before advancing thee simulated
+  // time system to give the health checker time to catch up. If we advance time
+  // before the health check timer is enabled, the next health check will never
+  // happen.
+  timeSystem().realSleepDoNotUseWithoutScrutiny(std::chrono::milliseconds(100));
```
Comment (mattklein123) [inline test/integration/health_check_integration_test.cc:335]: Sorry to keep going back and forth on this, but maybe we should talk on Slack. It's not OK to use a real sleep here since it will flake. Please either stop using simulated time entirely, or just do what we talked about before and wait on the stat. It's not clear to me that simulated time is the best use for this case? Since you are just waiting for an HC failure to occur and then another reconnect?

/wait

**Comment by mattklein123** [comment]
Can you merge main to fix OSX CI and I can take a final pass?

/wait

**Comment by mattklein123** [comment]
LGTM, needs a main merge since we just cut the release, thanks.

/wait
