### PR TITLE
lua: fix default `trace_sampled` on `httpCall`

### LINKED ISSUE #33164: Tracing: Lua `httpCall` requests are sampled regardless of the sampling decision for the overall request
*Title*: Lua [`httpCall`](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#httpcall) requests are sampled regardless of the sampling decision for the overall request

*Description*:
If you have a tracer configured on your connection manager and make any `httpCall`s from a Lua filter, spans from the resulting call are sampled by default and are sent to the tracing provider regardless of whether the downstream request itself is to be sampled, e.g. as a result of `random_sampling`. This results in orphaned spans if the downstream request is not being sampled; the `httpCall` span is sent but no other spans from the trace are.

You can disable sampling for the `httpCall` span using the `trace_sampled` option, but not in a way that comports with `random_sampling`, as (as far as I know) there is no way to determine that sampling decision in Lua. (Perhaps you can write a native filter that projects the trace context's `sampled` flag into dynamic metadata, but that is a high bar for users to clear.)

I think the default value of `httpCall`'s [`trace_sampled` flag](https://github.com/envoyproxy/envoy/blob/7f6df241c61094c6e1ec26c8d1acf05f5803a32c/source/extensions/filters/http/lua/lua_filter.cc#L54-L58) should change from [`true`](https://github.com/envoyproxy/envoy/blob/7f6df241c61094c6e1ec26c8d1acf05f5803a32c/envoy/http/async_client.h#L426-L427), to one derived from the trace context for the request.

*Repro steps*:
I will make a minimal reproduction when I have time, hopefully within the next few hours; sorry.

### PR DESCRIPTION
**Pull request by isker**
Commit Message:
lua: fix default `trace_sampled` on `httpCall`

Default to using the parent span's `sampled` status instead of `true`, so that we don't emit orphan spans for all `httpCall`s where the parent span is not sampled.

Fixes #33164.

Additional Description: 
The same fix was applied to `ext_authz` spans in https://github.com/envoyproxy/envoy/pull/19343. CC @alyssawilk who approved that change.

Risk Level:
Low. I think the status quo is both buggy, generating nonsense/orphaned spans, and operationally dangerous, in that if you are expecting to sample only a small fraction of traffic based upon your tracing config (e.g. low/zero `random_sampling`), envoy will be sending way more spans than expected to the tracing backend.

The fact that the same kind of fix was previously applied in `ext_authz` should give us confidence that this is change is good.

Testing:
Added brief unit test coverage.

Docs Changes:
Updated the description of the `trace_sampled` flag to describe this default.

Release Notes: Yes.

Platform Specific Features: N/A

### CODE REVIEW

**Comment by wbpcode** [comment]
Similar to https://github.com/envoyproxy/envoy/pull/19343.

Considering we do similar things in the #19343, I inclined not to introduce new runtime guard here. @envoyproxy/runtime-guard-changes

File: source/extensions/filters/http/lua/lua_filter.cc [hunk 1]
```diff
@@ -372,7 +378,6 @@ int StreamHandleWrapper::luaHttpCall(lua_State* state) {
     options.is_async_request_ = lua_toboolean(state, AsyncFlagIndex);
   }
 
-  options.request_options_.setParentSpan(callbacks_.activeSpan());
```
Comment (isker) [inline source/extensions/filters/http/lua/lua_filter.cc:375]: I don't strictly need to move this line up higher, but it is semantically related to the `setSampled` call, which does need to sit at the top of the method body, so that it can be overridden by the `trace_sampled` option.

Nothing else in here can call `setParentSpan`.

File: changelogs/current.yaml [hunk 2]
```diff
@@ -94,6 +94,12 @@ minor_behavior_changes:
     Disables recvmmsg (multi-message) for reading packets from a client QUIC UDP socket, if GRO
     is not set or not supported. recvmsg will be used instead. This behavior change can be
     reverted by setting ``envoy.reloadable_features.disallow_quic_client_udp_mmsg`` to ``false``.
+- area: lua
+  change: |
+    Previously, tracing spans generated by ``httpCall`` were always sampled by default.
+    Now, the default sampling decision is inherited from the parent span, so that no "orphaned"
+    sampled span associated with the ``httpCall`` is emitted. The default remains overridable
+    with the ``trace_sampled`` option.
```
Comment (wbpcode) [inline changelogs/current.yaml:102]: nit: Please point out that we only change the default value in lua:

`... Now, the default sampling decision in lua is .....`

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks. And defer this to @mattklein123 to merge because this minor behavior change and he may have other comments.

File: changelogs/current.yaml (hunk 2 above)
Comment (isker) [reply changelogs/current.yaml]: How's this?

**Review by wbpcode — DISMISSED** [review]

**Comment by soulxu** [comment]
gentle ping @mattklein123

**Review by mattklein123 — APPROVED** [review]
LGTM please merge main.

/wait

**Comment by isker** [comment]
@wbpcode @mattklein123 that's done.

**Review by wbpcode — APPROVED** [review]

**Comment by isker** [comment]
Thanks!
