### PR TITLE
admin: fix the EDS_STATUS_DRAINING map

### LINKED ISSUE #32799: Admin EDS_STATUS_DRAINING setting bug.
#30622 Introduce a bug for the admin EDS_STATUS_DRAINING setting,

we should check it is actually set before setting DRAINING.

Fixing.

### PR DESCRIPTION
**Pull request by botengyao**
fix the EDS_STATUS_DRAINING map introduced in #30622

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #32799

### CODE REVIEW

File: source/server/admin/clusters_handler.h [hunk 1]
```diff
@@ -13,6 +14,9 @@
 namespace Envoy {
 namespace Server {
 
+void setHealthFlag(Upstream::Host::HealthFlag flag, const Upstream::Host& host,
```
Comment (jmarantz) [inline source/server/admin/clusters_handler.h:17]: Can you add a doxygen comment? It's a in the Envoy::Server space but it is realy just mutating an admin proto. At first glance I thought it might be mutating the health status in the host.

File: test/server/admin/clusters_handler_test.cc [hunk 2]
```diff
@@ -243,5 +245,70 @@ fake_cluster::1.2.3.4:80::local_origin_success_rate::93.2
...
+
+  // FAILED_OUTLIER_CHECK
+  host->healthFlagSet(Upstream::Host::HealthFlag::FAILED_OUTLIER_CHECK);
+  setHealthFlag(Upstream::Host::HealthFlag::FAILED_OUTLIER_CHECK, *host, health_status);
+  EXPECT_TRUE(health_status.failed_outlier_check());
+
+  // FAILED_EDS_HEALTH
+  host->healthFlagSet(Upstream::Host::HealthFlag::FAILED_EDS_HEALTH);
+  setHealthFlag(Upstream::Host::HealthFlag::FAILED_EDS_HEALTH, *host, health_status);
+  EXPECT_EQ(health_status.eds_health_status(), envoy::config::core::v3::UNHEALTHY);
```
Comment (jmarantz) [inline test/server/admin/clusters_handler_test.cc:267]: thanks for filling in all these missing tests. Was this all previously uncovered by tests? Maybe we should increase the coverage expectation.

File: source/server/admin/clusters_handler.h [hunk 3]
```diff
@@ -14,6 +14,13 @@
 namespace Envoy {
 namespace Server {
 
+/**
+ * A utility to retrieve admin health status information from a specified host.
```
Comment (jmarantz) [inline source/server/admin/clusters_handler.h:18]: actually, given how this is worded, WDYT of renaming this getHealthFlag and having it return the status?

Maybe that's out of scope for this PR, but would that make more sense?

Comment (botengyao) [reply source/server/admin/clusters_handler.h:18]: yes, makes sense, can I refactor it as a follow up?

Comment (jmarantz) [reply source/server/admin/clusters_handler.h:18]: sure. WDYT about tightening coverage for this PR?

File: test/server/admin/clusters_handler_test.cc (hunk 2 above)
Comment (botengyao) [reply test/server/admin/clusters_handler_test.cc:267]: I don't see the specific test cover this utility, but just [one json unit test](https://github.com/envoyproxy/envoy/pull/32801/files#diff-7fc8d177a372e19dab401678b8126faea43dff984156aad5e39ca74a795f9bebR18). It is using `oncall.return(true)`, so the coverage is same (96.1).

Comment (botengyao) [reply test/server/admin/clusters_handler_test.cc:267]: taking a second look.

Comment (jmarantz) [reply test/server/admin/clusters_handler_test.cc:275]: you are saying all the lines covered by this new test were already covered?

Comment (botengyao) [reply test/server/admin/clusters_handler_test.cc:275]: For this specific bug, the coverage system does not distinguish the

```
ON_CALL(*host, healthFlagGet(Upstream::Host::HealthFlag::EDS_STATUS_DRAINING))
      .WillByDefault(Return(true));
```
or `Return(false)` by marking it was tested. If we return false, the tests should fail, since the buggy code always assume the flag is set without checking it is false or not.

Comment (jmarantz) [reply test/server/admin/clusters_handler_test.cc:275]: I see; we were hitting the lines, just not in a meaningful way; SGTM.

**Review by jmarantz — APPROVED** [review]

**Comment by jmarantz** [comment]
@ggreenway for senior maintainer stamp

**Review by ggreenway — APPROVED** [review]
