### PR TITLE
http: tracking active session under L7 timers

### LINKED ISSUE #7300: Improve Envoy crash logging
While core dumps are often better for in-depth debugging we've found that a high percentage of bugs can be debugged a bit more quickly with a combination of stack trace and information about the stream which caused the crash.

To start with I'd love to replicate what we have for L7 debugging in-house, where we track and dump active session.   Essentially each active stream in each worker thread registers itself with a scoped thread-local object on all dispatcher entry points, and the crash signal handler logs a bunch of information about active stream on segfault.  This is super useful for debug but for consistent state dumping, every alarm and IO entry point has to create a scoped tracker for traces (worse case you just miss out on debug info)

It'd be a bunch of code churn but I don't think it's terrible to have an Printable interface with dumpState() function which various  stream / hcm / connection interfaces can implement, and have L7 alarms and IO entry points (interested folks could implement for L4 as well, if inclined, we'd likely not need that for some time) which latch a thread-local-storage Printable interface for the stream.   the dumpState functions can also be quite helpful in debug/error logging, especially for ASSERTs/RELEASE_ASSERT as they generally have enough information about state to help assess what went wrong.

Checking in with @envoyproxy/maintainers before I go off code spelunking, both for if we're up for the extra APIage and plumbing, and if you all have lower hanging fruit which might make sense to tackle first.

### PR DESCRIPTION
**Pull request by alyssawilk**
Tracking active session under the scope of L7 timers

Risk Level: Medium (L7 changes)
Testing: new UT
Docs Changes: n/a
Release Notes: n/a
Fixes #7300

### CODE REVIEW

File: source/common/router/router.cc [hunk 1]
```diff
@@ -1539,6 +1539,7 @@ void Filter::UpstreamRequest::onPoolFailure(Http::ConnectionPool::PoolFailureRea
 
 void Filter::UpstreamRequest::onPoolReady(Http::StreamEncoder& request_encoder,
                                           Upstream::HostDescriptionConstSharedPtr host) {
+  ScopeTrackerScopeState scope(&parent_.callbacks_->scope(), parent_.callbacks_->dispatcher());
```
Comment (mattklein123) [inline source/common/router/router.cc]: IIRC this can happen synchronously during decode headers. I assume double scope tracking works OK? Might be worth a comment?

File: source/extensions/filters/http/fault/fault_filter.h [hunk 2]
```diff
@@ -144,12 +145,13 @@ class StreamRateLimiter : Logger::Loggable<Logger::Id::filter> {
...
    * @param time_source the time source to run the token bucket with.
    * @param dispatcher the stream's dispatcher to use for creating timers.
+   * @param scope the stream's scope
    */
   StreamRateLimiter(uint64_t max_kbps, uint64_t max_buffered_data,
                     std::function<void()> pause_data_cb, std::function<void()> resume_data_cb,
                     std::function<void(Buffer::Instance&, bool)> write_data_cb,
                     std::function<void()> continue_cb, TimeSource& time_source,
-                    Event::Dispatcher& dispatcher);
+                    Event::Dispatcher& dispatcher, const ScopeTrackedObject* scope = nullptr);
```
Comment (mattklein123) [inline source/extensions/filters/http/fault/fault_filter.h]: Should this ever actually be null? Should we make this a reference?

**Comment by alyssawilk** [comment]
I think this is most of the per stream timers?  Let me know if there are other areas I should have looked

grep -rl enableTimer source/extensions/filters/http/* source/extensions/filters/common/*
source/extensions/filters/http/fault/fault_filter.cc  <- here
source/extensions/filters/http/health_check/health_check.cc <- for cache results
source/extensions/filters/http/squash/squash_filter.cc <- here

alyssar@alyssar:~/git/envoy$ grep -rl enableTimer source/common/http/*
source/common/http/codec_client.h <- per codec not per stream
source/common/http/conn_manager_impl.cc  <- connection timer and request timeout (added)
source/common/http/date_provider_impl.cc < tls refresh
source/common/http/http1/conn_pool.cc <- onPoolReady and onPoolFailure now covered
source/common/http/http2/conn_pool.cc <- onPoolReady and onPoolFailure now covered
source/common/http/rest_api_fetcher.cc <- I think not on data plane.

**Comment by mattklein123** [comment]
I'm surprised there are so few places but yeah seems like a good first cut to me.

I have a more general question which is how human scalable this solution is going to be. If there are so few call sites, WDYT about actually adding this to `enableTimer()` itself and other similar call sites? Basically a scope tracker could be optionally passed into each of the dispatcher functions. I think this could be less awful than it sounds by having a `ScopeTrackingDispatcher` that exposes the current functions as is, but wraps the lower level dispatcher with the scope in various cases. This is roughly the solution I have discussed with @htuch for multi-tenant charging and fairness. Anyway, this is probably more work than you want to take on right now, but I'm wondering if we should work in that direction? Mainly because I think it's going to be very easy to not add new scope trackers for new timers, etc. as they get added to the code.

/wait-any

**Comment by alyssawilk** [comment]
Yeah, I'd thought of doing that not for the dispatcher in general (which is operating on the level of connnections, which we want to deal with eventually but not today), but for alarms (since there's a bunch of those in the L7 scope).  My take-away after doing a bit of code analysis was that maybe 1/3 of the call sites where I want to track incoming alarm ended up not being done at the alarm (e.g the connection pool callbacks), at which point trying to create a generalized solution I couldn't use everywhere didn't seem worth tackling today.  
That said, given that the dispatcher takes a scope pointer, it wouldn't be horribly painful to have createTimer take an optional (default null) scope, and have TimerImpl::TimerImpl do the scope tracking before it calls the callback, for the 2/3 which use timers, if you'd prefer I lay that groundwork now?

**Comment by mattklein123** [comment]
> That said, given that the dispatcher takes a scope pointer, it wouldn't be horribly painful to have createTimer take an optional (default null) scope, and have TimerImpl::TimerImpl do the scope tracking before it calls the callback, for the 2/3 which use timers, if you'd prefer I lay that groundwork now?

+1 this would be awesome if are up for it. Might be worth it to briefly sync up with @htuch on this and see if he has any thoughts as it relates to the multi-tenancy work.

**Comment by htuch** [comment]
Yeah, I'm still not sure exactly which multi-tenant isolation path we want to do ideally; it could either be dispatcher per tenant, in which case we don't need any special sauce here or it could be multiple tenants with a scope aware dispatcher. The structural approach @mattklein123 is advocating would be useful in enabling the latter and SGTM providing it doesn't make the code unreadable or introduce too much boilerplate :)

**Comment by alyssawilk** [comment]
This ended up being large enough I'm inclined to split out the alarm changes into their own PR, and using them in this one.  WDYT?

**Comment by mattklein123** [comment]
> This ended up being large enough I'm inclined to split out the alarm changes into their own PR, and using them in this one. WDYT?

+1 that would be great, thanks.

/wait
