### PR TITLE
stats: convert tag extractor regexs to Re2

### LINKED ISSUE #14439: std::regex overhead is too high during CDS updates
Locally we have seen flame-graphs implicating the regex parsing in tag-extraction taking significant amount of time, even though the heaviest regex has now been converted to RE2. Combined, all the other ones are still a CPU bottleneck.

If you simply convert the `addRegex` calls in source/common/config/well_known_names.cc to `addRe2` the following RE2 compilation errors are reported when running unit tests:
```
 RUN      ] UtilityTest.createTagProducer
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^http(?=\.).*?\.dynamodb\.table(?=\.).*?\.capacity(?=\.).*?(\.__partition_id=(\w{7}))$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^http(?=\.).*?\.dynamodb.(?:operation|table(?=\.).*?\.capacity)(\.(.*?))(?:\.|$)': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^mongo(?=\.).*?\.collection(?=\.).*?\.callsite\.((.*?)\.).*?query.\w+?$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^http(?=\.).*?\.dynamodb.(?:table|error)\.((.*?)\.)': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^mongo(?=\.).*?\.collection\.((.*?)\.).*?query.\w+?$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^mongo(?=\.).*?\.cmd\.((.*?)\.)\w+?$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^cluster(?=\.).*?\.grpc(?=\.).*\.((.*?)\.)\w+?$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^http(?=\.).*?\.user_agent\.((.*?)\.)\w+?$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^vhost(?=\.).*?\.vcluster\.((.*?)\.)\w+?$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^http(?=\.).*?\.fault\.((.*?)\.)\w+?$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^listener(?=\.).*?\.ssl\.cipher(\.(.*?))$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^cluster(?=\.).*?\.ssl\.ciphers(\.(.*?))$': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^cluster(?=\.).*?\.grpc\.((.*?)\.)': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^listener(?=\.).*?\.http\.((.*?)\.)': invalid perl operator: (?=
external/com_googlesource_code_re2/re2/re2.cc:205: Error parsing '^http(?=\.).*?\.rds\.((.*?)\.)\w+?$': invalid perl operator: (?=
test/common/config/utility_test.cc:107: Failure
Expected equality of these values:
  extracted_name
    Which is: "http.config_test.rq_total"
  "http.rq_total"
Stack trace:
  0x18859b4: Envoy::Config::(anonymous namespace)::UtilityTest_createTagProducer_Test::TestBody()
  0x3dda514: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x3dc8fdb: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x3db4a73: testing::Test::Run()
  0x3db5447: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] UtilityTest.createTagProducer (97 ms)
```

### PR DESCRIPTION
**Pull request by rojkov**
Commit Message: stats: convert tag extractor regexs to Re2
Additional Description:
Risk Level: high, the regexes are updated to match more specific patterns.
Testing: unit tests
Docs Changes: N/A
Release Notes: N/A
Fixes #14439

### CODE REVIEW

**Comment by rojkov** [comment]
The added benchmark gives these numbers for the currently used regexes
```
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations
-----------------------------------------------------------
bmExtractTags/0        5489 ns         5482 ns       116242
bmExtractTags/1        1750 ns         1747 ns       404362
bmExtractTags/2        1346 ns         1344 ns       507597
bmExtractTags/3        1705 ns         1703 ns       412873
bmExtractTags/4        2645 ns         2641 ns       271216
bmExtractTags/5        1555 ns         1553 ns       450419
bmExtractTags/6         622 ns          622 ns      1164196
bmExtractTags/7        1662 ns         1659 ns       423913
bmExtractTags/8        4497 ns         4491 ns       152800
bmExtractTags/9        4064 ns         4058 ns       173024
bmExtractTags/10       4959 ns         4951 ns       145306
bmExtractTags/11        911 ns          910 ns       754577
bmExtractTags/12        894 ns          893 ns       791770
bmExtractTags/13       6537 ns         6528 ns       105229
bmExtractTags/14      10092 ns        10077 ns        68439
bmExtractTags/15       5058 ns         5051 ns       136795
bmExtractTags/16       3404 ns         3399 ns       207761
bmExtractTags/17       3361 ns         3356 ns       214349
bmExtractTags/18       3292 ns         3287 ns       212676
bmExtractTags/19       2049 ns         2046 ns       341955
bmExtractTags/20       1080 ns         1078 ns       640417
bmExtractTags/21       1233 ns         1231 ns       565355
bmExtractTags/22       1583 ns         1581 ns       446222
bmExtractTags/23       2463 ns         2460 ns       288727
bmExtractTags/24       2427 ns         2424 ns       276382
bmExtractTags/25        505 ns          505 ns      1361377
bmExtractTags/26        277 ns          276 ns      2503746
bmExtractTags/27       3651 ns         3646 ns       185178
```

With regexes converted to RE2
```
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations
-----------------------------------------------------------
bmExtractTags/0        1832 ns         1829 ns       382449
bmExtractTags/1         512 ns          512 ns      1361810
bmExtractTags/2         808 ns          807 ns       879382
bmExtractTags/3        1254 ns         1252 ns       554894
bmExtractTags/4        1336 ns         1334 ns       525821
bmExtractTags/5         858 ns          857 ns       824452
bmExtractTags/6         339 ns          339 ns      2086426
bmExtractTags/7         991 ns          989 ns       701679
bmExtractTags/8        2850 ns         2847 ns       239643
bmExtractTags/9        2541 ns         2537 ns       278245
bmExtractTags/10       3400 ns         3395 ns       208227
bmExtractTags/11        716 ns          715 ns       937773
bmExtractTags/12        510 ns          509 ns      1382508
bmExtractTags/13       2973 ns         2968 ns       231524
bmExtractTags/14       4958 ns         4950 ns       141460
bmExtractTags/15       3606 ns         3601 ns       194652
bmExtractTags/16       2104 ns         2100 ns       338673
bmExtractTags/17       1204 ns         1203 ns       566432
bmExtractTags/18       1226 ns         1224 ns       582547
bmExtractTags/19       1273 ns         1271 ns       529859
bmExtractTags/20        867 ns          866 ns       819005
bmExtractTags/21       1157 ns         1156 ns       606544
bmExtractTags/22       1370 ns         1368 ns       518921
bmExtractTags/23       1567 ns         1565 ns       447355
bmExtractTags/24       2137 ns         2134 ns       323261
bmExtractTags/25        319 ns          318 ns      2231632
bmExtractTags/26        296 ns          295 ns      2330274
bmExtractTags/27        500 ns          499 ns      1402414
```

I assumed that `<operation_name>`, `<table_name>`, `<callsite>` tags and some others can't contain dots in their values.
`<stat_prefix>`, `<virtual_host_name>` can contain dots (though not in the case of  `http.(<stat_prefix>.)*` - this is also the current behavior). The benchmark results would be better if neither could contain dots. Particularly for `tcp.(<stat_prefix>.)<base_stat>`, `udp.(<stat_prefix>.)<base_stat>`, `auth.clientssl.(<stat_prefix>.)<base_stat>` the result could be 3 times better, because there would be no need to maintain full match (that is to have `\w+?$` at the end of the patterns).

File: source/common/config/well_known_names.cc [hunk 1]
```diff
@@ -24,97 +24,100 @@ TagNameValues::TagNameValues() {
...
-  addRe2(CLUSTER_NAME, "^cluster\\.(([^\\.]+)\\.).*");
+  addRe2(CLUSTER_NAME, R"(^cluster\.(([\w-]+)\.))");
 
   // listener.[<address>.]http.(<stat_prefix>.)*
-  addRegex(HTTP_CONN_MANAGER_PREFIX, R"(^listener(?=\.).*?\.http\.((.*?)\.))", ".http.");
+  addRe2(HTTP_CONN_MANAGER_PREFIX, R"(^listener\.(?:.*?\.)?http\.(([\w-]+)\.))", ".http.");
 
   // http.(<stat_prefix>.)*
-  addRegex(HTTP_CONN_MANAGER_PREFIX, "^http\\.((.*?)\\.)");
+  addRe2(HTTP_CONN_MANAGER_PREFIX, R"(^http\.(([\w-]+)\.))");
```
Comment (rojkov) [inline source/common/config/well_known_names.cc:103]: BTW, is it OK to have two patterns with the same name like in the lines 100 and 103?

**Review by jmarantz — COMMENTED** [review]
This in general looks right to me, though I wonder if we can have even more speedup by hand-tweaking each RE2 more. I don't have any specific ideas, but that could also be done as a follow-up, maybe once informed by actual need once https://github.com/envoyproxy/envoy/pull/14167 lands and we can understand detailed regex overheads in context.

Can you also confirm that we have correctness test for each regex? I think we probably do, but it is worth making sure.

**Comment by rojkov** [comment]
I checked every regex has a corresponding test. Also I modified the tests to contain dashes where they can be theoretically used.

From the old regexes for UDP, TCP, HTTP prefixes and others I inferred that dots are not allowed in `<stat_prefix>`, so this led to getting rid of some unneeded complexity. Then I realized that "stat_name is not mutated until all the extraction is done". This let me simplify the regexes even more.

Now the benchmarks for the old and new regexes look like this

old
```
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations
-----------------------------------------------------------
bmExtractTags/0        5534 ns         5526 ns       118957
bmExtractTags/1        1734 ns         1732 ns       405390
bmExtractTags/2        1294 ns         1292 ns       539449
bmExtractTags/3        1678 ns         1676 ns       417579
bmExtractTags/4        2559 ns         2555 ns       270832
bmExtractTags/5        1484 ns         1482 ns       471794
bmExtractTags/6         607 ns          606 ns      1186264
bmExtractTags/7        1616 ns         1614 ns       436987
bmExtractTags/8        4517 ns         4510 ns       156829
bmExtractTags/9        3991 ns         3985 ns       174039
bmExtractTags/10        886 ns          885 ns       809248
bmExtractTags/11        880 ns          879 ns       818406
bmExtractTags/12       6712 ns         6701 ns       105144
bmExtractTags/13      10088 ns        10072 ns        69762
bmExtractTags/14       5113 ns         5105 ns       135417
bmExtractTags/15       3366 ns         3361 ns       212136
bmExtractTags/16       3291 ns         3286 ns       213164
bmExtractTags/17       3304 ns         3299 ns       208676
bmExtractTags/18       2014 ns         2012 ns       351865
bmExtractTags/19       1062 ns         1060 ns       662142
bmExtractTags/20       1217 ns         1215 ns       574421
bmExtractTags/21       1539 ns         1537 ns       450240
bmExtractTags/22       2452 ns         2449 ns       281554
bmExtractTags/23       2413 ns         2409 ns       290230
bmExtractTags/24        495 ns          494 ns      1426162
bmExtractTags/25        282 ns          282 ns      2444675
bmExtractTags/26       3716 ns         3711 ns       186759
```

new
```
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations
-----------------------------------------------------------
bmExtractTags/0        1803 ns         1801 ns       387066
bmExtractTags/1         508 ns          507 ns      1000000
bmExtractTags/2         790 ns          789 ns       876999
bmExtractTags/3         644 ns          643 ns      1010080
bmExtractTags/4        1317 ns         1315 ns       526524
bmExtractTags/5         853 ns          852 ns       819996
bmExtractTags/6         334 ns          333 ns      2126458
bmExtractTags/7         577 ns          576 ns      1218636
bmExtractTags/8        1352 ns         1350 ns       493885
bmExtractTags/9        1779 ns         1776 ns       390343
bmExtractTags/10        317 ns          316 ns      2246623
bmExtractTags/11        510 ns          509 ns      1317685
bmExtractTags/12       1150 ns         1148 ns       611562
bmExtractTags/13       1354 ns         1352 ns       514080
bmExtractTags/14       1654 ns         1652 ns       444191
bmExtractTags/15        960 ns          959 ns       741186
bmExtractTags/16        816 ns          815 ns       845007
bmExtractTags/17        804 ns          803 ns       891785
bmExtractTags/18        827 ns          826 ns       842946
bmExtractTags/19        336 ns          336 ns      2103591
bmExtractTags/20        344 ns          344 ns      2051805
bmExtractTags/21        393 ns          392 ns      1769019
bmExtractTags/22        882 ns          881 ns       790379
bmExtractTags/23       2071 ns         2069 ns       336449
bmExtractTags/24        317 ns          317 ns      2190476
bmExtractTags/25        310 ns          310 ns      2327887
bmExtractTags/26        495 ns          494 ns      1412560
```

File: source/common/config/well_known_names.cc [hunk 2]
```diff
@@ -24,97 +24,95 @@ TagNameValues::TagNameValues() {
...
+  addRe2(CLIENTSSL_PREFIX, R"(^auth\.clientssl\.(([\w-]+)\.))");
 
-  // ratelimit.(<stat_prefix>.)<base_stat>
-  addRegex(RATELIMIT_PREFIX, R"(^ratelimit\.((.*?)\.)\w+?$)");
+  // ratelimit.(<stat_prefix>.)*
+  addRe2(RATELIMIT_PREFIX, R"(^ratelimit\.(([\w-]+)\.))");
 
   // cluster.(<cluster_name>.)*
-  addRe2(CLUSTER_NAME, "^cluster\\.(([^\\.]+)\\.).*");
+  addRe2(CLUSTER_NAME, R"(^cluster\.(([\w-]+)\.))");
```
Comment (jmarantz) [inline source/common/config/well_known_names.cc:92]: I have a question on the use of `\w` here -- does this possibly reject expressions that the original one did not? I think the answer is "yes". E.g. punctuation other than "." or "-" that might be expected to work. I think cluster-names are in control of the user, so this might be a visible change in behavior.

Is there a speed difference for using `\w-` vs `^\.` ?

File: source/common/config/well_known_names.cc [hunk 3]
```diff
@@ -24,97 +24,95 @@ TagNameValues::TagNameValues() {
...
-  addRegex(RESPONSE_CODE_CLASS, "_rq_(\\d)xx$", "_rq_");
+  addRe2(RESPONSE_CODE_CLASS, R"(_rq_((\d))xx$)", "_rq_");
 
   // http.[<stat_prefix>.]dynamodb.table.[<table_name>.]capacity.[<operation_name>.](__partition_id=<last_seven_characters_from_partition_id>)
-  addRegex(DYNAMO_PARTITION_ID,
-           "^http(?=\\.).*?\\.dynamodb\\.table(?=\\.).*?\\."
-           "capacity(?=\\.).*?(\\.__partition_id=(\\w{7}))$",
-           ".dynamodb.table.");
+  addRe2(DYNAMO_PARTITION_ID,
+         R"(^http\.[\w-]+\.dynamodb\.table\.[\w-]+\.capacity\.[\w-]+(\.__partition_id=(\w{7}))$)",
```
Comment (jmarantz) [inline source/common/config/well_known_names.cc:34]: one thought on how these segments are expressed in code: I wonder if we should define some infrastructure like macros or helper functions to provide some of these symbolically rather than spelling out the full regexes. That might make them easier to read for non-regex-experts, and also have a single point where we define what a "word" means, e.g. (alphanumerics plus -) vs (everything except .)

**Comment by jmarantz** [comment]
FYI your coverage fails with `Code coverage for source/common/network is lower than limit of 95.3 (95.2)`. Not sure why that would appear in your PR but maybe just try merging main?

File: source/common/config/well_known_names.cc (hunk 2 above)
Comment (rojkov) [reply source/common/config/well_known_names.cc]: `^\.` seems to perform better. Perhaps this is a negated comparison with a single symbol vs comparisons with multiple symbols. Replaced with `^\.` everywhere.

File: source/common/config/well_known_names.cc (hunk 3 above)
Comment (rojkov) [reply source/common/config/well_known_names.cc]: how about the `expandRegex()` function I added?

File: source/common/config/well_known_names.cc [hunk 4]
```diff
@@ -1,8 +1,37 @@
...
 
+namespace {
+
+const std::string& wordRegex() { CONSTRUCT_ON_FIRST_USE(std::string, R"([^\.]+)"); }
+
+std::string expandRegex(const std::string& regex) {
+  return absl::StrReplaceAll(
+      regex, {{"<ADDRESS>",
+               R"((?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}_\d+|\[[_aAbBcCdDeEfF[:digit:]]+\]_\d+))"},
+              {"<CALLSITE>", wordRegex()},
```
Comment (jmarantz) [inline source/common/config/well_known_names.cc:16]: This looks great. But WDYT of collapsing all these wordRegex() substitution into one generic `<NAME>`? That would leave you with about 4 subtitutions.

Comment (rojkov) [reply source/common/config/well_known_names.cc]: Yeap, that's more readable. Updated.

File: source/common/config/well_known_names.cc [hunk 5]
```diff
@@ -24,107 +39,102 @@ TagNameValues::TagNameValues() {
...
 
   // listener_manager.(worker_<id>.)*
-  addRegex(WORKER_ID, R"(^listener_manager\.((worker_\d+)\.))", "listener_manager.worker_");
+  addRe2(WORKER_ID, R"(^listener_manager\.((worker_\d+)\.))", "listener_manager.worker_");
 }
 
 void TagNameValues::addRegex(const std::string& name, const std::string& regex,
                              const std::string& substr) {
-  descriptor_vec_.emplace_back(Descriptor{name, regex, substr, Regex::Type::StdRegex});
+  descriptor_vec_.emplace_back(Descriptor{name, expandRegex(regex), substr, Regex::Type::StdRegex});
```
Comment (jmarantz) [inline source/common/config/well_known_names.cc:132]: Nit: I think this is not called now. Delete?

File: test/common/stats/tag_extractor_impl_test.cc [hunk 6]
```diff
@@ -156,9 +156,9 @@ TEST(TagExtractorTest, DefaultTagExtractors) {
   // Cluster name
   Tag cluster_tag;
   cluster_tag.name_ = tag_names.CLUSTER_NAME;
-  cluster_tag.value_ = "ratelimit";
+  cluster_tag.value_ = "rate_limit-14";
 
-  regex_tester.testRegex("cluster.ratelimit.upstream_rq_timeout", "cluster.upstream_rq_timeout",
+  regex_tester.testRegex("cluster.rate_limit-14.upstream_rq_timeout", "cluster.upstream_rq_timeout",
```
Comment (jmarantz) [inline test/common/stats/tag_extractor_impl_test.cc:161]: nit: you could revert the changes to add dashes as dashes are no longer special in your regexes.

**Review by jmarantz — DISMISSED** [review]
2 nits, but I think this is ready for @envoyproxy/senior-maintainers review.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks for working on this. I didn't audit the regex in detail and trust @jmarantz to do that, but one comment comment. Also, can you merge main which hopefully will fix coverage otherwise can we look into that also?

/wait

File: source/common/config/well_known_names.cc [hunk 7]
```diff
@@ -24,107 +39,97 @@ TagNameValues::TagNameValues() {
...
+         R"(^http\.<NAME>\.dynamodb\.table\.<NAME>\.capacity\.<NAME>(\.__partition_id=(\w{7}))$)",
+         ".dynamodb.table.");
 
   // http.[<stat_prefix>.]dynamodb.operation.(<operation_name>.)<base_stat> or
   // http.[<stat_prefix>.]dynamodb.table.[<table_name>.]capacity.(<operation_name>.)[<partition_id>]
-  addRegex(DYNAMO_OPERATION,
-           "^http(?=\\.).*?\\.dynamodb.(?:operation|table(?="
-           "\\.).*?\\.capacity)(\\.(.*?))(?:\\.|$)",
-           ".dynamodb.");
+  addRe2(DYNAMO_OPERATION,
```
Comment (jmarantz) [inline source/common/config/well_known_names.cc:54]: I think maybe the two options listed above are a holdover from when the stat extraction was serial and this regex would have to run either before or after the previous one. I wonder if this could be simplified now that every extractor runs on the original stat-name, rather than being chained.

This is not related to the RE2 conversion and I'm fine to leave this as a TODO. But I'm bringing it up now because it might make it easier to inspect the RE pattern.

File: source/common/config/well_known_names.cc [hunk 8]
```diff
@@ -24,107 +39,97 @@ TagNameValues::TagNameValues() {
...
+  // ratelimit.(<stat_prefix>.)*
+  addRe2(RATELIMIT_PREFIX, R"(^ratelimit\.((<NAME>)\.))");
 
   // cluster.(<cluster_name>.)*
-  addRe2(CLUSTER_NAME, "^cluster\\.(([^\\.]+)\\.).*");
+  addRe2(CLUSTER_NAME, R"(^cluster\.((<NAME>)\.))");
 
   // listener.[<address>.]http.(<stat_prefix>.)*
-  addRegex(HTTP_CONN_MANAGER_PREFIX, R"(^listener(?=\.).*?\.http\.((.*?)\.))", ".http.");
+  addRe2(HTTP_CONN_MANAGER_PREFIX, R"(^listener\..*?\.http\.((<NAME>)\.))", ".http.");
```
Comment (jmarantz) [inline source/common/config/well_known_names.cc:109]: Should we use `<ADDRESS>` for the address segment here?

**Review by jmarantz — COMMENTED** [review]
Thinking about this further, it would be nice to mechanically determine whether all these REs get matched by actual stats in a live config.

I think it's hard for anyone (even an RE expert) to know by inspection with certainty if these are all correct, or even if the previous ones were.

**Comment by jmarantz** [comment]
merging master will resolve the coverage issue in source/common/network.

File: source/common/config/well_known_names.cc (hunk 8 above)
Comment (rojkov) [reply source/common/config/well_known_names.cc:116]: This way the automata is much simpler: just grab anything until ".http" is met vs maintaining a substate for addresses. The benchmark shows the latter impacts performance significantly.

**Comment by rojkov** [comment]
> Thinking about this further, it would be nice to mechanically determine whether all these REs get matched by actual stats in a live config.

You mean adding per-regex stats incremented upon a match?

File: source/common/config/well_known_names.cc (hunk 8 above)
Comment (jmarantz) [reply source/common/config/well_known_names.cc:116]: Cool; that  makes sense. Any reason not to put that into a code comment?

**Review by jmarantz — COMMENTED** [review]
I didn't mean to add permanent per-regex stats. I meant doing something more like adding instrumentation temporarily to make sure that we are matching the actual stat-names as composed elsewhere in the code, just to make sure the tag-matching is doing something useful.

File: source/common/config/well_known_names.cc (hunk 8 above)
Comment (rojkov) [reply source/common/config/well_known_names.cc:118]: Yeap, added a comment.

**Comment by rojkov** [comment]
I've added counters to the tag extractors with permanent overhead for increments. Would it be useful in production?

The current output is like
```
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.tcp_prefix tag extractor: skipped 0, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.ratelimit_prefix tag extractor: skipped 0, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.worker_id tag extractor: skipped 12, matched 8, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.virtual_cluster tag extractor: skipped 0, matched 6, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.virtual_host tag extractor: skipped 0, matched 6, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.udp_prefix tag extractor: skipped 0, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.dynamo_partition_id tag extractor: skipped 155, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.dynamo_operation tag extractor: skipped 155, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.dynamo_table tag extractor: skipped 155, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.http_user_agent tag extractor: skipped 155, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.fault_downstream_cluster tag extractor: skipped 155, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.http_conn_manager_prefix tag extractor: skipped 0, matched 155, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.rds_route_config tag extractor: skipped 155, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.ssl_cipher tag extractor: skipped 0, matched 0, missing 38
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.http_conn_manager_prefix tag extractor: skipped 26, matched 12, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.listener_address tag extractor: skipped 0, matched 20, missing 18
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.grpc_bridge_method tag extractor: skipped 95, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for cipher_suite tag extractor: skipped 95, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.grpc_bridge_service tag extractor: skipped 95, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.cluster_name tag extractor: skipped 0, matched 95, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.clientssl_prefix tag extractor: skipped 0, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.mongo_callsite tag extractor: skipped 0, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.mongo_collection tag extractor: skipped 0, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.mongo_cmd tag extractor: skipped 0, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.mongo_prefix tag extractor: skipped 0, matched 0, missing 0
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.response_code tag extractor: skipped 282, matched 0, missing 84
[2021-01-08 14:06:26.076][603190][trace][stats] [source/common/stats/tag_extractor_impl.cc:53] Stats for envoy.response_code_class tag extractor: skipped 282, matched 20, missing 64
```

**Comment by jmarantz** [comment]
I wasn't thinking it would be that useful in production, but if we could aggregate that data over all the tests we could see which of the regexes matched actual usage.

With the code you have in there now, I guess you could post-process all the test-logs by doing something like
```
bazel test //test/... --test_output=streamed | grep `[trace][stats] [source/common/stats/tag_extractor_impl.cc:53]` > /tmp/file-to-analyze.tmp
```

**Comment by jmarantz** [comment]
...actually we'd want to exclude the tag-extractor test itself from that :)

**Comment by jmarantz** [comment]
I started messing with that myself (passing this PR). It helps a lot to make the message be loglevel=error rather than loglevel=trace, because the tests run a lot more slowly with '-l trace', especially when you are running all of them.

My suggestion for now though is to remove that production logging or ifdef it. I don't think it's going to be that useful.

I'll post results when/if it this all finishes.

**Comment by rojkov** [comment]
I've already moved the output under ifdef. Will push it promptly. Still WIP though.

**Comment by rojkov** [comment]
Here it is. Will continue on Monday

File: source/common/config/well_known_names.cc [hunk 9]
```diff
@@ -1,8 +1,23 @@
 #include "common/config/well_known_names.h"
 
+#include "absl/strings/str_replace.h"
+
 namespace Envoy {
 namespace Config {
 
+namespace {
+
+std::string expandRegex(const std::string& regex) {
```
[the remark this answers is not in the document]
Comment (jmarantz) [reply source/common/config/well_known_names.cc:11]: @rojkov I think a little more description here is what @mattklein123 wants, maybe something like:

> To allow for more readable regular expressions to be declared below, and to reduce duplication, define a few common pattern substitutions for regex segments.

**Review by jmarantz — APPROVED** [review]
I just did a pass over a patched version of this PR with the following changes:
 - made the tag-extractor-stats log more greppable (added keyword TagStats) and switched it to an 'error' so I don't have to do trace-logging which is slow
 - commented out tag_extractor_impl_test.cc in the BUILD file
 -  ran `bazel test --cache_test_results=no //test/... --test_output=all | fgrep TagStats >/tmp/tag_extraction.log 
 
Then I hacked the output with sort/unique and just scanned through it, convincing myself that every tag-matcher expression had at least one match in the test suite.

So I'm good to go with this PR, modulo Matt's comment about adding some comments to the extractRegex function.

**Comment by rojkov** [comment]
Thanks!

I've added TagStats to the output string for greppability and updated `expandRegex()`'s comment.

**Review by jmarantz — APPROVED** [review]
@envoyproxy/senior-maintainers for a final pass?

File: source/common/stats/tag_extractor_impl.h [hunk 10]
```diff
@@ -14,6 +18,39 @@
...
+
+#define PERF_TAG_COUNTERS(var)                                                                     \
+  ~TagExtractorImplBase() override {                                                               \
+    std::cout << fmt::format("TagStats for {} tag extractor: skipped {}, matched {}, missing {}",  \
+                             name_, var->skipped_, var->matched_, var->missed_)                    \
+              << std::endl;                                                                        \
+  }                                                                                                \
+  std::unique_ptr<Counters> var
+
+#define PERF_TAG_COUNTERS_INIT(var) var = std::make_unique<Counters>()
```
Comment (htuch) [inline source/common/stats/tag_extractor_impl.h:39]: Nit: wrap the expansion in parens or do/while for safety.

**Review by htuch — CHANGES_REQUESTED** [review]
Awesome, just a handful of comments.
/wait

File: source/common/config/well_known_names.cc [hunk 11]
```diff
@@ -24,107 +48,99 @@ TagNameValues::TagNameValues() {
...
+  // cluster.[<route_target_cluster>.]grpc.[<grpc_service>.](<grpc_method>.)*
+  addRe2(GRPC_BRIDGE_METHOD, R"(^cluster\.<NAME>\.grpc\.<NAME>\.((<NAME>)\.))", ".grpc.");
 
-  // http.[<stat_prefix>.]user_agent.(<user_agent>.)<base_stat>
-  addRegex(HTTP_USER_AGENT, R"(^http(?=\.).*?\.user_agent\.((.*?)\.)\w+?$)", ".user_agent.");
+  // http.[<stat_prefix>.]user_agent.(<user_agent>.)*
+  addRe2(HTTP_USER_AGENT, R"(^http\.<NAME>\.user_agent\.((<NAME>)\.))", ".user_agent.");
 
-  // vhost.[<virtual host name>.]vcluster.(<virtual_cluster_name>.)<base_stat>
-  addRegex(VIRTUAL_CLUSTER, R"(^vhost(?=\.).*?\.vcluster\.((.*?)\.)\w+?$)", ".vcluster.");
```
[the remark this answers is not in the document]
Comment (jmarantz) [reply source/common/config/well_known_names.cc:68]: that's not a bad idea, though we do have:
 * unit tests that validate that all the tag extractions work
 * a manual validation that every one of these regexes got a match somewhere in our testsuite, excluding the unit tests.

My main concern with using fuzzing for this is that it feels quite possible that there *will* be differences in behavior between re2 and std::regex on parts of the input space that don't matter. For example, in some of the original regexes we use "\w" but in the new versions we use `([^\.]+)` which is measured to be faster, but will admit more characters. I actually think `([^\.]+)` is more correct within the stats system but we're likely to get a lot of noise to sift through.

File: source/common/stats/tag_extractor_impl.h (hunk 10 above)
Comment (jmarantz) [reply source/common/stats/tag_extractor_impl.h:39]: Out of curiosity, what's the scenario where this would parse unexpectedly?

Usually I'd use do/while in a macro if there were multiple statements in the expansion.

File: source/common/config/well_known_names.cc [hunk 12]
```diff
@@ -1,8 +1,32 @@
...
+// reduce duplication, define a few common pattern substitutions for regex
+// segments.
+std::string expandRegex(const std::string& regex) {
+  return absl::StrReplaceAll(
+      regex, {// Regex to look for either IPv4 or IPv6 addresses.
+              {"<ADDRESS>",
+               R"((?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}_\d+|\[[_aAbBcCdDeEfF[:digit:]]+\]_\d+))"},
+              // Cipher names can contain alphanumerics with dashes and
+              // underscores.
+              {"<CIPHER>", R"([0-9A-Za-z_-]+)"},
```
[the remark this answers is not in the document]
Comment (rojkov) [reply source/common/config/well_known_names.cc]: Those parts are copy-paste from the current version of regexes. Unified the usage of classes in the new version.

File: source/common/config/well_known_names.cc [hunk 13]
```diff
@@ -1,8 +1,32 @@
...
+namespace {
+
+// To allow for more readable regular expressions to be declared below, and to
+// reduce duplication, define a few common pattern substitutions for regex
+// segments.
+std::string expandRegex(const std::string& regex) {
+  return absl::StrReplaceAll(
+      regex, {// Regex to look for either IPv4 or IPv6 addresses.
+              {"<ADDRESS>",
+               R"((?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}_\d+|\[[_aAbBcCdDeEfF[:digit:]]+\]_\d+))"},
```
[the remark this answers is not in the document]
Comment (rojkov) [reply source/common/config/well_known_names.cc]: Updated the comment to reflect it's a regex for IP address plus port number.

Also grouped IPv4 and IPv6 as two alternatives in a single non-capturing group. The benchmark doesn't detect any degradation in performance.

File: source/common/config/well_known_names.cc [hunk 14]
```diff
@@ -24,107 +48,99 @@ TagNameValues::TagNameValues() {
...
-  addRegex(DYNAMO_TABLE, R"(^http(?=\.).*?\.dynamodb.(?:table|error)\.((.*?)\.))", ".dynamodb.");
+  addRe2(DYNAMO_TABLE, R"(^http\.<NAME>\.dynamodb.(?:table|error)\.((<NAME>)\.))", ".dynamodb.");
 
   // mongo.[<stat_prefix>.]collection.(<collection>.)query.<base_stat>
-  addRegex(MONGO_COLLECTION, R"(^mongo(?=\.).*?\.collection\.((.*?)\.).*?query.\w+?$)",
-           ".collection.");
+  addRe2(MONGO_COLLECTION, R"(^mongo\.<NAME>\.collection\.((<NAME>)\.).*?query\.)", ".collection.");
 
   // mongo.[<stat_prefix>.]cmd.(<cmd>.)<base_stat>
-  addRegex(MONGO_CMD, R"(^mongo(?=\.).*?\.cmd\.((.*?)\.)\w+?$)", ".cmd.");
```
[the remark this answers is not in the document]
Comment (rojkov) [reply source/common/config/well_known_names.cc:59]: Yeap, updated

File: source/common/stats/tag_extractor_impl.h (hunk 10 above)
Comment (rojkov) [reply source/common/stats/tag_extractor_impl.h:39]: What if I make the macros non-parameterized as they are used only once?

Comment (jmarantz) [reply source/common/stats/tag_extractor_impl.h:39]: Yes that makes sense. You could also have
```
#define PERF_TAG_INC(member) ++counters->member
```
and then you only need one macro rather than one each for skipped/missed/matched, but I am not too concerned about this; whatever you prefer.

Comment (rojkov) [reply source/common/stats/tag_extractor_impl.h]: Thanks! This simplifies the code a bit. Updated.

File: source/common/config/well_known_names.cc [hunk 15]
```diff
@@ -24,107 +47,99 @@ TagNameValues::TagNameValues() {
...
-  addRegex(VIRTUAL_HOST, "^vhost\\.((.*?)\\.)");
+  addRe2(VIRTUAL_HOST, R"(^vhost\.((<NAME>)\.))");
 
   // mongo.(<stat_prefix>.)*
-  addRegex(MONGO_PREFIX, "^mongo\\.((.*?)\\.)");
+  addRe2(MONGO_PREFIX, R"(^mongo\.((<NAME>)\.))");
 
   // http.[<stat_prefix>.]rds.(<route_config_name>.)<base_stat>
-  addRegex(RDS_ROUTE_CONFIG, R"(^http(?=\.).*?\.rds\.((.*?)\.)\w+?$)", ".rds.");
+  addRe2(RDS_ROUTE_CONFIG, R"(^http\.<NAME>\.rds\.((<ROUTE_CONFIG_NAME>)\.)\w+?$)", ".rds.");
```
Comment (htuch) [inline source/common/config/well_known_names.cc:134]: Out of curiosity, why not drop the base_stat at the end in this case?

File: source/common/stats/tag_extractor_impl.h [hunk 16]
```diff
@@ -14,6 +18,35 @@
...
+#ifdef ENVOY_PERF_ANNOTATION
+
+struct Counters {
+  uint32_t skipped_{};
+  uint32_t matched_{};
+  uint32_t missed_{};
+};
+
+#define PERF_TAG_COUNTERS                                                                          \
+  ~TagExtractorImplBase() override {                                                               \
```
Comment (htuch) [inline source/common/stats/tag_extractor_impl.h:32]: Nit: putting the whole destructor here is a bit magical, I think I would prefer it under an explicit `#ifdef`

**Review by htuch — COMMENTED** [review]
LGTM modulo nits

File: source/common/config/well_known_names.cc (hunk 15 above)
Comment (rojkov) [reply source/common/config/well_known_names.cc:136]: `<ROUTE_CONFIG_NAME>` can contain dots and there's no any other anchor after it except EOL. This makes the regex slower unfortunately.
Added a comment to explain it to my future self.

File: source/common/stats/tag_extractor_impl.h (hunk 16 above)
Comment (rojkov) [reply source/common/stats/tag_extractor_impl.h]: done

**Review by jmarantz — APPROVED** [review]
explicit ifdef is much more readable; thanks.

**Review by htuch — APPROVED** [review]
LGTM, thanks!

**Comment by jmarantz** [comment]
And thanks for doing this @rojkov !
