### PR TITLE
hds: validate messages on receive to catch a missing field exception

### LINKED ISSUE #11014: HDS: Incorrect HealthCheck from xDS config causes std:terminate
**Note:** I saw the notice about crash bugs being disclosed via security list first however this issue was already discussed publicly in #1310 and @htuch requested this to filed as a separate issue and confirmed that since it's a control-plane induced crash it's outside the threat model.

---

*Description*:

When a control plan being used for HDS sends a `HealthCheck` with missing required fields (e.g. `UnhealthyThreshold`) Envoy 1.14.1 will crash with `std:terminate` called.

*Repro steps*:

 1. Run Envoy 1.14.1 with HDS configured pointing to an xDS control plane
 2. Have control plane sent `HealthCheckSpecifier` with at least one `HealthCheck` with a missing required field. e.g. (in go code):

  ```go
func (s *Server) hds(stream v2disco.HealthDiscoveryService_StreamHealthCheckServer) error {
	resp := &v2disco.HealthCheckSpecifier{
		ClusterHealthChecks: []*v2disco.ClusterHealthCheck{
			{
				ClusterName: "cluster-00000",
				HealthChecks: []*v2core.HealthCheck{
					{
						Timeout: &duration.Duration{
							Seconds: 1,
						},
						Interval: &duration.Duration{
							Seconds: 1,
						},
						UnhealthyThreshold: &wrappers.UInt32Value{Value: 2},

						// NOTICE THE FIELD BELOW IS NOT SET, uncommenting it prevents crash.
						//HealthyThreshold:   &wrappers.UInt32Value{Value: 2},
						HealthChecker: &v2core.HealthCheck_HttpHealthCheck_{
							HttpHealthCheck: &v2core.HealthCheck_HttpHealthCheck{
								Host: "localhost",
								Path: "/v1/agent/self",
							},
						},
						AlwaysLogHealthCheckFailures: false,
					},
				},
				LocalityEndpoints: []*v2disco.LocalityEndpoints{
					{
						Locality: &v2core.Locality{
							Region: "us-west-1",
							Zone:   "zone-a",
						},
						Endpoints: []*v2endpoint.Endpoint{
							{
								Address: &v2core.Address{
									Address: &v2core.Address_SocketAddress{
										SocketAddress: &v2core.SocketAddress{
											Address: "127.0.0.1",
											PortSpecifier: &v2core.SocketAddress_PortValue{
												PortValue: 8500,
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		Interval: &duration.Duration{
			Seconds: 5,
		},
	}
	return stream.Send(resp)
}
  ```

 3. Watch Envoy Crash.

*Config*:

<details><summary>bootstrap.yaml</summary>

```yaml
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 19000

hds_config:
  api_type: GRPC
  grpc_services:
  - envoy_grpc:
      cluster_name: xds_cluster
  set_node_on_first_message_only: true

node:
  cluster: test-cluster
  id: test-id

static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 1s
    http2_protocol_options: {}
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080

```

</details>

*Logs*:

<details><summary>stdout</summary>

```
[2020-04-30 15:10:28.888][4435550][debug][upstream] [external/envoy/source/common/upstream/health_discovery_service.cc:187] New health check response message cluster_health_checks {
  cluster_name: "cluster-00000"
  health_checks {
    timeout {
      seconds: 1
    }
    interval {
      seconds: 1
    }
    unhealthy_threshold {
      value: 2
    }
    http_health_check {
      host: "localhost"
      path: "/v1/agent/self"
    }
  }
  locality_endpoints {
    locality {
      region: "us-west-1"
      zone: "zone-a"
    }
    endpoints {
      address {
        socket_address {
          address: "127.0.0.1"
          port_value: 8500
        }
      }
    }
  }
}
interval {
  seconds: 5
}

[2020-04-30 15:10:28.888][4435550][debug][upstream] [external/envoy/source/common/upstream/health_discovery_service.cc:140] New health check response message cluster_health_checks {
  cluster_name: "cluster-00000"
  health_checks {
    timeout {
      seconds: 1
    }
    interval {
      seconds: 1
    }
    unhealthy_threshold {
      value: 2
    }
    http_health_check {
      host: "localhost"
      path: "/v1/agent/self"
    }
  }
  locality_endpoints {
    locality {
      region: "us-west-1"
      zone: "zone-a"
    }
    endpoints {
      address {
        socket_address {
          address: "127.0.0.1"
          port_value: 8500
        }
      }
    }
  }
}
interval {
  seconds: 5
}

[2020-04-30 15:10:28.888][4435550][debug][upstream] [external/envoy/source/common/upstream/health_discovery_service.cc:169] New HdsCluster config name: "cluster-00000"
connect_timeout {
  seconds: 1
}
per_connection_buffer_limit_bytes {
  value: 32768
}
health_checks {
  timeout {
    seconds: 1
  }
  interval {
    seconds: 1
  }
  unhealthy_threshold {
    value: 2
  }
  http_health_check {
    host: "localhost"
    path: "/v1/agent/self"
  }
}
load_assignment {
  endpoints {
    lb_endpoints {
      endpoint {
        address {
          socket_address {
            address: "127.0.0.1"
            port_value: 8500
          }
        }
      }
    }
  }
}

[2020-04-30 15:10:28.888][4435550][debug][upstream] [external/envoy/source/common/upstream/health_discovery_service.cc:228] Creating an HdsCluster
[2020-04-30 15:10:28.889][4435550][debug][upstream] [external/envoy/source/common/upstream/upstream_impl.cc:275] transport socket match, socket default selected for host with address 127.0.0.1:8500
[2020-04-30 15:10:28.896][4435550][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[2020-04-30 15:10:28.896][4435550][critical][backtrace] [bazel-out/darwin-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-04-30 15:10:28.896][4435550][critical][backtrace] [bazel-out/darwin-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: 3504d40f752eb5c20bc2883053547717bcb92fd8/1.14.1/clean-getenvoy-902f20f-envoy/RELEASE/BoringSSL
[2020-04-30 15:10:28.896][4435550][critical][backtrace] [bazel-out/darwin-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Abort trap: 6, suspect faulting address 0x7fff70d6d2c2
[2020-04-30 15:10:28.896][4435550][critical][backtrace] [bazel-out/darwin-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-04-30 15:10:28.896][4435550][critical][backtrace] [bazel-out/darwin-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: 3504d40f752eb5c20bc2883053547717bcb92fd8/1.14.1/clean-getenvoy-902f20f-envoy/RELEASE/BoringSSL
AsyncClient 0xefda000, stream_id_: 11052890408606538608
&stream_info_:
  StreamInfoImpl 0xefda1b0, protocol_: 1, response_code_: null, response_code_details_: via_upstream, health_check_request_: 0, route_name_:
fish: 'envoy -c ./bootstrap.yaml -l de…' terminated by signal SIGABRT (Abort)
```

</details>

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:

I was unable to use `stack_decode.py` on MacOS and with a prebuilt binary after some investigation. I believe this should be easy to reproduce if necessary although @htuch [already speculated on where the bug exists](https://github.com/envoyproxy/envoy/issues/1310#issuecomment-621834512).

### PR DESCRIPTION
**Pull request by drewsortega**
Commit Message:
Validate messages to catch missing fields in received specifiers in health discovery service.

Additional Description:
Use MessageUtil::validate over the HealthCheckSpecifier proto on message receive. HDS then instead ends its current task rather then exiting over std::terminate.

Risk Level: Low
Testing: Added an unit test test based on the example given in the related issue #11014 which calls the modified onReceiveMessage function with an invalid Health Check Specifier. Another unit test passes a valid specifier followed by an invalid specifier and ensures the previous valid configuration continues to be used.
Docs Changes: N/A
Release Notes: N/A
Fixes #11014

### CODE REVIEW

File: test/integration/hds_integration_test.cc [hunk 1]
```diff
@@ -360,6 +360,40 @@ TEST_P(HdsIntegrationTest, SingleEndpointUnhealthyHttp) {
   cleanupHdsConnection();
 }
 
+// Tests Envoy HTTP health checking a single unhealthy endpoint and reporting that it is
```
Comment (mdberman54321) [inline test/integration/hds_integration_test.cc:363]: This is a test.

File: source/common/upstream/health_discovery_service.cc [hunk 2]
```diff
@@ -189,6 +192,18 @@ void HdsDelegate::onReceiveMessage(
   stats_.requests_.inc();
   ENVOY_LOG(debug, "New health check response message {} ", message->DebugString());
 
+  // Validate message fields
+  try {
+    MessageUtil::validate(*message, validation_visitor_);
+  } catch (const ProtoValidationException& ex) {
+    // Increment error count
+    stats_.errors_.inc();
+    ENVOY_LOG(warn, "unable to validate hds proto: {}", ex.what());
```
Comment (htuch) [inline source/common/upstream/health_discovery_service.cc:201]: Nit: `"Unable to validate health check specifier: {}"`

File: source/common/upstream/health_discovery_service.cc [hunk 3]
```diff
@@ -189,6 +192,18 @@ void HdsDelegate::onReceiveMessage(
...
+
+    // Do not continue processing message
+    return;
+  }
+
```
Comment (htuch) [inline source/common/upstream/health_discovery_service.cc:206]: I wonder if we still want to keep ticking by issuing a `setHdsStreamResponseTimer()` as below with the latched `server_response_ms_`? This would ensure we keep reporting with previous valid config.

File: source/common/upstream/health_discovery_service.cc (hunk 2 above)
Comment (drewsortega) [reply source/common/upstream/health_discovery_service.cc]: I agree that this is more clear, code now reflects this.

File: source/common/upstream/health_discovery_service.cc (hunk 3 above)
Comment (drewsortega) [reply source/common/upstream/health_discovery_service.cc:212]: Harvey, I went ahead and checked this one out. It looks like this is a good idea, as long as there is a previous valid specifier that was received. I added a check to see if there previously was valid clusters, and in this case enables the timer based on the previous value. I also added a unit test to have one successful call with a valid specifier followed by an invalid one, which falls back upon failing the validation check.

Comment (xdzhai) [reply source/common/upstream/health_discovery_service.cc:212]: Harvey,
Not sure if I missed anything. If hds_clsters_ was not empty, it was created by previous onReceiveMessage, which should already enabled the timer, unless the previous valid config has a interval=ZeroDuration.
The code below only calls setHdsStreamResponseTimer() when server_response_ms is different from the existing one.
For this case, do we want to use the new server_response_ms if different?
Thanks!

Comment (htuch) [reply source/common/upstream/health_discovery_service.cc:212]: Actually @xdzhai is right. This behavior should have been working before. No need to adjust `server_response_ms_` is we have an invalid config received.

File: test/common/upstream/hds_test.cc [hunk 4]
```diff
@@ -227,6 +228,66 @@ TEST_F(HdsTest, TestProcessMessageHealthChecks) {
...
+
+  // Create a invalid message
+  message.reset(createSimpleMessage());
+
+  // remove healthy threshold field to create an error
+  message->mutable_cluster_health_checks(0)->mutable_health_checks(0)->clear_healthy_threshold();
+
+  // call onReceiveMessage function for testing. Should increment stat_ errors upon
+  // getting a bad message
+  EXPECT_CALL(*server_response_timer_, enableTimer(_, _)).Times(AtLeast(1));
```
Comment (htuch) [inline test/common/upstream/hds_test.cc:283]: Instead of this, I think you should be able to verify that some timer that was previously enabled is still active.

Comment (drewsortega) [reply test/common/upstream/hds_test.cc]: @htuch thanks for the suggestion. I am now verifying over the available enabled_ field on each timer in the tests, asserting it is disabled if there has never been a valid specifier, and asserting it is enabled if there was a previous valid specifier even after the current invalid one.

File: source/common/upstream/health_discovery_service.cc (hunk 3 above)
Comment (drewsortega) [reply source/common/upstream/health_discovery_service.cc:206]: @htuch yes, it seems I looked over the timer enable call at the end of the sendResponse call. I've removed the redundant timer enable call as a result and use your suggestion about checking timer statuses instead.

File: test/common/upstream/hds_test.cc [hunk 5]
```diff
@@ -227,6 +228,72 @@ TEST_F(HdsTest, TestProcessMessageHealthChecks) {
...
+  // remove healthy threshold field to create an error
+  message->mutable_cluster_health_checks(0)->mutable_health_checks(0)->clear_healthy_threshold();
+
+  // Pass invalid message through. Should increment stat_ errors upon
+  // getting a bad message.
+  hds_delegate_->onReceiveMessage(std::move(message));
+
+  // Ensure that the timer is enabled since there was a previous valid specifier.
+  EXPECT_TRUE(server_response_timer_->enabled_);
+
```
Comment (xdzhai) [inline test/common/upstream/hds_test.cc:291]: Is it helpful to try sendResponse() and verify the correctness?

File: test/common/upstream/hds_test.cc [hunk 6]
```diff
@@ -227,6 +228,72 @@ TEST_F(HdsTest, TestProcessMessageHealthChecks) {
...
+  message->mutable_cluster_health_checks(0)->mutable_health_checks(0)->clear_healthy_threshold();
+
+  // call onReceiveMessage function for testing. Should increment stat_ errors upon
+  // getting a bad message
+  hds_delegate_->onReceiveMessage(std::move(message));
+
+  // Ensure that we never enabled the response timer that would start health checks,
+  // since this config was invalid.
+  EXPECT_FALSE(server_response_timer_->enabled_);
+
```
Comment (xdzhai) [inline test/common/upstream/hds_test.cc:249]: Maybe also check hdsClusters() is empty.

File: test/common/upstream/hds_test.cc (hunk 5 above)
Comment (drewsortega) [reply test/common/upstream/hds_test.cc:296]: It would be helpful to ensure the previous cluster information was being used rather than some partial version of the invalid information. To check this, I changed the endpoint address 127.0.0.0 to 9.9.9.9 on the second invalid pass, and at the end of the test verify that the sendResponse() function ran a health check on the previous valid 127.0.0.0 instead of the 9.9.9.9 provided in the invalid specifier.

**Comment by drewsortega** [comment]
For those curious, the CI two failures are related to a linting error in the HDS constructor calling initialize(). This linting error was already in the repository before this change and is unrelated to the changes proposed in this PR.

**Comment by htuch** [comment]
@drewsortega do you think it would be super simple to fix those or more involved? If the former, might as well clean it up.

@lizan I'm seeing this kind of issue a lot these days; we have unrelated clang-tidy issues appearing in a PR where a file is modified. Is there anyway to make clang-tidy smarter about only calling out actually modified lines?

**Comment by drewsortega** [comment]
@htuch yes, the change is quite simple and I went ahead and cleaned this up. I simply expanded the initialize function into the constructor so it doesn't try to call the virtual method. I left the original initialize function intact as well.
