### PR TITLE
upstream: consistent H1 and H2 rq_total stats

### LINKED ISSUE #6350: upstream_rq_total is not consistent during H1 and H2 circuit breaking
For the HTTP/1 connection pool, we increment upstream_rq_total even if the request ends up being circuit broken. For the HTTP/2 connection pool we do not. 

This is confusing and we should fix this to be consistent, one way or the other.

cc @danielhochman @junr03

### PR DESCRIPTION
**Pull request by spenceral**
Description: Previously, we incremented rq_total and upstream_rq_total for the HTTP/1
conn pool even if the request ended up being circuit broken. The stats
were not incremented for HTTP/2 requests. This change no longer
increments the stats for HTTP/1 circuit broken requests for consistency
between the two.
Risk Level: Low
Testing: Added checks to an existing unit test
Docs Changes: N/A
Release Notes: N/A
Fixes #6350

### CODE REVIEW

File: source/common/http/http1/conn_pool.cc [hunk 1]
```diff
@@ -90,9 +90,10 @@ void ConnPoolImpl::createNewConnection() {
 
 ConnectionPool::Cancellable* ConnPoolImpl::newStream(StreamDecoder& response_decoder,
                                                      ConnectionPool::Callbacks& callbacks) {
-  host_->cluster().stats().upstream_rq_total_.inc();
-  host_->stats().rq_total_.inc();
   if (!ready_clients_.empty()) {
+    host_->cluster().stats().upstream_rq_total_.inc();
```
Comment (mattklein123) [inline source/common/http/http1/conn_pool.cc]: Can you potentially move this into `attachRequestToCleint()` and remove from below? I think it's better to have the logic in one place and it's more accurate since we still may not send the request upstream if it gets cancelled while pending.

Comment (spenceral) [reply source/common/http/http1/conn_pool.cc]: This makes sense to me, thanks for catching that pending request case.
