### PR TITLE
opentelemetry tracer: Not crash envoy when environment resource detector can't detect attributes

### LINKED ISSUE #32225: OTEL Environment resource detector is unsafe/non-compliant due to error handling
*Title*: OTEL Environment resource detector is unsafe/non-compliant due to error handling

*Description*:
When configuring a resource detector over XDS, the config is rejected if there is no env var set: `Error adding/updating listener(s) 0.0.0.0_9080: Environment variable doesn't exist: OTEL_RESOURCE_ATTRIBUTES`.

This causes two issues: ability to use it safely, and OTEL compliance.

**Safe usage**: As an XDS server, I generally do not know all the environment variables a pod does or does not have access to. And in general, I think most servers are trying to avoid client-context-aware XDS resources to improve performance/caching/etc. This means I cannot reasonably set this configuration over XDS, unless I _know_ all clients will set this variable, which is quite hard to guarantee. This makes it unsafe to ever use this field. This, IMO, is quite different from most of XDS in general (I won't say _all_, since its a huge API!) - with the exception of ability to bind to a port, most things are safe for an xds server to push down to a client.

Rejected config can cause widespread outages. For example, if we added this to our control plane and pushed everywhere, 99.9% of clients probably do not set this env var, and thus will get NACKs and fail to startup or fail to get new updates.

**OTEL compliances**

The OTel [spec for resource detectors](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.29.0/specification/resource/sdk.md#detecting-resource-information-from-the-environment) says:

> Resource detection logic is expected to complete quickly since this code will be run during application initialization. Errors should be handled as specified in the [Error Handling principles](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.29.0/specification/error-handling.md#basic-error-handling-principles). Note the **failure to detect any resource information MUST NOT be considered an error**, whereas an error that occurs during an attempt to detect resource information SHOULD be considered an error.

(emphasis mine)

Additionally, the [Error Handling principles](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.29.0/specification/error-handling.md#basic-error-handling-principles) it links says:

> The API or SDK MAY fail fast and cause the application to fail on initialization, e.g. **because of a bad user config** or environment, but **MUST NOT cause the application to fail later at run time, e.g. due to dynamic config settings** received from the Collector.

The latter case, dynamic config settings, is what is triggered here.

Specifically to OTEL_RESOURCE_ATTRIBUTES, all of the other SDKs ignore it being unset. And this is even when a user explicitly writes code like `UseEnvResources()`.

---

For these two reasons, I would propose this is case does not result in rejected config. If need-be, this could be an option in the config, though I personally think its fine to just change the behavior for everyone for the reasons above.

### PR DESCRIPTION
**Pull request by joaopgrassi**
Commit Message: Not crash envoy when env resource detector can't detect attributes
Additional Description:
Risk Level: Low
Testing: Unit/Integration/Manual 
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:] 
[Optional Fixes #32225]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by joaopgrassi** [comment]
CC @wbpcode

File: source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc [hunk 1]
```diff
@@ -29,22 +29,21 @@ Resource EnvironmentResourceDetector::detect() {
...
+    return resource;
   }
 
   for (const auto& pair : StringUtil::splitToken(attributes_str, ",")) {
     const auto keyValue = StringUtil::splitToken(pair, "=");
     if (keyValue.size() != 2) {
-      throw EnvoyException(
-          fmt::format("The OpenTelemetry environment resource detector is configured but the '{}'"
-                      " environment variable has an invalid format.",
-                      kOtelResourceAttributesEnv));
```
Comment (wbpcode) [inline source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc:47]: I think this should still throw the exception because this should be treat as config error. We can accept the env variable absent but if it exist, it should have correct format?

cc @howardjohn WDYT?

/wait-any

Comment (howardjohn) [reply source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc:47]: https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#parsing-empty-value seems to require a specific behavior?

Comment (joaopgrassi) [reply source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc:47]: The spec above is indeed unclear (I will submit an issue for it), because I wasn't able to find a definition/behavior of "unset". But, I looked at all major SDKs resource implementation and **all** are treating unset/empty as no error (so, treat them as the same, which is what I expected), and returning an empty resource:

- [C++](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/src/resource/resource_detector.cc#L19)
- [Java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java#L62C23-L62C42)
- [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Resources/OtelEnvResourceDetector.cs#L26)
- [PHP](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Resource/Detectors/Environment.php#L21-L23)
- [Go](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/resource/env.go#L54)
- [Collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/env/env.go#L45-L51)
- [JS](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-resources/src/detectors/EnvDetectorSync.ts#L57)

So that's why I wanted to keep the same behavior here.

Comment (joaopgrassi) [reply source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc:47]: Another situation/use-case for empty could be: You set the `OTEL_RESOURCE_ATTRIBUTES` on the host with some attributes. But then on a specific app running on this host, you want to remove them. Then you would set for that specific app it empty. (or replace with something else..) So I think we shouldn't treat empty as an error here.

Comment (wbpcode) [reply source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc:47]: Do I missed something? My initial comment is for the format error, seems you are discussing the empty value?

Comment (joaopgrassi) [reply source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc:47]: Yeah, I was mostly replying to john's question. For invalid values I'd also not throw an exception. Maybe just log that it was invalid then. I think in general a resource detector should not fail due to this. Again, several other SDKs do the same:

- [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Resources/OtelEnvResourceDetector.cs#L43)
- [JS](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-resources/src/detectors/EnvDetectorSync.ts#L109)|
- [Python](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L316)

The OTel collector does return an [error from the detector ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/env/env.go#L69-L71) but that error is [swallowed and simply logged ](- [Collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/resourcedetection.go#L130))

I just ran the collector with an invalid env value `OTEL_RESOURCE_ATTRIBUTES=extra=chars, a` and the collector starts but logs: 

```shell
otel-local-collector-1  | 2024-02-07T12:01:09.651Z      info    internal/resourcedetection.go:125       began detecting resource information    {"kind": "processor", "name": "resourcedetection/env", "pipeline": "traces"}
otel-local-collector-1  | 2024-02-07T12:01:09.654Z      warn    internal/resourcedetection.go:130       failed to detect resource       {"kind": "processor", "name": "resourcedetection/env", "pipeline": "traces", "error": "invalid resource format, invalid text: \" a\""}
otel-local-collector-1  | 2024-02-07T12:01:09.654Z      info    internal/resourcedetection.go:139       detected resource information   {"kind": "processor", "name": "resourcedetection/env", "pipeline": "traces", "resource": {}}
```

Comment (wbpcode) [reply source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc:47]: Okay, if there are reasonable precedent.

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.
