### PR TITLE
network: reintroduce #4382 (delayed conn close) with segv fix

### LINKED ISSUE #4583: Investigate crash introduced in #4382
*Description*:
Code merged in https://github.com/envoyproxy/envoy/pull/4382 is causing a SEGV in source/common/network/connection_impl.cc:586. 

My comment from #4581:
>As @junr03 pointed out, it seems the delayed close timeout callback is being issued after a ConnectionImpl::closeSocket() call which resets the connection_stats_ pointer has occurred. This points to an interesting race since destruction of the ConnectionImpl should lead to disarming the timeout, so it's possible the onDelayedCloseTimeout() cb is triggering while the ConnectionImpl is in the deferred deletion stage.

### PR DESCRIPTION
**Pull request by AndresGuedez**
Reintroduce PR #4382 (aa9478f06d613cd7b845e609a8c20c1ce116dad5) with a bug fix to prevent segfaults during connection tear down race conditions.

#4382 was reverted in PR #4581 (9d32e5c2a14cd9ab96b6e77fb04f7bd77b2c0d71) due to detection of the crashing bug. 

Risk Level: Medium (reintroduces medium risk, previously reverted PR)
Testing: Added unit tests to reproduce (previously) crashing states
Docs Changes: N/A
Release Notes: Added

Fixes #4583

### CODE REVIEW

**Comment by AndresGuedez** [comment]
asan/tsan failing due to an issue with one of the tests I added; I'm working on a fix.

File: source/common/network/connection_impl.cc [hunk 1]
```diff
@@ -70,10 +70,7 @@ ConnectionImpl::ConnectionImpl(Event::Dispatcher& dispatcher, ConnectionSocketPt
 ConnectionImpl::~ConnectionImpl() {
   ASSERT(fd() == -1, "ConnectionImpl was unexpectedly torn down without being closed.");
 
-  if (delayed_close_timer_) {
-    // It's ok to disable even if the timer has already fired.
-    delayed_close_timer_->disableTimer();
-  }
+  disableDelayedCloseTimer();
```
Comment (mattklein123) [inline source/common/network/connection_impl.cc]: Can the timer ever exist here? I don't think so? Can this just be an ASSERT that the timer is nullptr? If so we can remove the private function I think?

File: test/common/network/connection_impl_test.cc [hunk 2]
```diff
@@ -1068,6 +1080,58 @@ TEST_P(ConnectionImplTest, FlushWriteAndDelayConfigDisabledTest) {
   server_connection->close(ConnectionCloseType::NoFlush);
 }
 
+// Test that tearing down the connection will disable the delayed close timer.
+TEST_P(ConnectionImplTest, DelayedCloseTimeoutDisableOnSocketClose) {
```
Comment (mattklein123) [inline test/common/network/connection_impl_test.cc]: This might be a big pain, but is it possible to switch all these new tests over to using `InSequence`? For tests like this IMO it makes the tests much stronger.

File: source/common/network/connection_impl.cc (hunk 1 above)
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: The timer disablement was here as a defensive measure (like the close() call after it is). However, now that closeSocket() is disabling the timer, I agree this is no longer needed and have added a check to the ASSERT().

File: test/common/network/connection_impl_test.cc (hunk 2 above)
Comment (AndresGuedez) [reply test/common/network/connection_impl_test.cc]: Agreed and done.

**Comment by mattklein123** [comment]
@AndresGuedez sorry looks like you need another master merge.

**Comment by AndresGuedez** [comment]
> @AndresGuedez sorry looks like you need another master merge.

Done. Thanks!
