### PR TITLE
docker: Refactor `docker_ci.sh`

### LINKED ISSUE #25765: Docker build in CI is now slow due to repeated building
Since adding the new tag variants this has increased the number of times that we build and push

The current pattern is to warm the cache by building first and then doing a `--push` build with buildx using the warmed cache

The problem with this pattern is that altho it uses the caches it still has to send the build context to ascertain changes and this is very large so

### LINKED ISSUE #25766: Published Docker `version-latest` tag variants are missing
For versioned releases we have a latest image

eg `1.22.8` also gets published as `1.22-latest`

for the new tag variants - eg `dev-1.22.8` we seem to be missing the latest variant - ie `dev-1.22-latest`

### LINKED ISSUE #25767: Docker multi-stage build is throwing errors
It doesnt seem to prevent the image from building so not sure what this is, but needs to be investigated

```console

#15 [linux/arm64 binary 4/5] COPY linux/arm64/build_envoy-contrib_release/schema_validator_tool /usr/local/bin/schema_validator_tool
#15 ERROR: failed to load ref: jsj4es5ljnpugo7i6d1d1nu69: not found

#16 [linux/amd64 binary 3/5] COPY --chown=root:root linux/amd64/build_envoy-contrib_release/su-exec /usr/local/bin/
#16 ERROR: failed to load ref: qm35a59zpn9rq27pd8l6t6cxt: not found

#14 [linux/arm64 binary 3/5] COPY --chown=root:root linux/arm64/build_envoy-contrib_release/su-exec /usr/local/bin/
#14 ERROR: failed to load ref: m4ljx5ldyxzzz2iigegusgftn: not found

#10 [linux/amd64 binary 2/5] ADD configs/envoyproxy_io_proxy.yaml /etc/envoy/envoy.yaml
#10 ERROR: failed to load ref: norvfpukyesfz4uvuys5c9736: not found

#13 [linux/arm64 binary 2/5] ADD configs/envoyproxy_io_proxy.yaml /etc/envoy/envoy.yaml
#13 ERROR: failed to load ref: k9lhvnazno28pqhdhad6p3gqr: not found

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=129068&view=logs&j=2229703b-209a-5c70-43aa-3eacf674f12a&t=06218374-b1ef-5f45-4455-5a78d6d63b65&l=1725

### PR DESCRIPTION
**Pull request by phlax**
This refactors and adds regression tests to `./ci/docker_ci.sh`.

Images are no longer built repeatedly (in postsubmit) so it should be much faster.

Fixes missing `-latest` images from release builds.

Fix #25767 
Fix #25766 
Fix #25765 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: ci/test/docker/windows/dev/release [hunk 1]
```diff
@@ -0,0 +1,2 @@
+>> BUILD: envoyproxy/envoy-legacy-dev:MOCKSHA
+> docker build --platform windows/amd64 -f ci/Dockerfile-envoy-windows --build-arg BUILD_OS=mcr.microsoft.com/windows/fakecore --build-arg BUILD_TAG=ltsc1992 -t envoyproxy/envoy-legacy-dev:MOCKSHA .
```
Comment (phlax) [inline ci/test/docker/windows/dev/release:2]: this should push

File: ci/test_docker_ci.sh [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+    testdata="ci/test/docker/${platform}/${dev_name}/${test_type}"
+
+    export ENVOY_VERSION="${version}"
+    export AZP_BRANCH="$branch"
+    export DOCKER_CI_DRYRUN=1
+    export ENVOY_DOCKER_IMAGE_DIRECTORY=/non/existent/test/path
+
+    if [[ "$platform" == "windows" ]]; then
+        export DOCKER_FAKE_WIN=1
+        export WINDOWS_IMAGE_BASE="mcr.microsoft.com/windows/fakecore"
```
Comment (phlax) [inline ci/test_docker_ci.sh:49]: move these to code

File: ci/docker_ci.sh [hunk 3]
```diff
@@ -24,128 +24,76 @@ if [[ -n "$DOCKER_CI_DRYRUN" ]]; then
...
+    BUILD_TYPES=("-${WINDOWS_BUILD_TYPE}")
+    # BuildKit is not available for Windows images, use standard build command
+    BUILD_COMMAND=("build")
+else
+    # "-google-vrp" must come afer "" to ensure we rebuild the local base image dependency.
+    BUILD_TYPES=("" "-debug" "-contrib" "-contrib-debug" "-distroless" "-google-vrp" "-tools")
+
+    # Configure docker-buildx tools
+    BUILD_COMMAND=("buildx" "build")
+    if [[ -z "$DOCKER_CI_DRYRUN" ]]; then
```
Comment (phlax) [inline ci/docker_ci.sh:88]: move this to `config_env` and add some buildx output

File: ci/docker_ci.sh [hunk 4]
```diff
@@ -172,68 +123,189 @@ new_image_tag_name () {
...
+    local build_type=$1
 
-if [[ -z "$DOCKER_CI_DRYRUN" ]]; then
-    docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
-fi
+    if is_windows; then
+        printf ' -f ci/Dockerfile-envoy-windows --build-arg BUILD_OS=%s --build-arg BUILD_TAG=%s' "${WINDOWS_IMAGE_BASE}" "${WINDOWS_IMAGE_TAG}"
+    else
+        TARGET="${build_type/-debug/}"
+        TARGET="${TARGET/-contrib/}"
```
Comment (phlax) [inline ci/docker_ci.sh:145]: make local

File: ci/docker_ci.sh [hunk 5]
```diff
@@ -172,68 +123,189 @@ new_image_tag_name () {
...
+    fi
+
+    if [[ "${build_type}" == *-debug ]]; then
+        printf ' --build-arg ENVOY_BINARY_SUFFIX='
+    fi
+}
+
+use_builder() {
+    # BuildKit is not available for Windows images, skip this
+    if ! is_windows && [[ -z "$DOCKER_CI_DRYRUN" ]]; then
```
Comment (phlax) [inline ci/docker_ci.sh:160]: add debug output

File: ci/docker_ci.sh [hunk 6]
```diff
@@ -172,68 +123,189 @@ new_image_tag_name () {
...
+        echo "..."
+        docker "${docker_tag_args[@]}"
+    fi
+}
+
+push_image () {
+    local build_tag="$1" docker_image_tarball="$2"
+    # Use skopeo to push from the created oci archive
+    echo ">> PUSH: oci-archive:${docker_image_tarball} -> docker-registry:${DOCKER_REGISTRY}/${build_tag}"
+    echo "> skopeo copy --multi-arch all oci-archive:${docker_image_tarball} docker-registry:${DOCKER_REGISTRY}/${build_tag}"
```
Comment (phlax) [inline ci/docker_ci.sh:248]: enable for non-debug

File: ci/docker_ci.sh [hunk 7]
```diff
@@ -172,68 +123,189 @@ new_image_tag_name () {
...
+    docker_image_tarball="${ENVOY_DOCKER_IMAGE_DIRECTORY}/envoy${image_type}.tar"
+
+    # docker_image_tarball2="${ENVOY_DOCKER_IMAGE_DIRECTORY}/envoy${image_type}2.tar"
+    build_and_maybe_push_image "$image_type" "$build_tag" "$platform" "$docker_image_tarball" "${args[@]}"
+
+    if [[ -z "$PUSH_IMAGES_TO_REGISTRY" ]]; then
+        return
+    fi
+
+    #
```
Comment (phlax) [inline ci/docker_ci.sh:267]: add comment

File: ci/docker_ci.sh [hunk 8]
```diff
@@ -172,68 +123,189 @@ new_image_tag_name () {
...
+
+use_builder() {
+    # BuildKit is not available for Windows images, skip this
+    if ! is_windows && [[ -z "$DOCKER_CI_DRYRUN" ]]; then
+        docker buildx use multi-builder
+    fi
+}
+
+build_and_maybe_push_image () {
+    # If the image is not required for local testing this will push immediately
```
Comment (phlax) [inline ci/docker_ci.sh:166]: ... and this is main or a release ...

File: ci/docker_ci.sh [hunk 9]
```diff
@@ -172,68 +123,189 @@ new_image_tag_name () {
...
+
+    # docker_image_tarball2="${ENVOY_DOCKER_IMAGE_DIRECTORY}/envoy${image_type}2.tar"
+    build_and_maybe_push_image "$image_type" "$build_tag" "$platform" "$docker_image_tarball" "${args[@]}"
+
+    if [[ -z "$PUSH_IMAGES_TO_REGISTRY" ]]; then
+        return
+    fi
+
+    #
+    if ! is_windows && ! [[ "${image_type}" =~ debug ]]; then
```
Comment (phlax) [inline ci/docker_ci.sh:268]: move this to `build_and_maybe_push_image`

**Comment by phlax** [comment]
tested here:

https://hub.docker.com/repositories/gpt4

**Comment by phlax** [comment]
CI regression failure:

- https://dev.azure.com/cncf/envoy/_build/results?buildId=129143&view=logs&j=d7f1a0be-becb-58a1-5a8b-396ef299780d&t=8a63d2ed-ccf3-59e7-d8ce-9ba785e4c976&l=106
- https://dev.azure.com/cncf/_apis/resources/Containers/17932826/docker_ci?itemPath=docker_ci%2Ffix_docker.diff
-

**Comment by phlax** [comment]
cc @lizan

File: ci/test_docker_ci.sh [hunk 10]
```diff
@@ -0,0 +1,159 @@
...
+
+    echo "TEST(${name}): "
+    echo "  DOCKER_FAKE_WIN=${DOCKER_FAKE_WIN} ENVOY_VERSION=${version} AZP_BRANCH=${branch} DOCKER_CI_DRYRUN=1 ./ci/docker_ci.sh | grep -E \"^>\""
+    echo "     <> ${testdata}"
+    generated="$(mktemp)"
+
+    ./ci/docker_ci.sh | grep -E "^>" > "$generated"
+
+    cmp --silent "$testdata" "$generated" || {
+        echo "files are different"
```
Comment (phlax) [inline ci/test_docker_ci.sh:81]: `> stderr`

and make linings more consistent

File: ci/docker_ci.sh [hunk 11]
```diff
@@ -154,7 +115,10 @@ image_tag_name () {
 }
 
 new_image_tag_name () {
-    # envoyproxy/envoy:dev-latest
+    # envoyproxy/envoy:dev
+    # envoyproxy/envoy:dev-v1.73.3
```
Comment (phlax) [inline ci/docker_ci.sh:119]: dev is a bad example - use other

File: ci/docker_ci.sh [hunk 12]
```diff
@@ -172,68 +136,221 @@ new_image_tag_name () {
...
+    echo "> docker buildx use multi-builder"
+
+    if [[ -n "$DOCKER_CI_DRYRUN" ]]; then
+        return
+    fi
+    docker buildx use multi-builder
+}
+
+build_and_maybe_push_image () {
+    # If the image is not required for local testing and this is main or a release this will push immediately
```
Comment (phlax) [inline ci/docker_ci.sh:186]: ... if it is required for testing on a main release branch it will push to a tar archive and then push to registry from there ...

**Review by mattklein123 — APPROVED** [review]
