### PR TITLE
ensure via_upstream is populated in RESPONSE_CODE_DETAILS for response headers

### LINKED ISSUE #20413: %RESPONSE_CODE_DETAILS% empty for response_headers_to_add
*Description*:
When adding a response header with the value of `%RESPONSE_CODE_DETAILS%`, a normally completing request from upstream will contain no value instead of the expected `via_upstream` value. However, a similarly defined access_log entry will contain the correct `via_upstream` value.

I will attach a proposed PR that seems to solve the issue.

*Repro steps*:
Start Envoy with the following config. Note that the header value set for `x-response-code-details` is: `=%RESPONSE_CODE_DETAILS%` - this is simply to ensure there will be a value and the header will be added even when the `%RESPONSE_CODE_DETAILS%` is empty.

```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: service }
                      response_headers_to_add:
                          - header:
                              key: x-response-code-details
                              value: "=%RESPONSE_CODE_DETAILS%"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config: {}
                access_log:
                    - name: envoy.access_loggers.file
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                          path: "/dev/stdout"
                          log_format:
                              json_format:
                                status: "%RESPONSE_CODE%"
                                resp_code_deets: "%RESPONSE_CODE_DETAILS%"

  clusters:
    - name: service
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: round_robin
      load_assignment:
        cluster_name: service
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: httpbin.org
                  port_value: 80

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

Attempt a curl and check the headers. Note that the `x-response-code-details` header has only the constant value of "=".
```
$ curl localhost:8080/get -i
HTTP/1.1 200 OK
date: Thu, 17 Mar 2022 22:07:37 GMT
content-type: application/json
content-length: 298
server: envoy
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 127
x-response-code-details: = 
```
And note the console output for Envoy will correctly contain the log entry:

```
{"status":200,"resp_code_deets":"via_upstream"}
```

### PR DESCRIPTION
**Pull request by theganyo**
Commit Message: ensure via_upstream is populated in RESPONSE_CODE_DETAILS for response headers
Additional Description:
Risk Level: Low
Testing: Manual testing
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #Issue] Fixes #20413
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by wbpcode** [comment]
Although this can close https://github.com/envoyproxy/envoy/issues/20413, it will result  in repeated reponse code detail setting.

And please fix DCO and format. You can try run `./ci/do_ci.sh format_pre` locally to find format errors.

File: source/common/router/router.cc [hunk 1]
```diff
@@ -1470,6 +1470,8 @@ void Filter::onUpstreamHeaders(uint64_t response_code, Http::ResponseHeaderMapPt
   for (const auto& header_value : downstream_set_cookies_) {
     headers->addReferenceKey(Http::Headers::get().SetCookie, header_value);
   }
+  
+  callbacks_->streamInfo().setResponseCodeDetails(StreamInfo::ResponseCodeDetails::get().ViaUpstream);
```
Comment (alyssawilk) [inline source/common/router/router.cc:1474]: so below I see callbacks_->encodeHeaders(.. ViaUpstream).  Is that not sufficient? Perhaps you could add a regression test which fails with the current code
/wait

Comment (alyssawilk) [reply source/common/router/router.cc:1474]: hm, can you tell me a bit more about your manual testing?
I wouldn't expect the details to be set in unit tests, say, because the function which sets it would be mocked out.
We do have a number of integration tests which verify "via_upstream" makes it into access logs for the happy path (grep -r via_upstream test/integration/*) so if you can tell me a bit more about where you're not seeing it, maybe I can help sort out what's going on!

Comment (wbpcode) [reply source/common/router/router.cc:1474]: > so below I see callbacks_->encodeHeaders(.. ViaUpstream).  Is that not sufficient? Perhaps you could add a regression test which fails with the current code
> /wait

The finalizeRespnseHeaders will called before the setRespnseCodeDetail, which results in #

Comment (theganyo) [reply source/common/router/router.cc:1474]: @alyssawilk Yes, as I mentioned in the associated issue, the access logs work fine, it's only the response headers that fail. It did feel like an ordering issue to me, as @wbpcode has mentioned, but I was unsure of how to address that more specifically.

Comment (alyssawilk) [reply source/common/router/router.cc:1474]: No the fix is totally fine (sorry for missing that linked bug) but you do need a test.
given it's likely my bug, I've whipped one up over here: https://github.com/envoyproxy/envoy/compare/main...alyssawilk:add?expand=1 
you can either copy the test / release notes and put them in your PR, or I can create a PR for that one and just co-author attribute you.

Comment (theganyo) [reply source/common/router/router.cc:1474]: Fantastic and thank you! I've copied your test and will add to my PR.

Comment (alyssawilk) [reply source/common/router/router.cc:1474]: mind copying the release notes over too?  worth noting functional changes for this sort of thing :-)

**Comment by theganyo** [comment]
I think I've fixed the DCO - I followed the instructions to squash and force push, since the original commit was in error.

File: source/common/router/router.cc (hunk 1 above)
Comment (alyssawilk) [reply source/common/router/router.cc:1474]: alas I'm not sure what's going on locally. maybe you didn't git add and commit that file?
/wait on CI

Comment (theganyo) [reply source/common/router/router.cc:1474]: It was really strange, it just wasn't showing up at all... but I redid the edit and it worked this time. Thanks again!

**Comment by alyssawilk** [comment]
can you check CI output - format still looks unhappy
/wait

**Comment by theganyo** [comment]
OK. Thanks for your patience. Hopefully I've made it through the maze now. :)

**Review by alyssawilk — COMMENTED** [review]
Just one nit but otherwise I think  you're good to go :-)

File: docs/root/version_history/current.rst [hunk 2]
```diff
@@ -44,6 +44,7 @@ Bug Fixes
 * data plane: fix crash when internal redirect selects a route configured with direct response or redirect actions.
 * data plane: fixing error handling where writing to a socket failed while under the stack of processing. This should genreally affect HTTP/3. This behavioral change can be reverted by setting ``envoy.reloadable_features.allow_upstream_inline_write`` to false.
 * eds: fix the eds cluster update by allowing update on the locality of the cluster endpoints. This behavioral change can be temporarily reverted by setting runtime guard ``envoy.reloadable_features.support_locality_update_on_eds_cluster_endpoints`` to false.
+* http: fixed a bug where %%RESPONSE_CODE_DETAILS% was not set correctly in :ref:`request_headers_to_add <envoy_v3_api_field_config.route.v3.RouteConfiguration.request_headers_to_add>`.
```
[the remark this answers is not in the document]
Comment (theganyo) [reply docs/root/version_history/current.rst]: D'oh! I should've caught that. Done.

**Review by alyssawilk — APPROVED** [review]
LGTM pending CI :-)
Thanks for the fix!
