### PR TITLE
Oauth2 lifetime of refresh token

### LINKED ISSUE #30053: oauth2: Can't use refresh token to refresh session, as all cookies have expired
*Title*: Can't use refresh token to refresh session, as all cookies have expired

*Description*:
Issue #24684 recently landed, which should allow the refresh token to get a new access token, after the access token expires.

In local testing, I found that all cookies were set based on the expiry time of the access token. Therefore, at the point where the refresh token _could_ be used, it was no longer sent by the browser. 

*Repro steps*:
Configure your OAuth2 authorization server so access tokens have a short lifetime (e.g. 5 minutes), and give refresh tokens a longer lifetime (e.g. infinite). Also, request a refresh token by requesting the `offline_access` scope. In addition, the refresh token feature seems to depend on `forward_bearer_token: true`.
 
While the refresh token doesn't expire, the cookie that holds it (and all other oauth2 cookies) are set with an expiry time which is the same as that of the access token (now plus 5 minutes).

I was able to modify the cookie expiry times in the browser (e.g. set to +1 day), and found that the access token was updated without requiring a redirect. However, the new cookies were again reset to expire after 5 minutes (the expiry time of the access token).

*Suggested behavior*:
The `RefreshToken` cookie, and any other cookies needed to mark that cookie as valid (e.g. HMAC, ...) should have a much higher expiry time than the access token lifetime reported by the authorization server, when the `use_refresh_token` feature is enabled. The existence of the `OauthExpires` cookie should continue to maintain the security of the protocol, as it should continue to report the actual expiry time of the current access token.

The cookie lifetimes should be relatively long, as refresh tokens can potentially have an unbounded lifetime (but the exact lifetime is unknown). Ideally, the value should be configurable.

*Config*:
The relevant parts of the config are:
```
"typed_config": {
  "@type": "type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2",
  "config": {
    "auth_scopes": [
      "email",
      "openid",
      "offline_access"
    ],
    "forward_bearer_token": true,
    "use_refresh_token": true,
    ...
  }
}
```

### PR DESCRIPTION
**Pull request by Alexcei88**
Commit Message:

**OAuth2 filter: fixing the lifetime of the refresh token**. The refresh token is not expired together with the access token. So, once the access token is expired, the oauth2 filter can update the access token using by the refresh token.

Additional Description:

The expiration time of the access token and refresh token is the same. So, once the access token is expired oauth filter cannot update it using by refresh token because the refresh token is expired too. 

The refresh token has an [exp](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4) claim which specifes a lifetime of the token. So now the expiration time of the refresh token is equaled of the value in the exp claim. This value is more than a lifetime of the access token. So once the access token is expired the oauth filter can update the access token using by the refresh token.

Besides that I cannot sure that every jwt contains the exp claim. So I have provided a new option `default_refresh_token_expires_in` that is specified a default lifetime in seconds of the refresh token, if the exp claim is omitted in the refresh token or the refresh token is not JWT. Default value is 604800 seconds (a week)

Fix for issue #30053

Risk Level: Low
Testing: Unit Tests
Docs Changes: Needs
Release Notes: Needs

Platform Specific Features:
[Optional Fixes #30053]

### CODE REVIEW

**Review by nezdolik — COMMENTED** [review]
Looks like there are bunch of unrelated changes in this patch (.github/workflows/*, ci/*, changelog). Please remove those from patch. Also tests need to be added/updated.

**Comment by loewenstein** [comment]
Should we allow setting the default expiration to unlimited via some magical number? Given `0` is already used for immediate expiration, I guess `-1` is the next available option.

Thoughts?

**Comment by Alexcei88** [comment]
@loewenstein, As far as I know according [this](https://datatracker.ietf.org/doc/html/rfc6265.txt#section-5.2.2) if value is less than or equal to zero then cookie expires immediately. Maybe I wrong, honestly I have not checked.

**Comment by loewenstein** [comment]
> @loewenstein, As far as I know according [this](https://datatracker.ietf.org/doc/html/rfc6265.txt#section-5.2.2) if value is less than or equal to zero then cookie expires immediately. Maybe I am wrong, honestly I have not checked.

Understood. Would **not** setting `Max-Age` at all then be an alternative we should consider users to be able to configure?

**Comment by fiadliel** [comment]
> > @loewenstein, As far as I know according [this](https://datatracker.ietf.org/doc/html/rfc6265.txt#section-5.2.2) if value is less than or equal to zero then cookie expires immediately. Maybe I am wrong, honestly I have not checked.
> 
> Understood. Would **not** setting `Max-Age` at all then be an alternative we should consider users to be able to configure?

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#expiresdate -
> If unspecified, the cookie becomes a session cookie. A session finishes when the client shuts down, after which the session cookie is removed.

I would see this as closely similar to not supporting refresh token at all (which is a current configuration parameter).

I don't think there's any unlimited value for cookie lifetimes, just various options of "far into the future", with different browsers supporting different max values. Chrome itself currently caps the maximum lifetime to 400 days, there's not much value in having a default value higher than this: https://chromestatus.com/feature/4887741241229312

**Comment by fiadliel** [comment]
@Alexcei88:
>  The refresh token has an [exp](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4) claim which specifes a lifetime of the token

This is only in cases where the refresh token is a JWT. I'm not familiar with any providers that do this, but as it's defined as an opaque identifier, there are probably providers who do. (e.g. Okta and Google provide refresh tokens which are not JWTs).

> But I think in the most cases the value is not needed to configure.

All the refresh tokens I remember seeing in the wild cannot be parsed in this way, so a default is necessary (but also, I think, not especially important, a fairly long duration will suffice; the provider will reply with whether the refresh token worked or not).

**Comment by Alexcei88** [comment]
@fiadliel , thank you for information. I always face with refresh token that is JWT. So I wonder sometimes it is not so. What is default value are you suggesting? 24 hours?

**Comment by Alexcei88** [comment]
> Understood. Would **not** setting `Max-Age` at all then be an alternative we should consider users to be able to configure?

I have had such thought. But in the cases when we can figure out exactly the lifetime of the token it's best to use this value. So I decided to make so.

**Comment by fiadliel** [comment]
> @fiadliel , thank you for information. I always face with refresh token that is JWT. So I wonder sometimes it is not so. What default value are you suggesting? 24 hours?

It's the auth provider that validates the refresh token, this is different to how the access token is validated. So it's not a security issue to extend the token on the client side.

The tradeoffs (in my mind) on refresh token cookie lifetime:

Shorter lifetime advantages:
 - invalid refresh token doesn't use up bandwidth or cookie storage
 - attempt to use invalid refresh token makes the latency of call longer

Longer lifetime advantages:
 - if not sure if token is invalid, you _might_ avoid a new login cycle

The advantages of a short cookie lifetime are minor, and the advantage of a longer lifetime is a good potential quality of life improvement for the client.

Some example refresh tokens validity policies with Okta:
 - 1 day
 - 1 week
 - Unlimited, but will expire if not used every 7 days

Personally, I would err on the side of a longer cookie lifetime (e.g. 1 year). The cost is fairly low, a failed attempt to refresh the cookie, followed by redirect to login.

**Comment by Alexcei88** [comment]
Default value of default_refresh_token_expires_in = 604800 seconds (a week)

**Comment by Alexcei88** [comment]
All required changes have pushed. Ready for look.

File: source/extensions/filters/http/oauth2/filter.cc [hunk 1]
```diff
@@ -537,6 +545,34 @@ std::string OAuth2Filter::getEncodedToken() const {
   return encoded_token;
 }
 
+std::string
+OAuth2Filter::getExpiresTimeForRefreshToken(const std::string& refresh_token,
+                                            const std::chrono::seconds& expires_in) const {
+
+  if (config_->useRefreshToken()) {
+
```
Comment (nezdolik) [inline source/extensions/filters/http/oauth2/filter.cc:553]: nit: prefer dense code lines

File: test/extensions/filters/http/oauth2/filter_test.cc [hunk 2]
```diff
@@ -1743,6 +1750,237 @@ TEST_P(OAuth2Test, OAuthAccessTokenSucessWithTokens) {
...
+                                   std::chrono::seconds(600));
+}
+
+/**
+ * Scenario: The Oauth filter doesn't save cookie with refresh token because the token is expired
+ *
+ * Expected behavior: the age of the cookie with refresh token is equaled zero.
+ */
+
+TEST_P(OAuth2Test, OAuthAccessTokenSucessWithTokens_use_refresh_token_and_expired_refresh_token) {
```
Comment (nezdolik) [inline test/extensions/filters/http/oauth2/filter_test.cc:1926]: is there is a test when jwt refresh token is parsed successfully but exp is not set in the token?

File: test/extensions/filters/http/oauth2/filter_test.cc [hunk 3]
```diff
@@ -1838,7 +2076,7 @@ TEST_P(OAuth2Test, OAuthAccessTokenSucessWithTokens_oauth_make_token_cookie_http
       {Http::Headers::get().SetCookie.get(),
        "IdToken=some-id-token;version=1;path=/;Max-Age=600;secure"},
       {Http::Headers::get().SetCookie.get(),
-       "RefreshToken=some-refresh-token;version=1;path=/;Max-Age=600;secure"},
+       "RefreshToken=some-refresh-token;version=1;path=/;Max-Age=600;secure;HttpOnly"},
```
Comment (nezdolik) [inline test/extensions/filters/http/oauth2/filter_test.cc:2079]: is this change related to the patch?

**Review by nezdolik — COMMENTED** [review]
Thank you for the contribution. Looks good overall. Consider updating [integration test](https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/oauth2/oauth_integration_test.cc) as well.

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto [hunk 4]
```diff
@@ -137,6 +137,12 @@ message OAuth2Config {
   // If this value is not set, it will default to ``0s``. In this case, the expiry must be set by
   // the authorization server or the OAuth flow will fail.
   google.protobuf.Duration default_expires_in = 13;
+
+  // The default lifetime in seconds of the refresh token, if the exp claim is omitted in the refresh token or the refresh token is not JWT
```
[the remark this answers is not in the document]
Comment (Alexcei88) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:141]: Accroding [this](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4) this is well known abbreviation.

File: source/extensions/filters/http/oauth2/filter.cc [hunk 5]
```diff
@@ -537,6 +545,34 @@ std::string OAuth2Filter::getEncodedToken() const {
...
+      if (now < expirationFromJwt) {
+        const auto expiration_epoch = expirationFromJwt - now;
+        return std::to_string(expiration_epoch.count());
+      } else {
+        ENVOY_LOG(debug, "An expiration time in the refresh token is less of the current time");
+        return "0";
+      }
+    }
+    const std::chrono::seconds default_refresh_token_expires_in =
```
[the remark this answers is not in the document]
Comment (Alexcei88) [reply source/extensions/filters/http/oauth2/filter.cc:569]: I think it is better that this field has seconds type by semantics.

File: test/extensions/filters/http/oauth2/filter_test.cc (hunk 2 above)
Comment (Alexcei88) [reply test/extensions/filters/http/oauth2/filter_test.cc:1926]: There is no such tests. But I am not sure that I don't know how to generate such token. I will try

File: test/extensions/filters/http/oauth2/filter_test.cc (hunk 3 above)
Comment (Alexcei88) [reply test/extensions/filters/http/oauth2/filter_test.cc:2079]: Yep, I set cookie with `HttpOnly` attribute. Using without this attribute causes a security problem. There is an [issue](https://github.com/envoyproxy/envoy/issues/31979) to turn on attribute by defaut. Because I have added new code I decided to add cookie with this option by default at once.

File: source/extensions/filters/http/oauth2/filter.cc [hunk 6]
```diff
@@ -537,6 +545,34 @@ std::string OAuth2Filter::getEncodedToken() const {
...
 }
 
+std::string
+OAuth2Filter::getExpiresTimeForRefreshToken(const std::string& refresh_token,
+                                            const std::chrono::seconds& expires_in) const {
+
+  if (config_->useRefreshToken()) {
+
+    ::google::jwt_verify::Jwt jwt;
+    if (jwt.parseFromString(refresh_token) == ::google::jwt_verify::Status::Ok) {
```
[the remark this answers is not in the document]
Comment (Alexcei88) [reply source/extensions/filters/http/oauth2/filter.cc:555]: I have added log

File: test/extensions/filters/http/oauth2/filter_test.cc (hunk 2 above)
Comment (nezdolik) [reply test/extensions/filters/http/oauth2/filter_test.cc]: According to JWT RFC, that field is optional: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4 in the spec

**Comment by nezdolik** [comment]
@derekargueta could you take a look?

File: test/extensions/filters/http/oauth2/filter_test.cc (hunk 2 above)
Comment (Alexcei88) [reply test/extensions/filters/http/oauth2/filter_test.cc]: I have added such test. Thank you for your attention.

**Comment by michaelsauter** [comment]
I stumbled across this PR because I ran into a related issue: https://github.com/envoyproxy/envoy/issues/32485. If I am not mistake, the implementation of reading the expiry from the JWT could be reused to solve https://github.com/envoyproxy/envoy/issues/32485 as well.

**Comment by Alexcei88** [comment]
@michaelsauter , Yes, if ID token is JWT the expiration time of the that can be taken from itself JWT.

**Comment by nezdolik** [comment]
@markdroth would you mind doing the api check for this change?

File: source/extensions/filters/http/oauth2/filter.cc [hunk 7]
```diff
@@ -362,6 +366,9 @@ Http::FilterHeadersStatus OAuth2Filter::decodeHeaders(Http::RequestHeaderMap& he
 
     // Check if we can update the access token via a refresh token.
     if (config_->useRefreshToken() && validator_->canUpdateTokenByRefreshToken()) {
+
+      ENVOY_LOG(debug, "Trying to update the access token using by the refresh token");
```
Comment (nezdolik) [inline source/extensions/filters/http/oauth2/filter.cc:370]:
```suggestion
      ENVOY_LOG(debug, "Trying to update the access token using the refresh token");
```

**Review by nezdolik — DISMISSED** [review]

**Review by lizan — COMMENTED** [review]
How common the refresh token is a JWT? I'm a bit worried about pulling JWT dependencies in the OAuth filter.

**Comment by Alexcei88** [comment]
I am using Keycloak server that is pretty popular Identity Provider. it provides the refresh token as JWT. So I consider it's common.

**Comment by michaelsauter** [comment]
> How common the refresh token is a JWT? I'm a bit worried about pulling JWT dependencies in the OAuth filter.

@lizan Please also have a look at https://github.com/envoyproxy/envoy/issues/32485. For that issue, the JWT dependencies would also be needed as an ID token is always represented as a JWT, see https://openid.net/specs/openid-connect-core-1_0.html#IDToken.

**Comment by ergonjona** [comment]
I didn't test this, but there might be an issue with the HMAC over the cookie values.
The CookieValidator should not be able to successfully validate the cookies if the only surviving cookie is the refresh token cookie since the HMAC is done with all tokens.
I think the refresh token should have it's own HMAC cookie with the same Max-Age.

Did I miss something?

**Comment by Alexcei88** [comment]
Once the access token is expired, the HMAC become invalid too. It's expected behaviour. So once next request is recieved it triggers updating the access token using the refresh token and HMAC is recalculated again.
The refresh token is accessory token. There are no succesfull requests once only refresh token exists.There is no reason to save separated HMAC for refresh token.

**Comment by fiadliel** [comment]
OAuth2 itself has nothing to say about JWTs (e.g. search for the phrase in https://datatracker.ietf.org/doc/html/rfc6749). The ID token is part of OpenID Connect Core, which does require JWTs for full support.

**Comment by ergonjona** [comment]
@Alexcei88 Thank you for your explanation, now I see that it will work.
But isn't it an issue, that the refresh token is now unsecured? An attacker may now send bogus refresh tokens, causing the filter to issue requests to the authentication server.
Those request may cause undesired load to the authentication server or even worse open a new attack vector to the authentication server and envoy.

**Comment by Alexcei88** [comment]
I don't want to add one more cookie. There are too many of them....  Do you have any idea withous adding one more HMAC cookie?

The oauth provider validates token in any case. 
The best solution would be saving the refresh token in some other place which is more secured than as cookie.

**Comment by ergonjona** [comment]
> Do you have any idea without adding one more HMAC cookie?

Well the HMAC does not need to be in a separate Cookie.
You could exclude the refresh token cookie from the original HMAC and change the refresh token cookie value to a combination of expiry + HMAC(expiry).

**Comment by Alexcei88** [comment]
@ergonjona , I not sure I catch your idea. Could you explain please what you suggest?

**Comment by ergonjona** [comment]
@Alexcei88, Excuse me, I mixed things up a little bit.
The idea is to write the refresh token and its HMAC into one cookie.
So there would be just four cookies:
- bearer_token
- id_token
- oauth_hmac (of bearer_token and id_token)
- refresh_token (with its own HMAC joined to the token value)

**Comment by Alexcei88** [comment]
I don't consider that sending an invalid refresh token to identity provider server is a critical secured issue. I expect that Identity provider server is ready for it. So, I am looking forward for review.

**Comment by Alexcei88** [comment]
@lizan , could you take a look a PR and ask questions if any

**Comment by KBaichoo** [comment]
PTAL @lizan

**Comment by KBaichoo** [comment]
Seems like this needs a merge.

Ping @lizan

**Comment by Alexcei88** [comment]
@lizan, Are you going to take a look?

**Review by lizan — COMMENTED** [review]
LGTM, can you merge main to resolve conflicts on changelog?

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto [hunk 8]
```diff
@@ -142,6 +142,12 @@ message OAuth2Config {
   // Automatic access token refresh will be performed for these requests, if enabled.
   // This behavior can be useful for AJAX requests.
   repeated config.route.v3.HeaderMatcher deny_redirect_matcher = 14;
+
+  // The default lifetime in seconds of the refresh token, if the exp (expiration time) claim is omitted in the refresh token or the refresh token is not JWT.
```
Comment (arminabf) [inline api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:146]: I suggest to mention that this setting is only considered if _use_refresh_token_ is set to true, otherwise the authorization server expiration or _defaul_expires_in_ is used

Comment (Alexcei88) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:146]: thank you, I will add

File: source/extensions/filters/http/oauth2/filter.cc [hunk 9]
```diff
@@ -24,6 +24,10 @@
 #include "absl/strings/str_cat.h"
 #include "absl/strings/str_join.h"
 #include "absl/strings/str_split.h"
+#include "jwt_verify_lib/jwt.h"
+#include "jwt_verify_lib/status.h"
+
+using namespace std::chrono_literals;
```
Comment (lizan) [inline source/extensions/filters/http/oauth2/filter.cc:30]: where is this used?

**Review by lizan — COMMENTED** [review]
One last thing, can you update this file to reflect that oauth filter is also depends on the jwt verifier?

https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl#L825

File: source/extensions/filters/http/oauth2/filter.cc (hunk 9 above)
Comment (Alexcei88) [reply source/extensions/filters/http/oauth2/filter.cc:30]: 568 line

**Comment by arminabf** [comment]
@Alexcei88 I have built the branch and tested the change in conjunction with keycloak... works as expected. Looking forward to having the fix be released. Thank you very much for your efforts!

**Review by lizan — APPROVED** [review]

**Comment by lizan** [comment]
can anyone from @envoyproxy/dependency-shepherds approve?

File: bazel/repository_locations.bzl [hunk 10]
```diff
@@ -822,7 +822,7 @@ REPOSITORY_LOCATIONS_SPEC = dict(
         strip_prefix = "jwt_verify_lib-{version}",
         urls = ["https://github.com/google/jwt_verify_lib/archive/{version}.tar.gz"],
         use_category = ["dataplane_ext"],
-        extensions = ["envoy.filters.http.jwt_authn", "envoy.filters.http.gcp_authn"],
+        extensions = ["envoy.filters.http.jwt_authn", "envoy.filters.http.gcp_authn", "envoy.filters.http.oauth2"],
```
Comment (phlax) [inline bazel/repository_locations.bzl:825]: /lgtm deps
