### PR TITLE
gzip filter: make sure the stream ends properly

### LINKED ISSUE #2909: GZip Filter doesn't work on some clients
**Title**: GZip filter doesn't work on some http clients

**Description**:
Using Gzip filter doens't work some http client (apache http client).

**Repro steps**:

1. Using curl , netcat and gunzip
- Enable GZip Filter:

```
static_resources:
  listeners:
  - address: #http-address
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: AUTO
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.gzip
            config:
              memory_level: 9
              compression_level: BEST
          - name: envoy.router
          route_config:
            virtual_hosts: #http-hosts
            - name: local-test-server
              domains:
              - test-server.com
              routes:
              - match:
                  prefix: ""
                route:
                  cluster: local-test-server
  clusters:
  - name: local-test-server
    type: STRICT_DNS
    connect_timeout:
      seconds: 60
      nanos: 0
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 1234
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

- Run a netcat server -> ./test-server
```
#!/bin/bash

echo -n -e "HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 64\r\n\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" | nc -l -p 1234
```

- Curl and try to decompress using gunzip:

```
curl -XPOST http://127.0.0.1:80 -H 'Host: test-server.com' -H 'Accept-Encoding: gzip' | gunzip -
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
gzip: stdin: unexpected end of file
```

```
curl -XGET http://127.0.0.1:80 -H 'Host: test-server.com' -H 'Accept-Encoding: gzip' | gunzip -
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
gzip: stdin: unexpected end of file
```

2. Using apache http client:

- Create a simple http client-server
- Do Request to a server returning payload >30 bytes to trigger gzip compression
- the http client raises exception

Stacktrace of the http-client:

> com.xxx.cham.http.DefaultHttpClient [DEFAULT_HTTP_CLIENT] An error occurred when trying to perform HTTP request. Request: HttpRequest{uri='http://test-api.example.com', headers={}, params={}, method=POST, body='{"example":"tetst"}', contentType=JSON, options=HttpRequestOptions{proxy='null', requestTimeout=-1, ignoreSocketTimeout=false}}::java.io.EOFException: Unexpected end of ZLIB input stream 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) 	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) 	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:70) 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) 	at java.io.InputStreamReader.read(InputStreamReader.java:184) 	at java.io.BufferedReader.fill(BufferedReader.java:161) 	at java.io.BufferedReader.readLine(BufferedReader.java:324) 	at java.io.BufferedReader.readLine(BufferedReader.java:389) 	at com.airy.cham.http.DefaultHttpClient$HttpSendRunnable.processHttpResponse(DefaultHttpClient.java:90) 	at com.airy.cham.http.DefaultHttpClient$HttpSendRunnable.doPostRequest(DefaultHttpClient.java:154) 	at com.airy.cham.http.DefaultHttpClient$HttpSendRunnable.run(DefaultHttpClient.java:187) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)
> --

The GZIP filter's test cases also doesn't seem to include HTTP POST requests

### PR DESCRIPTION
**Pull request by dio**
gzip filter: make sure the stream ends properly

This patch adds additional call of Z_FINISH to properly ends gzip
stream. This also provides a reset functionality since an ended stream 
needs to be re-init'ed.

*Risk Level*: Low

*Testing*:
- Maintain the corresponding unit and integration tests to be PASSED.
- Manual test by following repro steps defined in https://github.com/envoyproxy/envoy/issues/2909

*Docs Changes*:
N/A

*Release Notes*:
N/A

Fixes #2909 

Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

### CODE REVIEW

**Comment by dio** [comment]
@gsagula this is an attempt to try to cure #2909. Thanks!

**Comment by gsagula** [comment]
@dio I'll take a look at. Thank you for pinging me.

File: source/common/compressor/zlib_compressor_impl.cc [hunk 1]
```diff
@@ -82,5 +82,28 @@ void ZlibCompressorImpl::updateOutput(Buffer::Instance& output_buffer) {
...
+void ZlibCompressorImpl::finish(Buffer::Instance& output_buffer) {
+  // Once the Z_FINISH parameter is provided, deflate() will begin to complete the compressed output
+  // stream. However depending on how much output space is provided, deflate() may have to be called
+  // several times until it has provided the complete compressed stream, even after it has consumed
+  // all of the input. The flush parameter must continue to be Z_FINISH for those subsequent calls.
+  // Ref: https://zlib.net/zlib_how.html.
+  const int result = deflate(zstream_ptr_.get(), Z_FINISH);
+  updateOutput(output_buffer);
+  if (result == Z_OK || result == Z_BUF_ERROR) {
+    finish(output_buffer);
```
Comment (mattklein123) [inline source/common/compressor/zlib_compressor_impl.cc]: nit: prefer to do this in a loop vs recursively (even though I know the recursion depth will be small).

File: source/common/http/filter/gzip_filter.cc [hunk 2]
```diff
@@ -139,11 +139,15 @@ FilterDataStatus GzipFilter::encodeData(Buffer::Instance& data, bool end_stream)
 
   if (end_stream) {
     compressor_.flush(compressed_data_);
+    compressor_.finish(compressed_data_);
```
Comment (mattklein123) [inline source/common/http/filter/gzip_filter.cc]: I haven't look at this code much at all, but it seems like flush/finish finish can be logically combined? Shouldn't finish implicitly flush before finishing?

**Comment by gsagula** [comment]
@dio My apologies for missing the GH notifications about the issue and, thank you again for this fix! It looks great, just a few comments.

**Comment by dio** [comment]
@gsagula yes, that came to my mind while proposing this PR. Will try to have a test on it.

File: source/common/compressor/zlib_compressor_impl.cc [hunk 3]
```diff
@@ -82,5 +82,28 @@ void ZlibCompressorImpl::updateOutput(Buffer::Instance& output_buffer) {
   zstream_ptr_->next_out = chunk_char_ptr_.get();
 }
 
+void ZlibCompressorImpl::reset() {
+  const bool result = deflateReset(zstream_ptr_.get());
+  RELEASE_ASSERT(result == Z_OK);
```
[the remark this answers is not in the document]
Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: OK. Will try to have it.

File: source/common/compressor/zlib_compressor_impl.h [hunk 4]
```diff
@@ -81,6 +81,18 @@ class ZlibCompressorImpl : public Compressor {
    */
   uint64_t checksum();
 
+  /**
+   * This is required to re-init the stream after calling finish(_).
```
[the remark this answers is not in the document]
Comment (dio) [reply source/common/compressor/zlib_compressor_impl.h]: Got it.

File: source/common/compressor/zlib_compressor_impl.cc (hunk 1 above)
Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: Thanks. This is nicer. 👍

**Comment by dio** [comment]
@gsagula, so I have this simple test server in node (sorry for some `.js`) serving a small `.txt` file and an over 100MB `.pdf` file. The following will give you `Transfer-Encoding: chunked`, 

```js
const Server = require("http").Server;
const fs = require("fs");
const server = new Server((req, res) => {
  return fs
    .createReadStream(req.url == "/book" ? "book.pdf" : "a.txt")
    .pipe(res);
});

server.listen(1234);
```

Then, 

1. Run and put the server as an upstream host 
2. Get the `book.pdf` using `curl` `curl localhost:9000/book -H 'Host: test-server.com' -H 'Accept-Encoding: gzip' -o book1.pdf.gz`
4. `gunzip` the dumped file. 
5. Open the file.

Seems fine.

**Comment by gsagula** [comment]
@dio That's awesome! I will do a final pass + some manual testing a bit later. Thanks for all the work 👍

ps. (Js and Crypto) are the two words that make things popular these days 😛

File: test/common/compressor/zlib_compressor_impl_test.cc [hunk 5]
```diff
@@ -86,23 +136,7 @@ TEST_F(ZlibCompressorImplTest, CompressWithReducedInternalMemory) {
...
-  EXPECT_EQ("1f8b", header_hex_str.substr(0, 4));
-  // CM 0x8 = deflate (compression method)
-  EXPECT_EQ("08", header_hex_str.substr(4, 2));
-
-  const std::string footer_hex_str =
-      Hex::encode(reinterpret_cast<unsigned char*>(compressed_slices[num_comp_slices - 1].mem_),
-                  compressed_slices[num_comp_slices - 1].len_);
-  // FOOTER four-byte sequence (sync flush)
-  EXPECT_EQ("0000ffff", footer_hex_str.substr(footer_hex_str.size() - 8, 10));
+  expectValidCompressedBuffer(output_buffer);
```
Comment (gsagula) [inline test/common/compressor/zlib_compressor_impl_test.cc]: This looks much cleaner 👍

File: source/common/compressor/zlib_compressor_impl.cc [hunk 6]
```diff
@@ -68,18 +68,41 @@ void ZlibCompressorImpl::process(Buffer::Instance& output_buffer, int64_t flush_
   }
 
   if (flush_state == Z_SYNC_FLUSH) {
```
Comment (mattklein123) [inline source/common/compressor/zlib_compressor_impl.cc]: nit/question: IMO it's a bit strange to finish in the context of a sync_flush operation. They are distinct operations from the deflate perspective. Since I think now when we call flush() we actually want to finish(), should we remove the flush() method for now and just add a direct finish() method?

Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: @mattklein123 yes, from my test it works fine to just calling `finish()` from the filter. 

Since the `flush()` would not be used anymore, I think I need to: update the tests as well. Since the current tests are around `Z_SYNC_FLUSH`.

Comment (gsagula) [reply source/common/compressor/zlib_compressor_impl.cc]: @mattklein123 I'm in favor to delete any method that is not being used. @dio It makes sense to replace flush() with finish(), but we still use Z_SYNC_FLUSH internally, correct? FYI, as soon as I get a chance I would like to revisit this entire implementation anyway, so don't worry too much about the design.

Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: > It makes sense to replace flush() with finish(), but we still use Z_SYNC_FLUSH internally, correct?

Comment (gsagula) [reply source/common/compressor/zlib_compressor_impl.cc]: > I think without Z_SYNC_FLUSH-ing it is fine. Z_SYNC_FLUSH adds that 0000ffff right before crc32 and isize, which probably it is not necessary?

@dio Good point, but I think we still need sync for byte padding (I'll need to look into it). Here is what others have done. It seems that Z_SYNC_FLUSH is still broadly used.
  
https://github.com/apache/trafficserver/blob/711c4f4be103b44c1971196297c373d7684a0db5/plugins/gzip/gzip.cc#L319

https://github.com/facebook/proxygen/blob/1084545a0015b65882e3256fe18f505942472d40/proxygen/lib/utils/ZlibStreamCompressor.cpp#L146

https://github.com/nginx/nginx/blob/53eae18826d13cb4c7db6680029cac53bfb2a18a/src/http/modules/ngx_http_gzip_filter_module.c#L745

> Fantastic! Probably we can include deflate and deflateRaw as well

I think to do one for Brotli as well would be cool. Some interesting use-cases can be explored when multiple compression types are available :)

**Comment by dio** [comment]
@gsagula sorry for missing that. Will revert back and investigate.

**Comment by gsagula** [comment]
No worries, thanks for looking into it!
I think what you had before was correct. Deflating with `Z_NO_FLUSH` till buffer gets full,  Z_SYNC_FLUSH to do the byte-alignment, and then Z_FINISH when the end_stream is received.
Did you have a chance to test this last change with your js server and few clients?
I'm still at work, but I'll dig in a bit more when I get home.

**Comment by mattklein123** [comment]
@dio @gsagula I thought about this more, and here is actually what I think we want to do:
1) I think we basically want to SYNC_FLUSH on every data frame. The reason I think this is in the case of streaming responses where there might be long delay between data frames.
2) Then we want to FINISH on end_stream.

This is also different from what we did before. WDYT?

**Comment by gsagula** [comment]
@mattklein123 Thanks for the input. Calling SYNC_FLUSH on every data frame was in my very initial design. It simplifies a lot the implementation. I dumped it because Zlib documentation states that this might degrade compression and, it should be avoided. I didn't see too much difference to be honest
Now, thinking about slow responses, the current implementation will indeed aggravate delay. I'm in favour of changing it 👍 

Side question: Would be better also to have only one input buffer in this case?
https://github.com/dio/envoy/blob/d44d929d63d6f0821231d8341cfac2242f860a0c/source/common/compressor/zlib_compressor_impl.cc#L36

**Comment by mattklein123** [comment]
> Side question: Would be better also to have only one input buffer in this case?
https://github.com/dio/envoy/blob/d44d929d63d6f0821231d8341cfac2242f860a0c/source/common/compressor/zlib_compressor_impl.cc#L36

I would compress all slices of the input buffer, then SYNC_FLUSH. Then only if end_stream FINISH.

**Comment by mattklein123** [comment]
@dio @gsagula big apologies but you are going to lose the race with this: https://github.com/envoyproxy/envoy/pull/3074

Please merge master once that goes in. Sorry. :(

**Comment by dio** [comment]
@gsagula @mattklein123 one question. (While not end_stream) If we flush every time after we compressed all slices, this https://github.com/envoyproxy/envoy/blob/master/test/extensions/filters/http/gzip/gzip_filter_test.cc#L89 would not be true anymore.

Is it really necessary to expect `Http::FilterDataStatus::StopIterationNoBuffer` first?

I tried to change the filter's `encodeData` as follows:

```cpp
Http::FilterDataStatus GzipFilter::encodeData(Buffer::Instance& data, bool end_stream) {
  if (skip_compression_) {
    return Http::FilterDataStatus::Continue;
  }

  const uint64_t n_data = data.length();
  if (n_data > 0) {
    compressor_.compress(data, compressed_data_);
    // Always do flush after compressing all slices.
    compressor_.flush(compressed_data_);
  }

  if (end_stream) {
    compressor_.finish(compressed_data_);
  }

  if (compressed_data_.length() > 0) {
    data.drain(n_data);
    data.move(compressed_data_);
    return Http::FilterDataStatus::Continue;
  }

  return Http::FilterDataStatus::StopIterationNoBuffer;
}
```

I can confirm that it works (using that little server serving 110MB book.pdf). So I think it wouldn't hurt any kittens if I change the expectation to be:

```cpp
void doResponseCompression(Http::TestHeaderMapImpl&& headers) {
    uint64_t content_length;
    ASSERT_TRUE(StringUtil::atoul(headers.get_("content-length").c_str(), content_length));
    feedBuffer(content_length);
    EXPECT_EQ(Http::FilterHeadersStatus::Continue, filter_->encodeHeaders(headers, false));
    EXPECT_EQ("", headers.get_("content-length"));
    EXPECT_EQ(Http::Headers::get().ContentEncodingValues.Gzip, headers.get_("content-encoding"));
    // no Http::FilterDataStatus::StopIterationNoBuffer anymore.
    EXPECT_EQ(Http::FilterDataStatus::Continue, filter_->encodeData(data_, true));
    verifyCompressedData();
    drainBuffer();
}
```

WDYT?

**Comment by gsagula** [comment]
Hi @dio 

> one question. (While not end_stream) If we flush every time after compressing all slices, this https://github.com/envoyproxy/envoy/blob/master/test/extensions/filters/http/gzip/gzip_filter_test.cc#L89 would not be true anymore.

That's right. We no longer need to buffer the response.

> I tried to change the filter's encodeData as follows: 
..

Based on the above Matt's response, I think you should deflate the data frame in one pass. It would change a bit compress() implementation. That's kind of what I think.

```
Http::FilterDataStatus GzipFilter::encodeData(Buffer::Instance& data, bool end_stream) {
  if (!skip_compression_) {
     // Z_FINISH when end_stream is true, otherwise Z_FLUSH.
     compressor_.compress(data, end_stream); 
  }

  return Http::FilterDataStatus::Continue;
}
```

**Comment by dio** [comment]
@gsagula deflate-in-one-go is accommodated in the PR now. Thanks!

**Comment by gsagula** [comment]
@dio Thank you for doing this! I'll take a look at the changes a bit later today.

File: include/envoy/compressor/compressor.h [hunk 7]
```diff
@@ -13,11 +13,11 @@ class Compressor {
   virtual ~Compressor() {}
 
   /**
-   * Compresses data from one buffer into another buffer.
-   * @param input_buffer supplies the buffer with data to be compressed.
-   * @param output_buffer supplies the buffer to output compressed data.
+   * Compresses data buffer.
+   * @param buffer supplies the reference to data to be compressed.
+   * @param trailer supplies the indication to write trailer at the end of compressed buffer.
```
Comment (mattklein123) [inline include/envoy/compressor/compressor.h]: IMO "trailer" is a bit hard to understand. Personally I would just call it "finish" along with "supplies whether to finish the compression and flush any buffered compression data" WDYT?

File: source/common/compressor/zlib_compressor_impl.cc [hunk 8]
```diff
@@ -31,32 +31,38 @@ void ZlibCompressorImpl::init(CompressionLevel comp_level, CompressionStrategy c
...
+  buffer.getRawSlices(slices, num_slices);
 
   for (const Buffer::RawSlice& input_slice : slices) {
     zstream_ptr_->avail_in = input_slice.len_;
     zstream_ptr_->next_in = static_cast<Bytef*>(input_slice.mem_);
-    process(output_buffer, Z_NO_FLUSH);
+    process(buffer, Z_NO_FLUSH);
   }
+
+  buffer.drain(buffer.length());
```
Comment (mattklein123) [inline source/common/compressor/zlib_compressor_impl.cc]: How can this be correct? Aren't you compressing into the buffer directly so maybe you should only drain the initial uncompressed data? I'm confused.

Comment (gsagula) [reply source/common/compressor/zlib_compressor_impl.cc]: @mattklein123 What happens is that all the slices are taken inside `zlib` without producing any output. Only when Z_SYNC_FLUSH or Z_FINISH is called, `zlib` updates `avail_out` and `next_out`. The problem would be if we call  
If the intention is to produce output on every slice, then `Z_SYNC_FLUSH` should be used in replacement of `Z_NO_FLUSH`. I'm not sure about the benefit of doing this though.

@dio One think that we could potentially simplify, are the number of helper functions.

Comment (mattklein123) [reply source/common/compressor/zlib_compressor_impl.cc]: I see. OK can you add some comments? It's a bit confusing now.

File: include/envoy/compressor/compressor.h (hunk 7 above)
Comment (dio) [reply include/envoy/compressor/compressor.h]: @mattklein123 @gsagula before I thought that having explicit APIs like

Comment (gsagula) [reply include/envoy/compressor/compressor.h]: @dio Go ahead if you think that having a more explicit API is easier to understand and reason about it. The above were just suggestions :)

File: source/common/compressor/zlib_compressor_impl.cc (hunk 8 above)
Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: @gsagula somehow, following @mattklein123 suggestion fixed the failed test of the decompressor when using the compressor with uncommon params.

File: source/common/compressor/zlib_compressor_impl.cc [hunk 9]
```diff
@@ -42,10 +42,10 @@ void ZlibCompressorImpl::compress(Buffer::Instance& buffer, bool trailer) {
     zstream_ptr_->avail_in = input_slice.len_;
     zstream_ptr_->next_in = static_cast<Bytef*>(input_slice.mem_);
     process(buffer, Z_NO_FLUSH);
+    buffer.drain(input_slice.len_);
```
Comment (gsagula) [inline source/common/compressor/zlib_compressor_impl.cc]: I see that you found a way to use no_flush. Did you check if it works with multiple slices?

Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: I have a test in here a291b5c.

File: source/common/compressor/zlib_compressor_impl.cc [hunk 10]
```diff
@@ -31,32 +31,38 @@ void ZlibCompressorImpl::init(CompressionLevel comp_level, CompressionStrategy c
...
   const int result = deflate(zstream_ptr_.get(), flush_state);
-  if (result == Z_BUF_ERROR && zstream_ptr_->avail_in == 0) {
-    return false; // This means that zlib needs more input, so stop here.
+  switch (flush_state) {
+  case Z_FINISH:
+    if (result != Z_OK && result != Z_BUF_ERROR) {
+      RELEASE_ASSERT(result == Z_STREAM_END);
+      return false;
+    }
+  default:
```
[the remark this answers is not in the document]
Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: Will definitely check this out. 

Thinking to put the number of helpers to be minimal as your suggestion.

**Comment by dio** [comment]
@gsagula 

> - stream a large text file and save it in .gz format (the actual bug)

I have manually tested it. And I think it is passed.

> - stream a large text to clients (browser/curl --compressed)

I have manually tested it. And I think it is passed.

> - stream a non-compressible file (it actually expands)

I can see that currently the filter by default compress the stream (if the accept-encoding is required and trasferred as chunks). I think we should by default don't compress and only care for whitelisted content-type.

I can do detection (of the magic numbers) but it seems to much and will introduce false-positive?

File: source/common/compressor/zlib_compressor_impl.cc (hunk 10 above)
[the remark this answers is not in the document]
Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: @gsagula the `Z_PARTIAL_FLUSH` works confirmed by a quick manual test for a small and big file stream from upstream. (the unit tests obviously need to be adapted, do you want me to make it an option i.e. either to use SYNC_FLUSH or PARTIAL_FLUSH).

[the remark this answers is not in the document]
Comment (gsagula) [reply source/common/compressor/zlib_compressor_impl.cc]: No, I was just wondering if other states also work since the currently logic will default to any that is not Z_FINISH. Thanks for testing it.

**Comment by gsagula** [comment]
> I can see that currently, the filter by default compresses the stream (if the accept-encoding is required and transferred as chunks). I think we should by default don't compress and only care for whitelisted content-type.
I'm not sure I follow this one. Would mind to elaborate it, please?

> I can do detection (of the magic numbers) but it seems too much and will introduce false-positive?
I think checking for the magic number is still not reliable. One common idiom is to buffer the entire response, compress it and, verify that didn't expand. However, this approach would have other side-effects such as latency and memory. For now, we just compress anything and assume that most of the time this filter will be receiving compressible content.

**Comment by dio** [comment]
> I'm not sure I follow this one. Would mind to elaborate it, please?

@gsagula e.g. having this:

```yaml
          http_filters:
          - name: envoy.gzip
            config:
              memory_level: 9
              compression_level: BEST
```

when a client asks for `Accept-Encoding: gzip`, the filter compresses the upstream's stream regardless `Content-Type` (hence even when the chunks from the upstream are already compressed, the filter compresses again)

**Comment by gsagula** [comment]
> the filter compresses the upstream's stream regardless Content-Type

I don't think so, it validates against a default content-type's list if none is specified in the config:
> A response does not contain a content-type value that matches one of the selected mime-types, which default to application/javascript, application/json, application/xhtml+xml, image/svg+xml, text/css, text/html, text/plain, text/xml.

https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/gzip_filter.html?highlight=gzip#how-it-works 

https://github.com/envoyproxy/envoy/blob/55a95f481798a571ef00e02d056fe6b180de8876/source/extensions/filters/http/gzip/gzip_filter.cc#L32

**Comment by dio** [comment]
@gsagula Hum, it seems my test server doesn't send Content-Type. Haha. So it is being hit by

https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/gzip/gzip_filter.cc#L205

Sorry for false alarm.

So yeah, I think I have your concerns tested now.

**Comment by gsagula** [comment]
LGTM, Thanks for correcting it. Just one minor comment.

File: test/test_common/utility.h [hunk 11]
```diff
@@ -239,6 +239,22 @@ class TestUtility {
   ipTestParamsToString(const testing::TestParamInfo<Network::Address::IpVersion>& params) {
     return params.param == Network::Address::IpVersion::v4 ? "IPv4" : "IPv6";
   }
+
+  /**
+   * Return flip-ordered bytes.
+   * @param bytes input bytes.
+   * @return Type flip-ordered bytes.
+   */
+  template <class Type> static Type flipOrder(const Type& bytes) {
```
[the remark this answers is not in the document]
Comment (dio) [reply test/test_common/utility.h]: https://github.com/dio/envoy/blob/3f3a1757b08128dcd7f21c9a6980c5d4c9f33e69/test/common/compressor/zlib_compressor_impl_test.cc#L60 to check the correctness of stored `ISIZE` after a buffer is `Z_FINISH`-ed

File: test/common/decompressor/zlib_decompressor_impl_test.cc [hunk 12]
```diff
@@ -126,51 +164,90 @@ TEST_F(ZlibDecompressorImplTest, DecompressWithSmallOutputBuffer) {
...
   for (uint64_t i = 0; i < 20; ++i) {
-    TestUtility::feedBufferWithRandomCharacters(input_buffer, default_input_size * i, i);
-    compressor.compress(input_buffer, output_buffer);
-    original_text.append(TestUtility::bufferToString(input_buffer));
-    input_buffer.drain(default_input_size * i);
+    Buffer::BufferFragmentImpl* frag = new Buffer::BufferFragmentImpl(
+        sample.c_str(), sample.size(),
+        [](const void*, size_t, const Buffer::BufferFragmentImpl* frag) { delete frag; });
+
+    buffer.addBufferFragment(*frag);
```
[the remark this answers is not in the document]
Comment (dio) [reply test/common/decompressor/zlib_decompressor_impl_test.cc]: OK.

File: test/common/decompressor/zlib_decompressor_impl_test.cc [hunk 13]
```diff
@@ -13,6 +13,48 @@ namespace {
...
+      original_text.append(TestUtility::bufferToString(buffer));
+      compressor.compress(buffer, Compressor::State::Flush);
+      accumulation_buffer.add(buffer);
+      drainBuffer(buffer);
+    }
+
+    ASSERT_EQ(0, buffer.length());
+
+    compressor.compress(buffer, Compressor::State::Finish);
+    ASSERT_GE(10, buffer.length());
```
[the remark this answers is not in the document]
Comment (dio) [reply test/common/decompressor/zlib_decompressor_impl_test.cc]: Think this one is part of my debugging artifacts. Guess it should be 6, but I will remove it for now to avoid confusion.

File: test/test_common/utility.h (hunk 11 above)
[the remark this answers is not in the document]
Comment (gsagula) [reply test/test_common/utility.h]: Oh sorry, I didn't see.

File: include/envoy/compressor/compressor.h [hunk 14]
```diff
@@ -13,11 +18,11 @@ class Compressor {
   virtual ~Compressor() {}
 
   /**
-   * Compresses data from one buffer into another buffer.
-   * @param input_buffer supplies the buffer with data to be compressed.
-   * @param output_buffer supplies the buffer to output compressed data.
+   * Compresses data buffer.
+   * @param buffer supplies the reference to data to be compressed.
```
Comment (mattklein123) [inline include/envoy/compressor/compressor.h]: Can you specify that the buffer contents will be replaced inline with compressed data?

File: source/common/compressor/zlib_compressor_impl.cc [hunk 15]
```diff
@@ -31,32 +31,38 @@ void ZlibCompressorImpl::init(CompressionLevel comp_level, CompressionStrategy c
...
+  const uint64_t num_slices = buffer.getRawSlices(nullptr, 0);
   Buffer::RawSlice slices[num_slices];
-  input_buffer.getRawSlices(slices, num_slices);
+  buffer.getRawSlices(slices, num_slices);
 
   for (const Buffer::RawSlice& input_slice : slices) {
     zstream_ptr_->avail_in = input_slice.len_;
     zstream_ptr_->next_in = static_cast<Bytef*>(input_slice.mem_);
-    process(output_buffer, Z_NO_FLUSH);
+    process(buffer, Z_NO_FLUSH);
```
Comment (mattklein123) [inline source/common/compressor/zlib_compressor_impl.cc]: Can you add an ASSERT into `process` that confirms that in the case of Z_NO_FLUSH no data is added to the buffer? Is that always guaranteed? I'm still a little concerned about the in/out buffer behavior here. Otherwise can you add more comments?

Comment (dio) [reply source/common/compressor/zlib_compressor_impl.cc]: It turns out if with RLE, SPEED and 1 as memory level, I can see data is being added to the buffer when flush_state == Z_NO_FLUSH. Will try to debug it.

Comment (gsagula) [reply source/common/compressor/zlib_compressor_impl.cc]: Hi @mattklein123 You probably saw something that we didn't see. Question, even if data is added to the buffer, what the consequences would be?

Comment (mattklein123) [reply source/common/compressor/zlib_compressor_impl.cc]: I think it will work, because you add data to the end, and you drain from the beginning. Also, you snap the slices before you start adding, so you should never drain compressed data. However, it's not super intuitive how this works, so if you keep it this way I would add a bunch of comments (I think it's probably fine w/ comments).

Comment (gsagula) [reply source/common/compressor/zlib_compressor_impl.cc]: I agree that this is not the most intuitive design. I'm planning on revisiting this implementation as soon as I get some stuff out of my way. What I and @dio agreed, was to go for correctness now. We will add the comments though. Thanks for the input.

**Comment by dio** [comment]
Thanks, @mattklein123! I have added the comments and done a master merge.
