### PR TITLE
router: do not retry when max_retries set to 0

### LINKED ISSUE #9552: num_retries of 0 still attempts a retry
*Title*: `num_retries` set to 0 in the `retry_policy` still attempts a retry after a failure. 

*Description*:
The only way to completely stop retries seems to be to completely remove the `retry_policy` from the config.  This seems counter intuitive, since I would expect that setting the `num_retries` to 0 would stop the server from doing a retry.  None of the docs seem to indicate this caveat that i've seen (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-max-retries)

*Repro steps*:
- binary extracted from Envoyproxy v1.12.2 from Dockerhub
- bootstrap config provided below
- and no local service at the configured cluster

1. w/ a retry policy and num_retries=3, you will see the initial request + 3 retry attempts
2. w/ a retry policy and num_retries=1, you will see the initial request + 1 retry
3. w/ a retry policy and num_retries=0, you will again see the initial request + 1 retry
4. w/ no retry policy, only the initial request is seen.  No retry is attempted.  

Logs (with connection logging set to debug to see the retries)
### Config as above, `curl localhost:10000`
```bash
[2020-01-03 12:35:49.914][24240][debug][connection] [source/common/network/connection_impl.cc:711] [C2] connecting to 127.0.0.1:443
[2020-01-03 12:35:49.914][24240][debug][connection] [source/common/network/connection_impl.cc:720] [C2] connection in progress
[2020-01-03 12:35:49.914][24240][debug][connection] [source/common/network/connection_impl.cc:568] [C2] delayed connection error: 111
[2020-01-03 12:35:49.914][24240][debug][connection] [source/common/network/connection_impl.cc:193] [C2] closing socket: 0
[2020-01-03 12:35:49.930][24240][debug][connection] [source/common/network/connection_impl.cc:711] [C3] connecting to 127.0.0.1:443
[2020-01-03 12:35:49.930][24240][debug][connection] [source/common/network/connection_impl.cc:720] [C3] connection in progress
[2020-01-03 12:35:49.930][24240][debug][connection] [source/common/network/connection_impl.cc:568] [C3] delayed connection error: 111
[2020-01-03 12:35:49.930][24240][debug][connection] [source/common/network/connection_impl.cc:193] [C3] closing socket: 0
[2020-01-03 12:35:49.953][24240][debug][connection] [source/common/network/connection_impl.cc:711] [C4] connecting to 127.0.0.1:443
[2020-01-03 12:35:49.953][24240][debug][connection] [source/common/network/connection_impl.cc:720] [C4] connection in progress
[2020-01-03 12:35:49.954][24240][debug][connection] [source/common/network/connection_impl.cc:568] [C4] delayed connection error: 111
[2020-01-03 12:35:49.954][24240][debug][connection] [source/common/network/connection_impl.cc:193] [C4] closing socket: 0
[2020-01-03 12:35:49.993][24240][debug][connection] [source/common/network/connection_impl.cc:711] [C5] connecting to 127.0.0.1:443
[2020-01-03 12:35:49.993][24240][debug][connection] [source/common/network/connection_impl.cc:720] [C5] connection in progress
[2020-01-03 12:35:49.993][24240][debug][connection] [source/common/network/connection_impl.cc:568] [C5] delayed connection error: 111
[2020-01-03 12:35:49.993][24240][debug][connection] [source/common/network/connection_impl.cc:193] [C5] closing socket: 0
[2020-01-03 12:35:49.993][24240][debug][connection] [source/common/network/connection_impl.cc:527] [C1] remote close
[2020-01-03 12:35:49.993][24240][debug][connection] [source/common/network/connection_impl.cc:193] [C1] closing socket: 0
```

### `num_retries: 1`
```bash
[2020-01-03 12:37:14.722][24398][debug][connection] [source/common/network/connection_impl.cc:527] [C0] remote close
[2020-01-03 12:37:14.722][24398][debug][connection] [source/common/network/connection_impl.cc:193] [C0] closing socket: 0
[2020-01-03 12:37:15.753][24417][debug][connection] [source/common/network/connection_impl.cc:711] [C2] connecting to 127.0.0.1:443
[2020-01-03 12:37:15.753][24417][debug][connection] [source/common/network/connection_impl.cc:720] [C2] connection in progress
[2020-01-03 12:37:15.753][24417][debug][connection] [source/common/network/connection_impl.cc:568] [C2] delayed connection error: 111
[2020-01-03 12:37:15.753][24417][debug][connection] [source/common/network/connection_impl.cc:193] [C2] closing socket: 0
[2020-01-03 12:37:15.766][24417][debug][connection] [source/common/network/connection_impl.cc:711] [C3] connecting to 127.0.0.1:443
[2020-01-03 12:37:15.766][24417][debug][connection] [source/common/network/connection_impl.cc:720] [C3] connection in progress
[2020-01-03 12:37:15.766][24417][debug][connection] [source/common/network/connection_impl.cc:568] [C3] delayed connection error: 111
[2020-01-03 12:37:15.766][24417][debug][connection] [source/common/network/connection_impl.cc:193] [C3] closing socket: 0
[2020-01-03 12:37:15.766][24417][debug][connection] [source/common/network/connection_impl.cc:527] [C1] remote close
[2020-01-03 12:37:15.766][24417][debug][connection] [source/common/network/connection_impl.cc:193] [C1] closing socket: 0
```
### `num_retries: 0`
```bash
[2020-01-03 12:38:14.392][24533][debug][connection] [source/common/network/connection_impl.cc:711] [C2] connecting to 127.0.0.1:443
[2020-01-03 12:38:14.392][24533][debug][connection] [source/common/network/connection_impl.cc:720] [C2] connection in progress
[2020-01-03 12:38:14.392][24533][debug][connection] [source/common/network/connection_impl.cc:568] [C2] delayed connection error: 111
[2020-01-03 12:38:14.392][24533][debug][connection] [source/common/network/connection_impl.cc:193] [C2] closing socket: 0
[2020-01-03 12:38:14.407][24533][debug][connection] [source/common/network/connection_impl.cc:711] [C3] connecting to 127.0.0.1:443
[2020-01-03 12:38:14.407][24533][debug][connection] [source/common/network/connection_impl.cc:720] [C3] connection in progress
[2020-01-03 12:38:14.407][24533][debug][connection] [source/common/network/connection_impl.cc:568] [C3] delayed connection error: 111
[2020-01-03 12:38:14.407][24533][debug][connection] [source/common/network/connection_impl.cc:193] [C3] closing socket: 0
[2020-01-03 12:38:14.407][24533][debug][connection] [source/common/network/connection_impl.cc:527] [C1] remote close
[2020-01-03 12:38:14.407][24533][debug][connection] [source/common/network/connection_impl.cc:193] [C1] closing socket: 0
```
### No Retry policy at all
```bash
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:711] [C2] connecting to 127.0.0.1:443
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:720] [C2] connection in progress
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:568] [C2] delayed connection error: 111
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:193] [C2] closing socket: 0
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:527] [C1] remote close
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:193] [C1] closing socket: 0
```

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

```bash
justin@mal:~$ curl -X POST localhost:9901/stats
cluster.service.assignment_stale: 0
cluster.service.assignment_timeout_received: 0
cluster.service.bind_errors: 0
cluster.service.circuit_breakers.default.cx_open: 0
cluster.service.circuit_breakers.default.cx_pool_open: 0
cluster.service.circuit_breakers.default.rq_open: 0
cluster.service.circuit_breakers.default.rq_pending_open: 0
cluster.service.circuit_breakers.default.rq_retry_open: 0
cluster.service.circuit_breakers.high.cx_open: 0
cluster.service.circuit_breakers.high.cx_pool_open: 0
cluster.service.circuit_breakers.high.rq_open: 0
cluster.service.circuit_breakers.high.rq_pending_open: 0
cluster.service.circuit_breakers.high.rq_retry_open: 0
cluster.service.default.total_match_count: 1
cluster.service.external.upstream_rq_503: 1
cluster.service.external.upstream_rq_5xx: 1
cluster.service.external.upstream_rq_completed: 1
cluster.service.http1.metadata_not_supported_error: 0
cluster.service.lb_healthy_panic: 0
cluster.service.lb_local_cluster_not_ok: 0
cluster.service.lb_recalculate_zone_structures: 0
cluster.service.lb_subsets_active: 0
cluster.service.lb_subsets_created: 0
cluster.service.lb_subsets_fallback: 0
cluster.service.lb_subsets_fallback_panic: 0
cluster.service.lb_subsets_removed: 0
cluster.service.lb_subsets_selected: 0
cluster.service.lb_zone_cluster_too_small: 0
cluster.service.lb_zone_no_capacity_left: 0
cluster.service.lb_zone_number_differs: 0
cluster.service.lb_zone_routing_all_directly: 0
cluster.service.lb_zone_routing_cross_zone: 0
cluster.service.lb_zone_routing_sampled: 0
cluster.service.max_host_weight: 0
cluster.service.membership_change: 1
cluster.service.membership_degraded: 0
cluster.service.membership_excluded: 0
cluster.service.membership_healthy: 1
cluster.service.membership_total: 1
cluster.service.original_dst_host_invalid: 0
cluster.service.retry_or_shadow_abandoned: 0
cluster.service.update_attempt: 48
cluster.service.update_empty: 0
cluster.service.update_failure: 0
cluster.service.update_no_rebuild: 0
cluster.service.update_success: 48
cluster.service.upstream_cx_active: 0
cluster.service.upstream_cx_close_notify: 0
cluster.service.upstream_cx_connect_attempts_exceeded: 0
cluster.service.upstream_cx_connect_fail: 1
cluster.service.upstream_cx_connect_timeout: 0
cluster.service.upstream_cx_destroy: 1
cluster.service.upstream_cx_destroy_local: 0
cluster.service.upstream_cx_destroy_local_with_active_rq: 0
cluster.service.upstream_cx_destroy_remote: 1
cluster.service.upstream_cx_destroy_remote_with_active_rq: 0
cluster.service.upstream_cx_destroy_with_active_rq: 0
cluster.service.upstream_cx_http1_total: 1
cluster.service.upstream_cx_http2_total: 0
cluster.service.upstream_cx_idle_timeout: 0
cluster.service.upstream_cx_max_requests: 0
cluster.service.upstream_cx_none_healthy: 0
cluster.service.upstream_cx_overflow: 0
cluster.service.upstream_cx_pool_overflow: 0
cluster.service.upstream_cx_protocol_error: 0
cluster.service.upstream_cx_rx_bytes_buffered: 0
cluster.service.upstream_cx_rx_bytes_total: 0
cluster.service.upstream_cx_total: 1
cluster.service.upstream_cx_tx_bytes_buffered: 0
cluster.service.upstream_cx_tx_bytes_total: 0
cluster.service.upstream_flow_control_backed_up_total: 0
cluster.service.upstream_flow_control_drained_total: 0
cluster.service.upstream_flow_control_paused_reading_total: 0
cluster.service.upstream_flow_control_resumed_reading_total: 0
cluster.service.upstream_internal_redirect_failed_total: 0
cluster.service.upstream_internal_redirect_succeeded_total: 0
cluster.service.upstream_rq_503: 1
cluster.service.upstream_rq_5xx: 1
cluster.service.upstream_rq_active: 0
cluster.service.upstream_rq_cancelled: 0
cluster.service.upstream_rq_completed: 1
cluster.service.upstream_rq_maintenance_mode: 0
cluster.service.upstream_rq_pending_active: 0
cluster.service.upstream_rq_pending_failure_eject: 1
cluster.service.upstream_rq_pending_overflow: 0
cluster.service.upstream_rq_pending_total: 1
cluster.service.upstream_rq_per_try_timeout: 0
cluster.service.upstream_rq_retry: 0
cluster.service.upstream_rq_retry_overflow: 0
cluster.service.upstream_rq_retry_success: 0
cluster.service.upstream_rq_rx_reset: 0
cluster.service.upstream_rq_timeout: 0
cluster.service.upstream_rq_total: 0
cluster.service.upstream_rq_tx_reset: 0
cluster.service.version: 0
cluster_manager.active_clusters: 1
cluster_manager.cluster_added: 1
cluster_manager.cluster_modified: 0
cluster_manager.cluster_removed: 0
cluster_manager.cluster_updated: 0
cluster_manager.cluster_updated_via_merge: 0
cluster_manager.update_merge_cancelled: 0
cluster_manager.update_out_of_merge_window: 0
cluster_manager.warming_clusters: 0
filesystem.flushed_by_timer: 23
filesystem.reopen_failed: 0
filesystem.write_buffered: 5
filesystem.write_completed: 5
filesystem.write_failed: 0
filesystem.write_total_buffered: 0
http.admin.downstream_cx_active: 1
http.admin.downstream_cx_delayed_close_timeout: 0
http.admin.downstream_cx_destroy: 5
http.admin.downstream_cx_destroy_active_rq: 0
http.admin.downstream_cx_destroy_local: 0
http.admin.downstream_cx_destroy_local_active_rq: 0
http.admin.downstream_cx_destroy_remote: 5
http.admin.downstream_cx_destroy_remote_active_rq: 0
http.admin.downstream_cx_drain_close: 0
http.admin.downstream_cx_http1_active: 1
http.admin.downstream_cx_http1_total: 6
http.admin.downstream_cx_http2_active: 0
http.admin.downstream_cx_http2_total: 0
http.admin.downstream_cx_http3_active: 0
http.admin.downstream_cx_http3_total: 0
http.admin.downstream_cx_idle_timeout: 0
http.admin.downstream_cx_max_duration_reached: 0
http.admin.downstream_cx_overload_disable_keepalive: 0
http.admin.downstream_cx_protocol_error: 0
http.admin.downstream_cx_rx_bytes_buffered: 84
http.admin.downstream_cx_rx_bytes_total: 533
http.admin.downstream_cx_ssl_active: 0
http.admin.downstream_cx_ssl_total: 0
http.admin.downstream_cx_total: 6
http.admin.downstream_cx_tx_bytes_buffered: 0
http.admin.downstream_cx_tx_bytes_total: 20586
http.admin.downstream_cx_upgrades_active: 0
http.admin.downstream_cx_upgrades_total: 0
http.admin.downstream_flow_control_paused_reading_total: 0
http.admin.downstream_flow_control_resumed_reading_total: 0
http.admin.downstream_rq_1xx: 0
http.admin.downstream_rq_2xx: 4
http.admin.downstream_rq_3xx: 0
http.admin.downstream_rq_4xx: 1
http.admin.downstream_rq_5xx: 0
http.admin.downstream_rq_active: 1
http.admin.downstream_rq_completed: 5
http.admin.downstream_rq_http1_total: 6
http.admin.downstream_rq_http2_total: 0
http.admin.downstream_rq_http3_total: 0
http.admin.downstream_rq_idle_timeout: 0
http.admin.downstream_rq_non_relative_path: 0
http.admin.downstream_rq_overload_close: 0
http.admin.downstream_rq_response_before_rq_complete: 0
http.admin.downstream_rq_rx_reset: 0
http.admin.downstream_rq_timeout: 0
http.admin.downstream_rq_too_large: 0
http.admin.downstream_rq_total: 6
http.admin.downstream_rq_tx_reset: 0
http.admin.downstream_rq_ws_on_non_ws_route: 0
http.admin.rs_too_large: 0
http.async-client.no_cluster: 0
http.async-client.no_route: 0
http.async-client.rq_direct_response: 0
http.async-client.rq_redirect: 0
http.async-client.rq_reset_after_downstream_response_started: 0
http.async-client.rq_retry_skipped_request_not_complete: 0
http.async-client.rq_total: 0
http.ingress_http.downstream_cx_active: 0
http.ingress_http.downstream_cx_delayed_close_timeout: 0
http.ingress_http.downstream_cx_destroy: 1
http.ingress_http.downstream_cx_destroy_active_rq: 0
http.ingress_http.downstream_cx_destroy_local: 0
http.ingress_http.downstream_cx_destroy_local_active_rq: 0
http.ingress_http.downstream_cx_destroy_remote: 1
http.ingress_http.downstream_cx_destroy_remote_active_rq: 0
http.ingress_http.downstream_cx_drain_close: 0
http.ingress_http.downstream_cx_http1_active: 0
http.ingress_http.downstream_cx_http1_total: 1
http.ingress_http.downstream_cx_http2_active: 0
http.ingress_http.downstream_cx_http2_total: 0
http.ingress_http.downstream_cx_http3_active: 0
http.ingress_http.downstream_cx_http3_total: 0
http.ingress_http.downstream_cx_idle_timeout: 0
http.ingress_http.downstream_cx_max_duration_reached: 0
http.ingress_http.downstream_cx_overload_disable_keepalive: 0
http.ingress_http.downstream_cx_protocol_error: 0
http.ingress_http.downstream_cx_rx_bytes_buffered: 0
http.ingress_http.downstream_cx_rx_bytes_total: 79
http.ingress_http.downstream_cx_ssl_active: 0
http.ingress_http.downstream_cx_ssl_total: 0
http.ingress_http.downstream_cx_total: 1
http.ingress_http.downstream_cx_tx_bytes_buffered: 0
http.ingress_http.downstream_cx_tx_bytes_total: 225
http.ingress_http.downstream_cx_upgrades_active: 0
http.ingress_http.downstream_cx_upgrades_total: 0
http.ingress_http.downstream_flow_control_paused_reading_total: 0
http.ingress_http.downstream_flow_control_resumed_reading_total: 0
http.ingress_http.downstream_rq_1xx: 0
http.ingress_http.downstream_rq_2xx: 0
http.ingress_http.downstream_rq_3xx: 0
http.ingress_http.downstream_rq_4xx: 0
http.ingress_http.downstream_rq_5xx: 1
http.ingress_http.downstream_rq_active: 0
http.ingress_http.downstream_rq_completed: 1
http.ingress_http.downstream_rq_http1_total: 1
http.ingress_http.downstream_rq_http2_total: 0
http.ingress_http.downstream_rq_http3_total: 0
http.ingress_http.downstream_rq_idle_timeout: 0
http.ingress_http.downstream_rq_non_relative_path: 0
http.ingress_http.downstream_rq_overload_close: 0
http.ingress_http.downstream_rq_response_before_rq_complete: 0
http.ingress_http.downstream_rq_rx_reset: 0
http.ingress_http.downstream_rq_timeout: 0
http.ingress_http.downstream_rq_too_large: 0
http.ingress_http.downstream_rq_total: 1
http.ingress_http.downstream_rq_tx_reset: 0
http.ingress_http.downstream_rq_ws_on_non_ws_route: 0
http.ingress_http.no_cluster: 0
http.ingress_http.no_route: 0
http.ingress_http.rq_direct_response: 0
http.ingress_http.rq_redirect: 0
http.ingress_http.rq_reset_after_downstream_response_started: 0
http.ingress_http.rq_retry_skipped_request_not_complete: 0
http.ingress_http.rq_total: 1
http.ingress_http.rs_too_large: 0
http.ingress_http.tracing.client_enabled: 0
http.ingress_http.tracing.health_check: 0
http.ingress_http.tracing.not_traceable: 0
http.ingress_http.tracing.random_sampling: 0
http.ingress_http.tracing.service_forced: 0
http1.metadata_not_supported_error: 0
listener.0.0.0.0_10000.downstream_cx_active: 0
listener.0.0.0.0_10000.downstream_cx_destroy: 1
listener.0.0.0.0_10000.downstream_cx_total: 1
listener.0.0.0.0_10000.downstream_pre_cx_active: 0
listener.0.0.0.0_10000.downstream_pre_cx_timeout: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_1xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_2xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_3xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_4xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_5xx: 1
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_completed: 1
listener.0.0.0.0_10000.no_filter_chain_match: 0
listener.0.0.0.0_10000.worker_0.downstream_cx_active: 0
listener.0.0.0.0_10000.worker_0.downstream_cx_total: 0
listener.0.0.0.0_10000.worker_1.downstream_cx_active: 0
listener.0.0.0.0_10000.worker_1.downstream_cx_total: 0
listener.0.0.0.0_10000.worker_2.downstream_cx_active: 0
listener.0.0.0.0_10000.worker_2.downstream_cx_total: 0
listener.0.0.0.0_10000.worker_3.downstream_cx_active: 0
listener.0.0.0.0_10000.worker_3.downstream_cx_total: 0
listener.0.0.0.0_10000.worker_4.downstream_cx_active: 0
listener.0.0.0.0_10000.worker_4.downstream_cx_total: 0
listener.0.0.0.0_10000.worker_5.downstream_cx_active: 0
listener.0.0.0.0_10000.worker_5.downstream_cx_total: 0
listener.0.0.0.0_10000.worker_6.downstream_cx_active: 0
listener.0.0.0.0_10000.worker_6.downstream_cx_total: 0
listener.0.0.0.0_10000.worker_7.downstream_cx_active: 0
listener.0.0.0.0_10000.worker_7.downstream_cx_total: 1
listener.admin.downstream_cx_active: 1
listener.admin.downstream_cx_destroy: 5
listener.admin.downstream_cx_total: 6
listener.admin.downstream_pre_cx_active: 0
listener.admin.downstream_pre_cx_timeout: 0
listener.admin.http.admin.downstream_rq_1xx: 0
listener.admin.http.admin.downstream_rq_2xx: 4
listener.admin.http.admin.downstream_rq_3xx: 0
listener.admin.http.admin.downstream_rq_4xx: 1
listener.admin.http.admin.downstream_rq_5xx: 0
listener.admin.http.admin.downstream_rq_completed: 5
listener.admin.main_thread.downstream_cx_active: 1
listener.admin.main_thread.downstream_cx_total: 6
listener.admin.no_filter_chain_match: 0
listener_manager.listener_added: 1
listener_manager.listener_create_failure: 0
listener_manager.listener_create_success: 8
listener_manager.listener_modified: 0
listener_manager.listener_removed: 0
listener_manager.listener_stopped: 0
listener_manager.total_listeners_active: 1
listener_manager.total_listeners_draining: 0
listener_manager.total_listeners_warming: 0
runtime.admin_overrides_active: 0
runtime.deprecated_feature_use: 0
runtime.load_error: 0
runtime.load_success: 1
runtime.num_keys: 0
runtime.num_layers: 2
runtime.override_dir_exists: 0
runtime.override_dir_not_exists: 1
server.concurrency: 8
server.days_until_first_cert_expiring: 2147483647
server.debug_assertion_failures: 0
server.dynamic_unknown_fields: 0
server.hot_restart_epoch: 0
server.live: 1
server.main_thread.watchdog_mega_miss: 0
server.main_thread.watchdog_miss: 0
server.memory_allocated: 4113088
server.memory_heap_size: 5242880
server.parent_connections: 0
server.state: 0
server.static_unknown_fields: 0
server.stats_recent_lookups: 0
server.total_connections: 0
server.uptime: 235
server.version: 9381141
server.watchdog_mega_miss: 0
server.watchdog_miss: 0
server.worker_0.watchdog_mega_miss: 0
server.worker_0.watchdog_miss: 0
server.worker_1.watchdog_mega_miss: 0
server.worker_1.watchdog_miss: 0
server.worker_2.watchdog_mega_miss: 0
server.worker_2.watchdog_miss: 0
server.worker_3.watchdog_mega_miss: 0
server.worker_3.watchdog_miss: 0
server.worker_4.watchdog_mega_miss: 0
server.worker_4.watchdog_miss: 0
server.worker_5.watchdog_mega_miss: 0
server.worker_5.watchdog_miss: 0
server.worker_6.watchdog_mega_miss: 0
server.worker_6.watchdog_miss: 0
server.worker_7.watchdog_mega_miss: 0
server.worker_7.watchdog_miss: 0
cluster.service.upstream_cx_connect_ms: No recorded values
cluster.service.upstream_cx_length_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
http.admin.downstream_cx_length_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
http.admin.downstream_rq_time: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
http.ingress_http.downstream_cx_length_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
http.ingress_http.downstream_rq_time: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
listener.0.0.0.0_10000.downstream_cx_length_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
listener.admin.downstream_cx_length_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
server.initialization_time_ms: P0(nan,2) P25(nan,2.025) P50(nan,2.05) P75(nan,2.075) P90(nan,2.09) P95(nan,2.095) P99(nan,2.099) P99.5(nan,2.0995) P99.9(nan,2.0999) P100(nan,2.1)
```

### clusters
```bash
justin@mal:~$ curl -X POST localhost:9901/clusters
service::default_priority::max_connections::1024
service::default_priority::max_pending_requests::1024
service::default_priority::max_requests::1024
service::default_priority::max_retries::3
service::high_priority::max_connections::1024
service::high_priority::max_pending_requests::1024
service::high_priority::max_requests::1024
service::high_priority::max_retries::3
service::added_via_api::false
service::127.0.0.1:443::cx_active::0
service::127.0.0.1:443::cx_connect_fail::1
service::127.0.0.1:443::cx_total::1
service::127.0.0.1:443::rq_active::0
service::127.0.0.1:443::rq_error::1
service::127.0.0.1:443::rq_success::0
service::127.0.0.1:443::rq_timeout::0
service::127.0.0.1:443::rq_total::0
service::127.0.0.1:443::hostname::localhost
service::127.0.0.1:443::health_flags::healthy
service::127.0.0.1:443::weight::1
service::127.0.0.1:443::region::
service::127.0.0.1:443::zone::
service::127.0.0.1:443::sub_zone::
service::127.0.0.1:443::canary::false
service::127.0.0.1:443::priority::0
service::127.0.0.1:443::success_rate::-1
service::127.0.0.1:443::local_origin_success_rate::-1
```
### routes
* no routes endpoint on admin server

### server_info
```json
justin@mal:~$ curl -X POST localhost:9901/server_info
{
 "version": "8f2515a19bdcc75bea0bfd7016231a7661d0be6e/1.12.2/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "11.104",
 "command_line_options": {
  "base_id": "0",
  "concurrency": 8,
  "config_path": "envoy.yaml",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "info",
  "component_log_level": "",
  "log_format": "[%Y-%m-%d %T.%e][%t][%l][%n] %v",
  "log_path": "",
  "service_cluster": "",
  "service_node": "",
  "service_zone": "",
  "mode": "Serve",
  "max_stats": "0",
  "max_obj_name_len": "0",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "900s"
 },
 "uptime_current_epoch": "143s",
 "uptime_all_epochs": "143s"
}
````

*Config*:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service
                  retry_policy:
                    num_retries: 3
                    retry_on: 5xx
          http_filters:
          - name: envoy.router
  clusters:
  - name: service
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 443
```

*Logs*:
See above for log snippets of suspect behavior.  Full logs of a single run below.  

```bash
justin@mal:~$ ./envoy -c envoy.yaml 
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:249] initializing epoch 0 (hot restart version=11.104)
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:251] statically linked extensions:
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:253]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log,envoy.tcp_grpc_access_log
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:256]   filters.http: envoy.buffer,envoy.cors,envoy.csrf,envoy.ext_authz,envoy.fault,envoy.filters.http.adaptive_concurrency,envoy.filters.http.dynamic_forward_proxy,envoy.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.grpc_stats,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.original_src,envoy.filters.http.rbac,envoy.filters.http.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:259]   filters.listener: envoy.listener.http_inspector,envoy.listener.original_dst,envoy.listener.original_src,envoy.listener.proxy_protocol,envoy.listener.tls_inspector
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:262]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.filters.network.dubbo_proxy,envoy.filters.network.mysql_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thrift_proxy,envoy.filters.network.zookeeper_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:264]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:266]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.tracers.opencensus,envoy.tracers.xray,envoy.zipkin
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:269]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.transport_sockets.raw_buffer,envoy.transport_sockets.tap,envoy.transport_sockets.tls,raw_buffer,tls
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:272]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transport_sockets.raw_buffer,envoy.transport_sockets.tap,envoy.transport_sockets.tls,raw_buffer,tls
[2020-01-03 12:38:35.360][24588][info][main] [source/server/server.cc:278] buffer implementation: new
[2020-01-03 12:38:35.362][24588][info][main] [source/server/server.cc:344] admin address: 127.0.0.1:9901
[2020-01-03 12:38:35.363][24588][info][main] [source/server/server.cc:458] runtime: layers:
  - name: base
    static_layer:
      {}
  - name: admin
    admin_layer:
      {}
[2020-01-03 12:38:35.363][24588][info][config] [source/server/configuration_impl.cc:62] loading 0 static secret(s)
[2020-01-03 12:38:35.363][24588][info][config] [source/server/configuration_impl.cc:68] loading 1 cluster(s)
[2020-01-03 12:38:35.363][24588][info][config] [source/server/configuration_impl.cc:72] loading 1 listener(s)
[2020-01-03 12:38:35.364][24588][info][config] [source/server/configuration_impl.cc:97] loading tracing configuration
[2020-01-03 12:38:35.364][24588][info][config] [source/server/configuration_impl.cc:117] loading stats sink configuration
[2020-01-03 12:38:35.364][24588][info][main] [source/server/server.cc:549] starting main dispatch loop
[2020-01-03 12:38:35.364][24588][info][upstream] [source/common/upstream/cluster_manager_impl.cc:161] cm init: all clusters initialized
[2020-01-03 12:38:35.364][24588][info][main] [source/server/server.cc:528] all clusters initialized. initializing init manager
[2020-01-03 12:38:35.364][24588][info][config] [source/server/listener_manager_impl.cc:578] all dependencies initialized. starting workers
[2020-01-03 12:38:37.106][24588][debug][connection] [source/common/network/connection_impl.cc:527] [C0] remote close
[2020-01-03 12:38:37.106][24588][debug][connection] [source/common/network/connection_impl.cc:193] [C0] closing socket: 0
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:711] [C2] connecting to 127.0.0.1:443
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:720] [C2] connection in progress
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:568] [C2] delayed connection error: 111
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:193] [C2] closing socket: 0
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:527] [C1] remote close
[2020-01-03 12:38:39.122][24607][debug][connection] [source/common/network/connection_impl.cc:193] [C1] closing socket: 0
```

### PR DESCRIPTION
**Pull request by snowp**
Previously the number of retries to issue would be at least 1 as long as
the retry stanza was defined for the route. This changes this so that if
the number of retries is configured explicitly to be zero no retries are
issued.

Fixes #9552

Signed-off-by: Snow Pettersen <aickck@gmail.com>

Risk Level: Low
Testing: Added UT
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

File: include/envoy/router/router.h [hunk 1]
```diff
@@ -173,9 +173,10 @@ class RetryPolicy {
   virtual std::chrono::milliseconds perTryTimeout() const PURE;
 
   /**
-   * @return uint32_t the number of retries to allow against the route.
+   * @return absl::optional<uint32_t> the number of retries to allow against the route.
+   *         Returns absl::nullopt if no retry count was specified in the route config.
    */
-  virtual uint32_t numRetries() const PURE;
+  virtual absl::optional<uint32_t> numRetries() const PURE;
```
Comment (mattklein123) [inline include/envoy/router/router.h]: I'm tired and probably missing something obvious, but why do we need the optional here? Why can't the retries remaining just be set directly to 0 if this is what the route says, and then potentially overridden by headers?

Comment (snowp) [reply include/envoy/router/router.h]: Its to maintain the current behavior in which setting the retry-on header when hitting a route without a retry block specified (the absl::nullopt case) we should default to 1 retry.

That said I think I have an easier implementation: just change the numRetries returned by the default constructed RetryPolicy to be one. Will push that up

File: source/common/router/config_impl.h [hunk 2]
```diff
@@ -260,7 +260,7 @@ class RetryPolicyImpl : public RetryPolicy {
 
 private:
   std::chrono::milliseconds per_try_timeout_{0};
-  uint32_t num_retries_{};
+  uint32_t num_retries_{1};
```
Comment (mattklein123) [inline source/common/router/config_impl.h]: This is more clear I agree, but is this explicitly necessary just for my understanding? We default to 1 when we try to read from proto?

Comment (snowp) [reply source/common/router/config_impl.h]: It's because here https://github.com/envoyproxy/envoy/blob/master/source/common/router/config_impl.cc#L639-L655 we create a default `RetryPolicyImpl` without parsing any protos when there is no route or vhost level retry policy configured.

Comment (mattklein123) [reply source/common/router/config_impl.h]: OK got it. Do you mind adding some comments? Probably worth it given how many questions I had about this. :)

/wait
