### PR TITLE
Removes setting `BAZEL_BUILD_EXTRA_OPTIONS` in .devcontainer/setup.sh

### LINKED ISSUE #23239: tools/vscode/generate_debug_config.py Failed
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Exec `tools/vscode/generate_debug_config.py //source/exe:envoy-static  --args "-c envoy-config.yaml" --debugger lldb` failed

*Description*:
>Describe the issue.
Local OS: Mac M1
I use vscode-remote container to debug envoy, but when i exec `tools/vscode/generate_debug_config.py`, it failed, the detail is: 

image

could you please help me? thanks!
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by mathetake**
Commit Message: Removes unnecessary RBE default config in .devcontainer/setup.sh

Additional Description:
This removes the unnecessary default bazelrc configuration used in .devcontainer.
This was a cause of #23239 people asked about multiple times before.

cc @phlax 

Closes #23239

### CODE REVIEW

File: .devcontainer/setup.sh [hunk 1]
```diff
@@ -2,11 +2,9 @@
 
 BAZELRC_FILE=~/.bazelrc bazel/setup_clang.sh /opt/llvm
 
-# TODO(phlax): use user.bazelrc
-# Use generated toolchain config because we know the base container is the one we're using in RBE.
-# Not using libc++ here because clangd will raise some tidy issue in libc++ header as of version 9.
-echo "build --config=rbe-toolchain-clang-libc++" >> ~/.bazelrc
-echo "build ${BAZEL_BUILD_EXTRA_OPTIONS}" | tee -a ~/.bazelrc
+if [[ -n "${BAZEL_BUILD_EXTRA_OPTIONS}" ]]; then
+    echo "build ${BAZEL_BUILD_EXTRA_OPTIONS}" | tee -a ~/.bazelrc
```
Comment (phlax) [inline .devcontainer/setup.sh:6]: im wondering if this should be added to user.bazelrc instead - also wondering if there is a risk of the flags repeating

i dont use this, but the change looks otherwise sensible to me

Comment (mathetake) [reply .devcontainer/setup.sh:6]: yeah to be honest this could be deleted and users can simply put this either in their user.bazelrc or the global ~/.bazelrc by hand - I see no need for this setup.sh to do this on behalf of them

Comment (phlax) [reply .devcontainer/setup.sh:6]: sgtm - i suspect there are few if any vscode/rbe users - cc @envoyproxy/maintainers

**Review by phlax — APPROVED** [review]
lgtm, thanks @mathetake
