### PR TITLE
connection handler: correct the handling of listener update

### LINKED ISSUE #22449: Envoy crashes when IPv4-compat listeners are used
Hello everyone,
I recently stumbled across an issue that is leading Envoy (tested on the 1.22.2 release) to crash when IPv4-compat listeners are employed.
I already contacted the envoy security team that confirmed that this crash is not exploitable, therefore I'm opening a public GitHub issue.

The crash itself happens quite often (although not every single time) when I initialize multiple connections targeting an IPv4-compat cluster. Specifically, I noticed that this seems to happen when I do multiple burst of traffic (each with a new set of connections) targeting the same cluster.
I made a debug build of Envoy and captured multiple core-dump, all of them seem to suggest that this is related to the changes introduced in #19716.
I have also verified that reverting the aforementioned commit is preventing the issue from showing up (although this leads to the issue that got fixed by that commit).

I attach the [backtrace](https://github.com/envoyproxy/envoy/files/9212232/backtrace.log) and the [configdump](https://github.com/envoyproxy/envoy/files/9212250/configdump_crash_ipv4compat.log). Please note that the configdump was captured after my Envoy container restarted.

If needed I can share the Envoy debug build + coredump file (although the build itself is 1.6GB).
I think I should also note that I'm using the runtime flag "envoy.reloadable_features.strict_check_on_ipv4_compat".

### PR DESCRIPTION
**Pull request by soulxu**
Signed-off-by: He Jie Xu <hejie.xu@intel.com>

Commit Message: connection handler: correct the handling of listener update
Additional Description:
To balance the IPv4 mapped address request to IPv4-mapped IPv6 address listener, inserting a mapping item into `tcp_listener_map_by_address_` using IPv4 mapped address as the key.

There can be a chance to override the mapping with the same key(the IP address key). The override cases are:
1. a listener using the same IPv4 address with a listener which has the same IPv4 mapped address.
2. an update of IPv4 mapped address listener.

Currently, the override checks only allow the stopped listener can be overridden, since it prevents the IPv4 listener was override by the listener which has the same IPv4-mapped address.
https://github.com/envoyproxy/envoy/blob/a866dceb91d0ae0d2f1b45f116463bd33d1a9310/source/server/connection_handler_impl.cc#L117-L118

But this will lead to a memory leak when an update happened on an IPv4-mapped IPv6 listener.

When updating a listener, the old listener mapping will be left in the `tcp_listener_map_by_address_` since the old listener will be stopped after updated new listener. After draining the old listener, the old listener will be stopped and removed, then the old listener's left mapping item in the `tcp_listener_map_by_address_` still reference the old listener resource, which leads to segment fault.

This PR changes to check the listening address, it also can prevent the IPv4 listener was override by the listener which has the same IPv4-mapped address, and also allow the IPv4-mapped listener to update the old mapping item.

Risk Level: high
Testing: unittest added
Docs Changes: n/a
Release Notes: an item for bug fixes added.
Fixes #22449

### CODE REVIEW

File: test/server/connection_handler_test.cc [hunk 1]
```diff
@@ -1786,10 +1786,9 @@ TEST_F(ConnectionHandlerTest, MatchhIpv4WhenBothIpv4AndIPv6WithIpv4CompatFlag2)
   EXPECT_CALL(*access_log_, log(_, _, _, _));
 }
 
-// This test the case of there is stopped "0.0.0.0" listener, then add
-// "::" listener with ipv4_compat. Ensure the ipv6 listener will take over the
-// ipv4 listener.
-TEST_F(ConnectionHandlerTest, AddIpv4MappedListenerAfterIpv4ListenerStopped) {
```
Comment (soulxu) [inline test/server/connection_handler_test.cc:1792]: Note for the reviewer: after the fix, this case will be dropped. But it seems fine, it doesn't seem someone needs this case in the real world.

**Comment by soulxu** [comment]
cc @mattklein123 @ggreenway

**Comment by soulxu** [comment]
/wait

need double check

**Comment by soulxu** [comment]
This is ready for review

**Comment by soulxu** [comment]
gently ping @mattklein123 @ggreenway since want to include this into v1.22.5 release https://github.com/envoyproxy/envoy/pull/22556

**Review by mattklein123 — APPROVED** [review]
Thanks!
