### PR TITLE
websocket: fix crash when data is received after failing to connect to upstream

### LINKED ISSUE #3236: Crash with "use_websocket": true on trunk
**Bug Template**

*Title*: Crash with "use_websocket": true on trunk

*Description*:

envoy crashes on trunk (tested with f0af99c0fffd69e73f8c8c0757373729b0f970db on macOS) when WebSockets are enabled, and a particular traffic pattern is sent.

*Repro steps*:

Launch Envoy with:
```shell
$ bazel-bin/source/exe/envoy-static -c /tmp/ws-crash.json --service-cluster A --service-node B
```
using the config below.

Then send data using [tcpkali](https://github.com/satori-com/tcpkali), as follows:
```shell
$ tcpkali --ws 127.1:1111 -1 "hey" --channel-lifetime=0.1s --channel-lifetime=0.1s --channel-lifetime=0.1s
```

Envoy will immediately crash.

*Config*:
```json
{
  "listeners": [
    {
      "address": "tcp://127.0.0.1:1111",
      "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {
            "codec_type": "http1",
            "stat_prefix": "whatever",
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "whatever",
                  "domains": ["*"],
                  "routes": [
                    {
                      "prefix": "/",
                      "use_websocket": true,
                      "cluster": "whatever"
                    }
                  ]
                }
              ]
            },
            "filters": [
              {
                "type": "decoder",
                "name": "router",
                "config": {}
              }
            ]
          }
        }
        ]
    }
  ],
  "admin": {
    "access_log_path": "/dev/null",
    "address": "tcp://127.0.0.1:8001"
  },
  "cluster_manager": {
    "sds": {
      "cluster": {
        "name": "sds",
        "connect_timeout_ms": 1000,
        "type": "static",
        "lb_type": "least_request",
        "hosts": [ { "url": "tcp://127.0.0.1:443" } ]
      },
      "refresh_delay_ms": 15000    
    },
    "clusters": [
      {
        "name": "whatever",
        "connect_timeout_ms": 1000,
        "type": "sds",
        "service_name": "whatever",
        "lb_type": "round_robin"
      }
    ]
  }
}
```

*Logs*:
```
 bazel-bin/source/exe/envoy-static -c /tmp/ws-crash.json --service-cluster A --service-node B
[2018-04-26 16:21:19.862][24590546][info][main] source/server/server.cc:200] initializing epoch 0 (hot restart version=disabled)
[2018-04-26 16:21:19.863][24590546][info][main] source/server/server.cc:202] statically linked extensions:
[2018-04-26 16:21:19.863][24590546][info][main] source/server/server.cc:204]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log
[2018-04-26 16:21:19.863][24590546][info][main] source/server/server.cc:207]   filters.http: envoy.buffer,envoy.cors,envoy.ext_authz,envoy.fault,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash
[2018-04-26 16:21:19.863][24590546][info][main] source/server/server.cc:210]   filters.listener: envoy.listener.original_dst,envoy.listener.proxy_protocol,envoy.listener.tls_inspector
[2018-04-26 16:21:19.863][24590546][info][main] source/server/server.cc:213]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy
[2018-04-26 16:21:19.864][24590546][info][main] source/server/server.cc:215]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.statsd
[2018-04-26 16:21:19.864][24590546][info][main] source/server/server.cc:217]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.zipkin
[2018-04-26 16:21:19.864][24590546][info][main] source/server/server.cc:220]   transport_sockets.downstream: raw_buffer,ssl
[2018-04-26 16:21:19.864][24590546][info][main] source/server/server.cc:223]   transport_sockets.upstream: raw_buffer,ssl
[2018-04-26 16:21:19.888][24590546][info][upstream] source/common/upstream/cluster_manager_impl.cc:108] cm init: initializing secondary clusters
[2018-04-26 16:21:19.889][24590546][info][config] source/server/configuration_impl.cc:52] loading 1 listener(s)
[2018-04-26 16:21:19.900][24590546][info][config] source/server/configuration_impl.cc:92] loading tracing configuration
[2018-04-26 16:21:19.900][24590546][info][config] source/server/configuration_impl.cc:114] loading stats sink configuration
[2018-04-26 16:21:19.905][24590546][info][main] source/server/server.cc:399] starting main dispatch loop
[2018-04-26 16:21:19.908][24590546][info][upstream] source/common/upstream/cluster_manager_impl.cc:131] cm init: all clusters initialized
[2018-04-26 16:21:19.908][24590546][info][main] source/server/server.cc:383] all clusters initialized. initializing init manager
[2018-04-26 16:21:19.908][24590546][info][config] source/server/listener_manager_impl.cc:602] all dependencies initialized. starting workers
```

*Call Stack*:

Envoy immediately crashes with the following backtrace:
```
[2018-04-26 16:23:22.460][24590562][critical][assert] source/common/http/websocket/ws_handler_impl.cc:53] assert failure: queued_data_.length() == 0
[2018-04-26 16:23:22.460][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] Caught Abort trap: 6, suspect faulting address 0x7fff74b1fb6e
[2018-04-26 16:23:22.463][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:87] Backtrace obj<envoy-static> thr<123145494134784>:
[2018-04-26 16:23:22.463][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:99] thr<123145494134784> obj<envoy-static                        0x0000000106230c66 _ZN8backward7details6unwindINS_14StackTraceImplINS_10system_tag10darwin_tagEE8callbackEEEmT_m>
[2018-04-26 16:23:22.463][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<123145494134784> #0 0x106230c66: 
[2018-04-26 16:23:22.463][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:99] thr<123145494134784> obj<envoy-static>
[2018-04-26 16:23:22.463][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<123145494134784> #1 0x1062307d5: backward::StackTraceImpl<backward::system_tag::darwin_tag>::load_here(unsigned long) + 101
[2018-04-26 16:23:22.489][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<123145494134784> #2 0x1062305d1: backward::StackTraceImpl<backward::system_tag::darwin_tag>::load_from(void*, unsigned long) + 49
[2018-04-26 16:23:22.489][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<123145494134784> #3 0x10622eb2e: Envoy::BackwardsTrace::captureFrom(void*) + 46
[2018-04-26 16:23:22.489][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:105] thr<123145494134784> #4 0x10622e9ef: Envoy::SignalAction::sigHandler(int, __siginfo*, void*) + 143
[2018-04-26 16:23:22.489][24590562][critical][backtrace] bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:110] end backtrace thread 123145494134784
Abort trap: 6
```

### PR DESCRIPTION
**Pull request by ggreenway**
Fixes #3236

Signed-off-by: Greg Greenway <ggreenway@apple.com>

*Risk Level*: Low

*Testing*: Unit test added; test fails before this change

### CODE REVIEW

File: source/common/http/websocket/ws_handler_impl.cc [hunk 1]
```diff
@@ -46,6 +48,11 @@ Network::FilterStatus WsHandlerImpl::onData(Buffer::Instance& data, bool end_str
   ENVOY_LOG(debug, "WsHandlerImpl::onData with buffer length {}, end_stream == {}", data.length(),
             end_stream);
 
+  if (init_failure_) {
+    ENVOY_LOG(debug, "WsHandlerImpl::onData init_failure_ == true; discarding");
```
Comment (rshriram) [inline source/common/http/websocket/ws_handler_impl.cc]: should be trace?

File: source/common/http/websocket/ws_handler_impl.cc [hunk 2]
```diff
@@ -46,6 +48,11 @@ Network::FilterStatus WsHandlerImpl::onData(Buffer::Instance& data, bool end_str
   ENVOY_LOG(debug, "WsHandlerImpl::onData with buffer length {}, end_stream == {}", data.length(),
             end_stream);
 
+  if (init_failure_) {
```
Comment (rshriram) [inline source/common/http/websocket/ws_handler_impl.cc]: it would be nice if this logic can be moved into the if-else loop below, such that is_connected_ can become some sort of an ENUM - connecting, connected, failed_to_connect, that can be handled by a switch case.

File: source/common/http/websocket/ws_handler_impl.h [hunk 3]
```diff
@@ -62,6 +62,7 @@ class WsHandlerImpl : public Extensions::NetworkFilters::TcpProxy::TcpProxyFilte
   Buffer::OwnedImpl queued_data_;
   bool queued_end_stream_{false};
   bool is_connected_{false};
+  bool init_failure_{false};
```
Comment (rshriram) [inline source/common/http/websocket/ws_handler_impl.h]: nit: rename to upstream_failed ? or something in past tense

File: source/common/http/websocket/ws_handler_impl.cc (hunk 1 above)
Comment (ggreenway) [reply source/common/http/websocket/ws_handler_impl.cc]: All other logging in this function is at level debug, so I'll leave it this way for consistency.

Comment (ggreenway) [reply source/common/http/websocket/ws_handler_impl.cc]: And then I went and touched all of it, so I'll change it to trace.

File: source/common/http/websocket/ws_handler_impl.cc [hunk 4]
```diff
@@ -43,22 +46,29 @@ void WsHandlerImpl::onInitFailure(UpstreamFailureReason failure_reason) {
...
     queued_data_.move(data);
     queued_end_stream_ = end_stream;
+    break;
+  case ConnectState::Connected:
+    // Data should have been drained already when we transitioned to Connected.
+    ASSERT(queued_data_.length() == 0);
+
+    ENVOY_LOG(trace, "WsHandlerImpl::onData is connected");
+    return Extensions::NetworkFilters::TcpProxy::TcpProxyFilter::onData(data, end_stream);
+  case ConnectState::Failed:
```
Comment (alyssawilk) [inline source/common/http/websocket/ws_handler_impl.cc]: Any reason to not readDisable when we send the error response?  This is going to result in dropping the first onData's worth of data then buffering the rest in the network stack until we hit the connection limit.   Seems better to stop reading incoming data even if it should be a fairly fast response as it's headers-only.

Comment (ggreenway) [reply source/common/http/websocket/ws_handler_impl.cc]: I felt this made it more robust to future changes. It's already a little weird that TcpProxy is doing readDisable(true) and ConnectionManagerImpl::encodeHeaders() is doing readDisable(false). Adding another actor that modifies the readDisable() state seemed like it would just get more brittle.

Comment (alyssawilk) [reply source/common/http/websocket/ws_handler_impl.cc]: Fair.  I do think we should readDisable any time we send a response in HTTP/1.1 land but perhaps this is not the place :-)
