### PR TITLE
healthcheck: defer health check until cluster finishes warming

### LINKED ISSUE #43116: Active health checks fail when using upstream TLS with client certificate
**Description:**

_Prerequisites:_

- The cluster has a TLS transport socket configured for upstream connections.
- The TLS transport socket references a client certificate via SDS.
- The cluster has active health checking enabled.

All of these must be true for the bug to happen. If removing any of them, the problem goes away.

Control plane ([Contour](https://github.com/projectcontour/contour)) uses basic xDS with SotW updates (separate gRPC streams for each resource type).

_The Problem:_

The upstream service is unavailable for certain period of time:

- **Scenario 1:** The client gets a `503 Service Unavailable` "no healthy upstream" error for 4 minutes after Envoy restarts
  - This is counted from the moment Envoy is back up and ready with all configuration from XDS. It doesn't include the time Envoy takes to be ready serve requests.
  - The downtime lasts for `healthy_threshold` * `no_traffic_interval` (for example: 4 * 60s = 4min).
- **Scenario 2:** The client gets a `503 Service Unavailable` "no healthy upstream" error for several seconds after rotating the Envoy client certificate.
  - The downtime lasts for `healthy_threshold` * `interval` seconds (for example: 4 * 5s = 20s).

I don't know exactly which Envoy versions are affected, but this isn't just a problem in the newest code. It's not specific to any recent version.

I do not have a complete understanding of the root cause yet, but the issue appears to be related to the order in which xDS resources are delivered and processed. Envoy handles the request forwarding correctly regardless the delivery order. However, active health checks fail if the SDS secret isn't ready when the cluster and endpoints are created. This happens even if the secrets arrive just a few milliseconds later. It seems there isn't any special retry logic for this. Instead, it just acts like the upstream host is actually down.

My current theory is as follows:

**Scenario 1:** 4 minutes of unavailability after Envoy restart

Envoy is restarted and it connects to the xDS server to fetch its configuration:

1. Cluster is created via CDS with:
   - Active health checking enabled
   - TLS transport socket with SDS-referenced client certificate
2. Cluster endpoints are added via EDS
3. Health checker is started
   - Endpoints are marked unhealthy because the SDS secret is not yet available
4. SDS discovery request is sent by Envoy and the secret is delivered by the control plane
5. Cluster enters warming state and it starts sending health check probes
   - Upstream respond with success and probes succeed
   - Upstream remains unhealthy until `healthy_threshold` * `no_traffic_interval` (for example: 4 * 60s = 4min)
6. Cluster becomes healthy and client requests start to succeed

During this time (about 4 minutes) traffic is rejected with `503 Service Unavailable` "no healthy upstream".

Note: If triggering a cluster update during this period, then upstream becomes available again immediately.

**Scenario 2:** 20 seconds of unavailability after client certificate rotation

The cluster is updated with a new SDS secret reference due to certificate rotation:

1. Cluster is updated via CDS with
   - Active health checking enabled
   - TLS transport socket with new SDS reference
2. Old cluster is removed and new cluster is created
3. There is no EDS update since endpoints remain the same
4. Client requests still succeed for a while (~6 seconds but it varies)
5. Health checker for new cluster is started
   - Endpoints are marked unhealthy because the SDS secret is not yet available
   - Client requests start to fail with `503 Service Unavailable` "no healthy upstream"
6. New SDS secret is delivered
7. Cluster re-enters warming state and it starts sending health check probes
   - Upstream respond with success and probes succeed
   - Upstream remains unhealthy until `healthy_threshold` * `interval` (for example: 4 * 5s = 20s)
8. Cluster becomes healthy and client requests start to succeed

During this time (about 20 seconds) traffic is rejected with `503 Service Unavailable` "no healthy upstream".

**Repro steps:**

It's hard to provide steps to reproduce this, as it requires XDS server code. You can find the steps for Contour here: https://github.com/projectcontour/contour/issues/7384.

**Admin and Stats Output:**

Stats are included in attached logs.

**Config:**

See the XDS gRPC captures attached below.

**Logs:**

I'm attaching gRPC captures taken from control plane side of the xDS connection (Contour) using my own capture tool. They can be viewed just as plain json file or with the browser based [grpc-json-sniffer](https://github.com/tsaarni/grpc-json-sniffer) app.

* [troubleshooting-grpc-capture-certificate-rotation.json](https://github.com/user-attachments/files/24799892/troubleshooting-grpc-capture-certificate-rotation.json) xDS message dump, taken from certificate rotation test (traffic disturbance for 20 seconds) 
* [troubleshooting-logs-certificate-rotation.txt](https://github.com/user-attachments/files/24799916/troubleshooting-logs-certificate-rotation.txt) logs, stats etc, taken from certificate rotation test (which caused traffic disturbance)
* [troubleshooting-grpc-capture-envoy-restart.json](https://github.com/user-attachments/files/24799928/troubleshooting-grpc-capture-envoy-restart.json)  xDS message dump taken after Envoy restart (traffic disturbance for 4 minutes after full configuration has been received by Envoy) 
* [troubleshooting-grpc-capture-initial-httproxy-creation.json](https://github.com/user-attachments/files/24799936/troubleshooting-grpc-capture-initial-httproxy-creation.json) xDS message dump from initial/successful cluster creation (no disturbance) 
* [troubleshooting-envoy-restart.txt](https://github.com/user-attachments/files/24816796/troubleshooting-envoy-restart.txt) logs (no stats) from Envoy restart (which caused traffic disturbance). These logs have some additional debug prints I've added (lines with `[SDS-DEBUG]` prefix)

### PR DESCRIPTION
**Pull request by tsaarni**
Fixes #43116

**Commit Message:** healthcheck: defer health check until cluster finishes warming

**Additional Description:**
Active health checks started before the cluster finished initializing, causing failures when the cluster required SDS secrets for upstream connections. Health checks failed because the transport socket configuration was not ready, leading to intermittent failures at startup and when recreating the cluster to update the SDS reference, such as during certificate rotation..

See #43116 for full problem description.

This change defers the start of health checks until the cluster has finished warming, ensuring that all necessary configurations (including SDS secrets) are fetched before checks begin.

**Risk Level:** Low

**Testing:**
Added test to verify that health checks are deferred until the cluster warming state is cleared.

**Docs Changes:** N/A

**Release Notes:**
health_check: Fixed a race condition where active health checks could start before required upstream TLS SDS secrets were fetched, causing intermittent health check failures.

**Platform Specific Features:** N/A

### CODE REVIEW

**Comment by tsaarni** [comment]
Cc @yanavlasov @adisuissa

File: source/extensions/health_checkers/common/health_checker_base_impl.cc [hunk 1]
```diff
@@ -172,7 +172,11 @@ void HealthCheckerImplBase::addHosts(const HostVector& hosts) {
 
 void HealthCheckerImplBase::onClusterMemberUpdate(const HostVector& hosts_added,
                                                   const HostVector& hosts_removed) {
-  addHosts(hosts_added);
+  // Skip adding hosts while cluster is still warming (e.g., waiting for SDS secrets).
+  // start() will add all existing hosts after warming completes.
+  if (cluster_.info()->configUpdateStats().warming_state_.value() == 0) {
```
Comment (adisuissa) [inline source/extensions/health_checkers/common/health_checker_base_impl.cc]: It seems a bit strange that stats are used to determine whether the cluster is active or warmed. Is there a different path that can be used here (that avoids using the stats)?

File: source/extensions/health_checkers/common/health_checker_base_impl.cc [hunk 2]
```diff
@@ -160,7 +160,7 @@ HealthCheckerImplBase::intervalWithJitter(uint64_t base_time_ms,
 
 void HealthCheckerImplBase::addHosts(const HostVector& hosts) {
   for (const HostSharedPtr& host : hosts) {
-    if (host->disableActiveHealthCheck()) {
+    if (host->disableActiveHealthCheck() || active_sessions_.contains(host)) {
```
Comment (adisuissa) [inline source/extensions/health_checkers/common/health_checker_base_impl.cc]: I'm guessing this is an improvement that is not related to the current fix, correct?

**Review by adisuissa — COMMENTED** [review]
Thanks, the fix makes sense to me, and overall LGTM.
Please add a runtime-guard as this is a behavior-visible change, and a release note.

File: source/extensions/health_checkers/common/health_checker_base_impl.cc (hunk 1 above)
Comment (tsaarni) [reply source/extensions/health_checkers/common/health_checker_base_impl.cc]: There was not, but I have now added the new flag `HealthCheckerImplBase::started_` to track if `HealthCheckerImplBase::start()` has been called. Since `start()` is now delayed until the cluster is active, this flag effectively serves the same purpose.

File: source/extensions/health_checkers/common/health_checker_base_impl.cc (hunk 2 above)
Comment (tsaarni) [reply source/extensions/health_checkers/common/health_checker_base_impl.cc]: I needed to make this change to prevent a new issue caused by delaying `HealthCheckerImplBase::start()`: 

When running `IpVersionsClientType/LedsIntegrationTest.BasicLeds`  I got a crash due to the `ASSERT` in the health checker session destructor [here](https://github.com/envoyproxy/envoy/blob/3a0a0946868bce07c38fa3776d67fac9fdf56f00/source/extensions/health_checkers/http/health_checker_impl.cc#L220). 

With delayed `start()`, the sequence was:

1. Host is added during cluster warming.
2. Health checker is finally started and `HealthCheckerImplBase::start() ` adds all current hosts by calling `addHosts()`.
3. `HealthCheckerImplBase::onClusterMemberUpdate()` is called with the same host, which calls `addHosts()` again.
4. A new session is created, it replaces the old session object, and the destructor of to-be-replaced old session fails due to the `ASSERT(client_ == nullptr)`.

Previously, before this PR, the sequence was:

1. `HealthCheckerImplBase::start() ` is called immediately, but there are no hosts yet, so `addHosts()` is not called.
2. Host is added.
3. `HealthCheckerImplBase::onClusterMemberUpdate()` is called and the session is created successfully.

Now I'm wondering if there is any state that requires recreating the session at every cluster member update, rather than skipping creation when a session already exists. I must admit, I don't understand how the `client_` is released.

**Comment by tsaarni** [comment]
> Please add a runtime-guard as this is a behavior-visible change, and a release note.

@adisuissa I've now added a runtime guard to restore the old behavior and a test case for that.

File: source/extensions/health_checkers/common/health_checker_base_impl.cc (hunk 2 above)
Comment (tsaarni) [reply source/extensions/health_checkers/common/health_checker_base_impl.cc]: I guess  `HealthCheckerImplBase::addHosts()` was probably never called twice for the same host before this change. Maybe instead of re-creating same host, the host always went through the `HealthCheckerImplBase::onClusterMemberUpdate(..., removed_hosts)` and therefore the session, including `client_` was released [here](https://github.com/envoyproxy/envoy/blob/19ad0bd3b71cd97bf1d5c0780428bdc35d617cbc/source/extensions/health_checkers/common/health_checker_base_impl.cc#L182-L184).

**Comment by tsaarni** [comment]
@adisuissa, friendly reminder, I'd appreciate your review when you have time! I've caught up with main and resolved new conflicts.

File: source/extensions/health_checkers/common/health_checker_base_impl.cc (hunk 2 above)
Comment (adisuissa) [reply source/extensions/health_checkers/common/health_checker_base_impl.cc]: I don't have enough context here, but the fix seems OK to me as there shouldn't really be a need to make a session to the same host (assuming the previous session is already valid).
To ensure that this doesn't cause an accidental issue, it is suggested to also have this under the runtime guard.

Comment (tsaarni) [reply source/extensions/health_checkers/common/health_checker_base_impl.cc]: Thanks @adisuissa, I have placed this behind the existing runtime guard in new commit 7cb86af99f0fb6f839537d37f8ec89ce785003b9.

**Comment by agrawroh** [comment]
@tsaarni Needs a main merge.

/wait

**Comment by tsaarni** [comment]
@agrawroh I've merged.

It would be great to get this forward!

**Comment by tsaarni** [comment]
@yanavlasov @wbpcode @phlax, I’d appreciate an additional maintainer review on this PR when you have a moment 🙏

**Comment by tsaarni** [comment]
Thank you @wbpcode.
