### PR TITLE
prometheus stats: Correctly group lines of the same metric name.

### LINKED ISSUE #10073: Envoy doesn't output valid prometheus metrics
**Bug Template**

*Title*: Envoy doesn't output valid prometheus metrics

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Envoy should produce valid prometheus metrics. Specifically, it should group all metrics of the same type into a single block (which it currently does not).

From the prometheus spec [here](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md): `All lines for a given metric must be provided as one single group, with the optional HELP and TYPE lines first (in no particular order). Beyond that, reproducible sorting in repeated expositions is preferred but not required, i.e. do not sort if the computational cost is prohibitive.`

See an example in the repro steps.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Configure multiple upstreams and then curl your envoy proxy's prometheus endpoint.

Here is an example prometheus endpoint query of one of my envoy proxies below. As an example, look at the `envoy_cluster_upstream_cx_rx_bytes_total metric`. This is preventing us from reliably monitoring envoy. (Note that we're running this with Istio):

```
# TYPE envoy_cluster_upstream_cx_total counter
envoy_cluster_upstream_cx_total{cluster_name="outbound|9901||istio-galley.istio-system.svc.cluster.local"} 0
# TYPE envoy_cluster_upstream_cx_rx_bytes_total counter
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|9901||istio-galley.istio-system.svc.cluster.local"} 0
# TYPE envoy_cluster_upstream_cx_tx_bytes_total counter
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|9901||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15014||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15014||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15014||istio-galley.istio-system.svc.cluster.local"} 0
# TYPE envoy_cluster_manager_cds_update_rejected counter
envoy_cluster_manager_cds_update_rejected{} 0
# TYPE envoy_cluster_manager_cds_init_fetch_timeout counter
envoy_cluster_manager_cds_init_fetch_timeout{} 0
# TYPE envoy_cluster_manager_cds_update_attempt counter
envoy_cluster_manager_cds_update_attempt{} 48
# TYPE envoy_cluster_manager_cds_update_failure counter
envoy_cluster_manager_cds_update_failure{} 1
# TYPE envoy_cluster_manager_cds_update_success counter
envoy_cluster_manager_cds_update_success{} 46
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15014_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15014_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15014_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.8060_._.istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.8060_._.istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.8060_._.istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.443_._.serviceF.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.443_._.serviceF.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.443_._.serviceF.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|2379||serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|2379||serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|2379||serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15014||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15014||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15014||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.9091_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.9091_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.9091_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15443_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15443_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15443_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15031_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15031_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15031_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15032||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15032||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15032||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15010_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15010_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15010_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.8421_._.team-system-serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.8421_._.team-system-serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.8421_._.team-system-serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.443_._.https-service.scale-test-istio.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.443_._.https-service.scale-test-istio.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.443_._.https-service.scale-test-istio.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.443_._.istio-sidecar-injector.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.443_._.istio-sidecar-injector.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.443_._.istio-sidecar-injector.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|8080||kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|8080||kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|8080||kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.8080_._.kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.8080_._.kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.8080_._.kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15029||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15029||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15029||istio-ingressgateway.istio-system.svc.cluster.local"} 0
# TYPE envoy_listener_manager_lds_update_failure counter
envoy_listener_manager_lds_update_failure{} 1
# TYPE envoy_listener_manager_lds_init_fetch_timeout counter
envoy_listener_manager_lds_init_fetch_timeout{} 0
# TYPE envoy_listener_manager_lds_update_attempt counter
envoy_listener_manager_lds_update_attempt{} 48
# TYPE envoy_listener_manager_lds_update_rejected counter
envoy_listener_manager_lds_update_rejected{} 0
# TYPE envoy_listener_manager_lds_update_success counter
envoy_listener_manager_lds_update_success{} 46
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|443||https-service.scale-test-istio.svc.cluster.local"} 6953545
envoy_cluster_upstream_cx_total{cluster_name="outbound|443||https-service.scale-test-istio.svc.cluster.local"} 12
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|443||https-service.scale-test-istio.svc.cluster.local"} 7513272
# TYPE envoy_cluster_internal_upstream_rq counter
envoy_cluster_internal_upstream_rq{response_code_class="2xx",cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 68
envoy_cluster_upstream_cx_total{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 12
# TYPE envoy_cluster_upstream_rq counter
envoy_cluster_upstream_rq{response_code_class="2xx",cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 68
# TYPE envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds counter
envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 5494
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 36679
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|443||serviceE.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|443||serviceE.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|443||serviceE.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.2379_._.serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.2379_._.serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.2379_._.serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15011_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15011_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15011_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|8643||serviceG.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|8643||serviceG.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|8643||serviceG.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15019||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15019||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15019||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.6443_._.kube-apiserver.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.6443_._.kube-apiserver.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.6443_._.kube-apiserver.kube-system.svc.cluster.local"} 0
# TYPE envoy_listener_admin_http_admin_downstream_rq counter
envoy_listener_admin_http_admin_downstream_rq{response_code_class="4xx"} 0
envoy_listener_admin_http_admin_downstream_rq{response_code_class="5xx"} 0
# TYPE envoy_listener_admin_main_thread_downstream_cx_total counter
envoy_listener_admin_main_thread_downstream_cx_total{} 5
envoy_listener_admin_http_admin_downstream_rq{response_code_class="1xx"} 0
# TYPE envoy_listener_admin_downstream_cx_total counter
envoy_listener_admin_downstream_cx_total{} 5
envoy_listener_admin_http_admin_downstream_rq{response_code_class="2xx"} 1196
envoy_listener_admin_http_admin_downstream_rq{response_code_class="3xx"} 0
# TYPE envoy_http_stats_downstream_cx_tx_bytes_total counter
envoy_http_stats_downstream_cx_tx_bytes_total{} 1410002
# TYPE envoy_http_stats_downstream_rq counter
envoy_http_stats_downstream_rq{response_code_class="3xx"} 0
envoy_http_stats_downstream_rq{response_code_class="5xx"} 0
# TYPE envoy_http_stats_downstream_cx_total counter
envoy_http_stats_downstream_cx_total{} 136
envoy_http_stats_downstream_rq{response_code_class="4xx"} 0
envoy_http_stats_downstream_rq{response_code_class="1xx"} 0
envoy_http_stats_downstream_rq{response_code_class="2xx"} 135
# TYPE envoy_http_stats_downstream_cx_rx_bytes_total counter
envoy_http_stats_downstream_cx_rx_bytes_total{} 37355
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|53||kube-dns.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|53||kube-dns.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|53||kube-dns.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.31001_._.k8s-serviceB.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.31001_._.k8s-serviceB.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.31001_._.k8s-serviceB.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15014_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15014_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15014_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15443||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15443||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15443||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15029_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15029_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15029_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|8421||serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|8421||serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|8421||serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.443_._.kubernetes.default.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.443_._.kubernetes.default.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.443_._.kubernetes.default.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.80_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.80_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.80_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|8060||istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|8060||istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|8060||istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|31001||k8s-serviceB.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|31001||k8s-serviceB.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|31001||k8s-serviceB.team-system.svc.cluster.local"} 0
# TYPE envoy_cluster_upstream_rq_pending_overflow counter
envoy_cluster_upstream_rq_pending_overflow{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_zone_routing_sampled counter
envoy_cluster_lb_zone_routing_sampled{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_ssl_session_reused counter
envoy_cluster_ssl_session_reused{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_healthy_panic counter
envoy_cluster_lb_healthy_panic{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_upstream_cx_connect_attempts_exceeded counter
envoy_cluster_upstream_cx_connect_attempts_exceeded{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_internal_redirect_failed_total counter
envoy_cluster_upstream_internal_redirect_failed_total{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_ssl_sigalgs_rsa_pss_rsae_sha256 counter
envoy_cluster_ssl_sigalgs_rsa_pss_rsae_sha256{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_upstream_rq_200 counter
envoy_cluster_upstream_rq_200{cluster_name="xds-grpc"} 2
# TYPE envoy_cluster_http2_outbound_flood counter
envoy_cluster_http2_outbound_flood{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_subsets_created counter
envoy_cluster_lb_subsets_created{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_destroy_with_active_rq counter
envoy_cluster_upstream_cx_destroy_with_active_rq{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_assignment_timeout_received counter
envoy_cluster_assignment_timeout_received{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_close_notify counter
envoy_cluster_upstream_cx_close_notify{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_http2_outbound_control_flood counter
envoy_cluster_http2_outbound_control_flood{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_ssl_versions_TLSv1_2 counter
envoy_cluster_ssl_versions_TLSv1_2{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_upstream_cx_destroy_remote counter
envoy_cluster_upstream_cx_destroy_remote{cluster_name="xds-grpc"} 0
envoy_cluster_internal_upstream_rq{response_code_class="2xx",cluster_name="xds-grpc"} 2
# TYPE envoy_cluster_upstream_cx_idle_timeout counter
envoy_cluster_upstream_cx_idle_timeout{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_internal_upstream_rq_503 counter
envoy_cluster_internal_upstream_rq_503{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_upstream_flow_control_paused_reading_total counter
envoy_cluster_upstream_flow_control_paused_reading_total{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_http2_too_many_header_frames counter
envoy_cluster_http2_too_many_header_frames{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_zone_number_differs counter
envoy_cluster_lb_zone_number_differs{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_flow_control_backed_up_total counter
envoy_cluster_upstream_flow_control_backed_up_total{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_cancelled counter
envoy_cluster_upstream_rq_cancelled{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_zone_routing_cross_zone counter
envoy_cluster_lb_zone_routing_cross_zone{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_pending_total counter
envoy_cluster_upstream_rq_pending_total{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_upstream_rq_timeout counter
envoy_cluster_upstream_rq_timeout{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_http2_inbound_window_update_frames_flood counter
envoy_cluster_http2_inbound_window_update_frames_flood{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_bind_errors counter
envoy_cluster_bind_errors{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_membership_change counter
envoy_cluster_membership_change{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_ssl_fail_verify_no_cert counter
envoy_cluster_ssl_fail_verify_no_cert{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_completed counter
envoy_cluster_upstream_rq_completed{cluster_name="xds-grpc"} 3
# TYPE envoy_cluster_ssl_curves_X25519 counter
envoy_cluster_ssl_curves_X25519{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_original_dst_host_invalid counter
envoy_cluster_original_dst_host_invalid{cluster_name="xds-grpc"} 0
envoy_cluster_upstream_cx_total{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_internal_upstream_rq_200 counter
envoy_cluster_internal_upstream_rq_200{cluster_name="xds-grpc"} 2
# TYPE envoy_cluster_default_total_match_count counter
envoy_cluster_default_total_match_count{cluster_name="xds-grpc"} 7
# TYPE envoy_cluster_http2_tx_reset counter
envoy_cluster_http2_tx_reset{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_update_attempt counter
envoy_cluster_update_attempt{cluster_name="xds-grpc"} 7
# TYPE envoy_cluster_upstream_internal_redirect_succeeded_total counter
envoy_cluster_upstream_internal_redirect_succeeded_total{cluster_name="xds-grpc"} 0
envoy_cluster_upstream_rq{response_code_class="5xx",cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_client_ssl_socket_factory_downstream_context_secrets_not_ready counter
envoy_cluster_client_ssl_socket_factory_downstream_context_secrets_not_ready{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_pool_overflow counter
envoy_cluster_upstream_cx_pool_overflow{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_http1_total counter
envoy_cluster_upstream_cx_http1_total{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_flow_control_resumed_reading_total counter
envoy_cluster_upstream_flow_control_resumed_reading_total{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_destroy_local_with_active_rq counter
envoy_cluster_upstream_cx_destroy_local_with_active_rq{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_subsets_fallback_panic counter
envoy_cluster_lb_subsets_fallback_panic{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_max_requests counter
envoy_cluster_upstream_cx_max_requests{cluster_name="xds-grpc"} 0
envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds{cluster_name="xds-grpc"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="xds-grpc"} 593552
# TYPE envoy_cluster_upstream_cx_connect_fail counter
envoy_cluster_upstream_cx_connect_fail{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_none_healthy counter
envoy_cluster_upstream_cx_none_healthy{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_http2_trailers counter
envoy_cluster_http2_trailers{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_flow_control_drained_total counter
envoy_cluster_upstream_flow_control_drained_total{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_retry counter
envoy_cluster_upstream_rq_retry{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_internal_upstream_rq_completed counter
envoy_cluster_internal_upstream_rq_completed{cluster_name="xds-grpc"} 3
# TYPE envoy_cluster_lb_subsets_removed counter
envoy_cluster_lb_subsets_removed{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_http2_header_overflow counter
envoy_cluster_http2_header_overflow{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_update_empty counter
envoy_cluster_update_empty{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_http2_total counter
envoy_cluster_upstream_cx_http2_total{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_http2_rx_messaging_error counter
envoy_cluster_http2_rx_messaging_error{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_http2_rx_reset counter
envoy_cluster_http2_rx_reset{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_upstream_rq_maintenance_mode counter
envoy_cluster_upstream_rq_maintenance_mode{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_update_success counter
envoy_cluster_update_success{cluster_name="xds-grpc"} 7
# TYPE envoy_cluster_lb_zone_routing_all_directly counter
envoy_cluster_lb_zone_routing_all_directly{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_total counter
envoy_cluster_upstream_rq_total{cluster_name="xds-grpc"} 2
# TYPE envoy_cluster_upstream_cx_destroy_local counter
envoy_cluster_upstream_cx_destroy_local{cluster_name="xds-grpc"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="xds-grpc"} 3755664
# TYPE envoy_cluster_ssl_fail_verify_san counter
envoy_cluster_ssl_fail_verify_san{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_recalculate_zone_structures counter
envoy_cluster_lb_recalculate_zone_structures{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_retry_success counter
envoy_cluster_upstream_rq_retry_success{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_ssl_ciphers_ECDHE_RSA_AES128_GCM_SHA256 counter
envoy_cluster_ssl_ciphers_ECDHE_RSA_AES128_GCM_SHA256{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_update_failure counter
envoy_cluster_update_failure{cluster_name="xds-grpc"} 0
envoy_cluster_upstream_rq{response_code_class="2xx",cluster_name="xds-grpc"} 2
# TYPE envoy_cluster_upstream_cx_overflow counter
envoy_cluster_upstream_cx_overflow{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_ssl_handshake counter
envoy_cluster_ssl_handshake{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_ssl_fail_verify_error counter
envoy_cluster_ssl_fail_verify_error{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_tx_reset counter
envoy_cluster_upstream_rq_tx_reset{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_subsets_selected counter
envoy_cluster_lb_subsets_selected{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_subsets_fallback counter
envoy_cluster_lb_subsets_fallback{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_ssl_fail_verify_cert_hash counter
envoy_cluster_ssl_fail_verify_cert_hash{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_update_no_rebuild counter
envoy_cluster_update_no_rebuild{cluster_name="xds-grpc"} 6
# TYPE envoy_cluster_client_ssl_socket_factory_upstream_context_secrets_not_ready counter
envoy_cluster_client_ssl_socket_factory_upstream_context_secrets_not_ready{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_pending_failure_eject counter
envoy_cluster_upstream_rq_pending_failure_eject{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_retry_overflow counter
envoy_cluster_upstream_rq_retry_overflow{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_503 counter
envoy_cluster_upstream_rq_503{cluster_name="xds-grpc"} 1
envoy_cluster_internal_upstream_rq{response_code_class="5xx",cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_assignment_stale counter
envoy_cluster_assignment_stale{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_http2_headers_cb_no_stream counter
envoy_cluster_http2_headers_cb_no_stream{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_destroy counter
envoy_cluster_upstream_cx_destroy{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_zone_no_capacity_left counter
envoy_cluster_lb_zone_no_capacity_left{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_retry_or_shadow_abandoned counter
envoy_cluster_retry_or_shadow_abandoned{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_connect_timeout counter
envoy_cluster_upstream_cx_connect_timeout{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_protocol_error counter
envoy_cluster_upstream_cx_protocol_error{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_http2_inbound_empty_frames_flood counter
envoy_cluster_http2_inbound_empty_frames_flood{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_destroy_remote_with_active_rq counter
envoy_cluster_upstream_cx_destroy_remote_with_active_rq{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_http2_inbound_priority_frames_flood counter
envoy_cluster_http2_inbound_priority_frames_flood{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_ssl_no_certificate counter
envoy_cluster_ssl_no_certificate{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_local_cluster_not_ok counter
envoy_cluster_lb_local_cluster_not_ok{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_zone_cluster_too_small counter
envoy_cluster_lb_zone_cluster_too_small{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_per_try_timeout counter
envoy_cluster_upstream_rq_per_try_timeout{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_ssl_connection_error counter
envoy_cluster_ssl_connection_error{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_rx_reset counter
envoy_cluster_upstream_rq_rx_reset{cluster_name="xds-grpc"} 1
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15014||istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15014||istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15014||istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|8080||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|8080||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|8080||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15014||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15014||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15014||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.9901_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.9901_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.9901_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15019_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15019_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15019_._.istio-galley.istio-system.svc.cluster.local"} 0
# TYPE envoy_http_mixer_filter_total_remote_quota_calls counter
envoy_http_mixer_filter_total_remote_quota_calls{} 0
# TYPE envoy_http_mixer_filter_total_remote_check_denies counter
envoy_http_mixer_filter_total_remote_check_denies{} 0
# TYPE envoy_http_mixer_filter_total_remote_call_send_errors counter
envoy_http_mixer_filter_total_remote_call_send_errors{} 0
# TYPE envoy_http_mixer_filter_total_remote_quota_denies counter
envoy_http_mixer_filter_total_remote_quota_denies{} 0
# TYPE envoy_http_mixer_filter_total_quota_cache_misses counter
envoy_http_mixer_filter_total_quota_cache_misses{} 0
# TYPE envoy_http_outbound_0_0_0_0_80_downstream_rq counter
envoy_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="1xx"} 0
# TYPE envoy_http_mixer_filter_total_remote_quota_prefetch_calls counter
envoy_http_mixer_filter_total_remote_quota_prefetch_calls{} 0
# TYPE envoy_http_mixer_filter_total_remote_call_timeouts counter
envoy_http_mixer_filter_total_remote_call_timeouts{} 0
# TYPE envoy_http_mixer_filter_total_check_calls counter
envoy_http_mixer_filter_total_check_calls{} 0
# TYPE envoy_http_mixer_filter_total_remote_check_calls counter
envoy_http_mixer_filter_total_remote_check_calls{} 0
# TYPE envoy_http_mixer_filter_total_remote_check_accepts counter
envoy_http_mixer_filter_total_remote_check_accepts{} 0
# TYPE envoy_http_mixer_filter_total_remote_quota_accepts counter
envoy_http_mixer_filter_total_remote_quota_accepts{} 0
# TYPE envoy_http_mixer_filter_total_remote_call_retries counter
envoy_http_mixer_filter_total_remote_call_retries{} 0
# TYPE envoy_http_mixer_filter_total_quota_cache_hits counter
envoy_http_mixer_filter_total_quota_cache_hits{} 0
# TYPE envoy_http_mixer_filter_total_remote_calls counter
envoy_http_mixer_filter_total_remote_calls{} 0
# TYPE envoy_http_mixer_filter_total_remote_call_cancellations counter
envoy_http_mixer_filter_total_remote_call_cancellations{} 0
# TYPE envoy_http_mixer_filter_total_report_calls counter
envoy_http_mixer_filter_total_report_calls{} 0
# TYPE envoy_http_mixer_filter_total_check_cache_hits counter
envoy_http_mixer_filter_total_check_cache_hits{} 0
# TYPE envoy_http_outbound_0_0_0_0_80_downstream_cx_rx_bytes_total counter
envoy_http_outbound_0_0_0_0_80_downstream_cx_rx_bytes_total{} 0
# TYPE envoy_http_mixer_filter_total_quota_calls counter
envoy_http_mixer_filter_total_quota_calls{} 0
# TYPE envoy_http_outbound_0_0_0_0_80_downstream_cx_tx_bytes_total counter
envoy_http_outbound_0_0_0_0_80_downstream_cx_tx_bytes_total{} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="4xx"} 0
# TYPE envoy_http_mixer_filter_total_remote_call_successes counter
envoy_http_mixer_filter_total_remote_call_successes{} 0
# TYPE envoy_http_mixer_filter_total_check_cache_misses counter
envoy_http_mixer_filter_total_check_cache_misses{} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="2xx"} 0
# TYPE envoy_http_outbound_0_0_0_0_80_downstream_cx_total counter
envoy_http_outbound_0_0_0_0_80_downstream_cx_total{} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="3xx"} 0
# TYPE envoy_http_mixer_filter_total_quota_cache_hit_accepts counter
envoy_http_mixer_filter_total_quota_cache_hit_accepts{} 0
# TYPE envoy_http_mixer_filter_total_remote_report_calls counter
envoy_http_mixer_filter_total_remote_report_calls{} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="5xx"} 0
# TYPE envoy_http_mixer_filter_total_remote_call_other_errors counter
envoy_http_mixer_filter_total_remote_call_other_errors{} 0
# TYPE envoy_http_mixer_filter_total_quota_cache_hit_denies counter
envoy_http_mixer_filter_total_quota_cache_hit_denies{} 0
# TYPE envoy_http_mixer_filter_total_remote_report_send_errors counter
envoy_http_mixer_filter_total_remote_report_send_errors{} 0
# TYPE envoy_http_mixer_filter_total_check_cache_hit_accepts counter
envoy_http_mixer_filter_total_check_cache_hit_accepts{} 0
# TYPE envoy_http_mixer_filter_total_remote_report_successes counter
envoy_http_mixer_filter_total_remote_report_successes{} 0
# TYPE envoy_http_mixer_filter_total_remote_report_other_errors counter
envoy_http_mixer_filter_total_remote_report_other_errors{} 0
# TYPE envoy_http_mixer_filter_total_remote_report_timeouts counter
envoy_http_mixer_filter_total_remote_report_timeouts{} 0
# TYPE envoy_http_mixer_filter_total_check_cache_hit_denies counter
envoy_http_mixer_filter_total_check_cache_hit_denies{} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15004_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15004_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15004_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15031||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15031||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15031||istio-ingressgateway.istio-system.svc.cluster.local"} 0
# TYPE envoy_listener_manager_listener_modified counter
envoy_listener_manager_listener_modified{} 0
# TYPE envoy_listener_manager_listener_create_failure counter
envoy_listener_manager_listener_create_failure{} 0
# TYPE envoy_listener_manager_listener_stopped counter
envoy_listener_manager_listener_stopped{} 0
# TYPE envoy_listener_manager_listener_added counter
envoy_listener_manager_listener_added{} 3
# TYPE envoy_listener_manager_listener_removed counter
envoy_listener_manager_listener_removed{} 1
# TYPE envoy_listener_manager_listener_create_success counter
envoy_listener_manager_listener_create_success{} 12
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|443||serviceF.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|443||serviceF.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|443||serviceF.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.8200_._.serviceD.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.8200_._.serviceD.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.8200_._.serviceD.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.8643_._.serviceG.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.8643_._.serviceG.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.8643_._.serviceG.team-system.svc.cluster.local"} 0
# TYPE envoy_listener_http_stats_downstream_rq counter
envoy_listener_http_stats_downstream_rq{response_code_class="4xx",listener_address="0.0.0.0_15090"} 0
envoy_listener_http_stats_downstream_rq{response_code_class="5xx",listener_address="0.0.0.0_15090"} 0
envoy_listener_http_stats_downstream_rq{response_code_class="1xx",listener_address="0.0.0.0_15090"} 0
# TYPE envoy_listener_worker_0_downstream_cx_total counter
envoy_listener_worker_0_downstream_cx_total{listener_address="0.0.0.0_15090"} 20
# TYPE envoy_listener_downstream_cx_total counter
envoy_listener_downstream_cx_total{listener_address="0.0.0.0_15090"} 136
envoy_listener_http_stats_downstream_rq{response_code_class="3xx",listener_address="0.0.0.0_15090"} 0
envoy_listener_http_stats_downstream_rq{response_code_class="2xx",listener_address="0.0.0.0_15090"} 135
# TYPE envoy_listener_worker_2_downstream_cx_total counter
envoy_listener_worker_2_downstream_cx_total{listener_address="0.0.0.0_15090"} 37
# TYPE envoy_listener_worker_3_downstream_cx_total counter
envoy_listener_worker_3_downstream_cx_total{listener_address="0.0.0.0_15090"} 64
# TYPE envoy_listener_worker_1_downstream_cx_total counter
envoy_listener_worker_1_downstream_cx_total{listener_address="0.0.0.0_15090"} 15
envoy_cluster_upstream_cx_total{cluster_name="outbound_.8081_._.kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.8081_._.kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.8081_._.kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|443||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|443||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|443||istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15014_._.istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15014_._.istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15014_._.istio-citadel.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.123_._.serviceH-operator-reflector-health-check.team-serviceG.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.123_._.serviceH-operator-reflector-health-check.team-serviceG.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.123_._.serviceH-operator-reflector-health-check.team-serviceG.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|8200||serviceD.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|8200||serviceD.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|8200||serviceD.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|443||kubernetes.default.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|443||kubernetes.default.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|443||kubernetes.default.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15020||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15020||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15020||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_listener_worker_0_downstream_cx_total{listener_address="0.0.0.0_80"} 0
# TYPE envoy_listener_http_outbound_0_0_0_0_80_downstream_rq counter
envoy_listener_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="2xx",listener_address="0.0.0.0_80"} 0
envoy_listener_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="1xx",listener_address="0.0.0.0_80"} 0
envoy_listener_worker_1_downstream_cx_total{listener_address="0.0.0.0_80"} 0
envoy_listener_worker_2_downstream_cx_total{listener_address="0.0.0.0_80"} 0
envoy_listener_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="4xx",listener_address="0.0.0.0_80"} 0
envoy_listener_downstream_cx_total{listener_address="0.0.0.0_80"} 0
envoy_listener_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="5xx",listener_address="0.0.0.0_80"} 0
envoy_listener_worker_3_downstream_cx_total{listener_address="0.0.0.0_80"} 0
envoy_listener_http_outbound_0_0_0_0_80_downstream_rq{response_code_class="3xx",listener_address="0.0.0.0_80"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|80||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|80||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|80||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|123||serviceH-operator-reflector-health-check.team-serviceG.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|123||serviceH-operator-reflector-health-check.team-serviceG.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|123||serviceH-operator-reflector-health-check.team-serviceG.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|8421||team-system-serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|8421||team-system-serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|8421||team-system-serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15032_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15032_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15032_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|2380||serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|2380||serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|2380||serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|6443||kube-apiserver.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|6443||kube-apiserver.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|6443||kube-apiserver.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.443_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.443_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.443_._.istio-galley.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.443_._.serviceE.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.443_._.serviceE.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.443_._.serviceE.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="prometheus_stats"} 4
# TYPE envoy_cluster_external_upstream_rq counter
envoy_cluster_external_upstream_rq{response_code_class="2xx",cluster_name="prometheus_stats"} 135
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="prometheus_stats"} 1404495
envoy_cluster_upstream_rq{response_code_class="2xx",cluster_name="prometheus_stats"} 135
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="prometheus_stats"} 52475
envoy_cluster_upstream_cx_total{cluster_name="outbound|15030||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15030||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15030||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.53_._.kube-dns.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.53_._.kube-dns.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.53_._.kube-dns.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.2380_._.serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.2380_._.serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.2380_._.serviceA-etcd.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="BlackHoleCluster"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="BlackHoleCluster"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="BlackHoleCluster"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15020_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15020_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15020_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.443_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.443_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.443_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|443||istio-sidecar-injector.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|443||istio-sidecar-injector.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|443||istio-sidecar-injector.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15010||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15010||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15010||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.42422_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.42422_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.42422_._.istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.8421_._.serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.8421_._.serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.8421_._.serviceC.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15030_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15030_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15030_._.istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|443||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|443||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|443||istio-ingressgateway.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|9091||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|9091||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|9091||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.8080_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.8080_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.8080_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.443_._.https-service.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.443_._.https-service.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.443_._.https-service.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|8081||kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|8081||kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|8081||kube-state-metrics.kube-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|443||https-service.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|443||https-service.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|443||https-service.team-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|42422||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|42422||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|42422||istio-telemetry.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="zipkin"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="zipkin"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="zipkin"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound|15011||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound|15011||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound|15011||istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_rx_bytes_total{cluster_name="outbound_.15014_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_tx_bytes_total{cluster_name="outbound_.15014_._.istio-pilot.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_total{cluster_name="outbound_.15014_._.istio-pilot.istio-system.svc.cluster.local"} 0
# TYPE envoy_http_admin_downstream_rq counter
envoy_http_admin_downstream_rq{response_code_class="2xx"} 1196
# TYPE envoy_cluster_manager_update_out_of_merge_window counter
envoy_cluster_manager_update_out_of_merge_window{} 0
# TYPE envoy_server_worker_1_watchdog_mega_miss counter
envoy_server_worker_1_watchdog_mega_miss{} 0
# TYPE envoy_cluster_manager_cluster_modified counter
envoy_cluster_manager_cluster_modified{} 0
# TYPE envoy_server_worker_3_watchdog_mega_miss counter
envoy_server_worker_3_watchdog_mega_miss{} 0
# TYPE envoy_http_admin_downstream_cx_tx_bytes_total counter
envoy_http_admin_downstream_cx_tx_bytes_total{} 2797885
# TYPE envoy_server_worker_2_watchdog_miss counter
envoy_server_worker_2_watchdog_miss{} 0
# TYPE envoy_http_admin_downstream_cx_total counter
envoy_http_admin_downstream_cx_total{} 5
# TYPE envoy_cluster_manager_cluster_updated counter
envoy_cluster_manager_cluster_updated{} 100
# TYPE envoy_server_watchdog_miss counter
envoy_server_watchdog_miss{} 0
envoy_http_admin_downstream_rq{response_code_class="1xx"} 0
# TYPE envoy_server_debug_assertion_failures counter
envoy_server_debug_assertion_failures{} 0
envoy_http_admin_downstream_rq{response_code_class="4xx"} 0
# TYPE envoy_server_main_thread_watchdog_miss counter
envoy_server_main_thread_watchdog_miss{} 0
# TYPE envoy_server_worker_2_watchdog_mega_miss counter
envoy_server_worker_2_watchdog_mega_miss{} 0
# TYPE envoy_server_dynamic_unknown_fields counter
envoy_server_dynamic_unknown_fields{} 0
# TYPE envoy_server_static_unknown_fields counter
envoy_server_static_unknown_fields{} 0
# TYPE envoy_cluster_manager_update_merge_cancelled counter
envoy_cluster_manager_update_merge_cancelled{} 0
# TYPE envoy_server_worker_1_watchdog_miss counter
envoy_server_worker_1_watchdog_miss{} 0
# TYPE envoy_server_worker_0_watchdog_mega_miss counter
envoy_server_worker_0_watchdog_mega_miss{} 0
# TYPE envoy_cluster_manager_cluster_removed counter
envoy_cluster_manager_cluster_removed{} 0
# TYPE envoy_http_admin_downstream_cx_rx_bytes_total counter
envoy_http_admin_downstream_cx_rx_bytes_total{} 166005
envoy_http_admin_downstream_rq{response_code_class="5xx"} 0
# TYPE envoy_server_watchdog_mega_miss counter
envoy_server_watchdog_mega_miss{} 0
# TYPE envoy_server_worker_0_watchdog_miss counter
envoy_server_worker_0_watchdog_miss{} 0
# TYPE envoy_cluster_manager_cluster_added counter
envoy_cluster_manager_cluster_added{} 84
# TYPE envoy_server_main_thread_watchdog_mega_miss counter
envoy_server_main_thread_watchdog_mega_miss{} 0
# TYPE envoy_server_worker_3_watchdog_miss counter
envoy_server_worker_3_watchdog_miss{} 0
envoy_http_admin_downstream_rq{response_code_class="3xx"} 0
# TYPE envoy_cluster_manager_cluster_updated_via_merge counter
envoy_cluster_manager_cluster_updated_via_merge{} 0
# TYPE envoy_cluster_manager_cds_version gauge
envoy_cluster_manager_cds_version{} 5446068728736381235
# TYPE envoy_listener_manager_lds_version gauge
envoy_listener_manager_lds_version{} 5446068728736381235
# TYPE envoy_cluster_circuit_breakers_default_rq_pending_open gauge
envoy_cluster_circuit_breakers_default_rq_pending_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_circuit_breakers_high_cx_pool_open gauge
envoy_cluster_circuit_breakers_high_cx_pool_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_circuit_breakers_high_rq_retry_open gauge
envoy_cluster_circuit_breakers_high_rq_retry_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_membership_healthy gauge
envoy_cluster_membership_healthy{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_circuit_breakers_default_rq_retry_open gauge
envoy_cluster_circuit_breakers_default_rq_retry_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_lb_subsets_active gauge
envoy_cluster_lb_subsets_active{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_circuit_breakers_high_rq_open gauge
envoy_cluster_circuit_breakers_high_rq_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_rx_bytes_buffered gauge
envoy_cluster_upstream_cx_rx_bytes_buffered{cluster_name="xds-grpc"} 332
# TYPE envoy_cluster_circuit_breakers_high_rq_pending_open gauge
envoy_cluster_circuit_breakers_high_rq_pending_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_circuit_breakers_default_cx_pool_open gauge
envoy_cluster_circuit_breakers_default_cx_pool_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_membership_degraded gauge
envoy_cluster_membership_degraded{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_circuit_breakers_high_cx_open gauge
envoy_cluster_circuit_breakers_high_cx_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_active gauge
envoy_cluster_upstream_rq_active{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_circuit_breakers_default_cx_open gauge
envoy_cluster_circuit_breakers_default_cx_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_tx_bytes_buffered gauge
envoy_cluster_upstream_cx_tx_bytes_buffered{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_rq_pending_active gauge
envoy_cluster_upstream_rq_pending_active{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_membership_total gauge
envoy_cluster_membership_total{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_version gauge
envoy_cluster_version{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_max_host_weight gauge
envoy_cluster_max_host_weight{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_membership_excluded gauge
envoy_cluster_membership_excluded{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_circuit_breakers_default_rq_open gauge
envoy_cluster_circuit_breakers_default_rq_open{cluster_name="xds-grpc"} 0
# TYPE envoy_cluster_upstream_cx_active gauge
envoy_cluster_upstream_cx_active{cluster_name="xds-grpc"} 1
# TYPE envoy_listener_manager_total_listeners_draining gauge
envoy_listener_manager_total_listeners_draining{} 0
# TYPE envoy_listener_manager_total_listeners_warming gauge
envoy_listener_manager_total_listeners_warming{} 0
# TYPE envoy_listener_manager_total_listeners_active gauge
envoy_listener_manager_total_listeners_active{} 2
# TYPE envoy_server_memory_allocated gauge
envoy_server_memory_allocated{} 9024744
# TYPE envoy_server_concurrency gauge
envoy_server_concurrency{} 4
# TYPE envoy_server_days_until_first_cert_expiring gauge
envoy_server_days_until_first_cert_expiring{} 88
# TYPE envoy_server_stats_recent_lookups gauge
envoy_server_stats_recent_lookups{} 0
# TYPE envoy_server_total_connections gauge
envoy_server_total_connections{} 0
# TYPE envoy_server_hot_restart_epoch gauge
envoy_server_hot_restart_epoch{} 0
# TYPE envoy_server_version gauge
envoy_server_version{} 6249826
# TYPE envoy_server_state gauge
envoy_server_state{} 0
# TYPE envoy_server_parent_connections gauge
envoy_server_parent_connections{} 0
# TYPE envoy_server_uptime gauge
envoy_server_uptime{} 2046
# TYPE envoy_cluster_manager_active_clusters gauge
envoy_cluster_manager_active_clusters{} 84
# TYPE envoy_server_memory_heap_size gauge
envoy_server_memory_heap_size{} 11534336
# TYPE envoy_cluster_manager_warming_clusters gauge
envoy_cluster_manager_warming_clusters{} 0
# TYPE envoy_server_live gauge
envoy_server_live{} 1
# TYPE envoy_cluster_upstream_rq_time histogram
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="0.5"} 0
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="1"} 0
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="5"} 61
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="10"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="25"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="50"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="100"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="250"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="500"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="1000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="2500"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="5000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="10000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="30000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="60000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="300000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="600000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="1800000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="3600000"} 68
envoy_cluster_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="+Inf"} 68
envoy_cluster_upstream_rq_time_sum{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 144.39999999999997726263245567679
envoy_cluster_upstream_rq_time_count{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 68
# TYPE envoy_cluster_internal_upstream_rq_time histogram
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="0.5"} 0
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="1"} 0
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="5"} 61
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="10"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="25"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="50"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="100"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="250"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="500"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="1000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="2500"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="5000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="10000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="30000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="60000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="300000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="600000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="1800000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="3600000"} 68
envoy_cluster_internal_upstream_rq_time_bucket{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local",le="+Inf"} 68
envoy_cluster_internal_upstream_rq_time_sum{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 144.39999999999997726263245567679
envoy_cluster_internal_upstream_rq_time_count{cluster_name="outbound|15004||istio-telemetry.istio-system.svc.cluster.local"} 68
# TYPE envoy_http_stats_downstream_rq_time histogram
envoy_http_stats_downstream_rq_time_bucket{le="0.5"} 0
envoy_http_stats_downstream_rq_time_bucket{le="1"} 0
envoy_http_stats_downstream_rq_time_bucket{le="5"} 135
envoy_http_stats_downstream_rq_time_bucket{le="10"} 135
envoy_http_stats_downstream_rq_time_bucket{le="25"} 135
envoy_http_stats_downstream_rq_time_bucket{le="50"} 135
envoy_http_stats_downstream_rq_time_bucket{le="100"} 135
envoy_http_stats_downstream_rq_time_bucket{le="250"} 135
envoy_http_stats_downstream_rq_time_bucket{le="500"} 135
envoy_http_stats_downstream_rq_time_bucket{le="1000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="2500"} 135
envoy_http_stats_downstream_rq_time_bucket{le="5000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="10000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="30000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="60000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="300000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="600000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="1800000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="3600000"} 135
envoy_http_stats_downstream_rq_time_bucket{le="+Inf"} 135
envoy_http_stats_downstream_rq_time_sum{} 369.75
envoy_http_stats_downstream_rq_time_count{} 135
# TYPE envoy_cluster_upstream_cx_connect_ms histogram
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="0.5"} 0
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="1"} 0
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="5"} 0
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="10"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="25"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="50"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="100"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="250"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="500"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="1000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="2500"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="5000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="10000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="30000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="60000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="300000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="600000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="1800000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="3600000"} 1
envoy_cluster_upstream_cx_connect_ms_bucket{cluster_name="xds-grpc",le="+Inf"} 1
envoy_cluster_upstream_cx_connect_ms_sum{cluster_name="xds-grpc"} 9.0500000000000007105427357601002
envoy_cluster_upstream_cx_connect_ms_count{cluster_name="xds-grpc"} 1
# TYPE envoy_cluster_upstream_cx_length_ms histogram
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="0.5"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="1"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="5"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="10"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="25"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="50"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="100"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="250"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="500"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="1000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="2500"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="5000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="10000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="30000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="60000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="300000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="600000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="1800000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="3600000"} 0
envoy_cluster_upstream_cx_length_ms_bucket{cluster_name="xds-grpc",le="+Inf"} 0
envoy_cluster_upstream_cx_length_ms_sum{cluster_name="xds-grpc"} 0
envoy_cluster_upstream_cx_length_ms_count{cluster_name="xds-grpc"} 0
# TYPE envoy_http_outbound_0_0_0_0_80_downstream_rq_time histogram
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="0.5"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="1"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="5"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="10"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="25"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="50"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="100"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="250"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="500"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="1000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="2500"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="5000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="10000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="30000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="60000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="300000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="600000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="1800000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="3600000"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_bucket{le="+Inf"} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_sum{} 0
envoy_http_outbound_0_0_0_0_80_downstream_rq_time_count{} 0
# TYPE envoy_cluster_external_upstream_rq_time histogram
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="0.5"} 0
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="1"} 0
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="5"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="10"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="25"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="50"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="100"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="250"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="500"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="1000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="2500"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="5000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="10000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="30000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="60000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="300000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="600000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="1800000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="3600000"} 135
envoy_cluster_external_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="+Inf"} 135
envoy_cluster_external_upstream_rq_time_sum{cluster_name="prometheus_stats"} 327.74999999999994315658113919199
envoy_cluster_external_upstream_rq_time_count{cluster_name="prometheus_stats"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="0.5"} 0
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="1"} 0
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="5"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="10"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="25"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="50"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="100"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="250"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="500"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="1000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="2500"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="5000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="10000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="30000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="60000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="300000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="600000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="1800000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="3600000"} 135
envoy_cluster_upstream_rq_time_bucket{cluster_name="prometheus_stats",le="+Inf"} 135
envoy_cluster_upstream_rq_time_sum{cluster_name="prometheus_stats"} 327.74999999999994315658113919199
envoy_cluster_upstream_rq_time_count{cluster_name="prometheus_stats"} 135
# TYPE envoy_server_initialization_time_ms histogram
envoy_server_initialization_time_ms_bucket{le="0.5"} 0
envoy_server_initialization_time_ms_bucket{le="1"} 0
envoy_server_initialization_time_ms_bucket{le="5"} 0
envoy_server_initialization_time_ms_bucket{le="10"} 0
envoy_server_initialization_time_ms_bucket{le="25"} 0
envoy_server_initialization_time_ms_bucket{le="50"} 0
envoy_server_initialization_time_ms_bucket{le="100"} 0
envoy_server_initialization_time_ms_bucket{le="250"} 0
envoy_server_initialization_time_ms_bucket{le="500"} 0
envoy_server_initialization_time_ms_bucket{le="1000"} 0
envoy_server_initialization_time_ms_bucket{le="2500"} 1
envoy_server_initialization_time_ms_bucket{le="5000"} 1
envoy_server_initialization_time_ms_bucket{le="10000"} 1
envoy_server_initialization_time_ms_bucket{le="30000"} 1
envoy_server_initialization_time_ms_bucket{le="60000"} 1
envoy_server_initialization_time_ms_bucket{le="300000"} 1
envoy_server_initialization_time_ms_bucket{le="600000"} 1
envoy_server_initialization_time_ms_bucket{le="1800000"} 1
envoy_server_initialization_time_ms_bucket{le="3600000"} 1
envoy_server_initialization_time_ms_bucket{le="+Inf"} 1
envoy_server_initialization_time_ms_sum{} 1450
envoy_server_initialization_time_ms_count{} 1
# TYPE envoy_http_admin_downstream_rq_time histogram
envoy_http_admin_downstream_rq_time_bucket{le="0.5"} 1056
envoy_http_admin_downstream_rq_time_bucket{le="1"} 1056
envoy_http_admin_downstream_rq_time_bucket{le="5"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="10"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="25"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="50"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="100"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="250"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="500"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="1000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="2500"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="5000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="10000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="30000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="60000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="300000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="600000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="1800000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="3600000"} 1194
envoy_http_admin_downstream_rq_time_bucket{le="+Inf"} 1194
envoy_http_admin_downstream_rq_time_sum{} 287.89999999999997726263245567679
envoy_http_admin_downstream_rq_time_count{} 1194
```

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.
Configured via Istio's XDS.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

### PR DESCRIPTION
**Pull request by ggreenway**
Signed-off-by: Greg Greenway <ggreenway@apple.com>

Description: The prometheus exposition format requires all metrics of the same name (without tags) be grouped contiguously in the output. Additionally, it specifies that it is preferred for the stats to be output in the same order every time they are produced. Fix Envoy to comply with both of these constraints by taking an extra pass to collect all the stats so that they can be sorted before the final output is generated.

Risk Level: Low
Testing: New unit test
Docs Changes: Not needed
Release Notes: Added
Fixes #10073

### CODE REVIEW

**Comment by ggreenway** [comment]
Question for anyone with knowledge of the exposition format (https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#grouping-and-sorting):

The format says `All lines for a given metric must be provided as one single group, with the optional HELP and TYPE lines first (in no particular order).`. 

How does this apply to histograms? Is a single histogram, which is composed of several `_bucket` lines plus the `_sum` and `_count` lines, considered a single metric in the sorting directive? For example, which of the following is correct?

```
hist_bucket{cluster="a", le="1"} 1
hist_bucket{cluster="a", le="+Inf"} 1
hist_sum{cluster="a"} 1
hist_count{cluster="a"} 1
hist_bucket{cluster="b", le="1"} 1
hist_bucket{cluster="b", le="+Inf"} 1
hist_sum{cluster="b"} 1
hist_count{cluster="b"} 1
```

Or

```
hist_bucket{cluster="a", le="1"} 1
hist_bucket{cluster="a", le="+Inf"} 1
hist_bucket{cluster="b", le="1"} 1
hist_bucket{cluster="b", le="+Inf"} 1
hist_sum{cluster="a"} 1
hist_sum{cluster="b"} 1
hist_count{cluster="a"} 1
hist_count{cluster="b"} 1
```

File: source/server/http/stats_handler.cc [hunk 1]
```diff
@@ -190,52 +190,65 @@ uint64_t PrometheusStatsFormatter::statsAsPrometheus(
...
-
-    const Stats::HistogramStatistics& stats = histogram->cumulativeStatistics();
+    return groups.size();
+  };
+
+  // Returns a pair of metric_name and prometheus output line for a counter or a gauge.
+  auto generate_counter_and_gauge_output =
+      [](const auto& metric) -> std::pair<std::string, std::string> {
+    const std::string tags = formattedTags(metric.tags());
+    const std::string metric_name = metricName(metric.tagExtractedName());
```
Comment (jmarantz) [inline source/server/http/stats_handler.cc:233]: I'm worried about the explosion of string-storage during the sort. Can we populate a vector of metrics, and sort them by Metric::tagExtractedStatName()? StatNames are sortable.

Then we could stream out the formatted value?

I realize that at the moment the admin output infrastructure buffers everything, so I'm not under the delusion we can in this PR have the prometheus handler consume constant space. But I think we could make it consume half the space it consumes with this approach, and that's probably a significant memory bump. And I think it wouldn't be hugely difficult to update the admin output infrastructure to stream rather than fully buffer.

There was a talk at KubeCon by Splunk about stats cardinality blowing through hundreds of gigs of memory in Prometheus [(slides)](https://static.sched.com/hosted_files/kccncna19/2c/great_cardinality_disasters_of_our_time.pdf) and the source of the stats explosion was Istio.

Comment (jmarantz) [reply source/server/http/stats_handler.cc:233]: also to sort by StatName you can use:
https://github.com/envoyproxy/envoy/blob/62777e87edc9f16af5c7920bb86f198585789a3d/source/common/stats/symbol_table_impl.h#L697

Comment (ggreenway) [reply source/server/http/stats_handler.cc:233]: I worried about this too. Let me take a pass at this and see how it comes out.

**Comment by ggreenway** [comment]
@jmarantz I think I've fixed the memory usage. PTAL.

File: source/server/http/stats_handler.cc [hunk 2]
```diff
@@ -190,52 +190,99 @@ uint64_t PrometheusStatsFormatter::statsAsPrometheus(
...
-    }
+    // There should only be one symbol table for all of the stats in the admin
+    // interface. If this assumption changes, the name comparisons in this function
+    // will have to change to compare to convert all StatNames to strings before
+    // comparison.
+    const Stats::SymbolTable& global_symbol_table = metrics.front()->constSymbolTable();
+
+    // Sorted collection of metrics sorted by their tagExtractedName, to satisfy the requirements
+    // of the exposition format.
+    std::map<Stats::StatName, MetricTypeSortedCollection, Stats::StatNameLessThan> groups(
```
Comment (jmarantz) [inline source/server/http/stats_handler.cc:242]: this looks much better, thank you! WDYT of using a std::vector and calling std::sort -- my cargo-culted opinion is that that will be faster and more memory-efficient (by a constant factor) than using std::map as a sorter.

Ditto for the std::set in MetricTypeSortedCollection; once you have the vector populated you can just sort it.

File: source/server/http/stats_handler.cc [hunk 3]
```diff
@@ -190,52 +190,99 @@ uint64_t PrometheusStatsFormatter::statsAsPrometheus(
...
+  /**
+   * Processes a metric type (counter, gauge, histogram) by generating all output lines, sorting
+   * them by tag-extracted metric name, and then outputting them in the correct sorted order into
+   * response.
+   *
+   * @param metrics A vector of pointers to a metric type.
+   * @param generate_output A std::function<std::string(const MetricType& metric, const std::string&
+   *        prefixedTagExtractedName)> which returns the output text for this metric.
+   */
+  auto process_type = [&](const auto& metrics, const auto& generate_output,
```
Comment (jmarantz) [inline source/server/http/stats_handler.cc:213]: suggest capturing explicitly what you need here, rather than capturing everything.

File: source/server/http/stats_handler.cc [hunk 4]
```diff
@@ -244,18 +291,25 @@ uint64_t PrometheusStatsFormatter::statsAsPrometheus(
...
 
-  return metric_type_tracker.size();
-}
+    return output;
+  };
+
+  uint64_t metric_name_count = 0;
+  metric_name_count += process_type(counters, generate_counter_and_gauge_output, "counter");
+  metric_name_count += process_type(gauges, generate_counter_and_gauge_output, "gauge");
+  metric_name_count += process_type(histograms, generate_histogram_output, "histogram");
```
Comment (jmarantz) [inline source/server/http/stats_handler.cc:309]: any thoughts on what to do for TextReadouts, why you are in here? This is a new stat type recently added by @efimki -- do they make sense in Prometheus?

Comment (efimki) [reply source/server/http/stats_handler.cc:309]: If TextReadouts make sense in Prometeus, then I'll be happy to add them, but would need a pointers on how to properly sanitize, escape and quote the text string.

File: source/server/http/stats_handler.cc (hunk 2 above)
Comment (ggreenway) [reply source/server/http/stats_handler.cc:242]: That would be fine for the inner std::set. For the outer std::map, we're doing a lot of lookups by key. I could use a flat_hash_map and then order it at the end, but that sounds painful; I don't think there's a better way to do it than to first make an unordered-copy into a vector and then sort the vector.

File: source/server/http/stats_handler.cc (hunk 4 above)
Comment (ggreenway) [reply source/server/http/stats_handler.cc:309]: I don't want to expand the scope of this PR; let's investigate addint text readouts later.

File: source/server/http/stats_handler.cc (hunk 2 above)
Comment (jmarantz) [reply source/server/http/stats_handler.cc:242]: That makes sense, sgtm.

File: include/envoy/stats/refcount_ptr.h [hunk 5]
```diff
@@ -25,6 +25,8 @@ namespace Stats {
 // API in years.
 template <class T> class RefcountPtr {
 public:
+  using element_type = T;
```
Comment (jmarantz) [inline include/envoy/stats/refcount_ptr.h:28]: doc this? And also consider spelling it ElementType per Envoy style?

File: source/server/http/stats_handler.cc [hunk 6]
```diff
@@ -190,52 +190,110 @@ uint64_t PrometheusStatsFormatter::statsAsPrometheus(
...
+  /**
+   * Processes a metric type (counter, gauge, histogram) by generating all output lines, sorting
+   * them by tag-extracted metric name, and then outputting them in the correct sorted order into
+   * response.
+   *
+   * @param metrics A vector of Stats::RefcountPtr to a metric type.
+   * @param generate_output A std::function<std::string(const MetricType& metric, const std::string&
+   *        prefixedTagExtractedName)> which returns the output text for this metric.
+   */
+  auto process_type = [&response, &regex, used_only](const auto& metrics,
```
Comment (jmarantz) [inline source/server/http/stats_handler.cc:213]: I was wondering whether you could use templates in some way to reduce the user of `auto` -- the `auto` for the generated function is OK but it'd be nicer to be explicit about what type metrics and generate_output were.

See https://google.github.io/styleguide/cppguide.html#Type_deduction for discussion.

I think my concrete suggestion is to break up most of this code into a private helper method `processType` which is templatized. Then you could have the body of statsAsPrometheus() simply be:
```
  uint64_t metric_name_count = 0;
  metric_name_count += rocessType<Stats::Counter>(counters, generate_counter_and_gauge_output, "counter");
  metric_name_count += processType<Stats::Gauge>(gauges, generate_counter_and_gauge_output, "gauge");
  metric_name_count += processType<Stats::Histogram>(histograms, generate_histogram_output, "histogram");
```

I think that might be clearer than using the lambda with the auto...WDYT?

That would also remove the need for the `element_type` in the refcount, at least for this PR.

File: include/envoy/stats/refcount_ptr.h (hunk 5 above)
Comment (ggreenway) [reply include/envoy/stats/refcount_ptr.h:28]: This definition is taken from std::shared_ptr. I'll doc it.

File: source/server/http/stats_handler.cc (hunk 6 above)
Comment (ggreenway) [reply source/server/http/stats_handler.cc:213]: Both `metrics` and `generate_output` are templatized types because of how `Counter`, `Gauge`, and `Histogram` are defined. There isn't a common/inherited defintion for the functions that get the data. I had tried to make these non-auto, and it isn't possible.

I can make the helpers into template methods instead of a lambda, and I agree that may make this a little easier to follow. Some of the types will become more concrete.

Comment (jmarantz) [reply source/server/http/stats_handler.cc:213]: I think once you make the helper into an explicit template method you'll be able to drop the `auto`, though I could be wrong.

Comment (ggreenway) [reply source/server/http/stats_handler.cc]: Yeah, it came out better than I expected, although I had to explicitly specify template parameters in some cases that were unexpected to me. But I think it is more readable.

**Comment by ggreenway** [comment]
Haven't seen this error before: 

```
Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 6117 total actions
Merging coverage data...
error: bazel-out/k8-fastbuild/testlogs/test/coverage/coverage_tests/shard_20_of_50/coverage.dat: Malformed instrumentation profile data
```

/retest
