### PR TITLE
fix oauth filter sds update

### LINKED ISSUE #16126: envoy.filters.http.oauth2 stops working after upgrade from 1.17.2 to 1.18.2
Hello,

i have Envoy Proxy PoC with Keycloak 12.4 and Okta. All works with Envoy 1.17-latest.
After upgrade to 1.18-latest (1.18.2) neither Okta nor Keycloak PoC work.

The error thrown is: "client credentials are invalid"
Client credentials are 100% valid and did not change after upgrade.
Downgrade to 1.17-latest immediately solves problem.

Example config for Okta:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10444
static_resources:
  listeners:
  - name: listener_proxy
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/developer"
                route:
                  prefix_rewrite: "/"
                  cluster: envoy-okta-back-developer
                response_headers_to_add:
                  - header:
                      key: cache-control
                      value: "no-cache, no-store"
              - match:
                  prefix: "/"
                route:
                  cluster: envoy-okta-back-employee
                response_headers_to_add:
                  - header:
                      key: cache-control
                      value: "no-cache, no-store"
          http_filters:
          - name: envoy.filters.http.oauth2
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3alpha.OAuth2
              config:
                token_endpoint:
                  cluster: okta-cluster-https
                  uri: https://testpoc.okta.com/oauth2/clientxxx/v1/token
                  timeout: 5s
                authorization_endpoint: https://testpoc.okta.com/oauth2/clientxxx/v1/authorize
                redirect_uri: "https://%REQ(:authority)%/callback"
                redirect_path_matcher:
                  path:
                    exact: /callback
                signout_path:
                  path:
                    exact: /signout
                forward_bearer_token: true
                credentials:
                  client_id: "blablabla"
                  token_secret:
                    name: token
                    sds_config:
                      path: "/etc/envoy/token-secret.yaml"
                  hmac_secret:
                    name: hmac
                    sds_config:
                      path: "/etc/envoy/hmac.yaml"
          - name: envoy.filters.http.router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: /etc/envoy/certs/intranet_sitesitesite_com.crt
              private_key:
                filename: /etc/envoy/certs/intranet_sitesitesite_com.key
  clusters:
  - name: okta-cluster-https
    connect_timeout: 2.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: okta-cluster-https
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: testpoc.okta.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: testpoc.okta.com
        common_tls_context:
          validation_context:
            match_subject_alt_names:
              - exact: "*.okta.com"
            trusted_ca:
              filename: /etc/envoy/certs/ca-bundle.crt
  - name: envoy-okta-back-employee
    connect_timeout: 2.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: envoy-okta-back-employee
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy-okta-back-employee
                port_value: 33233
  - name: envoy-okta-back-developer
    connect_timeout: 2.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: envoy-okta-back-developer
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy-okta-back-developer
                port_value: 22222
```

Example config for Keycloak:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10001
static_resources:
  listeners:
  - name: listener_proxy
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/developer"
                route:
                  prefix_rewrite: "/"
                  cluster: envoy-keycloak-back-developer
                response_headers_to_add:
                  - header:
                      key: cache-control
                      value: "no-cache, no-store"
              - match:
                  prefix: "/"
                route:
                  cluster: envoy-keycloak-back-employee
                response_headers_to_add:
                  - header:
                      key: cache-control
                      value: "no-cache, no-store"
          http_filters:
          - name: envoy.filters.http.oauth2
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3alpha.OAuth2
              config:
                token_endpoint:
                  cluster: keycloak
                  uri: http://keycloak.sitesitesite.com:8080/auth/realms/api/protocol/openid-connect/token
                  timeout: 5s
                authorization_endpoint: http://keycloak.sitesitesite.com:8080/auth/realms/api/protocol/openid-connect/auth
                redirect_uri: "https://%REQ(:authority)%/callback"
                redirect_path_matcher:
                  path:
                    exact: /callback
                signout_path:
                  path:
                    exact: /signout
                forward_bearer_token: true
                credentials:
                  client_id: "api"
                  token_secret:
                    name: token
                    sds_config:
                      path: "/etc/envoy/token-secret.yaml"
                  hmac_secret:
                    name: hmac
                    sds_config:
                      path: "/etc/envoy/hmac.yaml"
          - name: envoy.filters.http.router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: /etc/envoy/certs/example-com.crt
              private_key:
                filename: /etc/envoy/certs/example-com.key
  clusters:
  - name: keycloak
    connect_timeout: 1.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: keycloak
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: keycloak
                port_value: 8080
  - name: envoy-keycloak-back-employee
    connect_timeout: 1.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: envoy-keycloak-back-employee
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy-keycloak-back-employee
                port_value: 11111
  - name: envoy-keycloak-back-developer
    connect_timeout: 1.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: envoy-keycloak-back-developer
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy-keycloak-back-developer
                port_value: 11121
```

Envoy proxy log in case of Okta:
```
[2021-04-22 17:33:07.686][14][debug][http] [source/common/http/filter_manager.cc:779] [C15][S17665552354465055548] request end stream
[2021-04-22 17:33:07.686][14][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:43] Dispatching OAuth request for access token.
[2021-04-22 17:33:07.686][14][debug][router] [source/common/router/router.cc:445] [C0][S17369098839487975571] cluster 'okta-cluster-https' match for URL '/oauth2/clientxxx/v1/token'
[2021-04-22 17:33:07.687][14][debug][router] [source/common/router/router.cc:631] [C0][S17369098839487975571] router decoding headers:
':path', '/oauth2/clientxxx/v1/token'
':authority', 'testpoc.okta.com'
':method', 'POST'
':scheme', 'http'
'content-type', 'application/x-www-form-urlencoded'
'accept', 'application/json'
'x-envoy-internal', 'true'
'x-forwarded-for', '172.19.0.6'
'x-envoy-expected-rq-timeout-ms', '5000'

[2021-04-22 17:33:07.687][14][debug][pool] [source/common/http/conn_pool_base.cc:74] queueing stream due to no available connections
[2021-04-22 17:33:07.687][14][debug][pool] [source/common/conn_pool/conn_pool_base.cc:241] trying to create new connection
[2021-04-22 17:33:07.687][14][debug][pool] [source/common/conn_pool/conn_pool_base.cc:143] creating a new connection
[2021-04-22 17:33:07.687][14][debug][client] [source/common/http/codec_client.cc:43] [C27] connecting
[2021-04-22 17:33:07.687][14][debug][connection] [source/common/network/connection_impl.cc:860] [C27] connecting to 44.234.52.11:443
[2021-04-22 17:33:07.687][14][debug][connection] [source/common/network/connection_impl.cc:876] [C27] connection in progress
[2021-04-22 17:33:07.687][14][debug][http2] [source/common/http/http2/codec_impl.cc:1222] [C27] updating connection-level initial window size to 268435456
[2021-04-22 17:33:07.689][14][debug][connection] [source/common/network/connection_impl.cc:665] [C27] connected
[2021-04-22 17:33:07.693][14][debug][client] [source/common/http/codec_client.cc:82] [C27] connected
[2021-04-22 17:33:07.693][14][debug][pool] [source/common/conn_pool/conn_pool_base.cc:275] [C27] attaching to next stream
[2021-04-22 17:33:07.693][14][debug][pool] [source/common/conn_pool/conn_pool_base.cc:171] [C27] creating stream
[2021-04-22 17:33:07.693][14][debug][router] [source/common/router/upstream_request.cc:371] [C0][S17369098839487975571] pool ready
[2021-04-22 17:33:07.725][14][debug][router] [source/common/router/router.cc:1244] [C0][S17369098839487975571] upstream headers complete: end_stream=false
[2021-04-22 17:33:07.726][14][debug][http] [source/common/http/async_client_impl.cc:104] async http request response headers (end_stream=false):
':status', '401'
'date', 'Thu, 22 Apr 2021 17:33:07 GMT'
'content-type', 'application/json'
'server', 'nginx'
'public-key-pins-report-only', 'pin-sha256="r5EfzZxQVvQpKo3AgYRaT7X2bDO/kj3ACwmxfdT2zt8="; pin-sha256="MaqlcUgk2mvY/RFSGeSwBRkI+rZ6/dxe/DuQfBT/vnQ="; pin-sha256="72G5IEvDEWn+EThf3qjR7/bQSWaS2ZSLqolhnO6iyJI="; pin-sha256="rrV6CLCCvqnk89gWibYT0JO6fNQ8cCit7GGoiVTjCOg="; max-age=60; report-uri="https://okta.report-uri.com/r/default/hpkp/reportOnly"'
'x-okta-request-id', 'YIGzU@Y06dIV-mUFsj0MXAAABlc'
'x-xss-protection', '0'
'p3p', 'CP="HONK"'
'x-rate-limit-limit', '300'
'x-rate-limit-remaining', '298'
'x-rate-limit-reset', '1619112847'
'cache-control', 'no-cache, no-store'
'pragma', 'no-cache'
'expires', '0'
'content-security-policy', 'default-src 'self' *.oktacdn.com testpoc.okta.com; connect-src 'self' *.oktacdn.com *.mixpanel.com *.mapbox.com app.pendo.io data.pendo.io pendo-static-5634101834153984.storage.googleapis.com testpoc.okta.com testpoc-admin.okta.com testpoc.kerberos.okta.com https://oinmanager.okta.com data:; script-src 'unsafe-inline' 'unsafe-eval' 'self' *.oktacdn.com; style-src 'unsafe-inline' 'self' *.oktacdn.com app.pendo.io cdn.pendo.io pendo-static-5634101834153984.storage.googleapis.com; frame-src 'self' login.okta.com testpoc.okta.com testpoc-admin.okta.com; img-src 'self' *.oktacdn.com testpoc.okta.com *.tiles.mapbox.com *.mapbox.com app.pendo.io data.pendo.io cdn.pendo.io pendo-static-5634101834153984.storage.googleapis.com data: blob:; font-src data: 'self' *.oktacdn.com fonts.gstatic.com'
'expect-ct', 'report-uri="https://oktaexpectct.report-uri.com/r/t/ct/reportOnly", max-age=0'
'x-content-type-options', 'nosniff'
'strict-transport-security', 'max-age=315360000; includeSubDomains'
'set-cookie', 'sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/'
'set-cookie', 'JSESSIONID=CE85E4B0F797FCCFA07A485DBF63A0E4; Path=/; Secure; HttpOnly'
'x-envoy-upstream-service-time', '38'

[2021-04-22 17:33:07.726][14][debug][client] [source/common/http/codec_client.cc:124] [C27] response complete
[2021-04-22 17:33:07.726][14][debug][pool] [source/common/conn_pool/conn_pool_base.cc:200] [C27] destroying stream: 0 remaining
[2021-04-22 17:33:07.726][14][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:72] Oauth response code: 401
[2021-04-22 17:33:07.726][14][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:73] Oauth response body: {"error":"invalid_client","error_description":"Client authentication failed. Either the client or the client credentials are invalid."}
[2021-04-22 17:33:07.726][14][debug][http] [source/common/http/filter_manager.cc:883] [C15][S17665552354465055548] Sending local reply with details
[2021-04-22 17:33:07.726][14][debug][http] [source/common/http/conn_manager_impl.cc:1455] [C15][S17665552354465055548] encoding headers via codec (end_stream=false):
':status', '401'
'cache-control', 'no-cache, no-store'
'content-length', '18'
'content-type', 'text/plain'
'date', 'Thu, 22 Apr 2021 17:33:07 GMT'
'server', 'envoy'

[2021-04-22 17:33:07.726][14][debug][http2] [source/common/http/http2/codec_impl.cc:997] [C27] stream closed: 0
```
Search for error message:
```
"Client authentication failed. Either the client or the client credentials are invalid."
```

Envoy proxy log in case of Keycloak:
```
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:43] Dispatching OAuth request for access token.
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][router] [source/common/router/router.cc:445] [C0][S3744323587196550320] cluster 'keycloak' match for URL '/auth/realms/api/protocol/openid-connect/token'
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][router] [source/common/router/router.cc:631] [C0][S3744323587196550320] router decoding headers:
envoy-keycloak-front              | ':path', '/auth/realms/api/protocol/openid-connect/token'
envoy-keycloak-front              | ':authority', 'keycloak.sitesitesite.com:8080'
envoy-keycloak-front              | ':method', 'POST'
envoy-keycloak-front              | ':scheme', 'http'
envoy-keycloak-front              | 'content-type', 'application/x-www-form-urlencoded'
envoy-keycloak-front              | 'accept', 'application/json'
envoy-keycloak-front              | 'x-envoy-internal', 'true'
envoy-keycloak-front              | 'x-forwarded-for', '172.18.0.6'
envoy-keycloak-front              | 'x-envoy-expected-rq-timeout-ms', '5000'
envoy-keycloak-front              |
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][pool] [source/common/http/conn_pool_base.cc:74] queueing stream due to no available connections
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][pool] [source/common/conn_pool/conn_pool_base.cc:241] trying to create new connection
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][pool] [source/common/conn_pool/conn_pool_base.cc:143] creating a new connection
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][client] [source/common/http/codec_client.cc:43] [C4] connecting
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][connection] [source/common/network/connection_impl.cc:860] [C4] connecting to 172.18.0.3:8080
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][connection] [source/common/network/connection_impl.cc:876] [C4] connection in progress
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][connection] [source/common/network/connection_impl.cc:665] [C4] connected
envoy-keycloak-front              | [2021-04-22 17:26:03.574][24][debug][client] [source/common/http/codec_client.cc:82] [C4] connected
envoy-keycloak-front              | [2021-04-22 17:26:03.575][24][debug][pool] [source/common/conn_pool/conn_pool_base.cc:275] [C4] attaching to next stream
envoy-keycloak-front              | [2021-04-22 17:26:03.575][24][debug][pool] [source/common/conn_pool/conn_pool_base.cc:171] [C4] creating stream
envoy-keycloak-front              | [2021-04-22 17:26:03.575][24][debug][router] [source/common/router/upstream_request.cc:371] [C0][S3744323587196550320] pool ready
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][router] [source/common/router/router.cc:1244] [C0][S3744323587196550320] upstream headers complete: end_stream=false
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][http] [source/common/http/async_client_impl.cc:104] async http request response headers (end_stream=false):
envoy-keycloak-front              | ':status', '401'
envoy-keycloak-front              | 'cache-control', 'no-store'
envoy-keycloak-front              | 'x-xss-protection', '1; mode=block'
envoy-keycloak-front              | 'pragma', 'no-cache'
envoy-keycloak-front              | 'x-frame-options', 'SAMEORIGIN'
envoy-keycloak-front              | 'referrer-policy', 'no-referrer'
envoy-keycloak-front              | 'date', 'Thu, 22 Apr 2021 17:26:03 GMT'
envoy-keycloak-front              | 'connection', 'keep-alive'
envoy-keycloak-front              | 'strict-transport-security', 'max-age=31536000; includeSubDomains'
envoy-keycloak-front              | 'x-content-type-options', 'nosniff'
envoy-keycloak-front              | 'content-type', 'application/json'
envoy-keycloak-front              | 'content-length', '75'
envoy-keycloak-front              | 'x-envoy-upstream-service-time', '42'
envoy-keycloak-front              |
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][client] [source/common/http/codec_client.cc:124] [C4] response complete
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:72] Oauth response code: 401
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:73] Oauth response body: {"error":"unauthorized_client","error_description":"Invalid client secret"}
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][http] [source/common/http/filter_manager.cc:883] [C3][S10340968160964716544] Sending local reply with details
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][http] [source/common/http/conn_manager_impl.cc:1455] [C3][S10340968160964716544] encoding headers via codec (end_stream=false):
envoy-keycloak-front              | ':status', '401'
envoy-keycloak-front              | 'cache-control', 'no-cache, no-store'
envoy-keycloak-front              | 'content-length', '18'
envoy-keycloak-front              | 'content-type', 'text/plain'
envoy-keycloak-front              | 'date', 'Thu, 22 Apr 2021 17:26:03 GMT'
envoy-keycloak-front              | 'server', 'envoy'
envoy-keycloak-front              |
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][pool] [source/common/http/http1/conn_pool.cc:53] [C4] response complete
envoy-keycloak-front              | [2021-04-22 17:26:03.617][24][debug][pool] [source/common/conn_pool/conn_pool_base.cc:200] [C4] destroying stream: 0 remaining
envoy-keycloak-front              | [2021-04-22 17:26:05.946][1][debug][main] [source/server/server.cc:209] flushing stats
```

Search for error message:
```
"{"error":"unauthorized_client","error_description":"Invalid client secret"}"
```

In both cases client secret is defined in following way:
```
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: token
    generic_secret:
      secret:
        # Fill in the client secret your OAuth2 provider assigned to you.
        inline_string: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
```

Any advice how to fix it?

Thank you!

### PR DESCRIPTION
**Pull request by Inode1**
Additional Description:
The client_secret field was not updated on configuration changes.

Risk Level: Low
Testing: n/a
Docs Changes: n/a
Release Notes: inline
Fixes #16126

### CODE REVIEW

File: source/extensions/filters/http/oauth2/filter.h [hunk 1]
```diff
@@ -51,23 +51,23 @@ class SDSSecretReader : public SecretReader {
...
   }
 
   const std::string& clientSecret() const override { return client_secret_; }
 
   const std::string& tokenSecret() const override { return token_secret_; }
 
 private:
-  void readAndWatchSecret(std::string& value,
-                          Secret::GenericSecretConfigProvider& secret_provider) {
+  void readAndWatchSecret(std::string& value, Secret::GenericSecretConfigProvider& secret_provider,
```
Comment (dmitri-d) [inline source/extensions/filters/http/oauth2/filter.h:63]: Could you return the update_callback from the method instead of using a parameter? I think it would be more readable...

**Comment by dmitri-d** [comment]
Could you provide a brief explanation of how this fixes the problem in  https://github.com/envoyproxy/envoy/issues/16126? Also, could you add tests?

File: source/extensions/filters/http/oauth2/filter.h (hunk 1 above)
Comment (Inode1) [reply source/extensions/filters/http/oauth2/filter.h:63]: Good point.

**Comment by Inode1** [comment]
Yup. This method **secret_provider->addUpdateCallback** calls [this](https://github.com/envoyproxy/envoy/blob/63307f55889d35ce98a34afe7a9aaaf0277304d3/source/common/common/callback_impl.h#L25) at the end. And if we don't save results in unique_ptr it will be destroyed and deleted from the callbacks list according to [this](https://github.com/envoyproxy/envoy/blob/63307f55889d35ce98a34afe7a9aaaf0277304d3/source/common/common/callback_impl.h#L52). We need to create two objects [here](https://github.com/envoyproxy/envoy/blob/63307f55889d35ce98a34afe7a9aaaf0277304d3/source/extensions/filters/http/oauth2/filter.h#L70). If we don't do it the **update_callback_** will be rewrited and callback will be deleted.

**Comment by dmitri-d** [comment]
Nice catch, @Inode1. Could you add a test?

**Comment by Inode1** [comment]
Here you are, check this out.

File: test/extensions/filters/http/oauth2/filter_test.cc [hunk 2]
```diff
@@ -155,6 +157,69 @@ class OAuth2Test : public testing::Test {
...
+generic_secret:
+  secret:
+    inline_string: "token_test"
+)EOF";
+  TestUtility::loadFromYaml(TestEnvironment::substitute(yaml_token), typed_secret);
+  const auto decoded_resources_token = TestUtility::decodeResources({typed_secret});
+
+  token_callback->onConfigUpdate(decoded_resources_token.refvec_, "");
+  EXPECT_EQ(secret_reader.clientSecret(), "client_test");
+  EXPECT_EQ(secret_reader.tokenSecret(), "token_test");
```
Comment (dmitri-d) [inline test/extensions/filters/http/oauth2/filter_test.cc:221]: Could you add another check where token stays the same, but the client secret is updated again? To make sure that an update to client secret doesn't overwrite the token.

**Comment by dmitri-d** [comment]
Lgtm, just a small ask in the test.

File: test/extensions/filters/http/oauth2/filter_test.cc [hunk 3]
```diff
@@ -155,6 +157,82 @@ class OAuth2Test : public testing::Test {
   Event::SimulatedTimeSystem test_time_;
 };
 
+// Verifies that the OAuth SDSSecretReader correctly updates dynamic generic secret
+TEST_F(OAuth2Test, SdsDynamicGenericSecret) {
+  NiceMock<Server::MockConfigTracker> config_tracker;
+  std::unique_ptr<Secret::SecretManager> secret_manager(
+      new Secret::SecretManagerImpl(config_tracker));
```
Comment (snowp) [inline test/extensions/filters/http/oauth2/filter_test.cc:164]: You can probably get by here by allocating this on the stack?

File: test/extensions/filters/http/oauth2/filter_test.cc [hunk 4]
```diff
@@ -155,6 +157,82 @@ class OAuth2Test : public testing::Test {
...
+  envoy::config::core::v3::ConfigSource config_source;
+
+  NiceMock<Server::Configuration::MockTransportSocketFactoryContext> secret_context;
+  NiceMock<LocalInfo::MockLocalInfo> local_info;
+  Api::ApiPtr api = Api::createApiForTest();
+  Stats::IsolatedStoreImpl stats;
```
Comment (snowp) [inline test/extensions/filters/http/oauth2/filter_test.cc:170]: At least this one can use the store_ defined on the fixture class instead of redefining one here

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks! Could you include a bit more information in the PR description that describes that the bug is and how this fixes it?

Also, do you think it would be possible to write an integration test for this? Would be good to have a test that verifies this end to end.

File: test/extensions/filters/http/oauth2/filter_test.cc [hunk 5]
```diff
@@ -155,6 +157,82 @@ class OAuth2Test : public testing::Test {
   Event::SimulatedTimeSystem test_time_;
 };
 
+// Verifies that the OAuth SDSSecretReader correctly updates dynamic generic secret
```
[the remark this answers is not in the document]
Comment (Inode1) [reply test/extensions/filters/http/oauth2/filter_test.cc]: Done

File: test/extensions/filters/http/oauth2/filter_test.cc [hunk 6]
```diff
@@ -155,6 +157,82 @@ class OAuth2Test : public testing::Test {
...
+
+  const std::string yaml_client = R"EOF(
+name: client
+generic_secret:
+  secret:
+    inline_string: "client_test"
+)EOF";
+
+  envoy::extensions::transport_sockets::tls::v3::Secret typed_secret;
+  TestUtility::loadFromYaml(TestEnvironment::substitute(yaml_client), typed_secret);
```
[the remark this answers is not in the document]
Comment (Inode1) [reply test/extensions/filters/http/oauth2/filter_test.cc]: Done

File: test/extensions/filters/http/oauth2/filter_test.cc (hunk 3 above)
Comment (Inode1) [reply test/extensions/filters/http/oauth2/filter_test.cc]: Done

File: test/extensions/filters/http/oauth2/filter_test.cc (hunk 4 above)
Comment (Inode1) [reply test/extensions/filters/http/oauth2/filter_test.cc:168]: I think it will be more readable if we leave it in the function scope to save the context.

**Comment by Inode1** [comment]
I don't know how to update secrets in integration tests, so if you give me a hint, I think I can do it.

**Comment by snowp** [comment]
Maybe try looking at sds_static_integration_test or sds_dynamic_integration_test for how that sets up SDS triggers?

**Comment by Inode1** [comment]
@snowp could you review the test and could you check [this](https://github.com/envoyproxy/envoy/blob/85a8570cd0530402de21c48c6688dddb187775d5/source/extensions/filters/http/oauth2/filter.h#L71) and [this](https://github.com/envoyproxy/envoy/blob/85a8570cd0530402de21c48c6688dddb187775d5/source/extensions/filters/http/oauth2/filter.h#L125) I think it's not thread safe to use it this way.

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks for getting an integration test together!

Re your question on thread safety it's hard to say without deeper inspection. What specifically makes you think that it's not thread safe? At a quick look it does seem problematic that we're just updating the secrets from the main thread and then presumably read from the filters? We might want to make use of a TLS slot here to avoid that, but if we can get an integration test reproducing the issue first that would be awesome.

File: source/common/http/utility.h [hunk 7]
```diff
@@ -240,6 +240,14 @@ absl::string_view findQueryStringStart(const HeaderString& path);
  **/
 std::string parseCookieValue(const HeaderMap& headers, const std::string& key);
 
+/**
+ * Parse a particular value out of a set-cookie
+ * @param headers supplies the headers to get the set-cookie from.
+ * @param key the key for the particular set-cookie value to return
+ * @return std::string the parsed set-cookie value, or "" if none exists
+ **/
+std::string parseSetCookieValue(const HeaderMap& headers, const std::string& key);
```
Comment (snowp) [inline source/common/http/utility.h:249]: Mind adding a test for this function? Ideally we have coverage for this outside of extensions. Thanks!

File: test/extensions/filters/http/oauth2/oauth_integration_test.cc [hunk 8]
```diff
@@ -122,6 +125,73 @@ name: oauth
...
+
+    validate_headers.addReferenceKey(Http::Headers::get().Cookie, absl::StrCat("OauthHMAC=", hmac));
+    validate_headers.addReferenceKey(Http::Headers::get().Cookie,
+                                     absl::StrCat("OauthExpires=", expires));
+    validate_headers.addReferenceKey(Http::Headers::get().Cookie,
+                                     absl::StrCat("BearerToken=", token));
+
+    OAuth2CookieValidator validator{api_->timeSource()};
+    validator.setParams(validate_headers, std::string(hmac_secret));
+    ASSERT_TRUE(validator.isValid());
```
Comment (snowp) [inline test/extensions/filters/http/oauth2/oauth_integration_test.cc:145]: if you return `validator.isValid()` here instead you can do an `EXPECT_TRUE` at call site and provide better error messaging

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks this looks great, just a few more comments and then I think we're good to go

File: source/common/http/utility.h (hunk 7 above)
Comment (Inode1) [reply source/common/http/utility.h:249]: I can copy-past some tests from utility_test.cpp with parseCookieValue check and trasnform them for parseCookieValue. Will it be okay?

**Review by snowp — APPROVED** [review]
Thanks!
