### PR TITLE
golang extension: fix loaded_ may be overwritten unexpectedly.

### LINKED ISSUE #25757: golang filter: loaded_ may be overwrite unexpectly
Only the last one take affects.
https://github.com/envoyproxy/envoy/blob/c256b948683b8bd800df80f69f470e1202510242/contrib/golang/filters/http/source/common/dso/dso.cc#L59-L70

It's not a serious bug, better fix it after #25677 is merged, otherwise, we may have to resolve conflicts.

### PR DESCRIPTION
**Pull request by doujiang24**
Commit Message:
fix loaded_ may be overwritten unexpectedly.
fix #25757
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: contrib/golang/common/dso/dso.cc [hunk 1]
```diff
@@ -39,18 +43,18 @@ Dso::~Dso() {
 }
 
 HttpFilterDsoImpl::HttpFilterDsoImpl(const std::string dso_name) : HttpFilterDso(dso_name) {
-  loaded_ = dlsymInternal<decltype(envoy_go_filter_new_http_plugin_config_)>(
+  dlsymInternal<decltype(envoy_go_filter_new_http_plugin_config_)>(
```
Comment (wangfakang) [inline contrib/golang/common/dso/dso.cc:46]: nit: use `&=` instead of `=` is the easiest way to fix it. such as below:
```
loaded_ &= dlsymInternal<decltype(envoy_go_filter_new_http_plugin_config_)>(envoy_go_filter_new_http_plugin_config_, handler_, dso_name,
      "envoyGoFilterNewHttpPluginConfig");
```

**Review by wangfakang — APPROVED** [review]
some nits. LGTM

File: contrib/golang/common/dso/dso.cc (hunk 1 above)
Comment (doujiang24) [reply contrib/golang/common/dso/dso.cc]: Thanks, done.

**Review by wangfakang — APPROVED** [review]

**Comment by doujiang24** [comment]
/assign @wbpcode 
Could you please take a look? Thanks!

**Review by wbpcode — APPROVED** [review]
LGTM. Thanks.
