### PR TITLE
test: deflaking */LoadStatsIntegrationTest.LocalityWeighted/*

### LINKED ISSUE #6874: IpVersions/LoadStatsIntegrationTest.LocalityWeighted/IPv4 timing out coverage
AFIK reverting 6761 got us from pretty deterministic failure to generally passing but I've seen 2 failures since

https://circleci.com/gh/envoyproxy/envoy/213854?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
https://circleci.com/gh/envoyproxy/envoy/213482?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

### PR DESCRIPTION
**Pull request by alyssawilk**
For posterity #6875 got us the information it was a "waiting for stats" bug, which is then debuggable by lowering load stats interval to 1ms.

This exposed two issues with merge.  When request 1 arrived in a separate interval from request 2, the stats protos could arrive in the opposite order (fixed by ignoring order) and that if there was a stats-update with a request in progress it never resolved because we were always adding fields (oops!)

I'm tempted to leave the interval low now that this is thoroughly debugged, but there's expectations on the time being within a range which wouldn't work if we lower it so meh?

Risk Level: n/a (test only)
Testing: yes.  very much so.
Docs Changes: n/a
Release Notes: n/a
Fixes #6874

### CODE REVIEW

File: test/test_common/utility.h [hunk 1]
```diff
@@ -260,35 +260,76 @@ class TestUtility {
   static std::vector<std::string> split(const std::string& source, const std::string& split,
                                         bool keep_empty_string = false);
 
+  /**
```
Comment (htuch) [inline test/test_common/utility.h]: https://github.com/envoyproxy/envoy/blob/3e0ee3c1529a463ee7fa64a820e7224836ddde11/source/common/protobuf/utility.h#L144 was recently added, this should do the job I think.

File: test/test_common/utility.h [hunk 2]
```diff
@@ -260,35 +260,76 @@ class TestUtility {
...
-                                    const Protobuf::RepeatedPtrField<ProtoType>& rhs) {
+                                    const Protobuf::RepeatedPtrField<ProtoType>& rhs,
+                                    bool ignore_repeated_field_ordering = false) {
     if (lhs.size() != rhs.size()) {
       return false;
     }
 
-    for (int i = 0; i < lhs.size(); ++i) {
-      if (!TestUtility::protoEqual(lhs[i], rhs[i], /*ignore_repeated_field_ordering=*/false)) {
+    if (ignore_repeated_field_ordering == false) {
```
Comment (htuch) [inline test/test_common/utility.h]: `!ignore_repeated_field_ordering`

File: test/test_common/utility.h [hunk 3]
```diff
@@ -260,35 +260,76 @@ class TestUtility {
...
+        if (!TestUtility::protoEqual(lhs[i], rhs[i], /*ignore_repeated_field_ordering=*/false)) {
+          return false;
+        }
+      }
+
+      return true;
+    }
+    // ignore_repeated_field_ordering = true
+    std::list<ProtoType> lhs_list = repeatedProtoToList(lhs);
+    std::list<ProtoType> rhs_list = repeatedProtoToList(rhs);
```
Comment (htuch) [inline test/test_common/utility.h]: Can't we use `std::unordered_set` here with appropriate hashing/equality providers?

File: test/test_common/utility.h [hunk 4]
```diff
@@ -260,35 +260,76 @@ class TestUtility {
...
+   * @param ignore_repeated_field_ordering if ordering should be ignored. Note if true this turns
+   *   comparison into an N^2 operation.
    * @return bool indicating whether the RepeatedPtrField are equal. TestUtility::protoEqual() is
    *              used for individual element testing.
    */
   template <class ProtoType>
   static bool repeatedPtrFieldEqual(const Protobuf::RepeatedPtrField<ProtoType>& lhs,
-                                    const Protobuf::RepeatedPtrField<ProtoType>& rhs) {
+                                    const Protobuf::RepeatedPtrField<ProtoType>& rhs,
+                                    bool ignore_repeated_field_ordering = false) {
```
Comment (htuch) [inline test/test_common/utility.h]: I think it would be clearer to call this `ignored_ordering`, since the repeated ptr aspect is already in the type system and this should be read as "ignore ordering for fields that appear more than once".

File: test/test_common/utility.h (hunk 1 above)
Comment (alyssawilk) [reply test/test_common/utility.h]: I can use that, but to avoid the removal getting really expensive I'd have to iterate from the back.  I think that makes the code harder enough to read I'd prefer to leave as-is unless you have strong feelings about it?

File: test/test_common/utility.h (hunk 3 above)
Comment (alyssawilk) [reply test/test_common/utility.h]: No, because the fields in the sub-proto may have different order as well.  I'll add a comment for clarity.

File: test/test_common/utility.h (hunk 1 above)
Comment (htuch) [reply test/test_common/utility.h]: The template could probably easily be extended to have other container types if you are concerned about the `list` vs. `vector` ^^.

File: source/common/protobuf/utility.h [hunk 5]
```diff
@@ -142,15 +142,15 @@ class RepeatedPtrUtil {
...
+   * @return ReturnType the container of const Message pointers.
    */
-  template <typename ProtoType>
-  static ProtobufTypes::ConstMessagePtrVector
-  convertToConstMessagePtrVector(const Protobuf::RepeatedPtrField<ProtoType>& repeated_field) {
-    ProtobufTypes::ConstMessagePtrVector ret_vector;
+  template <typename ProtoType, typename ReturnType>
+  static ReturnType
+  convertToConstMessagePtrContainer(const Protobuf::RepeatedPtrField<ProtoType>& repeated_field) {
+    ReturnType ret_vector;
```
Comment (snowp) [inline source/common/protobuf/utility.h]: Maybe rename the variable now that it's not always a vector?

File: test/integration/load_stats_integration_test.cc [hunk 6]
```diff
@@ -461,22 +478,16 @@ TEST_P(LoadStatsIntegrationTest, LocalityWeighted) {
   initialize();
 
   // Debug logs for #6874
```
Comment (snowp) [inline test/integration/load_stats_integration_test.cc]: Remove comment?

File: test/test_common/utility.h [hunk 7]
```diff
@@ -265,30 +265,59 @@ class TestUtility {
    *
    * @param lhs RepeatedPtrField on LHS.
    * @param rhs RepeatedPtrField on RHS.
+   * @param ignore_repeated_field_ordering if ordering should be ignored. Note if true this turns
```
Comment (snowp) [inline test/test_common/utility.h]: Name here doesn't match the paramter name
