### PR TITLE
Bootstrap agent

### LINKED ISSUE #16471: bootstrap fields for user_agent overwritten internally
*Title*: `user_agent_name` and `user_agent_version` are overwritten if supplied via bootstrap configs. 

*Description*:
The [documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-node) for the bootstrap config indicates that these fields should be free-form strings.  I would expect to be able to override them if I chose, but they always revert back to the envoy build version.  Probably a niche group that would want to set these, but I do expect to be able to do so from the docs and the behavior of every other field i've encountered so far.  

I can get around this a bit by using the metadata field to provide my agent overrides, but seems like the docs should be updated or the behavior changed in order to avoid confusion.  

*Repro steps*:
1. run envoy with a bootstrap config that specifies `node.user_agent_name` and `node.user_agent_version`. 
2. get the config dump from the admin endpoint and verify the output `node` information has been changed.
 
e.g. a bootstrap node of
```
node:
  id: "test"
  cluster: "test-cluster"
  user_agent_name: "test-justin-agent"
  user_agent_version: "33"
```

gives the following from the config dump

```yaml
{
  "id": "test",
  "cluster": "test-cluster",
  "hidden_envoy_deprecated_build_version": "93753017cb8c64ba92536b755ddf756df377c6c3/1.19.0-dev/Clean/RELEASE/BoringSSL",
  "user_agent_name": "envoy",
  "user_agent_build_version": {
    "version": {
      "major_number": 1,
      "minor_number": 19
    },
```

*Config*:
```
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}

  clusters:
  - name: web_service
    connect_timeout: 0.25s
    type: STRICT_DNS # static
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: web_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: web_service
                port_value: 80

node:
  id: "test"
  cluster: "test-cluster"
  user_agent_name: "test-justin-agent"
  user_agent_version: "33"

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

### PR DESCRIPTION
**Pull request by justincely**
Commit Message: allow user_agent fields to be overridden from bootstrap config

Additional Description: `user_agent_name`, `user_agent_version` and `user_agent_build_version` all look like they're settable from the docs, but the server just sets these values from the internals.  This allows the users to override them if desired, but falls back to the default behavior. 

Risk Level: low

Testing: Added integration tests for using the values from the fields.  But to test manually: update any of those 3 fields in the bootstrap node config to whatever valid values you want, then verify that they show up in the /config_dump output.  If you omit them, the current defaults will still be populated.  

Docs Changes:

Release Notes: 

Platform Specific Features:

Fixes #16471

### CODE REVIEW

**Comment by prosper86** [comment]
Please tell me how to generate this setup? Mozilla/5.0 (Linux; Android 7.0; PRA-LA1 Build/HUAWEIPRA-LA1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.116 Mobile Safari/537.36 binu/1078 (1ceb656684e4cf54)

**Comment by justincely** [comment]
It's not clear to me what to fix on these failing builds, or if they're intermittent failures.  @yanavlasov just LMK if there's something I should do at this point

File: source/server/server.cc [hunk 1]
```diff
@@ -412,8 +412,29 @@ void InstanceImpl::initialize(const Options& options,
...
 
-  bootstrap_.mutable_node()->set_hidden_envoy_deprecated_build_version(VersionInfo::version());
-  bootstrap_.mutable_node()->set_user_agent_name("envoy");
+  // Check to see if bootstrap has set user_agent_name.  If yes, use that.  
+  // If not, use "envoy"
+  std::string user_agent_name = bootstrap_.node().user_agent_name();
+  if (user_agent_name == "" ) {
+    user_agent_name = "envoy";
+  }
+  bootstrap_.mutable_node()->set_user_agent_name(user_agent_name);
```
Comment (yanavlasov) [inline source/server/server.cc:421]: I think it would be more readable if you move setting the value into the `if` statement-true part. Since this is the only way it is modified in the proto.

Same for below cases.

**Review by yanavlasov — CHANGES_REQUESTED** [review]
The format error is indicated here: https://dev.azure.com/cncf/envoy/_build/results?buildId=76714&view=logs&j=c5dd2866-6ab3-5f3c-3a44-4cef0ec909b5&t=a9eb66d6-8944-5769-b3f7-476949dadcb8&l=56

It is too bad that it does not show line numbers. I just configured my editor to remove trailing whitespace when it saves a file to solve this issue.

/wait

File: source/server/server.cc (hunk 1 above)
Comment (justincely) [reply source/server/server.cc:421]: sure thing, happy to do whatever is most idiomatic here.  I took the original approach to do a few lines of determining what the right value is, then a single line to set it.  I think if I move the setting into the conditional then I need two lines that call the actual setting.  

I'll throw something up and you can tell me if that's what you were thinking.

**Comment by justincely** [comment]
thanks, I thought trailing whitespace removal was on for all, turns out I didn't have it set editor wide but rather for a couple specific languages.

File: source/server/server.cc [hunk 2]
```diff
@@ -412,9 +412,32 @@ void InstanceImpl::initialize(const Options& options,
...
 
-  bootstrap_.mutable_node()->set_hidden_envoy_deprecated_build_version(VersionInfo::version());
-  bootstrap_.mutable_node()->set_user_agent_name("envoy");
-  *bootstrap_.mutable_node()->mutable_user_agent_build_version() = VersionInfo::buildVersion();
+  // Check to see if bootstrap has set user_agent_name. If yes, use that.
+  // If not, use "envoy"
+  if (bootstrap_.node().user_agent_name().empty()) {
+    bootstrap_.mutable_node()->set_user_agent_name("envoy");
+  } else {
+    bootstrap_.mutable_node()->set_user_agent_name(bootstrap_.node().user_agent_name());
```
Comment (yanavlasov) [inline source/server/server.cc:420]: Why do you need the `else` statement? It looks noop.

**Review by yanavlasov — COMMENTED** [review]
/wait

File: source/server/server.cc (hunk 2 above)
Comment (justincely) [reply source/server/server.cc]: Looks like you're right for 2 of the 3.  You'll have to bear with me for a little; first time really working with this codebase and all he protos and generated bits.  I was a bit confused on the `node` vs `mutable_node` and which 

Looks like `user_agent_name` and `user_agent_build_version` both only need to be set IF the user hasn't set anything.  

However, the `user_agent_version` seems to be different due to the user of the `set_hidden_deprecated_build_version` bit.  I don't quite know why, but regardless of if `bootstrap_.node().user_agent_version()` has been set, it seems we still need to call `bootstrap_.mutable_node()->set_hidden_envoy_deprecated_build_version()` to get it to pop out in the `/config_dump`.  

Related, though not necessarily part of this issue: it is odd to me that the output node information from /config_dump doesn't match the input for this field.  It actually dumps out `hidden_envoy_deprecated_build_version` rather than `user_agent_version`

```json
    "node": {
     "id": "bootstrap_id",
     "cluster": "bootstrap_cluster",
     "hidden_envoy_deprecated_build_version": "test",
     "user_agent_name": "test-ci-user-agent",
     "user_agent_build_version": {
      "version": {
       "major_number": 1,
       "minor_number": 19
      },

```

**Comment by prosper86** [comment]
I'm using this adress as remote proxy myassupol.datafree.co then I'm
getting 407 Proxy-Authenticate. How can I fix it?

**Comment by justincely** [comment]
@prosper86 please open issues in the main issue tracker or ask questions in the envoy slack channel.  This pull request isn't the correct place for these discussions.

**Comment by justincely** [comment]
@yanavlasov do you know if/how I can run the failing test locally? I'm trying to fix the null pointer error it raises

**Comment by justincely** [comment]
nvm, think i found it with
```bash
./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'
ci/run_envoy_docker.sh 'ci/do_ci.sh bazel.clang_tidy'
```

**Review by yanavlasov — APPROVED** [review]

**Comment by yanavlasov** [comment]
Thanks
