### PR TITLE
network: fix sporadic test failures related to Network::ConnectionImpl

### LINKED ISSUE #2271: Mac CircleCI tests are flaky
*Description*:
Periodically the mac tests fail, and a PR close/open cycle can be used to re-run.  The test that failed for me most recently was:

```
//test/common/http:codec_client_test                                     FAILED in 0.2s
  /private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/execroot/envoy/bazel-out/darwin-fastbuild/testlogs/test/common/http/codec_client_test/test.log
```

I don't know which of the codec_client_test methods fail, or how to see the contents of test.log.  I've also tried to re-run with various sanitizers at Google and haven't been able to repro the problem yet.

*Relevant Links*:

Here's a CircleCI failing case: https://circleci.com/gh/envoyproxy/envoy/14854?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### PR DESCRIPTION
**Pull request by zuercher**
*Description*:

Fixes non-determinism in setup of `test/common/http:codec_client_test` (similar to changes previously made to `test/common/network:connection_impl_test`). Doing that uncovered a reliable test failure as describe in #2271, which is resolved by not invoking the connection read filter's onData callback if no data was processed on a read event.

*Risk Level*: Medium -- relatively low-level change, coverage shows that even without the new test both paths of the onData guard were followed

*Testing*:
Flakey test no longer fails after 1000 runs (where before ~50 were sufficient). Added direct test of change in ConnectionImpl.

Fixes #2271

### CODE REVIEW

**Comment by zuercher** [comment]
FWIW, I have another branch that just modifies the test to handle seeing the same buffer multiple times. It's a simpler change, since it only modifies the codec_client_test.

File: source/common/network/connection_impl.cc [hunk 1]
```diff
@@ -421,7 +421,11 @@ void ConnectionImpl::onReadReady() {
   IoResult result = transport_socket_->doRead(read_buffer_);
   uint64_t new_buffer_size = read_buffer_.length();
   updateReadBufferStats(result.bytes_processed_, new_buffer_size);
-  onRead(new_buffer_size);
+  if (result.bytes_processed_ != 0) {
```
Comment (mattklein123) [inline source/common/network/connection_impl.cc]: This seems reasonable to me. I can't think of any reason why we would want to raise onRead if no bytes were processed, even if there are bytes still in the read buffer. However I want to make sure I understand the flow here which I don't think I do. Can you clarify the sequence of events that causes the problems on OSX that don't happen on Linux? I'm mainly trying to understand if there is potentially a larger lurking problem here that we don't know about. @alyssawilk can you take a look at this also?

Comment (alyssawilk) [reply source/common/network/connection_impl.cc]: I'm curious as well.  Is this only on initial connection (like the initial EPOLLIN arrives before bytes and somehow translates to onRead?) or in general?

Comment (zuercher) [reply source/common/network/connection_impl.cc]: The sequence is:

1. Read event. In this test 36 bytes (`"HTTP/1.1 200 OK\r\ncontent-length: 0\r\n"`) are added to `read_buffer_` and `Http::MockClientConnection::dispatch()` is invoked (via `onRead`). The test does not arrange to drain the buffer.
2. A second read event is triggered. There's no new data, but `onRead` is invoked again and the same buffer is delivered to dispatch. I believe in actual usage the http parser would have processed the bytes and the buffer would have been drained.
3. `Http::CodecClient` invokes dispatch with an empty buffer as part of handling the stream reset.

Step 2 doesn't always happen. I think it's related to the socket close. AFAICT libevent should be using kqueue on OSX. Based on my reading of the kqueue man page, kqueue read events are triggered on remote close, which sets an EV_EOF flag in the kqueue event. This may happen with or without available data. Looking at libevent they don't seem to check for this case. I presume that usually there's one read event with data and EV_EOF set, but sometimes the data and the EOF are reported separately and libevent passes both events on.

My other branch modifies this test to accept that the buffer might be delivered once or twice. It's also not difficult to modify the test to drain the buffer, but we'd still see 3 calls to dispatch (one with data, and two with empty buffers).

Comment (alyssawilk) [reply source/common/network/connection_impl.cc]: Ahhh, so basically on MacOS we were just getting the FIN separately and the current code would do an onRead for that?  Makes sense and code LGTM.

Could I also ask that you dup the flaky test where we did a write + close and event loop and instead write (loop) close (loop) to unit test how this is likely to occur in production?

Comment (mattklein123) [reply source/common/network/connection_impl.cc]: I think this looks good to me also. In the case where we process zero bytes, can we also assert that `result.action_ == PostIoAction::Close`? I think that should always be the case. I think in general this is a better more common solution, as we don't require connection users to drain read buffers.

Comment (ggreenway) [reply source/common/network/connection_impl.cc]: I don't trust either linux or macos to never cause a spurious wakeup, given that they're mostly harmless.  I think asserting is too harsh.

Comment (zuercher) [reply source/common/network/connection_impl.cc]: @mattklein123 in SSL connections a handshake error (see `source/common/ssl/ssl_socket.cc` lines 38 and 103) results in PostIoAction::KeepOpen but no data. Looking at adding the assertion in RawBufferSocket, but there's already a case in there that handles EAGAIN, so it may well be possible to get an empty read on an open socket there too.

Comment (mattklein123) [reply source/common/network/connection_impl.cc]: OK just skip it.

Comment (zuercher) [reply source/common/network/connection_impl.cc]: And empty read with KeepOpen also happens when the read buffer has reached it's buffer limit (if I'm reading the test correctly).

File: test/common/network/connection_impl_test.cc [hunk 2]
```diff
@@ -583,23 +583,26 @@ TEST_P(ConnectionImplTest, IgnoreEmptyReadTest) {
...
+  client_connection_->write(data);
+  dispatcher_->run(Event::Dispatcher::RunType::Block);
 
+  // Close the connection and verify that the undrained buffer is not passed to the read filter a
+  // second time.
   EXPECT_CALL(client_callbacks_, onEvent(ConnectionEvent::LocalClose));
   EXPECT_CALL(server_callbacks_, onEvent(ConnectionEvent::RemoteClose))
       .WillOnce(Invoke([&](Network::ConnectionEvent) -> void { dispatcher_->exit(); }));
-
+  client_connection_->close(ConnectionCloseType::NoFlush);
```
Comment (alyssawilk) [inline test/common/network/connection_impl_test.cc]: Oh sorry for miscommunication but I think we want both tests, the original and this edited one.  It'd be good to verify if the data and fin arrive together (which they usually do on non-mac-OS) we handle that case as well as this.  WDYT?

Comment (zuercher) [reply test/common/network/connection_impl_test.cc]: Ah. Ok.

Comment (zuercher) [reply test/common/network/connection_impl_test.cc]: Comments wrong now anyway, since in this version of the test there's always an empty read, even on Linux.

File: test/common/network/connection_impl_test.cc [hunk 3]
```diff
@@ -575,6 +575,57 @@ TEST_P(ConnectionImplTest, BindFailureTest) {
   dispatcher_->run(Event::Dispatcher::RunType::NonBlock);
 }
 
+// ReadOnCloseTest verifies that the read filter's onData function is invoked with available data
+// when the connection is closed.
+TEST_P(ConnectionImplTest, ReadOnCloseTest) {
+  setUpBasicConnection();
+  connect();
+
+  // Close without flush will immediately invokes this callback.
```
Comment (mattklein123) [inline test/common/network/connection_impl_test.cc]: nit: grammar "will immediately invokes"
