### PR TITLE
wasm: accept cluster name in grpcCall()

### LINKED ISSUE #15170: Fallback when GrpcService parse failed to create gRPC call on wasm
It will be troublesome not to allow just identifying gRPC target host name as `grpcCall` argument. Specifically, we should provide fallback mechanism if `GrpcService` parse failed from bytes stream. 

https://github.com/envoyproxy/envoy/blob/c8fb3a56b4e8e282b0da80e2b19a347969d9cb2f/source/extensions/common/wasm/context.cc#L981-L984

We will get into some trouble without this feature when we introduce support gRPC client from proxy-wasm SDK such as Rust. (It doesn't have gRPC client support right now), because it will be required new code for the desired language generated from Envoy API proto. 

My expected behavior is when we failed to parse bytes stream, then try to parse the bytes stream as hostname. We will get `ParseFailure` after failed to parse hostname.

### PR DESCRIPTION
**Pull request by Shikugawa**
Signed-off-by: Shikugawa <rei@tetrate.io>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

Commit Message: Close #15170. Add capability to accept yaml style GrpcService message for grprCall(). It is required to support gRPC related operation on SDK, such as Rust which doesn't have gRPC support. It is required to ease use of grpcCall()
Additional Description:
Risk Level: Low
Testing: Unit
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by Shikugawa** [comment]
cc @mathetake

File: source/extensions/common/wasm/context.cc [hunk 1]
```diff
@@ -980,7 +982,13 @@ WasmResult Context::grpcCall(absl::string_view grpc_service, absl::string_view s
                              uint32_t* token_ptr) {
   GrpcService service_proto;
   if (!service_proto.ParseFromArray(grpc_service.data(), grpc_service.size())) {
-    return WasmResult::ParseFailure;
+    try {
+      ProtobufMessage::StrictValidationVisitorImpl validation_visitor;
+      MessageUtil::loadFromYaml(std::string(grpc_service.substr(0, grpc_service.size())),
+                                service_proto, validation_visitor);
+    } catch (const EnvoyException& e) {
```
Comment (mathetake) [inline source/extensions/common/wasm/context.cc:989]: nit: I don't see there's no test case added coving this branch. Could you?

Comment (PiotrSikora) [inline source/extensions/common/wasm/context.cc:989]: I believe that exceptions are not allowed in the data path anymore.

**Review by PiotrSikora — CHANGES_REQUESTED** [review]
As mentioned in https://github.com/envoyproxy/envoy/issues/15170, I think this requires patch-level ABI bump, otherwise plugins built with SDKs that support this new format will be loaded sucessfully in Envoy that doesn't support the fallback (i.e. v1.17 or Istio 1.9), and will fail at runtime.

**Comment by Shikugawa** [comment]
@PiotrSikora I think that this is not so bad (even if this is just a workaround) until ABI v1.0.0 released. (It can be also tech debt since we should introduce runtime guard flag of this bahavior) 
Do you have any thoughts?

File: source/extensions/common/wasm/context.cc [hunk 2]
```diff
@@ -980,7 +982,13 @@ WasmResult Context::grpcCall(absl::string_view grpc_service, absl::string_view s
                              uint32_t* token_ptr) {
   GrpcService service_proto;
   if (!service_proto.ParseFromArray(grpc_service.data(), grpc_service.size())) {
-    return WasmResult::ParseFailure;
```
Comment (PiotrSikora) [inline source/extensions/common/wasm/context.cc:983]: Could we support using existing cluster here, by providing only the cluster name, and not a proto service (regardless of whether it's binary or YAML)?

**Review by PiotrSikora — CHANGES_REQUESTED** [review]
> @PiotrSikora I think that this is not so bad (even if this is just a workaround) until ABI v1.0.0 released. (It can be also tech debt since we should introduce runtime guard flag of this bahavior)
Do you have any thoughts?

There is no perfect answer here.

- If we don't bump the ABI, then plugins that want to use this feature will load successfully, but they will fail at runtime with `ParseFailure`, which is a bit unfortunate.

- If we bump the ABI, then we need to bump the ABI in SDKs in order to use this feature, and then all plugins built using those SDKs will stop loading in older Envoy releases, even when not using this feature, which is definitely a deal breaker.

I'll try to figure out a way to detect optional features in the future, but in the meantime, I think we need to get this in without the ABI bump. Sorry for the noise!

File: source/extensions/common/wasm/context.cc [hunk 3]
```diff
@@ -1013,7 +1022,6 @@ WasmResult Context::grpcCall(absl::string_view grpc_service, absl::string_view s
   Protobuf::RepeatedPtrField<HashPolicy> hash_policy;
   hash_policy.Add()->mutable_header()->set_header_name(Http::Headers::get().Host.get());
   options.setHashPolicy(hash_policy);
-
```
Comment (PiotrSikora) [inline source/extensions/common/wasm/context.cc:1016]: Nit: unnecessary line removal.

File: test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc [hunk 4]
```diff
@@ -40,20 +40,20 @@ class GrpcCallRootContext : public RootContext {
   MyGrpcCallHandler* handler_ = nullptr;
 };
 
-class GrpcCallContext : public Context {
+class GrpcCallContextLegacy : public Context {
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc:43]: Nit: It's in tests, so it doesn't really matter, but we should probably use "...Proto" and not "...Legacy".

File: test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc [hunk 5]
```diff
@@ -80,4 +80,40 @@ FilterHeadersStatus GrpcCallContext::onRequestHeaders(uint32_t, bool end_of_stre
...
+    }
+    return FilterHeadersStatus::Continue;
+  }
+  root()->grpcCallHandler("cluster", "service", "method", initial_metadata, value, 1000,
+                          std::unique_ptr<GrpcCallHandlerBase>(root()->handler_));
+  if (root()->grpcCallHandler(
+          "bogus grpc_service", "service", "method", initial_metadata, value, 1000,
+          std::unique_ptr<GrpcCallHandlerBase>(new MyGrpcCallHandler())) == WasmResult::Ok) {
+    logError("bogus grpc_service accepted error");
+  }
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc:115]: I know the existing tests are full of this pattern, but this construction is wrong, since it doesn't test if the test case passed or even if it was executed at all.

This should be changed to positive tests, i.e.:
```
if (root()->grpcCallHandler(...) == WasmResult::BadArgument) {
  logInfo("bogus grpc_service rejected");
}
```
and the test runner should verify that this log entry was generated by the plugin.

Same in other new tests.

**Review by PiotrSikora — COMMENTED** [review]
Thanks! Looks mostly good, but I'd like to see some changes in tests.

**Comment by PiotrSikora** [comment]
@mandarjog @bianpengyuan @kyessenov we should figure out how/if we can migrate from Google gRPC proto definitions with STS credentails embedded in Istio Stackdriver plugin to using a cluster configured by Istiod.

File: test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc (hunk 4 above)
Comment (Shikugawa) [reply test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc]: done

File: test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc (hunk 5 above)
Comment (Shikugawa) [reply test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc]: done

File: source/extensions/common/wasm/context.cc [hunk 6]
```diff
@@ -994,7 +994,16 @@ WasmResult Context::grpcCall(absl::string_view grpc_service, absl::string_view s
                              uint32_t* token_ptr) {
   GrpcService service_proto;
   if (!service_proto.ParseFromArray(grpc_service.data(), grpc_service.size())) {
-    return WasmResult::ParseFailure;
+    if (Runtime::runtimeFeatureEnabled("envoy.reloadable_features.wasm_cluster_name_envoy_grpc")) {
+      auto cluster_name = std::string(grpc_service.substr(0, grpc_service.size()));
+      const auto thread_local_cluster = clusterManager().getThreadLocalCluster(cluster_name);
+      if (thread_local_cluster == nullptr) {
+        return WasmResult::BadArgument;
```
Comment (PiotrSikora) [inline source/extensions/common/wasm/context.cc:1001]: I think we should return `WasmResult::ParseFailure` here, since previously neither `grpcCall` nor `grpcStream` could return `WasmResult::BadArgument`, so this would result in a new code path for callers, and since we're not bumping the ABI version, I don't think that we should do that.

Having said that, this is a "better" result code, so feel free to add a `TODO` saying that we should switch to `WasmResult::BadArgument` in the next iteration of the ABI.

**Review by PiotrSikora — CHANGES_REQUESTED** [review]

File: source/extensions/common/wasm/context.cc (hunk 6 above)
Comment (Shikugawa) [reply source/extensions/common/wasm/context.cc]: done

**Comment by kyessenov** [comment]
Istio would need to offer STS as a feature I think. It's not exposed in the API, so it would require an EnvoyFilter.

**Comment by Shikugawa** [comment]
@PiotrSikora How is going?

File: test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc [hunk 7]
```diff
@@ -72,11 +77,42 @@ FilterHeadersStatus GrpcCallContext::onRequestHeaders(uint32_t, bool end_of_stre
...
-    logError("bogus grpc_service accepted error");
+          std::unique_ptr<GrpcCallHandlerBase>(new MyGrpcCallHandler())) == WasmResult::ParseFailure) {
+    logError("bogus grpc_service rejected");
   }
+  if (end_of_stream) {
+    if (root()->grpcCallHandler("cluster", "service", "method", initial_metadata, value,
+                                1000, std::unique_ptr<GrpcCallHandlerBase>(root()->handler_)) ==
+        WasmResult::Ok) {
+      logError("expected failure did not occur");
+    }
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc:111]: Please convert this to a positive test and log that failure occured.

File: test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc [hunk 8]
```diff
@@ -72,11 +77,42 @@ FilterHeadersStatus GrpcCallContext::onRequestHeaders(uint32_t, bool end_of_stre
...
+    return FilterHeadersStatus::Continue;
+  }
+  root()->grpcCallHandler("cluster", "service", "method", initial_metadata, value, 1000,
+                          std::unique_ptr<GrpcCallHandlerBase>(root()->handler_));
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc:115]: Please check for `WasmResult::Ok`.

File: test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc [hunk 9]
```diff
@@ -91,4 +92,32 @@ FilterHeadersStatus GrpcStreamContext::onRequestHeaders(uint32_t, bool) {
...
+                                                         ROOT_FACTORY(GrpcStreamRootContext),
+                                                         "grpc_stream");
+
+FilterHeadersStatus GrpcStreamContext::onRequestHeaders(uint32_t, bool) {
+  HeaderStringPairs initial_metadata;
+  if (root()->grpcStreamHandler("bogus service string", "service", "method", initial_metadata,
+                                std::unique_ptr<GrpcStreamHandlerBase>(
+                                    new MyGrpcStreamHandler())) != WasmResult::ParseFailure) {
+    logError("unexpected bogus service string OK");
+  }
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc:112]: Please convert this to a positive test and log that failure occured.

File: test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc [hunk 10]
```diff
@@ -91,4 +92,32 @@ FilterHeadersStatus GrpcStreamContext::onRequestHeaders(uint32_t, bool) {
...
+  if (root()->grpcStreamHandler("cluster", "service", "bad method", initial_metadata,
+                                std::unique_ptr<GrpcStreamHandlerBase>(
+                                    new MyGrpcStreamHandler())) != WasmResult::InternalFailure) {
+    logError("unexpected bogus method OK");
+  }
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc:117]: Please convert this to a positive test and log that failure occured.

File: test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc [hunk 11]
```diff
@@ -91,4 +92,32 @@ FilterHeadersStatus GrpcStreamContext::onRequestHeaders(uint32_t, bool) {
...
+  root()->grpcStreamHandler("cluster", "service", "method", initial_metadata,
+                            std::unique_ptr<GrpcStreamHandlerBase>(new MyGrpcStreamHandler()));
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc:119]: Please check for `WasmResult::Ok`.

**Review by PiotrSikora — CHANGES_REQUESTED** [review]
LGTM for code, but please convert tests to verify that errors occured (I've asked about this previously, but it looks that you fixed it only in 1 of 6 calls).

**Comment by PiotrSikora** [comment]
@Shikugawa friendly ping to get this in before next release. Also, it looks like it needs a merge with `main` branch.

File: test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc (hunk 7 above)
Comment (Shikugawa) [reply test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc:111]: done

File: test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc (hunk 9 above)
Comment (Shikugawa) [reply test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc:112]: done

File: test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc (hunk 10 above)
Comment (Shikugawa) [reply test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc:121]: done

File: test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc (hunk 9 above)
Comment (Shikugawa) [reply test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc:112]: done

File: test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc [hunk 12]
```diff
@@ -107,16 +107,18 @@ FilterHeadersStatus GrpcStreamContext::onRequestHeaders(uint32_t, bool) {
   HeaderStringPairs initial_metadata;
   if (root()->grpcStreamHandler("bogus service string", "service", "method", initial_metadata,
                                 std::unique_ptr<GrpcStreamHandlerBase>(
-                                    new MyGrpcStreamHandler())) != WasmResult::ParseFailure) {
-    logError("unexpected bogus service string OK");
+                                    new MyGrpcStreamHandler())) == WasmResult::ParseFailure) {
+    logError("unexpected bogus service parse failure");
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc:111]: Nit: This is expected failure, so you should remove the "unexpected" word from the log line.

File: test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc [hunk 13]
```diff
@@ -107,16 +107,18 @@ FilterHeadersStatus GrpcStreamContext::onRequestHeaders(uint32_t, bool) {
...
   }
   if (root()->grpcStreamHandler("cluster", "service", "bad method", initial_metadata,
                                 std::unique_ptr<GrpcStreamHandlerBase>(
-                                    new MyGrpcStreamHandler())) != WasmResult::InternalFailure) {
-    logError("unexpected bogus method OK");
+                                    new MyGrpcStreamHandler())) == WasmResult::InternalFailure) {
+    logError("unexpected bogus method call failure");
```
Comment (PiotrSikora) [inline test/extensions/filters/http/wasm/test_data/test_grpc_stream_cpp.cc:116]: Nit: This is expected failure, so you should remove the "unexpected" word from the log line.

File: source/extensions/common/wasm/context.cc [hunk 14]
```diff
@@ -1055,8 +1067,21 @@ WasmResult Context::grpcStream(absl::string_view grpc_service, absl::string_view
...
+        // callers to change their own codebase with ABI 0.1.x. We should treat this failure as
+        // `BadArgument` after ABI 0.2.x will have released.
+        return WasmResult::ParseFailure;
+      }
+      service_proto.mutable_envoy_grpc()->set_cluster_name(cluster_name);
+    } else {
+      return WasmResult::ParseFailure;
+    }
   }
+
```
Comment (PiotrSikora) [inline source/extensions/common/wasm/context.cc:1084]: Nit: unnecesary empty line.

**Review by PiotrSikora — APPROVED** [review]
Thanks! LGTM, 2 minor nits in comments.

**Review by PiotrSikora — APPROVED** [review]
Thanks!

File: docs/root/version_history/current.rst [hunk 15]
```diff
@@ -70,6 +70,7 @@ Minor Behavior Changes
   are very frequent. This change can be disabled by setting the `envoy.reloadable_features.upstream_host_weight_change_causes_rebuild`
   feature flag to false. If setting this flag to false is required in a deployment please open an
   issue against the project.
+* wasm: accpet cluster name to invoke grpc call and stream creation. This value won't break current wasm ABI spec and guaraded with `envoy.reloadable_features.wasm_cluster_name_envoy_grpc` that enabled by default.
```
Comment (mattklein123) [inline docs/root/version_history/current.rst:73]: Typo "accpet", also since is effectively not documented (from my perspective) I think we should skip release notes. When WASM is sufficiently documented we can start doing release notes. So I would just remove this.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Small comment, thanks.

/wait

**Review by mattklein123 — APPROVED** [review]
