### PR TITLE
ci: Create diff and upload artefacts from clang-tidy fixes yaml

### LINKED ISSUE #25749: Add `clang-tidy` diff output in CI
Currently we run `clang-tidy-diff` (ie against changed files) in CI 

even with a small number of files this can be very expensive CI-wise

at the end it prints the `fix.yaml` that `clang-tidy` produces in the CI console but does not upload anything

we can use `clang-apply-replacements` to create a diff from this yaml file

i would suggest we do so and upload both as artefacts in CI to save devs a lot of time trying to run it themselves if the fixes are ~simple

when i used `clang-apply-replacements` locally i had to hack the file paths, but tbh i had already hacked a lot of things by that point so that may well be a local issue

### PR DESCRIPTION
**Pull request by phlax**
Fix #25749 

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: ci/run_clang_tidy.sh [hunk 1]
```diff
@@ -138,6 +140,27 @@ fi
...
+  if [[ -n "${CLANG_TIDY_APPLY_FIXES}" ]]; then
+      if [[ ! -e "$CLANG_APPLY_REPLACEMENTS" ]]; then
+          echo "clang-apply-replacements MISSING: ${CLANG_APPLY_REPLACEMENTS}"
+      else
+          ${CLANG_APPLY_REPLACEMENTS} .
+      fi
+      if [[ -n "${CLANG_TIDY_FIX_DIFF}" ]]; then
+          git diff > "${CLANG_TIDY_FIX_DIFF}"
+      fi
+      if [[ -e "${CLANG_TIDY_FIX_DIFF}" ]]; then
```
Comment (phlax) [inline ci/run_clang_tidy.sh:157]: probably show the diff even if the output file is not created

**Comment by phlax** [comment]
finally got this working:

- https://dev.azure.com/cncf/_apis/resources/Containers/17912695/bazel.clang_tidy.fixes?itemPath=bazel.clang_tidy.fixes%2Fclang-tidy-fixed.diff
- https://dev.azure.com/cncf/_apis/resources/Containers/17912695/bazel.clang_tidy.fixes?itemPath=bazel.clang_tidy.fixes%2Fclang-tidy-fixes.yaml
- https://dev.azure.com/cncf/envoy/_build/results?buildId=129094&view=logs&j=b7634614-24f3-5416-e791-4f3affaaed6c&t=21e6aa7d-f369-5abd-5e4e-e888cac18e9c&l=2345

**Review by KBaichoo — APPROVED** [review]
