### PR TITLE
async_client: add the option to keep parent sampling status for child spans

### LINKED ISSUE #17085: x-b3-sampled header always set to 1 in ext_authz request
The ext_authz envoy filter seems to always use an x-b3-sampled header value of 1 even after setting the`HttpConnectionManager.tracing.random_sampling` to a value of 0.0.  Is there some global sampling configuration being used by the filter that I was unable to find in the docs or is this unexpected behavior? 

Incoming requests do not have the `x-client-trace-id`, `x-envoy-force-trace`, or `x-b3-sampled` headers set and outgoing requests to other services (not including the ext_authz filter request) in the envoy mesh are abiding by the `HttpConnectionManager.tracing.random_sampling` setting.

### PR DESCRIPTION
**Pull request by carolinestere**
Commit Message: async_client: add the option to keep parent sampling status for child spans
Additional Description: ext authz requests always get traced, regardless of parent sampling status; this happens because the HTTP async client (used by ext authz) overrides the span's sampling status with `true`.
Risk Level: low
Testing: added a test case for keeping the parent's sampling status; built envoy and ran it with a config, confirming that authz spans keep the parent sampling status.
Docs Changes: Added
Release Notes: Added
Fixes #17085

Signed-off-by: Caroline Stere <stere@adobe.com>

### CODE REVIEW

File: source/common/http/async_client_impl.cc [hunk 1]
```diff
@@ -256,7 +256,10 @@ AsyncRequestImpl::AsyncRequestImpl(RequestMessagePtr&& request, AsyncClientImpl&
   } else {
     child_span_ = std::make_unique<Tracing::NullSpan>();
   }
-  child_span_->setSampled(options.sampled_);
+  if (options.sampled_) {
+    // Force span to get sampled; otherwise keep sampling status of the parent
+    child_span_->setSampled(true);
+  }
```
Comment (wbpcode) [inline source/common/http/async_client_impl.cc:262]: I am sure if this is a good choice. Because this will prevent someone from using request options to disable sampling.

File: source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc [hunk 2]
```diff
@@ -279,7 +279,8 @@ void RawHttpClientImpl::check(RequestCallbacks& callbacks,
     auto options = Http::AsyncClient::RequestOptions()
                        .setTimeout(config_->timeout())
                        .setParentSpan(parent_span)
-                       .setChildSpanName(config_->tracingName());
+                       .setChildSpanName(config_->tracingName())
+                       .setSampled(false);
```
Comment (wbpcode) [inline source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc:283]: It would be better to add new interface to get sampled status from parent span and then just use `.setSampled(parent_span.sampled())` to achieve your original target.

**Review by wbpcode — CHANGES_REQUESTED** [review]
Thanks for calling this out. 😄 Here are initial comments.

File: source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc (hunk 2 above)
Comment (carolinestere) [reply source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc:283]: Yep yep, that was my original idea too. But I hit some bumps when trying to implement `getSampled` in the `Span` implementations in tracers, and I thought ookay first keep it simple, and we'll see from there 😅

Comment (carolinestere) [reply source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc:283]: For example in the opentracing `Span` interface, I couldn't find a way to retrieve the sampled tag...

File: source/common/http/async_client_impl.cc (hunk 1 above)
Comment (carolinestere) [reply source/common/http/async_client_impl.cc:262]: I could add another field in options, `override_parent_sampling` which defaults to `true`, to keep the current behavior.

```
if (options.override_parent_sampling) {
	child_span_->setSampled(options.sampled_);
}
```

Comment (wbpcode) [reply source/common/http/async_client_impl.cc:262]: 🤔 sounds good to me.

Comment (wbpcode) [reply source/common/http/async_client_impl.cc:262]: Would it be more simple make the `sampled_` optional: `absl::optional<bool> sampled_`?

The default value of `sampled_` still be `true` and we can set it to `absl::nullopt` in which case the child span will keep sampling status of parent span.

.

Comment (carolinestere) [reply source/common/http/async_client_impl.cc:262]: Oh that's even better! I'll make the changes 😄

File: test/common/http/async_client_impl_test.cc [hunk 3]
```diff
@@ -273,8 +274,8 @@ TEST_F(AsyncClientImplTracingTest, BasicNamedChildSpan) {
   AsyncClient::RequestOptions options = AsyncClient::RequestOptions()
                                             .setParentSpan(parent_span_)
                                             .setChildSpanName(child_span_name_)
-                                            .setSampled(false);
-  EXPECT_CALL(*child_span, setSampled(false));
+                                            .setSampled(absl::nullopt);
+  EXPECT_CALL(*child_span, setSampled(_)).Times(0);
```
Comment (wbpcode) [inline test/common/http/async_client_impl_test.cc:278]: Can we reserve this test case where set sampling status to `false` and just add a new case where set sampling status to `absl::nullopt`?

Comment (carolinestere) [reply test/common/http/async_client_impl_test.cc]: Of course, good point! Done.

**Review by wbpcode — APPROVED** [review]
LGTM. cc @dio

**Comment by carolinestere** [comment]
@dio or somebody else 😅 Can someone please take a look at this PR so we can merge it?

File: source/common/http/async_client_impl.cc [hunk 4]
```diff
@@ -256,7 +256,10 @@ AsyncRequestImpl::AsyncRequestImpl(RequestMessagePtr&& request, AsyncClientImpl&
   } else {
     child_span_ = std::make_unique<Tracing::NullSpan>();
   }
-  child_span_->setSampled(options.sampled_);
+  if (options.sampled_.has_value()) {
+    // Change span's sampling status; otherwise keep sampling status of the parent
```
Comment (dio) [inline source/common/http/async_client_impl.cc:260]:
```suggestion
    // Change span's sampling status; otherwise keep sampling status of the parent.
```

File: source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc [hunk 5]
```diff
@@ -279,7 +280,8 @@ void RawHttpClientImpl::check(RequestCallbacks& callbacks,
     auto options = Http::AsyncClient::RequestOptions()
                        .setTimeout(config_->timeout())
                        .setParentSpan(parent_span)
-                       .setChildSpanName(config_->tracingName());
+                       .setChildSpanName(config_->tracingName())
+                       .setSampled(absl::nullopt);
```
Comment (dio) [inline source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc:284]: Could you add a comment here on why this is helping on keeping the parent sampling status?

**Review by dio — CHANGES_REQUESTED** [review]
Thanks, @carolinestere for working on this. Sorry for the very late review.

Overall looks good. However, I need clarification on how this is controlled from a user perspective (how to change that `bool` from config).

Also please add an entry in `docs/root/version_history/current.rst` since it potentially changes a behavior.

File: source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc (hunk 5 above)
Comment (carolinestere) [reply source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc]: Sure thing, done.

**Comment by carolinestere** [comment]
@dio Thanks for the review! However I'm not sure why would the user need to individually control the sampling status of the ext authz span. Doesn't it make sense for it to always keep the sampling status of the parent span?

**Comment by dio** [comment]
> Doesn't it make sense for it to always keep the sampling status of the parent span?

@carolinestere it does make sense yeah. 

Could you please add that to `docs/root/version_history/current.rst` as a minor behavior change: from always true, to depending on the parent's settings? I'm also thankful if we can find a way to surface this to the docs (probably here: `docs/root/configuration/http/http_filters/ext_authz_filter.rst`?). 

Thank you!

**Comment by carolinestere** [comment]
@dio Done and done 😄 What do you think?

File: docs/root/version_history/current.rst [hunk 6]
```diff
@@ -25,6 +25,7 @@ Minor Behavior Changes
 * router: take elapsed time into account when setting the x-envoy-expected-rq-timeout-ms header for retries, and never send a value that's longer than the request timeout. This behavioral change can be temporarily reverted by setting runtime guard ``envoy.reloadable_features.update_expected_rq_timeout_on_retry`` to false.
 * stream_info: response code details with empty space characters (' ', '\t', '\f', '\v', '\n', '\r') is not accepted by the ``setResponseCodeDetails()`` API.
 * upstream: fixed a bug where auto_config didn't work for wrapped TLS sockets (e.g. if proxy proto were configured for TLS).
+* ext_authz: the ext_authz span was always getting sampled, even if the parent span was not; now the ext_authz span follows the parent's sampling status.
```
Comment (dio) [inline docs/root/version_history/current.rst:28]: Nit: you need to sort this. alpha-ordered (the formatter will ask it from you).

Comment (carolinestere) [reply docs/root/version_history/current.rst:28]: Oh thanks 😅

**Review by dio — DISMISSED** [review]
Thanks! Looks good!

**Comment by dio** [comment]
/assign-from @envoyproxy/senior-maintainers 

for a final pass.

File: envoy/http/async_client.h [hunk 7]
```diff
@@ -313,7 +313,7 @@ class AsyncClient {
     // Only used if parent_span_ is set.
     std::string child_span_name_{""};
     // Sampling decision for the tracing span. The span is sampled by default.
```
Comment (alyssawilk) [inline envoy/http/async_client.h:315]: Is it still sampled by default?

**Review by alyssawilk — COMMENTED** [review]
Nice fix!  Just one question below
/wait

File: envoy/http/async_client.h (hunk 7 above)
Comment (carolinestere) [reply envoy/http/async_client.h:315]: Yep yep. Only in the [ext_authz span](https://github.com/envoyproxy/envoy/blob/4c40c781f29856f19662f194bbcc767bf1631b79/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc#L285) do we set `sampled_` to `absl::nullopt`, so that the span doesn't get sampled by default and instead keep the parent's sampling decision.

Comment (alyssawilk) [reply envoy/http/async_client.h:315]: But in the constructor it says sets the value iff the value is present in the constructor, "otherwise keep sampling status of the parent" not "otherwise keep sampling by default"  It sounds like the two comments explain different defaults?  Or I'm confused but in that case we should still ideally make it more clear :-)

Comment (carolinestere) [reply envoy/http/async_client.h:315]: The two comments refer to two different aspects:

The one from the [RequestOptions struct](https://github.com/envoyproxy/envoy/blob/4c40c781f29856f19662f194bbcc767bf1631b79/envoy/http/async_client.h#L315) says that, by default, the `sampled_` field in `RequestOptions` is `optional<true>`.

The one from the [async_client_impl](https://github.com/envoyproxy/envoy/blob/4c40c781f29856f19662f194bbcc767bf1631b79/source/common/http/async_client_impl.cc#L260) refers to how the async client interprets the value of `RequestOption`'s `sampled_` field: if `sampled_` has any value, then it will `Change span's sampling status`; otherwise it will `keep sampling status of the parent`.

Is this clearer?

Comment (wbpcode) [reply envoy/http/async_client.h:315]: @alyssawilk I agree keeping parent's sampling default is more reasonable. But here I think @carolinestere is try to keep original behavior so keep the flag default to true.

Comment (carolinestere) [reply envoy/http/async_client.h:315]: Yep, exactly, I kept the `sampled_` default as `true`, just like it was before, to keep the original behavior.

@alyssawilk I will update the comment in async_client, so it's clear that, by default, the span always gets sampled.

Comment (carolinestere) [reply envoy/http/async_client.h:315]: @alyssawilk Is it better now? 😄

**Review by alyssawilk — APPROVED** [review]
Yes much more clear - thanks for explaining both in comments and now in the code :-)
