### PR TITLE
upstream: fix outlier detector's exponential backoff for time-based monitors

### LINKED ISSUE #26758: Failure percentage based outlier detection time does not increase on successive ejections
*Title*: Failure percentage based outlier detection time does not increase on successive ejections

*Description*:
In a cluster configured to detect outliers based on failure percentage, when a host gets ejected multiple times in a row, envoy  does not properly increase the time of ejection.

Here is an example of what the membership_healthy looks like over time in my setup.
In this case, `interval` is 30s, `baseEjectionTime` is 60s and `maxEjectionTime` is 300s.

image

*Repro steps*:
Set up a cluster with a host that only sends back 500 codes, and configure the outlier detection to use failure percentage. Then put some load for a few minutes and observe as the host is ejected and un-ejected at a regular pace.

*Config*:
```json
       {
        "version_info": "2023-04-14T14:54:23Z/1608",
        "cluster": {
         "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
         "name": "outbound|80|ivts-31677c-piv|egressgateway.istio-gateways.svc.cluster.local",
         "type": "EDS",
         "eds_cluster_config": {
          "eds_config": {
           "ads": {},
           "initial_fetch_timeout": "0s",
           "resource_api_version": "V3"
          },
          "service_name": "outbound|80|ivts-31677c-piv|egressgateway.istio-gateways.svc.cluster.local"
         },
         ...
         "outlier_detection": {
          "consecutive_5xx": 5,
          "interval": "30s",
          "base_ejection_time": "60s",
          "max_ejection_percent": 100,
          "enforcing_consecutive_5xx": 0,
          "enforcing_success_rate": 0,
          "enforcing_consecutive_gateway_failure": 0,
          "failure_percentage_threshold": 25,
          "enforcing_failure_percentage": 100,
          "enforcing_failure_percentage_local_origin": 100,
          "failure_percentage_minimum_hosts": 0,
          "failure_percentage_request_volume": 50,
          "max_ejection_time": "300s",
          "max_ejection_time_jitter": "0s"
         },
         ...
       }
```

*Version*:
I am using envoy in an istio 1.15.1 setup, this is the version of envoy that I could retrieve - "94bd57194ed66b70e231dbf22a7771a9e9e43a74/1.23.2-dev/Clean/RELEASE/BoringSSL"

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
fix outlier detector's exponential backoff for time-based monitors
Additional Description:
There was a bug in logic deciding if the backoff time should be decremented. It worked properly only for consecutive 5xx errors. It did not work for monitors which kicked in on periodic basis: success rate and failure percentage. The main difference between those monitors is that consecutive error's monitor ejects a node immediately and time-based monitors keep the node in the pool until periodic timer triggers outlier's detector's calculation.
The new logic starts decrementing backoff time when the node was not declared unhealthy for at least one period of periodic monitors' check.
Risk Level: Low
Testing: Added unit test to check the proper logic.
Docs Changes: No
Release Notes: Yes
Fixes #26758, #21142

### CODE REVIEW

**Comment by ravenblackx** [comment]
ping @wbpcode

File: source/common/upstream/outlier_detection_impl.cc [hunk 1]
```diff
@@ -760,6 +756,22 @@ void DetectorImpl::onIntervalTimer() {
...
+      if (monitor->lastUnejectionTime().has_value() &&
+          ((now - monitor->lastUnejectionTime().value()) >=
+           std::chrono::milliseconds(
+               runtime_.snapshot().getInteger(IntervalMsRuntime, config_.intervalMs())))) {
+        if (monitor->ejectTimeBackoff() != 0) {
+          monitor->ejectTimeBackoff()--;
+        }
+      }
+    }
+  }
```
Comment (wbpcode) [inline source/common/upstream/outlier_detection_impl.cc:773]: This is LGTM overall. But should we decrement the backoff directly if the host is healthy?

From the docs,
>  If the host is healthy during that check, the ejection time multiplier is decremented.

**Review by wbpcode — COMMENTED** [review]
LGTM overall. Please add a release note for this fix because this bug fix changed the behavior.

And a comment is added about the decrement of backoff value.

File: source/common/upstream/outlier_detection_impl.cc (hunk 1 above)
Comment (cpakulski) [reply source/common/upstream/outlier_detection_impl.cc:773]: That line of code checks is the node is healthy:

`
    if (!host.first->healthFlagGet(Host::HealthFlag::FAILED_OUTLIER_CHECK)) {
`

In outlier detection terms, HEALTHY means that it has not been ejected by one of outlier detection monitors yet. The logic here is: if the node was not ejected during last period of interval and is healthy now, we can start decrementing backoff time.

Comment (wbpcode) [reply source/common/upstream/outlier_detection_impl.cc:773]: I think you mis-understood it. But never mind. After a think again, I think you are right.

This is a reasonable change. There is no actual evidence that a host is healthy when a host is not be ejected. Because the host maybe just leave jail and haven't prove itself by processing enough traffic.

Comment (wbpcode) [reply source/common/upstream/outlier_detection_impl.cc:773]: cc @mattklein123 wdyt? I think you also take part in discussion in related issues.

Comment (wbpcode) [reply source/common/upstream/outlier_detection_impl.cc:773]: /wait-any

Comment (cpakulski) [reply source/common/upstream/outlier_detection_impl.cc:773]: > This is a reasonable change. There is no actual evidence that a host is healthy when a host is not be ejected. Because the host maybe just leave jail and haven't prove itself by processing enough traffic.

That is correct. Opposite to active HC, outlier is passive. Unless there is enough traffic to determine the node's state, the logic assumes that the node is healthy.

Thanks for reviewing!

Comment (mattklein123) [reply source/common/upstream/outlier_detection_impl.cc:773]: Yes this makes sense.

**Review by mattklein123 — APPROVED** [review]
LGTM, thanks!
