### PR TITLE
network: delayed conn close

### LINKED ISSUE #2929: http: not proxying 413 correctly
*Description*:
In the case envoy is proxying large HTTP request, even upstream returns 413, the client of proxy is getting 503.

*Repro steps*:
A sample envoy config is [here](https://gist.github.com/lizan/14fdcdebc332088eb03501dcbffdf48f).

```
$ curl -v http://127.0.0.1:8080 --data @envoy.log
> POST / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 28576635
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 413 Payload Too Large
< content-length: 17
< content-type: text/plain
< date: Thu, 29 Mar 2018 02:10:27 GMT
< server: envoy
< connection: close
<
* we are done reading and this is set to close, stop send
* Closing connection 0
```
is hitting directly to listener with buffer filter, results 413.

However,
```
curl -v http://127.0.0.1:8000 --data @envoy.log
> POST / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 28576635
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Thu, 29 Mar 2018 02:10:21 GMT
< server: envoy
< connection: close
<
```
will results 503, the port 8000 is proxying to 8080, which should return 413 too.

`envoy.log` above could be substitute with any large file (mine is 28MB), if you use smaller file (around 10K) which could fit in the TCP buffer, the port 8000 will return 413 correctly:

```
curl -v http://127.0.0.1:8000 --data @STYLE.md
> POST / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 11450
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 413 Payload Too Large
< content-length: 17
< content-type: text/plain
< date: Thu, 29 Mar 2018 02:15:29 GMT
< server: envoy
< x-envoy-upstream-service-time: 0
<
```

From the trace log below, it looks like when envoy write to upstream and it fails, it immediately result 503 without trying to read if the server already sent back the response.
```
[2018-03-28 19:02:10.131][23666][trace][http] source/common/http/http1/codec_impl.cc:322] [C1] parsed 1048576 bytes
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/connection_impl.cc:386] [C2] socket event: 2
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/connection_impl.cc:454] [C2] write ready
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/raw_buffer_socket.cc:67] [C2] write returns: 524288
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/raw_buffer_socket.cc:67] [C2] write returns: -1
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/raw_buffer_socket.cc:70] [C2] write error: 32 (Broken pipe)
[2018-03-28 19:02:10.131][23666][debug][connection] source/common/network/connection_impl.cc:134] [C2] closing socket: 0
[2018-03-28 19:02:10.131][23666][trace][http] source/common/http/http1/codec_impl.cc:305] [C2] parsing 0 bytes
[2018-03-28 19:02:10.131][23666][trace][http] source/common/http/http1/codec_impl.cc:322] [C2] parsed 0 bytes
[2018-03-28 19:02:10.131][23666][debug][client] source/common/http/codec_client.cc:81] [C2] disconnect. resetting 1 pending requests
[2018-03-28 19:02:10.131][23666][debug][client] source/common/http/codec_client.cc:104] [C2] request reset
[2018-03-28 19:02:10.131][23666][trace][main] source/common/event/dispatcher_impl.cc:126] item added to deferred deletion list (size=1)
[2018-03-28 19:02:10.131][23666][debug][router] source/common/router/router.cc:464] [C1][S12280405291311848063] upstream reset
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S12280405291311848063] encoding headers via codec (end_stream=false):
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   ':status':'503'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'content-length':'57'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'content-type':'text/plain'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'date':'Thu, 29 Mar 2018 02:02:10 GMT'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'server':'envoy'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'connection':'close'
[2018-03-28 19:02:10.132][23666][trace][connection] source/common/network/connection_impl.cc:323] [C1] writing 153 bytes, end_stream false
[2018-03-28 19:02:10.132][23666][trace][http] source/common/http/conn_manager_impl.cc:1031] [C1][S12280405291311848063] encoding data via codec (size=57 end_stream=true)
[2018-03-28 19:02:10.132][23666][trace][connection] source/common/network/connection_impl.cc:323] [C1] writing 57 bytes, end_stream false
```

Thanks @JimmyCYJ who originally find this with adding test in istio for #2919.

### PR DESCRIPTION
**Pull request by AndresGuedez**
network: Support delayed close of downstream conns (#2929)

Mitigate client read/close race issues on downstream HTTP connections by adding a new connection
close type 'FlushWriteAndDelay'. This new close type flushes the write buffer on a connection but
does not immediately close after emptying the buffer (unlike ConnectionCloseType::FlushWrite).

A timer has been added to track delayed closes for both 'FlushWrite' and 'FlushWriteAndDelay'. Upon
triggering, the socket will be closed and the connection will be cleaned up.

Delayed close processing can be disabled by setting the newly added HCM 'delayed_close_timeout'
config option to 0.

Risk Level: Medium (changes common case behavior for closing of downstream HTTP connections)
Testing: Unit tests and integration tests added.
Fixes #2929.

Signed-off-by: Andres Guedez <aguedez@google.com>

### CODE REVIEW

File: test/common/network/connection_impl_test.cc [hunk 1]
```diff
@@ -870,6 +887,173 @@ TEST_P(ConnectionImplTest, EmptyReadOnCloseTest) {
...
+// buffer is not flushed within the configured interval.
+TEST_P(ConnectionImplTest, FlushWriteCloseTimeoutTest) {
+  NiceMock<Event::MockDispatcher> dispatcher;
+  EXPECT_CALL(dispatcher.buffer_factory_, create_(_, _))
+      .WillRepeatedly(Invoke([](std::function<void()> below_low,
+                                std::function<void()> above_high) -> Buffer::Instance* {
+        return new Buffer::WatermarkBuffer(below_low, above_high);
+      }));
+
+  auto timer = new Event::MockTimer(&dispatcher);
```
Comment (dnoe) [inline test/common/network/connection_impl_test.cc]: Why can't we put these on the stack? They shouldn't be needed after the TEST_P body ends, right?

File: test/common/network/connection_impl_test.cc [hunk 2]
```diff
@@ -870,6 +887,173 @@ TEST_P(ConnectionImplTest, EmptyReadOnCloseTest) {
...
+  auto file_event = new NiceMock<Event::MockFileEvent>;
+  EXPECT_CALL(dispatcher, createFileEvent_(0, _, _, _)).WillOnce(Return(file_event));
+
+  auto transport_socket = new NiceMock<MockTransportSocket>;
+  EXPECT_CALL(*transport_socket, canFlushClose()).WillOnce(Return(true));
+
+  std::unique_ptr<Network::ConnectionImpl> server_connection(new Network::ConnectionImpl(
+      dispatcher, std::make_unique<ConnectionSocketImpl>(0, nullptr, nullptr),
+      TransportSocketPtr(transport_socket), true));
+  server_connection->setDelayedCloseTimeout(std::chrono::milliseconds(500));
```
Comment (dnoe) [inline test/common/network/connection_impl_test.cc]: Are we safe from flakes here?

File: test/common/network/connection_impl_test.cc [hunk 3]
```diff
@@ -870,6 +887,173 @@ TEST_P(ConnectionImplTest, EmptyReadOnCloseTest) {
...
+  server_connection_->close(ConnectionCloseType::FlushWriteAndDelay);
+  dispatcher_->run(Event::Dispatcher::RunType::Block);
+}
+
+// Test that a FlushWriteAndDelay close triggers a timeout which forces Envoy to close the
+// connection when a client has not issued a close within the configured interval.
+TEST_P(ConnectionImplTest, FlushWriteAndDelayCloseTimerTriggerTest) {
+  setUpBasicConnection();
+  connect();
+  server_connection_->setDelayedCloseTimeout(std::chrono::milliseconds(500));
```
Comment (dnoe) [inline test/common/network/connection_impl_test.cc]: Same question about flakes here. How do we know 500ms is the right number?

File: test/common/network/connection_impl_test.cc [hunk 4]
```diff
@@ -33,6 +33,7 @@ using testing::InSequence;
 using testing::Invoke;
 using testing::InvokeWithoutArgs;
 using testing::Return;
+using testing::ReturnNew;
```
Comment (dnoe) [inline test/common/network/connection_impl_test.cc]: Is this used?

File: test/integration/http2_integration_test.cc [hunk 5]
```diff
@@ -384,6 +384,63 @@ TEST_P(Http2IntegrationTest, SimultaneousRequestWithBufferLimits) {
...
+  RawConnectionDriver connection(
+      lookupPort("http"), buffer,
+      [&](Network::ClientConnection& connection, const Buffer::Instance& data) -> void {
+        response.append(data.toString());
+        connection.dispatcher().exit();
+      },
+      version_);
+
+  connection.run();
+  EXPECT_TRUE(response.find("SETTINGS expected") != std::string::npos);
```
Comment (dnoe) [inline test/integration/http2_integration_test.cc]: I find the form `EXPECT_THAT(response, HasSubstr("SETTINGS expected"))` more readable when trying to understand how the test works.

File: test/integration/http2_integration_test.cc [hunk 6]
```diff
@@ -384,6 +384,63 @@ TEST_P(Http2IntegrationTest, SimultaneousRequestWithBufferLimits) {
...
```
Comment (dnoe) [inline test/integration/http2_integration_test.cc]: Same here, the HasSubstr matcher will make this read nicely.

**Comment by AndresGuedez** [comment]
The CircleCI mac failure is due to the lack of early connection close detection in macOS (see #4299). Per the conversation in that issue, I am disabling the failing test on macOS.

File: api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto [hunk 7]
```diff
@@ -175,6 +175,17 @@ message HttpConnectionManager {
   // option is not specified.
   google.protobuf.Duration drain_timeout = 12 [(gogoproto.stdduration) = true];
 
+  // The delayed close timeout is for downstream connections managed by the HTTP connection manager.
+  // It is defined as a grace period after connection close processing has been locally initiated
+  // during which Envoy will flush the write buffers for the connection and await the peer to close
+  // the connection (i.e., issue a TCP FIN/RST).
```
Comment (lizan) [inline api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: In the case flush the write buffer and delay close, we should issue TCP FIN but not RST, the expected behavior is issue FIN after flush writing, and RST on timeout.

File: api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto [hunk 8]
```diff
@@ -175,6 +175,17 @@ message HttpConnectionManager {
...
+  //
+  // If the timeout triggers, Envoy will close the connection's socket.
+  //
+  // A value of 0 will completely disable delayed close processing, and the downstream connection's
+  // socket will be closed immediately after the write flush is completed.
+  google.protobuf.Duration delayed_close_timeout = 25 [(gogoproto.stdduration) = true];
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: There is a default timeout value of 1000 ms. I've amended the comment to note this.

File: include/envoy/network/connection.h [hunk 9]
```diff
@@ -63,7 +63,8 @@ class ConnectionCallbacks {
  */
 enum class ConnectionCloseType {
   FlushWrite, // Flush pending write data before raising ConnectionEvent::LocalClose
-  NoFlush     // Do not flush any pending data and immediately raise ConnectionEvent::LocalClose
+  NoFlush,    // Do not flush any pending data and immediately raise ConnectionEvent::LocalClose
+  FlushWriteAndDelay
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply include/envoy/network/connection.h]: Done.

File: source/common/network/connection_impl.cc [hunk 10]
```diff
@@ -106,10 +112,29 @@ void ConnectionImpl::close(ConnectionCloseType type) {
 
     closeSocket(ConnectionEvent::LocalClose);
   } else {
-    // TODO(mattklein123): We need a flush timer here. We might never get open socket window.
-    ASSERT(type == ConnectionCloseType::FlushWrite);
-    close_with_flush_ = true;
+    RELEASE_ASSERT(type == ConnectionCloseType::FlushWrite ||
+                       type == ConnectionCloseType::FlushWriteAndDelay,
+                   "");
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: I'm using the RELEASE_ASSERT to provide runtime protection against bugs introduced in this logic, since they could lead to issues such as resource leaks and/or memory corruption.

I just re-read the style guide and it does mention that ASSERT should be the common case for this type of check, so I can certainly change it if that's the convention.

File: source/common/network/connection_impl.cc [hunk 11]
```diff
@@ -106,10 +112,29 @@ void ConnectionImpl::close(ConnectionCloseType type) {
...
+    delayed_close_ = true;
+    bool delayed_close_timeout_set = delayedCloseTimeout().count();
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Done.

File: source/common/network/connection_impl.cc [hunk 12]
```diff
@@ -106,10 +112,29 @@ void ConnectionImpl::close(ConnectionCloseType type) {
...
+
+    // All close types that follow do not actually close() the socket immediately so that buffered
+    // data can be written. However, we do want to stop reading to apply TCP backpressure.
     read_enabled_ = false;
+
+    // Force a closeSocket() after the write buffer is flushed if the close_type calls for it or if
+    // no delayed close timeout is set.
+    close_after_flush_ = type == ConnectionCloseType::FlushWrite || !delayed_close_timeout_set;
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Done.

File: source/extensions/filters/network/http_connection_manager/config.cc [hunk 13]
```diff
@@ -136,7 +136,8 @@ HttpConnectionManagerConfig::HttpConnectionManagerConfig(
       date_provider_(date_provider),
       listener_stats_(Http::ConnectionManagerImpl::generateListenerStats(stats_prefix_,
                                                                          context_.listenerScope())),
-      proxy_100_continue_(config.proxy_100_continue()) {
+      proxy_100_continue_(config.proxy_100_continue()),
+      delayed_close_timeout_(PROTOBUF_GET_MS_OR_DEFAULT(config, delayed_close_timeout, 1000)) {
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/extensions/filters/network/http_connection_manager/config.cc]: Done.

File: test/common/network/connection_impl_test.cc [hunk 14]
```diff
@@ -870,6 +887,173 @@ TEST_P(ConnectionImplTest, EmptyReadOnCloseTest) {
   disconnect(true);
 }
 
+// Test that a FlushWrite close immediately triggers a close after the write buffer is flushed.
+TEST_P(ConnectionImplTest, FlushWriteCloseTest) {
+  setUpBasicConnection();
+  connect();
+  // Set a very high timeout value to prevent flaking. We are testing the common case where the
+  // timeout does not trigger.
+  server_connection_->setDelayedCloseTimeout(std::chrono::milliseconds(50000));
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply test/common/network/connection_impl_test.cc]: Thanks for the tip. I'm doing local flake detection with --runs_per_test and will be checking CI builds as part of this PR and post-merge to make sure this timeout is long enough.

File: test/common/network/connection_impl_test.cc (hunk 1 above)
Comment (AndresGuedez) [reply test/common/network/connection_impl_test.cc]: The WatermarkBuffer and MockTimer need to be allocated on the free store because ownership is handed over to Envoy::Network::ConnectionImpl when Envoy::MockBufferFactory::create() and Envoy::Event::MockDispatcher::createTimer() are called (respectively).

File: test/common/network/connection_impl_test.cc (hunk 4 above)
Comment (AndresGuedez) [reply test/common/network/connection_impl_test.cc]: Removed.

File: test/integration/http2_integration_test.cc (hunk 5 above)
Comment (AndresGuedez) [reply test/integration/http2_integration_test.cc]: Thanks for pointing out the matcher. Done.

File: test/integration/http2_integration_test.cc (hunk 6 above)
Comment (AndresGuedez) [reply test/integration/http2_integration_test.cc]: Done.

File: test/common/network/connection_impl_test.cc (hunk 2 above)
Comment (AndresGuedez) [reply test/common/network/connection_impl_test.cc]: Yes. The timer's callback is manually invoked at the end of the test. The 'setDelayedCloseTimeout()'  call is required to enable creation of the timer, but the actual value does not matter (as long as it's >0). I've added a clarifying comment.

File: test/common/network/connection_impl_test.cc (hunk 3 above)
Comment (AndresGuedez) [reply test/common/network/connection_impl_test.cc]: This is safe. Since the client connection does not issue a close() during this test, the timer always triggers. I've added a clarifying comment and reduced the timeout value since there is no need to wait so long.

File: test/common/network/connection_impl_test.cc (hunk 1 above)
Comment (dnoe) [reply test/common/network/connection_impl_test.cc]: That explanation makes sense. I get nervous when I see bare new calls, especially without a comment. I think this test might be doing the opposite of the pattern I usually see, which is to have a `unique_ptr` here in the test body which is `std::move`d into the right place to be returned by `Envoy::MockBufferFactory::create()` but only after you steal a bare pointer out of the `unique_ptr` to use when setting up any the gmock expectations. This is a clear case of dangerous cheating the `unique_ptr`, but it's ok in this limited test case example since we know the unique pointer scope lives as long as the body of this test. I think it leaves the object life cycle a bit clearer defined than if you don't use `unique_ptr` here.

If this doesn't work in your case, please add a comment explaining the object lifecycle at the bare `new`s. Happy to chat more about this in person tomorrow too if it helps.

File: .circleci/config.yml [hunk 15]
```diff
@@ -10,7 +10,6 @@ jobs:
      resource_class: xlarge
      working_directory: /source
      environment:
-       BAZEL_REMOTE_CACHE: https://storage.googleapis.com/envoy-circleci-bazel-cache/
```
[the remark this answers is not in the document]
Comment (lizan) [reply .circleci/config.yml]: #4407

File: source/common/network/connection_impl.cc [hunk 16]
```diff
@@ -106,10 +112,29 @@ void ConnectionImpl::close(ConnectionCloseType type) {
...
+
+    // Create and activate a timer which will immediately close the connection if triggered.
+    // A config value of 0 disables the timeout.
+    if (delayed_close_timeout_set) {
+      delayed_close_timer_ = dispatcher_.createTimer([this]() -> void { onDelayedCloseTimeout(); });
+      ENVOY_CONN_LOG(debug, "setting delayed close timer with timeout {}", *this,
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Done.

File: source/common/network/connection_impl.cc (hunk 10 above)
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Changed to ASSERT() per style guidelines.

**Comment by AndresGuedez** [comment]
@dnoe -- thanks for the review!

File: test/integration/http_integration.cc [hunk 17]
```diff
@@ -149,18 +149,36 @@ IntegrationCodecClient::startRequest(const Http::HeaderMap& headers) {
...
+      wait_timer_triggered = true;
+    });
+    wait_timer->enableTimer(std::chrono::milliseconds(time_to_wait));
+  }
+
   connection_->dispatcher().run(Event::Dispatcher::RunType::Block);
+  if (wait_timer_triggered && !disconnected_) {
+    return false;
+  }
   EXPECT_TRUE(disconnected_);
```
Comment (zuercher) [inline test/integration/http_integration.cc]: Should disable the timer if it hasn't fired.

File: test/integration/integration_test.cc [hunk 18]
```diff
@@ -364,4 +364,111 @@ TEST_P(IntegrationTest, ViaAppendWith100Continue) {
...
+                                                          {":scheme", "http"},
+                                                          {":authority", "host"}});
+  request_encoder_ = &encoder_decoder.first;
+  auto response = std::move(encoder_decoder.second);
+
+  codec_client_->sendData(*request_encoder_, 1024 * 65, false);
+
+  response->waitForEndStream();
+  // The delayed close timeout should trigger since client is not closing the connection.
+  EXPECT_TRUE(codec_client_->waitForDisconnect(750));
```
Comment (zuercher) [inline test/integration/integration_test.cc]: Have you given this the runs_per_test treatment?

File: include/envoy/network/connection.h [hunk 19]
```diff
@@ -86,6 +88,8 @@ class Connection : public Event::DeferredDeletable, public FilterManager {
     Stats::Gauge& write_current_;
     // Counter* as this is an optional counter. Bind errors will not be tracked if this is nullptr.
     Stats::Counter* bind_errors_;
+    // Optional counter. Delayed close semantics are only used by HTTP connections.
+    Stats::Counter* delayed_close_timeouts_;
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply include/envoy/network/connection.h]: Agreed the delayed close timeout is not inherently HTTP specific, but the intent of the comment is to point out that _as currently implemented_ it only affects HTTP connections, since the H{1,2} codecs are the only callers of `setDelayedCloseTimeout()` on a connection to enable it.

I'm fine removing this however if you don't think the note/clarification is required.

File: test/common/network/connection_impl_test.cc [hunk 20]
```diff
@@ -1251,8 +1449,8 @@ class ReadBufferLimitTest : public ConnectionImplTest {
     Buffer::OwnedImpl data(std::string(buffer_size, 'a'));
     client_connection_->write(data, false);
     dispatcher_->run(Event::Dispatcher::RunType::Block);
-  }
-};
+  } // namespace Network
+};  // namespace Envoy
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply test/common/network/connection_impl_test.cc]: tools/check_format.py fails when this is reverted -- 'FixNamespaceComments' appears to be required.

File: source/common/network/connection_impl.cc [hunk 21]
```diff
@@ -106,10 +112,28 @@ void ConnectionImpl::close(ConnectionCloseType type) {
...
+    close_after_flush_ = !delayed_close_timeout_set || type == ConnectionCloseType::FlushWrite;
+
+    // Create and activate a timer which will immediately close the connection if triggered.
+    // A config value of 0 disables the timeout.
+    if (delayed_close_timeout_set) {
+      delayed_close_timer_ = dispatcher_.createTimer([this]() -> void { onDelayedCloseTimeout(); });
+      ENVOY_CONN_LOG(debug, "setting delayed close timer with timeout {} ms", *this,
+                     delayedCloseTimeout().count());
+      delayed_close_timer_->enableTimer(delayedCloseTimeout());
+    }
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: 1. Yes, I am addressing an outstanding `TODO(mattklein123)` to create a timer to terminate the connection if the flush never completes.  It is possible that `closeSocket(LocalClose)` will be called twice if the timer event has fired when the write flush completes, but the second call returns immediately due to the `if (fd() == -1)` check.

2. I am adding a runtime check to avoid processing a delayed close request twice, since it does seem to be possible for `close()` to be called multiple times with FlushWrite/FlushWriteAndDelay based on tests I just ran.

File: include/envoy/network/connection.h (hunk 19 above)
[the remark this answers is not in the document]
Comment (zuercher) [reply include/envoy/network/connection.h]: My feeling is that it's just a comment we'll have to delete (or will be incorrect) when someone inevitably enables this for a different purpose.

File: test/common/network/connection_impl_test.cc (hunk 20 above)
[the remark this answers is not in the document]
Comment (zuercher) [reply test/common/network/connection_impl_test.cc]: I downloaded this file and it seems to pass format checks locally without the stray namespace comments. Has it failed CI's format check?

File: include/envoy/network/connection.h (hunk 19 above)
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply include/envoy/network/connection.h]: Ok. Cleaned up the comment.

File: source/common/network/connection_impl.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Done.

File: source/common/network/connection_impl.cc [hunk 22]
```diff
@@ -535,6 +559,13 @@ bool ConnectionImpl::bothSidesHalfClosed() {
   return read_end_stream_ && write_end_stream_ && write_buffer_->length() == 0;
 }
 
+void ConnectionImpl::onDelayedCloseTimeout() {
+  ENVOY_CONN_LOG(debug, "triggered delayed close", *this);
+  ASSERT(connection_stats_->delayed_close_timeouts_);
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Done.

File: source/common/network/connection_impl.cc [hunk 23]
```diff
@@ -70,6 +70,12 @@ ConnectionImpl::ConnectionImpl(Event::Dispatcher& dispatcher, ConnectionSocketPt
 ConnectionImpl::~ConnectionImpl() {
   ASSERT(fd() == -1, "ConnectionImpl was unexpectedly torn down without being closed.");
 
+  if (delayed_close_timer_) {
+    // It's ok to disable even if the timer has already fired.
+    delayed_close_timer_->disableTimer();
+    delayed_close_timer_.reset();
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Done.

File: test/integration/http_integration.cc [hunk 24]
```diff
@@ -149,18 +149,36 @@ IntegrationCodecClient::startRequest(const Http::HeaderMap& headers) {
   return {encoder, std::move(response)};
 }
 
-void IntegrationCodecClient::waitForDisconnect() {
+bool IntegrationCodecClient::waitForDisconnect(uint32_t time_to_wait) {
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply test/integration/http_integration.cc]: Done.

File: test/integration/http_integration.cc (hunk 17 above)
Comment (AndresGuedez) [reply test/integration/http_integration.cc]: Done.

File: test/integration/integration_test.cc (hunk 18 above)
Comment (AndresGuedez) [reply test/integration/integration_test.cc]: Yeah, I've done extensive flake testing and did not hit any issues. I've adjusted the timeouts though to make it even more resistant since the CI environment is considerably more flake prone than my machine.

File: test/common/network/connection_impl_test.cc (hunk 20 above)
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply test/common/network/connection_impl_test.cc]: Reverted comments. I was looking at the wrong lines... Thanks.

File: source/common/network/connection_impl.cc [hunk 25]
```diff
@@ -128,6 +141,7 @@ void ConnectionImpl::close(ConnectionCloseType type) {
     // Create and activate a timer which will immediately close the connection if triggered.
     // A config value of 0 disables the timeout.
     if (delayed_close_timeout_set) {
+      ASSERT(connection_stats_->delayed_close_timeouts_ != nullptr);
```
Comment (zuercher) [inline source/common/network/connection_impl.cc]: Sorry, I meant in setDelayedCloseTimeout.I don't want someone to enable this feature on a connection and then only later get an assertion about this stat.

Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: `connection_stats_` is set via `setConnectionStats()`, so asserting on the counter != nullptr in `setDelayedCloseTimeout()` will introduce an ordering dependency (which is not currently met). I think it would be preferable to keep these two functions independent of each other.

Unfortunately, initialization of `ConnectionImpl`s is spread out between codec creation (allocation and call to `setDelayedCloseTimeout`) and `ConnectionManagerImpl::initializeReadFilterCallbacks()` where `setConnectionStats()` is called. Therefore, adding an `initFinished()` function where the ASSERT could be safely issued will require some work.

I can mark this with a TODO so we can move it into the appropriate place when such a function is added. What do you think?

Comment (zuercher) [reply source/common/network/connection_impl.cc]: Or just make setting connection_state_->delayed_close_timeouts_ optional? (E.g. don't assert, just don't increment if it's null?)

Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Ok, done.

File: .circleci/config.yml (hunk 15 above)
Comment (ggreenway) [inline .circleci/config.yml]: Let's revert these; if we are going to disable the cache, it should be a separate PR.

File: api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto [hunk 26]
```diff
@@ -175,6 +175,19 @@ message HttpConnectionManager {
   // option is not specified.
   google.protobuf.Duration drain_timeout = 12 [(gogoproto.stdduration) = true];
 
+  // The delayed close timeout is for downstream connections managed by the HTTP connection manager.
```
Comment (ggreenway) [inline api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: I'd like to see some documentation on why one would change this setting. It's talked about in the linked issue, but from just reading this documentation, I wouldn't know what could go wrong if I change this setting to 0/disabled here.

**Comment by zuercher** [comment]
This failed with a timeout in the SDS integration test. Can you check if your branch has c4211b3195c885a1547070f02acdea0eb88e316a (which was supposed to fix the timeout).

**Comment by AndresGuedez** [comment]
> This failed with a timeout in the SDS integration test. Can you check if your branch has [c4211b3](https://github.com/envoyproxy/envoy/commit/c4211b3195c885a1547070f02acdea0eb88e316a) (which was supposed to fix the timeout).

I don't have that commit in my branch; I'll merge and kick off new CI runs.

**Comment by ggreenway** [comment]
@mattklein123 Please take a look.

File: source/common/http/http1/codec_impl.cc [hunk 27]
```diff
@@ -450,8 +450,11 @@ void ConnectionImpl::onResetStreamBase(StreamResetReason reason) {
 
 ServerConnectionImpl::ServerConnectionImpl(Network::Connection& connection,
                                            ServerConnectionCallbacks& callbacks,
-                                           Http1Settings settings)
-    : ConnectionImpl(connection, HTTP_REQUEST), callbacks_(callbacks), codec_settings_(settings) {}
+                                           Http1Settings settings,
+                                           std::chrono::milliseconds delayed_close_timeout)
+    : ConnectionImpl(connection, HTTP_REQUEST), callbacks_(callbacks), codec_settings_(settings) {
+  connection_.setDelayedCloseTimeout(delayed_close_timeout);
```
Comment (mattklein123) [inline source/common/http/http1/codec_impl.cc]: What's the reasoning for doing this set in the codec? It seems like something that is unrelated to the codec itself and should be done by higher layer code? Same question for the HTTP/2 codec below.

File: source/common/network/connection_impl.cc [hunk 28]
```diff
@@ -106,10 +111,42 @@ void ConnectionImpl::close(ConnectionCloseType type) {
...
   } else {
-    // TODO(mattklein123): We need a flush timer here. We might never get open socket window.
-    ASSERT(type == ConnectionCloseType::FlushWrite);
-    close_with_flush_ = true;
+    ASSERT(type == ConnectionCloseType::FlushWrite ||
+           type == ConnectionCloseType::FlushWriteAndDelay);
+
+    // No need to continue if a FlushWrite/FlushWriteAndDelay has already been issued and there is a
+    // pending delayed close.
+    if (delayed_close_) {
```
Comment (mattklein123) [inline source/common/network/connection_impl.cc]: Does this happen in practice? Mostly just wondering about the flow that causes this. Perhaps flesh out the comment with some examples of cases where this happens?

File: source/common/network/connection_impl.cc [hunk 29]
```diff
@@ -106,10 +111,42 @@ void ConnectionImpl::close(ConnectionCloseType type) {
...
+      return;
+    }
+
+    delayed_close_ = true;
+    bool delayed_close_timeout_set = delayedCloseTimeout().count() > 0;
```
Comment (mattklein123) [inline source/common/network/connection_impl.cc]: nit: const

Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Done.

File: source/common/network/connection_impl.cc (hunk 28 above)
Comment (AndresGuedez) [reply source/common/network/connection_impl.cc]: Yes, I initially tried an ASSERT() which triggered in multiple tests during a //test/... run. I just tracked down a failure during an integration_test and added it to the comment. Based on that example and code inspection, this conditional can evaluate true under fairly standard use cases such as when Envoy initiates the close() sequence during codec processing.

File: source/common/http/http1/codec_impl.cc (hunk 27 above)
Comment (AndresGuedez) [reply source/common/http/http1/codec_impl.cc]: It's not related to the codec directly but this particular delayed_close_timeout is HTTP only since it is managed via the HCM configuration. This seemed to be the most appropriate place to set the timeout for HTTP connections just after they are constructed.

Since the timeout value is intended to be network filter specific, I wouldn't expect any layer higher than the corresponding filter to issue the call to setDelayedCloseTimeout().

Comment (mattklein123) [reply source/common/http/http1/codec_impl.cc]: I agree it should be done in the filter. Why not do it in the HCM filter and avoid codec modifications?

Comment (AndresGuedez) [reply source/common/http/http1/codec_impl.cc]: Agreed it's best to contain it within the HCM. I revisited the code and moved setting the timeout to the HCM config.

File: source/extensions/filters/network/http_connection_manager/config.cc [hunk 30]
```diff
@@ -301,6 +302,7 @@ Http::ServerConnectionPtr
 HttpConnectionManagerConfig::createCodec(Network::Connection& connection,
                                          const Buffer::Instance& data,
                                          Http::ServerConnectionCallbacks& callbacks) {
+  connection.setDelayedCloseTimeout(delayed_close_timeout_);
```
[the remark this answers is not in the document]
Comment (AndresGuedez) [reply source/extensions/filters/network/http_connection_manager/config.cc]: Done.

File: api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto [hunk 31]
```diff
@@ -175,6 +175,25 @@ message HttpConnectionManager {
...
+  // write(). This race leads to such clients failing to process the response code sent by Envoy,
+  // which could result in erroneous downstream processing.
+  //
+  // If the timeout triggers, Envoy will close the connection's socket.
+  //
+  // The default timeout is 1000 ms if this option is not specified.
+  //
+  // A value of 0 will completely disable delayed close processing, and the downstream connection's
+  // socket will be closed immediately after the write flush is completed.
+  google.protobuf.Duration delayed_close_timeout = 26 [(gogoproto.stdduration) = true];
```
Comment (mattklein123) [inline api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: Sorry I forget this from before. Can you add this to the release notes also with a link to this field?

Comment (AndresGuedez) [reply api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: Done.

**Comment by AndresGuedez** [comment]
@mattklein123 Thanks for the review!
