### PR TITLE
sds: add ability to reload TLS session ticket keys

### LINKED ISSUE #7397: Finish implementation of TLS Session Ticket keys delivery via SDS
Currently TLS Session Tickets can only be configured as `DataSource` which limits them to inline string/bytes or individual files.  This type of setup requires a restart of envoy to rotate the keys.  The API already has a provision to pull them from SDS, albeit currently stubbed out.  Further, trying to configure SDS for tickets throws an explicit "SDS not supported" error.

Please consider fully implementing SDS for TLS session ticket keys.

api stub: https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/auth/cert.proto#L357-L358
exception: https://github.com/envoyproxy/envoy/blob/master/source/extensions/transport_sockets/tls/context_config_impl.cc#L351-L353

### PR DESCRIPTION
**Pull request by euroelessar**
Description: Finish migration of TLS session ticket keys to provider-based API.
Risk Level: Medium
Testing: added new tests
Docs Changes: updated
Release Notes: updated
Fixes #7397

### CODE REVIEW

File: source/extensions/transport_sockets/tls/context_config_impl.cc [hunk 1]
```diff
@@ -327,27 +363,22 @@ ServerContextConfigImpl::ServerContextConfigImpl(
...
-        default:
-          throw EnvoyException(fmt::format("Unexpected case for oneof session_ticket_keys: {}",
-                                           config.session_ticket_keys_type_case()));
-        }
-
-        return ret;
-      }()) {
+      session_ticket_keys_provider_(getTlsSessionTicketKeysConfigProvider(
+          factory_context, config, &session_ticket_keys_dynamic_sds_)) {
+  if (session_ticket_keys_provider_ != nullptr && session_ticket_keys_dynamic_sds_) {
```
Comment (lizan) [inline source/extensions/transport_sockets/tls/context_config_impl.cc]: Seems session_ticket_keys_dynamic_sds_ only used here? Can you just pass the validation callback to `getTlsSessionTicketKeysConfigProvider` so it can be added when it is needed?
