### PR TITLE
test: fix use after free in oauth_integration_test

### LINKED ISSUE #12960: Test flake in OauthIntegrationTest.UnauthenticatedFlow
In a CI coverage run for another PR, a flake was caught in OauthIntegrationTest.UnauthenticatedFlow
which I haven't been able to reproduce locally using O(10k) repetitions. Possibly something
that coverage does, like adding pressure on certain system resources, is needed to tease the issue
out.

Relevant CI log: https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/50172/logs/98

### PR DESCRIPTION
**Pull request by antoniovicente**
Commit Message:
test: fix use after free in oauth_integration_test

The client request stream can be deleted under the call stack of Envoy::IntegrationCodecClient::startRequest if the proxy replies quickly enough. Attempts to send an end stream on that request result in use-after-free on the client stream in cases where the client processed the full reply inside startRequest.
Additional Description:
Risk Level: n/a test-only
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Fixes #12960

### CODE REVIEW

**Review by rgs1 — APPROVED** [review]
Thanks!

File: test/extensions/filters/http/oauth2/oauth_integration_test.cc [hunk 1]
```diff
@@ -91,8 +91,6 @@ TEST_F(OauthIntegrationTest, UnauthenticatedFlow) {
                                          {":authority", "authority"}};
   auto encoder_decoder = codec_client_->startRequest(headers);
 
-  Buffer::OwnedImpl buffer;
```
Comment (mattklein123) [inline test/extensions/filters/http/oauth2/oauth_integration_test.cc:94]: I actually wonder if responding before the request is complete (since this is effectively what is tested now) is going to break some clients who don't handle this well? Unrelated to this test fix but maybe something to think about in the future. cc @rgs1.

**Review by mattklein123 — APPROVED** [review]
Awesome, thanks for debugging and fixing.

File: test/extensions/filters/http/oauth2/oauth_integration_test.cc (hunk 1 above)
Comment (rgs1) [reply test/extensions/filters/http/oauth2/oauth_integration_test.cc:94]: Shall we add the above as a note?

Comment (mattklein123) [reply test/extensions/filters/http/oauth2/oauth_integration_test.cc:94]: Yeah it might be worth it to document this somewhere but up to you all as whether to do it in here or a follow up, etc.

Comment (antoniovicente) [reply test/extensions/filters/http/oauth2/oauth_integration_test.cc:94]: I think this is generic H2 behavior.  The proxy does have fully request headers for the GET by the time it replies.  I'll make a note to try to look at the more general issue in test frameworks.

Comment (mattklein123) [reply test/extensions/filters/http/oauth2/oauth_integration_test.cc:94]: Sorry I know it's correct/generic behavior, I was just suggesting that I can envision some clients not dealing with this well so we should keep that in mind for future support queries.

**Comment by cpakulski** [comment]
Backported to rel 1.16. Releases 1.13-1.15 do not have oauth_integration_test and are not affected.
Removing backport/approved label.
