### PR TITLE
rds: normalize rds provider's config before calculating hash

### LINKED ISSUE #32283: Envoy does not use previously sent RouteConfiguration when initial_fetch_timeout value is changed inside Rds config
*Title*: *Envoy does not use previously sent RouteConfiguration when initial_fetch_timeout value is changed inside Rds config*

*Description*:

 Based on [Resource warming](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol.html#resource-warming) section on the envoy documentation, envoy is expected to use the previously sent `RouteConfiguration` while warming up a `Listener` and management does not need to send the `RouteConfiguration` if there is no change. However, when a field inside `Rds` field in the `Listener`, including [`initial_fetch_timeout`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/config_source.proto#envoy-v3-api-msg-config-core-v3-configsource) field, is changed in a `Listener`, Envoy does not use the previously sent `RouteConfiguration` and wait for management server for the `RouteConfiguration`. 

  This can cause Envoy to time out while waiting for the `RouteConfiguration`, and finishes `Listener` warming without the `RouteConfiguration`. Once a `Listener` is warmed up without `RouteCofiguration`, Envoy responds to requests to the route with 404(NR) responses until it is restarted or the `RouteConfiguration` is updated and management server sends the updated `RouteConfiguration` to Envoy.

 This happens because Envoy does not use `existing_provider` in https://github.com/envoyproxy/envoy/blob/v1.26.6/source/common/rds/route_config_provider_manager.cc#L82 if the hash value of rds configuration changes which prevents Envoy from using previously sent `RouteConfiguration`

 Can we update Envoy to use `existing_provider` when `initial_fetch_timeout` value is changed? Although we do not need to change it often, we sometimes need to change the value, and we want to avoid restarting envoy proxies whenever we need to update `initial_fetch_timeout` value.

*Repro steps*:

This can be reproduced by running an envoy proxy that uses ADS to fetch configurations from a management server, and change initial_fetch_timeout value in ConfigSource in a listener. I have a simple management server to reproduce the issue, and can provide it if helps.

### PR DESCRIPTION
**Pull request by cpakulski**
Additional Description:
RDS provider manager identifies different providers by hashing their config. If the hash is different than already known to the provider manager, it is assumed that provider changed. But some parameters in the provider's config, namely `initial_fetch_timeout`, does not define a new rds provider and therefore should not be taken into account when RDS provider manager checks (by hashing) if such provider is already known and should be reused. More info in #32283.

Risk Level: Low
Testing: Adjusted unit tests.
Docs Changes: No
Release Notes: Yes
Platform Specific Features: No
Runtime guard: envoy.reloadable_features.normalize_rds_provider_config
Fixes #32283

### CODE REVIEW

File: source/common/router/rds_impl.cc [hunk 1]
```diff
@@ -180,8 +180,21 @@ RouteConfigProviderSharedPtr RdsFactoryImpl::createRdsRouteConfigProvider(
     Server::Configuration::ServerFactoryContext& factory_context, const std::string& stat_prefix,
     Init::Manager& init_manager, ProtoTraitsImpl& proto_traits,
     Rds::RouteConfigProviderManager& manager) {
+  envoy::extensions::filters::network::http_connection_manager::v3::Rds normalized_rds;
+  if (Runtime::runtimeFeatureEnabled("envoy.reloadable_features.normalize_rds_provider_config")) {
```
Comment (adisuissa) [inline source/common/router/rds_impl.cc:184]: I think it makes more sense to have this functionality in [addDynamicProvider](https://github.com/envoyproxy/envoy/blob/868d371518cceaf867d13d567d42b1c39d999fe2/source/common/rds/route_config_provider_manager.cc#L78). This way other uses of the same function will also benefit from the fix.

File: source/common/router/rds_impl.cc [hunk 2]
```diff
@@ -180,8 +180,21 @@ RouteConfigProviderSharedPtr RdsFactoryImpl::createRdsRouteConfigProvider(
...
+    normalized_rds = rds;
+    // Normalization clears RDS providers's parameters which are not important
+    // for actual fetching of routes. When one of those "not important" parameters is changed,
+    // the existing provider should be chosen.
+    // TODO(cpakulski): Consider adding RdsFactoryImpl::normalizeRdsConfigProvider method, if more
+    // fields needs to be cleared.
+    normalized_rds.mutable_config_source()->clear_initial_fetch_timeout();
```
Comment (adisuissa) [inline source/common/router/rds_impl.cc:191]: I wonder what's the performance penalty of this approach compared to moving out the `initial_fetch_timeout` and moving it back in after the operation.

Not sure if it's worth breaking the constness, but just wanted to think out loud with you.

**Review by adisuissa — COMMENTED** [review]
Thanks for fixing this, and for adding the runtime flag!
Left minor comments.

File: source/common/router/rds_impl.cc (hunk 1 above)
Comment (cpakulski) [reply source/common/router/rds_impl.cc:184]: That was my initial idea, but [addDynamicProvider](https://github.com/envoyproxy/envoy/blob/868d371518cceaf867d13d567d42b1c39d999fe2/source/common/rds/route_config_provider_manager.cc#L78) takes `const Protobuf::Message& rds` as argument, so I have to either change the signature of `addDynamicProvider` or cast/convert the first parameter `rds` to `envoy::extensions::filters::network::http_connection_manager::v3::Rds` in order to access `initial_fetch_timeout` field.

But I agree with you that this would be better. Let me try it again. I was not super familiar with that code when I tried it first time, so maybe now it will be easier to do.

File: source/common/router/rds_impl.cc (hunk 2 above)
Comment (cpakulski) [reply source/common/router/rds_impl.cc:191]: I had the same dilemma. As you noted above, originally I just wanted to save the field, clear it, calculate hash and restore the value, but constness does not allow to do that, so I came up with copy. The thing is that the caller of `RdsFactoryImpl::createRdsRouteConfigProvider` also takes proto as const, so there are at least 2 levels of function calls (maybe even more) which needs to be changed to eliminate const attribute.

As per performance, in my opinion, the proto message is rather small, as it contains only where to take the routes from, not the routes itself.

I am sure that if I write the microbenchmark, results will point to some degradation of performance, but I also believe that rds updates are not happening all that often.

File: test/common/router/rds_impl_test.cc [hunk 3]
```diff
@@ -962,6 +962,14 @@ name: foo_route_config
                   ->onConfigUpdate(decoded_resources.refvec_, "1")
                   .ok());
 
+  envoy::extensions::filters::network::http_connection_manager::v3::Rds rds2;
```
[the remark this answers is not in the document]
Comment (cpakulski) [reply test/common/router/rds_impl_test.cc:965]: OK. Let me add separate test.

File: source/common/router/rds_impl.cc (hunk 1 above)
Comment (cpakulski) [reply source/common/router/rds_impl.cc]: Moved the "normalization" to addDynamicProvider. I had to use reflection to find the right fields. The only assumption is that whatever dynamic config is passed, it must contain `config_source` field. If it does not, runtime assert will fail. Fortunately all components which use dynamic rds providers (generic_proxy, thrift_proxy and dubbo_proxy) have `config_source`. New components added in the future will have to use the same schema. I added a long comment next to assertion, so when it fails it will be easy to correct.

File: source/common/router/rds_impl.cc (hunk 2 above)
Comment (cpakulski) [reply source/common/router/rds_impl.cc]: Reverted this change to original code.

File: test/common/router/rds_impl_test.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (cpakulski) [reply test/common/router/rds_impl_test.cc]: Added extra test.

File: source/common/rds/route_config_provider_manager.cc [hunk 4]
```diff
@@ -80,8 +81,39 @@ RouteConfigProviderSharedPtr RouteConfigProviderManager::addDynamicProvider(
     std::function<
         std::pair<RouteConfigProviderSharedPtr, const Init::Target*>(uint64_t manager_identifier)>
         create_dynamic_provider) {
+
   // RdsRouteConfigSubscriptions are unique based on their serialized RDS config.
-  const uint64_t manager_identifier = MessageUtil::hash(rds);
+  uint64_t manager_identifier;
+  if (Runtime::runtimeFeatureEnabled("envoy.reloadable_features.normalize_rds_provider_config")) {
+    Protobuf::ReflectableMessage reflectable_message = createReflectableMessage(rds);
```
Comment (adisuissa) [inline source/common/rds/route_config_provider_manager.cc:88]: If it is possible to change the method signature so it will be a templated method (for the `rds` argument), I think it will get around the reflection and the code will be able to access the `config_source` field directly.

Comment (cpakulski) [reply source/common/rds/route_config_provider_manager.cc:88]: Yes, it is possible. But in order to "reset" initial_fetch_timeout, I will need to make a copy of entire config (as it was done before trying reflection). But I guess it is better than removing constness across multiple levels of calls. I will push template version soon. Thanks for great idea.

Comment (adisuissa) [reply source/common/rds/route_config_provider_manager.cc:88]: IMHO removing the costness is OK (as long as the function also reinstates the removed timeout), but the reflection is less desirable.

Comment (cpakulski) [reply source/common/rds/route_config_provider_manager.cc:88]: I was not sure how expensive reflection is. I have working template version now. Let me see how much I have to change to remove constness.

Comment (cpakulski) [reply source/common/rds/route_config_provider_manager.cc]: I used `const_cast` to take away constness in the templated method.

File: source/common/rds/route_config_provider_manager.h [hunk 5]
```diff
@@ -34,12 +35,43 @@ class RouteConfigProviderManager {
 
   RouteConfigProviderPtr
   addStaticProvider(std::function<RouteConfigProviderPtr()> create_static_provider);
+
+  template <class RdsConfig>
   RouteConfigProviderSharedPtr
-  addDynamicProvider(const Protobuf::Message& rds, const std::string& route_config_name,
+  addDynamicProvider(const RdsConfig& rds, const std::string& route_config_name,
```
Comment (adisuissa) [inline source/common/rds/route_config_provider_manager.h:41]: nit: it may be better to keep the method implementation in the .cc file.
If linking is an issue, it may be solved by explicitly stating the instances that are supported ([an example](https://github.com/envoyproxy/envoy/blob/e456b9ba7683a09cea7a7f2af6d3a5a5c2ac10a6/source/extensions/config_subscription/grpc/xds_mux/grpc_mux_impl.cc#L451-L456) that does this for templated classes, I'm assuming that templated functions are similar).

**Review by adisuissa — COMMENTED** [review]
Thanks! Overall LGTM!
Left one nit.
/assign-from @envoyproxy/senior-maintainers

File: source/common/rds/route_config_provider_manager.h (hunk 5 above)
Comment (cpakulski) [reply source/common/rds/route_config_provider_manager.h:41]: @adisuissa I tried to move the templated method implementation back to .cc file, but run into some problems. 
In order to do explicit function template instantiation, the template definition must be visible from the place when explicit template instantiation happens. Since the template definition is moved back to source/common/rds/route_config_provider_manager.cc file, the explicit function instantiation must happen at the same file. It means that I would have to import protos of all rds configs which I know use addDynamicProvider (router, thrift, dubbo and maybe few more from contrib - did not check). To be honest I am not sure if this makes sense. Notice that in [the example](https://github.com/envoyproxy/envoy/blob/e456b9ba7683a09cea7a7f2af6d3a5a5c2ac10a6/source/extensions/config_subscription/grpc/xds_mux/grpc_mux_impl.cc#L451-L456), [method template definition](https://github.com/envoyproxy/envoy/blob/e456b9ba7683a09cea7a7f2af6d3a5a5c2ac10a6/source/extensions/config_subscription/grpc/xds_mux/grpc_mux_impl.cc#L433-L449) happens just before explicit instantiation.

**Comment by ggreenway** [comment]
@cpakulski merge conflict on changelog

**Review by ggreenway — APPROVED** [review]
LGTM

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Comment by cpakulski** [comment]
@adisuissa Thanks a lot for helping with code structure!
