### PR TITLE
rds: split subscription out from RdsRouteConfigProviderImpl

### LINKED ISSUE #3953: Crash at RDS onConfigUpdate
*Description*:

Please see crash backtrace in https://github.com/istio/proxy/issues/1877

It crashed at this line: https://github.com/envoyproxy/envoy/blob/c92a3017017dfa31241dec13dc6a1479090318d0/source/common/router/rds_impl.cc#L100

factory_context_ is gone.  One possible cause is this RdsRouteConfigProvider is created by one ListenerImpl which is stored as factory_context_ in the provider.  But this provider is shared by the second ListenerImpl since provider_manager is singleton or global.   The first ListenerImpl object maybe gone when the provider::onConfigUpdate is called. 

*Repro steps*: None

*Call Stack*:

#0 0x0000000000d71379 in uw_frame_state_for () at src/base/logging.h:229
#1 0x0000000000d72fb8 in _Unwind_Backtrace () at src/base/logging.h:229
#2 0x0000000000ce46ac in backward::details::Unwinder<backward::StackTraceImplbackward::system_tag::linux_tag::callback>::operator() (depth=72,
f=..., this=0x7fa881f95a00) at external/com_github_bombela_backward/backward.hpp:647
#3 backward::details::unwind<backward::StackTraceImplbackward::system_tag::linux_tag::callback> (depth=72, f=...)
at external/com_github_bombela_backward/backward.hpp:688
#4 backward::StackTraceImplbackward::system_tag::linux_tag::load_here (this=this@entry=0x7fa881f95a60, depth=depth@entry=72)
at external/com_github_bombela_backward/backward.hpp:704
#5 0x0000000000ce5c65 in backward::StackTraceImplbackward::system_tag::linux_tag::load_from (depth=64, addr=0x55, this=0x7fa881f95a60)
at external/com_github_bombela_backward/backward.hpp:710
#6 Envoy::BackwardsTrace::captureFrom (address=0x55, this=0x7fa881f95a60)
at bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:66
#7 Envoy::SignalAction::sigHandler (sig=11, info=, context=) at external/envoy/source/exe/signal_action.cc:33
#8 
#9 0x0000000000000055 in ?? ()
#10 0x00000000007c089d in Envoy::Router::RdsRouteConfigProviderImpl::onConfigUpdate (this=0x28e0c40, resources=..., version_info=...)
at external/envoy/source/common/router/rds_impl.cc:100
#11 0x00000000007c2188 in Envoy::Config::GrpcMuxSubscriptionImplenvoy::api::v2::RouteConfiguration::onConfigUpdate (this=0x300dc70,
resources=..., version_info=...)
at bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:55
#12 0x00000000008d2f3f in Envoy::Config::GrpcMuxImpl::onReceiveMessage(std::unique_ptr<envoy::api::v2::DiscoveryResponse, std::default_deleteenvoy::api::v2::DiscoveryResponse >&&) (this=0x28b67e0,
message=<unknown type in /home/qiwzhang/debug_proxy/sym/usr/local/bin/envoy, CU 0x8ac27a2, DIE 0x8b7e86d>)
at external/envoy/source/common/config/grpc_mux_impl.cc:217
#13 0x00000000008d06e3 in Envoy::Grpc::TypedAsyncStreamCallbacksenvoy::api::v2::DiscoveryResponse::onReceiveMessageUntyped(std::unique_ptr<google::protobuf::Message, std::default_deletegoogle::protobuf::Message >&&) (this=0x28b67e8, message=)
at bazel-out/k8-opt/bin/external/envoy/include/envoy/grpc/_virtual_includes/async_client_interface/envoy/grpc/async_client.h:172
#14 0x00000000008f8a66 in Envoy::Grpc::AsyncStreamImpl::onData (this=0x296d7c0, data=..., end_stream=)
at external/envoy/source/common/grpc/async_client_impl.cc:138
#15 0x00000000008fd73c in Envoy::Http::AsyncStreamImpl::encodeData (this=0x2949b00, data=..., end_stream=false)
at external/envoy/source/common/http/async_client_impl.cc:103
#16 0x0000000000932f54 in Envoy::Http::Http2::ConnectionImpl::onFrameReceived (this=0x2979c08, frame=0x2b8c198)
at external/envoy/source/common/http/http2/codec_impl.cc:426
#17 0x0000000000936bc7 in session_call_on_frame_received (frame=0x2b8c198, session=0x2b8c000) at nghttp2_session.c:3295
#18 nghttp2_session_on_data_received (session=session@entry=0x2b8c000, frame=frame@entry=0x2b8c198) at nghttp2_session.c:4941
#19 0x000000000093a942 in session_process_data_frame (session=0x2b8c000) at nghttp2_session.c:4961
#20 nghttp2_session_mem_recv (session=0x2b8c000, in=0x2ba4b67 "", inlen=13246) at nghttp2_session.c:6581
#21 0x0000000000932b1f in Envoy::Http::Http2::ConnectionImpl::dispatch (this=0x2979c08, data=...)
at external/envoy/source/common/http/http2/codec_impl.cc:285
#22 0x00000000008df32f in Envoy::Http::CodecClient::onData (this=0x2b881b0, data=...) at external/envoy/source/common/http/codec_client.cc:115
#23 0x00000000008df4ad in Envoy::Http::CodecClient::CodecReadFilter::onData (this=, data=...)
at bazel-out/k8-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_client_lib/common/http/codec_client.h:162
#24 0x00000000007b0b97 in Envoy::Network::FilterManagerImpl::onContinueReading (this=this@entry=0x297bb98, filter=filter@entry=0x0)
at external/envoy/source/common/network/filter_manager_impl.cc:56
#25 0x00000000007b0c6c in Envoy::Network::FilterManagerImpl::onRead (this=this@entry=0x297bb98)
at external/envoy/source/common/network/filter_manager_impl.cc:66
#26 0x00000000007af21f in Envoy::Network::ConnectionImpl::onRead (read_buffer_size=13246, this=0x297bb80)
at external/envoy/source/common/network/connection_impl.cc:213
#27 Envoy::Network::ConnectionImpl::onReadReady (this=this@entry=0x297bb80) at external/envoy/source/common/network/connection_impl.cc:446
#28 0x00000000007afa0e in Envoy::Network::ConnectionImpl::onFileEvent (this=0x297bb80, events=3)
at external/envoy/source/common/network/connection_impl.cc:422
#29 0x00000000007a8e68 in std::function<void (unsigned int)>::operator()(unsigned int) const (__args#0=3, this=)
at /usr/include/c++/5/functional:2267
#30 Envoy::Event::FileEventImpl::<lambda(int, short int, void*)>::operator() (__closure=0x0, arg=, what=)
at external/envoy/source/common/event/file_event_impl.cc:60
#31 Envoy::Event::FileEventImpl::<lambda(int, short int, void*)>::_FUN(int, short, void *) ()
at external/envoy/source/common/event/file_event_impl.cc:61
#32 0x0000000000aa07e2 in event_persist_closure (ev=, base=0x28b82c0) at event.c:1580
#33 event_process_active_single_queue (base=base@entry=0x28b82c0, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0,
activeq=) at event.c:1639
#34 0x0000000000aa0f3f in event_process_active (base=0x28b82c0) at event.c:1738
#35 event_base_loop (base=0x28b82c0, flags=0) at event.c:1961
#36 0x00000000007795ee in Envoy::Server::InstanceImpl::run (this=0x286ec80) at external/envoy/source/server/server.cc:413
#37 0x0000000000572b81 in Envoy::MainCommonBase::run (this=this@entry=0x28a69a8) at external/envoy/source/exe/main_common.cc:83
#38 0x00000000004227d3 in Envoy::MainCommon::run (this=)
at bazel-out/k8-opt/bin/external/envoy/source/exe/_virtual_includes/envoy_main_common_lib/exe/main_common.h:44
#39 main (argc=18, argv=0x7ffc9a3284c8) at external/envoy/source/exe/main.cc:37

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <zlizan@google.com>

*Description*:
`RdsRouteConfigProviderImpl` holds reference to `FactoryContext` (implemented by `ListenerImpl`), which could be freed after LDS update (#3953), this PR split subscription part out and make `RdsRouteConfigProviderImpl` owned by each Listener. The subscription class holds references to all live providers to provide RDS update.

*Risk Level*: Low
*Testing*: unit test, integration test
*Docs Changes*:
*Release Notes*:

Fixes #3953

### CODE REVIEW

**Comment by lizan** [comment]
Thanks to integration test added by @qiwzhang (#3955) and @PiotrSikora (#3957).

This PR is still WIP: need cleanup interface between `RdsRouteConfig*`, add comment for them, and tests in `rds_impl_test`. At least `ads_integration_test` passes with ASAN for now.

Let me know if you think this is a right approach. @htuch @mattklein123 @PiotrSikora @qiwzhang @mandarjog

File: source/common/router/rds_impl.cc [hunk 1]
```diff
@@ -80,24 +74,20 @@ RdsRouteConfigProviderImpl::RdsRouteConfigProviderImpl(
...
   // The ownership of RdsRouteConfigProviderImpl is shared among all HttpConnectionManagers that
   // hold a shared_ptr to it. The RouteConfigProviderManager holds weak_ptrs to the
   // RdsRouteConfigProviders. Therefore, the map entry for the RdsRouteConfigProvider has to get
   // cleaned by the RdsRouteConfigProvider's destructor.
-  route_config_provider_manager_.route_config_providers_.erase(manager_identifier_);
-}
-
-Router::ConfigConstSharedPtr RdsRouteConfigProviderImpl::config() {
-  return tls_->getTyped<ThreadLocalConfig>().config_;
+  route_config_provider_manager_.route_config_subscriptions_.erase(manager_identifier_);
```
Comment (rshriram) [inline source/common/router/rds_impl.cc]: how do you avoid the race here?
an updated lister's rdsrouteconfig object is being deleted and tries to tell the routeconfig manager that it should be removed..
At the same time, an RDS update arrives and the subscription manager is updating all the routeconfig objects.

Comment (qiwzhang) [reply source/common/router/rds_impl.cc]: There is not race.  ProviderImpl and RdsSubscription are separated.   ProviderImpl is tightly associated with ListenerImpl, one per one.  But RdsSubscription is shared, across ListenerImpl,  the ones with different names, or old one with the new one with config change.   A freed ProviderImpl will not free RdsSubscription if it is shared by others.  
BTW, here provider_manager should be called subscripton_manager.

**Comment by qiwzhang** [comment]
@lizan I think this approach should work.  This is the smallest change I can think of to fix this crash.  BTW, provider should be changed to use unique_ptr instead of shared_ptr.

File: source/common/router/rds_impl.cc (hunk 1 above)
Comment (lizan) [reply source/common/router/rds_impl.cc]: > BTW, here provider_manager should be called subscripton_manager.

provider_manager still manage providers (both static and rds), it doesn't own each rds provider but manages them through subscriptions.

**Comment by lizan** [comment]
I think eventually we will need to break FactoryContext into small pieces and locking them down, but for now this should be good.

shared_ptr is used for a couple reasons (weak_ptr, config_dump), I will see if it can be unique_ptr as follow up.

File: source/common/router/rds_impl.cc [hunk 2]
```diff
@@ -115,35 +107,79 @@ void RdsRouteConfigProviderImpl::onConfigUpdate(const ResourceVector& resources,
...
 
-void RdsRouteConfigProviderImpl::registerInitTarget(Init::Manager& init_manager) {
-  init_manager.registerTarget(*this);
+RdsRouteConfigProviderImpl::RdsRouteConfigProviderImpl(
+    RdsRouteConfigSubscriptionSharedPtr&& subscription,
+    Server::Configuration::FactoryContext& factory_context)
+    : subscription_(std::move(subscription)), factory_context_(factory_context),
+      tls_(factory_context.threadLocal().allocateSlot()) {
+  ConfigConstSharedPtr initial_config;
+  if (subscription_->config_info_.has_value()) {
```
Comment (qiwzhang) [inline source/common/router/rds_impl.cc]: can we define a getter function?  not to use subscription member directly.

File: source/common/router/rds_impl.cc [hunk 3]
```diff
@@ -115,35 +107,79 @@ void RdsRouteConfigProviderImpl::onConfigUpdate(const ResourceVector& resources,
...
+    initial_config =
+        std::make_shared<ConfigImpl>(subscription_->route_config_proto_, factory_context_, false);
+  } else {
+    initial_config = std::make_shared<NullConfigImpl>();
+  }
+  tls_->set([initial_config](Event::Dispatcher&) -> ThreadLocal::ThreadLocalObjectSharedPtr {
+    return std::make_shared<ThreadLocalConfig>(initial_config);
+  });
+  subscription_->route_config_providers_.insert(this);
```
Comment (qiwzhang) [inline source/common/router/rds_impl.cc]: Subscription defines a OnUpdate interface,  it only stores the interface pointers.

File: source/common/router/rds_impl.cc [hunk 4]
```diff
@@ -195,26 +232,29 @@ Router::RouteConfigProviderSharedPtr RouteConfigProviderManagerImpl::getRdsRoute
...
+    subscription = it->second.lock();
   }
+  ASSERT(subscription);
 
-  // Because the RouteConfigProviderManager's weak_ptrs only get cleaned up
-  // in the RdsRouteConfigProviderImpl destructor, and the single threaded nature
-  // of this code, locking the weak_ptr will not fail.
-  Router::RouteConfigProviderSharedPtr new_provider = it->second.lock();
-  ASSERT(new_provider);
+  Router::RouteConfigProviderSharedPtr new_provider{
```
Comment (qiwzhang) [inline source/common/router/rds_impl.cc]: Can this be unique_ptr?

File: source/common/router/rds_impl.h [hunk 5]
```diff
@@ -138,21 +122,62 @@ class RdsRouteConfigProviderImpl
...
   const std::string manager_identifier_;
-  envoy::api::v2::RouteConfiguration route_config_proto_;
+  SystemTimeSource& time_source_;
   SystemTime last_updated_;
+  absl::optional<LastConfigInfo> config_info_;
+  envoy::api::v2::RouteConfiguration route_config_proto_;
+  std::unordered_set<RdsRouteConfigProviderImpl*> route_config_providers_;
+
+  friend class RouteConfigProviderManagerImpl;
+  friend class RdsRouteConfigProviderImpl;
```
Comment (qiwzhang) [inline source/common/router/rds_impl.h]: can we not use friend class?  define some getter functions.

File: source/common/router/rds_impl.h [hunk 6]
```diff
@@ -138,21 +122,62 @@ class RdsRouteConfigProviderImpl
...
   RdsStats stats_;
-  std::function<void()> initialize_callback_;
   RouteConfigProviderManagerImpl& route_config_provider_manager_;
   const std::string manager_identifier_;
-  envoy::api::v2::RouteConfiguration route_config_proto_;
+  SystemTimeSource& time_source_;
   SystemTime last_updated_;
+  absl::optional<LastConfigInfo> config_info_;
+  envoy::api::v2::RouteConfiguration route_config_proto_;
+  std::unordered_set<RdsRouteConfigProviderImpl*> route_config_providers_;
```
Comment (qiwzhang) [inline source/common/router/rds_impl.h]: Not to store the whole provider object,   define OnUpdate interface,  only store the interface pointers.

File: source/common/router/rds_impl.h [hunk 7]
```diff
@@ -138,21 +122,62 @@ class RdsRouteConfigProviderImpl
...
+
+  void onConfigUpdate();
+
+  RdsRouteConfigSubscriptionSharedPtr subscription_;
+  Server::Configuration::FactoryContext& factory_context_;
+  ThreadLocal::SlotPtr tls_;
+  const std::string route_config_name_;
 
   friend class RouteConfigProviderManagerImpl;
+  friend class RdsRouteConfigSubscription;
```
Comment (qiwzhang) [inline source/common/router/rds_impl.h]: Why does Subscription need to access ProviderImpl private members?

**Comment by mattklein123** [comment]
Talked to @lizan offline. This approach/fix LGTM. Please let me know when the rest of the comments are finished and I can take a look. Thank you for fixing!

File: test/integration/ads_integration_test.cc [hunk 8]
```diff
@@ -471,6 +472,72 @@ TEST_P(AdsIntegrationTest, Failure) {
...
+  sendDiscoveryResponse<envoy::api::v2::Listener>(
+      Config::TypeUrl::get().Listener, {buildListener("listener_0", "route_config_0", "rds_crash")},
+      "2");
+  test_server_->waitForCounterGe("listener_manager.listener_create_success", 2);
+
+  // Update existing RDS (no changes).
+  sendDiscoveryResponse<envoy::api::v2::RouteConfiguration>(
+      Config::TypeUrl::get().RouteConfiguration, {buildRouteConfig("route_config_0", "cluster_0")},
+      "2");
+}
```
Comment (qiwzhang) [inline test/integration/ads_integration_test.cc]: can we make "makeSingleRequest()" call here

File: test/integration/ads_integration_test.cc [hunk 9]
```diff
@@ -471,6 +472,72 @@ TEST_P(AdsIntegrationTest, Failure) {
...
+  sendDiscoveryResponse<envoy::api::v2::Listener>(
+      Config::TypeUrl::get().Listener, {buildListener("listener_0", "route_config_0", "rds_crash")},
+      "2");
+  test_server_->waitForCounterGe("listener_manager.listener_create_success", 2);
+
+  // Update existing RDS (migrate traffic to cluster_1).
+  sendDiscoveryResponse<envoy::api::v2::RouteConfiguration>(
+      Config::TypeUrl::get().RouteConfiguration, {buildRouteConfig("route_config_0", "cluster_1")},
+      "2");
+}
```
Comment (qiwzhang) [inline test/integration/ads_integration_test.cc]: can we add "makeSingleRequest()" call here to  make sure it works?  
May have to wait for rds update success.

File: source/common/router/rds_impl.cc (hunk 3 above)
Comment (lizan) [reply source/common/router/rds_impl.cc]: No it won't work, you will need a pointer to RdsRouteConfigProviderImpl to implement `std::vector<RouteConfigProviderSharedPtr> getRdsRouteConfigProviders()` in `RouteConfigProviderManagerImpl`

All the onUpdate is only used in `rds_impl` and should not be used elsewhere, would rather keep this in private.

File: source/common/router/rds_impl.cc (hunk 4 above)
Comment (lizan) [reply source/common/router/rds_impl.cc]: It will involving interface changes and make them consistent with StaticRouteConfigProviders, and update `HttpConnectionManager` too.

File: source/common/router/rds_impl.h (hunk 6 above)
Comment (lizan) [reply source/common/router/rds_impl.h]: ditto above, you need pointer to ProviderImpl to get shared_ptr of it.

File: source/common/router/rds_impl.h (hunk 7 above)
Comment (lizan) [reply source/common/router/rds_impl.h]: mostly for for onConfigUpdate since no class other than Subscription should call it. will make it public and remove friend here.

File: source/common/router/rds_impl.h (hunk 5 above)
Comment (lizan) [reply source/common/router/rds_impl.h]: What is the point of define more getter functions? No other classes should access them via getter than friend classes listed here.

File: source/common/router/rds_impl.cc (hunk 4 above)
Comment (qiwzhang) [reply source/common/router/rds_impl.cc]: IMHO, it is important to use unique_ptr to show Provider object is not shared, only HttpConnectionManager owns it.

File: source/common/router/rds_impl.h (hunk 6 above)
Comment (qiwzhang) [reply source/common/router/rds_impl.h]: This is what I mean:

class RdsSubscriptionCallback {
  public:
     virtual onConfigUpdate() PURE;
};

Here RdsConfigSubscription uses it as:

 std::unordered_set<RdsSubscriptionCallback*> update_callbacks_;

File: source/common/router/rds_impl.h (hunk 7 above)
Comment (qiwzhang) [reply source/common/router/rds_impl.h]: If we use SubscriptionCallback interface,  this friend class will not be needed.

File: source/common/router/rds_impl.h (hunk 6 above)
Comment (lizan) [reply source/common/router/rds_impl.h]: Yes I know what you meant, then you won't be able to do https://github.com/lizan/envoy/blob/6d433fef72eebc37b63acef63fd492cbbb9ff659/source/common/router/rds_impl.cc#L204 without dynamic_cast.

It doesn't make sense to make an interface which is completely implementation detail.

**Comment by qiwzhang** [comment]
LGTM for the quick fix.

Maybe a follow up PR to do the follow clean up:
1) use unique_ptr for Provider
2) Try to cleanly separate Subscription class with ProviderImpl class.

**Comment by lizan** [comment]
@mattklein123 and/or @htuch PTAL.

@qiwzhang I'm looking at how large it will be to do unique_ptr, within or not in this PR. Though not convinced that we need to do 2.
