### PR TITLE
Remove scope id from ipv6 address in getLocalAddress

### LINKED ISSUE #25326: Envoy-mobile clients fail to speak IPV6 on Android clients with ndk >=24
Currently the posix version of getifaddrs() has 2 paths:
For Android with ndk version < 24, it calls getifaddrs that's specific to [Android](https://github.com/envoyproxy/envoy/blob/main/source/common/api/posix/os_sys_calls_impl.cc#L361).
For all other situations, it uses Envoy's default getifaddrs() [impl](https://github.com/envoyproxy/envoy/blob/main/source/common/api/posix/os_sys_calls_impl.cc#L391).

It is discovered that the default getifaddrs() doesn't quite work with Android with ndk level >=24. It's not able to send traffic in IPV6 but works fine in IPV4.
This is not an issue now since all Envoy-mobile applications are built with <24 ndk. But it's an ticking bomb that will go off with future toolchain upgrade.

It's verified that the <24 code path also works with >=24 build. Thus the easiest solution is to remove the __ANDROID_API__ < 24 guard and jus run the Android specific getifaddrs() for all Android ndk versions.

### PR DESCRIPTION
**Pull request by RenjieTang**
Signed-off-by: Renjie Tang <renjietang@google.com>

Commit Message: Remove scope id from ipv6 address in getLocalAddress
Additional Description: This fixes the issue where Envoy-mobile fails to send out any packet on ipv6.
Risk Level: Low
Testing: unit tests
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Fixes #25326

### CODE REVIEW

File: source/common/network/utility.cc [hunk 1]
```diff
@@ -236,6 +236,9 @@ Address::InstanceConstSharedPtr Utility::getLocalAddress(const Address::IpVersio
       if (!isLoopbackAddress(*interface_address.interface_addr_) &&
           interface_address.interface_addr_->ip()->version() == version) {
         ret = interface_address.interface_addr_;
+        if (ret->ip()->version() == Address::IpVersion::v6) {
```
Comment (RyanTheOptimist) [inline source/common/network/utility.cc:239]: Is it possible that ret is null, or ret->ip() is null? Maybe:
```
if (ret && ret->ip() && ret->ip()->version() == Address::IpVersion::v6) {
````

**Review by RyanTheOptimist — COMMENTED** [review]
LGTM, modulo one nit.

File: source/common/network/utility.cc (hunk 1 above)
Comment (RenjieTang) [reply source/common/network/utility.cc:239]: I don't think the null guard is needed here because in the if statement above, there's already a `interface_address.interface_addr_->ip()->version() == version` call.

Comment (RyanTheOptimist) [reply source/common/network/utility.cc:239]: Oh good lord! You're totally right.

**Review by RyanTheOptimist — APPROVED** [review]
