### PR TITLE
upstream: ensure hosts are updated when overprovisioning factor is set

### LINKED ISSUE #5555: IPs not set if version never changes
*Title*: IPs not set if version never changes 

*Description*:
We are using a control-plane based on the go-control-plane project. We are using ADS to serve resources to envoy over gRPC. When the clusters/endpoints do not change from the initial version, Envoy does not correctly associate the IPs it receives from the control-plane with the clusters. Envoy receives the IPs and acknowledges them in the logs, but the IPs do not appear in the /clusters endpoint and attempts to route to these clusters fail with 503. Forcing a new version in the control-plane triggers envoy to correctly associate the IPs it receives with the cluster. 

*version* 5d25f466c3410c0dfa735d7d4358beb76b2da507/1.8.0/Clean/RELEASE
This has been confirmed to also occur with the docker image for v1.9.0 but does not occur with the image for v1.7.0

*Repro steps*:
* Start dummy service
* Start control plane
* Start Envoy
* Try to route to dummy service -> 503
* add new service, verify version changed in log
* Try to route to dummy service -> 200

logs and output attached (ips redacted) 
[clusters.txt](https://github.com/envoyproxy/envoy/files/2742364/clusters.txt)
[clusters_after.txt](https://github.com/envoyproxy/envoy/files/2742376/clusters_after.txt)
[envoy-config.txt](https://github.com/envoyproxy/envoy/files/2742366/envoy-config.txt)
[envoy_log.txt](https://github.com/envoyproxy/envoy/files/2742367/envoy_log.txt)

### PR DESCRIPTION
**Pull request by snowp**
This fixes a bug where `updateDynamicHostList` was not called when the
overprovisoning factor changed, which meant that the list of hosts
would not get updated. This meant that when `updateClusterPrioritySet` was
called it would always be called with the old host lists, ignoring any
new change.

This would cause the initial host update to not add any
hosts when an overprovisioning factor was set, as the overprovisioning factor of a host set is initialized to
the default value before this code path is hit, so this would be treated as an overprovisioning update.

Fixes #5555

Signed-off-by: Snow Pettersen <snowp@squareup.com>

Risk Level: Low
Testing: Added UT
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

File: source/common/upstream/eds.cc [hunk 1]
```diff
@@ -214,9 +214,9 @@ bool EdsClusterImpl::updateHostsPerLocality(
   // out of the locality scheduler, we discover their new weights. We don't currently have a shared
   // object for locality weights that we can update here, we should add something like this to
   // improve performance and scalability of locality weight updates.
-  if (host_set.overprovisioningFactor() != overprovisioning_factor ||
-      updateDynamicHostList(new_hosts, *current_hosts_copy, hosts_added, hosts_removed,
+  if (updateDynamicHostList(new_hosts, *current_hosts_copy, hosts_added, hosts_removed,
```
Comment (mattklein123) [inline source/common/upstream/eds.cc]: This is a really subtle bug. To prevent this from accidentally happening again can you potentially lift the call to `updateDynamicHostList` out of this if statement and assign it to its own const bool with a description of why it's done that way?
