### PR TITLE
Bugfix issue 27877 jwt token with space is valid

### LINKED ISSUE #27877: Jwt Authentication filter falsely authenticates invalid JWT made up of a valid JWT followed by a space and additional characters
*Title*: *Jwt Authentication filter falsely authenticates invalid JWT made up of a valid JWT followed by a space and additional characters*

*Description*:
>When sending a valid token followed by a space and some other character, the JWT Authentication filter considers it as a valid token. 
I checked this same thing with Auth0 server and its response for this case was:
{
   "statusCode": 400,
   "error": "Bad Request",
   "message": "Bad HTTP authentication header format",
   "errorCode": "Bearer"
})
In addition, RFC 7519 implies that adding non-Base64URL characters after a valid JWT token makes it invalid. Thus, if I will add space and after that some character or if I will add in the end of valid token some non-Base64 characters like ### (without any space)
The JWT Authentication filter however will consider these types of tokens as valid token

*Repro steps*:
> 1.	Deploy Envoy env with jwt filter 
> 2.	send request with Authorization header and value is Bearer + your token + space + some characters (as mentioned in the example)

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Solution*:
>source/extensions/filters/http/jwt_authn/extractor.cc
>In code we suggest to remove all lines from "ending" variable to the end of function and instead return "value_str.substr(starting) [delete lines 327-332]
>
image
>According to RFC7519 in this case the token is invalid and currently this function “cuts out” the non-Base64URL part and passes the token only which it itself is valid.
So, in this case we want to return the complete token (including the non-Base64 part) and then Envoy will mark it as invalid token.

### PR DESCRIPTION
**Pull request by danieldradware**
…non base64 characters

Commit Message:
This PR should fix issue [#27877](https://github.com/envoyproxy/envoy/issues/27877)
Additional Description:
New behavior isn't cutting characters after non base64 character
Now expected to get all token and then mark it as invalid jwt
All details in issue [#27877](https://github.com/envoyproxy/envoy/issues/27877)
Risk Level:
Medium
Testing:
Added unit test
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
Fixes #27877
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by yanavlasov** [comment]
The spell checker is not happy: https://dev.azure.com/cncf/envoy/_build/results?buildId=144417&view=logs&j=c7de00aa-b0fb-52ba-707b-da6afd918eda&t=2ec0901d-43fb-521a-88ec-473706b56eab&l=45

File: source/extensions/filters/http/jwt_authn/extractor.cc [hunk 1]
```diff
@@ -325,12 +325,9 @@ absl::string_view ExtractorImpl::extractJWT(absl::string_view value_str,
...
     return value_str;
   }
+
   // There should be two dots (periods; 0x2e) inside the string, but we don't verify that here
-  auto ending = value_str.find_first_not_of(ConstantBase64UrlEncodingCharsPlusDot, starting);
-  if (ending == value_str.npos) { // Base64Url-encoded string occupies the rest of the line
-    return value_str.substr(starting);
-  }
-  return value_str.substr(starting, ending - starting);
+  return value_str.substr(starting);
```
Comment (nareddyt) [inline source/extensions/filters/http/jwt_authn/extractor.cc:330]: Is a runtime guard warranted for this change? https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#runtime-guarding

> Generally as a community we try to guard [...] most user-visible non-config-guarded changes to protocol processing (for example additions or changes to HTTP headers or how HTTP is serialized out) for non-alpha features. Feel free to tag @envoyproxy/maintainers if you aren't sure if a given change merits runtime guarding.

I'm slightly worried it will break runtime traffic for clients using it (https://www.hyrumslaw.com/). Though this is a very unique corner case and I doubt clients rely on this behavior. Either way, worth asking @envoyproxy/maintainers

Comment (danieldradware) [reply source/extensions/filters/http/jwt_authn/extractor.cc:330]: RFC 7519 implies that adding non-Base64URL characters after a valid JWT token makes it invalid. Thus, if a the JWT is followed by a space and some Base64URL characters or just followed by non Base64URL characters like ### (without any space) it should be considered invalid.

**Review by yanavlasov — CHANGES_REQUESTED** [review]
/wait

**Comment by yanavlasov** [comment]
@danieldradware the runtime features require alphanumeric order

```
ERROR: From ./source/common/runtime/runtime_features.cc
ERROR: RUNTIME_GUARD(envoy_reloadable_features_http_reject_path_with_fragment); and RUNTIME_GUARD(envoy_reloadable_features_token_passed_entirely); are out of order
```

**Comment by yanavlasov** [comment]
Can you also add a test that check the behavior with the `envoy.reloadable_features.token_passed_entirely` == false, please? In this was it is certain that old behavior is still working with override. Look good otherwise.

/wait

**Comment by phlax** [comment]
@yanavlasov i think this is waiting on further review

/wait-any

**Comment by danieldradware** [comment]
Hi @yanavlasov @phlax 
I saw there is a failure in pipeline cause network issue, 
Can you please rerun only specific jobs that failures?
Thanks!

**Comment by danieldradware** [comment]
> Hi @yanavlasov @phlax I saw there is a failure in pipeline cause network issue, Can you please rerun only specific jobs that failures? Thanks!

Thanks for rerun it.
Can you please approve the PR and merge it with main?

File: source/common/runtime/runtime_features.cc [hunk 2]
```diff
@@ -77,7 +77,10 @@ RUNTIME_GUARD(envoy_reloadable_features_successful_active_health_check_uneject_h
 RUNTIME_GUARD(envoy_reloadable_features_test_feature_true);
 RUNTIME_GUARD(envoy_reloadable_features_thrift_allow_negative_field_ids);
 RUNTIME_GUARD(envoy_reloadable_features_thrift_connection_draining);
+RUNTIME_GUARD(envoy_reloadable_features_token_passed_entirely);
 RUNTIME_GUARD(envoy_reloadable_features_uhv_allow_malformed_url_encoding);
+RUNTIME_GUARD(envoy_reloadable_features_uhv_preserve_url_encoded_case);
```
Comment (yanavlasov) [inline source/common/runtime/runtime_features.cc:82]: These runtime keys looks like result of a bad merge. Please remove them, since they are not part of this change.

**Review by yanavlasov — CHANGES_REQUESTED** [review]
/wait

**Comment by yanavlasov** [comment]
I was also looking for a test with the following in it:
```
      TestScopedRuntime scoped_runtime;
      scoped_runtime.mergeValues({{"envoy.reloadable_features.token_passed_entirely", "false"}});
```

that tests old behavior. Can you add a test like this please?

**Comment by danieldradware** [comment]
> I was also looking for a test with the following in it:
> 
> ```
>       TestScopedRuntime scoped_runtime;
>       scoped_runtime.mergeValues({{"envoy.reloadable_features.token_passed_entirely", "false"}});
> ```
> 
> that tests old behavior. Can you add a test like this please?

Hi @yanavlasov 
Sure I already added unit test to test the old behavior, you can see it at:test/extensions/filters/http/jwt_authn/extractor_runtime_guard_test.cc and BUILD file that contain:   args = ["--runtime-feature-disable-for-tests=envoy.reloadable_features.token_passed_entirely"],

**Comment by danieldradware** [comment]
Can you please rerun Linux arm64 section?
Thanks!

**Comment by danieldradware** [comment]
Hi @yanavlasov 
Can you please remove "change requested" action? (I already pushed all changed you asked from me).

BTW who can give to this PR an approval?

Thanks a lot
Daniel
