### PR TITLE
reverse_bridge: fix null dereference when upstream content type is missing

### LINKED ISSUE #8784: Caught Segmentation fault, suspect faulting address 0x0.
*Title*: *Caught Segmentation fault, suspect faulting address 0x0.*

*Description*:
>We are experiencing periodic restarts due to a segmentation fault. With envoy.filters.http.grpc_http1_reverse_bridge enabled.
We have realized that it is "always" after an error 418 due to [nginx waf](https://docs.nginx.com/nginx-waf/).
Is it possible that we have forgotten some envoy config?
Envoy version: ebd972ecb49bc50bd754fdecb3f84c70d2ad26b6/1.12.0-dev/Clean/RELEASE/BoringSSL (but we experienced it using v1.11.0 stable version too)

*Config*:
```
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          use_remote_address: true
          access_log:
          - name: envoy.file_access_log
            config:
              path: /dev/stdout
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: grpcbackend-internal
                  cluster: backend
                  timeout: 50.00s
          http_filters:
          - name: envoy.filters.http.grpc_http1_reverse_bridge
            config:
              content_type: application/grpc+proto
              withhold_grpc_frames: true
          - name: envoy.router
      use_proxy_proto: true
      tls_context:
        common_tls_context:
          alpn_protocols:
            - h2
            - http/1.1
          tls_certificates:
            - certificate_chain: {filename: xxx.pem}
              private_key: {filename: xxx.key}
  clusters:
  - name: backend
    connect_timeout: 50.00s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: http-internal
          port_value: 80
```

*Call Stack*:
>
```
StreamInfoImpl 0x2506eb8, protocol_: 2, response_code_: null, response_code_details_: via_upstream, health_check_request_: 0, route_name_:
&stream_info_:
response_trailers_: null
'x-envoy-upstream-service-time', '29'
'connection', 'keep-alive'
'content-length', '0'
'date', 'Mon, 28 Oct 2019 10:49:42 GMT'
'server', 'nginx'
':status', '418'
response_headers_:
request_trailers_: null
'x-envoy-expected-rq-timeout-ms', '50000'
'accept', 'application/grpc+proto'
'x-request-id', 'xxx'
'x-envoy-external-address', 'x.x.x.x'
'x-forwarded-proto', 'https'
'x-forwarded-for', 'x.x.x.x'
'grpc-timeout', '4770m'
'accept-encoding', 'identity,gzip'
'grpc-accept-encoding', 'identity,deflate,gzip'
'user-agent', 'grpc-csharp/1.23.0-dev grpc-c/7.0.0 (android; chttp2; gangnam)'
'content-type', 'application/grpc+proto'
'te', 'trailers'
':path', '/rpc.backend.Service/Xxxx'
':authority', 'backend'
':method', 'POST'
':scheme', 'http'
request_headers_:
ActiveStream 0x2506d80, stream_id_: 9773374393975308796, has_continue_headers_: 0, is_head_request_: 0, decoding_headers_only_: 0, encoding_headers_only_: 0
[2019-10-28 10:49:42.552][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #22: [0x7f859b400f30]
[2019-10-28 10:49:42.552][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #21: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x128d1a5]
[2019-10-28 10:49:42.548][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #20: Envoy::Server::WorkerImpl::threadRoutine() [0xe0bd3b]
[2019-10-28 10:49:42.543][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #19: event_base_loop [0x1104d9e]
[2019-10-28 10:49:42.459][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #18: event_process_active_single_queue [0x11065b7]
[2019-10-28 10:49:42.454][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #17: Envoy::Event::FileEventImpl::assignEvents()::$_0::__invoke() [0xe13f15]
[2019-10-28 10:49:42.450][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #16: Envoy::Network::ConnectionImpl::onFileEvent() [0xe19381]
[2019-10-28 10:49:42.445][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #15: Envoy::Network::ConnectionImpl::onReadReady() [0xe198c6]
[2019-10-28 10:49:42.366][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #14: Envoy::Network::FilterManagerImpl::onContinueReading() [0xe1cf0b]
[2019-10-28 10:49:42.363][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #13: Envoy::Http::CodecClient::CodecReadFilter::onData() [0xfbeb4d]
[2019-10-28 10:49:42.360][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #12: Envoy::Http::CodecClient::onData() [0xfbdf96]
[2019-10-28 10:49:42.357][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: Envoy::Http::Http1::ConnectionImpl::dispatch() [0x103546f]
[2019-10-28 10:49:42.353][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: Envoy::Http::Http1::ConnectionImpl::dispatchSlice() [0x1035685]
[2019-10-28 10:49:42.349][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: http_parser_execute [0x110c95e]
[2019-10-28 10:49:42.345][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: Envoy::Http::Http1::ConnectionImpl::$_7::__invoke() [0x1039e9d]
[2019-10-28 10:49:42.261][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: Envoy::Http::Http1::ConnectionImpl::onMessageCompleteBase() [0x1036429]
[2019-10-28 10:49:42.254][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: Envoy::Http::Http1::ClientConnectionImpl::onMessageComplete() [0x1038b16]
[2019-10-28 10:49:42.250][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: Envoy::Http::StreamDecoderWrapper::decodeHeaders() [0xfbec7c]
[2019-10-28 10:49:42.245][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Http::Http1::ConnPoolImpl::StreamWrapper::decodeHeaders() [0xf4f336]
[2019-10-28 10:49:42.238][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: Envoy::Router::Filter::UpstreamRequest::decodeHeaders() [0xfddbf6]
[2019-10-28 10:49:42.234][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: Envoy::Router::Filter::onUpstreamHeaders() [0xfdba05]
[2019-10-28 10:49:42.229][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Envoy::Http::ConnectionManagerImpl::ActiveStream::encodeHeaders() [0x102710b]
[2019-10-28 10:49:42.225][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #0: [0x7f859b40c420]
[2019-10-28 10:49:42.224][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: ebd972ecb49bc50bd754fdecb3f84c70d2ad26b6/1.12.0-dev/Clean/RELEASE/BoringSSL
[2019-10-28 10:49:42.224][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-10-28 10:49:42.224][18][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x0
```

### PR DESCRIPTION
**Pull request by snowp**
Fixes an issue where Envoy would segfault when the upstream responded
without a content-type set.

Fixes #8784

Signed-off-by: Snow Pettersen <snowp@squareup.com>

Risk Level: Low 
Testing: UT
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

File: source/extensions/filters/http/grpc_http1_reverse_bridge/filter.cc [hunk 1]
```diff
@@ -37,8 +38,20 @@ Grpc::Status::GrpcStatus grpcStatusFromHeaders(Http::HeaderMap& headers) {
...
+  } else {
+    return fmt::format(
+        "envoy reverse bridge: upstream responded with no content-type header, status code {}",
+        headers.Status()->value().getStringView());
+  }
+}
+
 void adjustContentLength(Http::HeaderMap& headers,
-                         std::function<uint64_t(uint64_t value)> adjustment) {
+                         const std::function<uint64_t(uint64_t value)>& adjustment) {
```
Comment (snowp) [inline source/extensions/filters/http/grpc_http1_reverse_bridge/filter.cc]: this was an unrelated change that my IDE linter suggested, can revert if  we want to isolate the  change

**Comment by sp-manuel-jurado** [comment]
Thanks @snowp
