### PR TITLE
upstream: reject invalid config when using zone aware routing

### LINKED ISSUE #9013: Invalid priority causing crash on host update
A fuzz bug in `config_fuzz_bug` is catching a crash when you use a priority value that goes against the guidelines in the config (in this case, we have a priority 10 when we should be using priority 0). The following is a reporoducer for the test, and crashes on `ASSERT(priority == 0)`. 

```
TEST_F(ClusterManagerImplTest, InvalidPriority) {
  const std::string yaml = R"EOF(
static_resources:
  clusters:
  - name: cluster_2
    connect_timeout: 0.250s
    type: STRICT_DNS
  - name: new_cluster
    connect_timeout: 4s
    load_assignment:
      cluster_name: "domains"
      endpoints:
        - priority: 10
          lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 11001
            health_status: DEGRADED
cluster_manager:
  local_cluster_name: new_cluster
)EOF";

  create(parseBootstrapFromV2Yaml(yaml));
}
```
It seems like the cluster manager is updating the cluster membership for `new_cluster`, calling a post thread local cluster update. When the priority set updates the hosts we end up running the callback set in `load_balancer_impl.cc` with the fatal assert:
https://github.com/envoyproxy/envoy/blob/74fbb938dab53ebf782348371091ab49ffe039f6/source/common/upstream/load_balancer_impl.cc#L299-L312

This seems like a config that should have been caught early on, since it violates have priorities set from 0 to N without skipping. I can't seem to find any code in the cluster manager or in the priority set impl that will throw an exception if this is violated. Is there a better way to handle this that won't cause a fatal assert?

(Here's a stack trace:2019-11-13 18:30:10.063][14][critical][assert] [source/common/upstream/load_balancer_impl.cc:309] assert failure: priority == 0.
[2019-11-13 18:30:10.063][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Aborted, suspect faulting address 0x6fad50000000e
[2019-11-13 18:30:10.063][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-11-13 18:30:10.063][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 0/1.13.0-dev/redacted/DEBUG/BoringSSL
[2019-11-13 18:30:10.074][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: Envoy::SignalAction::sigHandler() [0x1e51c5c]
[2019-11-13 18:30:10.074][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: __restore_rt [0x7fb6c48093a0]
[2019-11-13 18:30:10.085][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: std::_Function_handler<>::_M_invoke() [0x122671c]
[2019-11-13 18:30:10.096][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: std::function<>::operator()() [0x50cc54]
[2019-11-13 18:30:10.106][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Common::CallbackManager<>::runCallbacks() [0x539243]
[2019-11-13 18:30:10.117][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: Envoy::Upstream::PrioritySetImpl::runReferenceUpdateCallbacks() [0x833a84]
[2019-11-13 18:30:10.127][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: Envoy::Upstream::PrioritySetImpl::getOrCreateHostSet()::$_0::operator()() [0x1031c34]
[2019-11-13 18:30:10.138][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: std::_Function_handler<>::_M_invoke() [0x1031a8c]
[2019-11-13 18:30:10.138][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: std::function<>::operator()() [0x50cc54]
[2019-11-13 18:30:10.138][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: Envoy::Common::CallbackManager<>::runCallbacks() [0x539243]
[2019-11-13 18:30:10.148][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: Envoy::Upstream::HostSetImpl::runUpdateCallbacks() [0x836b08]
[2019-11-13 18:30:10.159][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: Envoy::Upstream::HostSetImpl::updateHosts() [0x1020a19]
[2019-11-13 18:30:10.169][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #12: Envoy::Upstream::PrioritySetImpl::updateHosts() [0x10224c8]
[2019-11-13 18:30:10.180][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #13: Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::updateClusterMembership() [0x5cfd04]
[2019-11-13 18:30:10.190][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #14: Envoy::Upstream::ClusterManagerImpl::postThreadLocalClusterUpdate()::$_17::operator()() [0x5d64a4]
[2019-11-13 18:30:10.200][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #15: std::_Function_handler<>::_M_invoke() [0x5d60cd]
[2019-11-13 18:30:10.211][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #16: std::function<>::operator()() [0x5358ae]
)

### PR DESCRIPTION
**Pull request by snowp**
Adds checks to reject config that configures endpoint with a priority >
0 when using zone aware load balancing (e.g. when a local cluster is
defined).

Fixes #9013

Signed-off-by: Snow Pettersen <snowp@squareup.com>

Description:
Risk Level: Low
Testing: UTs
Docs Changes: n/a
Release Notes: n/a

### CODE REVIEW

File: source/common/upstream/cluster_manager_impl.cc [hunk 1]
```diff
@@ -220,6 +220,14 @@ ClusterManagerImpl::ClusterManagerImpl(
     }
   }
 
+  // We need to know whether we're zone aware  early on, so make sure we do this lookup
```
Comment (mattklein123) [inline source/common/upstream/cluster_manager_impl.cc]: nit: double space

File: source/common/upstream/cluster_manager_impl.cc [hunk 2]
```diff
@@ -541,11 +546,12 @@ bool ClusterManagerImpl::addOrUpdateCluster(const envoy::api::v2::Cluster& clust
   //    primary/secondary init, static/CDS init, warming all clusters, etc.
   // 2) After initial server load, we handle warming independently for each cluster in the warming
   //    map.
-  // Note: It's likely possible that all warming logic could be centralized in the init manager, but
-  //       a decision was made to split the logic given how complex the init manager already is. In
-  //       the future we may decide to undergo a refactor to unify the logic but the effort/risk to
-  //       do that right now does not seem worth it given that the logic is generally pretty clean
-  //       and easy to understand.
+  // Note: It's likely possible that all warming logic could be centralized in the init manager,
+  // but
```
Comment (mattklein123) [inline source/common/upstream/cluster_manager_impl.cc]: nit: strange formatting, revert? Can you potentially revert all the unrelated text formatting changes?

File: source/common/upstream/cluster_manager_impl.cc [hunk 3]
```diff
@@ -220,6 +220,14 @@ ClusterManagerImpl::ClusterManagerImpl(
     }
   }
 
+  // We need to know whether we're zone aware  early on, so make sure we do this lookup
+  // before we load any clusters.
+  absl::optional<std::string> local_cluster_name;
```
Comment (mattklein123) [inline source/common/upstream/cluster_manager_impl.cc]: nit: why not just make the member variable an optional?

File: source/common/upstream/logical_dns_cluster.cc [hunk 4]
```diff
@@ -37,6 +38,11 @@ LogicalDnsCluster::LogicalDnsCluster(
       cluster, dns_refresh_rate_ms_.count(), factory_context.random());
 
   const auto& locality_lb_endpoints = load_assignment_.endpoints();
+  if (!locality_lb_endpoints.empty() && locality_lb_endpoints[0].priority() != 0) {
```
Comment (mattklein123) [inline source/common/upstream/logical_dns_cluster.cc]: I don't think zone aware routing make sense at all for logical DNS. Should we just block it entirely? I guess it makes sense for static? Basically I'm just wondering if we should block it for cases in which it would not really work well? WDYT?

Comment (snowp) [reply source/common/upstream/logical_dns_cluster.cc]: I think the main concern would be that there are existing users that use zone aware LB that happens to have a logical DNS cluster defined.  

How about we instead rewrite the priority of the LLB that is used to always be 0? Since we enforce that there is ever only one host, the priority value shouldn't matter, so it seems safe to just coerce it into 0 during cluster creation?

Comment (mattklein123) [reply source/common/upstream/logical_dns_cluster.cc]: Yeah that seems reasonable to me and maybe also emit a warning?

File: source/common/upstream/cluster_manager_impl.cc (hunk 1 above)
Comment (mattklein123) [reply source/common/upstream/cluster_manager_impl.cc]: ping
