### PR TITLE
Unroot docker examples and fix stdout permissions in container

### LINKED ISSUE #11506: examples/front-proxy tutorial is broken
I'm using Docker for Mac and for some reason the example proxy in examples/front-proxy cannot bind to 0.0.0.0:80 inside the container.

    front-envoy_1  | [2020-06-08 21:04:27.772][7][critical][main] [source/server/server.cc:100] error initializing configuration '/etc/front-envoy.yaml': cannot bind '0.0.0.0:80': Permission denied

`docker run --rm -p 80:80 nginx` works fine. 

So it makes me think something’s wrong with the docker-compose config. I unfortunately don't know enough to contribute.

### LINKED ISSUE #11551: Getting permission denied on latest dev image for access logs
```
- filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: envoy_egress
          upgrade_configs:
          - upgrade_type: "CONNECT"          
          access_log:
            name: envoy.file_access_log
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout

```
When the envoy-dev container is started it gives out following error, can someone help out here.
```
proxy_1        | [2020-06-11 06:29:12.117][6][critical][main] [source/server/server.cc:100] error initializing configuration '/etc/envoy/envoy.yaml': unable to open file '/dev/stdout': Permission denied
proxy_1        | [2020-06-11 06:29:12.130][6][info][main] [source/server/server.cc:685] exiting
proxy_1        | unable to open file '/dev/stdout': Permission denied
```

Image: envoyproxy/envoy-dev:92e608f066b017d664d8fa161cfc735f0c6b41e7

### PR DESCRIPTION
**Pull request by phlax**
Commit Message: Update examples to use non-well known ports and not the root user
Additional Description:
I have updated `80` -> `8000` for any ports I could see that were exposed by an `envoy` container.

I left one example (`load-reporting-service`) using port `80` and instead added the `ENVOY_UID` env var

Some docs (eg `docs/root/start/sandboxes`) that have port `80` coded in relation to these examples, have been updated

Also adds fix for `envoy` permissions on `/dev/stdout` and `/dev/stderr`

Risk Level: Low
Testing: Manual testing
Docs Changes: 
- Sandbox examples updated to reflect port changes 
- Note added about `uid/gid` of container user

Release Notes: N/A
Fix #11506 
Fix #11551

### CODE REVIEW

**Comment by phlax** [comment]
@junr03 i have updated the relevant docs - not sure if there are others - but these seem to be the ones that directly referenced the port `80` settings.

I have again committed separately - but will happily squash

**Comment by phlax** [comment]
also, im wondering if i should add a doc about the `ENVOY_UID` setting. Adding to the existing `load_reporting_service` example seems a bit arbitrary

**Comment by junr03** [comment]
> also, im wondering if i should add a doc about the `ENVOY_UID` setting.

Yes, please.

/wait

**Comment by phlax** [comment]
documentation added

**Comment by lu4t** [comment]
Adding a comment and link to this issue: 

https://github.com/envoyproxy/envoy/issues/11679

as @dio requested....

**Comment by phlax** [comment]
@lu4t @dio - i updated the docs to use `py3-pip` - but then i saw #11679 so i can remove this commit in favour of that pr if required

**Comment by junr03** [comment]
@lu4t @dio does this look good to both of you?

**Comment by dio** [comment]
Looks good, just a question: @phlax, do you want to tackle the access issue to `/dev/stdout` here as well (since it is related to privileged access too)? Thank you!

**Comment by phlax** [comment]
@dio i added a fix for permissions on `/dev/stdout`.

I also added it for `/dev/stderr` on the basis that a config may well use that pipe too.

I have tested the built image with the `fault-injection` example and this seems to work ok. 

I wasn't entirely clear where the `envoy-dev` image is built - but im assuming its based on the recipe in `ci/Dockerfile-envoy`

File: ci/docker-entrypoint.sh [hunk 1]
```diff
@@ -20,6 +20,7 @@ if [ "$ENVOY_UID" != "0" ]; then
     if [ -n "$ENVOY_GID" ]; then
 	groupmod -g "$ENVOY_GID" envoy
     fi
+    chown envoy:envoy /dev/stdout /dev/stderr
```
Comment (dio) [inline ci/docker-entrypoint.sh:23]: Could you add a comment here?

File: docs/root/start/start.rst [hunk 2]
```diff
@@ -148,6 +148,18 @@ by using a volume.
...
+
+The `uid` and `gid` of this user can be set at runtime using the `ENVOY_UID` and `ENVOY_GID`
+environment variables. This can be done, for example, on the Docker command line:
+
+  $ docker run -d --name envoy -e ENVOY_UID=777 -e ENVOY_GID=777 -p 9901:9901 -p 10000:10000 envoy:v1
+
+This can be useful if you wish to restrict or provide access to `unix` sockets inside the container, or
+for controlling access to an `envoy` socket from outside of the container.
+
+If you wish to run the container as the `root` user you can set `ENVOY_UID` to `0`.
```
Comment (dio) [inline docs/root/start/start.rst:161]: Nit. To use double backticks instead of the single one, e.g. for uid and gid, and other words that need to be rendered inside `<span class="pre"></span>` tag. For example:

image

**Comment by dio** [comment]
> I wasn't entirely clear where the envoy-dev image is built - but im assuming its based on the recipe in ci/Dockerfile-envoy

Yes, you're right.

File: ci/docker-entrypoint.sh (hunk 1 above)
Comment (phlax) [reply ci/docker-entrypoint.sh:24]: comment added

File: docs/root/start/start.rst (hunk 2 above)
Comment (phlax) [reply docs/root/start/start.rst]: updated
