### PR TITLE
http: fix upstream_rq stat increment 

### LINKED ISSUE #3950: Stats - upstream_rq_5xx don't add up with 2xx and rq_total
Total
>cluster.external_app1_http.upstream_rq_total: 37988

2xx
>cluster.external_app1_http.upstream_rq_200: 37981
>cluster.external_app1_http.upstream_rq_2xx: 37981

5xx
>cluster.external_app1_http.upstream_rq_503: 7303
>cluster.external_app1_http.upstream_rq_5xx: 7303

Retries
>cluster.external_app1_http.upstream_rq_retry: 0
>cluster.external_app1_http.upstream_rq_retry_overflow: 0
>cluster.external_app1_http.upstream_rq_retry_success: 0

There are around 7k `5xx` and 0 `retries`.
So how come the `2xx` count is pretty much same as `rq_total` ??

Shouldn't it be like `rq_total` - `5xx` (i.e) 37k - 7k ~= 30k `2xx`  ?
How are those 7k `5xx` not subtracted in `2xx`

[Full Stats Link](https://gist.github.com/tak2siva/25a9bc1c0139a5220a82e663a6021224)

--------------------------------------------------------------------------------------------------
**Additional Info:**

I have a setup like this in k8s

       ( front proxy ) ->       [ Envoy Sidecar ]   ->    [   Envoy Sidecar   ]
                                  [ Gateway]                [external_app_1]                          

Above is the log for `Gateway Envoy Sidecar`

### PR DESCRIPTION
**Pull request by ramaraochavali**
Signed-off-by: Rama <rama.rao@salesforce.com>
*Description*: Increment upstream_rq in case of connection failures also for http1.
*Risk Level*: Low
*Testing*: Added Automated tests
*Docs Changes*: N/A
*Release Notes*: N/A
Fixes #3950

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@mattklein123 PTAL. Fixed upstream_rq increment incase of connection failure in http1. For http2 it seems to work correctly, so just added test validation.

File: source/common/http/http1/conn_pool.cc [hunk 1]
```diff
@@ -145,6 +145,11 @@ void ConnPoolImpl::onConnectionEvent(ActiveClient& client, Network::ConnectionEv
       // The only time this happens is if we actually saw a connect failure.
       host_->cluster().stats().upstream_cx_connect_fail_.inc();
       host_->stats().cx_connect_fail_.inc();
+
+      // Increment the total requests also.
+      host_->cluster().stats().upstream_rq_total_.inc();
```
Comment (mattklein123) [inline source/common/http/http1/conn_pool.cc]: I think it would be better to consolidate this logic and only increment these stats in 1 place. Can you take a look at the other place we do this and move the increment to when the connection pool is first asked for a stream?

**Comment by ramaraochavali** [comment]
@mattklein123 consolidated the logic. PTAL when you get a chance?

File: source/common/http/http1/conn_pool.cc [hunk 2]
```diff
@@ -265,9 +268,7 @@ ConnPoolImpl::StreamWrapper::StreamWrapper(StreamDecoder& response_decoder, Acti
       StreamDecoderWrapper(response_decoder), parent_(parent) {
 
   StreamEncoderWrapper::inner_.getStream().addCallbacks(*this);
-  parent_.parent_.host_->cluster().stats().upstream_rq_total_.inc();
   parent_.parent_.host_->cluster().stats().upstream_rq_active_.inc();
```
Comment (mattklein123) [inline source/common/http/http1/conn_pool.cc]: Arguably rq_active should move also, though, the logic to keep that consistent will be more complicated and I'm not sure it's worth it. Thoughts?

Comment (ramaraochavali) [reply source/common/http/http1/conn_pool.cc]: Yes.It may not be worth the complication.
