### PR TITLE
Fix flaky redirect integration test for H/3

### LINKED ISSUE #25544: ` //test/integration:redirect_integration_test` is (very) flakey
This is failing pretty regularly - testing it locally and its a real deal flake - sometimes passes, sometimes not

In CI its failing fairly often and causing PRs to fail (eg https://github.com/envoyproxy/envoy/pull/25488#issuecomment-1428730776)

The error as posted on above comment is:

```console
test/integration/redirect_integration_test.cc:704
Expected equality of these values:
1
test_server_->counter("cluster.cluster_0.upstream_internal_redirect_succeeded_total") ->value()
Which is: 0
```

I believe this started with #23648 (after reverting i didnt trigger) cc @pksohn (if not it began at ~same time, apologies)

### PR DESCRIPTION
**Pull request by pksohn**
Should fix #25544.

Commit Message: Fix a flaky redirect integration test for HTTP/3.
Additional Description: This test fails when the check for a counter happens before deferred logging (a new HTTP/3 feature) is complete. 
Risk Level: Test only.

### CODE REVIEW

File: test/integration/redirect_integration_test.cc [hunk 1]
```diff
@@ -700,15 +700,15 @@ TEST_P(RedirectIntegrationTest, InternalRedirectHandledByDirectResponse) {
   ASSERT_TRUE(response->waitForEndStream());
   ASSERT_TRUE(response->complete());
   EXPECT_EQ("204", response->headers().getStatusValue());
+  EXPECT_THAT(waitForAccessLog(access_log_name_, 0, true),
+              HasSubstr("302 internal_redirect test-header-value"));
+  // No test header
+  EXPECT_THAT(waitForAccessLog(access_log_name_, 1), HasSubstr("204 direct_response -"));
```
Comment (danzh2010) [inline test/integration/redirect_integration_test.cc:706]: Can you explain why the counter increment has to do with Access logger log()?

**Review by danzh2010 — APPROVED** [review]

**Comment by phlax** [comment]
cc @adisuissa for maintainer stamp
