### PR TITLE
http conn man: stopped filters can add data from encodeTrailers

### LINKED ISSUE #8402: Filter can't add data from encodeTrailers
Calling addEncodedData from the encodeTrailers callback fails when encodeHeaders had previously returned StopIteration.

A filter (e.g. the grpc-json transcoder) wants to turn a headers-only response into a response with a body. And StreamEncoderFilterCallbacks::addEncodedData allows that:

     1) If a headers only response needs to be turned into a response with a body, this method can
     be called to add body in the encodeHeaders() callback. Subsequent filters will receive
     encodeHeaders(..., false) followed by encodeData(..., true). This works both in the direct
     iteration as well as the continuation case.

However it doesn't work when upstream sends a header frame and a trailer frame:
The filter returns StopIteration from `encodeHeaders`.
In `encodeTrailers`, it calls `addEncodedData`.
`ConnectionManagerImpl::ActiveStream::addEncodedData` has a special branch for EncodeTrailers, which calls encodeData with the comment:

    // In this case we need to inline dispatch the data to further filters. If those filters
    // choose to buffer/stop iteration that's fine.

Now there are two cases: 
1) if there is another filter, encodeData will call its encodeData callback, and then fail the `ASSERT(headers_continued_)` in `ActiveStreamFilterBase::commonHandleAfterDataCallback` - this filter never had its encodeHeaders called.
2) if there is no filter to iterate, ActiveStream::encodeData will call `response_encoder_->encodeData` and write response body before writing any headers.

For HTTP/1.1 downstream it will assume chunked transfer-encoding and write something like:

    4
    body
    HTTP/1.1 200 OK
    other: headers

How to fix that:

For EncodeTrailers, the ActiveStream::addEncodedData should buffer data when filter stopped iteration.

### PR DESCRIPTION
**Pull request by ascheglov**
Now filters can return StopIteration from encodeHeaders,
and then call addEncodedData from encodeTrailers.

This allows the JsonTranscoderFilter to properly transcode gRPC status
in trailer headers into a JSON reply body.

Risk Level: Low
Testing: manual testing, unit-tests, integration tests in gRPC JSON transcoder filter.
Documentation: n/a
Release notes: n/a
Fixes #8402

### CODE REVIEW

File: test/common/http/conn_manager_impl_test.cc [hunk 1]
```diff
@@ -2917,6 +2917,65 @@ TEST_F(HttpConnectionManagerImplTest, FilterAddBodyInTrailersCallback) {
...
+  setupFilterChain(2, 1);
+
+  EXPECT_CALL(*decoder_filters_[0], decodeHeaders(_, false))
+      .WillOnce(Return(FilterHeadersStatus::StopIteration));
+
+  Buffer::OwnedImpl trailers_data("hello");
+  EXPECT_CALL(*decoder_filters_[0], decodeTrailers(_))
+      .WillOnce(InvokeWithoutArgs([&]() -> FilterTrailersStatus {
+        decoder_filters_[0]->callbacks_->addDecodedData(trailers_data, false);
+        return FilterTrailersStatus::Continue;
```
Comment (mattklein123) [inline test/common/http/conn_manager_impl_test.cc]: Can you add a similar parallel test in which the filter decode/encodeTrailers() callbacks continue to stop iteration and then do a continuation later outside of callback context?

Comment (ascheglov) [reply test/common/http/conn_manager_impl_test.cc]: done
