### PR TITLE
http: strip additional invalid h/2 response headers

### LINKED ISSUE #3788: Remove invalid h/2 response headers
Currently when Envoy receives a h/2 response with Connection specific headers (like `keep-alive`) it will fail with: `Invalid HTTP header field was received`

This is due to [nghttp explicitly disallowing these headers](https://github.com/nghttp2/nghttp2/blob/842509dab604e6cc62f7fb98d448294c6ec85763/lib/nghttp2_http.c#L206). This is in accordance with the h/2 spec: https://tools.ietf.org/html/rfc7540#section-8.1.2.2 , which states that these headers should not be present in h/2 messages.

It seems like Envoy should be stripping these headers when converting a h/1.1 response into a h/2 response, or maybe just blindly strip these for h/2 given that they'll cause a protocol error downstream.

### PR DESCRIPTION
**Pull request by snowp**
This removes the keep-alive and proxy-connection headers from http/2
response headers. These headers are explcitly called out in
https://tools.ietf.org/html/rfc7540#section-8.1.2.2 headers as headers
that should be removed in http/2. The RFC calls out other headers as
well, but they seem to be covered by the existing logic.

Signed-off-by: Snow Pettersen <snowp@squareup.com>

*Risk Level*: Low, small spec compliance fix
*Testing*: Added unit tests
*Docs Changes*: N/A
*Release Notes*: N/A

Fixes #3788

### CODE REVIEW

File: source/common/http/conn_manager_utility.cc [hunk 1]
```diff
@@ -319,6 +319,11 @@ void ConnectionManagerUtility::mutateResponseHeaders(Http::HeaderMap& response_h
     response_headers.insertRequestId().value(*request_headers.RequestId());
   }
 
+  if (protocol == Protocol::Http2) {
```
Comment (snowp) [inline source/common/http/conn_manager_utility.cc]: thinking out loud: should we also remove Upgrade? it's also mentioned in the RFC

Comment (alyssawilk) [reply source/common/http/conn_manager_utility.cc]: tl;dr let's leave it as-is for now.

Per https://tools.ietf.org/html/draft-mcmanus-httpbis-h2-websockets-02 when we do upgrade over h2 connect, we won't be using the upgrade headers on the H2-H2 hop.  That said, we've had some discussion of how we want to handle normalizing websocket.   We don't want things like the CORS filter to have to look at CONNECT for H2 and GET/Upgrade:Websocket for HTTP/1.    The plan of record is to have the websocket data traverse the Envoy filter chain normalized to HTTP/1.1 so we'd turn successful H2 bootstrapped/connect/websocket into HTTP/1 Upgrade:Websocket when we read it in from the H2 codec, pass it through Envoy, and then convert it back when serializing back to H2.   So I think for this header, we'll strip it at the H2 codec.

File: source/common/http/conn_manager_utility.cc [hunk 2]
```diff
@@ -319,6 +319,11 @@ void ConnectionManagerUtility::mutateResponseHeaders(Http::HeaderMap& response_h
...
+    response_headers.removeKeepAlive();
```
Comment (alyssawilk) [inline source/common/http/conn_manager_utility.cc]: Isn't this a hop by hop header which we should clear for HTTP/1.1 as well?  We clear it for both H2 and H1 on the request path.

I'm having trouble finding anything in the spec about proxy connection but given we clear consistently in the request headers I wonder if it's the same

Comment (snowp) [reply source/common/http/conn_manager_utility.cc]: I suspected so, but I didn't have any documentation at hand like I did for h/2, so I only did h/2 to begin with. At this point I'm pretty sure it's the same so I'll remove the protocol check.
