### PR TITLE
upstream: update host's socket factory when metadata is updated.

### LINKED ISSUE #16536: transport_socket_matches doesn't update properly when endpoint metadata updates
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: transport_socket_matches doesn't update properly when endpoint metadata updates

*Description*:
When an endpoint metadata is updated, the transport_socket_matches doesn't update accordingly

*Repro steps*:
Envoy config:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 15000
node:
  id: id
  cluster: test
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: outbound
          http_filters:
          - name: envoy.router
  clusters:
  - name: outbound
    connect_timeout: 0.25s
    type: EDS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    max_requests_per_connection: 1
    common_lb_config:
      locality_weighted_lb_config: {}
    eds_cluster_config:
      eds_config:
        path: ./eds.yaml
    transport_socket_matches:
    - match:
        tlsMode: istio
      name: tlsMode-istio
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: httpbin.org
    - match: {}
      name: tlsMode-disabled
      transport_socket:
        name: envoy.transport_sockets.raw_buffer
```

Where eds.yaml is one of:

"EDS tls"
```yaml
resources:
- "@type": type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
  clusterName: outbound
  endpoints:
  - lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 127.0.0.1
            portValue: 8080
      metadata:
        filterMetadata:
          envoy.transport_socket_match:
            tlsMode: istio
```

or "EDS no tls"
```yaml
resources:
- "@type": type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
  clusterName: outbound
  endpoints:
  - lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 127.0.0.1
            portValue: 8080
```

I ran `mitmdump -p 8080 --mode reverse:http://httpbin.org -v` locally as the upstream server which will accept HTTPS and HTTP and give info about which was used.

Behavior:
* With "EDS TLS", https is used
* With "EDS no TLS", plaintext is used
* If I start with "EDS TLS", then switch to "EDS no TLS", HTTPS is still used, and vice versa

When I do the switch, I can see  envoy logging
```
transport socket match, socket tlsMode-disabled selected for host with address 127.0.0.1:8080
transport socket match, socket tlsMode-istio selected for host with address 127.0.0.1:8080
transport socket match, socket tlsMode-disabled selected for host with address 127.0.0.1:8080
transport socket match, socket tlsMode-istio selected for host with address 127.0.0.1:8080
```

but the behavior isn't actually changing.

cc @incfly

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
Update host's socket factory when metadata is updated.

Additional Description:
During dynamic endpoint updates via EDS, `BaseDynamicClusterImpl::updateDynamicHostList` method
tries to minimize deletions/insertions. If only metadata was changed, endpoint is updated in-place by calling `HostDescriptionImpl::metadata`, which updates metadata but not fields dependent on metadata. In particular, 
if metadata's transport socket matcher was changed, socket_factory was not updated. 
Risk Level: Low
Testing: added unit test
Docs Changes: no
Release Notes: no 
Platform Specific Features:
Fixes #16536

### CODE REVIEW

File: source/common/upstream/upstream_impl.h [hunk 1]
```diff
@@ -107,6 +107,8 @@ class HostDescriptionImpl : virtual public HostDescription,
   void metadata(MetadataConstSharedPtr new_metadata) override {
     absl::WriterMutexLock lock(&metadata_mutex_);
     metadata_ = new_metadata;
+    // Update data members dependent on metadata.
```
Comment (lambdai) [inline source/common/upstream/upstream_impl.h:110]: Could  resolveTransportSocketFactory be moved out of the lock guard?
The referenced Metadata should be immutable and valid.

Comment (cpakulski) [reply source/common/upstream/upstream_impl.h:110]: @lambdai I can add a scope around the lock to unlock it before calling `resolveTransportSocketFactory`. Why do you think it is necessary? Deadlock?

Comment (lambdai) [reply source/common/upstream/upstream_impl.h:110]: Sorry for the late reply.
It's not necessary but nice to have. 
The only reason is performance. `resolveTransportSocketFactory` doesn't need the lock to protecting

Comment (lambdai) [reply source/common/upstream/upstream_impl.h:110]: Take it or leave it. It's probably not a bottleneck.

auto factory = resolveTransportSocketFactory(address_, new_metadata.get());
{
 absl::WriterMutexLock lock(&amp;metadata_mutex_);    
 metadata_ = new_metadata;
 socket_factory_ = factory;
}

File: source/common/upstream/upstream_impl.h [hunk 2]
```diff
@@ -178,7 +183,7 @@ class HostDescriptionImpl : virtual public HostDescription,
   Outlier::DetectorHostMonitorPtr outlier_detector_;
   HealthCheckHostMonitorPtr health_checker_;
   std::atomic<uint32_t> priority_;
-  Network::TransportSocketFactory& socket_factory_;
+  std::reference_wrapper<Network::TransportSocketFactory> socket_factory_;
```
Comment (lizan) [inline source/common/upstream/upstream_impl.h:186]: This needs a `ABSL_GUARDED_BY` annotation as well? Should this use same mutex as metadata?

Comment (cpakulski) [reply source/common/upstream/upstream_impl.h]: Annotation added . 
Yeah, after checking the code layout I believe that it is possible that metadata update and creating a new upstream connection (which needs access to transport socket factory) to happen at the same time on different threads. To protect against race conditions, a mutex around socket_factory_ has been added.

**Review by lizan — APPROVED** [review]
/assign-from @envoyproxy/maintainers
for non-tetrands review

File: test/common/upstream/eds_test.cc [hunk 3]
```diff
@@ -117,7 +147,7 @@ class EdsTest : public testing::Test {
 
   bool initialized_{};
   Stats::TestUtil::TestStore stats_;
-  Ssl::MockContextManager ssl_context_manager_;
+  testing::NiceMock<Ssl::MockContextManager> ssl_context_manager_;
```
Comment (jmarantz) [inline test/common/upstream/eds_test.cc:150]: I don't think you need to qualify with `testing::` per below.

File: test/common/upstream/eds_test.cc [hunk 4]
```diff
@@ -452,6 +482,49 @@ TEST_F(EdsTest, EndpointMetadata) {
...
+  auto health_checker = std::make_shared<MockHealthChecker>();
+  EXPECT_CALL(*health_checker, start());
+  EXPECT_CALL(*health_checker, addHostCheckCompleteCb(_)).Times(2);
+  cluster_->setHealthChecker(health_checker);
+
+  // Add single endpoint to the cluster.
+  auto* endpoints = cluster_load_assignment.add_endpoints();
+  auto* endpoint = endpoints->add_lb_endpoints();
+
+  endpoint->mutable_endpoint()->mutable_address()->mutable_socket_address()->set_address("1.2.3.4");
```
Comment (jmarantz) [inline test/common/upstream/eds_test.cc:503]: make a temp for `endpoint->mutable_endpoint()->mutable_address()->mutable_socket_address()`

File: test/common/upstream/eds_test.cc [hunk 5]
```diff
@@ -452,6 +482,49 @@ TEST_F(EdsTest, EndpointMetadata) {
...
+  endpoint->mutable_endpoint()->mutable_address()->mutable_socket_address()->set_port_value(80);
+
+  doOnConfigUpdateVerifyNoThrow(cluster_load_assignment);
+
+  auto& hosts = cluster_->prioritySet().hostSetsPerPriority()[0]->hosts();
+  EXPECT_EQ(hosts.size(), 1);
```
Comment (jmarantz) [inline test/common/upstream/eds_test.cc:509]: ASSERT_EQ here (needs to return from test-method at this point if it fails to avoid crashing below).

File: test/common/upstream/eds_test.cc [hunk 6]
```diff
@@ -452,6 +482,49 @@ TEST_F(EdsTest, EndpointMetadata) {
...
+
+  // Verify that default transport socket is raw (does not implement secure transport).
+  ASSERT_FALSE((hosts[0].get())->transportSocketFactory().implementsSecureTransport());
```
Comment (jmarantz) [inline test/common/upstream/eds_test.cc:512]: conversely I think this can be EXPECT_FALSE (continues testing on failure)

File: test/common/upstream/eds_test.cc [hunk 7]
```diff
@@ -452,6 +482,49 @@ TEST_F(EdsTest, EndpointMetadata) {
...
+
+  // Create metadata with transport socket match pointing to secure mode.
+  auto metadata = new envoy::config::core::v3::Metadata();
+  MetadataConstSharedPtr metadata_sharedptr(metadata);
+  Envoy::Config::Metadata::mutableMetadataValue(
```
Comment (jmarantz) [inline test/common/upstream/eds_test.cc:517]: probably don't need `Envoy::` qual here either

File: test/common/upstream/eds_test.cc [hunk 8]
```diff
@@ -452,6 +482,49 @@ TEST_F(EdsTest, EndpointMetadata) {
...
+      *metadata, Envoy::Config::MetadataFilters::get().ENVOY_TRANSPORT_SOCKET_MATCH, "secure")
+      .set_string_value("enabled");
+
+  // Update metadata.
+  dynamic_cast<HostImpl*>(hosts[0].get())->metadata(metadata_sharedptr);
```
Comment (jmarantz) [inline test/common/upstream/eds_test.cc:522]: why do we need the dynamic_cast? It looks like metadata is an override; not just defined on `HostImpl`.

I'd put `hosts[0]` in a temp also.

File: test/common/upstream/eds_test.cc [hunk 9]
```diff
@@ -452,6 +482,49 @@ TEST_F(EdsTest, EndpointMetadata) {
...
+
+  // Transport socket factory should point to tls, which implements secure transport.
+  ASSERT_TRUE((hosts[0].get())->transportSocketFactory().implementsSecureTransport());
```
Comment (jmarantz) [inline test/common/upstream/eds_test.cc:525]: This can definitely be an EXPECT_EQ.

File: source/common/upstream/upstream_impl.h [hunk 10]
```diff
@@ -103,8 +104,16 @@ class HostDescriptionImpl : virtual public HostDescription,
...
   void metadata(MetadataConstSharedPtr new_metadata) override {
-    absl::WriterMutexLock lock(&metadata_mutex_);
-    metadata_ = new_metadata;
+    auto& new_socket_factory = resolveTransportSocketFactory(address_, new_metadata.get());
+    {
+      absl::WriterMutexLock lock(&metadata_mutex_);
+      metadata_ = new_metadata;
+    }
+    {
+      absl::WriterMutexLock lock(&socket_factory_mutex_);
```
Comment (jmarantz) [inline source/common/upstream/upstream_impl.h:113]: is it semantically sound to have a separate lock for the socket factory? If there's a thread wakeup between these two locks will there be an inconsistent view of the data?

**Review by jmarantz — COMMENTED** [review]
Some superficial comments here. I think someone that knows the semantics of this corner of the code also needs to review.

File: source/common/upstream/upstream_impl.h (hunk 10 above)
Comment (cpakulski) [reply source/common/upstream/upstream_impl.h]: Simplified it and one mutex is used to protect metadata_ and fields dependent on it - in this case socket_factory_.

**Review by jmarantz — APPROVED** [review]
Thanks, looks much better.

This was pre-existing but most people I know including myself have seen worse performance from reader/writer locks vs just plain locks. This was pre-existing though.

**Comment by cpakulski** [comment]
@jmarantz Thanks for reviewing and explaining issue with locks.

**Review by jmarantz — COMMENTED** [review]
@lizan do you want to to do a final senior maintainer pass?

**Review by lizan — APPROVED** [review]
