### PR TITLE
lua: Fix printing Lua string containing hex characters

### LINKED ISSUE #17975: Lua filter's bodyBuffer be truncated when contain two-digit hexadecimal
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
Lua filter's bodyBuffer be truncated when string contain two-digit hexadecimal.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
```
http_filters:
     - name: envoy.filters.http.lua
     typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inline_code: |
                 function envoy_on_request(request_handle)
                     request_handle:body():setBytes("prefix\x00suffix")
                     local body_str = request_handle:body():getBytes(0, request_handle:body():length())
                     request_handle:logInfo(body_str)
                 end
```
Log print:
```
[2021-09-03 14:47:43.099][164756][trace][lua] [./source/extensions/filters/common/lua/lua.h:200] marking live N5Envoy10Extensions11HttpFilters3Lua19StreamHandleWrapperE at 0x7bbc8f88f18
[2021-09-03 14:47:43.099][164756][debug][lua] [source/extensions/filters/http/lua/lua_filter.cc:230] resuming body due to end stream
[2021-09-03 14:47:43.099][164756][trace][lua] [./source/extensions/filters/common/lua/lua.h:130] creating N5Envoy10Extensions7Filters6Common3Lua13BufferWrapperE at 0x7bbc8f73fa8
[2021-09-03 14:47:43.100][164756][trace][lua] [./source/extensions/filters/common/lua/lua.h:130] creating N5Envoy10Extensions11HttpFilters3Lua16HeaderMapWrapperE at 0x7bbc8f8a960
[2021-09-03 14:47:43.100][164756][info][lua] [source/extensions/filters/http/lua/lua_filter.cc:795] script log: prefix
[2021-09-03 14:47:43.100][164756][debug][lua] [source/extensions/filters/common/lua/lua.cc:39] coroutine finished
```
The body be truncated, print these:
```
[2021-09-03 14:47:43.100][164756][info][lua] [source/extensions/filters/http/lua/lua_filter.cc:795] script log: prefix
```

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)
```
{
 "version": "1b9c688997f5e25cc73d27b68cdad4fb0396f2a9/1.20.0-dev/Modified/DEBUG/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "11.120",
 "command_line_options": {
  "base_id": "0",
  "use_dynamic_base_id": false,
  "base_id_path": "",
  "concurrency": 4,
  "config_path": "grpc-bridge-envoy-proxy.yaml",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "ignore_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "trace",
  "component_log_level": "",
  "log_format": "[%Y-%m-%d %T.%e][%t][%l][%n] [%g:%#] %v",
  "log_format_escaped": false,
  "log_path": "",
  "service_cluster": "",
  "service_node": "",
  "service_zone": "",
  "drain_strategy": "Gradual",
  "mode": "Serve",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "disabled_extensions": [],
  "bootstrap_version": 0,
  "enable_fine_grain_logging": false,
  "socket_path": "@envoy_domain_socket",
  "socket_mode": 0,
  "enable_core_dump": false,
  "hidden_envoy_deprecated_max_stats": "0",
  "hidden_envoy_deprecated_max_obj_name_len": "0",
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "900s"
 },
 "node": {
  "id": "",
  "cluster": "",
  "dynamic_parameters": {},
  "user_agent_name": "envoy",
  "user_agent_build_version": {
   "version": {
    "major_number": 1,
    "minor_number": 20,
    "patch": 0
   },
   "metadata": {
    "revision.sha": "1b9c688997f5e25cc73d27b68cdad4fb0396f2a9",
    "build.label": "dev",
    "ssl.version": "BoringSSL",
    "build.type": "DEBUG",
    "revision.status": "Modified"
   }
  },
  "extensions": [
   {
    "name": "envoy.filters.http.lua",
    "category": "envoy.filters.http",
    "type_descriptor": "",
    "disabled": false
   },
   {
    "name": "envoy.lua",
    "category": "envoy.filters.http",
    "type_descriptor": "",
    "disabled": false
   },
   {
    "name": "envoy.router",
    "category": "envoy.filters.http",
    "type_descriptor": "",
    "disabled": false
   }
  ],
  "client_features": [],
  "listening_addresses": [],
  "hidden_envoy_deprecated_build_version": "1b9c688997f5e25cc73d27b68cdad4fb0396f2a9/1.20.0-dev/Modified/DEBUG/BoringSSL"
 },
 "uptime_current_epoch": "1599s",
 "uptime_all_epochs": "1599s"
}

```
>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

### PR DESCRIPTION
**Pull request by Patrick0308**
Commit Message: Fix printing Lua string containing hex characters.
Additional Description:
Risk Level: Low
Testing: Unit test
Docs Changes: N/A
Release Notes: Added

Fixes #17975

Signed-off-by: Patrick <patrickjiang0530@gmail.com>

### CODE REVIEW

**Comment by Patrick0308** [comment]
@wbpcode PTAL

File: source/extensions/filters/common/lua/wrappers.cc [hunk 1]
```diff
@@ -67,7 +67,9 @@ int BufferWrapper::luaGetBytes(lua_State* state) {
 
 int BufferWrapper::luaSetBytes(lua_State* state) {
   data_.drain(data_.length());
-  absl::string_view bytes = luaL_checkstring(state, 2);
+  size_t input_size;
+  const char* input = luaL_checklstring(state, 2, &input_size);
+  absl::string_view bytes = absl::string_view(input, input_size);
```
Comment (wbpcode) [inline source/extensions/filters/common/lua/wrappers.cc:72]: May be we can wrapper these code into a function? Because we repeat these code in multiple positions?

Comment (wbpcode) [reply source/extensions/filters/common/lua/wrappers.cc:72]: We also need some new test case to cover these new codes.

**Review by wbpcode — CHANGES_REQUESTED** [review]
Thanks. This is looks great. And I added some comments.

File: source/extensions/filters/common/lua/wrappers.cc (hunk 1 above)
Comment (Patrick0308) [reply source/extensions/filters/common/lua/wrappers.cc:72]: ok

**Comment by Patrick0308** [comment]
@wbpcode PTAL

File: test/extensions/filters/http/lua/lua_filter_test.cc [hunk 2]
```diff
@@ -2392,6 +2392,31 @@ TEST_F(LuaHttpFilterTest, LuaFilterSetResponseBufferChunked) {
   EXPECT_EQ(Http::FilterDataStatus::Continue, filter_->encodeData(response_body, true));
 }
 
+TEST_F(LuaHttpFilterTest, LuaBodyBufferSetBytesWithHex) {
```
Comment (wbpcode) [inline test/extensions/filters/http/lua/lua_filter_test.cc:2395]: We also need a use case to test the string contains zero.

**Review by wbpcode — CHANGES_REQUESTED** [review]
Looks great. Thanks for your contribution. Just some new comments. And we also need to format codes with `tools/code_format/check_format.py fix`.

**Comment by wbpcode** [comment]
In addition, try not to use force push. Force push is not friendly to reviewers 🤣 . Thanks.

**Comment by Patrick0308** [comment]
@wbpcode Sorry, I pushed force because I forget sign off.

File: test/extensions/filters/http/lua/lua_filter_test.cc (hunk 2 above)
Comment (Patrick0308) [reply test/extensions/filters/http/lua/lua_filter_test.cc:2395]: >  contains zero
Does it means empty string?

Comment (wbpcode) [reply test/extensions/filters/http/lua/lua_filter_test.cc:2395]: I may not describe it clearly. I mean a string containing embedded zeros ('\0'), not an empty string.  @Patrick0308

**Comment by Patrick0308** [comment]
@wbpcode PTAL

File: source/extensions/filters/common/lua/wrappers.h [hunk 3]
```diff
@@ -11,6 +11,7 @@ namespace Filters {
 namespace Common {
 namespace Lua {
 
+
```
Comment (dio) [inline source/extensions/filters/common/lua/wrappers.h]: Nit. We can remove this :)

File: source/extensions/filters/common/lua/lua.h [hunk 4]
```diff
@@ -69,6 +69,15 @@ namespace Lua {
   lua_pushnumber(state, val);                                                                      \
   lua_settable(state, -3);
 
+/**
+ * Check string from lua with length
+ */
+inline absl::string_view checkLuaStringWithLength(lua_State* state, int arg) {
```
Comment (dio) [inline source/extensions/filters/common/lua/lua.h:75]: `getStringViewFromLuaString()`? And adding `doxygen`-like comment will be really appreciated. Something like:

```
/**
 * Get absl::string_view from Lua string. This checks if the argument at index is a string
 * And build a nabsl::string_view from it.   
 * @param state the current Lua state.
 * @param index the index of argument.
 * @return absl::string_view of Lua string with proper string length.
 **/
```

File: source/extensions/filters/common/lua/lua.h [hunk 5]
```diff
@@ -69,6 +69,19 @@ namespace Lua {
...
+/**
+ * Get absl::string_view from Lua string. This checks if the argument at index is a string
+ * and build an absl::string_view from it.
+ * @param state the current Lua state.
+ * @param index the index of argument.
+ * @return absl::string_view of Lua string with proper string length.
+ **/
+inline absl::string_view getStringViewFromLuaString(lua_State* state, int arg) {
+  size_t input_size;
+  const char* input = luaL_checklstring(state, arg, &input_size);
```
Comment (dio) [inline source/extensions/filters/common/lua/lua.h:81]: Can you clarify that if this fails, we return an empty string?

Comment (wbpcode) [reply source/extensions/filters/common/lua/lua.h:81]: @dio From the source code of LuaJIT, `luaL_checklstring` will throws an error if this is invalid.

File: source/extensions/filters/common/lua/lua.h [hunk 6]
```diff
@@ -69,6 +69,19 @@ namespace Lua {
...
 
+/**
+ * Get absl::string_view from Lua string. This checks if the argument at index is a string
+ * and build an absl::string_view from it.
+ * @param state the current Lua state.
+ * @param index the index of argument.
+ * @return absl::string_view of Lua string with proper string length.
+ **/
+inline absl::string_view getStringViewFromLuaString(lua_State* state, int arg) {
+  size_t input_size;
```
Comment (wbpcode) [inline source/extensions/filters/common/lua/lua.h:80]: Please init `input_size` with zero.

File: source/extensions/filters/common/lua/lua.h (hunk 5 above)
Comment (Patrick0308) [reply source/extensions/filters/common/lua/lua.h:81]: `luaL_checklstring` is similar with `luaL_checkstring`. It also return the size by an additional parameter.

**Review by wbpcode — CHANGES_REQUESTED** [review]
Looks great. Thanks for your contribution and patience. Only last comment. And after fix this comment, we can move this to the next step. Thanks again.
cc @dio

File: source/extensions/filters/common/lua/lua.h (hunk 5 above)
Comment (dio) [reply source/extensions/filters/common/lua/lua.h:81]: Yes. I know that it has been the default behavior for these `luaL_check*` APIs. I think we can have a comment on this.

File: test/extensions/filters/http/lua/lua_filter_test.cc [hunk 7]
```diff
@@ -841,7 +842,7 @@ TEST_F(LuaHttpFilterTest, HttpCall) {
   response_message->body().add(response, 8);
   EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq(":status 200")));
   EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("8")));
-  EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("resp")));
+  EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("resp0nse")));
```
Comment (dio) [inline test/extensions/filters/http/lua/lua_filter_test.cc:845]: Sorry, why we do have this additional `0nse` again?

File: test/extensions/filters/http/lua/lua_filter_test.cc [hunk 8]
```diff
@@ -2392,6 +2393,54 @@ TEST_F(LuaHttpFilterTest, LuaFilterSetResponseBufferChunked) {
   EXPECT_EQ(Http::FilterDataStatus::Continue, filter_->encodeData(response_body, true));
 }
```
Comment (dio) [inline test/extensions/filters/http/lua/lua_filter_test.cc:2395]: Add a comment here explaining what the test is doing will be helpful.

File: test/extensions/filters/http/lua/lua_filter_test.cc [hunk 9]
```diff
@@ -2392,6 +2393,54 @@ TEST_F(LuaHttpFilterTest, LuaFilterSetResponseBufferChunked) {
...
+  Http::TestResponseHeaderMapImpl response_headers{{":status", "200"}};
+  EXPECT_EQ(Http::FilterHeadersStatus::StopIteration,
+            filter_->encodeHeaders(response_headers, false));
+
+  Buffer::OwnedImpl response_body("");
+  EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("G1111")));
+  EXPECT_EQ(Http::FilterDataStatus::Continue, filter_->encodeData(response_body, true));
+  EXPECT_EQ(5, encoder_callbacks_.buffer_->length());
+}
+
```
Comment (dio) [inline test/extensions/filters/http/lua/lua_filter_test.cc:2421]: Comment here as well.

**Review by dio — COMMENTED** [review]
Thank you @Patrick0308 for working on this. Looks good. Asking for more comments since some of the tests are not obvious to me.

File: test/extensions/filters/http/lua/lua_filter_test.cc (hunk 7 above)
Comment (Patrick0308) [reply test/extensions/filters/http/lua/lua_filter_test.cc:845]: At pervious test, `request_hanle:logTrace(body)` want to print "resp\0nse". However, testing:StrEq can not handling this situation with string contains '\0'. So I change `request_handle:logTrace(body)` to  `request_handle:logTrace(string.sub(body, 1, 4) .. string.byte(body, 5) .. string.sub(body, 6, 8))`.

File: source/extensions/filters/common/lua/lua.h (hunk 5 above)
Comment (Patrick0308) [reply source/extensions/filters/common/lua/lua.h:81]: > a sample output in the log

Is it means catch the error, and print error msg in the log?

File: test/extensions/filters/http/lua/lua_filter_test.cc (hunk 7 above)
Comment (wbpcode) [reply test/extensions/filters/http/lua/lua_filter_test.cc:845]: It would be better to just keep only one line log body in the lua script.

```
request_handle:logTrace(body)
```

And use only one `EXPECT_CALL` to validate it. Remote all others unnecessary `EXPECT_CALL`.

```
EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq(std::string(response, 8))));
```

But I have no particular insistence on this.

File: test/extensions/filters/http/lua/lua_filter_test.cc [hunk 10]
```diff
@@ -2393,6 +2393,7 @@ TEST_F(LuaHttpFilterTest, LuaFilterSetResponseBufferChunked) {
   EXPECT_EQ(Http::FilterDataStatus::Continue, filter_->encodeData(response_body, true));
 }
 
+// bodyBuffer should not truncated when bodyBuffer set hex character
```
Comment (wbpcode) [inline test/extensions/filters/http/lua/lua_filter_test.cc:2396]: May be:
```
Test the case that updating the body buffer with a string with hex characters.
```

File: test/extensions/filters/http/lua/lua_filter_test.cc [hunk 11]
```diff
@@ -2419,6 +2420,7 @@ TEST_F(LuaHttpFilterTest, LuaBodyBufferSetBytesWithHex) {
   EXPECT_EQ(5, encoder_callbacks_.buffer_->length());
 }
 
+// bodyBuffer should not truncated when bodyBuffer set zero
```
Comment (wbpcode) [inline test/extensions/filters/http/lua/lua_filter_test.cc:2423]: May be:
```
Test the case that updating the body buffer with a string with embedded zero ('\0').
```

File: source/extensions/filters/common/lua/lua.h [hunk 12]
```diff
@@ -69,6 +69,19 @@ namespace Lua {
...
+/**
+ * Get absl::string_view from Lua string. This checks if the argument at index is a string
+ * and build an absl::string_view from it.
+ * @param state the current Lua state.
+ * @param index the index of argument.
+ * @return absl::string_view of Lua string with proper string length.
+ **/
+inline absl::string_view getStringViewFromLuaString(lua_State* state, int arg) {
+  size_t input_size = 0;
+  const char* input = luaL_checklstring(state, arg, &input_size);
```
Comment (wbpcode) [inline source/extensions/filters/common/lua/lua.h:81]: According to @dio 's comments, we also need to add a comment here to explain the case of parameter errors (the case that `luaL_checklstring` cannot get valid string).

**Review by wbpcode — CHANGES_REQUESTED** [review]
Thanks. Thank you very much for your patience and contribution. 🌹 

I think there is no big problem with the code itself. But comments seem to have some problems. 

But I'm not a native English speaker either, so let's see if @dio has some suggestions for changes.

File: source/extensions/filters/common/lua/lua.h [hunk 13]
```diff
@@ -69,6 +69,19 @@ namespace Lua {
...
   lua_settable(state, -3);
 
+/**
+ * Get absl::string_view from Lua string. This checks if the argument at index is a string
+ * and build an absl::string_view from it.
+ * @param state the current Lua state.
+ * @param index the index of argument.
+ * @return absl::string_view of Lua string with proper string length.
+ **/
+inline absl::string_view getStringViewFromLuaString(lua_State* state, int arg) {
```
Comment (dio) [inline source/extensions/filters/common/lua/lua.h:79]: nit. change `arg` to `index` to match the comment above.

File: source/extensions/filters/common/lua/lua.h (hunk 5 above)
Comment (dio) [reply source/extensions/filters/common/lua/lua.h:81]: A comment is enough for now. For example:

```
  // When the argument at index in Lua state is not a string, for example, giving a table to
  // logTrace (which uses this function under the hood), Lua script exits with an error like the
  // following: "[string \"...\"]:3: bad argument #1 to 'logTrace' (string expected, got table)".
  // However, "luaL_checklstring" accepts a number as its argument and implicitly converts it to a
  // string, since Lua provides automatic conversion between string and number values at run time
  // (https://www.lua.org/manual/5.1/manual.html#2.2.1).

```

Optionally you can add a test, for example in lua_filter_test.cc as it is easier (?). This also depicts the current behavior of this filter, which can be useful when one wants to implement a feature like: `fail-close/fail-open` https://github.com/envoyproxy/envoy/issues/14980.

```c++
// Script logging a table instead of the expected string.
TEST_F(LuaHttpFilterTest, LogTableInsteadOfString) {
  const std::string LOG_TABLE{R"EOF(
    function envoy_on_request(request_handle)
      request_handle:logTrace({})
    end
  )EOF"};

  InSequence s;
  setup(LOG_TABLE);

  Http::TestRequestHeaderMapImpl request_headers{{":path", "/"}};
  EXPECT_CALL(*filter_, scriptLog(spdlog::level::err, StrEq("[string \"...\"]:3: bad argument #1 to 'logTrace' (string expected, got table)")));
  EXPECT_EQ(Http::FilterHeadersStatus::Continue, filter_->decodeHeaders(request_headers, true));
}

```

**Review by dio — DISMISSED** [review]
Looks good. Thank you!

**Comment by dio** [comment]
Oops. Sorry that I missed asking for adding an entry in: docs/root/version_history/current.rst.

Please add something like:

```
* lua: Fix printing Lua string containing hex characters.
```

File: source/extensions/filters/common/lua/lua.h [hunk 14]
```diff
@@ -69,6 +69,24 @@ namespace Lua {
...
+ * @param index the index of argument.
+ * @return absl::string_view of Lua string with proper string length.
+ **/
+inline absl::string_view getStringViewFromLuaString(lua_State* state, int index) {
+  size_t input_size = 0;
+  // When the argument at index in Lua state is not a string, for example, giving a table to
+  // logTrace (which uses this function under the hood), Lua script exits with an error like the
+  // following: "[string \"...\"]:3: bad argument #1 to 'logTrace' (string expected, got table)".
+  // However,`luaL_checklstring` accepts a number as its argument and implicitly converts it to a
+  // string, since Lua provides automatic conversion between string and number values at run time
```
Comment (dio) [inline source/extensions/filters/common/lua/lua.h:85]:
```suggestion
  // string, since Lua provides automatic conversion between string and number values at run time
  // (https://www.lua.org/manual/5.1/manual.html#2.2.1).
```

**Comment by Patrick0308** [comment]
@dio Previously, bodyBuffer set string with hex characters will be truncated too.

**Comment by Patrick0308** [comment]
Sorry, I made a mistake when resolving conflict. It requested review from many people.

**Review by dio — APPROVED** [review]
Thank you!

**Comment by wbpcode** [comment]
Thanks. Waiting @envoyproxy/senior-maintainers for a second review.

**Review by mattklein123 — APPROVED** [review]
Thanks!
