### PR TITLE
network dns: fix AUTO settings to properly fallback to v4 lookup when v6 returns only cname entries

### LINKED ISSUE #2634: DNS lookup AUTO settings doesn't fallback to V4 when a single CNAME entry is returned
*Title*: *DNS lookup AUTO settings doesn't fallback to V4 when a single CNAME entry is returned*

*Description*:
I am just getting started with envoy, so I might be wrong here and missing something. 

When working with a cluster that has a host address with a single CNAME entry returned for IPv6 lookups, envoy will not fallback to do a lookup using IPv4. From looking at the code at dns_impl.cc it looks like envoy assumes that if a success code (ARES_SUCCESS) is returned from getHostByName then it is assumed that an ip address was returned. This is not necessarily the case. A DNS request may contain only a CNAME entry with no IP. For example this happens to me with s3.amazonaws.com. Setting V4_ONLY solves the problem. Here is the dig output for IPv6 and IPv4:

```
$ dig s3.amazonaws.com AAAA

; <<>> DiG 9.10.3-P4-Ubuntu <<>> s3.amazonaws.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34567
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0005 , udp: 4096
;; QUESTION SECTION:
;s3.amazonaws.com.              IN      AAAA

;; ANSWER SECTION:
s3.amazonaws.com.       5       IN      CNAME   s3-1.amazonaws.com.

;; AUTHORITY SECTION:
s3-1.amazonaws.com.     5       IN      SOA     ns-1726.awsdns-23.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86
```
*Repro steps*:
Use following envoy.yaml file:
```yaml
admin:
  access_log_path: "admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto          
          idle_timeout: 300s
          access_log:
          - name: envoy.file_access_log
            config:
              path: "egress_http.log"
          stat_prefix: egress_http
          http_protocol_options: 
            allow_absolute_url: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_s3
          http_filters: 
            - name: envoy.router
              config: {}          
  clusters:
  - name: service_s3
    type: logical_dns
    lb_policy: round_robin                                                                                                                                                
    connect_timeout: 1s
    http_protocol_options: {}    
    # dns_lookup_family: V4_ONLY    
    hosts:
    - socket_address:
        address: s3.amazonaws.com      
        port_value: 443
    tls_context: 
      sni: "s3.amazonaws.com"
    
```
Run envoy and then use curl to test out a simple request from s3:
```
curl -v --proxy http://localhost:10000 http://s3.amazonaws.com/my-test-bucket22/
*   Trying ::1...
* connect to ::1 port 10000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 10000 (#0)
> GET http://s3.amazonaws.com/my-test-bucket22/ HTTP/1.1
> Host: s3.amazonaws.com
> User-Agent: curl/7.47.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Fri, 16 Feb 2018 15:41:24 GMT
< server: envoy
<
* Connection #0 to host localhost left intact
no healthy upstream
```
*Work around*: un-comment the line: `dns_lookup_family: V4_ONLY` in the yaml file. Then curl will succeed:
```
 curl -v --proxy http://localhost:10000 http://s3.amazonaws.com/my-test-bucket22/
*   Trying ::1...
* connect to ::1 port 10000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 10000 (#0)
> GET http://s3.amazonaws.com/my-test-bucket22/ HTTP/1.1
> Host: s3.amazonaws.com
> User-Agent: curl/7.47.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< x-amz-id-2: fnwlOvun/jf7YAeI7eMlYm50XlhMoeXzeYu3tfCXY1SbZGvFChRrD+zo1vDFS3s0eoLqhyl9a64=
< x-amz-request-id: 302CF4548DD2CF9A
< date: Fri, 16 Feb 2018 15:46:58 GMT
< x-amz-bucket-region: us-east-1
< content-type: application/xml
< server: envoy
< x-envoy-upstream-service-time: 184
< transfer-encoding: chunked
<
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>my-test-bucket22</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>test.txt</Key><LastModified>2018-02-16T15:23:08.000Z</LastModified><ETag>&quot;0b26e313ed4a7ca6904b0e9369e5b957&quot;</ETag><Size>19</Size><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
```

Would be happy to submit a PR to fix this. Just want to be sure I am not missing something basic before moving forward.

### PR DESCRIPTION
**Pull request by glicht**
network dns: fix AUTO settings to properly fallback to v4 lookup when v6 returns only cname entries

*Description*:

Fixes #2634

Fixed dns_impl.cc to assume completed only when actual ips are returned from a v6 lookup.

*Risk Level*: Low 

*Testing*:
* Added unit tests to test the CNAME scenario where a v6 lookup returns only cnames. 
* Manual testing as described at #2634

*Release Notes*: N/A

### CODE REVIEW

**Comment by alyssawilk** [comment]
@junr03 you up for doing first pass?

File: test/common/network/dns_impl_test.cc [hunk 1]
```diff
@@ -107,31 +124,78 @@ class TestDnsServerQuery {
...
+        if (q_type == T_A) {
+          response_ip_rest_len =
+              ips != nullptr ? ips->size() * (ip_name_len + RRFIXEDSZ + sizeof(in_addr)) : 0;
+        } else {
+          response_ip_rest_len =
+              ips != nullptr ? ips->size() * (ip_name_len + RRFIXEDSZ + sizeof(in6_addr)) : 0;
+        }
+        size_t response_cname_len =
+            encodedCname.size() > 0 ? name_len + RRFIXEDSZ + encodedCname.size() + 1 : 0;
+        // Send response to client.
```
Comment (junr03) [inline test/common/network/dns_impl_test.cc]: This comment makes this section a little confusing. 

Previously, we computed all the elements of the response and then wrote them all to the client. 

In this PR we have moved to computing and writing in lockstep on each piece of the request. 

I think we should either refactor to how it was previously done (compute then write all),  or change the comments (the one this review comment hangs off of, add a comment above line 171 `size_t response_ip_rest_len`, etc)

File: test/common/network/dns_impl_test.cc [hunk 2]
```diff
@@ -107,31 +124,78 @@ class TestDnsServerQuery {
...
+        }
+        const char* hostLookup = name;
+        const unsigned char* ip_question = question;
+        long ip_name_len = name_len;
+        std::string encodedCname;
+        if (cname.size() > 0) {
+          hostLookup = cname.c_str();
+          encodedCname = TestDnsServerQuery::encodeDnsName(cname);
+          ip_question = reinterpret_cast<const unsigned char*>(encodedCname.c_str());
+          ip_name_len = encodedCname.size() + 1;
```
[the remark this answers is not in the document]
Comment (glicht) [reply test/common/network/dns_impl_test.cc]: +1, as the encoded cname format always ends with a null (0) char which also needs to written out. Will add this in a comment.

File: test/common/network/dns_impl_test.cc (hunk 1 above)
Comment (glicht) [reply test/common/network/dns_impl_test.cc]: I agree the cname flow is a bit confusing. First there is need to see if a domain name resolves to a cname entry. Then there is need to lookup the cname record to see if it resolves to an ip or multiple ips. We still need to compute the total response size before starting to write each response element. This is computed with the variable: `response_size_n`. After writing out the header response, then we need to write out all response elements which include the cname entry and the ips. I'll add a comment to better explain this logic.

**Comment by junr03** [comment]
@alyssawilk looks fine to me. Want to give a pass?

File: test/common/network/dns_impl_test.cc [hunk 3]
```diff
@@ -43,19 +44,36 @@ namespace {
...
 
   ~TestDnsServerQuery() { connection_->close(ConnectionCloseType::NoFlush); }
 
+  // Utility to encode a dns string in the rfc format. Example: \004some\004good\006domain
+  // RFC link: https://www.ietf.org/rfc/rfc1035.txt
+  static std::string encodeDnsName(const std::string& input) {
+    auto name_split = StringUtil::splitToken(input, ".");
+    std::string res;
+    for (const auto& it : name_split) {
+      res += static_cast<char>(it.size());
```
Comment (alyssawilk) [inline test/common/network/dns_impl_test.cc]: Can you toss in an assert on the total size, just to make it super clear it won't work with illegally long DNS names?

File: test/common/network/dns_impl_test.cc [hunk 4]
```diff
@@ -107,31 +125,81 @@ class TestDnsServerQuery {
...
+              ips != nullptr ? ips->size() * (ip_name_len + RRFIXEDSZ + sizeof(in_addr)) : 0;
+        } else {
+          response_ip_rest_len =
+              ips != nullptr ? ips->size() * (ip_name_len + RRFIXEDSZ + sizeof(in6_addr)) : 0;
+        }
+        size_t response_cname_len =
+            encodedCname.size() > 0 ? name_len + RRFIXEDSZ + encodedCname.size() + 1 : 0;
+        const uint16_t response_size_n =
+            htons(response_base_len + response_ip_rest_len + response_cname_len);
+        Buffer::OwnedImpl write_buffer_;
```
Comment (alyssawilk) [inline test/common/network/dns_impl_test.cc]: If this is local scope you don't need the trailing _ - that's only for member variables

File: test/common/network/dns_impl_test.cc [hunk 5]
```diff
@@ -107,31 +125,81 @@ class TestDnsServerQuery {
...
         memcpy(response_base, request, response_base_len);
         DNS_HEADER_SET_QR(response_base, 1);
         DNS_HEADER_SET_AA(response_base, 0);
-        DNS_HEADER_SET_RCODE(response_base, ips != nullptr ? NOERROR : NXDOMAIN);
-        DNS_HEADER_SET_ANCOUNT(response_base, ips != nullptr ? ips->size() : 0);
+        DNS_HEADER_SET_RCODE(response_base, answer_size > 0 ? NOERROR : NXDOMAIN);
+        DNS_HEADER_SET_ANCOUNT(response_base, answer_size);
         DNS_HEADER_SET_NSCOUNT(response_base, 0);
         DNS_HEADER_SET_ARCOUNT(response_base, 0);
+        // Total response size will be computed according to cname response size + ip response sizes
```
Comment (alyssawilk) [inline test/common/network/dns_impl_test.cc]: Optional - this function is getting reaaally long.  If there's anything else you can easily factor into a utility helper that'd be nice. Optional because it's test code and you've done a great job with comments and variable names.

File: test/common/network/dns_impl_test.cc (hunk 4 above)
Comment (junr03) [reply test/common/network/dns_impl_test.cc]: eyes of a falcon, totally missed it

Comment (glicht) [reply test/common/network/dns_impl_test.cc]: The trailing "_" was present before my changes, so I didn't really give this thought. Anyway, I'll add a commit to change the name of the variable.

File: test/common/network/dns_impl_test.cc (hunk 3 above)
Comment (glicht) [reply test/common/network/dns_impl_test.cc]: Will do

File: test/common/network/dns_impl_test.cc (hunk 5 above)
Comment (glicht) [reply test/common/network/dns_impl_test.cc]: I'll pass on this. I agree the function is getting long. But, I am not too sure that refactoring will make this easier to understand.

**Comment by glicht** [comment]
@alyssawilk, I've added a commit following your code review. Let me know if you see need for more changes.

**Comment by alyssawilk** [comment]
@junr03 LGTY?  I can only force-merge while github has you flagged as having requested changes :-/
