### PR TITLE
Fixes #7617 - fixes handling creation of VHDS subscription after Init…

### LINKED ISSUE #7617: [xDS] VHDS support of subscription creation after initManager.initiliaze()
*Title*: in the case where a VHDS config is sent by management server after the initManager has been initialized, the RDS config update end in programming error. 

*Description*:
> At present a VHDS subscription is started by initManager.initialize(), in the case a newly added VHDS is sent after the initManager been initialized, it ends in programming error when trying to add the init_target_ to the init manager.

*Repro steps*:
> 
1. Management server sends RouteConfiguration w/o VHDS
2. initManager initialize() called, Envoy starts serving.
3. Management server sends RouteConfiguration w/ VHDS 
4. RDS impl tries to create a VHDS subscription, adds an init-target to the initManager which has been initialized, causes an assert failure.

### PR DESCRIPTION
**Pull request by dmitri-d**
…Manager has completed initialization

Signed-off-by: Dmitri Dolguikh <ddolguik@redhat.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description: Fixes https://github.com/envoyproxy/envoy/issues/7617
Risk Level:
Testing: added an integration test
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/7617
[Optional Deprecated:]

### CODE REVIEW

File: source/common/router/rds_impl.cc [hunk 1]
```diff
@@ -130,6 +134,41 @@ void RdsRouteConfigSubscription::onConfigUpdate(
...
+      // up.
+      Init::WatcherImpl noop_watcher(
+          // Note: we just throw it away.
+          fmt::format("VHDS ConfigUpdate watcher {}:{}", route_config_name_, version_info),
+          []() { /*Do nothing.*/ });
+      init_manager->initialize(noop_watcher);
+      // New RDS subscriptions should have been created, now lift the floodgate.
+      // Note in the case of partial acceptance, accepted RDS subscriptions should be started
+      // despite of any error.
+      if (factory_context_.clusterManager().adsMux()) {
```
[the remark this answers is not in the document]
Comment (dmitri-d) [reply source/common/router/rds_impl.cc]: You are indeed right, this isn't needed. Removed.

File: source/common/router/rds_impl.cc [hunk 2]
```diff
@@ -130,6 +134,41 @@ void RdsRouteConfigSubscription::onConfigUpdate(
...
+    std::unique_ptr<Cleanup>& resume_rds) {
+  if (factory_context_.initManager().state() == Init::Manager::State::Initialized) {
+    init_manager = std::make_unique<Init::ManagerImpl>(
+        fmt::format("VHDS {}:{}", route_config_name_, version_info));
+    // Pause RDS to not send a burst of RDS requests until we start all the new subscriptions.
+    // In the case if factory_context_.initManager() is uninitialized, RDS is already paused either
+    // by Server init or LDS init.
+    if (factory_context_.clusterManager().adsMux()) {
+      factory_context_.clusterManager().adsMux()->pause(
+          ConstSingleton<::Envoy::Config::TypeUrlValues>::get().RouteConfiguration);
```
[the remark this answers is not in the document]
Comment (dmitri-d) [reply source/common/router/rds_impl.cc]: Removed pausing/restarting of ADS.

**Comment by dmitri-d** [comment]
@mattklein123: This is just a bugfix, with no changes to existing VHDS functionality, not sure what docs you wanted to go with this PR.

**Comment by mattklein123** [comment]
> @mattklein123: This is just a bugfix, with no changes to existing VHDS functionality, not sure what docs you wanted to go with this PR.

There are no docs for VHDS currently. I'm using these PRs as a forcing function to get docs into the code base. We should have never gotten this far without docs.

File: source/common/router/rds_impl.cc [hunk 3]
```diff
@@ -130,6 +134,41 @@ void RdsRouteConfigSubscription::onConfigUpdate(
   init_target_.ready();
 }
 
+// Initialize a no-op InitManager in case the one in the factory_context has completed
+// initialization. This can happen if an RDS config update for an already established RDS
+// subscription contains VHDS configuration.
+void RdsRouteConfigSubscription::maybeCreateInitManager(
```
[the remark this answers is not in the document]
Comment (dmitri-d) [reply source/common/router/rds_impl.cc]: I'm populating both init_manager and init_vhds method parameters, I think returning just one of them as the result of the method call would be confusing...

**Comment by dmitri-d** [comment]
* rebased, responded to feedback

**Comment by dmitri-d** [comment]
* added a test that verifies creation of a noop init manager

**Comment by dmitri-d** [comment]
ping @lambdai

**Comment by dmitri-d** [comment]
* rebased and squashed the commits

**Comment by zuercher** [comment]
You have a use-after-free error because the `std::unique_ptr<Cleanup>` you can struct has a reference to the `std::unique_ptr<Init::ManagerImpl>`. The init manager is being destroyed first in this test and when the cleanup runs it references freed memory.

Rather than just fixing the ordering in the test, I think it's probably better to figure out a way to remove or make explicit the destruction order dependency.

**Comment by dmitri-d** [comment]
@zuercher: the issue was that the ```route_config_provider``` created by ```route_config_provider_manager_->createRdsRouteConfigProvider``` call was going out of scope and taking the subscription with it.

**Comment by dmitri-d** [comment]
ping @lambdai

**Comment by dmitri-d** [comment]
* rebased

ping @lambdai: I think this is ready to be merged now.

**Comment by dmitri-d** [comment]
* rebased

ping @lambdai

**Comment by lambdai** [comment]
CC @zuercher  for more comments

File: source/common/router/rds_impl.h [hunk 4]
```diff
@@ -111,6 +115,9 @@ class RdsRouteConfigSubscription : Envoy::Config::SubscriptionCallbacks,
     return route_config_providers_;
   }
   RouteConfigUpdatePtr& routeConfigUpdate() { return config_update_info_; }
+  void maybeCreateInitManager(const std::string& version_info,
```
Comment (zuercher) [inline source/common/router/rds_impl.h]: Let's not leak this method into the public API of this class. Is it not possible to test its behavior in the context of onConfigUpdate?

File: test/integration/vhds_integration_test.cc [hunk 5]
```diff
@@ -72,6 +72,16 @@ const char Config[] = R"EOF(
                     cluster_name: xds_cluster
 )EOF";
 
+const char RdsWithoutVhdsConfig[] = R"EOF(
```
Comment (zuercher) [inline test/integration/vhds_integration_test.cc]: We prefer these configs to are created using the protobuf objects directly rather than parsing configs.

File: test/integration/vhds_integration_test.cc [hunk 6]
```diff
@@ -100,6 +110,113 @@ name: my_route
           cluster_name: xds_cluster
 )EOF";
 
+const char VhostTemplate[] = R"EOF(
```
Comment (zuercher) [inline test/integration/vhds_integration_test.cc]: Same as above.

**Comment by mattklein123** [comment]
> @mattklein123 were you documentation concerns addressed?

There is still no documentation merged for VHDS. Since this is a bug fix I won't hold this PR hostage, but nothing else will be merged until there is docs.

File: test/integration/vhds_integration_test.cc (hunk 5 above)
Comment (dmitri-d) [reply test/integration/vhds_integration_test.cc]: This is the first time I hear about this preference. This test suit been around for a while now, with this exact setup (and it's not the only test suite to use yaml for setup). 

FWIW, configurations used in these tests have enough nested fields/protobufs that building them programmatically will be laborious and harder to read.

File: source/common/router/rds_impl.h (hunk 4 above)
Comment (dmitri-d) [reply source/common/router/rds_impl.h]: > Let's not leak this method into the public API of this class
This is a concrete implementation class, not a public interface. I very strongly prefer testability over encapsulation in such a case.

> Is it not possible to test its behavior in the context of onConfigUpdate?

I'm trying to test this in isolation; the setup is already difficult (and fragile) enough without dragging in another method.

**Comment by dmitri-d** [comment]
ping @zuercher, @lambdai

**Comment by dmitri-d** [comment]
* updated with the latest changes from master

File: source/common/router/rds_impl.h (hunk 4 above)
Comment (zuercher) [reply source/common/router/rds_impl.h]: Perhaps make it private and make the test class a friend so that it can access it?

Comment (dmitri-d) [reply source/common/router/rds_impl.h]: That would result in a dependency to test code in production code, would it not?

File: test/integration/vhds_integration_test.cc (hunk 5 above)
Comment (dmitri-d) [reply test/integration/vhds_integration_test.cc]: I disagree re: adding vhds to one of default configs (shared test configuration couples independent tests and can make them brittle), but I see value in adding helper methods to generate VHDS config. Will, but in a separate PR if that's ok.

**Comment by lambdai** [comment]
@dmitri-d My understanding is that it's only a TODO away from @zuercher 's approval on this PR

**Comment by lambdai** [comment]
The rest LGTM

**Comment by dmitri-d** [comment]
* added a todo re: test configuration
* merged latest changes from upstream master

**Comment by dmitri-d** [comment]
ping @lambdai, @zuercher

File: source/common/router/rds_impl.h (hunk 4 above)
Comment (zuercher) [reply source/common/router/rds_impl.h]: I think the friend class statement constitutes a forward reference and needn't ever be declared, but I could be wrong.
