### PR TITLE
test, oauth2: Make sure config test runs field validation

### LINKED ISSUE #13023: Oauth2 extention not work
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Oauth2 extention not work*

*Description*:
Hi All:
When I try to follow  the instruction (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter), to test Oauth2 functionality, but I met the challenge about below when I start envoy, any idea about this? and would like to know what kind of hmac_secret i need to provide. Thx

[2020-09-09 12:02:32.681][14][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #20: [0x563ac830b885]
[2020-09-09 12:02:32.681][14][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #21: [0x563ac76a1dab]
[2020-09-09 12:02:32.681][14][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #22: [0x563ac76a14cd]
[2020-09-09 12:02:32.682][14][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #23: [0x563ac76a23c2]
[2020-09-09 12:02:32.682][14][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #24: [0x563ac76a2783]
[2020-09-09 12:02:32.682][14][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #25: [0x563ac76a0f9c]
[2020-09-09 12:02:32.682][14][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #26: __libc_start_main [0x7f7a631e1b97]
Segmentation fault

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

This is my yaml file setting:

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: auth }
          http_filters:
            - name: auth
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3alpha.OAuth2
                config: 
                  token_endpoint:
                    cluster: auth
                    uri: authorization-server.com/token
                    timeout: 3s
                  authorization_endpoint: https://authorization-server.com/authorize
                  redirect_uri: "https://www.oauth.com/playground/oidc.html"
                  redirect_path_matcher:
                    path:
                      exact: /callback
                  signout_path:
                    path:
                      exact: /signout
                  credentials:
                    client_id: <client_id from Oauth website>
                    token_secret:
                      name: <token from Oauth website>
                    hmac_secret:
                      name: hmac
                  # timeout: 3s
            - name: envoy.filters.http.router

  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 1234
  - name: auth
    connect_timeout: 5s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: auth
      endpoints:
      - lb_endpoints:
        - endpoint:
            address: { socket_address: { address: www.oauth.com, port_value: 443 }}
    tls_context: { sni: www.oauth.com }

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This makes sure config tests for oauth2 filter checks field validations. This also handles possible `nullptr` values for `token_secret` and `hmac_secret` fields due to misconfigurations (for example: `token_secret: {}`). The example config in the docs is also updated.

Risk Level: Low
Testing: Updated
Docs Changes: Updated example config
Release Notes: N/A
Fixes #13023

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

File: test/extensions/filters/http/oauth2/config_test.cc [hunk 1]
```diff
@@ -22,33 +22,101 @@ namespace Oauth2 {
...
     )EOF";
 
-  envoy::extensions::filters::http::oauth2::v3alpha::OAuth2 proto_config;
-  MessageUtil::loadFromYaml(yaml, proto_config, ProtobufMessage::getStrictValidationVisitor());
-  NiceMock<Server::Configuration::MockFactoryContext> factory_context;
-  auto& secret_manager = factory_context.cluster_manager_.cluster_manager_factory_.secretManager();
+  OAuth2Config factory;
+  ProtobufTypes::MessagePtr proto_config = factory.createEmptyConfigProto();
+  TestUtility::loadFromYaml(yaml, *proto_config);
+  testing::StrictMock<Server::Configuration::MockFactoryContext> context;
```
Comment (snowp) [inline test/extensions/filters/http/oauth2/config_test.cc:92]: I think the mocks are strict by default? Does specifying `StrictMock` do anything?

File: test/extensions/filters/http/oauth2/config_test.cc [hunk 2]
```diff
@@ -22,33 +22,101 @@ namespace Oauth2 {
...
+  EXPECT_CALL(context, api());
+  EXPECT_CALL(context, getTransportSocketFactoryContext());
+  Http::FilterFactoryCb cb = factory.createFilterFactoryFromProto(*proto_config, "stats", context);
+  testing::StrictMock<Http::MockFilterChainFactoryCallbacks> filter_callback;
+  EXPECT_CALL(filter_callback, addStreamDecoderFilter(_));
+  cb(filter_callback);
+}
+
+TEST(ConfigTest, InvalidTokenSecret) {
+  // The token secret is correctly loaded, hence expecting invalid HMAC config.
```
Comment (snowp) [inline test/extensions/filters/http/oauth2/config_test.cc:113]: Maybe it would be clearer if we specified the failing secret name instead of the passing one?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks! Just a few comments

File: source/extensions/filters/http/well_known_names.h [hunk 3]
```diff
@@ -81,7 +81,7 @@ class HttpFilterNameValues {
   // AWS Lambda filter
   const std::string AwsLambda = "envoy.filters.http.aws_lambda";
   // OAuth filter
-  const std::string OAuth = "envoy.filters.http.oauth";
+  const std::string OAuth = "envoy.filters.http.oauth2";
```
[the remark this answers is not in the document]
Comment (dio) [reply source/extensions/filters/http/well_known_names.h:84]: Yes. This is for consistency since we print the name of extensions at startup, i.e. `[info][main] [external/envoy/source/server/server.cc:309]: envoy.filters.http: ...`

- 

-

File: test/extensions/filters/http/oauth2/config_test.cc (hunk 2 above)
Comment (dio) [reply test/extensions/filters/http/oauth2/config_test.cc]: Updated.

File: test/extensions/filters/http/oauth2/config_test.cc (hunk 1 above)
Comment (dio) [reply test/extensions/filters/http/oauth2/config_test.cc]: Removed. Seems like I need to clean up the ext_authz one.

**Comment by dio** [comment]
@snowp I think have updated the patch following your comments. Please help to take a look. Thank you!

**Comment by dio** [comment]
My bad. One test was failed since missing secret names.

**Review by snowp — APPROVED** [review]
Thanks!
