### PR TITLE
tls: add CRLDP data to transport failure reason

### LINKED ISSUE #43642: TLS: add CRL-related information to `TRANSPORT_FAILURE_REASON`
*Title*: *TLS: add CRL-related information to TRANSPORT_FAILURE_REASON*

*Description*:
Currently, operators are responsible for providing and maintaining CRLs used by Envoy proxy. CRL verification checks may fail due to not-yet-ready/expired CRLs or missing CRLs (e.g. for a new CRLDP not previously known to operators). 

Similar to previous enhancements that included certificate SANs when SAN validation fails, adding certificate CRLDP and CRL-related error information to the `TRANSPORT_FAILURE_REASON` can help operators quickly troubleshoot issues. 

[optional *Relevant Links*:]

- https://github.com/envoyproxy/envoy/issues/31320 
- https://github.com/envoyproxy/envoy/pull/43069

### PR DESCRIPTION
**Pull request by guydc**
Commit Message: tls: add CRLDP data to transport failure reason 

Additional Description: For errors such as ``unable to get certificate CRL``,  the error message now includes the certificate's CRL distribution points and a clarification that the check is performed against user-defined CRLs (e.g., ``X509_verify_cert: certificate verification error at depth 0: certificate revocation check against provided CRLs failed: unable to get certificate CRL, certificate CRL distribution points: [http://crl.example.com/ca.crl, http://backup-crl.example.com/ca.crl]``)

Risk Level: Low
Testing: Added unit tests
Docs Changes: No
Release Notes: Added
Platform Specific Features: No
Fixes #43642

### CODE REVIEW

File: test/common/tls/utility_test.cc [hunk 1]
```diff
@@ -323,6 +323,46 @@ TEST(UtilityTest, TestGetX509ErrorInfo) {
...
+  EXPECT_TRUE(X509_STORE_CTX_init(store_ctx.get(), ssl_ctx.get(), cert.get(), nullptr));
+  int result = X509_verify_cert(store_ctx.get());
+  EXPECT_EQ(result, 0); // Verification should fail
+  EXPECT_EQ(X509_STORE_CTX_get_error(store_ctx.get()), X509_V_ERR_UNABLE_TO_GET_CRL);
+
+  EXPECT_EQ(
+      Utility::getX509VerificationErrorInfo(store_ctx.get()),
+      "X509_verify_cert: certificate verification error at depth 0: unable to get certificate CRL, "
+      "certificate CRL distribution points: [http://crl.example.com/ca.crl, "
+      "http://backup-crl.example.com/ca.crl]");
```
Comment (ggreenway) [inline test/common/tls/utility_test.cc]: I'm worried that this error will be quite misleading. The text implies that envoy would be fetching the CRL from the distribution point, but the actual error is that the CRL isn't included in Envoy's configuration

Comment (guydc) [reply test/common/tls/utility_test.cc]: Hi @ggreenway, thanks for reviewing. Sure, I changed it to `CRL for certificate was not provided` instead. I think that other error CRL-related errors are sufficiently clear.

Comment (guydc) [reply test/common/tls/utility_test.cc]: actually, seems like ssl_socket_test expects to find the original BoringSSL error messages. I'll wrap them instead.

**Review by ggreenway — APPROVED** [review]
LGTM
