### PR TITLE
postgres: fixed message decoder for Array of Sequence type of messages

### LINKED ISSUE #31674: postgres: filter is not computing metrics in certain cases
When investigating #30952 I've noticed that Postgres filter is stopping to collect metrics in the following conditions:
1. When executing a query returning more than one column like a simple `SELECT 1, 2;` 
2. When a given query throw an error like `SELECT 1/0;`

Just after entering in one of two situations listed above the plugin stop to decode the trafic. For example the tracing outputs below.

For a simple query like `SELECT oid FROM pg_class LIMIT 1` everything works as expected
```
[2024-01-04 15:45:34.696][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_filter.cc:31] [Tags: "ConnectionId":"102"] postgres_proxy (onData): got 39 bytes
[2024-01-04 15:45:34.696][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:338] postgres_proxy (onDataInSync): decoding 39 bytes
[2024-01-04 15:45:34.696][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:340] postgres_proxy (onDataInSync): parsing message, len 39
[2024-01-04 15:45:34.696][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:349] postgres_proxy (onDataInSync): command is Q
[2024-01-04 15:45:34.696][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:378] postgres_proxy (onDataInSync): []
[2024-01-04 15:45:34.696][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:323] (Frontend) command = Q (Query)
[2024-01-04 15:45:34.696][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:324] (Frontend) length = 38
[2024-01-04 15:45:34.696][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:325] (Frontend) message = [SELECT oid FROM pg_class LIMIT 1;]
[2024-01-04 15:45:34.696][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:327] postgres_proxy (processMessageBody): 34 bytes remaining in buffer
[2024-01-04 15:45:34.696][69956][trace][filter] [source/common/tcp_proxy/tcp_proxy.cc:696] [Tags: "ConnectionId":"102"] downstream connection received 39 bytes, end_stream=false
[2024-01-04 15:45:34.699][69956][trace][filter] [source/common/tcp_proxy/tcp_proxy.cc:778] [Tags: "ConnectionId":"102"] upstream connection received 65 bytes, end_stream=false
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_filter.cc:56] [Tags: "ConnectionId":"102"] postgres_proxy (onWrite): got 65 bytes
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:338] postgres_proxy (onDataInSync): decoding 65 bytes
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:340] postgres_proxy (onDataInSync): parsing message, len 65
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:349] postgres_proxy (onDataInSync): command is T
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:378] postgres_proxy (onDataInSync): [Array of 1:{[][0][0][0][0][0][0]}]
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:319] postgres_proxy (processMessageBody): no actions do be processed
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:323] (Backend) command = T (RowDescription)
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:324] (Backend) length = 28
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:325] (Backend) message = [Array of 1:{[oid][1259][1][26][4][4294967295][0]}]
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:327] postgres_proxy (processMessageBody): 60 bytes remaining in buffer
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:338] postgres_proxy (onDataInSync): decoding 36 bytes
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:340] postgres_proxy (onDataInSync): parsing message, len 36
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:349] postgres_proxy (onDataInSync): command is D
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:378] postgres_proxy (onDataInSync): [Array of 1:{[(5 bytes):]}]
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:319] postgres_proxy (processMessageBody): no actions do be processed
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:323] (Backend) command = D (DataRow)
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:324] (Backend) length = 15
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:325] (Backend) message = [Array of 1:{[(5 bytes):49 54 52 49 52]}]
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:327] postgres_proxy (processMessageBody): 31 bytes remaining in buffer
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:338] postgres_proxy (onDataInSync): decoding 20 bytes
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:340] postgres_proxy (onDataInSync): parsing message, len 20
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:349] postgres_proxy (onDataInSync): command is C
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:378] postgres_proxy (onDataInSync): []
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:323] (Backend) command = C (CommandComplete)
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:324] (Backend) length = 13
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:325] (Backend) message = [SELECT 1]
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:327] postgres_proxy (processMessageBody): 15 bytes remaining in buffer
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:338] postgres_proxy (onDataInSync): decoding 6 bytes
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:340] postgres_proxy (onDataInSync): parsing message, len 6
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:349] postgres_proxy (onDataInSync): command is Z
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:378] postgres_proxy (onDataInSync): []
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:319] postgres_proxy (processMessageBody): no actions do be processed
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:323] (Backend) command = Z (ReadyForQuery)
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:324] (Backend) length = 5
[2024-01-04 15:45:34.699][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:325] (Backend) message = [I]
[2024-01-04 15:45:34.699][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:327] postgres_proxy (processMessageBody): 1 bytes remaining in buffer
```

But when trying the query `SELECT oid, relname FROM pg_class LIMIT 1` for three times this is what trace show:
```
[2024-01-04 15:46:10.324][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_filter.cc:31] [Tags: "ConnectionId":"102"] postgres_proxy (onData): got 48 bytes
[2024-01-04 15:46:10.324][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:338] postgres_proxy (onDataInSync): decoding 48 bytes
[2024-01-04 15:46:10.324][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:340] postgres_proxy (onDataInSync): parsing message, len 48
[2024-01-04 15:46:10.324][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:349] postgres_proxy (onDataInSync): command is Q
[2024-01-04 15:46:10.324][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:378] postgres_proxy (onDataInSync): []
[2024-01-04 15:46:10.324][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:323] (Frontend) command = Q (Query)
[2024-01-04 15:46:10.324][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:324] (Frontend) length = 47
[2024-01-04 15:46:10.324][69956][debug][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:325] (Frontend) message = [SELECT oid, relname FROM pg_class LIMIT 1;]
[2024-01-04 15:46:10.324][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:327] postgres_proxy (processMessageBody): 43 bytes remaining in buffer
[2024-01-04 15:46:10.324][69956][trace][filter] [source/common/tcp_proxy/tcp_proxy.cc:696] [Tags: "ConnectionId":"102"] downstream connection received 48 bytes, end_stream=false
[2024-01-04 15:46:10.326][69956][trace][filter] [source/common/tcp_proxy/tcp_proxy.cc:778] [Tags: "ConnectionId":"102"] upstream connection received 110 bytes, end_stream=false
[2024-01-04 15:46:10.326][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_filter.cc:56] [Tags: "ConnectionId":"102"] postgres_proxy (onWrite): got 110 bytes
[2024-01-04 15:46:10.326][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:338] postgres_proxy (onDataInSync): decoding 110 bytes
[2024-01-04 15:46:10.326][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:340] postgres_proxy (onDataInSync): parsing message, len 110
[2024-01-04 15:46:10.326][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:349] postgres_proxy (onDataInSync): command is T
[2024-01-04 15:46:10.326][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_decoder.cc:378] postgres_proxy (onDataInSync): [Array of 0:{}]


[2024-01-04 15:46:17.239][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_filter.cc:31] [Tags: "ConnectionId":"102"] postgres_proxy (onData): got 48 bytes
[2024-01-04 15:46:17.240][69956][trace][filter] [source/common/tcp_proxy/tcp_proxy.cc:696] [Tags: "ConnectionId":"102"] downstream connection received 48 bytes, end_stream=false
[2024-01-04 15:46:17.241][69956][trace][filter] [source/common/tcp_proxy/tcp_proxy.cc:778] [Tags: "ConnectionId":"102"] upstream connection received 110 bytes, end_stream=false
[2024-01-04 15:46:17.241][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_filter.cc:56] [Tags: "ConnectionId":"102"] postgres_proxy (onWrite): got 110 bytes


[2024-01-04 15:46:23.014][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_filter.cc:31] [Tags: "ConnectionId":"102"] postgres_proxy (onData): got 48 bytes
[2024-01-04 15:46:23.015][69956][trace][filter] [source/common/tcp_proxy/tcp_proxy.cc:696] [Tags: "ConnectionId":"102"] downstream connection received 48 bytes, end_stream=false
[2024-01-04 15:46:23.015][69956][trace][filter] [source/common/tcp_proxy/tcp_proxy.cc:778] [Tags: "ConnectionId":"102"] upstream connection received 110 bytes, end_stream=false
[2024-01-04 15:46:23.016][69956][trace][filter] [contrib/postgres_proxy/filters/network/source/postgres_filter.cc:56] [Tags: "ConnectionId":"102"] postgres_proxy (onWrite): got 110 bytes
```

The same weird behavior happen if a given query throw an error.

### PR DESCRIPTION
**Pull request by cpakulski**
Commit Message:
fixed postgres message decoder for `Array of Sequence` type of messages
Additional Description:
There was a bug in message decoder which resulted that only one `Sequence` type was parsed per message.
Results for multiple columns like `SELECT oid, relname FROM pg_class LIMIT 1;` are of `Array of Sequence`, so there may be multiple `Sequence` types. The first `Sequence` was parsed properly but not the subsequent ones.
Risk Level: Low
Testing: Added unit test to cover this case.
Docs Changes: No
Release Notes: No
Platform Specific Features: No
Fixes #31674

### CODE REVIEW

File: contrib/postgres_proxy/filters/network/source/postgres_message.h [hunk 1]
```diff
@@ -350,6 +350,11 @@ template <typename... Types> class MessageImpl : public Message, public Sequence
     uint64_t pos = start_pos;
     uint64_t left = length;
     validation_result_ = Sequence<Types...>::validate(data, start_pos, pos, left);
+    if (validation_result_ != Message::ValidationOK) {
+      return validation_result_;
+    }
+    // verify that parser iterated over entire message and nothing is left.
+    validation_result_ = left == 0 ? Message::ValidationOK : Message::ValidationFailed;
```
Comment (ravenblackx) [inline contrib/postgres_proxy/filters/network/source/postgres_message.h:357]: Seems like this would be both clearer here, and perhaps clearer in coverage that it's not covered by the new test (unless it's covered by an existing test), as an if rather than a ternary. Also shorter, though more lines.
```
if (left != 0) {
  return Message::ValidationFailed;
}
```

**Comment by cpakulski** [comment]
> the problem remains when a query raise an error returning an [ErrorResponse](https://www.postgresql.org/docs/current/protocol-message-formats.html#PROTOCOL-MESSAGE-FORMATS-ERRORRESPONSE) from backend like SELECT 1/0;.

Yes, you are right. This is not related to changes I did for `SELECT oid, relname FROM pg_class`. I found the reason and will code the fix early next week.

File: contrib/postgres_proxy/filters/network/source/postgres_message.h (hunk 1 above)
Comment (cpakulski) [reply contrib/postgres_proxy/filters/network/source/postgres_message.h:357]: Good point with coverage. Thanks!

Comment (cpakulski) [reply contrib/postgres_proxy/filters/network/source/postgres_message.h]: Done.

**Comment by cpakulski** [comment]
@fabriziomello Unless you find that changes in this PR do fix issues described in #31674, I consider this PR ready for the final review.

**Comment by ravenblackx** [comment]
Ping for @fabriziomello

**Comment by fabriziomello** [comment]
> @fabriziomello Unless you find that changes in this PR do fix issues described in #31674, I consider this PR ready for the final review.

Having a look right now!!!

**Review by fabriziomello — APPROVED** [review]
LGTM. Also made several tests on a real Postgres instance and seem now everything is working as expected.

**Review by ravenblackx — APPROVED** [review]
