### PR TITLE
fix: Only append to xfh if it was not the last value appended

### LINKED ISSUE #26286: `X-Forwarded-Host` is appended once per retry
*Title*: `X-Forwarded-Host` is appended once per retry

*Description*:
When Envoy is configured with `auto_host_rewrite` and `retry_policy`, the `Host` header is appended to `X-Forwarded-Host` once per retry attempt. I am not entirely sure whether this is a bug, but it isn't mentioned in the documentation and doesn't match my expectations.

*Repro steps*:
Start Envoy with the configuration below. You can either run `httpbin` locally or just use http://httpbin.org.

Make the following request and observe the response:

```
$ curl localhost:8080/anything
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "deflate, gzip, br, zstd", 
    "Host": "httpbin", 
    "User-Agent": "curl/7.87.0", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "14912", 
    "X-Forwarded-Host": "0.0.0.0:32778,httpbin,httpbin,httpbin"
  }, 
  "json": null, 
  "method": "GET", 
  "origin": "10.255.26.2", 
  "url": "http://0.0.0.0:32778/anything"
}
```

*Admin and Stats Output*:
See https://gist.github.com/joshuaspence/2f2d1ff038c7e5de129d9ab1a04adee8

*Config*:
```yaml
---
static_resources:
  listeners:
    - address:
        socket_address:
          address: '0.0.0.0'
          port_value: 8080
      default_filter_chain:
        filters:
          - name: 'envoy.filters.network.http_connection_manager'
            typed_config:
              '@type': 'type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager'
              stat_prefix: 'ingress_http'
              route_config:
                virtual_hosts:
                  - name: 'default'
                    domains: ['*']
                    routes:
                      - match:
                          prefix: ''
                        route:
                          cluster: 'httpbin'
                          append_x_forwarded_host: true
                          auto_host_rewrite: true
                    retry_policy:
                      retry_on: 'retriable-status-codes'
                      num_retries: 3
                      retriable_status_codes: [200]
              http_filters:
                - name: 'envoy.filters.http.router'
                  typed_config:
                    '@type': 'type.googleapis.com/envoy.extensions.filters.http.router.v3.Router'
              
  clusters:
    - name: 'httpbin'
      type: 'STRICT_DNS'
      load_assignment:
        cluster_name: 'httpbin'
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 'httpbin'
                      port_value: 80
```

*Logs*:
```
basic-envoy-1    | [2023-03-23 02:21:24.469][26][debug][http] [source/common/http/conn_manager_impl.cc:306] [C0] new stream
basic-envoy-1    | [2023-03-23 02:21:24.469][26][debug][http] [source/common/http/conn_manager_impl.cc:972] [C0][S16682388373139477951] request headers complete (end_stream=true):
basic-envoy-1    | ':authority', '0.0.0.0:32780'
basic-envoy-1    | ':path', '/anything'
basic-envoy-1    | ':method', 'GET'
basic-envoy-1    | 'user-agent', 'curl/7.87.0'
basic-envoy-1    | 'accept', '*/*'
basic-envoy-1    | 'accept-encoding', 'deflate, gzip, br, zstd'
basic-envoy-1    | 
basic-envoy-1    | [2023-03-23 02:21:24.469][26][debug][http] [source/common/http/conn_manager_impl.cc:955] [C0][S16682388373139477951] request end stream
basic-envoy-1    | [2023-03-23 02:21:24.469][26][debug][router] [source/common/router/router.cc:470] [C0][S16682388373139477951] cluster 'httpbin' match for URL '/anything'
basic-envoy-1    | [2023-03-23 02:21:24.469][26][debug][router] [source/common/router/router.cc:678] [C0][S16682388373139477951] router decoding headers:
basic-envoy-1    | ':authority', '0.0.0.0:32780'
basic-envoy-1    | ':path', '/anything'
basic-envoy-1    | ':method', 'GET'
basic-envoy-1    | ':scheme', 'http'
basic-envoy-1    | 'user-agent', 'curl/7.87.0'
basic-envoy-1    | 'accept', '*/*'
basic-envoy-1    | 'accept-encoding', 'deflate, gzip, br, zstd'
basic-envoy-1    | 'x-forwarded-proto', 'http'
basic-envoy-1    | 'x-request-id', '7796d4f8-7cc1-4eac-8375-ae94b6ddfdfc'
basic-envoy-1    | 'x-envoy-expected-rq-timeout-ms', '15000'
basic-envoy-1    | 
basic-envoy-1    | [2023-03-23 02:21:24.469][26][debug][router] [source/common/router/upstream_request.cc:581] [C0][S16682388373139477951] pool ready
basic-envoy-1    | [2023-03-23 02:21:24.472][26][debug][router] [source/common/router/router.cc:1363] [C0][S16682388373139477951] upstream headers complete: end_stream=false
basic-envoy-1    | [2023-03-23 02:21:24.472][26][debug][router] [source/common/router/upstream_request.cc:500] [C0][S16682388373139477951] resetting pool request
basic-envoy-1    | [2023-03-23 02:21:24.479][26][debug][router] [source/common/router/router.cc:1783] [C0][S16682388373139477951] performing retry
basic-envoy-1    | [2023-03-23 02:21:24.479][26][debug][router] [source/common/router/upstream_request.cc:581] [C0][S16682388373139477951] pool ready
basic-envoy-1    | [2023-03-23 02:21:24.480][26][debug][router] [source/common/router/router.cc:1363] [C0][S16682388373139477951] upstream headers complete: end_stream=false
basic-envoy-1    | [2023-03-23 02:21:24.480][26][debug][router] [source/common/router/upstream_request.cc:500] [C0][S16682388373139477951] resetting pool request
basic-envoy-1    | [2023-03-23 02:21:24.490][26][debug][router] [source/common/router/router.cc:1783] [C0][S16682388373139477951] performing retry
basic-envoy-1    | [2023-03-23 02:21:24.491][26][debug][router] [source/common/router/upstream_request.cc:581] [C0][S16682388373139477951] pool ready
basic-envoy-1    | [2023-03-23 02:21:24.492][26][debug][router] [source/common/router/router.cc:1363] [C0][S16682388373139477951] upstream headers complete: end_stream=false
basic-envoy-1    | [2023-03-23 02:21:24.492][26][debug][router] [source/common/router/upstream_request.cc:500] [C0][S16682388373139477951] resetting pool request
basic-envoy-1    | [2023-03-23 02:21:24.516][26][debug][router] [source/common/router/router.cc:1783] [C0][S16682388373139477951] performing retry
basic-envoy-1    | [2023-03-23 02:21:24.517][26][debug][router] [source/common/router/upstream_request.cc:581] [C0][S16682388373139477951] pool ready
basic-envoy-1    | [2023-03-23 02:21:24.518][26][debug][router] [source/common/router/router.cc:1363] [C0][S16682388373139477951] upstream headers complete: end_stream=false
basic-envoy-1    | [2023-03-23 02:21:24.518][26][debug][http] [source/common/http/conn_manager_impl.cc:1588] [C0][S16682388373139477951] encoding headers via codec (end_stream=false):
basic-envoy-1    | ':status', '200'
basic-envoy-1    | 'server', 'envoy'
basic-envoy-1    | 'date', 'Thu, 23 Mar 2023 02:21:24 GMT'
basic-envoy-1    | 'content-type', 'application/json'
basic-envoy-1    | 'content-length', '435'
basic-envoy-1    | 'access-control-allow-origin', '*'
basic-envoy-1    | 'access-control-allow-credentials', 'true'
basic-envoy-1    | 'x-envoy-upstream-service-time', '49'
```

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

### PR DESCRIPTION
**Pull request by RiverPhillips**
Commit Message: Only append to xfh if it was not the last value appended
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fixes #26286
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: source/common/http/utility.cc [hunk 1]
```diff
@@ -462,9 +462,19 @@ void Utility::appendVia(RequestOrResponseHeaderMap& headers, const std::string&
 
 void Utility::updateAuthority(RequestHeaderMap& headers, absl::string_view hostname,
                               const bool append_xfh) {
-  if (append_xfh && !headers.getHostValue().empty()) {
-    headers.appendForwardedHost(headers.getHostValue(), ",");
+  // only append to x-forwarded-host if the value was not the last value appended
```
Comment (snowp) [inline source/common/http/utility.cc:465]: We try to keep comments using proper grammar
```suggestion
  // Only append to x-forwarded-host if the value was not the last value appended.
```

**Review by snowp — CHANGES_REQUESTED** [review]
I think this makes sense, but I think this needs to be runtime guarded as it's a behavioral change in the core proxy, see https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#runtime-guarding

It will also need a release note and an update to the API docs to reflect this behavior

**Comment by RiverPhillips** [comment]
@snowp had a bit of a nightmare with the DCO making this look like hundreds of commits. Happy to squash it away if that makes this easier, or we can squash when we merge

**Comment by adisuissa** [comment]
Needs to merge main.

/wait

File: source/common/http/utility.cc [hunk 2]
```diff
@@ -463,9 +463,26 @@ void Utility::appendVia(RequestOrResponseHeaderMap& headers, const std::string&
...
+  if (Runtime::runtimeFeatureEnabled("envoy.reloadable_features.append_xfh_idempotent")) {
+    // Only append to x-forwarded-host if the value was not the last value appended.
+    const auto xfh = headers.getForwardedHostValue();
+
+    if (append_xfh && !host.empty() && !xfh.empty()) {
+      const auto xfh_split = StringUtil::splitToken(xfh, ",");
+      if (!xfh_split.empty() && xfh_split.back() != host) {
+        headers.appendForwardedHost(host, ",");
+      }
+    } else if (append_xfh && !host.empty()) {
```
Comment (adisuissa) [inline source/common/http/utility.cc:477]: nit: these conditions are the same as the first conditions of the previous if statement. This can probably be refactored into:
```
if (append_xfh && !host.empty()) {
  ...
  if (!xfh.empty()) {
    ...
  } else {
    ...
  }
}
```

**Review by adisuissa — COMMENTED** [review]
Thanks. Left a few comments.

File: source/common/runtime/runtime_features.cc [hunk 3]
```diff
@@ -31,6 +31,8 @@
 // problem of the bugs being found after the old code path has been removed.
 RUNTIME_GUARD(envoy_reloadable_features_allow_compact_maglev);
 RUNTIME_GUARD(envoy_reloadable_features_append_query_parameters_path_rewriter);
+RUNTIME_GUARD(envoy_reloadable_features_append_xfh_idempotent);
+RUNTIME_GUARD(envoy_reloadable_features_closer_shadow_behavior);
```
[the remark this answers is not in the document]
Comment (RiverPhillips) [reply source/common/runtime/runtime_features.cc]: Thanks, looks like I messed up a merge

**Comment by RiverPhillips** [comment]
Got it green now, the test suites seem to be very flaky on CI. Is this expected?
