### PR TITLE
sds: Ignore Delta Removals

### LINKED ISSUE #24373: Missing SDS resources for 62ab872c-038e-4311-90bc-74a77cda9f53-webserver-certs in onConfigUpdate()
*Title*: *Missing SDS resources error during config update*

*Description*:
We are using the XDS ADS with incremental mode (DeltaStream) instead of stow and observing an error. We have configured the the source of config for the LDS, CDS, RDS and SDS dynamic resources as ADS. We are using the go control plane snapshot cache to set the new configuration snapshot. In case of the change in the listener filter chain configuration, for example, one of the filter chain is being deleted, the corresponding SDS resource entry is also removed from the configuration. 
However, on SDS config update from the go control plane to the envoy proxy, envoy returns the below error.

*'typeUrl [type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret](http://type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret) error :code:13 message:\"Missing SDS resources for d0232574-dc99-4599-9b92-6b27f10a520d-mtls-certs in onConfigUpdate()'*

*Attaching below the response from @adisuissa  on the slack channel:*

It seems that the error comes from: https://github.com/envoyproxy/envoy/blob/d142c9d55ae9aab34e9924aa25f20bd27635e060/source/common/secret/sds_api.cc#L150
What I think happens here, is that Envoy deletes the subscription, and doesn't expect an update to the resource to be returned.
I guess the way to improve this is to do something like in RDS (https://github.com/envoyproxy/envoy/blob/5b9183f80d6c7ab38877b8f8f48b152509f49d3e/source/common/rds/rds_route_config_subscription.cc#L122). Please open an issue so we can track this.
[sds_api.cc](https://github.com/envoyproxy/envoy/blob/d142c9d55ae9aab34e9924aa25f20bd27635e060/source/common/secret/sds_api.cc)
<https://github.com/[envoyproxy/envoy](https://github.com/envoyproxy/envoy)|envoyproxy/envoy>envoyproxy/envoy | Added by [GitHub](https://envoyproxy.slack.com/services/B01UCCXGF2T)
[rds_route_config_subscription.cc](https://github.com/envoyproxy/envoy/blob/5b9183f80d6c7ab38877b8f8f48b152509f49d3e/source/common/rds/rds_route_config_subscription.cc)

*Repro steps*:
1. Configure envoy config update in DELTA_GRPC with LDS, SDS as dynamic resources
5. Update the listener configuration such that it results in the deletion of SDS resource
6. On SDS resource deletion, go control plane is sending the resource removal update but envoy is responding with an Missing SDS error.

*Logs*:
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret error :code:13  message:\"Missing SDS resources for 62ab872c-038e-4311-90bc-74a77cda9f53-webserver-certs in onConfigUpdate()\" respNonce: 39","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"ResourceNamesSubscribe: [] ResourceNamesUnsubscribe: [] InitialResourceVersions: map[]","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.config.route.v3.RouteConfiguration error :\u003cnil\u003e respNonce: 40","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.config.listener.v3.Listener error :\u003cnil\u003e respNonce: 41","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.config.listener.v3.Listener error :\u003cnil\u003e respNonce: 39","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.config.route.v3.RouteConfiguration error :\u003cnil\u003e respNonce: 39","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret error :code:13  message:\"Missing SDS resources for 62ab872c-038e-4311-90bc-74a77cda9f53-webserver-certs in onConfigUpdate()\" respNonce: 40","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"ResourceNamesSubscribe: [] ResourceNamesUnsubscribe: [] InitialResourceVersions: map[]","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret error :code:13  message:\"Missing SDS resources for 62ab872c-038e-4311-90bc-74a77cda9f53-mtls-fps in onConfigUpdate()\" respNonce: 40","time":"2022-12-05T23:58:09Z"}

### PR DESCRIPTION
**Pull request by keithmattix**
Commit Message: Ignore Delta SDS removals
Additional Description: Fixes #24373 and #32832
Risk Level: Low
Testing: Manual testing with the Istio scenario described in #32832. Investigating how to add a unit test
Docs Changes:
Release Notes: Delta SDS removals will no longer result in a "Missing SDS resources" error message
Platform Specific Features:

### CODE REVIEW

File: source/common/secret/sds_api.cc [hunk 1]
```diff
@@ -154,14 +168,17 @@ void SdsApi::onConfigUpdateFailed(Envoy::Config::ConfigUpdateFailureReason reaso
   init_target_.ready();
 }
 
-absl::Status SdsApi::validateUpdateSize(int num_resources) {
-  if (num_resources == 0) {
+absl::Status SdsApi::validateUpdateSize(uint32_t added_resources_num,
+                                        uint32_t removed_resources_num) {
+  if (added_resources_num + removed_resources_num == 0) {
```
Comment (adisuissa) [inline source/common/secret/sds_api.cc:173]: nit: prefer `(A == 0 && B == 0)`, to avoid overflow (not that it should ever happen in reality, but just to be on the safe side).

File: source/common/secret/sds_api.cc [hunk 2]
```diff
@@ -154,14 +168,17 @@ void SdsApi::onConfigUpdateFailed(Envoy::Config::ConfigUpdateFailureReason reaso
...
   }
-  if (num_resources != 1) {
+  if (added_resources_num > 1 || removed_resources_num > 1) {
     return absl::InvalidArgumentError(
-        fmt::format("Unexpected SDS secrets length: {}", num_resources));
+        fmt::format("Unexpected SDS secrets length for {}, number of added resources "
+                    "{}, number of removed resources {}",
+                    sds_config_name_, added_resources_num, removed_resources_num));
   }
   return absl::OkStatus();
```
Comment (adisuissa) [inline source/common/secret/sds_api.cc:183]: hmm... this seems to allow adding and removing of the resource (which I guess should just be updating the resource) when both added and removed are 1.
To the best of my (limited) understanding SDS should currently be a single-resource subscription. That implies that for a given resource name it should either be in the added part or removed part.

If you think this is incorrect, please point me to a test or config that you are aware of.

**Review by adisuissa — COMMENTED** [review]
Thanks for tackling this issue!
Overall I think this is ok, but I think more tests are needed.
Specifically I think we need to ensure that the owning cluster/listener are actually removing the resource prior to receiving a response with a `removed_resources`,
and tests that exercise the different validation paths.

File: source/common/secret/sds_api.cc (hunk 2 above)
Comment (keithmattix) [reply source/common/secret/sds_api.cc:183]: That was my understanding as well based on the code, but I came across this [test](https://github.com/envoyproxy/envoy/blob/ffcc257e16c9046b2fec7497a6bf9293d8ada286/test/common/secret/sds_api_test.cc#L562) that seemed to imply add + removal is allowed? I'm open to modifying the test though (with a release note clarifying the behavior)

**Comment by keithmattix** [comment]
Thanks for the review @adisuissa!

> Specifically I think we need to ensure that the owning cluster/listener are actually removing the resource prior to receiving a response with a `removed_resources`,
> and tests that exercise the different validation paths.

I'm still getting up to speed on Envoy's testing approaches; is there a section of the integration tests that allow testing the dependent resource flow (specifically with SDS)?

File: source/common/secret/sds_api.cc (hunk 2 above)
Comment (adisuissa) [reply source/common/secret/sds_api.cc:183]: Interesting. I don't have enough context on this test.
@htuch seems the test was added [here](https://github.com/envoyproxy/envoy/commit/73c46c9aba2c032f8fccb32e1b2c0c7a1df25a8d#diff-8e5f56463d7c4e0a70b111fef53b4e4d535b3c690b901441834fc4c891989167R138-R166)  (that you've reviewed and maybe you have some context), and we are wondering whether an xDS response of a single resource in delta-xDS can have both add/update and remove included?

**Comment by keithmattix** [comment]
>  Specifically I think we need to ensure that the owning cluster/listener are actually removing the resource prior to receiving a response with a removed_resources,

I added an integration test that I think covers this; I'd appreciate feedback! I also modified the implementation so that removing a secret won't complete cluster warming.

File: source/common/secret/sds_api.cc (hunk 2 above)
Comment (htuch) [reply source/common/secret/sds_api.cc:180]: I don't think this was really deliberate AFAIU. It's been a long time so I don't have much context to add, but it seems a case where you could go either way with behaviors (ignore an unrelated or nonsensical removal, or perhaps a strong error like a NACK), this seems reasonable.

Comment (keithmattix) [reply source/common/secret/sds_api.cc:180]: Yeah testing that we don't NACK makes sense. I'm more inclined to keep this behavior for stability's sake and since the spec tends to be permissive of nonsensical removals

File: test/integration/ads_integration_test.cc [hunk 3]
```diff
@@ -236,6 +236,93 @@ TEST_P(AdsIntegrationTest, ClusterInitializationUpdateOneOfThe2Warming) {
   test_server_->waitForGaugeGe("cluster_manager.active_clusters", 4);
 }
 
+TEST_P(AdsIntegrationTest, DeltaSdsRemovals) {
```
Comment (adisuissa) [inline test/integration/ads_integration_test.cc:239]: This test LGTM, but I wonder whether it should be here (ads_integration_test.cc) or in the sds integration tests.
Looking at the test it seems it only needs the sds to be updated, and if that's the case, I think it should be moved there.

Also, please add a short comment describing what the test validates and why it only relates to delta-xDS.

**Review by adisuissa — COMMENTED** [review]
Overall LGTM, thanks!
Left on comment on the organization of the integration test, but otherwise LGTM.

**Comment by adisuissa** [comment]
Assigning Harvey as a senior-maintainer reviewer in the domain.
/assign @htuch

File: test/integration/ads_integration_test.cc (hunk 3 above)
Comment (adisuissa) [reply test/integration/ads_integration_test.cc:239]: Ah, I see.
LGTM, thanks!

File: source/common/secret/sds_api.h [hunk 4]
```diff
@@ -92,7 +92,7 @@ class SdsApi : public Envoy::Config::SubscriptionBase<
   Api::Api& api_;
 
 private:
-  absl::Status validateUpdateSize(int num_resources);
+  absl::Status validateUpdateSize(uint32_t added_resources_num, uint32_t removed_resources_num);
```
[the remark this answers is not in the document]
Comment (keithmattix) [reply source/common/secret/sds_api.h:95]: Done!

File: test/integration/ads_integration_test.cc [hunk 5]
```diff
@@ -236,6 +236,93 @@ TEST_P(AdsIntegrationTest, ClusterInitializationUpdateOneOfThe2Warming) {
...
+  // This test is for delta only
```
Comment (adisuissa) [inline test/integration/ads_integration_test.cc:240]: Please add a comment why this is only relevant to Delta-xDS and not SotW.

Also comments style-guide, comments need to end with '.'.

**Review by adisuissa — DISMISSED** [review]
LGTM, thanks!
One minor comment.

File: test/integration/ads_integration_test.cc (hunk 5 above)
Comment (keithmattix) [reply test/integration/ads_integration_test.cc]: Ack; done!

**Review by howardjohn — APPROVED** [review]

**Review by adisuissa — APPROVED** [review]

File: source/common/secret/sds_api.cc (hunk 2 above)
Comment (htuch) [reply source/common/secret/sds_api.cc:186]: I think this behavior is fine to retain, but please add a comment explaining what's going on for posterity.

File: source/common/secret/sds_api.cc [hunk 6]
```diff
@@ -143,13 +143,24 @@ absl::Status SdsApi::onConfigUpdate(const std::vector<Config::DecodedResourceRef
...
+                       const Protobuf::RepeatedPtrField<std::string>& removed_resources,
+                       const std::string&) {
+  const absl::Status status = validateUpdateSize(added_resources.size(), removed_resources.size());
   if (!status.ok()) {
     return status;
   }
+
+  if (removed_resources.size() == 1) {
+    // We only removed a resource here; don't go through the SotW init process
+    // and expect this to be cleaned up by the owning cluster or listener.
```
Comment (htuch) [inline source/common/secret/sds_api.cc:157]: Please expand on the comment here. I think the key idea is this is a singleton resource subscription, so in normal operation, an xDS server should not be removing the resource until the referencing cluster / listener is no longer using it. 

@adisuissa why don't we structurally forbid singleton resource subscriptions from having removals in the baseline xDS infra, wondering why something like SDS needs to worry about this?

**Review by htuch — COMMENTED** [review]
I think this is right - if you look at what eds.cc is doing, it just ignores the removed resources for delta. LGTM modulo comments.

File: source/common/secret/sds_api.cc (hunk 6 above)
Comment (keithmattix) [reply source/common/secret/sds_api.cc:157]: +1 to enforcing this in the generic xDS machinery. I also think more documentation around "singleton" resources would be helpful as well; in any case, I've expanded the comment

**Review by htuch — DISMISSED** [review]
LGTM, thanks!

**Review by htuch — APPROVED** [review]

**Review by adisuissa — APPROVED** [review]
