### PR TITLE
rds: validate config in depth before update config dump

### LINKED ISSUE #7939: [config] /config_dump shows rejected RDS config vs the last valid RDS config envoy is running
*config*: */config_dump shows rejected RDS config vs the last valid RDS config envoy is running*

*Description*:
When triaging an invalid RDS config on our fleet, /config_dump showed the version sha of the bad config, rather than version sha envoy was running (which was the last valid configuration). So when a new box came up that was not able to serve traffic, config_dump showed the same sha, making it very difficult to debug. 

We ended up realizing RDS was being rejected via startup logs and update_rejected stat. But we should have solved it faster of config_dump showed the last valid version sha.

*Repro steps*:
Have the control plane send RDS config with a duplicate domain.

*Logs*:
```
[2019-08-13 22:21:07.185][31248][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:72] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Only unique values for domains are permitted. Duplicate entry of domain maptiles-staging.lyft.net
```

### PR DESCRIPTION
**Pull request by lizan**
Description:
Route config need deep validation for virtual host duplication check, regex check, per filter config validation etc, which PGV wasn't enough.

Risk Level: Low
Testing: regression test
Docs Changes: N/A
Release Notes: N/A
Fixes #7939

### CODE REVIEW

File: source/common/router/rds_impl.cc [hunk 1]
```diff
@@ -99,6 +99,11 @@ void RdsRouteConfigSubscription::onConfigUpdate(
     throw EnvoyException(fmt::format("Unexpected RDS configuration (expecting {}): {}",
                                      route_config_name_, route_config.name()));
   }
+  for (auto* provider : route_config_providers_) {
+    // This seems inefficient, though it is necessary to validate config in each context,
+    // especially when it comes with per_filter_config,
+    provider->validateConfig(route_config);
```
Comment (htuch) [inline source/common/router/rds_impl.cc]: @stevenzzzz FYI, keep in mind we need to retain this behavior in the world of SRDS.

File: test/common/router/rds_impl_test.cc [hunk 2]
```diff
@@ -493,6 +493,93 @@ TEST_F(RouteConfigProviderManagerImplTest, onConfigUpdateWrongSize) {
...
+  setup();
+  EXPECT_CALL(*factory_context_.cluster_manager_.subscription_factory_.subscription_, start(_));
+  factory_context_.init_manager_.initialize(init_watcher_);
+
+  const std::string response1_json = R"EOF(
+{
+  "version_info": "1",
+  "resources": [
+    {
+      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
```
Comment (htuch) [inline test/common/router/rds_impl_test.cc]: Can you use YAML for examples? it's more concise and the canonical text proto representation in Envoy.

File: test/common/router/rds_impl_test.cc [hunk 3]
```diff
@@ -493,6 +493,93 @@ TEST_F(RouteConfigProviderManagerImplTest, onConfigUpdateWrongSize) {
...
+      ]
+    }
+  ]
+}
+)EOF";
+  auto response1 = TestUtility::parseYaml<envoy::api::v2::DiscoveryResponse>(response1_json);
+
+  EXPECT_CALL(init_watcher_, ready());
+
+  EXPECT_THROW(rds_callbacks_->onConfigUpdate(response1.resources(), response1.version_info()),
```
Comment (htuch) [inline test/common/router/rds_impl_test.cc]: Can you explain why we should expect a throw here? I.e. what's throw-worthy in the config?

File: source/common/router/rds_impl.cc (hunk 1 above)
Comment (stevenzzzz) [reply source/common/router/rds_impl.cc]: SG. This is another reason RDS should move to the config-provider-framework. Where RDSSubscription holds a single RDSProvider and this sort of validation(ConfigImpl instantiation) happens before update propagation.

File: test/common/router/rds_impl_test.cc (hunk 3 above)
Comment (lizan) [reply test/common/router/rds_impl_test.cc]: done

File: test/common/router/rds_impl_test.cc (hunk 2 above)
Comment (lizan) [reply test/common/router/rds_impl_test.cc]: done

File: source/common/router/rds_impl.cc (hunk 1 above)
Comment (lizan) [reply source/common/router/rds_impl.cc]: > Where RDSSubscription holds a single RDSProvider

@stevenzzzz This is not the case because RDS is being used in multiple context and each context needs its own provider, that's what we address here. We may want to limit that flexibility but it will be hard to do so without breaking API compatibility.
