### PR TITLE
subset loadbalancing: respect overprovisioning factor and weighted priority health overrides

### LINKED ISSUE #24916: Overprovisioning factor is ignored when subset load balancing is enabled
*Title*: *Overprovisioning factor is ignored when subset load balancing is enabled*

*Description*:
When subset load balancing is enabled on a cluster, the overprovisioning factor is ignored. For example, if a cluster has two endpoints in priority 0, one endpoint in priority 1, and the overprovisioning factor is 9999, traffic should not be routed to priority 1 if only one of the endpoints in priority 0 becomes unhealthy. This is not the behavior we're seeing. It appears that envoy continues to use the default overprovisioning factor of 140 in this case. Whenever less than 71% of our hosts in priority 0 are healthy, we see traffic spill over into priority 1. I've confirmed with some local tests (detailed below) that this only happens when subset load balancing is enabled. We also disable panic routing.

*Repro steps*:
The following steps use the attached docker-compose.yml file and envoy configurations to repro the issue. The basic setup is one downstream (aka client) and three upstreams that belong to a single cluster. upstream1 and upstream2 are priority 0, and upstream3 is priority 1. The test has subset load balancing enabled with fallback policy `ANY_ENDPOINT`, panic routing disabled, overprovisioning factor set to 9999, upstream1 and upstream3 passing health checks, and upstream2 failing health checks.

1. Start the containers
```
docker compose up
```
2. Confirm upstream1 and upstream3 are healthy, and upstream2 is unhealthy
```
$ > curl -s http://127.0.0.1:10000/clusters | grep some_service | grep -E "health|upstream|:prior"
some_service::172.21.0.4:11001::hostname::upstream1
some_service::172.21.0.4:11001::health_flags::healthy
some_service::172.21.0.4:11001::priority::0
some_service::172.21.0.5:12001::hostname::upstream2
some_service::172.21.0.5:12001::health_flags::/failed_active_hc
some_service::172.21.0.5:12001::priority::0
some_service::172.21.0.3:13001::hostname::upstream3
some_service::172.21.0.3:13001::health_flags::healthy
some_service::172.21.0.3:13001::priority::1
```
3. Send traffic to the client envoy, which will get proxied to the upstream cluster.
```
for i in {1..100}; do
  curl -s http://127.0.0.1:10001/ >/dev/null
done
```
4. Check how many requests went to each envoy
```
# client
$ > curl -s http://127.0.0.1:10000/stats | grep cluster.some_service.upstream_rq_total

# upstream1
$ > curl -s http://127.0.0.1:11000/stats | grep cluster.icanhazip.upstream_rq_total

# upstream2
$ > curl -s http://127.0.0.1:12000/stats | grep cluster.icanhazip.upstream_rq_total

# upstream3
$ > curl -s http://127.0.0.1:13000/stats | grep cluster.icanhazip.upstream_rq_total
```
5. You'll see that with overprovisioning_factor set to 9999 in client_config.yaml, upstream1 ***and*** upstream3 both receive traffic. This mirrors the bug we see in our production environment where the overprovisioning factor is being ignored.
6. You can comment out the subset load balancing config and rerun the test if you want to verify that the bug does not trigger in that scenario.

*Config*:
[docker-compose.txt](https://github.com/envoyproxy/envoy/files/10405109/docker-compose.txt)
[client_config.txt](https://github.com/envoyproxy/envoy/files/10405111/client_config.txt)
[upstream1_config.txt](https://github.com/envoyproxy/envoy/files/10405112/upstream1_config.txt)
[upstream2_config.txt](https://github.com/envoyproxy/envoy/files/10405113/upstream2_config.txt)
[upstream3_config.txt](https://github.com/envoyproxy/envoy/files/10405114/upstream3_config.txt)

### PR DESCRIPTION
**Pull request by michaelfinch**
Commit Message: subset loadbalancing: respect overprovisioning factor and weighted priority health overrides
Additional Description: fix bug in subset loadbalancer where custom overprovisioning factor and weighted priority health were not respected
Risk Level: Low
Testing: integration
Docs Changes: N/A
Release Notes: Added an entry to the changelog.
Fixes #24916

### CODE REVIEW

File: source/extensions/load_balancing_policies/subset/subset_lb.cc [hunk 1]
```diff
@@ -828,12 +828,12 @@ void SubsetLoadBalancer::HostSubsetImpl::update(const HostHashSet& matching_host
...
-                               degraded_hosts, degraded_hosts_per_locality, excluded_hosts,
-                               excluded_hosts_per_locality),
-                           determineLocalityWeights(*hosts_per_locality), hosts_added,
-                           hosts_removed, absl::nullopt, absl::nullopt);
+  HostSetImpl::updateHosts(
+      HostSetImpl::updateHostsParams(
+          hosts, hosts_per_locality, healthy_hosts, healthy_hosts_per_locality, degraded_hosts,
+          degraded_hosts_per_locality, excluded_hosts, excluded_hosts_per_locality),
+      determineLocalityWeights(*hosts_per_locality), hosts_added, hosts_removed, absl::nullopt,
+      original_host_set_.overprovisioningFactor());
```
Comment (michaelfinch) [inline source/extensions/load_balancing_policies/subset/subset_lb.cc:836]: **Old behavior**
When a subset load balancer is created, a priority set with the default overprovisioning factor is passed into the constructor here https://github.com/envoyproxy/envoy/blob/54fd807063590190ac31850a9be0d64fbb33851e/source/common/upstream/cluster_manager_impl.cc#L1560-L1567. The subset load balancer then uses that overprovisioning factor value when creating a priority subset here https://github.com/envoyproxy/envoy/blob/54fd807063590190ac31850a9be0d64fbb33851e/source/extensions/load_balancing_policies/subset/subset_lb.cc#L876. The overprovisioning factor used by the subset load balancer will not be updated when the original host set's overprovisioning factor is updated, because the call to `HostSetImpl::updateHosts` above^ uses `absl::nullopt` for the overprovisioning factor parameter.

**New behavior**
The overprovisioning factor used by the subset load balancer _will_ be updated when the original host set's overprovisioning factor is updated, because the original host set's overprovisioning factor is passed in when calling `HostSetImpl::updateHosts` above^.

**Comment by wbpcode** [comment]
Good catch! Thanks. But seems this is a minor behavior change, even it fix a bug. So, change log is necessary.

And not sure whether a runtime guard is necessary cc @envoyproxy/runtime-guard-changes, I think this is very minor behavior change?

/wait

File: source/extensions/load_balancing_policies/subset/subset_lb.cc [hunk 2]
```diff
@@ -828,12 +828,12 @@ void SubsetLoadBalancer::HostSubsetImpl::update(const HostHashSet& matching_host
...
-                               hosts, hosts_per_locality, healthy_hosts, healthy_hosts_per_locality,
-                               degraded_hosts, degraded_hosts_per_locality, excluded_hosts,
-                               excluded_hosts_per_locality),
-                           determineLocalityWeights(*hosts_per_locality), hosts_added,
-                           hosts_removed, absl::nullopt, absl::nullopt);
+  HostSetImpl::updateHosts(
+      HostSetImpl::updateHostsParams(
+          hosts, hosts_per_locality, healthy_hosts, healthy_hosts_per_locality, degraded_hosts,
+          degraded_hosts_per_locality, excluded_hosts, excluded_hosts_per_locality),
+      determineLocalityWeights(*hosts_per_locality), hosts_added, hosts_removed, absl::nullopt,
```
Comment (ggreenway) [inline source/extensions/load_balancing_policies/subset/subset_lb.cc:835]: This will fix another related bug:

```suggestion
      determineLocalityWeights(*hosts_per_locality), hosts_added, hosts_removed, original_host_set_.weightedPriorityHealth(),
```

**Review by ggreenway — CHANGES_REQUESTED** [review]

**Comment by michaelfinch** [comment]
> Good catch! Thanks. But seems this is a minor behavior change, even it fix a bug. So, change log is necessary.
> 
> And not sure whether a runtime guard is necessary cc @envoyproxy/runtime-guard-changes, I think this is very minor behavior change?
> 
> /wait

I added a note to the changelog. Let me know if a runtime guard is necessary.

File: source/extensions/load_balancing_policies/subset/subset_lb.cc (hunk 2 above)
Comment (michaelfinch) [reply source/extensions/load_balancing_policies/subset/subset_lb.cc]: Fixed, and added integration tests around this behavior.

**Comment by wbpcode** [comment]
friendly ping @zuercher @ggreenway

**Comment by davidsmith-square** [comment]
Eagerly anticipating this PR!! 🚀

**Comment by michaelfinch** [comment]
friendly ping @zuercher @ggreenway

**Comment by wbpcode** [comment]
@michaelfinch could you resolve the conflict first, thanks?

Seems @ggreenway and @zuercher is busy recently, if they are still non-responstive, I will take this, thanks.

/wait

**Review by zuercher — APPROVED** [review]
Sorry for the slow response. This looks good to me, though it needs a merge from main again.

File: changelogs/current.yaml [hunk 3]
```diff
@@ -11,6 +11,12 @@ bug_fixes:
 - area: connection limit
   change: |
     fixed a use-after-free bug in the connection limit filter.
+- area: subset load balancer
+  change: |
+    Fixed a bug where
+    :ref:`overprovisioning_factor<envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.weighted_priority_health>` and
```
Comment (ggreenway) [inline changelogs/current.yaml:17]:
```suggestion
    :ref:`overprovisioning_factor<envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>` and
```

File: contrib/golang/common/dso/test/test_data/simple.go [hunk 4]
```diff
@@ -6,10 +6,9 @@ typedef struct {
 } httpRequest;
 */
 import "C"
-import "unsafe"
-
 import (
 	"sync"
+	"unsafe"
```
Comment (ggreenway) [inline contrib/golang/common/dso/test/test_data/simple.go:11]: This change is unrelated; please revert

**Review by ggreenway — CHANGES_REQUESTED** [review]
Looks good aside from a couple nits

/wait

**Review by ggreenway — APPROVED** [review]

**Comment by davidsmith-square** [comment]
🔥

Do we know when we might see this rolled out to production? 🚀
