### PR TITLE
http: fixing a bug where responseDataTooLarge skipped HCM work

### LINKED ISSUE #9881: responseDataTooLarge bypasses HCM header transformation
Noticed when fixing #9797 that the new connection close logic won't apply to responseDataTooLarge. Because it calls the encoder directly, it bypasses a bunch of common code with stats and header tweaks and such.

I think I'd prefer to land a fix for this separately as it's going to require some analysis and untangling of filter chain calls vs HCM logic.

### PR DESCRIPTION
**Pull request by alyssawilk**
responseDataTooLarge needs to skip the filter chain, but should do the rest of standard HTTP processing, including HCM header transformations, calling maybeEndEncode, etc.

Risk Level: medium (HCM refactor)
Testing: validated with unit tests
Docs Changes: n/a
Release Notes: did not add
Fixes #9881

### CODE REVIEW

File: source/common/http/conn_manager_impl.cc [hunk 1]
```diff
@@ -1524,6 +1524,23 @@ void ConnectionManagerImpl::ActiveStream::encodeHeaders(ActiveStreamEncoderFilte
     }
   }
 
+  bool modified_end_stream =
```
Comment (mattklein123) [inline source/common/http/conn_manager_impl.cc]: nit: const here and similar cases below.

**Comment by alyssawilk** [comment]
Will tackle comments and tests later - giving context early.

Basically when we have an overly large response if we haven't sent the original response headers to the user, we want to send an error response.   We need to avoid that response going back through the filter chain, since that has the overly large response in progress, so we bypassed the standard encodeHeaders / encodeData functions when calling sendLocalReply, and called response_encoder_->encodeWhatever directly.

Unfortunately we've been adding more and more stuff to encodeHeaders and encodeData - it does mutateResponseHeaders(), it checks for connection close for HTTP/1.0, it changes decoration, it updates timing stats etc.  This refactor allows responseDataTooLarge to bypass filters but still share all the rest of the common code for tweaking headers and updating stats.

**Comment by mattklein123** [comment]
Thanks, that explanation makes a lot of sense to me, so I think some more comments will help. Thank you!

/wait
