### PR TITLE
ext_proc: remove exception throw in ext_proc configuration parsing code

### LINKED ISSUE #37046: Removing exception throw in ext_proc configuration parsing code
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Removing exception throw in ext_proc configuration parsing code

*Description*:

There are exception throwing in ext_proc filter configuration parsing code: 
https://github.com/envoyproxy/envoy/blob/a5f9f0ad7fbdef3171715a5ba45b85d3be010ced/source/extensions/filters/http/ext_proc/ext_proc.cc#L245

This can be refactored to return a absl::Status.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by agrawroh**
## Description

This PR refactors the exception throwing logic in the **ext_proc** filter to use `absl::Status` returns instead of throwing exceptions.

Fixes #37046

---

**Commit Message:** ext_proc: remove exception throw in ext_proc configuration parsing code

**Additional Description:** This change makes the error handling in ext_proc more consistent with other parts of the codebase by using Status returns instead of exceptions. The validation logic remains unchanged.

**Risk Level:** Low

**Testing:**
- Added new Unit Tests around config validation
- Existing unit tests modified to verify status returns
- Integration tests remain unchanged as external behavior is the same

**Docs Changes:** N/A

**Release Notes:** N/A

### CODE REVIEW

File: source/extensions/filters/http/ext_proc/ext_proc.cc [hunk 1]
```diff
@@ -261,15 +263,22 @@ FilterConfig::FilterConfig(const ExternalProcessor& config,
                           config.response_attributes()),
       immediate_mutation_checker_(context.regexEngine()),
       thread_local_stream_manager_slot_(context.threadLocal().allocateSlot()) {
-  // Validate processing mode configuration.
-  verifyProcessingModeConfig(config);
+
+  // Validate processing mode configuration
+  auto status = verifyProcessingModeConfig(config);
+  if (!status.ok()) {
```
Comment (tyxia) [inline source/extensions/filters/http/ext_proc/ext_proc.cc:269]: I think the ultimate goal here is to avoid the exception throw. This PR doesn't achieve as it will eventually the exception will be thrown here. It will be a larger refactor in ext_proc

Here is relevant discussion. https://github.com/envoyproxy/envoy/pull/34942#discussion_r1825852719

Comment (alyssawilk) [reply source/extensions/filters/http/ext_proc/ext_proc.cc:269]: happy to see this as an intermediate step

**Review by alyssawilk — APPROVED** [review]

**Comment by yanjunxiang-google** [comment]
HI, @alyssawilk , thanks for reviewing this PR.

Could you please clarify what's the eventual goal about Envoy exception throwing?  Are we supposed not to throw exception during filter passing configuration, but has to return a not-ok absl::Status if configuration parsing failed here: https://github.com/envoyproxy/envoy/blob/77e0bfc20090ad1e636e20d2060ae562780fd98e/source/extensions/filters/http/ext_proc/config.cc#L14.

If that's the case, then this PR is not achieving the goal yet.

**Comment by alyssawilk** [comment]
so the goal is to remove exceptions from core Envoy. Envoy will always support exceptions (and have try-catch) so folks downstream don't need to rewrite filters.  That said, Envoy does not support exceptions on the data plane and the exception removal project has found a non-trivial number of (uncaught) exceptions on the data plane, so the fewer exceptions Envoy has and the farther up the stack they are, the less likely uncaught data plane exceptions will be to end up being reintroduced.
I think if we get to the point that all of core Envoy has no exceptions it behooves google to remove exceptions from extensions we use, just so we don't need to use them at all, but that project is not staffed or planned.

File: source/extensions/filters/http/ext_proc/ext_proc.cc (hunk 1 above)
Comment (tyxia) [reply source/extensions/filters/http/ext_proc/ext_proc.cc:269]: I agree this PR is one step closer to final goal, as it merges multiple exception-throws to one place.

**Review by tyxia — APPROVED** [review]

**Comment by yanjunxiang-google** [comment]
Thanks @alyssawilk for the clarification.

HI, @agrawroh ,

I think it should be easy to surface the absl::status and return here:
https://github.com/envoyproxy/envoy/blob/5a241d32cc89ce9aa492a5820707fd584547d843/source/extensions/filters/http/ext_proc/config.cc#L13
,  if the ext_proc configuration is wrong.

What you can do is that instead of checking the configuration in the c'tor of FilterConfig here: https://github.com/envoyproxy/envoy/blob/5a241d32cc89ce9aa492a5820707fd584547d843/source/extensions/filters/http/ext_proc/ext_proc.cc#L265,  you can move that configuration check out to here: https://github.com/envoyproxy/envoy/blob/5a241d32cc89ce9aa492a5820707fd584547d843/source/extensions/filters/http/ext_proc/config.cc#L22, i.e, before the c'tor of FilterConfig.

That way, you can easily return a an absl::status for this function: ExternalProcessingFilterConfig::createFilterFactoryFromProtoTyped() if configuration check failed.

You can also move below checks to the same place:
https://github.com/envoyproxy/envoy/blob/5a241d32cc89ce9aa492a5820707fd584547d843/source/extensions/filters/http/ext_proc/ext_proc.cc#L266

https://github.com/envoyproxy/envoy/blob/5a241d32cc89ce9aa492a5820707fd584547d843/source/extensions/filters/http/ext_proc/ext_proc.cc#L61

This way, we can make the ext_proc filter code free of throwing any exception.

File: source/extensions/filters/http/ext_proc/ext_proc.cc (hunk 1 above)
Comment (yanjunxiang-google) [reply source/extensions/filters/http/ext_proc/ext_proc.cc:269]: Agreed this PR made some progress.  However, we can do better than this as we are specially targeting this area now.

**Comment by alyssawilk** [comment]
I don't know how this got 5 assignees but seems overkill.  As this is pure extension code removing all but tyxia who is codeowner and can approve and merge extension code.  @tyxia you can add me back in if you prefer a second pass review

**Comment by yanjunxiang-google** [comment]
@agrawroh Thanks for your good work! 

Only one thing left is that we should call verifyFilterConfig() here:
https://github.com/envoyproxy/envoy/blob/64036b42e1581df185d02858d0e5d48b8aaaef97/source/extensions/filters/http/ext_proc/config.cc#L60, and if the configuration is bad, throw an exception to keep the existing behavior.  It's a little bit unfortunate createFilterFactoryFromProtoWithServerContextTyped() does not support return an absl::status, and it's caller chain does not throw exception, so ext_proc should throw it here if configuration is bad.  Please add a unit test case to cover this code change as well.

**Comment by yanjunxiang-google** [comment]
LGTM

**Review by yanjunxiang-google — APPROVED** [review]

**Review by tyxia — APPROVED** [review]
LGTM, Thanks!

I think we can not remove ext proc from tools/code_format/config.yaml at the moment, as it is not exception free due to createFilterFactoryFromProtoWithServerContextTyped
