### PR TITLE
docs: fix links for public docs

### LINKED ISSUE #19017: docs: links broken for items like http_filters/grpc_json_transcoder_filter
*Title*: docs: links broken for items like http_filters/grpc_json_transcoder_filter

*Description*:

Links to documentation like that found in the [Sample Envoy configuration for gRPC JSON transcoding](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sample-envoy-configuration) use a link path that predates #8027. Following these links yield page not found. Also the web links no longer need to use the `www` prefix.

### PR DESCRIPTION
**Pull request by kriswuollett**
Previously doc paths were not updated within #8027. Resolves #19017.

Signed-off-by: Kristopher Wuollett <kristopher.wuollett@gmail.com>

Commit Message: docs: fix links for public docs
Additional Description: fixes links from file migration in #8027
Risk Level: Low
Testing: N/A
Docs Changes: Yes
Release Notes: N/A
Platform Specific Features: N/A

### CODE REVIEW

**Comment by kriswuollett** [comment]
Does the [`redirects.txt`](https://github.com/envoyproxy/envoy/blob/6f7a015bc56be53bc12f0635746d52ff7a226e49/docs/redirects.txt#L2) file need to be updated too for `observability/access_log`?

**Comment by phlax** [comment]
> Does the redirects.txt file need to be updated too...

possibly, i will need to review the pr further to figure out 

we can use redirects to either fix a broken historical link eg posted elsewhere, or when we are actually moving a page that has existed

the PR seems to have triggered an upstream flake

/retest

**Comment by phlax** [comment]
docs (will be) rendered here https://storage.googleapis.com/envoy-pr/19018/docs/index.html

**Comment by kriswuollett** [comment]
The only potential explanation for the error I see in the [presubmit run](https://dev.azure.com/cncf/envoy/_build/results?buildId=94622&view=logs&jobId=91e633a5-4907-5da1-5862-92a79fe2387a&j=91e633a5-4907-5da1-5862-92a79fe2387a&t=f29e24e7-a093-5724-80bd-d79975d268cb) is:

`intersphinx inventory 'https://www.envoyproxy.io/docs/envoy/v1.17.4/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 400 Client Error: Bad Request for url: https://www.envoyproxy.io/docs/envoy/v1.17.4/objects.inv`

Is that what could be the source of the flake?

**Comment by phlax** [comment]
> Is that what could be the source of the flake?

yep, it is

File: contrib/postgres_proxy/filters/network/source/BUILD [hunk 1]
```diff
@@ -12,7 +12,7 @@ envoy_contrib_package()
 #package(default_visibility = ["//visibility:public"])
 
 # PostgresSQL proxy L7 network filter.
-# Public docs: docs/root/configuration/network_filters/postgres_proxy_filter.rst
+# Public docs: docs/root/configuration/listeners/network_filters/postgres_proxy_filter.rst
```
Comment (phlax) [inline contrib/postgres_proxy/filters/network/source/BUILD:15]: with these links that are prefixed `docs/root` (ie repo relative links) im wondering if we should replace with links to the actual docs (as in links below)

Comment (kriswuollett) [reply contrib/postgres_proxy/filters/network/source/BUILD:15]: IMO, that change seems like it would be more useful to developers as text editing apps may automatically create a clickable link to see what's already labeled as public docs.

Comment (phlax) [reply contrib/postgres_proxy/filters/network/source/BUILD:15]: yep, and the repo rst files are source files so not as easy/useful to read

**Comment by phlax** [comment]
@kriswuollett looks like this PR needs a main merge

it would be good to fix these links

**Comment by kriswuollett** [comment]
@phlax, sure thing. Will update them now.

File: source/common/formatter/substitution_formatter.h [hunk 2]
```diff
@@ -31,7 +31,7 @@ class SubstitutionFormatParser {
    * Parse a header format rule of the form: %REQ(X?Y):Z% .
    * Will populate a main_header and an optional alternative header if specified.
    * See doc:
-   * docs/root/configuration/access_log.rst#format-rules
+   * docs/root/configuration/observability/access_log/access_log.rst#format-rules
```
Comment (phlax) [inline source/common/formatter/substitution_formatter.h:34]: i think these couple of links can also be updated to full urls

File: source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.h [hunk 3]
```diff
@@ -11,7 +11,7 @@ namespace Extensions {
 namespace HttpFilters {
 namespace GrpcHttp1Bridge {
 /**
- * See docs/configuration/http_filters/grpc_http1_bridge_filter.rst
+ * See docs/configuration/http/http_filters/grpc_http1_bridge_filter.rst
```
Comment (phlax) [inline source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.h:14]: and this one

**Comment by kriswuollett** [comment]
I can also update all the other links like in the Markdown files to not have the redirect from the `www` domain prefix, but wasn't sure how much doc/formatting noise the project is ok with.

**Review by phlax — CHANGES_REQUESTED** [review]
thanks for updating @kriswuollett 

there are a few repo links left and then this should be good to land

**Comment by phlax** [comment]
> I can also update all the other links like in the Markdown files ...

lets address that in a separate PR

File: source/extensions/filters/network/ext_authz/BUILD [hunk 4]
```diff
@@ -8,7 +8,7 @@ load(
 licenses(["notice"])  # Apache 2
 
 # External authorization L4 network filter
-# Public docs: TODO(saumoh): Docs needed in docs/root/configuration/network_filters
+# Public docs: TODO(saumoh): Docs needed in docs/root/configuration/listeners/network_filters
```
[the remark this answers is not in the document]
Comment (phlax) [reply source/extensions/filters/network/ext_authz/BUILD:11]: nm i see this isnt necessary

File: source/extensions/filters/http/ext_authz/BUILD [hunk 5]
```diff
@@ -8,7 +8,7 @@ load(
 licenses(["notice"])  # Apache 2
 
 # External authorization L7 HTTP filter
-# Public docs: TODO(saumoh): Docs needed in docs/root/configuration/http_filters
+# Public docs: TODO(saumoh): Docs needed in docs/root/configuration/http/http_filters
```
[the remark this answers is not in the document]
Comment (phlax) [reply source/extensions/filters/http/ext_authz/BUILD:11]: ignore me here!

File: source/common/formatter/substitution_formatter.h (hunk 2 above)
Comment (kriswuollett) [reply source/common/formatter/substitution_formatter.h]: Ok. Also made the no www prefix consistent. Let me know if anything else needs to be addressed.

File: source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.h (hunk 3 above)
Comment (kriswuollett) [reply source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.h]: done

File: source/extensions/filters/http/grpc_web/grpc_web_filter.h [hunk 6]
```diff
@@ -14,7 +14,7 @@ namespace HttpFilters {
 namespace GrpcWeb {
 
 /**
- * See docs/configuration/http_filters/grpc_web_filter.rst
+ * See docs/configuration/http/http_filters/grpc_web_filter.rst
```
[the remark this answers is not in the document]
Comment (kriswuollett) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.h]: done

File: source/common/formatter/substitution_formatter.h (hunk 2 above)
Comment (kriswuollett) [reply source/common/formatter/substitution_formatter.h]: Just remembered that you requested it should go in another pull request, so just took that out now.

**Comment by phlax** [comment]
@kriswuollett i think the formatting issues are because you need to merge main

**Review by phlax — APPROVED** [review]
@kriswuollett thanks for taking the time to go through and fix these, lgtm
