### PR TITLE
Fix refresh manager race

### LINKED ISSUE #10384: Flake: ClusterRefreshManagerTest.BasicFailureEvents
*Title*: ClusterRefreshManagerTest.BasicFailureEvents failing intermittently on master

*Description*:
Various PR's have exhibited the following flaw in envoy-linux testing;
```
[ RUN      ] ClusterRefreshManagerTest.BasicFailureEvents
test/extensions/common/redis/cluster_refresh_manager_test.cc:195: Failure
Expected equality of these values:
  cluster_info->failures_count_
    Which is: 1
  0
Stack trace:
  0x635b09: Envoy::Extensions::Common::Redis::ClusterRefreshManagerTest_BasicFailureEvents_Test::TestBody()
  0xee0a78: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0xee09a5: testing::Test::Run()
  0xee15c0: testing::TestInfo::Run()
... Google Test internal frames ...
[  FAILED  ] ClusterRefreshManagerTest.BasicFailureEvents (16 ms)
```
*Examples*:
#20200313.36 Enable Windows CI //source/exe:envoy-static build
https://dev.azure.com/cncf/envoy/_build/results?buildId=34161&view=logs&j=431348f8-7191-5fd1-d3a8-72635bfc039a&t=4111d0d2-6ea0-5092-9e44-b46f3a3ee2b0&l=4212

#20200313.13 xDS: type url aggregation
https://dev.azure.com/cncf/envoy/_build/results?buildId=34076&view=logs&j=431348f8-7191-5fd1-d3a8-72635bfc039a&t=4111d0d2-6ea0-5092-9e44-b46f3a3ee2b0&l=4264

### PR DESCRIPTION
**Pull request by HenryYYang**
Description: Enforce the count is 0 if one of the other threads have reset the callback time.
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Fixes #10384

### CODE REVIEW

File: source/extensions/common/redis/cluster_refresh_manager_impl.cc [hunk 1]
```diff
@@ -90,6 +90,11 @@ bool ClusterRefreshManagerImpl::onEvent(const std::string& cluster_name, EventTy
           }
         });
         return true;
+      } else if (info->last_callback_time_ms_.load() != last_callback_time_ms) {
```
Comment (mattklein123) [inline source/extensions/common/redis/cluster_refresh_manager_impl.cc:93]: If we stick with this approach I think it would be more clear if this was a basic else statement paired with the CAS, inside a large if statement with the counter increment.

File: source/extensions/common/redis/cluster_refresh_manager_impl.cc [hunk 2]
```diff
@@ -90,6 +90,11 @@ bool ClusterRefreshManagerImpl::onEvent(const std::string& cluster_name, EventTy
...
+        // If someone else updated the last callback time, then they will trigger the callback.
+        // During this time we don't want to continue to increment the count, so we enforce the
+        // count is 0
+        *count = 0;
```
Comment (mattklein123) [inline source/extensions/common/redis/cluster_refresh_manager_impl.cc:97]: Based on the comment above, should this be a decrement to undo the increment? Or is that not safe since it might also race?

Comment (HenryYYang) [reply source/extensions/common/redis/cluster_refresh_manager_impl.cc:97]: decrement can race as well.  If the decrement is called after count got set to 0 in another thread, this would set the counter to -1.

File: source/extensions/common/redis/cluster_refresh_manager_impl.cc (hunk 1 above)
Comment (HenryYYang) [reply source/extensions/common/redis/cluster_refresh_manager_impl.cc:93]: I think if we have the if counter set to 0 is in a if statement, it would also race. because if thread 1 set the counter to 0, the incr in thread 2 might not trigger the threshold.  Let me rewrite this logic to make it clearer.

File: source/extensions/common/redis/cluster_refresh_manager_impl.cc [hunk 3]
```diff
@@ -73,14 +73,25 @@ bool ClusterRefreshManagerImpl::onEvent(const std::string& cluster_name, EventTy
...
         // last_callback_time_ms_ successfully updated without any changes since it was
         // initially read. This thread is allowed to post a call to the registered callback
         // on the main thread. Otherwise, the thread would be ignored to prevent over-triggering
         // cluster callbacks.
+        postCallBack = true;
+      }
+
+      // If a callback should be triggered(in this or some other threads) signaled by the changed
+      // last callback time, we reset the count to 0
+      if (postCallBack || info->last_callback_time_ms_.load() != last_callback_time_ms) {
```
Comment (mattklein123) [inline source/extensions/common/redis/cluster_refresh_manager_impl.cc:90]: I'm still a little confused here by this logic so I think it needs some more comments. What is the exact sequence that leads to post_callback being false but the times being not equal?

Comment (HenryYYang) [reply source/extensions/common/redis/cluster_refresh_manager_impl.cc]: ok, let me add those to the comments
