### PR TITLE
router: add gateway-error retry-on policy

### LINKED ISSUE #2300: more granular 5xx retry policy
(cross-posting from [envoy-users](https://groups.google.com/forum/#!topic/envoy-users/lFCtyGZa3QU) for tracking an issue)

What do you guys think about having more granular retry policy rather than just 5xx?

The motivation behind this post is that:
1) we use nginx + uwsgi at $work.
2) setting 5xx as default retry policy is not safe due to possible non-idempotent requests: did data arrive on the server? did server process them?
3) however, in our setup, 502 errors are common: nginx failed to talk to uwsgi for whatever reason. Retry is safe, no data hit uwsgi. Same for 503 btw.

Basically, what I'm trying to achieve is to provide safe default retry policy for my users which would be: "connect-failure" + 502 + 503.

I see that envoy's code base has:
```
static bool isGatewayError(uint64_t code) { return code >= 502 && code < 505; }
```
which made me think about having retry policy: "gateway_error". This policy would cover my needs but as a downside includes 504 which is redundant.

Alternatively, maybe explicitly enumerating HTTP response codes? retry_on=connect_failure,502,503

### PR DESCRIPTION
**Pull request by dio**
*router: add gateway-error retry-on policy*

*Description*: Add gateway-error (consider 502, 503 and 504 only) as a subset of 5xx retry-on policy.

*Risk Level*: Low

*Testing*: unit test

*Docs Changes*:
- [docs: add gateway-error as one of retry-on policies](https://github.com/envoyproxy/data-plane-api/pull/415)

*Release Notes*: N/A

Fixes #2300

### CODE REVIEW

File: source/common/router/retry_state_impl.cc [hunk 1]
```diff
@@ -187,6 +190,12 @@ bool RetryStateImpl::wouldRetry(const Http::HeaderMap* response_headers,
     }
   }
 
+  if (retry_on_ & RetryPolicy::RETRY_ON_GATEWAY_ERROR) {
+    if (Http::CodeUtility::isGatewayError(Http::Utility::getResponseStatus(*response_headers))) {
```
Comment (mattklein123) [inline source/common/router/retry_state_impl.cc]: You need to check here that response_headers is not nullptr. Please add a test to cover this case.

File: source/common/router/retry_state_impl.cc [hunk 2]
```diff
@@ -15,9 +15,10 @@
 namespace Envoy {
 namespace Router {
 
-// These are defined in envoy/server/router.h, however during certain cases the compiler is
+// These are defined in envoy/router.h, however during certain cases the compiler is
```
[the remark this answers is not in the document]
Comment (dio) [reply source/common/router/retry_state_impl.cc]: Thanks @zuercher!

File: source/common/router/retry_state_impl.cc (hunk 1 above)
Comment (dio) [reply source/common/router/retry_state_impl.cc]: Hi, @mattklein123 thanks for the review. Since this policy has the same behavior with 5xx, I assume I need to have reset overflow and remote reset tests in place?

Comment (dio) [reply source/common/router/retry_state_impl.cc]: Or vice versa? Hum, it seems so. So I think, regarding this policy, I need to not retry if the response_headers is nullptr. Is that correct?

File: source/common/router/retry_state_impl.cc [hunk 3]
```diff
@@ -187,6 +190,13 @@ bool RetryStateImpl::wouldRetry(const Http::HeaderMap* response_headers,
     }
   }
 
+  if (retry_on_ & RetryPolicy::RETRY_ON_GATEWAY_ERROR) {
+    if (response_headers != nullptr &&
```
Comment (mattklein123) [inline source/common/router/retry_state_impl.cc]: Per your other comment, I think you actually want `||` here for the same reason as the 5xx case. A reset will always result in a 503 or 504 (IIRC for timeout), so should be included.

Comment (dio) [reply source/common/router/retry_state_impl.cc]: Ah yes, sorry for misunderstanding that. Will update it.

**Comment by mattklein123** [comment]
@dio LGTM but needs a DCO fix.

**Comment by dio** [comment]
OH yeah, sorry for that. I thought I have run that `support/bootstrap`, but I guess it was not for this local copy. Fixed.

Thanks @mattklein123.

**Comment by mattklein123** [comment]
@dio apologies, one last thing: Can you please add a release note about the new feature here: https://github.com/envoyproxy/envoy/blob/master/RAW_RELEASE_NOTES.md. Thank you!

**Comment by dio** [comment]
@mattklein123 added. Thanks for reminding me!
