### PR TITLE
ext_proc: refactoring handleBodyResponse() to make it more modularized

### LINKED ISSUE #37048: ext_proc: refactoring handleBodyResponse() to make it more modularized
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: ext_proc: refactoring handleBodyResponse() to make it more modularized

*Description*:
Adding one helper function for each callback state.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by agrawroh**
## Description

This PR refactors the `handleBodyResponse()` method in the **ext_proc** filter to improve code maintainability and readability. The current implementation contains complex nested logic handling different callback states, making it difficult to understand and maintain. This change breaks down the functionality into smaller, focused methods while preserving the existing behavior.

Fixes #37048

---

**Commit Message:** ext_proc: refactor handleBodyResponse() into modular components

**Additional Description:** The refactoring introduces several helper methods to handle different aspects of body response processing inside `ext_proc`'s `handleBodyResponse()`. This modularization makes the code easier to understand, test, and modify while maintaining all existing functionality and error handling.

**Risk Level:** Low

**Testing:**
- Existing test suite passes
- No new tests needed as this is a refactor
- Current test coverage validates all code paths

### CODE REVIEW

**Comment by tyxia** [comment]
/assign @yanjunxiang-google 

Do you want to take a first pass? Thanks

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 1]
```diff
@@ -272,111 +272,211 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
 }
 
-// TODO(#37048) Refactoring this function by adding one helper function for each callback state.
+/**
+ * Handles responses containing body modifications from an external processor. Supports three modes
+ * of operation: buffered, streamed, and buffered partial.
+ *
+ * @param response The body response received from the external processor
+ * @return Status indicating success or failure of the handling operation
+ */
```
Comment (tyxia) [inline source/extensions/filters/http/ext_proc/processor_state.cc:281]: @agrawroh Thanks for refactoring! 

Just the style nit from a quick drive-by : They are nice comments but i think it is better to be added to the function declaration in the header file

**Comment by yanjunxiang-google** [comment]
Thanks @agrawroh for working on this!

/wait

**Comment by tyxia** [comment]
@yanjunxiang-google, Just to clarify: `wait` is for the case that requires PR author's action, which is not applicable here. We probably want to review this PR (i.e., this PR is waiting for reviewer's action) , even though i left a nit comment in code style. WDYT?

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 2]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+    return handleBufferedPartialBodyCallback(common_response, should_continue);
+  default:
+    // Fake a grpc error when processor state and received message type doesn't match
+    onFinishProcessorCall(Grpc::Status::FailedPrecondition);
+    return absl::OkStatus();
+  }
+}
+
+absl::Status ProcessorState::handleBufferedBodyCallback(const CommonResponse& common_response,
+                                                        bool& should_continue) {
```
Comment (jmarantz) [inline source/extensions/filters/http/ext_proc/processor_state.cc:319]: I think we should initialize should_continue to false here so that it has deterministic state on an early return.

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 3]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
-        ENVOY_LOG(trace, "Injecting {} bytes of leftover data to filter stream",
-                  chunkQueue().receivedData().length());
-        injectDataToFilterChain(chunkQueue().receivedData(), all_data.end_stream);
-      }
-    } else {
-      // Fake a grpc error when processor state and received message type doesn't match, beware this
-      // is not an error from grpc.
-      onFinishProcessorCall(Grpc::Status::FailedPrecondition);
-    }
+  auto process_status = processResponseBasedOnState(common_response, should_continue);
```
Comment (jmarantz) [inline source/extensions/filters/http/ext_proc/processor_state.cc:284]: use an explicit type here per style guide.

But i think all this code would be clearer and more concise if you had these functions return `absl::StatusOr<bool>` rather than passing a writeable ref to a bool for should_continue.

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 4]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+  }
+  should_continue = *result;
+  return absl::OkStatus();
+}
+
+absl::Status
+ProcessorState::handleBufferedPartialBodyCallback(const CommonResponse& common_response,
+                                                  bool& should_continue) {
+  Buffer::OwnedImpl chunk_data;
+  auto chunk = dequeueStreamingChunk(chunk_data);
```
Comment (jmarantz) [inline source/extensions/filters/http/ext_proc/processor_state.cc:357]: explicit type, here and for most `auto` in your PR.

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 5]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+  if (!chunk) {
+    ENVOY_BUG(false, "Bad partial body callback state");
+    return absl::InternalError("Invalid chunk in partial body callback");
+  }
 
-    if (should_continue || (trailers_available_ && chunk_queue_.empty())) {
-      continueIfNecessary();
+  // Process header mutations if present
+  if (common_response.has_header_mutation()) {
+    const auto mut_status = processHeaderMutationIfAvailable(common_response);
```
Comment (jmarantz) [inline source/extensions/filters/http/ext_proc/processor_state.cc:365]: can you spell out `mut_status` more fully? I don't know what `mut` is short for.

File: source/extensions/filters/http/ext_proc/processor_state.h [hunk 6]
```diff
@@ -297,6 +304,59 @@ class ProcessorState : public Logger::Loggable<Logger::Id::ext_proc> {
...
+   * @param common_response The common response portion from the external processor
+   * @param should_continue Output parameter indicating if processing should continue
+   * @return Status indicating success or failure of processing
+   */
+  absl::Status
+  processResponseBasedOnState(const envoy::service::ext_proc::v3::CommonResponse& common_response,
+                              bool& should_continue);
+  /**
+   * Handles responses in buffered body callback state. Processes both header and body mutations if
+   * present in the response.
```
Comment (jmarantz) [inline source/extensions/filters/http/ext_proc/processor_state.h:320]: document params and return, here and below.

File: source/extensions/filters/http/ext_proc/processor_state.h [hunk 7]
```diff
@@ -297,6 +304,59 @@ class ProcessorState : public Logger::Loggable<Logger::Id::ext_proc> {
   void clearStreamingChunk() { chunk_queue_.clear(); }
   CallbackState getCallbackStateAfterHeaderResp(
       const envoy::service::ext_proc::v3::CommonResponse& common_response) const;
+  bool isValidCallbackState() const;
```
Comment (jmarantz) [inline source/extensions/filters/http/ext_proc/processor_state.h:307]: nit: usually we put a blank line between documented methods.

**Review by jmarantz — COMMENTED** [review]
this is great, thank you! Just a few minor comments.

/wait

File: source/extensions/filters/http/ext_proc/processor_state.cc (hunk 3 above)
Comment (yanjunxiang-google) [reply source/extensions/filters/http/ext_proc/processor_state.cc:284]: Agreed

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 8]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+
+  clearWatermark();
+  onFinishProcessorCall(Grpc::Status::Ok);
+  should_continue = true;
+  return absl::OkStatus();
+}
+
+absl::Status ProcessorState::handleStreamedBodyCallback(const CommonResponse& common_response,
+                                                        bool& should_continue) {
+  absl::StatusOr<bool> result = handleBodyInStreamedState(common_response);
```
Comment (yanjunxiang-google) [inline source/extensions/filters/http/ext_proc/processor_state.cc:345]: Let's get rid of function: handleBodyInStreamedState(). We do not need another layer.

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 9]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+  if (chunkQueue().receivedData().length() > 0) {
+    const auto& all_data = consolidateStreamedChunks();
+    ENVOY_LOG(trace, "Injecting {} bytes of leftover data to filter stream",
+              chunkQueue().receivedData().length());
+    injectDataToFilterChain(chunkQueue().receivedData(), all_data.end_stream);
+  }
+}
+
+// Finalizes the response processing by handling trailers and continuation
+absl::Status ProcessorState::finalizeResponse(bool should_continue) {
```
Comment (yanjunxiang-google) [inline source/extensions/filters/http/ext_proc/processor_state.cc:437]: Same as above. Please name it as finalizeBodyResponse().

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 10]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+}
+
+// Validates if the current callback state is valid for processing body responses
+bool ProcessorState::isValidCallbackState() const {
+  return callback_state_ == CallbackState::BufferedBodyCallback ||
+         callback_state_ == CallbackState::StreamedBodyCallback ||
+         callback_state_ == CallbackState::BufferedPartialBodyCallback;
+}
+
+absl::Status ProcessorState::processResponseBasedOnState(const CommonResponse& common_response,
```
Comment (yanjunxiang-google) [inline source/extensions/filters/http/ext_proc/processor_state.cc:302]: We can directly add below swtich ... case ... inside the function handleBodyResponse(). i.e, we do not need this processResponseBasedOnState() function.

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 11]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+
+  if (content_length != common_response.body_mutation().body().size()) {
+    return absl::InternalError(
+        "mismatch between content length and the length of the mutated body");
+  }
+
+  return absl::OkStatus();
+}
+
+void ProcessorState::applyBufferedBodyMutation(const CommonResponse& common_response) {
```
Comment (yanjunxiang-google) [inline source/extensions/filters/http/ext_proc/processor_state.cc:413]: This function is called only in one place.  Why not just put these a few lines inline its caller?

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 12]
```diff
@@ -272,111 +272,183 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+}
+
+void ProcessorState::processChunkDataAndLeftovers(Buffer::OwnedImpl& chunk_data, bool end_stream) {
+  if (chunk_data.length() > 0) {
+    ENVOY_LOG(trace, "Injecting {} bytes of processed data to filter stream", chunk_data.length());
+    injectDataToFilterChain(chunk_data, end_stream);
+  }
+
+  // If anything else is left on the queue, inject it too
+  if (chunkQueue().receivedData().length() > 0) {
```
Comment (yanjunxiang-google) [inline source/extensions/filters/http/ext_proc/processor_state.cc:428]: This modified original code logic.

Originally, this leftover data processing is handled after onFinishProcessorCall(), which call filter_.logGrpcStreaminfo() for bytes counting.  I recommend do not make such logic change within this PR.

File: source/extensions/filters/http/ext_proc/processor_state.cc (hunk 11 above)
Comment (jmarantz) [reply source/extensions/filters/http/ext_proc/processor_state.cc:413]: IMO it's OK to have a single-use function, even if it's not huge, if it makes call-sites more readable. I'm not sure if that's the case here.

File: source/extensions/filters/http/ext_proc/processor_state.cc (hunk 12 above)
Comment (agrawroh) [reply source/extensions/filters/http/ext_proc/processor_state.cc:428]: Was unintentional, I'll fix it to follow the old behavior

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 13]
```diff
@@ -272,111 +272,187 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+    onFinishProcessorCall(Grpc::Status::FailedPrecondition);
+    return absl::OkStatus();
+  }
+
+  if (!result.ok()) {
+    return result.status();
+  }
+
+  // Clear route cache before finalizing
+  clearRouteCache(common_response);
```
[the remark this answers is not in the document]
Comment (yanjunxiang-google) [reply source/extensions/filters/http/ext_proc/processor_state.cc:305]: SG

File: source/extensions/filters/http/ext_proc/processor_state.cc [hunk 14]
```diff
@@ -272,111 +272,180 @@ absl::Status ProcessorState::handleHeadersResponse(const HeadersResponse& respon
...
+  case CallbackState::BufferedBodyCallback:
+    result = handleBufferedBodyCallback(common_response);
+    break;
+  case CallbackState::StreamedBodyCallback:
+    result = handleStreamedBodyCallback(common_response);
+    break;
+  case CallbackState::BufferedPartialBodyCallback:
+    result = handleBufferedPartialBodyCallback(common_response);
+    break;
+  default:
```
Comment (yanjunxiang-google) [inline source/extensions/filters/http/ext_proc/processor_state.cc:294]: This seems to be dead code based on the context.  We can clean it up in the next PR.

**Comment by yanjunxiang-google** [comment]
LGTM

**Review by yanjunxiang-google — APPROVED** [review]

**Comment by agrawroh** [comment]
@jmarantz Could you please take another look?

File: source/extensions/filters/http/ext_proc/processor_state.cc (hunk 14 above)
Comment (jmarantz) [reply source/extensions/filters/http/ext_proc/processor_state.cc:294]: what happens if you remove the 'default' block here? Will it compile? if CallbackState is a C++ enum and you've covered all the options it's better to omit the 'default'. If there are cases which exist in the enum but you think they can't happen, we can use IS_ENVOY_BUG in the default to log it in production or crash in tests.

**Review by jmarantz — COMMENTED** [review]
lgtm with one remaining nit.

/wait

File: source/extensions/filters/http/ext_proc/processor_state.cc (hunk 14 above)
Comment (yanjunxiang-google) [reply source/extensions/filters/http/ext_proc/processor_state.cc:294]: Line 276 clearly checked the callback_state has to be one of these three body states. Thus, the "default" case will never be hit.  Let's just remove it then.

Comment (agrawroh) [reply source/extensions/filters/http/ext_proc/processor_state.cc:294]: @jmarantz It looks like `CallbackState` have more states than what we have in our ExtProc handling today,
```
enum class CallbackState {
    // Not waiting for anything
    Idle,
    // Waiting for a "headers" response. This may be true even if we started
    // to receive data frames for a message.
    HeadersCallback,
    // Waiting for a "body" response in buffered mode.
    BufferedBodyCallback,
    // Waiting for a "body" response in streaming mode.
    StreamedBodyCallback,
    // Waiting for a body callback in "buffered partial" mode.
    BufferedPartialBodyCallback,
    // Waiting for a "trailers" response.
    TrailersCallback,
};
```

When I try to remove `default` and add `IS_ENVOY_BUG(...)`, I see this error:

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
source/extensions/filters/http/ext_proc/processor_state.cc:284:11: error: enumeration values 'Idle', 'HeadersCallback', and 'TrailersCallback' not handled in switch [-Werror,-Wswitch]
  switch (callback_state_) {
          ^~~~~~~~~~~~~~~
1 error generated.
```

Comment (yanjunxiang-google) [reply source/extensions/filters/http/ext_proc/processor_state.cc:294]: Had you tried this:
default:
   IS_ENVOY_BUG("callback state is wrong");
   break;

Comment (agrawroh) [reply source/extensions/filters/http/ext_proc/processor_state.cc:294]: @yanjunxiang-google Okay, added that.

**Review by yanjunxiang-google — APPROVED** [review]

**Review by jmarantz — DISMISSED** [review]

File: source/extensions/filters/http/ext_proc/processor_state.cc (hunk 14 above)
Comment (jmarantz) [reply source/extensions/filters/http/ext_proc/processor_state.cc:294]: I'm OK with this as is but it would be slightly better (IMO) to put the IS_ENVOY_BUG call first. No big deal.

I'd also slightly favor enumerating all the missing cases rather than use 'default'. That way if a new enum choice is added in the future, the compiler will point out the missing new case here, and the author of this code will then consider the new case for this block with it fresh in his/her mind.

**Review by yanavlasov — APPROVED** [review]
