### PR TITLE
connection: Remember transport socket read resumption requests and replay them when re-enabling read.

### LINKED ISSUE #12304: shouldDrainReadBuffer followed up by readDisable(true) and readDisable(false) strange behaviour
The behaviour I'm about to describe requires quite a lot of setup in order to reproduce.

To begin with I'm using v1.14.4.

My listeners use the following configuration.

> listener.mutable_per_connection_buffer_limit_bytes()->set_value(16384);

The default value of 1MB just seemed way too big and opened up lots of opportunities for oom so I ended up using 16k.

Then I have a **local** SSL client in which data in sent in chunks, e.g. 400 followed up by 16500 bytes (e.g. HTTP headers and body). 

What can be seen in the trace logs is the following:

> 2020-07-23T14:56:23.084Z trace [source/common/network/connection_impl.cc:534] [C187] socket event: 3
> 2020-07-23T14:56:23.084Z trace [source/common/network/connection_impl.cc:622] [C187] write ready
> 2020-07-23T14:56:23.084Z trace [source/common/network/connection_impl.cc:572] [C187] read ready
> 2020-07-23T14:56:23.084Z trace [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C187] ssl read returns: 393
> 2020-07-23T14:56:23.084Z trace [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C187] ssl read returns: 15991
> 2020-07-23T14:56:23.084Z trace [source/extensions/transport_sockets/tls/ssl_socket.cc:167] [C187] ssl read 16384 bytes
> 2020-07-23T14:56:23.084Z trace [source/common/http/http1/codec_impl.cc:475] [C187] parsing 16384 bytes
> ...
> 2020-07-23T14:56:23.085Z debug [source/common/http/conn_manager_impl.cc:2344] [C187][S7433621899365225547] Read-disabling downstream stream due to filter callbacks.
> 2020-07-23T14:56:23.085Z trace [source/common/network/connection_impl.cc:355] [C187] readDisable: enabled=true disable=true state=0
> ...
> 2020-07-23T14:56:23.086Z debug [source/common/http/conn_manager_impl.cc:2368] [C187][S7433621899365225547] Read-enabling downstream stream due to filter callbacks.
> 2020-07-23T14:56:23.086Z trace [source/common/network/connection_impl.cc:355] [C187] readDisable: enabled=false disable=false state=0
> 2020-07-23T14:56:23.086Z trace [source/common/network/connection_impl.cc:534] [C187] socket event: 2
> 2020-07-23T14:56:23.086Z trace [source/common/network/connection_impl.cc:622] [C187] write ready

At that point envoy stops reading from the downstream and either the client or the server times out. According to the client the entire request has been sent and according to the server not the entire request was received.

To me it seems like the problem is that whenever we have this situation

> 2020-07-23T14:56:23.084Z trace [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C187] ssl read returns: 393
> 2020-07-23T14:56:23.084Z trace [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C187] ssl read returns: 15991
> 2020-07-23T14:56:23.084Z trace [source/extensions/transport_sockets/tls/ssl_socket.cc:167] [C187] ssl read 16384 bytes

only then do we execute the following code:

> 105 Network::IoResult SslSocket::doRead(Buffer::Instance& read_buffer) {
> ...
> 158     if (slices_to_commit > 0) {
> 159       read_buffer.commit(slices, slices_to_commit);
> 160       if (callbacks_->shouldDrainReadBuffer()) {
> 161         callbacks_->setReadBufferReady();
> 162         keep_reading = false;
> 163       }
> 164     }

and in my case I have shouldDrainReadBuffer() == true because

> 113   bool shouldDrainReadBuffer() override {
> 114     return read_buffer_limit_ > 0 && read_buffer_.length() >= read_buffer_limit_; // 16k > 0 && 16k == 16k
> 115   }

and then setReadBufferReady does

> 121   void setReadBufferReady() override { file_event_->activate(Event::FileReadyType::Read); }

which seems to immediately get eaten by the first readDisable(true)

> readDisable: enabled=true disable=true state=0

and when the second readDisable(false) happens 

> readDisable: enabled=false disable=false state=0

the read event is **not activated**.

If readDisable(true/false) isn't triggered or the setReadBufferReady() code path is not executed all is well.
I tried plain TCP and wasn't able to reproduce the issue (there's a similar if shouldDrainReadBuffer in it).
I wasn't able to reproduce the issue with an external connection either (maybe my network is slow).
The code snippets that I shared may be a few lines off v1.14.4 as I have a few ERR_clear_error() calls added as I'm using OpenSSL but looking at the behaviour I would not blame them or OpenSSL.
I can't unfortunately share either the client or the server code.

I can reliable reproduce the issue once every 5 minutes or so, so if anyone has a patch in mind I'll be willing to try it out. In the meantime, I'll see if I can come up with something.

### PR DESCRIPTION
**Pull request by antoniovicente**
Commit Message: connection: Remember transport socket read resumption requests and replay them when re-enabling read.
Additional Description: Fixes SslSocket read resumption after readDisable when processing the SSL record that contains the last bytes of the HTTP message
Risk Level: low
Testing: new unit and integration tests
Docs Changes: n/a
Release Notes: added
Platform Specific Features: n/a
Fixes #12304

### CODE REVIEW

File: source/common/network/connection_impl.cc [hunk 1]
```diff
@@ -554,6 +558,7 @@ void ConnectionImpl::onReadReady() {
     return;
   }
 
+  want_read_ = false;
```
Comment (alyssawilk) [inline source/common/network/connection_impl.cc:561]: should we also set this false for the early return onRead above?  If not please comment.

**Review by alyssawilk — COMMENTED** [review]
Nice, I like this *way* better.
High level thought - do we want to runtime guard this just because it's high risk?  Mild concerns about the complexity here opening up a spin loop bug.

File: source/common/network/connection_impl.cc (hunk 1 above)
Comment (antoniovicente) [reply source/common/network/connection_impl.cc:565]: Commented.

MockTransportConnectionImplTest.ResumeWhileAndAfterReadDisable covers the early return case which requires us to clear want_read_ just before doRead.

**Review by antoniovicente — COMMENTED** [review]
> Nice, I like this _way_ better.
> High level thought - do we want to runtime guard this just because it's high risk? Mild concerns about the complexity here opening up a spin loop bug.

Let's talk about the risk level of this PR. The case I'm adding resumption for is after a call to readDisable(false). That can happen when either:
- High watermark trigger cleared from read buffer as bytes are drained
- High watermark trigger cleared from write buffer as bytes are drained
- Finished processing of an H1 request from the client

All of these count as proofs of work. It doesn't seem likely that the connection will continuously wake up when there's no available work.

If for instance we were to not clear want_read_ when we should, we'ld get a spurious wakeup on readDisable(false), but only once unless the connection is able to successfully read additional bytes from the socket and push them to the filter pipeline.

I agree that this PR increases complexity as it requires that the connection track additional state about the state of the transport and increases coupling between the connection and transport implementation.

I think the risk level of this PR is relatively low. That said, I have no objections to runtime guarding this change as an extra precaution.

Thanks for the prompt review.

File: source/common/network/connection_impl.cc [hunk 2]
```diff
@@ -349,13 +350,16 @@ void ConnectionImpl::readDisable(bool disable) {
...
+        (read_disable_count_ == 0 && want_read_)) {
+      // If the read_buffer_ is not empty or want_read_ is true, the connection may be able to
+      // process additional bytes even if there is no data in the kernel to kick off the filter
+      // chain. Alternately if the read buffer has data the fd could be read disabled. To handle
+      // these cases, fake an event to make sure the buffered data in the read buffer or in
+      // transport socket internal buffers gets processed regardless and ensure that we dispatch it
+      // via onRead.
       dispatch_buffered_data_ = true;
-      setReadBufferReady();
+      file_event_->activate(Event::FileReadyType::Read);
```
Comment (mattklein123) [inline source/common/network/connection_impl.cc:362]: For clarity I might revert this change, even though it redundantly sets want_read_, but nbd either way. Up to you.

File: source/common/network/connection_impl.cc (hunk 1 above)
Comment (mattklein123) [reply source/common/network/connection_impl.cc:565]: Sorry how is want_read_ cleared before onRead above? Maybe update the comment above also as to why we don't need to clear or how it's already cleared?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks this is much better agreed! I haven't looked at the tests but the change looks like the right shape. Happy to take another pass once the comments are fleshed out a bit.

/wait

File: source/common/network/connection_impl.cc (hunk 2 above)
Comment (antoniovicente) [reply source/common/network/connection_impl.cc]: Reverted.

File: source/common/network/connection_impl.cc (hunk 1 above)
Comment (antoniovicente) [reply source/common/network/connection_impl.cc:567]: Added comment.

File: source/common/network/connection_impl.cc [hunk 3]
```diff
@@ -349,11 +350,14 @@ void ConnectionImpl::readDisable(bool disable) {
       file_event_->setEnabled(Event::FileReadyType::Read | Event::FileReadyType::Write);
     }
 
-    if (consumerWantsToRead() && read_buffer_.length() > 0) {
-      // If the connection has data buffered there's no guarantee there's also data in the kernel
-      // which will kick off the filter chain. Alternately if the read buffer has data the fd could
-      // be read disabled. To handle these cases, fake an event to make sure the buffered data gets
-      // processed regardless and ensure that we dispatch it via onRead.
+    if ((consumerWantsToRead() && read_buffer_.length() > 0) ||
+        (read_disable_count_ == 0 && want_read_)) {
```
Comment (mattklein123) [inline source/common/network/connection_impl.cc:354]: Sorry one other question from another look: is it possible to somehow fold all of this logic into `consumerWantsToRead()`? It seems kind of odd that we have a function that is tracking the consumer wants to read and then a different wants to read boolean. If it's too hard to merge them maybe some better names for both the function and the boolean?

**Review by mattklein123 — DISMISSED** [review]
Thanks this LGTM modulo potential comment on naming. I will defer to @alyssawilk for final review. Thank you for iteration this is much cleaner!

File: source/common/network/connection_impl.cc (hunk 3 above)
Comment (antoniovicente) [reply source/common/network/connection_impl.cc]: Tried to improve on names and the if predicate.

**Comment by yanavlasov** [comment]
The change looks good and I think is safe. My paranoid self tells me the flag protecting it is a good idea though. I think we just need to flag protect setting the `transport_wants_read_ = true` in the `setReadBufferReady()` method. Up to you though.

File: test/common/network/connection_impl_test.cc [hunk 4]
```diff
@@ -1857,6 +1857,197 @@ TEST_F(MockTransportConnectionImplTest, ObjectDestructOrder) {
...
+  connection_->readDisable(true);
+  EXPECT_CALL(*transport_socket_, doRead(_)).Times(0);
+  file_ready_cb_(Event::FileReadyType::Read);
+
+  // Expect a read activate when re-enabling since the file ready cb has not done a read.
+  EXPECT_CALL(*file_event_, setEnabled(_));
+  EXPECT_CALL(*file_event_, activate(Event::FileReadyType::Read));
+  connection_->readDisable(false);
+
+  // Do a read to clear the want_read_ flag, verify that no read activation is scheduled.
```
Comment (yanavlasov) [inline test/common/network/connection_impl_test.cc:1905]: `want_read_` -> `transport_wants_read_` here and other places below.

**Review by yanavlasov — CHANGES_REQUESTED** [review]

**Review by alyssawilk — APPROVED** [review]

File: test/common/network/connection_impl_test.cc (hunk 4 above)
Comment (antoniovicente) [reply test/common/network/connection_impl_test.cc]: Done.  Nice catch.

**Review by yanavlasov — APPROVED** [review]

File: source/common/network/connection_impl.cc [hunk 5]
```diff
@@ -352,11 +353,17 @@ void ConnectionImpl::readDisable(bool disable) {
...
+    if (filterChainWantsData() && (read_buffer_.length() > 0 || transport_wants_read_)) {
+      // If the read_buffer_ is not empty or transport_wants_read_ is true, the connection may be
+      // able to process additional bytes even if there is no data in the kernel to kick off the
+      // filter chain. Alternately if the read buffer has data the fd could be read disabled. To
+      // handle these cases, fake an event to make sure the buffered data in the read buffer or in
+      // transport socket internal buffers gets processed regardless and ensure that we dispatch it
+      // via onRead.
+
+      // Sanity check: resumption with read_disable_count_ > 0 should only happen if the read
+      // buffer's high watermark has triggered.
```
Comment (mattklein123) [inline source/common/network/connection_impl.cc:365]: Stupid question: why do we bother with this extra logic to read when the disable count is still 1 and high watermark triggered? Is the idea that we already have the data so we might as well flush it? If the high watermark triggered it's probably going to be stuck on the other side, so mostly just wondering if this extra logic is actually worth it.

**Review by mattklein123 — APPROVED** [review]
Thanks LGTM with one small question.

File: source/common/network/connection_impl.cc (hunk 5 above)
Comment (antoniovicente) [reply source/common/network/connection_impl.cc:365]: This is part of the implementation of high-watermarks on the read buffer introduced in PR #11170

The parser is able to consume input from the read buffer, we just don't want to read additional bytes from the transport into the read buffer.

Comment (mattklein123) [reply source/common/network/connection_impl.cc:365]: So the idea here is that we allow reading data out in the hope that it will get us below the low watermark? OK thanks that makes sense.

Comment (antoniovicente) [reply source/common/network/connection_impl.cc:365]: Yes.

The common scenario is when the H1 parser stops consuming bytes from the read buffer and calls readDisable(true) once it detects the end of the current request message.  When request processing is complete, the H1 parser re-enables read. When H1 pipelining is in use, a full second request message could be in the read buffer and the read buffer may have triggered the high-watermark.

Comment (mattklein123) [reply source/common/network/connection_impl.cc:365]: Make sense, though note that we don't do pipelining.

**Comment by antoniovicente** [comment]
/retest

giving macos one last chance.

**Comment by PiotrSikora** [comment]
/backport

(carried from the issue #12304)

**Comment by PiotrSikora** [comment]
@cpakulski anything with `backport/review` label needs to be evaluated for backporting and if approved, that label should be changed to `backport/approved` and PRs sent to stable releases.

**Comment by cpakulski** [comment]
Backported to releases 1.13, 1.14, 1.15 and 1.16. Removing `backport/approved` label.
