### PR TITLE
port stripping for CONNECT

### LINKED ISSUE #15771: How to strip host port for HTTP CONNECT
*Description*:

I have configured dynamic forward proxy that terminates HTTP/1.1 CONNECT and I have the following flow:

```
HTTP client ---HTTP-CONNECT---> Envoy ---HTTPS---> destination
```

The HTTP client (Micronaut app) uses HTTP CONNECT even for **plain HTTP** requests (as opposed to most HTTP clients that use [extended HTTP](https://docs.mitmproxy.org/stable/concepts-howmitmproxyworks/#explicit-http) request that includes a schema and host specification). It means that something like that is sent to Envoy:

```
 CONNECT www.google.com:80
```

 When the request reaches Envoy, I use CONNECT  matcher:

```
- match:
    connect_matcher:
      {}
  route:
    cluster: dynamic_forward_proxy_cluster
    upgrade_configs:
      - upgrade_type: CONNECT
        connect_config:
          {}
```

and:

```
http_filters:
- name: envoy.filters.http.router
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
http_protocol_options: {}
upgrade_configs:
  - upgrade_type: CONNECT
```

and forward the request to dynamic forward proxy cluster:

```
- name: dynamic_forward_proxy_cluster
  connect_timeout: 1s
  lb_policy: CLUSTER_PROVIDED
  cluster_type:
    name: envoy.clusters.dynamic_forward_proxy
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
      dns_cache_config:
        name: dynamic_forward_proxy_cache_config
        dns_lookup_family: V4_ONLY
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
      common_tls_context:
        validation_context:
          trusted_ca: { filename: /etc/ssl/certs/ca-certificates.crt }
```

The cluster has TLS context configured - and as a result, I end up with the request to `https://www.google.com:80`:

```
 router decoding headers:
':authority', 'www.google.com:80'
':method', 'CONNECT'  // not sure about this one though - there is no CONNECT in Wireshark, so I assume that CONNECT is terminated correctly 
':scheme', 'https'
'x-forwarded-proto', 'http'
'x-request-id', '4394422c-fe2f-4741-a8c3-e46e8f6aa0f6'
'x-envoy-expected-rq-timeout-ms', '15000'
```

which leads to:

```
[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:215] [C4] TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

I believe the culprit is the `:80` port that is forwarded from the listener to the dynamic forward cluster and then the cluster uses port 80 to establish TLS. If I explicitly specify `http://www.google.com:443` in Micronaut client, everything works well.

There is [strip_any_host_port](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-strip-any-host-port) switch, but it explicitly states: 

> The port would be removed only if request method is not CONNECT.

My questions are:
1) Why is there an exception in `strip_any_host_port` for CONNECT?
2) Is there other way to strip the host port in my scenario?

### PR DESCRIPTION
**Pull request by alyssawilk**
Port stripping the host for CONNECT requests for the duration of the filter chain (reinstating before sending upstream)

Risk Level: medium (data plane change defaulted on)
Testing: new integration test
Docs Changes: inline
Release Notes: inline
Fixes #15771
Runtime guard: envoy.reloadable_features.strip_port_from_connect

### CODE REVIEW

File: include/envoy/stream_info/stream_info.h [hunk 1]
```diff
@@ -303,6 +307,11 @@ class StreamInfo {
    */
   virtual absl::optional<uint32_t> responseCode() const PURE;
 
+  /**
+   * @return the original port from the authority header iff it was removed by Envoy.
+   */
+  virtual absl::optional<uint32_t> removedHostPort() const PURE;
```
Comment (snowp) [inline include/envoy/stream_info/stream_info.h:313]: meta question but does it make sense to put stuff like this into FilterState so that we can avoid bloating StreamInfo with more and more stuff?

File: test/integration/tcp_tunneling_integration_test.cc [hunk 2]
```diff
@@ -299,6 +299,101 @@ TEST_P(ProxyingConnectIntegrationTest, ProxyConnect) {
...
+  ASSERT_TRUE(upstream_request_->waitForData(*dispatcher_, 5));
+
+  // Also test upstream to downstream data.
+  upstream_request_->encodeData(12, false);
+  response_->waitForBodyData(12);
+
+  cleanupUpstreamAndDownstream();
+}
+
+TEST_P(ProxyingConnectIntegrationTest, ProxyConnectWithPortStripping) {
```
Comment (snowp) [inline test/integration/tcp_tunneling_integration_test.cc:350]: How does this test differ from the other test besides flipping the runtime flag? Isn't the observed behavior the same here since the upstream request is CONNECT? Should we have a test here where we terminate the CONNECT?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks! A few comments

File: source/common/router/config_impl.cc [hunk 3]
```diff
@@ -567,6 +571,14 @@ void RouteEntryImplBase::finalizeRequestHeaders(Http::RequestHeaderMap& headers,
     request_headers_parser_->evaluateHeaders(headers, stream_info);
   }
 
+  // Restore the port if this was a CONNECT request.
```
Comment (alyssawilk) [inline source/common/router/config_impl.cc:574]: I want to call out one bit of weirdness here, which is that if you're going from H2 downstream to H1 upstream, upgrade requests come in as CONNECT and go out upstream as GET (with upgrade headers) but will have ports restored by this code.

I think it's reasonable given it started as CONNECT and IMO adding more comments would likely add more confusion.  We could comment somewhere, or we could move the re-addition down to the codec to avoid the corner case.  LMK if you prefer something different!

File: test/integration/tcp_tunneling_integration_test.cc (hunk 2 above)
Comment (alyssawilk) [reply test/integration/tcp_tunneling_integration_test.cc:350]: largely doesn't - it's just to test the legacy code path because I hadn't had it unit tested earlier.  fixed now :-)

File: source/common/router/config_impl.cc (hunk 3 above)
Comment (snowp) [reply source/common/router/config_impl.cc:574]: Do we have any docs on the CONNECT -> GET transformation? Might be good to include this bit of information there, just so that it's recorded somewhere. Potentially we could have this behavior covered in a test so that we're clear that this is the expected behavior?

File: source/common/router/config_impl.cc [hunk 4]
```diff
@@ -567,6 +571,14 @@ void RouteEntryImplBase::finalizeRequestHeaders(Http::RequestHeaderMap& headers,
...
+  if (stream_info.filterState().hasData<OriginalConnectPort>(OriginalConnectPort::key()) &&
+      headers.getHostValue().find(':') == absl::string_view::npos) {
```
Comment (snowp) [inline source/common/router/config_impl.cc:576]: qq is this sufficient to check for ports given that ipv6 addresses can have : in them? Or do we normalize that away somewhere?

File: source/common/router/config_impl.h [hunk 5]
```diff
@@ -37,6 +37,19 @@
 namespace Envoy {
 namespace Router {
 
+/**
+ * Original port from the authority header.
+ */
+class OriginalConnectPort : public StreamInfo::FilterState::Object {
+public:
+  OriginalConnectPort(uint32_t port) : port_(port) {}
```
Comment (snowp) [inline source/common/router/config_impl.h:45]: explicit

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks, just a few more comments

/wait

File: source/common/http/header_utility.h [hunk 6]
```diff
@@ -187,7 +187,8 @@ class HeaderUtility {
    * @brief Remove the port part from host/authority header if it is equal to provided port.
    * If port is not passed, port part from host/authority header is removed.
    */
-  static void stripPortFromHost(RequestHeaderMap& headers, absl::optional<uint32_t> listener_port);
+  static absl::optional<uint32_t> stripPortFromHost(RequestHeaderMap& headers,
```
Comment (lizan) [inline source/common/http/header_utility.h:190]: Add comment above about returned value.

**Review by lizan — COMMENTED** [review]
/lgtm api

File: test/common/http/header_utility_test.cc [hunk 7]
```diff
@@ -34,6 +34,25 @@ class HeaderUtilityTest : public testing::Test {
...
+      {"", false},               // empty
+      {":443", true},            // just port
+      {"192.168.1.1", false},    // ipv4
+      {"192.168.1.1:443", true}, // ipv4 w/ port
+      {"[fc00::1]:443", true},   // ipv6 w/ port
+      {"[fc00::1]", false},      // ipv6
+  };
+
+  for (const auto& host_pair : host_headers) {
+    EXPECT_EQ(HeaderUtility::getPortStart(host_pair.first) != absl::string_view::npos,
```
Comment (snowp) [inline test/common/http/header_utility_test.cc:50]: Maybe check that the index is what we expect?

**Review by snowp — COMMENTED** [review]
Thanks! Would it be a lot of work to add an integration test that shows that filters see the port   stripped?

File: test/common/http/header_utility_test.cc (hunk 7 above)
Comment (alyssawilk) [reply test/common/http/header_utility_test.cc:50]: I'm going to claim the use in actual port removal validates that, sound reasonable?
(working on the e2e test either way)

Comment (snowp) [reply test/common/http/header_utility_test.cc:50]: Yep, sounds good!

**Review by lizan — COMMENTED** [review]
/lgtm api
defer to @snowp

**Review by snowp — APPROVED** [review]
Thanks!
