### PR TITLE
stats: envoy prometheus endpoint fails promlint #2597

### LINKED ISSUE #2597: envoy prometheus endpoint fails promlint
*Title*: *envoy prometheus endpoint fails promlint*

*Description*:
>The admin endpoint of envoy when queried as a prometheus endpoint fails promlint. Promlint is a sanity check tool offered by Prometheus to check the correctness of a prometheus endpoint.

[optional *Relevant Links*:]
>About promlint: Promlint is a metrics sanity checker exposed as part of promtool. As per their documentation:
```
Pass Prometheus metrics over stdin to lint them for consistency and correctness.
examples:
$ cat metrics.prom | promtool check metrics
$ curl -s http://localhost:9090/metrics | promtool check metrics
`)
```

The error reported by promlint is as follows:
```
curl -s https://gist.githubusercontent.com/vjsamuel/5898d02f8039d8d1bae4d8642182d1c3/raw/deff0c16f746bb2ab7a959c4d5ed9856d17c425d/gistfile1.txt | ./promtool check metrics
error while linting: text format parsing error in line 9: second TYPE line for metric name "envoy_listener_http_downstream_rq_xx", or TYPE reported after samples
```

Can this be fixed please so that the prometheus endpoint abides to the standard?

### PR DESCRIPTION
**Pull request by pitiwari**
Description: Fixes #2597"

The admin endpoint of envoy when queried as a prometheus endpoint fails promlint.
Promlint is a sanity check tool offered by Prometheus to check the correctness
of a prometheus endpoint.

following issues were fixed
-fixed issue with metric type being printed twice
-added unit test as well

Risk Level: Low

### CODE REVIEW

File: test/server/http/admin_test.cc [hunk 1]
```diff
@@ -293,5 +294,57 @@ TEST(PrometheusStatsFormatter, FormattedTags) {
...
+  Stats::CounterSharedPtr c1(
+      new Stats::CounterImpl(*data, alloc_, std::string(name), std::move(tags)));
+  std::list<Stats::CounterSharedPtr> counters;
+  counters.push_back(c1);
+
+  std::string name1 = "cluster.test_cluster_1.upstream_cx_total";
+  std::vector<Stats::Tag> tags1;
+  Stats::Tag tag2 = {"another_tag_name", "another_tag-value"};
+  tags1.push_back(tag2);
+  Stats::HeapRawStatDataAllocator alloc1_;
```
Comment (mrice32) [inline test/server/http/admin_test.cc]: @pitiwari I think the issue is a little subtle, but I think this is because the allocators are being destructed before the stats themselves.  

Fix: try declaring a single allocator as the first line in this test (to ensure it is the last thing to be destructed), and then use that allocator to allocate the data for all of the stats you create below.

Quick explanation of what's happening: the two lists `counters` and `gauges` are created before some of the allocators used to allocate the data for the `CounterImpl`s and `GuageImpl`s that they own.  This will delay the destruction of these stats until after their allocators are destructed, which means that the `CounterImpl` and `GaugeImpl` destructors will try to call methods on an object that has already been destructed.  The rule with these allocators is that they must outlive everything they allocate.

**Comment by pitiwari** [comment]
@mrice32 thanks. I had modified ut to create heap data allocator only once . UTS are passing now without needing any change in destructor, but still ref counting issue in HeapDataAllocator needs to be resolved since it is never incrementing or decrementing ref count.

**Comment by mrice32** [comment]
@pitiwari, agreed.  IIUC, that's being tracked #2453.  Are you interested in tackling that in #2752?  If so, that'd be awesome!

**Comment by pitiwari** [comment]
@mrice32 i can start looking into #2752 (#2453) . I have some other tasks in a plate so might take a week or two to fix it. In the meantime please review this pr and update with your comments

File: test/server/http/admin_test.cc [hunk 2]
```diff
@@ -293,5 +294,105 @@ TEST(PrometheusStatsFormatter, FormattedTags) {
   EXPECT_EQ(expected, actual);
 }
 
+TEST(PrometheusStatsFormatter, statsAsPrometheus) {
+
+  // create two clusters and two gauges with metric name being same same and
+  // different tag names. In the end there only two metric names
+  // should be inserted, one for gauge and one for counter
+
+  Stats::TagExtractorImpl tag_extractor("cluster_name", "^cluster\\.((.+?)\\.)");
```
Comment (mrice32) [inline test/server/http/admin_test.cc]: nit: are you using `tag_extractor`?

File: test/server/http/admin_test.cc [hunk 3]
```diff
@@ -293,5 +294,105 @@ TEST(PrometheusStatsFormatter, FormattedTags) {
   EXPECT_EQ(expected, actual);
 }
 
+TEST(PrometheusStatsFormatter, statsAsPrometheus) {
+
+  // create two clusters and two gauges with metric name being same same and
```
Comment (mrice32) [inline test/server/http/admin_test.cc]: nit: I would suggest that you change the comment to the following (similar for the comment in the second test):
```
Create two counters and two gauges with each pair having the same name, but having different tag names and values.  `statsAsPrometheus()` should return two implying it found two unique stat names.

File: source/server/http/admin.h [hunk 4]
```diff
@@ -250,9 +250,9 @@ class PrometheusStatsFormatter {
    * Extracts counters and gauges and relevant tags, appending them to
    * the response buffer after sanitizing the metric / label names.
    */
-  static void statsAsPrometheus(const std::list<Stats::CounterSharedPtr>& counters,
-                                const std::list<Stats::GaugeSharedPtr>& gauges,
-                                Buffer::Instance& response);
+  static uint64_t statsAsPrometheus(const std::list<Stats::CounterSharedPtr>& counters,
```
Comment (mrice32) [inline source/server/http/admin.h]: nit: please update the method documentation with `@return uint64_t explanation of return value.`

File: test/server/http/admin_test.cc [hunk 5]
```diff
@@ -293,5 +294,105 @@ TEST(PrometheusStatsFormatter, FormattedTags) {
...
+  EXPECT_EQ(2UL, PrometheusStatsFormatter::statsAsPrometheus(counters, gauges, response));
+}
+
+TEST(PrometheusStatsFormatter, statsAsPrometheus2) {
+
+  // create two clusters and two gauges with different metric and tag name
+  // In the end there should be 4 metric names inserted 2 for gauge
+  //`and 2 for counter metric names
+
+  Stats::TagExtractorImpl tag_extractor("cluster_name", "^cluster\\.((.+?)\\.)");
```
Comment (mrice32) [inline test/server/http/admin_test.cc]: nit: same as above - is this variable being used anywhere?

**Comment by mrice32** [comment]
@pitiwari side note: if you add "Fixes #2597" in the description of the PR, it will automatically close the issue when it gets merged.

**Comment by pitiwari** [comment]
@mrice32 thanks i had updated the code based on review comments

**Comment by mrice32** [comment]
@pitiwari Make sure you sign off on all your commits to allow the DCO to pass (see https://github.com/probot/dco#how-it-works).  Also, make sure you run the formatter on your code.  You can do this with docker by running `./ci/run_envoy_docker.sh './ci/do_ci.sh fix_format'`

File: test/server/http/admin_test.cc [hunk 6]
```diff
@@ -293,5 +294,121 @@ TEST(PrometheusStatsFormatter, FormattedTags) {
...
+  gauges.push_back(g);
+  }
+
+  Buffer::OwnedImpl response;
+  EXPECT_EQ(2UL, PrometheusStatsFormatter::statsAsPrometheus(counters, gauges, response));
+}
+
+TEST(PrometheusStatsFormatter, UniqueMetricName) {
+
+  //Create two counters and two gauges with each pair having the different name,
```
Comment (mrice32) [inline test/server/http/admin_test.cc]: nit - can we rephrase to: "Create two counters and two gauges, all with unique names. statsAsPrometheus() should return four implying it found four unique stat names."

Comment (pitiwari) [reply test/server/http/admin_test.cc]: done thanks

File: test/server/http/admin_test.cc [hunk 7]
```diff
@@ -293,5 +294,121 @@ TEST(PrometheusStatsFormatter, FormattedTags) {
   EXPECT_EQ(expected, actual);
 }
 
+TEST(PrometheusStatsFormatter, MetricNameCollison) {
+
+  // Create two counters and two gauges with each pair having the same name,
+  // but having different tag names and values.
+  //`statsAsPrometheus()` should return two implying it found two unique stat names
```
Comment (mrice32) [inline test/server/http/admin_test.cc]: Sorry, one more nit that I didn't notice the first few times through: please remove the backticks from `statsAsPrometheus()`.

**Comment by junr03** [comment]
looks like other than the DCO, @mrice32 is done with comments. @ggreenway or @htuch I think we can kick this up to you.

**Comment by ggreenway** [comment]
See this for how to fix DCO:

https://github.com/envoyproxy/envoy/blob/c5a982788e6b10d9a7831e201acc04d5953c703a/CONTRIBUTING.md#fixing-dco

**Comment by pitiwari** [comment]
rebased all the commits and added dco

**Comment by ggreenway** [comment]
It looks like your DCO value doesn't match the author value in your commits, so the DCO-bot still isn't accepting it. Sorry for the pedantic-ness of the DCO-bot. Can you please make the two match?

**Comment by pitiwari** [comment]
seems like all tests passed, can we go ahead and commit ?

**Comment by ggreenway** [comment]
@pitiwari Thanks for making the DCO-bot happy. I'm going to let @htuch do a final review pass and merge.

File: source/server/http/admin.h [hunk 8]
```diff
@@ -249,10 +249,11 @@ class PrometheusStatsFormatter {
   /**
    * Extracts counters and gauges and relevant tags, appending them to
    * the response buffer after sanitizing the metric / label names.
+   * @return int64_t total number of metric types inserted in response.
```
Comment (htuch) [inline source/server/http/admin.h]: Nit: s/int64_t/uint64_t/

File: test/server/http/admin_test.cc [hunk 9]
```diff
@@ -293,5 +294,121 @@ TEST(PrometheusStatsFormatter, FormattedTags) {
...
+  std::list<Stats::CounterSharedPtr> counters;
+  std::list<Stats::GaugeSharedPtr> gauges;
+
+  {
+    std::string name = "cluster.test_cluster_1.upstream_cx_total";
+    std::vector<Stats::Tag> cluster_tags;
+    Stats::Tag tag = {"a.tag-name", "a.tag-value"};
+    cluster_tags.push_back(tag);
+    Stats::RawStatData* data = alloc.alloc(name);
+    Stats::CounterSharedPtr c(
```
Comment (htuch) [inline test/server/http/admin_test.cc]: `c = std::make_shared<...` (here and below)

File: test/server/http/admin_test.cc [hunk 10]
```diff
@@ -293,5 +294,121 @@ TEST(PrometheusStatsFormatter, FormattedTags) {
...
+
+  {
+    std::string name = "cluster.test_cluster_1.upstream_cx_total";
+    std::vector<Stats::Tag> cluster_tags;
+    Stats::Tag tag = {"another_tag_name", "another_tag-value"};
+    cluster_tags.push_back(tag);
+    Stats::RawStatData* data = alloc.alloc(name);
+    Stats::CounterSharedPtr c(
+        new Stats::CounterImpl(*data, alloc, std::string(name), std::move(cluster_tags)));
+    counters.push_back(c);
```
Comment (htuch) [inline test/server/http/admin_test.cc]: This scenario seems contrived. How does it happen in practice?

Comment (pitiwari) [reply test/server/http/admin_test.cc]: counterImpl/GuageImpl are derived classes from counter/gauge class so i create two counters and two gauges and pass them with same or different metric names in two different tests and check if metric name was same then gauge/counter are inserted only once for each unique metric name . Promlint tool was failing due to same metric name printed multiple times.

Comment (htuch) [reply test/server/http/admin_test.cc]: I understand how this happens in the test, I'm curious though how this happens in actual Envoy use. How did you discover this? What were the offending counters?

**Comment by pitiwari** [comment]
@htuch can you please have a look. I had updated code based on your review comments

File: test/server/http/admin_test.cc (hunk 10 above)
Comment (giganteous) [reply test/server/http/admin_test.cc]: The envoy_listener_http_downstream_rq_xx counter appears many times, each time with a different set of tags and metrics that come with that tag (dimension). 

For each upstream server you get 5 envoy_listener_http_downstream_rq_xx counters: one for each http responsecode (1, 2, 3, 4, 5) as the value for the "envoy_response_code_class" tag.
