### PR TITLE
upstream: fix eds crash when changing priorities

### LINKED ISSUE #8764: Segmentation fault on host priority updates for EDS clusters
*Title*: Segmentation fault on host priority updates for EDS clusters

*Description*:
This issue is similar to https://github.com/envoyproxy/envoy/issues/6395, though the stack trace is different.

In this setup hosts are mapped to different localities whose priorities are dynamically updated by XDS control plane to optionally enable zonal affinity. When enabled, same locality endpoints get higher priority than other locality endpoints, or else all have the same priority.
When frequently updating locality priorities (e.g. enable/disable zonal affinity), I occasionally see Envoy crashing with the stack trace below. Setting the cluster load-assignment in CDS (with STATIC DiscoveryType), instead of using EDS does not show any issues.

```
[2019-10-25 01:25:35.319][69][critical][assert] [external/envoy/source/common/upstream/eds.cc:148] assert failure: std::all_of(current_hosts_copy->begin(), current_hosts_copy->end(), [&](const auto& host) { return host->priority() == priority; }).
```

*Relevant Links*:
Issue: https://github.com/envoyproxy/envoy/issues/6395

*Envoy Version*: v1.10.0

*Call Stack*:
```
[2019-10-25 01:24:58.358][69][warning][config] [bazel-out/k8-dbg/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13, 
[2019-10-25 01:25:35.319][69][critical][assert] [external/envoy/source/common/upstream/eds.cc:148] assert failure: std::all_of(current_hosts_copy->begin(), current_hosts_copy->end(), [&](const auto& host) { return host->priority() == priority; }).
[2019-10-25 01:25:35.319][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Aborted, suspect faulting address 0x45
[2019-10-25 01:25:35.319][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-10-25 01:25:35.335][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #0: Envoy::SignalAction::sigHandler() [0x5571674f410a]
[2019-10-25 01:25:35.335][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #1: __restore_rt [0x7f6ad4e8d890]
[2019-10-25 01:25:35.350][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #2: Envoy::Upstream::EdsClusterImpl::BatchUpdateHelper::batchUpdate() [0x557166ea8d8e]
[2019-10-25 01:25:35.365][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #3: Envoy::Upstream::PrioritySetImpl::batchHostUpdate() [0x557166e70b0a]
[2019-10-25 01:25:35.380][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #4: Envoy::Upstream::EdsClusterImpl::onConfigUpdate() [0x557166ea9318]
[2019-10-25 01:25:35.395][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #5: Envoy::Config::GrpcMuxSubscriptionImpl::onConfigUpdate() [0x557166bd2f28]
[2019-10-25 01:25:35.410][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #6: Envoy::Config::GrpcMuxImpl::handleResponse() [0x557166eb0805]
[2019-10-25 01:25:35.425][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #7: Envoy::Config::GrpcStream<>::onReceiveMessage() [0x557166eb6905]
[2019-10-25 01:25:35.440][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #8: Envoy::Grpc::TypedAsyncStreamCallbacks<>::onReceiveMessageUntyped() [0x557166eb6798]
[2019-10-25 01:25:35.455][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #9: Envoy::Grpc::AsyncStreamImpl::onData() [0x557166f07c74]
[2019-10-25 01:25:35.471][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #10: Envoy::Http::AsyncStreamImpl::encodeData() [0x557166f0d0e7]
[2019-10-25 01:25:35.486][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #11: Envoy::Router::Filter::onUpstreamData() [0x557166f1ba72]
[2019-10-25 01:25:35.501][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #12: Envoy::Router::Filter::UpstreamRequest::decodeData() [0x557166f1db3c]
[2019-10-25 01:25:35.516][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #13: Envoy::Http::StreamDecoderWrapper::decodeData() [0x557166e59901]
[2019-10-25 01:25:35.531][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #14: Envoy::Http::Http2::ConnectionImpl::onFrameReceived() [0x557166fb9312]
[2019-10-25 01:25:35.546][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #15: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::{lambda()#6}::operator()() [0x557166fbb3f9]
[2019-10-25 01:25:35.561][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #16: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::{lambda()#6}::_FUN() [0x557166fbb428]
[2019-10-25 01:25:35.576][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #17: nghttp2_session_on_data_received [0x557166fcd530]
[2019-10-25 01:25:35.591][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #18: nghttp2_session_mem_recv [0x557166fd1aab]
[2019-10-25 01:25:35.606][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #19: Envoy::Http::Http2::ConnectionImpl::dispatch() [0x557166fb84db]
[2019-10-25 01:25:35.620][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #20: Envoy::Http::CodecClient::onData() [0x557166ef26f4]
[2019-10-25 01:25:35.635][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #21: Envoy::Http::CodecClient::CodecReadFilter::onData() [0x557166ef319e]
[2019-10-25 01:25:35.650][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #22: Envoy::Network::FilterManagerImpl::onContinueReading() [0x557166c37e7b]
[2019-10-25 01:25:35.665][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #23: Envoy::Network::FilterManagerImpl::onRead() [0x557166c37f92]
[2019-10-25 01:25:35.680][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #24: Envoy::Network::ConnectionImpl::onRead() [0x557166c2eb42]
[2019-10-25 01:25:35.695][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #25: Envoy::Network::ConnectionImpl::onReadReady() [0x557166c30309]
[2019-10-25 01:25:35.710][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #26: Envoy::Network::ConnectionImpl::onFileEvent() [0x557166c300a7]
[2019-10-25 01:25:35.726][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #27: Envoy::Network::ConnectionImpl::ConnectionImpl()::{lambda()#3}::operator()() [0x557166c2c88d]
[2019-10-25 01:25:35.741][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #28: std::_Function_handler<>::_M_invoke() [0x557166c321f1]
[2019-10-25 01:25:35.756][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #29: std::function<>::operator()() [0x557166c263aa]
[2019-10-25 01:25:35.772][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #30: Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::operator()() [0x557166c26006]
[2019-10-25 01:25:35.787][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #31: Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::_FUN() [0x557166c26084]
[2019-10-25 01:25:35.802][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #32: event_process_active_single_queue.isra.31 [0x5571672462e3]
[2019-10-25 01:25:35.817][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #33: event_process_active [0x55716724683f]
[2019-10-25 01:25:35.832][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #34: event_base_loop [0x55716724aef0]
[2019-10-25 01:25:35.847][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #35: Envoy::Event::LibeventScheduler::run() [0x557166c45358]
[2019-10-25 01:25:35.862][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #36: Envoy::Event::DispatcherImpl::run() [0x557166c21420]
[2019-10-25 01:25:35.877][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #37: Envoy::Server::InstanceImpl::run() [0x557166b6e58b]
[2019-10-25 01:25:35.892][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #38: Envoy::MainCommonBase::run() [0x5571664ffa5c]
[2019-10-25 01:25:35.906][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #39: Envoy::MainCommon::run() [0x5571664fdd04]
[2019-10-25 01:25:35.921][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #40: main [0x5571664fd7bb]
[2019-10-25 01:25:35.921][69][critical][backtrace] [bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #41: [0x7f6ad470db97]
```

### PR DESCRIPTION
**Pull request by wozz**
Description: EDS crashes when priorities change, see #8764 

When receiving an EDS config update, if there is an empty priority in the new update, the update function gets skipped instead of updating the priority with an empty list of hosts. This is particularly bad when the update would move an existing host to a different priority, because the result is the host ends up in two priorities because it doesn't get removed from the existing priority. This change ensures that the update function is called with an empty list of hosts if the priority was previously configured with hosts and the new config does not contain hosts in that priority.

Risk Level: medium
Testing: added integration test that failed with previous code, updated unit tests to include a previously failing case
Docs Changes: none
Release Notes: 
Fixes #8764 

cc @snowp

### CODE REVIEW

**Comment by wozz** [comment]
@snowp I think this is ready for review now

File: source/common/upstream/eds.cc [hunk 1]
```diff
@@ -62,26 +62,31 @@ void EdsClusterImpl::BatchUpdateHelper::batchUpdate(PrioritySet::HostUpdateCb& h
...
+    }
     if (priority_state[i].first != nullptr) {
-      if (parent_.locality_weights_map_.size() <= i) {
-        parent_.locality_weights_map_.resize(i + 1);
-      }
       cluster_rebuilt |= parent_.updateHostsPerLocality(
           i, overprovisioning_factor, *priority_state[i].first, parent_.locality_weights_map_[i],
           priority_state[i].second, priority_state_manager, updated_hosts);
+    } else {
+      // if the new update contains a priority with no hosts, call update with an empty set of hosts
```
Comment (snowp) [inline source/common/upstream/eds.cc]: nit: use proper  grammar (capitalization, punctuation, etc.) in comments

File: source/common/upstream/eds.cc [hunk 2]
```diff
@@ -62,26 +62,31 @@ void EdsClusterImpl::BatchUpdateHelper::batchUpdate(PrioritySet::HostUpdateCb& h
...
+      cluster_rebuilt |= parent_.updateHostsPerLocality(
+          i, overprovisioning_factor, empty_hosts, parent_.locality_weights_map_[i],
```
Comment (snowp) [inline source/common/upstream/eds.cc]: can you just create the `empty_hosts`/`empty_locality_map`inline? i.e. just do `{}` or `HostVector{}` instead of using a variable

File: test/common/upstream/eds_test.cc [hunk 3]
```diff
@@ -833,6 +840,28 @@ TEST_F(EdsTest, EndpointMovedToNewPriority) {
...
+    auto& hosts = cluster_->prioritySet().hostSetsPerPriority()[1]->hosts();
+    EXPECT_EQ(hosts.size(), 2);
+
+    // The endpoints were healthy, so moving them around should preserve that.
+    EXPECT_FALSE(hosts[0]->healthFlagGet(Host::HealthFlag::FAILED_ACTIVE_HC));
+    EXPECT_FALSE(hosts[1]->healthFlagGet(Host::HealthFlag::FAILED_ACTIVE_HC));
+  }
+
+  {
+    // priority 1 should now be empty
```
Comment (snowp) [inline test/common/upstream/eds_test.cc]: nit: casing + punctuation

File: test/common/upstream/eds_test.cc [hunk 4]
```diff
@@ -1361,14 +1390,14 @@ TEST_F(EdsTest, EndpointHostsPerPriority) {
   EXPECT_EQ(0, cluster_->prioritySet().hostSetsPerPriority()[2]->hosts().size());
   EXPECT_EQ(5, cluster_->prioritySet().hostSetsPerPriority()[3]->hosts().size());
 
-  // Update the number of hosts in priority #4. Make sure no other priority
-  // levels are affected.
+  // Update the number of hosts in priority #4. Make sure other priority
+  // levels are removed
```
Comment (snowp) [inline test/common/upstream/eds_test.cc]: nit: `Make sure we clear out the priorities previously occupied by the hosts.`

File: test/integration/eds_integration_test.cc [hunk 5]
```diff
@@ -25,6 +25,39 @@ class EdsIntegrationTest : public testing::TestWithParam<Network::Address::IpVer
...
+  // filesystem delivery to simplify test mechanics.
+  void setEndpointsInPriorities(uint32_t first_priority, uint32_t second_priority,
+                                bool await_update = true) {
+    envoy::api::v2::ClusterLoadAssignment cluster_load_assignment;
+    cluster_load_assignment.set_cluster_name("cluster_0");
+
+    {
+      for (uint32_t i = 0; i < first_priority; ++i) {
+        auto* locality_lb_endpoints = cluster_load_assignment.add_endpoints();
+        locality_lb_endpoints->mutable_locality()->set_zone(&"1234"[i]);
```
Comment (snowp) [inline test/integration/eds_integration_test.cc]: i think you might not need to set the zone at all? Does it still reproduce if we remove this line here and below?

File: test/integration/eds_integration_test.cc [hunk 6]
```diff
@@ -112,6 +145,22 @@ class EdsIntegrationTest : public testing::TestWithParam<Network::Address::IpVer
 INSTANTIATE_TEST_SUITE_P(IpVersions, EdsIntegrationTest,
                          testing::ValuesIn(TestEnvironment::getIpVersionsForTest()));
 
+TEST_P(EdsIntegrationTest, Http2UpdatePriorities) {
```
Comment (snowp) [inline test/integration/eds_integration_test.cc]: can you include a comment to explain what this test test for?

File: test/common/upstream/eds_test.cc (hunk 3 above)
Comment (snowp) [inline test/common/upstream/eds_test.cc]: this is priority 0, not 1? 

I think it might make sense to have the assertions against P0 before P1, so maybe move this up before the checks against P1?

File: source/common/upstream/eds.cc (hunk 2 above)
Comment (wozz) [reply source/common/upstream/eds.cc]: I get an error when I try to do this for empty_locality_map, but it looks like empty_hosts can be converted.

File: source/common/upstream/eds.cc [hunk 7]
```diff
@@ -62,32 +62,37 @@ void EdsClusterImpl::BatchUpdateHelper::batchUpdate(PrioritySet::HostUpdateCb& h
   const uint32_t overprovisioning_factor = PROTOBUF_GET_WRAPPED_OR_DEFAULT(
       cluster_load_assignment_.policy(), overprovisioning_factor, kDefaultOverProvisioningFactor);
 
+  LocalityWeightsMap empty_locality_map;
```
Comment (snowp) [inline source/common/upstream/eds.cc]: i think this can go next to the line where it's used

File: test/common/upstream/eds_test.cc [hunk 8]
```diff
@@ -833,6 +840,28 @@ TEST_F(EdsTest, EndpointMovedToNewPriority) {
     // around should preserve that.
     EXPECT_FALSE(hosts[0]->healthFlagGet(Host::HealthFlag::FAILED_ACTIVE_HC));
   }
+
+  // Moves the endpoints all to priority 1.
```
Comment (snowp) [inline test/common/upstream/eds_test.cc]: nit: `Moves all the endpoints to priority 1.`

File: source/common/upstream/eds.cc (hunk 7 above)
Comment (wozz) [reply source/common/upstream/eds.cc]: it's used twice... should I declare it twice separately?

Comment (snowp) [reply source/common/upstream/eds.cc]: my bad, just keep it as is then

**Comment by wozz** [comment]
looks like build is broken due to #9538
