### PR TITLE
Move up life cycle callbacks before config_ to prevent use-after-free bug

### LINKED ISSUE #9292: Use-after-free problem with Cluster update callbacks
Cluster update callbacks[[1]](https://github.com/envoyproxy/envoy/blob/80cea119e0910e9c41ba543017bfc3ee0cb0909f/include/envoy/upstream/cluster_manager.h#L39) (introduced in https://github.com/envoyproxy/envoy/pull/2814) cannot be used correctly if the callback is owned by an object destroyed *after* the Envoy server's instance `thread_local_`[[2]](https://github.com/envoyproxy/envoy/blob/80cea119e0910e9c41ba543017bfc3ee0cb0909f/source/server/server.h#L276) object.

The cluster manager's list of update callbacks is freed once during thread local storage cleanup in the `Envoy::Server::InstanceImpl::terminate()` function[[3]](https://github.com/envoyproxy/envoy/blob/80cea119e0910e9c41ba543017bfc3ee0cb0909f/source/server/server.cc#L545), in which the Envoy instance deletes thread local data bound to the main thread, and then freed a second time during the destructor of its holding class (in our case a `Stats` sink) when the `Envoy::Server::InstanceImpl` instance itself is being destroyed.

During Envoy server termination, I am getting a use-after-free error when using ASAN. See sanitized ASAN stack-trace [here](https://github.com/envoyproxy/envoy/files/3942039/envoy_cluster_update_callbacks_asan.txt).
 
Ideally there would be some mechanism to release the RAII handle object before thread local data is freed, or perhaps move the `thread_local_` object earlier in the list of fields belonging to the Envoy server instance.

I'm curious if anyone else sees this an issue or if perhaps I'm misunderstanding how to use or store the `ClusterUpdateCallbacksHandle` object returned from the `ClusterManager`.

### PR DESCRIPTION
**Pull request by fcfort**
Signed-off-by: Frank Fort <ffort@google.com>

Description: Cluster update callbacks (introduced in #2814) cannot be used correctly if the callback is owned by an object destroyed after the Envoy server's instance `thread_local_` object. Using a server lifecycle callback to free the cluster update callback handle also introduces another separate use-after-free bug related to the ordering of destruction of fields in `Envoy::Server::Instance`.

This PR mitigates the issue by moving the server lifecycle callbacks lists up above the `Configuration::MainImpl config_` object so that the Stats sinks can remove their handle before the server lifecycle callbacks lists destructor gets a chance to free the handle again.

See #9292 for more details.

Risk Level: Low
Testing: Ran `bazel test test/exe/... test/server/...` successfully.
Docs Changes: N/A
Release Notes: N/A
Fixes #9292

### CODE REVIEW

**Comment by mattklein123** [comment]
As you say while this is kicking the can down the road it seems OK to me. Can you add some kind of test that would cover this? Maybe a server_test with a fake stat sink that replicates your internal problem?

/wait

File: test/server/server_test.cc [hunk 1]
```diff
@@ -957,6 +957,56 @@ TEST_P(StaticValidationTest, ClusterUnknownField) {
...
+};
+
+REGISTER_FACTORY(CallbacksStatsSinkFactory, Server::Configuration::StatsSinkFactory);
+
+// This test ensures that a stats sink can use cluster update callbacks properly. Using only a
+// cluster update callback is insufficient to protect against double-free bugs, so a server
+// lifecycle callback is also used to ensure that the cluster update callback is freed during
+// Server::Instance's destruction. See issue #9292 for more details.
+TEST_P(ServerInstanceImplTest, CallbacksStatsSinkTest) {
+  ENVOY_LOG_MISC(warn, "starting server");
```
Comment (mattklein123) [inline test/server/server_test.cc]: nit: is this needed?

Comment (fcfort) [reply test/server/server_test.cc]: Sorry, missed that. Removed.
