### PR TITLE
Fix compilation in http_integration.cc

### LINKED ISSUE #8894: Compilation error in http_integration.cc
The `HttpIntegrationTest::waitForNextUpstreamRequest` in test/integration/http_integration.cc has the following code:

```
  uint64_t upstream_with_request;
  if (!fake_upstream_connection_) {
    ...
        upstream_with_request = upstream_index;
    ...
  }
  ...
  return upstream_with_request;
```

and it fails to compile with
```
test/integration/http_integration.cc:364:10: error: 'upstream_with_request' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   return upstream_with_request;
          ^~~~~~~~~~~~~~~~~~~~~
```

(gcc, opt build)

### PR DESCRIPTION
**Pull request by ascheglov**
Fixes -Werror=maybe-uninitialized

Risk Level: Low
Testing: yes
Docs Changes: n/a
Release Notes: n/a
Fixes #8894

### CODE REVIEW

File: test/integration/protocol_integration_test.cc [hunk 1]
```diff
@@ -422,6 +422,7 @@ TEST_P(DownstreamProtocolIntegrationTest, RetryHostPredicateFilter) {
 
   // Note how we're expecting each upstream request to hit the same upstream.
   auto upstream_idx = waitForNextUpstreamRequest({0, 1});
+  ASSERT_LT(upstream_idx, fake_upstreams_.size());
```
Comment (ascheglov) [inline test/integration/protocol_integration_test.cc]: That's the only place where the return value was used.

Comment (mattklein123) [reply test/integration/protocol_integration_test.cc]: Instead can you have it return an absl::optional? That is more future proof IMO.
