### PR TITLE
Fix race in file_system_buffer filter (destroy filter vs open file)

### LINKED ISSUE #21856: Test flake in //test/extensions/filters/http/file_system_buffer:file_system_buffer_integration_test
Failed in CI, able to reproduce locally:

`bazel test -c fastbuild --config=clang --test_output=errors //test/extensions/filters/http/file_system_buffer:file_system_buffer_integration_test --runs_per_test=100`

```
INFO: From Testing //test/extensions/filters/http/file_system_buffer:file_system_buffer_integration_test (shard 1 of 2, run 15 of 100):
==================== Test output for //test/extensions/filters/http/file_system_buffer:file_system_buffer_integration_test (shard 1 of 2, run 15 of 100):
Note: This is test shard 1 of 2.
[==========] Running 76 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 76 tests from Protocols/FileSystemBufferIntegrationTest
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_HttpDownstream_HttpUpstreamNghttp2NoDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_HttpDownstream_HttpUpstreamNghttp2NoDeferredProcessing (415 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_HttpDownstream_Http2UpstreamWrappedNghttp2NoDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_HttpDownstream_Http2UpstreamWrappedNghttp2NoDeferredProcessing (366 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_HttpDownstream_Http2UpstreamOghttp2NoDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_HttpDownstream_Http2UpstreamOghttp2NoDeferredProcessing (350 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_HttpDownstream_Http2UpstreamNghttp2WithDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_HttpDownstream_Http2UpstreamNghttp2WithDeferredProcessing (304 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_HttpUpstreamWrappedNghttp2NoDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_HttpUpstreamWrappedNghttp2NoDeferredProcessing (327 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_HttpUpstreamOghttp2NoDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_HttpUpstreamOghttp2NoDeferredProcessing (308 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_HttpUpstreamNghttp2WithDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_HttpUpstreamNghttp2WithDeferredProcessing (335 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_Http2UpstreamWrappedNghttp2NoDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_Http2UpstreamWrappedNghttp2NoDeferredProcessing (316 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_Http2UpstreamOghttp2NoDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_Http2UpstreamOghttp2NoDeferredProcessing (313 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_Http2UpstreamNghttp2WithDeferredProcessing
[       OK ] Protocols/FileSystemBufferIntegrationTest.NotFoundBodyBuffer/IPv4_Http2Downstream_Http2UpstreamNghttp2WithDeferredProcessing (303 ms)
[ RUN      ] Protocols/FileSystemBufferIntegrationTest.RequestAndResponseWithGiantBodyBuffer/IPv4_HttpDownstream_Http2UpstreamNghttp2NoDeferredProcessing
[2022-06-23 17:58:18.551][146][critical][assert] [source/extensions/common/async_files/async_file_context_thread_pool.cc:220] assert failure: file_descriptor_ == -1.
[2022-06-23 17:58:18.552][146][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x3a06c8740000000e
[2022-06-23 17:58:18.552][146][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2022-06-23 17:58:18.552][146][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 0/1.23.0-dev/test/DEBUG/BoringSSL
[2022-06-23 17:58:18.588][146][critical][backtrace] [./source/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x440e948]
[2022-06-23 17:58:18.588][146][critical][backtrace] [./source/server/backtrace.h:96] #1: __restore_rt [0x7fcbd08f1980]
[2022-06-23 17:58:18.624][146][critical][backtrace] [./source/server/backtrace.h:96] #2: __gnu_cxx::new_allocator<>::destroy<>() [0x1da61a9]
[2022-06-23 17:58:18.660][146][critical][backtrace] [./source/server/backtrace.h:96] #3: std::allocator_traits<>::destroy<>() [0x1da614d]
[2022-06-23 17:58:18.696][146][critical][backtrace] [./source/server/backtrace.h:96] #4: std::_Sp_counted_ptr_inplace<>::_M_dispose() [0x1da5f96]
[2022-06-23 17:58:18.733][146][critical][backtrace] [./source/server/backtrace.h:96] #5: std::_Sp_counted_base<>::_M_release() [0x1caf533]
[2022-06-23 17:58:18.768][146][critical][backtrace] [./source/server/backtrace.h:96] #6: std::__shared_count<>::~__shared_count() [0x1caf4ea]
[2022-06-23 17:58:18.804][146][critical][backtrace] [./source/server/backtrace.h:96] #7: std::__shared_ptr<>::~__shared_ptr() [0x1d76d19]
[2022-06-23 17:58:18.842][146][critical][backtrace] [./source/server/backtrace.h:96] #8: std::shared_ptr<>::~shared_ptr() [0x1d755c5]
[2022-06-23 17:58:18.878][146][critical][backtrace] [./source/server/backtrace.h:96] #9: Envoy::Extensions::HttpFilters::FileSystemBuffer::FileSystemBufferFilter::maybeStorage()::$_3::operator()()::{lambda()#2}::~operator() [0x1d72549]
[2022-06-23 17:58:18.913][146][critical][backtrace] [./source/server/backtrace.h:96] #10: std::_Function_base::_Base_manager<>::_M_destroy() [0x1d72e7f]
[2022-06-23 17:58:18.950][146][critical][backtrace] [./source/server/backtrace.h:96] #11: std::_Function_base::_Base_manager<>::_M_manager() [0x1d72c6d]
[2022-06-23 17:58:18.986][146][critical][backtrace] [./source/server/backtrace.h:96] #12: std::_Function_base::~_Function_base() [0x1cc31c1]
[2022-06-23 17:58:19.038][146][critical][backtrace] [./source/server/backtrace.h:96] #13: std::function<>::~function() [0x1d75825]
[2022-06-23 17:58:19.083][146][critical][backtrace] [./source/server/backtrace.h:96] #14: Envoy::Extensions::HttpFilters::FileSystemBuffer::FileSystemBufferFilter::getSafeDispatch()::$_6::operator()()::{lambda()#1}::~operator() [0x1d73e1d]
[2022-06-23 17:58:19.120][146][critical][backtrace] [./source/server/backtrace.h:96] #15: std::_Function_base::_Base_manager<>::_M_destroy() [0x1d7419f]
[2022-06-23 17:58:19.156][146][critical][backtrace] [./source/server/backtrace.h:96] #16: std::_Function_base::_Base_manager<>::_M_manager() [0x1d73f5d]
[2022-06-23 17:58:19.156][146][critical][backtrace] [./source/server/backtrace.h:96] #17: std::_Function_base::~_Function_base() [0x1cc31c1]
[2022-06-23 17:58:19.156][146][critical][backtrace] [./source/server/backtrace.h:96] #18: std::function<>::~function() [0x1d75825]
[2022-06-23 17:58:19.192][146][critical][backtrace] [./source/server/backtrace.h:96] #19: __gnu_cxx::new_allocator<>::destroy<>() [0x1da3b89]
[2022-06-23 17:58:19.228][146][critical][backtrace] [./source/server/backtrace.h:96] #20: std::allocator_traits<>::destroy<>() [0x1da3b0d]
[2022-06-23 17:58:19.264][146][critical][backtrace] [./source/server/backtrace.h:96] #21: std::__cxx11::list<>::_M_erase() [0x28973ca]
[2022-06-23 17:58:19.301][146][critical][backtrace] [./source/server/backtrace.h:96] #22: std::__cxx11::list<>::pop_front() [0x3873a8a]
[2022-06-23 17:58:19.337][146][critical][backtrace] [./source/server/backtrace.h:96] #23: Envoy::Event::DispatcherImpl::runPostCallbacks() [0x410d1bd]
[2022-06-23 17:58:19.374][146][critical][backtrace] [./source/server/backtrace.h:96] #24: Envoy::Event::DispatcherImpl::DispatcherImpl()::$_3::operator()() [0x4111a08]
[2022-06-23 17:58:19.412][146][critical][backtrace] [./source/server/backtrace.h:96] #25: std::_Function_handler<>::_M_invoke() [0x41118cd]
[2022-06-23 17:58:19.448][146][critical][backtrace] [./source/server/backtrace.h:96] #26: std::function<>::operator()() [0x1d750c5]
[2022-06-23 17:58:19.481][146][critical][backtrace] [./source/server/backtrace.h:96] #27: Envoy::Event::SchedulableCallbackImpl::SchedulableCallbackImpl()::$_0::operator()() [0x4375752]
[2022-06-23 17:58:19.519][146][critical][backtrace] [./source/server/backtrace.h:96] #28: Envoy::Event::SchedulableCallbackImpl::SchedulableCallbackImpl()::$_0::__invoke() [0x4375719]
[2022-06-23 17:58:19.554][146][critical][backtrace] [./source/server/backtrace.h:96] #29: event_process_active_single_queue [0x47bbffc]
[2022-06-23 17:58:19.591][146][critical][backtrace] [./source/server/backtrace.h:96] #30: event_process_active [0x47b6858]
[2022-06-23 17:58:19.624][146][critical][backtrace] [./source/server/backtrace.h:96] #31: event_base_loop [0x47b575c]
[2022-06-23 17:58:19.661][146][critical][backtrace] [./source/server/backtrace.h:96] #32: Envoy::Event::LibeventScheduler::run() [0x4372b4f]
[2022-06-23 17:58:19.695][146][critical][backtrace] [./source/server/backtrace.h:96] #33: Envoy::Event::DispatcherImpl::run() [0x410cbec]
[2022-06-23 17:58:19.731][146][critical][backtrace] [./source/server/backtrace.h:96] #34: Envoy::Server::WorkerImpl::threadRoutine() [0x28ba518]
[2022-06-23 17:58:19.767][146][critical][backtrace] [./source/server/backtrace.h:96] #35: Envoy::Server::WorkerImpl::start()::$_6::operator()() [0x28bc310]
[2022-06-23 17:58:19.809][146][critical][backtrace] [./source/server/backtrace.h:96] #36: std::_Function_handler<>::_M_invoke() [0x28bc13d]
[2022-06-23 17:58:19.809][146][critical][backtrace] [./source/server/backtrace.h:96] #37: std::function<>::operator()() [0x1d750c5]
[2022-06-23 17:58:19.844][146][critical][backtrace] [./source/server/backtrace.h:96] #38: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::operator()() [0x479647d]
[2022-06-23 17:58:19.881][146][critical][backtrace] [./source/server/backtrace.h:96] #39: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::__invoke() [0x4796455]
[2022-06-23 17:58:19.881][146][critical][backtrace] [./source/server/backtrace.h:96] #40: start_thread [0x7fcbd08e66db]
================================================================================
```

### PR DESCRIPTION
**Pull request by ravenblackx**
Commit Message: Fix race in file_system_buffer filter (destroy filter vs open file)
Additional Description: If a filter is destroyed while asynchronously opening a file (too late to cancel but before the callback) it did not close the file, leading to an assertion in debug builds (file handle destroyed but not closed) or an open file descriptor leak in other builds. This change makes the callback close the file if the filter was destroyed. Fixes #21856.
Risk Level: Very Low (experimental filter, change only fixes unintentional behavior)
Testing: Test that was about 3% flaky passed with runs_per_test=200.
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a

### CODE REVIEW

File: source/extensions/filters/http/file_system_buffer/filter.cc [hunk 1]
```diff
@@ -389,22 +389,30 @@ bool FileSystemBufferFilter::maybeStorage(BufferedStreamState& state,
...
+          config_->storageBufferPath(), [this, me = std::weak_ptr(shared_from_this()),
+                                         dispatcher = &request_callbacks_->dispatcher(),
+                                         &state](absl::StatusOr<AsyncFileHandle> file_handle) {
+            dispatcher->post([this, me = std::move(me), &state, file_handle]() {
+              if (!me.lock()) {
+                // If we opened a file but the filter went away in the meantime, close the file
+                // to avoid leaving a dangling file handle.
+                if (file_handle.ok()) {
+                  file_handle.value()->close([](absl::Status) {}).IgnoreError();
+                }
```
Comment (mattklein123) [inline source/extensions/filters/http/file_system_buffer/filter.cc:407]: Quick question: Is there a reason we can't just use RAII to make sure that a file handle is closed if we end up destroying it without explicitly calling closed?

This seems like a safer way to make sure we don't have any fd leaks?  wdyt?

/wait-any

Comment (ravenblackx) [reply source/extensions/filters/http/file_system_buffer/filter.cc:407]: Doing it that way would make it get closed in the envoy thread that we're trying not to block. I don't know if close can cause a long block, but open certainly can, so I wouldn't bet on 'no'.

Comment (ravenblackx) [reply source/extensions/filters/http/file_system_buffer/filter.cc:407]: (Or, if you mean using RAII of the filter to call this close function, that doesn't work because the filter is destroyed before it knows whether it has a file handle.)

Comment (mattklein123) [reply source/extensions/filters/http/file_system_buffer/filter.cc:407]: OK sounds good, thanks.

**Review by mattklein123 — APPROVED** [review]
Thanks!
