### PR TITLE
mobile: Re-enable -Xcheck:jni

### LINKED ISSUE #28981: mobile: //test/kotlin/integration:filter_throwing_exception_test produces lots of warnings
When running //test/kotlin/integration:filter_throwing_exception_test there are 11,000 warnings like:

```
WARNING in native method: JNI call made without checking exceptions when required to from CallObjectMethodV
```

which show up in the logs. We need to clean up the exception handling we're doing and remove these exceptions.

### PR DESCRIPTION
**Pull request by fredyw**
This PR fixes #28981 by creating wrappers for JNI's `Call<Type>Method` and `CallStatic<Type>Method` that will check on the exception that might be thrown to satisfy `-Xcheck:jni` and updating the code to use the wrappers.

Risk Level: low
Testing: unit test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: mobile

### CODE REVIEW

File: mobile/library/common/jni/jni_utility.cc [hunk 1]
```diff
@@ -384,3 +384,55 @@ std::vector<MatcherData> javaObjectArrayToMatcherData(JNIEnv* env, jobjectArray
   }
   return ret;
 }
+
+#define DEFINE_CALL_METHOD(JAVA_TYPE, JNI_TYPE)                                                    \
+  JNI_TYPE call##JAVA_TYPE##Method(JNIEnv* env, jobject object, jmethodID method_id, ...) {        \
+    va_list args;                                                                                  \
+    va_start(args, method_id);                                                                     \
+    JNI_TYPE result = env->Call##JAVA_TYPE##MethodV(object, method_id, args);                      \
```
Comment (abeyad) [inline mobile/library/common/jni/jni_utility.cc:392]: curious about this and below, why the `V` at the end of the method?  could this code be changed to `env->Call##JAVA_TYPE##Method(...)` without the args initialization?

**Review by abeyad — COMMENTED** [review]
Thanks for fixing this!

**Comment by abeyad** [comment]
FYI, you can add "Fixes #{issue_num}" in your PR description and it will auto close the open issue.

**Comment by fredyw** [comment]
> FYI, you can add "Fixes #{issue_num}" in your PR description and it will auto close the open issue.

Yup, I already have that in the PR description. From the GitHub PR page:

`Successfully merging this pull request may close these issues.`
