### PR TITLE
init: replace old init manager with with new "safe" init manager

### LINKED ISSUE #6116: use-after-free in Init::Manager
We've discovered a reproducible use-after-free in `InitManagerImpl`. The general pattern is:

1. A `Target` registers itself with an `InitManagerImpl`.
2. `InitManagerImpl::initialize()` is called, which invokes `Target::initialize()` on the target. It passes a callback argument, a lambda that captures (but does not own) `InitManagerImpl`. The target, in this case, stores the callback and begins initializing asynchronously.
3. The `InitManagerImpl` is freed from the heap.
4. Finally, the `Target`s finishes initializing and invokes its callback, which attempts to use the freed `InitManagerImpl` previously captured.

The specific case where we are hitting this is essentially a race between LDS and RDS. I'll try to describe this at both the xDS level, and the code level (in terms of the steps above).

* Start from a state where `ListenerManagerImpl` has all its workers started, so any `ListenerImpl` created will use its own `dynamic_init_manager_` rather than the global one (see `ListenerImpl::initManager`).
* LDS receives a listener, which references some route configuration that hasn't been defined yet, so RDS requests that route configuration.
    * A `ListenerImpl` is created for the listener, which owns an `InitManagerImpl`.
    * A `RdsRouteConfigSubscription` is created, and registers itself as a target with the above `InitManagerImpl` (step 1 above).
    * The `ListenerImpl` is initialized, which calls initialize on the `RdsRouteConfigSubscription`. The callback is stored while we wait for the RDS response (step 2 above).
* LDS then receives a new version of the same listener, overwriting the old version.
    * The original `ListenerImpl` is destroyed, which destroys the `InitManagerImpl` it owns (step 3 above).
* Finally, RDS receives the response for the route configuration it had previously requested.
    * The `RdsRouteConfigSubscription` invokes its callback, referencing the now deleted `InitManagerImpl` (step 4 above).

The relevant bits from the actual stack trace:
```
#0: Envoy::SignalAction::sigHandler() [0x1b6fd0c] source/exe/signal_action.cc:17
#1: __restore_rt [0x7fa1b0d540c0] ??:0
#2: std::__cxx11::list<>::remove() [0x126d1a4] /usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/8.0.1/bits/list.tcc:335
#3: Envoy::Server::InitManagerImpl::initializeTarget()::$_0::operator()() [0x126c61b] source/server/init_manager_impl.cc:45
#4: std::_Function_handler<>::_M_invoke() [0x126c29d] /usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/8.0.1/bits/std_function.h:299
#5: std::function<>::operator()() [0x4f645e] /usr/lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/8.0.1/bits/std_function.h:687
#6: Envoy::Router::RdsRouteConfigSubscription::runInitializeCallbackIfAny() [0xa4ded0] source/common/router/rds_impl.cc:138
#7: Envoy::Router::RdsRouteConfigSubscription::onConfigUpdate() [0xa4e48b] source/common/router/rds_impl.cc:?
#8: Envoy::Config::GrpcMuxSubscriptionImpl<>::onConfigUpdate() [0xa59929] bazel-out/k8-dbg/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:55
#9: Envoy::Config::GrpcMuxImpl::handleResponse() [0x11697f4] source/common/config/grpc_mux_impl.cc:171
#10: Envoy::Config::GrpcStream<>::onReceiveMessage() [0x116b3de] bazel-out/k8-dbg/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:82
#11: Envoy::Grpc::TypedAsyncStreamCallbacks<>::onReceiveMessageUntyped() [0x116b2a9] bazel-out/k8-dbg/bin/include/envoy/grpc/_virtual_includes/async_client_interface/envoy/grpc/async_client.h:172
#12: Envoy::Grpc::AsyncStreamImpl::onData() [0xd96c8d] source/common/grpc/async_client_impl.cc:142
#13: Envoy::Http::AsyncStreamImpl::encodeData() [0xd9bd35] source/common/http/async_client_impl.cc:105
#14: Envoy::Router::Filter::onUpstreamData() [0x119a13b] source/common/router/router.cc:770
#15: Envoy::Router::Filter::UpstreamRequest::decodeData() [0x119bc67] source/common/router/router.cc:985
#16: Envoy::Http::StreamDecoderWrapper::decodeData() [0x8c65ec] bazel-out/k8-dbg/bin/source/common/http/_virtual_includes/codec_wrappers_lib/common/http/codec_wrappers.h:37
#17: Envoy::Http::Http2::ConnectionImpl::onFrameReceived() [0x12a305b] source/common/http/http2/codec_impl.cc:503
#18: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_9::operator()() [0x12a7aa8] source/common/http/http2/codec_impl.cc:808
#19: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_9::__invoke() [0x12a7a75] source/common/http/http2/codec_impl.cc:807
```

Decoding that a bit:
* Frames 8 through 6: RDS receives update...
* Frames 5 through 3: RDS calls its stored callback...
* Frame 2: The callback attempts to remove the RdsRouteConfigSubscription from its list of init targets...
* Frames 1 and 0: Oh noes, that list of init targets was previously freed.

### PR DESCRIPTION
**Pull request by mergeconflict**
Description: Replace the old init manager with the new "safe" init manager and update all use sites.
Risk Level: Low
Testing: All tests pass, including a new integration test to cover the specific crash observed in #6116.
Docs Changes: n/a
Release Notes: n/a
Fixes #6116

Signed-off-by: Dan Rosen <mergeconflict@google.com>

### CODE REVIEW

**Comment by mergeconflict** [comment]
/review @htuch @mattklein123 @lizan 

This is a mostly mechanical, uninteresting set of changes. I've deleted the old `Init`, renamed `SafeInit` back to `Init`, and updated everything to use the new stuff. The only somewhat interesting change is the new ADS integration test.

File: test/server/server_test.cc [hunk 1]
```diff
@@ -92,27 +91,30 @@ class RunHelperTest : public testing::Test {
...
-  EXPECT_CALL(start_workers_, ready()).Times(0);
-  Init::MockTarget target;
-  init_manager_.registerTarget(target, "");
-  EXPECT_CALL(target, initialize(_));
-  cm_init_callback_();
-  sigterm_->callback_();
-  EXPECT_CALL(server_, isShutdown()).WillOnce(Return(shutdown_));
-  target.callback_();
-}
+// TODO(mergeconflict): this test isn't valid anymore, since the "if (!shutdown) startWorkers()"
```
Comment (mattklein123) [inline test/server/server_test.cc]: Let's either fix this now or open an issue and assign to yourself for follow up, prefer not to leave commented out code.

File: source/common/upstream/upstream_impl.h [hunk 2]
```diff
@@ -673,8 +672,9 @@ class ClusterImplBase : public Cluster, protected Logger::Loggable<Logger::Id::u
    */
   void onInitDone();
 
+  Init::ManagerImpl init_manager_;
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.h]: From a quick skim it's a little confusing when we have a manager and a watcher. We have this pattern in a few places. Can you potentially add comments in similar cases on what the manager is managing and what the watcher is watching?

File: source/server/listener_manager_impl.cc [hunk 3]
```diff
@@ -168,6 +168,12 @@ ListenerImpl::ListenerImpl(const envoy::api::v2::Listener& config, const std::st
       listener_tag_(parent_.factory_.nextListenerTag()), name_(name), modifiable_(modifiable),
       workers_started_(workers_started), hash_(hash),
       dynamic_init_manager_(fmt::format("Listener {}", name)),
+      init_watcher_("ListenerImpl",
+                    [this]() -> void {
+                      if (!initialize_canceled_) {
```
[the remark this answers is not in the document]
Comment (mergeconflict) [reply source/server/listener_manager_impl.cc]: That's a good question. There's a comment in `ListenerImpl`'s dtor that makes me think it's still necessary:
```c++
// The filter factories may have pending initialize actions (like in the case of RDS). Those
// actions will fire in the destructor to avoid blocking initial server startup. If we are using
// a local init manager we should block the notification from trying to move us from warming to
// active.
```
I don't know enough about this code, but it looks like the `listener_filter_factories_` might contain some initialization targets (notably `RdsRouteConfigSubscription`s) that will signal `ready` on destruction, causing the listener to notify its parent even though it'll be destroyed immediately after.

File: test/server/server_test.cc (hunk 1 above)
Comment (mergeconflict) [reply test/server/server_test.cc]: Yeah, definitely agree. I just need to figure out how I want to fix this...

File: source/common/upstream/upstream_impl.h (hunk 2 above)
Comment (mergeconflict) [reply source/common/upstream/upstream_impl.h]: Sure, good idea.

File: source/server/listener_manager_impl.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (mattklein123) [reply source/server/listener_manager_impl.cc]: One thing you could potentially do to avoid the extra variable is to allocate `init_watcher_` on the heap, and then explicitly `reset()` it in the destructor. This I think would have the effect of dropping any future completions. WDYT? Not a big deal either way but seems a better use of the new design.

File: source/common/config/config_provider_impl.h [hunk 4]
```diff
@@ -200,20 +194,17 @@ class ConfigSubscriptionInstanceBase : public Init::Target,
...
 
   void setLastUpdated() { last_updated_ = time_source_.systemTime(); }
 
-  void runInitializeCallbackIfAny();
-
 private:
-  void registerInitTarget(Init::Manager& init_manager) {
-    init_manager.registerTarget(*this, fmt::format("ConfigSubscriptionInstanceBase {}", name_));
-  }
+  void registerInitTarget(Init::Manager& init_manager) { init_manager.add(init_target_); }
```
Comment (htuch) [inline source/common/config/config_provider_impl.h]: In terms of naming, this is a bit of a weird inversion. Should we just make the init target available to the caller in `getSubscription()` and inline this there?

File: source/common/secret/sds_api.cc [hunk 5]
```diff
@@ -17,27 +17,25 @@ SdsApi::SdsApi(const LocalInfo::LocalInfo& local_info, Event::Dispatcher& dispat
                const envoy::api::v2::core::ConfigSource& sds_config,
                const std::string& sds_config_name, std::function<void()> destructor_cb,
                Api::Api& api)
-    : local_info_(local_info), dispatcher_(dispatcher), random_(random), stats_(stats),
+    : init_target_(
+          fmt::format("SdsApi {}", sds_config_name),
+          [this]() {
```
Comment (htuch) [inline source/common/secret/sds_api.cc]: Prefer maybe to make this a private method or anonymous namespace and reference it rather than inline; otherwise this C++ starts to look like Javascript..

File: test/integration/ads_integration_test.cc [hunk 6]
```diff
@@ -675,6 +675,85 @@ TEST_P(AdsIntegrationTest, RdsAfterLdsWithRdsChange) {
   makeSingleRequest();
 }
 
+// Regression test for the use-after-free crash when a listener awaiting an RDS update is destroyed
```
Comment (htuch) [inline test/integration/ads_integration_test.cc]: Can you move this to another PR? I think it doesn't logically belong with this. Ideally, the changes in this PR are all mechanical.

**Comment by mergeconflict** [comment]
cc @htuch

File: test/integration/ads_integration_test.cc (hunk 6 above)
Comment (mergeconflict) [reply test/integration/ads_integration_test.cc]: I could, and you're right, these are mostly mechanical changes ... but I want to try to push back a little. The fix for #6116 is in this PR, and I feel like it's a little weird for the regression test to land separately.

File: source/common/secret/sds_api.h [hunk 7]
```diff
@@ -55,6 +55,7 @@ class SdsApi : public Config::SubscriptionCallbacks<envoy::api::v2::auth::Secret
   Common::CallbackManager<> update_callback_manager_;
 
 private:
+  void initialize();
```
Comment (mattklein123) [inline source/common/secret/sds_api.h]: nit: newline between methods and members.
