### PR TITLE
tls: moving the server name into SocketAddressProvider

### LINKED ISSUE #14922: Listener access logs missing %REQUESTED_SERVER_NAME% when no filter chain matches
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
When I send a request that matches a filter chain, I see access logs:
`{"requested_server_name":"hello.example.com", ...}`

However, if I send a request that does *not* match any filter chains:
`{"requested_server_name":null,...}`

*Repro steps*:
Access log config, at the listener level:
```json
       "access_log": [
        {
         "name": "envoy.access_loggers.file",
         "filter": {
          "response_flag_filter": {
           "flags": [
            "NR"
           ]
          }
         },
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
          "path": "/dev/stdout",
          "log_format": {
           "json_format": {
            "authority": "%REQ(:AUTHORITY)%",
            "bytes_received": "%BYTES_RECEIVED%",
            "bytes_sent": "%BYTES_SENT%",
            "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
            "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
            "duration": "%DURATION%",
            "method": "%REQ(:METHOD)%",
            "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
            "protocol": "%PROTOCOL%",
            "request_id": "%REQ(X-REQUEST-ID)%",
            "requested_server_name": "%REQUESTED_SERVER_NAME%",
            "response_code": "%RESPONSE_CODE%",
            "response_flags": "%RESPONSE_FLAGS%",
            "route_name": "%ROUTE_NAME%",
            "start_time": "%START_TIME%",
            "upstream_cluster": "%UPSTREAM_CLUSTER%",
            "upstream_host": "%UPSTREAM_HOST%",
            "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
            "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
            "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
            "user_agent": "%REQ(USER-AGENT)%",
            "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%"
           }
          }
         }
        }
       ]
      },
```

My expectation is that the REQUESTED_SERVER_NAME field would be populated here. Given tls_inspector runs before we do filter chain matching, I would expect this information is available?

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: tls: moving the server name into SocketAddressProvider

Additional Description:
Making the SocketAddressProvider is single source of server name.

Risk Level: low
Testing: n/a
Part of  #17168
Fixes #14922

Signed-off-by: He Jie Xu <hejie.xu@intel.com>

### CODE REVIEW

File: source/server/active_tcp_listener.cc [hunk 1]
```diff
@@ -123,6 +123,9 @@ void ActiveTcpSocket::unlink() {
   }
   // Emit logs if a connection is not established.
   if (!connected_) {
+    // Only HCM and tcp proxy filter will populate the server name into stream info.
+    // So the stream info will have no server name at this point.
+    stream_info_->setRequestedServerName(socket_->requestedServerName());
```
Comment (snowp) [inline source/server/active_tcp_listener.cc:128]: Instead of having this fallback in case a L4 filter sets this, would it be possible to consolidate where we set this so that filters don't need to be concerned with it? Can we set this somewhere in the TLS stack perhaps? 

cc @lizan @ggreenway

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks for working on a fix here! High level question on the approach

File: source/server/active_tcp_listener.cc (hunk 1 above)
Comment (ggreenway) [reply source/server/active_tcp_listener.cc:128]: I agree; this should be set in a common location, earlier in the process. I think the value is only initially sourced by the tls_inspector, so this could be set in `ActiveTcpListener::newConnection` or somewhere nearby, in `source/server/active_tcp_listener.cc`.

Comment (ggreenway) [reply source/server/active_tcp_listener.cc:128]: tls_inspector sets it on the socket, but listener filters don't have access to the streamInfo, so something has to move it from the socket to the streamIfno. I think `newConnection()`, before bailing out for no-filter-chain-found, is possibly the right place.

Comment (soulxu) [reply source/server/active_tcp_listener.cc:128]: thanks for the review!

the ActiveTCPSocket own the stream info and passed into listener filter. unfortunately, there is no interface to access that, except we extend the interface https://github.com/envoyproxy/envoy/blob/main/include/envoy/network/filter.h#L264

I also aware @lambdai 's comment https://github.com/envoyproxy/envoy/issues/14922#issuecomment-773606556, it sounds like the SNI may be sniffed by transport socket, but I didn't find it. Maybe have him help to ensure that.

Otherwise, newConnection() sounds like right place.

File: source/server/active_tcp_listener.cc [hunk 2]
```diff
@@ -284,6 +284,10 @@ void ActiveTcpListener::resumeListening() {
 
 void ActiveTcpListener::newConnection(Network::ConnectionSocketPtr&& socket,
                                       std::unique_ptr<StreamInfo::StreamInfo> stream_info) {
+  // populate the SNI into stream info, the network filters needn't do that again.
```
Comment (snowp) [inline source/server/active_tcp_listener.cc:287]: Maybe something like `// Set the SNI as early as possible, this ensures that it gets set even if we end up not instantiating any network filters.`?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks this seems like a better direction to me, a few comments.

@ggreenway do you also want to review this?

File: source/common/http/conn_manager_impl.cc [hunk 3]
```diff
@@ -662,9 +662,6 @@ ConnectionManagerImpl::ActiveStream::ActiveStream(ConnectionManagerImpl& connect
     max_stream_duration_timer_->enableTimer(connection_manager_.config_.maxStreamDuration().value(),
                                             this);
   }
-
-  filter_manager_.streamInfo().setRequestedServerName(
```
Comment (ggreenway) [inline source/common/http/conn_manager_impl.cc:666]: I thought this was being done per http request. I'm not sure this one can be removed. But OTOH, all the tests passed. @mattklein123 is this really not needed, or are we just lacking test coverage somewhere?

File: source/server/active_tcp_listener.cc [hunk 4]
```diff
@@ -284,6 +284,10 @@ void ActiveTcpListener::resumeListening() {
...
+  if (!socket->requestedServerName().empty()) {
```
Comment (ggreenway) [inline source/server/active_tcp_listener.cc:288]: Can this be done unconditionally? I would expect that calling `setRequestedServerName()` with an empty string would have no effect.

**Review by ggreenway — COMMENTED** [review]
This is looking good; I like this approach better.

File: test/server/active_tcp_listener_test.cc [hunk 5]
```diff
@@ -61,6 +61,35 @@ class ActiveTcpListenerTest : public testing::Test, protected Logger::Loggable<L
...
+  auto active_listener1 =
+      std::make_unique<ActiveTcpListener>(conn_handler_, std::move(listener), listener_config_);
+
+  Network::MockConnectionSocket* accepted_socket1 = new NiceMock<Network::MockConnectionSocket>();
+  EXPECT_CALL(*accepted_socket1, requestedServerName()).WillRepeatedly(Return("envoy.io"));
+
+  EXPECT_CALL(manager_, findFilterChain(_)).WillRepeatedly(Return(nullptr));
+
+  std::unique_ptr<StreamInfo::StreamInfoImpl> stream_info(
+      new StreamInfo::StreamInfoImpl(dispatcher_.timeSource(), nullptr));
```
[the remark this answers is not in the document]
Comment (soulxu) [reply test/server/active_tcp_listener_test.cc:88]: got it, thanks

File: source/server/active_tcp_listener.cc (hunk 2 above)
Comment (soulxu) [reply source/server/active_tcp_listener.cc:287]: got it

File: source/server/active_tcp_listener.cc (hunk 4 above)
Comment (soulxu) [reply source/server/active_tcp_listener.cc:288]: It has a constructor even for empty string https://github.com/envoyproxy/envoy/blob/main/source/common/stream_info/stream_info_impl.h#L237. Or we can move the check inside the `setRequestedServerName()`, but that will block the case when want to set the server name back to empty. Although I'm not sure we have any case to set the server name back to empty, but it still feels bad for an interface.

File: source/server/active_tcp_listener.cc (hunk 1 above)
Comment (lambdai) [reply source/server/active_tcp_listener.cc]: Thank you @soulxu 

I do agree set in newConnection() beats late set in TcpProxy and HCM.
But it's also nice to have it here as well: the newConnection is not always invoked on listening timeout. #14922 describes the scenario and the requirement.


SNI is not sniffed by transport sockets but the tls_inspector: https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/listener/tls_inspector/tls_inspector.cc#L144

That's what lizan mentions. Although we cannot set the requestservername there because the stream_info is not yet created at that moment

Comment (soulxu) [reply source/server/active_tcp_listener.cc]: > I do agree set in newConnection() beats late set in TcpProxy and HCM.
> But it's also nice to have it here as well: the newConnection is not always invoked on listening timeout. #14922 describes the scenario and the requirement.

I can add it back, thanks for the replay.

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc:666]: Yes I think this is likely a bug in the same class of issues I fixed a while back with addresses. Optimally, we would do something similar here so we don't mess this up.

Comment (ggreenway) [reply source/common/http/conn_manager_impl.cc:666]: I'm 99% sure that deleting this line will break things, but apparently we don't have any test coverage of this. I think this line needs to be reverted.

File: source/server/active_tcp_listener.cc (hunk 4 above)
Comment (ggreenway) [reply source/server/active_tcp_listener.cc:293]: I think it is functionally the same without this check; setting it to empty is the same as not setting it. Please remove the conditional to simplify the code. Same in `unlink()`.

File: test/server/active_tcp_listener_test.cc [hunk 6]
```diff
@@ -61,6 +61,34 @@ class ActiveTcpListenerTest : public testing::Test, protected Logger::Loggable<L
...
+  EXPECT_CALL(listener_config_, filterChainManager()).WillRepeatedly(ReturnRef(manager_));
+  EXPECT_CALL(listener_config_, openConnections()).WillRepeatedly(ReturnRef(resource_limit_));
+
+  auto active_listener1 =
+      std::make_unique<ActiveTcpListener>(conn_handler_, std::move(listener), listener_config_);
+
+  auto accepted_socket1 = std::make_unique<NiceMock<Network::MockConnectionSocket>>();
+  EXPECT_CALL(*accepted_socket1, requestedServerName()).WillRepeatedly(Return("envoy.io"));
+
+  EXPECT_CALL(manager_, findFilterChain(_)).WillRepeatedly(Return(nullptr));
```
Comment (ggreenway) [inline test/server/active_tcp_listener_test.cc:85]: I think this can be `WillOnce` instead of `WillRepeatedly`

File: test/server/active_tcp_listener_test.cc [hunk 7]
```diff
@@ -61,6 +61,34 @@ class ActiveTcpListenerTest : public testing::Test, protected Logger::Loggable<L
...
+
+  auto stream_info =
```
Comment (ggreenway) [inline test/server/active_tcp_listener_test.cc:87]: Use a `MockStreamInfo`, and add `EXPECT_CALL(stream_info, setRequestedServerName("envoy.io"))` (or similar).

**Review by ggreenway — CHANGES_REQUESTED** [review]
Please add another test case for listener filter timeout that verifies the server name is set.

/wait

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (soulxu) [reply source/common/http/conn_manager_impl.cc:666]: Yes, I dig into it. Then I realized this isn't the same streamInfo with the L4 layer one. This streamInfo is an instance inside ActiveStream, although part of its info is coming from the L4 layer(include this server name). So I shouldn't remove it.

I also added unitest to cover this case https://github.com/envoyproxy/envoy/pull/16797

File: source/server/active_tcp_listener.cc (hunk 4 above)
Comment (soulxu) [reply source/server/active_tcp_listener.cc:293]: got it, let me remove it.

File: test/server/active_tcp_listener_test.cc (hunk 6 above)
Comment (soulxu) [reply test/server/active_tcp_listener_test.cc:85]: yes, let me fix it

File: test/server/active_tcp_listener_test.cc (hunk 7 above)
Comment (soulxu) [reply test/server/active_tcp_listener_test.cc:87]: got it.

**Comment by soulxu** [comment]
thanks for the review, I will update soon!

**Comment by ggreenway** [comment]
> Yes I think this is likely a bug in the same class of issues I fixed a while back with addresses. Optimally, we would do something similar here so we don't mess this up.

I didn't realize until now how similar it is. There's an accessor for the requestedServerName on the Connection, which I didn't realize. Maybe we can just delete that entirely, and say that the way to get it is always from the streamInfo, and make sure it's always populated on the streamInfo. Then it becomes a simpler problem than the addresses. It's only used in about ~10 places off of the Connection. Thoughts @mattklein123 ?

**Comment by mattklein123** [comment]
> I didn't realize until now how similar it is. There's an accessor for the requestedServerName on the Connection, which I didn't realize. Maybe we can just delete that entirely, and say that the way to get it is always from the streamInfo, and make sure it's always populated on the streamInfo. Then it becomes a simpler problem than the addresses. It's only used in about ~10 places off of the Connection. Thoughts @mattklein123 ?

I think this would be fine, but keep in mind that there are unfortunately multiple stacked stream infos (connection, stream, etc.) so we need to make sure to not actually break copying the data over.

Another option would be just adding this to `SocketAddressProvider` (and maybe renaming it) which is how I fixed all the address bugs. Basically I made it impossible to not have this data be carried everywhere.

**Comment by soulxu** [comment]
> > I didn't realize until now how similar it is. There's an accessor for the requestedServerName on the Connection, which I didn't realize. Maybe we can just delete that entirely, and say that the way to get it is always from the streamInfo, and make sure it's always populated on the streamInfo. Then it becomes a simpler problem than the addresses. It's only used in about ~10 places off of the Connection. Thoughts @mattklein123 ?
> 
> I think this would be fine, but keep in mind that there are unfortunately multiple stacked stream infos (connection, stream, etc.) so we need to make sure to not actually break copying the data over.
> 
> Another option would be just adding this to `SocketAddressProvider` (and maybe renaming it) which is how I fixed all the address bugs. Basically I made it impossible to not have this data be carried everywhere.

Hope I understand correctly. I search the socket address issue https://github.com/envoyproxy/envoy/issues/14133, so the goal here is not to carry the info anywhere, avoid the bug we always forget to populate the info somewhere, just share the same info from the connection.  So we can put the server_name into the socket address provider(need to rename it). Is it correct? @mattklein123 

If it is correct, I found other than the 'server name', we also can put the 'downstream ssl info' https://github.com/envoyproxy/envoy/blob/233546f9e6cef00df4ec7d0bde58bfec7b1f0397/source/common/http/conn_manager_impl.cc#L651 and 'connection id' 
https://github.com/envoyproxy/envoy/blob/233546f9e6cef00df4ec7d0bde58bfec7b1f0397/source/common/http/conn_manager_impl.cc#L654
into the socket address provider. Those are used for l4 stream info and http stream info and also populated from the connection. 

Also, @ggreenway mentioned, we should clean up the way to get the stream info, it should be always from the stream info. for example: 
https://github.com/envoyproxy/envoy/blob/233546f9e6cef00df4ec7d0bde58bfec7b1f0397/source/extensions/filters/http/rbac/rbac_filter.cc#L49

let me know whether this is the direction you guys looking for, I'm happy to work on it :)

**Comment by mattklein123** [comment]
Yeah in general ^ makes sense to me. In general if we can consolidate information that should never change into a single structure to avoid bugs in copying it around that would be optimal.

**Comment by soulxu** [comment]
@mattklein123 @ggreenway I'm going to separate the whole thing into different PR since I found the PR will become huge and hard to review, this PR is just moving the server_name inside SocketAddressProvider.  Then I will have other PRs for moving 'ssl info' and 'connection id'. Then a PR for ensure the server name only get from the address provider, the last PR will rename the SocketAddressProvider to proper name. But let me know if you have other perference.

**Comment by soulxu** [comment]
fyi, I create an issue to track the whole thing https://github.com/envoyproxy/envoy/issues/17168

**Comment by mattklein123** [comment]
Check CI?

/wait

File: envoy/network/socket.h [hunk 8]
```diff
@@ -73,6 +73,11 @@ class SocketAddressProvider {
    */
   virtual const Address::InstanceConstSharedPtr& directRemoteAddress() const PURE;
 
+  /**
```
Comment (mattklein123) [inline envoy/network/socket.h:76]: Just to leave an intermediate comment trail, can you add a TODO above here on what you plan to rename it to? Otherwise this will get confusing if someone looks at it now.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks this looks like a great improvement. One small comment.

/wait

File: envoy/network/socket.h (hunk 8 above)
Comment (soulxu) [reply envoy/network/socket.h:76]: yea, good point. let me add a TODO

**Review by mattklein123 — APPROVED** [review]
Thanks!
