### PR TITLE
upstream: fix maglev locality weighting

### LINKED ISSUE #5982: Locality weighting in Maglev inconsistent with other LBs
The way Maglev currently implements weighting for any given host and locality is: `effective_weight = host_weight * locality_weight`. This is nice and simple, but it's inconsistent with how the other LBs implement locality weighting. A simple example:

* Locality _A_: locality_weight = 1
     * contains 100 hosts, each with host_weight = 1
* Locality _B_: locality_weight = 1
    * contains 50 hosts, each with host_weight = 1

The way Maglev figures it, the effective weight for all hosts is 1: they all get equal traffic. But the way all other LBs figure it, and what users expect (per [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/locality_weight), assuming healthy hosts) is that _A_ should be getting the same traffic as _B_, no matter how many hosts happen to be in each locality: consequently, each of the 50 hosts in _B_ should be taking twice as much traffic as each of the 100 hosts in _A_.

Judging by https://github.com/envoyproxy/envoy/issues/2725#issuecomment-370586299, we meant to do this at some point, but didn't.

The correct math is to sum the locality weights, and sum the host weights within each locality, to get the right proportions. For example, given:

* Locality _A_: locality_weight = 2
    * Host _a_: host_weight = 3
    * Host _b_: host_weight = 5
* Locality _B_: locality_weight = 7
    * Host _c_: host_weight = 11
    * Host _d_: host_weight = 13

The sum of locality weights = 9, the sum of host weights in _A_ is 8, and the sum of host weights in _B_ is 24, which gives us effective weights:

* Host _a_: (2/9) * (3/8) ~= .083
* Host _b_: (2/9) * (5/8) ~= .139
* Host _c_: (7/9) * (11/24) ~= .356
* Host _d_: (7/9) * (13/24) ~= .421

### PR DESCRIPTION
**Pull request by mergeconflict**
*Description*: Make Maglev LB locality weighting work the same way as all other LBs. Fixes #5982.
*Risk Level*: Medium
*Testing*: Updated unit tests to reflect correct weights, updated load balancer benchmark and verified no regression.
*Docs Changes*: Documented the effect (and edge effects) of weighting, and new gauges.
*Release Notes*: n/a

Signed-off-by: Dan Rosen <mergeconflict@google.com>

### CODE REVIEW

File: test/common/upstream/maglev_lb_test.cc [hunk 1]
```diff
@@ -224,18 +224,18 @@ TEST_F(MaglevLoadBalancerTest, LocalityWeightedGlobalPanic) {
...
+  // maglev: i=12 host=127.0.0.1:90
   // maglev: i=13 host=127.0.0.1:90
   // maglev: i=14 host=127.0.0.1:91
   // maglev: i=15 host=127.0.0.1:90
   // maglev: i=16 host=127.0.0.1:91
   LoadBalancerPtr lb = lb_->factory()->create();
-  const std::vector<uint32_t> expected_assignments{1, 0, 0, 1, 0, 1, 1, 0, 1,
-                                                   1, 1, 1, 1, 0, 1, 0, 1};
+  const std::vector<uint32_t> expected_assignments{1, 0, 0, 1, 0, 1, 1, 0, 0,
+                                                   1, 0, 1, 0, 0, 1, 0, 1};
```
Comment (htuch) [inline test/common/upstream/maglev_lb_test.cc]: Thanks for this fix; I'll do a more significant review in a bit, but to get started, I think it would be good to add the extreme locality weighting test that we had for ring hash LB for Maglev as well, to ensure we see similar correct behavior.

Comment (mergeconflict) [reply test/common/upstream/maglev_lb_test.cc]: Done. The expected behavior is a bit different, but it's still a good test case.

File: test/common/upstream/maglev_lb_test.cc [hunk 2]
```diff
@@ -224,24 +224,60 @@ TEST_F(MaglevLoadBalancerTest, LocalityWeightedGlobalPanic) {
...
+    uint32_t port = lb->chooseHost(&context)->address()->ip()->port();
+    ++counts[port];
+  }
+
+  // Each of the light_but_dense hosts should appear in the table once.
+  for (uint32_t i = 1; i < 1024; ++i) {
+    EXPECT_EQ(1, counts[i]);
+  }
+
+  // The heavy_but_sparse host should occupy the remainder of the table.
```
Comment (htuch) [inline test/common/upstream/maglev_lb_test.cc]: Is it worth adding to the documentation some discussion on the effects of granularity as the number of light weighted hosts approaches the size of the Maglev table? Basically, you get some kind of dilation effect which is a bit unintuitive.

Comment (mergeconflict) [reply test/common/upstream/maglev_lb_test.cc]: Yeah, probably worth documenting. But it makes me wonder about two things:

* How will users know if they're experiencing this behavior?
* What can they do about it?

It seems like, if we really want to pursue that, I should probably add a couple gauges here, like I did in ring hash: `min_hashes_per_host` and `max_hashes_per_host`. And table size should be configurable (we'll pick the next prime number >= the parameter's value). Do you think this is worth doing?

Comment (htuch) [reply test/common/upstream/maglev_lb_test.cc]: Sure, these are good metrics!

Comment (htuch) [reply test/common/upstream/maglev_lb_test.cc]: I don't think it's worth making table size configurable in the context of this PR though, maybe just open an issue; when someone wants it, we can add :)

Comment (mergeconflict) [reply test/common/upstream/maglev_lb_test.cc]: Done!

**Comment by mergeconflict** [comment]
Some thoughts about follow-up work:
* Still need to implement the behavior described in the docs where unhealthy localities have their weights reduced. Planning to do that in a separate PR, because it will probably involve adding tests for both ring hash and Maglev lb.
* I think the gauges warrant a bit more bikeshedding. First, they're called "hashes-per-host" in ring hash and "entries-per-host" here, which probably should be unified. And second, we only store "min" and "max" — they could be more useful if we made them histograms (which should include p0 and p100).

File: docs/root/intro/arch_overview/load_balancing/load_balancers.rst [hunk 3]
```diff
@@ -93,6 +93,17 @@ any place in which consistent hashing is desired. Like the ring hash load balanc
 hashing load balancer is only effective when protocol routing is used that specifies a value to
 hash on.
 
+The table construction algorithm places each host on in the table some number of times proportional
```
Comment (htuch) [inline docs/root/intro/arch_overview/load_balancing/load_balancers.rst]: Nit: s/on in/in/

Comment (mergeconflict) [reply docs/root/intro/arch_overview/load_balancing/load_balancers.rst]: Oops, thanks!
