### PR TITLE
ssl: clarify exception when tls_certificates are missing

### LINKED ISSUE #4408: Incorrect TLS example in documentation
*Title*: *Incorrect TLS example in documentation*

*Description*:
There is an invalid `tls_context` block In [https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/ssl#example-configuration]()

```
      tls_context:
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /usr/local/my-client-ca.crt
```

When trying to use this example with envoy 1.7.1, error "A single TLS certificate is required for server contexts" occurs. To fix it, `tls_certificates` section should be added:

```
      tls_context:
        common_tls_context:
          tls_certificates:
            certificate_chain: { "filename": "/cert.crt" }
            private_key: { "filename": "/cert.key" }
          validation_context:
            trusted_ca:
              filename: /ca.crt
```

Also, error message "A single TLS certificate is required for server contexts" isn't informative in this case

### PR DESCRIPTION
**Pull request by cmluciano**
*Description*
tls_certificates are necessary else validation errors with
"A single TLS certificate is required for server contexts".

context_config_impl and relevant tests have also been updated
to clarify that tls_certificates is required in the server context.
The existing error is still output if more than one certificate is detected.

Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

*Risk Level*: Low, clarifying error message and docs fix
*Testing*: bazel test
*Docs Changes*: Included
* Fixes #4408

### CODE REVIEW

File: source/common/ssl/context_config_impl.cc [hunk 1]
```diff
@@ -189,7 +189,10 @@ ServerContextConfigImpl::ServerContextConfigImpl(
       }()) {
   // TODO(PiotrSikora): Support multiple TLS certificates.
   if ((config.common_tls_context().tls_certificates().size() +
-       config.common_tls_context().tls_certificate_sds_secret_configs().size()) != 1) {
+       config.common_tls_context().tls_certificate_sds_secret_configs().size()) == 0) {
+    throw EnvoyException("Missing tls_certificates specification for server context");
```
Comment (zuercher) [inline source/common/ssl/context_config_impl.cc]: Nit: Because the certificates can come from different sources, it might be better to just say "No TLS certificates found for server context"
