### PR TITLE
http: return per route config when direct response is set

### LINKED ISSUE #17377: Disabling LuaPerRoute  configuration doesn't work with envoy-v1.19.0
*Title*: *Disabling LuaPerRoute  configuration doesn't work with envoy-v1.19.0*

*Description*:
Lua filter is executed  for requests which match a route with Lua disabled using [LuaPerRoute](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/lua/v3/lua.proto#extensions-filters-http-lua-v3-luaperroute) configuration. We are seeing this only in the latest envoy version - v1.19.0.

*Repro steps*:

1. Using the example from envoy [doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples), add a lua filter before the `envoy.filters.http.router` filter.
```
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  request_handle:logInfo("Hello World.")
                end
                function envoy_on_response(response_handle)
                  response_handle:logInfo("Goodbye")
                end
```
2.  Create the following route in `envoy.filters.network.http_connection_manager` with lua filter disabled.

```
- match:
       prefix: "/healthcheck"
  direct_response:
       status: 200
  typed_per_filter_config:
     envoy.filters.http.lua:
        "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
         disabled: true
```

3. Start Envoy
```
docker run -it -v $(pwd):/etc -p 10000:10000 -e ENVOY_UID=0 envoyproxy/envoy:v1.19.0 -c /etc/static.yaml
```
3. Make a request to `/healthcheck`.
```
curl -v  localhost:10000/healthcheck

< HTTP/1.1 200 OK
< date: Thu, 15 Jul 2021 14:35:12 GMT
< server: envoy
< content-length: 0
```

Expectation: Lua filter should not be executed

Actual logs:

```
[2021-07-15 14:30:45.627][23][debug][http] [source/common/http/conn_manager_impl.cc:858] [C0][S7712392761175078799] request headers complete (end_stream=true):
':authority', 'localhost:10000'
':path', '/healthcheck'
':method', 'GET'
'user-agent', 'curl/7.64.1'
'accept', '*/*'

[2021-07-15 14:30:45.627][23][info][lua] [source/extensions/filters/http/lua/lua_filter.cc:795] script log: Hello World.

[2021-07-15 14:30:45.628][23][debug][http] [source/common/http/filter_manager.cc:909] [C0][S7712392761175078799] Sending local reply with details direct_response

[2021-07-15 14:30:45.628][23][info][lua] [source/extensions/filters/http/lua/lua_filter.cc:795] script log: Goodbye
```

*Config*:[ static.yaml](https://gist.github.com/nandu-vinodan/6b90e1160d535b3ee9f6ef75cc1a5356#file-static-yaml)

*Logs*: [trace logs](https://gist.github.com/nandu-vinodan/6b90e1160d535b3ee9f6ef75cc1a5356#file-envoy-logs)

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: http: return per route config when direct response is set
Additional Description:
When the direct response is set, the `Route::routeEntry()` could be `nullptr`, but it
doesn't mean there is no per route typed config.  So the most specific route config
should be able to get from the `class Route`. So move the `mostSpecificPerFilterConfigTyped`
interface into class `Route`.
Risk Level: low
Testing: unittest 
Docs Changes: n/a
Release Notes: n/a
[Optional Runtime guard:]
Fixes #17377

Signed-off-by: He Jie Xu <hejie.xu@intel.com>

### CODE REVIEW

File: envoy/router/router.h [hunk 1]
```diff
@@ -1068,6 +1058,13 @@ class Route {
    */
   virtual const RouteSpecificFilterConfig* perFilterConfig(const std::string& name) const PURE;
 
+  /**
+   * This is a helper to get the route's per-filter config if it exists, otherwise the virtual
+   * host's. Or nullptr if none of them exist.
+   */
+  virtual const RouteSpecificFilterConfig*
+  mostSpecificPerFilterConfig(const std::string& name) const PURE;
```
Comment (mattklein123) [inline envoy/router/router.h:1066]: Is there any reason at this point to keep `perFilterConfig` at the interface level? Can we remove it? That can be an internal implementation detail. It seems that users should never care about whether the config comes from route/vhost/etc.?

**Review by mattklein123 — COMMENTED** [review]
Thanks for fixing! One question.

/wait-any

File: envoy/router/router.h (hunk 1 above)
Comment (soulxu) [reply envoy/router/router.h:1066]: looks like `traversePerFilterConfig` is only place using the `perFilterConfig` out side the class.
https://github.com/envoyproxy/envoy/blob/6834081f835d609606e77ef84d734e30fc403d58/source/common/http/utility.h#L536

So we can move the `traversePerFilterConfig` to the interface also.

Both `traversePerFilterConfig` and `mostSpecificPerFilterConfig` needs the `perFilterConfig`, we can make it as private.

File: envoy/router/router.h [hunk 2]
```diff
@@ -581,6 +566,16 @@ class VirtualHost {
    *         rather than no limit applies.
    */
   virtual uint32_t retryShadowBufferLimit() const PURE;
+
+private:
+  friend class RouteEntryImplBase;
```
Comment (soulxu) [inline envoy/router/router.h:571]: @mattklein123 this may not what you want, it is required by https://github.com/envoyproxy/envoy/pull/17449/files/53a962d6e6d34bb91ffb3937dd90da95939a4e14..202bf5655ae666a93bf2ce55adcf0cb55918d89d#diff-caa28d598c49a80fee49bb96c71783c953c6840fb72821cebfc2faff22d49563R600

Comment (mattklein123) [reply envoy/router/router.h:571]: Once you are inside the impl, can you just use impl methods? I'm not sure why this has to be defined at the interface level?

Comment (soulxu) [reply envoy/router/router.h:571]: oh, you are right. It needn't to be in interface. I thought there are a lot of subclasses of Route, then we need the virtual functional here. But actually, it is not.

Comment (soulxu) [reply envoy/router/router.h:571]: There are two things.

First, the `RouteEntryImplBase::mostSpecificPerFilterConfig` is using VirtualHost's perFilterConfig interface which I can't remove from the VirtualHost interface.
https://github.com/envoyproxy/envoy/pull/17449/files#diff-caa28d598c49a80fee49bb96c71783c953c6840fb72821cebfc2faff22d49563R598-R601

Second, `RouteEntryImplBase::traversePerFilterConfig` it needs the RouteEntry's perFilterConfig.  
https://github.com/envoyproxy/envoy/pull/17449/files#diff-2663fc9624b6710b28f768baef19fe0d321f541c74be11a492735ae90bd681cdR1026-R1031

From the name of variable `maybe_weighted_cluster_config`, it should be for `WeightedClusterEntry`. But I think I can remove that, since `WeightedClusterEntry` has the own implement of `traversePerFilterConfig`

https://github.com/envoyproxy/envoy/pull/17449/files#diff-2663fc9624b6710b28f768baef19fe0d321f541c74be11a492735ae90bd681cdR1080-R1090

Comment (mattklein123) [reply envoy/router/router.h:571]: I think all usage is inside config_impl though, right? Can you just replace calls to virtualHost() with a direct access to the impl class? I'm pretty sure this can all be pretty easily refactored to be internal to config_impl only and not the interface?

Comment (soulxu) [reply envoy/router/router.h:571]: oh, right, I can use the member directly since it is virtualHostImpl, let me update

Comment (soulxu) [reply envoy/router/router.h:571]: ah, you are right, I got it, let me update.

File: source/common/router/config_impl.cc [hunk 3]
```diff
@@ -1001,9 +1001,22 @@ void RouteEntryImplBase::validateClusters(
   }
 }
 
-const RouteSpecificFilterConfig*
-RouteEntryImplBase::perFilterConfig(const std::string& name) const {
-  return per_filter_configs_.get(name);
+void RouteEntryImplBase::traversePerFilterConfig(
+    const std::string& filter_name,
+    std::function<void(const Router::RouteSpecificFilterConfig&)> cb) const {
+  const Router::RouteEntry* route_entry = routeEntry();
```
Comment (mattklein123) [inline source/common/router/config_impl.cc:1007]: Isn't this the same bug? Shouldn't we not be gating this on `routeEntry()`? Or are you not fixing this because you want it changes extauth and you want to fix this separately? If the latter can you add a comment/TODO here?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks, looks great. One small comment.

/wait

File: source/common/router/config_impl.cc (hunk 3 above)
Comment (soulxu) [reply source/common/router/config_impl.cc:1007]: Yes, I plan to fix this in separate PR, along with https://github.com/envoyproxy/envoy/issues/17502, Let me add a todo.

Actually, I'm a little confused about the separate PR. I used to use gerrit before. Everybody is reviewing the each commit and merge each commit separately. But PR includes multiple commits, but look like people doesn't care about how many commits in a PR.  But let me know what is preference way people do here :)

Comment (mattklein123) [reply source/common/router/config_impl.cc:1007]: We squash all the commits when we merge, so just add as many commits as you want. The GH review system is very bad compared to Gerrit and this is the only way to make it reasonably work.

**Review by mattklein123 — DISMISSED** [review]
Thanks!

**Comment by soulxu** [comment]
> Sorry looks like this needs a main merge.
> 
> /wait

done

**Comment by mattklein123** [comment]
Sorry can you merge main again which should fix the verify examples breakage?

/wait

**Comment by soulxu** [comment]
> Sorry can you merge main again which should fix the verify examples breakage?
> 
> /wait

haha, did merge again :)

**Review by mattklein123 — APPROVED** [review]
Thanks!

**Comment by ggreenway** [comment]
/backport

This results in broken configs, with no workaround.
