### PR TITLE
tracing: Cancel active tracing requests upon destruction.

### LINKED ISSUE #2257: lightstep tracer crash during shutdown
```
(gdb) bt
#0  0x0000000000660350 in lightstep::collector::ReportRequest::Clear() ()
#1  0x000000000064d01a in lightstep::ManualRecorder::OnFailure(std::error_code) ()
#2  0x000000000063e6ec in Envoy::Tracing::LightStepDriver::LightStepTransporter::onSuccess(std::unique_ptr<Envoy::Http::Message, std::default_delete<Envoy::Http::Message> >&&) (this=<optimized out>, response=<optimized out>) at external/envoy/source/common/tracing/lightstep_tracer_impl.cc:78
#3  0x00000000006a8b26 in Envoy::Http::AsyncRequestImpl::onComplete (this=<optimized out>) at external/envoy/source/common/http/async_client_impl.cc:196
#4  0x00000000006a8a49 in Envoy::Http::AsyncStreamImpl::encodeData (this=0xf07ad88, data=..., end_stream=true) at external/envoy/source/common/http/async_client_impl.cc:101
#5  0x0000000000742bf5 in operator() (__args#1=true, __args#0=..., this=0x7f1ecb87c0c0) at /usr/include/c++/5/functional:2267
#6  Envoy::Http::Utility::sendLocalReply(std::function<void (std::unique_ptr<Envoy::Http::HeaderMap, std::default_delete<Envoy::Http::HeaderMap> >&&, bool)>, std::function<void (Envoy::Buffer::Instance&, bool)>, bool const&, Envoy::Http::Code, std::string const&) (encode_headers=..., encode_data=..., 
    is_reset=@0xf07ae74: false, response_code=response_code@entry=Envoy::Http::ServiceUnavailable, body_text=...) at external/envoy/source/common/http/utility.cc:234
#7  0x00000000006aa86c in Envoy::Router::Filter::sendLocalReply (this=this@entry=0xf07adc8, code=code@entry=Envoy::Http::ServiceUnavailable, body=..., overloaded=overloaded@entry=false) at external/envoy/source/common/router/router.cc:188
#8  0x00000000006af284 in Envoy::Router::Filter::onUpstreamReset (this=0xf07adc8, type=type@entry=Envoy::Router::Filter::Reset, reset_reason=...) at external/envoy/source/common/router/router.cc:507
#9  0x00000000006af5ec in Envoy::Router::Filter::UpstreamRequest::onResetStream (this=0x4756500, reason=Envoy::Http::ConnectionTermination) at external/envoy/source/common/router/router.cc:842
#10 0x00000000006109a9 in runResetCallbacks (reason=Envoy::Http::ConnectionTermination, this=0x836ee28) at bazel-out/k8-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_helper_lib/common/http/codec_helper.h:45
#11 Envoy::Http::Http2::ConnectionImpl::StreamImpl::resetStream (this=0x836ee00, reason=Envoy::Http::ConnectionTermination) at external/envoy/source/common/http/http2/codec_impl.cc:263
#12 0x000000000059c530 in Envoy::Http::CodecClient::onEvent (this=0x86d15e0, event=<optimized out>) at external/envoy/source/common/http/codec_client.cc:75
#13 0x00000000005af0b5 in Envoy::Network::ConnectionImpl::raiseEvent (this=0x8ed8000, event=Envoy::Network::LocalClose) at external/envoy/source/common/network/connection_impl.cc:292
#14 0x000000000057bafe in Envoy::Http::Http2::ConnPoolImpl::closeConnections (this=0x38b84b0) at external/envoy/source/common/http/http2/conn_pool.cc:30
#15 0x000000000057ccae in Envoy::Http::Http2::ConnPoolImpl::~ConnPoolImpl (this=0x38b84b0, __in_chrg=<optimized out>) at external/envoy/source/common/http/http2/conn_pool.cc:22
#16 0x000000000057cd88 in ~ProdConnPoolImpl (this=0x38b84b0, __in_chrg=<optimized out>) at bazel-out/k8-opt/bin/external/envoy/source/common/http/http2/_virtual_includes/conn_pool_lib/common/http/http2/conn_pool.h:96
#17 Envoy::Http::Http2::ProdConnPoolImpl::~ProdConnPoolImpl (this=0x38b84b0, __in_chrg=<optimized out>) at bazel-out/k8-opt/bin/external/envoy/source/common/http/http2/_virtual_includes/conn_pool_lib/common/http/http2/conn_pool.h:96
#18 0x0000000000557fbd in operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:76
#19 ~unique_ptr (this=0x3a4b818, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#20 ~array (this=0x3a4b818, __in_chrg=<optimized out>) at /usr/include/c++/5/array:89
#21 ~ConnPoolsContainer (this=0x3a4b818, __in_chrg=<optimized out>) at bazel-out/k8-opt/bin/external/envoy/source/common/upstream/_virtual_includes/cluster_manager_lib/common/upstream/cluster_manager_impl.h:187
#22 ~pair (this=0x3a4b808, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/stl_pair.h:96
#23 destroy<std::pair<std::shared_ptr<Envoy::Upstream::Host const> const, Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::ConnPoolsContainer> > (this=<synthetic pointer>, __p=<optimized out>) at /usr/include/c++/5/ext/new_allocator.h:124
#24 destroy<std::pair<std::shared_ptr<Envoy::Upstream::Host const> const, Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::ConnPoolsContainer> > (__a=<synthetic pointer>, __p=<optimized out>) at /usr/include/c++/5/bits/alloc_traits.h:542
#25 _M_deallocate_node (this=<optimized out>, __n=0x3a4b800) at /usr/include/c++/5/bits/hashtable_policy.h:1973
#26 _M_deallocate_nodes (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/5/bits/hashtable_policy.h:1986
#27 std::_Hashtable<std::shared_ptr<Envoy::Upstream::Host const>, std::pair<std::shared_ptr<Envoy::Upstream::Host const> const, Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::ConnPoolsContainer>, std::allocator<std::pair<std::shared_ptr<Envoy::Upstream::Host const> const, Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::ConnPoolsContainer> >, std::__detail::_Select1st, std::equal_to<std::shared_ptr<Envoy::Upstream::Host const> >, std::hash<std::shared_ptr<Envoy::Upstream::Host const> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::clear (this=this@entry=0x4b09130) at /usr/include/c++/5/bits/hashtable.h:1914
#28 0x0000000000558103 in clear (this=0x4b09130) at /usr/include/c++/5/bits/unordered_map.h:568
#29 Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::~ThreadLocalClusterManagerImpl (this=0x4b090e0, __in_chrg=<optimized out>) at external/envoy/source/common/upstream/cluster_manager_impl.cc:524
#30 0x0000000000558181 in Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::~ThreadLocalClusterManagerImpl (this=0x4b090e0, __in_chrg=<optimized out>) at external/envoy/source/common/upstream/cluster_manager_impl.cc:531
#31 0x00000000005269fa in _M_release (this=0x3784740) at /usr/include/c++/5/bits/shared_ptr_base.h:150
#32 ~__shared_count (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:659
#33 ~__shared_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:925
#34 reset (this=0x36a8020) at /usr/include/c++/5/bits/shared_ptr_base.h:1022
#35 Envoy::ThreadLocal::InstanceImpl::shutdownThread (this=<optimized out>) at external/envoy/source/common/thread_local/thread_local_impl.cc:146
#36 0x0000000000537c59 in Envoy::Server::WorkerImpl::threadRoutine (this=0x2fe5920, guard_dog=...) at external/envoy/source/server/worker_impl.cc:119
#37 0x00000000007c1f2e in Envoy::Thread::Thread::Thread(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) () at /usr/include/c++/5/functional:2267
#38 0x00007f1ecc9b8184 in start_thread (arg=0x7f1ecb87e700) at pthread_create.c:312
#39 0x00007f1ecc3deffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

@rnburn FYI ^. I haven't debugged this yet but just opening the issue as we just saw an instance of this in prod. I will do some more analysis over the next couple of days.

### PR DESCRIPTION
**Pull request by rnburn**
Signed-off-by: Ryan Burn <ryan.burn@gmail.com>

*Description*:
When a LightStepTransporter gets destroyed, any active requests it has must be cancelled; otherwise callbacks will be invoked on a destructed object.

*Risk Level*: Low

*Testing*:
Added a unit test to verify described behavior.

Fixes #2257

### CODE REVIEW

File: test/common/tracing/lightstep_tracer_impl_test.cc [hunk 1]
```diff
@@ -320,6 +320,39 @@ TEST_F(LightStepDriverTest, FlushOneSpanGrpcFailure) {
...
+                         message->headers().Path()->value().c_str());
+            EXPECT_STREQ("fake_cluster", message->headers().Host()->value().c_str());
+            EXPECT_STREQ("application/grpc", message->headers().ContentType()->value().c_str());
+
+            return &request;
+          }));
+  EXPECT_CALL(runtime_.snapshot_, getInteger("tracing.lightstep.min_flush_spans", 5))
+      .WillOnce(Return(1));
+  EXPECT_CALL(runtime_.snapshot_, getInteger("tracing.lightstep.request_timeout", 5000U))
+      .WillOnce(Return(5000U));
```
Comment (htuch) [inline test/common/tracing/lightstep_tracer_impl_test.cc]: Can you factor out the boiler plate here with the other test(s) that share it?

File: test/common/tracing/lightstep_tracer_impl_test.cc [hunk 2]
```diff
@@ -320,6 +320,39 @@ TEST_F(LightStepDriverTest, FlushOneSpanGrpcFailure) {
...
+
+  SpanPtr span = driver_->startSpan(config_, request_headers_, operation_name_, start_time_);
+  span->finishSpan();
+
+  EXPECT_CALL(request, cancel()).Times(1);
```
Comment (mattklein123) [inline test/common/tracing/lightstep_tracer_impl_test.cc]: nit: `Times(1)` is redundant. The default is 1 time. You can just do `EXPECT_CALL(request, cancel());`

File: test/common/tracing/lightstep_tracer_impl_test.cc (hunk 1 above)
Comment (rnburn) [reply test/common/tracing/lightstep_tracer_impl_test.cc]: I removed the redundant testing code that's covered in other cases.

I'm not sure how to factor that portion out since it does vary in a few of the test cases (`FlushSeveralSpans` uses a different setup than the others)

File: test/common/tracing/lightstep_tracer_impl_test.cc (hunk 2 above)
Comment (rnburn) [reply test/common/tracing/lightstep_tracer_impl_test.cc]: Fixed.
