### PR TITLE
fix Postgres filter's incorrect transaction metrics calculation

### LINKED ISSUE #14065: postgres: filter is not computing explicit transaction metrics correctly
**Postgres Network Filter is not computing explicit transactions metrics correctly**

In Postgres all single statements are considered as an implicit transaction if they are not executed inside an explicit transaction block. For example:

```sql
CREATE TABLE foo(id integer);
INSERT INTO foo (id) VALUES (1), (2);
SELECT * FROM foo;
```

The example above should be considered as 3 (three) distinct transactions, then the envoy metrics should be something like:

```
postgres.egress_postgres.statements: 3
postgres.egress_postgres.statements_delete: 0
postgres.egress_postgres.statements_insert: 1
postgres.egress_postgres.statements_other: 1
...
postgres.egress_postgres.statements_select: 1
postgres.egress_postgres.statements_update: 0
postgres.egress_postgres.transactions: 3
postgres.egress_postgres.transactions_commit: 3
postgres.egress_postgres.transactions_rollback: 0
```

The metrics above are 100% correct, but now let's try it using explicit transaction statements:

```sql
BEGIN;
CREATE TABLE foo(id integer);
INSERT INTO foo (id) VALUES (1), (2);
SELECT * FROM foo;
COMMIT;
```

The example above should be considered as 1 (one) single transaction, but the envoy metrics get confused about it:

```
postgres.egress_postgres.statements: 5
postgres.egress_postgres.statements_delete: 0
postgres.egress_postgres.statements_insert: 1
postgres.egress_postgres.statements_other: 3
...
postgres.egress_postgres.statements_select: 1
postgres.egress_postgres.statements_update: 0
postgres.egress_postgres.transactions: 5
postgres.egress_postgres.transactions_commit: 5
postgres.egress_postgres.transactions_rollback: 0
```

The correct and expected result for the second statement set should be:

```
postgres.egress_postgres.statements: 5
postgres.egress_postgres.statements_delete: 0
postgres.egress_postgres.statements_insert: 1
postgres.egress_postgres.statements_other: 3
...
postgres.egress_postgres.statements_select: 1
postgres.egress_postgres.statements_update: 0
postgres.egress_postgres.transactions: 1
postgres.egress_postgres.transactions_commit: 1
postgres.egress_postgres.transactions_rollback: 0
```

There are two more statements (BEGIN and COMMIT) and it's totally Ok, but the main problem is with the `transactions` metrics that are not computed correctly.

### PR DESCRIPTION
**Pull request by fabriziomello**
Commit Message: fix incorrect transaction metrics calculation on Postgres filter
Additional Description:
In Postgres all single statements are considered as an implicit transaction if they are not executed inside an explicit transaction block, but if they are so the transaction metrics should be increased once per transaction block and not for each statement.

Risk Level: Low
Testing: Improved unit tests
Docs Changes: N/A.
Release Notes: N/A.
Platform Specific Features: N/A.
Fixes #14065

### CODE REVIEW

File: source/extensions/filters/network/postgres_proxy/postgres_decoder.cc [hunk 1]
```diff
@@ -292,13 +292,23 @@ bool DecoderImpl::onData(Buffer::Instance& data, bool frontend) {
...
+    // take the whole message.
+    position = message_.find('\0');
+  }
+  std::string statement = message_.substr(0, position);
+
+  ENVOY_LOG(debug, "statement = {} {}", statement, statement.length());
 
   auto it = BE_statements_.find(statement);
   if (it != BE_statements_.end()) {
+    ENVOY_LOG(debug, "FOUND statement", statement);
```
Comment (cpakulski) [inline source/extensions/filters/network/postgres_proxy/postgres_decoder.cc:308]: Should it contain {} in log message?

File: source/extensions/filters/network/postgres_proxy/postgres_decoder.cc [hunk 2]
```diff
@@ -292,13 +292,23 @@ bool DecoderImpl::onData(Buffer::Instance& data, bool frontend) {
...
     (*it).second(this);
   } else {
+    ENVOY_LOG(debug, "NOT FOUND statement", statement);
```
Comment (cpakulski) [inline source/extensions/filters/network/postgres_proxy/postgres_decoder.cc:311]: The same as above: {}?

**Review by cpakulski — CHANGES_REQUESTED** [review]
LGTM accept log format. Can you verify that. Thanks.

File: source/extensions/filters/network/postgres_proxy/postgres_decoder.cc (hunk 1 above)
Comment (fabriziomello) [reply source/extensions/filters/network/postgres_proxy/postgres_decoder.cc]: My bad... leaved this trash behind!!! Fixed.

File: source/extensions/filters/network/postgres_proxy/postgres_decoder.cc (hunk 2 above)
Comment (fabriziomello) [reply source/extensions/filters/network/postgres_proxy/postgres_decoder.cc]: My bad... leaved this trash behind!!! Fixed.

**Review by cpakulski — APPROVED** [review]
LGTM. Thanks.

**Comment by fabriziomello** [comment]
Thanks for your review @cpakulski ... now just wait for @dio review!!!

**Comment by fabriziomello** [comment]
Hi @dio ... can you review this PR pls... it's very important because we're facing errors on Transactions metrics and it lead to wrong dashboards

File: source/extensions/filters/network/postgres_proxy/postgres_message.h [hunk 3]
```diff
@@ -11,7 +11,7 @@ namespace PostgresProxy {
 
 /**
  * Postgres messages are described in official Postgres documentation:
- * https://www.postgresql.org/docs/12/protocol-message-formats.html
+ * https://www.postgresql.org/docs/current/protocol-message-formats.html
```
Comment (dio) [inline source/extensions/filters/network/postgres_proxy/postgres_message.h:14]: This will change over time? I'm OK with this though.

File: source/extensions/filters/network/postgres_proxy/postgres_decoder.cc [hunk 4]
```diff
@@ -292,8 +292,14 @@ bool DecoderImpl::onData(Buffer::Instance& data, bool frontend) {
...
-  // take the whole message.
-  std::string statement = message_.substr(0, message_.find(' '));
+  // try to find for the null terminator character (\0).
+  std::size_t position = message_.find(' ');
+  if (position == std::string::npos) {
+    // If the null terminator character (\0) cannot be found then
+    // take the whole message.
+    position = message_.find('\0');
+  }
+  std::string statement = message_.substr(0, position);
```
Comment (dio) [inline source/extensions/filters/network/postgres_proxy/postgres_decoder.cc:302]: const?

**Review by dio — DISMISSED** [review]
An optional const.

File: source/extensions/filters/network/postgres_proxy/postgres_message.h (hunk 3 above)
Comment (fabriziomello) [reply source/extensions/filters/network/postgres_proxy/postgres_message.h:14]: The work we did here with the filter is to be totally independent of the Postgres version, so make sense to point to the current stable version.

File: source/extensions/filters/network/postgres_proxy/postgres_decoder.cc (hunk 4 above)
Comment (fabriziomello) [reply source/extensions/filters/network/postgres_proxy/postgres_decoder.cc]: Fixed!

**Comment by fabriziomello** [comment]
@dio @cpakulski IMHO it should be back patched to 1.15. What do you think about it? How back patches are handled in Envoy development?

**Review by dio — APPROVED** [review]

**Comment by dio** [comment]
re: backporting, I think @cpakulski is the one who in charge of it. I think he can decide and ask around on this. :)

**Comment by cpakulski** [comment]
Normally only security fixes are backported, like crashes, memory leaks, etc. In rare situations other fixes may be backported if previous release is really unusable without the fix. But back releases are released more or less along with main releases. So, even if the fix is backported it does not mean that there will be an official 1.15.x release available immediately.
