### PR TITLE
test: fixing a teardown ordering bug

### LINKED ISSUE #11538: http2_integration_test flood test flake
I've seen this a few times in CI:
```
2020-06-10T14:23:40.3629074Z [ RUN      ] IpVersions/Http2FloodMitigationTest.Data/IPv6
2020-06-10T14:23:40.3629467Z ==================
2020-06-10T14:23:40.3629850Z WARNING: ThreadSanitizer: data race (pid=15)
2020-06-10T14:23:40.3630294Z   Read of size 8 at 0x0000087c1178 by thread T3:
2020-06-10T14:23:40.3631800Z     #0 Envoy::InjectableSingleton<Envoy::Runtime::Loader>::getExisting() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/singleton/_virtual_includes/threadsafe_singleton/common/singleton/threadsafe_singleton.h:60:36 (http2_integration_test+0x2e92f1f)
2020-06-10T14:23:40.3632816Z     #1 Envoy::Runtime::getInteger(absl::string_view, unsigned long) /proc/self/cwd/source/common/runtime/runtime_features.cc:26:7 (http2_integration_test+0x5bcd09a)
2020-06-10T14:23:40.3633669Z     #2 Envoy::Buffer::WatermarkBuffer::setWatermarks(unsigned int, unsigned int) /proc/self/cwd/source/common/buffer/watermark_buffer.cc:75:7 (http2_integration_test+0x57e752f)
2020-06-10T14:23:40.3635061Z     #3 Envoy::Http::Http2::ConnectionImpl::StreamImpl::setWriteBufferWatermarks(unsigned int, unsigned int) /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/http/http2/_virtual_includes/codec_lib/common/http/http2/codec_impl.h:252:26 (http2_integration_test+0x55ee24e)
2020-06-10T14:23:40.3636169Z     #4 Envoy::Http::Http2::ConnectionImpl::StreamImpl::StreamImpl(Envoy::Http::Http2::ConnectionImpl&, unsigned int) /proc/self/cwd/source/common/http/http2/codec_impl.cc:99:5 (http2_integration_test+0x55c718f)
2020-06-10T14:23:40.3638284Z     #5 Envoy::Http::Http2::ConnectionImpl::ServerStreamImpl::ServerStreamImpl(Envoy::Http::Http2::ConnectionImpl&, unsigned int) /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/http/http2/_virtual_includes/codec_lib/common/http/http2/codec_impl.h:359:11 (http2_integration_test+0x55f2bbc)
2020-06-10T14:23:40.3639470Z     #6 Envoy::Http::Http2::ServerConnectionImpl::onBeginHeaders(nghttp2_frame const*) /proc/self/cwd/source/common/http/http2/codec_impl.cc:1256:34 (http2_integration_test+0x55d708e)
2020-06-10T14:23:40.3641194Z     #7 non-virtual thunk to Envoy::Http::Http2::ServerConnectionImpl::onBeginHeaders(nghttp2_frame const*) /proc/self/cwd/source/common/http/http2/codec_impl.cc (http2_integration_test+0x55d746f)
2020-06-10T14:23:40.3642354Z     #8 Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_10::operator()(nghttp2_session*, nghttp2_frame const*, void*) const /proc/self/cwd/source/common/http/http2/codec_impl.cc:1037:57 (http2_integration_test+0x55da7cc)
2020-06-10T14:23:40.3643418Z     #9 Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_10::__invoke(nghttp2_session*, nghttp2_frame const*, void*) /proc/self/cwd/source/common/http/http2/codec_impl.cc:1036:19 (http2_integration_test+0x55da728)
2020-06-10T14:23:40.3644298Z     #10 session_call_on_begin_headers /b/f/w/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:3314:10 (http2_integration_test+0x5cdaad0)
2020-06-10T14:23:40.3645018Z     #11 nghttp2_session_on_request_headers_received /b/f/w/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:3915:8 (http2_integration_test+0x5cda63b)
2020-06-10T14:23:40.3645720Z     #12 session_process_headers_frame /b/f/w/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:4059:12 (http2_integration_test+0x5ce94a0)
2020-06-10T14:23:40.3647204Z     #13 nghttp2_session_mem_recv /b/f/w/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:5570:14 (http2_integration_test+0x5ce0df3)
2020-06-10T14:23:40.3648168Z     #14 Envoy::Http::Http2::ConnectionImpl::innerDispatch(Envoy::Buffer::Instance&) /proc/self/cwd/source/common/http/http2/codec_impl.cc:495:9 (http2_integration_test+0x55cf25f)
2020-06-10T14:23:40.3649298Z     #15 Envoy::Http::Http2::ServerConnectionImpl::innerDispatch(Envoy::Buffer::Instance&) /proc/self/cwd/source/common/http/http2/codec_impl.cc:1382:26 (http2_integration_test+0x55d9424)
2020-06-10T14:23:40.3650462Z     #16 Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23::operator()(Envoy::Buffer::Instance&) const /proc/self/cwd/source/common/http/http2/codec_impl.cc:1368:60 (http2_integration_test+0x55eb284)
2020-06-10T14:23:40.3652045Z     #17 decltype(std::__1::forward<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&>(fp)(std::__1::forward<Envoy::Buffer::Instance&>(fp0))) std::__1::__invoke<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&, Envoy::Buffer::Instance&>(Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&, Envoy::Buffer::Instance&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1 (http2_integration_test+0x55eb194)
2020-06-10T14:23:40.3654153Z     #18 absl::Status std::__1::__invoke_void_return_wrapper<absl::Status>::__call<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&, Envoy::Buffer::Instance&>(Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&, Envoy::Buffer::Instance&) /opt/llvm/bin/../include/c++/v1/__functional_base:317:16 (http2_integration_test+0x55eb0c4)
2020-06-10T14:23:40.3655815Z     #19 std::__1::__function::__alloc_func<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23, std::__1::allocator<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23>, absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) /opt/llvm/bin/../include/c++/v1/functional:1533:16 (http2_integration_test+0x55eb034)
2020-06-10T14:23:40.3657741Z     #20 std::__1::__function::__func<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23, std::__1::allocator<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23>, absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) /opt/llvm/bin/../include/c++/v1/functional:1707:12 (http2_integration_test+0x55e92d3)
2020-06-10T14:23:40.3659239Z     #21 std::__1::__function::__value_func<absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) const /opt/llvm/bin/../include/c++/v1/functional:1860:16 (http2_integration_test+0x47740eb)
2020-06-10T14:23:40.3660430Z     #22 std::__1::function<absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) const /opt/llvm/bin/../include/c++/v1/functional:2419:12 (http2_integration_test+0x4773fff)
2020-06-10T14:23:40.3661762Z     #23 Envoy::Http::Utility::exceptionToStatus(std::__1::function<absl::Status (Envoy::Buffer::Instance&)>, Envoy::Buffer::Instance&) /proc/self/cwd/source/common/http/utility.cc:41:14 (http2_integration_test+0x5bce840)
2020-06-10T14:23:40.3663065Z     #24 Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&) /proc/self/cwd/source/common/http/http2/codec_impl.cc:1367:10 (http2_integration_test+0x55d8ed2)
2020-06-10T14:23:40.3663906Z     #25 Envoy::FakeHttpConnection::ReadFilter::onData(Envoy::Buffer::Instance&, bool) /proc/self/cwd/./test/integration/fake_upstream.h:453:45 (http2_integration_test+0x2cffbc9)
2020-06-10T14:23:40.3664859Z     #26 Envoy::Network::FilterManagerImpl::onContinueReading(Envoy::Network::FilterManagerImpl::ActiveReadFilter*, Envoy::Network::ReadBufferSource&) /proc/self/cwd/source/common/network/filter_manager_impl.cc:66:48 (http2_integration_test+0x57e0358)
2020-06-10T14:23:40.3665780Z     #27 Envoy::Network::FilterManagerImpl::onRead() /proc/self/cwd/source/common/network/filter_manager_impl.cc:76:3 (http2_integration_test+0x57e0651)
2020-06-10T14:23:40.3666504Z     #28 Envoy::Network::ConnectionImpl::onRead(unsigned long) /proc/self/cwd/source/common/network/connection_impl.cc:297:19 (http2_integration_test+0x57b8bb2)
2020-06-10T14:23:40.3667443Z     #29 Envoy::Network::ConnectionImpl::onReadReady() /proc/self/cwd/source/common/network/connection_impl.cc:579:5 (http2_integration_test+0x57bddc0)
2020-06-10T14:23:40.3668389Z     #30 Envoy::Network::ConnectionImpl::onFileEvent(unsigned int) /proc/self/cwd/source/common/network/connection_impl.cc:539:5 (http2_integration_test+0x57bc310)
2020-06-10T14:23:40.3669981Z     #31 Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6::operator()(unsigned int) const /proc/self/cwd/source/common/network/connection_impl.cc:77:74 (http2_integration_test+0x57d2157)
2020-06-10T14:23:40.3673640Z     #32 decltype(std::__1::forward<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&>(fp)(std::__1::forward<unsigned int>(fp0))) std::__1::__invoke<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1 (http2_integration_test+0x57d209c)
2020-06-10T14:23:40.3678431Z     #33 void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9 (http2_integration_test+0x57d1fcd)
2020-06-10T14:23:40.3682690Z     #34 std::__1::__function::__alloc_func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) /opt/llvm/bin/../include/c++/v1/functional:1533:16 (http2_integration_test+0x57d1f4d)
2020-06-10T14:23:40.3686283Z     #35 std::__1::__function::__func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) /opt/llvm/bin/../include/c++/v1/functional:1707:12 (http2_integration_test+0x57d01fc)
2020-06-10T14:23:40.3689215Z     #36 std::__1::__function::__value_func<void (unsigned int)>::operator()(unsigned int&&) const /opt/llvm/bin/../include/c++/v1/functional:1860:16 (http2_integration_test+0x47a88f4)
2020-06-10T14:23:40.3690155Z     #37 std::__1::function<void (unsigned int)>::operator()(unsigned int) const /opt/llvm/bin/../include/c++/v1/functional:2419:12 (http2_integration_test+0x47a87e8)
2020-06-10T14:23:40.3691548Z     #38 Envoy::Event::FileEventImpl::assignEvents(unsigned int, event_base*)::$_0::operator()(int, short, void*) const /proc/self/cwd/source/common/event/file_event_impl.cc:66:9 (http2_integration_test+0x57a6d44)
2020-06-10T14:23:40.3692492Z     #39 Envoy::Event::FileEventImpl::assignEvents(unsigned int, event_base*)::$_0::__invoke(int, short, void*) /proc/self/cwd/source/common/event/file_event_impl.cc:50:7 (http2_integration_test+0x57a6ac6)
2020-06-10T14:23:40.3693266Z     #40 event_persist_closure /b/f/w/external/com_github_libevent_libevent/event.c:1639:9 (http2_integration_test+0x7a1a1f0)
2020-06-10T14:23:40.3693901Z     #41 event_process_active_single_queue /b/f/w/external/com_github_libevent_libevent/event.c:1698:4 (http2_integration_test+0x7a18c18)
2020-06-10T14:23:40.3694520Z     #42 event_process_active /b/f/w/external/com_github_libevent_libevent/event.c:1799:9 (http2_integration_test+0x7a0e458)
2020-06-10T14:23:40.3695121Z     #43 event_base_loop /b/f/w/external/com_github_libevent_libevent/event.c:2041:12 (http2_integration_test+0x7a0c103)
2020-06-10T14:23:40.3695841Z     #44 Envoy::Event::LibeventScheduler::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/libevent_scheduler.cc:47:3 (http2_integration_test+0x5a8e9ef)
2020-06-10T14:23:40.3696800Z     #45 Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/dispatcher_impl.cc:203:19 (http2_integration_test+0x57926a1)
2020-06-10T14:23:40.3697771Z     #46 Envoy::FakeUpstream::threadRoutine() /proc/self/cwd/test/integration/fake_upstream.cc:494:16 (http2_integration_test+0x2cc2174)
2020-06-10T14:23:40.3699206Z     #47 Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12::operator()() const /proc/self/cwd/test/integration/fake_upstream.cc:457:67 (http2_integration_test+0x2ce7a5b)
2020-06-10T14:23:40.3702670Z     #48 decltype(std::__1::forward<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&>(fp)()) std::__1::__invoke<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&>(Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1 (http2_integration_test+0x2ce79b0)
2020-06-10T14:23:40.3706672Z     #49 void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&>(Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9 (http2_integration_test+0x2ce7910)
2020-06-10T14:23:40.3710891Z     #50 std::__1::__function::__alloc_func<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12, std::__1::allocator<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1533:16 (http2_integration_test+0x2ce78b0)
2020-06-10T14:23:40.3714212Z     #51 std::__1::__function::__func<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12, std::__1::allocator<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1707:12 (http2_integration_test+0x2ce5b7f)
2020-06-10T14:23:40.3716360Z     #52 std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:1860:16 (http2_integration_test+0x2ca9936)
2020-06-10T14:23:40.3717556Z     #53 std::__1::function<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:2419:12 (http2_integration_test+0x2ca95c8)
2020-06-10T14:23:40.3719134Z     #54 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/source/common/common/posix/thread_impl.cc:49:11 (http2_integration_test+0x79f283b)
2020-06-10T14:23:40.3721653Z     #55 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/source/common/common/posix/thread_impl.cc:48:9 (http2_integration_test+0x79f27c8)
2020-06-10T14:23:40.3722495Z 
2020-06-10T14:23:40.3722840Z   Previous write of size 8 at 0x0000087c1178 by thread T6:
2020-06-10T14:23:40.3723969Z     #0 Envoy::InjectableSingleton<Envoy::Runtime::Loader>::clear() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/singleton/_virtual_includes/threadsafe_singleton/common/singleton/threadsafe_singleton.h:67:33 (http2_integration_test+0x306208b)
2020-06-10T14:23:40.3725427Z     #1 Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>::~ScopedInjectableLoader() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/singleton/_virtual_includes/threadsafe_singleton/common/singleton/threadsafe_singleton.h:81:31 (http2_integration_test+0x306203c)
2020-06-10T14:23:40.3726794Z     #2 std::__1::default_delete<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader> >::operator()(Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>*) const /opt/llvm/bin/../include/c++/v1/memory:2338:5 (http2_integration_test+0x3061f76)
2020-06-10T14:23:40.3728496Z     #3 std::__1::unique_ptr<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>, std::__1::default_delete<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader> > >::reset(Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>*) /opt/llvm/bin/../include/c++/v1/memory:2593:7 (http2_integration_test+0x3061ea0)
2020-06-10T14:23:40.3729924Z     #4 std::__1::unique_ptr<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>, std::__1::default_delete<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader> > >::~unique_ptr() /opt/llvm/bin/../include/c++/v1/memory:2547:19 (http2_integration_test+0x304412c)
2020-06-10T14:23:40.3731085Z     #5 Envoy::Server::InstanceImpl::~InstanceImpl() /proc/self/cwd/source/server/server.cc:133:1 (http2_integration_test+0x3003e62)
2020-06-10T14:23:40.3732502Z     #6 Envoy::IntegrationTestServerImpl::createAndRunEnvoyServer(Envoy::OptionsImpl&, Envoy::Event::TimeSystem&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::ListenerHooks&, Envoy::Thread::BasicLockable&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Runtime::RandomGenerator, std::__1::default_delete<Envoy::Runtime::RandomGenerator> >&&, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >) /proc/self/cwd/test/integration/server.cc:221:3 (http2_integration_test+0x2e1899d)
2020-06-10T14:23:40.3734402Z     #7 Envoy::IntegrationTestServer::threadRoutine(Envoy::Network::Address::IpVersion, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >) /proc/self/cwd/test/integration/server.cc:181:3 (http2_integration_test+0x2e180e3)
2020-06-10T14:23:40.3736186Z     #8 Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0::operator()() const /proc/self/cwd/test/integration/server.cc:93:9 (http2_integration_test+0x2e1c2aa)
2020-06-10T14:23:40.3739805Z     #9 decltype(std::__1::forward<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&>(fp)()) std::__1::__invoke<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&>(Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1 (http2_integration_test+0x2e1c0e0)
2020-06-10T14:23:40.3743979Z     #10 void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&>(Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9 (http2_integration_test+0x2e1c040)
2020-06-10T14:23:40.3747526Z     #11 std::__1::__function::__alloc_func<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0, std::__1::allocator<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1533:16 (http2_integration_test+0x2e1bfe0)
2020-06-10T14:23:40.3751144Z     #12 std::__1::__function::__func<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0, std::__1::allocator<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1707:12 (http2_integration_test+0x2e1a6af)
2020-06-10T14:23:40.3753283Z     #13 std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:1860:16 (http2_integration_test+0x2ca9936)
2020-06-10T14:23:40.3754101Z     #14 std::__1::function<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:2419:12 (http2_integration_test+0x2ca95c8)
2020-06-10T14:23:40.3755525Z     #15 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/source/common/common/posix/thread_impl.cc:49:11 (http2_integration_test+0x79f283b)
2020-06-10T14:23:40.3757371Z     #16 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/source/common/common/posix/thread_impl.cc:48:9 (http2_integration_test+0x79f27c8)
2020-06-10T14:23:40.3758154Z 
2020-06-10T14:23:40.3759022Z   Location is global 'Envoy::InjectableSingleton<Envoy::Runtime::Loader>::loader_' of size 8 at 0x0000087c1178 (http2_integration_test+0x0000087c1178)
2020-06-10T14:23:40.3759572Z 
2020-06-10T14:23:40.3759966Z   Thread T3 (tid=1262, running) created by main thread at:
2020-06-10T14:23:40.3761029Z     #0 pthread_create /tmp/final/llvm.src/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:967:3 (http2_integration_test+0x297678b)
2020-06-10T14:23:40.3762091Z     #1 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:46:20 (http2_integration_test+0x79f1267)
2020-06-10T14:23:40.3763588Z     #2 std::__1::__unique_if<Envoy::Thread::ThreadImplPosix>::__unique_single std::__1::make_unique<Envoy::Thread::ThreadImplPosix, std::__1::function<void ()>&, absl::optional<Envoy::Thread::Options> const&>(std::__1::function<void ()>&, absl::optional<Envoy::Thread::Options> const&) /opt/llvm/bin/../include/c++/v1/memory:3003:32 (http2_integration_test+0x79f0bbf)
2020-06-10T14:23:40.3764966Z     #3 Envoy::Thread::ThreadFactoryImplPosix::createThread(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:121:10 (http2_integration_test+0x79f07f3)
2020-06-10T14:23:40.3766491Z     #4 Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool) /proc/self/cwd/test/integration/fake_upstream.cc:457:35 (http2_integration_test+0x2cc04fb)
2020-06-10T14:23:40.3768560Z     #5 Envoy::FakeUpstream::FakeUpstream(std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool, bool) /proc/self/cwd/test/integration/fake_upstream.cc:420:7 (http2_integration_test+0x2cc0bfd)
2020-06-10T14:23:40.3769957Z     #6 Envoy::AutonomousUpstream::AutonomousUpstream(std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool) /proc/self/cwd/./test/integration/autonomous_upstream.h:57:9 (http2_integration_test+0x2d7f802)
2020-06-10T14:23:40.3771443Z     #7 Envoy::BaseIntegrationTest::createUpstreams() /proc/self/cwd/test/integration/integration.cc:314:40 (http2_integration_test+0x2d5f0e5)
2020-06-10T14:23:40.3772178Z     #8 Envoy::BaseIntegrationTest::initialize() /proc/self/cwd/test/integration/integration.cc:305:3 (http2_integration_test+0x2d5e781)
2020-06-10T14:23:40.3772912Z     #9 Envoy::Http2FloodMitigationTest::beginSession() /proc/self/cwd/test/integration/http2_integration_test.cc:1500:3 (http2_integration_test+0x2a163c4)
2020-06-10T14:23:40.3773836Z     #10 Envoy::Http2FloodMitigationTest_Data_Test::TestBody() /proc/self/cwd/test/integration/http2_integration_test.cc:1625:3 (http2_integration_test+0x2a18d01)
2020-06-10T14:23:40.3774834Z     #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10 (http2_integration_test+0x7b90d2c)
2020-06-10T14:23:40.3776010Z     #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14 (http2_integration_test+0x7b7542e)
2020-06-10T14:23:40.3776936Z     #13 testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2508:5 (http2_integration_test+0x7b5a511)
2020-06-10T14:23:40.3777866Z     #14 testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2684:11 (http2_integration_test+0x7b5b3b3)
2020-06-10T14:23:40.3778653Z     #15 testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2816:28 (http2_integration_test+0x7b5bdea)
2020-06-10T14:23:40.3779475Z     #16 testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5338:44 (http2_integration_test+0x7b6b58d)
2020-06-10T14:23:40.3780780Z     #17 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10 (http2_integration_test+0x7b97cdc)
2020-06-10T14:23:40.3782255Z     #18 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14 (http2_integration_test+0x7b792fe)
2020-06-10T14:23:40.3783338Z     #19 testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:4925:10 (http2_integration_test+0x7b6ae4b)
2020-06-10T14:23:40.3784041Z     #20 RUN_ALL_TESTS() /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2473:46 (http2_integration_test+0x56c3177)
2020-06-10T14:23:40.3784861Z     #21 Envoy::TestRunner::RunTests(int, char**) /proc/self/cwd/test/test_runner.cc:134:10 (http2_integration_test+0x56c24ed)
2020-06-10T14:23:40.3785473Z     #22 main /proc/self/cwd/test/main.cc:34:10 (http2_integration_test+0x56bfe91)
2020-06-10T14:23:40.3785813Z 
2020-06-10T14:23:40.3786178Z   Thread T6 (tid=1263, running) created by main thread at:
2020-06-10T14:23:40.3787327Z     #0 pthread_create /tmp/final/llvm.src/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:967:3 (http2_integration_test+0x297678b)
2020-06-10T14:23:40.3788513Z     #1 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:46:20 (http2_integration_test+0x79f1267)
2020-06-10T14:23:40.3789962Z     #2 std::__1::__unique_if<Envoy::Thread::ThreadImplPosix>::__unique_single std::__1::make_unique<Envoy::Thread::ThreadImplPosix, std::__1::function<void ()>&, absl::optional<Envoy::Thread::Options> const&>(std::__1::function<void ()>&, absl::optional<Envoy::Thread::Options> const&) /opt/llvm/bin/../include/c++/v1/memory:3003:32 (http2_integration_test+0x79f0bbf)
2020-06-10T14:23:40.3791544Z     #3 Envoy::Thread::ThreadFactoryImplPosix::createThread(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:121:10 (http2_integration_test+0x79f07f3)
2020-06-10T14:23:40.3793374Z     #4 Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >) /proc/self/cwd/test/integration/server.cc:91:28 (http2_integration_test+0x2e16c02)
2020-06-10T14:23:40.3795786Z     #5 Envoy::IntegrationTestServer::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Envoy::Network::Address::IpVersion, std::__1::function<void (Envoy::IntegrationTestServer&)>, std::__1::function<void ()>, bool, Envoy::Event::TestTimeSystem&, Envoy::Api::Api&, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, bool) /proc/self/cwd/test/integration/server.cc:67:11 (http2_integration_test+0x2e16671)
2020-06-10T14:23:40.3798793Z     #6 Envoy::BaseIntegrationTest::createGeneratedApiTestServer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, Envoy::Server::FieldValidationConfig, bool) /proc/self/cwd/test/integration/integration.cc:457:18 (http2_integration_test+0x2d603a3)
2020-06-10T14:23:40.3800519Z     #7 Envoy::BaseIntegrationTest::createEnvoy() /proc/self/cwd/test/integration/integration.cc:375:3 (http2_integration_test+0x2d5fed6)
2020-06-10T14:23:40.3801396Z     #8 Envoy::BaseIntegrationTest::initialize() /proc/self/cwd/test/integration/integration.cc:307:3 (http2_integration_test+0x2d5e7b6)
2020-06-10T14:23:40.3802267Z     #9 Envoy::Http2FloodMitigationTest::beginSession() /proc/self/cwd/test/integration/http2_integration_test.cc:1500:3 (http2_integration_test+0x2a163c4)
2020-06-10T14:23:40.3804491Z     #10 Envoy::Http2FloodMitigationTest_Data_Test::TestBody() /proc/self/cwd/test/integration/http2_integration_test.cc:1625:3 (http2_integration_test+0x2a18d01)
2020-06-10T14:23:40.3805688Z     #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10 (http2_integration_test+0x7b90d2c)
2020-06-10T14:23:40.3807113Z     #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14 (http2_integration_test+0x7b7542e)
2020-06-10T14:23:40.3808345Z     #13 testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2508:5 (http2_integration_test+0x7b5a511)
2020-06-10T14:23:40.3809129Z     #14 testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2684:11 (http2_integration_test+0x7b5b3b3)
2020-06-10T14:23:40.3809904Z     #15 testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2816:28 (http2_integration_test+0x7b5bdea)
2020-06-10T14:23:40.3810722Z     #16 testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5338:44 (http2_integration_test+0x7b6b58d)
2020-06-10T14:23:40.3812025Z     #17 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10 (http2_integration_test+0x7b97cdc)
2020-06-10T14:23:40.3813465Z     #18 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14 (http2_integration_test+0x7b792fe)
2020-06-10T14:23:40.3814727Z     #19 testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:4925:10 (http2_integration_test+0x7b6ae4b)
2020-06-10T14:23:40.3815474Z     #20 RUN_ALL_TESTS() /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2473:46 (http2_integration_test+0x56c3177)
2020-06-10T14:23:40.3816190Z     #21 Envoy::TestRunner::RunTests(int, char**) /proc/self/cwd/test/test_runner.cc:134:10 (http2_integration_test+0x56c24ed)
2020-06-10T14:23:40.3816953Z     #22 main /proc/self/cwd/test/main.cc:34:10 (http2_integration_test+0x56bfe91)
2020-06-10T14:23:40.3817523Z 
2020-06-10T14:23:40.3818734Z SUMMARY: ThreadSanitizer: data race /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/singleton/_virtual_includes/threadsafe_singleton/common/singleton/threadsafe_singleton.h:60:36 in Envoy::InjectableSingleton<Envoy::Runtime::Loader>::getExisting()
2020-06-10T14:23:40.3819561Z ==================
2020-06-10T14:23:40.3819893Z ==================
2020-06-10T14:23:40.3820571Z WARNING: ThreadSanitizer: data race (pid=15)
2020-06-10T14:23:40.3821009Z   Write of size 8 at 0x0000087c1178 by thread T6:
2020-06-10T14:23:40.3822163Z     #0 Envoy::InjectableSingleton<Envoy::Runtime::Loader>::clear() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/singleton/_virtual_includes/threadsafe_singleton/common/singleton/threadsafe_singleton.h:67:33 (http2_integration_test+0x306208b)
2020-06-10T14:23:40.3823701Z     #1 Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>::~ScopedInjectableLoader() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/singleton/_virtual_includes/threadsafe_singleton/common/singleton/threadsafe_singleton.h:81:31 (http2_integration_test+0x306203c)
2020-06-10T14:23:40.3824997Z     #2 std::__1::default_delete<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader> >::operator()(Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>*) const /opt/llvm/bin/../include/c++/v1/memory:2338:5 (http2_integration_test+0x3061f76)
2020-06-10T14:23:40.3826291Z     #3 std::__1::unique_ptr<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>, std::__1::default_delete<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader> > >::reset(Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>*) /opt/llvm/bin/../include/c++/v1/memory:2593:7 (http2_integration_test+0x3061ea0)
2020-06-10T14:23:40.3827829Z     #4 std::__1::unique_ptr<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader>, std::__1::default_delete<Envoy::ScopedInjectableLoader<Envoy::Runtime::Loader> > >::~unique_ptr() /opt/llvm/bin/../include/c++/v1/memory:2547:19 (http2_integration_test+0x304412c)
2020-06-10T14:23:40.3828877Z     #5 Envoy::Server::InstanceImpl::~InstanceImpl() /proc/self/cwd/source/server/server.cc:133:1 (http2_integration_test+0x3003e62)
2020-06-10T14:23:40.3830647Z     #6 Envoy::IntegrationTestServerImpl::createAndRunEnvoyServer(Envoy::OptionsImpl&, Envoy::Event::TimeSystem&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::ListenerHooks&, Envoy::Thread::BasicLockable&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Runtime::RandomGenerator, std::__1::default_delete<Envoy::Runtime::RandomGenerator> >&&, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >) /proc/self/cwd/test/integration/server.cc:221:3 (http2_integration_test+0x2e1899d)
2020-06-10T14:23:40.3832615Z     #7 Envoy::IntegrationTestServer::threadRoutine(Envoy::Network::Address::IpVersion, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >) /proc/self/cwd/test/integration/server.cc:181:3 (http2_integration_test+0x2e180e3)
2020-06-10T14:23:40.3834355Z     #8 Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0::operator()() const /proc/self/cwd/test/integration/server.cc:93:9 (http2_integration_test+0x2e1c2aa)
2020-06-10T14:23:40.3838246Z     #9 decltype(std::__1::forward<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&>(fp)()) std::__1::__invoke<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&>(Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1 (http2_integration_test+0x2e1c0e0)
2020-06-10T14:23:40.3843489Z     #10 void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&>(Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9 (http2_integration_test+0x2e1c040)
2020-06-10T14:23:40.3847325Z     #11 std::__1::__function::__alloc_func<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0, std::__1::allocator<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1533:16 (http2_integration_test+0x2e1bfe0)
2020-06-10T14:23:40.3851001Z     #12 std::__1::__function::__func<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0, std::__1::allocator<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >)::$_0>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1707:12 (http2_integration_test+0x2e1a6af)
2020-06-10T14:23:40.3853031Z     #13 std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:1860:16 (http2_integration_test+0x2ca9936)
2020-06-10T14:23:40.3853809Z     #14 std::__1::function<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:2419:12 (http2_integration_test+0x2ca95c8)
2020-06-10T14:23:40.3855246Z     #15 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/source/common/common/posix/thread_impl.cc:49:11 (http2_integration_test+0x79f283b)
2020-06-10T14:23:40.3857053Z     #16 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/source/common/common/posix/thread_impl.cc:48:9 (http2_integration_test+0x79f27c8)
2020-06-10T14:23:40.3857800Z 
2020-06-10T14:23:40.3858337Z   Previous read of size 8 at 0x0000087c1178 by thread T3:
2020-06-10T14:23:40.3859773Z     #0 Envoy::InjectableSingleton<Envoy::Runtime::Loader>::getExisting() /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/singleton/_virtual_includes/threadsafe_singleton/common/singleton/threadsafe_singleton.h:60:36 (http2_integration_test+0x2e92f1f)
2020-06-10T14:23:40.3861122Z     #1 Envoy::Runtime::getInteger(absl::string_view, unsigned long) /proc/self/cwd/source/common/runtime/runtime_features.cc:26:7 (http2_integration_test+0x5bcd09a)
2020-06-10T14:23:40.3861955Z     #2 Envoy::Buffer::WatermarkBuffer::setWatermarks(unsigned int, unsigned int) /proc/self/cwd/source/common/buffer/watermark_buffer.cc:75:7 (http2_integration_test+0x57e752f)
2020-06-10T14:23:40.3863316Z     #3 Envoy::Http::Http2::ConnectionImpl::StreamImpl::setWriteBufferWatermarks(unsigned int, unsigned int) /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/http/http2/_virtual_includes/codec_lib/common/http/http2/codec_impl.h:251:26 (http2_integration_test+0x55ee231)
2020-06-10T14:23:40.3864573Z     #4 Envoy::Http::Http2::ConnectionImpl::StreamImpl::StreamImpl(Envoy::Http::Http2::ConnectionImpl&, unsigned int) /proc/self/cwd/source/common/http/http2/codec_impl.cc:99:5 (http2_integration_test+0x55c718f)
2020-06-10T14:23:40.3866408Z     #5 Envoy::Http::Http2::ConnectionImpl::ServerStreamImpl::ServerStreamImpl(Envoy::Http::Http2::ConnectionImpl&, unsigned int) /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/http/http2/_virtual_includes/codec_lib/common/http/http2/codec_impl.h:359:11 (http2_integration_test+0x55f2bbc)
2020-06-10T14:23:40.3867555Z     #6 Envoy::Http::Http2::ServerConnectionImpl::onBeginHeaders(nghttp2_frame const*) /proc/self/cwd/source/common/http/http2/codec_impl.cc:1256:34 (http2_integration_test+0x55d708e)
2020-06-10T14:23:40.3868820Z     #7 non-virtual thunk to Envoy::Http::Http2::ServerConnectionImpl::onBeginHeaders(nghttp2_frame const*) /proc/self/cwd/source/common/http/http2/codec_impl.cc (http2_integration_test+0x55d746f)
2020-06-10T14:23:40.3869884Z     #8 Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_10::operator()(nghttp2_session*, nghttp2_frame const*, void*) const /proc/self/cwd/source/common/http/http2/codec_impl.cc:1037:57 (http2_integration_test+0x55da7cc)
2020-06-10T14:23:40.3871005Z     #9 Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_10::__invoke(nghttp2_session*, nghttp2_frame const*, void*) /proc/self/cwd/source/common/http/http2/codec_impl.cc:1036:19 (http2_integration_test+0x55da728)
2020-06-10T14:23:40.3871931Z     #10 session_call_on_begin_headers /b/f/w/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:3314:10 (http2_integration_test+0x5cdaad0)
2020-06-10T14:23:40.3872680Z     #11 nghttp2_session_on_request_headers_received /b/f/w/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:3915:8 (http2_integration_test+0x5cda63b)
2020-06-10T14:23:40.3873447Z     #12 session_process_headers_frame /b/f/w/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:4059:12 (http2_integration_test+0x5ce94a0)
2020-06-10T14:23:40.3874189Z     #13 nghttp2_session_mem_recv /b/f/w/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:5570:14 (http2_integration_test+0x5ce0df3)
2020-06-10T14:23:40.3875014Z     #14 Envoy::Http::Http2::ConnectionImpl::innerDispatch(Envoy::Buffer::Instance&) /proc/self/cwd/source/common/http/http2/codec_impl.cc:495:9 (http2_integration_test+0x55cf25f)
2020-06-10T14:23:40.3876172Z     #15 Envoy::Http::Http2::ServerConnectionImpl::innerDispatch(Envoy::Buffer::Instance&) /proc/self/cwd/source/common/http/http2/codec_impl.cc:1382:26 (http2_integration_test+0x55d9424)
2020-06-10T14:23:40.3877180Z     #16 Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23::operator()(Envoy::Buffer::Instance&) const /proc/self/cwd/source/common/http/http2/codec_impl.cc:1368:60 (http2_integration_test+0x55eb284)
2020-06-10T14:23:40.3878807Z     #17 decltype(std::__1::forward<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&>(fp)(std::__1::forward<Envoy::Buffer::Instance&>(fp0))) std::__1::__invoke<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&, Envoy::Buffer::Instance&>(Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&, Envoy::Buffer::Instance&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1 (http2_integration_test+0x55eb194)
2020-06-10T14:23:40.3880788Z     #18 absl::Status std::__1::__invoke_void_return_wrapper<absl::Status>::__call<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&, Envoy::Buffer::Instance&>(Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23&, Envoy::Buffer::Instance&) /opt/llvm/bin/../include/c++/v1/__functional_base:317:16 (http2_integration_test+0x55eb0c4)
2020-06-10T14:23:40.3882722Z     #19 std::__1::__function::__alloc_func<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23, std::__1::allocator<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23>, absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) /opt/llvm/bin/../include/c++/v1/functional:1533:16 (http2_integration_test+0x55eb034)
2020-06-10T14:23:40.3884610Z     #20 std::__1::__function::__func<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23, std::__1::allocator<Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_23>, absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) /opt/llvm/bin/../include/c++/v1/functional:1707:12 (http2_integration_test+0x55e92d3)
2020-06-10T14:23:40.3886010Z     #21 std::__1::__function::__value_func<absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) const /opt/llvm/bin/../include/c++/v1/functional:1860:16 (http2_integration_test+0x47740eb)
2020-06-10T14:23:40.3887011Z     #22 std::__1::function<absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) const /opt/llvm/bin/../include/c++/v1/functional:2419:12 (http2_integration_test+0x4773fff)
2020-06-10T14:23:40.3888485Z     #23 Envoy::Http::Utility::exceptionToStatus(std::__1::function<absl::Status (Envoy::Buffer::Instance&)>, Envoy::Buffer::Instance&) /proc/self/cwd/source/common/http/utility.cc:41:14 (http2_integration_test+0x5bce840)
2020-06-10T14:23:40.3889534Z     #24 Envoy::Http::Http2::ServerConnectionImpl::dispatch(Envoy::Buffer::Instance&) /proc/self/cwd/source/common/http/http2/codec_impl.cc:1367:10 (http2_integration_test+0x55d8ed2)
2020-06-10T14:23:40.3890490Z     #25 Envoy::FakeHttpConnection::ReadFilter::onData(Envoy::Buffer::Instance&, bool) /proc/self/cwd/./test/integration/fake_upstream.h:453:45 (http2_integration_test+0x2cffbc9)
2020-06-10T14:23:40.3891701Z     #26 Envoy::Network::FilterManagerImpl::onContinueReading(Envoy::Network::FilterManagerImpl::ActiveReadFilter*, Envoy::Network::ReadBufferSource&) /proc/self/cwd/source/common/network/filter_manager_impl.cc:66:48 (http2_integration_test+0x57e0358)
2020-06-10T14:23:40.3892676Z     #27 Envoy::Network::FilterManagerImpl::onRead() /proc/self/cwd/source/common/network/filter_manager_impl.cc:76:3 (http2_integration_test+0x57e0651)
2020-06-10T14:23:40.3893463Z     #28 Envoy::Network::ConnectionImpl::onRead(unsigned long) /proc/self/cwd/source/common/network/connection_impl.cc:297:19 (http2_integration_test+0x57b8bb2)
2020-06-10T14:23:40.3894243Z     #29 Envoy::Network::ConnectionImpl::onReadReady() /proc/self/cwd/source/common/network/connection_impl.cc:579:5 (http2_integration_test+0x57bddc0)
2020-06-10T14:23:40.3895126Z     #30 Envoy::Network::ConnectionImpl::onFileEvent(unsigned int) /proc/self/cwd/source/common/network/connection_impl.cc:539:5 (http2_integration_test+0x57bc310)
2020-06-10T14:23:40.3896559Z     #31 Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6::operator()(unsigned int) const /proc/self/cwd/source/common/network/connection_impl.cc:77:74 (http2_integration_test+0x57d2157)
2020-06-10T14:23:40.3900945Z     #32 decltype(std::__1::forward<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&>(fp)(std::__1::forward<unsigned int>(fp0))) std::__1::__invoke<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1 (http2_integration_test+0x57d209c)
2020-06-10T14:23:40.3905525Z     #33 void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9 (http2_integration_test+0x57d1fcd)
2020-06-10T14:23:40.3909945Z     #34 std::__1::__function::__alloc_func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) /opt/llvm/bin/../include/c++/v1/functional:1533:16 (http2_integration_test+0x57d1f4d)
2020-06-10T14:23:40.3914067Z     #35 std::__1::__function::__func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) /opt/llvm/bin/../include/c++/v1/functional:1707:12 (http2_integration_test+0x57d01fc)
2020-06-10T14:23:40.3916486Z     #36 std::__1::__function::__value_func<void (unsigned int)>::operator()(unsigned int&&) const /opt/llvm/bin/../include/c++/v1/functional:1860:16 (http2_integration_test+0x47a88f4)
2020-06-10T14:23:40.3917579Z     #37 std::__1::function<void (unsigned int)>::operator()(unsigned int) const /opt/llvm/bin/../include/c++/v1/functional:2419:12 (http2_integration_test+0x47a87e8)
2020-06-10T14:23:40.3918560Z     #38 Envoy::Event::FileEventImpl::assignEvents(unsigned int, event_base*)::$_0::operator()(int, short, void*) const /proc/self/cwd/source/common/event/file_event_impl.cc:66:9 (http2_integration_test+0x57a6d44)
2020-06-10T14:23:40.3919629Z     #39 Envoy::Event::FileEventImpl::assignEvents(unsigned int, event_base*)::$_0::__invoke(int, short, void*) /proc/self/cwd/source/common/event/file_event_impl.cc:50:7 (http2_integration_test+0x57a6ac6)
2020-06-10T14:23:40.3920939Z     #40 event_persist_closure /b/f/w/external/com_github_libevent_libevent/event.c:1639:9 (http2_integration_test+0x7a1a1f0)
2020-06-10T14:23:40.3921711Z     #41 event_process_active_single_queue /b/f/w/external/com_github_libevent_libevent/event.c:1698:4 (http2_integration_test+0x7a18c18)
2020-06-10T14:23:40.3922415Z     #42 event_process_active /b/f/w/external/com_github_libevent_libevent/event.c:1799:9 (http2_integration_test+0x7a0e458)
2020-06-10T14:23:40.3923062Z     #43 event_base_loop /b/f/w/external/com_github_libevent_libevent/event.c:2041:12 (http2_integration_test+0x7a0c103)
2020-06-10T14:23:40.3923827Z     #44 Envoy::Event::LibeventScheduler::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/libevent_scheduler.cc:47:3 (http2_integration_test+0x5a8e9ef)
2020-06-10T14:23:40.3924692Z     #45 Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/dispatcher_impl.cc:203:19 (http2_integration_test+0x57926a1)
2020-06-10T14:23:40.3925488Z     #46 Envoy::FakeUpstream::threadRoutine() /proc/self/cwd/test/integration/fake_upstream.cc:494:16 (http2_integration_test+0x2cc2174)
2020-06-10T14:23:40.3926834Z     #47 Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12::operator()() const /proc/self/cwd/test/integration/fake_upstream.cc:457:67 (http2_integration_test+0x2ce7a5b)
2020-06-10T14:23:40.3930919Z     #48 decltype(std::__1::forward<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&>(fp)()) std::__1::__invoke<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&>(Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1 (http2_integration_test+0x2ce79b0)
2020-06-10T14:23:40.3935319Z     #49 void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&>(Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9 (http2_integration_test+0x2ce7910)
2020-06-10T14:23:40.3939469Z     #50 std::__1::__function::__alloc_func<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12, std::__1::allocator<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1533:16 (http2_integration_test+0x2ce78b0)
2020-06-10T14:23:40.3943412Z     #51 std::__1::__function::__func<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12, std::__1::allocator<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_12>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1707:12 (http2_integration_test+0x2ce5b7f)
2020-06-10T14:23:40.3945531Z     #52 std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:1860:16 (http2_integration_test+0x2ca9936)
2020-06-10T14:23:40.3946276Z     #53 std::__1::function<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:2419:12 (http2_integration_test+0x2ca95c8)
2020-06-10T14:23:40.3948110Z     #54 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/source/common/common/posix/thread_impl.cc:49:11 (http2_integration_test+0x79f283b)
2020-06-10T14:23:40.3949902Z     #55 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/source/common/common/posix/thread_impl.cc:48:9 (http2_integration_test+0x79f27c8)
2020-06-10T14:23:40.3950943Z 
2020-06-10T14:23:40.3951763Z   Location is global 'Envoy::InjectableSingleton<Envoy::Runtime::Loader>::loader_' of size 8 at 0x0000087c1178 (http2_integration_test+0x0000087c1178)
2020-06-10T14:23:40.3952294Z 
2020-06-10T14:23:40.3952647Z   Thread T6 (tid=1263, running) created by main thread at:
2020-06-10T14:23:40.3953519Z     #0 pthread_create /tmp/final/llvm.src/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:967:3 (http2_integration_test+0x297678b)
2020-06-10T14:23:40.3954437Z     #1 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:46:20 (http2_integration_test+0x79f1267)
2020-06-10T14:23:40.3955772Z     #2 std::__1::__unique_if<Envoy::Thread::ThreadImplPosix>::__unique_single std::__1::make_unique<Envoy::Thread::ThreadImplPosix, std::__1::function<void ()>&, absl::optional<Envoy::Thread::Options> const&>(std::__1::function<void ()>&, absl::optional<Envoy::Thread::Options> const&) /opt/llvm/bin/../include/c++/v1/memory:3003:32 (http2_integration_test+0x79f0bbf)
2020-06-10T14:23:40.3957524Z     #3 Envoy::Thread::ThreadFactoryImplPosix::createThread(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:121:10 (http2_integration_test+0x79f07f3)
2020-06-10T14:23:40.3959781Z     #4 Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, bool, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >) /proc/self/cwd/test/integration/server.cc:91:28 (http2_integration_test+0x2e16c02)
2020-06-10T14:23:40.3962555Z     #5 Envoy::IntegrationTestServer::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Envoy::Network::Address::IpVersion, std::__1::function<void (Envoy::IntegrationTestServer&)>, std::__1::function<void ()>, bool, Envoy::Event::TestTimeSystem&, Envoy::Api::Api&, bool, absl::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, bool) /proc/self/cwd/test/integration/server.cc:67:11 (http2_integration_test+0x2e16671)
2020-06-10T14:23:40.3965308Z     #6 Envoy::BaseIntegrationTest::createGeneratedApiTestServer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, Envoy::Server::FieldValidationConfig, bool) /proc/self/cwd/test/integration/integration.cc:457:18 (http2_integration_test+0x2d603a3)
2020-06-10T14:23:40.3967161Z     #7 Envoy::BaseIntegrationTest::createEnvoy() /proc/self/cwd/test/integration/integration.cc:375:3 (http2_integration_test+0x2d5fed6)
2020-06-10T14:23:40.3968103Z     #8 Envoy::BaseIntegrationTest::initialize() /proc/self/cwd/test/integration/integration.cc:307:3 (http2_integration_test+0x2d5e7b6)
2020-06-10T14:23:40.3968889Z     #9 Envoy::Http2FloodMitigationTest::beginSession() /proc/self/cwd/test/integration/http2_integration_test.cc:1500:3 (http2_integration_test+0x2a163c4)
2020-06-10T14:23:40.3969755Z     #10 Envoy::Http2FloodMitigationTest_Data_Test::TestBody() /proc/self/cwd/test/integration/http2_integration_test.cc:1625:3 (http2_integration_test+0x2a18d01)
2020-06-10T14:23:40.3970991Z     #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10 (http2_integration_test+0x7b90d2c)
2020-06-10T14:23:40.3972302Z     #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14 (http2_integration_test+0x7b7542e)
2020-06-10T14:23:40.3973572Z     #13 testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2508:5 (http2_integration_test+0x7b5a511)
2020-06-10T14:23:40.3974355Z     #14 testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2684:11 (http2_integration_test+0x7b5b3b3)
2020-06-10T14:23:40.3975144Z     #15 testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2816:28 (http2_integration_test+0x7b5bdea)
2020-06-10T14:23:40.3976301Z     #16 testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5338:44 (http2_integration_test+0x7b6b58d)
2020-06-10T14:23:40.3977521Z     #17 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10 (http2_integration_test+0x7b97cdc)
2020-06-10T14:23:40.3979397Z     #18 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14 (http2_integration_test+0x7b792fe)
2020-06-10T14:23:40.3980549Z     #19 testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:4925:10 (http2_integration_test+0x7b6ae4b)
2020-06-10T14:23:40.3981619Z     #20 RUN_ALL_TESTS() /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2473:46 (http2_integration_test+0x56c3177)
2020-06-10T14:23:40.3982295Z     #21 Envoy::TestRunner::RunTests(int, char**) /proc/self/cwd/test/test_runner.cc:134:10 (http2_integration_test+0x56c24ed)
2020-06-10T14:23:40.3983253Z     #22 main /proc/self/cwd/test/main.cc:34:10 (http2_integration_test+0x56bfe91)
2020-06-10T14:23:40.3983620Z 
2020-06-10T14:23:40.3984010Z   Thread T3 (tid=1262, running) created by main thread at:
2020-06-10T14:23:40.3985032Z     #0 pthread_create /tmp/final/llvm.src/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:967:3 (http2_integration_test+0x297678b)
2020-06-10T14:23:40.3986178Z     #1 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:46:20 (http2_integration_test+0x79f1267)
2020-06-10T14:23:40.3987998Z     #2 std::__1::__unique_if<Envoy::Thread::ThreadImplPosix>::__unique_single std::__1::make_unique<Envoy::Thread::ThreadImplPosix, std::__1::function<void ()>&, absl::optional<Envoy::Thread::Options> const&>(std::__1::function<void ()>&, absl::optional<Envoy::Thread::Options> const&) /opt/llvm/bin/../include/c++/v1/memory:3003:32 (http2_integration_test+0x79f0bbf)
2020-06-10T14:23:40.3989478Z     #3 Envoy::Thread::ThreadFactoryImplPosix::createThread(std::__1::function<void ()>, absl::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:121:10 (http2_integration_test+0x79f07f3)
2020-06-10T14:23:40.3991165Z     #4 Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool) /proc/self/cwd/test/integration/fake_upstream.cc:457:35 (http2_integration_test+0x2cc04fb)
2020-06-10T14:23:40.3992953Z     #5 Envoy::FakeUpstream::FakeUpstream(std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool, bool) /proc/self/cwd/test/integration/fake_upstream.cc:420:7 (http2_integration_test+0x2cc0bfd)
2020-06-10T14:23:40.3994483Z     #6 Envoy::AutonomousUpstream::AutonomousUpstream(std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool) /proc/self/cwd/./test/integration/autonomous_upstream.h:57:9 (http2_integration_test+0x2d7f802)
2020-06-10T14:23:40.3995785Z     #7 Envoy::BaseIntegrationTest::createUpstreams() /proc/self/cwd/test/integration/integration.cc:314:40 (http2_integration_test+0x2d5f0e5)
2020-06-10T14:23:40.3996678Z     #8 Envoy::BaseIntegrationTest::initialize() /proc/self/cwd/test/integration/integration.cc:305:3 (http2_integration_test+0x2d5e781)
2020-06-10T14:23:40.3997434Z     #9 Envoy::Http2FloodMitigationTest::beginSession() /proc/self/cwd/test/integration/http2_integration_test.cc:1500:3 (http2_integration_test+0x2a163c4)
2020-06-10T14:23:40.3998491Z     #10 Envoy::Http2FloodMitigationTest_Data_Test::TestBody() /proc/self/cwd/test/integration/http2_integration_test.cc:1625:3 (http2_integration_test+0x2a18d01)
2020-06-10T14:23:40.3999543Z     #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10 (http2_integration_test+0x7b90d2c)
2020-06-10T14:23:40.4000952Z     #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14 (http2_integration_test+0x7b7542e)
2020-06-10T14:23:40.4002217Z     #13 testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2508:5 (http2_integration_test+0x7b5a511)
2020-06-10T14:23:40.4003196Z     #14 testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2684:11 (http2_integration_test+0x7b5b3b3)
2020-06-10T14:23:40.4003991Z     #15 testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2816:28 (http2_integration_test+0x7b5bdea)
2020-06-10T14:23:40.4004801Z     #16 testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5338:44 (http2_integration_test+0x7b6b58d)
2020-06-10T14:23:40.4006142Z     #17 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10 (http2_integration_test+0x7b97cdc)
2020-06-10T14:23:40.4007587Z     #18 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14 (http2_integration_test+0x7b792fe)
2020-06-10T14:23:40.4008921Z     #19 testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:4925:10 (http2_integration_test+0x7b6ae4b)
2020-06-10T14:23:40.4009692Z     #20 RUN_ALL_TESTS() /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2473:46 (http2_integration_test+0x56c3177)
2020-06-10T14:23:40.4010430Z     #21 Envoy::TestRunner::RunTests(int, char**) /proc/self/cwd/test/test_runner.cc:134:10 (http2_integration_test+0x56c24ed)
2020-06-10T14:23:40.4011222Z     #22 main /proc/self/cwd/test/main.cc:34:10 (http2_integration_test+0x56bfe91)
2020-06-10T14:23:40.4011583Z 
2020-06-10T14:23:40.4012724Z SUMMARY: ThreadSanitizer: data race /proc/self/cwd/bazel-out/k8-dbg/bin/source/common/singleton/_virtual_includes/threadsafe_singleton/common/singleton/threadsafe_singleton.h:67:33 in Envoy::InjectableSingleton<Envoy::Runtime::Loader>::clear()
2020-06-10T14:23:40.4013696Z ==================
```

### PR DESCRIPTION
**Pull request by alyssawilk**
As (now) commented, when codecs access runtime, it creates a destruction order invariant that the fake upstreams are torn down before the server (and its runtime).  Fixing this in the base integration test and cleaning up test sub-classes.

Risk Level: n/a (test only)
Testing: http2 test passes cleanly with 200 runs (where before it flaked out)
Docs Changes: n/a
Release Notes: n/a
Fixes #11538

### CODE REVIEW

File: test/integration/integration.cc [hunk 1]
```diff
@@ -282,6 +282,14 @@ BaseIntegrationTest::BaseIntegrationTest(Network::Address::IpVersion version,
           },
           version, config) {}
 
+BaseIntegrationTest::~BaseIntegrationTest() {
+  // Tear down the fake upstream before the test server.
+  // When the HTTP codecs do runtime checks, it is important to finish all
+  // runtime access before the server, and the runtime singleton, go away.
+  fake_upstreams_.clear();
```
Comment (yanavlasov) [inline test/integration/integration.cc:289]: I think you could also reverse declarations of `test_server_` and `fake_upstreams_` in the class and have C++ enforce the cleanup order. If you are into that sort of thing.

**Comment by yanavlasov** [comment]
Thanks for tracking this down.

File: test/integration/integration.cc (hunk 1 above)
Comment (alyssawilk) [reply test/integration/integration.cc:289]: Yeah, I thought about that, but I was concerned there might be other things that needed to go before the server.

I should just be non-lazy and put it at the top :-P

Comment (alyssawilk) [reply test/integration/integration.cc:289]: Actually yeah, if I move it up something else fails.
How about we land this to remove the flake and I file a tracking issue for cleaning up the tests a bit?

Comment (alyssawilk) [reply test/integration/integration.cc:289]: https://github.com/envoyproxy/envoy/issues/11553
