### PR TITLE
io_uring: skip tests if unsupported

### LINKED ISSUE #20763: io_uring tests fail on non-supported Linux kernels
*Title*: io_uring tests fail on non-supported Linux kernels

*Description*:
When running the [io_uring tests](https://github.com/envoyproxy/envoy/blob/main/test/common/io/io_uring_impl_test.cc) on a machine that doesn't support io_uring, we get the "Function not implemented" error:
```
[==========] Running 9 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 4 tests from IoUringImplTest
[ RUN      ] IoUringImplTest.Instantiate
[2022-04-08 21:15:22.667][31390][critical][assert] [source/common/io/io_uring_impl.cc:31] assert failure: ret == 0. Details: unable to initialize io_uring: Function not implemented
[2022-04-08 21:15:22.667][31390][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x3e800007a9e
[2022-04-08 21:15:22.667][31390][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2022-04-08 21:15:22.667][31390][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 0/1.22.0-dev/test/DEBUG/BoringSSL
[2022-04-08 21:15:22.702][31390][critical][backtrace] [./source/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x3d00f7c]
[2022-04-08 21:15:22.702][31390][critical][backtrace] [./source/server/backtrace.h:96] #1: __restore_rt [0x7fd089821980]
[2022-04-08 21:15:22.737][31390][critical][backtrace] [./source/server/backtrace.h:96] #2: std::__1::__shared_ptr_emplace<>::__shared_ptr_emplace<>() [0x1e3e2f5]
[2022-04-08 21:15:22.771][31390][critical][backtrace] [./source/server/backtrace.h:96] #3: std::__1::allocate_shared<>() [0x1e3e116]
[2022-04-08 21:15:22.806][31390][critical][backtrace] [./source/server/backtrace.h:96] #4: std::__1::make_shared<>() [0x1e3e092]
[2022-04-08 21:15:22.840][31390][critical][backtrace] [./source/server/backtrace.h:96] #5: Envoy::Io::IoUringFactoryImpl::onServerInitialized()::$_0::operator()() [0x1e39f7e]
[2022-04-08 21:15:22.875][31390][critical][backtrace] [./source/server/backtrace.h:96] #6: std::__1::__invoke<>() [0x1e39f35]
[2022-04-08 21:15:22.910][31390][critical][backtrace] [./source/server/backtrace.h:96] #7: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x1e39ec5]
[2022-04-08 21:15:22.944][31390][critical][backtrace] [./source/server/backtrace.h:96] #8: std::__1::__function::__alloc_func<>::operator()() [0x1e39e75]
[2022-04-08 21:15:22.979][31390][critical][backtrace] [./source/server/backtrace.h:96] #9: std::__1::__function::__func<>::operator()() [0x1e38f94]
[2022-04-08 21:15:23.014][31390][critical][backtrace] [./source/server/backtrace.h:96] #10: std::__1::__function::__value_func<>::operator()() [0x1e3df0d]
[2022-04-08 21:15:23.048][31390][critical][backtrace] [./source/server/backtrace.h:96] #11: std::__1::function<>::operator()() [0x1e3dea0]
[2022-04-08 21:15:23.084][31390][critical][backtrace] [./source/server/backtrace.h:96] #12: std::__1::__invoke<>() [0x1e3dd95]
[2022-04-08 21:15:23.118][31390][critical][backtrace] [./source/server/backtrace.h:96] #13: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x1e3dcf5]
[2022-04-08 21:15:23.153][31390][critical][backtrace] [./source/server/backtrace.h:96] #14: std::__1::__function::__alloc_func<>::operator()() [0x1e3dc95]
[2022-04-08 21:15:23.188][31390][critical][backtrace] [./source/server/backtrace.h:96] #15: std::__1::__function::__func<>::operator()() [0x1e3cdd4]
[2022-04-08 21:15:23.223][31390][critical][backtrace] [./source/server/backtrace.h:96] #16: std::__1::__function::__value_func<>::operator()() [0x20d1bad]
[2022-04-08 21:15:23.258][31390][critical][backtrace] [./source/server/backtrace.h:96] #17: std::__1::function<>::operator()() [0x20d1720]
[2022-04-08 21:15:23.294][31390][critical][backtrace] [./source/server/backtrace.h:96] #18: Envoy::ThreadLocal::MockInstance::SlotImpl::set() [0x20ce083]
[2022-04-08 21:15:23.329][31390][critical][backtrace] [./source/server/backtrace.h:96] #19: Envoy::ThreadLocal::TypedSlot<>::set() [0x1e3a126]
[2022-04-08 21:15:23.364][31390][critical][backtrace] [./source/server/backtrace.h:96] #20: Envoy::Io::IoUringFactoryImpl::onServerInitialized() [0x1e35ce5]
[2022-04-08 21:15:23.398][31390][critical][backtrace] [./source/server/backtrace.h:96] #21: Envoy::Io::(anonymous namespace)::IoUringBaseTest::IoUringBaseTest() [0x1dc201e]
[2022-04-08 21:15:23.433][31390][critical][backtrace] [./source/server/backtrace.h:96] #22: Envoy::Io::(anonymous namespace)::IoUringImplTest::IoUringImplTest() [0x1dc4ee9]
[2022-04-08 21:15:23.468][31390][critical][backtrace] [./source/server/backtrace.h:96] #23: Envoy::Io::(anonymous namespace)::IoUringImplTest_Instantiate_Test::IoUringImplTest_Instantiate_Test() [0x1dc4ea9]
[2022-04-08 21:15:23.502][31390][critical][backtrace] [./source/server/backtrace.h:96] #24: testing::internal::TestFactoryImpl<>::CreateTest() [0x1dc4e5c]
[2022-04-08 21:15:23.537][31390][critical][backtrace] [./source/server/backtrace.h:96] #25: testing::internal::HandleSehExceptionsInMethodIfSupported<>() [0x4ddf9fb]
[2022-04-08 21:15:23.573][31390][critical][backtrace] [./source/server/backtrace.h:96] #26: testing::internal::HandleExceptionsInMethodIfSupported<>() [0x4dcf89a]
[2022-04-08 21:15:23.608][31390][critical][backtrace] [./source/server/backtrace.h:96] #27: testing::TestInfo::Run() [0x4dbb44d]
[2022-04-08 21:15:23.791][31390][critical][backtrace] [./source/server/backtrace.h:96] #28: testing::TestSuite::Run() [0x4dbbbbb]
[2022-04-08 21:15:23.826][31390][critical][backtrace] [./source/server/backtrace.h:96] #29: testing::internal::UnitTestImpl::RunAllTests() [0x4dc7edd]
[2022-04-08 21:15:23.862][31390][critical][backtrace] [./source/server/backtrace.h:96] #30: testing::internal::HandleSehExceptionsInMethodIfSupported<>() [0x4de300b]
[2022-04-08 21:15:23.897][31390][critical][backtrace] [./source/server/backtrace.h:96] #31: testing::internal::HandleExceptionsInMethodIfSupported<>() [0x4dd147a]
[2022-04-08 21:15:23.932][31390][critical][backtrace] [./source/server/backtrace.h:96] #32: testing::UnitTest::Run() [0x4dc7a9e]
[2022-04-08 21:15:23.967][31390][critical][backtrace] [./source/server/backtrace.h:96] #33: RUN_ALL_TESTS() [0x392bcd1]
[2022-04-08 21:15:24.001][31390][critical][backtrace] [./source/server/backtrace.h:96] #34: Envoy::TestRunner::RunTests() [0x392b4e5]
[2022-04-08 21:15:24.036][31390][critical][backtrace] [./source/server/backtrace.h:96] #35: main [0x39287f4]
[2022-04-08 21:15:24.036][31390][critical][backtrace] [./source/server/backtrace.h:96] #36: __libc_start_main [0x7fd08943fc87]
```

The io_uring lib should not be used if io_uring isn't supported, and the test should not be executed or pass.

Related PR: #19339.

### PR DESCRIPTION
**Pull request by rojkov**
Commit Message: io_uring: skip tests if unsupported

Risk Level: low
Testing: run unittests on machines where io_uring supported and not (MS WSL).
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: no features added
Fixes #20763

### CODE REVIEW

**Review by yanavlasov — DISMISSED** [review]

**Comment by yanavlasov** [comment]
I recall this these tests were failing in CI. How was it resolved?

File: source/common/io/io_uring_impl.cc [hunk 1]
```diff
@@ -5,6 +5,18 @@
 namespace Envoy {
 namespace Io {
 
+bool isIoUringSupported() {
+  struct io_uring_params p {};
+  struct io_uring ring;
+
+  bool is_supported = io_uring_queue_init_params(2, &ring, &p) == 0;
```
Comment (adisuissa) [inline source/common/io/io_uring_impl.cc:12]: Read the  [code](https://github.com/axboe/liburing/blob/8695f66bccda2170d8af2f99d3c1b8c6ee8bf602/src/setup.c#L132), and I agree that 0 is the valid result of the function.

Should we use the setup syscall directly or some alternative way to validate io_uring support?

File: test/common/io/io_uring_impl_test.cc [hunk 2]
```diff
@@ -12,20 +12,36 @@ namespace {
...
+      factory_ = std::make_unique<IoUringFactoryImpl>(2, false, context_.threadLocal());
+      factory_->onServerInitialized();
+    } else {
+      should_skip_ = true;
+    }
+  }
+
+  void SetUp() override {
+    if (should_skip_) {
+      GTEST_SKIP();
```
Comment (adisuissa) [inline test/common/io/io_uring_impl_test.cc:26]: Thinking out loud here, is there a way to ensure that CI does not skip these tests? (I realize that CI images support io_uring, but lets say some accidental change removes that support).
This will ensure that the code is checked at least in CI.

**Review by adisuissa — COMMENTED** [review]
Thanks for fixing this. Left a couple of questions.

**Comment by rojkov** [comment]
> I recall this these tests were failing in CI. How was it resolved?

They failed because RBE had io_uring disabled explicitly while supporting it (the return code was EPERM). Now it's enabled.

File: source/common/io/io_uring_impl.cc (hunk 1 above)
Comment (rojkov) [reply source/common/io/io_uring_impl.cc:12]: The syscall number for io_uring_setup may differ for different archs and libc may lack correct wrappers. I'd rather let liburing handle these subtleties.

File: test/common/io/io_uring_impl_test.cc (hunk 2 above)
Comment (rojkov) [reply test/common/io/io_uring_impl_test.cc:26]: Good point! I've added `source/common/io` to `test/per_file_coverage.sh`. So, skipped tests should be detected in the coverage task.

**Review by yanavlasov — APPROVED** [review]

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
