### PR TITLE
fix memory leaking in dfp

### LINKED ISSUE #30999: Memory leak in dynamic forward proxy mode w/ DNS Cache
*Description*:
We have an envoy in a dynamic forward proxy mode.  It usually behaves well, but sometimes it gets into a state where it tries to allocate 10s MiB/s and eventually gets OOM'ed:
Screenshot 2023-11-21 at 11 22 01 AM

Full heap profiles show that most of the memory is inside `DnsCacheImpl` (it should be limited to 10000 entries in theory though).

>  As a side note, I've also noticed that envoy tries to resolve internal search paths (`*.svc.cluster.local.`), even though `no_default_search_domain` is set to true.

*Heap dumps*
Diff heap profile:
profile001

Raw profiles:
https://gist.github.com/rbtz-openai/13d35aea14013f12273c6aa7478184cb

*Admin and Stats Output*:
```
 "version": "b5ca88acee3453c9459474b8f22215796eff4dde/1.28.0/Clean/RELEASE/BoringSSL",
```

There are a lot of cluster due to dynamic forward proxy mode:
```
# curl -s localhost:XXX/clusters | fgrep -c hostname
6752
```

```
$ curl -s localhost:XXX/stats/prometheus | fgrep dns
# TYPE envoy_dns_cares_get_addr_failure counter
envoy_dns_cares_get_addr_failure{} 310
# TYPE envoy_dns_cares_not_found counter
envoy_dns_cares_not_found{} 178
# TYPE envoy_dns_cares_resolve_total counter
envoy_dns_cares_resolve_total{} 186188
# TYPE envoy_dns_cares_timeouts counter
envoy_dns_cares_timeouts{} 32
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_cache_load counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_cache_load{} 0
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_attempt counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_attempt{} 184881
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_failure counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_failure{} 667
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_success counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_success{} 184213
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_timeout counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_timeout{} 365
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_rq_pending_overflow counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_rq_pending_overflow{} 0
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_host_added counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_host_added{} 33253
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_host_address_changed counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_host_address_changed{} 90554
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_host_overflow counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_host_overflow{} 0
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_host_removed counter
envoy_dns_cache_dynamic_forward_proxy_cache_config_host_removed{} 26501
# TYPE envoy_dns_cares_pending_resolutions gauge
envoy_dns_cares_pending_resolutions{} 1
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_circuit_breakers_rq_pending_open gauge
envoy_dns_cache_dynamic_forward_proxy_cache_config_circuit_breakers_rq_pending_open{} 0
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_circuit_breakers_rq_pending_remaining gauge
envoy_dns_cache_dynamic_forward_proxy_cache_config_circuit_breakers_rq_pending_remaining{} 1024
# TYPE envoy_dns_cache_dynamic_forward_proxy_cache_config_num_hosts gauge
envoy_dns_cache_dynamic_forward_proxy_cache_config_num_hosts{} 6752
```

*Config*:

The interesting part of the config is the dynamic forward proxy with DNS Cache (same configuration in `http_filters`)
```
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          max_hosts: 10000
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
                - socket_address:
                    address: 8.8.8.8
                    port_value: 53
                - socket_address:
                    address: 1.1.1.1
                    port_value: 53
                - socket_address:
                    address: 8.8.4.4
                    port_value: 53
                - socket_address:
                    address: 1.0.0.1
                    port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: true
                # There is no need to use the default search domain when resolving external requests
                no_default_search_domain: true
```

cc: @alyssawilk @euroelessar

### PR DESCRIPTION
**Pull request by doujiang24**
Commit Message:
fix #30999

1. when host is resolved to IP A, A will be added into `mutable_cross_priority_host_map_`
2. when host is resolved to IP B, the address saved in `logical_host_` will be updated to IP B.
3. when host is TTL expired, only IP B will be removed in `mutable_cross_priority_host_map_`, IP A is leaking in `mutable_cross_priority_host_map_`.

this PR do fix the leaking issue, but I'm not sure if it is a proper fix.

Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by adisuissa** [comment]
Assigning Alyssa as codeowner
/assign @alyssawilk

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc [hunk 1]
```diff
@@ -237,9 +233,9 @@ bool Cluster::ClusterInfo::checkIdle() {
 
 void Cluster::addOrUpdateHost(
     absl::string_view host,
-    const Extensions::Common::DynamicForwardProxy::DnsHostInfoSharedPtr& host_info,
-    std::unique_ptr<Upstream::HostVector>& hosts_added) {
+    const Extensions::Common::DynamicForwardProxy::DnsHostInfoSharedPtr& host_info) {
   Upstream::LogicalHostSharedPtr emplaced_host;
+  bool founded = false;
```
Comment (alyssawilk) [inline source/extensions/clusters/dynamic_forward_proxy/cluster.cc:238]: host_found?

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc [hunk 2]
```diff
@@ -270,41 +266,42 @@ void Cluster::addOrUpdateHost(
...
+
+  if (founded) {
+    // removing host from priorityState first, with the old address.
+    updatePriorityState({}, hosts);
+    ENVOY_LOG(debug, "updating dfproxy cluster host address '{}'", host);
+    emplaced_host->setNewAddresses(host_info->address(), host_info->addressList(),
+                                   dummy_lb_endpoint_);
+    // will add host into priorityState again, with the new address.
+  }
+  updatePriorityState(hosts, {});
```
Comment (alyssawilk) [inline source/extensions/clusters/dynamic_forward_proxy/cluster.cc:297]: do we actually need to do the add/remove here?  I don't think we really use priority for DFP, and the address update grabs a lock and updates (I think) globally so I'm not sure if the update is necessary.  strict DNS appears to simply do the priority update on host addition and skip on resolution change.   
One nice way to test e2e would be to do an e2e test where we start with a bad resolved IP via cache and a short DNS refresh timeout, and verify that the update makes it to the worker threads (crib off of test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc tests for cache files)

File: source/common/upstream/upstream_impl.cc [hunk 3]
```diff
@@ -831,14 +833,18 @@ void MainPrioritySetImpl::updateCrossPriorityHostMap(const HostVector& hosts_add
...
   }
 
   for (const auto& host : hosts_removed) {
     mutable_cross_priority_host_map_->erase(addressToString(host->address()));
+    ENVOY_LOG(debug, "cross_priority host map, removing: {}", addressToString(host->address()));
   }
 
   for (const auto& host : hosts_added) {
     mutable_cross_priority_host_map_->insert({addressToString(host->address()), host});
+    ENVOY_LOG(debug, "cross_priority host map, adding: {}", addressToString(host->address()));
```
Comment (yanjunxiang-google) [inline source/common/upstream/upstream_impl.cc:847]: Based on your problem description, it looks like the problem is that when the host is initially resolved into IP_A, IP_A is inserted into the mutable_cross_priority_host_map_ here. And later on if the host is resolved into IP_B, then IP_B is inserted here. However, the above  (Line 841) mutable_cross_priority_host_map_->erase(addressToString(host->address())) for IP_A is somehow not called.

Intuitively, I would think when the DNS resolving returns a different address, MainPrioritySetImpl::updateCrossPriorityHostMap() will be called with both host_added and host_removed set.  But, it looks like host_removed is empty here. Could you please share which code path is causing that?

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 1 above)
Comment (doujiang24) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:238]: okay, will fix it later :)

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 2 above)
Comment (doujiang24) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:297]: > I don't think we really use priority for DFP

yep, I do think so too. can we remove the priority entirely? if yes, it would be much simpler.

> do we actually need to do the add/remove here

yes, I do think so, we have to keep tracking the correct address in priority, otherwise,
when host is TTL expired, the old(before change) address will leaking in priority.

> One nice way to test e2e would be to do an e2e test

okay, I will have a try later, after we figure out the proper way to fix it.

Comment (doujiang24) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:297]: the different between logical DNS and strict DNS is that - strict DNS could remove all of the IPs from priority, but logic DNS could not.
since there is only the latest IP in logic DNS when removing the expired host:
https://github.com/envoyproxy/envoy/blob/7a9543d2813e8041a69bba708cdc3c542e0ec8f5/source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc#L268

File: source/common/upstream/upstream_impl.cc (hunk 3 above)
Comment (doujiang24) [reply source/common/upstream/upstream_impl.cc:847]: > Based on your problem description, it looks like the problem is that when the host is initially resolved into IP_A, IP_A is inserted into the mutable_cross_priority_host_map_ here. And later on if the host is resolved into IP_B, then IP_B is inserted here. However, the above (Line 841) mutable_cross_priority_host_map_->erase(addressToString(host->address())) for IP_A is somehow not called.

yep, that's it.

> 
> Intuitively, I would think when the DNS resolving returns a different address, MainPrioritySetImpl::updateCrossPriorityHostMap() will be called with both host_added and host_removed set. But, it looks like host_removed is empty here. Could you please share which code path is causing that?

Nope, in the old implementation, it simply do the priority update on host addition and skip on host subtraction, similar to strict DNS, as @alyssawilk said.
And I think that't the problem.
since it only remove the latest IP in logic DNS when removing an expired host:
https://github.com/envoyproxy/envoy/blob/7a9543d2813e8041a69bba708cdc3c542e0ec8f5/source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc#L268

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 2 above)
Comment (zuercher) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:297]: I worry a little about the double-call to `updatePriorityState` -- I think it means theres's a brief period with no host in the priority set. Perhaps that's ok. 

An alternative might be to check for the existing host but always create a new one for the updated IP and then make a single call to `updatePriorityState` with the new/old host.

Comment (alyssawilk) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:297]: yeah if it's not super complicated it'd be nice to fix updatePriortySet properly so it handles a remove/add of a single host.

Comment (doujiang24) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc]: okay, already updated to a single call to `updatePriorityState`.

Comment (alyssawilk) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc]: @zuercher can you do first pass here?  I didn't expect the single call to  updatePriorityState to require an add/remove of host instead of updateAddress and I'm not really sure which is better

**Comment by phlax** [comment]
the mobile (compile-time-options) job is passing - there was a ci glitch (since fixed) that meant it didnt always complete

**Comment by alyssawilk** [comment]
ping @zuercher

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 2 above)
Comment (alyssawilk) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc]: hm, not sure what happened to @zuercher on this review, but I'm wondering if it's possible to do an update while not replacing the host, still doing the address resolution change option
/wait-any

**Review by zuercher — APPROVED** [review]
I think this seems reasonable. I suppose the old version had an efficiency when many hosts were added or removed at once. If that's a concern we could lift the loop in startPreInit to happen under lock.

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 2 above)
Comment (doujiang24) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc]: Oh, nope, seems hard to reach it, it needs two `logicalHost`, sine we want a single call to `updatePriorityState`

**Comment by doujiang24** [comment]
Thanks @zuercher 
> If that's a concern

I think it might be fine, since it only happens while cluster initize, means low rate usually.

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc [hunk 4]
```diff
@@ -267,44 +264,31 @@ void Cluster::addOrUpdateHost(
...
+    hosts_added.emplace_back(new_host);
   }
 
-  ASSERT(emplaced_host);
-  if (hosts_added == nullptr) {
-    hosts_added = std::make_unique<Upstream::HostVector>();
-  }
-  hosts_added->emplace_back(emplaced_host);
+  ASSERT(hosts_added.size() > 0);
+  updatePriorityState(hosts_added, hosts_removed);
```
Comment (alyssawilk) [inline source/extensions/clusters/dynamic_forward_proxy/cluster.cc:284]: Actually looking through this code belatedly, doesn't updatePriorityState cause updateHosts cause drainOrCloseConnPools(host, ConnectionPool::DrainBehavior::DrainAndDelete) on the "old host"?  I think this could be a pretty bad latency hit where we want to lame-duck drain rather than force-remove drain.

Comment (doujiang24) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:284]: Oh, I see the problem.
But, I think it might be reasonable to force-remove drain.
When dns resolve result changes, force-remove drain the `old host` should be expected?

The root cause is the dfp cluster use logical DNS mode instead of strict dns mode, it may lead to host change even when dns resolve result not changes.

I haven't found a simple solution yet.
Maybe we can recommend people to use the new [sub_cluster_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/dynamic_forward_proxy/v3/dynamic_forward_proxy.proto#envoy-v3-api-field-extensions-filters-http-dynamic-forward-proxy-v3-filterconfig-sub-cluster-config)?
Or, any suggestions?

Comment (alyssawilk) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:284]: DrainExistingConnections would maybe be OK, but DrainAndDelete is too aggressive IMO as it will force-close connections.

Either way I'm thinking we should probably roll this back as I don't think the prior leak had caused many problems in production and (I think) this ended up being an unexpected non-flag-guarded behavioral change.

I am also OK writing a test to verify if this resulted in the behavioral change I think it did before we go that route but  @yanavlasov @ggreenway for their thoughts.

Comment (doujiang24) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:284]: This bug is first reported in #30999, and it leads to a large leak, according to the profile data.
But, according @rbtz-openai's update, brotli decompression is the root cause for the large leak.
I also agree that it just leaking in extremely case, with very low rate.
Revert this patch might be a proper choice, since it's hard to keep the old behaviour to fix this extremely low rate leak.
Maybe @rbtz-openai could reconfirm that this dfp leak could be ignored in your production case?

For "DrainAndDelete will force-close connections":
After reading the comments of DrainExistingConnections/DrainAndDelete, and the code of drainConnections(drain_behavior), I didn't find force-close connections.
I think I missed it somewhere. Would you please give a guideline? i.e. some keywords of the code.
Thanks very much~

Comment (alyssawilk) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:284]: Yeah so I added tests (https://github.com/envoyproxy/envoy/pull/32710) and while I'm not sure why (having looked at the code) we're not force-closing, it does appear we're not force closing. I'll do a little more investigation before pushing for rollback.  Thanks for looking into this as well!

File: source/common/upstream/upstream_impl.cc (hunk 3 above)
Comment (alyssawilk) [reply source/common/upstream/upstream_impl.cc:855]: really I don't think having an IP based host map makes sense for DFP hosts, as we can have many "unique" hosts refered to by the same address.  Pinging @wbpcode for thoughts - if it still lived in the LB classes I'd nix it for the DFP cluster but that's not an easy option nowadays.

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 4 above)
Comment (alyssawilk) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:284]: Ah ok, figured out what's wrong with my test.

OK so this PR both did fix the memory leak described, but also result in a functional change to connection lifetimes.

By the Envoy change guidelines I think it should not have landed without flag protection (because data plane change).  The particular change is problematic for Envoy Mobile.  Given the memory leak is long standing and hadn't been largely I'm inclined to roll back to prior (buggy) state than keep this (also buggy for E-M) state.  We could also flag guard the change if there's anyone who wants the memory leak fix and doesn't mind the connectivity change?

cc @yanavlasov @RyanTheOptimist for second opinions.

for context, this fixes the leak in the mutable_cross_priority_host_map_  as described but does so by updating the host in worker threads, which results in an (new, undesirable for E-M) connection pool drain and fresh non-warmed-CWND connection being used for subsequent streams.

Ideally we'd have a solution which handled both but until we have a solution the question is which bug to prefer. I'm inclined to stick with the old one but would also be amenable into making it a flag-guarded "behavioral change + fix".  Unclear if the correct behavior for a server is to drain on DNS refresh - it does do a better job of respecting DNS TTL but can also result in a lot of connection churn and suboptimal bandwidth.

Comment (RyanTheOptimist) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:284]: Yeah, I agree with @alyssawilk that since this included a non-flag protected behavior change (especially since it broke mobile), we should roll this back. We can go ahead and roll forward with flag protection, of course, but we should return to a stable state first, I think.

Comment (doujiang24) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:284]: okay, I see. Rolling back does make sense. If someone really need this fix, we could create a new PR with a flag guard.
