### PR TITLE
http: don't close TCP connection when response body is empty and request is retried

### LINKED ISSUE #5023: TCP connection is closed when HTTP upstream returns a 503 & retries are enabled
*Title*: TCP connection is closed when HTTP upstream returns a 503

*Description*:

When a HTTP upstream returns a 503 *and* retries are enabled, Envoy closes the TCP connection to the upstream (with a `FIN` packet). This is really confusing because it *doesn't* happen when retries are disabled, which makes me think that it may be a bug in Envoy.

This is similar to https://github.com/envoyproxy/envoy/issues/5022 but it's different enough (a `FIN`, not a `RST`, and the behavior depends on the HTTP headers sent) that I decided to open a separate issue.

*Repro steps*:

To start Envoy & the upstream server:

```
git clone https://gist.github.com/julia-stripe/41fdc36f96b33c1e0e1708376fb7540d
cd 41fdc36f96b33c1e0e1708376fb7540d
ruby ./server.rb # start a server that always returns 503s
envoy -c ./envoy-config.yaml  --service-cluster test --service-node test
```

To cause the connection to be closed after each request:

```
curl localhost:8190 -i -H "x-envoy-retry-on: 5xx" -H "x-envoy-max-retries: 1"
```

To make a similar request that *doesn't result in the connection being closed:

```
curl localhost:8190 -i
```

*tcpdump*

* [tcpdump-503s.pcap](https://gist.github.com/julia-stripe/41fdc36f96b33c1e0e1708376fb7540d/raw/5b574fe26d9f7cd29139f53bcdf711870c4af5e7/tcpdump-503s.pcap). Note that every connection is closed almost immediately by Envoy after the response is received. 
* [tcpdump-503s-no-retry.pcap](https://gist.github.com/julia-stripe/41fdc36f96b33c1e0e1708376fb7540d/raw/5b574fe26d9f7cd29139f53bcdf711870c4af5e7/tcpdump-503s-no-retry.pcap). Note that in this packet capture almost all of the requests happen over the same TCP connection.

The only difference between these two packet captures is retry HTTP headers -- they're running with exactly the same Envoy configuration & server.

*Admin and Stats Output*:

In this gist:

https://gist.github.com/julia-stripe/ced04325aa7ce299a2304f7374b236c0

*Config*:

https://gist.githubusercontent.com/julia-stripe/41fdc36f96b33c1e0e1708376fb7540d/raw/5b574fe26d9f7cd29139f53bcdf711870c4af5e7/envoy-config.yaml

### PR DESCRIPTION
**Pull request by julia-stripe**
*Description*:

This fixes the issue described in #5023: right now we set `end_stream=false` for many HTTP/1 responses even if the HTTP body is empty (and the stream has ended). Retried requests with `end_stream=false` close the connection, so this results in the TCP connection being closed in many cases where it could be kept open, which results in unnecessary connection churn. 

With this change, when an upstream returns a HTTP/1 response with an empty body and the request is retried, the TCP connection will no longer be closed.

*Risk Level*:

Low

*Testing*:

Did manual testing to see that the connection is no longer closed when an upstream returns a 503, and added a unit test to ensure that `end_stream` is set correctly.

*Release note*

When a HTTP/1 request is retried due to a 5xx/499 response, we now keep the TCP connection open instead of closing it

Fixes #5023

### CODE REVIEW

**Comment by julia-stripe** [comment]
The CI issue was that the code was marking the stream as ended for `101 Switching Protocols` responses, which is incorrect. I changed it to only mark the stream as ended if the content length is 0 and the status is a 4xx/5xx.

File: source/common/http/http1/codec_impl.cc [hunk 1]
```diff
@@ -669,7 +669,8 @@ ClientConnectionImpl::ClientConnectionImpl(Network::Connection& connection, Conn
 
 bool ClientConnectionImpl::cannotHaveBody() {
   if ((!pending_responses_.empty() && pending_responses_.front().head_request_) ||
-      parser_.status_code == 204 || parser_.status_code == 304) {
+      parser_.status_code == 204 || parser_.status_code == 304 ||
+      (parser_.status_code >= 400 && parser_.content_length == 0)) {
```
Comment (mattklein123) [inline source/common/http/http1/codec_impl.cc]: I don't think this is correct. For example, this should apply to 200: https://tools.ietf.org/html/rfc7230#section-3.3. I would need to look into all the code in more detail, but I think 1xx should never have body (though not end_stream), but I think You might just be able to do >= 200 && parser_.content_length == 0.

Comment (mattklein123) [reply source/common/http/http1/codec_impl.cc]: Nevermind, just reread https://tools.ietf.org/html/rfc7230#section-3.3.2. I think you want to keep 204 and 304 as always no body, but then also >= 200 && content_length == 0. If you could read the RFC in this area and check me on this that would be great. :)

Comment (mattklein123) [reply source/common/http/http1/codec_impl.cc]: Ah I see that is what you did. Great, thanks!

File: test/common/http/http1/codec_impl_test.cc [hunk 2]
```diff
@@ -700,6 +700,19 @@ TEST_F(Http1ClientConnectionImplTest, PrematureResponse) {
   EXPECT_THROW(codec_->dispatch(response), PrematureResponseException);
 }
 
+TEST_F(Http1ClientConnectionImplTest, EmptyBodyResponse) {
```
Comment (mattklein123) [inline test/common/http/http1/codec_impl_test.cc]: We already have a test that covers 1xx, but can you add a test for maybe 200 with content_length zero also?

**Comment by mattklein123** [comment]
SGTM re: release note. @julia-stripe do you mind adding one?

**Comment by julia-stripe** [comment]
added a note!

File: docs/root/intro/version_history.rst [hunk 3]
```diff
@@ -23,6 +23,8 @@ Version history
   See `#3611 <https://github.com/envoyproxy/envoy/issues/3611>`_ for details.
 * http: augmented the `sendLocalReply` filter API to accept an optional `GrpcStatus`
   value to override the default HTTP to gRPC status mapping.
+* http: no longer close the TCP connection when a HTTP/1 request is retried due
+  to a 5xx/499 response with empty body.
```
Comment (alyssawilk) [inline docs/root/intro/version_history.rst]: really small nit:
due  to a 5xx/499 response with empty body. -> due to a response with empty body.
since we cover a few other cases?  Otherwise LGTM!

Comment (julia-stripe) [reply docs/root/intro/version_history.rst]: oh, I see, it does! TIL `x-envoy-retriable-status-codes`

**Comment by julia-stripe** [comment]
rebased because it said there was a merge conflict

File: docs/root/intro/version_history.rst [hunk 4]
```diff
@@ -26,6 +26,8 @@ Version history
 * http: augmented the `sendLocalReply` filter API to accept an optional `GrpcStatus`
   value to override the default HTTP to gRPC status mapping.
 * load balancer: added a `configuration <envoy_api_msg_Cluster.LeastRequestLbConfig>` option to specify the number of choices made in P2C.
+* http: no longer close the TCP connection when a HTTP/1 request is retried due
```
Comment (mattklein123) [inline docs/root/intro/version_history.rst]: nit: sorry, can you alpha order this
