### PR TITLE
lds: continue listener creation even after failures in between

### LINKED ISSUE #6010: Continue with Listener creation even if one listener in the list fails
This is similar to what has been done for CDS here https://github.com/envoyproxy/envoy/pull/5806 but for LDS. If a listener fails for some reason, we would stop the listener creation and throw exception, half of the listeners would have been created by that time. I think it makes sense to continue with other listeners in the list.

Thoughts?

### PR DESCRIPTION
**Pull request by ramaraochavali**
*Description*: Continues listener creation even after listener creation fails for one of the listeners.
*Risk Level*: Low
*Testing*: Added automated tests
*Docs Changes*: N/A
*Release Notes*: N/A
Fixes #6010

### CODE REVIEW

**Comment by mattklein123** [comment]
> Should this behavior be enabled via configuration? Some users may prefer the fail-fast approach.

We opted out of a config option for the CDS variant of this change (see that PR for discussion), so we should be consistent here.

File: source/server/lds_api.cc [hunk 1]
```diff
@@ -75,13 +76,16 @@ void LdsApiImpl::onConfigUpdate(const ResourceVector& resources, const std::stri
...
-          fmt::format("Error adding/updating listener {}: {}", listener_name, e.what()));
+      exception_msgs.push_back(fmt::format("{}: {}", listener_name, e.what()));
     }
   }
 
   version_info_ = version_info;
   runInitializeCallbackIfAny();
+  if (!exception_msgs.empty()) {
+    throw EnvoyException(fmt::format("Error adding/updating listener(s) {}",
+                                     StringUtil::join(exception_msgs, ", ")));
```
Comment (htuch) [inline source/server/lds_api.cc]: Why do we join with `, ` here and https://github.com/envoyproxy/envoy/pull/5806/files does `\n` for CDS? Ideally they look and behave as close to eah other as possible.

FWIW, this also relates to https://github.com/envoyproxy/envoy/issues/6026.

File: test/server/lds_api_test.cc [hunk 2]
```diff
@@ -180,9 +190,41 @@ TEST_F(LdsApiTest, MisconfiguredListenerNameIsPresentInException) {
...
+      .WillOnce(Throw(EnvoyException("something is wrong")))
+      .WillOnce(Return(true))
+      .WillOnce(Throw(EnvoyException("something else is wrong")));
+
+  EXPECT_CALL(init_.initialized_, ready());
 
   EXPECT_THROW_WITH_MESSAGE(lds_->onConfigUpdate(listeners, ""), EnvoyException,
-                            "Error adding/updating listener invalid-listener: something is wrong");
+                            "Error adding/updating listener(s) invalid-listener-1: something is "
+                            "wrong, invalid-listener-2: something else is wrong");
```
Comment (htuch) [inline test/server/lds_api_test.cc]: Can we have similar behavioral coverage to https://github.com/envoyproxy/envoy/pull/5806/files?

File: source/server/lds_api.cc [hunk 3]
```diff
@@ -75,13 +76,16 @@ void LdsApiImpl::onConfigUpdate(const ResourceVector& resources, const std::stri
         ENVOY_LOG(debug, "lds: add/update listener '{}' skipped", listener_name);
       }
     } catch (const EnvoyException& e) {
-      throw EnvoyException(
-          fmt::format("Error adding/updating listener {}: {}", listener_name, e.what()));
+      exception_msgs.push_back(fmt::format("{}: {}", listener_name, e.what()));
```
Comment (htuch) [inline source/server/lds_api.cc]: This doesn't capture the duplicate listener case above, do we also want to support continuation for that?

File: source/server/lds_api.cc (hunk 1 above)
Comment (ramaraochavali) [reply source/server/lds_api.cc]: I thought comma separated is more concise rather than a `\n`. I was actually thinking of changing CDS to to be like this once this is merged. But if you think I can change this to `\n` - not a strong preference. Also CDS is not adding the line `Error adding/updating cluster(s)` which I think we should add.

File: source/server/lds_api.cc (hunk 3 above)
Comment (ramaraochavali) [reply source/server/lds_api.cc]: This I tried to make it consistent with how CDS behaves. If there are duplicates it just rejects the message with out adding any cluster - which I think may be OK.

File: test/server/lds_api_test.cc (hunk 2 above)
Comment (ramaraochavali) [reply test/server/lds_api_test.cc]: Sorry. I did n't get it. which specific test case you are talking about ?

Comment (ramaraochavali) [reply test/server/lds_api_test.cc]: I could only one additional empty update test - that I have added now if that  is what you are referring to. Otherwise LMK, will add.

File: source/server/lds_api.cc (hunk 1 above)
Comment (ramaraochavali) [reply source/server/lds_api.cc]: @htuch found another problem with CDS implementation - it does not include the cluster name, it is difficult to find which cluster is the problematic one. Fixed and changed it also to use the same `,` separated join in https://github.com/envoyproxy/envoy/pull/6039

Comment (htuch) [reply source/server/lds_api.cc]: I left a comment on #6039, I will continue reviewing this PR to move forward, but I feel we're introducing some technical debt.

File: source/server/lds_api.cc (hunk 3 above)
Comment (htuch) [reply source/server/lds_api.cc]: Fair enough.

**Comment by ramaraochavali** [comment]
@htuch Agree with you on the proto/json serialization, also if we can tie that in to https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/discovery.proto#L59 - management servers can make intelligent decisions, of-course that comes with the cost/risk of making these errors part of contract.
