### PR TITLE
xds: safely handle watch removals during update, nested pause/resume.

### LINKED ISSUE #11877: Segfault when updating cluster to TLS with SDS
We've noticed a segfault in our envoys when updating a cluster via CDS from using plain TCP to TLS with validation context provided via SDS.

Attached are the initial version, the update that caused the segfault and the printed stack, the only thing added is the transport socket configuration pointing to SDS.
[previous_version.txt](https://github.com/envoyproxy/envoy/files/4866371/previous_version.txt)
[updated_version.txt](https://github.com/envoyproxy/envoy/files/4866372/updated_version.txt)
[stack.txt](https://github.com/envoyproxy/envoy/files/4866381/stack.txt)

Some comments:
- Crashing envoys are registered to updates of this cluster but not all are actively handling traffic for this cluster
- Not all our envoys subscribed to this cluster crash, haven't found a relation yet.
- We've had this happen in envoys running 1.14.1 and 1.15 from master, but we've seen similar issues since envoy 1.12 I recall.
- We're using DeltaXds with ADS and everything in v3.
- The SDS resource named "validation_context" is used by multiple clusters and is actually loaded statically by envoy during bootstrap
- The logs are from an envoy running 1.15 built from master, our logging system looses order, so the logs could be somehow unordered.
- Envoy was not built with debugging symbols so we cannot translate to lines, but we'll try to reproduce this.

### PR DESCRIPTION
**Pull request by htuch**
To fix https://github.com/envoyproxy/envoy/issues/11877, we need to handle safely the case where two
watches point at the same resource, and a WatchMap onConfigUpdate() causes one watch to
remove the other watch during its invoked onConfigUpdate().

While working on this, it made sense to fix https://github.com/envoyproxy/envoy/issues/11674,
avoiding spurious ClusterLoadAssignment discovery requests in the regression integration test.

Risk level: Medium (this has xDS wire-level implications).
Testing: New unit tests for pause/resume, regression unit and integration tests for watch map
  removal behaviors.

Fixes #11877 #11674

Signed-off-by: Harvey Tuch <htuch@google.com>
Co-authored-by: Sebastian Schepens <sebastian.schepens@mercadolibre.com>

### CODE REVIEW

**Comment by htuch** [comment]
@sschepens can you verify this fixes your issue? @wgallagher can you take a first pass at this? Thanks.

**Comment by htuch** [comment]
@stevenzzzz for pause/resume ref counting FYI

**Comment by sschepens** [comment]
@htuch this seems to fix our issue, tried several times to reproduce it without success. Thanks!

**Comment by htuch** [comment]
@samflattery FY I wonder if you can replicate this corner case in the xDS fuzzer, seems like it should have been possible to induce there.

**Comment by htuch** [comment]
@wgallagher friendly ping. Also tagging @lizan as senior maintainer reviewer.

File: source/common/config/grpc_mux_impl.cc [hunk 1]
```diff
@@ -94,7 +94,7 @@ GrpcMuxWatchPtr GrpcMuxImpl::addWatch(const std::string& type_url,
   // TODO(htuch): For RDS/EDS, this will generate a new DiscoveryRequest on each resource we added.
   // Consider in the future adding some kind of collation/batching during CDS/LDS updates so that we
   // only send a single RDS/EDS update after the CDS/LDS update.
-  queueDiscoveryRequest(type_url);
+  sendDiscoveryRequest(type_url);
```
Comment (wgallagher) [inline source/common/config/grpc_mux_impl.cc:97]: are there any ordering concerns with bypassing the queue?

File: source/common/config/grpc_mux_impl.cc [hunk 2]
```diff
@@ -234,7 +238,7 @@ void GrpcMuxImpl::onDiscoveryResponse(
     error_detail->set_message(Config::Utility::truncateGrpcStatusMessage(e.what()));
   }
   api_state_[type_url].request_.set_response_nonce(message->nonce());
-  queueDiscoveryRequest(type_url);
+  sendDiscoveryRequest(type_url);
```
Comment (wgallagher) [inline source/common/config/grpc_mux_impl.cc:241]: are there any ordering concerns because the queue is bypassed here?

Comment (htuch) [reply source/common/config/grpc_mux_impl.cc:241]: No, since `sendDiscoveryResponse` sets `pending_` state and effectively queues when we resume.

File: test/common/config/grpc_mux_impl_test.cc [hunk 3]
```diff
@@ -527,7 +534,7 @@ TEST_F(GrpcMuxImplTestWithMockTimeSystem, TooManyRequestsWithEmptyRateLimitSetti
 
   // Validate that drain_request_timer is enabled when there are no tokens.
   EXPECT_CALL(*drain_request_timer, enableTimer(std::chrono::milliseconds(100), _));
-  onReceiveMessage(99);
+  onReceiveMessage(100);
```
Comment (wgallagher) [inline test/common/config/grpc_mux_impl_test.cc:537]: This is happening b/c of the change to bypass queueDiscoveryRequest?

File: source/common/config/watch_map.cc [hunk 4]
```diff
@@ -81,6 +97,9 @@ void WatchMap::onConfigUpdate(const Protobuf::RepeatedPtrField<ProtobufWkt::Any>
   // We just bundled up the updates into nice per-watch packages. Now, deliver them.
   for (auto& watch : watches_) {
     const auto this_watch_updates = per_watch_updates.find(watch);
+    if (deferred_removed_during_update_->count(watch.get()) > 0) {
```
Comment (wgallagher) [inline source/common/config/watch_map.cc:100]: nit: this should probably be moved above the previous line (99)

File: test/common/config/grpc_mux_impl_test.cc (hunk 3 above)
Comment (htuch) [reply test/common/config/grpc_mux_impl_test.cc]: I did a bit of digging into why this change. It turns out there are some messages sent when watches get destroyed. Previously we basically had a mix of queue/sendDiscoveryRequest, and rate limiting only applied to some. I've done some refactoring to make this easier (I hope) to understand and added comments, PTAL.

**Comment by htuch** [comment]
Ended up having to move around a bit of logic to deal with the remote closes and reconnects.

@lizan can you take a pass? Thanks.

File: source/common/config/watch_map.cc [hunk 5]
```diff
@@ -62,6 +75,9 @@ void WatchMap::onConfigUpdate(const Protobuf::RepeatedPtrField<ProtobufWkt::Any>
     return;
   }
 
+  // Track any removals triggered by earlier watch updates.
+  deferred_removed_during_update_ = std::make_unique<absl::flat_hash_set<Watch*>>();
```
Comment (lizan) [inline source/common/config/watch_map.cc:79]: Is the assumption here `deferred_removed_during_update_ == nullptr`, lets `ASSERT`?

Comment (htuch) [reply source/common/config/watch_map.cc:79]: Nup, the goal is to reset the queue on reconnect.

Comment (lizan) [reply source/common/config/watch_map.cc:79]: I'm bit confused, what happen to the existing set in there? Aren't we assume they are already removed?

Comment (htuch) [reply source/common/config/watch_map.cc:80]: Right, I thought you were referring to another place we assign to a new unique_ptr. In this case, you are right, it should be null. Added the ASSERTs. Thanks.

**Comment by htuch** [comment]
@lizan not sure what is going on with macOS CI here, but I've fixed a few ASAN/TSAN/coverage snafus and this is now ready for approval again. Thanks.

**Comment by htuch** [comment]
@lizan ready for approval, CI is passing.
