### PR TITLE
eds: update all priorities on eds config updates

### LINKED ISSUE #3312: Unable to remove entire priority through EDS
Suppose Envoy has been previously configured with EDS with two localities, L1 and L2 with priorities 0 and 1 respectively. Sending an EDS update that only contains L1 does not remove L2 from the cluster. 

Looking at the code, this is because in `EdsClusterImpl::onConfigUpdate` we look at all the priorities found in the new config and iterate over the priority sets corresponding to those priorities on the cluster, leaving any other priority set untouched. As a result we ignore (i.e. don't remove) priorities that are not present in the incoming config update. 

I'd expect removing an entire priority from EDS to work the same way as removing any other group of hosts. 

Failing test case: https://github.com/snowp/envoy/commit/c892cac9181284044ec7bf5d129a8d1e063aa474

Filing this mostly for informational purposes as I'm already working on getting this fixed.

### PR DESCRIPTION
**Pull request by snowp**
*Description*:
Updates all priorities for a cluster even if the priority is not present in the incoming EDS update. This fixes a bug where endpoints would not get drained and removed from the cluster when their priority was not present in the config update (e.g. if you wanted to delete an entire priority). 

*Risk Level*: 
Low: Small change to existing EDS behavior. 

*Testing*:
Unit test to verify that the HostSet for the removed priority is emptied out. 

*Docs Changes*:
N/A

*Release Notes*:
Added note about bug fix

Fixes #3312

### CODE REVIEW

File: source/common/upstream/eds.cc [hunk 1]
```diff
@@ -105,6 +108,17 @@ void EdsClusterImpl::onConfigUpdate(const ResourceVector& resources) {
...
     }
   }
+
+  // Loop over all priorities not present in the config that already exists. This will
+  // empty out any remaining priority that the config update did not refer to.
+  for (size_t i = priority_state.size(); i < priority_set_.hostSetsPerPriority().size(); ++i) {
+    const HostVector empty_hosts;
+    LocalityWeightsMap empty_locality_map;
+
+    cluster_rebuilt |= updateHostsPerLocality(priority_set_.getOrCreateHostSet(i), empty_hosts,
```
Comment (snowp) [inline source/common/upstream/eds.cc]: Unclear to me whether we also want to delete the `HostSet` for priorities that are emptied out. Wanted to get input from reviewers before putting in the work to do so as it makes the solution much less trivial. The current solution will leave an empty `HostSet` around forever, but I don't imagine the cost of that is super high?

File: test/common/upstream/eds_test.cc [hunk 2]
```diff
@@ -528,6 +528,67 @@ TEST_F(EdsTest, EndpointHostsPerLocality) {
...
+      socket_address->set_port_value(port++);
+    }
+  };
+
+  add_hosts_to_locality("oceania", "koala", "ingsoc", 2, 0);
+  add_hosts_to_locality("", "us-east-1a", "", 1, 1);
+
+  bool initialized = false;
+  cluster_->initialize([&initialized] { initialized = true; });
+  VERBOSE_EXPECT_NO_THROW(cluster_->onConfigUpdate(resources));
```
Comment (PiotrSikora) [inline test/common/upstream/eds_test.cc]: Please sync with master, since this function's prototype changed.

Comment (snowp) [reply test/common/upstream/eds_test.cc]: done, thanks for the heads up

File: docs/root/intro/version_history.rst [hunk 3]
```diff
@@ -24,8 +24,10 @@ Version history
 * cli: added --config-yaml flag to the Envoy binary. When set its value is interpreted as a yaml
   representation of the bootstrap config and overrides --config-path.
 * cluster: Add :ref:`option <envoy_api_field_Cluster.close_connections_on_host_health_failure>`
+  to close tcp_proxy upstream connections when health checks fail.
```
Comment (snowp) [inline docs/root/intro/version_history.rst]: Looks like I accidentally deleted this in my previous PR. Opened #3322 to add this back in its own PR.

File: source/common/upstream/eds.cc (hunk 1 above)
Comment (alyssawilk) [reply source/common/upstream/eds.cc]: If this is simpler I think it's fine to leave it until anyone needs that particular optimization.    Honestly I'd think we'd want to delete the entire priority level and that's definitely non-trivial!

File: source/common/upstream/eds.cc [hunk 4]
```diff
@@ -95,6 +95,9 @@ void EdsClusterImpl::onConfigUpdate(const ResourceVector& resources, const std::
 
   // Track whether we rebuilt any LB structures.
   bool cluster_rebuilt = false;
+
+  // Loop over all priorities present in the config. This will either update an existing
+  // HostSet or create a new one.
```
Comment (alyssawilk) [inline source/common/upstream/eds.cc]: I think 
// Loop over existing priorities not present in the config.  This will empty out any priorities the config update did not refer to
might be a bit easier to read

Comment (snowp) [reply source/common/upstream/eds.cc]: I like it! Will update
