### PR TITLE
tls_inspector: do not close plain text connections for >16Kb reads

### LINKED ISSUE #40730: v1.35.0 on Ingress causing 502's from AWS ALB
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: After upgrading partial amount of our fleet to Envoy v1.35.0, we see ALB 502's around POST requests over HTTP/1.1

*Description*:
Previously we were running Envoy v1.34.1 across out fleet of services. After slowly rolling out upgrade of Envoy v1.35.0 to services, we started to see ALB 502's increasing. 
Immediately after rolling back the to Envoy v1.34.1 the ALB 502's started to decrease. 
The amount of traffic that experienced this was quite small (maybe less than ~0.1%), and if that same request was retried using Envoy retries, the request would succeed. It also appeared to only happen on POST requests. This was also happening regardless of what HTTP client to the ALB.

*Repro steps*:
I was able to reproduce this by redeploying out v1.35.0 and just sending constant traffic ~ roughly 50 RPS, Each request was a post HTTP/1.1 to the ALB. 

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
N/A

*Admin and Stats Output*:
Not available

*Config*:
ALB: HTTP2 listener with TLS. With target groups using HTTP/1.1 with no TLS to the Envoy instance.
Ingress Envoy: [ingress.yaml](https://github.com/user-attachments/files/21790741/ingress.yaml)

*Logs*:
I had trace logging on for these components - `connection:trace,http:trace,router:trace,filter:trace,dns:trace,upstream:trace`, and only captured the 4 below ingress logs around the exact time of the request hit the ALB and then nothing else was logged until the next request hit Envoy from the ALB.
Envoy Trace Logs on Ingress side - [ingress.csv](https://github.com/user-attachments/files/21789805/ingress.csv)
ALB Logs showing that exact request - [alb logs.csv](https://github.com/user-attachments/files/21789999/alb.logs.csv)

### PR DESCRIPTION
**Pull request by yanavlasov**
Commit Message:
#39903 introduced a regression where plain text connections were closed if Envoy read more than 16Kb in a single read operation. The bug was always there, but it before #39903 a single read of more than 64Kb was needed which is unlikely (and recommended network buffer size is 32Kb). See issue #40730

After #39903 Envoy gained ability to disconnect connections with TLS client hello above 16Kb (which is marginal) but made pre-existing bug that caused valid plain text connections to be disconnected much more likely.

This PR bring Envoy largely to the old behavior. Connections with TLS client hello above 16Kb will be interpreted as plain text (as it was before #39903). The only difference is that Envoy will not disconnect connections with a single read of more than 64Kb, but this is too rare to be a meaningful difference in behavior and is arguably more correct.

Risk Level: low (brings back old behavior)
Testing: unit tests
Docs Changes: n/a
Release Notes: yes
Platform Specific Features: n/a
Runtime guard: envoy.reloadable_features.tls_inspector_no_length_check_on_error
Fixes #40730

### CODE REVIEW

File: source/extensions/filters/listener/tls_inspector/tls_inspector.h [hunk 1]
```diff
@@ -65,7 +65,7 @@ class Config {
 
   // This is the maximum size of a ClientHello that boring ssl will accept.
   // Here is the check in boring ssl:
-  // https://github.com/google/boringssl/blob/56383dabf472100181226cd14249f04c69a0c10b/ssl/tls_record.cc#L133
+  // https://boringssl.googlesource.com/boringssl/+/HEAD/ssl/handshake.cc#137
```
Comment (ggreenway) [inline source/extensions/filters/listener/tls_inspector/tls_inspector.h]: A link to HEAD may have the line number drift over time; can you link to a specific tag/commit?

File: source/extensions/filters/listener/tls_inspector/tls_inspector.cc [hunk 2]
```diff
@@ -175,6 +176,61 @@ Network::FilterStatus Filter::onData(Network::ListenerFilterBuffer& buffer) {
...
+    } else {
+      // Checking max message length should not be done here as it will close all plain text
+      // connections that happened to read more than maxConfigReadBytes() in one I/O operation. With
+      // the default limit of 16Kb it is fairly likely.
+      if (!Runtime::runtimeFeatureEnabled(
+              "envoy.reloadable_features.tls_inspector_no_length_check_on_error") &&
+          read_ >= maxConfigReadBytes()) {
+        // We've hit the specified size limit. This is an unreasonably large ClientHello;
+        // indicate failure.
+        config_->stats().client_hello_too_large_.inc();
```
Comment (ggreenway) [inline source/extensions/filters/listener/tls_inspector/tls_inspector.cc]: #39903 added this to add visibility into the case when the clienthello is too long. Given that we can't correctly distinguish plain text vs tls client hello that is too long, should we add a config to the filter (instead of a runtime flag) so that if it's known that all traffic is TLS (no plaintext) this metric can be tracked here?

**Review by ggreenway — CHANGES_REQUESTED** [review]
/wait

File: source/extensions/filters/listener/tls_inspector/tls_inspector.h (hunk 1 above)
Comment (yanavlasov) [reply source/extensions/filters/listener/tls_inspector/tls_inspector.h]: done

File: source/extensions/filters/listener/tls_inspector/tls_inspector.cc (hunk 2 above)
Comment (yanavlasov) [reply source/extensions/filters/listener/tls_inspector/tls_inspector.cc]: Sounds good.

**Comment by agrawroh** [comment]
@yanavlasov Are we also planning on back-porting it to v1.35.x? We are hitting this issue for fast clients sending plaintext requests with large payloads.

**Comment by yanavlasov** [comment]
Yes, I think we should backport.

**Review by adisuissa — COMMENTED** [review]
/lgtm api
