### PR TITLE
fix: slow start config add min_weight_percent field to avoid too big edf deadline 

### LINKED ISSUE #19526: slow start mode formula result very big edf dealine_ cause slow start invalid
in slow start window, endpoints need slow start receives no traffic and beyond the slow start window, they still receive no traffic. because endpoints which need slow start will have a very high `deadline_` in edf scheduler.
```
(gdb) ppqueue queue_
$25 = {
  deadline_ = 300000,
  order_offset_ = 1,
  entry_ = {
    __ptr_ = 0x555562060158,
    __cntrl_ = 0x55556205b260
  }
}
$26 = {
  deadline_ = 2,
  order_offset_ = 2,
  entry_ = {
    __ptr_ = 0x555561eed7d8,
    __cntrl_ = 0x555561f4c820
  }
}
Priority queue size = 2
Priority queue capacity = 2
``` 
if host_weight=1, then `weight=host_weight * applyAggressionFactor(time_factor)` will be less than 1, but `deadline_ = current_time_+1/weight` will be too big.
and the endpoints will receive no traffic because it will never in top of the queue_ utils the normal endpoints deadline_ catch up it. this cause beyond the slow start window the endpoints still receive no traffic.

3. istio default set the host weight to 1. so don't work in istio. and may cause bug when deployment rolling update, just old endpoints receive traffic may cause these pods load too high.

> @jiangshantao-dbg @du2016 thanks for reporting the issue, this is unfortunate that the bug has not been caught in tests. I've submitted [patch](https://github.com/envoyproxy/envoy/pull/19518) for fixing slow start config propagation in Round Robin Lb. Would suggest to open a dedicated issue for revisiting the slow start formula. cc @tonya11en @wbpcode

how about change slow start formula to just a static percent. just use `aggression` as `new_weight=weight*aggression`. default aggression to 0.5, which means slow start endpoint just receive 50% of traffic to the normal one.

use formula can't avoid a too small new_weight which will cause unexpected situation.

_Originally posted by @jiangshantao-dbg in https://github.com/envoyproxy/envoy/issues/19437#issuecomment-1011685017_

### PR DESCRIPTION
**Pull request by jiangshantao-dbg**
PR to fix #19526 

Commit Message:
cluster SlowStartConfig add min_weight_percent field to avoid too big edf deadline. set default value 0.1.

Additional Description:
Risk Level: Low
Testing: Done
Docs Changes: Done
Release Notes:Done
Fixes #19526

### CODE REVIEW

**Review by adisuissa — CHANGES_REQUESTED** [review]
/lgtm api
Looked briefly at the code, and left a comment.
Consider adding tests for the minimal (0.0) and maximal (100.0) values.
/wait

File: source/common/upstream/load_balancer_impl.cc [hunk 1]
```diff
@@ -783,6 +783,19 @@ EdfLoadBalancerBase::EdfLoadBalancerBase(
           recalculateHostsInSlowStart(hosts_added);
         }
       });
+
+  min_weight_percent_ = 0.1;
+  if (slow_start_config.has_value()) {
+    if (slow_start_config.value().min_weight_percent() > 0.0 &&
+        slow_start_config.value().min_weight_percent() < 100.0) {
```
[the remark this answers is not in the document]
Comment (jiangshantao-dbg) [reply source/common/upstream/load_balancer_impl.cc:790]: what if remove the PGV validator for this field, just use the constructor to init the value. It will throw an exception if the PGV failed, which cause the cluster can't be adding to manager. I think the `min_weight_percent` should not affect the cluster update, so just the warning message and use the default value 0.1 is enough ? 

Also the `min_weight_percent` can't be 0 which will cause a really big edf deadline, and we want use the default value if the user not specify a value. so the constraint in proto use `gte: 0.0`(pb default value 0.0) and the constructor use `> 0.0`.

[the remark this answers is not in the document]
Comment (adisuissa) [reply source/common/upstream/load_balancer_impl.cc]: PGV is meant to detect problems early and reject configs that are incorrect, so I encourage using that.

If `min_weight_percent` must be greater than 0.0, why not use `gt` instead of `gte`? Same goes for the upper bound (see [here](https://github.com/envoyproxy/protoc-gen-validate#numerics) for more info)

[the remark this answers is not in the document]
Comment (adisuissa) [reply source/common/upstream/load_balancer_impl.cc]: PING?

**Comment by adisuissa** [comment]
Please let me know what you think about changing the PGV constraint (using `lt` and `gt`).
/wait

File: source/common/upstream/load_balancer_impl.cc (hunk 1 above)
[the remark this answers is not in the document]
Comment (jiangshantao-dbg) [reply source/common/upstream/load_balancer_impl.cc]: sorry, these days i am in a vacation. i will use `{lt: 1.0 gt: 0.0 ignore_empty: true}` to the field `min_weight_percent`, which allows users has not to specify the default value. and will keep checking logic in constructor to ensure the default value to 0.1.

**Comment by jiangshantao-dbg** [comment]
> Please let me know what you think about changing the PGV constraint (using `lt` and `gt`). /wait

@adisuissa sorry, i rebase the branch which cause the reviewing processing reset. i have completed the changes, and all test cases are ok. please have a look.

File: api/envoy/config/cluster/v3/cluster.proto [hunk 2]
```diff
@@ -363,12 +363,17 @@ message Cluster {
...
     // where `time_factor=(time_since_start_seconds / slow_start_time_seconds)`.
     //
     // As time progresses, more and more traffic would be sent to endpoint, which is in slow start window.
     // Once host exits slow start, time_factor and aggression no longer affect its weight.
     core.v3.RuntimeDouble aggression = 2;
+
+    // Configures the minimum percentage of origin weight that avoids too small new weight,
+    // which may cause endpoints in slow start mode receive no traffic in slow start window.
+    // Range between (0.0, 1.0). If not specified, the default is 0.1.
+    double min_weight_percent = 3 [(validate.rules).double = {lt: 1.0 gt: 0.0 ignore_empty: true}];
```
Comment (adisuissa) [inline api/envoy/config/cluster/v3/cluster.proto:376]: The type should be changed to `Percent` (see [api style](https://github.com/envoyproxy/envoy/blob/main/api/STYLE.md#api-style-guidelines)).
Also note that this implies that the range should be (0, 100).

**Review by adisuissa — COMMENTED** [review]
Thanks for the update.
Looked again at the API style guide, and left a comment to what I think should be changed here.
/wait

File: api/envoy/config/cluster/v3/cluster.proto (hunk 2 above)
Comment (adisuissa) [reply api/envoy/config/cluster/v3/cluster.proto:376]: Another option is to use a double wrapper (as the default value isn't 0), and then use `PROTOBUF_GET_WRAPPED_OR_DEFAULT` to set the value in the c'tor.

File: source/common/upstream/load_balancer_impl.cc [hunk 3]
```diff
@@ -783,6 +783,19 @@ EdfLoadBalancerBase::EdfLoadBalancerBase(
...
+    if (slow_start_config.value().min_weight_percent() > 0.0 &&
+        slow_start_config.value().min_weight_percent() < 1.0) {
+      min_weight_percent_ = slow_start_config.value().min_weight_percent();
+    } else {
+      ENVOY_LOG(warn,
+                "Invalid value {} provided for min_weight_percent parameter, must be in range "
+                "(0.0, 1.0), so use default value 0.1",
+                slow_start_config.value().min_weight_percent());
+    }
+  }
```
[the remark this answers is not in the document]
Comment (jiangshantao-dbg) [reply source/common/upstream/load_balancer_impl.cc]: thanks for advice. i have change to use `Percent`. please have a look.

**Review by adisuissa — COMMENTED** [review]
/lgtm api

@tonya11en can you please review this, I think you got the most context on slow-start

File: docs/root/intro/arch_overview/upstream/load_balancing/slow_start.rst [hunk 4]
```diff
@@ -25,6 +25,8 @@ where,
 
 As time progresses, more and more traffic would be sent to endpoint within slow start window.
 
+:ref:`MinWeightPercent parameter<envoy_v3_api_field_config.cluster.v3.Cluster.SlowStartConfig.min_weight_percent>` specifies the minimum percent of origin weight to make sure the ebf scheduler has a reasonable deadline, default is 10%.
```
Comment (tonya11en) [inline docs/root/intro/arch_overview/upstream/load_balancing/slow_start.rst:28]: Spelling- change `ebf` to `EDF`

File: source/common/upstream/load_balancer_impl.h [hunk 5]
```diff
@@ -459,6 +459,7 @@ class EdfLoadBalancerBase : public ZoneAwareLoadBalancerBase,
   const absl::optional<Runtime::Double> aggression_runtime_;
   TimeSource& time_source_;
   MonotonicTime latest_host_added_time_;
+  double min_weight_percent_;
```
Comment (tonya11en) [inline source/common/upstream/load_balancer_impl.h:462]: It's clear what this is for in the context of this PR, but in the load balancer file the name can be confusing. Can you change it to something that makes it clear this is specifically for the slow-start weight modifications? Something like `slow_start_min_weight_pct_`

**Review by tonya11en — APPROVED** [review]
This is the fix suggested in https://github.com/envoyproxy/envoy/issues/19526, so the approach LGTM. I had a few nits in the comments, but overall the docs/code are great.

One thing unrelated to the code that I would suggest is to elaborate on the problem this PR is solving. The release note doesn't make it clear why this was necessary and it would just make it easier for anyone who's curious to quickly get an answer.

Thank you for doing this!

**Comment by jiangshantao-dbg** [comment]
> This is the fix suggested in #19526, so the approach LGTM. I had a few nits in the comments, but overall the docs/code are great.
> 
> One thing unrelated to the code that I would suggest is to elaborate on the problem this PR is solving. The release note doesn't make it clear why this was necessary and it would just make it easier for anyone who's curious to quickly get an answer.
> 
> Thank you for doing this!

Thank for you advise. i has fix code/docs as the comments suggests. please have a look.

File: docs/root/intro/arch_overview/upstream/load_balancing/slow_start.rst (hunk 4 above)
Comment (jiangshantao-dbg) [reply docs/root/intro/arch_overview/upstream/load_balancing/slow_start.rst]: done

File: source/common/upstream/load_balancer_impl.h (hunk 5 above)
Comment (jiangshantao-dbg) [reply source/common/upstream/load_balancer_impl.h]: done

**Review by tonya11en — DISMISSED** [review]
Thanks, LGTM!

**Comment by rojkov** [comment]
/wait
on merge conflict

**Comment by jiangshantao-dbg** [comment]
> /wait on merge conflict

@rojkov conflict resolved

**Comment by rojkov** [comment]
Sorry, you might need to merge the main branch again as it had been broken for some time.

**Comment by jiangshantao-dbg** [comment]
> Sorry, you might need to merge the main branch again as it had been broken for some time.

@rojkov done

**Comment by rojkov** [comment]
@tonya11en could you reinstate your approval?

**Review by tonya11en — APPROVED** [review]

**Comment by jiangshantao-dbg** [comment]
@adisuissa could you review this pr again. there is 1 workflow awaiting approval. thanks

File: test/common/upstream/load_balancer_impl_test.cc [hunk 6]
```diff
@@ -44,6 +44,9 @@ class EdfLoadBalancerBasePeer {
     return std::chrono::time_point_cast<std::chrono::milliseconds>(edf_lb.latest_host_added_time_)
         .time_since_epoch();
   }
+  static double slowStartMinWeightPercent(EdfLoadBalancerBase& edf_lb) {
```
Comment (adisuissa) [inline test/common/upstream/load_balancer_impl_test.cc:47]: nit:
```suggestion
  static double slowStartMinWeightPercent(const EdfLoadBalancerBase& edf_lb) {
```

Comment (jiangshantao-dbg) [reply test/common/upstream/load_balancer_impl_test.cc]: done

File: source/common/upstream/load_balancer_impl.h [hunk 7]
```diff
@@ -467,6 +467,7 @@ class EdfLoadBalancerBase : public ZoneAwareLoadBalancerBase,
   const absl::optional<Runtime::Double> aggression_runtime_;
   TimeSource& time_source_;
   MonotonicTime latest_host_added_time_;
+  double slow_start_min_weight_percent_;
```
[the remark this answers is not in the document]
Comment (jiangshantao-dbg) [reply source/common/upstream/load_balancer_impl.h]: done

**Review by adisuissa — APPROVED** [review]

**Review by yanavlasov — APPROVED** [review]
