### PR TITLE
api: validate and fix API v3alpha structure.

### LINKED ISSUE #9580: Add checks to avoid regressing to v2 layout in v3
Post #9555 and #9515, we have a new directory layout for v3alpha. However, it's easy to accidentally have a v2 proto addition be reflected to v3alpha with the v2 structure, since we require explicit proto migration annotations to achieve the new layout.

We should add some checks to ensure that any new v2 proto either has a migration annotation for v3 or has a matching v2/v3 layout. This will largely be heuristic, but with some simple rules we should be able to catch most cases.

This should run as part of `check_format`.

CC @lizan

### PR DESCRIPTION
**Pull request by htuch**
This patch introduces a new checker, tools/api/validate_structure.py, that is run as part of the
bazel.api CI job. It ensures that the package layout for the API doesn't violate some constraints,
largely reflecting the heuristics we used for v3alpha migration.

Along the way, I discovered there were some packages that were versionless and not boosted to
v3alpha, and there were some extensions left behind in envoy.config. These are fixed as well to
allow the validation to succeed.

Risk level: Low
Testing: tools/api/validate_structure.py passes, bazel test //test/...

Fixes #9580

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

File: tools/clang_tools/api_booster/main.cc [hunk 1]
```diff
@@ -485,6 +485,7 @@ class ApiBooster : public clang::ast_matchers::MatchFinder::MatchCallback,
       return result;
     } else if (!absl::StartsWith(proto_type_name, "envoy.HotRestart") &&
                !absl::StartsWith(proto_type_name, "envoy.RouterCheckToolSchema") &&
+               !absl::StartsWith(proto_type_name, "envoy.annotations") &&
```
Comment (mattklein123) [inline tools/clang_tools/api_booster/main.cc]: Should the annotations be versioned? Orthogonal to this PR but curious,

File: tools/type_whisperer/typedb_gen.py [hunk 2]
```diff
@@ -143,7 +147,7 @@ def NextVersionUpgrade(type_name, type_map, next_version_upgrade_memo, visited=N
       type_desc.qualified_package
       for type_name, type_desc in type_map.items()
       if NextVersionUpgrade(type_name, type_map, next_version_upgrade_memo)
-  ])
+  ]).union(set(['envoy.config.retry.previous_priorities', 'envoy.config.cluster.redis']))
```
Comment (mattklein123) [inline tools/type_whisperer/typedb_gen.py]: Why are these 2 special cased here but there are more in TYPE_UPGRADE_REGEXES?

File: tools/clang_tools/api_booster/main.cc (hunk 1 above)
Comment (htuch) [reply tools/clang_tools/api_booster/main.cc]: I don't see annotations as part of the wire contract, since management servers shouldn't be relying on them. So, less concerned about versioning them and it's simpler not to have the concern around versioning the versioning annotations.

File: tools/type_whisperer/typedb_gen.py (hunk 2 above)
Comment (htuch) [reply tools/type_whisperer/typedb_gen.py]: The other versionless packages had deprecated fields or other deps that forced them to be upgraded. These didn't, but we do it explicitly to leave behind the versionless world.
