### PR TITLE
ci: Make clang-tidy repo/diff more robust

### LINKED ISSUE #25871: Clang-tidy CI can fail on github permissions
Not exactly sure why but the code that was added recently to fix clang-tidy that fetches and unshallows the checked out repo can fail in mirror CI with insufficient permissions

```console

fatal: could not read Username for 'https://github.com'/: No such device or address

```

### PR DESCRIPTION
**Pull request by phlax**
Fix #25871 

this also fixes `run_clang_tidy` when run against other CI branches (eg release) which would have broken after the next release otherwise

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by phlax** [comment]
@adisuissa @KBaichoo i think i may have been to blame for breaking clang-tidy when we shifted to shallow checkouts by default - not sure probably my bad there.

either way the newer algorithm using `merge-base` is i think the more correct way for finding change in a PR

this should make it a bit more robust

File: ci/run_envoy_docker.sh [hunk 1]
```diff
@@ -91,6 +91,7 @@ docker run --rm \
        "${VOLUMES[@]}" \
        -e AZP_BRANCH \
        -e AZP_COMMIT_SHA \
+       -e AZP_TARGET_BRANCH \
```
Comment (phlax) [inline ci/run_envoy_docker.sh:94]: i have added this separate to `AZP_BRANCH` as it doesnt work quite the same way so it would have been ambiguous to just use that

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!
