### PR TITLE
golang filter: avoid segfault when the DecodeHeaders returns status ode Stop and the request doesn't have body

### LINKED ISSUE #30688: golang filter: Envoy segfault when the DecodeHeaders returns status code Stop and the request doesn't have body
*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Write a go plugin, which returns `StopAndBuffer` as the `api.StatusType`, and the request doesn't have a body (`endStream` is true).
It seems Envoy segfault when it tries to access fields relative to the body, which is nullptr in this case.

Suggestion: 
treat `StopAndBuffer` as `Continue` if `endStream` is true in DecodeHeaders.

### PR DESCRIPTION
**Pull request by spacewander**
Fixes #30688

### CODE REVIEW

File: contrib/golang/filters/http/source/processor_state.cc [hunk 1]
```diff
@@ -47,13 +47,18 @@ bool BufferList::checkExisting(Buffer::Instance* data) {
...
+bool ProcessorState::handleHeaderGolangStatus(GolangStatus status) {
   ENVOY_LOG(debug, "golang filter handle header status, state: {}, phase: {}, status: {}",
             stateStr(), phaseStr(), int(status));
 
   ASSERT(state_ == FilterState::ProcessingHeader);
   bool done = false;
 
+  if (do_end_stream_ &&
+      (status == GolangStatus::StopAndBuffer || status == GolangStatus::StopAndBufferWatermark)) {
+    status = GolangStatus::Continue;
```
Comment (doujiang24) [inline contrib/golang/filters/http/source/processor_state.cc:59]: maybe it worth a warning log? since it is a unexpected status, there might be something wrong in the Golang plugin.

**Review by doujiang24 — COMMENTED** [review]
only a simple suggestion, otherwise, lgtm, thanks~

**Review by doujiang24 — APPROVED** [review]
lgtm~

File: contrib/golang/filters/http/source/processor_state.cc (hunk 1 above)
Comment (mattklein123) [reply contrib/golang/filters/http/source/processor_state.cc:63]: If this is broken it's going to log spam at high right. I would use ENVOY_BUG or one of the rate limiting logging messages.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
/wait

File: contrib/golang/filters/http/source/processor_state.cc (hunk 1 above)
Comment (spacewander) [reply contrib/golang/filters/http/source/processor_state.cc:63]: This path is triggered when the user provides a wrong status code from their plugin, so using ENVOY_BUG may be misleading, as it is user's BUG.

@mattklein123 
Is there any rate limiting logging messages mechanism that we can take advantage of?

Comment (doujiang24) [reply contrib/golang/filters/http/source/processor_state.cc:63]: @spacewander Seems there isn't a  rate limiting logging messages mechanism yet.

or maybe we can check the status in the Golang filter filter manager, and it will panic when status is unexpected, instead of ignore it?
and panic means the request will be terminated with 500 status, and do not affect other requests.

Comment (spacewander) [reply contrib/golang/filters/http/source/processor_state.cc:63]: > @spacewander Seems there isn't a rate limiting logging messages mechanism yet.
> 
> or maybe we can check the status in the Golang filter filter manager, and it will panic when status is unexpected, instead of ignore it? and panic means the request will be terminated with 500 status, and do not affect other requests.

LGTM. I will do it later.

**Review by doujiang24 — APPROVED** [review]
lgtm, thanks~

**Review by mattklein123 — APPROVED** [review]
