### PR TITLE
redis_proxy: fix infinite loop in shardSize(), adding an upper limit and returning the number of unique hosts

### LINKED ISSUE #38508: redis_proxy: KEYS command hangs
*Description*:
`KEYS` command hangs with envoy redis_proxy, after such query envoy can't be killed normally by TERM,INT signals.

*Repro steps*:
debian 12 amd64, redis 7.4.1, envoy-contrib-1.33.0-linux-x86_64
```
echo 'SET test test123' | redis-cli -h 127.0.0.1 -p 6380 -a pass1
OK
echo 'GET test' | redis-cli -h 127.0.0.1 -p 6380 -a pass1
"test123"
```
while
```
echo 'KEYS *' | redis-cli -h 127.0.0.1 -p 6380 -a pass1
```
hangs forever, other queries continue to work, but after `KEYS *` query - envoy can't be killed by TERM,INT (KILL works).

*Config*:
```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 6380
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 5s
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
          downstream_auth_passwords:
          - inline_string: "pass1"
  clusters:
  - name: redis_cluster
    connect_timeout: 3s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: redis
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6379
    typed_extension_protocol_options:
        envoy.filters.network.redis_proxy:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
          auth_password:
            inline_string: "pass2"
```

*Logs*:
Just one line about the query, with debug enabled:
```
[2025-02-20 17:03:25.591][4005349][debug][redis] [source/extensions/filters/network/redis_proxy/command_splitter_impl.cc:875] splitting '["KEYS", "*"]'
```

### PR DESCRIPTION
**Pull request by RaquelASRodrigues**
Commit Message: redis proxy: fix infinite loop in shardSize(), adding an upper limit and returning unique hosts

Additional Description: 
The KEYS command caused Envoy's redis_proxy to hang indefinitely
because the shardSize() function would enter an infinite loop when
chooseHost() never returned nullptr. This prevented Envoy from being
terminated with TERM or INT signals. This fix introduces an upper bound
(MaxSlot) on the loop and keeps track of unique hosts returned by
chooseHost(). Once the loop completes, shardSize() correctly returns
the number of shards instead of 0, preventing the infinite loop.

Risk Level: Low

Testing: added a unit test to make sure shardSize() does not count duplicate hosts and an integration test for a simple Keys Request. Both of these tests failed prior to this fix.

Docs Changes:
Release Notes:
Platform Specific Features:

Fixes #38508

### CODE REVIEW

File: source/extensions/filters/network/redis_proxy/conn_pool_impl.cc [hunk 1]
```diff
@@ -287,16 +287,18 @@ uint16_t InstanceImpl::ThreadLocalPool::shardSize() {
   }
 
   Common::Redis::RespValue request;
-  for (uint16_t size = 0;; size++) {
+  std::set<Upstream::HostConstSharedPtr> uniqueHosts;
```
Comment (tonya11en) [inline source/extensions/filters/network/redis_proxy/conn_pool_impl.cc:290]: std::unordered_set would be more appropriate for this. Also, our coding style prefers snake case for variable names.

Since we know the upper bound on the number of hosts, we'll want something like:
```suggestion
  std::unordered_set<Upstream::HostConstSharedPtr> unique_hosts;
  unique_hosts.reserve(Envoy::Extensions::Clusters::Redis::MaxSlot);
```

File: source/extensions/filters/network/redis_proxy/conn_pool_impl.cc [hunk 2]
```diff
@@ -287,16 +287,18 @@ uint16_t InstanceImpl::ThreadLocalPool::shardSize() {
...
+  for (uint16_t size = 0; size < Envoy::Extensions::Clusters::Redis::MaxSlot; size++) {
     Clusters::Redis::RedisSpecifyShardContextImpl lb_context(
         size, request, Common::Redis::Client::ReadPolicy::Primary);
     Upstream::HostConstSharedPtr host = Upstream::LoadBalancer::onlyAllowSynchronousHostSelection(
         cluster_->loadBalancer().chooseHost(&lb_context));
     if (!host) {
       return size;
     }
+    uniqueHosts.insert(host);
```
Comment (tonya11en) [inline source/extensions/filters/network/redis_proxy/conn_pool_impl.cc:299]: The compiler may do this automatically, but just to be explicit you should move the shared ptr into the set:
```suggestion
    uniqueHosts.insert(std::move(host));
```

File: test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc [hunk 3]
```diff
@@ -456,6 +456,33 @@ TEST_F(RedisConnPoolImplTest, ShardNoHost) {
   tls_.shutdownThread();
 };
 
+TEST_F(RedisConnPoolImplTest, ShardSizeDuplicateHosts) {
```
Comment (tonya11en) [inline test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc:459]: How is this testing duplicated hosts? Can you add a quick comment explaining what you are testing for?

File: test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc [hunk 4]
```diff
@@ -456,6 +456,33 @@ TEST_F(RedisConnPoolImplTest, ShardNoHost) {
...
+  Common::Redis::RespValueSharedPtr value = std::make_shared<Common::Redis::RespValue>();
+  MockPoolCallbacks callbacks;
+
+  uint16_t max_hosts = 5;
+  std::vector<std::shared_ptr<NiceMock<Upstream::MockHost>>> mock_hosts;
+  for (uint16_t i = 0; i < max_hosts; i++) {
+    mock_hosts.push_back(std::make_shared<NiceMock<Upstream::MockHost>>());
+  }
+
+  uint16_t call_count = 0;
```
Comment (tonya11en) [inline test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc:473]: Can you assert the call count you expect at the end of the test?

**Review by tonya11en — CHANGES_REQUESTED** [review]
Thanks for contributing! I'm not familiar with this extension, so I'm just just driving by and commenting on some cpp style items.

File: test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc (hunk 4 above)
Comment (tonya11en) [reply test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc:473]: I think the only important thing here is that call_count > max_hosts. If that's right, you can just assert that.

File: source/extensions/filters/network/redis_proxy/conn_pool_impl.cc (hunk 1 above)
Comment (RaquelASRodrigues) [reply source/extensions/filters/network/redis_proxy/conn_pool_impl.cc]: Thank you for pointing this out! I have replaced std::set with absl::flat_hash_set as it is preferred over std::unordered_set for performance reasons. I have also added .reserve() to pre-allocate memory based on the known upper bound as you suggested.

File: source/extensions/filters/network/redis_proxy/conn_pool_impl.cc (hunk 2 above)
Comment (RaquelASRodrigues) [reply source/extensions/filters/network/redis_proxy/conn_pool_impl.cc]: Just implemented this change as well, thank you for the feedback!

File: test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc (hunk 4 above)
Comment (RaquelASRodrigues) [reply test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc:473]: I see your point, the test now asserts that call count > max_hosts in addition to the other assertion.

File: test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc (hunk 3 above)
Comment (RaquelASRodrigues) [reply test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc:459]: The idea here is that even though chooseHost() is called up to MaxSlot times, it repeatedly returns one of 5 mock hosts. The goal is to validate that shardSize() correctly handles duplicate hosts and returns the count of unique ones, which should be equal to max_hosts in this case. Should I add another comment to the code for clarity?

**Review by tonya11en — APPROVED** [review]
Thanks for the fix. This still needs to be reviewed by an owner or senior maintainer, so I'll assign one.
