### PR TITLE
Fix missing additional addresses from endpoint config dump

### LINKED ISSUE #34740: configdump `include_eds` hides additional_addresses
*Title*: configdump `include_eds` hides additional_addresses

*Description*:
Config dump does not show the full EDS. Specifically additional_addresses is missing (possibly more, that one I am sure of).

Missing code is here https://github.com/envoyproxy/envoy/blob/73bf655edd1b84815e9348d545da704046402460/source/server/admin/config_dump_handler.cc#L360

*Repro steps*:
Send EDS like
```json
    {
      "versionInfo": "2024-06-13T22:20:53Z/12",
      "endpointConfig": {
        "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
        "clusterName": "outbound|9090||echo-v6.default.svc.cluster.local",
        "endpoints": [
          {
            "locality": {},
            "lbEndpoints": [
              {
                "endpoint": {
                  "address": {
                    "socketAddress": {
                      "address": "10.244.0.9",
                      "portValue": 9090
                    }
                  },
                  "additionalAddresses": [
                    {
                      "address": {
                        "socketAddress": {
                          "address": "fd00:10:244::9",
                          "portValue": 9090
                        }
                      }
                    }
                  ]
                },
                "healthStatus": "HEALTHY",
                "metadata": {
                  "filterMetadata": {
                    "envoy.transport_socket_match": {
                      "tlsMode": "istio"
                    },
                    "istio": {
                      "workload": "echo;default;echo;;Kubernetes"
                    }
                  }
                },
                "loadBalancingWeight": 1
              }
            ],
            "loadBalancingWeight": 1
          }
        ]
      }
    },
```

Look at configdump, you will see
```json
    {
     "endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "cluster_name": "outbound|9090||echo-v6.default.svc.cluster.local",
      "endpoints": [
       {
        "locality": {},
        "lb_endpoints": [
         {
          "endpoint": {
           "address": {
            "socket_address": {
             "address": "10.244.0.9",
             "port_value": 9090
            }
           },
           "health_check_config": {}
          },
          "health_status": "HEALTHY",
          "metadata": {
           "filter_metadata": {
            "istio": {
             "workload": "echo;default;echo;;Kubernetes"
            },
            "envoy.transport_socket_match": {
             "tlsMode": "istio"
            }
           }
          },
          "load_balancing_weight": 1
         }
        ],
        "load_balancing_weight": 1
       }
      ],
      "policy": {
       "overprovisioning_factor": 140
      }
     }
    },
```

cc @leosarra

### PR DESCRIPTION
**Pull request by leosarra**
Commit Message: Fix missing additional addresses from endpoint config dump
Additional Description:
Risk Level: Low
Testing: updated existing unit test to provide coverage
Docs Changes: None
Release Notes: Added
Platform Specific Features: None
Fixes #34740
[Optional Runtime guard:]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: test/server/admin/config_dump_handler_test.cc [hunk 1]
```diff
@@ -16,13 +16,25 @@ INSTANTIATE_TEST_SUITE_P(IpVersions, AdminInstanceTest,
 
 // helper method for adding host's info
 void addHostInfo(NiceMock<Upstream::MockHost>& host, const std::string& hostname,
-                 const std::string& address_url, envoy::config::core::v3::Locality& locality,
+                 const std::vector<std::string> addresses_url_list,
```
Comment (adisuissa) [inline test/server/admin/config_dump_handler_test.cc:19]: nit: I think it may be better to separate the `address_url` from the list of addresses (i.e., add an additional `additional_addresses_url`), as the expected output is different - the `address_url` will be in its own field, and the list will be in their own field. (keeping the same separation)

File: changelogs/current.yaml [hunk 2]
```diff
@@ -180,6 +180,9 @@ bug_fixes:
     Validate http service path_prefix
     :ref:`path_prefix <envoy_v3_api_field_extensions.filters.http.ext_authz.v3.HttpService.path_prefix>`,
     Validate http service path_prefix configuration must start with ``/``.
+- area: admin
+  change: |
+    Fixed missing additional addresses for :ref:`LbEndpoint <envoy_v3_api_field_config.endpoint.v3.LbEndpoint.endpoint>` in config dump.
```
Comment (adisuissa) [inline changelogs/current.yaml:185]: Can you please add a link for `additional addresses` (to this field: https://github.com/envoyproxy/envoy/blob/de6b730c3f59e8ee3ee756c60bc826d7ede295e1/api/envoy/config/endpoint/v3/endpoint_components.proto#L60).

**Review by adisuissa — COMMENTED** [review]
Thanks for fixing this!
Overall LGTM, modulo minor comments.

**Comment by tyxia** [comment]
/assign @howardjohn 

Could you take a first pass to see if this PR fix the issue you reported? Thanks!

File: test/server/admin/config_dump_handler_test.cc (hunk 1 above)
Comment (leosarra) [reply test/server/admin/config_dump_handler_test.cc:19]: Sure, I will update it :+1:

Comment (leosarra) [reply test/server/admin/config_dump_handler_test.cc]: Done, changed back to having two separate fields: address_url and additional_addresses_url.

File: changelogs/current.yaml (hunk 2 above)
Comment (leosarra) [reply changelogs/current.yaml]: Done

**Review by adisuissa — APPROVED** [review]
LGTM, thanks!

**Review by tyxia — APPROVED** [review]
LGTM. Thanks!

Based on [code comment](https://github.com/envoyproxy/envoy/blob/main/envoy/upstream/host_description.h#L177-L188) , `addressListOrNull` represents optional additional address
