### PR TITLE
Fix handling locality update for an eds cluster endpoint

### LINKED ISSUE #12392: Address changing localities results in corrupted EDS
When an address is switched to a different locality, it appears something goes wrong in the update, resulting in the EDS update not being applied correctly.

Initial EDS:
```yaml
  endpoints:
  - locality:
      region: primary
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.10.10.10
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
  - locality:
      region: secondary
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 20.20.20.20
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
    priority: 1
```

Later send:
```yaml
  endpoints:
  - locality:
      region: primary
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 20.20.20.20
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 20
  - locality:
      region: secondary
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 30.30.30.30
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 80
```

Resulting EDS (from config_dump, but I originally found this in a real cluster and verified traffic was incorrect as well, proving its not just a config_dump bug)
```yaml
- locality:
    region: secondary
  lb_endpoints:
  - endpoint:
      address:
        socket_address:
          address: 20.20.20.20
          port_value: 80
      health_check_config: {}
    health_status: HEALTHY
    load_balancing_weight: 1
  - endpoint:
      address:
        socket_address:
          address: 30.30.30.30
          port_value: 80
      health_check_config: {}
    health_status: HEALTHY
    load_balancing_weight: 1
  load_balancing_weight: 80
```

Here you can see the `20.20.20.20` address ends up in the wrong locality.

This is not limited to just having the endpoints simply not move localities either:

<details>

Input 1:
```yaml
  endpoints:
  - locality:
      region: region
      zone: zone
      subZone: subzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.10.10.10
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
  - locality:
      region: notregion
      zone: notzone
      subZone: notsubzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.103.93.137
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
    priority: 2
  - locality:
      region: nearregion
      zone: zone
      subZone: subzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.103.220.97
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
    priority: 1
```

Input 2:
```yaml
  endpoints:
  - locality:
      region: region
      zone: zone
      subZone: subzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.103.93.137
            portValue: 80
      load_balancing_weight: 1
    load_balancing_weight: 20
  - locality:
      region: notregion
      zone: notzone
      subZone: notsubzone
    load_balancing_weight: 1
  - locality:
      region: nearregion
      zone: zone
      subZone: subzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.103.220.97
            portValue: 80
      load_balancing_weight: 1
    load_balancing_weight: 80
```

Result:
```yaml
- locality:
    region: nearregion
    zone: zone
    sub_zone: subzone
  lb_endpoints:
  - endpoint:
      address:
        socket_address:
          address: 10.103.220.97
          port_value: 80
      health_check_config: {}
    health_status: HEALTHY
    load_balancing_weight: 1
  load_balancing_weight: 80
- locality:
    region: notregion
    zone: notzone
    sub_zone: notsubzone
  lb_endpoints:
  - endpoint:
      address:
        socket_address:
          address: 10.103.93.137
          port_value: 80
      health_check_config: {}
    health_status: HEALTHY
    load_balancing_weight: 1
  load_balancing_weight: 1
```

You can see here notregion gets load_balancing_weight=1 when its expected to be `20`

</details>

Reproduce: 
[repro.tar.gz](https://github.com/envoyproxy/envoy/files/5004122/repro.tar.gz)

```
ln -sf eds1.yaml eds.yaml
envoy -c envoy-eds.yaml
ln -sf eds2.yaml eds.yaml
```

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Commit message: Fix handling locality update for an eds cluster endpoint
Risk Level: Low
Testing: new integration test
Docs Changes: N/A
Release Notes: Added
Runtime guard: `support_locality_update_on_eds_cluster_endpoints`
Fixes #12392

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
image

signed-off part seems correct, not sure why `DCO` is failing. Would appreciate if someone could guide me please.

**Comment by rojkov** [comment]
DCO is failing because the `Author` field doesn't contain correct email:
```
Author: vikas <vikaschoudhary16>
```

**Comment by vikaschoudhary16** [comment]
Thanks @rojkov :) !!!

File: source/common/upstream/upstream_impl.cc [hunk 1]
```diff
@@ -1611,13 +1614,24 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(
...
-        *existing_host->second->healthCheckAddress() != *host->healthCheckAddress();
+    const bool health_check_address_changed =
+        (health_checker_ != nullptr && existing_host_found &&
+         *existing_host->second->healthCheckAddress() != *host->healthCheckAddress());
+
+    const bool locality_changed =
+        (existing_host_found &&
+         ((host->locality().region() != existing_host->second->locality().region()) ||
+          (host->locality().zone() != existing_host->second->locality().zone()) ||
+          (host->locality().sub_zone() != existing_host->second->locality().sub_zone())));
```
Comment (snowp) [inline source/common/upstream/upstream_impl.cc:1625]: Can you just do a proto equality check here to avoid a per member comparison?

File: source/common/upstream/upstream_impl.cc [hunk 2]
```diff
@@ -1595,6 +1595,9 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(
       current_priority_hosts.size());
   // Keep track of hosts we're adding (or replacing)
   absl::flat_hash_set<std::string> new_hosts_for_current_priority(new_hosts.size());
+  // Keep track of hosts for which locality is changed.
+  absl::flat_hash_set<std::string> existing_hosts_for_current_priority_locality_changed(
```
Comment (snowp) [inline source/common/upstream/upstream_impl.cc:1599]: maybe remove `existing` from this since we it's somewhat explicit if the locality changed? `hosts_with_updated_locality_for_current_priority` maybe?

File: source/common/upstream/upstream_impl.cc [hunk 3]
```diff
@@ -1726,15 +1740,24 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(
   if (!current_priority_hosts.empty() && dont_remove_healthy_hosts) {
     erase_from =
         std::remove_if(current_priority_hosts.begin(), current_priority_hosts.end(),
-                       [&all_new_hosts, &new_hosts_for_current_priority, &final_hosts,
+                       [&all_new_hosts, &new_hosts_for_current_priority,
+                        &existing_hosts_for_current_priority_locality_changed, &final_hosts,
                         &max_host_weight](const HostSharedPtr& p) {
+                         // This host is being added as a new host, total replacement
+                         // remove the older host
```
Comment (snowp) [inline source/common/upstream/upstream_impl.cc:1747]: This comment seems a bit incomplete, could you elaborate? Are we adding a new host with the updated locality, then remove the old one?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks, this looks about right to me just a few nits.

What was the previous behavior? Would the update get ignored or would we add another endpoint?

/wait

**Comment by vikaschoudhary16** [comment]
> Thanks, this looks about right to me just a few nits.
> 
> What was the previous behavior? Would the update get ignored or would we add another endpoint?
> 
> /wait

Previously it was getting ignored silently.

Thanks for the feedback. I will go through the feedback.
At the moment struggling with a weird ci issue. ci reports a seg fault in the test that I added. Unable to figure out the reason because whatever options I try locally, it never crashes. Even with ` ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release  //test/common/upstream:eds_test -c opt'` , it passes locally. 
Any pointers what else i can try?

File: test/common/upstream/eds_test.cc [hunk 4]
```diff
@@ -1456,6 +1456,65 @@ TEST_F(EdsTest, EndpointLocality) {
...
+  // Update locality now
+  locality->set_region("space");
+  locality->set_zone("station");
+  locality->set_sub_zone("mars");
+  doOnConfigUpdateVerifyNoThrow(cluster_load_assignment);
+
+  auto& updatedHosts = cluster_->prioritySet().hostSetsPerPriority()[0]->hosts();
+  EXPECT_EQ(updatedHosts.size(), 2);
+  for (int i = 0; i < 2; ++i) {
+    EXPECT_EQ(0, hosts[i]->priority());
```
Comment (dio) [inline test/common/upstream/eds_test.cc:1510]: This should be `updatedHost`?

```suggestion
    EXPECT_EQ(0, updatedHost[i]->priority());
```

File: source/common/upstream/upstream_impl.cc (hunk 1 above)
Comment (vikaschoudhary16) [reply source/common/upstream/upstream_impl.cc]: done

File: source/common/upstream/upstream_impl.cc (hunk 2 above)
Comment (vikaschoudhary16) [reply source/common/upstream/upstream_impl.cc]: done

File: source/common/upstream/upstream_impl.cc (hunk 3 above)
Comment (vikaschoudhary16) [reply source/common/upstream/upstream_impl.cc]: updated

File: source/common/upstream/upstream_impl.cc [hunk 5]
```diff
@@ -1724,32 +1736,41 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(
   const bool dont_remove_healthy_hosts =
       health_checker_ != nullptr && !info()->drainConnectionsOnHostRemoval();
   if (!current_priority_hosts.empty() && dont_remove_healthy_hosts) {
-    erase_from =
```
Comment (snowp) [inline source/common/upstream/upstream_impl.cc:1727]: Is it possible to avoid this reformatting? I think it would be good to avoid the git history churn here

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks this LGTM, just one comment re formatting

File: source/common/upstream/upstream_impl.cc (hunk 5 above)
Comment (vikaschoudhary16) [reply source/common/upstream/upstream_impl.cc:1727]: done

Comment (vikaschoudhary16) [reply source/common/upstream/upstream_impl.cc:1727]: oh, looks like ci wants formatting:

```
021-12-13T23:53:11.8379276Z diff --git a/source/common/upstream/upstream_impl.cc b/source/common/upstream/upstream_impl.cc
2021-12-13T23:53:11.8380398Z index 2e4e84b2d..87c6b3196 100644
2021-12-13T23:53:11.8384499Z --- a/source/common/upstream/upstream_impl.cc
2021-12-13T23:53:11.8385175Z +++ b/source/common/upstream/upstream_impl.cc
2021-12-13T23:53:11.8385947Z @@ -1736,42 +1736,41 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(
2021-12-13T23:53:11.8386543Z    const bool dont_remove_healthy_hosts =
2021-12-13T23:53:11.8387232Z        health_checker_ != nullptr && !info()->drainConnectionsOnHostRemoval();
2021-12-13T23:53:11.8387824Z    if (!current_priority_hosts.empty() && dont_remove_healthy_hosts) {
2021-12-13T23:53:11.8388431Z -    erase_from =
2021-12-13T23:53:11.8389152Z -        std::remove_if(current_priority_hosts.begin(), current_priority_hosts.end(),
2021-12-13T23:53:11.8389939Z -                       [&all_new_hosts, &new_hosts_for_current_priority,
2021-12-13T23:53:11.8390787Z -                        &hosts_with_updated_locality_for_current_priority, &final_hosts,
2021-12-13T23:53:11.8391583Z -                        &max_host_weight](const HostSharedPtr& p) {
2021-12-13T23:53:11.8392501Z -                         // This host has already been added as a new host in the
2021-12-13T23:53:11.8395844Z -                         // new_hosts_for_current_priority. Return false here to make sure that host
2021-12-13T23:53:11.8397375Z -                         // reference with older locality gets cleaned up from the priority.
2021-12-13T23:53:11.8398850Z -                         if (hosts_with_updated_locality_for_current_priority.contains(
2021-12-13T23:53:11.8400187Z -                                 p->address()->asString())) {
2021-12-13T23:53:11.8401055Z -                           return false;
2021-12-13T23:53:11.8401878Z -                         }
2021-12-13T23:53:11.8402351Z -
2021-12-13T23:53:11.8403698Z -                         if (all_new_hosts.contains(p->address()->asString()) &&
2021-12-13T23:53:11.8404634Z -                             !new_hosts_for_current_priority.contains(p->address()->asString())) {
2021-12-13T23:53:11.8405475Z -                           // If the address is being completely deleted from this priority, but is
2021-12-13T23:53:11.8406284Z -                           // referenced from another priority, then we assume that the other
2021-12-13T23:53:11.8407246Z -                           // priority will perform an in-place update to re-use the existing Host.
2021-12-13T23:53:11.8408214Z -                           // We should therefore not mark it as PENDING_DYNAMIC_REMOVAL, but
2021-12-13T23:53:11.8409106Z -                           // instead remove it immediately from this priority.
2021-12-13T23:53:11.8410265Z -                           // Example: health check address changed and priority also changed
2021-12-13T23:53:11.8411154Z -                           return false;
2021-12-13T23:53:11.8411957Z -                         }
2021-12-13T23:53:11.8412487Z -
2021-12-13T23:53:11.8413803Z -                         if (!(p->healthFlagGet(Host::HealthFlag::FAILED_ACTIVE_HC) ||
2021-12-13T23:53:11.8415695Z -                               p->healthFlagGet(Host::HealthFlag::FAILED_EDS_HEALTH))) {
2021-12-13T23:53:11.8416691Z -                           if (p->weight() > max_host_weight) {
2021-12-13T23:53:11.8417555Z -                             max_host_weight = p->weight();
2021-12-13T23:53:11.8419015Z -                           }
2021-12-13T23:53:11.8419880Z -
2021-12-13T23:53:11.8420517Z -                           final_hosts.push_back(p);
2021-12-13T23:53:11.8421304Z -                           p->healthFlagSet(Host::HealthFlag::PENDING_DYNAMIC_REMOVAL);
2021-12-13T23:53:11.8423123Z -                           return true;
2021-12-13T23:53:11.8423870Z -                         }
2021-12-13T23:53:11.8424480Z -                         return false;
2021-12-13T23:53:11.8425030Z -                       });
2021-12-13T23:53:11.8425807Z +    erase_from = std::remove_if(
2021-12-13T23:53:11.8426236Z +        current_priority_hosts.begin(), current_priority_hosts.end(),
2021-12-13T23:53:11.8426861Z +        [&all_new_hosts, &new_hosts_for_current_priority,
2021-12-13T23:53:11.8427394Z +         &hosts_with_updated_locality_for_current_priority, &final_hosts,
2021-12-13T23:53:11.8427795Z +         &max_host_weight](const HostSharedPtr& p) {
2021-12-13T23:53:11.8428329Z +          // This host has already been added as a new host in the
2021-12-13T23:53:11.8428798Z +          // new_hosts_for_current_priority. Return false here to make sure that host
2021-12-13T23:53:11.8429406Z +          // reference with older locality gets cleaned up from the priority.
2021-12-13T23:53:11.8430161Z +          if (hosts_with_updated_locality_for_current_priority.contains(p->address()->asString())) {
2021-12-13T23:53:11.8430673Z +            return false;
2021-12-13T23:53:11.8431017Z +          }
2021-12-13T23:53:11.8431393Z +
2021-12-13T23:53:11.8431954Z +          if (all_new_hosts.contains(p->address()->asString()) &&
2021-12-13T23:53:11.8432679Z +              !new_hosts_for_current_priority.contains(p->address()->asString())) {
2021-12-13T23:53:11.8433262Z +            // If the address is being completely deleted from this priority, but is
2021-12-13T23:53:11.8433831Z +            // referenced from another priority, then we assume that the other
2021-12-13T23:53:11.8434762Z +            // priority will perform an in-place update to re-use the existing Host.
2021-12-13T23:53:11.8435466Z +            // We should therefore not mark it as PENDING_DYNAMIC_REMOVAL, but
2021-12-13T23:53:11.8436022Z +            // instead remove it immediately from this priority.
2021-12-13T23:53:11.8436555Z +            // Example: health check address changed and priority also changed
2021-12-13T23:53:11.8436961Z +            return false;
2021-12-13T23:53:11.8437308Z +          }
2021-12-13T23:53:11.8437617Z +
2021-12-13T23:53:11.8438639Z +          if (!(p->healthFlagGet(Host::HealthFlag::FAILED_ACTIVE_HC) ||
2021-12-13T23:53:11.8439731Z +                p->healthFlagGet(Host::HealthFlag::FAILED_EDS_HEALTH))) {
2021-12-13T23:53:11.8440438Z +            if (p->weight() > max_host_weight) {
2021-12-13T23:53:11.8441245Z +              max_host_weight = p->weight();
2021-12-13T23:53:11.8441815Z +            }
2021-12-13T23:53:11.8442110Z +
2021-12-13T23:53:11.8442389Z +            final_hosts.push_back(p);
2021-12-13T23:53:11.8442994Z +            p->healthFlagSet(Host::HealthFlag::PENDING_DYNAMIC_REMOVAL);
2021-12-13T23:53:11.8443665Z +            return true;
2021-12-13T23:53:11.8443961Z +          }
2021-12-13T23:53:11.8444579Z +          return false;
2021-12-13T23:53:11.8444904Z +        });
2021-12-13T23:53:11.8445305Z      current_priority_hosts.erase(erase_from, current_priority_hosts.end());
2021-12-13T23:53:11.8445646Z    }
2021-12-13T23:53:11.8445937Z  
2021-12-13T23:53:11.9481096Z ##[error]Bash exited with code '1'.
2021-12-13T23:53:11.9527811Z ##[section]Finishing: Run check format scripts
```

Comment (vikaschoudhary16) [reply source/common/upstream/upstream_impl.cc:1727]: do you think we can avoid the formatting?

Comment (snowp) [reply source/common/upstream/upstream_impl.cc:1727]: I guess this is fine then, just a bit confused why it wants to move std::remove_if to the next line.

**Review by snowp — APPROVED** [review]
LGTM! 

@envoyproxy/envoy-maintainers anyone else up for review this as a second reviewer? Normally I'd ask Matt but he's out

**Review by snowp — CHANGES_REQUESTED** [review]
Looking at this again do you think you could add a runtime guard for this? This code is pretty complicated so if we can I think we should guard this change

https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#runtime-guarding

**Comment by vikaschoudhary16** [comment]
> Looking at this again do you think you could add a runtime guard for this? This code is pretty complicated so if we can I think we should guard this change
> 
> https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#runtime-guarding

sure, updated. PTAL!

File: test/common/upstream/eds_test.cc [hunk 6]
```diff
@@ -1456,6 +1456,65 @@ TEST_F(EdsTest, EndpointLocality) {
   EXPECT_EQ(nullptr, cluster_->prioritySet().hostSetsPerPriority()[0]->localityWeights());
 }
 
+// Validate that onConfigUpdate() updates the endpoint locality of an existing endpoint.
+TEST_F(EdsTest, EndpointLocalityUpdated) {
```
Comment (snowp) [inline test/common/upstream/eds_test.cc:1460]: Can you add a test that verifies that the runtime flag can be used to revert to the old behavior? Thanks

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks, one small nit and this LGTM.

For second set of eyes: 
/assign-from @envoyproxy/envoy-maintainers

**Comment by snowp** [comment]
Maybe @dio can take a look as a second reviewer?

File: test/common/upstream/eds_test.cc (hunk 6 above)
Comment (vikaschoudhary16) [reply test/common/upstream/eds_test.cc:1460]: done. PTAL!

File: source/common/runtime/runtime_features.cc [hunk 7]
```diff
@@ -61,6 +61,7 @@ constexpr const char* runtime_features[] = {
     "envoy.reloadable_features.correct_scheme_and_xfp",
     "envoy.reloadable_features.disable_tls_inspector_injection",
     "envoy.reloadable_features.fix_added_trailers",
+    "envoy.reloadable_features.fix_locality_update_for_eds_cluster_endpoints",
```
Comment (dio) [inline source/common/runtime/runtime_features.cc:64]: I know this follows the above `fix_added_trailers` (also naming is hard!), but can we have a better name for this flag that describes the behavior change?

And since this has a behavior change and a runtime feature flag, let's surface that to the current version history (https://github.com/envoyproxy/envoy/blob/main/docs/root/version_history/current.rst). As an example, you can find when the `envoy.reloadable_features.fix_added_trailers` was added here: https://github.com/envoyproxy/envoy/blob/1d1c63ceb19fd2420db13c7568a9302343e882de/docs/root/version_history/v1.20.0.rst#bug-fixes,

File: test/common/upstream/eds_test.cc [hunk 8]
```diff
@@ -1456,6 +1456,129 @@ TEST_F(EdsTest, EndpointLocality) {
...
+    const auto& locality = updatedHosts[i]->locality();
+    EXPECT_EQ("space", locality.region());
+    EXPECT_EQ("station", locality.zone());
+    EXPECT_EQ("mars", locality.sub_zone());
+  }
+}
+
+// Validate that onConfigUpdate() does not update the endpoint locality if fix is
+// disabled
+TEST_F(EdsTest, EndpointLocalityNotUpdatedIfFixDisabled) {
```
Comment (dio) [inline test/common/upstream/eds_test.cc:1520]: Please help to describe what the "actual" fix is, or probably comparing the previous behavior with the proposed will be helpful. 🙇🏾

**Review by dio — COMMENTED** [review]
Thanks, @vikaschoudhary16! The code looks good. Need to add an entry to version history?

**Review by dio — APPROVED** [review]
Awesome. Looks good. Thanks, @vikaschoudhary16!

**Comment by snowp** [comment]
Can you look at CI? The failure seems legit

Also if possible avoid force pushing to PRs under review, as it makes it harder to maintain change history throughout the review process

**Comment by vikaschoudhary16** [comment]
> Can you look at CI? The failure seems legit
> 
> Also if possible avoid force pushing to PRs under review, as it makes it harder to maintain change history throughout the review process

PTAL @snowp . Thanks!

**Review by snowp — APPROVED** [review]
Thanks!
