### PR TITLE
listener: fix stat tag extraction to work with listener stat_prefix

### LINKED ISSUE #16103: Prometheus stats for listener with stat_prefix set have wrong labels/extraction
If a listener has a `stat_prefix` configured (new in Envoy 1.18) and the stat_prefix does not match the regular expression for an address (`1.2.3.4_443` or similar), the prometheus stats will include the `stat_prefix` in the stat name instead of in a label, eg `envoy_listener_vip_downstream_cx_overflow{}` for `stat_prefix: vip`.

The correct output is `envoy_listener_downstream_cx_overflow{envoy_listener_address="vip"}`

### PR DESCRIPTION
**Pull request by ggreenway**
Fixes #16103

Signed-off-by: Greg Greenway <ggreenway@apple.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by ggreenway** [comment]
@jmarantz we discussed this, including the runtime override, a few months ago. However, the test fails because I realized the vector of default regex's is held in a ConstSingleton, so a Runtime flag doesn't work for that. Do you think I should change it to not be a ConstSingleton (and create the list on demand when we need it)? Even if we do that, the stats store_ is created in main_common, well before we load config, which is when we know the value of a runtime override. Thoughts on the best way to handle this?

**Comment by jmarantz** [comment]
Sorry I missed this, Greg! Yes I think we can change the regexes to be created in some other way, either lazy or explicitly, if that helps.

We could also allow the regex-collection to be modified after we read the runtime flags, as long as we assert that happens before we start spawning worker threads.

**Comment by ggreenway** [comment]
I looked into this, and it looks like the runtime is initialized much later than the TagProducer. There are a lot of dependencies between subsystems during initialization; I'm not sure if this can be made to work or not.

Specifically, the TagProducer is configured [here](https://github.com/envoyproxy/envoy/blob/b9eada56a2ce8203c47796f80b64a7822616fa09/source/server/server.cc#L408), and the Runtime is setup [here](https://github.com/envoyproxy/envoy/blob/b9eada56a2ce8203c47796f80b64a7822616fa09/source/server/server.cc#L595). The Runtime LoaderImpl creates some stats, so there's no clear way to resolve.

**Comment by jmarantz** [comment]
Does the Runtime get created after we spawn worker threads? If not maybe we could just mutate the regex-list when the Runtime gets created, and ignore whatever stats had been created prior to the Runtime.

**Comment by ggreenway** [comment]
> Does the Runtime get created after we spawn worker threads? If not maybe we could just mutate the regex-list when the Runtime gets created, and ignore whatever stats had been created prior to the Runtime.

Some of the stats created are ones affected by this change; the AdminListener is created before the Runtime.

**Comment by ggreenway** [comment]
@jmarantz I added a few more tests; I think this is ready for review

File: source/common/config/well_known_names.cc [hunk 1]
```diff
@@ -135,8 +135,8 @@ TagNameValues::TagNameValues() {
   // http.(<stat_prefix>.)*
   addTokenized(HTTP_CONN_MANAGER_PREFIX, "http.$.**");
 
-  // listener.(<address>.)*
-  addRe2(LISTENER_ADDRESS, R"(^listener\.((<ADDRESS>)\.))");
+  // listener.(<address|stat_prefix>.)*, but specifically excluding "admin"
+  addRe2(LISTENER_ADDRESS, R"(^listener\.((<ADDRESS>|<TAG_VALUE>)\.))", "", "admin");
```
Comment (ggreenway) [inline source/common/config/well_known_names.cc:139]: Note that in `std::regex` this could all be part of the regex, as this engine supports negative matches. But I don't want to add any more uses of std::regex if it's all possible to avoid, due to performance issues.

Comment (jmarantz) [reply source/common/config/well_known_names.cc:139]: I agree with your call here.

**Review by jmarantz — APPROVED** [review]
