### PR TITLE
grpc-web: Fix 503 handling for gRPC Web text

### LINKED ISSUE #13831: grpc-web RPC blocks forever if gRPC server terminates
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *grpc-web RPC blocks forever if gRPC server terminates*

*Description*:
I have a gRPC-web client and a C++ gRPC server. When using envoy v1.14, if a gRPC server died, the invocation of an RPC from the client side would throw an exception. In envoy v1.16, the RPC instead blocks forever, which is undesirable.

My config:
```yaml
admin:
  access_log_path: /dev/stdout
  address:
    socket_address: { address: 0.0.0.0, port_value: 9902 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          { address: 0.0.0.0, port_value: "8080" }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/my.package" }
                          route:
                            cluster: gprc_server
                            max_grpc_timeout: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
 
  clusters:
    - name: gprc_server
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: gprc_server
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: gprc_server
                      port_value: "7000"

layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        overload:
          global_downstream_max_connections: 50000

```

I noticed that the [v1.16](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.16.0) release notes state that:

"http: changed how local replies are processed for requests which transform from grpc to not-grpc, or not-grpc to grpc. Previously the initial generated reply depended on which filter sent the reply, but now the reply is consistently generated the way the downstream expects. This behavior can be temporarily reverted by setting envoy.reloadable_features.unify_grpc_handling to false."

If i set envoy.reloadable_features.unify_grpc_handling to false, this issue goes away.

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This fixes the 503 handling for gRPC Web requests with `application/grpc-web-text` content-type. Previously, when the upstream cannot be contacted (since local reset or connection reset), the gRPC Web filter always expects gRPC response from the local reply handler. This fix is guarded by `envoy.reloadable_features.grpc_web_fix_non_proto_encoded_response_handling` feature flag.

Additional Description: https://github.com/envoyproxy/envoy/issues/13831#issuecomment-748548659.
Risk Level: Low
Testing: Integration test, and manual test
Docs Changes: N/A
Release Notes: Added, since adding `envoy.reloadable_features.grpc_web_fix_non_proto_encoded_response_handling` feature flag.
Platform-Specific Features: N/A

Fixes #13831 

Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

### CODE REVIEW

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 1]
```diff
@@ -30,27 +63,17 @@ struct RcDetailsValues {
...
-  if (content_type != nullptr) {
-    return gRpcWebContentTypes().count(content_type->value().getStringView()) > 0;
+bool GrpcWebFilter::checkGrpcResponseHeaders(Http::ResponseHeaderMap& headers, bool end_stream) {
+  const bool ok = Http::Utility::getResponseStatus(headers) == enumToInt(Http::Code::OK);
+  if (ok && (Grpc::Common::isGrpcResponseHeaders(headers, end_stream) ||
+             hasGrpcWebContentType(headers))) {
+    return true;
   }
+
+  ENVOY_LOG(info, "upstream response is not gRPC response");
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:73]: This happens also during local replies right?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 2]
```diff
@@ -30,27 +63,17 @@ struct RcDetailsValues {
...
-
-bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
-  if (!headers.Path()) {
-    return false;
-  }
-  const Http::HeaderEntry* content_type = headers.ContentType();
-  if (content_type != nullptr) {
-    return gRpcWebContentTypes().count(content_type->value().getStringView()) > 0;
+bool GrpcWebFilter::checkGrpcResponseHeaders(Http::ResponseHeaderMap& headers, bool end_stream) {
+  const bool ok = Http::Utility::getResponseStatus(headers) == enumToInt(Http::Code::OK);
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:67]: Doesn't `isGrpcResponseHeaders` already check for OK?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 3]
```diff
@@ -30,27 +63,17 @@ struct RcDetailsValues {
...
+  if (ok && (Grpc::Common::isGrpcResponseHeaders(headers, end_stream) ||
+             hasGrpcWebContentType(headers))) {
+    return true;
   }
+
+  ENVOY_LOG(info, "upstream response is not gRPC response");
+  headers.setGrpcStatus(
+      Grpc::Utility::httpToGrpcStatus(enumToInt(Http::Utility::getResponseStatus(headers))));
+  response_headers_ = &headers;
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:76]: Since we mutate the response header I would change the name of this function to reflect that

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 4]
```diff
@@ -156,6 +180,12 @@ Http::FilterHeadersStatus GrpcWebFilter::encodeHeaders(Http::ResponseHeaderMap&
   } else {
     headers.setReferenceContentType(Http::Headers::get().ContentTypeValues.GrpcWebProto);
   }
+
+  if (!checkGrpcResponseHeaders(headers, end_stream)) {
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:184]: Is stopping iteration correct when end_stream=true? We wouldn't get a subsequent data frame that could be used to continue iteration

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 5]
```diff
@@ -156,6 +180,12 @@ Http::FilterHeadersStatus GrpcWebFilter::encodeHeaders(Http::ResponseHeaderMap&
...
+    ENVOY_LOG(info, "stop iteration");
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:185]: this seems either unnecessary or underspecified

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 6]
```diff
@@ -164,6 +194,15 @@ Http::FilterDataStatus GrpcWebFilter::encodeData(Buffer::Instance& data, bool) {
...
   }
 
+  // When the upstream response is not a gRPC response, we set the "grpc-message" header with the
+  // upstream body content.
+  if (response_headers_ != nullptr) {
+    data.drain(data.length());
+    response_headers_->setGrpcMessage(Http::Utility::PercentEncoding::encode(data.toString()));
+    response_headers_->setContentLength(0);
+    return Http::FilterDataStatus::Continue;
+  }
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:204]: I'm not sure if this works right if there are multiple data frames? It also might not be feasible if the upstream body is huge

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks, some comments to get this started

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 6 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:204]: Yeah, will update this.

File: test/extensions/filters/http/grpc_web/grpc_web_filter_test.cc [hunk 7]
```diff
@@ -195,6 +195,25 @@ TEST_F(GrpcWebFilterTest, Base64NoPadding) {
...
+  Http::TestResponseHeaderMapImpl response_headers{{":status", "400"}};
+  EXPECT_EQ(Http::FilterHeadersStatus::StopIteration,
+            filter_.encodeHeaders(response_headers, false));
+  Buffer::OwnedImpl data1("start");
+  EXPECT_EQ(Http::FilterDataStatus::StopIterationNoBuffer, filter_.encodeData(data1, false));
+  Buffer::OwnedImpl data2("hello");
+  EXPECT_EQ(Http::FilterDataStatus::StopIterationNoBuffer, filter_.encodeData(data2, false));
+  Buffer::OwnedImpl data3("end");
+  EXPECT_EQ(Http::FilterDataStatus::Continue, filter_.encodeData(data3, true));
+
```
Comment (qiwzhang) [inline test/extensions/filters/http/grpc_web/grpc_web_filter_test.cc:212]: can we verify response_headers has "grpc-message" with "start hello end"?

File: test/extensions/filters/http/grpc_web/grpc_web_filter_integration_test.cc [hunk 8]
```diff
@@ -141,7 +164,13 @@ TEST_P(GrpcWebFilterIntegrationTest, UpstreamDisconnect) {
 
   ASSERT_TRUE(fake_upstream_connection_->close());
   response->waitForEndStream();
+  EXPECT_TRUE(response->complete());
+
+  // TODO(dio): Need to check each response body, should reflect the requirement mandated by the
+  // request "Accept" header.
   EXPECT_EQ("503", response->headers().getStatusValue());
+  EXPECT_NE(nullptr, response->headers().GrpcMessage());
```
Comment (qiwzhang) [inline test/extensions/filters/http/grpc_web/grpc_web_filter_integration_test.cc:172]: why there is not GrpcMessage header?  LocalReply text body should be converted to it.

Comment (dio) [reply test/extensions/filters/http/grpc_web/grpc_web_filter_integration_test.cc]: Sorry, this is "EXPECT_NE", hence we expect to have it in "grpc-message". I added the content expectation instead to make it clear.

File: test/extensions/filters/http/grpc_web/grpc_web_filter_test.cc (hunk 7 above)
Comment (dio) [reply test/extensions/filters/http/grpc_web/grpc_web_filter_test.cc:212]: My proposal will be: expect the last frame here, i.e. "end", since I think this is a failure anyway, so do not want to spend time buffering the content.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 6 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Updated with no buffering if we know the response is wrong, and take the last frame (when end_stream true) as the grpc-message content. Let me know what you think.

File: test/extensions/filters/http/grpc_web/grpc_web_filter_test.cc (hunk 7 above)
Comment (qiwzhang) [reply test/extensions/filters/http/grpc_web/grpc_web_filter_test.cc:212]: SG

**Review by qiwzhang — APPROVED** [review]

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 9]
```diff
@@ -17,6 +19,45 @@ namespace Extensions {
 namespace HttpFilters {
 namespace GrpcWeb {
 
+namespace {
+
+// Bit mask denotes a trailers frame of gRPC-Web.
+constexpr const uint8_t GRPC_WEB_TRAILER = 0b10000000;
+constexpr const uint64_t MAX_GRPC_MESSAGE_LENGTH = 1024;
+
+const absl::flat_hash_set<std::string>& gRpcWebContentTypes() {
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:28]: Should this be a unit tested utility?

Also is there a reason for the move?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 10]
```diff
@@ -156,14 +174,43 @@ Http::FilterHeadersStatus GrpcWebFilter::encodeHeaders(Http::ResponseHeaderMap&
...
-Http::FilterDataStatus GrpcWebFilter::encodeData(Buffer::Instance& data, bool) {
+Http::FilterDataStatus GrpcWebFilter::encodeData(Buffer::Instance& data, bool end_stream) {
   if (!is_grpc_web_request_) {
     return Http::FilterDataStatus::Continue;
   }
 
+  // When the upstream response (this is also relevant for local reply, since gRPC-Web request is
+  // not a gRPC request which makes the local reply's is_grpc_request set to false) is not a gRPC
+  // response, we set the "grpc-message" header with the upstream body content.
+  if (response_headers_ != nullptr) {
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:196]: I know it's a bug fix but I think we should flag protect regardless.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 11]
```diff
@@ -156,14 +174,43 @@ Http::FilterHeadersStatus GrpcWebFilter::encodeHeaders(Http::ResponseHeaderMap&
...
+    if (!end_stream) {
+      return Http::FilterDataStatus::StopIterationNoBuffer;
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:198]: won't this cause the same problem?  Shouldn't it buffer until end_stream?

**Review by alyssawilk — COMMENTED** [review]
Thanks for tackling this!  A few thoughts

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 10 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:196]: Do you mean adding a reloadable feature flag?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 11 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:198]: Will add a test for this. Seems like I failed to cover this case in this patch.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 9 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:28]: No specific reason, but it is tested indirectly, but yeah good point on adding unit tests. Thanks!

Comment (alyssawilk) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:28]: if we can minimize diffs to that'd be helpful!

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 12]
```diff
@@ -156,14 +174,43 @@ Http::FilterHeadersStatus GrpcWebFilter::encodeHeaders(Http::ResponseHeaderMap&
   } else {
     headers.setReferenceContentType(Http::Headers::get().ContentTypeValues.GrpcWebProto);
   }
-  return Http::FilterHeadersStatus::Continue;
+
+  if (end_stream || isValidResponseHeaders(headers, end_stream)) {
+    return Http::FilterHeadersStatus::Continue;
+  }
+
+  ENVOY_LOG(debug, "received invalid response headers since the upstream response or local reply "
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:182]: If we think it's invalid for the local reply to not send gRPC web, I'd suggest that sendLocalReply track both is_grpc and is_grpc_web.  Then this filter need not transform. WDYT?

Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:182]: Yes, I think that will be one of the solution. I discussed this offline with @snowp, since we need to transform bad upstream response as well, probably this is enough to handle it here. Either way I'm good.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 13]
```diff
@@ -156,14 +175,44 @@ Http::FilterHeadersStatus GrpcWebFilter::encodeHeaders(Http::ResponseHeaderMap&
...
   if (!is_grpc_web_request_) {
     return Http::FilterDataStatus::Continue;
   }
 
+  // When the upstream response (this is also relevant for local reply, since gRPC-Web request is
+  // not a gRPC request which makes the local reply's is_grpc_request set to false) is not a gRPC
+  // response, we set the "grpc-message" header with the upstream body content.
+  if (response_headers_ != nullptr) {
+    if (!end_stream) {
+      return Http::FilterDataStatus::StopIterationAndBuffer;
```
Comment (lizan) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:199]: It is possible that upstream send large response and then we buffer a lot here?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 14]
```diff
@@ -156,14 +175,44 @@ Http::FilterHeadersStatus GrpcWebFilter::encodeHeaders(Http::ResponseHeaderMap&
...
+    }
+
+    constexpr uint64_t max_grpc_message_length = 1024;
+    // Take the last frame as the grpc-message value, but the size of it is limited by
+    // max_grpc_message_length.
+    const auto message =
+        Http::Utility::PercentEncoding::encode(data.toString().substr(0, max_grpc_message_length));
```
Comment (lizan) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:206]: use data.copyOut so it doesn't convert all content to string.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 13 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:199]: Are you suggesting `StopIterationAndNoBuffer`? I have it there but since https://github.com/envoyproxy/envoy/pull/14516#discussion_r552968560. I think I misunderstood the statement 😅. will revert back.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 11 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:202]: This is now tested.

Comment (alyssawilk) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:202]: This code should tell the HCM to throw away body data. 
It looks like your test verifies that if you send
a
{\"percentage\": \"100%\"}
that the resultant body is
{\"percentage\": \"100%\"}

I don't think that is the intended behavior?

Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:202]: My proposal was: I thought that since this is a bad upstream response, we _can_ throw away part of the body except the last one. Since this is a "bad upstream response" anyway.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 13 above)
Comment (lizan) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Not really, you can buffer until 1024 bytes then throw the rest.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 15]
```diff
@@ -7,16 +7,50 @@
...
+#include "common/runtime/runtime_features.h"
 
 namespace Envoy {
 namespace Extensions {
 namespace HttpFilters {
 namespace GrpcWeb {
 
+namespace {
+
+constexpr uint64_t MAX_GRPC_MESSAGE_LENGTH = 1024;
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:25]: comment where this comes from? I'm surprised we're going that small given gRPC messages allow up to 4M.

I can easily see custom HTTP response messages sent by sendLocalReply and the local reply mapper being larger than this.

I assume it's arbitrary and just to cap buffering up to the configured buffer limits?

File: docs/root/version_history/current.rst [hunk 16]
```diff
@@ -42,6 +42,7 @@ Bug Fixes
 * dns: fix a bug where custom resolvers provided in configuration were not preserved after network issues.
 * dns_filter: correctly associate DNS response IDs when multiple queries are received.
 * grpc mux: fix sending node again after stream is reset when ::ref:`set_node_on_first_message_only <envoy_api_field_core.ApiConfigSource.set_node_on_first_message_only>` is set.
+* grpc-web: fix local reply and non-gRPC response handling. This fix can be temporarily reverted by setting `envoy.reloadable_features.grpc_web_fix_non_grpc_response_handling` to false.
```
Comment (alyssawilk) [inline docs/root/version_history/current.rst:45]: for small response bodies?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 17]
```diff
@@ -7,16 +7,50 @@
...
+
+std::string buildGrpcMessage(const Buffer::Instance* buffered, Buffer::Instance* last) {
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:27]: comments please?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 18]
```diff
@@ -54,6 +56,22 @@ bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
   return false;
 }
 
+bool GrpcWebFilter::hasGrpcWebContentType(const Http::RequestOrResponseHeaderMap& headers) const {
+  const Http::HeaderEntry* content_type = headers.ContentType();
+  if (content_type != nullptr) {
+    return gRpcWebContentTypes().count(content_type->value().getStringView()) > 0;
```
[the remark this answers is not in the document]
Comment (alyssawilk) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:94]: ping?

[the remark this answers is not in the document]
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:94]: Sorry I missed this, I'll fix this.

[the remark this answers is not in the document]
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:94]: If we consider only grpc-web (and grpc-web+proto) here, should the filter "Continue" on grpc-web-text (and grpc-web-text+proto)?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 15 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:25]: @alyssawilk and I'm not sure if the "configured (encoder) buffer limit" is really big we should put everything on "grpc-message" header. cc. @lizan @qiwzhang.

Comment (alyssawilk) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:25]: Yeah, it's always a question of what too big is.  I think we could comment the limit is arbitrary (and that it could be made configurable if it is ever needed) and raising it to say 16k (which we're willing to buffer on socket reads) would help.  Second, if we get one large response (sendLocalReply sends in one fell swoop) it's already buffered and I'd be inclined to stick it in.  That way if folks configure any Envoy direct response even if it's 16.1k (which is still within Envoy default header limits) it'll go through, but if upstream screws up the protocol it'd be best effort.   And then test both cases.  Sound reasonable?

Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:25]: @alyssawilk OK, thanks for the explanation!

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 10 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: This is added and tested, please let me know if I missed anything.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 12 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Accommodated.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 15 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Modified.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 19]
```diff
@@ -7,16 +7,54 @@
...
 
 namespace Envoy {
 namespace Extensions {
 namespace HttpFilters {
 namespace GrpcWeb {
 
+namespace {
+
+// This is arbitrarily chosen.
+// TODO(dio): Make it configurable when it is needed.
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:26]: optional, but I don't think you need a TODO.  You can just say it's arbitrary and a config knob can be added should it be needed.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 20]
```diff
@@ -7,16 +7,54 @@
...
+constexpr uint64_t MAX_GRPC_MESSAGE_LENGTH = 16384;
+
+// This builds grpc-message header value from encoding buffer and the last frame (when
+// end_stream=true). When we have buffered data in encoding buffer, we limit the length of
+// grpc-message to be smaller than MAX_GRPC_MESSAGE_LENGTH. However, when we only have "last" data,
+// we send it all.
+std::string buildGrpcMessage(const Buffer::Instance* buffered, Buffer::Instance* last) {
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:33]: Again I don't think we can enforce limits here, if we want to handle local replies correctly

We can enforce limits if there are multiple encodeData calls.  Each encodeData call represents data we're already willing to buffer, and we want to make sure we handle local replies.

I'd suggest cribbing one of the tests from local_reply_integration_test to make sure we handle large local replies correctly.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 21]
```diff
@@ -54,6 +92,58 @@ bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
   return false;
 }
 
+bool GrpcWebFilter::hasGrpcWebContentType(const Http::RequestOrResponseHeaderMap& headers) const {
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:95]: unit tests, please!

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 18 above)
[the remark this answers is not in the document]
Comment (alyssawilk) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: oh sorry, this was less about web vs web-text and more about +proto vs +thrift.  I _think_ we should support anything that's legit grpc-web and proto encoding but not grpc-web which is thrift encoded. Though maybe @lizan has thoughts here?

Also if you agree let's fix the function name to indicate it's not all grpc-web but proto encoded grpc web.

**Review by alyssawilk — COMMENTED** [review]
Making progress!  Here's some more ideas from my end.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 20 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:34]: Added.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 19 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Updated: https://github.com/envoyproxy/envoy/pull/14516/commits/041096cd830dec6101a58dc61e09c4b69cdc39ee.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 21 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Added: https://github.com/envoyproxy/envoy/pull/14516/commits/27070e0c0cc67ff13b874970c0f1eebec8f74724.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 18 above)
[the remark this answers is not in the document]
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: The name is updated.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 20 above)
Comment (alyssawilk) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:34]: I'm confused how you could have an integration test with local reply greater than max grpc messagae length and not trip the asserts below:
 ASSERT(buffered->length() <= MAX_GRPC_MESSAGE_LENGTH);

can you clue me in?

Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:34]: From my understanding, `buffered` here is the encoding buffer, which is nullptr in the case of local reply.

Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: I have updated it to have two separate functions.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 22]
```diff
@@ -143,27 +239,55 @@ Http::FilterDataStatus GrpcWebFilter::decodeData(Buffer::Instance& data, bool en
...
-Http::FilterDataStatus GrpcWebFilter::encodeData(Buffer::Instance& data, bool) {
+Http::FilterDataStatus GrpcWebFilter::encodeData(Buffer::Instance& data, bool end_stream) {
   if (!is_grpc_web_request_) {
     return Http::FilterDataStatus::Continue;
   }
 
+  // When the upstream response (this is also relevant for local reply, since gRPC-Web request is
+  // not a gRPC request which makes the local reply's is_grpc_request set to false) is not a gRPC
+  // response, we set the "grpc-message" header with the upstream body content.
+  if (needs_response_transformation_) {
```
[the remark this answers is not in the document]
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Updated the name.

**Review by alyssawilk — COMMENTED** [review]
Nice, this is way easier to read, thanks for the refactors.  Almost there!

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 23]
```diff
@@ -7,16 +7,36 @@
...
 
 namespace Envoy {
 namespace Extensions {
 namespace HttpFilters {
 namespace GrpcWeb {
 
+namespace {
+
+// This is arbitrarily chosen. This can be made configurable when it is required.
+constexpr uint64_t MAX_GRPC_MESSAGE_LENGTH = 16384;
```
[the remark this answers is not in the document]
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Ah, OK. Thank you. This is changed.

**Comment by dio** [comment]
The error message from CI: ##[error]System.IO.IOException: No space left on device

File: source/common/runtime/runtime_features.cc [hunk 24]
```diff
@@ -66,6 +66,8 @@ constexpr const char* runtime_features[] = {
     "envoy.reloadable_features.check_ocsp_policy",
     "envoy.reloadable_features.disable_tls_inspector_injection",
     "envoy.reloadable_features.fix_wildcard_matching",
+    "envoy.reloadable_features.fixed_connection_close",
```
Comment (alyssawilk) [inline source/common/runtime/runtime_features.cc:69]: bad merge?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 25]
```diff
@@ -54,6 +74,71 @@ bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
...
+  return false;
+}
+
+// If response headers do not contain gRPC or gRPC-Web response headers, it needs transformation.
+bool GrpcWebFilter::needsTransformationForNonProtoEncodedResponse(Http::ResponseHeaderMap& headers,
+                                                                  bool end_stream) const {
+  return Runtime::runtimeFeatureEnabled(
+             "envoy.reloadable_features.grpc_web_fix_non_proto_encoded_response_handling") &&
+         !Grpc::Common::isGrpcResponseHeaders(headers, end_stream) &&
+         !(Http::Utility::getResponseStatus(headers) == enumToInt(Http::Code::OK) &&
```
Comment (alyssawilk) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:103]: mind commenting why we do not convert if the response code is OK?

**Review by alyssawilk — COMMENTED** [review]
Almost there.  @lizan and @snowp can you two do a pass as well?

File: source/common/runtime/runtime_features.cc (hunk 24 above)
Comment (dio) [reply source/common/runtime/runtime_features.cc]: Ah, sorry. Fixed.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 25 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:107]: Sure. Commented.

**Review by lizan — APPROVED** [review]

**Review by alyssawilk — DISMISSED** [review]

**Comment by dio** [comment]
@snowp please let me know if you need me to introduce more changes to this PR. Thank you!

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 26]
```diff
@@ -54,6 +74,82 @@ bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
...
+  }
+  return false;
+}
+
+// If response headers do not contain valid response headers, it needs transformation.
+bool GrpcWebFilter::needsTransformationForNonProtoEncodedResponse(Http::ResponseHeaderMap& headers,
+                                                                  bool end_stream) const {
+  return Runtime::runtimeFeatureEnabled(
+             "envoy.reloadable_features.grpc_web_fix_non_proto_encoded_response_handling") &&
+         // We do transformation when the response headers is not gRPC response headers and it is
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:112]: I think this would be easier to read if it said something like `We transform the response unless it's already a gRPC or gRPC-Web response`

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 27]
```diff
@@ -54,6 +74,82 @@ bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
...
+                                                             Buffer::Instance* last_data) {
+  const auto* encoding_buffer = encoder_callbacks_->encodingBuffer();
+  if (encoding_buffer != nullptr) {
+    encoder_callbacks_->modifyEncodingBuffer([&output](Buffer::Instance& buffered) {
+      output.move(buffered, MAX_BUFFERED_PLAINTEXT_LENGTH);
+      buffered.drain(buffered.length());
+    });
+  }
+
+  // In the case of local reply, "encoding_buffer" is nullptr and we only have filled "last_data".
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:128]: Wouldn't this also be when the response only contains a single DATA chunk?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 28]
```diff
@@ -54,6 +74,82 @@ bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
...
+             "envoy.reloadable_features.grpc_web_fix_non_proto_encoded_response_handling") &&
+         // We do transformation when the response headers is not gRPC response headers and it is
+         // not proto-encoded gRPC-Web response headers.
+         !Grpc::Common::isGrpcResponseHeaders(headers, end_stream) &&
+         !isProtoEncodedGrpcWebResponseHeaders(headers);
+}
+
+void GrpcWebFilter::mergeAndLimitNonProtoEncodedResponseData(Buffer::OwnedImpl& output,
+                                                             Buffer::Instance* last_data) {
+  const auto* encoding_buffer = encoder_callbacks_->encodingBuffer();
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:120]: Instead of doing all this gymnastics to create a new buffer, can you just call `addEncodedData` and then read from the buffer?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 29]
```diff
@@ -54,6 +74,82 @@ bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
...
+    }
+    output.move(*last_data, needed);
+    last_data->drain(last_data->length());
+  }
+}
+
+void GrpcWebFilter::setTransformedNonProtoEncodedResponseHeaders(Buffer::Instance* data) {
+  Buffer::OwnedImpl merged_data;
+  // When we have buffered data in encoding buffer, we limit the length of the output to be smaller
+  // than MAX_BUFFERED_PLAINTEXT_LENGTH. However, when we only have "last" data, we send it all.
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:143]: Can the last frame not be larger than MAX_BUFFERED_PLAINTEXT_LENGTH?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 30]
```diff
@@ -143,27 +239,57 @@ Http::FilterDataStatus GrpcWebFilter::decodeData(Buffer::Instance& data, bool en
...
     return Http::FilterDataStatus::Continue;
   }
 
+  // When the upstream response (this is also relevant for local reply, since gRPC-Web request is
+  // not a gRPC request which makes the local reply's is_grpc_request set to false) is not a gRPC
+  // response, we set the "grpc-message" header with the upstream body content.
+  if (needs_transformation_for_non_proto_encoded_response_) {
+    const auto* encoding_buffer = encoder_callbacks_->encodingBuffer();
+    if (!end_stream) {
+      if (encoding_buffer != nullptr &&
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:280]: Maybe leave a comment for why we want to limit buffering here in addition to when we construct grpc-message

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 31]
```diff
@@ -54,6 +74,82 @@ bool GrpcWebFilter::isGrpcWebRequest(const Http::RequestHeaderMap& headers) {
...
+    absl::string_view current_content_type =
+        StringUtil::rtrim(content_type_value.substr(0, content_type_value.find_first_of(';')));
+    // We expect only proto encoding response
+    // https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md. And the value of media-type is
+    // case-sensitive https://tools.ietf.org/html/rfc2616#section-3.7.
+    return StringUtil::CaseInsensitiveCompare()(
+               current_content_type, Http::Headers::get().ContentTypeValues.GrpcWebProto) ||
+           StringUtil::CaseInsensitiveCompare()(current_content_type,
+                                                Http::Headers::get().ContentTypeValues.GrpcWeb);
+  }
```
Comment (snowp) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:103]: Should this live in some shared utility? I know we infer other content types elsewhere, but I don't think we use this kind of logic. Should we?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks for working on this! Just some questions/suggestions

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 29 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:143]: The last frame can be larger than MAX_BUFFERED_PLAINTEXT_LENGTH.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 28 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:121]: Do you mean `addEncodedData` for the `last_data`?

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 31 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:104]: Can I add TODO here, I can have another PR focus on moving this code.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 28 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:125]: Updated.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 30 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:286]: Added.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 27 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Added more comments to it.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 31 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:108]: I added a TODO here.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc (hunk 26 above)
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Updated as suggested. Thanks for this.

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 32]
```diff
@@ -7,16 +7,36 @@
...
+namespace {
+
+// This is the maximum buffered plaintext data length to be converted into grpc-message header. This
+// is arbitrarily chosen. This can be made configurable when it is required.
+constexpr uint64_t MAX_BUFFERED_PLAINTEXT_LENGTH = 16384;
+
+// This builds grpc-message header value from body data.
+std::string buildGrpcMessage(Buffer::Instance& body_data) {
+  const uint64_t message_length = body_data.length();
+  std::string message(message_length, 0);
```
[the remark this answers is not in the document]
Comment (dio) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc]: Updated as suggested.

**Review by snowp — APPROVED** [review]
Thanks this LGTM!
