### PR TITLE
stats: fix stats name for prometheus

### LINKED ISSUE #4568: prometheus fails to scrape metrics
We are trying to use envoy native support for promethues metrics, but prometheus fails to scrape the metrics because our cluster name contains characters '@' and '=', like following:

`xlsoa.example.greeter@v=v2.2.1`

It works fine previously when using statsd exporter which replaces all the illegal characters for prometheus(https://github.com/prometheus/statsd_exporter/blob/master/exporter.go#L252). The converted metric name is as below:

`# HELP envoy_cluster_xlsoa_example_greeter_v_v2_2_1_update_success_counter Metric autogenerated by statsd_exporter.`

But now, when using envoy native support for prometheus metrics, envoy doesn't replace all the illegal characters to match the regex required by prometheus(https://prometheus.io/docs/concepts/data_model/).

We expect envoy can convert the metric name to match the regex required by prometheus, what do you think?

### PR DESCRIPTION
**Pull request by jinuxstyle**
This commit replaces the illegal characters in stats name for matching the
regex required by prometheus, which is [a-zA-Z_:][a-zA-Z0-9_:]*.

Fixes #4568 

The changes can be covered by the existing unit test PrometheusStatsFormatterTest.

### CODE REVIEW

**Comment by ggreenway** [comment]
Also, see my comment on the related issue. I think that there was a failure much earlier in tag extraction. The prometheus metric name shouldn't contain your cluster name at all; it is supposed to be a label on the metric, and labels are allowed to contain any character I believe (because they're quoted strings).

**Comment by jinuxstyle** [comment]
Yes. It seems there has a problem in extracting the value for label envoy_cluster_name. I will try to find out.

File: source/server/http/admin.cc [hunk 1]
```diff
@@ -132,6 +132,8 @@ const char AdminHtmlEnd[] = R"(
 </body>
 )";
 
+const std::regex PromRegex("[^a-zA-Z0-9_]");
```
[the remark this answers is not in the document]
Comment (ggreenway) [reply source/server/http/admin.cc]: Sorry, I didn't notice that note about colons. I agree, they should not be supported here.

**Comment by jinuxstyle** [comment]
@ggreenway Updated PR per comments. 
@alyssawilk Added unit tests as requested. 

Please have a look.

The ci check_format failure looks irrelevant. It's about the order of header file "#include "server/http/admin.h"".

File: source/server/http/admin.cc [hunk 2]
```diff
@@ -594,10 +596,15 @@ Http::Code AdminImpl::handlerPrometheusStats(absl::string_view, Http::HeaderMap&
 }
 
 std::string PrometheusStatsFormatter::sanitizeName(const std::string& name) {
-  std::string stats_name = name;
-  std::replace(stats_name.begin(), stats_name.end(), '.', '_');
-  std::replace(stats_name.begin(), stats_name.end(), '-', '_');
-  return stats_name;
+  // The name must match the regex [a-zA-Z_:][a-zA-Z0-9_:]* as required by
+  // prometheus. Of which the colon is reserved and should not be exported.
+  // Refer to https://prometheus.io/docs/concepts/data_model/.
```
Comment (alyssawilk) [inline source/server/http/admin.cc]: Mild preference that we just update the regex.

  // The name must match the regex [a-zA-Z_][a-zA-Z0-9_]* as required by prometheus. 
  // Refer to ...

Comment (jinuxstyle) [reply source/server/http/admin.cc]: Updated.

File: source/server/http/admin.cc [hunk 3]
```diff
@@ -594,10 +596,14 @@ Http::Code AdminImpl::handlerPrometheusStats(absl::string_view, Http::HeaderMap&
...
 
 std::string PrometheusStatsFormatter::sanitizeName(const std::string& name) {
-  std::string stats_name = name;
-  std::replace(stats_name.begin(), stats_name.end(), '.', '_');
-  std::replace(stats_name.begin(), stats_name.end(), '-', '_');
-  return stats_name;
+  // The name must match the regex [a-zA-Z_][a-zA-Z0-9_]* as required by
+  // prometheus. Refer to https://prometheus.io/docs/concepts/data_model/.
+  std::string stats_name = std::regex_replace(name, PromRegex, "_");
+  if (stats_name[0] >= '0' && stats_name[0] <= '9') {
```
Comment (ggreenway) [inline source/server/http/admin.cc]: I think this case is unneeded, because this is always called from `PrometheusStatsFormatter::metricName()`, which prepends "envoy_" to the metric name.

File: test/server/http/admin_test.cc [hunk 4]
```diff
@@ -1141,6 +1141,20 @@ TEST_F(PrometheusStatsFormatterTest, MetricName) {
...
+TEST_F(PrometheusStatsFormatterTest, SanitizeMetricName) {
+  std::string raw = "An.artist.plays-violin@019street";
+  std::string expected = "envoy_An_artist_plays_violin_019street";
+  auto actual = PrometheusStatsFormatter::metricName(raw);
+  EXPECT_EQ(expected, actual);
+}
+
+TEST_F(PrometheusStatsFormatterTest, SanitizeMetricNameDigitFirst) {
+  std::string raw = "3.artists.play-violin@019street";
+  std::string expected = "envoy__3_artists_play_violin_019street";
```
Comment (ggreenway) [inline test/server/http/admin_test.cc]: As noted above, I think that `"envoy_3_artists_play_violin_019street"` (single underscore near beginning) is correct.

File: source/server/http/admin.cc (hunk 3 above)
Comment (jinuxstyle) [reply source/server/http/admin.cc]: Yes. The check is not necessary for current use case. I will remove the check.

File: test/server/http/admin_test.cc (hunk 4 above)
Comment (jinuxstyle) [reply test/server/http/admin_test.cc]: OK

File: source/server/http/admin.cc (hunk 3 above)
Comment (jinuxstyle) [reply source/server/http/admin.cc]: @ggreenway ？

Comment (jinuxstyle) [reply source/server/http/admin.cc]: Good point. I agree it's more reasonable to sanitize the metric and tag name as a whole.

**Comment by alyssawilk** [comment]
I'm not sure what's up with the mac failure.  Looks unrelated but it has failed 4 times thusfar...  Could you try a master merge and see if that fixes it?

**Comment by zuercher** [comment]
From my investigation, merging master will fix this. I think it's fine to just merge this PR.
