### PR TITLE
ci: Separate format checks

### LINKED ISSUE #15313: Split format checks in CI
### Description

its very helpful having the format jobs at the beginning and aborting ci if they fail

however, there are an increasing number of format jobs so this is taking quite a long time

in addition to this some of the format jobs dont provide any kind of fix if they fail - which means it takes longer rerunning the same (passing) jobs with no diff at the end of it, and incorrect messaging

i would suggest to split the format jobs so that they can run in parallel, perhaps on the basis of whether they can autofix or not

### LINKED ISSUE #15456: docs: Improve error output for config validation
https://dev.azure.com/cncf/envoy/_build/results?buildId=68915&view=logs&jobId=a9c3f16a-7a41-5cb0-a55b-0d11e9c98c50&j=a9c3f16a-7a41-5cb0-a55b-0d11e9c98c50&t=044b2326-1800-5bcd-b44b-584adc5b0b85

failed due to validation of included YAML snippets, but the errors appear in the middle of the output, making it not obvious where the error was. Ideally we can bring this error message closer to the end of the output, or at least indicate what failed at the end.

@phlax

### LINKED ISSUE #15552: Flake8 linter in CI is trying to use python 2
### description

the flake8 linter in CI is trying to use python 2 and failing

its also not failing CI when it fails - related #15313 #15456

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: ci: Separate format checks
Additional Description:

This PR resolves a few CI issues

- fixes broken flake8 test in CI
- adds a cleanup for python linting that should have failed
- improves error feedback for config validation fail 
- splits format checks that do not currently provide any autofixes
- adds `noshow_progress` and `noshow_loading_progress` flags to bazel in ci (see https://kevin.burke.dev/kevin/bazel-tests-on-travis-ci/)

it also provides a place to add general checks for text (code) files #15442 

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #15313 Fix #15456 Fix #15552 
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: ci/format_pre.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+}
+
+trap trap_errors ERR
+trap exit 1 INT
+
+CURRENT=shellcheck
+./tools/code_format/check_shellcheck_format.sh check
+
+CURRENT=configs
+bazel run "${BAZEL_BUILD_OPTIONS[@]}" //configs:example_configs_validation
```
Comment (phlax) [inline ci/format_pre.sh:23]: not sure this has any bazel build options - probs needs to use do_ci for that

File: .azure-pipelines/pipelines.yml [hunk 2]
```diff
@@ -13,8 +13,22 @@ pr: none
...
+            env:
+              ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
+              BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
+              BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
+              GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)
+            displayName: "Run format pre-checks"
+
       - job: format
-        dependsOn: [] # this removes the implicit dependency on previous stage and causes this to run in parallel.
+        dependsOn: ["format_pre"]
```
Comment (phlax) [inline .azure-pipelines/pipelines.yml:31]: not sure if this should just run parallel

File: ci/do_ci.sh [hunk 3]
```diff
@@ -397,12 +397,13 @@ elif [[ "$CI_TARGET" == "bazel.fuzz" ]]; then
...
   bazel_with_collection test "${BAZEL_BUILD_OPTIONS[@]}" --config=asan-fuzzer "${FUZZ_TEST_TARGETS[@]}" --test_arg="-runs=10"
   exit 0
+elif [[ "$CI_TARGET" == "format_pre" ]]; then
+  BAZEL_BUILD_OPTIONS="${BAZEL_BUILD_OPTIONS[*]}" ./ci/format_pre.sh
 elif [[ "$CI_TARGET" == "fix_format" ]]; then
   # proto_format.sh needs to build protobuf.
   setup_clang_toolchain
 
   echo "fix_format..."
-  ./tools/code_format/check_shellcheck_format.sh fix
```
Comment (phlax) [inline ci/do_ci.sh:405]: we lose the shellcheck autofix here but atm it doesnt actually apply any diff/fix (the fixes are unreliable and diffing is disabled)

File: ci/build_setup.sh [hunk 4]
```diff
@@ -97,6 +97,7 @@ BAZEL_BUILD_OPTIONS=(
   "--show_task_finish"
   "--experimental_generate_json_trace_profile"
   "--test_output=errors"
+  "--noshow_progress"
```
Comment (phlax) [inline ci/build_setup.sh:100]: not sure if we also want to add `noshow_loading_progress`

**Comment by phlax** [comment]
im not sure if this is the best way to split the format checks, for example, we will probably add a diff to the python checks, and this separates them partly on not having an autofix

i think for now this is better than what we have tho

File: ci/build_setup.sh (hunk 4 above)
Comment (phlax) [reply ci/build_setup.sh:100]: added

File: ci/do_ci.sh (hunk 3 above)
Comment (htuch) [reply ci/do_ci.sh:405]: How is this related to the objective of this change?

Comment (phlax) [reply ci/do_ci.sh:405]: shellcheck runs fast and the output is buried in logs with existing setup

Comment (phlax) [reply ci/do_ci.sh:405]: also with current format check it runs and if *any* fails it runs again with fix code

this means that if shellcheck fails it re-runs all the other checkers even tho shellcheck wont provide any diff

File: tools/api_versioning/generate_api_version_header_test.py [hunk 5]
```diff
@@ -32,12 +32,12 @@ def tearDown(self):
         pathlib.Path(self._temp_fname).unlink()
 
     # General success pattern when valid file contents is detected.
-    def SuccessfulTestTemplate(self, output_string, current_version: ApiVersion,
-                               oldest_version: ApiVersion):
+    def successful_test_template(self, output_string, current_version: ApiVersion,
```
Comment (htuch) [inline tools/api_versioning/generate_api_version_header_test.py:35]: This was missed because flake8 wasn't running properly before?

**Review by htuch — COMMENTED** [review]
LGTM modulo comments.

File: tools/api_versioning/generate_api_version_header_test.py (hunk 5 above)
Comment (phlax) [reply tools/api_versioning/generate_api_version_header_test.py:35]: yep

**Review by htuch — APPROVED** [review]
LGTM, thanks!
