### PR TITLE
test: fix flake in ssl_integration_test and future-proof

### LINKED ISSUE #3309: SslCaptureIntegration.TestTwoRequestsWithBinaryProto flaky
Looks like it fails 4% of the time with native bazel (can't say anything about docker)

bazel test test/integration:ssl_integration_test --runs_per_test=200

### PR DESCRIPTION
**Pull request by alyssawilk**
Fixes #3309, and generally makes sendRequestAndWaitForResponse into a function which isn't test flakes waiting to happen.

Risk Level: Low
Testing: bazel test test/integration:ssl_integration_test --runs_per_test=200  ; bazel test test/integration:all --runs_per_test=10

### CODE REVIEW

File: test/integration/http_integration.cc [hunk 1]
```diff
@@ -189,6 +191,7 @@ void HttpIntegrationTest::sendRequestAndWaitForResponse(Http::TestHeaderMapImpl&
                                                         uint32_t request_body_size,
                                                         Http::TestHeaderMapImpl& response_headers,
                                                         uint32_t response_size) {
+  response_.reset(new IntegrationStreamDecoder(*dispatcher_));
```
Comment (htuch) [inline test/integration/http_integration.cc]: Sure, this is a bit safer, I'll update my PR, as there are cleanups I'd also like, but I might as well do them.
