### PR TITLE
fix uhv underscore header sanitization use-after-free path

### LINKED ISSUE #44032: uhv: use-after-free read in sanitizeHeadersWithUnderscores with duplicate underscore headers
## summary

`HeaderValidator::sanitizeHeadersWithUnderscores()` stores header names as non-owning `absl::string_view` references and then removes headers from the header map while iterating. if the request contains duplicate header names with underscores, later iterations construct a `LowerCaseString` from a dangling view, producing a use-after-free read.

**callsite:** `source/extensions/http/header_validators/envoy_default/header_validator.cc:631-652`

## prerequisites

- UHV enabled in build/runtime (`envoy.reloadable_features.enable_universal_header_validator`)
- `headers_with_underscores_action: DROP_HEADER` configured in HTTP protocol options

## root cause

the function collects header names with underscores into `std::vector<absl::string_view>`. it then iterates and calls `header_map.remove(LowerCaseString(name))` for each. when two entries refer to the same backing storage (duplicate header names), the first removal frees the storage and the second iteration reads from a dangling view.

## reproduction

send a request with duplicate header names containing underscores (e.g. `x_foo` twice) through an envoy instance with UHV enabled and `DROP_HEADER` configured. under ASAN the heap-use-after-free read is deterministic.

## suggested fix

change the collected names from `absl::string_view` to `std::string` (owning copies) so that removals don't invalidate remaining references:

```diff
-  std::vector<absl::string_view> drop_headers;
+  std::vector<std::string> drop_headers;
   header_map.iterate([&drop_headers](const ::Envoy::Http::HeaderEntry& header_entry)
                          -> ::Envoy::Http::HeaderMap::Iterate {
     const absl::string_view header_name = header_entry.key().getStringView();
     if (absl::StrContains(header_name, '_')) {
-      drop_headers.push_back(header_name);
+      drop_headers.emplace_back(header_name);
     }

     return ::Envoy::Http::HeaderMap::Iterate::Continue;
   });
```

alternatively, deduplicating names before iterating and mutating the map would also prevent the dangling reference.

happy to open a PR with the fix + a regression test if that's preferred.

### PR DESCRIPTION
**Pull request by Achieve3318**
## Summary

This PR fixes a potential use-after-free path in underscore-header sanitization for Envoy default UHV when `headers_with_underscores_action` is `DROP_HEADER`.

In `sanitizeHeadersWithUnderscores()`, header names were collected as non-owning `absl::string_view` values and then removed from the same header map. With duplicate underscore headers (for example, `x_foo` appearing multiple times), removing one header can invalidate storage referenced by later views.

This change stores owning copies of header names (`std::string`) before mutation, preventing reads from dangling references during removal.

Fixes: #44032

## Changes

- Updated:
  - `source/extensions/http/header_validators/envoy_default/header_validator.cc`
- Replaced:
  - `std::vector<absl::string_view>` with `std::vector<std::string>`
  - `push_back(header_name)` with `emplace_back(header_name)`
- Added regression tests for duplicate underscore headers:
  - `test/extensions/http/header_validators/envoy_default/http1_header_validator_test.cc`
  - `test/extensions/http/header_validators/envoy_default/http2_header_validator_test.cc`

## Test Plan

- Ran:
  - `//test/extensions/http/header_validators/envoy_default:http1_header_validator_test`
  - `//test/extensions/http/header_validators/envoy_default:http2_header_validator_test`
- Both passed locally.

### CODE REVIEW

**Comment by Achieve3318** [comment]
hi, @paul-r-gall Please review my PR

File: source/extensions/http/header_validators/envoy_default/header_validator.cc [hunk 1]
```diff
@@ -634,12 +634,14 @@ void HeaderValidator::sanitizeHeadersWithUnderscores(::Envoy::Http::HeaderMap& h
...
-  std::vector<absl::string_view> drop_headers;
+  // Store owning copies because removing one duplicate header can free the
+  // underlying storage for another matching entry.
+  std::vector<std::string> drop_headers;
   header_map.iterate([&drop_headers](const ::Envoy::Http::HeaderEntry& header_entry)
                          -> ::Envoy::Http::HeaderMap::Iterate {
     const absl::string_view header_name = header_entry.key().getStringView();
     if (absl::StrContains(header_name, '_')) {
-      drop_headers.push_back(header_name);
+      drop_headers.emplace_back(header_name);
```
Comment (wbpcode) [inline source/extensions/http/header_validators/envoy_default/header_validator.cc]: rather than keep a copy, could we keep header name in a absl::flat_hash_set?

**Comment by Achieve3318** [comment]
@wbpcode Please review my PR again. Thank your for your review

File: source/extensions/http/header_validators/envoy_default/header_validator.cc [hunk 2]
```diff
@@ -634,19 +635,21 @@ void HeaderValidator::sanitizeHeadersWithUnderscores(::Envoy::Http::HeaderMap& h
...
-  std::vector<absl::string_view> drop_headers;
+  // Store owning copies because removing one duplicate header can free the
+  // underlying storage for another matching entry. We only need unique names.
+  absl::flat_hash_set<std::string> drop_headers;
   header_map.iterate([&drop_headers](const ::Envoy::Http::HeaderEntry& header_entry)
                          -> ::Envoy::Http::HeaderMap::Iterate {
     const absl::string_view header_name = header_entry.key().getStringView();
     if (absl::StrContains(header_name, '_')) {
-      drop_headers.push_back(header_name);
+      drop_headers.emplace(header_name);
```
Comment (wbpcode) [inline source/extensions/http/header_validators/envoy_default/header_validator.cc:647]: Sorry, I may didn't make it clear. I mean use an `absl::flat_hash_set<absl::string_view> drop_headers;` to keep the header key, then I think it should also could eliminate the use-after-free?

**Comment by Achieve3318** [comment]
@wbpcode , Sorry for my mistake. I have fixed again. please check again. Thank you

**Comment by phlax** [comment]
@Achieve3318 could you merge main please

@wbpcode i think this is waiting on you

File: source/extensions/http/header_validators/envoy_default/header_validator.cc (hunk 2 above)
Comment (wbpcode) [reply source/extensions/http/header_validators/envoy_default/header_validator.cc:647]: Could we use the `absl:flat_hash_set<absl::string_view>` as the type of drop_headers? Then we needn't to create a copy for these headers?

Before the headers are removed, the key will be valid, after the related headers are removed, the key won't be used?

So, use a `absl:flat_hash_set<absl::string_view>` should be safe?

**Review by wbpcode — COMMENTED** [review]
Sorry for the delay. I didn't handle the GitHub notifications for weeks except they slack me.

FYI, feel free to slack me at Envoy slack.

**Comment by mathetake** [comment]
@Achieve3318 this seems waiting for your to address the comment by @wbpcode

**Review by wbpcode — DISMISSED** [review]

**Review by wbpcode — APPROVED** [review]

**Comment by HusseinKabbout** [comment]
Will this be backported to 1.38?
