### PR TITLE
network: Conns with the same local/remote address are local

### LINKED ISSUE #7839: FilterChainMatch source_type LOCAL doesn't match local connections
*Description*:
FilterChainMatch has an option source_type that can be (from [docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener/listener.proto#envoy-api-enum-listener-filterchainmatch-connectionsourcetype)):

```
ANY - (DEFAULT) ⁣Any connection source matches.
LOCAL - ⁣Match a connection originating from the same host.
EXTERNAL - ⁣Match a connection originating from a different host.
```

If I set the option to `LOCAL` I would expect a connection from `100.96.4.33:48158` to `100.96.4.33:9094` to match and be considered local since `100.96.4.33==100.96.4.33`.  It does not.  I have attached the listener config below, I can see in the logs that Envoy is skipping the `fc-0` listener filter chain I expect and instead matching the fallthrough `fc-1` listener filter chain.

*Repro steps*:
1. Create a listener with a match for `source_type local`, such as the following:

```
{
  "version_info": "2019-08-06T18:27:01Z/2",
  "listener": {
    "name": "100.96.4.33_9094",
    "address": {
      "socket_address": {
        "address": "100.96.4.33",
        "port_value": 9094
      }
    },
    "filter_chains": [
      {
        "filter_chain_match": {
          "source_type": "LOCAL"
        },
        "filters": [
          {
            "name": "mixer",
            ...
          },
          {
            "name": "envoy.tcp_proxy",
            "config": {
              "access_log": [
                {
                  "name": "envoy.file_access_log",
                  "config": {
                    "format": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%DYNAMIC_METADATA(istio.mixer:status)%\" \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% fc-0\n",
                    "path": "/dev/stdout"
                  }
                }
              ],
              "stat_prefix": "inbound|9094|server|kafka-svc.kafka.svc.cluster.local",
              "cluster": "inbound|9094|server|kafka-svc.kafka.svc.cluster.local"
            }
          }
        ]
      }
  ]
  ...
}
```

2. If you connect from `100.96.4.33` to `100.96.4.33:9094` through Envoy, expect it to match this listener filter chain and see a log message ending in `fc-0` from the `envoy.file_access_log`

3. Instead, see it not match this listener filter chain; it may match another depending on your configuration (for me, it matched `fc-1` in the detailed full listener dump attached).

```
kafka-0 istio-proxy [2019-08-06T18:37:03.346Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.96.4.33:9094 100.96.4.33:37796 - fc-1
kafka-0 istio-proxy [2019-08-06T18:37:03.499Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.96.4.33:9094 100.96.4.33:37802 - fc-1
kafka-0 istio-proxy [2019-08-06T18:37:03.837Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.96.4.33:9094 100.96.4.33:37810 - fc-1
kafka-0 istio-proxy [2019-08-06T18:37:04.154Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.96.4.33:9094 100.96.4.33:37816 - fc-1
kafka-0 istio-proxy [2019-08-06T18:37:04.480Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.96.4.33:9094 100.96.4.33:37822 - fc-1
kafka-0 istio-proxy [2019-08-06T18:37:04.794Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.96.4.33:9094 100.96.4.33:37828 - fc-1
```

*Notes*
I am creating the Envoy configuration using an Istio build that I am developing in but I do not believe this is an Istio-specific problem.

I believe I've identified the root cause and I'll open a separate PR with my proposed fix.

### PR DESCRIPTION
**Pull request by andrewjjenkins**
**Description:** Connections with the same local/remote address should be considered local for the purposes of filter chain matching, but are currently considered remote (unless other criteria, like loopback addresses, make them local).

**Risk Level:** Low
  - The affected function `Utility::isLocalConnection()` is only called from the filter chain matcher.
  - The behavior before seems to me to be incorrect, so I do not believe anyone would be unpleasantly surprised by this change.
  - Covered by existing unit tests (with fixes)

**Testing:** Fixed unit tests, added new checks.
**Docs Changes:** None, this makes us correctly honor our docs.
**Release Notes:** None proposed, I'm OK with a note that this bug was fixed if that's desireable.
**Fixes #7839**

Before this commit, a connection was considered local if any true:

  1. It was Envoy::Network::Address::Type::Pipe
  2. Remote address is loopback
  3. The pointer to the local address was the same as the pointer to the
     remote address (probably not intentional).
  4. The pointer to the local address was the same as the pointer to a
     wrapper around an address we got out of `getifaddrs()` (probably not
     intentional)

(from https://github.com/envoyproxy/envoy/blob/master/source/common/network/utility.cc#L241-L251 )

Condition 3 and 4 were probably intended to call
Envoy::Network::Address::operator==() but because the "==" sign is
between two SharedPtrs, it is actually checking that the pointers are
equal (both are pointing at the same Envoy::Network::Address).  There's
an unfortunate aligned glitch in the unit test that obfuscates this for
condition 3, and condition 4 was not covered by any tests.

As implemented, this causes the
listener.FilterChainMatch.ConnectionSourceType LOCAL to not match
connections that I consider local (like connections from "4.4.4.4:1234"
to "4.4.4.4:4321").

I think a better condition 3 would be (and probably close to what was
intended):

  3. The local IP address is the same as the remote IP address, the
ports do not have to match.

This commit adjusts Utility::isLocalConnection() and helpers to achieve
that.  Then removes the broken condition 4 entirely.

First, fix the bug in the unit test where socket.localAddress() on the
mock returned remote_addr instead of local_addr.  We didn't have any
test cases that EXPECT_TRUE() for the addresses matching (they all rely
on Pipe or isLoopbackAddress()), so we didn't catch this issue before.

Next would be to change this pointer comparison:
```
  remote_address == socket.localAddress()
```
to actually invoke Address::operator==():
```
  *remote_address == *socket.localAddress()
```

I made this change locally and confirmed that we now invoke operator==()
but this still won't handle the case that the IP address matches but the
ports are different ("4.4.4.4:1234" to "4.4.4.4:4321" is local).

So instead convert to use `remote_address->ip()->addressAsString()` to
get the IP address as a string and compare.  We evaluated other options like
directly comparing the bits of the IPv4/v6 but decided against it at this point
since we're already constructing the addressAsString() output anyway.  If it
proves to be a performance problem, a common function to compare the bits
instead of the string could be dropped in with no behavior change.

Signed-off-by: Andrew Jenkins <andrew@volunteers.acasi.org>

### CODE REVIEW

File: test/common/network/utility_test.cc [hunk 1]
```diff
@@ -173,7 +173,7 @@ TEST(NetworkUtility, LocalConnection) {
 
   testing::NiceMock<Network::MockConnectionSocket> socket;
 
-  EXPECT_CALL(socket, remoteAddress()).WillRepeatedly(testing::ReturnRef(local_addr));
+  EXPECT_CALL(socket, localAddress()).WillRepeatedly(testing::ReturnRef(local_addr));
```
Comment (andrewjjenkins) [inline test/common/network/utility_test.cc]: This is a glitch in the unit tests (returning local_addr for calls to remoteAddress()) that obfuscated the fact that isLocalConnection() was accidentally doing pointer comparisons.

File: source/common/network/utility.cc [hunk 2]
```diff
@@ -246,7 +246,8 @@ bool Utility::isLocalConnection(const Network::ConnectionSocket& socket) {
   // connection. However, this is a rare exception and such assumption results in big
   // performance optimization.
   if (remote_address->type() == Envoy::Network::Address::Type::Pipe ||
-      remote_address == socket.localAddress() || isLoopbackAddress(*remote_address)) {
+      remote_address->equalsExceptPort(*socket.localAddress()) ||
+      isLoopbackAddress(*remote_address)) {
```
Comment (andrewjjenkins) [inline source/common/network/utility.cc]: This is the meat of the change

**Comment by mattklein123** [comment]
@PiotrSikora @silentdai PTAL

**Comment by silentdai** [comment]
Sorry I missed the previous notification!
`isLocalConnection` is invoked after the local address is restored. It works perfectly. Thanks!

/lgtm
/approve

**Comment by silentdai** [comment]
btw if you have 2 ip A and B on one machine, A can talk to B "locally". 
There might be alternative solution other than this envoy LOCAL matcher.

File: include/envoy/network/address.h [hunk 3]
```diff
@@ -104,6 +104,7 @@ class Instance {
   virtual ~Instance() = default;
 
   virtual bool operator==(const Instance& rhs) const PURE;
+  virtual bool equalsExceptPort(const Instance& rhs) const PURE;
```
Comment (mattklein123) [inline include/envoy/network/address.h]: IMO this is an abstraction leak to expose port up to this level. I would remove this interface change.

File: source/common/network/utility.cc (hunk 2 above)
Comment (mattklein123) [reply source/common/network/utility.cc]: Instead of trying to do this via an interface method, I would just do it here directly via testing if the addresses are IP addresses, and if so, then testing if the IP addresses are equal. Also, please update the comment above to talk about what is considered a local connection (similar to your PR description).

File: source/common/network/utility.cc [hunk 4]
```diff
@@ -240,16 +240,32 @@ Address::InstanceConstSharedPtr Utility::getLocalAddress(const Address::IpVersio
 
 bool Utility::isLocalConnection(const Network::ConnectionSocket& socket) {
   const auto& remote_address = socket.remoteAddress();
-  // Before calling getifaddrs, verify the obvious checks.
-  // Note that there are corner cases, where remote and local address will be the same
-  // while the client is not actually local. Example could be an iptables intercepted
-  // connection. However, this is a rare exception and such assumption results in big
-  // performance optimization.
+  // Before calling getifaddrs, verify the obvious checks. These are local:
```
Comment (andrewjjenkins) [inline source/common/network/utility.cc]: Updated comment per @mattklein123 's request.
I removed note about corner case as I feel that if something like iptables has made Envoy see the same remote and local IP addresses, then we are expected to treat it as local; it's not a corner case. I'm also fine with putting it back.

File: source/common/network/utility.cc [hunk 5]
```diff
@@ -272,7 +287,7 @@ bool Utility::isLocalConnection(const Network::ConnectionSocket& socket) {
       const auto local_address = Address::addressFromSockAddr(
           *addr, (af_look_up == AF_INET) ? sizeof(sockaddr_in) : sizeof(sockaddr_in6));
 
-      if (remote_address == local_address) {
+      if (*remote_address == *local_address) {
```
Comment (andrewjjenkins) [inline source/common/network/utility.cc]: This comparison from before is also wrong I believe, as Address::addressFromSockAddr() returns a SharedPtr, so this is a pointer comparison that is never going to be true.

I couldn't get the isLocalAddress tests to fail with or without this change, I am not sure this code is well-exercised (and that's probably hard without a mock for getifaddrs).

Which raises a question for me: should we remove the getifaddrs() code entirely?  Unless I'm confused (totally possible :-) ) I don't think anyone ever got a return of true out of this block before.  Seems like calling getifaddrs for each isLocalAddress() call could be expensive.  And checking if the local and remote IP addresses match on a connected socket you created meets my definition of "local".

File: source/common/network/utility.cc (hunk 2 above)
Comment (andrewjjenkins) [reply source/common/network/utility.cc]: done

File: source/common/network/utility.cc (hunk 5 above)
Comment (mattklein123) [reply source/common/network/utility.cc]: Yeah from looking at the coverage report, this code has no coverage and it is clearly broken as you point out (nice find): https://storage.googleapis.com/envoy-coverage/report-master/coverage/proc/self/cwd/source/common/network/utility.cc.html

Given that it never worked and we have no coverage, I would be inclined to delete all of it until someone wants to bring it back. @envoyproxy/maintainers any thoughts here?

File: source/common/network/utility.cc [hunk 6]
```diff
@@ -240,16 +240,32 @@ Address::InstanceConstSharedPtr Utility::getLocalAddress(const Address::IpVersio
...
+  // Before calling getifaddrs, verify the obvious checks. These are local:
+  // - Pipes
+  // - Sockets to a loopback address
+  // - Sockets where the local and remote address (ignoring port) are the same
   if (remote_address->type() == Envoy::Network::Address::Type::Pipe ||
-      remote_address == socket.localAddress() || isLoopbackAddress(*remote_address)) {
+      isLoopbackAddress(*remote_address)) {
     return true;
   }
+  const auto local_ip = socket.localAddress()->ip();
```
Comment (mattklein123) [inline source/common/network/utility.cc]: I think you can simplify this code by just comparing remote_address->ip()->addressAsString() == local_address->ip()->addressAsString(). If we deeply care about speed, I might go ahead and add an equality comparison on the Ip interface, and then deal with it inside there so we don't duplicate this code elsewhere?

Comment (andrewjjenkins) [reply source/common/network/utility.cc]: addressAsString() is fine with me.

Equality comparison on Ip can be done, but I have some hesitation.  I think that means adding `operator==() PURE` to [Envoy::Network::Address::Ip](https://github.com/envoyproxy/envoy/blob/master/include/envoy/network/address.h#L53), and for my purposes, making it compare IPs but *not ports*, even though port is a member of the Ipv4/Ipv6 implementation.  But, Envoy::Network::Address::Instance would have `operator==() PURE` that for IPs, compares it but [*with ports*](https://github.com/envoyproxy/envoy/blob/master/source/common/network/address_impl.cc#L217).

If I was a programmer that just showed up, I would be surprised if `*address1 == *address2` did compare ports, but `*address1->ip() == *address2->ip()` did not compare ports, especially since the port is a property of `*address1->ip()` (so `*address1->ip()->port() != *address2->ip()->port()`).  Basically I think since port is a property of the IP address, it's gotta be reflected in all `operator==()` up and down the class hierarchy the same.

My complaint though is a style consideration and I'm new here so I'm happy to do it if you're OK with it.

Other options:
1. Make the equality comparison not named `operator==()`, make it some other method (`addressEquals()` on the Ip class is a better name than `equalsExceptPort()` on Address).
2. Remove `port` from the Address.  Maybe ports are on some new thing, maybe Sockaddrs, but not Ip.  Feels like this is a pretty big change.

I'll update to use `addressAsString()` so we can take a look.  I'm OK with any of these choices though.

Comment (mattklein123) [reply source/common/network/utility.cc]: Hmm, I just looked and `addressAsString()` includes port, so I don't think that is going to work either?

Maybe just factor that code out into a utility function that we can test separately? You could make a function that takes 2 `Address::Ip` and returns whether they are equal without ports? WDYT?

Comment (andrewjjenkins) [reply source/common/network/utility.cc]: Turns out that `addressAsString()` does not include port, it's only the IP address.  `address->asString()` does include the IP and port.  Pushed code that works using `addressAsString()` (and double-checked locally that if I mangle an address but not a port, the string comparison fails as expected).

Gory details: `addressAsString()` returns the private member `friendly_address_` which is initialized with only the IPv4/IPv6 as a string (excluding port).  `friendly_name_` includes the IPv4/IPv6 **and** the port.

https://github.com/envoyproxy/envoy/blob/cb15cc3d2010aff77d6e022ddf6d723fa8becbc0/source/common/network/address_impl.cc#L178-L189

So, the code that I just pushed uses `addressAsString()` and works correctly.  I am also not terrified of the performance cost of string comparison especially since we are already always constructing the strings at `Ipv4`/`Ipv6` construction time.

File: source/common/network/utility.cc (hunk 5 above)
Comment (mattklein123) [reply source/common/network/utility.cc]: OK since no one else responded I will make the call to kill this broken code which no one must be using. Let's delete it! Thank you.

**Comment by htuch** [comment]
@andrewjjenkins @mattklein123 @PiotrSikora how does this work with IP_FREEBIND? Also, what about NAT? I'm wondering if there are any corner conditions that we've not considered with the new assumption.

**Comment by htuch** [comment]
@andrewjjenkins I'm just doing some security due diligence work, hence the followup. I agree that your PR is improving the existing situation. 

Looking at the problem more broadly, I think we just have a "truth in advertising" issue. This can lead to operator confusion and potential security issues due to a mismatch of intent and operation.

We claim that we are providing a local connection detection, but it's not always true:
* Sometimes local connections won't be LOCAL, see your example of the two local interfaces.
* Sometimes remote connection might be LOCAL. I don't have strong evidence for this, but I suspect clever enough configuration of things like NAT, IP_FREEBIND or network namespaces could do something like this.

I think we could resolve all of ^^ by renaming this to `SAME_IP` in the v3 xDS APIs, to avoid user confusion. The operator needs to decide the implications of `SAME_IP`, not Envoy.

We should also rename `Utility::isLocalConnection`, this is a mine waiting to be encountered if we start depending on this elsewhere in the code.

@andrewjjenkins @nickolaev @georgi-d @PiotrSikora @mattklein123 WDYT?

**Comment by mattklein123** [comment]
> WDYT?

These suggestions make sense to me.

**Comment by nickolaev** [comment]
Makes sense to me too.
