### PR TITLE
xds: introduce initial_fetch_timeout option to limit initialization time

### LINKED ISSUE #5862: Envoy is stuck in PRE_INITIALIZING state when management server doesn't respond
This is a follow up to a previous issue: https://github.com/envoyproxy/envoy/issues/5622
First of all, thanks for that fix. It did help for the case, when management server doesn't accept TCP connection.

Hovewer, the problem still exists when management server accepts the connection, but doesn't send any response.
Envoy will be in `PRE_INITIALIZING` state forever in that case.

We tried to set `timeout` parameter (https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/grpc_service.proto#core-grpcservice), but it changes nothing.

The problem can be easily reproduced by replacing the management server with `nc`:

1. Run nc in listening mode `nc -l 50000`
2. Run envoy with config presented at the end of the post. 
3. In envoy admin, you will see that envoy is in `PRE_INITIALIZING` state forever
4. In nc output you will see, that envoy sent xDS request. 

The real world scenario for this is a heavily loaded management server, that manages to accept TCP connection, but fails to deliver response in acceptable time. 

I think it would be nice to be able to configure Envoy in a way that it would be immune to any problem with management server. It should work with static-config-only in that case.

Tested on commit `f9107b2`

```yaml
node:
  id: "node-1"
  cluster: "nodes"
static_resources:
  listeners:
  - name: full_static_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 7000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: full_static_http
          route_config:
            name: full_static_routes
            virtual_hosts:
            - name: route
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: "static_service"
          http_filters:
          - name: envoy.router
  clusters:
  - name: static_service
    type: STATIC
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8080
    connect_timeout: 1s
  - name: xds
    type: static
    hosts:
    - socket_address:
        address: 192.168.65.2  # netcat listen on this address
        port_value: 50000
    connect_timeout: 1s
    http2_protocol_options: {}

dynamic_resources:
  cds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
      - envoy_grpc:
          cluster_name: xds
        timeout: 1s

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 6000
```

### PR DESCRIPTION
**Pull request by MarcinFalkowski**
xDS: introduce initial_fetch_timeout option to limit server initialization time

Signed-off-by: Marcin Falkowski <marcin.falkowski@allegro.pl>

*Description*: 

Introduce new optional configuration parameter `initial_fetch_timeout` to ConfigSource proto.
This parameter can be used to limit time Envoy spend on initialization of CDS, LDS and RDS.
Enabling this timeout prevents Envoy from being stuck in PRE_INITIALIZING or INITIALIZING phase, as described in #5862.

*Risk Level*: Low (optional feature, disabled by default)
*Testing*: manual testing, unit tests
*Docs Changes*: add new parameter `initial_fetch_timeout` to ConfigSource proto
*Release Notes*: Added

Fixes #5862

### CODE REVIEW

File: source/common/router/rds_impl.cc [hunk 1]
```diff
@@ -73,6 +73,24 @@ RdsRouteConfigSubscription::RdsRouteConfigSubscription(
...
+  }
+}
+
+void RdsRouteConfigSubscription::initialize(std::function<void()> callback) {
+  initialize_callback_ = callback;
+  if (initialization_timeout_.count() > 0) {
+    ASSERT(initialization_timeout_timer_);
+    initialization_timeout_timer_->enableTimer(initialization_timeout_);
+  }
+  subscription_->start({route_config_name_}, *this);
```
Comment (htuch) [inline source/common/router/rds_impl.cc]: Do you think we could put the timeout inside the `subscription_->start()`? That way we only need to implement once for gRPC and once for REST.

Comment (MarcinFalkowski) [reply source/common/router/rds_impl.cc]: I am trying to implement this. 
Do you think, in that case, we should move `initial_fetch_timeout` parameter to `config_source.api_config_source` or leave it in `config_source`? 

If we leave it on `config_source` level, it could be set for "path" config source type, but we don't want that - it will be not implemented for that type. Maybe it is not a problem if we mention that in docs?

If we move it to `api_config_source`, there will be a problem with ADS, because i believe we do not have access to ads mux config in [subscription_factory.h](/envoyproxy/envoy/blob/master/source/common/config/subscription_factory.h#L87). Moreover LDS, RDS and CDS would have to share the same timeout.

Comment (htuch) [reply source/common/router/rds_impl.cc]: I think it's fine to leave this on `config_source`. While it won't make sense for all source types, we can add explicit checks to reject or just ignore. Also, even for file based options, timeouts might make sense, since they use inotify and watch for updates.

Comment (MarcinFalkowski) [reply source/common/router/rds_impl.cc]: Done, I moved timeout to Subscription.

I also looked closer at [filesystem_subscription_impl.h](https://github.com/envoyproxy/envoy/blob/master/source/common/config/filesystem_subscription_impl.h) and I think (correct me if I'm wrong) it doesn't make much sense to implement the timeout there. I think filesystem subscription always calls `onConfigUpdate`/`onConfigUpdateFailed` immediately after it starts.

File: test/common/config/http_subscription_impl_test.cc [hunk 2]
```diff
@@ -42,6 +51,45 @@ TEST_F(HttpSubscriptionImplTest, BadJsonRecovery) {
   verifyStats(3, 1, 0, 1, 7148434200721666028);
 }
 
+TEST_F(HttpSubscriptionImplInitFetchTimeoutTest, InitialFetchTimeout) {
```
Comment (htuch) [inline test/common/config/http_subscription_impl_test.cc]: Arguably, we should have these tests in https://github.com/envoyproxy/envoy/blob/master/test/common/config/subscription_impl_test.cc as common and provide enough machinery in the harnesses to support a common test pattern.

File: test/common/config/delta_subscription_impl_test.cc [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+using testing::NiceMock;
+using testing::Return;
+
+namespace Envoy {
+namespace Config {
+namespace {
+
+typedef DeltaSubscriptionImpl<envoy::api::v2::ClusterLoadAssignment> DeltaEdsSubscriptionImpl;
+
+class DeltaSubscriptionImplTest : public testing::Test {
```
Comment (htuch) [inline test/common/config/delta_subscription_impl_test.cc]: I would advocate to factor this into harness/test as done for the other config tests. That way, we can reuse common tests (and write specialized ones where needed).

File: source/common/router/rds_impl.cc (hunk 1 above)
Comment (htuch) [reply source/common/router/rds_impl.cc]: Sure, this is fine for now, it's conceivable that we would want to timeout on inotify, but I doubt anyone would use it today.

File: test/common/config/http_subscription_impl_test.cc (hunk 2 above)
Comment (MarcinFalkowski) [reply test/common/config/http_subscription_impl_test.cc]: I find it hard to implement these test cases in `subscription_impl_test.cc`, because we run that test against `SubscriptionType::Filesystem` too, which doesn't implement `initial_fetch_timeout`. So it is not 100% common test pattern.

Comment (htuch) [reply test/common/config/http_subscription_impl_test.cc]: Can't we just fake the filesystem timeout behavior in the harness?

Comment (htuch) [reply test/common/config/http_subscription_impl_test.cc]: You can also add an initial line that decides to skip that test for filesystem implementations (based on checking `GetParam()`).

File: source/common/config/delta_subscription_impl.h [hunk 4]
```diff
@@ -120,6 +122,7 @@ class DeltaSubscriptionImpl
   void onConfigUpdate(const Protobuf::RepeatedPtrField<envoy::api::v2::Resource>& added_resources,
                       const Protobuf::RepeatedPtrField<std::string>& removed_resources,
                       const std::string& version_info) {
+    disableInitFetchTimeoutTimer();
```
[the remark this answers is not in the document]
Comment (MarcinFalkowski) [reply source/common/config/delta_subscription_impl.h]: Agree, it was redundant. Deleted.

File: test/common/config/http_subscription_impl_test.cc (hunk 2 above)
Comment (MarcinFalkowski) [reply test/common/config/http_subscription_impl_test.cc]: I did as you suggested. `initial_fetch_timeout` is now tested by one set of tests for all Subscription implementations. Filesystem subscription harness has fake/empty timeout behavior/expectations

File: test/common/config/delta_subscription_impl_test.cc (hunk 3 above)
Comment (MarcinFalkowski) [reply test/common/config/delta_subscription_impl_test.cc]: I created delta subscription test harness and attached it to common subscription tests in subscription_impl_test.cc.

**Comment by MarcinFalkowski** [comment]
@htuch should I add release notes for this change?

File: test/common/config/filesystem_subscription_test_harness.h [hunk 5]
```diff
@@ -33,7 +33,11 @@ class FilesystemSubscriptionTestHarness : public SubscriptionTestHarness {
         api_(Api::createApiForTest(stats_store_)), dispatcher_(api_->allocateDispatcher()),
         subscription_(*dispatcher_, path_, stats_, *api_) {}
 
-  ~FilesystemSubscriptionTestHarness() { EXPECT_EQ(0, ::unlink(path_.c_str())); }
+  ~FilesystemSubscriptionTestHarness() {
+    if (::access(path_.c_str(), F_OK) != -1) {
```
Comment (htuch) [inline test/common/config/filesystem_subscription_test_harness.h]: Why is this needed?

Comment (MarcinFalkowski) [reply test/common/config/filesystem_subscription_test_harness.h]: I added a test, where deliverConfigUpdate is never called. So the config file is not even created, and unlink fails. All other tests call deliverConfigUpdate, so it was not a problem until now.

**Comment by MarcinFalkowski** [comment]
Thanks!
