### PR TITLE
http/2: correctly handle stream refusal error

### LINKED ISSUE #13948: Envoy abruptly closes new listener H/2 connection before sending max concurrent streams settings
*Title*: Envoy abruptly closes new listener H/2 connection before sending max concurrent streams settings

*Description*:
When an Envoy listener accepts a new H/2 connection and is configured with a low max concurrent streams limit, there is a race between the client receiving the H/2 max concurrent streams setting from Envoy and the client opening an arbitrary number of streams.
If the clients opens too many streams (in excess of the server's max concurrent streams limit) before receiving the H/2 max concurrent streams settings frame, Envoy closes the connection with a protocol error.

*Repro steps*:
I'm reproducing this behavior with Envoy 1.15 in the following setup:
```Client (load generator) -> Envoy no.2 -> Envoy no.1 -> Go backend```
The listener on Envoy #1 is configured with H/2 max concurrent streams = 5.
Both Envoys are configured with concurrency 1 to help reproduction.

 * Go backend: https://gist.github.com/kryzthov-stripe/6cde4085a564010c252c43ad82de5349 listens on localhost:8080
 * Envoy no.1 configuration: https://gist.github.com/kryzthov-stripe/5552582ac4efd8189ca443ea6bbcd8a9 listens on localhost:10000 and forwards to the Go backend
    ```envoy-static --config-path envoy1.yaml --concurrency 1 --component-log-level connection:trace,http2:trace```
 * Envoy no.2 configuration: https://gist.github.com/kryzthov-stripe/beaa5a5ea9be34a247f2b409ecfc7ccc listens on localhost:20000 and forwards to Envoy #1
    ```envoy-static --config-path envoy2.yaml --concurrency 1 --component-log-level connection:trace,http2:trace```
 * Client: `go get github.com/rakyll/hey` sends 200 requests ~concurrently
    ```hey -c 200 -t 0 http://localhost:20000```

All the 200 requests will fail with HTTP 503:
```
Status code distribution:
  [503]	200 responses
```

The access logs for Envoy no.1 will show 5 requests failed with DPE:
```
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 0 - "-" "hey/0.0.1" "f079c522-298f-43e3-bc9b-c96c239b372c" "localhost:20000" "-" "-" - -
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 0 - "-" "hey/0.0.1" "9893eb75-5097-4474-b521-1e047a8b85df" "localhost:20000" "-" "-" - -
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 0 - "-" "hey/0.0.1" "784ef569-af2b-4876-8fc8-cfd6aa3c5285" "localhost:20000" "-" "-" - -
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 0 - "-" "hey/0.0.1" "2e7cbb58-d4df-4460-a1c8-b981b0b495e5" "localhost:20000" "-" "-" - -
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 1 - "-" "hey/0.0.1" "78a5da2a-6a06-4cef-a382-f6e1692a8318" "localhost:20000" "-" "-" - -
```

The access logs for Envoy no.2 will show 200 requests failed with UC 503s:
```
[2020-11-09T20:04:05.677Z] [-] "GET / HTTP/1.1" 503 UC 0 95 1008 - "-" "hey/0.0.1" "78a5da2a-6a06-4cef-a382-f6e1692a8318" "localhost:20000" "127.0.0.1:10000" "-" - -
```

The Envoy no.1 trace logs show that it handled 5 streams, and identified the 6th stream as invalid, and closed the connection:
```
source/server/configuration_impl.cc:79] loading 1 listener(s)
source/server/configuration_impl.cc:129] loading stats sink configuration
/source/common/runtime/runtime_impl.cc:524] RTDS has finished initialization
y/source/common/upstream/cluster_manager_impl.cc:182] cm init: all clusters initialized
/source/server/server.cc:534] there is no configured limit to the number of allowed active connections. Set a limit via the run
urce/server/server.cc:631] all clusters initialized. initializing init manager
source/server/listener_manager_impl.cc:844] all dependencies initialized. starting workers
urce/server/server.cc:652] starting main dispatch loop
nvoy/source/common/network/connection_impl.cc:506] [C0] socket event: 2
nvoy/source/common/network/connection_impl.cc:607] [C0] write ready
nvoy/source/common/network/connection_impl.cc:506] [C0] socket event: 3
nvoy/source/common/network/connection_impl.cc:607] [C0] write ready
nvoy/source/common/network/connection_impl.cc:544] [C0] read ready. dispatch_buffered_data=false
nvoy/source/common/network/raw_buffer_socket.cc:25] [C0] read returns: 532
nvoy/source/common/network/raw_buffer_socket.cc:38] [C0] read error: Resource temporarily unavailable
source/common/http/http2/codec_impl.cc:1062] [C0] updating connection-level initial window size to 268435456
source/common/http/http2/codec_impl.cc:524] [C0] dispatching 532 bytes
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=4, flags=0
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=4 flags=0 length=30 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=4
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=8, flags=0
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=8 flags=0 length=4 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=8
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=125 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
nvoy/source/common/network/connection_impl.cc:753] [C1] connecting to 127.0.0.1:8080
nvoy/source/common/network/connection_impl.cc:769] [C1] connection in progress
source/common/http/http2/codec_impl.cc:1062] [C1] updating connection-level initial window size to 268435456
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=38 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=37 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=37 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=37 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:763] [C0] invalid frame: Stream was refused on stream 11
nvoy/source/common/network/connection_impl.cc:112] [C0] closing data_to_write=0 type=2
nvoy/source/common/network/connection_impl_base.cc:30] [C0] setting delayed close timer with timeout 1000 ms
nvoy/source/common/network/connection_impl.cc:506] [C1] socket event: 2
nvoy/source/common/network/connection_impl.cc:607] [C1] write ready
nvoy/source/common/network/connection_impl.cc:616] [C1] connected
nvoy/source/common/network/connection_impl_base.cc:44] [C0] triggered delayed close
nvoy/source/common/network/connection_impl.cc:208] [C0] closing socket: 1
```

From a network capture, we can see Envoy no.1 never sent Envoy no.2 a settings.
image
Envoy no.2 still expects the max concurrent streams to be the H/2 default (ie. unlimited), per:
```
   SETTINGS_MAX_CONCURRENT_STREAMS (0x3):  Indicates the maximum number
      of concurrent streams that the sender will allow.  This limit is
      directional: it applies to the number of streams that the sender
      permits the receiver to create.  Initially, there is no limit to
      this value.  It is recommended that this value be no smaller than
      100, so as to not unnecessarily limit parallelism.
```

The *Stream concurrency* section of the H/2 spec seems to indicate that Envoy could simply refuse individual streams (https://tools.ietf.org/html/rfc7540#section-5.1.2).
In particular, the spec doesn't mention that this scenario should lead to a connection error, but merely a stream error:
```
   Endpoints MUST NOT exceed the limit set by their peer.  An endpoint
   that receives a HEADERS frame that causes its advertised concurrent
   stream limit to be exceeded MUST treat this as a stream error
   (Section 5.4.2) of type PROTOCOL_ERROR or REFUSED_STREAM.  The choice
   of error code determines whether the endpoint wishes to enable
   automatic retry (see Section 8.1.4) for details).
```

It seems Envoy no.1 could simple refuse streams in excess to its configured max concurrent streams settings, allowing the client (Envoy no.2) to possibly retry these requests on a different connection/endpoint?

### PR DESCRIPTION
**Pull request by venilnoronha**
Commit Message:
This adds the correct handling for invalid http2 frames with error code `NGHTTP2_ERR_REFUSED_STREAM`.

Additional Description:
The following error is typically seen when this occurs, and without this fix the connection is closed abruptly.
```
[2021-06-09 08:07:59.705][12][debug][http2] [source/common/http/http2/codec_impl.cc:946] [C2] invalid frame: Stream was refused on stream 3
```

Risk Level: Low
Testing: Added a test
Docs Changes: N/A
Release Notes: Updated
Platform Specific Features: N/A
Fixes #13948

### CODE REVIEW

File: source/common/http/http2/codec_impl.cc [hunk 1]
```diff
@@ -964,6 +969,7 @@ int ConnectionImpl::onInvalidFrame(int32_t stream_id, int error_code) {
       return 0;
     }
   }
+  }
```
Comment (antoniovicente) [inline source/common/http/http2/codec_impl.cc:972]: indentation seems a bit odd.  Could you remove the extra `{}`'s after `case NGHTTP2_ERR_HTTP_MESSAGING:`

File: source/common/http/http2/codec_impl.cc [hunk 2]
```diff
@@ -951,7 +951,12 @@ int ConnectionImpl::onInvalidFrame(int32_t stream_id, int error_code) {
     stream->setDetails(Http2ResponseCodeDetails::get().errorDetails(error_code));
   }
 
-  if (error_code == NGHTTP2_ERR_HTTP_HEADER || error_code == NGHTTP2_ERR_HTTP_MESSAGING) {
+  switch (error_code) {
+  case NGHTTP2_ERR_REFUSED_STREAM:
+    return 0;
```
Comment (antoniovicente) [inline source/common/http/http2/codec_impl.cc:956]: It would be good to runtime guard this change out of abundance of caution.

File: source/common/http/http2/codec_impl.cc [hunk 3]
```diff
@@ -951,7 +951,12 @@ int ConnectionImpl::onInvalidFrame(int32_t stream_id, int error_code) {
     stream->setDetails(Http2ResponseCodeDetails::get().errorDetails(error_code));
   }
 
-  if (error_code == NGHTTP2_ERR_HTTP_HEADER || error_code == NGHTTP2_ERR_HTTP_MESSAGING) {
+  switch (error_code) {
+  case NGHTTP2_ERR_REFUSED_STREAM:
```
Comment (antoniovicente) [inline source/common/http/http2/codec_impl.cc:955]: It would be good to add a stat to track number of refused streams.

File: source/common/http/http2/codec_impl.cc [hunk 4]
```diff
@@ -951,7 +951,12 @@ int ConnectionImpl::onInvalidFrame(int32_t stream_id, int error_code) {
...
+    return 0;
+
+  case NGHTTP2_ERR_HTTP_HEADER:
+  case NGHTTP2_ERR_HTTP_MESSAGING: {
```
Comment (antoniovicente) [inline source/common/http/http2/codec_impl.cc:959]: It would be good to more carefully enumerate error codes that we expect to get past this code and codes that we do not expect to run into.  One example for a code that we probably never want to see is `NGHTTP2_ERR_STREAM_CLOSED`

File: test/common/http/http2/codec_impl_test.cc [hunk 5]
```diff
@@ -1759,6 +1759,41 @@ TEST_P(Http2CodecImplStreamLimitTest, MaxClientStreams) {
...
+
+  // This causes the next stream creation to fail with a "invalid frame: Stream was refused" error.
+  absl::InlinedVector<nghttp2_settings_entry, 1> settings{
+      {NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS, 1}};
+  EXPECT_EQ(0, nghttp2_submit_settings(server_->session(), NGHTTP2_FLAG_NONE, settings.data(),
+                                       settings.size()));
+
+  request_encoder_ = &client_->newStream(response_decoder_);
+  setupDefaultConnectionMocks();
+  EXPECT_TRUE(request_encoder_->encodeHeaders(request_headers, true).ok());
```
Comment (antoniovicente) [inline test/common/http/http2/codec_impl_test.cc:1794]: I think this test is missing some expectations at the end which indicate that the connection refused a stream and the connection is still alive after processing the refused newStream

**Review by antoniovicente — COMMENTED** [review]
cc @yanavlasov 

Many thanks for the fix.  Some comments below related to runtime guards and improvements to handling of other possible error conditions that are currently not explicitly handled.

File: source/common/http/http2/codec_impl.cc (hunk 4 above)
Comment (venilnoronha) [reply source/common/http/http2/codec_impl.cc:959]: I only found `NGHTTP2_ERR_FLOW_CONTROL` and `NGHTTP2_ERR_PROTO` additionally that are being sent via this path. Is `NGHTTP2_ERR_STREAM_CLOSED` being thrown additionally from elsewhere?

**Comment by venilnoronha** [comment]
@antoniovicente thanks for the review! I've addressed your comments in 17cb402. Would you mind taking another look?

File: source/common/runtime/runtime_features.cc [hunk 6]
```diff
@@ -70,9 +70,10 @@ constexpr const char* runtime_features[] = {
     "envoy.reloadable_features.hash_multiple_header_values",
     "envoy.reloadable_features.health_check.graceful_goaway_handling",
     "envoy.reloadable_features.health_check.immediate_failure_exclude_from_cluster",
+    "envoy.reloadable_features.http2_consume_stream_refused_errors",
+    "envoy.reloadable_features.http2_skip_encoding_empty_trailers",
```
Comment (antoniovicente) [inline source/common/runtime/runtime_features.cc:74]: Could you remove `http2_skip_encoding_empty_trailers` from `UNSORTED_FLAGS` in `tools/code_format/check_format.py`

File: docs/root/version_history/current.rst [hunk 7]
```diff
@@ -48,6 +48,7 @@ Bug Fixes
 * cluster: fixed the :ref:`cluster stats <config_cluster_manager_cluster_stats_request_response_sizes>` histograms by moving the accounting into the router
   filter. This means that we now properly compute the number of bytes sent as well as handling retries which were previously ignored.
 * hot_restart: fix double counting of `server.seconds_until_first_ocsp_response_expiring` and `server.days_until_first_cert_expiring` during hot-restart. This stat was only incorrect until the parent process terminated.
+* http: fix erroneous handling of invalid nghttp2 frames with a `NGHTTP2_ERR_REFUSED_STREAM` error.
```
Comment (antoniovicente) [inline docs/root/version_history/current.rst:51]: I would suggest saying something about the old and new behaviors.  I think that on REFUSED_STREAM envoy used to close the H2 upstream connection.  After this change, Envoy will terminate just the refused stream.

File: test/common/http/http2/codec_impl_test.cc [hunk 8]
```diff
@@ -1804,6 +1804,95 @@ TEST_P(Http2CodecImplStreamLimitTest, MaxClientStreams) {
...
+  EXPECT_EQ(0, nghttp2_submit_settings(server_->session(), NGHTTP2_FLAG_NONE, settings.data(),
+                                       settings.size()));
+
+  request_encoder_ = &client_->newStream(response_decoder_);
+  setupDefaultConnectionMocks();
+  EXPECT_THROW_WITH_MESSAGE(request_encoder_->encodeHeaders(request_headers, true).IgnoreError(),
+                            ServerCodecError, "The user callback function failed");
+
+  EXPECT_EQ(0, server_stats_store_.counter("http2.stream_refused_errors").value());
+  EXPECT_EQ(0, server_stats_store_.counter("http2.tx_reset").value());
```
Comment (antoniovicente) [inline test/common/http/http2/codec_impl_test.cc:1891]: The stats below seem a bit off due to the EXPECT_THROW_WITH_MESSAGE above.  In a real proxy, the status returned from dispatch would trigger a connection close which I assume would result in the active stream gauges to go down to 0.  I would suggest adding a comment here and removing these counter/gauge expectations since they are not able to capture the codec connection close behavior.

**Comment by venilnoronha** [comment]
@antoniovicente I've addressed your comments in 2232827. Thanks for reviewing!

**Comment by antoniovicente** [comment]
> @antoniovicente I've addressed your comments in [bbaf3e7](https://github.com/envoyproxy/envoy/commit/bbaf3e7827e23e8fcf3dc930bb4799ff5fd14447). Thanks for reviewing!

Please please please avoid use of force push.  It messes up github code review history and makes your code reviewer's life harder:  comments can end up losing their code ancors, and it's harder to see what code has been reviewed and which hasn't been reviewed.

**Review by antoniovicente — APPROVED** [review]
Thanks!

**Comment by venilnoronha** [comment]
> Please please please avoid use of force push.

Sorry about that. I rebased coz the pipeline was flakey and I wanted to see if any recent commits on main would have fixed it.

**Review by mattklein123 — APPROVED** [review]
Thanks!
