### PR TITLE
upstream: Fix moving EDS hosts between priorities.

### LINKED ISSUE #11517: Assertion failure moving endpoints between priorities
Given a cluster performing http health checks, change the priority of an existing LocalityLbEndpoints containing at least one healthy host from priority >0 to 0.

This results in:
[source/common/upstream/health_checker_base_impl.cc:265] assert failure: interval_timer_ == nullptr && timeout_timer_ == nullptr.

[Test Case](https://github.com/envoyproxy/envoy/files/4751408/envoy-priority-crash.tar.gz)

Discussion on the security group concluded that there's no security issue here, so I'm re-raising it on github for tracking.

Call Stack:
```
[2020-05-27 13:18:39.912][592380][critical][assert] [source/common/upstream/health_checker_base_impl.cc:265] assert failure: interval_timer_ == nullptr && timeout_timer_ == nullptr.
[2020-05-27 13:18:39.912][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x644159a6000909fc
[2020-05-27 13:18:39.912][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-05-27 13:18:39.912][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: c8f330c1f99ee5d89048d52ac98faab2539d5a52/1.15.0-dev/Clean/DEBUG/BoringSSL
[2020-05-27 13:18:39.964][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x5562d0a459cc]
[2020-05-27 13:18:39.964][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #1: __restore_rt [0x7f1d9610f3c0]
[2020-05-27 13:18:40.014][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #2: Envoy::Upstream::HttpHealthCheckerImpl::HttpActiveHealthCheckSession::~HttpActiveHealthCheckSession() [0x5562d02c32c6]
[2020-05-27 13:18:40.062][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #3: Envoy::Upstream::HttpHealthCheckerImpl::HttpActiveHealthCheckSession::~HttpActiveHealthCheckSession() [0x5562d02c3383]
[2020-05-27 13:18:40.114][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #4: Envoy::Upstream::HttpHealthCheckerImpl::HttpActiveHealthCheckSession::~HttpActiveHealthCheckSession() [0x5562d02c341c]
[2020-05-27 13:18:40.168][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #5: std::__1::default_delete<>::operator()() [0x5562d02ec72f]
[2020-05-27 13:18:40.219][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #6: std::__1::unique_ptr<>::reset() [0x5562d02ec6af]
[2020-05-27 13:18:40.268][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #7: std::__1::unique_ptr<>::operator=() [0x5562d02e721d]
[2020-05-27 13:18:40.318][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #8: Envoy::Upstream::HealthCheckerImplBase::addHosts() [0x5562d02d8857]
[2020-05-27 13:18:40.366][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #9: Envoy::Upstream::HealthCheckerImplBase::onClusterMemberUpdate() [0x5562d02d8a3e]
[2020-05-27 13:18:40.417][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #10: Envoy::Upstream::HealthCheckerImplBase::HealthCheckerImplBase()::$_5::operator()() [0x5562d02dc0a8]
[2020-05-27 13:18:40.465][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #11: std::__1::__invoke<>() [0x5562d02dc067]
[2020-05-27 13:18:40.517][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #12: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x5562d02dbff7]
[2020-05-27 13:18:40.564][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #13: std::__1::__function::__alloc_func<>::operator()() [0x5562d02dbfa7]
[2020-05-27 13:18:40.612][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #14: std::__1::__function::__func<>::operator()() [0x5562d02db0d8]
[2020-05-27 13:18:40.659][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #15: std::__1::__function::__value_func<>::operator()() [0x5562cff73fca]
[2020-05-27 13:18:40.708][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #16: std::__1::function<>::operator()() [0x5562cff73ea5]
[2020-05-27 13:18:40.757][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #17: Envoy::Common::CallbackManager<>::runCallbacks() [0x5562cff73d7d]
[2020-05-27 13:18:40.805][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #18: Envoy::Upstream::PrioritySetImpl::runUpdateCallbacks() [0x5562cff6f68e]
[2020-05-27 13:18:40.851][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #19: Envoy::Upstream::PrioritySetImpl::batchHostUpdate() [0x5562d01d5c6c]
[2020-05-27 13:18:40.899][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #20: Envoy::Upstream::EdsClusterImpl::onConfigUpdate() [0x5562d0229cb2]
[2020-05-27 13:18:40.949][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #21: Envoy::Config::GrpcSubscriptionImpl::onConfigUpdate() [0x5562d025f948]
[2020-05-27 13:18:41.000][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #22: Envoy::Config::GrpcMuxImpl::onDiscoveryResponse() [0x5562d0263b9d]
[2020-05-27 13:18:41.047][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #23: Envoy::Config::GrpcStream<>::onReceiveMessage() [0x5562cff0f8b1]
[2020-05-27 13:18:41.096][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #24: Envoy::Grpc::AsyncStreamCallbacks<>::onReceiveMessageRaw() [0x5562cff0f699]
[2020-05-27 13:18:41.146][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #25: Envoy::Grpc::AsyncStreamImpl::onData() [0x5562d030ef73]
[2020-05-27 13:18:41.196][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #26: Envoy::Http::AsyncStreamImpl::encodeData() [0x5562d031b1fb]
[2020-05-27 13:18:41.244][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #27: Envoy::Router::Filter::onUpstreamData() [0x5562d03372eb]
[2020-05-27 13:18:41.297][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #28: Envoy::Router::UpstreamRequest::decodeData() [0x5562d035d494]
[2020-05-27 13:18:41.345][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #29: Envoy::Http::ResponseDecoderWrapper::decodeData() [0x5562d01b52dc]
[2020-05-27 13:18:41.397][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #30: Envoy::Http::Http2::ConnectionImpl::onFrameReceived() [0x5562d04f86cb]
[2020-05-27 13:18:41.445][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #31: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_14::operator()() [0x5562d04fde28]
[2020-05-27 13:18:41.497][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #32: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_14::__invoke() [0x5562d04fddf5]
[2020-05-27 13:18:41.544][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #33: session_call_on_frame_received [0x5562cfa08622]
[2020-05-27 13:18:41.594][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #34: nghttp2_session_on_data_received [0x5562cfa0a0ce]
[2020-05-27 13:18:41.642][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #35: session_process_data_frame [0x5562cfa0eb97]
[2020-05-27 13:18:41.693][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #36: nghttp2_session_mem_recv [0x5562cfa0c98c]
[2020-05-27 13:18:41.741][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #37: Envoy::Http::Http2::ConnectionImpl::innerDispatch() [0x5562d04f7051]
[2020-05-27 13:18:41.792][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #38: Envoy::Http::Http2::ConnectionImpl::dispatch()::$_5::operator()() [0x5562d05039ca]
[2020-05-27 13:18:41.838][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #39: std::__1::__invoke<>() [0x5562d050396b]
[2020-05-27 13:18:41.887][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #40: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x5562d05038eb]
[2020-05-27 13:18:41.937][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #41: std::__1::__function::__alloc_func<>::operator()() [0x5562d050388b]
[2020-05-27 13:18:41.981][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #42: std::__1::__function::__func<>::operator()() [0x5562d05029ad]
[2020-05-27 13:18:42.029][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #43: std::__1::__function::__value_func<>::operator()() [0x5562d072107b]
[2020-05-27 13:18:42.077][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #44: std::__1::function<>::operator()() [0x5562d071ce86]
[2020-05-27 13:18:42.123][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #45: Envoy::Http::Utility::exceptionToStatus() [0x5562d0711ea8]
[2020-05-27 13:18:42.169][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #46: Envoy::Http::Http2::ConnectionImpl::dispatch() [0x5562d04f6cd2]
[2020-05-27 13:18:42.214][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #47: Envoy::Http::Http2::ConnectionImpl::dispatch() [0x5562d04f6dab]
[2020-05-27 13:18:42.260][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #48: Envoy::Http::CodecClient::onData() [0x5562d02ee87b]
[2020-05-27 13:18:42.306][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #49: Envoy::Http::CodecClient::CodecReadFilter::onData() [0x5562d02f1f47]
[2020-05-27 13:18:42.355][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #50: Envoy::Network::FilterManagerImpl::onContinueReading() [0x5562cfded8d5]
[2020-05-27 13:18:42.404][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #51: Envoy::Network::FilterManagerImpl::onRead() [0x5562cfdedad7]
[2020-05-27 13:18:42.448][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #52: Envoy::Network::ConnectionImpl::onRead() [0x5562cfdd94c8]
[2020-05-27 13:18:42.495][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #53: Envoy::Network::ConnectionImpl::onReadReady() [0x5562cfddcd99]
[2020-05-27 13:18:42.543][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #54: Envoy::Network::ConnectionImpl::onFileEvent() [0x5562cfddb97c]
[2020-05-27 13:18:42.590][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #55: Envoy::Network::ConnectionImpl::ConnectionImpl()::$_4::operator()() [0x5562cfde4d0e]
[2020-05-27 13:18:42.636][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #56: std::__1::__invoke<>() [0x5562cfde4cd1]
[2020-05-27 13:18:42.685][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #57: std::__1::__invoke_void_return_wrapper<>::__call<>() [0x5562cfde4c72]
[2020-05-27 13:18:42.734][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #58: std::__1::__function::__alloc_func<>::operator()() [0x5562cfde4c32]
[2020-05-27 13:18:42.779][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #59: std::__1::__function::__func<>::operator()() [0x5562cfde3d73]
[2020-05-27 13:18:42.826][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #60: std::__1::__function::__value_func<>::operator()() [0x5562cfdce7bd]
[2020-05-27 13:18:42.873][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #61: std::__1::function<>::operator()() [0x5562cfdce75f]
[2020-05-27 13:18:42.922][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #62: Envoy::Event::FileEventImpl::assignEvents()::$_0::operator()() [0x5562cfdce442]
[2020-05-27 13:18:42.971][592380][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #63: Envoy::Event::FileEventImpl::assignEvents()::$_0::__invoke() [0x5562cfdce3a6]
AsyncClient 0x5562d407a900, stream_id_: 8013577971860007246
&stream_info_: 
  StreamInfoImpl 0x5562d407aab0, protocol_: 1, response_code_: null, response_code_details_: via_upstream, health_check_request_: 0, route_name_: 
[1]    592380 abort (core dumped)  ~/IdeaProjects/envoy/build_debug/envoy -c config/sotw.yaml
```

### PR DESCRIPTION
**Pull request by JonathanO**
At present if health checks are enabled and passing then moving an EDS host from P0->P1 is a NOOP, and P1->P0 results in an abort. The abort can be reproduced using the test case attached to #11517

In the first case:
* P0 processing treats A as being removed because it's not in P0's list of endpoints anymore.
* P0 marks A's existing Host as PENDING_DYNAMIC_REMOVAL. It marks A as having been updated in this config apply.
* P1 skips over A because it is marked as updated in this update cycle already.
This means the update is treated as if it completely removed A from the cluster.

In the second case:
* P0 updates the priority on the existing Host. It is appended to the vector of added hosts.
* P1 marks A's existing Host as PENDING_DYNAMIC_REMOVAL. It does not adjust the removed host vector as the host is still pending removal.
* A's Host is now in both priorities and is PENDING_DYNAMIC_REMOVAL. This is wrong, and would cause problems later but doesn't have a chance to because:
* onClusterMemberUpdate fires with A's existing Host in the added vector (remember it wasn't removed from P1!)
* HealthChecker attempts to create a new health check session on A.
This results in an abort from the destructor of the already existing heath check session.

This was masked in tests by the tests enabling ignore_health_on_host_removal.

We fix this by passing in the set of addresses that appear in the endpoint update. If a host being considered for removal appears in this set,
and it isn't being duplicated into the current priority as a result of a health check address change, then we assume it's being moved and will
immediately remove it.

To simplify the case where a host's health check address is being changed AND it is being moved between priorities we don't attempt to preserve PENDING_DYNAMIC_REMOVAL behaviour for the original host, instead we remove it immediately. I think this is probably OK considering it doesn't work at all today, and I'm also not entirely convinced it's desirable to preserve the old host in this case anyway?

Additional description:
It also feels like this could do with a larger refactoring to make it more understandable, and to allow new features such as the same endpoint appearing in multiple priorities. However, this PR fixes the immediate bug.

Risk Level: Medium
Testing: Unit tests updated
Docs Changes: N/A
Release Notes: N/A
fixes #11517

### CODE REVIEW

File: test/common/upstream/eds_test.cc [hunk 1]
```diff
@@ -890,7 +894,7 @@ TEST_F(EdsTest, EndpointMovedToNewPriority) {
 TEST_F(EdsTest, EndpointMoved) {
   envoy::config::endpoint::v3::ClusterLoadAssignment cluster_load_assignment;
   cluster_load_assignment.set_cluster_name("fare");
-  resetClusterDrainOnHostRemoval();
```
Comment (snowp) [inline test/common/upstream/eds_test.cc:893]: Do we still have test coverage for the `drain_on_host_removal` cases?

File: test/common/upstream/eds_test.cc [hunk 2]
```diff
@@ -970,6 +975,75 @@ TEST_F(EdsTest, EndpointMoved) {
...
+    EXPECT_EQ(hosts.size(), 1);
+
+    EXPECT_TRUE(hosts[0]->healthFlagGet(Host::HealthFlag::FAILED_ACTIVE_HC));
+    hosts[0]->healthFlagClear(Host::HealthFlag::FAILED_ACTIVE_HC);
+    hosts[0]->healthFlagClear(Host::HealthFlag::PENDING_ACTIVE_HC);
+  }
+
+  cluster_load_assignment.clear_endpoints();
+  add_endpoint(80, 0, 80);
+  add_endpoint(81, 0, 82);
```
Comment (snowp) [inline test/common/upstream/eds_test.cc:1031]: Can you add cases for moving from 0 to 1 as well?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks for working on this! Some comments to get this started.

I believe the `ignore_host_health_on_removal` flag was added to support this kind of moving endpoints between priorities, so happy to potentially see this working without having to use that.

We've been talking about how this code needs to be refactored for years, so any help you can provide would be greatly appreciated :)

File: test/common/upstream/eds_test.cc (hunk 1 above)
Comment (JonathanO) [reply test/common/upstream/eds_test.cc:893]: Yes, EndpointRemovalClusterDrainOnHostRemoval still covers the drain on removal case.

I don't think drain_on_host_removal should have been true for this test case since, other than hiding the bug I'm fixing, it's behaviour should have been irrelevant - a host moving priority should not have had any interaction with the draining behaviour.

File: source/common/upstream/upstream_impl.cc [hunk 3]
```diff
@@ -1575,7 +1577,15 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
...
-                       [&updated_hosts, &final_hosts, &max_host_weight](const HostSharedPtr& p) {
+                       [&all_new_hosts, &new_hosts_for_current_priority, &updated_hosts,
+                        &final_hosts, &max_host_weight](const HostSharedPtr& p) {
+                         if (all_new_hosts.contains(p->address()->asString()) &&
+                             !new_hosts_for_current_priority.contains(p->address()->asString())) {
+                           // It'll be an immediate deletion if the host exists in the cluster
+                           // somewhere other than this priority.
+                           return false;
+                         }
+
```
Comment (snowp) [inline source/common/upstream/upstream_impl.cc:1588]: I thought I'd already commented on this but seems like not: currently we somewhat support having a single endpoint exist in multiple priorities at once (I know of at least one company that told me that they did this). Will this break whatever support we have for having an endpoint exist in multiple priorities?

Comment (JonathanO) [reply source/common/upstream/upstream_impl.cc:1588]: That might have been me, we wanted to do that ages ago, but it doesn't work because the existing `updated_hosts` check (upstream_impl.cc line 1452) means that it only gets added to the first priority.

Comment (snowp) [reply source/common/upstream/upstream_impl.cc:1588]: I think @bplotnick was using endpoints in multiple priorities at a previous company as well, but maybe this functionality broke at some point?

Comment (bplotnick) [reply source/common/upstream/upstream_impl.cc:1588]: There's a lot of context including the use-case and tradeoffs of this strategy here: https://github.com/envoyproxy/envoy/issues/4280. I left Yelp a little over a year ago and we were still using this approach.

CC: @kaisen

Comment (JonathanO) [reply source/common/upstream/upstream_impl.cc:1588]: I think #3959 may have changed that behaviour. The address is added to `updated_hosts` when processing the first priority it's seen in. In further priorities a host with the same address is skipped over as it's already in `updated_hosts`, and so it's not added to `final_hosts` for those priorities.

Comment (JonathanO) [reply source/common/upstream/upstream_impl.cc:1588]: Unless I've missed some trick to doing it, I've confirmed confirmed that the ability to have an address in multiple priorities broke quite some time ago. It gets ignored from all but the first priority it appears in. Fixing that would require significant rewriting of this code.

As a result, I do not believe that this PR breaks behaviour that anyone might be relying on.

Comment (snowp) [reply source/common/upstream/upstream_impl.cc:1588]: Thanks for digging into it, I think I agree with your conclusion so I'm fine with going forward with this change. @mattklein123 any concerns on your end with this change?

File: source/common/upstream/upstream_impl.cc [hunk 4]
```diff
@@ -1575,7 +1577,15 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
   if (!current_priority_hosts.empty() && dont_remove_healthy_hosts) {
     erase_from =
         std::remove_if(current_priority_hosts.begin(), current_priority_hosts.end(),
-                       [&updated_hosts, &final_hosts, &max_host_weight](const HostSharedPtr& p) {
+                       [&all_new_hosts, &new_hosts_for_current_priority, &updated_hosts,
+                        &final_hosts, &max_host_weight](const HostSharedPtr& p) {
+                         if (all_new_hosts.contains(p->address()->asString()) &&
+                             !new_hosts_for_current_priority.contains(p->address()->asString())) {
+                           // It'll be an immediate deletion if the host exists in the cluster
+                           // somewhere other than this priority.
```
Comment (snowp) [inline source/common/upstream/upstream_impl.cc:1585]: Maybe add some flavor here? Maybe include that we treat it as a move?

**Review by snowp — CHANGES_REQUESTED** [review]
Does this change the behavior for the Redis cluster in any way? Should there be a test added?

**Comment by JonathanO** [comment]
> Does this change the behavior for the Redis cluster in any way? Should there be a test added?

Logically, no. The only change that is Redis specific is how the redis cluster populates `all_new_hosts`, but since there's only one priority for Redis any host that should be in `all_new_hosts` will also be added to `new_hosts_for_current_priority`, rendering the contents of `all_new_hosts` irrelevant. The correctness of the `new_hosts_for_current_priority` behaviour is already covered by other tests... However, there are no Redis cluster tests at present for removing hosts when health checks are enabled, which seems like an omission. I'll add some.

File: test/extensions/clusters/redis/redis_cluster_test.cc [hunk 5]
```diff
@@ -977,34 +977,75 @@ TEST_F(RedisClusterTest, HostRemovalAfterHcFail) {
...
+    // but the other should remain until its health check fails too.
+    EXPECT_THAT(cluster_->prioritySet().hostSetsPerPriority()[0]->hosts().size(), 3U);
+    expectHealthyHosts(
+        std::list<std::string>({"127.0.0.1:22120", "127.0.0.3:22120", "127.0.0.4:22120"}));
+    EXPECT_TRUE(hosts[2]->healthFlagGet(Upstream::Host::HealthFlag::PENDING_DYNAMIC_REMOVAL));
+  }
+
+  /*
+  // This part of the test doesn't pass, as removal of PENDING_DYNAMIC_REMOVAL hosts does not seem
+  // to be implemented for redis clusters at present.
```
Comment (snowp) [inline test/extensions/clusters/redis/redis_cluster_test.cc:1032]: Mind leaving a TODO here? Maybe link to an open issue

**Review by snowp — DISMISSED** [review]
Thanks, LGTM! @mattklein123 you wanna take a look as well to make sure that this change makes sense?

File: source/common/upstream/upstream_impl.h [hunk 6]
```diff
@@ -919,7 +919,8 @@ class BaseDynamicClusterImpl : public ClusterImplBase {
   bool updateDynamicHostList(const HostVector& new_hosts, HostVector& current_priority_hosts,
                              HostVector& hosts_added_to_current_priority,
                              HostVector& hosts_removed_from_current_priority,
-                             HostMap& updated_hosts, const HostMap& all_hosts);
+                             HostMap& updated_hosts, const HostMap& all_hosts,
+                             const absl::flat_hash_set<std::string>& all_new_hosts);
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.h:923]: Please add new doc comment on this above. I've been looking at this code recently and as you pointed out, it's already incredibly hard to understand. Any additional comments/corrections you can make would be very helpful.

File: source/common/upstream/eds.cc [hunk 7]
```diff
@@ -48,17 +48,19 @@ void EdsClusterImpl::startPreInit() { subscription_->start({cluster_name_}); }
 
 void EdsClusterImpl::BatchUpdateHelper::batchUpdate(PrioritySet::HostUpdateCb& host_update_cb) {
   absl::node_hash_map<std::string, HostSharedPtr> updated_hosts;
```
Comment (mattklein123) [inline source/common/upstream/eds.cc:50]: As long as you are in here can you make this flat_hash_map? I don't see why we would need node stability.

File: source/common/upstream/upstream_impl.cc [hunk 8]
```diff
@@ -1446,6 +1445,8 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(const HostVector& new_hosts,
   // Keep track of hosts we see in new_hosts that we are able to match up with an existing host.
   absl::node_hash_set<std::string> existing_hosts_for_current_priority(
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.cc:1446]: flat_hash_set here also

File: source/common/upstream/upstream_impl.h (hunk 6 above)
Comment (mattklein123) [reply source/common/upstream/upstream_impl.h:923]: Also, as an aside, I'm always concerned about the perf impact to changes like this. It seems a shame we need yet another map/etc. One possible idea: Since this set is only used for temporary comparisons, could it be a flat_hash_set of string views to avoid copying? I think all of the string should live until the update function is done?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks in general this makes sense to me. A few comments and I would appreciate more comments. Also, I think it's worth having a release note for this under bug fixes to make it clear what is being fixed in case people run into issues. I'm tempted to ask for a feature flag but it's pretty localized so not going to push hard for it.

/wait

File: source/common/upstream/upstream_impl.cc (hunk 8 above)
Comment (JonathanO) [reply source/common/upstream/upstream_impl.cc]: Done.

File: source/common/upstream/eds.cc (hunk 7 above)
Comment (JonathanO) [reply source/common/upstream/eds.cc]: updated_hosts is used in several places, including as a parameter to BaseDynamicClusterImpl::updateDynamicHostList and it's moved to all_hosts_. This resulted in needing to change a few things.

In the end I decided that it might be easier to change the definition of Upstream::HostMap. I think doing that is safe, but can easily revert it if you'd rather I didn't.

File: source/common/upstream/upstream_impl.h [hunk 9]
```diff
@@ -914,6 +914,7 @@ class BaseDynamicClusterImpl : public ClusterImplBase {
    * @param updated_hosts is used to aggregate the new state of all hosts across priority, and will
    * be updated with the hosts that remain in this priority after the update.
    * @param all_hosts all known hosts prior to this host update.
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.h:916]:
```suggestion
   * @param all_hosts all known hosts prior to this host update across all priorities.
```

?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks LGTM with small comment. Can you check format?

/wait

**Comment by mattklein123** [comment]
@JonathanO friendly request to please never force push. It makes reviews much more difficult. Thank you!

File: source/common/upstream/upstream_impl.h (hunk 6 above)
Comment (mattklein123) [reply source/common/upstream/upstream_impl.h:924]: Sorry did you look at this to see if we can use a hash_set of string_view vs. copied strings?

/wait-any

Comment (JonathanO) [reply source/common/upstream/upstream_impl.h:924]: I'm not sure I can use a string_view here, although it's new to me, so I may be misunderstanding it's usage. I'm not sure I can assume liveness of the underlying data (See e.g. eds.cc:63 or redis_cluster.cc:101 for how that set is populated.)

I've switched new_hosts_for_current_priority to use a string_view as that should be safe (upstream_impl.cc:1419), although I don't know if that improves anything?

Comment (JonathanO) [reply source/common/upstream/upstream_impl.h:924]: I had second thoughts about new_hosts_for_current_priority too so reverted changing that.

Comment (mattklein123) [reply source/common/upstream/upstream_impl.h:924]: OK yeah I see that we aren't using stable strings in all places, which is unfortunate. I think there is a separate effort to do perf analysis of some of the xDS paths so I guess we can look at this independently. cc @htuch @jmarantz @pgenera @rojkov

**Review by mattklein123 — APPROVED** [review]
Thanks!
