### PR TITLE
lb: gentle failover across load balancing priority levels.

### LINKED ISSUE #1929: Add support for N levels of failover endpoints
I would like to use Envoy to load balance long lived TCP connections under the following setup: 
Say, I have 2 machines m1 and m2. I would like all traffic to go to m1. The traffic should go to m2 only if m1 fails (either active/passive healthcheck)  Or if it exceeds certain number of connections defined per host.

This is similar to the "first" load balancer in HAProxy: https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#balance

### PR DESCRIPTION
**Pull request by alyssawilk**
Changes Envoy load balancing across priority levels from a hard failover to trickling data based on the health percentage of each priority level.  

*Risk Level*: Medium 

*Testing*:
Added thorough unit testing for the lb failover code, as well as fixing up ring hash failover testing and adding ring-hash specific tests.

*Docs Changes*:
https://github.com/envoyproxy/data-plane-api/pull/359

*Release Notes*: n/a: falls under existing note

[Optional Fixes #Issue]
Fixes #1929

### CODE REVIEW

File: source/common/upstream/load_balancer_impl.cc [hunk 1]
```diff
@@ -14,20 +14,12 @@ namespace Envoy {
...
-  }
-  // This is used for LoadBalancerBase priority_set_ and local_priority_set_
-  // which are guaranteed to have at least one host set.
-  ASSERT(!priority_set->hostSetsPerPriority().empty());
-
-  for (auto& host_set : priority_set->hostSetsPerPriority()) {
-    if (!host_set->healthyHosts().empty()) {
-      return host_set.get();
-    }
+uint32_t sumEntries(std::vector<uint32_t>& vector) {
```
Comment (mattklein123) [inline source/common/upstream/load_balancer_impl.cc]: nit: `const std::vector<uint32_t>&`

File: source/common/upstream/load_balancer_impl.cc [hunk 2]
```diff
@@ -36,24 +28,81 @@ static const std::string RuntimeZoneEnabled = "upstream.zone_routing.enabled";
...
+  // but O(N) is good enough for now given the expected number of priorities is
+  // small.
+  for (size_t priority = 0; priority < per_priority_load.size(); ++priority) {
+    aggregate_percentage_load += per_priority_load[priority];
+    if (hash <= aggregate_percentage_load) {
+      return priority;
+    }
+  }
+  // The percentages should always add up to 100 but we have to have a return for the compiler.
+  ASSERT(0);
```
Comment (mattklein123) [inline source/common/upstream/load_balancer_impl.cc]: nit: I would use `NOT_REACHED` here.

File: source/common/upstream/load_balancer_impl.cc [hunk 3]
```diff
@@ -36,24 +28,81 @@ static const std::string RuntimeZoneEnabled = "upstream.zone_routing.enabled";
...
+}
 
-} // namespace Upstream
+void LoadBalancerBase::recalculatePerPriorityState(uint32_t priority) {
+  per_priority_load_.resize(priority_set_.hostSetsPerPriority().size());
+  per_priority_health_.resize(priority_set_.hostSetsPerPriority().size());
+
+  // Determine the health of the newly modified priority level.
+  // Health ranges from 0-100, and is the ratio of healthy hosts to total hosts, modified by the
+  // overprovision factor of 1.4
```
Comment (mattklein123) [inline source/common/upstream/load_balancer_impl.cc]: Can you add some more detail on where 1.4 comes from? Also, nit, period end of sentence.

File: source/common/upstream/load_balancer_impl.cc [hunk 4]
```diff
@@ -36,24 +28,81 @@ static const std::string RuntimeZoneEnabled = "upstream.zone_routing.enabled";
...
+        std::min<uint32_t>(100, 140 * host_set.healthyHosts().size() / host_set.hosts().size());
+  }
+
+  // Now that we've updated health for the changed priority level, we need to caculate percentage
+  // load for all priority levels.
+  //
+  // First, determine if the load needs to be scaled relative to health. For example if there are
+  // 3 host sets with 20% / 20% / 10% health they will get 40% / 40% / 20% load to ensure total load
+  // adds up to 100.
+  uint32_t total_health = std::min<uint32_t>(sumEntries(per_priority_health_), 100);
```
Comment (mattklein123) [inline source/common/upstream/load_balancer_impl.cc]: nit: const

File: source/common/upstream/load_balancer_impl.cc [hunk 5]
```diff
@@ -36,24 +28,81 @@ static const std::string RuntimeZoneEnabled = "upstream.zone_routing.enabled";
...
+  }
+  if (total_load != 0) {
+    // Account for rounding errors.
+    ASSERT(total_load < per_priority_load_.size());
+    per_priority_load_[0] += total_load;
+  }
+}
+
+const HostSet& LoadBalancerBase::chooseHostSet() {
+  uint32_t priority = choosePriority(random_.random(), per_priority_load_);
```
Comment (mattklein123) [inline source/common/upstream/load_balancer_impl.cc]: nit: const

File: source/common/upstream/ring_hash_lb.cc [hunk 6]
```diff
@@ -37,41 +34,47 @@ void RingHashLoadBalancer::initialize() {
...
+  // If there is no hash in the context, just choose a random value (this effectively becomes
+  // the random LB but it won't crash if someone configures it this way).
+  // computeHashKey() may be computed on demand, so get it only once.
+  Optional<uint64_t> hash;
+  if (context) {
+    hash = context->computeHashKey();
+  }
+  const uint64_t h = hash.valid() ? hash.value() : random_.random();
+
+  uint32_t priority = LoadBalancerBase::choosePriority(h, per_priority_load_);
```
Comment (mattklein123) [inline source/common/upstream/ring_hash_lb.cc]: nit: const

File: source/common/upstream/ring_hash_lb.cc [hunk 7]
```diff
@@ -37,41 +34,47 @@ void RingHashLoadBalancer::initialize() {
...
+  if (per_priority_state_[priority]->global_panic_) {
     stats_.lb_healthy_panic_.inc();
   }
-  return ring_->chooseHost(context, random_);
+  RingConstSharedPtr ring = per_priority_state_[priority]->current_ring_;
```
Comment (mattklein123) [inline source/common/upstream/ring_hash_lb.cc]: the compiler will probably optimize this, but I would avoid the local variable so we don't inc/decref the shared pointer.

File: source/common/upstream/ring_hash_lb.cc [hunk 8]
```diff
@@ -37,41 +34,47 @@ void RingHashLoadBalancer::initialize() {
...
+  return ring->chooseHost(h);
 }
 
 LoadBalancerPtr RingHashLoadBalancer::LoadBalancerFactoryImpl::create() {
   // We must protect current_ring_ via a RW lock since it is accessed and written to by multiple
-  // threads. All complex processing happens outside of locking however.
-  RingConstSharedPtr ring_to_use;
-  bool global_panic_to_use;
-  {
-    std::shared_lock<std::shared_timed_mutex> lock(mutex_);
```
Comment (mattklein123) [inline source/common/upstream/ring_hash_lb.cc]: I might be missing something here but I don't think we can lose the locking?

File: source/common/upstream/ring_hash_lb.cc [hunk 9]
```diff
@@ -182,22 +185,31 @@ RingHashLoadBalancer::Ring::Ring(const Optional<envoy::api::v2::Cluster::RingHas
...
+      new_global_panic = true;
+    } else {
+      new_ring = std::make_shared<Ring>(config_, host_set->healthyHosts());
+      new_global_panic = false;
+    }
 
-  std::unique_lock<std::shared_timed_mutex> lock(factory_->mutex_);
-  factory_->current_ring_ = new_ring;
-  factory_->global_panic_ = new_global_panic;
+    std::unique_lock<std::shared_timed_mutex> lock(factory_->mutex_);
```
Comment (mattklein123) [inline source/common/upstream/ring_hash_lb.cc]: This happens on the main thread. You don't need the read lock here I don't think, you just need the write lock below when you swap it all in. You still need the read lock on the factory create call though.

File: source/common/upstream/ring_hash_lb.h [hunk 10]
```diff
@@ -45,26 +45,29 @@ class RingHashLoadBalancer : public LoadBalancerBase,
...
+        : stats_(stats), random_(random) {}
 
     // Upstream::LoadBalancer
     HostConstSharedPtr chooseHost(LoadBalancerContext* context) override;
 
     ClusterStats& stats_;
     Runtime::RandomGenerator& random_;
-    const RingConstSharedPtr ring_;
-    const bool global_panic_;
+    std::vector<PerPriorityStatePtr> per_priority_state_;
```
Comment (mattklein123) [inline source/common/upstream/ring_hash_lb.h]: Instead of copying the vectors can we just use shared_ptr to constant vector? This will make lock hold time smaller also. (I think per other comments the locking is not quite right unless I am missing something).

File: source/common/upstream/load_balancer_impl.cc (hunk 3 above)
Comment (alyssawilk) [reply source/common/upstream/load_balancer_impl.cc]: From a decade working somewhere where we over-provision roughly 20%.  I can make it configurable from the get go but I figured we could leave it until someone actually cared.  

I'll comment both that it's arbitrary and can eventually be configurable unless you'd prefer I make it a config option now.

File: source/common/upstream/ring_hash_lb.cc (hunk 9 above)
Comment (alyssawilk) [reply source/common/upstream/ring_hash_lb.cc]: Above was a clear error, but this one confuses me.

You were locking factory_->mutex before changing factory->current_ring and factory->global_panic. Why then don't I need to snag the same lock when changing factory->per_priority_state?

File: source/common/upstream/ring_hash_lb.h (hunk 10 above)
Comment (alyssawilk) [reply source/common/upstream/ring_hash_lb.h]: I can but it's a perf hit for everything else since they then can't do in-place edits.
If we're worried about lock time how about a shared pointer for the ring hash where we refresh, which can be shared by all the threads?

File: source/common/upstream/load_balancer_impl.cc [hunk 11]
```diff
@@ -14,20 +14,12 @@ namespace Envoy {
...
-    if (!host_set->healthyHosts().empty()) {
-      return host_set.get();
-    }
+uint32_t sumEntries(std::vector<uint32_t>& vector) {
+  size_t sum = 0;
+  for (auto entry : vector) {
+    sum += entry;
   }
-  return priority_set->hostSetsPerPriority()[0].get();
+  return sum;
```
Comment (htuch) [inline source/common/upstream/load_balancer_impl.cc]: Nit: could use http://en.cppreference.com/w/cpp/algorithm/accumulate

File: source/common/upstream/ring_hash_lb.cc (hunk 9 above)
Comment (mattklein123) [reply source/common/upstream/ring_hash_lb.cc]: Sorry I read this too quickly. The issue here I think is that you might have inconsistent state since you release the lock several times during this code. I think the correct way to do this is:
1) Do the first loop to generate state, etc.
2) Acquire lock
3) Do 2nd loop to store state.

File: source/common/upstream/ring_hash_lb.cc [hunk 12]
```diff
@@ -37,41 +34,47 @@ void RingHashLoadBalancer::initialize() {
...
-  {
-    std::shared_lock<std::shared_timed_mutex> lock(mutex_);
-    ring_to_use = current_ring_;
-    global_panic_to_use = global_panic_;
+  // threads. All complex processing has already been precalculated however.
+  auto lb = std::make_unique<LoadBalancerImpl>(stats_, random_);
+
+  std::shared_lock<std::shared_timed_mutex> lock(mutex_);
+  for (size_t i = 0; i < per_priority_state_.size(); ++i) {
+    lb->per_priority_state_.push_back(PerPriorityStatePtr{new PerPriorityState});
```
Comment (mattklein123) [inline source/common/upstream/ring_hash_lb.cc]: Can you build an allocate the vector outside of the lock? Then you can just acquire the lock and copy the data values in.

File: source/common/upstream/load_balancer_impl.cc [hunk 13]
```diff
@@ -12,48 +12,88 @@
...
+  for (size_t priority = 0; priority < per_priority_load.size(); ++priority) {
+    aggregate_percentage_load += per_priority_load[priority];
+    if (hash <= aggregate_percentage_load) {
+      return priority;
     }
   }
-  return priority_set->hostSetsPerPriority()[0].get();
+  // The percentages should always add up to 100 but we have to have a return for the compiler.
+  NOT_REACHED;
+  return 0;
```
Comment (mattklein123) [inline source/common/upstream/load_balancer_impl.cc]: nit: I don't think the compiler will require the return if you have NOT_REACHED.

File: source/common/upstream/ring_hash_lb.h (hunk 10 above)
Comment (mattklein123) [reply source/common/upstream/ring_hash_lb.h]: nit: I would either do shared_ptr for both per_priority_state_ and per_priority_load_, or for neither. It's fine with me either way (doing it out of lock with swap is fine). Any reason not to be consistent?

File: source/common/upstream/ring_hash_lb.cc [hunk 14]
```diff
@@ -37,41 +34,43 @@ void RingHashLoadBalancer::initialize() {
...
+  // If there is no hash in the context, just choose a random value (this effectively becomes
+  // the random LB but it won't crash if someone configures it this way).
+  // computeHashKey() may be computed on demand, so get it only once.
+  Optional<uint64_t> hash;
+  if (context) {
+    hash = context->computeHashKey();
+  }
+  const uint64_t h = hash.valid() ? hash.value() : random_.random();
+
+  uint32_t priority = LoadBalancerBase::choosePriority(h, *per_priority_load_);
```
Comment (mattklein123) [inline source/common/upstream/ring_hash_lb.cc]: nit: const
