### PR TITLE
userspace socket: treat a closed peer handle as writable

### LINKED ISSUE #38148: Envoy internal listener's active connections are not released with TcpProxy case
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Envoy internal listener's active connections are not released with TcpProxy case*

*Description*:
>running envoy:v1.33-latest image via docker,  active connections created by internal listener (using TcpProxy) are not released 
1. start envoy:v1.33-latest
docker run -d --name envoy -p 10000:10000 -p 9901:9901 -v $(pwd)/envoy.yaml:/etc/envoy/envoy.yaml:ro   envoyproxy/envoy:v1.33-latest -l trace -c /etc/envoy/envoy.yaml 

2. send traffic:
curl -vvv -x http://localhost:10000 https://example.com --http1.1

3.  The internal listener's active connections were NOT released nor cleaned up;  the connections created by the internal listener were held indefinitely.

C02CCPDLMD6M  ~/Desktop/PA_Project/myEnvoy  date
Wed Jan 22 14:30:53 PST 2025

C02CCPDLMD6M  ~/Desktop/PA_Project/myEnvoy  curl -s http://localhost:9901/stats | grep cx_active | grep -vw 0
http.admin.downstream_cx_active: 1
listener.admin.downstream_cx_active: 1
listener.admin.main_thread.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.downstream_cx_active: 8
listener.envoy_internal_internal_listener_https.worker_1.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.worker_10.downstream_cx_active: 2
listener.envoy_internal_internal_listener_https.worker_3.downstream_cx_active: 2
listener.envoy_internal_internal_listener_https.worker_5.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.worker_7.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.worker_8.downstream_cx_active: 1

C02CCPDLMD6M  ~/Desktop/PA_Project/myEnvoy  curl -s http://localhost:9901/stats | grep cx_active | grep -vw 0
http.admin.downstream_cx_active: 1
listener.admin.downstream_cx_active: 1
listener.admin.main_thread.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.downstream_cx_active: 9
listener.envoy_internal_internal_listener_https.worker_1.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.worker_10.downstream_cx_active: 2
listener.envoy_internal_internal_listener_https.worker_2.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.worker_3.downstream_cx_active: 2
listener.envoy_internal_internal_listener_https.worker_5.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.worker_7.downstream_cx_active: 1
listener.envoy_internal_internal_listener_https.worker_8.downstream_cx_active: 1

C02CCPDLMD6M  ~/Desktop/PA_Project/myEnvoy  date
Wed Jan 22 14:58:57 PST 2025

*Repro steps*:
>docker pull envoyproxy/envoy:v1.33-latest
  run standalone Envoy v1.33 with internal listener enabled using TcpProxy

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
envoy.yaml file
```
node:
  id: test-id
  cluster: test-cluster

bootstrap_extensions:
  - name: envoy.bootstrap.internal_listener
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.bootstrap.internal_listener.v3.InternalListener

static_resources:
  listeners:
    # Ingress Listener for HTTP and HTTPS
    - name: ingress_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: ingress_to_internal_route
                  virtual_hosts:
                    - name: internal_virtual_host
                      domains: ["*"]
                      routes:
                        - match: { connect_matcher: {} }
                          route:
                            cluster: internal_cluster_https
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                connect_config: {}
                        - match: { prefix: "/" }
                          route:
                            cluster: internal_cluster_http
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: "/tmp/envoy_access.log"

    # Internal Listener for HTTP traffic
    - name: internal_listener_http
      internal_listener: {}
      filter_chains:
      - transport_socket:
          name: envoy.transport_sockets.raw_buffer  # http://
          typed_config:
             "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
        transport_socket_connect_timeout: 0s
        filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: internal_http
                codec_type: AUTO
                common_http_protocol_options:
                    idle_timeout: 15s
                stream_idle_timeout: 15s                         
                route_config:
                  name: internal_to_dynamic_route
                  virtual_hosts:
                    - name: dynamic_virtual_host
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: dynamic_forward_proxy
                http_filters:
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache
                        dns_lookup_family: V4_ONLY
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    # Internal Listener for HTTPS traffic
    - name: internal_listener_https
      internal_listener: {}
      listener_filters:
      - name: "envoy.filters.listener.tls_inspector"
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector      
      filter_chains:
        - filters:
            - name: envoy.filters.network.sni_dynamic_forward_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
                port_value: 443
                dns_cache_config:
                  name: dynamic_forward_proxy_cache
                  dns_lookup_family: V4_ONLY
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: internal_https
                cluster: dynamic_forward_proxy
                idle_timeout: 15s
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: "/tmp/envoy_access.log"

  clusters:
    # Internal Cluster for HTTP traffic
    - name: internal_cluster_http
      connect_timeout: 15s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: internal_cluster_http
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    envoy_internal_address: { server_listener_name: internal_listener_http }

    # Internal Cluster for HTTPS traffic
    - name: internal_cluster_https
      connect_timeout: 15s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: internal_cluster_https
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    envoy_internal_address: { server_listener_name: internal_listener_https }

    # Dynamic Forward Proxy Cluster
    - name: dynamic_forward_proxy
      connect_timeout: 15s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache
            dns_lookup_family: V4_ONLY
      transport_socket:
        name: envoy.transport_sockets.raw_buffer
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer

admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
```

*Logs*:
>Include the access logs and the Envoy logs.

Envoy logs:  attached file envoy_service.log
```
Envoy access logs:
docker exec -it envoy more /tmp/envoy_access.log:
[2025-01-22T22:20:48.464Z] "CONNECT - HTTP/1.1" 200 DC 578 7336 2873 - "-" "curl/8.7.1" "9e89c290-68d7-40d4-b18f-31fe2ba53cd9" "example.com:443" "envoy://internal_listener_https/"
[2025-01-22T22:20:54.394Z] "CONNECT - HTTP/1.1" 200 DC 578 7337 127 - "-" "curl/8.7.1" "b1759241-37f5-4f46-a998-844320ef050a" "example.com:443" "envoy://internal_listener_https/"
[2025-01-22T22:20:57.574Z] "CONNECT - HTTP/1.1" 200 DC 578 7338 123 - "-" "curl/8.7.1" "f32d9bce-691d-4127-978e-3968fe67c9f9" "example.com:443" "envoy://internal_listener_https/"
[2025-01-22T22:21:00.746Z] "CONNECT - HTTP/1.1" 200 DC 578 7336 133 - "-" "curl/8.7.1" "8b73e76b-a6f9-434a-891c-780efc3e363f" "example.com:443" "envoy://internal_listener_https/"
[2025-01-22T22:21:03.923Z] "CONNECT - HTTP/1.1" 200 DC 578 7338 85 - "-" "curl/8.7.1" "eb4457d4-c44b-431f-9b1d-8f9139c87570" "example.com:443" "envoy://internal_listener_https/"
[2025-01-22T22:21:07.044Z] "CONNECT - HTTP/1.1" 200 DC 578 7336 65 - "-" "curl/8.7.1" "63250ee4-069d-4e6d-a406-509c81428179" "example.com:443" "envoy://internal_listener_https/"
[2025-01-22T22:21:10.172Z] "CONNECT - HTTP/1.1" 200 DC 578 7336 1698 - "-" "curl/8.7.1" "a2d48e28-3177-4c23-9080-d3b6d89335bd" "example.com:443" "envoy://internal_listener_https/"
[2025-01-22T22:21:14.906Z] "CONNECT - HTTP/1.1" 200 DC 578 7337 208 - "-" "curl/8.7.1" "43a8a725-a397-4591-9824-ec76e71d6872" "example.com:443" "envoy://internal_listener_https/"
[2025-01-22T22:51:40.798Z] "CONNECT - HTTP/1.1" 200 DC 578 7337 128 - "-" "curl/8.7.1" "08f1f9fa-b104-4806-8d3b-50ab4744d42c" "example.com:443" "envoy://internal_listener_https/"
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

### PR DESCRIPTION
**Pull request by pianiststickman**
Commit Message: userspace socket: treat a closed peer handle as writable
Additional Description:
If one side of an internal listener connection closes, subsequent writes from the other side may result in data waiting to be flushed on a half-close. For connections managed by the HCM, this is covered by the delayed close timer, but TcpProxy does not implement a delayed close timer and therefore the connection leak in #38148 can persist.

The fix here is treat a closed peer handle as writable in order to get the connection to attempt a write and error out. (This is analogous to Linux signalling `EPOLLOUT` along with `EPOLLHUP` when a peer closes for reads; without it, an epoll consumer on the other side may continue to write-block a socket indefinitely, which is exactly what's happening here but in userspace.)
Risk Level: low; subsequent calls to `write()` are guarded against peer being nullptr, and the error when calling `write()` is the point.
Testing: new CI and integration test that reproduces the issue
Docs Changes: n/a
Release Notes: n/a
Fixes #38148

### CODE REVIEW

**Comment by wbpcode** [comment]
gently ping @botengyao

File: source/extensions/io_socket/user_space/io_handle_impl.h [hunk 1]
```diff
@@ -133,8 +133,12 @@ class IoHandleImpl final : public Network::IoHandle,
   bool canReceiveData() const override { return !pending_received_data_.highWatermarkTriggered(); }
   bool hasReceivedEof() const override { return receive_data_end_stream_; }
   bool isWritable() const override {
-    return peer_handle_ != nullptr && !peer_handle_->hasReceivedEof() &&
-           peer_handle_->canReceiveData();
+    if (peer_handle_ == nullptr) {
```
Comment (botengyao) [inline source/extensions/io_socket/user_space/io_handle_impl.h:136]: discussed offline. I initially don't feel strong this is the right place to fix, since it will convert the `isWritable()` as “write-ready or write-error-ready,” which is mechanically useful for eventing, but it does not match the interface comment.

Another way is to fix during the `onPeerDestroy()`, but in turn it will still call the `setEnabled` which is checking the `isWritable` again. We could add some event handling inside `setEnabled`, but this fix looks the cleanest way. 

In general, calling an additional write is fine as the PR description pointed out like Linux, would you like to update the comment for the `isWritable` interface as well?

Comment (pianiststickman) [reply source/extensions/io_socket/user_space/io_handle_impl.h:136]: Done, I went ahead and renamed `isWritable()` to `isWriteUnblocked()` to be extra clear.
