### PR TITLE
http: using CONNECT_ERROR for HTTP/2

### LINKED ISSUE #13055: HTTP/2 CONNECT does not return CONNECT_ERROR on upstream RST
*Title*: HTTP/2 CONNECT does not return CONNECT_ERROR on upstream RST

*Description*:
I've have a downstream proxy that tunnels TCP via HTTP/2 to a backend service. Envoy is in front of the service and provides an HTTP/2 endpoint which supports the CONNECT method. The backend (Envoy upstream) service sometimes shuts down a connection by sending a TCP RST. According to the [HTTP/2 spec](https://http2.github.io/http2-spec/#CONNECT), "[a] proxy treats any error in the TCP connection, which includes receiving a TCP segment with the RST bit set, as a stream error [...] of type CONNECT_ERROR." While Envoy does send RST_STREAM, the error is NO_ERROR instead of CONNECT_ERROR.

The spec goes on to state that any error (stream or connection) must result in a TCP RST being sent to downstream clients, so I can work around this. However, I wanted to check if this was intended behavior.

*Repro steps*:
This is reproducible with Envoy v1.15.0 configured with support for HTTP/2 CONNECT as per https://github.com/envoyproxy/envoy/blob/master/configs/terminate_connect.v3.yaml (substituting the upstream `socket_address` as appropriate). My upstream service is MySQL. I can likely set up a more easily reproducible example if needed.

When the upstream service sends a TCP RST (in the case of MySQL, after there is no authentication within 10 seconds of connect by default), then Envoy will send RST_STREAM with NO_ERROR as the error. However, this error should be set to CONNECT_ERROR as per the spec.

*Config*:
https://github.com/envoyproxy/envoy/blob/master/configs/terminate_connect.v3.yaml

*Logs*:
Logs indicate a success (200).

### PR DESCRIPTION
**Pull request by alyssawilk**
Commit Message: http: using CONNECT_ERROR for HTTP/2
Risk Level: Low (changing rst code on the wire)
Testing: new unit, integration tests
Docs Changes: n/a
Release Notes: inline
Fixes #13055

### CODE REVIEW

File: source/common/http/conn_manager_impl.cc [hunk 1]
```diff
@@ -177,7 +188,19 @@ void ConnectionManagerImpl::doEndStream(ActiveStream& stream) {
     // TODO(snowp): This call might not be necessary, try to clean up + remove setter function.
     stream.filter_manager_.setLocalComplete();
     stream.state_.codec_saw_local_complete_ = true;
-    stream.response_encoder_->getStream().resetStream(StreamResetReason::LocalReset);
+
+    // Per https://tools.ietf.org/html/rfc7540#section-8.3 if there was an error
+    // with the TCP connection during a CONNECT request, it should be
+    // communicated via CONNECT_ERROR
+    if (requestWasConnect(stream.request_headers_, codec_->protocol()) &&
```
Comment (mattklein123) [inline source/common/http/conn_manager_impl.cc:195]: I have a vague sense that we do many header type checks to see if something is a connect request. Would it be better for perf if did this check once and stored this somewhere? Not a big deal but maybe something to think about in a follow up.

File: source/common/http/http2/codec_impl.cc [hunk 2]
```diff
@@ -984,6 +993,9 @@ int ConnectionImpl::onStreamClose(int32_t stream_id, uint32_t error_code) {
         if (error_code == NGHTTP2_REFUSED_STREAM) {
           reason = StreamResetReason::RemoteRefusedStreamReset;
           stream->setDetails(Http2ResponseCodeDetails::get().remote_refused);
+        } else if (error_code == NGHTTP2_CONNECT_ERROR) {
+          reason = StreamResetReason::ConnectError;
+          stream->setDetails(Http2ResponseCodeDetails::get().remote_reset);
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.cc:998]: Should we use a different details string here?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Nice, LGTM with small comment.

/wait

File: source/common/http/conn_manager_impl.cc (hunk 1 above)
Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc:195]: We do, but this case is quite special as most are looking at HTTP/1 style CONNECT requests (HTTP/1 connect and HTTP/2 CONNECTs-excluding-upgrades) and this particular one is doing all CONNECT methods (including HTTP/2 upgrades)

File: source/common/http/http2/codec_impl.cc (hunk 2 above)
Comment (alyssawilk) [reply source/common/http/http2/codec_impl.cc:998]: eh, I think it's not worth the detail here (I only split out the reason because otherwise it was impossible to unit test) but I will restructure the code so we only setDetails with it once as a matter of principle :-)

**Review by mattklein123 — APPROVED** [review]
Thanks!
