### PR TITLE
ext_authz: Format authorization request headers to add

### LINKED ISSUE #9980: config.filter.http.ext_authz.v2.AuthorizationRequest headers_to_add not doing interpolation
**Bug Template**

*Title*: *headers_to_add not doing interpolation*

*Description*:
I'm trying to use ext_authz with oauth2-proxy under istio. 

[these docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2-authorizationrequest) point to [this doc](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-msg-core-headervalue) which states `The same format specifier as used for HTTP access logging applies here, however unknown header values are replaced with the empty string instead of -.`

However, what gets sent is:
```
[Envoy (Epoch 0)] [2020-02-09 02:19:18.510][39][trace][filter] [external/envoy/source/extensions/filters/http/ext_authz/ext_authz.cc:80] [C1704][S12786298896255907122] ext_authz filter calling authorization server
[Envoy (Epoch 0)] [2020-02-09 02:19:18.510][39][debug][router] [external/envoy/source/common/router/router.cc:434] [C0][S17990863836512223039] cluster 'outbound|80||oauth2-proxy-oauth2-proxy.oauth2-proxy.svc.cluster.local' match for URL '/qfqf'
[Envoy (Epoch 0)] [2020-02-09 02:19:18.510][39][debug][router] [external/envoy/source/common/router/router.cc:549] [C0][S17990863836512223039] router decoding headers:
':authority', 'kubernetes-dashboard.home.mikebryant.me.uk'
':method', 'GET'
':path', '/qfqf'
':scheme', 'https'
'content-length', '0'
'x-auth-request-redirect', '%REQ(:SCHEME)://%REQ(:AUTHORITY)%/%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.244.128.46'
'x-envoy-expected-rq-timeout-ms', '5000'
```

Note the header sent to the authorization service hasn't been interpolated / formatted

*Repro steps*:
Use this config - the important part is to try and use format strings in the headers
```
        name: "envoy.ext_authz"
        config:
          failure_mode_allow: false
          http_service:
            authorization_request:
              allowed_headers:
                patterns:
                - exact: Authorization
                - exact: Cookie
              headers_to_add:
              - key: X-Auth-Request-Redirect
                value: "%REQ(:SCHEME)://%REQ(:AUTHORITY)%/%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            server_uri:
              cluster: outbound|80||oauth2-proxy-oauth2-proxy.oauth2-proxy.svc.cluster.local
              uri: http://oauth2-proxy-oauth2-proxy.oauth2-proxy.svc.cluster.local
              timeout: 5.000s
```

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

### PR DESCRIPTION
**Pull request by dio**
This allows adding request headers for authorization requests using patterns that are parseable by headers parser, hence the resulting authorization request carries the formatted headers (inferred from `stream_info` of that request).

Risk Level: Low
Testing: Unit
Docs Changes: N/A
Release Notes: N/A
Fixes #9980 

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

**Comment by dio** [comment]
cc. @snowp

File: source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc [hunk 1]
```diff
@@ -128,11 +128,11 @@ ClientConfig::ClientConfig(const envoy::extensions::filters::http::ext_authz::v3
       upstream_header_matchers_(toUpstreamMatchers(
           config.http_service().authorization_response().allowed_upstream_headers(),
           enable_case_sensitive_string_matcher_)),
-      authorization_headers_to_add_(
-          toHeadersAdd(config.http_service().authorization_request().headers_to_add())),
       cluster_name_(config.http_service().server_uri().cluster()), timeout_(timeout),
       path_prefix_(path_prefix),
-      tracing_name_(fmt::format("async {} egress", config.http_service().server_uri().cluster())) {}
+      tracing_name_(fmt::format("async {} egress", config.http_service().server_uri().cluster())),
+      request_headers_parser_(Router::HeaderParser::configure(
```
Comment (snowp) [inline source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc]: should there be an overload for configure that takes the HeaderValue proto instead of converting from proto to proto?

File: test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc [hunk 2]
```diff
@@ -318,11 +320,65 @@ TEST_F(ExtAuthzHttpClientTest, AuthorizationOkWithAddedAuthzHeaders) {
...
-  // Expect that header1 will be added and header2 correctly overwritten.
-  EXPECT_CALL(async_client_, send_(AllOf(ContainsPairAsHeader(config_->headersToAdd().front()),
-                                         ContainsPairAsHeader(config_->headersToAdd().back())),
-                                   _, _));
-  client_->check(request_callbacks_, request, active_span_);
+  // Expect that header1 will be added and header2 correctly overwritten. Due to this behavior, the
+  // append property of header value option should always be false.
+  const std::pair<const Http::LowerCaseString, const std::string> header1{"x-authz-header1",
+                                                                          "value"};
+  const std::pair<const Http::LowerCaseString, const std::string> header2{"x-authz-header2",
```
Comment (snowp) [inline test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc]: use the typedef here

File: test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc [hunk 3]
```diff
@@ -318,11 +320,65 @@ TEST_F(ExtAuthzHttpClientTest, AuthorizationOkWithAddedAuthzHeaders) {
...
+  const auto expected_headers = TestCommon::makeHeaderValueOption({{":status", "200", false}});
+  const auto authz_response = TestCommon::makeAuthzResponse(CheckStatus::OK);
+  auto check_response = TestCommon::makeMessageResponse(expected_headers);
+
+  EXPECT_CALL(active_span_, spawnChild_(_, config_->tracingName(), _)).WillOnce(Return(child_span));
+  EXPECT_CALL(*child_span,
+              setTag(Eq(Tracing::Tags::get().UpstreamCluster), Eq(config_->cluster())));
+  EXPECT_CALL(*child_span, injectContext(_));
+
+  const std::pair<const Http::LowerCaseString, const std::string> headers_to_add{"x-authz-header1",
```
Comment (snowp) [inline test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc]: name of this variable is a bit odd, i would just call this something like `expected_authz_header` or something

File: test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc [hunk 4]
```diff
@@ -318,11 +320,65 @@ TEST_F(ExtAuthzHttpClientTest, AuthorizationOkWithAddedAuthzHeaders) {
...
+                                                                                 "123"};
+  EXPECT_CALL(async_client_, send_(AllOf(ContainsPairAsHeader(headers_to_add)), _, _));
```
Comment (snowp) [inline test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc]: you dont need AllOf with just one matcher

File: source/extensions/filters/network/ext_authz/ext_authz.cc [hunk 5]
```diff
@@ -28,7 +28,8 @@ void Filter::callCheck() {
   config_->stats().total_.inc();
 
   calling_check_ = true;
-  client_->check(*this, check_request_, Tracing::NullSpan::instance());
+  client_->check(*this, check_request_, Tracing::NullSpan::instance(),
+                 filter_callbacks_->connection().streamInfo());
```
Comment (snowp) [inline source/extensions/filters/network/ext_authz/ext_authz.cc]: i assume this means that there is limited support for this /w the network filter as well (e.g. to embed the downstream SAN or something). Maybe add a test for that since I'm sure people will start relying on it?

File: source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc (hunk 1 above)
Comment (dio) [reply source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc]: Yeap. I can add that.

Comment (dio) [reply source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc]: Done

File: source/extensions/filters/network/ext_authz/ext_authz.cc (hunk 5 above)
Comment (dio) [reply source/extensions/filters/network/ext_authz/ext_authz.cc]: Done.

**Comment by dio** [comment]
@snowp, thanks for your review. Sorry, anything else I need to fix?

File: source/common/router/header_parser.cc [hunk 6]
```diff
@@ -235,6 +234,21 @@ HeaderParserPtr HeaderParser::configure(
   return header_parser;
 }
 
+HeaderParserPtr HeaderParser::configure(
+    const Protobuf::RepeatedPtrField<envoy::config::core::v3::HeaderValue>& headers_to_add,
+    bool append) {
+  HeaderParserPtr header_parser(new HeaderParser());
```
Comment (snowp) [inline source/common/router/header_parser.cc]: `make_unique`

File: source/extensions/filters/common/ext_authz/ext_authz.h [hunk 7]
```diff
@@ -90,11 +91,11 @@ class Client {
    *        NOTE: The callback may happen within the calling stack.
    * @param request is the proto message with the attributes of the specific payload.
    * @param parent_span source for generating an egress child span as part of the trace.
-   *
+   * @param stream_info supplies the client's request stream info.
```
Comment (snowp) [inline source/extensions/filters/common/ext_authz/ext_authz.h]: is this used for L4 as well? in that case it'd be the connection stream info

File: source/common/router/header_parser.cc (hunk 6 above)
Comment (dio) [reply source/common/router/header_parser.cc]: This one is protected.

File: test/extensions/filters/network/ext_authz/ext_authz_test.cc [hunk 8]
```diff
@@ -44,7 +46,8 @@ class ExtAuthzFilterTest : public testing::Test {
           "envoy_grpc": { "cluster_name": "ext_authz_server" }
       },
       "failure_mode_allow": true,
-      "stat_prefix": "name"
+      "stat_prefix": "name",
+      "include_peer_certificate": true
```
Comment (snowp) [inline test/extensions/filters/network/ext_authz/ext_authz_test.cc]: this doesnt seem to be related to this change? or am i missing something

Comment (snowp) [reply test/extensions/filters/network/ext_authz/ext_authz_test.cc]: oh if this is about my comment about verifying this for the network ext authz filter, I meant using the header formatting here to pass this information, not a dedicated field

Comment (dio) [reply test/extensions/filters/network/ext_authz/ext_authz_test.cc]: Sorry, can you clarify by: “using header formatting here”. Hum, network filter has its own impl that doesn’t use header formatter.

Comment (dio) [reply test/extensions/filters/network/ext_authz/ext_authz_test.cc]: Per offline conversation, this is reverted.
