### PR TITLE
grpc: simplify GoogleGrpcUtils::makeBufferInstance

### LINKED ISSUE #7266: BufferFragmentImpl destructor not called by GoogleGrpcUtils, which may result in memory leak
*Title*: BufferFragmentImpl destructor not called by GoogleGrpcUtils, which may result in memory leak

*Description*:
In GoogleGrpcUtils::makeBufferInstance, a "placement new" is used to allocate several instances of Buffer::BufferFragmentImpl into a previously allocated memory block that contains all of those objects.  The BufferFragmentImpl's use a releasor function to indicate when they are done with the memory, which releasor function uses a reference counter.  When all BufferFragmentImpls are done with the memory, the memory is deallocated in a block.  This means that the BufferFragmentImpl's *constructor* is called (by the placement new) but the class instances *destructor* is never called.  

If BufferFragmentImpl was a POD (plane old data) class, this would be fine.  However, it includes a std::function<> element.  That element is constructed via copying on construction of the BufferFragmentImpl.  If any memory is allocated in std::function<>'s constructor, it will be leaked.  I'm seeing such a leak in one of the internal tests we run @ Google; the backtrace is provided below.  

This is obviously dependent on the details of and path taken in std::function<>'s constructor.  That may explain why it wasn't seen in any CircleCI tests, and only in one of the many tests run on import into Google.  I'll admit that those two points still confuse me (i.e. why this isn't a more obvious leak than it appears to be) but I'm fairly comfortable in the bug by code inspection, so I figured I'd file it and get any feedback people had.

BufferFragmentImpl placement new construction: https://github.com/envoyproxy/envoy/blob/master/source/common/grpc/google_grpc_utils.cc#L100

BufferFragmentImpl's containing memory block's free: https://github.com/envoyproxy/envoy/blob/master/source/common/grpc/google_grpc_utils.cc#L89

BufferFragmentImpl's definition: https://github.com/envoyproxy/envoy/blob/master/source/common/buffer/buffer_impl.h#L422

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

Description:
Simplifying GoogleGrpcUtils::makeBufferInstance by leveraging ref count of grpc_slice.

Risk Level: Low
Testing: existing tests
Docs Changes:
Release Notes:
Fixes #7266.

### CODE REVIEW

**Comment by lizan** [comment]
gently ping @jplevyak. cc @curiouserrandy

File: source/common/grpc/google_grpc_utils.cc [hunk 1]
```diff
@@ -81,28 +73,16 @@ Buffer::InstancePtr GoogleGrpcUtils::makeBufferInstance(const grpc::ByteBuffer&
...
-                                   sizeof(Buffer::BufferFragmentImpl) * slices.size()),
-                 "posix_memalign failure");
-  for (size_t i = 0; i < slices.size(); i++) {
-    new (&container->fragments_[i])
-        Buffer::BufferFragmentImpl(slices[i].begin(), slices[i].size(), releaser);
-  }
+
   for (size_t i = 0; i < slices.size(); i++) {
-    buffer->addBufferFragment(container->fragments_[i]);
+    auto* slice = new grpc::Slice(std::move(slices[i]));
```
Comment (silentdai) [inline source/common/grpc/google_grpc_utils.cc]: Does slice need to be on heap?
Why not 
```
for (...) {
    buffer->addBufferFragment(*new Buffer::BufferFragmentImpl(
        slices[i]->begin(), slices[i]->size(),
        [slice = std::move(slices[i])](const void*, size_t, const Buffer::BufferFragmentImpl* frag) {
          delete frag;
        }));
}
```

Comment (lizan) [reply source/common/grpc/google_grpc_utils.cc]: Yes, it have to be on heap, that's my first try and it will fail with heap-use-after-free. the grpc_slice will inline slices length <= 8 bytes (<= a 64bit pointer), so in the case slice[i] is inlined, it is no longer alive beyond this method. Unless you do sth like previous implementation, ` container->slices_ = std::move(slices);` does keep the slices until the whole buffer is done.

**Comment by lizan** [comment]
@silentdai the naive solution to fix the leak would be call destructor for BufferFragmentImpl in the container, not just call `::free`, as I pointed in https://github.com/envoyproxy/envoy/issues/7266#issuecomment-502354463. This PR solves that by the `delete frag;` call, which calls the destructor.

**Comment by curiouserrandy** [comment]
@silentdai : Any std::function that allocated memory in its constructor would leak because (in the old code) the destructor was never called.

**Comment by curiouserrandy** [comment]
Also, warning that I'm about to be AFK for several days, so I won't be able to respond at all quickly to comments.

**Comment by lizan** [comment]
>  I'll call out the obvious, which is that this produces a much more fragmented memory allocation and freeing (two per slice instead of once for the entire container).

Yeah but I'm not too worried about this as long as tcmalloc is enabled. It could be potentially optimized to one per slice by inlining them into a struct. A good side of this is it frees up slices that are done with Buffer earlier than current implementation.

**Comment by silentdai** [comment]
Aha, I get it. It's the glitch in previous `~ByteBufferContainer()`. `std::function` behavior triggers the bug but it's not a fault in function. Thank you both!

File: source/common/grpc/google_grpc_utils.cc (hunk 1 above)
Comment (silentdai) [reply source/common/grpc/google_grpc_utils.cc]: This is subtle... Thank you for the explanation! 
`The caller must ensure <data> is valid until releasor() is called, `

**Comment by lizan** [comment]
@curiouserrandy this new version should address your concern about fragment memory allocation, it is now comparable to the original impl, by eliminating involving `std::function` per slice.

**Comment by curiouserrandy** [comment]
@lizan : I apologize, but I don't have time to review this to my own satisfaction before I disappear.  At a quick glance it looks basically ok, though I'm a bit uncomfortable with the possible persistence of the pointers to the buffer fragments past delete since that counts on the implementation of Buffer not to go back and look at them (IIRC done() is called incrementally as the buffer is processed).  But it's probably fine.  

I *am* fine with your original implementation too (as signaled by my approval); I just wanted to make explicit the performance/possible fragmentation concerns.  I don't know anything about tcmalloc internals, so I'm happy to defer to your knowledge if you think that takes care of the fragmentation issue.

File: source/common/grpc/google_grpc_utils.cc [hunk 2]
```diff
@@ -62,12 +62,17 @@ grpc::ByteBuffer GoogleGrpcUtils::makeByteBuffer(Buffer::InstancePtr&& buffer_in
...
-  Buffer::BufferFragmentImpl* fragments_ = nullptr;
-  std::vector<grpc::Slice> slices_;
+class GrpcSliceBufferFragmentImpl : public Buffer::BufferFragment {
+public:
+  explicit GrpcSliceBufferFragmentImpl(grpc::Slice&& slice) : slice_(std::move(slice)) {}
+
+  // Buffer::BufferFragment
+  const void* data() const override { return slice_.begin(); }
+  size_t size() const override { return slice_.size(); }
+  void done() override { delete this; }
```
Comment (silentdai) [inline source/common/grpc/google_grpc_utils.cc]: I am not sure if this is the best behavior: It assumes `GrpcSliceBufferFragmentImpl` is always on heap, which is not necessary although the only usage is :)

Comment (silentdai) [reply source/common/grpc/google_grpc_utils.cc]: I would choose to release the `slice_` here and don't allocate `GrpcSliceBufferFragmentImpl`.
I don't see the best way to release the slice but may be `slice_ = grpc::Slice()` is the closest expression.

File: source/common/grpc/google_grpc_utils.cc [hunk 3]
```diff
@@ -81,28 +86,10 @@ Buffer::InstancePtr GoogleGrpcUtils::makeBufferInstance(const grpc::ByteBuffer&
...
-                                   sizeof(Buffer::BufferFragmentImpl) * slices.size()),
-                 "posix_memalign failure");
-  for (size_t i = 0; i < slices.size(); i++) {
-    new (&container->fragments_[i])
-        Buffer::BufferFragmentImpl(slices[i].begin(), slices[i].size(), releaser);
-  }
+
   for (size_t i = 0; i < slices.size(); i++) {
-    buffer->addBufferFragment(container->fragments_[i]);
+    buffer->addBufferFragment(*new GrpcSliceBufferFragmentImpl(std::move(slices[i])));
```
Comment (silentdai) [inline source/common/grpc/google_grpc_utils.cc]: Along with my other inline comment
```
buffer->addBufferFragment(GrpcSliceBufferFragmentImpl(std::move(slices[i]));
```

File: source/common/grpc/google_grpc_utils.cc [hunk 4]
```diff
@@ -62,12 +62,17 @@ grpc::ByteBuffer GoogleGrpcUtils::makeByteBuffer(Buffer::InstancePtr&& buffer_in
...
+public:
+  explicit GrpcSliceBufferFragmentImpl(grpc::Slice&& slice) : slice_(std::move(slice)) {}
+
+  // Buffer::BufferFragment
+  const void* data() const override { return slice_.begin(); }
+  size_t size() const override { return slice_.size(); }
+  void done() override { delete this; }
+
+private:
+  const grpc::Slice slice_;
```
Comment (silentdai) [inline source/common/grpc/google_grpc_utils.cc]: Along with my suggestion `slice_` cannot be const anymore...

File: source/common/grpc/google_grpc_utils.cc (hunk 2 above)
Comment (lizan) [reply source/common/grpc/google_grpc_utils.cc]: That doesn't work, `addBufferFragment` only takes a reference but not ownership, so it need to being deleted here. This is no different from `Buffer::BufferFragmentImpl` with `delete frag;` in previous commit.

Comment (silentdai) [reply source/common/grpc/google_grpc_utils.cc]: Learnt a lot from the discussion before I write any code to crash the envoy :)

**Comment by lizan** [comment]
> I'm a bit uncomfortable with the possible persistence of the pointers to the buffer fragments past delete since that counts on the implementation of Buffer not to go back and look at them (IIRC done() is called incrementally as the buffer is processed).

@curiouserrandy this is how BufferFragment supposed to work, Buffer doesn't persistent them once the fragments are done.
