### PR TITLE
proxy_protocol: store TLV values in FilterState

### LINKED ISSUE #19046: Proxy Protocol Listener Filter v2 metadata not available at the HTTP level.
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Proxy Protocol Listener Filter v2 metadata not available at the HTTP level.*

*Description*:
Using the Proxy Protocol listener filter[0], we are extracting a TLV, and storing the value in metadata.  We would like to use this data in the HTTP connection manager, i.e. to add the TLV value as an HTTP header.  Access logging at the listener level confirms the TLV is being extracted correctly, and the value placed into dynamic metadata, but http access logging, shows that the values are not visible to the HTTP connection manager.  Based on previous Slack conversations, this seems like it's a bug, or at least isn't the intended behaviour of this filter.

*Repro steps*:

Any client generating ProxyProtocol with TLVs present will work for reproduction.  In our case, an AWS NLB configured with an PrivateLink endpoint service was used.  In this setup, AWS adds a TLV header to all incoming privatelink traffic, which contains a unique downstream identifier, in the standard AWS format[1] (ex: vpce-0xxx).  Note that the first byte in this TLV value is 0x01.  https://github.com/envoyproxy/envoy/issues/18580 references a similar issue, with this same TLV.

*Config*:
The following minimal config was used to reporduce the issue.  Note the cluster configuration, and other config boilerplate has been removed.

```json
{
  "staticResources": {
    "listeners": [
      {
        "name": "front_privatelink_8080",
        "address": {
          "socketAddress": {
            "address": "0.0.0.0",
            "portValue": 8080
          }
        },
        "listenerFilters": [
          {
            "name": "envoy.filters.listener.proxy_protocol",
            "typedConfig": {
              "@type": "type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol",
              "rules": [
                {
                  "tlv_type": 234,
                  "on_tlv_present": {
                    "key": "aws_vpce_id"
                  }
                }
              ]
            }
          },
          {
            "name": "envoy.filters.listener.tls_inspector"
          }
        ],
        "access_log": [
          {
            "name": "envoy.access_loggers.file",
            "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
              "path": "/var/log/envoy/access_listener.log",
              "log_format": {
                "json_format": {
                  "tlv": "%DYNAMIC_METADATA(envoy.filters.listener.proxy_protocol:aws_vpce_id)%"
                }
              }
            }
          }
        ],
        "filterChains": [
          {
            "filterChainMatch": {
              "serverNames": [
                "example.com"
              ]
            },
            "filters": [
              {
                "name": "envoy.http_connection_manager",
                "typedConfig": {
                  "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                  "stat_prefix": "echo",
                  "route_config": {
                    "name": "example",
                    "virtual_hosts": [
                      {
                        "name": "example",
                        "domains": [
                          "*"
                        ],
                        "routes": [
                          {
                            "match": {
                              "prefix": "/"
                            },
                            "route": {
                              "cluster": "example_cluster"
                            },
                          }
                        ],
                      }
                    ]
                  },
                  "http_filters": [
                    {
                      "name": "envoy.filters.http.router"
                    }
                  ],
                  "access_log": [
                    {
                      "name": "envoy.access_loggers.file",
                      "typed_config": {
                        "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                        "path": "/var/log/envoy/access_front.log",
                        "log_format": {
                          "json_format": {
                            "tlv": "%DYNAMIC_METADATA(envoy.filters.listener.proxy_protocol:aws_vpce_id)%"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        ]
      }
    ]
  }
}

```

*Logs*:
from `/var/log/envoy/access_listener.log` (the \u0001 prefix is per-AWS spec):
```
{"tlv":"\u0001vpce-0xxx"}
```

from `/var/log/envoy/access_front.log`:
```
{"tlv":null}
```

### PR DESCRIPTION
**Pull request by wdauchy**
Commit Message:
Store proxy protocol TLV values in FilterState as StringAccessor objects when they match configured rules. This enables filters to access proxy protocol TLV values via FilterStateInput without requiring custom HTTP filters to copy metadata.

Each TLV value is stored with a key format of
"envoy.network.proxy_protocol.tlv.<rule_key>" and Connection lifespan, making it accessible to HTTP filters via the FilterState parent chain.

Fixes #19046

Additional Description:
Risk Level: Low
Testing: Added unit test verifying TLV values are stored and accessible
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc [hunk 1]
```diff
@@ -583,6 +584,18 @@ bool Filter::parseTlvs(const uint8_t* buf, size_t len) {
...
+          absl::StrCat("envoy.network.proxy_protocol.tlv.", key_value_pair->key());
+      if (!cb_->filterState().hasDataWithName(filter_state_key)) {
+        std::string sanitised_value(sanitised_tlv_value.data(), sanitised_tlv_value.size());
+        cb_->filterState().setData(filter_state_key,
+                                   std::make_unique<Router::StringAccessorImpl>(sanitised_value),
+                                   StreamInfo::FilterState::StateType::ReadOnly,
+                                   StreamInfo::FilterState::LifeSpan::Connection);
+        ENVOY_LOG(trace, "proxy_protocol: Stored TLV type {} value in FilterState with key {}",
+                  tlv_type, filter_state_key);
+      }
```
Comment (wbpcode) [inline source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc]: Could we use single filter state for this attributes? Note the filter state could support sub `field`. So, I think it would be better to store a map-like object in the filter state with single key. :)

BTW, could you add a proto API at the proxy_protocol to control this behavior. Like we can add an enum to tell where the data should be stored into:
- DYNAMIC_METADATA (by default to avoid behavior change)
- FILTER_STATE

**Review by wbpcode — COMMENTED** [review]
Thanks. This should make more sense than copy all metadata to request metadata. And I added a comment to that.

File: source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc (hunk 1 above)
Comment (wdauchy) [reply source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc]: agreed, my last push should have addressed all of it

File: api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto [hunk 2]
```diff
@@ -18,11 +18,20 @@ option (udpa.annotations.file_status).package_version_status = ACTIVE;
...
 // [#extension: envoy.filters.listener.proxy_protocol]
 
-// [#next-free-field: 6]
+// [#next-free-field: 7]
 message ProxyProtocol {
   option (udpa.annotations.versioning).previous_message_type =
       "envoy.config.filter.listener.proxy_protocol.v2.ProxyProtocol";
 
+  // Controls where TLV values are stored when rules match.
+  enum TlvStorageLocation {
```
Comment (wbpcode) [inline api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto]: TlvStorageLocation -> TlvLocation

File: api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto [hunk 3]
```diff
@@ -92,4 +101,7 @@ message ProxyProtocol {
   // See the :ref:`filter's statistics documentation <config_listener_filters_proxy_protocol>` for
   // more information.
   string stat_prefix = 5;
+
+  // Controls where TLV values are stored when rules match. Defaults to DYNAMIC_METADATA.
+  TlvStorageLocation tlv_storage_location = 6;
```
Comment (wbpcode) [inline api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto]:
```suggestion
  TlvLocation tlv_location = 6;
```

File: source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc [hunk 4]
```diff
@@ -52,6 +54,52 @@ namespace Extensions {
...
+    const auto& fields = struct_.fields();
+    auto it = fields.find(std::string(field_name));
+    if (it != fields.end() && it->second.has_string_value()) {
+      return absl::string_view(it->second.string_value());
+    }
+    return absl::monostate{};
+  }
+
+private:
+  Protobuf::Struct struct_;
```
Comment (wbpcode) [inline source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc]: For pure string key value map, I think flat_hash_map<std::string, std::string> would be much better?

File: api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto (hunk 3 above)
Comment (wdauchy) [reply api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto]: applied

File: api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto (hunk 2 above)
Comment (wdauchy) [reply api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto]: applied

File: source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc (hunk 4 above)
Comment (wdauchy) [reply source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc]: agreed
