### PR TITLE
OAuth: Use URL-encoding when adding URL as query parameters.

### LINKED ISSUE #23167: OAuth2 filter fails a request with Non-ASCII characters
There is a listener with Oauth2 filter. 

User is not yet authorized.
User sends a request with non-ASCII characters to Envoy like this

`https%3A%2F%2Freg-portal.ca.dev.kontur.ru%3A4433%2FRC%2FSearch%2FLocal?stateGroup%3D0%26typeGroup%3D0%26isFromForm%3DFalse%26Query%3D%D0%B2%D0%B2%D1%81`

Once user authorize (login and password has been inputed), IDP server calls a callback url according our configuration that looks like

`https://reg-portal.ca.dev.kontur.ru:4433/oauth2/callback?state=https%3A%2F%2Freg-portal.ca.dev.kontur.ru%3A4433%2FRC%2FSearch%2FLocal?stateGroup%3D0%26typeGroup%3D0%26isFromForm%3DFalse%26Query%3D%D0%B2%D0%B2%D1%81&session_state=2f0c1f44-6726-47ca-ae04-9b27ab470403&code=d4245176-0970-4250-b536-62e5eb8cc6c9.2f0c1f44-6726-47ca-ae04-9b27ab470403.bac706d3-bede-49cf-b52d-a38a44c98d3c`

If we'll decode this url we get

`https://reg-portal.ca.dev.kontur.ru:4433/oauth2/callback?state=https://reg-portal.ca.dev.kontur.ru:4433/RC/Search/Local?stateGroup=0&typeGroup=0&isFromForm=False&Query=ввс&session_state=2f0c1f44-6726-47ca-ae04-9b27ab470403&code=d4245176-0970-4250-b536-62e5eb8cc6c9.2f0c1f44-6726-47ca-ae04-9b27ab470403.bac706d3-bede-49cf-b52d-a38a44c98d3c`

Most important here is that a state query parameter is a equals our source url and contains Non-ASCII characters (**Query=ввс**)

The problem is that Envoy cannot initialize `Http::Utility::Url` for provided url.

https://github.com/envoyproxy/envoy/blob/7461266aae623c7a0c9858fe9055aaf37aed95b6/source/extensions/filters/http/oauth2/filter.cc#L347-L353

As result I have the error 

> OAuth flow failed

instead of successfull flow.

### PR DESCRIPTION
**Pull request by yanavlasov**
Commit Message:
Decode these query parameters using reverse algorithm but leaving intact character sequences that must be encoded in URLs.

Additional Description:
This change addresses issue raised in #23167, which prevents OAuth filter from working with URLs that contain %-encoded UTF-8 characters in URL path or query.

During development I have also noticed that OAuth uses an odd character set for encoding URLs, which does not correspond to any standard I know. I have replaced it as well with well defined URL-encoding.

The behavioral changes are reflected in the additional tests.

Risk Level: Medium, Behavioral change in OAuth filter
Testing: Unit Tests
Docs Changes: Yes
Release Notes: Yes
Platform Specific Features: N/A
Optional Runtime guard: envoy.reloadable_features.oauth_use_url_encoding
Optional Fixes #23167

Signed-off-by: Yan Avlasov <yavlasov@google.com>

### CODE REVIEW

File: source/common/http/utility.cc [hunk 1]
```diff
@@ -1073,6 +1073,107 @@ std::string Utility::PercentEncoding::decode(absl::string_view encoded) {
...
+    0b00000000000000000000000000000000,
+    0b00000000000000000000000000000000,
+    0b00000000000000000000000000000000,
+    0b00000000000000000000000000000000,
+};
+
+bool testChar(const uint32_t table[8], char c) {
+  uint8_t uc = static_cast<uint8_t>(c);
+  return (table[uc >> 5] & (0x80000000 >> (uc & 0x1f))) != 0;
+}
```
Comment (snowp) [inline source/common/http/utility.cc:1115]: Is this an existing algorithm for checking whether a char is one of a well known set of chars? Not immediately obvious to me how it this works. First part takes the most significant few bits and use them to index into one of the bitmasks, and then the least significant bits are compared against the bitmask?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks! Makes sense to me

File: source/common/http/utility.cc (hunk 1 above)
Comment (yanavlasov) [reply source/common/http/utility.cc:1115]: Yes, we use it in other places, like UHV. It is CPU cache friendly bit array lookup.

The character validity check could be implemented as a table of size 256 with 0 or 1 in each element indicating character validity. This algorithm packs all 1s and 0s into bits of 32 bit words. That expression with shifts is equivalent to division by 32 and getting the remainder of division by 32 to figure which 32 bit word and which bit in that word to check. It is more CPU cache friendly because table size it 64 bytes instead of 256.

File: docs/root/configuration/http/http_filters/oauth2_filter.rst [hunk 2]
```diff
@@ -37,6 +37,20 @@ is set to true the filter will send over a
 cookie named ``BearerToken`` to the upstream. Additionally, the ``Authorization`` header will be populated
 with the same value.
 
+The OAuth filer encodes URLs in query parameters using the 
+`URL encoding alogirthm. <https://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm>`_
```
[the remark this answers is not in the document]
Comment (yanavlasov) [reply docs/root/configuration/http/http_filters/oauth2_filter.rst]: done

File: source/common/http/utility.cc (hunk 1 above)
Comment (snowp) [reply source/common/http/utility.cc:1115]: Makes sense, thanks for explaining!

**Review by snowp — APPROVED** [review]
