### PR TITLE
redis: add success and error stats for commands

### LINKED ISSUE #5439: redis command level success and error stats
Currently redis proxy has only `total` stats at each command level. It is difficult to figure out how many of these commands were successful and how many have failed. It would be easier if we have couple of new stats for each command called `success` and `error` that indicate the success/failure of commands.

### PR DESCRIPTION
**Pull request by ramaraochavali**
*Description*: Adds success and error stats for commands
*Risk Level*: Low
*Testing*: Added automated stats
*Docs Changes*: Added
*Release Notes*: Updated
Fixes #5439

### CODE REVIEW

**Comment by mattklein123** [comment]
@HenryYYang PTAL also. @ramaraochavali looks like you need another master merge. Sorry!

File: source/extensions/filters/network/redis_proxy/command_splitter_impl.cc [hunk 1]
```diff
@@ -31,15 +31,25 @@ void SplitRequestBase::onWrongNumberOfArguments(SplitCallbacks& callbacks,
       fmt::format("wrong number of arguments for '{}' command", request.asArray()[0].asString())));
 }
 
+void SplitRequestBase::updateStats(const bool success) {
```
Comment (ramaraochavali) [inline source/extensions/filters/network/redis_proxy/command_splitter_impl.cc]: I factored this in to a separate method because, I want to follow-up with latency stats as well. This will help to add latency metric in the future PR

File: docs/root/intro/version_history.rst [hunk 2]
```diff
@@ -8,9 +8,11 @@ Version history
 * admin: the admin server can now be accessed via HTTP/2 (prior knowledge).
 * buffer: fix vulnerabilities when allocation fails
 * config: removed deprecated_v1 sds_config from :ref:`Bootstrap config <config_overview_v2_bootstrap>`.
+* config: removed deprecated_v1 sds_config from :ref:`Bootstrap config <config_overview_v2_bootstrap>`.
```
Comment (danielhochman) [inline docs/root/intro/version_history.rst]: nit: dupe

File: docs/root/configuration/network_filters/redis_proxy_filter.rst [hunk 3]
```diff
@@ -56,6 +55,8 @@ The Redis filter will gather statistics for commands in the
   :widths: 1, 1, 2
 
   total, Counter, Number of commands
+  success, Counter, Number of commands that were successful
+  error, Counter, Number of commands that have resulted in errors
```
Comment (danielhochman) [inline docs/root/configuration/network_filters/redis_proxy_filter.rst]: nit: may want to clarify "Number of commands that returned a partial or complete error response"

**Comment by ramaraochavali** [comment]
@mattklein123 resolved the merge conflicts and merged the master. can you PTAL?
