### PR TITLE
listener: match rebalancer to listener IP family type

### LINKED ISSUE #16804: Matching IP Family for Outbound Listener
*Title*: Matching IP Family for Outbound Listener

*Description*:
To support dual stack in istio, for each service that has dual stack configured, two outbound listeners for the same port are created. One listener is with ipv6 wildcard with port and the other one is with ipv4 wildcard with port. 

Here is what we expect:
client (ipv4 address ) -> ipv4 iptable redirect to 15001 -> envoy original dst at 15001 -> only match ipv4 wildcard 0.0.0.0:<port> listener
client (ipv6 address ) -> ipv6 iptable redirect to 15001 -> envoy original dst at 15001 -> only match ipv6 wildcard [::]:<port> listener

However, in the [connection_handler_impl.cc](https://github.com/envoyproxy/envoy/blob/main/source/server/connection_handler_impl.cc#L194-L205)
it was not matching IP family type for the listener and target address.  Instead, it finds the first wildcard matching port from the listener list and it always returns that listener. This causes downstream client can use a different IP family listener from the original destination address. We think the code should match IP family and pick the corresponding wildcard listener based on the original destination IP family type.

```
ConnectionHandlerImpl::findActiveTcpListenerByAddress(const Network::Address::In
                    p.second.typed_listener_) &&
                p.second.listener_->listener() != nullptr &&
                p.first->type() == Network::Address::Type::Ip &&
-               p.first->ip()->port() == address.ip()->port() && p.first->ip()->isAnyAddress();
+               p.first->ip()->port() == address.ip()->port() && p.first->ip()->isAnyAddress() &&
+              ((p.first->ip()->ipv4() != nullptr && address.ip()->ipv4() != nullptr) ||
+               (p.first->ip()->ipv6() != nullptr && address.ip()->ipv6() != nullptr));
       });
```

With the above change, we tested with success of either IPv4 or IPv6 path.
```
kubectl exec -it -n test sleep-86786f67f4-s5bfm sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "sleep" out of: sleep, istio-proxy, istio-init (init)
/ # curl 10.96.65.101:8090/headers
X-Request-Id: a6b06ffb-724b-4785-b490-039dbde0baee
X-B3-Spanid: c1d76544d090db82
Accept: */*
X-Envoy-Attempt-Count: 1
Content-Length: 0
X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/test/sa/simpleserver;Hash=01b9728bd23645e1afc39c96826cbec8b46c6427ac9b147b998935cdd2271adc;Subject="";URI=spiffe://cluster.local/ns/test/sa/sleep
X-B3-Traceid: 24c6d5522b6172d88f843df561d424d8
X-B3-Parentspanid: 8f843df561d424d8
X-B3-Sampled: 0
User-Agent: curl/7.76.1
X-Forwarded-Proto: http
remote addr: 127.0.0.1:48372
host addr: 10.96.65.101:8090
/ # curl simpleserver:8090/headers
X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/test/sa/simpleserver;Hash=01b9728bd23645e1afc39c96826cbec8b46c6427ac9b147b998935cdd2271adc;Subject="";URI=spiffe://cluster.local/ns/test/sa/sleep
X-B3-Spanid: ea96060aa7025f33
X-B3-Parentspanid: f5e7ec00645e238a
User-Agent: curl/7.76.1
Accept: */*
X-Forwarded-Proto: http
X-Request-Id: f6e2dcb1-664d-4f54-baa1-0d5ca615a562
X-Envoy-Attempt-Count: 1
Content-Length: 0
X-B3-Traceid: 872552dfa9f3c99bf5e7ec00645e238a
X-B3-Sampled: 0
remote addr: [::1]:58248
host addr: simpleserver:8090
ipv6 only server
```
This is important for us to enable dual mode support in Istio as we create routes/clusters based on whether IPv4 or IPv6 listener is picked. 

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.
Attached the config_dump from istio.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Envoy logs with added trace:

### PR DESCRIPTION
**Pull request by jacob-delgado**
Commit Message:
When getting a rebalancer by address and a wild card match is being
used, the first match in the list is returned. However, if there are
listeners with addresses "0.0.0.0" and "::" then the first active
listener found will be used, irrespective of the IP family type. Change
the behavior to always return the listener of the same IP family type as
the rebalancer.

Co-authored-by: yingchun.cai@volunteers.acasi.info

Additional Description: N/A
Risk Level: Medium
Testing: TBD
Docs Changes: TBD
Release Notes: inline
Platform Specific Features: N/A
Runtime guard: envoy.reloadable_features.listener_wildcard_match_ip_family
Fixes #16804

### CODE REVIEW

**Comment by jacob-delgado** [comment]
cc @lambdai Please review.

I'm also looking for places to add a test, either in unit test or integration test, but could not find a suitable test to modify. Are you aware of any that I can modify or will I have to write a new one? Any guidance would be helpful.

It's also unclear where I need to modify docs, if at all.

File: source/server/connection_handler_impl.cc [hunk 1]
```diff
@@ -191,17 +192,33 @@ ConnectionHandlerImpl::getBalancedHandlerByAddress(const Network::Address::Insta
...
+        listeners_.begin(), listeners_.end(),
+        [&address](const std::pair<Network::Address::InstanceConstSharedPtr,
+                                   ConnectionHandlerImpl::ActiveListenerDetails>& p) {
+          return absl::holds_alternative<std::reference_wrapper<ActiveTcpListener>>(
+                     p.second.typed_listener_) &&
+                 p.second.listener_->listener() != nullptr &&
+                 p.first->type() == Network::Address::Type::Ip &&
+                 p.first->ip()->port() == address.ip()->port() && p.first->ip()->isAnyAddress() &&
+                 ((p.first->ip()->ipv4() != nullptr && address.ip()->ipv4() != nullptr) ||
+                  (p.first->ip()->ipv6() != nullptr && address.ip()->ipv6() != nullptr));
```
Comment (soulxu) [inline source/server/connection_handler_impl.cc:207]: is it can be done one check 'p.first-ip()->version() == address.ip()->version()'?

File: source/server/connection_handler_impl.cc [hunk 2]
```diff
@@ -191,17 +192,33 @@ ConnectionHandlerImpl::getBalancedHandlerByAddress(const Network::Address::Insta
...
-                   [&address](const std::pair<Network::Address::InstanceConstSharedPtr,
-                                              ConnectionHandlerImpl::ActiveListenerDetails>& p) {
-                     return absl::holds_alternative<std::reference_wrapper<ActiveTcpListener>>(
-                                p.second.typed_listener_) &&
-                            p.second.listener_->listener() != nullptr &&
-                            p.first->type() == Network::Address::Type::Ip &&
-                            p.first->ip()->port() == address.ip()->port() &&
-                            p.first->ip()->isAnyAddress();
-                   });
+  if (Runtime::runtimeFeatureEnabled(
```
Comment (lambdai) [inline source/server/connection_handler_impl.cc:195]: LGTM.

Can you add the test? When the test env declares IPv6, it's actually ipv4+ipv6 dual stack, or ipv6 only.  

You can add a test case that works for both cases and gain more eyes watching it.

**Review by lambdai — COMMENTED** [review]
LGTM!

Can you add the test? When the test env declares IPv6, it's actually ipv4+ipv6 dual stack, or ipv6 only.

You can add a test case that works for both cases and gain more eyes watching it.

**Comment by jacob-delgado** [comment]
> LGTM!
> 
> Can you add the test? When the test env declares IPv6, it's actually ipv4+ipv6 dual stack, or ipv6 only.
> 
> You can add a test case that works for both cases and gain more eyes watching it.

So after reaching out to Yuchen he pointed me to `listener_lds_integration_test.cc:560` for modification. After some investigation I found that listeners are always modified to be of the same IP familly type. Is this approach appropriate? My plan is to get a `fakeUpstream` that is listening on both IPv4 and IPv6 and to check that the appropriate upstream received the incoming data. Would that be a good approach for getting this merged?

Will I also need a unit test for this to be approved? I did take a look at `connection_handler_impl.cc`, but it didn't seem I could easily modify for testing. The `BalancedConnectionHandlerOptRef` that it gave me back (through some dynamtic casting of `handler_` to `ConnectionHandlerImpl` was difficult to parse and verify I was getting back the correct listener. Looking at some of the unit tests (even for `active_tcp_listener`) there's a lot of setup/mocking code. But maybe I'm just looking in the wrong places.

**Comment by ggreenway** [comment]
@lambdai can you answer the above questions?

**Comment by lambdai** [comment]
> So after reaching out to Yuchen he pointed me to `listener_lds_integration_test.cc:560` for modification. After some investigation I found that listeners are always modified to be of the same IP familly type

Sorry I may give the improper advice since I didn't know the trick here.


It's probably easier to unit test it by creating a ConnectionHandlerImpl, add 1 dispatching listener(virtual) and 2 wildcard listener(ipv4 and ipv6) and accept a MockConnection at dispatching listener. The wildcard listeners doesn't require OS ipv4/ipv6 socket now so you should see fewer obstacles. Search for "ActiveTcpListenerTest, RedirectedRebalancer" for reference. That test case confirmed the balance between 2 thread of the same listener  but you may want to confirm the target listener is the correct wildcard listener.

Ping me if you are seeing unexpected challenges.

File: test/server/connection_handler_test.cc [hunk 3]
```diff
@@ -746,6 +747,148 @@ TEST_F(ConnectionHandlerTest, FallbackToWildcardListener) {
...
+        return Network::FilterStatus::Continue;
+      }));
+  EXPECT_CALL(manager_, findFilterChain(_)).WillOnce(Return(filter_chain_.get()));
+  auto* connection = new NiceMock<Network::MockServerConnection>();
+  EXPECT_CALL(dispatcher_, createServerConnection_()).WillOnce(Return(connection));
+  EXPECT_CALL(factory_, createNetworkFilterChain(_, _)).WillOnce(Return(true));
+  listener_callbacks1->onAccept(Network::ConnectionSocketPtr{accepted_socket});
+  EXPECT_EQ(1UL, handler_->numConnections());
+
+  // Add negative test case check
```
Comment (jacob-delgado) [inline test/server/connection_handler_test.cc:812]: cc @lambdai There is where I'm struggling figuring out how to make sure the right listener is being used.

I had added some logging locally and was able to verify the correct listener was being returned, but a stronger check is needed. I was able to track it down to https://github.com/envoyproxy/envoy/blob/d526e38a79d643710d2236322abf7c0804e4146d/source/server/active_tcp_listener.cc#L239 as probably the best way to make sure the correct listener is needed with an `EXPECT_CALL`.

Something similar to
```
EXPECT_CALL(balancer1, pickTargetHandler(_))
      .WillOnce(testing::DoAll(
          testing::WithArg<0>(Invoke([](auto& target) { target.incNumConnections(); })),
          ReturnRef(*active_listener1)));
```

But some of the difficulties are the `connection_handler_test.cc` and `active_tcp_listener_test.cc` both approach similar testing differently. I could move this test into `active_tcp_listener_test.cc` if you'd think that'd be sufficient. I'd prefer to keep it close the `ConnectionHandlerImpl`, but at this point I'm open to move it. Thanks!

Comment (lambdai) [reply test/server/connection_handler_test.cc:812]: IMO The old behavior is not that critical.

File: test/server/connection_handler_test.cc [hunk 4]
```diff
@@ -746,6 +747,148 @@ TEST_F(ConnectionHandlerTest, FallbackToWildcardListener) {
...
+        return Network::FilterStatus::Continue;
+      }));
+  EXPECT_CALL(manager_, findFilterChain(_)).WillOnce(Return(filter_chain_.get()));
+  auto* connection = new NiceMock<Network::MockServerConnection>();
+  EXPECT_CALL(dispatcher_, createServerConnection_()).WillOnce(Return(connection));
+  EXPECT_CALL(factory_, createNetworkFilterChain(_, _)).WillOnce(Return(true));
+  listener_callbacks1->onAccept(Network::ConnectionSocketPtr{accepted_socket});
+  EXPECT_EQ(1UL, handler_->numConnections());
+
+  // metrics aren't sufficient for testing; need a better way to identify the socket
```
Comment (lambdai) [inline test/server/connection_handler_test.cc:882]: If you like, you can create dedicate FilterChainManager for `ipv6_any_listener` and `ipv4_any_listener`
You will expect `manager_ of ipv6_any_listener` be called with findFilterChain

**Review by lambdai — APPROVED** [review]
LGTM. Thanks!

**Comment by jacob-delgado** [comment]
cc @lambdai @ggreenway Yuchen had approved it, but I had to make some changes for coverage and a few other changes to make sure it's working as intended. Looking for a final review.

**Comment by ggreenway** [comment]
> Looking for a final review.

I'll aim to review today.

**Review by ggreenway — APPROVED** [review]
LGTM
