### PR TITLE
oauth2: disable chunked transfer for token request

### LINKED ISSUE #20179: [OAuth2] Failure to get token from login.microsoftonline.com (Azure AD)
*Title*: *Get token from login.microsoftonline.com returns 404*

*Description*:

I'm trying to use the OAuth2 filter to authenticate with Azure AD. The initial redirect to the authorization endpoint works as expected, as well as the callback redirect. But when the callback is being processed by the filter, the request to the token endpoint gets a 404 response, and the filter then fails with a 401 response. I initially had this problem as part of istio, but I get the exact same behavior when I run envoy locally in a docker container.

I can parse the data returned in the callback in a script, and send a token request that works perfectly, so I know that the authorization part is working as it should and that a correct token request does succeed. But for some reason the request that OAuth2 filter sends fails, it could be that the request is missing something or is not formatted correctly.

*Repro steps*:

1. I have configured envoy to listen on port 443 with a LetsEncrypt certificate.
2. I have added domain mytest.euw.dev.hivestreaming.net to my local hosts file, pointing to the docker container's IP address (which is the same as the host's).
3. In Azure AD, I have added an App Registration with the appropriate callback to https://mytest.euw.dev.hivestreaming.net/oauth2/callback, and a secret. The client_id and client_secret used in the filter configuration refer to this service principal.

The actual test consists of calling the URL which is protected by the OAuth2 filter:

1. Start the envoy docker container (docker-compose up).
4. Send request https://mytest.euw.dev.hivestreaming.net/oauth2/sign_out (to trigger a restart of the OAuth flow)
5. Enter login details in authorization endpoint.
6. The callback fails with response code 401 and the body text "OAuth flow failed". The debug logs show that the token request receives response code 404.

*Admin and Stats Output*:

The configuration below doesn't allow accessing these endpoints.

*Config*:

**docker-compose.yaml**
```YAML
version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:latest
    command:
      - envoy
      - -c
      - /etc/envoy/envoy.yaml
      - --component-log-level
      - http:debug,http2:info,connection:debug,upstream:debug,router:debug
    environment:
      ENVOY_UID: "0"
      ENVOY_GID: "0"
    ports:
      - "443:443"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./intserv:/etc/istio/oauth2/intserv
      - ./cert:/etc/istio/cert
      - ./logs:/var/logs
    network_mode: host
```

**envoy.yaml**
```YAML
node:
  id: node1
  cluster: cluster1

static_resources:
  listeners:
  - name: oauth_listener
    address:
      socketAddress:
        address: "0.0.0.0"
        portValue: 443

    filter_chains:
    - transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: TLSv1_2
              cipher_suites:
                - ECDHE-ECDSA-AES128-GCM-SHA256
                - ECDHE-RSA-AES128-GCM-SHA256
                - ECDHE-ECDSA-AES256-GCM-SHA384
                - ECDHE-RSA-AES256-GCM-SHA384
                - ECDHE-ECDSA-CHACHA20-POLY1305
                - ECDHE-RSA-CHACHA20-POLY1305
            tls_certificates:
              - certificate_chain:
                  filename: /etc/istio/cert/tls.crt
                private_key:
                  filename: /etc/istio/cert/tls.key
            alpn_protocols:
              - h2
              - http/1.1
          require_client_certificate: false
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: /dev/stdout
                log_format:
                  text_format_source:
                    inline_string: '[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n'
          http_filters:
          - name: envoy.filters.http.oauth2
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
              config:
                auth_scopes:
                - openid
                authorization_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
                credentials:
                  client_id: my-client-id
                  hmac_secret:
                    name: hmac
                    sds_config:
                      path: /etc/istio/oauth2/intserv/hmac-secret.yaml
                  token_secret:
                    name: token
                    sds_config:
                      path: /etc/istio/oauth2/intserv/token-secret.yaml
                forward_bearer_token: true
                redirect_path_matcher:
                  path:
                    exact: /oauth2/callback
                redirect_uri: https://%REQ(:authority)%/oauth2/callback
                signout_path:
                  path:
                    exact: /oauth2/sign_out
                token_endpoint:
                  cluster: azuread_oauth2
                  timeout: 10s
                  uri: login.microsoftonline.com/common/oauth2/v2.0/token
          - name: envoy.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          tracing: {}
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service
                  timeout: 5s

  clusters:
  - name: service
    connect_timeout: 5s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
  - name: azuread_oauth2
    type: LOGICAL_DNS
    connect_timeout: 10s
    dns_lookup_family: V4_ONLY
    dns_refresh_rate: 60s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: azuread_oauth2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: login.microsoftonline.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: login.microsoftonline.com
        common_tls_context:
          tls_params:
            tls_minimum_protocol_version: TLSv1_2
            cipher_suites:
              - ECDHE-ECDSA-AES128-GCM-SHA256
              - ECDHE-RSA-AES128-GCM-SHA256
              - ECDHE-ECDSA-AES256-GCM-SHA384
              - ECDHE-RSA-AES256-GCM-SHA384
              - ECDHE-ECDSA-CHACHA20-POLY1305
              - ECDHE-RSA-CHACHA20-POLY1305
```
*Logs*:

```
envoy_1  | [2022-03-02 01:00:33.997][16][debug][http] [source/common/http/conn_manager_impl.cc:299] [C0] new stream
envoy_1  | [2022-03-02 01:00:33.997][16][debug][http] [source/common/http/conn_manager_impl.cc:882] [C0][S9797740296726020573] request headers complete (end_stream=true):
envoy_1  | ':method', 'GET'
envoy_1  | ':authority', 'mytest.euw.dev.hivestreaming.net'
envoy_1  | ':scheme', 'https'
envoy_1  | ':path', '/'
envoy_1  | 'upgrade-insecure-requests', '1'
envoy_1  | 'user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.105 Safari/537.36'
envoy_1  | 'accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
envoy_1  | 'sec-fetch-site', 'none'
envoy_1  | 'sec-fetch-mode', 'navigate'
envoy_1  | 'sec-fetch-user', '?1'
envoy_1  | 'sec-fetch-dest', 'document'
envoy_1  | 'sec-ch-ua', '"Chromium";v="98", " Not A;Brand";v="99"'
envoy_1  | 'sec-ch-ua-mobile', '?0'
envoy_1  | 'sec-ch-ua-platform', '"Windows"'
envoy_1  | 'accept-encoding', 'gzip, deflate, br'
envoy_1  | 'accept-language', 'en-US,en;q=0.9,sv;q=0.8,sv-SE;q=0.7,en-SE;q=0.6'
envoy_1  |
envoy_1  | [2022-03-02 01:00:33.997][16][debug][http] [source/common/http/filter_manager.cc:845] [C0][S9797740296726020573] request end stream
envoy_1  | [2022-03-02 01:00:33.997][16][debug][connection] [./source/common/network/connection_impl.h:86] [C0] current connecting state: false
envoy_1  | [2022-03-02 01:00:33.997][16][debug][http] [source/common/http/conn_manager_impl.cc:1483] [C0][S9797740296726020573] encoding headers via codec (end_stream=true):
envoy_1  | ':status', '302'
envoy_1  | 'location', 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=my-client-id&scope=openid&response_type=code&redirect_uri=https%3A%2F%2Fmytest.euw.dev.hivestreaming.net%2Foauth2%2Fcallback&state=https%3A%2F%2Fmytest.euw.dev.hivestreaming.net%2F'
envoy_1  | 'date', 'Wed, 02 Mar 2022 01:00:33 GMT'
envoy_1  | 'server', 'envoy'
envoy_1  |
envoy_1  | [2022-03-02 01:00:34.633][16][debug][http] [source/common/http/conn_manager_impl.cc:299] [C0] new stream
envoy_1  | [2022-03-02 01:00:34.633][16][debug][http] [source/common/http/conn_manager_impl.cc:882] [C0][S18205729046624530172] request headers complete (end_stream=true):
envoy_1  | ':method', 'GET'
envoy_1  | ':authority', 'mytest.euw.dev.hivestreaming.net'
envoy_1  | ':scheme', 'https'
envoy_1  | ':path', '/oauth2/callback?code=0.AQUAiHDVdcRGXEmxcq5-n9KLnHseUZRobW5BhChgc0DO-lQFACM.AQABAAIAAAD--DLA3VO7QrddgJg7Wevrz_iG-eWnycLe8CF9pqZBnQyG78k2Qm09Nr3HHr7AX8atDVZKhLEBQhFx09bVFTJUhHjE1CGZR-6ov6845wU9qX1SLzqa3RhDtBKwAU61HmDIfGXT-V1Do0yN6jlprRjOzjPBg_lQVe2tO0MtWWicF4HihV2DL908wJyLUZ7K8s2WbbU5f-aVRQHW9DItmMWpCENTMQgV7A52I2QArcuZ1w08GaISCf0CmdiBIbdkLDnvkg_KAE_bu_ahNflX4DHgfZ110XVCkWR8UxnrV4WP4UDEUMuhxA3gRvXJTSu_SR4Mu3B6WaCf14K-Anao8wrcYY4fXgLbtBIsaWxmDBxzxHirj7hC-u8uUWv5SOi81YewGPj7oZzBJTJ_qX7AQUS1C2ArTp6fLuEkGRSZUKwDUahisicWDdztgtQF80Tno1WOF1A_nqdcSquvsWSJO9blKEvO0YicgzUEu4ODqXA1L5uQpCn87h9h11WCVUZOmsoF72B3d9KQ5jg1DG-aC2wLBl_--hL2xAbPMs6A6OTPxm-daiYUAnKF6KO3UAFK3v40ne2CYvceXs0_C45TELjCOPEL2k0uXInKIwIXVi1kymt95Bo-I8YS3H7QRm1zrgX42zr3RyDCt_uCCuwO6WNeLUsP1Y5HwmAOJSFjRxPyZ3vIGqR3k1CKfXPpFdVnZOQKPiPQhJs2FzaVtgf_53D3IAA&state=https%3a%2f%2fmytest.euw.dev.hivestreaming.net%2f&session_state=a18419d8-d557-4cd6-827c-8a970a2bcc71'
envoy_1  | 'upgrade-insecure-requests', '1'
envoy_1  | 'user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.105 Safari/537.36'
envoy_1  | 'accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
envoy_1  | 'sec-fetch-site', 'none'
envoy_1  | 'sec-fetch-mode', 'navigate'
envoy_1  | 'sec-fetch-user', '?1'
envoy_1  | 'sec-fetch-dest', 'document'
envoy_1  | 'sec-ch-ua', '"Chromium";v="98", " Not A;Brand";v="99"'
envoy_1  | 'sec-ch-ua-mobile', '?0'
envoy_1  | 'sec-ch-ua-platform', '"Windows"'
envoy_1  | 'accept-encoding', 'gzip, deflate, br'
envoy_1  | 'accept-language', 'en-US,en;q=0.9,sv;q=0.8,sv-SE;q=0.7,en-SE;q=0.6'
envoy_1  |
envoy_1  | [2022-03-02 01:00:34.633][16][debug][http] [source/common/http/filter_manager.cc:845] [C0][S18205729046624530172] request end stream
envoy_1  | [2022-03-02 01:00:34.633][16][debug][connection] [./source/common/network/connection_impl.h:86] [C0] current connecting state: false
envoy_1  | [2022-03-02 01:00:34.633][16][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:43] Dispatching OAuth request for access token.
envoy_1  | [2022-03-02 01:00:34.633][16][debug][router] [source/common/router/router.cc:476] [C0][S17508597091007979337] cluster 'azuread_oauth2' match for URL '/common/oauth2/v2.0/token'
envoy_1  | [2022-03-02 01:00:34.633][16][debug][router] [source/common/router/router.cc:682] [C0][S17508597091007979337] router decoding headers:
envoy_1  | ':path', '/common/oauth2/v2.0/token'
envoy_1  | ':authority', 'login.microsoftonline.com'
envoy_1  | ':method', 'POST'
envoy_1  | ':scheme', 'http'
envoy_1  | 'content-type', 'application/x-www-form-urlencoded'
envoy_1  | 'accept', 'application/json'
envoy_1  | 'x-envoy-internal', 'true'
envoy_1  | 'x-forwarded-for', '172.22.41.239'
envoy_1  | 'x-envoy-expected-rq-timeout-ms', '10000'
envoy_1  |
envoy_1  | [2022-03-02 01:00:34.633][16][debug][router] [source/common/router/upstream_request.cc:420] [C0][S17508597091007979337] pool ready
envoy_1  | [2022-03-02 01:00:34.682][16][debug][router] [source/common/router/router.cc:1333] [C0][S17508597091007979337] upstream headers complete: end_stream=true
envoy_1  | [2022-03-02 01:00:34.682][16][debug][http] [source/common/http/async_client_impl.cc:101] async http request response headers (end_stream=true):
envoy_1  | ':status', '404'
envoy_1  | 'set-cookie', 'x-ms-gateway-slice=estsfd; path=/; secure; httponly'
envoy_1  | 'date', 'Wed, 02 Mar 2022 01:00:36 GMT'
envoy_1  | 'content-length', '0'
envoy_1  | 'x-envoy-upstream-service-time', '48'
envoy_1  |
envoy_1  | [2022-03-02 01:00:34.682][16][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:72] Oauth response code: 404
envoy_1  | [2022-03-02 01:00:34.682][16][debug][upstream] [source/extensions/filters/http/oauth2/oauth_client.cc:73] Oauth response body:
envoy_1  | [2022-03-02 01:00:34.682][16][debug][http] [source/common/http/filter_manager.cc:957] [C0][S18205729046624530172] Sending local reply with details
envoy_1  | [2022-03-02 01:00:34.682][16][debug][http] [source/common/http/conn_manager_impl.cc:1483] [C0][S18205729046624530172] encoding headers via codec (end_stream=false):
envoy_1  | ':status', '401'
envoy_1  | 'content-length', '18'
envoy_1  | 'content-type', 'text/plain'
envoy_1  | 'date', 'Wed, 02 Mar 2022 01:00:34 GMT'
envoy_1  | 'server', 'envoy'
```

### PR DESCRIPTION
**Pull request by mhyllander**
Commit Message: Disable chunked transfer encoding in the oauth2 token request. 
Additional Description: The `Content-Length` header will be added to the token request, which effectively disables `Transfer-Encoding: chunked`. Azure AD login.microsoftonline.com does not support chunked transfers and returns a 404.
Risk Level: Low
Testing: A test case has been added for the presence of the Content-Length header. Manual testing was done using a custom docker image with login.microsoftonline.com as the identity provider. The test setup is described in issue #20179. The custom docker image was built from commit db0b80b and is available at DockerHub as mhyllander/envoy:issue_20179.
Docs Changes: N/A
Release Notes: yes
Platform Specific Features: N/A
Fixes #20179

### CODE REVIEW

File: source/extensions/filters/http/oauth2/oauth_client.cc [hunk 1]
```diff
@@ -40,6 +40,7 @@ void OAuth2ClientImpl::asyncGetAccessToken(const std::string& auth_code,
   const std::string body = fmt::format(GetAccessTokenBodyFormatString, auth_code, encoded_client_id,
                                        encoded_secret, encoded_cb_url);
   request->body().add(body);
+  request->headers().setContentLength(body.length());
```
Comment (daixiang0) [inline source/extensions/filters/http/oauth2/oauth_client.cc:43]: If users do want chunker transfer and not set Content-length, how to deal with it?

Comment (mhyllander) [reply source/extensions/filters/http/oauth2/oauth_client.cc]: I thought about that too, but thought that it might be OK to always disable chunked transfer. But I've now looked through the code and tried to add an optional `disable_chunked_transfer` configuration parameter, which defaults to `false` to preserve the current behavior.

Comment (daixiang0) [reply source/extensions/filters/http/oauth2/oauth_client.cc]: Sound good to me.

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto [hunk 2]
```diff
@@ -101,6 +101,9 @@ message OAuth2Config {
   // Optional resource parameter for authorization request
   // RFC: https://tools.ietf.org/html/rfc8707
   repeated string resources = 10;
+
+  // Disable chunked transfer encoding when requesting an access token.
+  bool disable_chunked_transfer = 11;
```
Comment (lizan) [inline api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:106]: It seems that we can always disable chunked transfer since the request isn't going to be big anyway. It makes more sense without the configuration.

**Review by lizan — CHANGES_REQUESTED** [review]
Can you fix CI as well?

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto (hunk 2 above)
Comment (daixiang0) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:106]: Is chunked transfer useful in the edge case? Not sure.

Comment (mhyllander) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:106]: I'm not an expert, but that was my reasoning too, that the request should be relatively small. At least login.microsoftonline.com apparently assumes so since it doesn't support chunked transfer.

**Comment by marcosrmendezthd** [comment]
@mhyllander we've hit the same exact issue.

**Comment by mhyllander** [comment]
@lizan @daixiang0 Looks like I managed to fix the CI issues. So what about the configuration parameter, do we keep it or not?

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto (hunk 2 above)
Comment (lizan) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:106]: Even when the request is big, the code below doesn't transfer them in chunks. So it doesn't make sense to use chunk transfer anyway. We should just make the change.

Comment (mhyllander) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:106]: @lizan OK, should I revert the commits with the configuration changes?

Comment (lizan) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto:106]: Yes, let's disable chunked transfer for all cases.

**Comment by phlax** [comment]
@lizan looks like this one is ready to go - could you give it a final review?

/wait-any

**Comment by marcosrmendezthd** [comment]
is there a docker image i can use to test this build out until the next release after it has been merged?

**Comment by mhyllander** [comment]
@lizan As per the discussion above, I reverted the configuration parameter so that chunked transfer encoding is always disabled.

File: api/envoy/extensions/filters/http/oauth2/v3/oauth.proto (hunk 2 above)
Comment (mhyllander) [reply api/envoy/extensions/filters/http/oauth2/v3/oauth.proto]: I reverted the configuration parameter.

**Comment by phlax** [comment]
@marcosrmendezthd 

see:

- https://hub.docker.com/r/envoyproxy/envoy-dev/tags
- https://hub.docker.com/r/envoyproxy/envoy-contrib-dev/tags

**Comment by marcosrmendezthd** [comment]
> @marcosrmendezthd
> 
> see:
> 
> * https://hub.docker.com/r/envoyproxy/envoy-dev/tags
> * https://hub.docker.com/r/envoyproxy/envoy-contrib-dev/tags


Thanks @phlax . I am searching for a build with that last commit, [c5e91f0](https://github.com/envoyproxy/envoy/pull/20290/commits/c5e91f0f5b6ea299e1cfacb2113c9de7aaa2b29d), but am unable to find it. Is there a trick to finding the builds for a specific PR?

**Comment by phlax** [comment]
sort of - but its not easy 

you need to click through from one of the azure CI tests `Details` and then onto azp

in the top section of the azp pr run you can see a "related" section which has (for this PR) "11 published" which takes you to the "Artefacts" page

there, under "docker" you should find tarballs with all of the images created in/for CI - untar the relevant one and load the contents with `docker load`

**Review by lizan — COMMENTED** [review]
Can you add a test and release note? Thanks

**Comment by mhyllander** [comment]
@davidnarayan Thanks for that suggestion, I've added it. I wasn't sure what testing I could do.

**Review by lizan — APPROVED** [review]
