### PR TITLE
udp: do not close listen socket after stop listening

### LINKED ISSUE #19006: QuicHttpIntegrationTest.AdminDrainDrainsListeners is flaky
QuicHttpIntegrationTest.AdminDrainDrainsListeners has failed recently in a number of PRs. There appear to be several issues associated with this test that make it flaky. The root of the flakiness, though, seems to be the socket being closed before the connection is finished.

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: After stopListener(), only close all the listen socket of that listen if the listener is not quic.

Risk Level: low, only quic is affected
Testing: re-enabled QuicHttpIntegrationTest::AdminDrainDrainsListeners, added unit test

Fixes #19006

### CODE REVIEW

File: source/server/listener_manager_impl.cc [hunk 1]
```diff
@@ -866,7 +875,14 @@ void ListenerManagerImpl::stopListeners(StopListenersType stop_listeners_type) {
...
           if (listener->listenerTag() == listener_tag) {
-            listener->listenSocketFactory().closeAllSockets();
+            if (!listener->udpListenerConfig().has_value() ||
+                listener->udpListenerConfig()->listenerFactory().isTransportConnectionless()) {
+              // Close the listen socket right away to avoid leaving TCP connections in accept queue
+              // already waiting for long timeout. However, connection-oriented UDP listener
+              // shouldn't close the socket because it needs to receive packets on existing
+              // connection via the listen socket.
+              listener->listenSocketFactory().closeAllSockets();
+            }
```
Comment (RyanTheOptimist) [inline source/server/listener_manager_impl.cc:885]: nit: Since we have this (almost) identical block of logic twice, could we have a method like `maybeCloseAllSockets(ListenerImplPtr listener)` which wraps this?

File: test/integration/quic_http_integration_test.cc [hunk 2]
```diff
@@ -663,8 +663,7 @@ TEST_P(QuicHttpIntegrationTest, PortMigrationFailureOnPathDegrading) {
   EXPECT_EQ(1024u * 2, upstream_request_->bodyLength());
 }
 
-// TODO(#19006): Track down the flakiness and re-enable.
-TEST_P(QuicHttpIntegrationTest, DISABLED_AdminDrainDrainsListeners) {
+TEST_P(QuicHttpIntegrationTest, AdminDrainDrainsListeners) {
```
Comment (RyanTheOptimist) [inline test/integration/quic_http_integration_test.cc:666]: Woo hoo!

Would it make sense to try to write a unit test for the new logic in source/server/listener_manager_impl.cc?

**Review by RyanTheOptimist — COMMENTED** [review]
Thanks for doing this!

File: source/server/listener_manager_impl.cc (hunk 1 above)
Comment (danzh2010) [reply source/server/listener_manager_impl.cc]: done

File: test/integration/quic_http_integration_test.cc (hunk 2 above)
Comment (danzh2010) [reply test/integration/quic_http_integration_test.cc:666]: added

**Review by RyanTheOptimist — APPROVED** [review]
Looks good. Any idea what's up with the failed tests? Flakes, perhaps?

**Comment by danzh2010** [comment]
coverage and api CIs failed in my other PRs as well, the failing test kill_request:kill_request_filter_integration_test is not related to this change.

**Comment by danzh2010** [comment]
CI failures are gone after sync'ing with HEAD. PTAL

**Review by RyanTheOptimist — DISMISSED** [review]

File: source/server/listener_manager_impl.cc [hunk 3]
```diff
@@ -1037,6 +1037,17 @@ Network::ListenSocketFactoryPtr ListenerManagerImpl::createListenSocketFactory(
   }
 }
 
+void ListenerManagerImpl::maybeCloseSocketsForListener(ListenerImpl& listener) {
+  if (!listener.udpListenerConfig().has_value() ||
+      listener.udpListenerConfig()->listenerFactory().isTransportConnectionless()) {
+    // Close the listen socket right away to avoid leaving TCP connections in accept queue
+    // already waiting for long timeout. However, connection-oriented UDP listener shouldn't
```
Comment (alyssawilk) [inline source/server/listener_manager_impl.cc:1044]: nit: UDP listener -> UDP listeners

File: source/server/listener_manager_impl.cc [hunk 4]
```diff
@@ -1037,6 +1037,17 @@ Network::ListenSocketFactoryPtr ListenerManagerImpl::createListenSocketFactory(
...
+    // close the socket because it needs to receive packets on existing connection via the
```
Comment (alyssawilk) [inline source/server/listener_manager_impl.cc:1045]: it needs to -> they need to 
on existing connection -> for existing connections

**Review by alyssawilk — COMMENTED** [review]
Lgtm modulo minor comment nits

File: source/server/listener_manager_impl.cc (hunk 3 above)
Comment (danzh2010) [reply source/server/listener_manager_impl.cc]: done

File: source/server/listener_manager_impl.cc (hunk 4 above)
Comment (danzh2010) [reply source/server/listener_manager_impl.cc]: done

**Comment by danzh2010** [comment]
ping @mattklein123

**Comment by RyanTheOptimist** [comment]
I think Matt it out on paternity leave. Once alyssa is happy, I think we should be good to go?

**Review by mattklein123 — APPROVED** [review]
Cool, thanks for the back and forth discussion on this one. I think this is the right fix.
