### PR TITLE
mysql_filter: fix integration test flakes

### LINKED ISSUE #6131: asan test timeout
See: https://circleci.com/gh/envoyproxy/envoy/174482

I wonder if this is flakey?
> //test/extensions/filters/network/mysql_proxy:mysql_integration_test    TIMEOUT in 315.0s

### LINKED ISSUE #6162: //test/extensions/filters/network/mysql_proxy:mysql_integration_test fails consistently on macOS
*Description*:
```
Executing tests from //test/extensions/filters/network/mysql_proxy:mysql_integration_test
-----------------------------------------------------------------------------
[==========] Running 6 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 6 tests from IpVersions/MySQLIntegrationTest
[ RUN      ] IpVersions/MySQLIntegrationTest.MySQLStatsNewSessionTest/0
[       OK ] IpVersions/MySQLIntegrationTest.MySQLStatsNewSessionTest/0 (225 ms)
[ RUN      ] IpVersions/MySQLIntegrationTest.MySQLStatsNewSessionTest/1
test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc:61: Failure
Value of: fake_upstreams_[0]->waitForRawConnection(fake_upstream_connection)
  Actual: false (Timed out waiting for raw connection)
Expected: true
[2019-03-04 20:25:25.653][9117704][critical][assert] [source/common/network/connection_impl.cc:74] assert failure: !ioHandle().isOpen() && delayed_close_timer_ == nullptr. Details: ConnectionImpl was unexpectedly torn down without being closed.
[2019-03-04 20:25:25.654][9117704][critical][backtrace] [bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Abort trap: 6, suspect faulting address 0x7fff6bb9623e
[2019-03-04 20:25:25.654][9117704][critical][backtrace] [bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
external/bazel_tools/tools/test/test-setup.sh: line 310: 72454 Abort trap: 6           "${TEST_PATH}" "$@" 2>&1
```

Tagging #6003, as a result of that we don't run this test in CI currently.

@rshriram @venilnoronha?

*Repro steps*:
`bazel test //test/extensions/filters/network/mysql_proxy:mysql_integration_test`

### PR DESCRIPTION
**Pull request by venilnoronha**
Description: This fixes flakes in the MySQL integration tests by introducing an exact
match for server responses. A separate issue was found when running under IPv6 due to the presence of IPv4 addresses in the test configuration. This fixes that issue as well.
Risk Level: Low
Testing: Ran `mysql_integration_test` x5000
Docs Changes: N/A
Release Notes: N/A
Fixes #6162
Fixes #6131

### CODE REVIEW

**Comment by jmarantz** [comment]
I got I think the same failure:
```
test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc:63: Failure
Value of: fake_upstreams_[0]->waitForRawConnection(fake_upstream_connection)
  Actual: false (Timed out waiting for raw connection)
Expected: true
[2019-03-12 20:02:50.503][14][critical][assert] [source/common/network/connection_impl.cc:74] assert failure: !ioHandle().isOpen() && delayed_close_timer_ == nullptr. Details: ConnectionImpl was unexpectedly torn down without being closed.
[2019-03-12 20:02:50.503][14][critical][backtrace] [bazel-out/k8-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Aborted, suspect faulting address 0x110900000000e
```

qq: is there a requirement that we have mysql installed locally as a service to run Envoy tests?

**Comment by venilnoronha** [comment]
No, `mysql` isn't required to run tests.

**Comment by venilnoronha** [comment]
@jmarantz what's OS are you running these tests on?

**Comment by venilnoronha** [comment]
@jmarantz I believe the flakes are fixed now.

**Comment by jmarantz** [comment]
Still fails for me; patching latest commit. Will poke around in the debugger for a few minutes.

**Comment by jmarantz** [comment]
I didn't get anywhere debugging yet, and I'm not going to be able to get back to it tonight. My OS is  4.19.20-1rodete1-amd64 #1 SMP Debian 4.19.20-1rodete1 (2019-02-12 > 2018) x86_64 GNU/Linux

**Comment by jmarantz** [comment]
It's worth noting that it failed for me in fastbuild, debug (g++), under tsan, and opt. The opt build was compiled without ASSERT of course, so the message was different:
```
[ RUN      ] IpVersions/MySQLIntegrationTest.MySQLStatsNewSessionTest/1
test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc:61: Failure
Value of: fake_upstreams_[0]->waitForRawConnection(fake_upstream_connection)
  Actual: false (Timed out waiting for raw connection)
Expected: true
[  FAILED  ] IpVersions/MySQLIntegrationTest.MySQLStatsNewSessionTest/1, where GetParam() = 4-byte object <01-00 00-00> (10027 ms)
[ RUN      ] IpVersions/MySQLIntegrationTest.MySQLLoginTest/0
[       OK ] IpVersions/MySQLIntegrationTest.MySQLLoginTest/0 (27 ms)
[ RUN      ] IpVersions/MySQLIntegrationTest.MySQLLoginTest/1
test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc:84: Failure
Value of: fake_upstreams_[0]->waitForRawConnection(fake_upstream_connection)
  Actual: false (Timed out waiting for raw connection)
Expected: true
[  FAILED  ] IpVersions/MySQLIntegrationTest.MySQLLoginTest/1, where GetParam() = 4-byte object <01-00 00-00> (10026 ms)
[ RUN      ] IpVersions/MySQLIntegrationTest.MySQLUnitTestMultiClientsLoop/0
[       OK ] IpVersions/MySQLIntegrationTest.MySQLUnitTestMultiClientsLoop/0 (32 ms)
[ RUN      ] IpVersions/MySQLIntegrationTest.MySQLUnitTestMultiClientsLoop/1
test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc:131: Failure
Value of: fake_upstreams_[0]->waitForRawConnection(fake_upstream_connection)
  Actual: false (Timed out waiting for raw connection)
Expected: true
[  FAILED  ] IpVersions/MySQLIntegrationTest.MySQLUnitTestMultiClientsLoop/1, where GetParam() = 4-byte object <01-00 00-00> (10026 ms)
```

**Comment by venilnoronha** [comment]
@jmarantz I figured it out. The tests were failing specifically for IPv6 because of static IPv4 addresses in Envoy configuration. I've fixed that in 9ed7dd0. Could you test it once more on your local system?

**Comment by jmarantz** [comment]
The latest patch works for me! The question that brings to mind is who was able to get these tests to pass *without* this? But that's a question for another day.

Thanks for the fix!

File: test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc [hunk 1]
```diff
@@ -74,8 +77,8 @@ TEST_P(MySQLIntegrationTest, MySQLStatsNewSessionTest) {
  * - correct number of attempts
  * - no failures
  */
-TEST_P(MySQLIntegrationTest, MysqLoginTest) {
-  std::string str;
+TEST_P(MySQLIntegrationTest, MySQLLoginTest) {
+  std::string str = "";
```
Comment (jmarantz) [inline test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc]: This initializer is not needed.

File: test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc [hunk 2]
```diff
@@ -116,9 +123,9 @@ TEST_P(MySQLIntegrationTest, MysqLoginTest) {
 TEST_P(MySQLIntegrationTest, MySQLUnitTestMultiClientsLoop) {
   int idx;
   std::string rcvd_data;
-  std::string str;
 
   for (idx = 0; idx < CLIENT_NUM; idx++) {
+    std::string str = "";
```
Comment (jmarantz) [inline test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc]: ditto

File: test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc (hunk 1 above)
Comment (venilnoronha) [reply test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc]: Fixed in 608507d.

File: test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc (hunk 2 above)
Comment (venilnoronha) [reply test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc]: Fixed in 608507d.

File: test/extensions/filters/network/mysql_proxy/mysql_test_config.yaml [hunk 3]
```diff
@@ -2,7 +2,7 @@ admin:
   access_log_path: /dev/null
```
Comment (mattklein123) [inline test/extensions/filters/network/mysql_proxy/mysql_test_config.yaml]: Question: Why are we using this config vs. just using the default config and config modifiers? Would that have made it easier to prevent this issue?

Comment (venilnoronha) [reply test/extensions/filters/network/mysql_proxy/mysql_test_config.yaml]: I think we could have done it either way. However, @gvalentinivmw might know more. We could have still run into this issue as the config modifiers itself don't constrain IP addresses AFAIK.

Comment (mattklein123) [reply test/extensions/filters/network/mysql_proxy/mysql_test_config.yaml]: OK that's fine. It's not a big deal either way, though I think in general it's better to use the stock config in case that changes in the future.

Comment (jmarantz) [reply test/extensions/filters/network/mysql_proxy/mysql_test_config.yaml]: For the record, I think the problem here is related to a bug I reported a while back: https://github.com/envoyproxy/envoy/issues/5556

it'd be nice to make tests that do not care about ports not have to specify anything about them, or care about ipv6 vs ipv4.

Comment (venilnoronha) [reply test/extensions/filters/network/mysql_proxy/mysql_test_config.yaml]: Yea, that'd definitely be helpful.
