### PR TITLE
bootstrap: allow /dev/fd/<fd> paths for config files

### LINKED ISSUE #7258: Consider relaxing /dev config file restrictions for /dev/fd/*
#3165 added additional file path sanity checking to avoid legitimate bad cases found during fuzz testing.

Unfortunately it breaks one valid case we have.

For background: Consul Connect need to configure Envoy's bootstrap to point it to the local Consul agent as an xDS endpoint. In order to enforce our security model where an agent is shared between different services/pods, the bootstrap therefore has to include a secret value that can be used to Authenticate the caller when passed in gRPC headers:

https://github.com/hashicorp/consul/blob/acfcc7daf4b795a9c531f4da275d5628a4b0017e/command/connect/envoy/bootstrap_tpl.go#L159-L166

```json
...
    "ads_config": {
      "api_type": "GRPC",
      "grpc_services": {
        "initial_metadata": [
          {
            "key": "x-consul-token",
            "value": "{{ .Token }}"
          }
...
```

We then have a helper command `consul connect envoy` that generates to correct bootstrap based on the local environment and the central proxy configuration in Consul before execing the envoy binary directly. (It is possible to just output the config for use with container etc. but the exec form is a nice shorthand where both consul and envoy binaries are available e.g. in Dev).

This left us with an unpleasant choice about how to pass the bootstrap config:
 1. Write it to a file and pass the path
 2. Pass it in the command arg

1 is unpleasant because you are writing a secret to disk somewhere silently without direct user control. 2 is even worse because although the secret isn't on disk it's now visible to most users on the system that can access the /proc info for the command and see it's arguments.

The solution we came up with was to create a temp file, and immediately unlink (without closing) it so it's not accessible in the file system, disable CLOEXEC on it, write the bootstrap content to it, and then exec Envoy. We then pass Envoy the `/dev/fd/<fd>` path as the config file which allows it to open the file directly from the inherited open FD even though the file is not present on the filesystem. Code for this is in https://github.com/hashicorp/consul/blob/master/command/connect/envoy/exec_unix.go.

Of course this mechanism is now broken in 1.10 by the check for `/dev`.

It seems reasonable to me to relax the checking and allow `/dev/fd/*` for this purpose.

We'd also be open to exploring alternative secure ways to pass bootstrap config to Envoy.

Thanks!

### PR DESCRIPTION
**Pull request by banks**
Signed-off-by: Paul Banks <banks@banksco.de>

**Description**:

As noted in #7528 the newly added sanity checking of possibly sensitive file paths prevents legitimate usage of passing bootstrap via a non-CLOEXEC file descriptor from a generator helper that execs Envoy.

This PR relaxes the validation such that any path resolving to a canonical path with the prefix `/dev/fd/` is considered valid.

**Risk Level**: Low
**Testing**: Unit test case is added that was failing before the change and passes afterwards. In addition I've manually verified that the old behaviour of allowing /dev/fd/<fd> paths works with my dev binary.
**Docs Changes**: None, I didn't find this limitation documented currently.
**Release Notes**: N/A (I didn't see the original change to make /dev invalid in 1.10 notes so I assume this doesn't warrant going in either.)

Fixes #7258

### CODE REVIEW

**Comment by banks** [comment]
Hmm the test failure seems legit - at least `filesystem_impl_test` is failing in CI. Passed on my machine. I'll take a look.

**Comment by lizan** [comment]
@banks I guess it is due to on some system {/dev/fd,/0} is a symlink, so the canonical path is outside of it. on my Linux /dev/fd/0 points to /dev/pts/4 (where it links to depends on the process I think.

**Comment by banks** [comment]
Thanks, I think you’re right. I guess that makes this not the simple fix I hoped. I’ll take another look next week but might need to abandon this if the list of possible places is large across different systems.

File: source/common/filesystem/posix/filesystem_impl.cc [hunk 1]
```diff
@@ -87,6 +87,17 @@ std::string InstanceImplPosix::fileReadToEnd(const std::string& path) {
...
+  // Special case, allow /dev/fd/* access here so that config can be passed in a
+  // file descriptor from an execing bootstrap script. The reason we do this
+  // _before_ canonicalizing the path is that different unix flavors implement
+  // /dev/fd/* differently, for example on linux they are symlinks to /dev/pts/*
+  // which are symlinks to /proc/self/fds/. On BSD (and darwin) they are not
+  // symlinks at all. To avoid lots of platform, specifics, we whitelist
+  // /dev/fd/* _before_ resolving the canonical path.
+  if (absl::StartsWith(path, "/dev/fd/")) {
+    return false;
+  }
```
Comment (banks) [inline source/common/filesystem/posix/filesystem_impl.cc]: This seems to be the simplest approach here rather than trying to research all the different OS implementations of this path and white list every possible ending point.

I'm not sure if there are any specific downsides of bypassing `realpath` here?

**Comment by banks** [comment]
Coverage test fail downloading some dependency...

**Comment by banks** [comment]
@htuch since you were assigned on the issue, would this be of interest to merge? Thanks!

File: source/common/filesystem/posix/filesystem_impl.cc (hunk 1 above)
Comment (htuch) [reply source/common/filesystem/posix/filesystem_impl.cc]: Sorry for the delay, been catching up on backlog after OOO. I think this is fine for now, but can you leave a TODO to switch to `https://en.cppreference.com/w/cpp/filesystem/absolute` when we have C++17? The main downside of what you have is that there is no relative path normalization, which we want independent of symlink following.
/wait

Comment (banks) [reply source/common/filesystem/posix/filesystem_impl.cc]: Added the TODO. I hope this is appropriate - I added it under your username as it seems to be more likely you will have context for this later than I will!

**Comment by banks** [comment]
Hey @htutch, is this TODO what you meant? Thanks!

**Comment by htuch** [comment]
@banks yep. Can you squash, fix DCO and force push? I can merge when CI DCO check passes.

**Comment by banks** [comment]
@htuch sorry, been travelling this week I think this should all be good to go now once CI completes.
