### PR TITLE
Use local_info.node() instead of bootstrap.node() whenever possible

### LINKED ISSUE #4085: --service-node and --service-cluster are not used when sending DiscoveryRequest
*Description*:
When envoy is run with --service-node and --service-cluster cli parameters the values are not respected when sending xDS DiscoveryRequests. If node element is present in the bootstrap file the values from bootstrap are sent, if node element is not present in bootstrap file node.id and node.cluster in DiscoveryRequest are empty.

Expected behavior is that value passed to --service-node is used as node.id in all DiscoveryRequests and --service-cluster is used as node.cluster.

*Repro steps*:
Given envoy is run with the following command
```envoy --service-cluster cluster0 --service-node _Node_0 -c envoy.yaml```
and node element is not present in envoy.yaml file, all xDS request are snet with following node definition:
```
Sending DiscoveryRequest for type.googleapis.com/envoy.api.v2.Cluster: node {
   build_version: "3f59fb5c0f6554f8b3f2e73ab4c1437a63d42668/1.7.0/Clean/RELEASE"
}
```

### PR DESCRIPTION
**Pull request by dio**
*Description*:
Use `local_info.node()` instead of `bootstrap.node()` whenever possible.

*Risk Level*: Low
*Testing*: Existing
*Docs Changes*: N/A
*Release Notes*: N/A
Fixes #4085

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

**Comment by mattklein123** [comment]
Test please?

**Comment by dio** [comment]
@mattklein123 yes, sorry missing some commits. I'm on it.

**Comment by ramaraochavali** [comment]
WDYT about adding an `ASSERT` while creating `DiscoveryRequest` which validates the existence of these two fields in the request?

**Comment by dio** [comment]
@mattklein123 I feel no confidence on the change for initializing `LoadStatsReporter` here: https://github.com/envoyproxy/envoy/pull/4120/files#diff-982df999d2cabd23afd6c25088035bf5R304 getting `node()` information from `local_info` instead of `bootstrap`; this is for consistency reason only (while `LoadStatsReporter` doesn't use `id()` or `cluster()` value).

And I haven't found a way to check the effect of those CLI flags directly. But, since it is being forced for xDS, via `Utility::checkLocalInfo`, I think the change here is fine.

**Comment by dio** [comment]
@ramaraochavali yeah, I'm thinking the same, what do you think about: https://github.com/envoyproxy/envoy/pull/4120/commits/6c263d3ebd2d8f16aed23b14c5ca8a892f41490f Do you have any suggestions to add a similar check in other places?

File: source/common/upstream/cluster_manager_impl.cc [hunk 1]
```diff
@@ -211,7 +211,7 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::config::bootstrap::v2::Boots
   // Now setup ADS if needed, this might rely on a primary cluster.
   if (bootstrap.dynamic_resources().has_ads_config()) {
     ads_mux_.reset(new Config::GrpcMuxImpl(
-        bootstrap.node(),
+        local_info.node(),
```
Comment (ramaraochavali) [inline source/common/upstream/cluster_manager_impl.cc]: Can we add method similar to Config::Utility::checkLocalInfo("ads", local_info);  at https://github.com/envoyproxy/envoy/blob/master/source/common/config/grpc_mux_impl.cc#L18 and validate that node has right info?

Comment (dio) [reply source/common/upstream/cluster_manager_impl.cc]: Yes, we can. However currently, if we failed to supply the info, it first throws an error for "cds", which I think serves the same purpose.

```
[2018-08-13 17:32:35.821][2350767][critical][main] source/server/server.cc:78] error initializing configuration '/envoy/config-local.yaml': cds: setting --service-cluster and --service-node is required
```

File: test/integration/ads_integration_test.cc [hunk 2]
```diff
@@ -132,6 +132,10 @@ class AdsIntegrationTest : public AdsIntegrationBaseTest,
     envoy::api::v2::DiscoveryRequest discovery_request;
     VERIFY_ASSERTION(ads_stream_->waitForGrpcMessage(*dispatcher_, discovery_request));
 
+    ASSERT(discovery_request.has_node());
```
[the remark this answers is not in the document]
Comment (dio) [reply test/integration/ads_integration_test.cc]: Yes, sure. Thanks for this.

File: source/common/upstream/cluster_manager_impl.cc (hunk 1 above)
Comment (dio) [reply source/common/upstream/cluster_manager_impl.cc]: @ramaraochavali after an experiment, I think it is tempting to have `Config::Utility::checkLocalInfo` inside the `GrpcMuxImpl`'s constructor (and testing it is easier, yeay!). However, since we want to pass in the `local_info` here, the implication is quite large (but mostly "replacing" `node` with `local_info`). I have the changeset ready but want to gather opinions about it. 

cc. @htuch @mattklein123.

File: test/integration/load_stats_integration_test.cc [hunk 3]
```diff
@@ -164,6 +164,9 @@ class LoadStatsIntegrationTest : public HttpIntegrationTest,
       return;
     } else if (loadstats_request.cluster_stats_size() == 0) {
       loadstats_request.CopyFrom(local_loadstats_request);
+      ASSERT(loadstats_request.has_node());
```
Comment (htuch) [inline test/integration/load_stats_integration_test.cc]: You probably want `ASSERT_TRUE` to use the asserts from gtest.

File: source/common/upstream/cluster_manager_impl.cc [hunk 4]
```diff
@@ -301,7 +301,7 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::config::bootstrap::v2::Boots
   if (cm_config.has_load_stats_config()) {
     const auto& load_stats_config = cm_config.load_stats_config();
     load_stats_reporter_.reset(
-        new LoadStatsReporter(bootstrap.node(), *this, stats,
+        new LoadStatsReporter(local_info.node(), *this, stats,
```
Comment (htuch) [inline source/common/upstream/cluster_manager_impl.cc]: Another option, not saying you have to do this, is to treat the CLI flags as a bootstrap override and override the bootstrap proto early in server config, so that `local_info` and `bootstrap` are consistent. Or, maybe nuke node from bootstrap once you've loaded up local_info. Ideally we have a single source-of-truth, and it's hard to confuse with other potential sources.

File: source/common/upstream/cluster_manager_impl.cc [hunk 5]
```diff
@@ -211,7 +211,7 @@ ClusterManagerImpl::ClusterManagerImpl(const envoy::config::bootstrap::v2::Boots
   // Now setup ADS if needed, this might rely on a primary cluster.
   if (bootstrap.dynamic_resources().has_ads_config()) {
     ads_mux_.reset(new Config::GrpcMuxImpl(
-        bootstrap.node(),
+        local_info,
```
Comment (htuch) [inline source/common/upstream/cluster_manager_impl.cc]: I have mixed opinions on this change. On the one hand, we make it more full proof, by forcing the `LocalInfo` type. On the other, we are now passing a strict superset of what we were passing before, and the new information is not used. My main thoughts on making `LocalInfo` canonical would be to just delete the node info from bootstrap very early in server init. But, this approach also works..

File: test/common/config/grpc_mux_impl_test.cc [hunk 6]
```diff
@@ -402,6 +418,28 @@ TEST_F(GrpcMuxImplTest, UnwatchedTypeRejectsResources) {
...
 
+TEST_F(GrpcMuxImplTest, BadLocalInfoEmptyClusterName) {
+  EXPECT_CALL(local_info_, clusterName()).WillOnce(Return(""));
+  EXPECT_THROW_WITH_MESSAGE(
+      GrpcMuxImpl(
+          local_info_, std::unique_ptr<Grpc::MockAsyncClient>(async_client_), dispatcher_,
+          *Protobuf::DescriptorPool::generated_pool()->FindMethodByName(
+              "envoy.service.discovery.v2.AggregatedDiscoveryService.StreamAggregatedResources"),
+          random_, time_source_),
+      EnvoyException, "ads: setting --service-cluster and --service-node is required");
```
[the remark this answers is not in the document]
Comment (dio) [reply test/common/config/grpc_mux_impl_test.cc]: I had some difficulties with crafting related test before, so I guess I need to read more on bootstrap steps.

File: test/common/config/grpc_mux_impl_test.cc [hunk 7]
```diff
@@ -33,16 +34,17 @@ namespace {
...
 class GrpcMuxImplTest : public testing::Test {
 public:
-  GrpcMuxImplTest()
-      : async_client_(new Grpc::MockAsyncClient()), timer_(new Event::MockTimer()), time_source_{} {
+  GrpcMuxImplTest() : async_client_(new Grpc::MockAsyncClient()), time_source_{} {}
+
+  void setup() {
     EXPECT_CALL(dispatcher_, createTimer_(_)).WillOnce(Invoke([this](Event::TimerCb timer_cb) {
       timer_cb_ = timer_cb;
+      timer_ = new Event::MockTimer();
```
[the remark this answers is not in the document]
Comment (dio) [reply test/common/config/grpc_mux_impl_test.cc]: Since the newly introduced tests do not call `setup()`, and `timer_` was previously initialized as `new Event::MockTimer()` at constructor, this makes sure no leak. Caught by LeakSanitizer in this build: https://circleci.com/gh/envoyproxy/envoy/84216.

File: source/common/upstream/cluster_manager_impl.cc (hunk 5 above)
Comment (dio) [reply source/common/upstream/cluster_manager_impl.cc]: Interesting POV, will try to explore that too.

File: test/common/config/grpc_mux_impl_test.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (dio) [reply test/common/config/grpc_mux_impl_test.cc]: Think we should revisit the thrown error message from `Config::Utility::checkLocalInfo(_, _);`.

File: source/common/upstream/cluster_manager_impl.cc (hunk 5 above)
Comment (htuch) [reply source/common/upstream/cluster_manager_impl.cc]: It's not necessarily the correct PoV; just sharing where my thinking was originally :)

File: test/common/config/grpc_mux_impl_test.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (htuch) [reply test/common/config/grpc_mux_impl_test.cc]: Yep, agree.
