### PR TITLE
load balancer: use the right scheduler when targeting degraded hosts

### LINKED ISSUE #6287: Sporadic UH during host updates
We've been seeing occasional requests fail with UH during deploys when using active health checking.

In this case we have 4 hosts that all have equal weighting (2 in each locality, with same locality weighting and same priority):

L1 has hosts A B
L2 has hosts C D

This is followed by a bunch of empty priorities (probably not relevant, but mentioning for the sake of completeness).

A rolling restart (no overlapping downtime, verified by looking at the hc logs) of the hosts in L2 result in calls from downstream failing with UH. Looking at the active health check logs for the downstream, we see the hosts in L2 go unhealthy, but neither A nor B have a failing health check event in the health check log. 

This is a low traffic setup, so we just see one failure, and by the time the next call is made everything is back to normal.

This kinda seems like we're routing a request while we're in some intermediate state where we end up routing to a `HostSet` with no hosts, but I don't have a great explanation as to why that might happen. @htuch Any clue what might be going on?

We're seeing this on dfbb069d634884e386130dc1b74ef0ff2d4657b0

### PR DESCRIPTION
**Pull request by snowp**
This fixes a bug where the wrong locality scheduler was used when
targeting degraded hosts. Instead of using the scheduler with weights
adjusted for the number of degraded hosts, the regular one adjusted for
the number of *healthy* hosts would be used instead. This would lead to
occasional UH failures because a degraded priority was selected, but a
locality with no degraded hosts got selected.

Signed-off-by: Snow Pettersen <snowp@squareup.com>

Risk Level: Medium
Testing: Added UT verifying we use the correct scheduler
Docs Changes: n/a
Release Notes: n/a
Fixes #6287

### CODE REVIEW

File: include/envoy/upstream/upstream.h [hunk 1]
```diff
@@ -300,6 +300,12 @@ class HostSet {
    */
   virtual absl::optional<uint32_t> chooseLocality() PURE;
```
[the remark this answers is not in the document]
Comment (snowp) [reply include/envoy/upstream/upstream.h]: that's a good idea, will do

File: source/common/upstream/upstream_impl.h [hunk 2]
```diff
@@ -387,6 +388,9 @@ class HostSetImpl : public HostSet {
       HostsPerLocalityConstSharedPtr all_hosts_per_locality,
       LocalityWeightsConstSharedPtr locality_weights, uint32_t overprovisioning_factor);
 
+  static absl::optional<uint32_t>
+  chooseLocality(std::unique_ptr<EdfScheduler<LocalityEntry>>& locality_scheduler);
+
   std::vector<std::shared_ptr<LocalityEntry>> locality_entries_;
   std::unique_ptr<EdfScheduler<LocalityEntry>> locality_scheduler_;
```
Comment (venilnoronha) [inline source/common/upstream/upstream_impl.h]: Should we also rename these to `healthy_locality_entries_` and `healthy_locality_entries_` respectively?

File: source/common/upstream/upstream_impl.h [hunk 3]
```diff
@@ -387,6 +388,9 @@ class HostSetImpl : public HostSet {
       HostsPerLocalityConstSharedPtr all_hosts_per_locality,
       LocalityWeightsConstSharedPtr locality_weights, uint32_t overprovisioning_factor);
 
+  static absl::optional<uint32_t>
+  chooseLocality(std::unique_ptr<EdfScheduler<LocalityEntry>>& locality_scheduler);
```
Comment (mergeconflict) [inline source/common/upstream/upstream_impl.h]: nit: this should probably just take an `EdfScheduler<LocalityEntry>&`

Comment (snowp) [reply source/common/upstream/upstream_impl.h]: Since it checks for nullptr I can't do that without adding null checks elsewhere, but I guess I could change it to raw pointer

Comment (mergeconflict) [reply source/common/upstream/upstream_impl.h]: That'd work, or no change would be fine too :)

Comment (mattklein123) [reply source/common/upstream/upstream_impl.h]: Passing a raw pointer in this case is more common, so I would probably do that, though it doesn't matter that much.
