### PR TITLE
aws_request_signing: fix coverage

### LINKED ISSUE #11990: extensions/filters/http/aws_request_signing coverage
Hello,
The Envoy project has recently started collecting per-extension coverage. You have been tagged with this issue as you are a co-owner of an extension, extensions/filters/http/aws_request_signing, which is below the 96.6 percent coverage mark.
Could you please take a look at coverage results (https://storage.googleapis.com/envoy-postsubmit/master/coverage/index.html) and add more tests when you get a chance? Once this is done you should be able to remove your extension from the exempt extensions in [test/per_file_coverage.sh](https://github.com/envoyproxy/envoy/blob/master/test/per_file_coverage.sh) 
Thanks!

### PR DESCRIPTION
**Pull request by rgs1**
Fixes #11990.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

### CODE REVIEW

File: test/extensions/filters/http/aws_request_signing/aws_request_signing_filter_test.cc [hunk 1]
```diff
@@ -72,6 +72,17 @@ TEST_F(AwsRequestSigningFilterTest, SignFails) {
...
 }
 
+// Verify FilterConfigImpl's getters.
+TEST_F(AwsRequestSigningFilterTest, FilterConfigImplGetters) {
+  Stats::IsolatedStoreImpl stats;
+  auto signer = std::make_unique<Common::Aws::MockSigner>();
+  FilterConfigImpl config(std::move(signer), "prefix", stats, "foo");
+
+  config.signer();
+  config.stats();
```
Comment (zuercher) [inline test/extensions/filters/http/aws_request_signing/aws_request_signing_filter_test.cc:82]: I think we should probably have some kind of expectation here. You could, for instance, `EXPECT_EQ(&stats, &config.stats())`. You could do something similar for signer if you grab the pointer (`signer.get()`) before moving it into the config. But if that seems too pedantic, I think `EXPECT_NO_THROW` would be reasonable.

Comment (rgs1) [reply test/extensions/filters/http/aws_request_signing/aws_request_signing_filter_test.cc:82]: Sure.

Comment (rgs1) [reply test/extensions/filters/http/aws_request_signing/aws_request_signing_filter_test.cc:82]: `EXPECT_EQ(&stats, &config.stats())` isn't what you think, since that returns the generated stats no the scope... so `NO_THROW` is probs good for that case.

**Comment by rgs1** [comment]
@zuercher updated -- thanks.
