### PR TITLE
upstream: make sure all_hosts_ is updated correctly

### LINKED ISSUE #4548: Envoy leaks cluster members when using  STRICT_DNS and ClusterLoadAssignment
*Title*: Envoy leaks cluster members when using  STRICT_DNS and ClusterLoadAssignment

*Description*:
We are using envoy sha f1aee97b079ad4a0130583ef7cd656351dd70bd7 with a configuration that sets up DNS entries in our cluster load assignment registered via a CDS

```
"load_assignment": {
     "cluster_name": "cluster_name",
     "endpoints": [
      {
       "lb_endpoints": [
        {
         "endpoint": {
          "address": {
           "socket_address": {
            "address": "host1",
            "port_value": 10652
           }
          }
         }
        }
       ],
       "load_balancing_weight": 70
      },
      {
       "lb_endpoints": [
        {
         "endpoint": {
          "address": {
           "socket_address": {
            "address": "host2",
            "port_value": 10652
           }
          }
         }
        }
       ],
       "load_balancing_weight": 30
      }
     ]
    }
   },
```

When we had this envoy would resolve the DNS and continuously say in the debug logs that the hosts have changed, and so it would add new members to the cluster.  The only indication this was happening was in the cluster membership add/change stats and the cluster member list under 9901/clusters.  The config dump always showed the correct load assignment configuration. 

I should note that the host names in our cluster addresses were aliased in /etc/hosts and did not need to be resolved via pure DNS. I tried to replicate this scenario in a docker container using a public IP like from google.com but was unable to reproduce it, so not sure if this is related.

When members are configured with health checks we ended up in a situation with a health check DDOS as envoy kept adding new cluster members.  

We switched over to using STATIC ip addresses, with the exact same configuration, and the membership changes stopped and stabilized.

### PR DESCRIPTION
**Pull request by dio**
*Description*: 
To make sure we all_hosts_ is updated correctly by all hosts from all priorities and no-rebuild if the update is the same. 

This #4548 seems to happen only for `STRICT_DNS` cluster.

*Risk Level*: Medium
*Testing*: unit tests on checking `update_no_rebuild` when `hosts_change` equals `false`, existing tests, manual tests.
*Docs Changes*: N/A
*Release Notes*: N/A

Fixes #4548

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

**Comment by mattklein123** [comment]
@snowp can you help take a look at this and the related issue? Much appreciated.

**Comment by snowp** [comment]
Yeah I’ll have a look later today.

File: source/common/upstream/upstream_impl.cc [hunk 1]
```diff
@@ -1193,6 +1200,14 @@ void StrictDnsClusterImpl::ResolveTarget::startResolve() {
           parent_.updateAllHosts(hosts_added, hosts_removed, locality_lb_endpoint_.priority());
         }
 
+        // TODO(dio): Not sure if we should do this if active health checking is disabled.
```
Comment (snowp) [inline source/common/upstream/upstream_impl.cc]: we should, the `all_hosts_` mapping is also used to determine if the new hosts match within the same priority, which affects `hosts_changed`

**Comment by snowp** [comment]
Part of my comment in #4548 that's relevant to this PR:
>I think we probably want to not use the updated_hosts mechanism for STRICT_EDS (since it's based around updating an entire priority) and instead keep track of what hosts were resolved per resolve target. With that, we could compute the diff for each resolve target after resolution and update all_hosts_ based on that (allowing cross priority moves).

The reason we're seeing duplicate addresses is because we fail to match a new address to an existing one, which is caused by the fact that we reset the `all_hosts_` map between resolves. While I think simply de-duping the addresses will solve the leak and risk of DDOS, it will cause unnecessary "cluster changed" triggers and priority moves would reset the HC status. Ideally we'd fix the core issue, but if we want to rush this in for 1.8 (I'm not sure when that's going to get cut?) I'd be okay with de-duping as a stop gap.

**Comment by dio** [comment]
Yeah, I think I'll add `update_no_rebuild` counter to this.

From my quick experiment:

```
cluster.service1.update_attempt: 34
cluster.service1.update_empty: 0
cluster.service1.update_failure: 0
cluster.service1.update_no_rebuild: 32
cluster.service1.update_success: 34
```

**Comment by mattklein123** [comment]
cc @tonya11en who I think is also hitting this at Lyft.

File: source/common/upstream/upstream_impl.cc [hunk 2]
```diff
@@ -1127,10 +1127,17 @@ void StrictDnsClusterImpl::updateAllHosts(const HostVector& hosts_added,
...
+    std::unordered_set<std::string> host_addresses;
+    if (target->locality_lb_endpoint_.priority() == current_priority) {
+      for (auto i = target->hosts_.begin(); i != target->hosts_.end();) {
+        if (host_addresses.count((*i)->address()->asString()) == 0) {
+          priority_state_manager.registerHostForPriority(*i, target->locality_lb_endpoint_,
+                                                         target->lb_endpoint_, absl::nullopt);
+          host_addresses.insert((*i)->address()->asString());
+          ++i;
+        } else {
+          i = target->hosts_.erase(i);
```
Comment (tonya11en) [inline source/common/upstream/upstream_impl.cc]: In the case of multiple instances of the same host, you could probably save yourself a few calls to `erase` if you just used `std::remove_if(i, hosts_.end(), XXXX)`. Your predicate function would just check for the existence of each element in `host_addresses`. `std::remove_if` also has the same complexity as a vector `erase`.

Comment (lizan) [reply source/common/upstream/upstream_impl.cc]: remove_if doesn't work on associative containers so that won't work.

Comment (tonya11en) [reply source/common/upstream/upstream_impl.cc]: @lizan  `target->hosts_` is a vector, so it will work. Which container are you referring to?

Comment (lizan) [reply source/common/upstream/upstream_impl.cc]: ah ignore my comment above, I thought it is about host_addresses (unordered_set)

File: source/common/upstream/upstream_impl.cc [hunk 3]
```diff
@@ -1127,10 +1127,20 @@ void StrictDnsClusterImpl::updateAllHosts(const HostVector& hosts_added,
   // At this point we know that we are different so make a new host list and notify.
   for (const ResolveTargetPtr& target : resolve_targets_) {
     priority_state_manager.initializePriorityFor(target->locality_lb_endpoint_);
-    for (const HostSharedPtr& host : target->hosts_) {
-      if (target->locality_lb_endpoint_.priority() == current_priority) {
-        priority_state_manager.registerHostForPriority(host, target->locality_lb_endpoint_,
-                                                       target->lb_endpoint_, absl::nullopt);
+    std::unordered_set<std::string> host_addresses;
```
[the remark this answers is not in the document]
Comment (dio) [reply source/common/upstream/upstream_impl.cc]: Sure will add more comments here. While I think this dedupe here probably is not required anymore since the underlying problem is indeed when we update the internal `all_hosts_` data (for EDS (STATIC), the updated hosts consist of all host sets, while for STRICT_DNS it is not, depends on each DNS resolution).

Will make sure the priority state manager can actually handle this (no duplications).

[the remark this answers is not in the document]
Comment (dio) [reply source/common/upstream/upstream_impl.cc]: @mattklein123 for following up this issue, I have opened one here: https://github.com/envoyproxy/envoy/issues/4590 to track. This is based on @snowp's comment. I'll take a look at that later.

File: source/common/upstream/upstream_impl.cc [hunk 4]
```diff
@@ -1191,8 +1196,18 @@ void StrictDnsClusterImpl::ResolveTarget::startResolve() {
             return host->priority() == locality_lb_endpoint_.priority();
           }));
           parent_.updateAllHosts(hosts_added, hosts_removed, locality_lb_endpoint_.priority());
+        } else {
+          parent_.info_->stats().update_no_rebuild_.inc();
         }
 
+        // This makes sure parent_.all_hosts_ is updated with all resolved hosts from all
+        // priorities. This reconciliation is required since we check each new host againsts this
```
Comment (mattklein123) [inline source/common/upstream/upstream_impl.cc]: typo "againsts"

I think this issue is confusing enough that we should have more explanation. Can you be really explicit about the flow here and why this is necessary? I think I understand but I want to make sure the next person that comes along has a really clear understanding of the bug and how we are fixing it for now. My limited understanding is that previously we would set "all hosts" to just this resolve group, which would leave to logic in the future continuing to add hosts that already exist? That's about where my understanding ends without paging back in all this code and the recent changes. So I think more explanation would be great. :)

I would potentially also reference the opened tracking issue to clean this up in the comment.

Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: The problem was that whenever a target resolved, it would set its hosts as `all_hosts_`, so that when another target resolved it wouldn't see its own hosts in `all_hosts_`. It would think that they're new hosts, so it would add them to its host list over and over again.

I'd probably add a comment explaining this exact thing, I think it would provide a decent explanation as to why we're doing this.

File: source/common/upstream/upstream_impl.cc [hunk 5]
```diff
@@ -1125,6 +1125,11 @@ void StrictDnsClusterImpl::updateAllHosts(const HostVector& hosts_added,
                                           uint32_t current_priority) {
   PriorityStateManager priority_state_manager(*this, local_info_);
   // At this point we know that we are different so make a new host list and notify.
+  //
+  // TODO(dio): The uniqueness of a host address resolved in STRICT_DNS cluster per priority is not
+  // guaranteed. Need a clear agreement on the behavior here, whether it is allowable to have
+  // duplicated hosts inside a priority. And if we want to enforce this behavior, it should be done
```
Comment (snowp) [inline source/common/upstream/upstream_impl.cc]: The other open question is whether we want to allow duplicated hosts *between* priorities. EDS does not allow this.

Comment (tonya11en) [reply source/common/upstream/upstream_impl.cc]: I think duplicated hosts between priorities could land us in trouble, but I'm not sure if the scenario is plausible. Consider this:

host A: 50% of endpoints, duplicated between priority 0 and 1.
host B: 25% of endpoints, priority 0
host C: 25% of endpoints, priority 1

If a large portion of host A's endpoints are unhealthy and trigger some percentage of traffic to go to the priority 1 hosts, the overall health of priority 1 is affected as well and could trigger failover into an even lower priority. It seems unintuitive and unnecessary to allow duplicate hosts between priorities.

I'd like to hear an argument in the other direction if anyone has a use-case in mind.

Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: This has been brought up in other issues: https://github.com/envoyproxy/envoy/issues/4280#issuecomment-416800260a

The issue talks about EDS and would probably be supported by the indirection that's later suggested in the issue, but I'm not sure if we could do the same for STRICT_DNS.

File: source/common/upstream/upstream_impl.cc (hunk 4 above)
Comment (dio) [reply source/common/upstream/upstream_impl.cc]: @mattklein123 @snowp I have updated the comment accordingly.
