### PR TITLE
ext_proc: fix logging info loss when gRPC stream closes before encodeComplete

### LINKED ISSUE #44447: `ExtProcIntegrationTest.ObservabilityModeWithLoggingCloseStream` is flakey
```console
[18](https://github.com/envoyproxy/envoy/actions/runs/24376768080/job/71191836075#step:19:632)
[ RUN      ] IpVersionsClientTypeDeferredProcessing/ExtProcIntegrationTest.ObservabilityModeWithLoggingCloseStream/0
test/extensions/filters/http/ext_proc/logging_test_filter.cc:44: Failure
Expected equality of these values:
  ext_proc_logging_info->httpResponseCodeDetails()
    Which is: ""
  expected_rcd_
    Which is: "via_upstream"
Stack trace:
  0x564d966c3060: Envoy::Extensions::HttpFilters::ExternalProcessing::LoggingTestFilter::encodeComplete()
  0x564d994aac4e: Envoy::Http::FilterManager::encodeData()
  0x564d994aa0bf: Envoy::Http::ActiveStreamDecoderFilter::encodeData()
  0x564d9922f32e: Envoy::Router::Filter::onUpstreamData()
  0x564d992684cf: Envoy::Router::UpstreamRequest::decodeData()
  0x564d99278a82: Envoy::Router::UpstreamRequestFilterManagerCallbacks::encodeData()
  0x564d994ab3cd: Envoy::Http::FilterManager::encodeData()
```

https://github.com/envoyproxy/envoy/actions/runs/24376768080/job/71191836075#step:19:632

### PR DESCRIPTION
**Pull request by phlax**
hopefully fix: #44447

### CODE REVIEW

**Comment by phlax** [comment]
@yanjunxiang-google im not 100% confident this fixes as i wasnt able to reproduce - despite this happening very frequently in ci (im using ci rbe to test fwiw)

it at least doesnt break anything - and the bot reasoning about why this should resolve _seems_ reasonable

File: source/extensions/filters/http/ext_proc/ext_proc.cc [hunk 1]
```diff
@@ -2007,6 +2007,12 @@ void Filter::onGrpcCloseWithStatus(Grpc::Status::GrpcStatus status) {
   processing_complete_ = true;
   stats_.streams_closed_.inc();
   stats_.server_half_closed_.inc();
+  // In observability mode, capture logging info before closing the stream.
+  // encodeComplete() also calls logStreamInfo(), but it races with this
```
Comment (jwendell) [inline source/extensions/filters/http/ext_proc/ext_proc.cc]: The comment says "races" but this isn't a thread race. Both callbacks execute on the same worker thread. It's an event-loop ordering issue — onGrpcCloseWithStatus can fire in the event
  loop before the response finishes encoding. The comment is slightly misleading; "ordering" would be more precise than "races."

**Review by jwendell — COMMENTED** [review]
- Consider whether finishProcessing() (line 2358-2361) has the same issue. It calls closeStreamMaybeGraceful() → closeStream() without logging first. If this path also runs before
  encodeComplete() in observability mode, it could have the same silent data loss. Worth investigating.

- PR title is misleading. The title says "tests/ext_proc" but the change is in production code (source/extensions/...). This is a real bug fix, not a test change — the title should reflect
   that. In production, if onGrpcCloseWithStatus fires before encodeComplete, logging info is silently lost.

**Review by jwendell — APPROVED** [review]

**Review by ravenblackx — APPROVED** [review]
