### PR TITLE
ext_authz: Make sure the time field in attribute context request is filled

### LINKED ISSUE #9667: ext_authz CheckRequest call does not include service.auth.v2.AttributeContext.Request.Time field as expected
*Description*:

The `service.auth.v2.AttributeContext.Request` object is missing the `google.protobuf.Timestamp time` field in the data passed via the CheckRequest call. Only the `http` field of this object seems to be populated. This prevents using the request time in the authorization and thus prevents calculating any latency for the call in metrics/logs created by the filter.

See: https://github.com/envoyproxy/envoy/blob/1f208984f1eb6253c3f2ee49139831f6766b673e/api/envoy/service/auth/v2/attribute_context.proto#L76-L83

For example, this is the what is logged from my ext_authz service as the `service.auth.v2.AttributeContext.Request` object for a simple GET request (note no `time` field:

> attributes:<source:<address:<socket_address:<address:"172.19.0.8" port_value:50316 > > > destination:<address:<socket_address:<address:"172.19.0.7" port_value:8085 > > > **request:<http:<id:"8676663115576215990" method:"GET" headers:<key:":authority" value:"envoy:8085" > headers:<key:":method" value:"GET" > headers:<key:":path" value:"/" > headers:<key:"user-agent" value:"test-user-agent" > headers:<key:"x-forwarded-proto" value:"http" > headers:<key:"x-request-id" value:"7a52cf15-dda2-4e2f-b063-75f71ca23a6e" > path:"/" host:"envoy:8085" protocol:"HTTP/1.1" > >** metadata_context:<> >

*Repro steps*:
> In any ext_authz enabled configuration, submit a request and log the gRPC call data. The `service.auth.v2.AttributeContext.Request` object is missing the `time` field (only has the `http` field).

### PR DESCRIPTION
**Pull request by dio**
Description: This patch makes sure the time field in the ext_authz check request's attribute context is filled with the start time.

Risk Level: Low
Testing: Unit and integration test
Docs Changes: N/A
Release Notes: N/A
Fixes #9667 

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

File: source/extensions/filters/common/ext_authz/check_request_utils.h [hunk 1]
```diff
@@ -70,8 +70,10 @@ class CheckRequestUtils {
   static void setAttrContextPeer(envoy::service::auth::v3alpha::AttributeContext::Peer& peer,
                                  const Network::Connection& connection, const std::string& service,
                                  const bool local, bool include_certificate);
+  static void setRequestTime(envoy::service::auth::v3alpha::AttributeContext::Request& req,
+                             Envoy::Http::StreamDecoderFilterCallbacks* callbacks);
   static void setHttpRequest(envoy::service::auth::v3alpha::AttributeContext::HttpRequest& httpreq,
-                             const Envoy::Http::StreamDecoderFilterCallbacks* callbacks,
+                             Envoy::Http::StreamDecoderFilterCallbacks* callbacks,
```
Comment (htuch) [inline source/extensions/filters/common/ext_authz/check_request_utils.h]: Why do the callbacks become mutable?

Comment (dio) [reply source/extensions/filters/common/ext_authz/check_request_utils.h]: Before this change, inside that setHttpRequest we had `const_cast` https://github.com/envoyproxy/envoy/pull/9678/files#diff-a1cbd6e906473b8ff3d53eac314d8213L99-L100 in order to access `streamId()` and `streamInfo()` since "'this' argument to member function 'streamId' has type 'const Envoy::Http::StreamDecoderFilterCallbacks', but function is not marked const". In this change, I need to access `streamInfo()` once again to get the `startTime`.

Comment (htuch) [reply source/extensions/filters/common/ext_authz/check_request_utils.h]: Is there a reason we can't provide `const` ID/info methods? Would prefer that if possible.

Comment (dio) [reply source/extensions/filters/common/ext_authz/check_request_utils.h]: Can do with `streamId()`. The `streamInfo()` is mutable, e.g. when route uses it to `setResponseFlag`.
