### PR TITLE
wasm: fix wasm vm crash before the body too large

### LINKED ISSUE #36989: large request body result in wasm crash
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:

#36411 fixed a bug where the wasm filter may cannot get complete request body. But it also introduce another new bug. Given a big request, the `addDecodedData()` in the `decode/encodeData()` may trigger the buffer high watermark callback and result in local reply sending (413 payload too large). And after the local reply is sent, the `decode/encodeData()` will continue run and call into the vm. But because the local reply is sent so the context in vm may has been removed, the calling into vm may finally result in a crash/panic (depends on the sdk implementation).

### PR DESCRIPTION
**Pull request by wbpcode**
Commit Message: wasm: fix wasm vm crash before the body too large
Additional Description:

To fix #36989

Risk Level: low.
Testing: unit/integration.
Docs Changes: n/a.
Release Notes: n/a.
Platform Specific Features: n/a.

### CODE REVIEW

File: source/extensions/common/wasm/context.cc [hunk 1]
```diff
@@ -1654,6 +1654,14 @@ Http::FilterDataStatus Context::decodeData(::Envoy::Buffer::Instance& data, bool
   }
   if (buffering_request_body_) {
     decoder_callbacks_->addDecodedData(data, false);
```
Comment (kyessenov) [inline source/extensions/common/wasm/context.cc:1656]: I didn't review the previous PR, but I'm genuinely confused why this isn't causing doubling the data somehow.

Comment (wbpcode) [reply source/extensions/common/wasm/context.cc:1656]: the add* actually use move semantics

File: test/extensions/filters/http/wasm/wasm_filter_integration_test.cc [hunk 2]
```diff
@@ -234,6 +237,49 @@ TEST_P(WasmFilterIntegrationTest, BodyBufferedMultipleChunksManipulation) {
           "upstream_very_long_body.end");
 }
 
+TEST_P(WasmFilterIntegrationTest, LargeRequestHitBufferLimit) {
```
Comment (juanmolle) [inline test/extensions/filters/http/wasm/wasm_filter_integration_test.cc:240]: I have tried to make the test failed, but with and without the change, both pass.

File: source/extensions/common/wasm/context.cc (hunk 1 above)
Comment (juanmolle) [reply source/extensions/common/wasm/context.cc:1656]: Probably the  request_body_buffer_ = &data;  should be in the else, it is not used if buffering. and the if should check the callback pointer is not null (probably never happends to be null) but to be consistent with the place  it is used getBuffer:

https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/wasm/context.cc#L818

File: test/extensions/filters/http/wasm/wasm_filter_integration_test.cc (hunk 2 above)
Comment (wbpcode) [reply test/extensions/filters/http/wasm/wasm_filter_integration_test.cc:240]: this test mainly used to ensure big body could works as expected and this patch doesn't break anything.

It's hard to reproduce the bug in integration test because it requires specific language sdk implementation and the data should be handled by chunks.

I think I should add a unit test for this.

Comment (johnlanni) [reply test/extensions/filters/http/wasm/wasm_filter_integration_test.cc:240]: The decode phase should not reproduce, as it will go through [prepareLocalReplyViaFilterChain](https://github.com/envoyproxy/envoy/blob/eb2033e982e5190785ab75a388b8383fd0cedbd5/source/common/http/filter_manager.cc#L1006-L1009) and will not immediately end the request

**Comment by RyanTheOptimist** [comment]
@mpwarres friendly maintainer-on-call ping

**Comment by wbpcode** [comment]
friendly ping @mpwarres

File: test/extensions/filters/http/wasm/wasm_filter_test.cc [hunk 3]
```diff
@@ -474,19 +474,28 @@ TEST_P(WasmHttpFilterTest, BodyRequestBufferBody) {
       .WillRepeatedly(Invoke([&bufferedBody](BufferFunction f) { f(bufferedBody); }));
 
   Buffer::OwnedImpl data1("hello");
-  bufferedBody.add(data1);
   EXPECT_CALL(filter(), log_(spdlog::level::err, Eq(absl::string_view("onBody hello"))));
   EXPECT_EQ(Http::FilterDataStatus::StopIterationAndBuffer, filter().decodeData(data1, false));
+  // The first call to decodeData() will not result in the addDecodedData() callback being called
+  // because the filter doesn't know will the VM's onRequestBody() return StopIterationAndBuffer or
```
Comment (mpwarres) [inline test/extensions/filters/http/wasm/wasm_filter_test.cc:480]: "because the filter doesn't yet know if the VM's onRequestBody() will return StopIterationAndBuffer or Continue"

File: test/extensions/filters/http/wasm/wasm_filter_test.cc [hunk 4]
```diff
@@ -501,6 +510,47 @@ TEST_P(WasmHttpFilterTest, BodyRequestBufferBody) {
   filter().onDestroy();
 }
 
+TEST_P(WasmHttpFilterTest, BodyRequestBufferBodyAndDestoryFilterInTheAddDecodedDataCallback) {
```
Comment (mpwarres) [inline test/extensions/filters/http/wasm/wasm_filter_test.cc:513]: typo: "Destory" -> "Destroy"

File: test/extensions/filters/http/wasm/wasm_filter_test.cc [hunk 5]
```diff
@@ -501,6 +510,47 @@ TEST_P(WasmHttpFilterTest, BodyRequestBufferBody) {
...
+  Buffer::OwnedImpl bufferedBody;
+  EXPECT_CALL(decoder_callbacks_, decodingBuffer()).WillRepeatedly(Return(&bufferedBody));
+  EXPECT_CALL(decoder_callbacks_, modifyDecodingBuffer(_))
+      .WillRepeatedly(Invoke([&bufferedBody](BufferFunction f) { f(bufferedBody); }));
+
+  Buffer::OwnedImpl data1("hello");
+  EXPECT_CALL(filter(), log_(spdlog::level::err, Eq(absl::string_view("onBody hello"))));
+  EXPECT_EQ(Http::FilterDataStatus::StopIterationAndBuffer, filter().decodeData(data1, false));
+  // The first call to decodeData() will not result in the addDecodedData() callback being called
+  // because the filter doesn't know will the VM's onRequestBody() return StopIterationAndBuffer or
```
Comment (mpwarres) [inline test/extensions/filters/http/wasm/wasm_filter_test.cc:530]: "because the filter doesn't yet know if the VM's onRequestBody() will return StopIterationAndBuffer or Continue"

File: test/extensions/filters/http/wasm/wasm_filter_integration_test.cc (hunk 2 above)
Comment (mpwarres) [reply test/extensions/filters/http/wasm/wasm_filter_integration_test.cc:240]: > It's hard to reproduce the bug in integration test because it requires specific language sdk implementation and the data should be handled by chunks.

I didn't quite follow how the bug is SDK-dependent, I thought both Rust and C++ SDKs can return `StopIterationAndBuffer` (i.e. the value 1) from body callbacks. Or is it something else?

**Review by mpwarres — APPROVED** [review]
Sorry for the delay, LGTM

**Comment by wbpcode** [comment]
friendly ping @ggreenway (on call maintainer) for a blind approval. Because this is approved by the senior extension maintainer.

**Review by ggreenway — APPROVED** [review]
