### PR TITLE
Fixes grpc-web filter content length handling

### LINKED ISSUE #40097: grpc-web filter does not strip returned content length header
If an upstream gRPC server returns a response with a `content-length` header set, this is not stripped by the grpc_web filter. This is a problem because the grpc_web filter modifies the response body, usually making it longer, by including the grpc trailers in the body. This results in HTTP protocol errors in clients, where the returned response is longer than the content length header reports.

### PR DESCRIPTION
**Pull request by jroper**
Fixes #40097

This fixes a bug in the grpc web filter where if an upstream grpc server sends a response with the content length, the grpc web filter modifies the body without updating or removing the content length. The result is that some clients truncate the body, other clients throw a protocol error, and if the downstream protocol is HTTP/1.1, there's a potential for HTTP response splitting.

I have attempted to run the tests, but multiple attempts to run the tests in docker have caused my machine to go to 100% CPU for multiple hours before the machine crashes. Running the tests outside of docker seem to have dependency issues.

### CODE REVIEW

File: source/extensions/filters/http/grpc_web/grpc_web_filter.cc [hunk 1]
```diff
@@ -251,6 +251,10 @@ Http::FilterHeadersStatus GrpcWebFilter::encodeHeaders(Http::ResponseHeaderMap&
   needs_transformation_for_non_proto_encoded_response_ =
       needsTransformationForNonProtoEncodedResponse(headers, end_stream);
 
+  // If upstream sets a content length, we must remove it because we're going to change the
+  // length of the body
+  headers.removeContentLength();
```
Comment (kyessenov) [inline source/extensions/filters/http/grpc_web/grpc_web_filter.cc:256]: I'm confused why this is necessary. I see that `setTransformedNonProtoEncodedResponseHeaders` sets the content length to 0 - which I think kicks in when there is a change to the body.

Comment (jroper) [reply source/extensions/filters/http/grpc_web/grpc_web_filter.cc:256]: `setTransformedNonProtoEncodedResponseHeaders` method is only invoked in cases where the upstream server has not sent a valid gRPC response, which is decided by this logic here:

```c++
// If response headers do not contain valid response headers, it needs transformation.
bool GrpcWebFilter::needsTransformationForNonProtoEncodedResponse(Http::ResponseHeaderMap& headers,
                                                                  bool end_stream) const {
  // We transform the response unless it is already a gRPC or proto-encoded gRPC-Web response.
  return !Grpc::Common::isGrpcResponseHeaders(headers, end_stream) &&
         !isProtoEncodedGrpcWebResponseHeaders(headers);
}
```

In that case, the filter transforms the returned response code to a gRPC error code, buffers the response, and places the response as the gRPC status message. The result has no body, which a gRPC(-web) server is allowed to do if it's only sending a gRPC error, and that's why it sets content length to zero.

For the happy case, where the upstream server sends a well formed gRPC response, `setTransformedNonProtoEncodedResponseHeaders` is not invoked, and the content length must be cleared if set, because the subsequent transformation of the body will change the content length.

**Review by kyessenov — APPROVED** [review]
