### PR TITLE
dns: [fix] cares resolver should respect cname ttl

### LINKED ISSUE #28925: Wrong ttl used when respect_dns_ttl is set
I have an upstream with `type: STRICT_DNS` and `respect_dns_ttl: true`. However, when I change the DNS entry, envoy *does not update the origin IP* as expected.

I have done a quick debug, and it appears that envoy uses the TTL from the CNAME resolved entry in the DNS response, instead of the base entry TTL. For example with an `entry.example.com` upstream and the observed below response:

```
dig entry.example.com
…
;; ANSWER SECTION:
entry.example.com.	10 	IN	CNAME	host1.example.com.
host1.example.com.	86400	IN	A	1.2.3.4
```

Here I can observe that envoy chose the value `86400` for ttl, rather than `10`. I can confirm this with `upstream` debug logging, which returns something like this when envoy starts:

```
[2023-08-09 12:04:43.386][233471][debug][upstream] [source/extensions/clusters/strict_dns/strict_dns_cluster.cc:149] DNS hosts have changed for entry.example.com
[2023-08-09 12:04:43.386][233471][debug][upstream] [source/extensions/clusters/strict_dns/strict_dns_cluster.cc:177] DNS refresh rate reset for entry.example.com, refresh rate 86400000 ms
```

I would expect envoy to refresh it as a normal DNS client would, ie. after 10s.

This was tested with v1.27.0 on Linux.

### Cause investigation

I expect this is an issues with the c-ares resolver interface. Looking at the logic, it seems that the `cnames` field in the [`ares_getaddrinfo`](https://c-ares.org/ares_getaddrinfo.html) response is completely ignored:

https://github.com/envoyproxy/envoy/blob/27218f51ba9a9fe5932deb26a949aadc7387e883/source/extensions/network/dns_resolver/cares/dns_impl.cc#L202-L228

The correct way to handle this, is probably to use the minimum TTL of all CNAME entries and the `ai_ttl` of the used node.

It could potentially be a problem with the apple resolver as well.

### PR DESCRIPTION
**Pull request by kanurag94**
Commit Message: dns: [fix] cares resolver should respect cname ttl
Additional Description: cares currently only uses node ttl in the DNS response which completely ignores the cname ttl. In case cname has a lower ttl, the updates would not be applied. Thus to always ensure the records are updated, we use minimum ttl of cname and node.
Risk Level: Medium
Testing: Modified unit tests. Functional testing done.
Docs Changes:  N/A
Release Notes: N/A
Platform Specific Features: N/A

Fixes #28925 

[Optional Runtime guard:]

### CODE REVIEW

**Review by botengyao — COMMENTED** [review]
Thanks for working on this!

File: source/extensions/network/dns_resolver/cares/dns_impl.cc [hunk 1]
```diff
@@ -204,6 +204,13 @@ void DnsResolverImpl::AddrInfoPendingResolution::onAresGetAddrInfoCallback(
       bool can_process_v6 =
           (!parent_.filter_unroutable_families_ || available_interfaces_.v6_available_);
 
+      int min_ttl = INT_MAX;
+      // Loop through cname and get min_ttl
+      for (const ares_addrinfo_cname* cname = addrinfo->cnames; cname != nullptr;
```
[the remark this answers is not in the document]
Comment (kanurag94) [reply source/extensions/network/dns_resolver/cares/dns_impl.cc:209]: AFAIK, there isn't an RFC.
Ideally the TTL of the whole request path should matter and in case the request has come for a cname record the TTL of the cname record should be honoured. The shortest of all guarantees lookup to be most recent and accurate.

**Comment by phlax** [comment]
@botengyao i think this waiting on signoff

/wait-any

File: source/extensions/network/dns_resolver/cares/dns_impl.cc [hunk 2]
```diff
@@ -204,6 +204,13 @@ void DnsResolverImpl::AddrInfoPendingResolution::onAresGetAddrInfoCallback(
...
+           cname = cname->next) {
+        min_ttl = std::min(min_ttl, cname->ttl);
```
Comment (botengyao) [inline source/extensions/network/dns_resolver/cares/dns_impl.cc:211]: Looking at the RFC 1035, Emm, what happens if the TTL is 0? 0 means we should not be cached. We may need to think about this case.

```
TTL             a 32 bit signed integer that specifies the time interval
                that the resource record may be cached before the source
                of the information should again be consulted.  Zero
                values are interpreted to mean that the RR can only be
                used for the transaction in progress, and should not be
                cached.  For example, SOA records are always distributed
                with a zero TTL to prohibit caching.  Zero values can
                also be used for extremely volatile data.
```

**Review by botengyao — COMMENTED** [review]
Thanks!

File: source/extensions/network/dns_resolver/cares/dns_impl.cc (hunk 2 above)
Comment (kanurag94) [reply source/extensions/network/dns_resolver/cares/dns_impl.cc:211]: Thanks for taking a look on this.

The minimum of all entries is taken so if some entry is 0, we would parse it as 0 only. I roughly remember that is handled already as part of dns cache implementation. Is it not?

The highest according to the RFC is 2^31-1 which we are starting with in `min_ttl = INT_MAX`. The ttl of atleast one record would be lesser than that. Thus I felt this just change just extends to respect ttl thoroughly in the lookup but not change what is already present.

File: tools/spelling/spelling_dictionary.txt [hunk 3]
```diff
@@ -1458,3 +1458,4 @@ SSLKEYLOGFILE
 DLB
 PCIE
 EDNS
+cname
```
Comment (botengyao) [inline tools/spelling/spelling_dictionary.txt:1461]: nit: can we use `CNAME` for the comments?

File: source/extensions/network/dns_resolver/cares/dns_impl.cc (hunk 2 above)
Comment (botengyao) [reply source/extensions/network/dns_resolver/cares/dns_impl.cc:211]: I see, thanks. Let's add some unit tests for 0 and max.

File: tools/spelling/spelling_dictionary.txt (hunk 3 above)
Comment (kanurag94) [reply tools/spelling/spelling_dictionary.txt:1461]: ack, done

File: source/extensions/network/dns_resolver/cares/dns_impl.cc (hunk 2 above)
Comment (kanurag94) [reply source/extensions/network/dns_resolver/cares/dns_impl.cc:211]: ack, done.
ps. I added tests considering cares will always use int (signed int32), and dns ttls can never be negative (RFC 2181)

**Comment by kanurag94** [comment]
Thanks @botengyao for reviewing, really appreciate the quick review. Have addressed the comments

**Review by zuercher — CHANGES_REQUESTED** [review]
Thanks for looking at this. I agree with the logic to use the minimum TTL across CNAME and address records.

In addition to the comment below, we should add a release note for this change.

File: source/extensions/network/dns_resolver/cares/dns_impl.cc (hunk 2 above)
Comment (kanurag94) [reply source/extensions/network/dns_resolver/cares/dns_impl.cc:211]: Thanks for reviewing this @zuercher 

I have added change as suggested by you to check in DNSResponse to set `std::min(2^31-1, std::max(0, ttl))` so that it is always bounded conforming to the RFC.

File: changelogs/current.yaml [hunk 4]
```diff
@@ -47,6 +47,15 @@ bug_fixes:
...
     fixed a bug where handshake may fail when both private key provider and cert validation are set.
+- area: dns
+  change: |
+    Fixed a bug where when respect_dns_ttl was set to true, c-ares dns resolver only considered address record for ttl calculation
+    while ignoring CNAME records TTL. Now when respect_dns_ttl is set to true minimum of all TTL records is considered.
+- area: dns
+  change: |
+    Fixed a bug where dns response was not always conforming [RFC 2181](https://datatracker.ietf.org/doc/html/rfc2181) for TTL values.
+    Previously a malicious user could add a TTL greater than 2^31 - 1, and with c-ares library using 32 bit signed int data type
+    would overflow and send a negative TTL.
```
Comment (kanurag94) [inline changelogs/current.yaml:58]: added two changelogs since both seemed somewhat independent

File: envoy/network/dns.h [hunk 5]
```diff
@@ -66,7 +66,15 @@ class DnsResponse {
   DnsResponse(const std::string& host, uint16_t port, uint16_t priority, uint16_t weight)
       : response_(SrvResponse{host, port, priority, weight}) {}
 
-  const AddrInfoResponse& addrInfo() const { return absl::get<AddrInfoResponse>(response_); }
+  const AddrInfoResponse addrInfo() const {
```
Comment (kanurag94) [inline envoy/network/dns.h:69]: @zuercher  changed the signature to return `value` instead of reference for proper thread synchronisation. Apart from memory consumption, it shouldn't add more complexity.

TBH, I am not completely sure this is what we should do or if there are other ways to do this. One thing probably could be to Assert() in this case instead. Please let me know your thoughts

Comment (botengyao) [reply envoy/network/dns.h:69]: We can move this logic to [#line65](https://github.com/envoyproxy/envoy/pull/29231/files#diff-6e80985af9d2f1d49e11a4dbaf343fa54286f6767d4ac449620d37b949ac5d9eR65). There should no `Assert()` in this Envoy's data plane as a general guidance.

Comment (kanurag94) [reply envoy/network/dns.h:69]: Thanks @botengyao, done.

**Review by zuercher — APPROVED** [review]

**Comment by kanurag94** [comment]
@zuercher @botengyao  thanks, really appreciate you taking time to review this.
I was wondering who to ping regarding merge. May you be able to help me here please

**Review by botengyao — APPROVED** [review]
cc @envoyproxy/senior-maintainers for another pass and merge. Thanks!
