### PR TITLE
lua: Manage imported public keys in stream handle

### LINKED ISSUE #12485: Using lua_pushlightuserdata() might be broken on ARM
```
2020-08-05T00:31:36.4291883Z [ RUN      ] LuaHttpFilterTest.ImportPublicKey
2020-08-05T00:31:36.4292591Z TestRandomGenerator running with seed 1094790776
2020-08-05T00:31:36.4293344Z unknown file: Failure
2020-08-05T00:31:36.4293602Z 
2020-08-05T00:31:36.4294586Z Unexpected mock function call - returning directly.
2020-08-05T00:31:36.4295160Z     Function call: scriptLog(4, 0xffff95346518 pointing to "bad light userdata pointer")
2020-08-05T00:31:36.4296042Z Google Mock tried the following 1 expectation, but it didn't match:
2020-08-05T00:31:36.4296451Z 
2020-08-05T00:31:36.4297076Z test/extensions/filters/http/lua/lua_filter_test.cc:2001: EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("succeeded to import public key")))...
2020-08-05T00:31:36.4297773Z   Expected arg #0: is equal to 0
2020-08-05T00:31:36.4298144Z            Actual: 4
2020-08-05T00:31:36.4298577Z   Expected arg #1: is equal to "succeeded to import public key"
2020-08-05T00:31:36.4299113Z            Actual: 0xffff95346518 pointing to "bad light userdata pointer"
2020-08-05T00:31:36.4299798Z          Expected: to be called once
2020-08-05T00:31:36.4300529Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4300970Z Stack trace:
2020-08-05T00:31:36.4301463Z   0x11d5210: testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith()
2020-08-05T00:31:36.4302166Z   0x6a5280: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::TestFilter::scriptLog()
2020-08-05T00:31:36.4302867Z   0x766e84: Envoy::Extensions::HttpFilters::Lua::Filter::scriptError()
2020-08-05T00:31:36.4303616Z   0x768dfc: Envoy::Extensions::HttpFilters::Lua::Filter::doHeaders()
2020-08-05T00:31:36.4304370Z   0x7597a8: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest_ImportPublicKey_Test::TestBody()
2020-08-05T00:31:36.4305120Z   0x11e69b8: testing::internal::HandleExceptionsInMethodIfSupported<>()
2020-08-05T00:31:36.4305629Z   0x11e68d0: testing::Test::Run()
2020-08-05T00:31:36.4306075Z   0x11e7548: testing::TestInfo::Run()
2020-08-05T00:31:36.4306496Z ... Google Test internal frames ...
2020-08-05T00:31:36.4306765Z 
2020-08-05T00:31:36.4307164Z test/extensions/filters/http/lua/lua_filter_test.cc:2001: Failure
2020-08-05T00:31:36.4308266Z Actual function call count doesn't match EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("succeeded to import public key")))...
2020-08-05T00:31:36.4308985Z          Expected: to be called once
2020-08-05T00:31:36.4309714Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4310151Z Stack trace:
2020-08-05T00:31:36.4310658Z   0x11d5c4c: testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked()
2020-08-05T00:31:36.4311310Z   0x6b70c8: testing::internal::FunctionMocker<>::~FunctionMocker()
2020-08-05T00:31:36.4311983Z   0x6a5218: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::TestFilter::~TestFilter()
2020-08-05T00:31:36.4312774Z   0x6f6e0c: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest::~LuaHttpFilterTest()
2020-08-05T00:31:36.4313684Z   0x759384: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest_ImportPublicKey_Test::~LuaHttpFilterTest_ImportPublicKey_Test()
2020-08-05T00:31:36.4314488Z   0x11e69b8: testing::internal::HandleExceptionsInMethodIfSupported<>()
2020-08-05T00:31:36.4315010Z   0x11e75a8: testing::TestInfo::Run()
2020-08-05T00:31:36.4315466Z   0x11e7e84: testing::TestSuite::Run()
2020-08-05T00:31:36.4315880Z ... Google Test internal frames ...
2020-08-05T00:31:36.4316152Z 
2020-08-05T00:31:36.4316512Z [  FAILED  ] LuaHttpFilterTest.ImportPublicKey (55 ms)
2020-08-05T00:31:36.4316978Z [ RUN      ] LuaHttpFilterTest.InvalidPublicKey
2020-08-05T00:31:36.4317415Z TestRandomGenerator running with seed 1094790776
2020-08-05T00:31:36.4317863Z [       OK ] LuaHttpFilterTest.InvalidPublicKey (6 ms)
2020-08-05T00:31:36.4318310Z [ RUN      ] LuaHttpFilterTest.SignatureVerify
2020-08-05T00:31:36.4318736Z TestRandomGenerator running with seed 1094790776
2020-08-05T00:31:36.4319133Z unknown file: Failure
2020-08-05T00:31:36.4319385Z 
2020-08-05T00:31:36.4319975Z Unexpected mock function call - returning directly.
2020-08-05T00:31:36.4320724Z     Function call: scriptLog(4, 0xffff95373f18 pointing to "bad light userdata pointer")
2020-08-05T00:31:36.4321345Z Google Mock tried the following 4 expectations, but none matched:
2020-08-05T00:31:36.4321717Z 
2020-08-05T00:31:36.4322353Z test/extensions/filters/http/lua/lua_filter_test.cc:2092: tried expectation #0: EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("signature is valid")))...
2020-08-05T00:31:36.4323054Z   Expected arg #0: is equal to 0
2020-08-05T00:31:36.4323422Z            Actual: 4
2020-08-05T00:31:36.4323838Z   Expected arg #1: is equal to "signature is valid"
2020-08-05T00:31:36.4324347Z            Actual: 0xffff95373f18 pointing to "bad light userdata pointer"
2020-08-05T00:31:36.4324844Z          Expected: to be called once
2020-08-05T00:31:36.4325572Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4326479Z test/extensions/filters/http/lua/lua_filter_test.cc:2093: tried expectation #1: EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("unknown is not supported.")))...
2020-08-05T00:31:36.4327200Z   Expected arg #0: is equal to 0
2020-08-05T00:31:36.4327570Z            Actual: 4
2020-08-05T00:31:36.4327984Z   Expected arg #1: is equal to "unknown is not supported."
2020-08-05T00:31:36.4328510Z            Actual: 0xffff95373f18 pointing to "bad light userdata pointer"
2020-08-05T00:31:36.4329005Z          Expected: to be called once
2020-08-05T00:31:36.4329912Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4330827Z test/extensions/filters/http/lua/lua_filter_test.cc:2095: tried expectation #2: EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("Failed to verify digest. Error code: 0")))...
2020-08-05T00:31:36.4331702Z   Expected arg #0: is equal to 0
2020-08-05T00:31:36.4332088Z            Actual: 4
2020-08-05T00:31:36.4332584Z   Expected arg #1: is equal to "Failed to verify digest. Error code: 0"
2020-08-05T00:31:36.4333171Z            Actual: 0xffff95373f18 pointing to "bad light userdata pointer"
2020-08-05T00:31:36.4333675Z          Expected: to be called once
2020-08-05T00:31:36.4334371Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4335217Z test/extensions/filters/http/lua/lua_filter_test.cc:2097: tried expectation #3: EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("Failed to verify digest. Error code: 0")))...
2020-08-05T00:31:36.4335994Z   Expected arg #0: is equal to 0
2020-08-05T00:31:36.4336360Z            Actual: 4
2020-08-05T00:31:36.4336846Z   Expected arg #1: is equal to "Failed to verify digest. Error code: 0"
2020-08-05T00:31:36.4337429Z            Actual: 0xffff95373f18 pointing to "bad light userdata pointer"
2020-08-05T00:31:36.4337912Z          Expected: to be called once
2020-08-05T00:31:36.4338631Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4339060Z Stack trace:
2020-08-05T00:31:36.4339557Z   0x11d5210: testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith()
2020-08-05T00:31:36.4340262Z   0x6a5280: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::TestFilter::scriptLog()
2020-08-05T00:31:36.4340953Z   0x766e84: Envoy::Extensions::HttpFilters::Lua::Filter::scriptError()
2020-08-05T00:31:36.4341566Z   0x768dfc: Envoy::Extensions::HttpFilters::Lua::Filter::doHeaders()
2020-08-05T00:31:36.4342320Z   0x75b300: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest_SignatureVerify_Test::TestBody()
2020-08-05T00:31:36.4343047Z   0x11e69b8: testing::internal::HandleExceptionsInMethodIfSupported<>()
2020-08-05T00:31:36.4343561Z   0x11e68d0: testing::Test::Run()
2020-08-05T00:31:36.4344003Z   0x11e7548: testing::TestInfo::Run()
2020-08-05T00:31:36.4344423Z ... Google Test internal frames ...
2020-08-05T00:31:36.4344683Z 
2020-08-05T00:31:36.4345087Z test/extensions/filters/http/lua/lua_filter_test.cc:2092: Failure
2020-08-05T00:31:36.4346127Z Actual function call count doesn't match EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("signature is valid")))...
2020-08-05T00:31:36.4347012Z          Expected: to be called once
2020-08-05T00:31:36.4347742Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4348183Z Stack trace:
2020-08-05T00:31:36.4348698Z   0x11d5c4c: testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked()
2020-08-05T00:31:36.4349337Z   0x6b70c8: testing::internal::FunctionMocker<>::~FunctionMocker()
2020-08-05T00:31:36.4350013Z   0x6a5218: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::TestFilter::~TestFilter()
2020-08-05T00:31:36.4350805Z   0x6f6e0c: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest::~LuaHttpFilterTest()
2020-08-05T00:31:36.4351869Z   0x75a574: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest_SignatureVerify_Test::~LuaHttpFilterTest_SignatureVerify_Test()
2020-08-05T00:31:36.4352811Z   0x11e69b8: testing::internal::HandleExceptionsInMethodIfSupported<>()
2020-08-05T00:31:36.4353318Z   0x11e75a8: testing::TestInfo::Run()
2020-08-05T00:31:36.4353779Z   0x11e7e84: testing::TestSuite::Run()
2020-08-05T00:31:36.4354205Z ... Google Test internal frames ...
2020-08-05T00:31:36.4354470Z 
2020-08-05T00:31:36.4354875Z test/extensions/filters/http/lua/lua_filter_test.cc:2093: Failure
2020-08-05T00:31:36.4355961Z Actual function call count doesn't match EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("unknown is not supported.")))...
2020-08-05T00:31:36.4356637Z          Expected: to be called once
2020-08-05T00:31:36.4357380Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4357812Z Stack trace:
2020-08-05T00:31:36.4358327Z   0x11d5c4c: testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked()
2020-08-05T00:31:36.4358962Z   0x6b70c8: testing::internal::FunctionMocker<>::~FunctionMocker()
2020-08-05T00:31:36.4359634Z   0x6a5218: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::TestFilter::~TestFilter()
2020-08-05T00:31:36.4360427Z   0x6f6e0c: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest::~LuaHttpFilterTest()
2020-08-05T00:31:36.4361343Z   0x75a574: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest_SignatureVerify_Test::~LuaHttpFilterTest_SignatureVerify_Test()
2020-08-05T00:31:36.4362139Z   0x11e69b8: testing::internal::HandleExceptionsInMethodIfSupported<>()
2020-08-05T00:31:36.4362642Z   0x11e75a8: testing::TestInfo::Run()
2020-08-05T00:31:36.4363093Z   0x11e7e84: testing::TestSuite::Run()
2020-08-05T00:31:36.4363513Z ... Google Test internal frames ...
2020-08-05T00:31:36.4363775Z 
2020-08-05T00:31:36.4364183Z test/extensions/filters/http/lua/lua_filter_test.cc:2095: Failure
2020-08-05T00:31:36.4365286Z Actual function call count doesn't match EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("Failed to verify digest. Error code: 0")))...
2020-08-05T00:31:36.4366028Z          Expected: to be called once
2020-08-05T00:31:36.4366762Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4367201Z Stack trace:
2020-08-05T00:31:36.4367713Z   0x11d5c4c: testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked()
2020-08-05T00:31:36.4368352Z   0x6b70c8: testing::internal::FunctionMocker<>::~FunctionMocker()
2020-08-05T00:31:36.4369020Z   0x6a5218: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::TestFilter::~TestFilter()
2020-08-05T00:31:36.4410799Z   0x6f6e0c: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest::~LuaHttpFilterTest()
2020-08-05T00:31:36.4411807Z   0x75a574: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest_SignatureVerify_Test::~LuaHttpFilterTest_SignatureVerify_Test()
2020-08-05T00:31:36.4412615Z   0x11e69b8: testing::internal::HandleExceptionsInMethodIfSupported<>()
2020-08-05T00:31:36.4413127Z   0x11e75a8: testing::TestInfo::Run()
2020-08-05T00:31:36.4413599Z   0x11e7e84: testing::TestSuite::Run()
2020-08-05T00:31:36.4414023Z ... Google Test internal frames ...
2020-08-05T00:31:36.4414561Z 
2020-08-05T00:31:36.4414974Z test/extensions/filters/http/lua/lua_filter_test.cc:2097: Failure
2020-08-05T00:31:36.4416352Z Actual function call count doesn't match EXPECT_CALL(*filter_, scriptLog(spdlog::level::trace, StrEq("Failed to verify digest. Error code: 0")))...
2020-08-05T00:31:36.4417116Z          Expected: to be called once
2020-08-05T00:31:36.4417810Z            Actual: never called - unsatisfied and active
2020-08-05T00:31:36.4418240Z Stack trace:
2020-08-05T00:31:36.4418755Z   0x11d5c4c: testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked()
2020-08-05T00:31:36.4419394Z   0x6b70c8: testing::internal::FunctionMocker<>::~FunctionMocker()
2020-08-05T00:31:36.4420076Z   0x6a5218: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::TestFilter::~TestFilter()
2020-08-05T00:31:36.4420873Z   0x6f6e0c: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest::~LuaHttpFilterTest()
2020-08-05T00:31:36.4421948Z   0x75a574: Envoy::Extensions::HttpFilters::Lua::(anonymous namespace)::LuaHttpFilterTest_SignatureVerify_Test::~LuaHttpFilterTest_SignatureVerify_Test()
2020-08-05T00:31:36.4422758Z   0x11e69b8: testing::internal::HandleExceptionsInMethodIfSupported<>()
2020-08-05T00:31:36.4423270Z   0x11e75a8: testing::TestInfo::Run()
2020-08-05T00:31:36.4423730Z   0x11e7e84: testing::TestSuite::Run()
2020-08-05T00:31:36.4424157Z ... Google Test internal frames ...
2020-08-05T00:31:36.4424419Z 
2020-08-05T00:31:36.4424786Z [  FAILED  ] LuaHttpFilterTest.SignatureVerify (13 ms)
```

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This patch manages the imported public keys in the stream-handle object instead of "exposing" it as pointer through `lua_pushlightuserdata` while preserving the current Lua APIs.

Risk Level: Low
Testing: Existing tests
Docs Changes: N/A
Release Notes: N/A
Fixes #12485

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

**Comment by dio** [comment]
cc. @yxue

File: source/extensions/filters/http/lua/wrappers.cc [hunk 1]
```diff
@@ -190,16 +190,10 @@ int DynamicMetadataMapWrapper::luaPairs(lua_State* state) {
...
-  if (public_key_ == nullptr || public_key_.get() == nullptr) {
+  if (public_key_.empty()) {
     lua_pushnil(state);
   } else {
-    auto wrapper = Common::Crypto::Access::getTyped<Common::Crypto::PublicKeyObject>(*public_key_);
-    EVP_PKEY* pkey = wrapper->getEVP_PKEY();
-    if (pkey == nullptr) {
-      lua_pushnil(state);
-    } else {
-      lua_pushlightuserdata(state, public_key_.get());
```
Comment (mattklein123) [inline source/extensions/filters/http/lua/wrappers.cc:201]: WDYT about having a format checker which blocks this API? I think we should never use it or at least make someone turn off the linter?

File: source/extensions/filters/http/lua/lua_filter.h [hunk 2]
```diff
@@ -308,6 +308,8 @@ class StreamHandleWrapper : public Filters::Common::Lua::BaseLuaObject<StreamHan
   State state_{State::Running};
   std::function<void()> yield_callback_;
   Http::AsyncClient::Request* http_request_{};
+
+  absl::flat_hash_map<std::string, Envoy::Common::Crypto::CryptoObjectPtr> public_key_storage_;
```
Comment (mattklein123) [inline source/extensions/filters/http/lua/lua_filter.h:312]: I think it's fine but can you add a comment that this map is never removed from?
