### PR TITLE
ads: Fix cluster remains not-initialized when eds is removed and then added.

### LINKED ISSUE #3355: ads: nonce is ignored when empty response arrives, resulting in a 503 responses.
When running gloo's integration tests, we noticed an issues that seems to be ADS related. (i was able to reduce it to a consistently failing e2e test,  here https://github.com/solo-io/gloo/blob/per-role-config/test/local_e2e/eds.go#L119)

It seems that an ADS Request is ignored. I believe that this is the scenario that causes it:
1. Cluster with EDS is added (envoy is synced with Cluster and ClusterLoadAssignment)
2. Cluster with EDS is removed
3. At this point:
3.1 go-control-plane sends a DiscoverResponse with the new ClusterLoadAssignment that has an empty list. 
3.2 in Envoy (probably because the cluster is removed already) there are no watchers for this response and it is ignored.
3.3 Envoy does *not* update the nonce to the nonce from the response.
4. A new cluster with EDS is added
5. go-control-plane updates envoy on the new cluster
6. Envoy sends a ClusterLoadAssignment discovery request with the cluster name.
7. request is *ignored* by go-control-plane as it thinks it is a stale nonce (as described here: https://github.com/envoyproxy/envoy/blob/master/api/XDS_PROTOCOL.md#resource-updates).
8. Since there is no EDS response the cluster 'warm-up' is never finished and is not available. all requests to that cluster return 503.

Note: I am not sure why, I only got this to reproduce when another non-eds cluster was added as well.

To fix this, I made the following patch, Where I update the nonce regardless if the resource list is empty:
https://github.com/yuval-k/envoy/commit/340a2652c439087e0e40e931015d3f2cca5412a2
(docker image is also available)

Before opening a PR and adding tests, I wanted to make sure with everyone that this is indeed the right solution. and maybe get some more insights about whats the best approach here.

Happy to provide more information as needed, as I have a consistently reproducing test locally.

### PR DESCRIPTION
**Pull request by yuval-k**
*Risk Level*: Low

*Testing*:
Added unit test that fails before the patch and passes after.

Fixes #3355

### CODE REVIEW

File: source/common/config/grpc_mux_impl.cc [hunk 1]
```diff
@@ -163,7 +163,12 @@ void GrpcMuxImpl::onReceiveMessage(std::unique_ptr<envoy::api::v2::DiscoveryResp
     return;
   }
   if (api_state_[type_url].watches_.empty()) {
-    ENVOY_LOG(warn, "Ignoring unwatched type URL {}", type_url);
+    if (message->resources().empty()) {
+      api_state_[type_url].request_.set_version_info(message->version_info());
+      api_state_[type_url].request_.set_response_nonce(message->nonce());
```
Comment (htuch) [inline source/common/config/grpc_mux_impl.cc]: Thanks for the fix PR @yuval-k.

Shouldn't we also do a `sendDiscoveryRequest()` (as done at EOF) to indicate back to the management server that this empty list has now been accepted? Similarly, with the two branches (above and below) with `ENVOY_LOG(warn,..`, I think we should do a `sendDiscoveryRequest()` with the new nonce but without updating version, to NACK.

Comment (yuval-k) [reply source/common/config/grpc_mux_impl.cc]: as far as I understand it, if the list of watches is empty you probably dont want to send a discovery request.
e.g. when a cluster removed, and there are no more EDS resources, no need to send a discover request. thoguhts?

In the mean time i'll update the other code paths.

Comment (yuval-k) [reply source/common/config/grpc_mux_impl.cc]: Not sure whats the best way to handle unknown type URL. sounds like something that should never happen... maybe RELEASE_ASSERT?

Comment (htuch) [reply source/common/config/grpc_mux_impl.cc]: Yep, you are right, there is no need to `sendDiscoveryRequest()` when the watch list is empty. On the two WARNING paths, we can't `RELEASE_ASSERT`, Envoy shouldn't crash because of a bad management server sequence. There are various behaviors that would be reasonable:
1. NACK, since this `DiscoveryResponse` could be be applied
2. Drop stream since there is a protocol violation, with a warning log.
3. Just print a warning log (existing behavior), there is a protocol violation, all bets are off.
I think (1) is maybe overkill, so either (2) or (3). Maybe just add a `TODO` at these sites to consider dropping the stream.

Comment (htuch) [reply source/common/config/grpc_mux_impl.cc]: Also, please add some brief comments capturing the above chain of thought, thanks!

File: test/common/config/grpc_mux_impl_test.cc [hunk 2]
```diff
@@ -336,6 +337,37 @@ TEST_F(GrpcMuxImplTest, TooManyRequests) {
...
+  response->set_type_url(type_url);
+  // This contains zero resources.
+  grpc_mux_->onReceiveMessage(std::move(response));
+
+  // when we add the new subscription version should be 1 and nonce should be bar
+  expectSendMessage(type_url, {"x"}, "1", "bar");
+
+  // simulate a new cluster x is added. add CLA subscription for it.
+  auto sub = grpc_mux_->subscribe(type_url, {"x"}, callbacks_);
+  expectSendMessage(type_url, {}, "1", "bar");
```
Comment (htuch) [inline test/common/config/grpc_mux_impl_test.cc]: Great, this test captures the essence of the issue.

File: source/common/config/grpc_mux_impl.cc (hunk 1 above)
Comment (yuval-k) [reply source/common/config/grpc_mux_impl.cc]: so to summarize:
no watches AND no resources ⇒ accept version; don't send discovery request
no watches AND some resources ⇒ reject version (update nonce but not version); send discovery request as a NACK
unknown type ⇒ Probably drop stream; add TODO for now. should 'warn' log be 'error'?

File: test/common/config/grpc_mux_impl_test.cc (hunk 2 above)
Comment (yuval-k) [reply test/common/config/grpc_mux_impl_test.cc]: thanks!

**Comment by yuval-k** [comment]
the ipv6_tests seems like a flake:
`fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Network is unreachable`
how can I restart the test?

**Comment by mattklein123** [comment]
There is something broken with IPv6 CI: https://github.com/envoyproxy/envoy/issues/3370

File: test/common/config/grpc_mux_impl_test.cc [hunk 3]
```diff
@@ -336,6 +337,70 @@ TEST_F(GrpcMuxImplTest, TooManyRequests) {
...
+}
+
+//  Verifies that a messsage with some resources is rejected when there are no watches.
+TEST_F(GrpcMuxImplTest, UnwatchedTypeRejectsResources) {
+  EXPECT_CALL(*async_client_, start(_, _)).WillOnce(Return(&async_stream_));
+
+  const std::string& type_url = Config::TypeUrl::get().ClusterLoadAssignment;
+
+  grpc_mux_->start();
+  {
```
Comment (htuch) [inline test/common/config/grpc_mux_impl_test.cc]: Nit: Don't think you need to use an explicit scope here, since we're not binding anything.

File: source/common/config/grpc_mux_impl.cc [hunk 4]
```diff
@@ -160,10 +160,26 @@ void GrpcMuxImpl::onReceiveMessage(std::unique_ptr<envoy::api::v2::DiscoveryResp
...
+    api_state_[type_url].request_.set_response_nonce(message->nonce());
+    if (message->resources().empty()) {
+      // No watches and no resources. This can happen when envoy unregisters from a resource
+      // that's removed from the server as well. For example, a deleted cluster triggers un-watching
+      // the ClusterLoadAssignment watch, and at the same time the xDS server sends an empty list of
+      // ClusterLoadAssignment resources. we'll accept this update. no need to send a discovery
+      // request, as we don't watch for anything.
+      api_state_[type_url].request_.set_version_info(message->version_info());
+    } else {
+      // No watches and we have resources - this should not happen. send ad NACK (by not updateding
```
Comment (htuch) [inline source/common/config/grpc_mux_impl.cc]: Nit: s/ad/a/, s/updateding/updating/
