### PR TITLE
Pass correct init manager to the secret manager

### LINKED ISSUE #22678: Segmentation Fault after `assert failure: false. Details: attempted to add shared target SdsApi <NAME_OF_SECRET> to initialized init manager Server
I've emailed <envoy-security@googlegroups.com> and was told to raise the issue here.

Please see the **_Segmentation Fault_** section at the later part of this email for the stack trace.

Please also see: <https://github.com/envoyproxy/go-control-plane/issues/581>.

## Issues

I've noticed a couple of things.

1. When we implement `SecretDiscoveryServiceServer` "[github.com/envoyproxy/go-control-plane/envoy/service/secret/v3](http://github.com/envoyproxy/go-control-plane/envoy/service/secret/v3)" sometimes the `StreamSecrets` does not get called back at all.
2. when `StreamSecrets` is called, it is called endlessly with a new stream each time, see the log output further down in this message.

When `StreamSecrets` is not called, obviously, our dynamically supplied secrets are titled `dynamic_warming_secrets` instead of `dynamic_active_secrets`.

## Code

Our code is public so, here are the definitions of:

1. `StreamSecrets`: https://github.com/kubeshop/kusk-gateway/blob/mbana-oauth-issue-401-sds/internal/envoy/sds/sds.go#L72
2. Where we register the `SecretDiscoveryServiceServer`: https://github.com/kubeshop/kusk-gateway/blob/mbana-oauth-issue-401-sds/internal/envoy/manager/envoy_config_manager.go#L183
3. Configuring the `cache` etc: https://github.com/kubeshop/kusk-gateway/blob/mbana-oauth-issue-401-sds/internal/envoy/manager/envoy_config_manager.go#L56.

Log of `StreamSecrets` being called multiple times (the `stream=&{0xc000f19c70}` is different each time):

```
2022-08-12T09:19:30Z | sds.go:74: SecretDiscoveryServiceServer.StreamSecrets: exiting method
2022-08-12T09:19:30Z | sds.go:92: 
2022-08-12T09:19:30Z | sds.go:93: SecretDiscoveryServiceServer.StreamSecrets: calling stream.Recv - stream=&{0xc000f19380}, len(s.ClientSecrets)=2
2022-08-12T09:19:30Z | sds.go:116: SecretDiscoveryServiceServer.StreamSecrets: request.TypeUrl=type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret, len(s.ClientSecrets)=2
2022-08-12T09:19:30Z | sds.go:153: SecretDiscoveryServiceServer.StreamSecrets: stream.Send(response) sent - responses=[<*>version_info:"2022-08-12T09:19:30Z"  resources:{[type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret]:{name:"hmac_secret"  generic_secret:{secret:{inline_bytes:"f9eckuGEcUNxAqKT0uK8OyM2Se01ukVLPHsiSoTh2X8="}}}}  type_url:"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret" <*>version_info:"2022-08-12T09:19:30Z"  resources:{[type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret]:{name:"client_secret"  generic_secret:{secret:{inline_string:"Z6MX7NreJumWLmf6unsQ5uiEUrTBxfNtqG9Vy5Kjktnvfj-_fRCBO9EU1mL1YzAJ"}}}}  type_url:"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"]
2022-08-12T09:19:30Z | sds.go:154: 
2022-08-12T09:19:30Z | sds.go:74: SecretDiscoveryServiceServer.StreamSecrets: exiting method
2022-08-12T09:19:30Z | sds.go:92: 
2022-08-12T09:19:30Z | sds.go:93: SecretDiscoveryServiceServer.StreamSecrets: calling stream.Recv - stream=&{0xc000f19c70}, len(s.ClientSecrets)=2
2022-08-12T09:19:30Z | sds.go:116: SecretDiscoveryServiceServer.StreamSecrets: request.TypeUrl=type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret, len(s.ClientSecrets)=2
2022-08-12T09:19:30Z | sds.go:153: SecretDiscoveryServiceServer.StreamSecrets: stream.Send(response) sent - responses=[<*>version_info:"2022-08-12T09:19:30Z"  resources:{[type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret]:{name:"client_secret"  generic_secret:{secret:{inline_string:"Z6MX7NreJumWLmf6unsQ5uiEUrTBxfNtqG9Vy5Kjktnvfj-_fRCBO9EU1mL1YzAJ"}}}}  type_url:"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret" <*>version_info:"2022-08-12T09:19:30Z"  resources:{[type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret]:{name:"hmac_secret"  generic_secret:{secret:{inline_bytes:"f9eckuGEcUNxAqKT0uK8OyM2Se01ukVLPHsiSoTh2X8="}}}}  type_url:"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"]
```

What we expect when we look at `/config_dump` of when `StreamSecrets` is being called:

```json
{
   "@type": "type.googleapis.com/envoy.admin.v3.SecretsConfigDump",
   "dynamic_active_secrets": [
    {
     "name": "client_secret",
     "version_info": "2022-08-12T09:22:18Z",
     "last_updated": "2022-08-12T09:22:18.140Z",
     "secret": {
      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret",
      "name": "client_secret",
      "generic_secret": {
       "secret": {
        "inline_string": "[redacted]"
       }
      }
     }
    },
    {
     "name": "hmac_secret",
     "version_info": "2022-08-12T09:22:18Z",
     "last_updated": "2022-08-12T09:22:18.386Z",
     "secret": {
      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret",
      "name": "hmac_secret",
      "generic_secret": {
       "secret": {
        "inline_bytes": "W3JlZGFjdGVkXQ=="
       }
      }
     }
    }
   ]
  }
```

Don't worry about the exposed the secrets, they'll be removed soon.

## Logs or Debug Information

In addition to that, here are dumps taken from the admin endpoint (`/config_dump`) of when it is working and when it is not working, i.e., when the `StreamSecrets` gRPC method is not invoked on the `go-control-plane` and when it is. Notice how the secrets are called `dynamic_warming_secrets`.

1. `config_dump-broken.json`: https://gist.github.com/mbana/61305292ddb9fd83e260a0125893f6ca
2. `logs-broken.log`: https://gist.github.com/mbana/a4636cf5e96a035db618f7c37b8dc275
3. `config_dump-working.json`: https://gist.github.com/mbana/e9b7b29ed7c1be032aca867304d86d60
4. `logs-working.log`: https://gist.github.com/mbana/2881bc1873090d8d82649ba95625d789

If there's anything further I can do to help get to the cause of this issue, please let me know.

---

## Envoy Compiled From `7af7608b022c5e3ae2ad110b4d94aa7506a643d7`

**Edit:** I went a step further and compiled Envoy from source and made a Docker image of it:

### Dockerfile

```dockerfile
FROM docker.io/ubuntu:22.04

COPY envoy-static /usr/local/bin/envoy
COPY envoy-static /usr/bin/envoy

ENTRYPOINT ["/usr/local/bin/envoy"]
```

### Build Steps

```sh
$ git remote -vv    
origin	git@github.com:envoyproxy/envoy.git (fetch)
origin	git@github.com:envoyproxy/envoy.git (push)
$ git rev-parse HEAD
7af7608b022c5e3ae2ad110b4d94aa7506a643d7
$ bazel/setup_clang.sh
$ echo "build --config=clang" >> user.bazelrc
$ echo "build --copt=-fno-limit-debug-info" >> user.bazelrc
$ bazel build --jobs=32 -c fastbuild envoy
$ cp bazel-bin/source/exe/envoy-static .
$ docker build --tag ttl.sh/kubeshop/envoy:24h --file ./Dockerfile .
$ docker push ttl.sh/kubeshop/envoy:24h
```

The image is available at `ttl.sh/kubeshop/envoy:24h` (`docker run --rm -it ttl.sh/kubeshop/envoy:24h`). **Note:** This image is only available for ~24 hours from the time of editing this post (`2022-08-12T13:47:31+00:00` UTC).

### Segmentation Fault

I noticed that Envoy crashes:

```log
[2022-08-12 13:35:16.253][7][critical][assert] [source/common/init/manager_impl.cc:36] assert failure: false. Details: attempted to add shared target SdsApi client_secret to initialized init manager Server
[2022-08-12 13:35:16.253][7][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x7
[2022-08-12 13:35:16.253][7][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2022-08-12 13:35:16.253][7][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 7af7608b022c5e3ae2ad110b4d94aa7506a643d7/1.24.0-dev/Modified/DEBUG/BoringSSL
[2022-08-12 13:35:16.272][7][critical][backtrace] [./source/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x5579a06c8b28]
[2022-08-12 13:35:16.273][7][critical][backtrace] [./source/server/backtrace.h:98] #1: [0x7f086bc6a520]
AsyncClient 0x550cbfc8ec00, stream_id_: 15115583590745907833
&stream_info_: 
  StreamInfoImpl 0x550cbfc8edc8, protocol_: 1, response_code_: null, response_code_details_: via_upstream, attempt_count_: 1, health_check_request_: 0, route_name_:   upstream_info_: 
    UpstreamInfoImpl 0x550cbfc81570, upstream_connection_id_: 0
Http2::ConnectionImpl 0x550cbf8d7dc8, max_headers_kb_: 60, max_headers_count_: 100, per_stream_buffer_limit_: 268435456, allow_metadata_: 0, stream_error_on_invalid_http_messaging_: 0, is_outbound_flood_monitored_control_frame_: 0, dispatching_: 1, raised_goaway_: 0, pending_deferred_reset_streams_.size(): 0
&protocol_constraints_: 
  ProtocolConstraints 0x550cbf8d7e48, outbound_frames_: 0, max_outbound_frames_: 10000, outbound_control_frames_: 0, max_outbound_control_frames_: 1000, consecutive_inbound_frames_with_empty_payload_: 0, max_consecutive_inbound_frames_with_empty_payload_: 1, opened_streams_: 1, inbound_priority_frames_: 0, max_inbound_priority_frames_per_stream_: 100, inbound_window_update_frames_: 4, outbound_data_frames_: 4, max_inbound_window_update_frames_per_data_frame_sent_: 10
Number of active streams: 1, current_stream_id_: 1 Dumping current stream:
stream: 
  ConnectionImpl::StreamImpl 0x550cbf50bd40, stream_id_: 1, unconsumed_bytes_: 0, read_disable_count_: 0, local_end_stream_: 0, local_end_stream_sent_: 0, remote_end_stream_: 0, data_deferred_: 1, received_noninformational_headers_: 1, pending_receive_buffer_high_watermark_called_: 0, pending_send_buffer_high_watermark_called_: 0, reset_due_to_messaging_error_: 0, cookies_:   pending_trailers_to_encode_:   null
  absl::get<ResponseHeaderMapPtr>(headers_or_trailers_):   null
Dumping corresponding downstream request for upstream stream 1:
  UpstreamRequest 0x550cbfdfcd80
[2022-08-12 13:35:16.273][7][critical][backtrace] [./source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0
[2022-08-12 13:35:16.273][7][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2022-08-12 13:35:16.273][7][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 7af7608b022c5e3ae2ad110b4d94aa7506a643d7/1.24.0-dev/Modified/DEBUG/BoringSSL
[2022-08-12 13:35:16.273][7][critical][backtrace] [./source/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x5579a06c8b28]
[2022-08-12 13:35:16.273][7][critical][backtrace] [./source/server/backtrace.h:98] #1: [0x7f086bc6a520]
[2022-08-12 13:35:16.292][7][critical][backtrace] [./source/server/backtrace.h:96] #2: Envoy::Http::ResponseDecoderWrapper::dumpState() [0x55799f4d23f8]
[2022-08-12 13:35:16.311][7][critical][backtrace] [./source/server/backtrace.h:96] #3: Envoy::Http::Http2::ClientConnectionImpl::dumpStreams() [0x55799fae8b21]
[2022-08-12 13:35:16.330][7][critical][backtrace] [./source/server/backtrace.h:96] #4: Envoy::Http::Http2::ConnectionImpl::dumpState() [0x55799fae850a]
[2022-08-12 13:35:16.348][7][critical][backtrace] [./source/server/backtrace.h:96] #5: Envoy::Event::DispatcherImpl::onFatalError() [0x5579a031cd35]
[2022-08-12 13:35:16.367][7][critical][backtrace] [./source/server/backtrace.h:96] #6: Envoy::FatalErrorHandler::callFatalErrorHandlers() [0x5579a06cf35a]
[2022-08-12 13:35:16.386][7][critical][backtrace] [./source/server/backtrace.h:96] #7: Envoy::SignalAction::sigHandler() [0x5579a06c8b8a]
[2022-08-12 13:35:16.386][7][critical][backtrace] [./source/server/backtrace.h:98] #8: [0x7f086bc6a520]
Our FatalActions triggered a fatal signal.
Segmentation fault (core dumped)
```

Can anyone see anything useful in this stack-trace? The assertion failing is particular interesting, but I don't know much about the Envoy code-base to tell if this is an issue or not:

```log
[2022-08-12 13:35:16.253][7][critical][assert] [source/common/init/manager_impl.cc:36] assert failure: false. Details: attempted to add shared target SdsApi client_secret to initialized init manager Server
```

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Commit Message: fixes #22678 and #22625 
oauth2 filter is passing "Server" init manager to the secret manager, which is already in "initialized" state if oauth2 filter gets added later on and thus the crash in manager_impl.cc saying "trying to add target to already initialized manager". outh2 filter is extracting init manager from the wrong transport socket factory. It is using listener's parents' transport socket factory from the factory context while the init manager that the current listener has initialized is the context.initManager(). This PR is making changes to pass init manager as an additional argument to the secret manager. 

Additional Description:
Risk Level: low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
Will update tests only if changes gets a thumbs up direction wise and hence the draft state.

File: source/common/secret/secret_manager_impl.h [hunk 1]
```diff
@@ -95,7 +100,8 @@ class SecretManagerImpl : public SecretManager {
       // It is important to add the init target to the manager regardless the secret provider is new
       // or existing. Different clusters / listeners can share same secret so they have to be marked
       // warming correctly.
-      secret_provider_context.initManager().add(*secret_provider->initTarget());
+
+      init_manager.add(*secret_provider->initTarget());
```
Comment (vikaschoudhary16) [inline source/common/secret/secret_manager_impl.h:104]: this is the actual change

**Comment by mbana** [comment]
I'm also interested in this pull request.

Why are the tests failing, @vikaschoudhary16.

**Comment by vikaschoudhary16** [comment]
> I'm also interested in this pull request.
> 
> Why are the tests failing, @vikaschoudhary16.

I changed the interface so tests are expected to be failing. Though I have tested the changes locally. Would invest time on tests once I get a go-ahead on the approach direction wise.

File: source/common/secret/secret_manager_impl.h [hunk 2]
```diff
@@ -77,7 +81,8 @@ class SecretManagerImpl : public SecretManager {
     std::shared_ptr<SecretType>
     findOrCreate(const envoy::config::core::v3::ConfigSource& sds_config_source,
                  const std::string& config_name,
-                 Server::Configuration::TransportSocketFactoryContext& secret_provider_context) {
+                 Server::Configuration::TransportSocketFactoryContext& secret_provider_context,
```
Comment (mattklein123) [inline source/common/secret/secret_manager_impl.h:84]: In a perfect world we would remove the init manager from the passed in context if it's not actually valid (so instead make some new type of context for the secret manager), but I would defer to @kyessenov and @alyssawilk who have more recent experience with all of the contexts and the right thing to do here. Otherwise this generally looks like the right track. Thanks!

Comment (alyssawilk) [reply source/common/secret/secret_manager_impl.h:84]: I don't have context on this particular change but
0) thank you for catching this and fixing this!
1) I have encountered the fact that the server context has an init manger being dangerous (I wonder if it's worth the churn to rename to something like startUpOnlyInitManager() but it might not have added clarity here)
2) definitely worth adding a reload test which would not have worked before (I think you can probably combine one of the lds integration tests with the oath tests?) and comments explaining why this is important

**Comment by mbana** [comment]
Thanks, @vikaschoudhary16.

I need to do further testing but I think it's working. I know see the log line appearing (from the `go-control-plane`):

```
kusk-system kusk-gateway-manager-554d5fbb7-k8r6m manager {"level":"info","ts":1664965401.9960532,"logger":"CacheManager","caller":"manager/envoy_callbacks.go:65","msg":"OnStreamRequest","id":1,"request.TypeUrl":"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret","request.Node.Cluster":"default.default","request.Node.Id":"default-565ddbd959-h9q8v"}
```

whereas before, I do not believe this was working. I need to do further tests to be sure.

I've made the images available at:

* `ttl.sh/kubeshop/envoy-fix-oauth-sds:24h` - this is only available for 24 hours from now and will expire after that.
* `docker.io/banaioltd/envoy:fix-oauth-sds`

---

@marcosrmendezthd and @kyessenov could you possibly test this out?

File: source/common/secret/secret_manager_impl.h (hunk 2 above)
Comment (kyessenov) [reply source/common/secret/secret_manager_impl.h:84]: Yes, I agree this is a good catch, and thanks for finding the root cause. I think this bug came to be because the original usage was only in the context of the upstream clusters and the downstream listeners, where the transport socket was the expected thing that needs to be initialized. So technically, the code isn't wrong and runtime detection wouldn't help. But I'd also recommend not sub-typing contexts (e.g. avoid passing any other context) to prevent lifetime issues.

**Comment by marcosrmendezthd** [comment]
what's the dev docker image I can use to test this?

**Comment by mbana** [comment]
> what's the dev docker image I can use to test this?

Originally from <https://github.com/kubeshop/kusk-gateway/pull/697#issuecomment-1268227665>:

It's available at:

`docker.io/banaioltd/envoy:fix-oauth-sds`

Built with `build --copt=-fno-limit-debug-info`.


@marcosrmendezthd, do you have a set of automated tests that you run or are you manually going to test it?

**Comment by marcosrmendezthd** [comment]
don't have automated tests for this unfortunately, just the bits I wrote to encounter the issue. https://github.com/envoyproxy/envoy/issues/22625#issuecomment-1209385502

**Review by kyessenov — COMMENTED** [review]
The change LGTM but I think it'd help to have a regression test. Maybe modify oauth2_integration test to use LDS for oauth2 config? I think that should trigger the code path that incorrectly adds to server init manager.

File: test/server/listener_manager_impl_test.h [hunk 3]
```diff
@@ -338,10 +340,27 @@ class ListenerManagerImplTest : public testing::TestWithParam<bool> {
...
+  GenericSecretConfigProviderSharedPtr helperFindOrCreateGenericSecretProvider(
+      const envoy::config::core::v3::ConfigSource& sds_config_source,
+      const std::string& config_name,
+      Server::Configuration::TransportSocketFactoryContext& secret_provider_context,
+      Init::Manager& init_manager) {
+    std::function<void()> unregister_secret_provider = []() {};
+    GenericSecretConfigProviderSharedPtr secret_provider(sds_api_->create(
+        secret_provider_context, sds_config_source, config_name, unregister_secret_provider));
+    init_manager.add(*secret_provider->initTarget());
+    // secret_provider_context.initManager().add(*secret_provider->initTarget());
```
Comment (vikaschoudhary16) [inline test/server/listener_manager_impl_test.h:352]: if we uncomment and use `secret_provider_context` which is the server's transport socket context, same failure we will encounter that is reported in the linked issue.
Currently `init_manager` is being used which is the newly created while adding listener and thus the test passes.
IOW, regression test is guarding against the case when the factory context's init manager is also set to the server's init manager.

Comment (kyessenov) [reply test/server/listener_manager_impl_test.h:352]: Is it possible to avoid duplicating the code for initialization? An integration test is probably a better option than a unit test in listener_manager. See, for example, https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/oauth2/oauth_integration_test.cc. My understanding is that the existing test did not exercise delayed oauth2 filter initialization (e.g. it probably put filter into bootstrap). So if we can initialize server and then push LDS, we should be able to exercise the code path directly?

**Review by kyessenov — COMMENTED** [review]
Please fix CI, left a comment.
/wait

File: test/server/listener_manager_impl_test.h (hunk 3 above)
Comment (vikaschoudhary16) [reply test/server/listener_manager_impl_test.h:352]: sure

File: test/mocks/server/transport_socket_factory_context.h [hunk 4]
```diff
@@ -22,7 +23,9 @@ class MockTransportSocketFactoryContext : public TransportSocketFactoryContext {
   MockTransportSocketFactoryContext();
   ~MockTransportSocketFactoryContext() override;
 
-  Secret::SecretManager& secretManager() override { return *(secret_manager_.get()); }
+  Secret::SecretManager& secretManager() override { return *secret_manager_; }
+  // Secret::MockSecretManager& secretManager() override { return secret_manager_; };
```
Comment (kyessenov) [inline test/mocks/server/transport_socket_factory_context.h:27]: Can you remove the commented out code?

File: test/server/BUILD [hunk 5]
```diff
@@ -307,6 +307,9 @@ envoy_cc_test(
         "//source/common/network:socket_option_lib",
         "//source/common/network:utility_lib",
         "//source/common/protobuf",
+        "//source/common/secret:secret_manager_impl_lib",
+        "//source/extensions/filters/http/oauth2:config",
```
Comment (kyessenov) [inline test/server/BUILD:311]: We generally try to avoid bringing extensions into core tests, since it prevents the import into Envoy versions without those extensions. Can we move this test into the extension specific test suite?

**Review by kyessenov — COMMENTED** [review]
/wait

**Comment by marcosrmendezthd** [comment]
@mbana seems to be working on the sample setup I provided on #22625. I was able to change the config back and forth, and envoy was able to pick up the correct OAuth2 secrets.

```
cluster_manager.cds.version_text: "oauth2"
listener_manager.lds.version_text: "oauth2"
sds.cluster_validation_context.version_text: "oauth2"
sds.listener_certificate.version_text: "oauth2"
sds.listener_validation_context.version_text: "oauth2"
sds.oauth2_hmac_secret.version_text: "oauth2"
sds.oauth2_token_secret.version_text: "oauth2"
```

File: test/mocks/server/transport_socket_factory_context.h (hunk 4 above)
Comment (vikaschoudhary16) [reply test/mocks/server/transport_socket_factory_context.h]: removed these tests and rather added integration test in the oauth as you suggested.

File: test/server/BUILD (hunk 5 above)
Comment (vikaschoudhary16) [reply test/server/BUILD]: removed these changes

**Comment by vikaschoudhary16** [comment]
> The change LGTM but I think it'd help to have a regression test. Maybe modify oauth2_integration test to use LDS for oauth2 config? I think that should trigger the code path that incorrectly adds to server init manager.

done. PTAL!

**Review by kyessenov — DISMISSED** [review]
The new integration test looks good to me. Thanks again for fixing this bug.
(CI format needs some fixes).

File: test/extensions/filters/http/oauth2/oauth_integration_test.cc [hunk 6]
```diff
@@ -211,8 +297,108 @@ name: oauth
...
+    // dummy listener is being sent so that lds api gets marked as ready, which would
+    // led to server's init manager reach initialized state
+    sendLdsResponse({listener}, "initial");
+  };
+
+  initialize();
+
+  // add listener with oauth2 filter and sds configs
+  sendLdsResponse({MessageUtil::getYamlStringFromMessage(listener_config_)}, "delayed");
+
```
Comment (kyessenov) [inline test/extensions/filters/http/oauth2/oauth_integration_test.cc:399]: Since you're going to have to push another commit: I think we need to add to wait for the new listener config to be applied here: `test_server_->waitForCounterGe("listener_manager.lds.update_success", 2);`.

Comment (kyessenov) [reply test/extensions/filters/http/oauth2/oauth_integration_test.cc:399]: Also: `test_server_->waitForGaugeEq("listener_manager.total_listeners_warming", 0);`

Comment (vikaschoudhary16) [reply test/extensions/filters/http/oauth2/oauth_integration_test.cc:400]: done!

**Review by kyessenov — APPROVED** [review]

**Comment by phlax** [comment]
i have raised a backport PR for the 1.24 branch here https://github.com/envoyproxy/envoy/pull/24823

backporting to 1.23 will take a bit more work - it creates some test conflict - if anyone was willing to take that on it can be reviewed for inclusion in the next patch release
