### PR TITLE
grpc mux: fix sending node again after stream is reset

### LINKED ISSUE #9682: set_node_on_first_message_only seems to never set node ID
**Issue Template**

*Title*: set_node_on_first_message_only seems to never set node ID

*Description*:
I turned on `set_node_on_first_message_only`, and now things are breaking because it appears the node id is actually never sent. Turning on verbose logging on the XDS server shows the first requests we get looks like:

```
version_info:"2020-01-14T23:12:41Z/1" type_url:"type.googleapis.com/envoy.api.v2.Cluster" response_nonce:"uj8hmiCQEes=2abe5090-3bef-43b8-be61-899e9e61623a"
```

Note the missing node id

@kyessenov

### PR DESCRIPTION
**Pull request by tbarrella**
Commit Message:
grpc mux: fix sending node again after stream is reset

Previously, first_stream_request_ wasn't working as intended because api_state_ is still cached from the previous stream

Signed-off-by: Taylor Barrella <tabarr@google.com>

Additional Description:
Risk Level: Low
Testing: Modified test was failing before the accompanying change
Docs Changes: N/A
Release Notes:
Fixes #9682

### CODE REVIEW

File: test/common/config/grpc_mux_impl_test.cc [hunk 1]
```diff
@@ -159,18 +159,23 @@ TEST_F(GrpcMuxImplTest, ResetStream) {
...
-      .Times(3);
+      .Times(4);
   EXPECT_CALL(random_, random());
   EXPECT_CALL(*timer, enableTimer(_, _));
   grpc_mux_->grpcStreamForTest().onRemoteClose(Grpc::Status::WellKnownGrpcStatus::Canceled, "");
   EXPECT_EQ(0, control_plane_connected_state_.value());
   EXPECT_EQ(0, control_plane_pending_requests_.value());
   EXPECT_CALL(*async_client_, startRaw(_, _, _, _)).WillOnce(Return(&async_stream_));
-  expectSendMessage("foo", {"x", "y"}, "", true);
+  expectSendMessage("foo", {"z", "x", "y"}, "", true);
```
Comment (lambdai) [inline test/common/config/grpc_mux_impl_test.cc:175]: Can you add the comment what is the confirmation that the node metadata is added?

File: test/common/config/grpc_mux_impl_test.cc [hunk 2]
```diff
@@ -159,18 +159,23 @@ TEST_F(GrpcMuxImplTest, ResetStream) {
   expectSendMessage("baz", {"z"}, "");
   grpc_mux_->start();
 
+  // Send another message for foo so that the node is cleared in the cached request.
+  expectSendMessage("foo", {"z", "x", "y"}, "");
```
Comment (lambdai) [inline test/common/config/grpc_mux_impl_test.cc:163]: Regarding https://github.com/envoyproxy/envoy/pull/14080/files#r526407920

OK... I didn't realize this clear op did not exist.

Comment (tbarrella) [reply test/common/config/grpc_mux_impl_test.cc]: (added another comment line to clarify)

File: test/common/config/grpc_subscription_test_harness.h [hunk 3]
```diff
@@ -44,7 +44,7 @@ class GrpcSubscriptionTestHarness : public SubscriptionTestHarness {
             "envoy.api.v2.EndpointDiscoveryService.StreamEndpoints")),
         async_client_(new NiceMock<Grpc::MockAsyncClient>()) {
     node_.set_id("fo0");
-    EXPECT_CALL(local_info_, node()).WillOnce(testing::ReturnRef(node_));
+    EXPECT_CALL(local_info_, node()).WillRepeatedly(testing::ReturnRef(node_));
```
Comment (htuch) [inline test/common/config/grpc_subscription_test_harness.h:47]: I think we should add some tests to `ads_integration_test` to capture this regression end-to-end, for both SotW and delta. This will provide confidence that we don't hit this issue again.

**Review by htuch — CHANGES_REQUESTED** [review]
Thanks for the fix, looks good but we should have a more complete e2e test.
/wait

File: test/common/config/grpc_subscription_test_harness.h (hunk 3 above)
Comment (tbarrella) [reply test/common/config/grpc_subscription_test_harness.h:47]: Do you know if there's already a way to reset the stream during an integration test? Also sorry, this might take me a while because I've never written an integration test

Comment (htuch) [reply test/common/config/grpc_subscription_test_harness.h:47]: Sure, you can just close the fake upstream corresponding to the ADS server. See `xds_upstream_`, which you can access from `ads_integration_test.cc`. You can probably use something like `encodeResetStream()` on the ADS stream.

Comment (tbarrella) [reply test/common/config/grpc_subscription_test_harness.h:47]: I think I got something working but should probably merge #14270 first

**Review by htuch — APPROVED** [review]
LGTM, thanks!
