### PR TITLE
http: delaying attach pending requests

### LINKED ISSUE #2715: HTTP1 conneciton pool attach pending request to half-closed connection
*Description*:
The HTTP1 connection pool attach pending request [when a response is complete](https://github.com/envoyproxy/envoy/blob/c932e50c34a11dd382dca9c5daf2026d4686daa9/source/common/http/http1/conn_pool.cc#L212). Though the upstream server may already closed the connection, this will result the pending request attached to it end up with 503.

A sample upstream HTTP1 trace log:
```
[2018-03-03 00:11:36.931][20][debug][client] external/envoy/source/common/http/codec_client.cc:23] [C581] connecting
[2018-03-03 00:11:36.931][20][debug][connection] external/envoy/source/common/network/connection_impl.cc:559] [C581] connecting to 127.0.0.1:8080
[2018-03-03 00:11:36.932][20][debug][connection] external/envoy/source/common/network/connection_impl.cc:568] [C581] connection in progress
[2018-03-03 00:11:37.178][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C581] socket event: 2
[2018-03-03 00:11:37.178][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C581] write ready
[2018-03-03 00:11:37.180][20][debug][connection] external/envoy/source/common/network/connection_impl.cc:455] [C581] connected
[2018-03-03 00:11:37.180][20][debug][client] external/envoy/source/common/http/codec_client.cc:52] [C581] connected
[2018-03-03 00:11:37.181][20][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:225] [C581] attaching to next request
[2018-03-03 00:11:37.184][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:314] [C581] writing 506 bytes, end_stream false
[2018-03-03 00:11:37.184][20][trace][connection] external/envoy/source/common/network/raw_buffer_socket.cc:67] [C581] write returns: 506
[2018-03-03 00:11:37.459][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C581] socket event: 2
[2018-03-03 00:11:37.459][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C581] write ready
[2018-03-03 00:11:37.487][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:377] [C581] socket event: 3
[2018-03-03 00:11:37.487][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:445] [C581] write ready
[2018-03-03 00:11:37.487][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:415] [C581] read ready
[2018-03-03 00:11:37.488][20][trace][connection] external/envoy/source/common/network/raw_buffer_socket.cc:25] [C581] read returns: 166
[2018-03-03 00:11:37.488][20][trace][connection] external/envoy/source/common/network/raw_buffer_socket.cc:25] [C581] read returns: 0
[2018-03-03 00:11:37.488][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:298] [C581] parsing 166 bytes
[2018-03-03 00:11:37.489][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:285] [C581] completed header: key=content-length value=0
[2018-03-03 00:11:37.489][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:285] [C581] completed header: key=date value=Sat, 03 Mar 2018 00:11:36 GMT
[2018-03-03 00:11:37.489][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:285] [C581] completed header: key=content-type value=text/plain; charset=utf-8
[2018-03-03 00:11:37.490][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:285] [C581] completed header: key=x-envoy-upstream-service-time value=49
[2018-03-03 00:11:37.490][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:354] [C581] headers complete
[2018-03-03 00:11:37.491][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:285] [C581] completed header: key=server value=envoy
[2018-03-03 00:11:37.497][20][debug][client] external/envoy/source/common/http/codec_client.cc:81] [C581] response complete
[2018-03-03 00:11:37.501][20][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:200] [C581] response complete
[2018-03-03 00:11:37.502][20][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:225] [C581] attaching to next request
[2018-03-03 00:11:37.503][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:314] [C581] writing 509 bytes, end_stream false
[2018-03-03 00:11:37.504][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:315] [C581] parsed 166 bytes
[2018-03-03 00:11:37.504][20][debug][connection] external/envoy/source/common/network/connection_impl.cc:439] [C581] remote close
[2018-03-03 00:11:37.505][20][debug][connection] external/envoy/source/common/network/connection_impl.cc:134] [C581] closing socket: 0
[2018-03-03 00:11:37.505][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:298] [C581] parsing 0 bytes
[2018-03-03 00:11:37.505][20][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:315] [C581] parsed 0 bytes
[2018-03-03 00:11:37.506][20][debug][client] external/envoy/source/common/http/codec_client.cc:70] [C581] disconnect. resetting 1 pending requests
[2018-03-03 00:11:37.506][20][debug][client] external/envoy/source/common/http/codec_client.cc:91] [C581] request reset
[2018-03-03 00:11:37.520][20][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:115] [C581] client disconnected
```

The first request was processed correctly while the 2nd request is attached at
```
[2018-03-03 00:11:37.502][20][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:225] [C581] attaching to next request
[2018-03-03 00:11:37.503][20][trace][connection] external/envoy/source/common/network/connection_impl.cc:314] [C581] writing 509 bytes, end_stream false
```

The write never complete and the request was reset immediately.

*Repro steps*:
It is a little bit hard to reproduce, I'll update when I have a minimal reproducible environment.

The current repro is with [Istio load testing tool](https://github.com/istio/istio/tree/0.6.0/tools) at 100 qps with mTLS enabled.
See https://github.com/istio/istio/issues/3295 for more details.

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <zlizan@google.com>

*Description*:
Another approach to #2715, attach pending request in next event after onResponseComplete.

*Risk Level*: Low
*Testing*: unit test, integration test
*Docs Changes*: N/A
*Release Notes*: N/A

Fixes #2715

### CODE REVIEW

File: source/common/http/http1/conn_pool.cc [hunk 1]
```diff
@@ -213,19 +213,29 @@ void ConnPoolImpl::onResponseComplete(ActiveClient& client) {
...
+
+void ConnPoolImpl::processIdleClient(ActiveClient& client) {
+  client.stream_wrapper_.reset();
+  // There is nothing to service so just move the connection into the ready list.
+  ENVOY_CONN_LOG(debug, "moving to ready", *client.codec_client_);
+  client.moveBetweenLists(busy_clients_, ready_clients_);
+
+  if (!pending_requests_.empty() && !upstream_ready_posted_) {
+    upstream_ready_posted_ = true;
+    dispatcher_.post([this]() { onUpstreamReady(); });
```
Comment (mattklein123) [inline source/common/http/http1/conn_pool.cc]: Instead of using `post()`, I would allocate a new "timer" and just enable it with a 0ms timeout here. The reason for this is that when the conn pool is destroyed (as might happen in certain cases), the wakeup is disabled. This pattern is used in a bunch of places for similar reasons.

Comment (lizan) [reply source/common/http/http1/conn_pool.cc]: Done

File: source/common/http/http1/conn_pool.cc [hunk 2]
```diff
@@ -213,19 +213,29 @@ void ConnPoolImpl::onResponseComplete(ActiveClient& client) {
...
-void ConnPoolImpl::processIdleClient(ActiveClient& client) {
-  client.stream_wrapper_.reset();
-  if (pending_requests_.empty()) {
-    // There is nothing to service so just move the connection into the ready list.
-    ENVOY_CONN_LOG(debug, "moving to ready", *client.codec_client_);
-    client.moveBetweenLists(busy_clients_, ready_clients_);
-  } else {
+void ConnPoolImpl::onUpstreamReady() {
+  upstream_ready_posted_ = false;
+  while (!pending_requests_.empty() && !ready_clients_.empty()) {
```
[the remark this answers is not in the document]
Comment (lizan) [reply source/common/http/http1/conn_pool.cc]: Do you mean `pending_requests_` should be always smaller than `ready_clients_`? I think the line only make sure the the sum of `ready_clients_` and `busy_clients_` is larger than `pending_requests_` so we should check both of them here, no?

[the remark this answers is not in the document]
Comment (mattklein123) [reply source/common/http/http1/conn_pool.cc]: I mean that when connections die, we should make a new connection if the number of existing ready + busy connections is not sufficient. I think the code already does that. I just want to make sure we have test coverage of this case. Does the integration test you have cover it? (Basically I think the code you have is correct. I just want to make sure we have good coverage).

File: test/common/http/http1/conn_pool_test.cc [hunk 3]
```diff
@@ -42,10 +42,15 @@ namespace Http1 {
...
-                      Upstream::ClusterInfoConstSharedPtr cluster)
+                      Upstream::ClusterInfoConstSharedPtr cluster,
+                      NiceMock<Event::MockTimer>* upstream_ready_timer)
       : ConnPoolImpl(dispatcher, Upstream::makeTestHost(cluster, "tcp://127.0.0.1:9000"),
                      Upstream::ResourcePriority::Default, nullptr),
-        mock_dispatcher_(dispatcher) {}
+        mock_dispatcher_(dispatcher), mock_upstream_ready_timer_(upstream_ready_timer) {
+    ON_CALL(*mock_upstream_ready_timer_, enableTimer(std::chrono::milliseconds(0)))
+        .WillByDefault(Invoke(
+            [&](const std::chrono::milliseconds&) { mock_upstream_ready_timer_->callback_(); }));
```
Comment (mattklein123) [inline test/common/http/http1/conn_pool_test.cc]: The fact that this gets invoked inline is not an accurate view of how the real code will work. I would not add this ON_CALL, and explicitly fire the ready even when needed outside of the immediate call stack. I really this is tedious, but given how important it is that this code is correct and how we would like it to track the real code as much as possible, I think it's worth it.

File: source/common/http/http1/conn_pool.cc (hunk 2 above)
[the remark this answers is not in the document]
Comment (lizan) [reply source/common/http/http1/conn_pool.cc]: OK, the new integration test I added is testing that behavior (and what would fail before this PR because of #2715).

**Comment by zuercher** [comment]
Going to unassign myself as I'll be unavailable next week. @alyssawilk can assign another non-senior reviewwe on Monday as necessary.

**Comment by alyssawilk** [comment]
@mattklein123 is assigned and he can cover both senior and cross-company.  Matt, I think you're most familiar with this code anyway, but let me know if you want a second pair of eyes on this one and I can take a look as well!

File: test/common/http/http1/conn_pool_test.cc (hunk 3 above)
Comment (lizan) [reply test/common/http/http1/conn_pool_test.cc]: Done.

**Comment by mattklein123** [comment]
@lizan can you check tests?

**Comment by lizan** [comment]
Yep, I'm trying to reproduce them locally.

**Comment by lizan** [comment]
Hmm, I cannot reproduce them outside CircleCI, (on my macOS, GCE with docker or without docker)... Will continue to investigate, does anyone have idea?

**Comment by mattklein123** [comment]
@lizan I'm guessing the test failures are spurious. Can you just push a dummy commit?

**Comment by lizan** [comment]
It seems consistent in CircleCI, I've pushed many merge commits which triggers CI run.

**Comment by mattklein123** [comment]
@lizan there must be some timing issue here. I haven't looked but given that ASAN/TSAN failed, maybe that's a clue? Or try running in a loop on your machine?

**Comment by lizan** [comment]
Yeah that's my suspect too. I had runs_per_test=100 with no luck, will try more...

**Comment by lizan** [comment]
The latest ASAN/TSAN failure is JVM OOO `java.io.IOException: Cannot allocate memory`, so for sure they are irrelevant (CircleCI failure)

**Comment by lizan** [comment]
oops, enable CircleCI in my fork resulted the CI result from there (with less resource, hence OOM) being reported here... Will try to add some dummy commit to debug the CI, feel free to ignore the notifications.

**Comment by lizan** [comment]
I'm still trying to fix the test but had no luck yet. It never reproduced on my local machine and only once on Istio circle CI, it seems only fails when 1st time running in a machine or something weird. I'll get back to this later this week.

**Comment by lizan** [comment]
@mattklein123 I changed the logic a bit (not using timer for onConnected event) and seems it fixed the tests and it also perform better. PTAL again. Thanks!

File: source/common/http/http1/conn_pool.h [hunk 4]
```diff
@@ -134,6 +134,9 @@ class ConnPoolImpl : Logger::Loggable<Logger::Id::pool>, public ConnectionPool::
   std::list<DrainedCb> drained_callbacks_;
   Upstream::ResourcePriority priority_;
   const Network::ConnectionSocket::OptionsSharedPtr socket_options_;
+
```
Comment (mattklein123) [inline source/common/http/http1/conn_pool.h]: nit: del newline

File: source/common/http/http1/conn_pool.cc [hunk 5]
```diff
@@ -209,25 +215,44 @@ void ConnPoolImpl::onResponseComplete(ActiveClient& client) {
...
+    client.moveBetweenLists(ready_clients_, busy_clients_);
   }
 }
 
-void ConnPoolImpl::processIdleClient(ActiveClient& client) {
+void ConnPoolImpl::processIdleClient(ActiveClient& client, bool delay) {
   client.stream_wrapper_.reset();
-  if (pending_requests_.empty()) {
+  if (pending_requests_.empty() || delay) {
     // There is nothing to service so just move the connection into the ready list.
```
Comment (alyssawilk) [inline source/common/http/http1/conn_pool.cc]: Update comment please

File: source/common/http/http1/conn_pool.cc [hunk 6]
```diff
@@ -209,25 +215,44 @@ void ConnPoolImpl::onResponseComplete(ActiveClient& client) {
     host_->cluster().stats().upstream_cx_max_requests_.inc();
     onDownstreamReset(client);
   } else {
-    processIdleClient(client);
+    processIdleClient(client, true);
```
Comment (alyssawilk) [inline source/common/http/http1/conn_pool.cc]: Can we comment why, perhaps with a link to the original issue to make it clear why we are doing this?

File: source/common/http/http1/conn_pool.cc [hunk 7]
```diff
@@ -209,25 +215,44 @@ void ConnPoolImpl::onResponseComplete(ActiveClient& client) {
...
+  }
+}
+
+void ConnPoolImpl::onUpstreamReady() {
+  upstream_ready_enabled_ = false;
+  while (!pending_requests_.empty() && !ready_clients_.empty()) {
```
Comment (alyssawilk) [inline source/common/http/http1/conn_pool.cc]: sanity check: this is simply deferring work we used to do in the last dispatcher loop to the next loop, so there's no corner case we'll end up batching together too much work and triggering the watchdog, right?

File: test/integration/http_integration.cc [hunk 8]
```diff
@@ -936,6 +936,57 @@ void HttpIntegrationTest::testIdleTimeoutWithTwoRequests() {
...
+  codec_client2->makeRequestWithBody(Http::TestHeaderMapImpl{{":method", "GET"},
+                                                             {":path", "/test/long/url"},
+                                                             {":scheme", "http"},
+                                                             {":authority", "host"}},
+                                     512, *response2);
+
+  // Response 1.
+  upstream_request_->encodeHeaders(Http::TestHeaderMapImpl{{":status", "200"}}, false);
+  upstream_request_->encodeData(512, true);
+  fake_upstream_connection_->close();
```
Comment (alyssawilk) [inline test/integration/http_integration.cc]: Sorry, I may not have had sufficient caffeine, but how are we making sure that the test Envoy is receiving the FIN before assigning the next request?  If there were a context switch between encodeData and the close() couldn't Envoy read the whole request and reassign the upstream before the close() occurs?    We may need to unit test this rather than integration test.  Alternately we could do a raw tcp connection, send the response and stray data in one write call.  I think that'd guarantee no race and I'd hope any activity on the delayed-use connection would cause it to be removed.

Comment (lizan) [reply test/integration/http_integration.cc]: The dispatcher is not running until next wait* call, so in the right next line `waitForEndSream` the dispatcher runs, the connection read 512 bytes and FIN in same event. So the request is not being scheduled before close() occurs.

Also added a unit test in conn_pool_test too.

File: source/common/http/http1/conn_pool.cc (hunk 7 above)
Comment (lizan) [reply source/common/http/http1/conn_pool.cc]: The chance of batching together is when multiple upstream connections are completing responses at same time (same epoll callback), I don't think there will will be too much work to trigger watchdog.

File: source/common/http/http1/conn_pool.cc [hunk 9]
```diff
@@ -236,7 +239,8 @@ void ConnPoolImpl::onUpstreamReady() {
 void ConnPoolImpl::processIdleClient(ActiveClient& client, bool delay) {
   client.stream_wrapper_.reset();
   if (pending_requests_.empty() || delay) {
-    // There is nothing to service so just move the connection into the ready list.
+    // There is nothing to service or delay processing is requested, so just move the connection
```
Comment (alyssawilk) [inline source/common/http/http1/conn_pool.cc]: delay -> delayed

File: test/integration/http_integration.cc (hunk 8 above)
Comment (alyssawilk) [reply test/integration/http_integration.cc]: Yeah, I'd like to think this will be fine, we've just had a spate of macos integration flakes due to slightly different network semantics.  We can just keep an eye out for test flakes and remove this if it causes problems now that we have a unit test.  @zuercher just so it's on his radar.

File: source/common/http/http1/conn_pool.cc (hunk 9 above)
Comment (lizan) [reply source/common/http/http1/conn_pool.cc]: Done

File: source/common/http/http1/conn_pool.cc [hunk 10]
```diff
@@ -209,25 +215,48 @@ void ConnPoolImpl::onResponseComplete(ActiveClient& client) {
...
-void ConnPoolImpl::processIdleClient(ActiveClient& client) {
+void ConnPoolImpl::processIdleClient(ActiveClient& client, bool delay) {
   client.stream_wrapper_.reset();
-  if (pending_requests_.empty()) {
-    // There is nothing to service so just move the connection into the ready list.
+  if (pending_requests_.empty() || delay) {
+    // There is nothing to service or delayed processing is requested, so just move the connection
+    // into the ready list.
     ENVOY_CONN_LOG(debug, "moving to ready", *client.codec_client_);
     client.moveBetweenLists(busy_clients_, ready_clients_);
```
Comment (silentdai) [inline source/common/http/http1/conn_pool.cc]: @lizan Too early to mark the client ready in this branch. Expecting anther read attempt to see if there is `EOF`. This client could be immediately used by another down stream request.
At the next cycle, dispatcher always handle write attempt first, even there is EOF in the read buffer, that is a 503 for this upstream request.

Comment (lizan) [reply source/common/http/http1/conn_pool.cc]: At the end of the upstream read event when we reach EOF the client will be removed so this is safe. https://github.com/envoyproxy/envoy/blob/v1.10.0/source/common/network/connection_impl.cc#L486
