### PR TITLE
api/config: deprecate build_version in DiscoveryRequest.

### LINKED ISSUE #9604: Mismatch of DiscoveryRequest message and transport API version
A blocking issue for https://github.com/envoyproxy/envoy/pull/9301 is that we're using the v3alpha `DiscoveryRequest` message for REST subscriptions. This is broken, since we're placing deprecated fields on the wire in #9301 (which introduces the first v2 vs. v3 distinction in the transport protocol).

We should scrub `envoy_hidden_` fields prior to sending out both gRPC and REST subscriptions discovery requests when connecting to a v3 endpoint (to avoid unknown fields), and downgrade the message to v2 when connecting to a v2 endpoint (to avoid shadow names for deprecated fields).

### PR DESCRIPTION
**Pull request by htuch**
This is a followup to #9301, where it was not possible to deprecate a
field on DiscoveryRequest as we were previously assuming identical v2/v3
transport protocols. After this deprecation, build_version can't appear
in v3 messages, and we need to convert back to a true v2
DiscoveryRequest prior to JSON serializing for REST.

There's more work to be done in the future, when we add new v3-only
fields, but this should work for 1.13.0. Future work tracked at
https://github.com/envoyproxy/envoy/issues/9619.

Risk level: Low
Testing: coverage of the behaviors for both gRPC and REST config sources
  is provided by api_version_integration_test (failing previously as soon
  as build_version was deprecated).

Fixes #9604

Signed-off-by: Harvey Tuch <htuch@google.com>

### CODE REVIEW

File: source/common/config/subscription_factory_impl.cc [hunk 1]
```diff
@@ -51,15 +51,17 @@ SubscriptionPtr SubscriptionFactoryImpl::subscriptionFromConfigSource(
           local_info_, cm_, api_config_source.cluster_names()[0], dispatcher_, random_,
           Utility::apiConfigSourceRefreshDelay(api_config_source),
           Utility::apiConfigSourceRequestTimeout(api_config_source), restMethod(type_url), type_url,
-          callbacks, stats, Utility::configSourceInitialFetchTimeout(config), validation_visitor_);
+          api_config_source.transport_api_version(), callbacks, stats,
```
Comment (yanavlasov) [inline source/common/config/subscription_factory_impl.cc]: Are there any tests that use versions other than the AUTO?

File: source/common/config/version_converter.cc [hunk 2]
```diff
@@ -40,5 +92,59 @@ DowngradedMessagePtr VersionConverter::downgrade(const Protobuf::Message& messag
...
+                              envoy::config::core::v3alpha::ApiVersion api_version) {
+  switch (api_version) {
+  case envoy::config::core::v3alpha::ApiVersion::AUTO:
+  case envoy::config::core::v3alpha::ApiVersion::V2:
+    // TODO(htuch): this works as long as there are no new fields in the v3+
+    // DiscoveryRequest. When they are added, we need to do a full v2 conversion
+    // and also discard unknown fields. Tracked at
+    // https://github.com/envoyproxy/envoy/issues/9619.
+    return downgrade(message);
+  case envoy::config::core::v3alpha::ApiVersion::V3ALPHA: {
```
Comment (yanavlasov) [inline source/common/config/version_converter.cc]: Are we planning to support V3 over REST?

File: source/common/config/version_converter.cc [hunk 3]
```diff
@@ -40,5 +92,59 @@ DowngradedMessagePtr VersionConverter::downgrade(const Protobuf::Message& messag
...
+    auto non_shadowed_message = std::make_unique<DynamicMessage>();
+    const Protobuf::Descriptor* desc = message.GetDescriptor();
+    non_shadowed_message->msg_.reset(
+        non_shadowed_message->dynamic_msg_factory_.GetPrototype(desc)->New());
+    non_shadowed_message->msg_->MergeFrom(message);
+    VersionUtil::scrubHiddenEnvoyDeprecated(*non_shadowed_message->msg_);
+    return non_shadowed_message;
+  }
+  default:
+    NOT_REACHED_GCOVR_EXCL_LINE;
```
Comment (yanavlasov) [inline source/common/config/version_converter.cc]: I wonder if this should really be RELASE_ASSERT, just in case we miss changing this function when going from V3ALPHA to V3 or V3 to V4ALPHA.

File: source/common/config/version_converter.cc [hunk 4]
```diff
@@ -1,12 +1,64 @@
...
+#include "absl/strings/match.h"
+
 namespace Envoy {
 namespace Config {
 
 namespace {
 
+// TODO(htuch): refactor these message visitor patterns into utility.cc and share with
+// MessageUtil::checkForUnexpectedFields.
+void messageFieldVisitor(std::function<void(Protobuf::Message&, const Protobuf::FieldDescriptor&,
```
[the remark this answers is not in the document]
Comment (htuch) [reply source/common/config/version_converter.cc]: How does that work? The const vs. non-const use different named accessors/mutators in the implementations. Ideally we could converge these two, but not sure how.

File: source/common/config/version_converter.cc (hunk 2 above)
Comment (htuch) [reply source/common/config/version_converter.cc]: Yes

File: source/common/config/version_converter.cc (hunk 3 above)
Comment (htuch) [reply source/common/config/version_converter.cc]: These are effectively RELEASE_ASSERTs, so I think we are good there.

File: source/common/config/subscription_factory_impl.cc (hunk 1 above)
Comment (htuch) [reply source/common/config/subscription_factory_impl.cc]: Sure, test coverage is provided by `api_version_integration_test` already, but I can fill in a few more tests here as well.

File: source/common/config/version_converter.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (yanavlasov) [reply source/common/config/version_converter.cc]: Ah yes, I was not squinting hard enough. Calls to the reflection use different methods. Never mind this comment.

File: source/common/config/subscription_factory_impl.cc (hunk 1 above)
Comment (yanavlasov) [reply source/common/config/subscription_factory_impl.cc]: Oh yes, that test. No need for additional tests, it should be enough.

File: source/common/config/grpc_mux_impl.cc [hunk 5]
```diff
@@ -62,6 +64,13 @@ void GrpcMuxImpl::sendDiscoveryRequest(const std::string& type_url) {
   if (skip_subsequent_node_ && !first_stream_request_) {
     request.clear_node();
   }
+  // TODO(htuch): this works as long as there are no new fields in the v3+
+  // DiscoveryRequest. When they are added, we need to do a full v2 conversion
+  // and also discard unknown fields. Tracked at
+  // https://github.com/envoyproxy/envoy/issues/9619.
+  if (transport_api_version_ == envoy::config::core::v3alpha::ApiVersion::V3ALPHA) {
```
Comment (mattklein123) [inline source/common/config/grpc_mux_impl.cc]: Should this potentially be != v2 instead of == v3alpha for when new versions get added? Possibly pedantic, not sure. Up to you.

File: source/common/config/grpc_mux_impl.h [hunk 6]
```diff
@@ -31,6 +31,8 @@ class GrpcMuxImpl
 public:
   GrpcMuxImpl(const LocalInfo::LocalInfo& local_info, Grpc::RawAsyncClientPtr async_client,
               Event::Dispatcher& dispatcher, const Protobuf::MethodDescriptor& service_method,
+
```
Comment (mattklein123) [inline source/common/config/grpc_mux_impl.h]: ? extra new line?

File: source/common/config/new_grpc_mux_impl.cc [hunk 7]
```diff
@@ -169,16 +172,24 @@ void NewGrpcMuxImpl::trySendDiscoveryRequests() {
...
       pausable_ack_queue_.pop();
     } else {
-      grpc_stream_.sendMessage(sub->second->sub_state_.getNextRequestAckless());
+      request = sub->second->sub_state_.getNextRequestAckless();
     }
+    // TODO(htuch): this works as long as there are no new fields in the v3+
+    // DiscoveryRequest. When they are added, we need to do a full v2 conversion
+    // and also discard unknown fields. Tracked at
+    // https://github.com/envoyproxy/envoy/issues/9619.
+    if (transport_api_version_ == envoy::config::core::v3alpha::ApiVersion::V3ALPHA) {
```
Comment (mattklein123) [inline source/common/config/new_grpc_mux_impl.cc]: Same comment.

File: source/common/config/new_grpc_mux_impl.h [hunk 8]
```diff
@@ -28,8 +28,11 @@ class NewGrpcMuxImpl
       Logger::Loggable<Logger::Id::config> {
 public:
   NewGrpcMuxImpl(Grpc::RawAsyncClientPtr&& async_client, Event::Dispatcher& dispatcher,
-                 const Protobuf::MethodDescriptor& service_method, Runtime::RandomGenerator& random,
-                 Stats::Scope& scope, const RateLimitSettings& rate_limit_settings,
+                 const Protobuf::MethodDescriptor& service_method,
+
```
Comment (mattklein123) [inline source/common/config/new_grpc_mux_impl.h]: same extra new line

File: source/common/config/version_converter.cc [hunk 9]
```diff
@@ -1,12 +1,64 @@
...
 
+#include "absl/strings/match.h"
+
 namespace Envoy {
 namespace Config {
 
 namespace {
 
+// TODO(htuch): refactor these message visitor patterns into utility.cc and share with
+// MessageUtil::checkForUnexpectedFields.
```
Comment (mattklein123) [inline source/common/config/version_converter.cc]: I had a similar comment also about the redacting stuff that @mergeconflict is working on. Can the utility be used there also if possible?

File: source/common/config/version_converter.cc [hunk 10]
```diff
@@ -40,5 +92,59 @@ DowngradedMessagePtr VersionConverter::downgrade(const Protobuf::Message& messag
...
+    NOT_REACHED_GCOVR_EXCL_LINE;
+  }
+}
+
+bool VersionUtil::hasHiddenEnvoyDeprecated(const Protobuf::Message& message) {
+  bool has_hidden = false;
+  constMessageFieldVisitor(
+      [&has_hidden](const Protobuf::Message& message, const Protobuf::FieldDescriptor& field,
+                    const Protobuf::Reflection& reflection) {
+        if (absl::StartsWith(field.name(), "hidden_envoy_deprecated_")) {
```
Comment (mattklein123) [inline source/common/config/version_converter.cc]: nit: store "hidden_envoy_deprecated_" in some const somewhere and use all the places its needed?

File: source/common/config/version_converter.h [hunk 11]
```diff
@@ -32,11 +34,37 @@ class VersionConverter {
...
+   * @param message message input.
+   * @return DynamicMessagePtr with the downgraded message (and associated
+   *         factory state).
+   */
+  static DynamicMessagePtr downgrade(const Protobuf::Message& message);
+
+  /**
+   * Reinterpret an Envoy internal API message at v3 based on a given API
+   * version. This will downgrade() to an earlier version or scrub the shadow
+   * deprecated fields in the existing one.
```
Comment (mattklein123) [inline source/common/config/version_converter.h]: sorry because I'm dense: the scrubbing here is for which case? Someone ingested v2, but we want to output v3, so we take the current converted v3, and just remove any of the hidden deprecated fields that got us here? But if we do that won't we lose context as the v3 message won't actually be accurate? I think I'm possibly just not understanding the use case.

Comment (htuch) [reply source/common/config/version_converter.h]: It's simpler than that. This is for an internal v3 proto (no ingestion), `DiscoveryRequest`. We have a deprecated field in it now, `build_version`, which has the weird mangling with `hidden_envoy_deprecated`. When we send it out on the wire, e.g. as a  v2 JSON REST message, it needs to still be around, but named with the original name, so we need to downgrade. When we send it out on the wire as v3, the field should be totally scrubbed, as it's not a valid v3 field.

File: source/common/config/grpc_mux_impl.cc (hunk 5 above)
Comment (htuch) [reply source/common/config/grpc_mux_impl.cc]: I think we need to come back to this code before too long anyway, per the tracking issue, so I think it's fine for the next short while.

File: source/common/config/version_converter.cc (hunk 9 above)
Comment (htuch) [reply source/common/config/version_converter.cc]: Probably. I need to do use this visitor in my next PR, so I reckon we can merge this as is, and I will move this to a more general location there

File: source/common/config/version_converter.cc [hunk 12]
```diff
@@ -40,5 +94,59 @@ DowngradedMessagePtr VersionConverter::downgrade(const Protobuf::Message& messag
...
+VersionConverter::reinterpret(const Protobuf::Message& message,
+                              envoy::config::core::v3alpha::ApiVersion api_version) {
+  switch (api_version) {
+  case envoy::config::core::v3alpha::ApiVersion::AUTO:
+  case envoy::config::core::v3alpha::ApiVersion::V2:
+    // TODO(htuch): this works as long as there are no new fields in the v3+
+    // DiscoveryRequest. When they are added, we need to do a full v2 conversion
+    // and also discard unknown fields. Tracked at
+    // https://github.com/envoyproxy/envoy/issues/9619.
+    return downgrade(message);
```
Comment (mattklein123) [inline source/common/config/version_converter.cc]: Sorry for being dense but I'm still a little confused around all of this. Is it possible to add some more comments throughout these functions with possibly some simple examples? If I'm downgrading from v3 -> v2, but I have a v3 message that has a smuggled deprecated field, how does that work with the serialize as string conversion? The old message doesn't know about the deprecated rename, so wouldn't we need code to actually map it back?

Comment (htuch) [reply source/common/config/version_converter.cc]: I can add some, but the key intuition is that v2/v3 actually have exactly the same fields from a proto wire perspective if we are using the v3 shadow protos. They are just different names, which proto doesn't care about on the wire.

Comment (mattklein123) [reply source/common/config/version_converter.cc]: Ah OK sorry, I saw `SerializeAsString` and I was thinking about a debug string which would have field names. We are just going back and forth with bytes. OK got it. I think some more comments would be good but feel free to do as a follow up.
