### PR TITLE
http: cap number of actions in conn_manager_impl_fuzz_test

### LINKED ISSUE #40524: Limit number of events fuzzer can generate in conn_manager_impl_fuzz_test
Test case:
[clusterfuzz-testcase-minimized-conn_manager_impl_fuzz_test-6184237135364096.txt](https://github.com/user-attachments/files/21553729/clusterfuzz-testcase-minimized-conn_manager_impl_fuzz_test-6184237135364096.txt)

Attached fuzz test case takes ~50 seconds to complete locally. Intermittently times out on oss-fuzz

Steps to reproduce:
Copy downloaded test case file into the `test/common/http/conn_manager_impl_corpus` directory and run

```
bazel build --config=asan -c dbg test/common/http/conn_manager_impl_fuzz_test
bazel-bin/test/common/http/conn_manager_impl_fuzz_test test/common/http/conn_manager_impl_corpus/clusterfuzz-testcase-minimized-conn_manager_impl_fuzz_test-6184237135364096.txt
```

### PR DESCRIPTION
**Pull request by shramanpaul**
Fixes #40524

cap number of actions in **conn_manager_impl_fuzz_test** to avoid long runtimes on pathological inputs. Process at most 1024 actions per testcase.

### **Additional Description:**

- Adds a bounded loop over input.actions() with kMaxActions = 1024.

- Mirrors limits used in other Envoy fuzzers to keep OSS-Fuzz/local runs stable.

### **Risk Level:**

- Low (test-only; no production code paths affected).

### **Testing:**

- Corpus run:

  - `bazel test //test/common/http:conn_manager_impl_fuzz_test --test_output=errors`

- Repro input timing (ASAN dbg):

  - `bazel-bin/test/common/http/conn_manager_impl_fuzz_test test/common/http/conn_manager_impl_corpus/clusterfuzz-testcase-minimized-conn_manager_impl_fuzz_test-6184237135364096.txt`
  - Completed in **~1.53s locally (previously ~50s).**

### CODE REVIEW

File: test/common/http/conn_manager_impl_fuzz_test.cc [hunk 1]
```diff
@@ -647,7 +648,11 @@ DEFINE_PROTO_FUZZER(const test::common::http::ConnManagerImplTestCase& input) {
 
   std::vector<FuzzStreamPtr> streams;
 
-  for (const auto& action : input.actions()) {
+  // Limiting the number of actions processed to avoid excessively long executions
+  constexpr int kMaxActions = 1024;
+  const int num_actions = std::min<int>(kMaxActions, input.actions_size());
+  for (int i = 0; i < num_actions; ++i) {
```
Comment (adisuissa) [inline test/common/http/conn_manager_impl_fuzz_test.cc]: nit: s/int/uint32_t/

**Review by adisuissa — COMMENTED** [review]
Thanks for your contribution, left a small nit but otherwise LGTM.

File: test/common/http/conn_manager_impl_fuzz_test.cc [hunk 2]
```diff
@@ -647,7 +648,11 @@ DEFINE_PROTO_FUZZER(const test::common::http::ConnManagerImplTestCase& input) {
 
   std::vector<FuzzStreamPtr> streams;
 
-  for (const auto& action : input.actions()) {
+  // Limiting the number of actions processed to avoid excessively long executions
+  constexpr int kMaxActions = 1024;
```
Comment (adisuissa) [inline test/common/http/conn_manager_impl_fuzz_test.cc]: Let's make it a bit bigger, say 4096, just in case.

**Comment by shramanpaul** [comment]
Hi @adisuissa 

I addressed the nits: switched counters to uint32_t and raised the cap to 4096.

Tradeoff data on the minimized testcase from #40524

- kMaxActions=1024 → ~1.53s (ASAN dbg)

- kMaxActions=4096 → ~25.4s (ASAN dbg)

Corpus-based test still passes. If you prefer a middle ground (e.g., 2048) to keep runtime lower on slower machines, I can update it, otherwise I have kept 4096 per your suggestion.

Looking forward to feedback! 🙏

**Comment by adisuissa** [comment]
> Hi @adisuissa
> 
> I addressed the nits: switched counters to uint32_t and raised the cap to 4096.
> 
> Tradeoff data on the minimized testcase from #40524
> 
> * kMaxActions=1024 → ~1.53s (ASAN dbg)
> * kMaxActions=4096 → ~25.4s (ASAN dbg)
> 
> Corpus-based test still passes. If you prefer a middle ground (e.g., 2048) to keep runtime lower on slower machines, I can update it, otherwise I have kept 4096 per your suggestion.
> 
> Looking forward to feedback! 🙏

I assume the non-linear increase is due to the actual contents of the test-case rather than the pure number.
I believe that's ok, and can be reduced further later if desired.

**Comment by shramanpaul** [comment]
> Thanks! Quick-question is the test-case in #40524 expected to be added as part of this PR?

The original issue #40524 didn’t request adding it, so I used the minimized input only for local validation to avoid bloating the corpus. Please let me know the preference and I will update the PR.
