### PR TITLE
Fix extension monitor name

### LINKED ISSUE #34932: [overload] Fix extension name of Downstream connections monitor
*Title*: *Fix extension name of the Downstream connections monitor extension*

*Description*:
There is currently a discrepancy between user docs for [Downstream connections monitor](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto#extensions-resource-monitors-downstream-connections-v3-downstreamconnectionsconfig) and the actual implementation. E.g. the docs suggest to use `envoy.resource_monitors.downstream_connections` as extension name, while implementation uses [`envoy.resource_monitors.global_downstream_max_connections` ](https://github.com/envoyproxy/envoy/blob/main/envoy/server/overload/thread_local_overload_state.h#L25C8-L25C65)to resolve the monitor. Due to this bunch of users have reported errors when configuring the extension after following to user docs:

```
[source/server/server.cc:1029] exiting
Didn't find a registered implementation for 'envoy.resource_monitors.downstream_connections' with type URL: 'envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig'
```

### PR DESCRIPTION
**Pull request by nezdolik**
Commit Message: Fix extension name in docs to match the actual implementation. Currently user docs (`envoy.resource_monitors.downstream_connections`) and implementation (`envoy.resource_monitors.global_downstream_max_connections`) don't match in terms of monitor name. Another approach would be to fix the name in the implementation and leave extension name in the docs as it is, but it would affect users who already figured out the correct full name of extension. Since the extension has already been promoted to stable the second approach may be more correct?

Additional Description:
Risk Level:
Testing: Done
Docs Changes: Done
Release Notes:
Platform Specific Features:
Fixes #34932

### CODE REVIEW

**Comment by nezdolik** [comment]
cc @KBaichoo @ravenblackx

File: source/extensions/resource_monitors/downstream_connections/config.h [hunk 1]
```diff
@@ -17,7 +17,7 @@ class ActiveDownstreamConnectionsMonitorFactory
               DownstreamConnectionsConfig> {
 public:
   ActiveDownstreamConnectionsMonitorFactory()
-      : ProactiveFactoryBase("envoy.resource_monitors.downstream_connections") {}
+      : ProactiveFactoryBase("envoy.resource_monitors.global_downstream_max_connections") {}
```
Comment (KBaichoo) [inline source/extensions/resource_monitors/downstream_connections/config.h:20]: Seems like the implementation was using `envoy.resource_monitors.downstream_connections`? Which the docs were also using?

File: api/envoy/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto [hunk 2]
```diff
@@ -12,7 +12,7 @@ option go_package = "github.com/envoyproxy/go-control-plane/envoy/extensions/res
 option (udpa.annotations.file_status).package_version_status = ACTIVE;
 
 // [#protodoc-title: Downstream connections]
-// [#extension: envoy.resource_monitors.downstream_connections]
+// [#extension: envoy.resource_monitors.global_downstream_max_connections]
```
Comment (adisuissa) [inline api/envoy/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto:15]: Just to make sure I understand this correctly, prior to this PR, if a user used `envoy.resource_monitors.global_downstream_max_connections` everything worked (but it was inconsistent with the docs).
If that's the case, then LGTM. The other way around might be more problematic, as it may break current users.

File: source/extensions/resource_monitors/downstream_connections/config.h (hunk 1 above)
Comment (nezdolik) [reply source/extensions/resource_monitors/downstream_connections/config.h:20]: @KBaichoo the resources are being instantiated in overload manager impl code, e.g. [here](https://github.com/envoyproxy/envoy/blob/main/source/server/overload_manager_impl.cc#L439) we extract resource name and check if it is a proactive type or not and based on that invoke the corresponding factory method. Basically resource name is matched against a map with [this value](https://github.com/envoyproxy/envoy/blob/main/envoy/server/overload/thread_local_overload_state.h#L24) as key.

File: api/envoy/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto (hunk 2 above)
Comment (nezdolik) [reply api/envoy/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto:15]: yes, this is the case

Comment (adisuissa) [reply api/envoy/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto:15]: Thanks!

**Review by KBaichoo — APPROVED** [review]
