### PR TITLE
quiche: support downstream using SDS

### LINKED ISSUE #15034: QuicDownstreamTransport never requests SDS certificate
*Title*: QuicDownstreamTransport never requests SDS certificate

*Description*:
I defined a transport_socket for my quic listener:
```json
         "transport_socket": {
          "name": "envoy.transport_sockets.quic",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport",
           "downstream_tls_context": {
            "common_tls_context": {
             "alpn_protocols": [
              "h2",
              "http/1.1"
             ],
             "tls_certificate_sds_secret_configs": [
              {
               "name": "kubernetes://sds-credential",
               "sds_config": {
                "ads": {},
                "resource_api_version": "V3"
               }
              }
             ]
            },
            "require_client_certificate": false
           }
          }
         }
        }
```

Secret shows up as WARMING in the config dump, but no 

*Repro steps*:
See config above

### PR DESCRIPTION
**Pull request by danzh2010**
Commit Message: Update quic server transport socket factory upon SDS updates. Add stats for SDS updates. Add checking of nullptr

Additional Description: fix UDP listener to register xDS with server init_manager.
Risk Level: low
Testing: enable downstream HTTP3 in sds_dynamic_integration_test.cc

Fixes #15034
Part of #12930 #2557

### CODE REVIEW

**Comment by alyssawilk** [comment]
I'll wait until you have CI sorted.
Since you mentioned offline this is downstream only can you add a TODO(14829) somewhere appropriate for upstream support?

File: source/common/quic/quic_transport_socket_factory.h [hunk 1]
```diff
@@ -11,44 +11,91 @@
...
   }
   bool implementsSecureTransport() const override { return true; }
   bool usesProxyProtocolOptions() const override { return false; }
+
+protected:
+  const Ssl::ContextConfig& contextConfig() const { return *context_config_; }
+  QuicTransportSocketFactoryStats stats_;
+
+private:
+  std::unique_ptr<Ssl::ContextConfig> context_config_;
```
Comment (lambdai) [inline source/common/quic/quic_transport_socket_factory.h:63]: I don't have the full picture regarding the client context. However, if you can put `context_config_` to derived  `QuicServerTransportSocketFactory` and `QuicClientTransportSocketFactory`, the dynamic cast can be eliminated.

Comment (danzh2010) [reply source/common/quic/quic_transport_socket_factory.h:63]: Actually I moved it from subclasses to the base class so that they can have the SDS update callback setup in the base class :)
Doing so is just to have the same behavior on both endpoints. Indeed it brings up the need of dynamic_cast in subclasses. I don't have strong preference for either way.

File: test/integration/sds_dynamic_integration_test.cc [hunk 2]
```diff
@@ -40,17 +46,62 @@ namespace Ssl {
...
+    for (auto grpc_type : {Grpc::ClientType::EnvoyGrpc, Grpc::ClientType::GoogleGrpc}) {
+#ifndef ENVOY_GOOGLE_GRPC
+      if (grpc_type == Grpc::ClientType::GoogleGrpc) {
+        continue;
+      }
+#endif
+
+      ret.push_back({ip_version, grpc_type, false});
+      if (test_quic) {
+#ifdef ENVOY_ENABLE_QUIC
```
Comment (alyssawilk) [inline test/integration/sds_dynamic_integration_test.cc:71]: I also think we should have one for client / upstream protocols but I can take that on, since I didn't add the correct utility over in https://github.com/envoyproxy/envoy/pull/15853/files

File: test/integration/sds_dynamic_integration_test.cc [hunk 3]
```diff
@@ -141,33 +192,43 @@ class SdsDynamicIntegrationBaseTest : public Grpc::GrpcClientIntegrationParamTes
...
   const std::string client_cert_;
   bool v3_resource_api_{false};
+  bool test_quic_;
 };
 
 // Downstream SDS integration test: static Listener with ssl cert from SDS
 class SdsDynamicDownstreamIntegrationTest : public SdsDynamicIntegrationBaseTest {
 public:
+  SdsDynamicDownstreamIntegrationTest()
+      : SdsDynamicIntegrationBaseTest((std::get<2>(GetParam()) ? Http::CodecClient::Type::HTTP3
```
Comment (alyssawilk) [inline test/integration/sds_dynamic_integration_test.cc:202]: optionally add a helper for protocol just as you did ipVersion

File: test/integration/sds_dynamic_integration_test.cc [hunk 4]
```diff
@@ -364,18 +458,21 @@ class SdsDynamicDownstreamCertValidationContextTest : public SdsDynamicDownstrea
...
+        transport_socket->set_name("envoy.transport_sockets.tls");
+        transport_socket->mutable_typed_config()->PackFrom(tls_context);
+      } else {
+        envoy::extensions::transport_sockets::quic::v3::QuicDownstreamTransport
+            transport_socket_config;
+        auto* common_tls_context =
+            transport_socket_config.mutable_downstream_tls_context()->mutable_common_tls_context();
+        configInlinedCerts(common_tls_context);
+        transport_socket->set_name("envoy.transport_sockets.quic");
+        transport_socket->mutable_typed_config()->PackFrom(transport_socket_config);
```
Comment (alyssawilk) [inline test/integration/sds_dynamic_integration_test.cc:474]: I feel like we're getting the quic vs tls stuff in a lot of places and I'd like to reduce that.  Can you think of something cleaner?  Passing in the context to a lambda and having it fill in the right one?  Setting the h2 tls context by default and having a convertIfHttp3 function which moved it over and set the correct transport socket name?

**Review by alyssawilk — COMMENTED** [review]
main merge should fix verify_examples, sorry for the breakage

File: test/integration/sds_dynamic_integration_test.cc (hunk 4 above)
Comment (danzh2010) [reply test/integration/sds_dynamic_integration_test.cc:456]: I added a utility function in ConfigHelper to distinguish ssl v.s quic.

File: test/config/utility.cc [hunk 5]
```diff
@@ -1062,6 +1062,30 @@ void ConfigHelper::setClientCodec(envoy::extensions::filters::network::http_conn
   }
 }
 
+void ConfigHelper::configDownstreamTransportSocketWitTls(
```
Comment (alyssawilk) [inline test/config/utility.cc:1065]: WitThs -> With

**Review by alyssawilk — COMMENTED** [review]
LGTM modulo that one typo.  Passing to Snow for second pass

File: test/config/utility.cc (hunk 5 above)
Comment (danzh2010) [reply test/config/utility.cc:1065]: fixed

File: source/common/quic/quic_transport_socket_factory.h [hunk 6]
```diff
@@ -11,44 +11,91 @@
...
 class QuicClientTransportSocketFactory : public QuicTransportSocketFactoryBase {
 public:
-  QuicClientTransportSocketFactory(Envoy::Ssl::ClientContextConfigPtr config)
-      : config_(std::move(config)) {}
+  QuicClientTransportSocketFactory(Stats::Scope& store, Ssl::ClientContextConfigPtr config)
+      : QuicTransportSocketFactoryBase(store, std::move(config), "client"),
+        config_(dynamic_cast<const Ssl::ClientContextConfig&>(contextConfig())) {}
 
-  const Ssl::ClientContextConfig& clientContextConfig() const { return *config_; }
+  const Ssl::ClientContextConfig& clientContextConfig() const { return config_; }
```
Comment (snowp) [inline source/common/quic/quic_transport_socket_factory.h:95]: I think an alternative way to do this would be to have this getter do 

````
ASSERT(dynamic_cast<...> != nullptr);
return static_cast<...>(contextConfig());
```

That way we avoid storing a separate ref on the derived classes while still avoiding a dynamic cast in prod builds?

File: source/common/quic/quic_transport_socket_factory.h (hunk 1 above)
Comment (snowp) [inline source/common/quic/quic_transport_socket_factory.h:63]: const

File: test/config/utility.cc [hunk 7]
```diff
@@ -1062,6 +1062,30 @@ void ConfigHelper::setClientCodec(envoy::extensions::filters::network::http_conn
...
+        fill_tls_stuff) {
+  for (auto& listener : *bootstrap.mutable_static_resources()->mutable_listeners()) {
+    ASSERT(listener.filter_chains_size() > 0);
+    auto* filter_chain = listener.mutable_filter_chains(0);
+    auto* transport_socket = filter_chain->mutable_transport_socket();
+    if (listener.has_udp_listener_config() && listener.udp_listener_config().has_quic_options()) {
+      transport_socket->set_name("envoy.transport_sockets.quic");
+      envoy::extensions::transport_sockets::quic::v3::QuicDownstreamTransport
+          quic_transport_socket_config;
+      fill_tls_stuff(*quic_transport_socket_config.mutable_downstream_tls_context()
```
Comment (snowp) [inline test/config/utility.cc:1077]: maybe make this name a bit more explicit? `configureTlsContext`?

File: test/integration/sds_dynamic_integration_test.cc [hunk 8]
```diff
@@ -40,17 +46,56 @@ namespace Ssl {
...
-                                      public HttpIntegrationTest {
+class SdsDynamicIntegrationBaseTest
+    : public Grpc::BaseGrpcClientIntegrationParamTest,
+      public HttpIntegrationTest,
+      public testing::TestWithParam<
+          std::tuple<Network::Address::IpVersion, Grpc::ClientType, bool>> {
 public:
   SdsDynamicIntegrationBaseTest()
-      : HttpIntegrationTest(Http::CodecClient::Type::HTTP1, ipVersion()),
+      : HttpIntegrationTest(Http::CodecClient::Type::HTTP1, std::get<0>(GetParam())),
```
Comment (snowp) [inline test/integration/sds_dynamic_integration_test.cc:86]: seems easier to read when this was `ipVersion()`?

File: test/integration/sds_dynamic_integration_test.cc [hunk 9]
```diff
@@ -40,17 +46,56 @@ namespace Ssl {
...
 // Sds integration base class with following support:
 // * functions to create sds upstream, and send sds response
 // * functions to create secret protobuf.
-class SdsDynamicIntegrationBaseTest : public Grpc::GrpcClientIntegrationParamTest,
-                                      public HttpIntegrationTest {
+class SdsDynamicIntegrationBaseTest
+    : public Grpc::BaseGrpcClientIntegrationParamTest,
+      public HttpIntegrationTest,
+      public testing::TestWithParam<
+          std::tuple<Network::Address::IpVersion, Grpc::ClientType, bool>> {
```
Comment (snowp) [inline test/integration/sds_dynamic_integration_test.cc:83]: Maybe document what the gRPC test parameter is used for? Also what the bool refer to

File: test/integration/sds_dynamic_integration_test.cc (hunk 4 above)
Comment (snowp) [reply test/integration/sds_dynamic_integration_test.cc:456]: Should we use the new test helper here?

**Review by snowp — CHANGES_REQUESTED** [review]
Overall looks reasonable to me, just a few suggestions/questions

File: test/integration/sds_dynamic_integration_test.cc (hunk 8 above)
Comment (danzh2010) [reply test/integration/sds_dynamic_integration_test.cc:86]: ipVersion() is a base class member. We haven't construct the base class here yet.

File: source/common/quic/quic_transport_socket_factory.h (hunk 1 above)
Comment (danzh2010) [reply source/common/quic/quic_transport_socket_factory.h]: After thinking about it more, I changed the ownership to subclasses as the client subclass may need to do extra work in the future. Thus avoiding the dynamic_cast. Thanks for pointing out the issue here!

Comment (danzh2010) [reply source/common/quic/quic_transport_socket_factory.h]: It shouldn't be const. setSecretUpdateCallback() is non-const method. But all these stuff has been moved to subclasses.

File: source/common/quic/quic_transport_socket_factory.h (hunk 6 above)
Comment (danzh2010) [reply source/common/quic/quic_transport_socket_factory.h]: see above.

File: test/config/utility.cc (hunk 7 above)
Comment (danzh2010) [reply test/config/utility.cc]: done

File: test/integration/sds_dynamic_integration_test.cc (hunk 9 above)
Comment (danzh2010) [reply test/integration/sds_dynamic_integration_test.cc]: I change the tuple to a struct. Hope it helps readability.

File: source/common/quic/quic_transport_socket_factory.h (hunk 1 above)
Comment (snowp) [reply source/common/quic/quic_transport_socket_factory.h]: I was thinking more about `const unique_ptr`, not `unique_ptr<const ...>`, since the pointer doesn't change

File: source/common/quic/quic_transport_socket_factory.h [hunk 10]
```diff
@@ -37,13 +37,12 @@ QuicTransportSocketFactoryStats generateStats(Stats::Scope& store, const std::st
...
+  QuicTransportSocketFactoryBase(Stats::Scope& store, Ssl::ContextConfig& context_config,
                                  const std::string& perspective)
-      : stats_(generateStats(store, perspective)), context_config_(std::move(config)) {
-    context_config_->setSecretUpdateCallback([this]() {
-      // The callback also triggers updating |context_config_| with the new secret.
-      // TODO(danzh) Client transport socket factory may also need to update quic crypto.
-      stats_.context_config_update_by_sds_.inc();
+      : stats_(generateStats(store, perspective)) {
+    context_config.setSecretUpdateCallback([this]() {
+      // The callback also triggers updating config_ with the new secret.
```
Comment (snowp) [inline source/common/quic/quic_transport_socket_factory.h:44]: `also updates`

File: source/common/quic/quic_transport_socket_factory.h [hunk 11]
```diff
@@ -37,13 +37,12 @@ QuicTransportSocketFactoryStats generateStats(Stats::Scope& store, const std::st
...
-  QuicTransportSocketFactoryBase(Stats::Scope& store, std::unique_ptr<Ssl::ContextConfig> config,
+  QuicTransportSocketFactoryBase(Stats::Scope& store, Ssl::ContextConfig& context_config,
                                  const std::string& perspective)
-      : stats_(generateStats(store, perspective)), context_config_(std::move(config)) {
-    context_config_->setSecretUpdateCallback([this]() {
-      // The callback also triggers updating |context_config_| with the new secret.
-      // TODO(danzh) Client transport socket factory may also need to update quic crypto.
-      stats_.context_config_update_by_sds_.inc();
+      : stats_(generateStats(store, perspective)) {
+    context_config.setSecretUpdateCallback([this]() {
```
Comment (snowp) [inline source/common/quic/quic_transport_socket_factory.h:43]: will this ever be immediately triggered? we'd call a virtual function in the ctor in that case

File: test/integration/sds_dynamic_integration_test.cc [hunk 12]
```diff
@@ -46,24 +46,27 @@ namespace Ssl {
...
-std::string sdsTestParamsToString(
-    const ::testing::TestParamInfo<std::tuple<Network::Address::IpVersion, Grpc::ClientType, bool>>&
-        p) {
-  return fmt::format(
-      "{}_{}_{}", std::get<0>(p.param) == Network::Address::IpVersion::v4 ? "IPv4" : "IPv6",
-      std::get<1>(p.param) == Grpc::ClientType::GoogleGrpc ? "GoogleGrpc" : "EnvoyGrpc",
-      std::get<2>(p.param) ? "UsesQuic" : "UsesTcp");
+struct TestParams {
+  Network::Address::IpVersion ip_version;
+  Grpc::ClientType grpc_type;
```
Comment (snowp) [inline test/integration/sds_dynamic_integration_test.cc:51]: `sds_grpc_type`? to make it clear that this relates to the SDS client, not the downstream client of the integration test

**Review by snowp — CHANGES_REQUESTED** [review]

File: source/common/quic/quic_transport_socket_factory.h (hunk 11 above)
Comment (danzh2010) [reply source/common/quic/quic_transport_socket_factory.h:43]: Yes, if triggerred in the callstack, it will call base class version of the virtual function which makes sense as the derived class hasn't use context_config to setup anything yet. Is this not desired in Envoy?

Comment (snowp) [reply source/common/quic/quic_transport_socket_factory.h:43]: https://google.github.io/styleguide/cppguide.html#Doing_Work_in_Constructors

It tends to lead to surprising behavior and is often not resilient to refactors, so I would avoid it if possible

File: test/integration/sds_dynamic_integration_test.cc (hunk 12 above)
Comment (danzh2010) [reply test/integration/sds_dynamic_integration_test.cc]: done

**Comment by danzh2010** [comment]
Ping @snowp

File: source/common/quic/quic_transport_socket_factory.h [hunk 13]
```diff
@@ -39,14 +39,11 @@ QuicTransportSocketFactoryStats generateStats(Stats::Scope& store, const std::st
...
-    context_config.setSecretUpdateCallback([this]() {
-      // The callback also triggers updating config_ with the new secret.
-      onSecretUpdated();
-    });
-  }
+  QuicTransportSocketFactoryBase(Stats::Scope& store, const std::string& perspective)
+      : stats_(generateStats(store, perspective)) {}
+
+  // To be called right after construction.
+  virtual void initialize() = 0;
```
Comment (snowp) [inline source/common/quic/quic_transport_socket_factory.h:46]: use the PURE macro

File: source/common/quic/quic_transport_socket_factory.h [hunk 14]
```diff
@@ -28,19 +53,42 @@ class QuicTransportSocketFactoryBase : public Network::TransportSocketFactory {
   bool implementsSecureTransport() const override { return true; }
   bool usesProxyProtocolOptions() const override { return false; }
   bool supportsAlpn() const override { return true; }
+
+protected:
+  virtual void onSecretUpdated() = 0;
```
Comment (snowp) [inline source/common/quic/quic_transport_socket_factory.h:58]: PURE

File: source/common/quic/quic_transport_socket_factory.h [hunk 15]
```diff
@@ -28,19 +53,42 @@ class QuicTransportSocketFactoryBase : public Network::TransportSocketFactory {
...
+
+  // Return TLS certificates if the context config is ready.
+  std::vector<std::reference_wrapper<const Envoy::Ssl::TlsCertificateConfig>>
+  getTlsCertificates() const {
+    if (!config_->isReady()) {
+      ENVOY_LOG(warn, "SDS hasn't finished updating Ssl context config yet.");
+      stats_.downstream_context_secrets_not_ready_.inc();
+      return {};
+    }
+    return config_->tlsCertificates();
```
Comment (snowp) [inline source/common/quic/quic_transport_socket_factory.h:84]: For my understanding when would this happen? Do we not block the usage of this on the SDS config being ready?

File: test/common/http/conn_pool_grid_test.cc [hunk 16]
```diff
@@ -395,11 +395,13 @@ namespace Http {
 namespace {
 
 TEST_F(ConnectivityGridTest, RealGrid) {
+  ASSERT(false);
```
Comment (snowp) [inline test/common/http/conn_pool_grid_test.cc:398]: ?

File: test/common/quic/envoy_quic_proof_source_test.cc [hunk 17]
```diff
@@ -1,5 +1,6 @@
 #include <memory>
 #include <string>
+#include <type_traits>
```
Comment (snowp) [inline test/common/quic/envoy_quic_proof_source_test.cc:3]: I don't see anything from type_traits being introduced in this PR, can this be removed?

File: test/integration/sds_dynamic_integration_test.cc [hunk 18]
```diff
@@ -179,29 +223,71 @@ class SdsDynamicDownstreamIntegrationTest : public SdsDynamicIntegrationBaseTest
     client_ssl_ctx_ = createClientSslTransportSocketFactory({}, context_manager_, *api_);
   }
 
+  void configToUseSds(
+      envoy::extensions::transport_sockets::tls::v3::CommonTlsContext& common_tls_context) {
+    common_tls_context.add_alpn_protocols(downstream_protocol_ == Http::CodecClient::Type::HTTP1
+                                              ? Http::Utility::AlpnNames::get().Http11
+                                              : Http::Utility::AlpnNames::get().Http3);
```
Comment (snowp) [inline test/integration/sds_dynamic_integration_test.cc:230]: Should this use `test_quic` instead? I think this logic just matches the logic above that uses `test_quic`? Not clear without that why we do this remapping

File: test/integration/sds_dynamic_integration_test.cc [hunk 19]
```diff
@@ -179,29 +223,71 @@ class SdsDynamicDownstreamIntegrationTest : public SdsDynamicIntegrationBaseTest
...
   void createUpstreams() override {
     create_xds_upstream_ = true;
     HttpIntegrationTest::createUpstreams();
   }
 
+  void waitForSdsUpdateStats(size_t times) {
+    test_server_->waitForCounterGe(
+        listenerStatPrefix(test_quic_
+                               ? "quic_server_transport_socket_factory.context_config_update_by_sds"
+                               : "server_ssl_socket_factory.ssl_context_update_by_sds"),
```
Comment (snowp) [inline test/integration/sds_dynamic_integration_test.cc:251]: This makes me wonder whether the stats name should match? ie make the stat introduced in this PR `ssl_context_update_by_sds`? Or does that not fit well with the quic naming of things?

File: test/integration/sds_dynamic_integration_test.cc [hunk 20]
```diff
@@ -408,6 +475,18 @@ class SdsDynamicDownstreamCertValidationContextTest : public SdsDynamicDownstrea
     client_ssl_ctx_ = createClientSslTransportSocketFactory({}, context_manager_, *api_);
   }
 
+  void configInlinedCerts(
```
Comment (snowp) [inline test/integration/sds_dynamic_integration_test.cc:478]: nit `config` -> `configure`

File: test/integration/sds_dynamic_integration_test.cc [hunk 21]
```diff
@@ -408,6 +475,18 @@ class SdsDynamicDownstreamCertValidationContextTest : public SdsDynamicDownstrea
...
+      envoy::extensions::transport_sockets::tls::v3::CommonTlsContext* common_tls_context) {
+    common_tls_context->add_alpn_protocols(Http::Utility::AlpnNames::get().Http11);
```
Comment (snowp) [inline test/integration/sds_dynamic_integration_test.cc:480]: Maybe pull this out or rename function to make it clear that we're also setting the ALPN?

**Review by snowp — CHANGES_REQUESTED** [review]
Thanks this is looking pretty good! A few more comments

File: source/common/quic/quic_transport_socket_factory.h (hunk 13 above)
Comment (danzh2010) [reply source/common/quic/quic_transport_socket_factory.h:46]: done

File: source/common/quic/quic_transport_socket_factory.h (hunk 14 above)
Comment (danzh2010) [reply source/common/quic/quic_transport_socket_factory.h:58]: done

File: test/common/http/conn_pool_grid_test.cc (hunk 16 above)
Comment (danzh2010) [reply test/common/http/conn_pool_grid_test.cc:398]: debug log. Removed.

File: test/common/quic/envoy_quic_proof_source_test.cc (hunk 17 above)
Comment (danzh2010) [reply test/common/quic/envoy_quic_proof_source_test.cc:3]: removed

File: source/common/quic/quic_transport_socket_factory.h (hunk 15 above)
Comment (danzh2010) [reply source/common/quic/quic_transport_socket_factory.h:84]: I think we do block. But I saw similar logic in SSL socket to create a dummy socket so might as well added this.

File: test/integration/sds_dynamic_integration_test.cc (hunk 18 above)
Comment (danzh2010) [reply test/integration/sds_dynamic_integration_test.cc:230]: Yes, test_quic_ and downstream_protocol_ are consistent. Switched to use test_quic_ as other places in this test do.

File: test/integration/sds_dynamic_integration_test.cc (hunk 19 above)
Comment (danzh2010) [reply test/integration/sds_dynamic_integration_test.cc:251]: ssl_context is a SslSocket thing. Quic transport socket factory uses its config directly instead of generating an ssl_context object. So I think use ssl_context in the stats name is confusing.

File: test/integration/sds_dynamic_integration_test.cc (hunk 20 above)
Comment (danzh2010) [reply test/integration/sds_dynamic_integration_test.cc:478]: done

File: test/integration/sds_dynamic_integration_test.cc (hunk 21 above)
Comment (danzh2010) [reply test/integration/sds_dynamic_integration_test.cc:480]: moved it out.

**Review by snowp — APPROVED** [review]
LGTM! I see @antoniovicente assigned himself so I'll let him take a look as well

**Comment by antoniovicente** [comment]
> LGTM! I see @antoniovicente assigned himself so I'll let him take a look as well

I mostly added myself as a reviewer due to Alyssa being OOO this week.  I did a quick pass and think that the changes in this PR look good.

**Review by antoniovicente — APPROVED** [review]
