### PR TITLE
http/1.1 codec: Rejects requests w/ invalid HTTP header values

### LINKED ISSUE #7061: Malformed HTTP headers cause Envoy to 503 when proxying via HTTP/2
*Title*: 
When making client requests that contain invalid chars in an HTTP header to an Envoy instance ("envoy-one") that's configured to proxy over H/2 to an upstream Envoy ("envoy-two"), we see envoy-one return a 503 response with response flags "UR", without proxying the request to “envoy-two”.  If we change the Envoy ←→ Envoy communication to use HTTP/1.1, we don’t see this behavior, and the request is happily proxied to the upstream Envoy.

*Description*:
While investigating some strange errors we were seeing in one of our applications, I wrote a quick test harness, so that I could make requests that contained invalid ASCII chars in HTTP headers.

The “invalid ASCII chars” are defined by the relevant RFC specs [0] [1].  In this specific test case, I inserted an ASCII control char (ASCII value 31, or `0x1F`) into an HTTP header value and executed that request against our stack (Envoy → Envoy → application).

*Relevant Links*:
[0] https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
[1]  https://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2

I saw that this would generate a 503 from the first Envoy before the request ever reaches our application, since it sits upstream of the second Envoy.

*Repro steps*:
The repro config and necessary files are located in a github repo: https://github.com/dcarney/envoy-repro

Reproing this scenario involves setting up the following topography:
diagram

I have the HTTP request saved in the `request.txt` file.  It includes the HTTP header value with an invalid ASCII control character, along with other random characters.

The included Docker Compose file sets up the following:
- envoy-one
  - a listener on port :10001
  - a cluster configured to use HTTP/2
  - all traffic from the listener is sent to cluster “envoy-two” on port :10002
- envoy-two
  - a listener on port :10002
  - a cluster configured to point to https://www.google.com (The actual upstream is irrelevant, as we’ll see)

Each envoy has its listener port and admin port mounted to the host, and the two Envoys are able to reach each other over the Docker network “envoytest”.

Build the two Envoy containers, and start everything up with:
```
$ docker build -t envoy:one -f Dockerfile.one .
$ docker build -t envoy:two -f Dockerfile.two .
$ docker-compose up
```

In another terminal, run the following, in order to make the HTTP request to the first Envoy (“envoy-one”):

```
$ cat request.txt | nc -n -i 127.0.0.1:10001
```

You should see the 503 response, which is emitted by the first Envoy (“envoy-one”):

```
HTTP/1.1 503 Service Unavailable
content-length: 85
content-type: text/plain
date: Wed, 22 May 2019 20:43:43 GMT
server: envoy

upstream connect error or disconnect/reset before headers. reset reason: remote reset%
```

Envoy access logs for the “client Envoy” (envoy-one) show that the “response flags” for this request are “UR”, which according to the Envoy docs means:

> UR: Upstream remote reset in addition to 503 response code.

We can change the connection between “envoy-one” and “envoy-two” to use HTTP/1.1, by removing line 43-45 in `envoy-one.yaml`:
```
35   clusters:
...
40     dns_lookup_family: V4_ONLY
41     lb_policy: ROUND_ROBIN
42     tls_context:
43     http2_protocol_options: 
44       hpack_table_size:
45       max_concurrent_streams:
46     load_assignment:
47       cluster_name: service_foobar
```

If we re-build the containers, restart the Docker Compose topology, and execute the request again, we find that we now get a 404 response from https://www.google.com/foo, which is what we expect when the request is successfully proxied through both Envoys.

I've included packet captures from `tcpdump` from both Envoys in the repo (`envoy-{one,two}.pcap`).  Looking at them in Wireshark clearly shows the upstream Envoy resetting the stream because of a "protocol error":

Screen Shot 2019-05-23 at 9 36 28 AM

Similarly, in the [trace logs](https://github.com/dcarney/envoy-repro/blob/e19b4b450728a91c2cd15a233283ad0f0db9fdf4/trace.log), we see this message from the "client Envoy":
```
envoy-one_1 [2019-05-23 16:31:36.076][11][debug][router] [source/common/router/router.cc:676] [C0][S8542315413287350126] upstream reset: reset reason remote reset
```

And this message from the upstream Envoy:
```
envoy-two_1 [2019-05-23 16:31:36.074][11][debug][http2] [source/common/http/http2/codec_impl.cc:539] [C0] invalid frame: Invalid HTTP header field was received on stream 1
```

I would _expect_ that the client Envoy would return a 400 error, rather than constructing an H/2 request that fails to parse in the upstream Envoy.

*Config*:
[envoy-one config](https://github.com/dcarney/envoy-repro/blob/e19b4b450728a91c2cd15a233283ad0f0db9fdf4/envoy-one.yaml)
[envoy-two config](https://github.com/dcarney/envoy-repro/blob/e19b4b450728a91c2cd15a233283ad0f0db9fdf4/envoy-two.yaml)

*Logs*:
[trace logs from both Envoys](https://github.com/dcarney/envoy-repro/blob/e19b4b450728a91c2cd15a233283ad0f0db9fdf4/trace.log)

I'm happy to provide any more details you might need.  Thanks for looking!

### PR DESCRIPTION
**Pull request by dcarney**
**Description:**
This PR addresses the behavior described in #7061 by modifying the HTTP/1.1 codec, such that it verifies the value of each HTTP header when `onHeaderValue` is called. The codec raises an exception, which results in a 400 response being returned if an invalid header value (per [RFC 7230, section 3.2](https://tools.ietf.org/html/rfc7230#section-3.2)) is found.  The actual validation is done via the [nghttp2_check_header_value](https://nghttp2.org/documentation/nghttp2_check_header_value.html) function, which is wrapped in `Envoy::Http::HeaderUtility::headerIsValid`.

(NOTE: this [has been discussed](https://github.com/nghttp2/nghttp2/issues/641) as something that `nghttp2` could do itself, but the issue seems to have languished.  Also note that Go handles this: Go uses the [httpguts.ValidHeaderFieldValue function](https://godoc.org/golang.org/x/net/http/httpguts#ValidHeaderFieldValue) (which is analogous to `nghttp2_check_header_value`) to ensure that all the HTTP header values conform to the relevant RFC specs before an http.Transport instance will [round-trip the request](https://github.com/golang/go/blob/2165452a37b156d154a6e2dc85495b23a4a61565/src/net/http/transport.go#L482-L493).

**Risk Level:**
Low/medium

This stricter validation semantics are controlled with the `envoy.reloadable_features.validate_header_values` runtime-guarded feature.  Originally, the PR used a new boolean on the HTTP connection manager proto to toggle the behavior, but [during the course of PR review, it was decided](https://github.com/envoyproxy/envoy/pull/7306#discussion_r295493188) that this would be more appropriate for a runtime guard.

**Testing:**
Unit tests were added to cover both the `HeaderUtility` changes as well as the HTTP codec changes.  Manual testing against an Envoy build made from this PR's branch was performed using the repro steps decribed in #7061.  During the manual testing, the "client Envoy" (or "envoy-one") returned a 400 as expected, rather than exhibiting the behavior described in the issue:

```
# run a newly-compiled envoy with an HTTP/1.1 listener 
# (on port :10001) and an H/2 upstream cluster

$ ./envoy-static -c config.yaml -l trace 2>&1                                               

# make the request with the invalid HTTP header(s):

$ cat invalid_request.txt | nc -n -i 1 127.0.0.1 10001      
HTTP/1.1 503 Service Unavailable
content-length: 85
content-type: text/plain
date: Thu, 11 Jul 2019 02:25:36 GMT
server: envoy

upstream connect error or disconnect/reset before headers. reset reason: remote reset%

# enable the new runtime feature to cause stricter header validation

$ curl --silent -X POST http://localhost:9901/runtime_modify\?envoy.reloadable_features.validate_header_values\=true
OK

# make the request with the invalid HTTP header(s) again:

$ cat invalid_request.txt | nc -n -i 1 127.0.0.1 10001 
HTTP/1.1 400 Bad Request
content-length: 0
connection: close
```

Success!

**Docs Changes:**

Release Notes: Updated
Fixes #7061

### CODE REVIEW

File: source/common/http/header_utility.cc [hunk 1]
```diff
@@ -117,6 +118,27 @@ bool HeaderUtility::matchHeaders(const Http::HeaderMap& request_headers,
...
 }
 
+bool HeaderUtility::validateHeaders(const Http::HeaderMap& headers) {
+  bool headers_are_valid = true;
+
+  headers.iterate(
+      [](const Http::HeaderEntry& header, void* context) -> Http::HeaderMap::Iterate {
+        const absl::string_view header_value = header.value().getStringView();
+        if (nghttp2_check_header_value(
+                reinterpret_cast<const uint8_t*>(std::string(header_value).data()),
```
Comment (snowp) [inline source/common/http/header_utility.cc]: Can you call .data on the string_view directly to avoid a temporary std::string?

File: api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto [hunk 2]
```diff
@@ -424,6 +424,12 @@ message HttpConnectionManager {
   // Note that Envoy does not perform
   // `case normalization <https://tools.ietf.org/html/rfc3986#section-6.2.2.1>`
   google.protobuf.BoolValue normalize_path = 30;
+
+  // If present and set to true, the connection manager will validate the values of each HTTP
+  // header, returning a 400 response if any of the headers contain an invalid
+  // value. See `Header Fields `<https://tools.ietf.org/html/rfc7230#section-3.2>`_
+  // for details.
+  google.protobuf.BoolValue validate_headers = 33;
```
Comment (snowp) [inline api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: Normally we use the POD boolean type when the default is false

Comment (dcarney) [reply api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: Sure, sounds good to me.  I think I had been looking at some [other fields on the conn manager](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-msg-config-filter-network-http-connection-manager-v2-httpconnectionmanager) like `add_user_agent`, which uses the proto wrapper type, but defaults to false.

File: source/common/http/conn_manager_impl.cc [hunk 3]
```diff
@@ -598,6 +599,17 @@ void ConnectionManagerImpl::ActiveStream::decodeHeaders(HeaderMapPtr&& headers,
   // called with end_stream=true.
   maybeEndDecode(end_stream);
 
+  if (connection_manager_.config_.validateHeaders()) {
+    ENVOY_STREAM_LOG(trace, "validating header values\n{}", *this, *request_headers_);
+    if (!Http::HeaderUtility::validateHeaders(*request_headers_)) {
```
Comment (rgs1) [inline source/common/http/conn_manager_impl.cc]: should we bump a stat here? might be useful

**Comment by dcarney** [comment]
@snowp Thanks for the feedback!  I addressed your comments, and CI is sorted out now.

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (snowp) [reply source/common/http/conn_manager_impl.cc]: +1

**Comment by snowp** [comment]
LGTM, though a stat would be nice. @alyssawilk do you wanna take a look?

File: api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto [hunk 4]
```diff
@@ -424,6 +424,12 @@ message HttpConnectionManager {
   // Note that Envoy does not perform
   // `case normalization <https://tools.ietf.org/html/rfc3986#section-6.2.2.1>`
   google.protobuf.BoolValue normalize_path = 30;
+
+  // If present and set to true, the connection manager will validate the values of each HTTP
+  // header, returning a 400 response if any of the headers contain an invalid
+  // value. See `Header Fields <https://tools.ietf.org/html/rfc7230#section-3.2>`
+  // for more details regarding the validity of HTTP headers.
+  bool validate_headers = 33;
```
Comment (alyssawilk) [inline api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: We can sanity check with @mattklein123 , but if this is making Envoy more standards compliant I'd lean towards making it a permanent change (off by default, and then see if on by default works for people)

If so I think instead of making changes to the Envoy API, we should just runtime guard per
https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#runtime-guarding

File: docs/root/intro/version_history.rst [hunk 5]
```diff
@@ -30,6 +30,7 @@ Version history
 * http: mitigated a race condition with the :ref:`delayed_close_timeout<envoy_api_field_config.filter.network.http_connection_manager.v2.HttpConnectionManager.delayed_close_timeout>` where it could trigger while actively flushing a pending write buffer for a downstream connection.
 * http: added support for :ref:`preserve_external_request_id<envoy_api_field_config.filter.network.http_connection_manager.v2.HttpConnectionManager.preserve_external_request_id>` that represents whether the x-request-id should not be reset on edge entry inside mesh
 * http: changed `sendLocalReply` to send percent-encoded `GrpcMessage`.
+* http: added support for rejecting requests containing invalid HTTP header values.
```
Comment (alyssawilk) [inline docs/root/intro/version_history.rst]: So if we leave this in, we should reference the config field.  If we runtime guard let's mention the string we guard it with.

File: include/envoy/stream_info/stream_info.h [hunk 6]
```diff
@@ -128,6 +128,8 @@ struct ResponseCodeDetailValues {
   // indicates that original "success" headers may have been sent downstream
   // despite the subsequent failure.
   const std::string LateUpstreamReset = "upstream_reset_after_response_started";
+  // The request was rejected due to invalid HTTP headers
```
Comment (alyssawilk) [inline include/envoy/stream_info/stream_info.h]: Specifically, the headers had invalid characters, yes?  If so let's be as specific as possible here and below

File: source/common/http/conn_manager_impl.cc [hunk 7]
```diff
@@ -598,6 +599,17 @@ void ConnectionManagerImpl::ActiveStream::decodeHeaders(HeaderMapPtr&& headers,
   // called with end_stream=true.
   maybeEndDecode(end_stream);
 
+  if (connection_manager_.config_.validateHeaders()) {
```
Comment (alyssawilk) [inline source/common/http/conn_manager_impl.cc]: I do just want to call out this solves your problem because your client is using HTTP/1.  If they use HTTP/2 with invalid characters, nghttp2 would reject the request before we got to the HCM decodeHeaders call.
I still think it's a good change, I just want to make sure the limitations are on your radar :-)

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (alyssawilk) [inline source/common/http/conn_manager_impl.cc]: From a perf perspective, this ends up being a full redundant header scan for HTTP/2 as nghttp2 has already validated headers at this point.  It might be worth moving this check in the HTTP/1 codec (maybe even doing onHeaderValue? rather than once at the end) and we could ASSERT that all characters are valid so that as we add more transports (QUIC etc.) we have consistent behavior.

File: api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto (hunk 4 above)
Comment (mattklein123) [reply api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: runtime guard for this SGTM :+1:

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc]: +1

File: api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto (hunk 4 above)
Comment (dcarney) [reply api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto]: Okay.  Just so I understand correctly, we'd be making this new behavior:

- a runtime-guarded option _only_, and removing the option it from the connection manager proto, as I have it currently.
- off by default

I'm basing that on the comments in [the original issue](https://github.com/envoyproxy/envoy/issues/7061) about making it opt-in.

I was a little confused by this verbiage from [the runtime guarding docs](https://github.com/envoyproxy/envoy/blob/5ee70cb19ca3bb6d817bae497b63c2a250d2d16b/CONTRIBUTING.md#runtime-guarding):
> Generally all runtime guarded features will be set true when a release is cut)

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (dcarney) [reply source/common/http/conn_manager_impl.cc]: @alyssawilk If I do it in the http/1.1 codec, it seems to make sense to handle it similarly to [this code](https://github.com/envoyproxy/envoy/blob/5ee70cb19ca3bb6d817bae497b63c2a250d2d16b/source/common/http/http1/codec_impl.cc#L424-L430), which is doing similar albeit more limited, header value checking (it even references the same RFC section!)

Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc]: Yeah, I think with the runtime guard false, it does the old thing, and with the runtime guard true, it does your new thing.
runtime starts out false, we flip it with the release, and then remove old code the following release.
If there's any docs clean up which would make that more clear in future feel free to include it in this PR (with my thanks)

**Comment by dcarney** [comment]
Update on this PR: I talked with @alyssawilk on Slack about some of the integration test failures I'd been seeing with the runtime guarding (thanks a ton Alyssa!).  

The TL;DR is that the runtime guarding has issues in certain integration tests due to its reliance on thread-local storage (which isn't available in all integration test threads, depending on the objects which are trying to use the runtime impl).  

We came up with a workaround approach which will allow this PR to make forward progress, and the runtime/thread-local stuff (and some docs improvements) can be sorted out in another PR.  I've got the implementation working correctly using the runtime guarding and incorporating the other PR feedback.  Now I just need to thread things through correctly in the integration tests.  👍

File: source/common/http/codec_client.cc [hunk 8]
```diff
@@ -136,11 +136,12 @@ void CodecClient::onData(Buffer::Instance& data) {
 
 CodecClientProd::CodecClientProd(Type type, Network::ClientConnectionPtr&& connection,
                                  Upstream::HostDescriptionConstSharedPtr host,
-                                 Event::Dispatcher& dispatcher)
+                                 Event::Dispatcher& dispatcher, bool validate_header_values)
```
Comment (alyssawilk) [inline source/common/http/codec_client.cc]: maybe strict_header_validation?
since we were validating a bit before, just not much

File: source/common/http/http1/codec_impl.cc [hunk 9]
```diff
@@ -421,14 +426,26 @@ void ConnectionImpl::onHeaderValue(const char* data, size_t length) {
...
   // http-parser should filter for this
   // (https://tools.ietf.org/html/rfc7230#section-3.2.6), but it doesn't today. HeaderStrings
   // have an invariant that they must not contain embedded zero characters
   // (NUL, ASCII 0x0).
-  if (absl::string_view(data, length).find('\0') != absl::string_view::npos) {
+  if (header_value.find('\0') != absl::string_view::npos) {
     throw CodecProtocolException("http/1.1 protocol error: header value contains NUL");
   }
 
+  if (validate_headers_) {
```
Comment (alyssawilk) [inline source/common/http/http1/codec_impl.cc]: I think this can be an if-else with the above clause, since I think headerIsValid should catch the '\0'
Can you check?  It'd mean that when we remove the old code path we can remove the extra header scan without worrying about a change in functionality

File: source/common/http/http1/codec_impl.cc [hunk 10]
```diff
@@ -664,8 +688,13 @@ void ServerConnectionImpl::onBelowLowWatermark() {
   }
 }
 
-ClientConnectionImpl::ClientConnectionImpl(Network::Connection& connection, ConnectionCallbacks&)
-    : ConnectionImpl(connection, HTTP_RESPONSE, MAX_RESPONSE_HEADERS_KB) {}
+ClientConnectionImpl::ClientConnectionImpl(Network::Connection& connection,
```
Comment (alyssawilk) [inline source/common/http/http1/codec_impl.cc]: Any reason to not just remove the old constructor and default validate_header_values to false?

Though now that I think about it, I think we'd be better off only having the new constructor and not having a default value.  If we force all callers to pick a boolean we won't miss any code sites using the new code path.

It will probably mean tweaking a bunch of unit tests (you can set them all true) but hopefully you can search and replace there

File: source/common/http/http1/codec_impl.h [hunk 11]
```diff
@@ -292,6 +296,10 @@ class ServerConnectionImpl : public ServerConnection, public ConnectionImpl {
   ServerConnectionImpl(Network::Connection& connection, ServerConnectionCallbacks& callbacks,
                        Http1Settings settings, uint32_t max_request_headers_kb);
 
+  ServerConnectionImpl(Network::Connection& connection, ServerConnectionCallbacks& callbacks,
```
Comment (alyssawilk) [inline source/common/http/http1/codec_impl.h]: Ditto here, regarding the new constructor

File: source/common/upstream/health_checker_impl.cc [hunk 12]
```diff
@@ -336,7 +336,7 @@ Http::CodecClient::Type HttpHealthCheckerImpl::codecClientType(bool use_http2) {
 Http::CodecClient*
 ProdHttpHealthCheckerImpl::createCodecClient(Upstream::Host::CreateConnectionData& data) {
```
Comment (alyssawilk) [inline source/common/upstream/health_checker_impl.cc]: I'd be inclined to snag the runtime value here too, so when we've flipped the default we can remove the old code path and always do full sanitization

File: source/common/http/http1/codec_impl.cc (hunk 9 above)
Comment (dcarney) [reply source/common/http/http1/codec_impl.cc]: Yep, the `HeaderUtility::headerIsValid` function will catch the `\0` char, along with any other ASCII char with decimal value [0-31] (with the exception of decimal value 9, which is allowed per the RFC).

File: source/common/http/http1/codec_impl.cc (hunk 10 above)
Comment (dcarney) [reply source/common/http/http1/codec_impl.cc]: The main reason I hadn't done that was the pervasiveness of the change: it involves a _bunch_ of find/replace that really blew up the diff for the PR.  (Due to the fact that it involves changing `ServerConnectionImpl`, `ClientConnectionImpl`, `CodecClient`/`CodecClientProd`, `ConnectionManagerConfig`, and associated mocks, unit tests, and call sites.

If you think that much code churn is warranted though, I can certainly do that, and make all the callers default to `false` (and default the unit test callers to `true`). I know originally we had talked about an overloaded constructor like the one included here, which didn't lead to nearly as much churn.

Comment (alyssawilk) [reply source/common/http/http1/codec_impl.cc]: Yeah, that's actually a fair point about code churn given we'd want to go back to the single argument once we flip this to true and deprecate.

Do you feel confident from grepping around that you have all the call sites under source/...?  If not, how about a hacked local version with a RELEASE_ASSERT in the old constructors to make sure we didn't miss any, and we'll call it a day?

File: docs/root/intro/version_history.rst (hunk 5 above)
Comment (alyssawilk) [reply docs/root/intro/version_history.rst]: Oops, I think we now have two release notes - how about removing this one since I think the upper one is correct?

Comment (alyssawilk) [reply docs/root/intro/version_history.rst]: actually this file looks odd in general - there seem to be a bunch of deltas which aren't yours.  Bad merge?

File: source/common/http/codec_client.cc (hunk 8 above)
Comment (alyssawilk) [reply source/common/http/codec_client.cc]: Hm, or maybe I'm pinging when you're not ready for me to take another pass.  Let me know when I should take a look?  :-)

Comment (dcarney) [reply source/common/http/codec_client.cc]: Sure, I think `strict_header_validation` is a slightly more accurate description of what's going on.  

`validate_header_values` is consistent with the runtime feature name, and all the other parameters/contructor args however.  Do you think I should find/replace them all, so we standardize on `strict_header_validation`?

Comment (alyssawilk) [reply source/common/http/codec_client.cc]: That'd be great, if you're up for it.

**Comment by alyssawilk** [comment]
Oh also, can you do a master merge, and move your release note to 1.12.0?  Thanks!

File: source/common/http/codec_client.cc (hunk 8 above)
Comment (dcarney) [reply source/common/http/codec_client.cc]: Did a PR-wide `s/validate_header_values/strict_header_validation/`

**Comment by dcarney** [comment]
@alyssawilk Just rebased against the latest `master` and moved the release note to 1.12.0.  Looks like I'm just missing that 1.11.0 train!

File: source/common/http/http1/codec_impl.cc (hunk 10 above)
Comment (dcarney) [reply source/common/http/http1/codec_impl.cc]: Yep, I added `RELEASE_ASSERT(false, "");` to the `{Client,Server}ConnectionImpl` constructors and ran Envoy to perform the steps outlined in the PR description (in the "testing" section).  Worked great.

File: source/common/upstream/health_checker_impl.cc (hunk 12 above)
Comment (alyssawilk) [reply source/common/upstream/health_checker_impl.cc]: I think you did this in the wrong block, for the gRPC health checker (always H2) rather than than here where it can be 1/1

Other than that, LGTM.
@snowp any other thoughts on your end?

Comment (dcarney-stripe) [reply source/common/upstream/health_checker_impl.cc]: @alyssawilk Good catch!  Just fixed that.
