### PR TITLE
upstream: fix bug causing hosts to be dropped

### LINKED ISSUE #4473: Changing endpoint priority causes Envoy to lose track of the endpoint
*Title*: *Changing endpoint priority causes Envoy to lose track of the endpoint*

*Description*:
When moving an endpoint to a new priority, Envoy loses track of that endpoint.

Example before and after eds config:

Before:
```
resources:
- "@type": type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: service1
  endpoints:
  - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: {{service1_1_ip}}
              port_value: 80
      - endpoint:
          address:
            socket_address:
              address: {{service1_2_ip}}
              port_value: 80
```

After:
```
resources:
- "@type": type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: service1
  endpoints:
  - priority: 0
    lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: {{service1_1_ip}}
              port_value: 80
  - priority: 1
    lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: {{service1_2_ip}}
              port_value: 80
```

Envoy will no longer know about `{{service1_2_ip}}`

*Repro steps*:
I've created a repro here: https://github.com/bplotnick/envoy_examples/tree/master/losing_endpoints

CC: @mpuncel and @snowp who dealt with something similar in #3930

### PR DESCRIPTION
**Pull request by snowp**
Previously when a host was moved from an existing priority to a new
priority, the update would not cause a host update, causing the host to
essentially disappear. This was happening because the code would
determine that it knew about the host already (it existed in another
priority), but due to a lack of distinction between whether the
existing host came from the same priority (should not trigger an update)
or another (should trigger another) it would not update the host list when 
the only new host came from another priority, leaving it empty.

The fix involves comparing the list of hosts for the current
priority with the list of hosts matched to an existing host. By being in
the list of existing hosts, the hosts must either exist in the current
priority or another. By comparing these lists we can determine whether
the matched host came from a different priority, in which case we mark
the host list as changed.

Signed-off-by: Snow Pettersen <snowp@squareup.com>

*Risk Level*: Medium, changes host update behavior
*Testing*: Added regression test
*Docs Changes*: n/a
*Release Notes*: n/a
Fixes #4473

### CODE REVIEW

File: source/common/upstream/upstream_impl.cc [hunk 1]
```diff
@@ -1004,13 +1004,22 @@ bool BaseDynamicClusterImpl::updateDynamicHostList(
...
-                                                return existing_hosts_for_current_priority.count(
-                                                    host->address()->asString());
-                                              }),
-                               current_priority_hosts.end());
+  for (auto itr = current_priority_hosts.begin(); itr != current_priority_hosts.end();) {
+    auto existing_itr = existing_hosts_for_current_priority.find((*itr)->address()->asString());
+
+    if (existing_itr != existing_hosts_for_current_priority.end()) {
+      existing_hosts_for_current_priority.erase(existing_itr);
+      current_priority_hosts.erase(itr);
```
Comment (htuch) [inline source/common/upstream/upstream_impl.cc]: In this branch, how does `itr` advance after the erase?

Comment (htuch) [inline source/common/upstream/upstream_impl.cc]: Why do we need to erase from `current_priority_hosts`?

Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: In this function we loop over all the new hosts (hosts in the config update) and attempt to match them against existing hosts in `all_hosts` (map of address -> host for all hosts for the cluster prior to this update). We keep track of the ones we find in `existing_hosts_for_current_priority` and in this loop we remove the hosts that we've already accounted for from `current_priority_hosts`. The remaining hosts in `current_priority_hosts` are ones that have been removed from this priority. Note that this bit didn't change in this PR, I've only added the part where we set `hosts_changed`.

Thinking about it some, it might be simpler if we pass `current_priority_hosts` as an `unordered_map` (we already make a copy, so converting probably won't be that bad?) and then delete from the map inline instead of keeping track of `existing_hosts_for_current_priority`. Does that sound reasonable?

Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: It would also get rid of all these O(n) deletions, which would be nice

Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: After reading the docs more thoroughly I'm surprised this even works, sounds like `itr` should be invalidated when I call erase. Might be that it happens to work because the iterator is pointing to the same index as before the deletion, which becomes the index of the next element after it gets shuffled down 

Seems like what I should be doing is setting `itr` to the return value of `erase`

Comment (snowp) [reply source/common/upstream/upstream_impl.cc]: Looking into implementing my suggestion it's a bit more involved to get right than I originally thought (this part of the code is still pretty complicated).

Might make more sense to get this merged to fix the bug, then revisit it at a later time to refactor if it's useful.
