### PR TITLE
tracing: don't sample requests classified as a health check

### LINKED ISSUE #3569: tracing: Health check filter only prevents sampling of root span
*Description*:

When the health check filter is used, any invocation that matches the health check path causes the root span to not be sampled, but the sampled flag is not be propagated to subsequent services. The subsequent services (or child spans) should also not be sampled.

*Repro steps*:

* Change to the `examples/jaeger-tracing` folder
* Edit the `front-envoy-jaeger.yaml` to update the `http_filter` to be:
```
          http_filters:
          - name: envoy.health_check
            config:
              endpoint: "/trace/1"
              pass_through_mode: true
          - name: envoy.router
            config:
               start_child_span: true
```
* Start the example using `docker-compose up --build -d`
* Send a request using `curl -v localhost:8000/trace/1`
* Access the Jaeger UI at endpoint `http://localhost:16686`
You should see a single trace, which when selected will show something like:
envoy-hc-traced

The root span has not been reported due to the classification as a health check, but the sampled status has not been passed to the child span created in the proxy, or on to the subsequent `service1`, etc.

The same applies if the `start_child_span` is false, the spans for `service1` and `service2` are created - this time with `service1` as the root span - so indicates that the root span in the ingress is being created but not reported, but the sampled flag is not being propagated to the child span or subsequent services.

Also the other strange thing is that if the `X-B3-Sampled` header is supplied (whether with 0 or 1 value), it does not cause a trace to be created.

### PR DESCRIPTION
**Pull request by objectiser**
*Description*:
This PR fixes #3569.

There are two separate problems.

* The reason that the root span was not being reported for the health check is that if a request was classified as a health check, it didn't finish the span. So all spans were still being created and considered sampled.

* The second issue was that when the sampling decision is being made, the health check filter had not yet been invoked, and therefore was not being taken into account. Therefore I exposed the `setSampled` method in the abstract `Span` API and enabled the health check filter to explicitly set whether the span is sampled.

The issue is that potentially by the time the filter is invoked, other filters may have created child spans. However I am not sure how else we can use logic executed mid stream (i.e. the health check filter) to influence the sampling decision.

The other issue is that normally the sampling decision is made when a root span for a trace is being created. With this PR, it is possible that an existing trace will have a subpart of the trace (i.e. the part  considered to be the health check) not sampled, while the remainder of the trace is still reported. Let me know if I haven't clearly explained this, as might be confusing :)

*Risk Level*: Low

*Testing*:
Needs tests - currently just looking for feedback on the fix.

*Docs Changes*:
none.

*Release Notes*:
none.

### CODE REVIEW

**Comment by mattklein123** [comment]
@lita do you mind taking a look at this and seeing if you have any concerns?

**Comment by rshriram** [comment]
Orthogonal comment: is it possible to ignore tracing for one or more paths ? In k8s, common complaint is that the pod health checks are flooding traces. 

Since you are working on this, thought I would put it out here

**Comment by objectiser** [comment]
@rshriram Already working on it https://github.com/istio/istio/pull/6068 - that is the motivation for fixing this.

**Comment by objectiser** [comment]
@lita Any thoughts before I start working on some tests?

File: test/common/http/conn_manager_impl_test.cc [hunk 1]
```diff
@@ -1069,64 +1069,6 @@ TEST_F(HttpConnectionManagerImplTest, DoNotStartSpanIfTracingIsNotEnabled) {
   conn_manager_->onData(fake_input, false);
 }
 
-TEST_F(HttpConnectionManagerImplTest, StartSpanOnlyHealthCheckRequest) {
```
Comment (lita) [inline test/common/http/conn_manager_impl_test.cc]: Why was this test removed?

**Comment by lita** [comment]
this makes sense to me. I am okay with this change.

File: test/common/http/conn_manager_impl_test.cc (hunk 1 above)
Comment (objectiser) [reply test/common/http/conn_manager_impl_test.cc]: The current implementation avoids sampling the initial span by not finishing it.

However if a child span is created from that initial span (as in the case of the router setting `start_child_span` to true, then the child span is reported with a parent span id that does not exist (on the server anyway).

So this PR uses the sampling mechanism to disable reporting of the span, which is then also propagated to the child spans.

**Comment by objectiser** [comment]
Ok thanks - I'll get some tests sorted.

**Comment by objectiser** [comment]
@lita Tests now included - should be ready for another review.

**Comment by objectiser** [comment]
@mattklein123 @lita Any further changes required, or can this be merged?

File: source/extensions/tracers/zipkin/zipkin_tracer_impl.h [hunk 2]
```diff
@@ -66,6 +66,8 @@ class ZipkinSpan : public Tracing::Span {
   Tracing::SpanPtr spawnChild(const Tracing::Config&, const std::string& name,
                               SystemTime start_time) override;
 
+  void setSampled(const bool sampled) override;
```
[the remark this answers is not in the document]
Comment (objectiser) [reply source/extensions/tracers/zipkin/zipkin_tracer_impl.h]: The OpenTracing compliant tracers can only have sampling decision influenced using the `sampling.priority` tag, which is set here: https://github.com/envoyproxy/envoy/pull/3578/files#diff-ab1d3267eb1d2cbca4a59b79e03df126R124

File: include/envoy/tracing/http_tracer.h [hunk 3]
```diff
@@ -99,6 +99,12 @@ class Span {
    */
   virtual SpanPtr spawnChild(const Config& config, const std::string& name,
                              SystemTime start_time) PURE;
+
+  /**
+   * Set the span's sampled flag.
+   * @param sampled whether the span and any subsequent child spans should be sampled
+   */
+  virtual void setSampled(const bool sampled) PURE;
```
Comment (mattklein123) [inline include/envoy/tracing/http_tracer.h]: nit: we don't typically do `const bool` so I would just remove `const`

File: source/extensions/filters/http/health_check/health_check.cc [hunk 4]
```diff
@@ -38,6 +38,9 @@ Http::FilterHeadersStatus HealthCheckFilter::decodeHeaders(Http::HeaderMap& head
     health_check_request_ = true;
     callbacks_->requestInfo().healthCheck(true);
 
+    // Hint to tracer to ignore the span and any subsequent child spans
+    callbacks_->activeSpan().setSampled(false);
```
Comment (mattklein123) [inline source/extensions/filters/http/health_check/health_check.cc]: Sorry I'm a little confused here. Why do we want to not sample health check requests? Can we make the comment more robust?

Comment (objectiser) [reply source/extensions/filters/http/health_check/health_check.cc]: As mentioned by @rshriram in https://github.com/envoyproxy/envoy/pull/3578#issuecomment-395902095, the health check probes generate a large number of unnecessary trace instances.

Previously the health checks were not being reported (assuming there were no child spans), because it didn't finish the span. So the behaviour is essentially the same from an Envoy perspective - however it fixes an issue in Istio as the mixer client performing the check is still being reported due to these health checks.

I will update the comment.

File: source/extensions/filters/http/health_check/health_check.cc [hunk 5]
```diff
@@ -38,6 +38,14 @@ Http::FilterHeadersStatus HealthCheckFilter::decodeHeaders(Http::HeaderMap& head
     health_check_request_ = true;
     callbacks_->requestInfo().healthCheck(true);
 
+    // Hint to tracer to ignore the span and any subsequent child spans.
+    // Health check probes are providing an operational check to ensure that the
+    // service is performing correctly. The benefit of distributed tracing is to
+    // record the path (and latency) a business transaction takes through multiple services to
+    // help diagnose issues. Recording trace instances for health check provides
+    // limited value, but consumes resources in the tracing system.
+    callbacks_->activeSpan().setSampled(false);
```
Comment (mattklein123) [inline source/extensions/filters/http/health_check/health_check.cc]: Sorry, I get why we don't want to trace health checks. I don't fully understand why disabling sampling makes the traces go away?

Comment (mattklein123) [reply source/extensions/filters/http/health_check/health_check.cc]: Ah I see. Sorry, this is quite confusing. `setSampled()` to me says whether to sample or not, and not sampled means always send. Can you rename the method at the Envoy API layer or add more comments?

Comment (objectiser) [reply source/extensions/filters/http/health_check/health_check.cc]: I would prefer to leave the method name as it is consistent with the propagation property name, e.g. https://github.com/openzipkin/b3-propagation#sampling-decision

Comment (mattklein123) [reply source/extensions/filters/http/health_check/health_check.cc]: OK then can you update the comment here? https://github.com/envoyproxy/envoy/pull/3578/files#diff-7b5f0d3c634c8c1ac2d4fcaa26541dd9R102

Comment (objectiser) [reply source/extensions/filters/http/health_check/health_check.cc]: Hope this next version is ok - happy for any suggestions on how to improve though.
