### PR TITLE
test: waiting for the upstream connection disconnected before invoke EXPECT_LOG_CONTAINS

### LINKED ISSUE #26082: Data race in LDS (reuse port) integration test
This one has been cycling for a while - iirc its pretty frequent offender on release branches

Not sure exactly what is flaking here - typical error:

```console
[ RUN      ] IpVersionsAndGrpcTypes/ListenerFilterIntegrationTest.UpdateListenerWithDifferentSocketOptionsWhenReusePortDisabled/1
==================
WARNING: ThreadSanitizer: data race (pid=16)
  Read of size 1 at 0x7b1000017db8 by thread T1126 (mutexes: read M0):
    #0 Envoy::Logger::DelegatingLogSink::log(spdlog::details::log_msg const&)::$_0::operator()(Envoy::Logger::SinkDelegate&) const /proc/self/cwd/source/common/common/logger.cc:98:9 (listener_lds_integration_test+0x917d352)
    #1 Envoy::Logger::DelegatingLogSink::log(spdlog::details::log_msg const&) /proc/self/cwd/source/common/common/logger.cc:117:3 (listener_lds_integration_test+0x917d21f)
    #2 spdlog::logger::sink_it_(spdlog::details::log_msg const&) /proc/self/cwd/external/com_github_gabime_spdlog/include/spdlog/logger-inl.h:186:23 (listener_lds_integration_test+0x32cc239)
    #3 spdlog::logger::log_it_(spdlog::details::log_msg const&, bool, bool) /proc/self/cwd/external/com_github_gabime_spdlog/include/spdlog/logger-inl.h:170:9 (listener_lds_integration_test+0x32e1377)
    #4 void spdlog::logger::log_<unsigned long, unsigned long&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::basic_string_view<char>, unsigned long&&, unsigned long&) /proc/self/cwd/external/com_github_gabime_spdlog/include/spdlog/logger.h:334:13 (listener_lds_integration_test+0x6e3c9d8)
    #5 void spdlog::logger::log<unsigned long, unsigned long&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::basic_format_string<char, fmt::v9::type_identity<unsigned long>::type, fmt::v9::type_identity<unsigned long&>::type>, unsigned long&&, unsigned long&) /proc/self/cwd/external/com_github_gabime_spdlog/include/spdlog/logger.h:83:9 (listener_lds_integration_test+0x6e208cd)
    #6 Envoy::Network::RawBufferSocket::doRead(Envoy::Buffer::Instance&) /proc/self/cwd/source/common/network/raw_buffer_socket.cc:24:7 (listener_lds_integration_test+0x8531772)
    #7 Envoy::Network::ConnectionImpl::onReadReady() /proc/self/cwd/source/common/network/connection_impl.cc:634:40 (listener_lds_integration_test+0x837aa48)
    #8 Envoy::Network::ConnectionImpl::onFileEvent(unsigned int) /proc/self/cwd/source/common/network/connection_impl.cc:602:5 (listener_lds_integration_test+0x837518f)
    #9 Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6::operator()(unsigned int) const /proc/self/cwd/source/common/network/connection_impl.cc:94:54 (listener_lds_integration_test+0x8391541)
    #10 decltype(static_cast<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&>(fp)(static_cast<unsigned int>(fp0))) std::__1::__invoke<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/type_traits:3640:23 (listener_lds_integration_test+0x83914cc)
    #11 void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional/invoke.h:61:9 (listener_lds_integration_test+0x839141a)
    #12 std::__1::__function::__alloc_func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:180:16 (listener_lds_integration_test+0x83913aa)
    #13 std::__1::__function::__func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:354:12 (listener_lds_integration_test+0x838fb49)
    #14 std::__1::__function::__value_func<void (unsigned int)>::operator()(unsigned int&&) const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16 (listener_lds_integration_test+0x3c61352)
    #15 std::__1::function<void (unsigned int)>::operator()(unsigned int) const /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12 (listener_lds_integration_test+0x3c6124f)
    #16 Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5::operator()(unsigned int) const /proc/self/cwd/source/common/event/dispatcher_impl.cc:184:9 (listener_lds_integration_test+0x82eec93)
    #17 decltype(static_cast<Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5&>(fp)(static_cast<unsigned int>(fp0))) std::__1::__invoke<Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5&, unsigned int>(Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/type_traits:3640:23 (listener_lds_integration_test+0x82eec0c)
    #85 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/source/common/common/posix/thread_impl.cc:48:9 (listener_lds_integration_test+0x9085da5)

SUMMARY: ThreadSanitizer: data race /proc/self/cwd/source/common/common/logger.cc:98:9 in Envoy::Logger::DelegatingLogSink::log(spdlog::details::log_msg const&)::$_0::operator()(Envoy::Logger::SinkDelegate&) const
==================
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=130696&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=266e17e3-d213-54b5-deef-0dcee01da137&l=931

### PR DESCRIPTION
**Pull request by soulxu**
Commit Message: test: waiting for the upstream connection disconnected before invoke EXPECT_LOG_CONTAINS 
Additional Description:
There is a race when `EXPECT_LOG_CONTAINS` invoke `Envoy::Logger::DelegatingLogSink::setShouldEscape(bool)` in the main test thread and the FakeUpstreamConnection will invoke `Envoy::Logger::DelegatingLogSink::setShouldEscape(bool)` in their own thread also.

So this PR will wait for the FakeUpstreamConnection disconnect first, then invoke the `EXPECT_LOG_CONTAINS`

Risk Level: low
Testing: n/a
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Fixes #26082

### CODE REVIEW

**Comment by soulxu** [comment]
This may fix the https://github.com/envoyproxy/envoy/issues/26082, but it isn't fix the root issue. Seems there are a lot of race for FakeRawConnection since it is running in the different thread than the test main thread.

**Comment by soulxu** [comment]
note for the reviewer: I can't reproduce the original race issue in my local, what I can reproduce is another race issue describe here https://github.com/envoyproxy/envoy/issues/26082#issuecomment-1469603708

But I think this fix may fix the original race.

File: test/integration/listener_lds_integration_test.cc [hunk 1]
```diff
@@ -1598,14 +1598,15 @@ TEST_P(ListenerFilterIntegrationTest,
       {
         sendLdsResponse({MessageUtil::getYamlStringFromMessage(listener_config_)}, "2");
         test_server_->waitForCounterGe("listener_manager.lds.update_rejected", 1);
-        IntegrationTcpClientPtr tcp_client2 = makeTcpConnection(lookupPort("test_listener"));
```
Comment (kyessenov) [inline test/integration/listener_lds_integration_test.cc:1601]: Not sure I understand - the macro `EXPECT_LOG_CONTAINS` executes `setShouldEscape` and the code block sequentially. Where's the data race?

Comment (soulxu) [reply test/integration/listener_lds_integration_test.cc:1601]: emm...indeed. 

The log said the write race is in the EXPECT_LOG_CONTANTS, but indeed, that happened before this code bock.

I can't reproduce this local, but I'm guessing this log 
https://dev.azure.com/cncf/envoy/_build/results?buildId=130696&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=266e17e3-d213-54b5-deef-0dcee01da137&l=767

may happened before a remote close
https://github.com/envoyproxy/envoy/blob/fa5f548d05da6495c175b5c124292fa0bae215de/source/common/network/raw_buffer_socket.cc#L24-L29

so the real race is at line 1584 closed the client client.
https://github.com/envoyproxy/envoy/pull/26098/files#diff-7fe1ad3a088b5d0ea44d9bace0dfa0675d5009bcb538afb778ebad50c802ddeaR1584

That trigger a remote close for upstream connection. And at same time EXPECT_LOG_CONTANTS executes the `setShouldEscape`

Let me try to update this.

Thanks for the review again!

File: test/integration/listener_lds_integration_test.cc [hunk 2]
```diff
@@ -1582,6 +1582,7 @@ TEST_P(ListenerFilterIntegrationTest,
   ASSERT_TRUE(fake_upstreams_[0]->waitForRawConnection(fake_upstream_connection));
   ASSERT_TRUE(fake_upstream_connection->waitForData(data.size(), &data));
   tcp_client->close();
+  ASSERT_TRUE(fake_upstream_connection->waitForDisconnect());
```
Comment (soulxu) [inline test/integration/listener_lds_integration_test.cc:1585]: emm...I need to think about how to avoid this happened again, people may invoke EXPECT_LOG_CONTAINS before upstream connection disconnect in other place

Comment (soulxu) [reply test/integration/listener_lds_integration_test.cc:1585]: I don't have anything in my mind, since it feels expensive to add lock for `Envoy::Logger::DelegatingLogSink::setShouldEscape(bool)`

**Comment by kyessenov** [comment]
Is this PR ready for review again? The code change doesn't seem to match the text description.
/wait

**Comment by soulxu** [comment]
> Is this PR ready for review again? The code change doesn't seem to match the text description. /wait

yes, this is ready for review, let me update the description, thanks

**Comment by soulxu** [comment]
Another fix, it fixed the same issue https://github.com/envoyproxy/envoy/pull/26139
