### PR TITLE
dns cache: Replace copy-on-add/remove with lock-guarded global map

### LINKED ISSUE #14018: Poor DNS cache performance with large number of unique domains
*Description*:
We are using Envoy as a dynamic forward proxy and are looking to connect upstream to a large number of hosts at unique domains (>> 100k).

We ran across performance issues in the implementation of the DNS cache when scaling to >40k hosts.

The primary issue is that both the DNS cache implementation and the dynamic forward proxy implementation each create a new copy of the entire cache on update. This is a reasonable implementation given Envoy's threading model and if you know the map is small, but it runs into scalability issues as the map grows.

With default configuration, the DNS cache will hit circuit-breaker limits before hitting this performance issue, so this issue won't be hit in overload conditions where you expect only a small number of hosts. The trouble occurs when you want to configure Envoy to handle a much larger number of host names.

This performance issue is probably not surprising, since I would expect the motivating use case was for a much smaller number of hosts. Looking at the [dynamic forward proxy documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy), it's fairly clear that there are some features that would not be feasible for a large number of hosts (e.g. observability in the admin output).

I'd like to understand if the intention is for the DNS cache to be used as a general-purpose cache that will be able to scale, or if it's primarily intended to only be paired with the dynamic forward proxy cluster.

*Repro steps*:
1. Configure Envoy to use a dynamic forward proxy.
2. Set the `max_hosts` and `host_ttl` in the `dns_cache_config` to something large.
3. Disable the DNS cache circuit breakers (`envoy.reloadable_features.enable_dns_cache_circuit_breakers`)
4. Run traffic against Envoy destined to ~50k unique domains or more

I also created a Google Benchmark test to exercise the DNS cache implementation in isolation and observed a cache insertion complexity of greater than O(N^2) (N=number of elements in the map).

### PR DESCRIPTION
**Pull request by chradcliffe**
Commit Message: 
* Change both dns cache and dfp cluster to use global maps guarded by mutexes. Previously, each of these maps would be copied on each add/remove, which led to performance issues as the maps grew.
* Change worker DNS cache callback container to use a map from hostnames to lists of callbacks. This ensures that callbacks are only invoked for the hosts that are completely ready (e.g. the dynamic forward proxy's host info has been populated).

Additional Description:

Risk Level: Medium -- change involves cross-thread synchronization
Testing:
* Unit tests
* Manual testing under heavy load

Docs Changes: N/A
Release Notes: N/A (not sure if this is a candidate for release notes)
Platform Specific Features: N/A
Fixes #14018

### CODE REVIEW

File: source/common/common/cleanup.h [hunk 1]
```diff
@@ -55,4 +55,39 @@ template <class T> class RaiiListElement {
   bool cancelled_;
 };
 
+template <class Key, class Value> class RaiiMapOfListElement {
```
Comment (mattklein123) [inline source/common/common/cleanup.h:58]: Please add a block comment about what this class does.

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc [hunk 2]
```diff
@@ -44,23 +43,23 @@ Cluster::Cluster(
 
 void Cluster::startPreInit() {
   // If we are attaching to a pre-populated cache we need to initialize our hosts.
-  auto existing_hosts = dns_cache_->hosts();
+  // TODO: Can we just loop over the actual DNS cache map here rather than a copy?
```
Comment (mattklein123) [inline source/extensions/clusters/dynamic_forward_proxy/cluster.cc:46]: nit: use TODO(username) format

To avoid the copy could you pass in a lambda/callback to receive each host or something like that? Just throwing out some ideas.

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc [hunk 3]
```diff
@@ -180,8 +165,9 @@ Cluster::LoadBalancer::chooseHost(Upstream::LoadBalancerContext* context) {
     return nullptr;
   }
 
-  const auto host_it = host_map_->find(host);
-  if (host_it == host_map_->end()) {
+  absl::ReaderMutexLock lock{&cluster_.host_map_lock_};
+  const auto host_it = cluster_.host_map_.find(host);
```
Comment (mattklein123) [inline source/extensions/clusters/dynamic_forward_proxy/cluster.cc:169]: perf nit: use braces to reduce lock scope to just the find.

File: source/extensions/clusters/dynamic_forward_proxy/cluster.h [hunk 4]
```diff
@@ -90,19 +87,14 @@ class Cluster : public Upstream::BaseDynamicClusterImpl,
...
-                    std::shared_ptr<HostInfoMap>& new_host_map,
-                    std::unique_ptr<Upstream::HostVector>& hosts_added);
-  void swapAndUpdateMap(const HostInfoMapSharedPtr& new_hosts_map,
-                        const Upstream::HostVector& hosts_added,
-                        const Upstream::HostVector& hosts_removed);
+  addOrUpdateHost(const std::string& host,
+                  const Extensions::Common::DynamicForwardProxy::DnsHostInfoSharedPtr& host_info,
+                  std::unique_ptr<Upstream::HostVector>& hosts_added)
+      ABSL_EXCLUSIVE_LOCKS_REQUIRED(host_map_lock_);
+  void updatePriorityState(const Upstream::HostVector& hosts_added,
```
Comment (mattklein123) [inline source/extensions/clusters/dynamic_forward_proxy/cluster.h:95]: I think it's important to not hold the lock while you call `updateClusterPrioritySet` inside this function, since that can invoke a large number of callbacks, etc. Can you potentially refactor to drop the lock before calling out to all the callbacks? Or is holding the lock required somehow?

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc [hunk 5]
```diff
@@ -56,19 +55,26 @@ DnsCacheImpl::loadDnsCacheEntry(absl::string_view host, uint16_t default_port,
                                 LoadDnsCacheEntryCallbacks& callbacks) {
   ENVOY_LOG(debug, "thread local lookup for host '{}'", host);
   ThreadLocalHostInfo& tls_host_info = *tls_slot_;
-  auto tls_host = tls_host_info.host_map_->find(host);
-  if (tls_host != tls_host_info.host_map_->end()) {
-    ENVOY_LOG(debug, "thread local hit for host '{}'", host);
+
+  auto [cache_hit, is_overflow] = [&]() {
+    // TODO: Consider returning the looked-up host
```
Comment (mattklein123) [inline source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:60]: TODO formatting nit, same elsehwere.

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Thanks for tackling this. Generally looks great. Flushing out a few comments.\

I assume you already did this but can you test this in your deployment where you already run this filter at larger scale? Thank you.

/wait

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 3 above)
Comment (chradcliffe) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc:169]: In the rest of the function we're using members on `cluster_.host_map` and using `host_it` to access the host info so it's not safe to drop the lock until the end of the function, but I'll add braces around the if/else so that the lock won't be held if down the road we need to do some work at the end of the function.

File: source/common/common/cleanup.h (hunk 1 above)
Comment (chradcliffe) [reply source/common/common/cleanup.h:61]: Done in 7862a45

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 2 above)
Comment (chradcliffe) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc]: I implemented `iterateHostMap` in 7862a45 to address this TODO since it was easy enough.

File: source/extensions/clusters/dynamic_forward_proxy/cluster.h (hunk 4 above)
Comment (chradcliffe) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.h:96]: I refactored the code in 7862a45 to release the lock before calling `updateClusterPrioritySet`.

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc (hunk 5 above)
Comment (chradcliffe) [reply source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc]: Updated in 7862a45.

**Comment by chradcliffe** [comment]
I ran this in my environment under load that previously caused the DNS cache to fall over, and the performance was much more stable as the cache grew larger -- I no longer see the super-linear cache lookup times (relative to cache size) at the rate I was testing.

I'm going to be doing some more performance testing over the next while, so some other ideas for improvement might fall out of that. For now, this is definitely a step in the right direction.

File: source/common/common/cleanup.h [hunk 6]
```diff
@@ -55,4 +55,42 @@ template <class T> class RaiiListElement {
...
+
+  virtual ~RaiiMapOfListElement() {
+    if (!cancelled_) {
+      erase();
+    }
+  }
+
+  void cancel() { cancelled_ = true; }
+
+  void erase() {
```
Comment (mattklein123) [inline source/common/common/cleanup.h:79]: I don't think you use this directly right now? Either make this private or inline it above?

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc [hunk 7]
```diff
@@ -100,14 +95,11 @@ void Cluster::addOrUpdateWorker(
...
-  const auto emplaced =
-      new_host_map->try_emplace(host, host_info,
-                                std::make_shared<Upstream::LogicalHost>(
-                                    info(), host, host_info->address(), dummy_locality_lb_endpoint_,
-                                    dummy_lb_endpoint_, nullptr, time_source_));
+  const auto emplaced = host_map_.try_emplace(
+      host, host_info,
+      std::make_shared<Upstream::LogicalHost>(info(), std::string{host}, host_info->address(),
+                                              dummy_locality_lb_endpoint_, dummy_lb_endpoint_,
+                                              nullptr, time_source_));
```
Comment (mattklein123) [inline source/extensions/clusters/dynamic_forward_proxy/cluster.cc:102]: nit: you can drop the write lock here I think.

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h [hunk 8]
```diff
@@ -117,7 +139,9 @@ class DnsCacheImpl : public DnsCache, Logger::Loggable<Logger::Id::forward_proxy
     Network::ActiveDnsQuery* active_query_{};
   };
 
-  using PrimaryHostInfoPtr = std::unique_ptr<PrimaryHostInfo>;
+  // Hold PrimaryHostInfo by shared_ptr to avoid having to hold the map mutex while updating
+  // individual entries.
```
Comment (mattklein123) [inline source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h:143]: It's not clear to me why this change is required. Expand? If it is required switch to `PrimaryHostInfoSharedPtr`

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc [hunk 9]
```diff
@@ -224,82 +246,75 @@ void DnsCacheImpl::finishResolve(const std::string& host,
...
-    if (primary_host.second->host_info_->first_resolve_complete_) {
-      new_host_map->emplace(primary_host.first, primary_host.second->host_info_);
-    }
-  }
-
-  tls_slot_.runOnAllThreads([new_host_map](OptRef<ThreadLocalHostInfo> local_host_info) {
-    local_host_info->updateHostMap(new_host_map);
+void DnsCacheImpl::notifyThreads(const std::string& host) {
+  auto host_ptr = std::make_shared<const std::string>(host);
+  tls_slot_.runOnAllThreads([host_ptr](OptRef<ThreadLocalHostInfo> local_host_info) {
```
Comment (mattklein123) [inline source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:294]: I think you can just capture by copy here?

**Review by mattklein123 — CHANGES_REQUESTED** [review]
Few more comments, nice work, thanks!

/wait

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h (hunk 8 above)
Comment (chradcliffe) [reply source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h:143]: I changed this so we could release the mutex after a map lookup and guarantee that the entry won't be deleted while we're updating it.

Now that I'm thinking more about it, it seems like it might be too strict since the current implementation only adds/removes in the main thread. I think it's probably fine to restore this to unique_ptr, document the constraint that the add/updates are in the main thread, and throw in a few `ASSERT(main_thread_dispatcher_.isThreadSafe())` for good measure. WDYT?

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc (hunk 9 above)
Comment (chradcliffe) [reply source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:306]: Ah I missed this comment in my last update. A capture by copy here will make a string copy for each worker thread. Is that an acceptable cost?

Comment (mattklein123) [reply source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:306]: My guess is that in most cases it will be small object inlined into the lambda, but I'm not sure. It doesn't matter that much so whatever you think is best.

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h (hunk 8 above)
Comment (mattklein123) [reply source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h:143]: Yup SGTM!

File: source/common/common/cleanup.h (hunk 6 above)
Comment (chradcliffe) [reply source/common/common/cleanup.h:80]: Fixed in 3e16973

File: source/extensions/clusters/dynamic_forward_proxy/cluster.cc (hunk 7 above)
Comment (chradcliffe) [reply source/extensions/clusters/dynamic_forward_proxy/cluster.cc]: Fixed in 3e16973

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h (hunk 8 above)
Comment (chradcliffe) [reply source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h:143]: Restored unique_ptr and added comments/assertions in 3e16973

File: source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc (hunk 9 above)
Comment (chradcliffe) [reply source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:306]: Ok I'll leave it as a shared_ptr for now.

**Comment by mattklein123** [comment]
TSAN issue looks legit. Can you take a look?

/wait

**Comment by chradcliffe** [comment]
> TSAN issue looks legit. Can you take a look?

This was an issue where the `onReResolve` timer and callback were being destroyed during execution of the `onReResolve` callback. This was an existing but previously benign issue that now started tripping the TSAN checker because the code uses the `host` parameter after the owner of the callback (`PrimaryHostInfo`) is deleted.

Fixed in 3e16973 by holding the to-be-erased `PrimaryHostInfo` pointer until the `onReResolve` function exits.

**Review by mattklein123 — APPROVED** [review]
Thanks!
