### PR TITLE
conn mgr: Use std::optional::has_value where appropriate

### LINKED ISSUE #5289: throw_bad_optional_access in HttpConnectionManager
As reported by @tonya11en 

At Lyft, we've observed an Envoy crash with the following stack trace on build 6d9de10:

Backtrace:
#0  0x00007f05ab87ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#0  0x00007f05ab87ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f05ab87e028 in __GI_abort () at abort.c:89
#2  0x0000000000bd711d in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x0000000000ba3df6 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x0000000000ba3e31 in std::terminate() ()
#5  0x0000000000ba52a8 in __cxa_throw ()
#6  0x0000000000b80ea7 in absl::optional_internal::throw_bad_optional_access() ()
#7  0x00000000007100af in value (this=<optimized out>) at external/com_google_absl/absl/types/optional.h:844
#8  Envoy::Http::ConnectionManagerImpl::ActiveStream::createFilterChain (this=this@entry=0x3cbd2000) at external/envoy/source/common/http/conn_manager_impl.cc:1408
#9  0x000000000071559b in createFilterChain (this=0x3cbd2000) at external/envoy/source/common/http/conn_manager_impl.cc:1001
#10 Envoy::Http::ConnectionManagerImpl::ActiveStream::sendLocalReply(bool, Envoy::Http::Code, std::string const&, std::function<void (Envoy::Http::HeaderMap&)> const&, bool, absl::optional<Envoy::Grpc::Status::GrpcStatus>) (this=this@entry=0x3cbd2000, is_grpc_request=is_grpc_request@entry=false, code=code@entry=Envoy::Http::UpgradeRequired, body=..., modify_headers=..., is_head_request=is_head_request@entry=false, grpc_status=...) at external/envoy/source/common/http/conn_manager_impl.cc:1002
#11 0x000000000071ab1b in Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders(std::unique_ptr<Envoy::Http::HeaderMap, std::default_delete<Envoy::Http::HeaderMap> >&&, bool) (this=0x3cbd2000, headers=<optimized out>, end_stream=true) at external/envoy/source/common/http/conn_manager_impl.cc:573
#12 0x000000000074154a in Envoy::Http::Http1::ServerConnectionImpl::onMessageComplete (this=0x4398b40) at external/envoy/source/common/http/http1/codec_impl.cc:623
#13 0x0000000000744afc in Envoy::Http::Http1::ConnectionImpl::onMessageCompleteBase (this=0x4398b48) at external/envoy/source/common/http/http1/codec_impl.cc:442
#14 0x0000000000744bbd in operator() (__closure=0x0, parser=<optimized out>) at external/envoy/source/common/http/http1/codec_impl.cc:294
#15 Envoy::Http::Http1::ConnectionImpl::<lambda(http_parser*)>::_FUN(http_parser *) () at external/envoy/source/common/http/http1/codec_impl.cc:296
#16 0x0000000000747a9f in http_parser_execute ()
#17 0x00000000007427c2 in Envoy::Http::Http1::ConnectionImpl::dispatchSlice (this=this@entry=0x4398b48, slice=<optimized out>, len=<optimized out>) at external/envoy/source/common/http/http1/codec_impl.cc:378
#18 0x00000000007445b3 in Envoy::Http::Http1::ConnectionImpl::dispatch (this=0x4398b48, data=...) at external/envoy/source/common/http/http1/codec_impl.cc:363
#19 0x0000000000717988 in Envoy::Http::ConnectionManagerImpl::onData (this=0x156381c0, data=...) at external/envoy/source/common/http/conn_manager_impl.cc:230
#20 0x00000000005f30e7 in Envoy::Network::FilterManagerImpl::onContinueReading (this=this@entry=0x29ad8018, filter=filter@entry=0x0) at external/envoy/source/common/network/filter_manager_impl.cc:60
#21 0x00000000005f31bc in Envoy::Network::FilterManagerImpl::onRead (this=this@entry=0x29ad8018) at external/envoy/source/common/network/filter_manager_impl.cc:70
#22 0x00000000005f041f in onRead (read_buffer_size=205, this=0x29ad8000) at external/envoy/source/common/network/connection_impl.cc:263
#23 Envoy::Network::ConnectionImpl::onReadReady (this=this@entry=0x29ad8000) at external/envoy/source/common/network/connection_impl.cc:496
#24 0x00000000005f0c6e in Envoy::Network::ConnectionImpl::onFileEvent (this=0x29ad8000, events=3) at external/envoy/source/common/network/connection_impl.cc:472
#25 0x00000000005ea7f8 in operator() (__args#0=3, this=<optimized out>) at /usr/include/c++/5/functional:2267
#26 operator() (__closure=0x0, arg=<optimized out>, what=<optimized out>) at external/envoy/source/common/event/file_event_impl.cc:60
#27 Envoy::Event::FileEventImpl::<lambda(int, short int, void*)>::_FUN(int, short, void *) () at external/envoy/source/common/event/file_event_impl.cc:61
#28 0x00000000008b9cef in event_persist_closure (ev=<optimized out>, base=0x2456dc0) at ../event.c:1580
#29 event_process_active_single_queue (base=base@entry=0x2456dc0, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0, activeq=<optimized out>) at ../event.c:1639
#30 0x00000000008ba41f in event_process_active (base=base@entry=0x2456dc0) at ../event.c:1738
#31 0x00000000008bd178 in event_base_loop (base=0x2456dc0, flags=<optimized out>) at ../event.c:1961
#32 0x00000000005e66b6 in Envoy::Server::WorkerImpl::threadRoutine (this=0x2edecc0, guard_dog=...) at external/envoy/source/server/worker_impl.cc:101
#33 0x00000000008cabe5 in Envoy::Thread::ThreadImpl::ThreadImpl(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) () at /usr/include/c++/5/functional:2267
#34 0x00007f05abf1b184 in start_thread (arg=0x7f05a8c79700) at pthread_create.c:312
#35 0x00007f05ab94203d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
This is due to the usage of std:optional::value() to check whether an optional variable has a value instead of std::optional::has_value(). value() throws an exception if has_value() would return false, so I suspect the intention is what can be found in this PR.

Please let me know if I'm misunderstanding something.

Risk Level:
Low

Testing:
Existing UTs

### PR DESCRIPTION
**Pull request by tonya11en**
At Lyft, we've observed an Envoy crash with the following stack trace on build 6d9de10ccdc6977a6ee381de2db158b223a83bb5:
```
Backtrace:
#0  0x00007f05ab87ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#0  0x00007f05ab87ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f05ab87e028 in __GI_abort () at abort.c:89
#2  0x0000000000bd711d in __gnu_cxx::__verbose_terminate_handler() ()
#3  0x0000000000ba3df6 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x0000000000ba3e31 in std::terminate() ()
#5  0x0000000000ba52a8 in __cxa_throw ()
#6  0x0000000000b80ea7 in absl::optional_internal::throw_bad_optional_access() ()
#7  0x00000000007100af in value (this=<optimized out>) at external/com_google_absl/absl/types/optional.h:844
#8  Envoy::Http::ConnectionManagerImpl::ActiveStream::createFilterChain (this=this@entry=0x3cbd2000) at external/envoy/source/common/http/conn_manager_impl.cc:1408
#9  0x000000000071559b in createFilterChain (this=0x3cbd2000) at external/envoy/source/common/http/conn_manager_impl.cc:1001
#10 Envoy::Http::ConnectionManagerImpl::ActiveStream::sendLocalReply(bool, Envoy::Http::Code, std::string const&, std::function<void (Envoy::Http::HeaderMap&)> const&, bool, absl::optional<Envoy::Grpc::Status::GrpcStatus>) (this=this@entry=0x3cbd2000, is_grpc_request=is_grpc_request@entry=false, code=code@entry=Envoy::Http::UpgradeRequired, body=..., modify_headers=..., is_head_request=is_head_request@entry=false, grpc_status=...) at external/envoy/source/common/http/conn_manager_impl.cc:1002
#11 0x000000000071ab1b in Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders(std::unique_ptr<Envoy::Http::HeaderMap, std::default_delete<Envoy::Http::HeaderMap> >&&, bool) (this=0x3cbd2000, headers=<optimized out>, end_stream=true) at external/envoy/source/common/http/conn_manager_impl.cc:573
#12 0x000000000074154a in Envoy::Http::Http1::ServerConnectionImpl::onMessageComplete (this=0x4398b40) at external/envoy/source/common/http/http1/codec_impl.cc:623
#13 0x0000000000744afc in Envoy::Http::Http1::ConnectionImpl::onMessageCompleteBase (this=0x4398b48) at external/envoy/source/common/http/http1/codec_impl.cc:442
#14 0x0000000000744bbd in operator() (__closure=0x0, parser=<optimized out>) at external/envoy/source/common/http/http1/codec_impl.cc:294
#15 Envoy::Http::Http1::ConnectionImpl::<lambda(http_parser*)>::_FUN(http_parser *) () at external/envoy/source/common/http/http1/codec_impl.cc:296
#16 0x0000000000747a9f in http_parser_execute ()
#17 0x00000000007427c2 in Envoy::Http::Http1::ConnectionImpl::dispatchSlice (this=this@entry=0x4398b48, slice=<optimized out>, len=<optimized out>) at external/envoy/source/common/http/http1/codec_impl.cc:378
#18 0x00000000007445b3 in Envoy::Http::Http1::ConnectionImpl::dispatch (this=0x4398b48, data=...) at external/envoy/source/common/http/http1/codec_impl.cc:363
#19 0x0000000000717988 in Envoy::Http::ConnectionManagerImpl::onData (this=0x156381c0, data=...) at external/envoy/source/common/http/conn_manager_impl.cc:230
#20 0x00000000005f30e7 in Envoy::Network::FilterManagerImpl::onContinueReading (this=this@entry=0x29ad8018, filter=filter@entry=0x0) at external/envoy/source/common/network/filter_manager_impl.cc:60
#21 0x00000000005f31bc in Envoy::Network::FilterManagerImpl::onRead (this=this@entry=0x29ad8018) at external/envoy/source/common/network/filter_manager_impl.cc:70
#22 0x00000000005f041f in onRead (read_buffer_size=205, this=0x29ad8000) at external/envoy/source/common/network/connection_impl.cc:263
#23 Envoy::Network::ConnectionImpl::onReadReady (this=this@entry=0x29ad8000) at external/envoy/source/common/network/connection_impl.cc:496
#24 0x00000000005f0c6e in Envoy::Network::ConnectionImpl::onFileEvent (this=0x29ad8000, events=3) at external/envoy/source/common/network/connection_impl.cc:472
#25 0x00000000005ea7f8 in operator() (__args#0=3, this=<optimized out>) at /usr/include/c++/5/functional:2267
#26 operator() (__closure=0x0, arg=<optimized out>, what=<optimized out>) at external/envoy/source/common/event/file_event_impl.cc:60
#27 Envoy::Event::FileEventImpl::<lambda(int, short int, void*)>::_FUN(int, short, void *) () at external/envoy/source/common/event/file_event_impl.cc:61
#28 0x00000000008b9cef in event_persist_closure (ev=<optimized out>, base=0x2456dc0) at ../event.c:1580
#29 event_process_active_single_queue (base=base@entry=0x2456dc0, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0, activeq=<optimized out>) at ../event.c:1639
#30 0x00000000008ba41f in event_process_active (base=base@entry=0x2456dc0) at ../event.c:1738
#31 0x00000000008bd178 in event_base_loop (base=0x2456dc0, flags=<optimized out>) at ../event.c:1961
#32 0x00000000005e66b6 in Envoy::Server::WorkerImpl::threadRoutine (this=0x2edecc0, guard_dog=...) at external/envoy/source/server/worker_impl.cc:101
#33 0x00000000008cabe5 in Envoy::Thread::ThreadImpl::ThreadImpl(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) () at /usr/include/c++/5/functional:2267
#34 0x00007f05abf1b184 in start_thread (arg=0x7f05a8c79700) at pthread_create.c:312
#35 0x00007f05ab94203d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

This is due to the usage of `std:optional::value()` to check whether an optional variable has a value instead of `std::optional::has_value()`. `value()` throws an exception if `has_value()` would return false, so I suspect the intention is what can be found in this PR.

Please let me know if I'm misunderstanding something.

*Risk Level*:
Low

*Testing*:
Existing UTs
Fixes #5289

### CODE REVIEW

**Comment by tonya11en** [comment]
CC @junr03 @lita

File: source/common/http/conn_manager_impl.cc [hunk 1]
```diff
@@ -661,7 +661,7 @@ void ConnectionManagerImpl::ActiveStream::decodeHeaders(HeaderMapPtr&& headers,
     // Allow non websocket requests to go through websocket enabled routes.
   }
 
-  if (cached_route_.value()) {
+  if (cached_route_.has_value()) {
```
Comment (zuercher) [inline source/common/http/conn_manager_impl.cc]: I don't understand why this is a `std::optional<Router:RouteConstSharedPtr>`, but it seems that `Router::RouteMatcher::route` can return a nullptr, in which case I believe `cached_route_.has_value()` can be true with `cached_route_.value()` returning `nullptr`, causing a different crash. 

I think whatever path is crashing never does a route lookup, and so cached_route_ is not initialized to have a value of nullptr. I think it's be worth understanding that better and adding a test that reproduces it.

Assuming this rare no-value case is valid, I think you'd need to do `cached_route_.has_value() && `cached_route_.value()` at these sites.

Note also, there's another `cached_route_.value()` call on line 653.

Comment (lizan) [reply source/common/http/conn_manager_impl.cc]: This doesn't seems right, the code asserting `cached_route_` has a value at https://github.com/envoyproxy/envoy/blob/988f7d81f973e17c76db3f900cf145c371d6e8b3/source/common/http/conn_manager_impl.cc#L647

> I think whatever path is crashing never does a route lookup, and so cached_route_ is not initialized to have a value of nullptr. I think it's be worth understanding that better and adding a test that reproduces it.

+1

Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc]: Yes agreed this isn't right. Which line crashes exactly?

Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc]: From looking at the call stack again, I think looks like an issue when we call `createFilterChain()` via an early `sendLocalReply()`. I'm very surprised this path doesn't have test coverage which causes a crash in a test. cc @alyssawilk

Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc]: I'm still trying to suss out when we might sendLocalReply (and do early createFilterChain) before we do decodeHeaders, but still have the stream persist long enough to actually decodeHeaders.   Is it a race onIdletimeout maybe?

Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc]: @alyssawilk I'm probably missing something because a) I've looked at this very quickly and b) I thought we had test coverage of this, but it looks to me like in `decodeHeaders()` we can call `sendLocalReply()` before we call `refreshRouteCache()`. So wouldn't this mean that we would then not have a cached route in these paths and have to guard against it?

Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc]: But in all of these cases when we sendLocalReply we also return, so the route cache should be set.  The only sendLocalReply I could think of which could still result in decodeHeaders is if we had partial headers, then got the rest in the same event loop maybe?  So I added a test for timing out mid-headers (which we should have in any case) and with 5k runs I couldn't trigger any such loop.  I'll probably still land it anyway as it's a pretty reasonable thing to have covered.

However!  After some thought of how else this might happen, if a filter calls clearRouteCache on creation (or rather immediately when it gets the callbacks set, which I think it can) I've got an integration test with a fake filter which does just that and crashes with 
terminate called after throwing an instance of 'absl::bad_optional_access'.  I doubt that's what is happening in prod unless you have a very silly filter, but it is at least a synthetic way of making sure the HCM behaves well when there's no cached route between filter creation and the router filter refreshing it.

It's over here:
https://github.com/envoyproxy/envoy/compare/master...alyssawilk:extra_tests
I'm happy to have it pulled into this PR or land it as a follow-up

Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc]: also to answer your question directly, yes we should totally guard against route cache not being set even if I can't figure out the path which you folks are seeing

Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc]: The call stack is like this:

```
#7  0x00000000007100af in value (this=<optimized out>) at external/com_google_absl/absl/types/optional.h:844
#8  Envoy::Http::ConnectionManagerImpl::ActiveStream::createFilterChain (this=this@entry=0x3cbd2000) at external/envoy/source/common/http/conn_manager_impl.cc:1408
#9  0x000000000071559b in createFilterChain (this=0x3cbd2000) at external/envoy/source/common/http/conn_manager_impl.cc:1001
#10 Envoy::Http::ConnectionManagerImpl::ActiveStream::sendLocalReply(bool, Envoy::Http::Code, std::string const&, std::function<void (Envoy::Http::HeaderMap&)> const&, bool, absl::optional<Envoy::Grpc::Status::GrpcStatus>) (this=this@entry=0x3cbd2000, is_grpc_request=is_grpc_request@entry=false, code=code@entry=Envoy::Http::UpgradeRequired, body=..., modify_headers=..., is_head_request=is_head_request@entry=false, grpc_status=...) at external/envoy/source/common/http/conn_manager_impl.cc:1002
#11 0x000000000071ab1b in Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders(std::unique_ptr<Envoy::Http::HeaderMap, std::default_delete<Envoy::Http::HeaderMap> >&&, bool) (this=0x3cbd2000, headers=<optimized out>, end_stream=true) at external/envoy/source/common/http/conn_manager_impl.cc:573
```

The crash is inline. I don't think return matters? How does this work when we do an early sendLocalReply() before we eventually populate the route cache? I'm confused how this works or if we don't actually test this case?

Comment (alyssawilk) [reply source/common/http/conn_manager_impl.cc]: We totally have tests where we sendLocalReply early, but my guess is we don't have tests where we sendLocalReply early to a request which has an upgrade header, which is one of the places we're checking cached_route_.value() and not cached_route_.has_value() && cached_route_.value() and I think the one in your call stack

I think it'd be safest to always check has_value() and value() in all places.

Comment (mattklein123) [reply source/common/http/conn_manager_impl.cc]: I see. OK. I think it still needs some analysis since I think in some places we do/should assume we have a route, so it might only be in `createFilterChain()` that we need a guard. @tonya11en can you add a test that crashes and then we can discuss a fix?

**Comment by tonya11en** [comment]
Fixing only the problem area. Will update with unit test that exercises this path when I get a chance. It's not as straightforward as I expected.

**Comment by tonya11en** [comment]
I was able to reproduce the issue in an integration test, so the patch is ready to roll once CI passes.

File: source/common/http/conn_manager_impl.cc [hunk 2]
```diff
@@ -1411,7 +1411,7 @@ bool ConnectionManagerImpl::ActiveStream::createFilterChain() {
   state_.created_filter_chain_ = true;
   if (upgrade != nullptr) {
     const Router::RouteEntry::UpgradeMap* upgrade_map = nullptr;
-    if (cached_route_.value() && cached_route_.value()->routeEntry()) {
+    if (cached_route_.has_value() && cached_route_.value() && cached_route_.value()->routeEntry()) {
```
Comment (mattklein123) [inline source/common/http/conn_manager_impl.cc]: Can you add a small comment above here on why we need to check if the optional is populated? It's not immediately obvious (basically that this can get called during early local reply, etc.).
