### PR TITLE
connection: Do not reset delayed closed timer if doWrite consumes 0 bytes from the output buffer.

### LINKED ISSUE #11829: Setting event priorities to work around level based events
#### Description

Currently Windows does not support edge based events. As a result we rely on level based events which causes various issues.

For example in testlist [//test/common/network:connection_impl_test](https://github.com/envoyproxy/envoy/blob/master/test/common/network/connection_impl_test.cc#L1289) `FlushWriteAndDelayCloseTimerTriggerTest` the scenario that depends on setting a `setDelayedCloseTimeout` on the server.

This event on Windows is added to the queue in Windows but it gets **buried by the Level write events**. Some logs that indicate this behavior are here:
```
[debug] event_del: 000001FB4DB1FC78 (fd -1), callback 00007FF76C608820
[debug] event_process_active: event: 000001FB4D6E48F8,  EV_WRITE  call 00007FF76C4C6670
[2020-06-30 15:05:41.026][6448][trace][connection] [source/common/network/connection_impl.cc:506] [C0] socket event: 2
[2020-06-30 15:05:41.026][6448][trace][connection] [source/common/network/connection_impl.cc:607] [C0] write ready[debug] event_del: 000001FB4DB1FC78 (fd -1), callback 00007FF76C608820
[debug] event_process_active: event: 000001FB4D6E48F8,  EV_WRITE  call 00007FF76C4C6670
[2020-06-30 15:05:41.026][6448][trace][connection] [source/common/network/connection_impl.cc:506] [C0] socket event: 2
[2020-06-30 15:05:41.026][6448][trace][connection] [source/common/network/connection_impl.cc:607] [C0] write ready
```

This causes the test to hang and exposes a limitation for envoy on windows, to set `Scheduled Callbacks` and `Timer` events.

#### Proposed Solution: Set event priorities

We could utilize libevent `event_base_priority_init` to create more granular priorities on jobs.

Create an enumeration with priorities and use it when we create new `SchedulableCallbackImpl`

```C++
enum eventPriorities:
{
   Standard,
   High
}

SchedulableCallbackImpl::SchedulableCallbackImpl(Libevent::BasePtr& libevent,
                                                 std::function<void()> cb, eventPriorities job_priority)
```

This behavior could be limited only to Windows (or to both if we would think it has wider value)

#### Questions 

1. How important is the scenario of `Timers` and `Scheduled Callbacks`?
2. Are there any scenarios that this could cause a regression?

@nigriMSFT @sunjayBhatia @wrowe

### PR DESCRIPTION
**Pull request by antoniovicente**
Commit Message: connection: Do not reset delayed closed timer if doWrite consumes 0 bytes from the output buffer.
Additional Description: Only reset the delayed close timer if the write attempt made progress. This works around spurious fd Write events which are delivered to a connection even after it manages to fully drain the output buffer and should be waiting for client FIN or the delay close timer to expire. This is known to happen when  listening for level events instead of edge-trigger fd events.
Risk Level: medium, changes to timeout behavior.
Testing: unit
Docs Changes: n/a
Release Notes: n/a
Fixes #11829

### CODE REVIEW

File: source/common/network/connection_impl.cc [hunk 1]
```diff
@@ -645,15 +645,18 @@ void ConnectionImpl::onWriteReady() {
   } else if ((inDelayedClose() && new_buffer_size == 0) || bothSidesHalfClosed()) {
     ENVOY_CONN_LOG(debug, "write flush complete", *this);
     if (delayed_close_state_ == DelayedCloseState::CloseAfterFlushAndWait) {
-      ASSERT(delayed_close_timer_ != nullptr);
-      delayed_close_timer_->enableTimer(delayed_close_timeout_);
+      ASSERT(delayed_close_timer_ != nullptr && delayed_close_timer_->enabled());
+      if (result.bytes_processed_ > 0) {
+        delayed_close_timer_->enableTimer(delayed_close_timeout_);
```
Comment (antoniovicente) [inline source/common/network/connection_impl.cc:650]: I don't think there's a way to distinguish between these two enableTimer calls in tests. Ideally we would move delayed_close_state_ to a WaitingForClose state or change the fd mask to:
  file_event_->setEnabled(enable_half_close_ ? 0 : Event::FileReadyType::Closed);
to avoid getting any Write events past this point.

**Comment by antoniovicente** [comment]
/cc @davinci26

Hey Sotiris,

Can you double check that this change addresses your problem?

**Comment by davinci26** [comment]
LGTM it address the issue. I have verified it locally in my devbox

File: source/common/network/connection_impl.cc (hunk 1 above)
Comment (alyssawilk) [reply source/common/network/connection_impl.cc:650]: nah, but I'll trust you made sure your test would fail without the code change :-)

**Comment by antoniovicente** [comment]
> LGTM, though I'd bump the risk to medium because event loop changes. I'll merge after we cut the release :-)

Bumped up to medium.
