### PR TITLE
grpc-json: add option to convert gRPC status into JSON body (#3383)

### LINKED ISSUE #3383: grpc-json transcoder: convert grpc-message to body in response
*Title*: *Envoy's grpc-json transcoder*

*Description*:
>I've a REST client and a gRPC server and I'm using Envoy's grpc-json transcoder.
When an exception is thrown by gRPC server with gRPC error code and gRPC error message, 
on the client side I receive corresponding HTTP  error status code (grpc-error-code converted to http error code) and  error message like "Invalid userid" is set in response header "grpc-message".
Now I want gRPC error message to appear in body rather than response header. Is it possible with Envoy? If yes, How can I do it?

### PR DESCRIPTION
**Pull request by ascheglov**
When trailer indicates a gRPC error and there was no HTTP body, with the `convert_grpc_status option` enabled, take `google.rpc.Status` from the `grpc-status-details-bin` header and use it as a JSON body.
If there was no such header, make `google.rpc.Status` out of the `grpc-status` and `grpc-message` headers.

This also adds `google.rpc.Status` to user-provided protobuf descriptor.

Risk Level: Small-medium
Testing: Added unit and integration tests tests, tested manually.
Docs Changes:
Added field description in api/envoy/config/filter/http/transcoder/v2/transcoder.proto
Release Notes:
Fixes #3383

### CODE REVIEW

File: source/common/grpc/common.cc [hunk 1]
```diff
@@ -68,6 +69,27 @@ std::string Common::getGrpcMessage(const Http::HeaderMap& trailers) {
   return entry ? std::string(entry->value().getStringView()) : EMPTY_STRING;
 }
 
+absl::optional<google::rpc::Status>
+Common::getGrpcStatusDetailsBin(const Http::HeaderMap& trailers) {
+  const Http::HeaderEntry* details_header = trailers.GrpcStatusDetailsBin();
+  if (!details_header) {
+    return {};
```
Comment (lizan) [inline source/common/grpc/common.cc]: nit: nullopt

File: source/common/http/conn_manager_impl.cc [hunk 2]
```diff
@@ -1501,7 +1501,8 @@ void ConnectionManagerImpl::ActiveStream::addEncodedData(ActiveStreamEncoderFilt
                                                          Buffer::Instance& data, bool streaming) {
   if (state_.filter_call_state_ == 0 ||
       (state_.filter_call_state_ & FilterCallState::EncodeHeaders) ||
-      (state_.filter_call_state_ & FilterCallState::EncodeData)) {
+      (state_.filter_call_state_ & FilterCallState::EncodeData) ||
```
Comment (lizan) [inline source/common/http/conn_manager_impl.cc]: The change here worth another PR as it at least seems risky and need a test case for here. Why did you need this?

File: source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc [hunk 3]
```diff
@@ -164,10 +168,34 @@ JsonTranscoderConfig::JsonTranscoderConfig(
   ignore_unknown_query_parameters_ = proto_config.ignore_unknown_query_parameters();
 }
 
+void JsonTranscoderConfig::AddFileDescriptor(const Protobuf::FileDescriptorProto& file) {
```
Comment (lizan) [inline source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc]: nit: addFileDescriptor

File: source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc [hunk 4]
```diff
@@ -164,10 +168,34 @@ JsonTranscoderConfig::JsonTranscoderConfig(
...
+  if (descriptor_pool_.BuildFile(file) == nullptr) {
+    throw EnvoyException("transcoding_filter: Unable to build proto descriptor pool");
+  }
+}
+
+void JsonTranscoderConfig::AddBuiltinSymbolDescriptor(const std::string& symbol_name) {
```
Comment (lizan) [inline source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc]: nit: addBuiltinSymbolDescriptor

File: source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc [hunk 5]
```diff
@@ -244,6 +272,14 @@ JsonTranscoderConfig::methodToRequestInfo(const Protobuf::MethodDescriptor* meth
   return ProtobufUtil::Status();
 }
 
+ProtobufUtil::Status
+JsonTranscoderConfig::translateProtoMessageToJson(const Protobuf::Message& message,
```
Comment (lizan) [inline source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc]: Use Protobuf::util::MessageToJsonString so you don't have to serialize to string once, and respect the `Protobuf::util::JsonPrintOptions print_options_` for that.

File: source/common/http/conn_manager_impl.cc (hunk 2 above)
Comment (ascheglov) [reply source/common/http/conn_manager_impl.cc]: This is a tricky one.
When a gRPC server responds with 200, and then it sends a trailer with an error,
as in the `GrpcJsonTranscoderIntegrationTest.UnaryGetErrorInTrailerConvertedToJson` test,
or as it happens in this code:
```
func myHandler(w http.ResponseWriter, req *http.Request) {
  w.Header().Set("content-type", "application/grpc")
  w.Header().Set("trailer", "grpc-status")
  w.WriteHeader(200)
  // Then something goes wrong and we send a trailer with error:
  w.Header().Set("grpc-status", "5")
}
```
the transcoder is expected to send something like this:
```
$ echo -ne 'GET /func HTTP/1.1\r\nHost: localhost:8888\r\n\r\n' | nc localhost 8888
HTTP/1.1 404 Not Found
content-type: application/json
content-length: 10
date: Sat, 24 Aug 2019 20:56:19 GMT
x-envoy-upstream-service-time: 2
server: envoy

{"code":5}
```

However without this patch, first it sends the reply body with chunked transfer-encoding, and then it sends headers:
```
a
{"code":5}
HTTP/1.1 404 Not Found
content-type: application/json
content-length: 0
date: Sat, 24 Aug 2019 20:27:03 GMT
x-envoy-upstream-service-time: 12
server: envoy

```
(This "a" is the chunk size)

Supposedly when it does `encodeData()` in the `if (EncodeTrailers)` branch, it assumes that the headers were already sent, and maybe there was some part of reply-body sent, so it just dumps data as is.

Maybe there is a better option for fixing this, and yes I will also add a HttpConnectionManagerImplTest for this.

File: source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc (hunk 5 above)
Comment (ascheglov) [reply source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc]: We should also respect the user-provided protobuf descriptor, as `google.rpc.Status` has this `repeated Any details` field, which may contain arbitrary user types, e.g. those standard details types from [google/rpc/error_details.proto](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto).

Thus `MessageToJsonString` would call the same `BinaryToJsonString` with global (built-in) TypeResolver, and fail to convert the message.

The `GrpcJsonTranscoderFilterConvertGrpcStatusTest.TranscodingStatusFromBinaryHeaderWithDetails` can reproduce this problem as it decodes a Status which contains the helloworld.HelloReply type in `details`, and the transcoder's test binary doesn't have helloworld_proto_cc in dependencies.

Comment (ascheglov) [reply source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc]: Speaking of those types in error_details.proto,
in the JsonTranscoderConfig ctor we can add types to a user-provided protobuf descriptor, as it's done with the google.rpc.Status type, and actually it adds whole proto files (Protobuf::FileDescriptorProto structures). 
So we could do the same with those somewhat "standard" details types, build them into envoy binary and add them to user's descriptor. This would help users to avoid writing messages like this:
```
message Dummy {
  google.rpc.RequestInfo request_info = 1;
}
```

File: source/common/grpc/common.cc (hunk 1 above)
Comment (ascheglov) [reply source/common/grpc/common.cc]: done

File: source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc (hunk 3 above)
Comment (ascheglov) [reply source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc]: done

File: source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc (hunk 4 above)
Comment (ascheglov) [reply source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc]: done

File: source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc (hunk 5 above)
Comment (ascheglov) [reply source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc]: But it already uses `print_options_`.

Adding error_details.proto would be great, but I think it would better be done in a separate PR.

File: source/common/http/conn_manager_impl.cc (hunk 2 above)
Comment (ascheglov) [reply source/common/http/conn_manager_impl.cc]: I've removed the changes in HCM and disabled the feature in case when there is a separate trailer frame.

To sum it ip, an upstream has three ways to report an error:

1) Send a single header frame with end_stream flag which is also a trailer.
That's what happens when an unary function returns an error.

2) Send a header frame, send some data, and then send an error in a trailer.
We don't transcode the error into JSON because that would replace the data sent by upstream.

3) Send a header frame, and then send an error in a trailer.
This can happen when a gRPC sends metadata first, and then it encounters some error, e.g.
```
func (this *myServer) Func(...) (*pb.Ret, error) {
        ...
	grpc.SendHeader(ctx, someMetadata)
        ...
	return nil, someError
}
```
We don't support this yet, because HCM doesn't buffer data added from `encodeTrailers`.

File: api/envoy/config/filter/http/transcoder/v2/transcoder.proto [hunk 6]
```diff
@@ -120,4 +120,12 @@ message GrpcJsonTranscoder {
   // not know them beforehand. Otherwise use ``ignored_query_parameters``.
   // Defaults to false.
   bool ignore_unknown_query_parameters = 8;
+
+  // Whether to convert gRPC status headers to JSON.
+  // When trailer indicates a gRPC error and there was no HTTP body, take ``google.rpc.Status``
+  // from the ``grpc-status-details-bin`` header and use it as JSON body.
+  // If there was no such header, make ``google.rpc.Status`` out of the ``grpc-status`` and
+  // ``grpc-message`` headers.
+  // This also adds ``google.rpc.Status`` to user-provided protobuf descriptor.
```
[the remark this answers is not in the document]
Comment (ascheglov) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: I've removed this line since there is not need to tell users what they don't need to do, and added an example of what they have to do.

File: source/common/protobuf/protobuf.h [hunk 7]
```diff
@@ -7,6 +7,7 @@
 #include "google/protobuf/any.pb.h"
 #include "google/protobuf/descriptor.h"
 #include "google/protobuf/descriptor.pb.h"
+#include "google/protobuf/descriptor_database.h"
```
Comment (lizan) [inline source/common/protobuf/protobuf.h]: not used?

Comment (ascheglov) [reply source/common/protobuf/protobuf.h]: It's intentional, I use the `DescriptorPoolDatabase` in transcoder, but I cannot include this directly, as the linter says "unexpected direct dependency on google.protobuf, use the definitions in common/protobuf/protobuf.h instead."

Comment (lizan) [reply source/common/protobuf/protobuf.h]: Ah OK that's fine.

**Comment by lizan** [comment]
@htuch for API.

File: api/envoy/config/filter/http/transcoder/v2/transcoder.proto [hunk 8]
```diff
@@ -120,4 +120,25 @@ message GrpcJsonTranscoder {
...
+  //
+  // .. code-block:: proto
+  //
+  //     import "google/rpc/error_details.proto";
+  //
+  //     message Dummy {
+  //       google.rpc.RequestInfo request_info = 1;
+  //     }
+  //
+  // If a gRPC service uses the types from the ``google/rpc/error_details.proto``, its proto files
```
Comment (htuch) [inline api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: I'm not grokking the example or this paragraph. Where does `Dummy` appear? In config? On the wire?

Comment (lizan) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: In the proto generating the descriptor set for transcoding.

Comment (ascheglov) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: Docs in this file already have two examples (for the match_incoming_request_route and the ignored_query_parameters options) that show user proto files used for making their proto descriptor.
And this is just another example of what should be written in user proto files.

This `Dummy` type is not used anywhere, but it's required as its contents ensures dependencies on types that have to be in a proto descriptor set.

Comment (lizan) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: for api approval: @mattklein123 since @htuch is OOO, do you have suggestion here? IMO this is enough given the examples in other fields does similar thing.

Comment (mattklein123) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: TBH I don't understand this example either, but I don't have a lot of context. Perhaps you could describe what the output looks like given a particular response?

Comment (ascheglov) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: Here is some context:
Upstream server responds with an error in the following headers frame:
```
grpc-status: 5
grpc-status-details-bin: CAUSElJlc291cmNlIG5vdCBmb3VuZA
```
The grpc-status-details-bin header contains base64 encoded protobuf `google.rpc.Status` message. We transcode it into
```
HTTP/1.1 404 Not Found
grpc-status: 5
content-type: application/json
...

{"code":5,"message":"Resource not found"}
```

Now, `google.rpc.Status` has the optional "details" field, which can hold arbitrary user-defined  types. E.g. `grpc-status-details-bin: CAUSBUVycm9yGjYKKXR5cGUuZ29vZ2xlYXBpcy5jb20vaGVsbG93b3JsZC5IZWxsb1JlcGx5EgkKB2RldGFpbHM` will be transcoded into
```
{"code":5,"message":"Error","details":[{"@type":"type.googleapis.com/helloworld.HelloReply","message":"details"}]}
```

Since Envoy knows nothing about this `helloworld.HelloReply` type, it should be in the proto descriptor set provided via config. And the example says "make sure that your details types are in the the proto descriptor set". "If those details types aren't used in any message types of your service, make a dummy message type for them".

Comment (lizan) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: @ascheglov actually, I don't think you really need the message dummy, only a include of `error_details.proto` or just pass `error_details.proto` to protoc when you generate the descriptor should work. protoc doesn't drop unused message descriptors when it generate them.

Comment (mattklein123) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: Can you potentially just update the description/docs to read more like https://github.com/envoyproxy/envoy/pull/8009#discussion_r322780622? That makes sense to me.

File: include/envoy/http/header_map.h [hunk 9]
```diff
@@ -315,6 +315,7 @@ class HeaderEntry {
   HEADER_FUNC(GrpcAcceptEncoding)                                                                  \
   HEADER_FUNC(GrpcMessage)                                                                         \
   HEADER_FUNC(GrpcStatus)                                                                          \
+  HEADER_FUNC(GrpcStatusDetailsBin)                                                                \
```
Comment (mattklein123) [inline include/envoy/http/header_map.h]: perf nit: given that this header is only used in error cases, my preference would be to not look it up via O(1) and just have it looked up by name? @lizan any thoughts here?

Comment (lizan) [reply include/envoy/http/header_map.h]: Look up by name works for me, I don't have strong opinion. The downside of having headers here is more memory usage per request?

Comment (mattklein123) [reply include/envoy/http/header_map.h]: Yes, basically we have to allocate space and zero out the memory for every header map. It's not free. With that said, we don't really know what the cost is because we don't have a microbenchmark. @cpakulski is looking at this in the context of https://github.com/envoyproxy/envoy/issues/4815. cc @jmarantz @oschaaf

Comment (jmarantz) [reply include/envoy/http/header_map.h]: cc @asraa as well who is looking at refactoring header-map for improved fuzzing.

Comment (mattklein123) [reply include/envoy/http/header_map.h]: > looking at refactoring header-map for improved fuzzing

@asraa can we open a design proposal on that separately to discuss before doing a bunch of work? I think that would be optimal.

File: api/envoy/config/filter/http/transcoder/v2/transcoder.proto (hunk 8 above)
Comment (ascheglov) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: > @ascheglov actually, I don't think you really need the message dummy, only a include of `error_details.proto` or just pass `error_details.proto` to protoc when you generate the descriptor should work. protoc doesn't drop unused message descriptors when it generate them.

Yes, that's true. With `protoc --include_imports` it's enough to just add an import.

Comment (ascheglov) [reply api/envoy/config/filter/http/transcoder/v2/transcoder.proto]: @mattklein123 done

**Comment by mattklein123** [comment]
@itayd I think the API bot is stuck here for some reason

**Comment by lizan** [comment]
@itayd I'm about to merge this, lmk when you're done debugging the bot

**Comment by itayd** [comment]
sorry for the noise! but i found the repokitteh ownerscheck problem. thanks.
