### PR TITLE
stats: clear hot-restart parent contributions from child gauges when parent terminates.

### LINKED ISSUE #10806: Inconsistent gauges after hot-restart on endpoints /clusters and /stats/prometheus
*Description*:
After hot-restart, gauges, especially upstream_cx_active on /stats/prometheus endpoint, do not reset themselves. Values from previous instances are added to current. 
Sending POST to /reset_counters does not reset gauges either.

Should envoy behave like this?

It can be easily reproduced by checking /stats/prometheus metrics, before and after hot-restart and comparing them to cx_active returned /clusters admin endpoint

```
curl http://localhost:8001/stats/prometheus 2>/dev/null | grep 'upstream_cx_active
```

*Repro steps*:

* checkout branch hot_restart_container of respository https://github.com/andrzejwaw/envoy/tree/hot_restart_container

* in *envoy/examples/front-proxy* execute 
    ```docker-compose-up```
* send some request to services
    ```
    wrk -t12 -c400 -d30s http://localhost:8000/service/1
    ```
* check metrics:
    ```
    $ curl http://localhost:8001/stats/prometheus 2>/dev/null | grep 'upstream_cx_active' | grep service1
    envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 6
    $ curl http://localhost:8001/clusters 2>/dev/null | grep 'cx_active' | grep service1
    service1::192.168.128.3:80::cx_active::6
    ```
* make a hot-restart (send SIGHUP signal to hot-restarter.py process) and wait for it (up to one minute):
* check metrics:    
    **After hot-restart gauge upstream_cx from /stats/prometheus is inconsistent with cx_active from /clusters endpoint:**

    ```
    $ curl http://localhost:8001/stats/prometheus 2>/dev/null | grep 'upstream_cx_active' | grep service1
    envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 6

    $ curl http://localhost:8001/clusters 2>/dev/null | grep 'cx_active' | grep service1
    service1::192.168.128.3:80::cx_active::0
    ```
    **this makes it difficult to analyze the metrics**

* send more requests
    ```
    wrk -t12 -c400 -d30s http://localhost:8000/service/1
    ```
* check metrics:    
    ```
    $ curl http://localhost:8001/stats/prometheus 2>/dev/null | grep 'upstream_cx_active' | grep service1
    envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 12

    $ curl http://localhost:8001/clusters 2>/dev/null | grep 'cx_active' | grep service1
    service1::192.168.128.3:80::cx_active::6
    ```

I was expecting that after hot-restart both cx_active values from /stats/prometheus endpoint and /clusters endpoint will be equal to 0.

### PR DESCRIPTION
**Pull request by jmarantz**
Commit Message: A typical gauge tracks some in-progress count within an Envoy process, which is expected to rise and eventually fall to zero. During the hot-restart process, the child stats for Gauges with an ImportMode of Accumulate include the parent data. However, not all parent gauges get zeroed and clean out their contributions to the child gauges, so do so forcibly on parent termination.

One exception to this rule is `server.hot_restart_generation` which should accumulate over the generations, by definition, so a mechanism was added to allow retention of accumulated gauges. It's possible others may need this as well. Arguably `server.hot_restart_generation` should be a counter and not a gauge, but due to the way counters transmit latched values over the generations, this will not work as is.
Additional Description:
Risk Level: medium -- will change behavior of some gauges.
Testing: //test/...
Docs Changes: n/a
Release Notes: n/a
Fixes #10806

### CODE REVIEW

**Comment by jmarantz** [comment]
Matt -- PTAL at all these Accumulate -> NeverImport changes & let me know if these (some or all) make sense to you.

File: source/server/hot_restarting_child.cc [hunk 1]
```diff
@@ -80,19 +80,31 @@ void HotRestartingChild::sendParentTerminateRequest() {
...
-  // receive no more responses, including stats. So, now safe to forget our stat transferral state.
+
+  // Note that we the 'generation' counter needs to retain the contribution
+  // from the parent....
+  stat_merger_->retainParentGaugeValue(hot_restart_generation_stat_name_);
+
+  // Once setting parent_terminated_ == true, we can send no more hot restart
+  // RPCs, and therefore receive no more responses, including stats. We should
+  // also zero out parent-stat contribution to child gauges (see
+  // https://github.com/envoyproxy/envoy/issues/10800).
```
Comment (ramaraochavali) [inline source/server/hot_restarting_child.cc:91]: nit: You want to mention https://github.com/envoyproxy/envoy/issues/10806?

Comment (jmarantz) [reply source/server/hot_restarting_child.cc]: thanks; good catch.

File: include/envoy/config/grpc_mux.h [hunk 2]
```diff
@@ -16,7 +16,7 @@ namespace Config {
 #define ALL_CONTROL_PLANE_STATS(COUNTER, GAUGE)                                                    \
   COUNTER(rate_limit_enforced)                                                                     \
   GAUGE(connected_state, NeverImport)                                                              \
-  GAUGE(pending_requests, Accumulate)
+  GAUGE(pending_requests, NeverImport)
```
Comment (jmarantz) [inline include/envoy/config/grpc_mux.h:19]: note to reviewers: it is worth discussing the gauges changed to NeverImport from Accumulate in this PR. They were all needed due to the assertion added to Gauge::set(). If there are objections to these transformations we should discuss what the semantics of set() should be across hot-restart; we might need a new mode.

Comment (jmarantz) [reply include/envoy/config/grpc_mux.h:19]: I was thinking about this more; if we want to allow set() on accumulated gauges we probably need the Gauge to add a new data field for the value from the parent, and make Gauge::value() return the sum of the child & parent values. We could also make this memory-neutral when hot-restart is disabled with an alternate Gauge implementation in allocator_impl.cc.

Comment (mattklein123) [reply include/envoy/config/grpc_mux.h:19]: Why does this gauge use set though? That seems broken. I would expect this to accumulate? (It's not a crisis if it doesn't and we can TODO this to fix later to land this PR if needed.)

File: include/envoy/upstream/upstream.h [hunk 3]
```diff
@@ -591,8 +591,8 @@ class PrioritySet {
   GAUGE(membership_healthy, NeverImport)                                                           \
   GAUGE(membership_total, NeverImport)                                                             \
   GAUGE(upstream_cx_active, Accumulate)                                                            \
-  GAUGE(upstream_cx_rx_bytes_buffered, Accumulate)                                                 \
-  GAUGE(upstream_cx_tx_bytes_buffered, Accumulate)                                                 \
+  GAUGE(upstream_cx_rx_bytes_buffered, NeverImport)                                                \
+  GAUGE(upstream_cx_tx_bytes_buffered, NeverImport)                                                \
```
Comment (mattklein123) [inline include/envoy/upstream/upstream.h:595]: I feel like these should be accumulate. Do they use set just for convenience? It seems like the code could be changed to not use set?

File: include/envoy/upstream/upstream.h [hunk 4]
```diff
@@ -611,16 +611,16 @@ class PrioritySet {
...
+  OPEN_GAUGE(cx_open, NeverImport)                                                                 \
+  OPEN_GAUGE(cx_pool_open, NeverImport)                                                            \
+  OPEN_GAUGE(rq_open, NeverImport)                                                                 \
+  OPEN_GAUGE(rq_pending_open, NeverImport)                                                         \
+  OPEN_GAUGE(rq_retry_open, NeverImport)                                                           \
+  REMAINING_GAUGE(remaining_cx, NeverImport)                                                       \
+  REMAINING_GAUGE(remaining_cx_pools, NeverImport)                                                 \
+  REMAINING_GAUGE(remaining_pending, NeverImport)                                                  \
+  REMAINING_GAUGE(remaining_retries, NeverImport)                                                  \
+  REMAINING_GAUGE(remaining_rq, NeverImport)
```
Comment (mattklein123) [inline include/envoy/upstream/upstream.h:623]: I think these make sense as NeverImport, though there may be some loss of fidelity here that I think is worth some doc updates. @tonya11en wdyt?

File: source/common/stats/allocator_impl.cc [hunk 5]
```diff
@@ -178,6 +178,7 @@ class GaugeImpl : public StatsSharedImpl<Gauge> {
   void dec() override { sub(1); }
   void inc() override { add(1); }
   void set(uint64_t value) override {
+    ASSERT(importMode() != ImportMode::Accumulate, name());
```
Comment (mattklein123) [inline source/common/stats/allocator_impl.cc:181]: Can you add a short comment about why this is blocked?

File: source/common/stats/stat_merger.cc [hunk 6]
```diff
@@ -136,6 +136,23 @@ void StatMerger::mergeGauges(const Protobuf::Map<std::string, uint64_t>& gauges,
...
 }
 
+void StatMerger::retainParentGaugeValue(Stats::StatName gauge_name) {
+  parent_gauge_values_.erase(gauge_name);
+}
+
+void StatMerger::removeParentContributionToGauges() {
+  for (auto& iter : parent_gauge_values_) {
+    Gauge& gauge = temp_scope_->gaugeFromStatName(iter.first, Gauge::ImportMode::Accumulate);
+    if (gauge.importMode() == Gauge::ImportMode::NeverImport) {
```
Comment (mattklein123) [inline source/common/stats/stat_merger.cc:146]: Can you add some comments here? I assume this is the case where the gauge type has changed in the child?

File: source/common/stats/stat_merger.cc [hunk 7]
```diff
@@ -136,6 +136,23 @@ void StatMerger::mergeGauges(const Protobuf::Map<std::string, uint64_t>& gauges,
...
+      continue;
+    }
+
+    uint64_t parent_value = iter.second;
```
Comment (mattklein123) [inline source/common/stats/stat_merger.cc]: nit: const

File: source/common/stats/stat_merger.h [hunk 8]
```diff
@@ -42,12 +42,43 @@ class StatMerger {
...
+   * Merge the values of stats_proto into stats_store. Counters are always
+   * straightforward addition, while gauges default to addition but have
+   * exceptions.
+   *
+   * @param counter_deltas map of counter changes from parent
+   * @param counter_deltas map of gauge changes from parent
+   * @param dynamics information about which segments of the names are dynamic.
+   */
   void mergeStats(const Protobuf::Map<std::string, uint64_t>& counter_deltas,
                   const Protobuf::Map<std::string, uint64_t>& gauges,
```
Comment (mattklein123) [inline source/common/stats/stat_merger.h:55]: This is pre-existing code, but uint64_t here is a bit odd. For subtraction does the rely on wrapping? Can you maybe update the comments to make this more clear? Same elsewhere where this applies.

File: source/common/stats/stat_merger.h [hunk 9]
```diff
@@ -42,12 +42,43 @@ class StatMerger {
...
+   * should be zero. But depending on the timing of the stat-merger
+   * communication shutdown and other shutdown activities on the parent, the
+   * gauges may not all be zero yet. So simply erase all the parent
+   * contributions.
+   */
+  void removeParentContributionToGauges();
+
+  /**
+   * Indicates that a gauge's value from the hot-restart parent should be
+   * retained, combining it with the child data, By default, data is transferred
```
Comment (mattklein123) [inline source/common/stats/stat_merger.h:69]:
```suggestion
   * retained, combining it with the child data. By default, data is transferred
```

File: source/common/upstream/health_checker_base_impl.h [hunk 10]
```diff
@@ -155,8 +154,6 @@ class HealthCheckerImplBase : public HealthChecker,
   const std::chrono::milliseconds unhealthy_edge_interval_;
   const std::chrono::milliseconds healthy_edge_interval_;
   std::unordered_map<HostSharedPtr, ActiveHealthCheckSessionPtr> active_sessions_;
-  uint64_t local_process_healthy_{};
-  uint64_t local_process_degraded_{};
```
Comment (mattklein123) [inline source/common/upstream/health_checker_base_impl.h:159]: Awesome cleanup. :)

File: source/common/upstream/maglev_lb.h [hunk 11]
```diff
@@ -14,8 +14,8 @@ namespace Upstream {
  * All Maglev load balancer stats. @see stats_macros.h
  */
 #define ALL_MAGLEV_LOAD_BALANCER_STATS(GAUGE)                                                      \
-  GAUGE(max_entries_per_host, Accumulate)                                                          \
-  GAUGE(min_entries_per_host, Accumulate)
+  GAUGE(max_entries_per_host, NeverImport)                                                         \
+  GAUGE(min_entries_per_host, NeverImport)
```
Comment (mattklein123) [inline source/common/upstream/maglev_lb.h:18]: This is not a comment about you, and more about the complexity of this entire situation, but I think we have a 0% success rate with landing changes like this without a regression. I think once we decide on the approach can we land the Accumulate -> NeverImport changes in an independent PR?

File: source/server/hot_restarting_child.cc [hunk 12]
```diff
@@ -80,19 +80,31 @@ void HotRestartingChild::sendParentTerminateRequest() {
...
+
+  // Note that we the 'generation' counter needs to retain the contribution
+  // from the parent....
+  stat_merger_->retainParentGaugeValue(hot_restart_generation_stat_name_);
+
+  // Once setting parent_terminated_ == true, we can send no more hot restart
+  // RPCs, and therefore receive no more responses, including stats. We should
+  // also zero out parent-stat contribution to child gauges (see
+  // https://github.com/envoyproxy/envoy/issues/10806).
+  stat_merger_->removeParentContributionToGauges();
```
Comment (mattklein123) [inline source/server/hot_restarting_child.cc:92]: nit: can we just do this in the stat merger destructor? I don't feel strongly about it but seems like we won't need this method.

File: source/server/server.h [hunk 13]
```diff
@@ -56,18 +56,18 @@ namespace Server {
...
   GAUGE(hot_restart_epoch, NeverImport)                                                            \
   /* hot_restart_generation is an Accumulate gauge; we omit it here for testing dynamics. */       \
   GAUGE(live, NeverImport)                                                                         \
-  GAUGE(memory_allocated, Accumulate)                                                              \
-  GAUGE(memory_heap_size, Accumulate)                                                              \
-  GAUGE(memory_physical_size, Accumulate)                                                          \
-  GAUGE(parent_connections, Accumulate)                                                            \
+  GAUGE(memory_allocated, NeverImport)                                                             \
+  GAUGE(memory_heap_size, NeverImport)                                                             \
+  GAUGE(memory_physical_size, NeverImport)                                                         \
```
Comment (mattklein123) [inline source/server/server.h:65]: I think we probbaly want this accumulated somehow...

File: source/server/server.h [hunk 14]
```diff
@@ -56,18 +56,18 @@ namespace Server {
...
+  GAUGE(parent_connections, NeverImport)                                                           \
```
Comment (mattklein123) [inline source/server/server.h:66]: This one I think is definitely a regression. We for sure want to import this.

File: source/server/server.h [hunk 15]
```diff
@@ -56,18 +56,18 @@ namespace Server {
...
   GAUGE(state, NeverImport)                                                                        \
   GAUGE(stats_recent_lookups, NeverImport)                                                         \
-  GAUGE(total_connections, Accumulate)                                                             \
-  GAUGE(uptime, Accumulate)                                                                        \
+  GAUGE(total_connections, NeverImport)                                                            \
```
Comment (mattklein123) [inline source/server/server.h:69]: Definitely accumulate.

File: include/envoy/upstream/upstream.h (hunk 4 above)
Comment (tonya11en) [reply include/envoy/upstream/upstream.h:623]: Unless someone increased the global request timeout, it should only be inaccurate for ~15 seconds in the absolute worst case. +1 on the doc updates.

**Comment by jmarantz** [comment]
Overall it seems pretty clear we need to be able to support set() on gauges that will also get parent contributions, and we can iterate on which ones that needs to apply to. There are 2 variants on approach I can think of:

1. add a new field to GaugeImpl to track parent/child contributions separately (simple, adds memory overhead)
2. add a new subclass to GaugeImpl used only when the Stats::Allocator is told to go into that mode, which adds the new field (adds complexity but it's localized to allocator_impl.cc)

Are there other options? Or preference between these 2?

**Comment by mattklein123** [comment]
> Are there other options? Or preference between these 2?

Either of these sound fine to me. Overall the number of gauges is much smaller than counters, so I doubt the memory overhead matters so (1) is likely fine and we can always switch to (2) later?

File: include/envoy/config/grpc_mux.h (hunk 2 above)
Comment (jmarantz) [reply include/envoy/config/grpc_mux.h]: i think there's a few places where the data is tracked by some other non-stat variable, and then copied into the stat from time to time.

**Comment by jmarantz** [comment]
Thanks for the feedback; I'm experimenting here with a strategy where we don't change any import-modes, but just make Accumulate work with set(), per above, using the simplest model. It turns out we did not detect any memory regression with this, possibly because we don't really have per-cluster gauges.

This should hopefully make the change less petrifying, though there are still some cleanups in the current state of the PR.

PTAL and let me know if you like this direction better.

File: include/envoy/stats/stats.h [hunk 16]
```diff
@@ -136,6 +136,7 @@ class Gauge : public Metric {
   virtual void set(uint64_t value) PURE;
   virtual void sub(uint64_t amount) PURE;
   virtual uint64_t value() const PURE;
+  virtual void setParentValue(uint64_t) {}
```
Comment (mattklein123) [inline include/envoy/stats/stats.h:139]: nit: I think it would be better if this were pure? Might be also worth a comment since not obvious like the others?

File: source/common/stats/stat_merger.h (hunk 8 above)
Comment (mattklein123) [reply source/common/stats/stat_merger.h:55]: Sorry nevermind this is not a delta, I see.

File: source/common/stats/stat_merger.h (hunk 9 above)
Comment (mattklein123) [reply source/common/stats/stat_merger.h:69]: ping

File: source/common/upstream/health_checker_base_impl.cc [hunk 17]
```diff
@@ -78,33 +78,19 @@ HealthCheckerImplBase::~HealthCheckerImplBase() {
   }
 }
 
-void HealthCheckerImplBase::decHealthy() {
-  ASSERT(local_process_healthy_ > 0);
```
Comment (mattklein123) [inline source/common/upstream/health_checker_base_impl.cc:82]: I see now that these stats are NeverImport, so is this just a cleanup since it basically does nothing? I think we can kill the member var also?

**Comment by jmarantz** [comment]
Good I will fix the nits... Just wanted to get closure on direction first.

The health check stats can be simplified but I think that can be a separate
pr.

File: include/envoy/stats/stats.h (hunk 16 above)
Comment (jmarantz) [reply include/envoy/stats/stats.h]: yup, was just doing the minimal edit to get a sense of direction. fixed.

File: source/common/stats/stat_merger.h (hunk 9 above)
Comment (jmarantz) [reply source/common/stats/stat_merger.h]: done, thanks.

File: source/common/upstream/health_checker_base_impl.cc (hunk 17 above)
Comment (jmarantz) [reply source/common/upstream/health_checker_base_impl.cc]: oh I meant to back this out and do it as a separate PR.

File: source/server/hot_restarting_child.cc (hunk 12 above)
Comment (jmarantz) [reply source/server/hot_restarting_child.cc]: yes...it changed the semantics of one of the tests a bit, but it's fine.

File: source/common/stats/stat_merger.cc [hunk 18]
```diff
@@ -7,6 +7,19 @@ namespace Stats {
...
+  // By the time a parent exits, all its contributions to accumulated gauges
+  // should be zero. But depending on the timing of the stat-merger
+  // communication shutdown and other shutdown activities on the parent, the
+  // gauges may not all be zero yet. So simply erase all the parent
+  // contributions.
+  for (StatName stat_name : parent_gauges_) {
+    Gauge& gauge = temp_scope_->gaugeFromStatName(stat_name, Gauge::ImportMode::Uninitialized);
+    gauge.setParentValue(0);
+  }
+  parent_gauges_.clear();
```
Comment (mattklein123) [inline source/common/stats/stat_merger.cc:20]: nit: not needed in destructor context.

File: source/server/hot_restarting_child.cc [hunk 19]
```diff
@@ -80,19 +80,25 @@ void HotRestartingChild::sendParentTerminateRequest() {
   wrapped_request.mutable_request()->mutable_terminate();
   sendHotRestartMessage(parent_address_, wrapped_request);
   parent_terminated_ = true;
-  // Once setting parent_terminated_ == true, we can send no more hot restart RPCs, and therefore
-  // receive no more responses, including stats. So, now safe to forget our stat transferral state.
+
+  // Note that the 'generation' counter needs to retain the contribution from
+  // the parent....
```
Comment (mattklein123) [inline source/server/hot_restarting_child.cc:85]:
```suggestion
  // the parent.
```

File: source/common/stats/stat_merger.cc (hunk 18 above)
Comment (jmarantz) [reply source/common/stats/stat_merger.cc]: done

File: source/server/hot_restarting_child.cc (hunk 19 above)
Comment (jmarantz) [reply source/server/hot_restarting_child.cc]: done

**Comment by slonka** [comment]
@mattklein123 can you review this again? This fix would be really useful for us.

File: test/integration/hotrestart_test.sh [hunk 20]
```diff
@@ -152,13 +153,15 @@ function run_testsuite() {
...
   enableHeapCheck
 
+  # For SERVER_1, we set a drain timer, so it exits a few seconds after SERVER_2 starts.
   start_test Starting epoch 1
   ADMIN_ADDRESS_PATH_1="${TEST_TMPDIR}"/admin.1."${TEST_INDEX}".address
   run_in_background_saving_pid "${ENVOY_BIN}" -c "${UPDATED_HOT_RESTART_JSON}" \
       --restart-epoch 1 --base-id "${BASE_ID}" --service-cluster cluster --service-node node \
-      --use-fake-symbol-table "$FAKE_SYMBOL_TABLE" --admin-address-path "${ADMIN_ADDRESS_PATH_1}"
+      --use-fake-symbol-table "$FAKE_SYMBOL_TABLE" --admin-address-path "${ADMIN_ADDRESS_PATH_1}" \
+      --drain-time-s 2
```
Comment (mattklein123) [inline test/integration/hotrestart_test.sh:162]: FWIW I don't think this actually impacts your test, since parent-shutdown-time is really what causes the exit. This just governs the drain close ramp time which doesn't matter in this case. Maybe remove this just to make the test more clear? Same in comments below if you agree.

Comment (jmarantz) [reply test/integration/hotrestart_test.sh:162]: agreed; will remove.

**Comment by jmarantz** [comment]
I need to get better at 'nc'...I tried something with another gauge but it wound up not being a good negative tests because even in the existing tests I think depending on timing you can wind up having the server decrement its gauges as it cleans up and they may be sent over in time.

Is it worth adding in a gauge into prod just to test this, maybe parallel to server.live, which is NeverImport. The new one would be Accumulate, would never decrements, so we expect it to be 2 during hot-restart, and (if this code is working) become 1 after the parent dies?

**Comment by mattklein123** [comment]
> Is it worth adding in a gauge into prod just to test this, maybe parallel to server.live, which is NeverImport. The new one would be Accumulate, would never decrements, so we expect it to be 2 during hot-restart, and (if this code is working) become 1 after the parent dies?

This doesn't thrill me, but given how high the regression risk here is, it seems like we should be able to test it. I wonder could this somehow just be done in the test binary we use for hot restart? Right now we use the real exe, but is there some way we could stub something out and link an exe that would allow us to hook this and add a testing stat?

**Comment by jmarantz** [comment]
@mattklein123 thanks for the idea of forking the binary; I think that wasn't too bad. I thought of adding some kind of hook to avoid duplicating main.cc, but let's see if we can avoid that for now.

File: source/server/hot_restarting_base.cc [hunk 21]
```diff
@@ -224,5 +225,21 @@ std::unique_ptr<HotRestartMessage> HotRestartingBase::receiveHotRestartMessage(B
   return ret;
 }
 
+Stats::Gauge& HotRestartingBase::hotRestartGeneration(Stats::Scope& scope) {
```
Comment (mattklein123) [inline source/server/hot_restarting_base.cc:228]: Do you think this gauge has any real use? I'm actually wondering with the test binary if we should just delete it and put a similar test gauge there?

File: test/integration/hotrestart_main.cc [hunk 22]
```diff
@@ -0,0 +1,55 @@
...
+    // functional difference with source/exe/main.cc.
+    Envoy::Server::Instance* server = main_common->server();
+    if (server != nullptr) {
+      // Creates a gauge that will be incremented once and then never touched. This is
+      // for testing parent-gauge accumulation in hot_restart_test.sh.
+      Envoy::Stats::Utility::gaugeFromElements(server->stats(),
+                                               {Envoy::Stats::DynamicName("hotrestart_test_gauge")},
+                                               Envoy::Stats::Gauge::ImportMode::Accumulate)
+          .inc();
+    }
```
Comment (mattklein123) [inline test/integration/hotrestart_main.cc:41]: Instead of copying the entire body of main, wdyt about just having a utility helper that takes an optional "post server create" lambda that can be null in the real impl? That would avoid all of this copying and I think be pretty trivial to do?

File: test/integration/hotrestart_test.sh [hunk 23]
```diff
@@ -1,6 +1,13 @@
 #!/bin/bash
 
+# For this test we use a slightly modiified test binary, based on
+# source/exe/enovy-static. If this starts failing to run or build, ensure that
+# source/exe/main.cc and ./hotrestart_main.cc have not diverged except for
+# adding the new gauge.
+export ENVOY_BIN="${TEST_SRCDIR}"/envoy/test/integration/hotrestart_main
 source "$TEST_SRCDIR/envoy/test/integration/test_utility.sh"
+echo ENVOY_BIN=${ENVOY_BIN}
```
Comment (mattklein123) [inline test/integration/hotrestart_test.sh:9]: ?

File: test/integration/hotrestart_test.sh [hunk 24]
```diff
@@ -174,18 +194,59 @@ function run_testsuite() {
...
+
+  # Now wait for the SERVER_0 to exit. It should occur immediately when SERVER_2 starts, as
+  # SERVER_1 will terminate SERVER_0 when it becomes the parent.
+  start_test Waiting for epoch 0 to finish.
+  echo time wait ${SERVER_0_PID}
+  time wait ${SERVER_0_PID}
+  [[ $? == 0 ]]
+
+  # Then wait for the SERVER_1 to exit, which should happen within a few seconds
+  # due to '--parent-shutdown-time-s 3' on SERVER_2, and '--drain-time-s 2' on
```
Comment (mattklein123) [inline test/integration/hotrestart_test.sh:224]: comment out of date (--drain-time-s)

File: test/integration/hotrestart_main.cc (hunk 22 above)
Comment (jmarantz) [reply test/integration/hotrestart_main.cc:41]: where would I register this post-server-create lambda? in a static ctor?

another thing I thought of, that wouldn't be too cumbersome and wouldn't affect prod execution flow, would be to move the contents of main.cc to main.h, and have in it:

```
  main_common = std::make_unique<Envoy::MainCommon>(argc, argv);
#ifdef POST_SERVER_CREATE_HOOK
  POST_SERVER_CREATE_HOOK(main_common->server())
#endif
```

Then main.cc would just have 
```
#include "source/exe/main.h"
```

WDYT?

Comment (mattklein123) [reply test/integration/hotrestart_main.cc:41]: I just meant something like this:
```
int main_helper(int argc, char** argv, std::function<void(Server::Instance&)> post_server_create) {
  ... What we do now
}

int main(int argc, char** argv) {
  return main_helper(argc, argv, nullptr);
}

int hot_restart_main(int argc, char** argv) {
  return main_helper(argc, argv, [](Server::Instance&) { ... });
}

?
```

Comment (jmarantz) [reply test/integration/hotrestart_main.cc:41]: I'm OK with that but I feel like this makes there be too many levels of "main" and I'd want to put this into MainCommon.

I feel like that will grow into a larger refactor and wonder if you'd be OK with the duplicated code for now and a TODO to refactor this into MainCommon?

Comment (mattklein123) [reply test/integration/hotrestart_main.cc:41]: Sure that's fine to take a TODO or it doesn't seem too hard to just do it in MainCommon now but up to you.

File: source/server/hot_restarting_base.cc (hunk 21 above)
Comment (jmarantz) [reply source/server/hot_restarting_base.cc:228]: At the time we added it, I remember discussing whether we should change infrastructure to use this and drop the manually maintained 'epoch'. I'm fine punting this one and relying on epic, but it's up to you.

But one thing I want to avoid is making that change in the same PR where we fix a functional bug. WDYT?

File: test/integration/hotrestart_main.cc (hunk 22 above)
Comment (jmarantz) [reply test/integration/hotrestart_main.cc:44]: I've added a TODO and opened a thread with the absl communithy about the implications of initializing the symbolizer indirectly from main().

File: test/integration/hotrestart_test.sh (hunk 23 above)
Comment (jmarantz) [reply test/integration/hotrestart_test.sh]: debug detritus; removed.

File: test/integration/hotrestart_test.sh (hunk 24 above)
Comment (jmarantz) [reply test/integration/hotrestart_test.sh]: done

File: source/common/stats/stat_merger.h [hunk 25]
```diff
@@ -41,20 +41,43 @@ class StatMerger {
...
 
-  // Merge the values of stats_proto into stats_store. Counters are always straightforward
-  // addition, while gauges default to addition but have exceptions.
+  /**
+   * Merge the values of stats_proto into stats_store. Counters are always
+   * straightforward addition, while gauges default to addition but have
+   * exceptions.
+   *
+   * @param counter_deltas map of counter changes from parent
+   * @param counter_deltas map of gauge changes from parent
```
Comment (mattklein123) [inline source/common/stats/stat_merger.h:52]: typo. I think this is gauge values also?

File: source/server/hot_restarting_base.cc (hunk 21 above)
Comment (mattklein123) [reply source/server/hot_restarting_base.cc:228]: Sure that's fine can discuss in a different PR.

File: test/integration/hotrestart_main.cc [hunk 26]
```diff
@@ -0,0 +1,58 @@
...
+/**
+ * Custom main() for hotrestart_test. This should be identical to
+ * source/exe/main.cc, except for the registration and increment of a new gauge
+ * specifically for hot_restart.test.sh.
+ *
+ * If this test starts failing to run or build, please ensure that all changes
+ * from source/exe/main.cc are incorporated in this file.
+ *
+ * TODO(jmarantz): factor out this code into MainCommon to avoid duplication,
+ * noting that absl::InitializeSymbolizer may want to be directly by main().
```
Comment (mattklein123) [inline test/integration/hotrestart_main.cc:18]:
```suggestion
 * noting that absl::InitializeSymbolizer may want to be directly called by main().
```

File: source/common/stats/stat_merger.h (hunk 25 above)
Comment (jmarantz) [reply source/common/stats/stat_merger.h:52]: Yes that was a typo; fixing.

File: test/integration/hotrestart_main.cc (hunk 26 above)
Comment (jmarantz) [reply test/integration/hotrestart_main.cc]: I've gotten confirmation from the absl team that running InitializeSymbolizer in a helper is OK, so I went ahead and did the TOOD and remove the comment you fixed here.

File: source/exe/main_common.h [hunk 27]
```diff
@@ -133,6 +137,7 @@ class MainCommon {
   DefaultListenerHooks default_listener_hooks_;
   ProdComponentFactory prod_component_factory_;
   MainCommonBase base_;
+  PostServerHook post_server_hook_;
```
Comment (mattklein123) [inline source/exe/main_common.h:140]: I think this is unused?
