### PR TITLE
re-enable runtime guard envoy_reloadable_features_quic_defer_logging_to_ack_listener

### LINKED ISSUE #29930: http3 access_log omissions
*Title*: *http3 access_log omissions*

*Description*:
We found when we sent 20 successfully completed test requests to an http3 endpoint, it was logging only 5-10 of them.

In a slack thread in envoy-dev, Alyssa pointed at #23648 which has a runtime flag in it; we tried changing that runtime flag to false from its default of true, and the issue was remedied.

It was not easy to reproduce this issue in other contexts - when I tried to repro in an integration test, logging was complete regardless of the flag. The current hypothesis is that the test client was terminating racily-before sending the 'ack' for the requests, so when it was sent the log entry appears, but when there was no 'ack' the log entry is (incorrectly) dropped. In the integration test, since the client was local, perhaps the race was always being won by the sending of the loopback packet.

I believe the behavior should be that, in the event of the final ack (perhaps even several acks) being dropped, the log should still record success after a short timeout.

@RyanTheOptimist @pksohn

### PR DESCRIPTION
**Pull request by pksohn**
Should finally close out https://github.com/envoyproxy/envoy/issues/29930.

Commit Message: re-enable runtime guard envoy_reloadable_features_quic_defer_logging_to_ack_listener
Additional Description: 
Risk Level: low
Testing: integration tests already exist for this feature (see quic_http_integration_test)
Docs Changes: N/A
Release Notes: N/A
Fixes  #29930

### CODE REVIEW

**Review by RyanTheOptimist — DISMISSED** [review]

**Comment by RyanTheOptimist** [comment]
@pksohn There appear to be several failing tests here. Any idea why?

https://github.com/envoyproxy/envoy/actions/runs/16323898629/job/46108859297

**Comment by pksohn** [comment]
Sorry for the delay, working on it.

File: test/integration/quic_http_integration_test.cc [hunk 1]
```diff
@@ -789,8 +789,6 @@ TEST_P(QuicHttpIntegrationTest, MultipleNetworkFilters) {
 }
 
 TEST_P(QuicHttpIntegrationTest, DeferredLogging) {
-  config_helper_.addRuntimeOverride("envoy.reloadable_features.quic_defer_logging_to_ack_listener",
```
Comment (danzh2010) [inline test/integration/quic_http_integration_test.cc]: Please keep the RUNTIME explicitly enabled for these tests in case the RUNTIME needs to be flipped to false again.

**Comment by pksohn** [comment]
/assign @yanavlasov

Would you mind taking a look?

**Review by yanavlasov — APPROVED** [review]
