### PR TITLE
oauth2: set accept header on access_token request

### LINKED ISSUE #14537: [OAuth2] Missing "accept" header in access_token request
*Title*: *[OAuth2] Missing "accept" header in access_token request*

*Description*:
The [OAuth2 HTTP filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) does not set the "Accept" header, but expects the server to return JSON.

This behavior is incompatible with GitHub's implementation of OAuth2: [GitHub web application flow](https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#web-application-flow). It says:

> By default, the response takes the following form:
>
> access_token=e72e16c7e42f292c6912e7710c838347ae178b4a&token_type=bearer
>
> You can also receive the content in different formats depending on the Accept header to `application/json` 

GitHub will return a form / urlencoded response body that Envoy fails to interpret as JSON.

This traces back the OAuth2 client implementation, which fails to set the `Accept` header.

https://github.com/envoyproxy/envoy/blob/dd0befa3e1e55e408329c7fb7356a84462416b02/source/extensions/filters/http/oauth2/oauth_client.h#L90-L94

*Repro steps*:
1. Set up OAuth2 filter [according to docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter)
2. Configure a GitHub OAuth app

*Config*:
not relevant

*Logs*:
```
[2020-12-30 00:10:03.907][122603][debug][upstream] [external/envoy/source/extensions/filters/http/oauth2/oauth_client.cc:43] Dispatching OAuth request for access token.                                                                                                
[2020-12-30 00:10:03.907][122603][debug][router] [external/envoy/source/common/router/router.cc:425] [C0][S5590288971988059178] cluster 'github-oauth' match for URL '/login/oauth/access_token'                                                                        
[2020-12-30 00:10:03.907][122603][debug][router] [external/envoy/source/common/router/router.cc:582] [C0][S5590288971988059178] router decoding headers:                                                                                                                
':path', '/login/oauth/access_token'                                                                                                
':authority', 'github.com'                                                                                                          
':method', 'POST'                                                                                                                   
':scheme', 'https'                                                                                                                  
'content-type', 'application/x-www-form-urlencoded'                                                                                 
'x-envoy-internal', 'true'                                                                                                          
'x-forwarded-for', <redacted>                                                                                                 
'x-envoy-expected-rq-timeout-ms', '3000'                                                                                            
```

...

```
[2020-12-30 00:10:04.474][122603][debug][client] [external/envoy/source/common/http/codec_client.cc:112] [C1] response complete
[2020-12-30 00:10:04.475][122603][debug][upstream] [external/envoy/source/extensions/filters/http/oauth2/oauth_client.cc:83] Error parsing response body, received exception: Unable to parse JSON as proto (INVALID_ARGUMENT:Unexpected token.
access_token=xxxxx
^): access_token=xxxxxxxxxxxxxxxxxxxxxxx&scope=user&token_type=bearer
[2020-12-30 00:10:04.475][122603][debug][upstream] [external/envoy/source/extensions/filters/http/oauth2/oauth_client.cc:84] Response body: access_token=xxxxxxxxxxxxxxxxxxxxxxx&scope=user&token_type=bearer
```

On the bright side, Envoy is nearly able to complete an SSO flow with GitHub, it just fails to parse the last response. Incredible job by the devs of this plugin. 🙌🏻

### PR DESCRIPTION
**Pull request by terorie**
Signed-off-by: Richard Patel <me@terorie.dev>
Co-authored-by: Dhi Aurrahman <dio@tetrate.io>

Commit Message: oauth2: set accept header on access_token request
Additional Description: Fixes compatibility with OAuth 2.0 implementations that do not respond to token requests with JSON by default, e.g. GitHub
Risk Level: Low
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
Fixes #14537

### CODE REVIEW

**Review by dio — CHANGES_REQUESTED** [review]
Thanks for working on this! Some suggestions:

File: source/extensions/filters/http/oauth2/oauth_client.h [hunk 1]
```diff
@@ -91,6 +91,7 @@ class OAuth2ClientImpl : public OAuth2Client, Logger::Loggable<Logger::Id::upstr
     auto request = Http::Utility::prepareHeaders(uri_);
     request->headers().setReferenceMethod(Http::Headers::get().MethodValues.Post);
     request->headers().setContentType(Http::Headers::get().ContentTypeValues.FormUrlEncoded);
+    request->headers().addCopy("accept", "application/json");
```
Comment (dio) [inline source/extensions/filters/http/oauth2/oauth_client.h:94]: Seems like:

```
    request->headers().setReferenceMethod(Http::Headers::get().MethodValues.Post);
    request->headers().setReferenceContentType(
        Http::Headers::get().ContentTypeValues.FormUrlEncoded);
    request->headers().addReference(Http::CustomHeaders::get().Accept,
                                    Http::Headers::get().ContentTypeValues.Json);

```

While you're here probably we can set that `setContentType` to `setReferenceContentType`.

And we can add test to: test/extensions/filters/http/oauth2/oauth_test.cc

e.g. in `TEST_F(OAuth2ClientTest, RequestAccessTokenSuccess) {`.

```cpp
  EXPECT_CALL(cm_.thread_local_cluster_.async_client_, send_(_, _, _))
      .WillRepeatedly(Invoke([&](Http::RequestMessagePtr& message, Http::AsyncClient::Callbacks& cb,
                                 const Http::AsyncClient::RequestOptions&)
                                 -> Http::AsyncClient::Request* {
        EXPECT_FALSE(message->headers().get(Http::CustomHeaders::get().Accept).empty());
        EXPECT_EQ(
            message->headers().get(Http::CustomHeaders::get().Accept)[0]->value().getStringView(),
            Http::Headers::get().ContentTypeValues.Json);
        callbacks_.push_back(&cb);
        return &request_;
      }));
```

**Review by dio — CHANGES_REQUESTED** [review]

File: source/extensions/filters/http/oauth2/oauth_client.h (hunk 1 above)
Comment (terorie) [reply source/extensions/filters/http/oauth2/oauth_client.h]: Thanks for the help!

I applied that almost exactly, but I had to change the Accept header value count assertion (`empty()`) from `ASSERT_FALSE` to `EXPECT_FALSE`, otherwise it wouldn't compile, probably because it's a lambda. But that also means the testing code is going to do an out-of-bounds array access in the line below if the accept header is not set. 


https://github.com/envoyproxy/envoy/blob/4d9fa702209a00cd1d9b407048af075d5c620435/test/extensions/filters/http/oauth2/oauth_test.cc#L85-L87

Do you have a better idea how to do this?

Sorry, for not getting to this sooner. I took me a while to find a machine that is big enough to run the Envoy unit tests without crashing :P
image

Comment (terorie) [reply source/extensions/filters/http/oauth2/oauth_client.h]: Would this work using short-circuit evaluation?

```c++
EXPECT_FALSE(
    message->headers().get(Http::CustomHeaders::get().Accept).empty() ||
    message->headers().get(Http::CustomHeaders::get().Accept)[0]->value().getStringView() !=
        Http::Headers::get().ContentTypeValues.Json);
```

File: test/extensions/filters/http/oauth2/oauth_test.cc [hunk 2]
```diff
@@ -79,12 +79,16 @@ TEST_F(OAuth2ClientTest, RequestAccessTokenSuccess) {
...
-      .WillRepeatedly(
-          Invoke([&](Http::RequestMessagePtr&, Http::AsyncClient::Callbacks& cb,
-                     const Http::AsyncClient::RequestOptions&) -> Http::AsyncClient::Request* {
-            callbacks_.push_back(&cb);
-            return &request_;
-          }));
+      .WillRepeatedly(Invoke([&](Http::RequestMessagePtr& message, Http::AsyncClient::Callbacks& cb,
+                                 const Http::AsyncClient::RequestOptions&)
+                                 -> Http::AsyncClient::Request* {
+        EXPECT_FALSE(message->headers().get(Http::CustomHeaders::get().Accept).empty());
```
Comment (dio) [inline test/extensions/filters/http/oauth2/oauth_test.cc:85]: I think this is fine, yeah. To make it complete, should we add checks for all the expected headers too here (including content-type, etc)?

File: source/extensions/filters/http/oauth2/oauth_client.h [hunk 3]
```diff
@@ -90,7 +90,10 @@ class OAuth2ClientImpl : public OAuth2Client, Logger::Loggable<Logger::Id::upstr
   Http::RequestMessagePtr createPostRequest() {
     auto request = Http::Utility::prepareHeaders(uri_);
     request->headers().setReferenceMethod(Http::Headers::get().MethodValues.Post);
-    request->headers().setContentType(Http::Headers::get().ContentTypeValues.FormUrlEncoded);
+    request->headers().setReferenceContentType(
+        Http::Headers::get().ContentTypeValues.FormUrlEncoded);
+    request->headers().setReference(Http::CustomHeaders::get().Accept,
+                                    Http::Headers::get().ContentTypeValues.Json);
```
Comment (rgs1) [inline source/extensions/filters/http/oauth2/oauth_client.h:96]: Hmm do we want to make this configurable but on by default?

cc: @williamsfu99

**Review by rgs1 — COMMENTED** [review]
LGTM, just a question as to whether this should be configurable (in case there's an implementation out there that would prefer this header not to be set).

File: source/extensions/filters/http/oauth2/oauth_client.h (hunk 3 above)
Comment (rgs1) [reply source/extensions/filters/http/oauth2/oauth_client.h:96]: cc: @jparise

Comment (dio) [reply source/extensions/filters/http/oauth2/oauth_client.h:96]: As a note, the current client expects (to parse) JSON payload from the server: https://github.com/envoyproxy/envoy/blob/4d9fa702209a00cd1d9b407048af075d5c620435/source/extensions/filters/http/oauth2/oauth_client.cc#L81

Comment (terorie) [reply source/extensions/filters/http/oauth2/oauth_client.h:96]: > Hmm do we want to make this configurable but on by default?

@rgs1 If Envoy is aiming for strict RFC 6749 compliance, I don't think it needs to be configurable. I'm not aware of a version of the OAuth 2.0 standard that allows `FormUrlEncoded` access token responses but I don't have much experience with OAuth to be honest. 

https://tools.ietf.org/html/rfc6749#section-4.1.4 states:
>  If the access token request is valid and authorized, the
   authorization server issues an access token and optional refresh
   token as described in Section 5.1.

https://tools.ietf.org/html/rfc6749#section-5.1 states:
> The authorization server issues an access token and optional refresh token, and constructs the response by adding the following parameters to the entity-body of the HTTP response with a 200 (OK) status code:
> [ ... ]
> The parameters are included in the entity-body of the HTTP response using the "application/json" media type as defined by [RFC4627].

I just noticed this also means Envoy's code was never really wrong to begin with. It's reasonable to expect a JSON response if the RFC says so, but of course setting the Accept header is nicer. GitHub just happened to violate the RFC by defaulting to `FormUrlEncoded` instead of JSON.

**Comment by terorie** [comment]
> in case there's an implementation out there that would prefer this header not to be set

Is there an informal list of OAuth 2.0 providers for which we aim for compatibility? I'm happy to set up some end-to-end tests so we can verify this plugin works in the real world. Reviewing provider documentation for obvious RFC 6749 violations (like GitHub returning a FormUrlEncoded access token response) also can't hurt. 

In case there's no such list, here's a start:
* Amazon.com
* Battle.net
* Discord
* Facebook
* GitHub
* GitLab
* Google
* Microsoft
* Okta
* Reddit
* Twitch

File: source/extensions/filters/http/oauth2/oauth_client.h (hunk 3 above)
Comment (rgs1) [reply source/extensions/filters/http/oauth2/oauth_client.h:96]: Awesome, thanks for the reply. Mind adding a summary of the above with those links into the code as a comment?

**Comment by rgs1** [comment]
> Is there an informal list of OAuth 2.0 providers for which we aim for compatibility? 

There isn't, I think we'll learn as the filter gains more usage. 

> I'm happy to set up some end-to-end tests so we can verify this plugin works in the real world. Reviewing provider documentation for obvious RFC 6749 violations (like GitHub returning a FormUrlEncoded access token response) also can't hurt.
> 
> In case there's no such list, here's a start:
> 
> * Amazon.com
> * Battle.net
> * Discord
> * Facebook
> * GitHub
> * GitLab
> * Google
> * Microsoft
> * Okta
> * Reddit
> * Twitch

This sounds very useful, thanks!

File: test/extensions/filters/http/oauth2/oauth_test.cc (hunk 2 above)
Comment (williamsfu99) [reply test/extensions/filters/http/oauth2/oauth_test.cc:85]: +1 for checking `FormUrlEncoded` ContentType.

File: source/extensions/filters/http/oauth2/oauth_client.h (hunk 3 above)
Comment (terorie) [reply source/extensions/filters/http/oauth2/oauth_client.h:99]: @rgs1 Done

File: test/extensions/filters/http/oauth2/oauth_test.cc (hunk 2 above)
Comment (terorie) [reply test/extensions/filters/http/oauth2/oauth_test.cc]: Added a check for content-type too here. I don't think this sets any other headers

**Review by dio — APPROVED** [review]
Thanks!

**Review by snowp — APPROVED** [review]
Thanks!
