### PR TITLE
config: allow unknown fields flag (take 2)

### LINKED ISSUE #4053: Unknown fields in the configuration and new features policy
Starting with #3778, Envoy ignores unknown fields in the configuration. This is enabled by default and without the ability to turn it off, which already lead to invalid configuration sneaking into tests (see: #4051).

Presumably, the reasoning behind that change was for proxies to be able to accept configuration produced by newer control planes, effectively ignoring new features they don't know about yet.

Unfortunately, this leads to Envoy silently accepting invalid (e.g. simple typo means that the setting is ignored and feature is not configured) and/or not working (e.g. new feature that's required for the deployment is silently ignored by older proxies, leading to unexpected behavior) configurations.

Having said that, we cannot rely on proxies and control planes always being in sync, and the drift can happen the other way around as well, i.e. having proxies with new features, without the ability to configure or even disable (!) them by older control planes, so we should have a solution for both scenarios.

Ultimately, having new features disabled by default and requiring explicit opt-in, might be the safest and easiest option to solve that. Though, it pushes the responsibility for configuring sane defaults onto control planes.

As for the unknown fields in the configuration, I think that control planes could send a list of fields that are safe to be ignored by the proxies.

Thoughts?

cc @mattklein123 @alyssawilk @htuch @ggreenway @kyessenov @rshriram

### PR DESCRIPTION
**Pull request by kyessenov**
*Description*: Add a flag `allow-unknown-fields` that controls whether proto conversion ignores unknown fields. Proto structs are uniformly used for extension configuration. A smaller fix than https://github.com/envoyproxy/envoy/pull/4094.

The validation is applied in the following places:
- Any conversion (e.g. xDS payloads)
- Struct conversion (e.g. filter configs)
- bootstrap proto binary

*Risk Level*: Medium. Allow unknown fields is set to false by default, meaning unknown fields will be rejected by envoy. A missing check for xDS type checking was discovered.

*Testing*: Unit tests were updated to have it strict by default. Some wrong filter configs were discovered.

*Docs Changes*: None

*Release Notes*:
Add a flag `allow-unknown-fields` to control validation of protobuf configurations for unknown fields.

Fixes #4053 

/cc @PiotrSikora

### CODE REVIEW

File: source/common/protobuf/utility.cc [hunk 1]
```diff
@@ -48,7 +48,17 @@ ProtoValidationException::ProtoValidationException(const std::string& validation
...
+
 void MessageUtil::loadFromJson(const std::string& json, Protobuf::Message& message) {
+  Protobuf::util::JsonParseOptions options;
+  const auto status = Protobuf::util::JsonStringToMessage(json, &message, options);
+  if (!status.ok()) {
+    throw EnvoyException("Unable to parse JSON as proto (" + status.ToString() + "): " + json);
+  }
+}
+
+void MessageUtil::loadFromJsonLenient(const std::string& json, Protobuf::Message& message) {
```
Comment (htuch) [inline source/common/protobuf/utility.cc]: Nit: could factor out some of the body of these two to a shared util.

File: tools/protodoc/protodoc.bzl [hunk 2]
```diff
@@ -92,4 +91,5 @@ proto_doc_aspect = aspect(
             cfg = "host",
         ),
     },
+    implementation = _proto_doc_aspect_impl,
```
Comment (htuch) [inline tools/protodoc/protodoc.bzl]: I assume this is just some Buildifier artifact..

File: test/extensions/filters/network/thrift_proxy/integration_test.cc [hunk 3]
```diff
@@ -46,12 +46,7 @@ class ThriftConnManagerIntegrationTest
             route_config:
               name: "routes"
               routes:
-                - match:
-                    method_name: "execute"
-                  route:
-                    cluster: "cluster_0"
-                - match:
-                    method_name: "poke"
+                - match: {}
```
Comment (zuercher) [inline test/extensions/filters/network/thrift_proxy/integration_test.cc]: Oops. Could you revert the original and switch method_name to method? That should eliminate the unknown fields. (I'll circle back and add a second cluster to this test and use it for the one of the routes.)

File: tools/protodoc/protodoc.bzl (hunk 2 above)
Comment (kyessenov) [reply tools/protodoc/protodoc.bzl]: Yes, not sure why `check_format` is eager to refactor all bazel files on my machine.

File: test/extensions/filters/network/thrift_proxy/integration_test.cc (hunk 3 above)
Comment (zuercher) [reply test/extensions/filters/network/thrift_proxy/integration_test.cc]: Actually, that'll just make half the tests fail. You can leave this and I'll fix it myself.

Comment (kyessenov) [reply test/extensions/filters/network/thrift_proxy/integration_test.cc]: Yes, I am getting errors if I put it back...

File: source/common/config/utility.h [hunk 4]
```diff
@@ -52,7 +52,14 @@ class Utility {
     Protobuf::RepeatedPtrField<ResourceType> typed_resources;
     for (const auto& resource : response.resources()) {
       auto* typed_resource = typed_resources.Add();
-      resource.UnpackTo(typed_resource);
```
Comment (kyessenov) [inline source/common/config/utility.h]: note: we were ignoring mismatched type errors during unpacking.

File: source/common/protobuf/utility.cc [hunk 5]
```diff
@@ -68,6 +78,11 @@ void MessageUtil::loadFromFile(const std::string& path, Protobuf::Message& messa
   if (StringUtil::endsWith(path, ".pb")) {
     // Attempt to parse the binary format.
     if (message.ParseFromString(contents)) {
+      if (!MessageUtil::allow_unknown_fields &&
```
Comment (htuch) [inline source/common/protobuf/utility.cc]: Can you factor this out to a common utility?

Comment (kyessenov) [reply source/common/protobuf/utility.cc]: Done

File: source/common/protobuf/utility.cc (hunk 1 above)
Comment (mattklein123) [reply source/common/protobuf/utility.cc]: The other way of doing this is to have one function, and make the parameter for leniency be an enum instead of bool. That would be my vote as you would share code and have callsite clarity.

File: source/common/protobuf/utility.h [hunk 6]
```diff
@@ -158,7 +158,17 @@ class MessageUtil {
     return HashUtil::xxHash64(text);
   }
 
+  static bool allow_unknown_fields;
+
+  static void checkUnknownFields(const Protobuf::Message& message) {
+    if (!MessageUtil::allow_unknown_fields &&
+        !message.GetReflection()->GetUnknownFields(message).empty()) {
+      throw EnvoyException("Protobuf Any (type " + message.GetTypeName() + ") has unknown fields");
```
[the remark this answers is not in the document]
Comment (kyessenov) [reply source/common/protobuf/utility.h]: Done, thanks

File: source/common/protobuf/utility.cc (hunk 1 above)
Comment (kyessenov) [reply source/common/protobuf/utility.cc]: Thanks. I combined the logic into one function which is only called from two places (json convert and a test). The old `loadFromJson` used in many places in tests, which makes me hesitant to change its signature.

File: source/common/protobuf/utility.cc [hunk 7]
```diff
@@ -48,9 +48,16 @@ ProtoValidationException::ProtoValidationException(const std::string& validation
   ENVOY_LOG_MISC(debug, "Proto validation error; throwing {}", what());
 }
 
+bool MessageUtil::allow_unknown_fields = false;
```
Comment (mattklein123) [inline source/common/protobuf/utility.cc]: Just for clarity, can we make this an enum with 2 states? Then the function can take the enum value like I mentioned before (and CLI can convert to enum).

File: source/common/protobuf/utility.cc [hunk 8]
```diff
@@ -48,9 +48,16 @@ ProtoValidationException::ProtoValidationException(const std::string& validation
...
+
 void MessageUtil::loadFromJson(const std::string& json, Protobuf::Message& message) {
+  MessageUtil::loadFromJsonCustom(json, message, false);
+}
+
+void MessageUtil::loadFromJsonCustom(const std::string& json, Protobuf::Message& message,
```
Comment (mattklein123) [inline source/common/protobuf/utility.cc]: `loadFromJsonEx` ? (Not sure what custom means exactly)

Comment (kyessenov) [reply source/common/protobuf/utility.cc]: Done

File: source/common/protobuf/utility.cc (hunk 7 above)
Comment (kyessenov) [reply source/common/protobuf/utility.cc]: Done, let me know if I need to change the names of anything to conform with the style.

File: source/common/protobuf/utility.h [hunk 9]
```diff
@@ -158,7 +160,19 @@ class MessageUtil {
     return HashUtil::xxHash64(text);
   }
 
+  static ProtoUnknownFieldsMode proto_unknown_fields;
```
Comment (htuch) [inline source/common/protobuf/utility.h]: Nit: For readability, can you do an explicit initialization to Strict here.

Comment (kyessenov) [reply source/common/protobuf/utility.h]: Can you give me an example how to initialize a non-const static in the header?
I have explicit initialization in the .cc file.

Comment (htuch) [reply source/common/protobuf/utility.h]: Ah, missed that, LGTM, thanks.
