### PR TITLE
http, utility: Allow to optionally decode the parsed param value when parsing query string

### LINKED ISSUE #10926: Envoy /stats/prometheus?filter not working with prometheus due to url percent encoding.
When a prometheus job is configured to scrape envoy using `filter` query arg, it sends the requests with the params url percent encoded:

```
GET /stats/prometheus?filter=upstream%7Cdownstream HTTP/1.1
Host: X.Y.Z.Q:8524
User-Agent: Prometheus/2.15.2
Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
Accept-Encoding: gzip
```

`upstream%7Cdownstream` doesn't get urldecoded properly and no metrics are returned.

`upstream|downstream` works fine, but prometheus can't be configured to not url percent encode the params from its scrape requests.

I'm willing to work on this if it's considered a bug and not expected behaviour. Assuming there already are some bits that do urldecoding in envoy, i think it's approachable even for someone that doesn't know c++ well (me).

Later edit:

use case: On large enough envoy deployments, we can't fit all the metrics we get from all envoys on just one prom box without eventually trashing it. So we're forced to rely on stats filtering so that each prom sees just a subset of the metrics. The lack of url decoding for `|`-based regex filters forces us to do quite a few unnecessary scrape jobs and various workarounds.

### PR DESCRIPTION
**Pull request by dio**
Commit Message: This introduces `parseAndDecodeQueryString` method to parse the URL into percent-decoded query params.

Additional comments: Especially for fixing the Prometheus handler decoding problem as mentioned in #10926.

Risk Level: Low
Testing: Unit
Docs Changes: N/A
Release Notes: N/A
Fixes #10926

Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

### CODE REVIEW

File: source/server/admin/stats_handler.cc [hunk 1]
```diff
@@ -140,7 +140,8 @@ Http::Code StatsHandler::handlerStats(absl::string_view url,
 Http::Code StatsHandler::handlerPrometheusStats(absl::string_view path_and_query,
                                                 Http::ResponseHeaderMap&,
                                                 Buffer::Instance& response, AdminStream&) {
-  const Http::Utility::QueryParams params = Http::Utility::parseQueryString(path_and_query);
+  const Http::Utility::QueryParams params =
+      Http::Utility::parseQueryString(path_and_query, /*do_percent_decoding=*/true);
```
Comment (zuercher) [inline source/server/admin/stats_handler.cc:144]: I think we should avoid the need for the comment to make clear what the true parameter means. Perhaps instead of a boolean flag we should use a separate method?

Comment (dio) [reply source/server/admin/stats_handler.cc]: Updated.

File: source/common/http/utility.cc [hunk 2]
```diff
@@ -275,6 +275,17 @@ Utility::QueryParams Utility::parseQueryString(absl::string_view url) {
...
 
+Utility::QueryParams Utility::parseAndDecodeQueryString(absl::string_view url) {
+  size_t start = url.find('?');
+  if (start == std::string::npos) {
+    QueryParams params;
+    return params;
+  }
+
+  start++;
+  return parseParameters(PercentEncoding::decode(StringUtil::subspan(url, start, url.size())), 0);
```
Comment (zuercher) [inline source/common/http/utility.cc:286]: Oh, I apologize. I read this code incorrectly the first time. I thought we could just implement this method as:

`return PercentEncoding::decode(parseQueryString(url))`

I see now that's percent-decoding the params and then parsing them.

Doesn't this have a bug? If I pass query params with a percent-encoded `&` (e.g. `x=a%26b`) then decoding before splitting parameters will split in the wrong location, yes?

Comment (dio) [reply source/common/http/utility.cc:286]: You're right! Will fix this while waiting for the chance to use GURL (https://github.com/envoyproxy/envoy/pull/11670) to arrive.

File: source/common/http/utility.cc [hunk 3]
```diff
@@ -291,8 +292,9 @@ Utility::QueryParams Utility::parseParameters(absl::string_view data, size_t sta
 
     const size_t equal = param.find('=');
     if (equal != std::string::npos) {
+      const auto param_value = StringUtil::subspan(data, start + equal + 1, end);
       params.emplace(StringUtil::subspan(data, start, start + equal),
-                     StringUtil::subspan(data, start + equal + 1, end));
+                     decode_param_value ? PercentEncoding::decode(param_value) : param_value);
```
Comment (zuercher) [inline source/common/http/utility.cc:297]: Should decode param names as well?

File: source/common/http/utility.cc [hunk 4]
```diff
@@ -264,22 +264,23 @@ std::string Utility::createSslRedirectPath(const RequestHeaderMap& headers) {
   return fmt::format("https://{}{}", headers.getHostValue(), headers.getPathValue());
 }
 
-Utility::QueryParams Utility::parseQueryString(absl::string_view url) {
+Utility::QueryParams Utility::parseQueryString(absl::string_view url, bool decode_param_value) {
```
Comment (zuercher) [inline source/common/http/utility.cc:267]: Sorry, but I still think the separate methods was easier to read.

File: source/common/router/config_impl.cc [hunk 5]
```diff
@@ -490,7 +490,7 @@ bool RouteEntryImplBase::matchRoute(const Http::RequestHeaderMap& headers,
   matches &= Http::HeaderUtility::matchHeaders(headers, config_headers_);
   if (!config_query_parameters_.empty()) {
     Http::Utility::QueryParams query_parameters =
-        Http::Utility::parseQueryString(headers.getPathValue());
+        Http::Utility::parseAndDecodeQueryString(headers.getPathValue());
```
Comment (zuercher) [inline source/common/router/config_impl.cc:493]: I think we can make this the default, but I think we probably need a runtime flag to disable this for people who are matching values with percent encoding enabled.

Same applies to the other filters. I think it's ok to change the behavior in the admin handlers.

Comment (dio) [reply source/common/router/config_impl.cc:493]: @zuercher I'll revert the change to places outside admin handler for now and do runtime flagging in different PR. WDYT?
