### PR TITLE
[balsa] Fix EOF handling.

### LINKED ISSUE #24557: [quiche] `headers_done_` should be set to false in BalsaParser::MessageDone()
Kudos to Dianna for catching this at https://github.com/envoyproxy/envoy/pull/24157#discussion_r1033909657.

### PR DESCRIPTION
**Pull request by bencebeky**
Signal an error when BalsaParser::execute() is called with zero length except for the already handled special cases. Reset `headers_done_` in BalsaParser::MessageDone(). Add a number of tests for EOF handling and other special cases.

Balsa work tracking issue: #21245

Fixes #24557.

Signed-off-by: Bence Béky <bnc@google.com>

Risk Level: low, changed code protected by existing default-false runtime flag.
Testing: //test/common/http/http1:codec_impl_test
Docs Changes: n/a
Release Notes: n/a
Platform Specific Features: n/a
Runtime guard: envoy.reloadable_features.http1_use_balsa_parser

### CODE REVIEW

File: test/common/http/http1/codec_impl_test.cc [hunk 1]
```diff
@@ -3904,5 +3880,301 @@ TEST_P(Http1ClientConnectionImplTest, InvalidResponseFirstCharacter) {
...
+TEST_P(Http1ServerConnectionImplTest, FirstReadEOF) {
+  initialize();
+  InSequence s;
+
+  Buffer::OwnedImpl empty;
+  auto status = codec_->dispatch(empty);
+  ASSERT_TRUE(status.ok());
+
+  StrictMock<MockRequestDecoder> decoder;
+  Http::ResponseEncoder* response_encoder = nullptr;
```
Comment (diannahu) [inline test/common/http/http1/codec_impl_test.cc:3893]: potential nit: The response_encoder here looks unused?

File: test/common/http/http1/codec_impl_test.cc [hunk 2]
```diff
@@ -3904,5 +3880,301 @@ TEST_P(Http1ClientConnectionImplTest, InvalidResponseFirstCharacter) {
...
+// A first read of zero bytes when parsing a request is ignored.
+TEST_P(Http1ServerConnectionImplTest, FirstReadEOF) {
+  initialize();
+  InSequence s;
+
+  Buffer::OwnedImpl empty;
+  auto status = codec_->dispatch(empty);
+  ASSERT_TRUE(status.ok());
+
+  StrictMock<MockRequestDecoder> decoder;
```
Comment (diannahu) [inline test/common/http/http1/codec_impl_test.cc:3892]: optional: Alright to create the StrictMock decoder above the first dispatch of the empty data? That would drive home the verification that the first empty read is ignored.

File: test/common/http/http1/codec_impl_test.cc [hunk 3]
```diff
@@ -3904,5 +3880,301 @@ TEST_P(Http1ClientConnectionImplTest, InvalidResponseFirstCharacter) {
...
+        response_encoder = &encoder;
+        return decoder;
+      }));
+
+  if (parser_impl_ == Http1ParserImpl::BalsaParser) {
+    EXPECT_CALL(decoder,
+                sendLocalReply(Http::Code::BadRequest, "Bad Request", _, _, "http1.codec_error"));
+  } else {
+    EXPECT_CALL(decoder, decodeHeaders_(_, true));
+  }
```
Comment (diannahu) [inline test/common/http/http1/codec_impl_test.cc:4109]: here and below: Whoa, nice! All of these differences make great sense (for Balsa).

**Review by diannahu — APPROVED** [review]
Nice fixes and ++test coverage!

**Review by diannahu — APPROVED** [review]
Looks great!

(I wanted to reply with a "good catch" comment on the nice mock thread but fear that the reply will unresolve the thread. So writing it here - good catch and thanks for pointer :D)

**Review by KBaichoo — APPROVED** [review]
Looks great, thanks for fixing this and adding all those test cases!

**Comment by bencebeky** [comment]
Thank you all for the review.
