### PR TITLE
ci: Add workaround for openssl cert gen bug

### LINKED ISSUE #15555: Occasional openssl flake in CI
### description

there is sometimes failures generating ssl certificates, eg:

```
2021-03-17T19:02:51.9734549Z Can't load /home/vsts/.rnd into RNG
2021-03-17T19:02:51.9735432Z 140516289237440:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/vsts/.rnd
```

not sure what the cause is but perhaps an openssl bug 

if it is the same as described here:

https://github.com/openssl/openssl/issues/7754#issuecomment-598808341

then doing:

```
touch ~/.rnd
```

before generating the certifcates seems to fix

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

Commit Message: ci: Add workaround for openssl cert gen bug
Additional Description:
ci is throwing openssl issues about `~/.rnd` not being accessible

afaict here https://github.com/openssl/openssl/issues/7754#issuecomment-598808341 it is an openssl issue that can be worked around by touching the `.rnd` file before generating certs

Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue] Fix #15555
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

### CODE REVIEW

File: examples/double-proxy/verify.sh [hunk 1]
```diff
@@ -9,6 +9,9 @@ export DELAY=5
 
 mkdir -p certs
 
+# openssl bug workaround
```
Comment (phlax) [inline examples/double-proxy/verify.sh:12]: add todo/link

**Comment by phlax** [comment]
@alyssawilk i can confirm that this resolves the openssl ci issue - not sure if it was causing a fail - but good to remove the noise anyway if not

**Comment by alyssawilk** [comment]
Oh awesome, thanks again for tracking this down!

**Review by lizan — APPROVED** [review]
